### ISSUE TITLE
Telemetry for improperly zipped apps

### ISSUE THREAD

**Issue by satvu** [Azure/azure-functions-host#10021]
Follow up of [this issue](https://github.com/Azure/azure-functions-dotnet-worker/issues/2335). We've been seeing an increase in "No Job Functions Found" errors as a result of improperly zipped apps that resulted in an unexpected folder structure. 

While these apps have the correct files needed to start up (like host.json), the incorrect folder and file structure can lead to vague errors that prevent the apps from behaving as expected. Some considerations for tracking this:

- Track guaranteed failure cases (double-zipping an app, similar to issue linked above)
  - Runtime languages have different payloads, need to avoid throwing errors for valid apps
- Logging (minimal) file structure to help with servicing and debugging this error
- Design error/failure behavior for improperly zipped apps, troubleshooting guides

**Comment by shashank3kapoor** [comment]
Could anyone please provide an update for this issue?
Has this issue been resolved?
or is a fix underway?

**Comment by satvu** [comment]
@shashank3kapoor Are you blocked by a deployment issue? I see that you commented on https://github.com/Azure/azure-functions-dotnet-worker/issues/2335 - if the solution there did not help you, could you open a support ticket instead? 

This tracking item is only for telemetry - resolving the root cause of an improperly zipped app will still depend on user action and investigation.

**Comment by shashank3kapoor** [comment]
@satvu 
Thanks.

**Below changes fixed the problem:**

Updating the file structure Startup.cs -> Program.cs
And using `Update` wizard (VS 2022) to upgrade to 8.0

**YAML:**(Linux)
- task: AzureAppServiceSettings@1
    generalSettings: |
        [
          {
            "linuxFxVersion": "DOTNETCORE|8.0",
            "netFrameworkVersion": "v8.0",
            "alwaysOn": true
          }
        ]
        
        
- task: AzureFunctionApp@1
    inputs:
      runtimeStack: "DOTNET-ISOLATED|8.0"
