### ISSUE TITLE
Job host stopped for unknown reason

### ISSUE THREAD

**Issue by tgancheva** [Azure/azure-functions-host#10022]
Investigating an issue with job host stopping for a prolonged period of time for a total of two times in the period between Apr 16th 09:53 AM and Apr 17th 05:29 AM (UTC time). Reason for halt is unknown. Function app stopped and restarted without any known user interaction and has been running without issues prior to or after the specified timespan.

#### Check for a solution in the Azure portal

Checked section `Diagnose and solve problems`, as described, it shows the following information:

![image](https://github.com/Azure/azure-functions-host/assets/50363463/90a5ab09-8604-41da-b0e4-3a7df88cbe09)
![image](https://github.com/Azure/azure-functions-host/assets/50363463/d3c3f2b2-d311-45f8-972f-2714d4a9962c)
![image](https://github.com/Azure/azure-functions-host/assets/50363463/2a6918ad-d017-4ef9-a864-5ba749bf5e15)

In addition, App Insights clearly shows the two periods of function inactivity:

![image](https://github.com/Azure/azure-functions-host/assets/50363463/7e869d27-f7d7-46c3-b1ec-788d6f2f80cf)

#### Investigative information

- Timestamp: 4/17/2024, 12:25:58 AM
- Function App version: 4.33.1.22394, .NET 6, Windows, Isolated worker
- Function App name: We'd rather not share publicly
- Function name(s) (as appropriate): MailItemsQueueTrigger
- Invocation ID: ddd68e3a-aee0-4452-9f7b-e48865c4f3f2
- Region: Australia Southeast

#### Repro steps

Timeline of events, as follows (all times UTC):

- 4/16/2024 9:32 AM - We initiate Zip Deploy from Azure DevOps release pipeline. Job host is stopped, deployment completes successfully, functions are started back and execute normally. Apart from the function mentioned above, we have a bunch of other functions in the same app, including an eternal Durable Functions orchestration, which executes successfully after deployment.
- 4/16/2024 09:53 AM - All listeners and eventually the job host are stopped for an unknown reason.
- 4/16/2024 10:07 AM - A queue message for the function and invocation above is written to the queue, along with hundreds of others, but the function does not start.
- 4/17/2024 12:25 AM - Job host and all functions start by themselves. Invocation id specified above is from this time.
- 4/17/2024 12:46 AM - All listeners and eventually the job host are stopped for an unknown reason again.
- 4/17/2024 05:28 AM - Job host and all functions start by themselves. Have been running since then.

#### Expected behavior

- We would expect no interruptions to functions processing and execution. 
- Deployment, if at all the cause of these issues, is shown as successful within Azure DevOps. 
- Zip Deploy is the recommended option to perform updates to functions and has been documented to not require any manual steps to sync triggers.

#### Actual behavior

- Job host stopped for an unknown reason.

#### Known workarounds

- No workarounds, as reason for halt is unknown. It's the reason we are after in the first place, so we can come up with solutions.

**Comment by liliankasem** [comment]
@tgancheva for issues like this a deeper investigation is needed for your specific app; please open a support ticket via the portal. Thanks!
