### ISSUE TITLE
Create .NET 8 in-proc Linux consumption images

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#10040]
Issue tracking the creation of the .NET 8 Linux consumption images.

**Comment by aishwaryabh** [comment]
PR: https://msazure.visualstudio.com/DefaultCollection/One/_git/AAPT-Antares-Functions-Docker/pullrequest/10020273?path=/test/index.ts

**Comment by aishwaryabh** [comment]
Merged in PR
