### ISSUE TITLE
Validate deployment flow for .NET 8 in-proc apps

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#10049]
### Deployment of new app:

- [x] Visual Studio
  - [x] Linux Consumption
  - [x] Linux Dedicated
  - [x] Windows Consumption
- [x] ADO
  - [x] Linux Cns
  - [x] Linux Ded 
  - [x] Windows Cns
- [x] VS Code
  - [x] Linux Cns
  - [x] Linux Ded
  - [x] Windows Cns

### Upgrading existing .NET6 inproc app to .NET8 inproc:

- [x] Visual Studio
  - [x] Linux Consumption (waiting for a rollout)
  - [x] Linux Dedicated (waiting for a rollout)
  - [x] Windows Consumption
- [x] ADO
  - [x] Linux Cns
  - [x] Linux Ded 
  - [x] Windows Cns
- [x] VS Code
  - [x] Linux Cns
  - [x] Linux Ded
  - [x] Windows Cns

NOTE: Only VS in Windows applied app settings to upgrade runtime version - the other methods will deploy the app successfully, but additional user action will be needed to update the necessary app settings.

**Comment by fabiocav** [comment]
Currently blocked by deployment.

**Comment by fabiocav** [comment]
@satvu moving this to 172 as it should be unblocked.

**Comment by fabiocav** [comment]
Progress is being made in SKUs where .NET 8 is available.

Moving this to 173 to continue validation.

**Comment by satvu** [comment]
Deployment of new app:

- [ ] Visual Studio
  - [ ] Linux Consumption (waiting for a rollout)
  - [ ] Linux Dedicated (waiting for a rollout)
  - [x] Windows Consumption
- [x] ADO
  - [x] Linux Cns
  - [x] Linux Ded 
  - [x] Windows Cns
- [x] VS Code
  - [x] Linux Cns
  - [x] Linux Ded
  - [x] Windows Cns

**Comment by satvu** [comment]
Upgrade of net6 -> net 8 inproc scenarios have been tested, but facing some issues that are under investigation/discussion.

**Comment by satvu** [comment]
Upgrading existing .NET6 inproc app to .NET8 inproc:

- [ ] Visual Studio
  - [ ] Linux Consumption (waiting for a rollout)
  - [ ] Linux Dedicated (waiting for a rollout)
  - [x] Windows Consumption
- [x] ADO
  - [x] Linux Cns
  - [x] Linux Ded 
  - [x] Windows Cns
- [x] VS Code
  - [x] Linux Cns
  - [x] Linux Ded
  - [x] Windows Cns

NOTE: Only VS will apply app settings to upgrade runtime version - the other methods will deploy the app successfully, but additional user action will be needed to update the necessary app settings.

**Comment by satvu** [comment]
Closing as complete
