### ISSUE TITLE
Support latest .NET 8 patches

### ISSUE THREAD

**Issue by TomGroeneboer** [Azure/azure-functions-host#10065]
#### Is your question related to a specific version? If so, please specify:

The latest version of the Azure Functions host, `4.33.1.22394` on our instance of Azure Functions.

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question

Hello!
We're building applications on the latest LTS version of .NET, 8.0.4. To enforce this, we set the `RuntimeFrameworkVersion` in our csproj to the latest, in this case `8.0.4`.

However, this fails when trying to deploy to an Azure function. The Azure function seems to support only up to .NET 8.0.1. How long do we usually need to wait for it to come available on the Azure Functions host?

Thanks!

**Comment by liliankasem** [comment]
Hi @TomGroeneboer - thank you for opening this issue. Please see our policy regarding security related issues.

https://github.com/Azure/azure-functions-host/security/policy

**Comment by TomGroeneboer** [comment]
@liliankasem I'm not sure whether I agree this falls under the security reports policy, but I've filed one anyway. Tracking number is VULN-124944.

Even if this wouldn't be a security fix, but just a stability update of .NET, are there any policies on how long it would take to deploy these versions to Azure Functions hosts? I can't find anything on that in the docs.

**Comment by fabiocav** [comment]
@TomGroeneboer we don't currently have public SLAs or component update policies, but we're actively working with the broader team to define them.

Although I don't have an ETA on the 8.0.4 deployment, this is in progress right now. This is indeed delayed on Windows, and we're taking steps to improve this process.

It's worth mentioning that different plan types/options have different deployment cadences, and this is particularly the case for our Linux based offerings. Today, those images see more frequent updates, and our current production environments are running on 8.0.4 there. Wanted to share this in case moving to Linux is a viable option for you or others reading this.

Thank you!

+ @mattchenderson , @bradygaster, @btardif

**Comment by TomGroeneboer** [comment]
@fabiocav Thanks for that explanation. That helps.
I tried the security report route and they redirected me to support again haha.

I've also tried converting the application to a Linux based environment as you mentioned, but then all of the sudden the functions aren't recognized anymore. I'll do some further digging for that later on, guess this issue can be closed!
