### ISSUE TITLE
Intermittent "No job functions found."

### ISSUE THREAD

**Issue by sadiqkhoja** [Azure/azure-functions-host#10076]
#### Check for a solution in the Azure portal
I am getting following error on Azure intermittently, fix for me is to "Advanced Application restart" under diagnostic tools.

```
No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.)
```

I have to do perform "Advance Application restart" every couple of days and then something happens (maybe system maintenance / change of instance) and I see following messages in logs:

```
Initializing Warmup Extension.
Initializing Host. OperationId: '27dcf955-469c-4e1d-a617-3b116bca02b4'.
Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=27dcf955-469c-4e1d-a617-3b116bca02b4
Starting JobHost
Starting Host
Loading functions metadata
Host lock lease acquired by instance ID '4674be82b396abaf83d02ae5cb9797e3'.
Application started. Press Ctrl+C to shut down.
Hosting environment: Production
Content root path: /home/site/wwwroot/
Reading functions metadata (Custom)
1 functions found (Custom)
1 functions loaded
Generating 1 job function(s)
Worker process started and initialized.
No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
Initializing function HTTP routes No HTTP routes mapped
Host initialized (14286ms)
Host started (14336ms)
Job host started
```

When application runs correctly I see `2 functions found (Custom)` even though I have only 1 function defined. Even when I run the app locally it says `2 functions found (Custom)`.

#### Investigative information

Please provide the following:

- Timestamp: 2024-04-26T15:11:47.7466553Z
- Function App version: 4.33.2.2
- cloud_RoleInstance: 4674be82b396abaf83d02ae5cb9797e3302ed577226c6d832720658f6837fffe
- HostInstanceId: fd43fae4-d328-49b6-9b30-d7859d15547d
- Region: Canada Central

**Comment by liliankasem** [comment]
Hi @sadiqkhoja  - for issues like this, please open a support ticket via the azure portal so that our team can investigate your specific application. Thanks!
