### ISSUE TITLE
Default hostname changes (azurewebsites.net)

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#10090]
The App Service platform is moving to a strategy where the default hostname for a site will vary regionally. This means that code can't simply assume "azurewebsites.net".

New default hostname format: `siteName-<dnlHash>.<region>.azurewebsites.net`​
SCM site will have this format:​ `siteName-<dnlHash>.scm.<region>.azurewebsites.net`

There are several known places in the host currently where we're using this string literal. We'll need to review all these and make changes as required. These include:

- In defaulting the hostname used by the Host ID provider for Linux Dedicated (code [here](https://github.com/Azure/azure-functions-host/blob/6c23426d7de334e628212eba095002f7d8a78ffe/src/WebJobs.Script/HostNameProvider.cs#L45))
- In constructing the Host ID for Linux Consumption (code [here](https://github.com/Azure/azure-functions-host/blob/6c23426d7de334e628212eba095002f7d8a78ffe/src/WebJobs.Script/Host/ScriptHostIdProvider.cs#L86))
  - Note: there's already a related issue for this https://github.com/Azure/azure-functions-host/issues/8788.
  - We might just be able to live with the existing code since it still technically works, even with the new hostname format.
  - Any changes to the Host ID format for existing apps would of course be breaking.
-  In the JWT issuer/audience values (code [here](https://github.com/Azure/azure-functions-host/blob/6c23426d7de334e628212eba095002f7d8a78ffe/src/WebJobs.Script/ScriptConstants.cs#L146)). **These aren't a problem** and would be difficult to change anyways, since the App Service platform and Kudu are using these same values and rely on this contract.
- FunctionsSyncManager uses the hostname to make Front End settriggers calls (code [here](https://github.com/Azure/azure-functions-host/blob/6c23426d7de334e628212eba095002f7d8a78ffe/src/WebJobs.Script.WebHost/Management/FunctionsSyncManager.cs#L731C39-L731C47)). We need to make sure that the hostname value returned by the [HostNameProvider](https://github.com/Azure/azure-functions-host/blob/6c23426d7de334e628212eba095002f7d8a78ffe/src/WebJobs.Script/HostNameProvider.cs#L31) is correct in all cases for these calls to work. For Linux Dedicated, I see there's already a problem - for that platform WEBSITE_HOSTNAME isn't set (at least it wasn't when the code was written), so it hardcodes "azurewebsites.net". **This will need to change**.

**Comment by fitchmultz** [comment]
Looking forward to this change since this issue is currently inhibiting my ability to deploy my Function App to a Sovereign tenant via VS Code. Any workarounds besides using an alternate deploy method?

**Comment by fabiocav** [comment]
Work for this is in progress. Finalizing validation.

**Comment by soninaren** [comment]
Please find notes from my investigation below.

> * In defaulting the hostname used by the Host ID provider for Linux Dedicated (code [here](https://github.com/Azure/azure-functions-host/blob/6c23426d7de334e628212eba095002f7d8a78ffe/src/WebJobs.Script/HostNameProvider.cs#L45))

HostName provider has hardcoded value for linux dedicated however the code path that hardcodes the value does not activate. This is because WEBSITE_HOSTNAME is available on Linux Dedicated. We simply need to remove the coding as it is dead code anyway. Remove the hardcoded string used to create hostname for Linux dedicated [Remove the hardcoded string used to create hostname for Linux dedicated](https://github.com/Azure/azure-functions-host/issues/10386).

> * In constructing the Host ID for Linux Consumption (code [here](https://github.com/Azure/azure-functions-host/blob/6c23426d7de334e628212eba095002f7d8a78ffe/src/WebJobs.Script/Host/ScriptHostIdProvider.cs#L86))
>   
>   * Note: there's already a related issue for this [[Linux Consumption] HostId generation logic should be cloud specific #8788](https://github.com/Azure/azure-functions-host/issues/8788).
>   * We might just be able to live with the existing code since it still technically works, even with the new hostname format.
>   * Any changes to the Host ID format for existing apps would of course be breaking.

The host id generated here for region specific host name works fine. Any change here would be breaking for existing customers in sovereign and air gapped clouds. We can try to make the change here so that it only applies to public cloud.

> * FunctionsSyncManager uses the hostname to make Front End settriggers calls (code [here](https://github.com/Azure/azure-functions-host/blob/6c23426d7de334e628212eba095002f7d8a78ffe/src/WebJobs.Script.WebHost/Management/FunctionsSyncManager.cs#L731C39-L731C47)). We need to make sure that the hostname value returned by the [HostNameProvider](https://github.com/Azure/azure-functions-host/blob/6c23426d7de334e628212eba095002f7d8a78ffe/src/WebJobs.Script/HostNameProvider.cs#L31) is correct in all cases for these calls to work. For Linux Dedicated, I see there's already a problem - for that platform WEBSITE_HOSTNAME isn't set (at least it wasn't when the code was written), so it hardcodes "azurewebsites.net". **This will need to change**.

Have validated the hostname for all SKU's. As mentioned above `WEBSITE_HOSTNAME` is available in Linux dedicated the path that hardcodes the value is not activated. 

Additionally have filed the item below [Evalute if WEBSITE_DEFAULT_HOSTNAME should be used for setting hostname](https://github.com/Azure/azure-functions-host/issues/10385)
