### ISSUE TITLE
Passing input data from Code + Test to durable activity does not work any more

### ISSUE THREAD

**Issue by ziegler-daniel** [Azure/azure-functions-host#10147]
It is not possible any more to pass input data to a durable activity from Code + Test in the Azure portal. The input data is now nested inside of an http request object. In the past (March this year), passing input to the durable orchestration from Code + Test worked fine.

#### Investigative information
- Timestamp: 2024-05-10T12:55:53Z
- Function App version: azurefunctions: 4.34.1.1
- Invocation ID: 0114fc85-990f-47a0-ba65-c6100e75cd9b
- Region: West Europe

#### Repro steps
1. Open a durable activity from a function app in the Azure portal
2. Navigate to "Code + Test"
3. Provide e.g. `{"requestId": "dbdd220d-8a2e-41ba-862a-3d21a0e8bd92"}` as input data
4. Click "Run"

![Screenshot from Code + Test](https://github.com/Azure/azure-functions-host/assets/44165453/0c64b2f9-f84a-4084-be1b-59ac83a88f9d)

#### Expected behavior
The durable activity should be started with `{"requestId": "dbdd220d-8a2e-41ba-862a-3d21a0e8bd92"}` as input in `context.bindingData.workflowData`

#### Actual behavior
The durable activity received `{"body":"{\n \"test\": 42\n}","headers":[],"method":"post","queryStringParams":[]}` as input in `context.bindingData.workflowData`

![Request details in Application Insights](https://github.com/Azure/azure-functions-host/assets/44165453/127691a3-8215-4a46-9d8c-bed83635b2f8)

#### Known workarounds
None

#### Related information 
- Calling the durable activity programmatically from a durable orchestration works fine
- In the past (March this year), passing input to the durable orchestration from Code + Test worked fine

Provide any related information 
- Programming language used: JavaScript

Thanks in advance!

**Comment by bhagyshricompany** [comment]
Hi @ziegler-daniel  Thanks for informing please  share the all repro steps.

**Comment by bhagyshricompany** [comment]
no response getting hence closing.Thanks
