### ISSUE TITLE
HTTP 500: Error in logs says Worker was unable to load function: 'Cannot find module 'uuid'Worker was unable to load function

### ISSUE THREAD

**Issue by charlesanim** [Azure/azure-functions-host#10156]
When i trigger the function i immediately get a http 500 error.
Then I see this below error thats says cannot find module `uuid`. The function was working fine until May 3, 2024. My hunch is maybe a regression occured at that time?
I'm not sure if I need to update something as my package.json doesn't have a dependency of uuid directly.

"@azure/functions": "^3.5.0",
"@azure/storage-blob": "^12.10.0"

In host.json, i have

    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[4.0.0, 5.0.0)"
    }
    
    
Result: Failure Exception: Worker was unable to load function reports: 'Cannot find module 'uuid' Require stack: - /home/site/wwwroot/node_modules/@azure/core-http/dist/index.js - /home/site/wwwroot/node_modules/@azure/storage-blob/dist/index.js - /home/site/wwwroot/dist/shared/containerClient.js - /home/site/wwwroot/dist/reports/index.js - /azure-functions-host/workers/node/dist/src/worker-bundle.js - /azure-functions-host/workers/node/dist/src/nodejsWorker.js' Stack: Error: Worker was unable to load function reports: 'Cannot find module 'uuid' Require stack: - /home/site/wwwroot/node_modules/@azure/core-http/dist/index.js - /home/site/wwwroot/node_modules/@azure/storage-blob/dist/index.js - /home/site/wwwroot/dist/shared/containerClient.js - /home/site/wwwroot/dist/reports/index.js - /azure-functions-host/workers/node/dist/src/worker-bundle.js - /azure-functions-host/workers/node/dist/src/nodejsWorker.js' at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15) at Module._load (node:internal/modules/cjs/loader:981:27) at Module.require (node:internal/modules/cjs/loader:1231:19) at Object.apply (/azure-functions-host/workers/node/dist/src/worker-bundle.js:2:51713) at require (node:internal/modules/helpers:177:18) at Object. (/home/site/wwwroot/node_modules/@azure/core-http/dist/index.js:5:12) at Module._compile (node:internal/modules/cjs/loader:1364:14) at Module._extensions..js (node:internal/modules/cjs/loader:1422:10) at Module.load (node:internal/modules/cjs/loader:1203:32) at Module._load (node:internal/modules/cjs/loader:1019:12)

**Comment by bhagyshricompany** [comment]
Thanks for informing please share the all repro steps.

**Comment by bhagyshricompany** [comment]
no  update getting hence closing
