### ISSUE TITLE
Host unable to write diagnostics events to table storage if app is configured with managed identity

### ISSUE THREAD

**Issue by nzthiago** [Azure/azure-functions-host#10163]
I had a function app that triggers from Service Bus. The app has service identity configured and the app and has the following role assignments:
Storage Blob Data Owner
Storage Table Data Contributor
Azure Service Bus Data Owner
Everything seems to work fine and the app successfully processes messages from Service Bus using identity but looking at the FunctionsLogs for the app I see a lot of entries with "Unable to get table reference. Aborting write operation" and "Azure Storage connection string is empty or invalid. Unable to write diagnostic events." exceptions in logs. 

This could be is due to the WebHost expecting only a connection string to write to table storage and not checking for identity-based connections. Worried this could happen for any app that has storage diagnostics settings on. 
[https://github.com/Azure/azure-functions-host/src/WebJobs.Script.WebHost/Diagnostics/DiagnosticEventTableStorageRepository.cs#L64](https://github.com/Azure/azure-functions-host/blob/29e348107d2fab40a36f501819bafb5f238a2f56/src/WebJobs.Script.WebHost/Diagnostics/DiagnosticEventTableStorageRepository.cs#L64)

**Comment by pragnagopa** [comment]
@fabiocav - please triage - tracking this for FlexConsumption GA

**Comment by pragnagopa** [comment]
Causes noise in the logs; Affects all SKUs. P1

**Comment by mattchenderson** [comment]
This is related to https://github.com/Azure/azure-functions-host/issues/9569 - the resolution here could be to properly converge on the shared services and fully remove the conditional check and log statement here.

**Comment by nzthiago** [comment]
Was this closed because it's a dupe of #9569 ?

**Comment by Red1971** [comment]
> I had a function app that triggers from Service Bus. The app has service identity configured and the app and has the following role assignments: Storage Blob Data Owner Storage Table Data Contributor Azure Service Bus Data Owner Everything seems to work fine and the app successfully processes messages from Service Bus using identity but looking at the FunctionsLogs for the app I see a lot of entries with "Unable to get table reference. Aborting write operation" and "Azure Storage connection string is empty or invalid. Unable to write diagnostic events." exceptions in logs.
> 
> This could be is due to the WebHost expecting only a connection string to write to table storage and not checking for identity-based connections. Worried this could happen for any app that has storage diagnostics settings on. [https://github.com/Azure/azure-functions-host/src/WebJobs.Script.WebHost/Diagnostics/DiagnosticEventTableStorageRepository.cs#L64](https://github.com/Azure/azure-functions-host/blob/29e348107d2fab40a36f501819bafb5f238a2f56/src/WebJobs.Script.WebHost/Diagnostics/DiagnosticEventTableStorageRepository.cs#L64)


@nzthiago - good day. I have an Azure Function app with the same issue. Did you manage to resolve this and if so how?

![Image](https://github.com/user-attachments/assets/75230436-33c7-4408-93d4-e6e48943971b)

**Comment by nzthiago** [comment]
This was a duplicate of #9569, which should have addressed this problem. @mattchenderson FYI.
