### ISSUE TITLE
Azure Function deploy WEBSITE_RUN_FROM_PACKAGE , requirements.txt modules not getting installed.

### ISSUE THREAD

**Issue by sa1sen** [Azure/azure-functions-host#10191]
#### Investigative information

- Function App version: 4, Linux, Python
- Region: East US 2

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a simple HTTP trigger file and 'import requests'. Add 'requests' in requirement.txt file
2. Package Python Function App project as .zip file (with correct folder structure, which includes requirements.txt at root)
3. Upload .zip file to Azure Storage
4. Generate SAS URL - verify if zip file is downloadable
5. In Azure Functions, add Environment variable 'WEBSITE_RUN_FROM_PACKAGE' and value = SAS URL
6. Test the function (fails) - Module not found error

#### Expected behavior

The module dependencies in requirement.txt should be automatically installed whenever a new zip URL is entered and saved (and function app is restarted). 

#### Actual behavior

No modules in requirement.txt are being installed. This is verified when I am trying to 'import requests' at the start of my Python function

#### Known workarounds

Going into the Azure function and installing it manually through SSH. However, for my use case, I am trying to automate this process with ARM templates so it will not work.

#### Related information 

I tested using below Az command and it works when deploying a local file and enabling remote build. However, I need to use SAS URL and builds to happen automatically including installation of requirements.txt modules.

`az functionapp deployment source config-zip --name FUNC_APP_NAME --resource-group RG_NAME --src localZipFile --build-remote true
`

I also tested enabling SCM_DO_BUILD_DURING_DEPLOYMENT = true as per documentation. But I believe this is only required if you are deploying a local package rather than a zip URL.

**Comment by bhagyshricompany** [comment]
Thanks for info pls share the code snippet or screen shot.Thanks
