### ISSUE TITLE
Duplicate Log Messages in Azure Dashboard Despite Single Message Sent to Application Insights

### ISSUE THREAD

**Issue by swarnimsuman** [Azure/azure-functions-host#10202]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app, select `Diagnose and solve problems` from the left, and view relevant dashboards before opening your issue.

We are experiencing a similar issue where duplicate log messages are being registered in the Azure dashboard. However, from the application's perspective, only a single message is being sent to the Application Insights tracer. This behavior is consistent for a few specific log messages but does not occur for all log messages.

<img width="1322" alt="image" src="https://github.com/Azure/azure-functions-host/assets/36529263/dbff45a4-9469-476e-863d-b979af49f3ae">

Application ID: 396353da-ae9b-4c0e-88dc-595930546782

#### Expected behavior
Each log message generated by the application should be sent once to the Application Insights tracer.
The Azure dashboard should display a single entry for each log message sent from the application.

#### Actual behavior
Some log messages are being duplicated in the Azure dashboard.
This duplication issue is consistent for specific log messages but does not occur for all log messages.

**Comment by swarnimsuman** [comment]
The resolution provided in [this GitHub issue](https://github.com/Azure/azure-functions-host/issues/9204) is not working for me.

**Comment by bhagyshricompany** [comment]
Thanks for informing pls share the all the repro steps and code.

**Comment by RohitRanjanMS** [comment]
Hi @swarnimsuman, can you share the repro steps?

**Comment by bhagyshricompany** [comment]
no update hence closing
