### ISSUE TITLE
Dynamic Concurrency with Service Bus Trigger

### ISSUE THREAD

**Issue by middiu** [Azure/azure-functions-host#10215]
Hi There, 

in our environment we have a Function App (isolated dotnet 8) with 5 Service Bus Triggers.
A couple of these Fucntions are really hungry of memory.

We have cuncurrency enabled in host.json to try to balance the load:
````
	"concurrency": {
		"dynamicConcurrencyEnabled": true,
		"snapshotPersistenceEnabled": true
	},
````

I can see some log under Category **Host.Concurrency** that confirms Dynamic Concurrency seems to be running:
![image](https://github.com/Azure/azure-functions-host/assets/428032/4c8761a8-a94e-45e1-8210-42242d8d08f0)

What we notice though doesn't make much sense:
1) Very often we can see the resources consumed by they 4 App Service instances are not really balanced. We can see one instance with 32GB or memory consumed out of 32GB, and the other 3 instance almost doing nothing.

My expectation would be that when one of the instance has reached 80-90% of its max Memory/CPU the concurrency manager would reduce the number of service bus messages processed by this instance, and increase the the same value for the other instances. Am I wrong about it?

2) All the log messages I can see are of the type
````
Applying status snapshot for function Host.Functions.xxxxx(Concurrency: 79)
Applying status snapshot for function Host.Functions.xxxxx(Concurrency: 8)
````

it sounds like it's applying the "snapshot" value of concurrency when the instance starts, but it doesn't change this value dynamically during the app life. is this correct?

I was expecting to see some more frrequent log messages about concurrency changes.

Any help would be appreciated.

Regards

**Comment by middiu** [comment]
Something I just notice is that I don't see any other **Host.Concurrency** log message expect the one when the Function App is started or redeployed, after that zero until the next deploy/restart.

Does it mean Dynamic Concurrency is not really working?

**Comment by bhagyshricompany** [comment]
Thanks for reporting pls share the all repro steps

**Comment by bhagyshricompany** [comment]
no respond hence closing.Thanks
