### ISSUE TITLE
Execution stops with no output but message still deleted from input queue binding

### ISSUE THREAD

**Issue by smythluke** [Azure/azure-functions-host#10227]
My Azure Function runs in the consumption plan. 
It is configured with a Storage Queue input binding.
Randomly (?) the Function will stop execution with nothing else being written to logs, however the message on the queue still gets deleted.

#### Investigative information

- Function App version: 4.34.2.22820
- Region: uk-south

Invocation example 1:
- Timestamp: 2024-06-12T01:00:03.7632823Z
- Invocation ID: 157f9ec3-9589-4e17-a084-680a8248eee3
- Queue message ID: d1cdf20a-29f6-4b49-8639-8a80d8fa3ed5

Invocation example 2:
- Timestamp: 2024-06-12T01:00:03.7690749Z
- Invocation ID: 4eabe54c-d168-4f23-b36d-0dcbcd9d6c7a
- Queue message ID: ab49a5e1-0729-4474-b222-24e3b181138f

Invocation example 3:
- Timestamp: 2024-06-12T01:00:03.769391Z
- Invocation ID: 31d2d38f-dc97-42fe-b617-bd07bae160fd
- Queue message ID: 60038948-e771-4b65-821b-9a8028d93923

Invocation that completed successfully in case it helps:
- Timestamp: 2024-06-12T01:00:03.7687273Z
- Invocation ID: 955b0820-3d5b-479b-bb8a-62f741061f05
- Queue message ID: 557bf290-72ae-4596-a112-e4ceb65e11a1

#### Repro steps

1. Put a message on the queue that is attached to the function as an input binding.

#### Expected behavior

The function should either
1. Fail in some way, log an error, and not delete the message from the queue
2. Successfully complete, then delete the message from the queue

#### Actual behavior

After a few log messages, there are no more logs written and yet the message is deleted from the queue. I don't see any errors in the logs and there is nothing to tell me that the function stopped.

#### Known workarounds

Run the function again and it works some times.

#### Related information 

We're using JavaScript.
Extension Bundle version is [4.0.0, 5.0.0)

**Comment by bhagyshricompany** [comment]
Hi Thanks for updating please share screen shots of code if possible.Thanks

**Comment by smythluke** [comment]
Hi @bhagyshricompany
The code in question is 250 lines long. What is it that would help you diagnose the issue? The code itself doesn't appear to be run anyway.

**Comment by bhagyshricompany** [comment]
ok will check and let you know.Thanks

**Comment by bhagyshricompany** [comment]
I create the seemsworking fine.can you try it again

**Comment by surgupta-msft** [comment]
Checked in the logs at our end. All the invocationIds you have shared were successfully completed. Did you not anything in the Application Insights logs for these invocations?

**Comment by smythluke** [comment]
Thankyou for looking into this.
It was my mistake. The function was invoked a lot in quick succession and the default logging policy samples the logs, making it seem as though it was not completing. Changing the sampling rate shows all the logs in application insights.
