### ISSUE TITLE
Manage Connections

### ISSUE THREAD

**Issue by Steffx115** [Azure/azure-functions-host#10235]
#### What problem would the feature you're requesting solve? Please describe.
Frustrating to deal with Connection Limit Exceeded (App needs to be restarted)

#### Describe the solution you'd like
Manage Connections internally (my implementation simply uses a semaphoreSlim and waits before every request. Optionally, if the CurrentCount of SemaphoreSlime is 0, throw an Exceptino)

#### Describe alternatives you've considered
Described my solution above, only problem is that is has to be implemented for every call that uses connections, and i dont have knowledge about the internals of the function host, so i cant optimize that right now

**Comment by JAdluri** [comment]
Could you please mention the number of connections you are using and meanwhile please look after the document : https://learn.microsoft.com/en-us/dotnet/standard/threading/semaphore-and-semaphoreslim
