### ISSUE TITLE
System.InvalidOperationException: The function invocation context is missing the forwarding task property

### ISSUE THREAD

**Issue by doorman02** [Azure/azure-functions-host#10236]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app, select `Diagnose and solve problems` from the left, and view relevant dashboards before opening your issue.

We are experiencing the same issues that are occuring in this [closed ticket](https://github.com/Azure/azure-functions-host/issues/10119 ) where the solution was to update the app runtime to version  4.34.2.2 . Our app is currently running on runtime version 4.34.1.1 in Switzerland North in isolated mode on Linux. Would it be possible to update it to the fixed version?

#### Investigative information

Please provide the following:

Timestamp: 2024-06-18T19:22:00.087Z
Function App version: 4
Function App name:
Function name: 
Invocation ID: 	aef546bf-977c-4f77-914a-8e47634ddb60
Region: Switzerland North 

#### Repro steps

Provide the steps required to reproduce the problem:

Watch telemetry or log streams, witness the Exception occur inconsistently.

#### Expected behavior

Provide a description of the expected behavior.

It should work without throwing exceptions regarding internal forwarding and proxying.

#### Actual behavior

We're experiencing internal exceptions randomly in different functions, the exception being The function invocation context is missing the forwarding task property. The error can be repeated by refreshing the browser a few times. 

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by kshyju** [comment]
@arroyc Could you provide the estimated completion date for the Linux rollout of version 4.34.2?

**Comment by doorman02** [comment]
Hi @kshyju , @arroyc thanks for your assistance. Since this is a critical update for the availability of the application I am considering to move the app to a location with the 4.34.2 runtime until the rollout is completed unless it happens in the next few days. I would prefer to use the current app location since the database is in the same region. Could you give a rough estimate for the rollout?  What regions have already rolled out the 4.34.2 runtime? Thanks!!

**Comment by amamounelsayed** [comment]
Hey @doorman02 we released 4.34.2.1 to Switzerland North for linux consumption. Thank you

**Comment by kshyju** [comment]
@doorman02 Let us know if you are still seeing the issue. Thank you!

**Comment by doorman02** [comment]
@amamounelsayed @kshyju thanks alot for the quick response. I have two apps running that I am using for deployment swapping. Both are running in Switzerland North but only one has been updated to 4.34.2.2 my staging app is still on runtime 4.34.1.1 . Is it possible that the rollout takes time to update? I tested the 4.34.2.2 and its running without problem :) but it would be great if the staging app could be updated as well to runtime 4.34.2.2 because I am swapping it. Thanks again for your help.

**Comment by amamounelsayed** [comment]
Thank you please could you recheck as it may be got updated by now. Please if it is still on 4.34.1.1 please could you share the app name?
Thank you

**Comment by doorman02** [comment]
Hi @amamounelsayed It's solved.
Thank you!

**Comment by amamounelsayed** [comment]
Thank you for sharing please if the staging app is on Linux consumption SKU, could you stop the app and start it again not "restart" if this works with you? Please let us know if this would work. Thank you so much

**Comment by doorman02** [comment]
@amamounelsayed this actually worked. Thanks alot for your help.
