### ISSUE TITLE
[FlexConsumption]Add Cold and Hot Sites for .Net 9

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#10242]
Parallel tracking item for platform work

cc @fabiocav @nzthiago

**Comment by kshyju** [comment]
FYI - we have an epic tracking .NET9 items here : https://github.com/Azure/azure-functions-dotnet-worker/issues/2500

**Comment by pragnagopa** [comment]
@kshyju @fabiocav - can you track this WI as part of the .Net 9 epic?

**Comment by fabiocav** [comment]
This is already tracked in the epic and there's no host issue (all the work is worker related), so closing this here.
