### ISSUE TITLE
Update Stacks API to include .NET 9

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#10243]
Include .NET 9 in https://github.com/Azure/azure-functions-ux/blob/dev/server/src/stacks/2020-10-01/stacks/function-app-stacks/Dotnet.ts

cc @fabiocav @nzthiago

**Comment by pragnagopa** [comment]
P0; Required for GA

**Comment by mattchenderson** [comment]
Duplicate of https://github.com/Azure/azure-functions-dotnet-worker/issues/2562
