### ISSUE TITLE
[Bug] App setting binding expressions cannot contain double underscores (__)

### ISSUE THREAD

**Issue by evanlouie** [Azure/azure-functions-host#10246]
### Expected Behavior

I should be able to use app settings and environment variables name which contain double underscores in app setting bindings.

### Actual Behavior

The webjobs host cannot resolve environment variables which where the name contains double underscores.

### Steps to Reproduce

1. local.settings.json:

   ```json
   {
     "IsEncrypted": false,
     "Values": {
       "AzureFunctionsJobHost__extensions__durableTask__hubName": "MyTaskHub",
       "AzureWebJobsStorage": "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=*************************==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1"
     }
   }
   ```

2. function_app.py

   ```py
   import json
   import logging

   import azure.functions as func

   app = func.FunctionApp(http_auth_level=func.AuthLevel.ANONYMOUS)


   @app.timer_trigger(arg_name="timer", schedule="0/5 * * * * *")
   @app.table_input(
       arg_name="entitiesJson",
       connection="AzureWebJobsStorage",
       table_name="%AzureFunctionsJobHost__extensions__durableTask__hubName%Instances",
       filter="RuntimeStatus eq 'Suspended'",
   )
   async def my_func(
       timer: func.TimerRequest,
       entitiesJson: str,
   ):
       entities = json.loads(entitiesJson)
       logging.info(f"There are {len(entities)} suspended orchestrations")
   ```

### Relevant log output

```shell
[2024-06-24T01:30:00.085Z] System.Private.CoreLib: Exception while executing function: Functions.my_func. Microsoft.Azure.WebJobs.Host: '%AzureFunctionsJobHost__extensions__durableTask__hubName%' does not resolve to a value.
```

### Where are you facing this problem?

Local - Core Tools

### Additional Information

- Binding works with single underscore; only double breaks bindings.
- `print(os.environ)` will show that the app setting is being loaded as an environment variable.
- Most likely conflicting with https://learn.microsoft.com/en-us/azure/azure-functions/functions-host-json#override-hostjson-values

**Comment by vrdmr** [comment]
Transferring to the host team to check if this is a valid scenario where the passed app setting is allowed to be resolved or now.

**Comment by bhagyshricompany** [comment]
will check and update Thanks

**Comment by bhagyshricompany** [comment]
Hi  @evanlouie  please ref this doc https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#app-setting-considerations
