### ISSUE TITLE
Clarify Different Release Branches

### ISSUE THREAD

**Issue by cpsnowden** [Azure/azure-functions-host#10241]
#### What language does your question apply to? C#

Please can I clarify the difference between release branches for `azure-function-hosts`, I see three different versions progressing recently:

- [4.1034.2](https://github.com/Azure/azure-functions-host/releases/tag/v4.1034.2)
- [4.834.4](https://github.com/Azure/azure-functions-host/releases/tag/v4.834.4)
- [4.34.2](https://github.com/Azure/azure-functions-host/releases/tag/v4.34.2)

**Comment by surgupta-msft** [comment]
- 4.XX – the traditional variant, which supports the in-process model and out-of-process workers 
- 4.6XX – the in-process host targeting .NET 6; apps clearly targeting the in-process model have been shifted to this 
- 4.8XX – the in-process host targeting .NET 8; apps must opt-into this explicitly 
- 4.10XX – the new default which will only support out-of-process workers; this is the primary subject of this post
