### ISSUE TITLE
Support telemetryMode: openTelemetry in .net isolated docker images

### ISSUE THREAD

**Issue by vmcbaptista** [Azure/azure-functions-host#10258]
#### What problem would the feature you're requesting solve? Please describe.
I'm running azure functions in a containerized environment and would like to have all observability based on open telemetry .
We will be using Azure Monitor Application Insights still, but via open telemetry, although we not exclude using other exporter in near future.

#### Describe the solution you'd like
Would be possible to create a new docker image of the .net 8 isolated host that supports the new telemetryMode: openTelemetry that is currently available on the dev branch?

#### Describe alternatives you've considered
There's the possibility to add open telemetry to the worker, but this causes duplication of the log entries on the application insights. Disabling the WorkerLogProvider stops this duplication, but the host telemetry data keeps being sent without using open telemetry, also worker logs stop being written in the console which sometimes we find useful.

**Comment by RohitRanjanMS** [comment]
Hi @vmcbaptista as of now the OTel feature is limited to Flex consumption plan. Our plan is to eventually roll out for all the hosting platforms. This feature has dependency on other components and hence the delay. I don't have any ETA, but this remains our priority.

**Comment by vmcbaptista** [comment]
Hi @RohitRanjanMS thanks for your reply, it's a shame to not have an ETA for this, but is good to know that this is on your radar. If there's anything I can contribute to help moving this further, please let me know.

**Comment by attilah** [comment]
@RohitRanjanMS any update on this? Why was the issue close if it's not done?
