### ISSUE TITLE
AzureFunction QueueBased is failing to process without error

### ISSUE THREAD

**Issue by eddynaka** [Azure/azure-functions-host#10286]
#### Investigative information

Please provide the following:

- Timestamp: From 2024-07-12 23:05:26.5817348 to 2024-07-12 23:05:26.7309554
- Function App version: v4 using .NET 6
- Function App name: githubsecretsprocessor
- Function name(s) (as appropriate): githubsecretsprocessor
- Invocation ID: 0ae50e4a-7d99-4c47-8855-d3ceee5d6236
- Region: EUS 

#### Repro steps

Starting at 2024-07-12 17:47:29.2943590, one of my queue based azure functions stopped working without deployments. I can see that there are many cases here the azure function hold the message for some time without processing anything.

Then, it marks as failed.

This already happened for almost 100k messages.
All are failing with the same behavior. No exceptions and no traces that could help me investigate what is going on.

#### Related information 

Reach out to teams internally in case you need more information.

**Comment by kshyju** [comment]
@eddynaka Please [open an ICM ticket](https://aka.ms/cri-functions).
