### ISSUE TITLE
How to turn off "Executing | Executed | Trigger details" traces

### ISSUE THREAD

**Issue by vany0114** [Azure/azure-functions-host#10308]
#### Is your question related to a specific version? If so, please specify:
"@azure/functions": "^3.5.1"

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
Javascript - NodeJS

#### Question
Is there a way to configure the log level to avoid ingesting these runtime traces?

```
Executing 'Functions.HttpTrigger1' ...
Executed 'Functions.HttpTrigger1' (Succeeded ...)
```

I noticed that using the Application Insights SDK there's no way we can sample those, they never land in the telemetry processor, I guess it's because they are runtime traces.

I know we can configure the log level per function, like:
```
"Function.HttpTrigger1": "None"
```

However, that's not ideal or maintainable and if I do this:
```
"Functions": "None"
```

Then I lose all the logs.

We need to do so because they swamped our telemetry data, they are not useful for us and we're being charged for that which is super expensive. 

Related issue: https://github.com/microsoft/ApplicationInsights-node.js/issues/1359#issuecomment-2237211129

**Comment by bhagyshricompany** [comment]
Thanks for reporting please refer this doc ::https://learn.microsoft.com/en-us/azure/azure-functions/functions-monitoring#disable-built-in-logging

**Comment by vany0114** [comment]
> Thanks for reporting please refer this doc ::https://learn.microsoft.com/en-us/azure/azure-functions/functions-monitoring#disable-built-in-logging

I've already seen that documentation, however, it doesn't answer the question.

**Comment by jviau** [comment]
@vany0114 it is not possible to configure these specific logs beyond the log-level filters you mentioned. However, we are making investments in moving to open telemetry, which will improve this area in the future.

/cc: @RohitRanjanMS

**Comment by RohitRanjanMS** [comment]
@vany0114, we recently launched [OpenTelemetry](https://github.com/Azure/azure-functions-host/issues/9273) support in Azure Functions, as detailed [here](https://learn.microsoft.com/en-us/azure/azure-functions/opentelemetry-howto?tabs=app-insights&pivots=programming-language-csharp). One of our goals was to reduce telemetry, and as a result, we no longer generate "Executing..." and "Executed..." logs. Instead, we only provide a request telemetry that contains all the necessary information.

Currently, this feature is available for the Flex consumption plan, but we plan to extend it to all SKUs in the future.
