### ISSUE TITLE
Is .NET 8 In-Process model available in Azure for US Government?

### ISSUE THREAD

**Issue by ivantioh** [Azure/azure-functions-host#10371]
#### Is your question related to a specific version? If so, please specify:

- .NET Version: .NET 8
- Model: In-Process
- Azure Function Version: 4

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 

- Language: C#

#### Questions

Understand from this [tracking thread](https://github.com/Azure/azure-functions-host/issues/9951) that .NET 8 In-Process model support in sovereign clouds is still in progress.

1. Would like to clarify is `sovereign clouds` in above context includes [Azure for US Government](https://azure.microsoft.com/en-us/explore/global-infrastructure/government)?
2. If yes, could we expect the ETA of the .NET 8 In-Process model support for `Azure for US Government` before [.NET 6 EOS](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) in November 2024?

Thank you.

**Comment by satvu** [comment]
Closed as resolved.
