### ISSUE TITLE
Is it possible to run streaming API fluently through API management?

### ISSUE THREAD

**Issue by ogiel** [Azure/azure-functions-host#10389]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
Python

#### Question
Is it possible to accomplish fluent stream responses when using API management in front of my API endpoints for security?

Some details; I made a streaming API a while ago and did extensive testing by just deploying to a (serverless) azure functions app in Python with the new fastapi stream functionality. This worked great. However, when I add the API management layer for access through JWT tokens, the response becomes quite jittery. 

Responses sort of 'stream' still but the text is returned in 3 blocks where it would normally consist of 50 small textual additions.

**Comment by bhagyshricompany** [comment]
1. Thanks for reporting please share full repro steps.
