### ISSUE TITLE
How to get and set custom status in the Isolated Worker model?

### ISSUE THREAD

**Issue by DeltekDavid** [Azure/azure-functions-host#10393]
#### Is your question related to a specific version? If so, please specify:
Functions 4.x on .NET 8.0, Isolated Worker model

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
We're planning on migrating our .NET 6 in-process functions to .NET 8 with isolated workers. In our current code, we make extensive use of the [custom status API](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-custom-orchestration-status?tabs=csharp) to store things like progress percentage. The client can then poll for the latest status and update a progress bar.

For example, we have code like:

```csharp
            int percentComplete = (int)((double)(itemsDone) / itemsTotal * 100);
            context.SetCustomStatus(new BackendProcessProgress
            {
                ProgressPercentage = percentComplete
            });
```
and
```csharp
        DurableOrchestrationStatus status = await client.GetStatusAsync(instanceId);  
```

Is there equivalent functionality in Isolated Worker? If not, what are the best practices/recommendations for doing this sort of thing?

**Comment by bhagyshricompany** [comment]
@DeltekDavid  Thanks for reporting please share all the repro steps. what you are trying

**Comment by DeltekDavid** [comment]
@bhagyshricompany this isn't a bug, I just want to know how to do the equivalent things in the new Isolated Process model (and whether it's even possible). Thanks

**Comment by cjaliaga** [comment]
@DeltekDavid the [.NET Isolated language worker extension](https://github.com/microsoft/durabletask-dotnet), `TaskOrchestrationContext` contains a `SetCustomStatus` method equivalent.

With the DurableTaskClient you can get the Instance metadata and then Read the Custom Status:

```csharp
var orchestrationMetadata = await client.GestInstanceAsync(instanceId);
var customStatus = orchestrationMetadata.ReadCustomStatusAs<BackendProcessProgress>();
```

**Comment by DeltekDavid** [comment]
Thank you @cjaliaga , this looks like just the thing. I couldn't find any mention of it in the docs, though. They still refer to the [in-process version](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-custom-orchestration-status?tabs=csharp).

**Comment by fabiocav** [comment]
Closing as resolved.
