### ISSUE TITLE
Enhancement : Using different verisons of Python

### ISSUE THREAD

**Issue by prashanthmadi** [Azure/azure-functions-host#1039]
Below link has details on how to use custom version of Python in Functions app
https://github.com/Azure/azure-webjobs-sdk-script/wiki/Using-a-custom-version-of-Python

Is there a way to change the folder where python need to be uploaded ?
 
Considering that we have site-extensions which would install newer version of python in D:\home\python27 (or) D:\home\python35.
It would be great if there is app-setting to change runtime to use above folder instead.

**Comment by prashanthmadi** [comment]
Adding Steve Dower Notes below
------------------------------------------
If there's already an environment variable there that could control where the site extension copies to. Of course, that assumes the ability to do a normal site extension installation.

If possible, I'd recommend the site extension or the nuget package for this, rather than the embeddable distro. See my latest blog at http://stevedower.id.au/ for a primer on the different options.

**Comment by prashanthmadi** [comment]
I wrote about current workaround for this @ https://prmadi.com/running-python-code-on-azure-functions-app/

**Comment by asavaritayal** [comment]
We will no longer be adding new features to Functions 1.0.

Python support has been reintroduced on Functions 2.0 and `python 3.6` is supported. You can follow the discussion here - https://aka.ms/functions-python-preview
