### ISSUE TITLE
Unable to parse host configuration file

### ISSUE THREAD

**Issue by ccarmannt** [Azure/azure-functions-host#10421]
#### Investigative information
Azure fails to parse the attached host.json file.
It provides only this error in the portal:

```
System.FormatException : Unable to parse host configuration file 'C:\home\site\wwwroot\host.json'. ---> 
Newtonsoft.Json.JsonReaderException : After parsing a value an unexpected character was encountered: ". Path 'extensions', line 8, position 4
```

But there is no "extensions" element in the file. Is it being read from a cache somewhere?

- Timestamp: Today, 22 August, 1537 New York time

#### Expected behavior

The file should be parsed correctly. 

#### Actual behavior

The file is not parsed correctly.

#### Known workarounds

None found.
I have attempted restarting the app. I have attempted stopping the app for a while and then restarting it. Neither was effective.
Additionally, running the function in my local development environment works fine, no complaints about this file.

#### Related information 

[host.json](https://github.com/user-attachments/files/16717297/host.json)

**Comment by bhagyshricompany** [comment]
Thanks for informing please share the repro  steps and host.json file config.

**Comment by ccarmannt** [comment]
The config file is already attached.

I don't have a known reproducible scenario. All I know is I changed it somehow that caused the parsing error, then reverted to the original. But after reverting to the original, the error didn't go away.

**Comment by bhagyshricompany** [comment]
ok will check and update

**Comment by simonlindner** [comment]
I have the same Error. I already tried to remove the Function and Create a new one, restarting the function, removing the host.json file and adding it again. That all did not work.

**Comment by bhagyshricompany** [comment]
it working fine locally as well as azure portal .![Image](https://github.com/user-attachments/assets/2040b50f-fea8-49f1-9e9d-58c02b077983)
![Image](https://github.com/user-attachments/assets/d439851c-784d-49a9-8fcc-bee7849c3623)

**Comment by ccarmannt** [comment]
@bhagyshricompany That is 2 months too late, and completely incorrect.

**Comment by bhagyshricompany** [comment]
Thanks for your patience @ccarmannt  what is incorrect?I just used your  config file ( host.json ) and tested it seems working fine.if you need more specific please mention what missing.Thanks will investigate and update you.Thanks again.

**Comment by ccarmannt** [comment]
The problem is that this is the configuration I uploaded and the server failed to parse it.  It then continued to fail to parse it for several days, before magically fixing itself.

There is nothing I can find to explain either the parsing failure or the magical fix.

**Comment by dsun615** [comment]
I got the same error as well and was able to find the issue and fix it.

It look like the host.json file didn't get uploaded even though the deployment said it was successful.

In Azure, find your Azure Function and checked the **App Files** under **Functions**.

It should show your host.json file. Mine was empty. Hence why we get the _"Unable to parse host configuration file"_ error.

I've copied my host.json file from my local into Azure and the error went away.

Hope that helps.

![Image](https://github.com/user-attachments/assets/48ecece4-b5b8-42fd-81d4-c5fe465866a3)

Below is the json I updated it to.

**{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[4.*, 5.0.0)"
  }
}**

**Comment by bhagyshricompany** [comment]
Hopes its working fine  if have issue please raise request again.Thanks

**Comment by ccarmannt** [comment]
Nothing's been fixed and no knowledge has been gained. Congrats.

**Comment by sadranyi** [comment]
I am also getting the same error, though running the functions works perfectly.

Message
Unable to parse host configuration file 'C:\home\site\wwwroot\host.json'.

Details
System.FormatException : Unable to parse host configuration file 'C:\home\site\wwwroot\host.json'. ---> Newtonsoft.Json.JsonReaderException : Unexpected end of content while loading JObject. Path 'logging', line 10, position 1. at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader,JsonLoadSettings options) at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader,JsonLoadSettings settings) at Newtonsoft.Json.Linq.JObject.Parse(String json,JsonLoadSettings settings) at Newtonsoft.Json.Linq.JObject.Parse(String json) at Microsoft.Azure.WebJobs.Script.Configuration.HostJsonFileConfigurationSource.HostJsonFileConfigurationProvider.LoadHostConfig(String configFilePath) at /_/src/WebJobs.Script/Config/HostJsonFileConfigurationSource.cs : 200 End of inner exception

Hit count
10

This is my host file content
```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  }
}
```

**Comment by TheNorth514** [comment]
Hi,

I have got the exact same issue as @sadranyi. I added the property to increase the timeout of our Azure Function and got the error. I revert back the file to its original state but the error remains.

I think it's a problem from the notification system keeping the message instead of clearing it. When I check the time of the issue (in my case), it displays an old date:

<img width="295" height="574" alt="Image" src="https://github.com/user-attachments/assets/80019b9c-8d5f-4417-bd49-e53565854fbc" />

**Comment by guwi-smartpoint** [comment]
Same problem as @TheNorth514 has described.

The provided timestamp is way before later successful deployments to the function app; the last one at 02:35 PM +2 GMT:

<img width="248" height="53" alt="Image" src="https://github.com/user-attachments/assets/1c700c71-8cb8-4340-b6d4-7afdad616fda" />

**Comment by thesidshah** [comment]
I am running into the same error!
There was some git merge issue for me, fixed it and redeployed, turns out, EVEN if the host.json is updated, it still is giving me the same error! I do not have a single angular bracket in my host file but still find the error.
