### ISSUE TITLE
Test run of timer trigger or service bus trigger failing with 403

### ISSUE THREAD

**Issue by shimedh** [Azure/azure-functions-host#10422]
This is a runtime issue. According to the logs in Kudu, the host listener isn't starting in the timer trigger instances where Test/Run doesn't work

This was reported in Portal's vendor test pass:
Bug for timer trigger that has the steps and attached har - 
 [Bug 29145902](https://msazure.visualstudio.com/Antares/_workitems/edit/29145902): [FunctionApp][Code + Test][Canary]: Getting an error after running the trigger 'test/run'. The output status is 403 Forbidden.
 
 
Bug for service bus trigger that has the steps and attached har-
[Bug 29146716](https://msazure.visualstudio.com/Antares/_workitems/edit/29146716): [FunctionApp][Canary]: Getting '403 forbidden' error when running the trigger.

**Comment by mattchenderson** [comment]
This seems connected to the admin isolation feature being on. For anyone encountering this issue, please check if the feature is enabled. You can find this in the portal under "Configuration" > "General Settings", and then check to see if "Functions admin isolation" is set to "on". The current test experience requires this to be set to "off". You may need to restart the app after turning this off.

**Comment by mattchenderson** [comment]
Closing based on above description. We addressed the portal change that led to this behavior being seen. The above instructions can be used if encountering the issue.
