### ISSUE TITLE
After updating to .NET 8 I'm getting this error: Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. Grpc.AspNetCore.Server: Could not load file or assembly 'Microsoft.AspNetCore.Routing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by mirwin101** [Azure/azure-functions-host#10450]
I updated to these versions:

    <ItemGroup>
        <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.42.0" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.16.4" />
        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.4.1" />
    </ItemGroup>

Everything works fine locally in Visual Studio. I just see the error after deploying to Azure.

**Comment by mirwin101** [comment]
The function is using .NET 8 (LTS) In-Process.  Here's the entire project file.

<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AzureFunctionsVersion>v4</AzureFunctionsVersion>

        
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <AssemblyName>UL.Framework.Audit.Function</AssemblyName>
        <AssemblyTitle>UL.Framework.Audit.Function</AssemblyTitle>
        <FileVersion>$(Version)</FileVersion>
        <AssemblyVersion>$(Version)</AssemblyVersion>

        
        <IsPublishable>True</IsPublishable>   
        <PublishDir>bin\publish</PublishDir>

        
        <IsPackable>true</IsPackable>                
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <NoWarn>1701;1702</NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <NoWarn>1701;1702</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.42.0" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.16.4" />
        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.4.1" />
    </ItemGroup>
    <ItemGroup>
        <None Update="host.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="local.settings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\DifferenceEngine\DifferenceEngine.csproj" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Update="NuGet.Build.Tasks.Pack" Version="6.11.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>
</Project>

**Comment by mirwin101** [comment]
I don't see any version of Microsoft.AspNetCore.Routing in the solution locally and the function works fine locally in Visual Studio.

**Comment by BorisWilhelms** [comment]
We ran into the same issue. We are hosting the functions in a Linux docker container. Everything works when started within Rider on Linux but not when published. Turns out we had to change the container to use `mcr.microsoft.com/azure-functions/dotnet:4-dotnet8.0` instead of `mcr.microsoft.com/azure-functions/dotnet:4` as the base image.

**Comment by mirwin101** [comment]
This was resolved by creating a new project and copying the user code from the original function over to it. Although this got it working again, I ended up converting the project to .NET 8 Isolated mode so we don't have to revisit this next year.

**Comment by erichkray** [comment]
I know this is a closed thread, but as it is the only one that came up in the results for this issue I am going to leave this here.

If you are running .NET 8 in-proc, then you need to add FUNCTIONS_INPROC_NET8_ENABLED set to 1 in your environment configuration.
See: https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#functions_inproc_net8_enabled

**Comment by runr02** [comment]
I'm encountering the same problem. My temporary workaround involves deploying using the publish feature in Visual Studio Pro, targeting .NET 6. Locally, I'm running .NET 8 in-proc. I'm eagerly awaiting any updates on this matter. When I create a Function App in .NET 8 and deploy the template code, it fails due to the code's use of a dynamic type. Neither recommendation above has helped with this issue.

**Comment by smadhukar2000** [comment]
> I know this is a closed thread, but as it is the only one that came up in the results for this issue I am going to leave this here.
> 
> If you are running .NET 8 in-proc, then you need to add FUNCTIONS_INPROC_NET8_ENABLED set to 1 in your environment configuration. See: https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#functions_inproc_net8_enabled

I was getting same issue and it resolved my issue.
