### ISSUE TITLE
Azure Functions (.NET8,Isolated) execution stalled and in limbo after uncaught exception

### ISSUE THREAD

**Issue by aaramians** [Azure/azure-functions-host#10489]
Core Tools Version:       4.0.6280 Commit hash: N/A +421f0144b42047aa289ce691dc6db4fc8b6143e6 (64-bit)
Function Runtime Version: 4.834.3.22875
.NET 8 - Isolated

Steps:
Start with brand new template project on Azure Function and throw an exception:
```
        [Function("Function1")]
        public IActionResult Run([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequest req)
        {
            throw new InvalidOperationException();

            _logger.LogInformation("C# HTTP trigger function processed a request.");
            return new OkObjectResult("Welcome to Azure Functions!");
        }
```
```
curl http://localhost:7135/api/Function1
```

Expectation: 
The client stalls, the server also stalls
I was expecting the client connection to be dropped and server/host to fail the invocation.

The issue I encountered was more complex. If the intended design is to prevent exceptions from bubbling up to the framework for handling, I can understand that this may be the expected behavior, where middleware would be responsible for catching the exception. This was the approach I attempted; however, I was unable to close the connection or mark the invocation as failed, while using function context/GetHttpContext/GetInvocationResult/...

On the other hand, if the framework is expected to handle this, I wouldn't anticipate a stall scenario.

**Comment by bhagyshricompany** [comment]
@aaramians  thanks for reporting will update you.

**Comment by bhagyshricompany** [comment]
@kshyju  pls confirm and validate.

**Comment by satvu** [comment]
@aaramians Does this still repro if you use the latest available package here: https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore?
