### ISSUE TITLE
The mirror pipeline should support force pushing from a public GitHub repository.

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-host#10498]
Currently, if the internal branch has a commit that is not available in the public GitHub repository, the mirror pipeline does not sync the repository. The mirror pipeline should be updated to trigger a sync when force pushing from the public GitHub repository for `release/*` branches only.

**Comment by fabiocav** [comment]
For clarity, this should be done for `release/*` branches only.

**Comment by jviau** [comment]
@Francisco-Gamino I need some clarification on your issue. Are you saying we have made a commit to Azure Devops release/* branch and you want that change to flow back into GitHub?

Or are you saying we have made a force-push to GitHub release/* branch, and that new commit is not being mirrored to Azure Devops?
