### ISSUE TITLE
Opentelemetry features and host versions

### ISSUE THREAD

**Issue by Sarabadu** [Azure/azure-functions-host#10534]
#### Is your question related to a specific version? If so, please specify:
Host Versions: 4.34.2.2 and 4.1036.2.2
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
Language: Javascript/ts
#### Question
-  How the host versions works.?  I see there are many different `minorVersionPrefix` with different features. Didn't find any docs explaining it sry
-  How the assignment of host version work on deployment? I would like my two environments to be as similar as posible

#### context:
We have been working with open telemetry in our function for a while, the functions are not flex consumption but trying out the config we saw good results in the App insights transaction view.

This week we migrated our functions to a new subscription same IaC 2 environments, but after deploying we noted one of the environment was not propagating any exceptions now. we also noted that we started getting telemetry from the host now(but not from our function).

After debugging for a while we noted that the host version in both environments was different  
- 4.34.2.2: was working as before getting all the application spans from our function and proper exception in the exception table.
- 4.1036.2.2: was not saving the exceptions and spans looked messed up.

looking on the tags I noted all 4.10x version have the otel functionality and all 4.x do not have that

Tested forcing the host version in the function it was working as we expected to be the same and we got same results.

I know this is not a bug as documentation state that this should work on flex consumption only(not still on our region) and also was just matter of disable otel on the host. 

If there is any docs referring to this please let me know, I searched but didn't find much regarding minor versions

Thanks!!!

**Comment by jviau** [comment]
> How the host versions works.? I see there are many different minorVersionPrefix with different features. Didn't find any docs explaining it sry

We have gone through a process to 'split' our functions host into distinct versions which are selected based on the customers app payload. We use a minor version prefix to differentiate the different hosts we deploy. They are:

- `4.10xx`: out-of-proc host. For all non-.net-in-proc function apps.
- `4.8xx`: .net 8 in-proc
- `4.6xx`: .net 6 in-proc

> How the assignment of host version work on deployment? I would like my two environments to be as similar as posible

We roll out new host versions incrementally. We are in the process of rolling out these split hosts. You should see all your apps eventually move to the `4.10xx` versions. The timing of that varies based on the sku, plan, and region your application is in.

As for documentation, otel support is in preview and we are actively working on both the functionality and documentation for it. As for spans/exceptions looking message up, there is an expected difference between legacy app insights and otel support. We are working towards adopting OTel semantic conventions to ensure the telemetry we emit is in line with that. These conventions are still experimental for faas. This issue: #10560 tracks that work.

**Comment by Sarabadu** [comment]
Thanks @jviau for your response!!!
