### ISSUE TITLE
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Mvc.Core, Version=8.0.0.0

### ISSUE THREAD

**Issue by AisseMTT** [Azure/azure-functions-host#10547]
### What version of .NET does your existing project use?

.NET 6

### What version of .NET are you attempting to target?

.NET 8

### Description

I followed instructions to migrate my function app from .NET6 to .NET8 by setting 
`<TargetFramework>net8.0</TargetFramework>`
`<AzureFunctionsVersion>v4</AzureFunctionsVersion>`

upgraded to 
`<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.5.0" />`
in my csproj file. 

In my local.settings.json file I included these three settings: 
`"FUNCTIONS_WORKER_RUNTIME": "dotnet",`
`"FUNCTIONS_EXTENSION_VERSION": "~4",`
`"FUNCTIONS_INPROC_NET8_ENABLED": "1",`

When I build my solution however, I am getting the above error: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Mvc.Core, Version=8.0.0.0

### Project configuration and dependencies

![Image](https://github.com/user-attachments/assets/b5f89690-7ed7-49fb-81f9-85da72598baf)

**Comment by bhagyshricompany** [comment]
@AisseMTT Thanks for reporting will check and update.please share config dependency here  in txt file or copy here   all sdk mention above .Thanks.

**Comment by bhagyshricompany** [comment]
Hi @AisseMTT  please provide the list   of sdk in group .so I can check at my side.Thanks

**Comment by majidazn** [comment]
I had this problem, and in my function method, I had some attributes that didn't work correctly in .NET 8.
forexamle [FromRoute]
