### ISSUE TITLE
.NET8 InProcess Azure function(service bus trigger) Migration

### ISSUE THREAD

**Issue by Sirishapujari** [Azure/azure-functions-host#10652]
### What version of .NET does your existing project use?

.NET Framework 4.8

### What version of .NET are you attempting to target?

.NET 8

### Description

Hi ,

I am migrating Azure function app (servicebus trigger )from .NET 4.8 to .NET 8 which is working in my local . When i deploy the functionapp to Portal I am facing an error 
"Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. Grpc.AspNetCore.Server: Could not load file or assembly 'Microsoft.AspNetCore.Routing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified."

Here is my .Cs proj file 
[Github .txt](https://github.com/user-attachments/files/17870889/Github.txt)

Please help me with the fix.

**Comment by kshyju** [comment]
Did you create a new function app and deploy to that or deployed to your old V1 app? Can you try deploying a brand new .NET8 in-process app?

**Comment by ipetrouchtchak-fi** [comment]
> I am migrating Azure function app (servicebus trigger )from .NET 4.8 to .NET 8 which is working in my local . When i deploy the functionapp to Portal I am facing an error "Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. Grpc.AspNetCore.Server: Could not load file or assembly 'Microsoft.AspNetCore.Routing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified."
> 
> Here is my .Cs proj file [Github .txt](https://github.com/user-attachments/files/17870889/Github.txt)
> 

@Sirishapujari, have you tried adding `_FunctionsSkipCleanOutput` in csproj?

```
﻿<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
...
```

**Comment by dellch** [comment]
A few things:
1.  You might be better off migrating directly to the [isolated worker model](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-in-process-differences), instead of using _in-process_.  
2. To expand on @ipetrouchtchak-fi's message above, an alternative to using `<_FunctionsSkipCleanOutput>` is to use 
`<FunctionsPreservedDependencies>` element:
    ```xml
    <ItemGroup>  
      <FunctionsPreservedDependencies Include="Microsoft.AspNetCore.Routing.dll" />
    </ItemGroup>
    ```
    The best explanation I've found about both the `_FunctionsSkipCleanOutput` and `FunctionsPreservedDependencies` is [this blog post by @bryanknox](https://bryanknox.github.io/2022/07/15/functionsskipcleanoutput-and-functionspreserveddependencies.html).

**Comment by Sirishapujari** [comment]
> Did you create a new function app and deploy to that or deployed to your old V1 app? Can you try deploying a brand new .NET8 in-process app?

I have created a new function app and deployed my code.

**Comment by Sirishapujari** [comment]
> > I am migrating Azure function app (servicebus trigger )from .NET 4.8 to .NET 8 which is working in my local . When i deploy the functionapp to Portal I am facing an error "Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. Grpc.AspNetCore.Server: Could not load file or assembly 'Microsoft.AspNetCore.Routing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified."
> > Here is my .Cs proj file [Github .txt](https://github.com/user-attachments/files/17870889/Github.txt)
> 
> [@Sirishapujari](https://github.com/Sirishapujari), have you tried adding `_FunctionsSkipCleanOutput` in csproj?
> 
> ```
> ﻿<Project Sdk="Microsoft.NET.Sdk">
>   <PropertyGroup>
>     <TargetFramework>net8.0</TargetFramework>
>     <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
> ...
> ```

Hi ,
Thanks for responding.

I added both the lines that you have given still I am facing the same issue with the dll .I am facing this issue only after deploying to Azure.![Image](https://github.com/user-attachments/assets/cd698c03-60e6-45b2-8c58-f0193cec8754)

attached the new cs.proj file for your reference
[Project file .txt](https://github.com/user-attachments/files/17880004/Project.file.txt)

**Comment by Sirishapujari** [comment]
> > I am migrating Azure function app (servicebus trigger )from .NET 4.8 to .NET 8 which is working in my local . When i deploy the functionapp to Portal I am facing an error "Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. Grpc.AspNetCore.Server: Could not load file or assembly 'Microsoft.AspNetCore.Routing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified."
> > Here is my .Cs proj file [Github .txt](https://github.com/user-attachments/files/17870889/Github.txt)
> 
> [@Sirishapujari](https://github.com/Sirishapujari), have you tried adding `_FunctionsSkipCleanOutput` in csproj?
> 
> ```
> ﻿<Project Sdk="Microsoft.NET.Sdk">
>   <PropertyGroup>
>     <TargetFramework>net8.0</TargetFramework>
>     <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
> ...
> ```



> > > I am migrating Azure function app (servicebus trigger )from .NET 4.8 to .NET 8 which is working in my local . When i deploy the functionapp to Portal I am facing an error "Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. Grpc.AspNetCore.Server: Could not load file or assembly 'Microsoft.AspNetCore.Routing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified."
> > > Here is my .Cs proj file [Github .txt](https://github.com/user-attachments/files/17870889/Github.txt)
> > 
> > 
> > [@Sirishapujari](https://github.com/Sirishapujari), have you tried adding `_FunctionsSkipCleanOutput` in csproj?
> > ```
> > ﻿<Project Sdk="Microsoft.NET.Sdk">
> >   <PropertyGroup>
> >     <TargetFramework>net8.0</TargetFramework>
> >     <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
> > ...
> > ```
> 
> Hi , Thanks for responding.
> 
> I added both the lines that you have given still I am facing the same issue with the dll .I am facing this issue only after deploying to Azure.![Image](https://github.com/user-attachments/assets/cd698c03-60e6-45b2-8c58-f0193cec8754)
> 
> attached the new cs.proj file for your reference [Project file .txt](https://github.com/user-attachments/files/17880004/Project.file.txt)

**Comment by Sirishapujari** [comment]
Hi ,

Thanks for responding.
The issue is fixed now after updating all the nuget packages to the latest version and downgrading the Microsoft.Azure.WebJobs.Extensions.ServiceBus to 5.120. 0.

Added the below value in Azure portal in the Configuration 
![Image](https://github.com/user-attachments/assets/129c4704-e65a-47a2-bc95-2bc12df990c9)

**Comment by bhagyshricompany** [comment]
Hi @Sirishapujari  hopes its working fine .hence closing here.
