### ISSUE TITLE
Overwrite Unsupported Write-* Functions Using Bootstrapper

### ISSUE THREAD

**Issue by jdkang** [Azure/azure-functions-host#1078]
Currently, `Write-Output` is the main equivalent to `log.Info()` for `.ps1` Azure Functions -- which writes to the console. However, this is not intuitive given one's inclination to use commands like `write-host` and `write-verbose`.

### Suggestions
Use a bootstrapper that (at a minimum) overrides `write-host`/`write-verbose`/`write-debug` to `write-output`. An alternative is to use "system messages" in a similar vein as to how [Octopus Deploy's agent bootstraps powershell](https://github.com/OctopusDeploy/Calamari/blob/master/source/Calamari/Integration/Scripting/WindowsPowerShell/Bootstrap.ps1).

**Comment by davidobrien1985** [comment]
I'd prefer to rather have this documented than have an application mess with my code (even if my code is wrong!).
What I might accept is something that parses the code upon change and spits out an error saying something like 'unsupported cmdlets detected'. Then again, they're not "not supported", those streams just don't make it to the console output.
So, maybe the host could also show those output streams?
