### ISSUE TITLE
CLI: appsettings.json contents is not being loaded?

### ISSUE THREAD

**Issue by jsiegmund** [Azure/azure-functions-host#1085]
I'm debugging a Bot Service instance, running locally in the functions cli. I downloaded the appsettings.json file from the online instance, which was neatly copied into appsettings.json locally. When I run "func settings", it shows the correct output. Here is the output with a very simple (test) appsettings.json: 

> E:\Sources\github\bots-test>func settings list
>    -> Name: AD_CLIENT_ID
>       Value: *****
> 

But now when I run the function (debug) in VS, and I have this line: 

`var test = System.Configuration.ConfigurationManager.AppSettings["AD_CLIENT_ID"];`

that gives `null`. This seems so trivial that I'm completely lost on what is happening here. I've used the app settings in other functions before in the exact same way, never had any issues. Also tried decrypting the file first, nothing. So what could I be overlooking?

**Comment by paulbatum** [comment]
@jsiegmund As far as I'm aware, the contents of the "appsettings.json" file is not actually loaded into ConfigurationManager.AppSettings. This is somewhat counter-intuitive. I would use the environment variables API. See [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#environment-variables) for a quick example.

**Comment by mathewc** [comment]
Note: we've recently moved the CLI to another repo https://github.com/Azure/azure-webjobs-sdk/issues/804. This issue should be moved there.
