### ISSUE TITLE
Node-inspector debugging for node functions

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-functions-host#1096]
Add debugging for node code.

- EDGE_NODE_PARAMS allows node command line options
- --inspect option launches node inspector

Figure out how to surface the debugger to the user ¯\\_(ツ)_/¯

**Comment by christopheranderson** [comment]
Can't you add this as App Settings today?

**Comment by mamaso** [comment]
EDGE_NODE_PARAMS can be added as an app setting yes, but then getting a view for inspector is not possible afaik (we're not following the existing iisnode path)

**Comment by mamaso** [comment]
Played with this a bit, the --inspect option doesn't play well with v6.5.0 and edgejs at present

**Comment by mhoeger** [comment]
Issue stale - work is done (hi Matt!!)
