### ISSUE TITLE
Strange behavior with Entity Framework

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#1114]
Need to investigate issues preventing EF from loading the expected providers when running in Azure Functions.

The issue seems to be triggered by configuration changes (App Setting/Connection strings) changes, causing the site to get in a bad state when it restarts. A full site restart seems to bring the site to a good state.

One of the issues we've observed is that it seemed like EF was attempting to load a previous version of the function assembly, potentially from a cached model.

**Comment by DibranMulder** [comment]
I can't reproduce this issue with EF Core and Azure Functions V2. Guess this is not relevant anymore.

**Comment by fabiocav** [comment]
It isn’t, this really applied to EF on full framework and V1, but closing this as this scenario has been addressed in V2

Thanks!
