### ISSUE TITLE
Let me choose my version of PowerShell

### ISSUE THREAD

**Issue by theMichaelB** [Azure/azure-functions-host#1144]
As the title says really! 

I'm using Functions as an alternative to Automation (because of the simple interaction with queues etc) but the fact that it is running such an old version of Azure PS is being frustrating (especially with regards to tags) 

Is there a way to upgrade Azure PS?

**Comment by christopheranderson** [comment]
This isn't possible today - I've editted the title to track this as a feature request.

**Comment by theMichaelB** [comment]
Would that include which version of Azure PS as well? (having the rest of the Azure modules would be nice too - Service Fabric, AD, etc) It could make Functions a really useful management platform (Automation has the same failings)

**Comment by tohling** [comment]
You can bring your own version Azure PowerShell.  The approach is mentioned in this thread.

https://github.com/Azure/Azure-Functions/issues/124

**Comment by paulbatum** [comment]
Closing this as I think everything relevant is tracked in https://github.com/Azure/Azure-Functions/issues/124
