### ISSUE TITLE
Cannot use Sql.Geography

### ISSUE THREAD

**Issue by JonCanning** [Azure/azure-functions-host#1176]
Please provide a succinct description of the issue.

When retrieving geography data from SQL database, the following error is logged

`2017-02-02T22:41:34.232 Exception while executing function: Functions.Test. mscorlib: Exception has been thrown by the target of an invocation. mscorlib: Could not load file or assembly 'Microsoft.SqlServer.Types, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.`

Provide the steps required to reproduce the problem

Create a database with a column containing geography data

```
#r "System.Data"

open Microsoft.Azure.WebJobs.Host
open Microsoft.SqlServer.Types
open System.Data
open System.Data.SqlClient

let run(msg : string, log: TraceWriter) =
  let connectionString = "connectionstring"
  let sqlConnection = new SqlConnection(connectionString)
  sqlConnection.Open()
  let sql = "SELECT TOP(1) geography from dbo.table"
  let command = new SqlCommand(sql, sqlConnection)
  let dataReader = command.ExecuteReader()
  dataReader.Read()
  dataReader.GetValue 0
  ()
```

```
{
  "frameworks": {
    "net46": {
      "dependencies": {
        "Microsoft.SqlServer.Types":"*"
      }
    }
  }
}
```

#### Expected behavior

Sql.Geography type is returned

#### Actual behavior

Exception thrown

**Comment by euangordon** [comment]
I have found a [way](https://stackoverflow.com/a/48284226/8626861)to load the SQL Server Types, which is allowing me to read geography data:

**Comment by fabiocav** [comment]
Closing this as this should be resolved.
