### ISSUE TITLE
Requests to webhooks with incorrect code fails with 400 instead of 401

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-functions-host#1214]
With regular http functions, we correctly get a 401. But with WebHooks, we end up with a 400.

I'm guessing it relates to the auth happening inside the WebHooks SDK instead of our own logic. But regardless, it's not correct.

**Comment by mathewc** [comment]
Yes this error isn't coming from us, its coming from the webhooks library. I'm sure some design thought was given to why that is a 400 and not a 401. @HenrikFrystykNielsen any comment? I'm not sure it would be worth it for us to try to change this via parsing of error messages.
