### ISSUE TITLE
Configure/Remove Standard .NET headers

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#1237]
Currently by virtue of the Functions runtime being an ASP.NET WebAPI app, a bunch of standard headers are added on all responses. See SO post here: https://stackoverflow.com/questions/42445686/access-azure-function-runtime-settings.

We should see if there is a way we can make this configurable for Functions users.

**Comment by AranVinkItility** [comment]
Agreed. This should be a configurable option.

I have managed to remove some of these using Extensions, but the X-AspNet-Version remains. See the issue I raised on Azure Functions GitHub for more information: https://github.com/Azure/Azure-Functions/issues/290#issuecomment-302278834

**Comment by mathewc** [comment]
Fixed

**Comment by mathewc** [comment]
https://github.com/Azure/azure-webjobs-sdk-script/commit/8e05f36e2001a0e5c5c7257163bfe8c10e418a8f disables the x-aspnet-version header, but there are still other headers remaining so leaving this bug open.

**Comment by soluto-yoav** [comment]
Tried removing the "X-Powered-By" header using both extensions mentioned in [Azure/Azure-Functions#290](https://github.com/Azure/Azure-Functions/issues/290#issue-229036760), and neither worked for me.
I'm using a bare-bones function for simplicity's sake:
```
module.exports = function (context, req) {
    context.res = { body: "hello" };
    context.done();
};
```
Is there anything to do beyond simply installing the extensions?

**Comment by alexandergs** [comment]
Is there any plan to allow removing additional headers? I am specially interested in the X-Powered-By and Server headers as most security code scanner raise flag for those.

**Comment by alexandergs** [comment]
There is an extension called Remove Custom Headers that works for Web Apps but not for functions that have the Consumption Hosting Plan. So, what you can do is: 
1. Create a regular Web App 
2. Create a function and make sure you use the same Hosting Plan as the Web App (do not use Consumption). 
3. Once the function is created, install the extension named: "Remove Custom Headers" 
4. Restart the function and the headers (Server and X-Powered-By) should disappear.

**Comment by haiquan** [comment]
Security tool also recommand to remove the following response headers.

- Server
- X-Powered-By

**Comment by tomvanenckevort** [comment]
I tried removing the Server and X-Powered-By headers by applying an applicationHost.config transform to the Functions app, as described [here](https://github.com/projectkudu/kudu/wiki/Xdt-transform-samples).
My transform file looks like:
```
<?xml version="1.0"?> 
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform"> 
  <system.webServer>
    <httpProtocol>
      <customHeaders>
        <add name="X-Powered-By" xdt:Locator="Match(name)" xdt:Transform="Remove" />
      </customHeaders>
    </httpProtocol>
    <security>
      <requestFiltering removeServerHeader="true" xdt:Transform="SetAttributes(removeServerHeader)" />
    </security>
  </system.webServer>
</configuration>
```
I can see that the transform was succesful by checking the updated applicationHost.config file through the Kudu console of the Functions app, but my function responses still includes both of the headers.

**Comment by sandeepnmenon** [comment]
+1
I am not able to remove server header and other headers injected by the IIS Server. Tried the "Remove Custom Headers" site extension as mentioned in [comment](https://github.com/Azure/azure-functions-host/issues/1237#issuecomment-406341047)


> There is an extension called Remove Custom Headers that works for Web Apps but not for functions that have the Consumption Hosting Plan. So, what you can do is:
> 
> 1. Create a regular Web App
> 2. Create a function and make sure you use the same Hosting Plan as the Web App (do not use Consumption).
> 3. Once the function is created, install the extension named: "Remove Custom Headers"
> 4. Restart the function and the headers (Server and X-Powered-By) should disappear.

For azure serverless function deployments, I need to remove them to be compliant with Microsoft's security protocols before deployment
