### ISSUE TITLE
Improve trigger sync behavior, perhaps on host startup

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-host#1300]
There are number of ways to edit/deploy function.json that result in triggers not being synced to the scale controller. I've listed them here so that we improve our documentation: https://github.com/Azure/Azure-Functions/issues/210

A better approach is for the host to know about the last time it synced with the scale controller (e.g., hash of function.json).

**Comment by mathewc** [comment]
Closing in favor of https://github.com/Azure/azure-functions-host/issues/3565
