### ISSUE TITLE
Visual Basic .NET support

### ISSUE THREAD

**Issue by johnnliu** [Azure/azure-functions-host#1360]
Please provide a succinct description of the issue.

I think there is great value to add Visual Basic support to Azure Functions.

* VB2017 https://blogs.msdn.microsoft.com/vbteam/2017/03/30/whats-new-in-visual-basic-2017/ has several features that aren't in C# - more languages the merrier.
* Functions is language neutral anyway - this demonstrates we are serious about embracing all things.  VB.NET should be up here with C# and F# 
* For traditional VSTO/VBA programmers building Access applications this can fast track them onto PowerApps with AzureFunctions
* VBTeam blog was relaunched Jan 2017 and there is a determined story to tell   https://blogs.msdn.microsoft.com/vbteam/2017/01/31/relaunching-the-visual-basic-team-blog/
* Have a chat with Anthony Green - I'm sure he'd be interested https://twitter.com/ThatVBGuy

**Comment by christopheranderson** [comment]
We should be able to support this via the precompiled approach. We are missing docs/etc. for "full support", but it should just work today.

**Comment by johnnliu** [comment]
hmm I might have a weekend project now.

**Comment by lindydonna** [comment]
@johnnliu I've reached out to Anthony Green (I know him quite well), and he'll see if there are ways that the VB team can partner with us on this.

You should indeed use the precompiled approach, outlined in https://aka.ms/precompiled-functions.

**Comment by johnnliu** [comment]
https://twitter.com/johnnliu/status/849643313942609920 

Oh we are going to have a lot of fun.


    Imports System.Net
    Imports System.Net.Http
    Imports System.Threading.Tasks
    Imports System.Runtime.CompilerServices
    Imports System.Web.Script.Serialization

    Public Class MyFunction

    Public Shared Async Function Run(ByVal req As HttpRequestMessage) As Task(Of HttpResponseMessage)

        'parse query parameter

        'Dim name = req.GetQueryNameValuePairs()
        '.FirstOrDefault(q >= String.Compare(q.Key, "name", True) == 0)
        '.Value;

        'Get request body
        Dim Data As String = Await req.Content.ReadAsStringAsync()

        'Set name to query string Or body data
        Dim json As Dictionary(Of String, Object) = New JavaScriptSerializer().Deserialize(Of Object)(Data)
        Dim name = json.Item("name")

        Dim response As HttpResponseMessage = New HttpResponseMessage()

        If name Is Nothing Then
            response.StatusCode = HttpStatusCode.BadRequest
            response.Content = New StringContent("Please pass a name on the query string or in the request body")
        Else
            response.StatusCode = HttpStatusCode.OK
            response.Content = New StringContent("Hello " & name)
        End If
        Return response
    End Function

    End Class

**Comment by johnnliu** [comment]
Can we tell VBTeam that HttpRequestMessageExtensions don't work and it's really hard to do things like req.GetQueryNameValuePairs() from query string...  

Also, VB really should have JSON literals like they have XML literals...

**Comment by johnnliu** [comment]
![image](https://cloud.githubusercontent.com/assets/1279372/24713468/1c8d234e-1a69-11e7-9c18-1422c155b1df.png)

solution structure.

**Comment by AnthonyDGreen** [comment]
Look @johnnliu,

I'm not saying that we _should_ have JSON literals. Just that I have an implemented [prototype of JSON literals](https://github.com/AnthonyDGreen/roslyn/tree/features/vb-json) in my fork of Roslyn that I'd love some user feedback on... shhh, don't tell anyone ;)

**Comment by lindydonna** [comment]
I'm going to move this issue into the backlog, as the main work to do here is to create samples and documentation. I'll work with @AnthonyDGreen to partner on this.

**Comment by fabiocav** [comment]
This is supported with the pre-compiled model. Documentation applies, but we don't currently plan on providing samples and templates.
