### ISSUE TITLE
Drive binding metadata (Binding.Json) directly from Attributes 

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-functions-host#1416]
The SDK attributes have enough information to provide a skeletal Binding.json. 
This will enable the UI editor to show custom bindings. 

If anything is missing, we should consider if it should be added to the SDK attributes. For example, regex validation should be added since the runtime will need that anyways. 
 
We can consider if this can also be used for builtin bindings.

**Comment by fabiocav** [comment]
Done.
