### ISSUE TITLE
Azure function app event hub trigger is not executed as per their respective consumer group configuration 

### ISSUE THREAD

**Issue by kapilghimire** [Azure/azure-functions-host#1495]
In azure function app i am using multiple event hub trigger configured with different consumer group.
But each event hub function trigger  is running for every event that comes to Event hub, but not as per their respective consumer group .

Provide the steps required to reproduce the problem

1. create event hub with multiple consumer group

2.  create azure function app event hub trigger function to listen event to specific consumer group

#### Expected behavior

every event hub trigger function should run as per their consumer group

#### Actual behavior

every event hub trigger is running for every event that is coming to event hub not as per their consumer group configuration

**Comment by paulbatum** [comment]
We have identified the problem and we're working on rolling out a fix. Its likely to be available globally by end of May.

**Comment by paulbatum** [comment]
@kapilghimire The fix for this was deployed a few weeks ago. Can you confirm that consumer groups are now working as you would expect?
