### ISSUE TITLE
Improve OpenAPI definition generation

### ISSUE THREAD

**Issue by alexkarcher-msft** [Azure/azure-functions-host#1510]
Currently the API definition generation does not include any happy path that produces a complete API definition. I would like to add at least one path from a blank function to the API definition such that it produces a complete API definition.

**Comment by paulbatum** [comment]
@soninaren is going to try to hack together a basic prototype this month

**Comment by blandoe** [comment]
Any update on this?

**Comment by wobba** [comment]
I've spent around two workdays on an Azure function reflecting out a proper Swagger def for .Net. https://github.com/wobba/AzureFunction-SwaggerDefinition Needed it for a customer project and dows pretty much what Swashbuckle does. Might be missing pieces, but covers quite a bit for now.

**Comment by Narnain** [comment]
This is the missing link for amazing integration with tools such as API Management and needs to work for v2 Functions.  Supporting attributes such as ProducesResponseType, Produces, and Consumes would make a big difference.

**Comment by wobba** [comment]
Also take a look at https://devkimchi.com/2019/02/02/introducing-swagger-ui-on-azure-functions/ and the github repo for it https://github.com/aliencube/AzureFunctions.Extensions and the nuget package https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/
