### ISSUE TITLE
leaked application settings between app service deployment slots?

### ISSUE THREAD

**Issue by jamesdixon** [Azure/azure-functions-host#1560]
_context: I'm running a handful of functions on an App Service instance. I have two deployment slots: the primary and another called staging. Running Node 7.10 on my App Service instance. Functions runtime 1.0.10917_

On a couple of occasions, I've run into some very odd behavior (one which is discussed in #1246) where it appears that functions/webjobs running on the same schedule, in differently deployment slots, appear to be leaking application settings.

For example, the most recent issue I ran into was with a payment processing job that essentially runs through and charges customers for services rendered. I woke up to find that my customers were sent two emails: 

1) That there payment was successfully processed
2) That there payment failed

It's not uncommon to have a failed payment, but the issue here is that each customer was sent two emails for a single transaction. The transaction should either succeed or fail, not both. When I looked into the webjob log, indeed, the job only ran once on the production slot. However, it also ran on the staging slot as well. Given that it's the same job, on the same schedule, just pointing to a different database, this was expected.

The second part of this that was fishy was that in the email for the failed payments, we show the user the reason for failure, which is usually something from the payment processor. In this case, it was the following error message:

```
error: insert into "transaction" ("amount", "business_id", "entity_id", "entity_type", "kind", "type", "user_id") values ($1, $2, $3, $4, $5, $6, $7) - duplicate key value violates unique constraint "transaction_pkey"
```

The `insert` being referenced here occurs after a payment succeeds from our payment processor; we add a payment transaction to our own log. The interesting thing about the above statement is that while it cites a duplicated primary key violation, you'll notice that the primary key isn't something we've generated and tried to insert -- it's assigned from the sequence. From what I've read, it seems that this is due to a race condition where two inserts have tried to run simultaneously.

This seems to point to the webjob running two instance simultaneously. The only thing I can think is that somehow that the two identical jobs in different deployment slots were somehow using the same application settings even though they are clearly different.

That said, I want to point out a couple of important facts:

1. This particular job has been running for months without any major issues. The last time something like this happened was discussed in #1246.

2. I had just done a environment swap a couple of hours before all of this happened.

I'm hoping someone might be able to give me some insight on how the functions runtime works within the context of using it directly on an App Service instance rather than as a Functions app. But more importantly, is the scenario I described above something that others have encountered? If not, is it a possibility? 

I'm really at a loss and this issue has caused a lot of problems that have made customers unhappy and resulted in a lot of lost time trying to clean up.

Thank you in advance for your help!

**Comment by jamesdixon** [comment]
:bump:

Anyone have any insight on this?

**Comment by paulbatum** [comment]
Its difficult for us to reason about what is happening here because of your unusual setup. We would at least have a bunch of logs on our side if you were running in a Function App. I understand that this issue does not repro reliably, but can you try to somehow repro from a normal function app?

**Comment by jamesdixon** [comment]
Thanks for the reply, Paul!

When you say that my setup is unusual, are you referring to the fact that I'm using the runtime as part of my app service instance?

Do you feel like I might gain some better stability and logging facilities if I moved to a functions app?

**Comment by paulbatum** [comment]
Yeah I'm referring to the fact that you're not using a Function App. We have systems that collect logs and telemetry for Function Apps and these help us troubleshoot problems, and potentially there are more variables in play when you are reusing the runtime code yourself. Its just really difficult for us to make headway on this type of problem given your current config.

Any thoughts on what a minimal repro would look like? What if you created a brand new function app with app insights enabled, added a timer trigger that logs the value of a sticky app setting, and then set up a slot with a different value of that app setting and then let them run for a week or so, swapping often? You could then query your logs in app insights for any log entries that appear to have ran in stage but used the prod setting or vice versa. If it repros in that configuration we'd have something very concrete to investigate.

**Comment by jamesdixon** [comment]
Great to know. Do you feel that in the future, using the runtime in an App Service instance will be deprecated?

As for reproducing, that sounds like a good plan. I'll create both a functions app and a plain app service instance with some custom logging to see if anything changes.

I realize the situation seems a bit bizarre and most certainly an outlier, but I swear I'm not crazy 😄

**Comment by paulbatum** [comment]
Apologies for being glib, but for something to be "deprecated" it first has to be "supported" 😈 . But let me be clear to avoid any confusion - we absolutely intend to continue supporting Function Apps on dedicated app service plans. What we don't officially support is grabbing our code or our binaries and running it yourself. But its open source so we're not going to stop you, and when its not particularly onerous we'll do our best to make sure you're still successful.

**Comment by jamesdixon** [comment]
Fair enough!

I suppose my confusion comes from the fact that as far as I can tell, it isn't clear whatsoever that using the binaries isn't a supported method. For example, this repo's wiki goes through [using the method I use as a deployment option](https://github.com/Azure/azure-webjobs-sdk-script/wiki#deployment). Not being snarky by any means, but it would be good to make this more clear if this method of usage indeed is not supported.

I actually started using this SDK before Functions apps were considered a thing (publicly) and was pointed to this repo as a way to use the various storage bindings, etc within my app service as Webjobs. That said, I am now officially confused when it comes to the difference between a webjob and function 😄 Are Webjobs being sunsetted as well?

**Comment by paulbatum** [comment]
By "officially support" what I'm really referring to is that if you were paying for Azure Support, whether you could file a ticket about an issue when running in this configuration. 

I can understand your confusion. The line between webjobs and functions can be blurry sometimes. Let me try to clear it up.

Nothing is being sunsetted. We continue to support webjobs. None of what I'm communicating here is a change in direction. One obvious difference between the functions packages and the webjobs packages is that the functions packages are still pre-release. There is no RTM release of those packages. For an example, see [here](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Script.WebHost/).

**Comment by jamesdixon** [comment]
Thanks for the clarification on support!

That said, I'm still a little hazy on the difference between webjobs and functions. Can you discuss any other significant difference?

Thank you!

**Comment by paulbatum** [comment]
This might help:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-compare-logic-apps-ms-flow-webjobs

**Comment by fabiocav** [comment]
Closing as answered/stale.
