### ISSUE TITLE
.NET Core migration

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#1576]
Opening this issue to track the work and discussions around the .NET Core/.NET Standard migration.

Work is currently in progress and will move through the various repositories, ultimately moving into the Azure Functions runtime (WebJobs Script): WebJobs SDK -> WebJobs extensions -> WebJobs Script.

The primary goal of this work, at least initially, is to enable x-plat (Windows, macOS, Linux) support for tooling (CLI/Core Tools, dev tools, etc.) and address on-prem requirements with Azure Functions Runtime.

**Comment by paulbatum** [comment]
@fabiocav can you expand this one with more detail or links to additional issues?

**Comment by fabiocav** [comment]
Will be linking issues back to this as I create them

**Comment by ColbyTresness** [comment]
@fabiocav is this still open for a reason?

**Comment by fabiocav** [comment]
No reason. I believe we had a duplicate. Closing as the work is completed.
