### ISSUE TITLE
Quota not "quota-ing"

### ISSUE THREAD

**Issue by NSTA1** [Azure/azure-functions-host#1578]
I have a (hobby) Azure Functions App which does a bunch of calculations every day and stores the results in table storage.  Because it's just for fun, I put a quota on the site to just use the free compute.

I recently modified the host.json to this (hoping to reduce the number of file write operations):

```
	"tracing": {
      "consoleLevel": "info",
      "fileLoggingMode": "never"
    }	
```

and it seems that the quota isn't kicking in... are those log entries what are used to calculate the usage for the quota ? ....    I'm going to disable the timer function which kicks this off for now.

**Comment by NSTA1** [comment]
I tested this again today, quota set to 28500 gbs and the app ran from 8am to 4pm using between 3 and 5 servers (64 bit) running at 60 to 80% CPU and about 120mb of memory (those numbers from the live metric feature of app insights)... App only stopped when I told it to.

**Comment by christopheranderson** [comment]
Would you please share your Function App with us? You can give us the name or just an (invocation id, timestamp, region) and we'll find it. I'll get someone to look at the quota enforcement logs for your app.
