### ISSUE TITLE
Using Python3 in Azure Python Functions

### ISSUE THREAD

**Issue by MartinPeschke** [Azure/azure-functions-host#1585]
Please provide a succinct description of the issue.

#### Repro steps

1. Create Python App Function

2. Observe it uses Python 2.7.8

3. Add runtime.txt with content: python-3.4 (python 34 being already pre-installed)

#### Expected behavior

Should use Python 3.4

#### Actual behavior

It still uses Python 2.7.8

#### Known workarounds

I tried to get python3 running largely because the docs suggested it would work, and I am trying to get azure-storage sdk to work with Azure Python Functions.

On 2.7.8 it however only returns 
```
from azure.storage.blob import BlockBlobService

  File "D:\home\site\wwwroot\AccountSink\run.py", line 7, in <module>
    from azure.storage.blob import BlockBlobService
  File "../pylibs\azure\storage\__init__.py", line 21, in <module>
    from .models import (
  File "../pylibs\azure\storage\models.py", line 27, in <module>
    from cryptography.hazmat.primitives.keywrap import(
  File "../pylibs\cryptography\hazmat\primitives\keywrap.py", line 12, in <module>
    from cryptography.hazmat.primitives.constant_time import bytes_eq
  File "../pylibs\cryptography\hazmat\primitives\constant_time.py", line 9, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by christopheranderson** [comment]
We don't yet support Requirements.txt for setting Python environment. We currently don't officially support running Python 3 with Azure Functions, today, but this is something we'll address when we move from Python Scripting (experimental) to a full Python Functions implementation.

**Comment by baizini** [comment]
Is there any timeline for full Python Functions implementation?

**Comment by JensMadsen** [comment]
Will it happen

**Comment by christopheranderson** [comment]
This discussion is best tracked in the new python worker. https://github.com/Azure/azure-functions-python-worker/issues/6
