### ISSUE TITLE
Cannot Add Package Reference via the Portal (Works as DLL or as uploaded from VS)

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-host#1598]
_From @MisterJames on June 14, 2017 2:19_

I am a package author and having a bit of trouble getting all my boxes ticked to say that my library works with Azure Functions.  I have a NuGet package that includes (with the latest release) a build for net46.  After adding the package to the Function via the portal I receive an error message and the Function can't compile.

### OS and Browser
Win 10/Edge

### Repro steps
Create a function (I used the `HttpTriggerCSharp` template) and add a `project.json` and a reference to GenFu 1.3.3.

```
{
  "frameworks": {
    "net46":{
      "dependencies": {        
        "GenFu": "1.3.3"        
      }
    }
   }   
}
```

### Error messages
There are four messages similar to this for all the types in `System.Net`:
```
'HttpRequestMessage' does not contain a definition for 'GetQueryNameValuePairs' and the best extension method overload 'HttpRequestMessageExtensions.GetQueryNameValuePairs(HttpRequestMessage)' requires a receiver of type 'HttpRequestMessage'
```

### Other Details
I have used the new VS 2017 tooling and added the GenFu package as a reference to an Azure Functions project and uploaded it to Azure, which works fine. 

Likewise, if I upload the DLL via Kudu I am able to reference the DLL, then `using` the namespace I can ultimately invoke library methods.

Is there something wrong with the way the compiler in the portal sees my NuGet package? Or is it the way I've got it packaged?

_Copied from original issue: Azure/azure-functions-ux#1466_

**Comment by lindydonna** [comment]
_From @MisterJames on June 15, 2017 19:34_

@ahmelsayed or @alrod, is this the right spot for this report/question, or should I move it to a different repo? Wasn't certain if it was a part of the UX-specific bits as it works locally, so open to suggestions.

**Comment by lindydonna** [comment]
_From @ahmelsayed on June 15, 2017 21:35_

it looks more like a runtime issue which technically should be opened over at https://github.com/Azure/azure-webjobs-sdk-script, but @fabiocav can confirm in the meantime.

**Comment by MisterJames** [comment]
@lindydonna thanks for moving this over!  

I am happy to test/try/experiment as required/requested, though I am about to go off-grid for the next 5 days.

**Comment by fabiocav** [comment]
Will be taking a look at this soon. Having the contents of your `project.lock.json` file may give us some interesting information, but I should be able to get that pretty easily with the repro steps you've provided.

**Comment by fabiocav** [comment]
Closing stale issue that has been addressed.
