### ISSUE TITLE
Azure functions and Login-AzureRmAccount

### ISSUE THREAD

**Issue by lzgrzebski** [Azure/azure-functions-host#1603]
Hello I'm struggling with Azure Authentication in Azure functions.
In my project I have 2 functions (powershell) + nodejs. 
In the first function I'm getting subscription from my account 

smth like (simplified):
```powershell
Login-AzureRmAccount -Credential $credentials
$subscriptions = Get-AzureRmSubscription
```
and then based on this article:  http://johnliu.net/blog/2017/6/azurefunctions-work-fan-out-with-azure-queue-in-powershell
Im sending each subscription separately to the queue (because the next step require a bit more time to finish and I was getting timeouts so I decided to split them)
smth like (simplified):
```powershell
$storeAuthContext = New-AzureStorageContext -ConnectionString $env:x_STORAGE 
$outQueue = Get-AzureStorageQueue –Name 'x' -Context $storeAuthContext

foreach($country in $config.countries) {
    $queueMessage = New-Object `
    -TypeName Microsoft.WindowsAzure.Storage.Queue.CloudQueueMessage `
    -ArgumentList (ConvertTo-Json -Depth 100 $country)
    $outQueue.CloudQueue.AddMessage($queueMessage)
}
```
I used the explicit connection instead of built in bindings because then I can send multiple messages to the queue..

then in the next function I added queue trigger
```json
{
    "bindings": [
        {
            "type": "queueTrigger",
            "name": "name",
            "queueName": "queueName",
            "connection": "x_STORAGE",
            "direction": "in"
        }
    ],
    "disabled": false
}
```

Everything works so far but in the second function Im getting information about web certificates so Im again login to azure selecting subscription and getting information about cerrificates

smth like (simplified):
```powershell
Login-AzureRmAccount -Credential $credentials

 $ctx = Get-AzureRmContext

if($ctx.Subscription.SubscriptionName -ne $name) {
    Set-AzureRmContext -SubscriptionName $name -ErrorAction:Stop
}

# get all registered certs
$certs = Get-AzureRmWebAppCertificate -ResourceGroupName $c.resource_group
        
# get certs registered in apps
$bindings = Get-AzureRmWebAppSSLBinding -ResourceGroupName $c.resource_group -WebAppName $c.app
```

Problem is for me sometimes seems like this is somehow cached and Im getting smth like this:
"The Resource 'x" under resource group 'x' was not found."

Im thinking maybe its beacuse when the second function is running in parralel then functions are using somehow the same auth session and then its trying to get website from the wrong resource group, because when Im slicing first function to only send one subscription then everything works fine..

**Comment by christopheranderson** [comment]
@tohling - Is it possible that the Azure Login state is getting overwritten by concurrent executions? Do we isolate runspaces?

**Comment by tohling** [comment]
@lzgrzebski, the PowerShell Functions are executed within their own runspaces, however, there might be an bug with the auth session.  If possible, could you isolate the Functions into 2 separate Function Apps and see if the issue goes away?

**Comment by lzgrzebski** [comment]
I would rather not split it more since I already separated this code from our main repo...
And I think it happen when the 2nd functions is running in parallel so we can have the same issue when we will divide 1 and 2 function into separated apps. I found a workaround for now (it slowing down a bit execution, but in this case its not a big deal - Im setting up batchSize of the queue to 1 so the second function is invoked multiple times, but run in more kind of controlled way, almost one after another, and problem seems to be gone...)

**Comment by adamwebbcollabware** [comment]
@tohling would you please be able to provide any insight into the issue (#1827) linked by @ahmelsayed. Even just some guidance so that I can make a decision if I should switch to Azure Automation in the interim. Thanks.

**Comment by tohling** [comment]
@adamwebbcollabware, PowerShell support in Azure Functions is in experimental stage and there are plans to revamp the experience in the near future.  In the meantime, kindly switch to Azure Automation for production scenarios.

**Comment by adamwebbcollabware** [comment]
@tohling Thanks for the clarification. Real shame as we've been using the webhook functionality of Azure Functions to respond to API requests and provide a JSON response, but Azure Automation does not appear to offer this functionality.

**Comment by mguirao** [comment]
Do you have any update about this issue ?
I experiencing the same behavior in my function when concurrent execution occurs.

**Comment by asavaritayal** [comment]
@mguirao PS support for the v2 runtime is still on the cards. We're partnering with the PowerShell team at Microsoft to determine the right approach and timeline for this feature. Unfortunately, I don't have an ETA to share at the moment.

**Comment by mguirao** [comment]
@asavaritayal Would that change anything if i switch to the "Beta" runtime ?

**Comment by mguirao** [comment]
As a temporary solution i have replaced all module commands by Rest API call to https://management.azure.com. 
That way i'm not using modules anymore, so no session conflict.

**Comment by HiltonGiesenow** [comment]
I think I'm seeing this too, having a Flow on a SPO document library calling an Azure PS function - when I update multiple list items at once, the Functions start stepping on each other's toes. It looks like simple variables are being shared across session executions

**Comment by HiltonGiesenow** [comment]
@mguirao it doesn't seem to run at all if you switch to "Beta" runtime - the function test page gives a 404. Also, if you create a new function app in beta, PowerShell's not available at all - I'm guessing this is what  @asavaritayal means about "still on the cards". Wondering if there's possibly any update?

**Comment by Francisco-Gamino** [comment]
Hello @lzgrzebski,

PowerShell in Azure Functions GA-ed on November 2019, and it is available in both V2 and V3. For more information, please see https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-powershell. 

By default, Managed Dependencies is enabled, so in the first function invocation we install the `Az` module which contains all the Azure modules. After, you can enable the MSI (https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=dotnet) to authenticate with Azure.

If you feel that something is missing for PowerShell in Function or you run into any problems, please open an issue at https://github.com/Azure/azure-functions-powershell-worker. Closing this issue.
