### ISSUE TITLE
Default eventhubs batchsize is incorrect

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#1629]
The default batchsize for eventhubs in Azure Functions is supposed to match the defaults that were changed in webjobs in [this commit](https://github.com/Azure/azure-webjobs-sdk/commit/2b36f4ff030b3e86ae18219976ef22742cc56eaa#diff-c3a25b906e46c6a4578e8dc6cc9d1887). However in practice these defaults are not honored. This results in the default batchsize being passed to event hub as 1000, and I think that then converts into 300 somehow (might be related to prefetch).

The configuration code needs to be fixed to allow the defaults specified by webjobs to take effect unless the user overrides them.

**Comment by mathewc** [comment]
@paulbatum can this issue be closed?

**Comment by paulbatum** [comment]
Yes.
