### ISSUE TITLE
Nuget.org package Microsoft.Azure.WebJobs.Script 1.0.0-beta3 is not up to date

### ISSUE THREAD

**Issue by KaiWalter** [Azure/azure-functions-host#1634]
I'm trying to use the Microsoft.Azure.WebJobs.Script Nuget package to create a Service Fabric Application Functions Hosts. For that I transformed WebJobs.WebHost and use the same dependencies.

I have problems getting the build successful. Microsoft.Azure.WebJobs.Script.Eventing seems not to be included in the Nuget package version available @nuget.org.
However when I create a package from this repo master branch I get a Microsoft.Azure.WebJobs.Script 1.0.0-beta3 including the above mentioned namespace.

As a workaround I installed it from local source
update-Package Microsoft.Azure.WebJobs.Script -Version 1.0.0-beta3 -Source C:\...\azure-webjobs-sdk-script\src\WebJobs.Script.NuGet\bin\Debug\NuGet

**Comment by christopheranderson** [comment]
This needs to get added to the release process. Also need to add WebHost to Nuget.

**Comment by KaiWalter** [comment]
not relevant anymore
