### ISSUE TITLE
Investigate why outbound HTTPS defaults to TLS 1.0

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#1639]
Make a function app with the following code:

```csharp
using System.Net;

public static async Task<HttpResponseMessage> Run(HttpRequestMessage req, TraceWriter log)
{
    log.Info("Security protocol: " + System.Net.ServicePointManager.SecurityProtocol.ToString());
    using(var client = new HttpClient())
    {      
        var result = await client.GetAsync("https://www.howsmyssl.com/a/check");
        return result;
    }
}
```

Run the function and the log output you get will show `Security protocol: Ssl3, Tls
` and the response from howsmyssl will contain `"tls_version":"TLS 1.0"`.

If you take the equivalent code, put it into a ASP.NET web application and deploy it to the same app service plan as your function app and run it, the response from howsmyssl will contain `tls_version":"TLS 1.2"`.

It appears there is something about the functions runtime that changes the `ServicePointManager.SecurityProtocol` setting. We should find out what it is and evaluate whether this can be safely changed (perhaps as a breaking change in the next major version).

**Comment by devpab** [comment]
Noticed the behavior myself also and saw that the function still runs on .net 4.6.1. I think .net 4.6.2 added TLS 1.1 and 1.2 to be used by default, so maybe the asp.net version simply runs on a newer framework?

**Comment by paulbatum** [comment]
@devpab Functions runs on the version of .NET 4.x that is installed on App Service, which is currently .NET Framework 4.7. The version targeted by the project itself does not impact this behavior. This is easily confirmed by writing an ASP.NET application that targets 4.6.1 and deploying it to app service. You'll get TLS 1.2 in that case.

**Comment by davidebbo** [comment]
A user ran into this here: https://social.msdn.microsoft.com/Forums/azure/en-US/ee89e21b-edb2-4013-a6f0-066f3a4817aa/error-after-deploying-to-azure?forum=AzureFunctions

The specific error is:

> Exception while executing function: Functions.MyFunc. Microsoft.Azure.WebJobs.Script: One or more errors occurred. mscorlib: An error occurred while sending the request. System: The underlying connection was closed: An unexpected error occurred on a send. System: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. System: An existing connection was forcibly closed by the remote host.

The workaround is to set:

    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

**Comment by paulbatum** [comment]
I've confirmed that functions v2 behaves as expected. The output from howsmyssl for the above code snippet contains: `"tls_version":"TLS 1.2"`. 

Considering that this is resolved in v2 and we don't know how to fix this for v1 in a non breaking way, it might make sense to close this issue.

**Comment by fabiocav** [comment]
Given that we have a workaround and this works as expected in 2.0, I agree.

**Comment by paulbatum** [comment]
Closing as won't fix for functions v1, fixed for functions v2.

**Comment by davidebbo** [comment]
As we found in https://stackoverflow.com/questions/48543315/proxy-breaks-when-forwarding-to-github-pages, the workaround can't be used for Proxies because you have no easy place to change the protocol.

The plan is to support a new App Setting that will change the protocol used for the Function App. This way, we don't take the chance of regression any v1 scenarios that may be relying on SSL.

**Comment by paulbatum** [comment]
The target framework of function apps was [updated to 4.7.1](https://github.com/Azure/azure-functions-host/commit/d74bd513283412f84896111f1cb6088b2f49e9bf) which changed this behavior. As a result, TLS 1.0 is no longer the default. Closing.
