### ISSUE TITLE
Allow special characteres in the url path of the function

### ISSUE THREAD

**Issue by rodolZ80** [Azure/azure-functions-host#1642]
When I use a special character inside the path of the function, it returns a 404 Not Found

Example:
Route template
service/v1/users/{user_id}

Request:
https://xxx.azurewebsites.net/service/v1/users/%2B555984567    

// %2B => '+' 

Response: 404 Not Found

(Chris: updated to make more clear)

**Comment by paulbatum** [comment]
Do you have proxies enabled? There is a known issue that will be fixed in a few weeks related to encoded characters in the URL when proxies is turned on.

**Comment by rodolZ80** [comment]
No, I have proxies off.

**Comment by microsoft-rorezend** [comment]
@paulbatum this is also affecting me.  Running functions v2 (Runtime version: 2.0.12246.0)

Any plan to support encoded URI components as part of the Azure Function URI?
I mean the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

Running in an environment POST is not an option.

**Comment by JohnReeson** [comment]
Fixed in #3916
