### ISSUE TITLE
Compiler failures should halt queue processing

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-host#169]
**Repro steps**:
1. Create a queue-triggered C# script which doesn't compile
2. Load up the queue with messages

**Observation**:
The host reads as many messages as it can and they all fail immediately and repeatedly until all the messages gets placed into the poison queue.

**Expectation**:
Since the script doesn't even compile, there is no chance that any message would succeed.  It's wasteful to try to do all the processing, logging, metering, and moving messages into the poison queue.  Instead, it would be better if we stopped queue processing until the script was fixed.

**Comment by davidebbo** [comment]
Agreed that a hopelessly broken function should conceptually be treated as disabled.

**Comment by fabiocav** [comment]
Agreed. This is something we can do relatively easily for C# functions. 
Currently, you'll also run into the same issue with the other languages.

**Comment by mathewc** [comment]
I'll take a look at this and come up with a plan of action - then we can decide if it meets the bar. We need the function to remain invokable via portal UI, but turn off automatic trigger. We have that capability.

**Comment by davidebbo** [comment]
At this point, I'm leaning toward doing this post-beta. We can live with this for now IMO.

**Comment by mathewc** [comment]
Yes, this would likely require a bit of work. We basically have to ensure we precompile the script before generating the SDK IL wrapper (for node, compile means pass the script to Edge). If there are any errors,  we generate the wrapper with the `[NoAutomaticTrigger]` attribute, same as we do now when the user has Disabled the function.

For other language types (e.g Python, BAT, F#) we can't precompile to determine if the script is bad.

**Comment by fabiocav** [comment]
For C#, this is a bit simpler at the moment since we already precompile, but I still think this is a post-beta item.

**Comment by mathewc** [comment]
On further thought, I don't think this issue is constrained to just functions that don't compile. Consider a function that compiles, but has a permanent logic error in it (e.g. a null ref) that causes all invocations to fail. You have the same issue there.

Thus, I really think this issue is best resolved in the core SDK, perhaps a feature to specify the number of consecutive failures to allow before stopping the job function (in SDK terms). A feature like that would be useful to SDK users as well.

**Comment by davidebbo** [comment]
Makes sense.

**Comment by fabiocav** [comment]
Agreed. Ideally, we'd have a back off strategy leading up to fully suspending execution to account for transient issues.

**Comment by christopheranderson** [comment]
RC Justification: This is important for our quality/reliability. It doesn't seem healthy to have a function go haywire when it is broken.

**Comment by mathewc** [comment]
As I mentioned above, this would be core SDK work. I honestly haven't heard many people complain about the behavior we have now, but I agree that we could improve. I don't think this is needed for RC though - we've never had it for the SDK and that has been RTM for a couple years.

**Comment by christopheranderson** [comment]
I'll back it out. We can make a call at our next triage.

**Comment by fabiocav** [comment]
Closing this as a stale issue. This hasn't come up in a while and we can revisit if demand increases.
