### ISSUE TITLE
Create an API that lists URLs of all functions

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-host#1691]
For scenarios such as the Azure CLI, there needs to be an API on the Script host or Kudu to provide the URLs of all Functions. 

Once this is done, ideally we would remove the portal logic that does this manually so that we don't have duplicated code.

**Comment by lindydonna** [comment]
CC @yugangw-msft

**Comment by fabiocav** [comment]
If this can wait, we'll have a very smooth path to expose this in 2.x (.NET Core)

**Comment by lindydonna** [comment]
@fabiocav Yes, this can wait. Let's do it in the Core branch only.

**Comment by paulbatum** [comment]
Resolved by https://github.com/Azure/azure-functions-host/pull/3219

The property InvokeUrlTemplate is part of the response when getting the function definition. Its a template because it might contain route params.
