### ISSUE TITLE
Binding errors should be detected at compile time

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#174]
With C# right now, you can't bind a httptrigger to a stream. Fine. But at compile time, I'm told that the compilation is successful. Its only when I invoke the http trigger that I get the following error:

`2016-03-26T00:55:08.908 Exception while executing function: Functions.HttpTriggerCSharp1. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'req'. Microsoft.Azure.WebJobs.Host: Unable to convert value to Stream.
`

The error is pretty good, but it would be better if it appeared during compilation.

**Comment by christopheranderson** [comment]
@fabiocav - is this a reasonable thing to do at all?

**Comment by fabiocav** [comment]
It would require some changes to the binding extension implementation. I had discussed this with @mathewc a while ago, but it wasn't a priority at the time. 
@mathewc, I know this would add complexity to the currently binding extensibility model, which we're trying to make and keep simple, but we'd need a mechanism to allow us to interrogate bindings for supported types. With a sensible default, perhaps we can make this an optional thing binding authors can do to enhance the experience.
I can work on this change, but wanted to see if you had any thoughts on this.

**Comment by fabiocav** [comment]
Closing this as this as won't fix due to priority.
