### ISSUE TITLE
Issue with Response parsing with mongodb's results object or any object with functions in it.

### ISSUE THREAD

**Issue by omkardusane** [Azure/azure-functions-host#1742]
#### Investigative information

Using azure functions with nodejs and ## **cosmosdb with mongodb driver**

docs is an object obtained as a find() query result. (this code is just a snippet please look at my 2nd comment for the full code)

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a function in the AF and use this code from t2.js.txt file attached to this  [t2.js.txt](https://github.com/Azure/azure-webjobs-sdk-script/files/1191810/t2.js.txt)

2. try to pass one of the variables a1 a2 a3 sample1 and sample2  one at a time in the response.

## This works
            //let a1 = _.clone(docs)
            let a2 = JSON.parse(JSON.stringify(docs));
            //let a3 = docs;

            context.res = {
                body: {
                    ok: true,
                   // v1: a1, // ERROR
                    v2: a2, // works fine
                   // v3: a3, // ERROR
                   // v4: sample1, //ERROR
                    v5: sample2, //works fine
                }
            }
            context.done();

____
## This doesn't

            let a1 = _.clone(docs)
            let a2 = JSON.parse(JSON.stringify(docs));
            let a3 = docs;
            context.res = {
                body: {
                    ok: true,
                    v1: a1, // ERROR
                    v2: a2, // works fine
                    v3: a3, // ERROR
                    v4: sample1, //ERROR
                    v5: sample2, //works fine
                }
            }
            context.done();

#### Expected behavior
it should send the variables in response without errors

**Comment by christopheranderson** [comment]
Is this the full code sample? This doesn't look like it'd run because "_" is undefined? Could you also please share your stack trace or any relevant error messages? At this point, it looks like a Node.js coding issue, not Functions related.

**Comment by omkardusane** [comment]
Sorry, this isnt the full code, I am sharing the full code here now : 

enable one snippet at a time and the error can be reproduced in third one. My workaround is snippet 2.

```
let MongoDB = require('mongodb');
let MongoClient = MongoDB.MongoClient;
let url = "uri_for_mongodb_server";
let mongo = {
    connect: function (next) {
        MongoClient.connect(url, function (err, DB) {
            let db = {
                close: DB.close,
                tasks: DB.collection('tasks'),
                users: DB.collection('users'),
                test: DB.collection('test'),
            };
            next(db);
        });


    }
}
module.exports = function (context, req) {
    mongo.connect(function (db) {
        db.test.find().toArray(function (er2, docs) {
            
            // snippet 1 start  | (working but docs isnt parsed)
            context.res = {
                isRaw: true,
                body: {
                    ok: true,
                    docs: docs,
                }
            }
            context.done();
            // snippet 1 ends

            // snippet 2 start  | (works with properly parsed docs)
            docs = docs.map(a => { a._id = a._id.toString(); return a; });
            context.res = {
                body: {
                    ok: true,
                    docs: docs,
                }
            }
            context.done();
            // snippet 2 ends

            // snippet 3 start  | (error , should respond just like snippet2, normal node server dont give this error)
            context.res = {
                body: {
                    ok: true,
                    docs: docs,
                }
            }
            context.done();
            // snippet 3 ends


        });
    });
};

```

**Comment by alrod** [comment]
@omkardusane. Was you able to solve the issue?

**Comment by omkardusane** [comment]
You might want to reproduce it with given code sample and check. Last time I used those functions, it was not working. but it's a long time ago.

**Comment by alrod** [comment]
Closed as an old issue.
