### ISSUE TITLE
ARM API to retrieve key breaks when enabling slots

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-functions-host#1752]
Enabling slots sets `AzureWebJobsSecretStorageType=Blob`, which changes how secrets are managed. But the ARM API goes through Kudu, which does not honor this and returns an unusable key.

The main scenario that this breaks in Logic Apps, since they use that API. So effectively, slots cannot be enabled when using Logic Apps. 

One option that was discussed is to make the ARM API go through the runtime instead of Kudu. The cons is that it won't work when the app is stopped, though that is I think a lesser evil.

**Comment by davidebbo** [comment]
Note: if an app gets enabled for slots and breaks as a result, the workaround is to go to the App Settings and remove `AzureWebjobSecretStorageType=blob`.

**Comment by christopheranderson** [comment]
@lindydonna - this basically means that Logic Apps + Slots is broken. We need to probably update UI, docs, etc. to help prevent people tripping up on this bug.

**Comment by christopheranderson** [comment]
@davidebbo suggests we also allow you to disable slots via the UI (it is currently 1 way)

**Comment by mathewc** [comment]
Resolved by https://github.com/Azure/azure-functions-host/issues/3994.
