### ISSUE TITLE
Azure function concurrency

### ISSUE THREAD

**Issue by apengwin** [Azure/azure-functions-host#1757]
I'm working with Azure functions. I've got a function triggered by a storage queue, where I put a large number of messages `(O(1000))` in bursts. I want them all to execute in parallel, but I'm currently throttled by the batch size of 32.
![screen shot 2017-08-07 at 1 41 23 pm](https://user-images.githubusercontent.com/7637700/29038575-270b9a62-7b76-11e7-9474-c245950354fc.png)

The HTTP trigger offers [unbounded paralleism](https://imgur.com/r/HighQualityGifs/cJlBUVL), but I want to be able to invoke functions asynchronously. That is, I want to be able to run some code that triggers a function and continue, without waiting for an HTTP response. Is there any way to achieve the best of both worlds? To be able to invoke a function asynchronously, and have an unbounded number run in parallel? 

Thanks!

**Comment by fabiocav** [comment]
The answer here provides recommendations on the approaches you can follow: https://stackoverflow.com/questions/38123887/can-i-implement-async-fire-and-forget-http-triggers-in-azure-functions

You may also want to take a look at Durable Functions for async HTTP APIs: https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-overview#pattern-3-async-http-apis

**Comment by paulbatum** [comment]
Closing as answered.
