### ISSUE TITLE
Add Script Abstractions Project

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-functions-host#1800]
We need a consumable package of interfaces / contracts for language worker extensibility.

In particular:
`IWorkerProvider`
`FunctionRpc.proto`

**Comment by MikeStall** [comment]
Binding extensions won't depend on this, right? It's important that those just depend on the SDK interfaces.

**Comment by mamaso** [comment]
Nope, this is for things like custom process start logic for language worker nugets

**Comment by christopheranderson** [comment]
I don't think this is necessary since we now have the json based approach.

**Comment by paulbatum** [comment]
I agree, closed.
