### ISSUE TITLE
Ensure language BI is consistent across direct load / language workers

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-functions-host#1822]
need metrics on language worker usage

**Comment by fabiocav** [comment]
Although we already have this data for other languages, we don't have a first class metric emitted to track this usage (we use a combination of other metrics and the `function.compile.<language>.latency`). I would take this out of the OOP scope and make sure we emit something that works consistently even when no descriptors/invokers are used (i.e. direct load).

**Comment by mamaso** [comment]
Good point - we'll need to consider direct load as well as language workers (language / version).

I believe that a first class metric is the ScriptType here, which will no longer be sufficient with language workers: https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script.WebHost/Diagnostics/EventGenerator.cs#L248

Instead of emitting as a log we should probably move to metrics for this type of data

**Comment by fabiocav** [comment]
You're right. We do log the function details so we do have the script type.

Still, it would be ideal to have this emitted as a proper metric and have this out of the OOP scope or work and done consistently for all languages.

**Comment by pragnagopa** [comment]
@fabiocav - for now assigned this one to you. Can you please add more details and reassign?

**Comment by mhoeger** [comment]
@ColbyTresness - should this be closed?

**Comment by ColbyTresness** [comment]
Yeah I believe this is complete
