### ISSUE TITLE
Functions API needs to be fully accessible over ARM

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-functions-host#1824]
Some upcoming scenarios will make it impossible for the portal to hit either the main or scm site. ARM is the only thing that will work.

It does mean we won't be able to support log streaming or file download/upload in those set ups, but at least everything else should work.

**Comment by ahmelsayed** [comment]
part of this is in PR #2005

**Comment by ahmelsayed** [comment]
This is done
