### ISSUE TITLE
Inconsistent behaviour when creating a KeyVault key via an Azure PowerShell Function

### ISSUE THREAD

**Issue by adamwebbcollabware** [Azure/azure-functions-host#1827]
When attempting to create a KeyVault key via an Azure PowerShell Function I am experiencing inconsistent behaviour. It seems that running identical PowerShell on different function hosts will return different results/failures. The failure is a variant of the following:

_Get-AzureRmKeyVault : Your Azure credentials have not been set up or have expired, please run Login-AzureRmAccount to set up your Azure credentials.

The script is designed to authenticate to Azure via an Azure AD service principal, get the relevant KeyVault and create a key within it. But, even when hard-coding all the values for troubleshooting, the inconsistency still exists across differing function hosts i.e. one creates a KeyVault key successfully, whereas the other fails.

`$ServicePrincipalPassword = ConvertTo-SecureString "password" -AsPlainText -Force
$ServicePrincipalCredential = New-Object System.Management.Automation.PSCredential ($ServicePrincipalAppId, $ServicePrincipalPassword)
$Login = Login-AzureRmAccount -ServicePrincipal -TenantId $TenantId -Credential $ServicePrincipalCredential
$KeyVault = Get-AzureRmKeyVault -VaultName "testkeyvault"
write-output "$($KeyVault.VaultURI)"
$Key = Add-AzureKeyVaultKey -VaultName $KeyVault.VaultName -Name 'testkey' -Destination Software
$KeyUrl = $Key.id.Substring(0, $Key.id.LastIndexOf("/"))
Write-Output $KeyUrl`

Is this behaviour expected or anything I can do to make the experience consistent? Also, given that this would be running in a production environment and the current status of PowerShell-based Functions, should I consider moving this code to Azure Automation?

Thanks.

**Comment by ahmelsayed** [comment]
related to https://github.com/Azure/azure-webjobs-sdk-script/issues/1603?

**Comment by adamwebbcollabware** [comment]
@ahmelsayed even when I create two Function Hosts with exactly the same function deployed, one of the executions is successful and one fails. The really tricky thing is that sometimes the host which fails will suddenly start succeeding, but this is seemingly random. Could this be due to that specific invocation of the function running in a different host or "runspace" and so has access to different Azure PowerShell cmdlet versions?

**Comment by adamwebbcollabware** [comment]
@ahmelsayed It appears I have managed to resolve this issue by switching from using a password-based credential for the service principal to leveraging a certificate-based credential. This still does not explain the inconsistency I experienced, but at least it is now solidly consistent.

**Comment by Francisco-Gamino** [comment]
Hello @adamwebbcollabware,

PowerShell in Azure Functions GA-ed on November 2019, and it is available in both V2 and V3. For more information, please see https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-powershell. Currently, we support PowerShell 6, and we plan to support 7 as soon as it GAs. 

By default, Managed Dependencies is enabled, so in the first function invocation we install the `Az` module which contains all the Azure modules. After that, you can enable the MSI (https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=dotnet) to authenticate with Azure.

If you feel that something is missing for PowerShell in Function or you run into any problems, please open an issue at https://github.com/Azure/azure-functions-powershell-worker. Closing this issue.
