### ISSUE TITLE
Functions without bindings should still compile

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#191]
There is an empty C# function template that has no bindings. When you edit the code and save, it doesnt compile (because there are no bindings).

Assuming we want to keep the idea of the "empty function" templates, compiling a function without bindings should be supported.

**Comment by mathewc** [comment]
A function with no bindings is not invokable. There is a ManualTrigger binding that can be used for functions that are not externally invokable, but invokable by the Admin API / Portal. I always thought of these empty templates as blank slate starting points only. When someone attempts to run an empty function or compile it, we should have good error messages.

**Comment by christopheranderson** [comment]
We should see what it costs to support "no bindings", but if this is expensive, we can probably live with the empty template starting with "Manual Trigger".
