### ISSUE TITLE
support embedded slashes in route paramaters

### ISSUE THREAD

**Issue by alexkarcher-msft** [Azure/azure-functions-host#1949]
Tracking this uservoice item https://feedback.azure.com/forums/355860/suggestions/31269439

"I’ve created an Azure C# HTTP triggered function with a route url: subscriptions/{token}/t. It works fine for urls such as subscriptions/blah/t but it fails with a 404 for parameters that contain encoded slashes: subscriptions/blah%2fblah/t."

Slashes are correctly interpreted by the URL parser, but any slash present in a URL parameter causes a 404. Even with a route such as /api/{paramater} it returns a 404 on "/api/slash%2ftest"

**Comment by mathewc** [comment]
@safihamid fixed this and it is comitted I believe. Hamid, can you link and close this?

**Comment by safihamid** [comment]
This is in our todo list. original issue tracking is here: https://github.com/Azure/azure-webjobs-sdk-script/issues/1981

**Comment by alexkarcher-msft** [comment]
This will be resolved along with this issue: https://github.com/Azure/azure-functions-host/issues/2249

**Comment by vfedonkin** [comment]
Resolved in issue #2249,  v1 and v2
