### ISSUE TITLE
Functions Proxy returns 403 when backend target service has clientCertEnabled set to true.

### ISSUE THREAD

**Issue by baabel** [Azure/azure-functions-host#1961]
Calling a Function App via Azure Function Proxies results in 403 status code when enableClientCert is set to true on target Function App.

I created a Function Proxy that routes to another Function App function.  The target Function App has the clientCertEnabled set to true, has a client certificate imported and performs client certificate authentication.   Direct calls to the Function from clients passing a valid X509 client certificate results in a successful response (or 401 if certificate from client is invalid).

Calls made via the Proxy that routes to the Function App always return a 403 error.

#### Investigative information

logs from the proxy app:
2017-09-27T20:00:15.028 Executed HTTP request: {
  "requestId": "9725ef8a-f00a-40ba-a6d0-1ed1968ae3b1",
  "method": "GET",
  "uri": "/registrations/1",
  "authorizationLevel": "Anonymous"
}
2017-09-27T20:00:15.028 Response details: {
  "requestId": "9725ef8a-f00a-40ba-a6d0-1ed1968ae3b1",
  "status": "Forbidden"
}

Please provide the following:

- Timestamp: 2017-09-27T20:00:15.028 
- Function App name: 
- Function name(s) (as appropriate):
- Invocation ID:9725ef8a-f00a-40ba-a6d0-1ed1968ae3b1
- Region: WestUS

<!--
Example:

Used Fiddler as the HTTP client.

1) Sent a request directly to the target function passing an X509 certificate in the request.  The request is processed correctly and returns 200.

2) Sent the same request with the URL set to the Proxy Function that routes to the target Function.  The response is always 403.

Is Azure Function Proxies a layer on  top of an IIS ARR Server where the routes are mapped to the routing rules on that server?   Could it be that the ARR has "require" set to Client Certificates and the SSL mutual handshake did not happen?

**Comment by AssafNeufeld** [comment]
Any news on this issue? 
I'm getting the exact same thing.. :(

**Comment by alexkarcher-msft** [comment]
Looping in @safihamid to see if he can shed any light on this. 

Thanks for the ping!

**Comment by safihamid** [comment]
This is not currently supported by Proxies. Proxy does not store any certs and does not validate any middle tier certs.

**Comment by midnightrun** [comment]
@safihamid so in this case we need to use the API Management ?

**Comment by safihamid** [comment]
Yes.
