### ISSUE TITLE
ACI: Container endpoint to return image metadata 

### ISSUE THREAD

**Issue by suwatch** [Azure/azure-functions-host#1995]
Agree on the api shape that would not conflict with the app.    Likely need to come up with a reserved path for internal use only.   For backward compat (since we deploy independently), we will have ?api-version=201...

Response content
```json
{
   "base": "ubuntu",
   "functions": "2.1.2.3090",
   "nodejs": "6.0.2",
   "java": "8.5.1"
}
```

**Comment by ahmelsayed** [comment]
Closing since it's captured in the open PR
