### ISSUE TITLE
Add support for OpenAPI 3

### ISSUE THREAD

**Issue by alexkarcher-msft** [Azure/azure-functions-host#2011]
Now that OpenAPI 3.0 has been ratified, we should provide the option to generate an OpenAPI 3.0 document.

https://feedback.azure.com/admin/v3/suggestions/31659034/activity

**Comment by gmoed** [comment]
Hello!, is there any ETA on this one?

Cheers!

**Comment by rikvandenberg** [comment]
Duplicate #2874 ?
