### ISSUE TITLE
Appropriately register services based on the standby/production scope

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#2021]
Some services should be scoped to the site standby state (placeholder vs specialized site), so we need to ensure those services are appropriately register with that scope to guarantee they will be correctly recreated and cleanup up when the specialization process happens.

**Comment by paulbatum** [comment]
We don't need do this until we are close to having 2.0 placeholder pools ready.

**Comment by fabiocav** [comment]
Closed as resolved.
