### ISSUE TITLE
What exact Node.js version is being used? (documentation)

### ISSUE THREAD

**Issue by yvele** [Azure/azure-functions-host#2036]
I can't figure out what exact version of Node.js is actually being used. I would like my [CI](https://en.wikipedia.org/wiki/Continuous_integration) machine to test my code under the same conditions as possible.

- In the documentation it's `6.5.0` https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#node-version-and-package-management
- But in [this recent issue](https://github.com/Azure/azure-webjobs-sdk-script/issues/1682#issuecomment-332218608), @mamaso said the node has been updated 
- In [Functions 1.0.11184](https://github.com/Azure/azure-webjobs-sdk-script/releases/tag/v1.0.11184) it's `6.11.2`
- In Node.js official website, the [LTS](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#6.11.4) is actually `6.11.4`

Is it `6.11.2`?

Where can I find a single, and updated information about Node.js version being used?

**Comment by mamaso** [comment]
@yvele it looks like the docs should be updated, thanks.

The version of node in `~1` is now `6.11.2`.

The version of node in `~2`, the `beta` runtime, is set via `WEBSITE_DEFAULT_NODE_VERSION` with official support for `>=8.4.0`

**Comment by SyntaxC4** [comment]
Tracking in VSTS 1108957

**Comment by tdykstra** [comment]
fixed by https://github.com/MicrosoftDocs/azure-docs-pr/pull/34503

**Comment by yvele** [comment]
@tdykstra 404

**Comment by tdykstra** [comment]
@yvele Yes the PR is in the private docs repo but the fix should be live on the public site this afternoon or tomorrow morning.
