### ISSUE TITLE
Proxies not working in 2.0 preview

### ISSUE THREAD

**Issue by egor-laufer** [Azure/azure-functions-host#2055]
Proxies appear to be not working in Function App 2.0 preview (Runtime version: 2.0.11276.0 (beta)).

I'm deploying netstandard2.0 app (I used https://github.com/lindydonna/CSharpHttpCore.git as a starting point) to a Function App from git repository. I have a custom deployment script, which runs dotnet restore/build/publish.

In Kudu I can see my proxies.json deployed correctly to D:\home\site\wwwroot. All functions are working correctly as well.

```proxies.json``` contents is as follows (proxy, function and domain names redacted):

```
{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "%proxy_name%": {
      "matchCondition": {
        "route": "/",
        "methods": [ "GET" ]
      },
      "backendUri": "https://%domain_name%/api/%function_name%"
    }
  }
}
```

I also can see proxy shown correctly on Azure Portal, however hitting ```/``` with a web browser shows default Function App welcome page instead of response from my function.

**Comment by kevbite** [comment]
I'm having the same problem, my user group site runs off azure functions and uses proxies to serve static content from a s3 bucket.

https://dotnetsheff-api.azurewebsites.net

![image](https://user-images.githubusercontent.com/5544715/31881775-851f5dc6-b7dc-11e7-8021-91c5a87ada3f.png)

**Comment by kevbite** [comment]
Looks like it's this that is getting executed and handled before the azure functions proxies.
https://github.com/Azure/azure-webjobs-sdk-script/blob/3f54f80a447e9330cb11b6a4ff203bcfdd6ba0ab/src/WebJobs.Script.WebHost/WebJobsApplicationBuilderExtension.cs#L30

**Comment by SimonLuckenuik** [comment]
Did you try setting AzureWebJobsDisableHomepage to false?
https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings

**Comment by SimonLuckenuik** [comment]
@kevbite  are you sure you are running from the preview? The preview "app is running" is darker and states  that it is a preview.

**Comment by kevbite** [comment]
It's randomly started working again, Has someone changed something?

**Comment by kevbite** [comment]
My app settings is also just a mangled mess
![image](https://user-images.githubusercontent.com/5544715/31899724-5173067a-b814-11e7-9aae-9f4d9e83a3ae.png)

**Comment by egor-laufer** [comment]
Hi @SimonLuckenuik, it looks like this setting is ignored completely for me. I did try to set it to true:
![image](https://user-images.githubusercontent.com/8051569/31959787-5633e95a-b8fe-11e7-869e-92137b619eb3.png)

However I'm still getting a default home page on ```/```:
![image](https://user-images.githubusercontent.com/8051569/31959807-6a255f0c-b8fe-11e7-8e9e-013857559486.png)

**Comment by paulbatum** [comment]
@safihamid can you take a look? I'd focus on the original posted question.

**Comment by JonathanGiles** [comment]
Just for completeness, this issue is present for Java as well as C# (I'm guessing for all v2 platforms), but I wanted to call out my pain point is with Azure Functions / Java.

**Comment by benc-uk** [comment]
Hi I see a PR is in progress to get this fixed, but do we have a timeline? For <complex reasons removed>  I need this capability for a demo I'm giving in 2 weeks. Will proxies be available in v2 before GA?

**Comment by safihamid** [comment]
This PR is checked in and will be released with our next release of Functions Beta runtime. There is usually a Functions runtime release every couple of weeks.

**Comment by safihamid** [comment]
This is already in prod.
