### ISSUE TITLE
Port functionality handled by the SystemTraceHandler to 2.0

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#2057]
The logging logic present in `SystemTraceHandler` class has not been ported over to 2.0. This would need to be implemented as middleware in the runtime. 

We need to evaluate if this is still needed and whether we want to keep it as verbose as it was in 1.x.

**Comment by brettsam** [comment]
@mathewc took care of this in https://github.com/Azure/azure-functions-host/pull/3548
