### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#2059]
It appears that we may have some managed memory leaks. You can see this yourself causing your function app to restart many times then take a look at the memory dump. You can automate this by creating a timer function that touches host.json once every 10 seconds. Let that run for a few minutes then look at memory for root objects under our namespaces. E.g. you'll see that the number of ScriptHost instances is roughly equal to the number of restarts.

**Comment by davidebbo** [comment]
To make sure you only see rooted objects, might make sense to also add a call to GC.Collect() in your test timer function.

**Comment by mathewc** [comment]
Fixed by changes made for https://github.com/Azure/azure-functions-host/issues/2313
