### ISSUE TITLE
Nightly function apps didn't run last night

### ISSUE THREAD

**Issue by brianbraeckel** [Azure/azure-functions-host#2069]
Hi,

We have several function apps setup to run nightly (07:00 UTC) and none of them triggered last night.

When I noticed the problem, I logged into the portal to see if there were any errors, and didn't see any logs at all from last night.  However, it appears that logging into the portal and opening a function app's monitoring page triggered them to start running, at which point they all ran to completion.  I'm at a loss for why they didn't fire until I logged into the portal (assuming that's what actually triggered them).

Here's an example function ID after running one of them manually:

Timestamp: 2017-10-25T18:12:29.645
Invocation ID: e0b04217-8cfb-4c8b-988f-3e5374545f88
Region: West US

Thanks!

**Comment by bedej** [comment]
This happened again last night. Same symptoms. We have three function apps. Two of them use precompiled binaries and appear to execute correctly on timer triggers. The app whose functions haven't correctly executed for the last two days is using C# script, written in the portal. We haven't updated the function since last week, and the failures started occurring yesterday, so it appears to us that this is an azure functions platform regression.

This is a serious production problem for us. Could anyone from the team offer any insight/help/work arounds?

**Comment by brianbraeckel** [comment]
Our timer triggers continued to fail regularly after I opened this issue. We copied all of our scripts to a new (identical) function app, and things appear to be working correctly in the duplicate. I'll keep this item open to track the issue, though, as it still seems to indicate a platform regression.

**Comment by fabiocav** [comment]
@brianbraeckel are you still experiencing problems? Can you share a more recent invocation ID?

**Comment by brianbraeckel** [comment]
We don't use the problematic function app anymore because I copied all its scripts over to a new one (which is working fine). I have the broken function app disabled right now. If re-enabling it and re-running one of its functions to get a new invocation ID would help you guys figure out what went wrong, I can do that. Has the old invocation ID expired?

**Comment by fabiocav** [comment]
It's old enough that it may be problematic finding all the relevant information from other logs. If you can repro the issue with the old app and provide a recent one, that would help.

**Comment by brianbraeckel** [comment]
I tried to restart the old app, but got an error even just turning it on, so I probably won't look at this anymore.  Here's the error I got in case it helps track anything down:

Error: The function runtime is unable to start. Please check the runtime logs for any errors or try again later.
Session Id: e2b2a39039cc4f8da6daa9286ed25d19
Timestamp: 2017-11-28T19:20:38:541Z

**Comment by brianbraeckel** [comment]
Closing due to lack of traction.
