### ISSUE TITLE
BlobTrigger Javascript Error: Received message larger than max (11112848 vs. 4194304)

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-host#2136]
_From @simonaco on November 15, 2017 11:58_

Javascript BlobTrigger function fails with error message (see logs bellow). I am running on:
OSX
dotnet-core: v2.0.2
Azure Functions Core Tools (2.0.1-beta.21)
Function Runtime Version: 2.0.11370.0

Worker.Node.fdef4ba8-9c72-479f-8e6a-3e2af09cea5b[0]
      Worker fdef4ba8-9c72-479f-8e6a-3e2af09cea5b encountered event stream error:  { Error: Received message larger than max (11112848 vs. 4194304)
info: Worker.Node.fdef4ba8-9c72-479f-8e6a-3e2af09cea5b[0]
          at ClientDuplexStream._emitStatusIfDone (/Users/simonacotin/.azurefunctions/bin/workers/node/worker-bundle.js:22590:19)
info: Worker.Node.fdef4ba8-9c72-479f-8e6a-3e2af09cea5b[0]
          at ClientDuplexStream._receiveStatus (/Users/simonacotin/.azurefunctions/bin/workers/node/worker-bundle.js:22568:8)
info: Worker.Node.fdef4ba8-9c72-479f-8e6a-3e2af09cea5b[0]
          at /Users/simonacotin/.azurefunctions/bin/workers/node/worker-bundle.js:23092:12 code: 8, metadata: Metadata { _internal_repr: {} } }
info: Worker.Node.fdef4ba8-9c72-479f-8e6a-3e2af09cea5b[0]
      Worker fdef4ba8-9c72-479f-8e6a-3e2af09cea5b uncaught exception:  { Error: Received message larger than max (11112848 vs. 4194304)
info: Worker.Node.fdef4ba8-9c72-479f-8e6a-3e2af09cea5b[0]
          at ClientDuplexStream._emitStatusIfDone (/Users/simonacotin/.azurefunctions/bin/workers/node/worker-bundle.js:22590:19)
info: Worker.Node.fdef4ba8-9c72-479f-8e6a-3e2af09cea5b[0]
          at ClientDuplexStream._receiveStatus (/Users/simonacotin/.azurefunctions/bin/workers/node/worker-bundle.js:22568:8)
info: Worker.Node.fdef4ba8-9c72-479f-8e6a-3e2af09cea5b[0]
          at /Users/simonacotin/.azurefunctions/bin/workers/node/worker-bundle.js:23092:12 code: 8, metadata: Metadata { _internal_repr: {} } }

_Copied from original issue: Azure/Azure-Functions#592_

**Comment by christopheranderson** [comment]
@simonaco - what size was the blob you were testing with?

### Workaround: 

Use event grid trigger for new Blobs and then stream the Blob in using Storage SDKs (not bindings, which have to go over our gRPC connections).

### Root Cause:

This is caused by sending messages that are too large in a single gRPC message.

### Potential fixes:
 - (Short term) Prevent execution and give a nice error - TBD
 - (Long term) Stream support - https://github.com/Azure/azure-webjobs-sdk-script/issues/1814
 - (Long term) multi-part messages for large message sizes - TBD
    - I'm inclined not to do this because it leads to bad practices like reading 4GB into memory

**Comment by pragnagopa** [comment]
Closing this issue. We have tracking item to increase the max message size over grpc #2301
