### ISSUE TITLE
Provide out-of-proc support for cancellation tokens

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#2152]
In C# functions you can take a `CancellationToken` argument to allow your function to detect that a host shutdown is occurring and abort gracefully. This work item tracks provide an equivalent mechanism for languages that execute out of proc. Exactly what type/data structure would be used would be language dependent.

**Comment by fabiocav** [comment]
Assigning to sprint 124 for spec/design.

**Comment by liliankasem** [comment]
Design document available [here](https://dev.azure.com/msazure/One/_git/AAPT-Antares-Docs?path=/TeamDocs/FunctionTeamDocs/Design/CancellationTokens/OutOfProcCancellationTokens.md&_a=preview&anchor=out-of-proc-support-for-cancellation-tokens). 

Had conversations with language owners and set expectations on what is in scope for this work item. The remaining work here is outlining the host changes we want to make to enable this, and implementation + testing. We should be move this out to the next sprint.

**Comment by fabiocav** [comment]
Design is complete. @liliankasem has made good progress on the implementation and is working on additional validation prior to opening a PR.

Moving to 126 as a tentative sprint as Lilian may not have enough cycles to complete the work then.
