### ISSUE TITLE
Add FunctionName/Source to Admin Host logs

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#2154]
For logs written to our host log via the admin/host/log api, we should include additional details in the log entry written when we have them.

E.g. rather than writing:

     2017-11-23T04:31:56.657 A very bad error occured

we'd write something like (including both Source and FunctionName):

     2017-11-23T04:31:56.657 [ScaleConroller, MyAwesomeFunction] A very bad error ocurred

This could either be done by formatting the message before it is written, or deeper in the FileTraceWriter itself. Note that for function specific log files written to the individual function directories, including the function name would be unnecessary additional noise, so we'd need to make the logic modal in FileTraceWriter. Probably easier to just special case the scenario and format the log message before writing it.

**Comment by pragnagopa** [comment]
Fix checked in [V1](https://github.com/Azure/azure-functions-host/pull/2467). Tracking issue [here ](https://github.com/Azure/azure-functions-host/issues/2391)for V2
