### ISSUE TITLE
Coldstart logging issue

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#2186]
Some host level logs aren't logged when the runtime is cold starting. E.g. the admin/host/log endpoint. To repro, cause the runtime to coldstart before invoking this log endpoint.

I suspect that the issue is that these controllers are being created with a noop TraceWriter (their ctor argument) because the DI container only returns a valid TraceWriter when the runtime host instance is not null. Otherwise it returns a NullTraceWriter (code [here](https://github.com/Azure/azure-webjobs-sdk-script/blob/12329065d4977d174ad5725d59d5940cfc729bb8/src/WebJobs.Script.WebHost/App_Start/AutofacBootstrap.cs#L27)). That's what I think the issue is. We need to change that code so there is a default trace writer that is used if the host is not yet running, one that logs to file and system logs.

Need to check other controllers as well, like KeysController, SwaggerController, etc.

**Comment by paulbatum** [comment]
To clarify, I think this applies to app insights logging too. So the challenge here is to make sure that the logs are written correctly to all locations (not just file and system logs).

**Comment by paulbatum** [comment]
I assume this bug is for v1, do we know if the same issue exists for V2 as well?

**Comment by mathewc** [comment]
Not sure if this issue exists in v2. Probably does. Here are some thoughts on how we might fix this:

- the TraceWriter resolver for the DI container should not require the host to be running
- instead, to the DI container we should be adding a default host level composite trace writer that writes to host log files and System logs
- Add a new method to WebHostResolver "GetTraceWriter(settings)" that returns this default trace writer
- We'll want to factor out the TraceWriter creation code currently buried in ScriptHost.Initialize so that it can be called as a static method to be reused above and for the new method. Ideally we'd be able to parse enough of host.json to be able to apply the right log settings.
- Do we need to do the the same for ILogger?. I see a code note already here indicating the same chicken and egg problem (missed logs): https://github.com/Azure/azure-webjobs-sdk-script/blob/12329065d4977d174ad5725d59d5940cfc729bb8/src/WebJobs.Script.WebHost/App_Start/WebHostResolver.cs#L47.
- The SecretManagerFactory that WebScriptHostManager creates should also probably use this new TraceWriter
-

**Comment by mathewc** [comment]
Reactivating this. Though I definitely fixed a class of issues with the commit I checked in for this issue. @tohling is still seeing this in her end to end tests.
