### ISSUE TITLE
New Feature: Validate Input Based on OpenAPI Definition

### ISSUE THREAD

**Issue by securityvoid** [Azure/azure-functions-host#2203]
Input validation is one of the key components for creating secure software, yet one of those things that can take quite a bit of time to do properly/maintain. With Azure Functions support for the OpenAPI/Swagger definitions; it would be great if those could be utilized to validate the incoming input without any further code being required to be written.

I imagine this being done with two toggles within the Platform Features.

1st Toggle: Enable validation against OpenAPI File: (On/Off)
2nd Toggle: Behavior when validation fails: (Log/Block)

If validation is enabled and the behavior is log, then any failures of the OpenAPI specifications will be logged to a file so they can be looked at.

If validation is enabled and the behavior is to block, then any failures of the OpenAPI specifications would return a "400 Bad Request" response.

This would mean that all you need to do to have incoming requests be validated is define an OpenAPI file, and enable the validation. You now know the schema of anything that hits your function.

**Comment by paulbatum** [comment]
Makes sense as a feature request.
