### ISSUE TITLE
Make sure our handler for AppDomain.AssemblyResolve cannot throw an exception

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#2205]
The specialization code path makes it possible for us to have two handlers registered on `AppDomain.CurrentDomain.AssemblyResolve`. The way this can happen is that we construct and assign a WebScriptHostManager for the main app, and then we call Stop() on the standby host manager. The main host manager might have hooked into AssemblyResolve before Stop() finished executing and unhooked the event. Because these actions are happening on different threads, the ordering is not deterministic.

The reason the above is important is because `AppDomain.CurrentDomain.AssemblyResolve` does not handle exceptions well. It will call the handlers one after another until one of them returns an Assembly or throws an exception (you can see this [here](https://referencesource.microsoft.com/#mscorlib/system/appdomain.cs,3157)). This means that if the AssemblyResolve handler for the standby host manages to throw an exception, it might prevent the AssemblyResolve handler for the user application from running. This can result in Assembly load failure errors.

In order to prevent the above we need to be extra defensive in our handler for AsssemblyResolve - even a logging call could throw an exception.

**Comment by fabiocav** [comment]
Have you experienced issues with that? Our `AssemblyResolve` handler is pretty defensive against errors in the resolution path and should work well even with scenarios where multiple registrations are in play (as they'd end up working on the same context).

**Comment by paulbatum** [comment]
The current implementation has calls that are not protected by a try/catch. Also when placeholders are in play, the contexts are not the same.

**Comment by fabiocav** [comment]
Yeah, the calls to get the context and logging calls are not in a try/catch today. I just noticed this was assigned to you, are you working on it or do you need me to take it?

**Comment by paulbatum** [comment]
Yeah I'll take it, this is a simple change.
