### ISSUE TITLE
[Powershell] Missing cmdlets needed for creating new VMs

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#2229]
Reported by user @pollardsg

Following seem to be missing cmdlets in my App Service powershell function:
New-AzureRmDiskConfig
New-AzureRmDisk
New-AzureRmVirtualNetwork
New-AzureRmVirtualNetworkSubnetConfig
New-AzureRmNetworkSecurityRuleConfig
New-AzureRmNetworkSecurityGroup
New-AzureRmPublicIpAddress
New-AzureRmNetworkInterface

Is there a reason they are not available?

For example I'm getting the following error:
New-AzureRmDisk : The term 'New-AzureRmDisk' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
at run.ps1: line 74

**Comment by soninaren** [comment]
moved from templates repo
https://github.com/Azure/azure-webjobs-sdk-templates/issues/614

**Comment by christopheranderson** [comment]
It is likely these aren't here because Azure PowerShell SDK isn't upgraded on App Service to avoid breaking changes. We don't yet have a means to selectively upgrade.

**Comment by Francisco-Gamino** [comment]
Hello @pollardsg,

If you need support for Azure PowerShell cmdlets, please take a look at https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell#dependency-management. This feature is available for PowerShell function apps, and we enable the `Az` module (this module is the `AzureRM` cross-platform equivalent) by default. Here is a reference doc for getting started with PowerShell functions https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-powershell.

Thanks,
Francisco
