### ISSUE TITLE
Can't properly parse multipart/form-data inside Azure functions using Node.js

### ISSUE THREAD

**Issue by celicoo** [Azure/azure-functions-host#2256]
I'm trying to parse multipart/form-data from my Azure function writing in Node.js, but the context.req.body is not binary, and if I try to parse a PDF (for example) it will loose information. Is there a way to bypass it? I've searched a LOT and it seems that this is a knowing issue.

```javascript
module.exports.handler = (context) => {
  context.info(context.req.body) // This is a string, not a binary
}
```

I've also tried to change the dataType to binary, inside the functions.json, but it still keeps going as string, so I guess this is a bug.

**Comment by christopheranderson** [comment]
I'm assuming this is v1 (you're not using our beta v2?)

**Comment by pragnagopa** [comment]
@celicoo - We recently fixed this issue #2009 . Can you please retry?

**Comment by mhoeger** [comment]
Closing as it appears to be fixed.
@celicoo - please reopen if it is not fixed for you!

**Comment by celicoo** [comment]
Hi! I'm sorry for taking so long to answer you guys, I was on vacation.

I'm not using Azure anymore, because of this bug I decided to move all my infrastructure to AWS. If I have sometime available in the future, I'm gonna test it.

Thanks!

**Comment by mhoeger** [comment]
@celicoo really sorry to hear that. If you do get a chance to verify that'd be great, but otherwise best of luck! Please do reach out if there were other pain points we can work on that led you to switching over - we'd love to know.
