### ISSUE TITLE
Enable setting and/or retrieving keys for local container validation for Functions on Linux

### ISSUE THREAD

**Issue by dariagrigoriu** [Azure/azure-functions-host#2262]
Enable setting and/or retrieving keys for local container validation that does not rely on anonymous mode for Functions on Linux.

**Comment by ahmelsayed** [comment]
This is a tooling issue not a runtime issue. The runtime shouldn't do anything differently.

**Comment by ahmelsayed** [comment]
This issue was moved to Azure/azure-functions-core-tools#439
