### ISSUE TITLE
[V2]Investigate if HTTP tracing logs are needed in V2 and populate activityId for httpRequests

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#2272]
The [TraceHandler](https://github.com/fabiocav/azure-webjobs-sdk-script/blob/5867f55820109c14d73ba94994abb92986b65118/test/WebJobs.Script.Tests/Handlers/SystemTraceHandlerTests.cs) and [Exception handler ](https://github.com/fabiocav/azure-webjobs-sdk-script/blob/5867f55820109c14d73ba94994abb92986b65118/test/WebJobs.Script.Tests/Handlers/ExceptionProcessingHandlerTests.cs) tests need to be re-enabled. We have not decided how (and if) the HTTP trace handler will be re-enabled. Functionality similar to the ExceptionProcessingHandler needs to be brought back using a proper exception handler/middleware.

**Comment by pragnagopa** [comment]
There are no request handlers in V2. [FunctionInvocationMiddleware.cs](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Middleware/FunctionInvocationMiddleware.cs) handles invocations.  
Once DI changes are checked in, need to figure out if we need system logs similar to V1 like the one [here](https://github.com/Azure/azure-functions-host/blob/v1.x/src/WebJobs.Script.WebHost/Handlers/SystemTraceHandler.cs#L71)

Also, need to populate ActivityIds for the http requests similar to [V1](https://github.com/Azure/azure-functions-host/blob/v1.x/src/WebJobs.Script.WebHost/Handlers/SystemTraceHandler.cs#L64)

**Comment by pragnagopa** [comment]
ActivityId and ColdStartEventName are added to the logdata [here](https://github.com/Azure/azure-functions-host/blob/bafab95344edf81ff100b2bb0f76ea5681ca57be/src/WebJobs.Script.WebHost/Features/FunctionExecutionFeature.cs#L77). Investigate if these properties can be added to the ILogger scope similar to other logging properties added [here](https://github.com/Azure/azure-webjobs-sdk/blob/5140983cb163b20bf6af60afccebb705bc80ad80/src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/LoggerExtensions.cs#L64)
