### ISSUE TITLE
Feature planning: first class PHP support

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/azure-functions-host#229]
This is a tracking item for First Class PHP support. We'll be tracking the requirements and issues for first class PHP support via this item. Feel free to leave comments about features/design patterns.
## Function format

For the PHP function format, I propose that we use the [ReactPHP](http://reactphp.org/) framework to provide a more event-driven programming approach. This means that your function code can be very minimalistic as we'll maintain the execution wrapper.

The scripting format should look very similar to this:

``` php

$app = function(context, data) {
  context->log('Webhook was triggered!');

  // process event

  context->done();
}
```
## Data Type formats

**TBD**
### Package management

For package management, we would like to provide [composer](http://getcomposer.org) as an option for including access to external packages of code. In order to dynamically include `extensions`, we would like to adopt [pickle](https://wiki.php.net/rfc/pickle), which will automatically update the `php.ini` and reload the `php-cgi` to include the new extensions to execute your function.
## Testing/CI

**TBD**
## Change log

5/5 - Chris - Add basic list of feature areas
5/25 - Cory - Updated the descriptions for format and package management

**Comment by dariuszparys** [comment]
Is this still on the roadmap? The current performance characteristics of script execution for the PHP runtime is too slow for certain scenarios.

**Comment by smoelker** [comment]
It seems like support for PHP and blob triggers is very basic. I can get the blob data using environment variables but I can't find a way to get the original blob name.

**Comment by fabiocav** [comment]
Closing this as this is not something we're actively tracking.
