### ISSUE TITLE
Enable runtime 2.0 to support logging for App Service Linux

### ISSUE THREAD

**Issue by dariagrigoriu** [Azure/azure-functions-host#2291]
This is a request to support the specific logging format for App Service Linux workers in the context of Functions on Linux dedicated.

**Comment by mathewc** [comment]
@dariagrigoriu I don't understand this work item.

**Comment by bala16** [comment]
the work here is to basically emit logs in csv format (similar to how it is done on seabreeze) but without the quote escaping and json object formatting logic. 
also the logs wont go to stdout but instead a mounted file depending on how Linux dedicated mds is setup.

**Comment by mathewc** [comment]
Specifically:

- update websites\src4\Hosting\Tuxedo\config\td-agent\td-agent.conf by adding new sources for all Functions log tables
- update the runtime to log to the buffer file locations defined by those sources

**Comment by balag0** [comment]
Fixed.
