### ISSUE TITLE
Correctly assign language worker fatal error

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#2299]
System logs need to show worker process  errors to help us figure out why worker did not start or why the process crashed.

Also, we need to add alerts to on these errors in Portal. One check is to set WEBSITE_NODE_DEFAULT_VERSION to an old node version and see if the fatal error message is informative.

**Comment by mhoeger** [comment]
I recently opened this issue (#2860), but looks like this covers it!

**Comment by mhoeger** [comment]
FYI @pragnagopa - changing the title to make this a more actionable work item

**Comment by mhoeger** [comment]
I think the behavior that we want is to check if we have functions in a language, and if so, fail the worker that is unable to start.

**Comment by mhoeger** [comment]
Edited title again after talking to @pragnagopa

**Comment by pragnagopa** [comment]
Thanks @mhoeger for flagging this in PR! I will verify changes in the PR fix this issue.

**Comment by paulbatum** [comment]
@pragnagopa I see PR #3194 was merged. Can we close this?

**Comment by pragnagopa** [comment]
Fix checked in.
