### ISSUE TITLE
Remove PHP from install section of appveyor

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-host#2302]
We don't need to install PHP into the CI machine for v2 anymore.

**Comment by paulbatum** [comment]
Isn't there just a single install script that applies for both v1 builds and v2 builds?

**Comment by paulbatum** [comment]
As part of this, we should delete the install script that is saved into the appveyor configuration since its not actually being applied.

**Comment by brettsam** [comment]
Note that I also moved all the settings to "Off" in the AppVeyor Web UI to reduce confusion.
