### ISSUE TITLE
HTTP headers and status sent with response body when context.res.body is undefined

### ISSUE THREAD

**Issue by pgraham** [Azure/azure-functions-host#2305]
#### Investigative information

Please provide the following:

- Timestamp: 2018-01-10
- Function App version (1.0 or 2.0-beta): 2.0-beta
- Function App name: N/A
- Function name(s) (as appropriate): N/A
- Invocation ID: N/A
- Region: N/A

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create an HTTP triggered function that sets headers and status but not body on response object:

``` js
module.exports = (ctx, req) => {
    ctx.res = {
        headers: {
            'Access-Control-Allow-Origin': req.headers.origin,
            // ... Set other Access-Control headers
        },
        status: 204,
        //body: '' <-- Adding this results in expected behaviour
    };
    ctx.done();
};
```

#### Expected behavior

Response has status 204 and Access-Control headers

#### Actual behavior

Response has status 200, no Access-Control headers and the following JSON encoded body:

``` js
{
    "headers": { "Access-Control-Allow-Origin": "..." },
    "status": 204
}
```

If I add a `body` property to `ctx.res` with an empty string value, I get the expected result.

#### Related information

I see this when running locally using the preview version of the cli on OSX.

**Comment by christopheranderson** [comment]
Weird. I wonder if we somehow have a code path that if there is no body returned just assumes there was no response. I'll check into this.

**Comment by securityvoid** [comment]
Something like this has existed for awhile, 

e.g. Slightly different, but very similar:
https://stackoverflow.com/questions/41709910/azure-functions-nodejs-http-response-renders-as-xml-rather-than-http-response/41709911#41709911

**Comment by christopheranderson** [comment]
Nice, two repros is helpful.

**Comment by mhoeger** [comment]
Could be the root cause of https://github.com/Azure/azure-functions-host/issues/2578 as well, where using v2.1.2 of [node-fetch](https://www.npmjs.com/package/node-fetch) appears to return the wrong body (some bad assumption is being made).

**Comment by mhoeger** [comment]
Root cause of this issue is https://github.com/Azure/azure-functions-host/issues/997

To summarize, an http response is created in two ways:
 1. `context.res = bodyValue; // res is interpreted as 200 with body bodyValue`
 2. `context.res = {  body: bodyValue, headers: ..., status: ... } // res is fully specified object`

Code assumes that a context.res object without a "body" property = bodyValue
