### ISSUE TITLE
Add support to gracefully shutdown language worker

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#2308]
FunctionRpc proto file defines: [WorkerTerminate ](https://github.com/Azure/azure-functions-host/blob/a32a63925c9e67a4ce1af4a49ae1dd3b16d7f7e2/src/WebJobs.Script.Grpc/azure-functions-language-worker-protobuf/src/proto/FunctionRpc.proto#L160-L162). Need to update host to send WorkerTerminate message with a grace period.

**Comment by fabiocav** [comment]
@pragnagopa I think this makes sense. We were wondering if we have evidence of issues that would be directly impacted by this work.

**Comment by liliankasem** [comment]
Dup of #3296

**Comment by liliankasem** [comment]
We will need to go through design to discuss the right approach for this. 

1. Should we use SIGTERM before SIGKILL to let the workers know of intent to shutdown, or
2. Should we use the gRPC to signal a graceful shutdown via the `WorkerTerminate` message

**Comment by surgupta-msft** [comment]
Moving forward with the implementation using WorkerTerminate grpc message.

Summary of the design discussion and investigation -

1. Using SIGTERM before SIGKILL -
         **Cons** -
                     - Will need different approaches for windows and linux.
                     - Cannot send any additional info/reason about worker termination.
         **Investigation details** -
                     - As part of reproducing the issue, found that it is the below line that actually kills the worker process. It is being done through JobObjectRegistry. Thus, it is not possible to replace it with another call which will gracefully shutdown the worker as it kills the process and the child processes. https://github.com/Azure/azure-functions-host/blob/46328aa355d6c4d36a88fb41a78c8baed87cb1dd/src/WebJobs.Script/Workers/ProcessManagement/JobObjectRegistry.cs#L83


2. Using WorkerTerminate GRPC message -
          **Pros** -
                     - Same approach for both windows and linux.
                     - Can send any additional info/reason about worker termination.
          **Implementation flow** -
                     - Host will send WorkerTerminate GRPC message before killing the worker process.
                     - Worker will need to handle the message and send success response to host, otherwise Host will restart the worker. Worker can also log additional info as it already knows about being terminated.
                     - 2 major scenarios to handle here - One where host is shutting down and killing the worker and the Other where Host is not shutting down but worker is being terminated. Both the cases should have graceful shutdown of worker.

**Comment by liliankasem** [comment]
> Moving forward with the implementation using WorkerTerminate grpc message.
> 
> Summary of the design discussion and investigation -
> 
> 1. Using SIGTERM before SIGKILL -
>    **Cons** -
>    - Will need different approaches for windows and linux.
>    - Cannot send any additional info/reason about worker termination.
>    **Investigation details** -
>    - As part of reproducing the issue, found that it is the below line that actually kills the worker process. It is being done through JobObjectRegistry. Thus, it is not possible to replace it with another call which will gracefully shutdown the worker as it kills the process and the child processes. https://github.com/Azure/azure-functions-host/blob/46328aa355d6c4d36a88fb41a78c8baed87cb1dd/src/WebJobs.Script/Workers/ProcessManagement/JobObjectRegistry.cs#L83
> 2. Using WorkerTerminate GRPC message -
>    **Pros** -
>    - Same approach for both windows and linux.
>    - Can send any additional info/reason about worker termination.
>    **Implementation flow** -
>    - Host will send WorkerTerminate GRPC message before killing the worker process.
>    - Worker will need to handle the message and send success response to host, otherwise Host will restart the worker. Worker can also log additional info as it already knows about being terminated.
>    - 2 major scenarios to handle here - One where host is shutting down and killing the worker and the Other where Host is not shutting down but worker is being terminated. Both the cases should have graceful shutdown of worker.

Can we make sure we have a design doc for this in the [design/host](https://dev.azure.com/msazure/One/_git/AAPT-Antares-Docs?path=/TeamDocs/FunctionTeamDocs/Design/Host&version=GBmaster&line=1) folder, and, if we need to create more issues across worker repos to address this

**Comment by surgupta-msft** [comment]
Sounds good @liliankasem. Will add doc in the design folder and create more issues as needed.

**Comment by fabiocav** [comment]
There's a concrete design proposed and we're coordinating with language owners. Moving to sprint 122 for implementation.

**Comment by fabiocav** [comment]
Changes currently in PR. Moving to sprint 127.
