### ISSUE TITLE
[V1]Include FunctionInvocationId and Host InstanceId directly in system logs

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#2312]
Querying/correlation would be much nicer if the function id and host instance id was a queryable column.

**Comment by paulbatum** [comment]
@pragnagopa is this straightforward? It would definitely be nice...

**Comment by pragnagopa** [comment]
Will look into this.

**Comment by pragnagopa** [comment]
Most of the logs coming from functions host are missing trace properties.  All the logs need to be updated to include FunctionInvocationId, HostInstanceId and Source. Once this is fixed issue #2255 and issue #2154 might be addressed as well.

**Comment by pragnagopa** [comment]
Checked in.
