### ISSUE TITLE
Azure timer function. 

### ISSUE THREAD

**Issue by komainu85** [Azure/azure-functions-host#2317]
I'm actually experiencing an issue currently with one of my timer functions. It should run ever hour with this hourly schedule "0 0 ", it works for a few hours then stops. A restart starts it working again, after a few hours it stops again. Sometimes it can run twice in an hour, with a few minutes gap.

Investigative information

Please provide the following:

Asked to create new issue of this is still happening, issue #2158

Function App version (1.0 or 2.0-beta): 1.0.11388.0
Function App name: MikeRetweetBot
Function name(s) (as appropriate): Retweet
Region: UK South
Expected behavior

The function should run every hour.

Actual behavior

Runs every hour for a few hours, then the function stops running. At times the function can fire twice within an hour within a few minutes of the previous run, ignoring the schedule. Ive also seen the function run up to 20 minute late of the schedule.

**Comment by komainu85** [comment]
Have another example. This Function App should run every hour on on the hour. It does run on the hour everytime, however it does run a few minutes before the hour too. So it runs a second time which doesnt match the cron. "schedule": "0 0 * * * *",


Function App version (1.0 or 2.0-beta): 1.0.11469.0
Function App name: KomainuRetweetBot
Function name(s) (as appropriate): Retweet
Region: UK South

**Comment by mhoeger** [comment]
@komainu85 Thanks for providing detailed information! I'm looking into this now. If you have any specific time ranges that you've noticed this behavior for either app, that would be helpful. Thanks for your patience!

**Comment by komainu85** [comment]
Hi @mhoeger

mikeretweetbot is the best to look at. It should be firing every hour, but if you check any day you can see it runs at very random times. It’s consistently running at the wrong times.

**Comment by mhoeger** [comment]
It looks like your timer function is configured to run on startup, which explains why the function is running at random times. You may have code that looks like this, which runs the funciton immediately on startup then follows the schedule thereafter: `[TimerTrigger("0 0 * * * *", RunOnStartup = true)] `
There are more details [here](https://github.com/Azure/azure-webjobs-sdk-extensions) under "TimerTrigger" around the Timer trigger attribute). 

We're also seeing some user code failures in our logs, which would cause the function to sometimes not execute (for example, at 2018-01-18 19:59:47.4464144).

Please let us know if these two things don't seem to correct your problem!

**Comment by komainu85** [comment]
@mhoeger  Looking at the logs inside the portal, i dont see the failures. It looks like the function hasn't ran. It should run every hour but there are huge gaps between the logs for some reason.


Retweet (2018-01-22T06:00:0 ...) |   | 3 hours ago | (660 ms) |  
Retweet (2018-01-22T05:59:3 ...) |   | 3 hours ago | (3,375 ms) |  
Retweet (2018-01-22T05:00:0 ...) |   | 4 hours ago | (638 ms) |  
Retweet (2018-01-22T04:59:3 ...) |   | 4 hours ago | (3,159 ms) |  
Retweet (2018-01-21T22:00:0 ...) |   | 11 hours ago | (1,100 ms) |  
Retweet (2018-01-21T21:59:3 ...) |   | 11 hours ago | (3,545 ms) |  
Retweet (2018-01-21T21:00:0 ...) |   | 12 hours ago | (811 ms) |  
Retweet (2018-01-21T20:59:3 ...) |   | 12 hours ago | (3,620 ms) |  
Retweet (2018-01-21T18:00:0 ...) |   | 15 hours ago | (690 ms) |  
Retweet (2018-01-21T17:59:3 ...) |   | 15 hours ago | (2,908 ms) |  
Retweet (2018-01-21T04:00:0 ...) |   | a day ago | (827 ms) |  
Retweet (2018-01-21T03:59:3 ...) |   | a day ago | (3,167 ms) |  
Retweet (2018-01-20T15:00:0 ...) |   | 2 days ago | (336 ms) |  
Retweet (2018-01-20T14:59:3 ...) |   | 2 days ago | (3,875 ms) |  
Retweet (2018-01-20T14:00:0 ...) |   | 2 days ago | (1,152 ms) |  
Retweet (2018-01-20T13:59:3 ...) |   | 2 days ago | (3,537 ms) |  
Retweet (2018-01-20T12:00:0 ...) |   | 2 days ago | (704 ms) |  
Retweet (2018-01-20T11:59:3 ...) |   | 2 days ago | (3,274 ms) |  
Retweet (2018-01-20T08:00:0 ...) |   | 2 days ago | (304 ms) |  
Retweet (2018-01-20T07:59:2 ...) |   | 2 days ago | (3,174 ms)

**Comment by mathewc** [comment]
@komainu85 I've investigated this issue and I believe we may have a bug, brought on by your use of EasyAuth. Do you have EasyAuth configured for this Function App? Since the app only contains a TimerTrigger currently, I wouldn't think EasyAuth would give you anything.

You could try disabling EasyAuth (if that is possible for you) and verify that the function returns to its proper schedule. You should also **remove the RunOnStartup** configuration from your attribute. If you can't disable EasyAuth, you could also try adding an application setting in the portal **WEBSITE_USE_PLACEHOLDER** to 0. If you can do either of these, it would help to confirm my theory on the nature of the bug.

**Comment by komainu85** [comment]
@mathewc Great, thanks for the update. I will make those changes now, ill let you know the outcome.

**Comment by komainu85** [comment]
@mathewc just checked and there is no Authentication on the function app. I created the function app by publishing from Visual Studio 2017, creating a new function app with the standard options.

I have added in WEBSITE_USE_PLACEHOLDER to 0 so ill see if that works. I've removed the RunOnStartUp flag too.

**Comment by mathewc** [comment]
FYI - I've fixed the underlying issue in https://github.com/Azure/azure-webjobs-sdk-script/pull/2346 and that fix will be in the next release.

**Comment by komainu85** [comment]
Thanks great news, thanks :)

**Comment by mhoeger** [comment]
Closing this issue. Thanks Mathew!
