### ISSUE TITLE
Function proxies json schema missing "comment" attributes on all levels / all subojects

### ISSUE THREAD

**Issue by amadl** [Azure/azure-functions-host#2337]
Function proxies json schema missing "comment" attributes on all levels / all subojects

#### Investigative information

2018-01-20

Function App version (1.0and 2.0-beta)
Function Proxies
Region: all

#### Repro steps

Provide the steps required to reproduce the problem:

Try to add additional comment attributes in a proxies.json file, you get an error when proxy definitions get loaded by the Function.

#### Expected behavior

Let us use additional "comment" attributes on all levels of the proxies.json.

#### Known workarounds

none

#### Related information 

Sample:

> {
>     "$schema": "http://json.schemastore.org/proxies",
>     "proxies": {
>         "appl_v1_Form('formname_formversion')_Redirect": {
>             "matchCondition": {
>                 "route": "/%ENVIRONMENT_APPL%/v1/Form('{formname}/{formversion}')/Redirect",
>                 "methods": ["GET"],
>                                 "comment": "HERE GOES MY COMMENT"
>             },
>             "backendUri": "https://%LOGICAPP-aim-ail-v1-frm-rdr-lap%",
>                     "comment": "HERE GOES ANOTERH COMMENT",
>             "requestOverrides": {
>                 "backend.request.method": "post",
>                 "backend.request.headers.Appl-Version": "v1",
>                 "backend.request.headers.Appl-Home": "https://{request.headers.DISGUISED-HOST}/%ENVIRONMENT_APPL%/v1/",
>                 "backend.request.headers.Entity-Name": "Form",
>                         "comment": "AND ANOTHER COMMENT", ......

**Comment by christopheranderson** [comment]
Please move this to a milestone after you've investigated.

**Comment by safihamid** [comment]
This is already working.

The key name is "desc".

here is a sample:

{
  "proxies": {
    "proxy1 - Simple Get Case": {
      "desc": 
      	[
          "Here is",
          "Just a",
          "Proxy description"
        ],
      "matchCondition": {
        "methods": [
          "GET"
        ],
        "route": "/ip"
      },
      "backendUri": "https://someapp.azurewebsites.net/api/ip"
    }
  }
}

And here is the schema definition:

      "properties": {
        "desc": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },

**Comment by amadl** [comment]
Thank a lot !
