### ISSUE TITLE
Investigate cold start NGEN replacement for v2

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-host#2353]
* Measurement current V1, V2 cold start: **Done**
* Looking on V2 in Visual Studio profiler, comparison V1 and V2 using Visual Studio profiler: **Done**
* Investigating CrossGen (NGEN replacament): **In porcess**
* Investigating Linker for NET Core: **Not Started**
* Investigating NET Core Native: **Not Started**

**Comment by fabiocav** [comment]
This needs to be a little less prescriptive and, for the initial work, more generic to track performance/cold start investigations for V2 in general.
