### ISSUE TITLE
Function v2 unable to add EFCore migration

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-functions-host#2366]
#### Investigative information

VS2017 15.5.4
Azure Functions and Web Jobs Tools 15.0.40108.0

#### Repro steps

1. Create new Azure Function project
1. Choose v2 option
1. Add Nuget package Microsoft.EntityFrameworkCore.SqlServer 2.0.0
1. Add Nuget package Microsoft.EntityFrameworkCore.Tools 2.0.0
1. Manually add Microsoft.EntityFrameworkCore.Tools.Dotnet 2.0.0 to CSPROJ file
1. Create a migration

#### Expected behavior

Empty migration is added (note: this error occurs if it is not empty as well)

#### Actual behavior

Receive error message

> Startup project 'FunctionApp1' targets framework '.NETStandard'. There is no runtime associated with this framework, and projects targeting it cannot be executed directly. To use the Entity Framework Core Package Manager Console Tools with this project, add an executable project targeting .NET Framework or .NET Core that references this project, and set it as the startup project; or, update this project to cross-target .NET Framework or .NET Core.

#### Related information 
This issue may be related to https://github.com/aspnet/EntityFrameworkCore/issues/8452

<details>
<summary>Function1.csproj</summary>

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.6" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.Dotnet" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```
</details>

**Comment by DibranMulder** [comment]
It is actually possible, I wrote a Blogpost about it. You should add a netcoreapp target framework.
For more information check the entire blogpost.

<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netcoreapp2.0.7;netstandard2.0</TargetFrameworks>
    </PropertyGroup>

    ...

</Project>
https://dibranmulder.github.io/2018/08/23/Azure-functions-V2-with-EF-Core/

**Comment by jeffhollan** [comment]
Here's another blog post detailing using entity framework core with Azure Functions https://dev.to/azure/using-entity-framework-with-azure-functions-50aa

**Comment by MisinformedDNA** [comment]
@jeffhollan From your post, I wish there was a more elegant solution than

```xml
<Target Name="PostBuild" AfterTargets="PostBuildEvent">
  <Exec Command="copy /Y &quot;$(TargetDir)bin\$(ProjectName).dll&quot; &quot;$(TargetDir)$(ProjectName).dll&quot;" />
</Target>
```

If the only difference is the "bin" folder, could we just delete the "bin" folder? For compatibility reasons, I'm going to guess the answer is no, but could we just override the "OutDir" property (or something else), so it is outputted in the right location in the first place? Or is the copy necessary?
