### ISSUE TITLE
Reduce default stdout logging verbosity in V2 runtime

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#2377]
This is an issue for Linux containers in App Service as all the stdout logs from the container are written to an unstructured text log file. The runtime stdout logs at the moment are very verbose (multiple logs per request/function invocation) and causes that log file to grow very rapidly eating up disk space and causing workers to run out of space.

**Comment by christopheranderson** [comment]
This is pretty configurable, so this should be simple. @brettsam

**Comment by brettsam** [comment]
@ahmelsayed can you give an example of the logs you want to turn off? We should be able to add an explicit filter to remove just about any category of logging. I can help with that.

**Comment by paulbatum** [comment]
@brettsam I would focus on reducing verbosity such that there arent log entries in stdout for every successful function execution.

**Comment by paulbatum** [comment]
This is done. The console logger was removed.
