### ISSUE TITLE
.NET 4.7.1 doesn't work on Win10 (v 1511 and 1607)

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-functions-host#2381]
.NET 4.7.1 cannot be installed on Win10 v1511 and v1607. This prevents users from upgrading the tooling. See also https://github.com/Azure/azure-functions-core-tools/issues/369

**Comment by davidebbo** [comment]
The other issue properly tracks this, so no need to have one here. But realistically, we just need to move forward and make the Windows update a requirement at this point.

**Comment by MisinformedDNA** [comment]
Is there a reason 4.7.1 needed to be adopted? There wasn't an attached issue that stated why this was necessary.

Also, given that 1607 is supported until October, and enterprises love to hold back releases, this is a pretty bad breaking change for us.

**Comment by davidebbo** [comment]
Can you please move conversation to the main issue so it doesn't get fragmented? Thanks!
