### ISSUE TITLE
Loading Jar-files from /lib in the function app root 

### ISSUE THREAD

**Issue by kevinhillinger** [Azure/azure-functions-host#2382]
Feature request to support jar files being loaded from a `lib` folder in function app root, so that fat jars are not required.

This is cross-referencing [this issue](https://github.com/Azure/azure-functions-java-worker/issues/48) in the azure-functions-java-worker repo.

**Comment by christopheranderson** [comment]
This issue was moved to Azure/azure-functions-java-worker#54
