### ISSUE TITLE
Queue triggered function not triggering when on idle

### ISSUE THREAD

**Issue by spplante** [Azure/azure-functions-host#2383]
I have a storage queue triggered function that I though was working perfectly fine. However, I recently realized that after a while the function seems to go in "idle" and stops getting triggered even if there is multiple messages stacked in the queue. The strange thing is, If I log in to the azure portal and go click on the actual function, it "wakes" it up and then the function starts processing the stacked messages with success. This seems to happen when : 

- We redeploy the function (Our package uses ARM templates, but we do delete/reupload the function's content with a custom script)

- Whenever the function has been inactive for 30+ minutes.

This particular problem seems to be documented in multiples threads but none of them have a working solution, I just don't get how this isn't a major issue yet.  We do NOT use any "connection string", we use app settings like documented instead. 

#### Investigative information

I have no invocation ID since it is not being triggered, I can provide the function name if required but would prefer not sharing it on GitHub.

#### Repro steps

- Deploy an queue triggered function using ARM templates
- Do NOT physically access the function using the UI
- Add a message to the queue
- The function should not be triggered

**Comment by paulbatum** [comment]
The invocation ID + region + timestamp combination is what we use to look your app up. We need this information to be able to do an investigation. Any random invocation on that function app in the last week or so is fine. You said your function is running when the portal is opened, so one of those invocations will suffice. Also, please provide a timestamp for a particular instance when you know a queue message was added but the function did not run.

**Comment by spplante** [comment]
Ah, gotcha.

Here it is : 

2018-02-05T19:48:47.738 Function started (Id=cda1d688-1e99-43e2-bffc-e26db0cf4f23)

**Comment by spplante** [comment]
@paulbatum, I am so sorry I clean-redeployed the whole resource group by accident, so guids obviously just changed. Anyway I problem is still there with the freshly created RG, so here is the correct info now  :

2018-02-05T20:22:14.000 Function started (Id=16d860fd-44ff-4cbd-9f1a-c8da4b0b0917)

**Comment by davidebbo** [comment]
@spplante how are you deploying your content in your script?

**Comment by spplante** [comment]
@davidebbo, we basically use the publishing username/password to deploy the content directly to wwwroot using the REST API, here is what the PowerShell code looks like :

```Powershell
# Zips the 'AppContent' 
$localDirectoryPath = join-Path -path $WorkingDirectory -childpath "AppContent";
Zip-AzureFunction -LocalDirectoryPath $localDirectoryPath -OutputPath $deployzip


# Retrieves the publish profile credential
Write-Output ("Retrieving publish profile credentials...");
$creds = Invoke-AzureRmResourceAction -ResourceGroupName $ResourceGroupName -ResourceType Microsoft.Web/sites/config -ResourceName $AzureFunctionName/publishingcredentials -Action list -ApiVersion 2015-08-01 -Force;
$username = $creds.Properties.PublishingUserName
$password = $creds.Properties.PublishingPassword


# Deletes the previous function's content
Delete-AzureFunctionContent -PublishingUsername $username -PublishingPassword $password -FunctionAppName $AzureFunctionName -LocalDirectoryPath $localDirectoryPath


# Deploys the azure function's content
Write-Output ("Uploading files ...");

$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $username,$password)));
$apiUrl = "https://$AzureFunctionName.scm.azurewebsites.net/api/zip/site/wwwroot";
Invoke-RestMethod -Uri $apiUrl -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} -Method PUT -InFile $deployzip -ContentType "multipart/form-data";
```

**Comment by davidebbo** [comment]
@spplante don't use that zip API, which is not meant for deployment and does not sync triggers. It also doesn't carry deletions, so it will not work correctly in a number of ways. May I ask how you ended up with that?

Instead, use the [zipdeploy API](https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file), which will do the right thing.

**Comment by spplante** [comment]
@davidebbo, how I ended up with that is a good question, probably because the fourth result when searching for « Azure function deploy files PowerShell » is a full article from a former MVP (Mark Heath) explaining how to use the Kudu REST API to deploy files to your azure function :

https://markheath.net/post/deploy-azure-functions-kudu-powershell

It’s been a couple of months since we created that code but back in the days this is what we found which doesn’t sound like a bad idea since using kudu is what I would do via the UI, so it all made sens.

Otherwise, after looking at the article you provided it seems like the way to go, it does say that it supports « triggers sync » and it also support deletion, which we had to code by ourselves using the previous API.

Will try this out shortly and come back here to confirm that everything works :)

Thanks!

**Comment by davidebbo** [comment]
@spplante thanks for pointing me there. I left a comment.

Let me know if you have questions with zipdeploy and we'll help you through it. Note that it's a POST and not a PUT.

**Comment by spplante** [comment]
@davidbbo, I confirm that everything works as expected with the /api/zipdeploy URL. Thanks!

**Comment by dallancarr** [comment]
Something quite similar on this github page bear the bottom.

https://github.com/projectkudu/kudu/wiki/REST-API#zip
