### ISSUE TITLE
Fix mutlipart in v1

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-host#2385]
backport/reimplement fix for https://github.com/Azure/azure-functions-host/issues/2009 in v2, for v1

Open question: this is a breaking change if people are already doing this handling in v1 (converting from utf8 encoding)?

**Comment by fabiocav** [comment]
Yes, this would be a breaking change.

**Comment by christopheranderson** [comment]
I move we close this as won't fix for v1.

**Comment by paulbatum** [comment]
Yes, makes sense.
