### ISSUE TITLE
Need better error message

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#2386]
From the PrimaryHostCoordinator [ProcessLeaseError method](https://github.com/Azure/azure-functions-host/blob/8c771e6a7368b5aad5cdea280ca7e099bd863e39/src/WebJobs.Script/Host/PrimaryHostCoordinator.cs#L117).

Seeing error messages like **"Host instance '003f772937479f7509ec554b9543b2ac' failed to acquire host lock lease: One or more errors occurred."** in the logs. Need to know what those "one or more errors" are :)

**Comment by paulbatum** [comment]
I think its this line in particular - it only grabs the message - if its an aggregate exception we need the details from the child exceptions.

https://github.com/Azure/azure-functions-host/blob/8c771e6a7368b5aad5cdea280ca7e099bd863e39/src/WebJobs.Script/Host/PrimaryHostCoordinator.cs#L115-L119
