### ISSUE TITLE
ServiceBus Topic message is not put in to dead-letter queue   

### ISSUE THREAD

**Issue by erkkikeranen** [Azure/azure-functions-host#2390]
I am using Function App v1.0 runtime.

Correct, expected behavior:
- Using ServiceBus Trigger **(Queue)** for javascript function places message in dead letter queue when function fails (i.e. throw exception)

- Using ServiceBus Trigger **(Topic with Subscription)** for javascript function does NOT place message in dead letter queue when function fails (i.e. throws exception). After max retries it just stops sending them (expected behavior). Message count for the given subscription shows equal to amount of failed messages like they never was delivered if I understand correctly from the portal view.

Is this a possible misconfiguration or something I don't understand? Is this related to forced (?) peek-lock behavior?

How can I have the runtime tell service bus that I want the message dead-lettered?

**Comment by christopheranderson** [comment]
@alrod, can you confirm what the expected behavior for Topics is?

**Comment by alrod** [comment]
SB trigger (Topic+Sub) puts message to dead letter queue, you need to use "`{subName}/$DeadLetterQueue`" as path. There is C# example:

```
        [FunctionName("Function1")]
        public static void Run1([ServiceBusTrigger("alrod-test-topic", "sub1", Connection = "SBConnection")]string start, TraceWriter log)
        {
            log.Info("Process message: " + start);
            throw new Exception("test");
        }

        [FunctionName("Function2")]
        public static void Run2([ServiceBusTrigger("alrod-test-topic", "sub1/$DeadLetterQueue", Connection = "SBConnection")]string message, TraceWriter log)
        {
            log.Info("Process message $DeadLetterQueue: " + message);
        }
```
