### ISSUE TITLE
Regression in Startup request handling

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#2397]
In the dev branch only (not v1.x) it seems that our "delay until host ready" logic that we had in place previously has regressed. In v1.x if you send requests to functions before the host is up and running, your requests block. In the dev branch you currently get a 404 instead.

I suspect that my commit https://github.com/Azure/azure-functions-host/commit/5fbaf462944c8fc409e47d574027aa49dc3feb1d regressed this.

**Comment by fabiocav** [comment]
That’s what I brought up today. I’m already looking at this

**Comment by mathewc** [comment]
Great - at least you have a tracking item for it now :) Let me know if I can help.
