### ISSUE TITLE
Runtime errors when parsing function.json should be more descriptive 

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#2401]
Repro: 

have a function with this function.json

```json
{
  "bindings":  [
    {
      "authLevel":  "function",
      "type":  "httpTrigger",
      "direction":  "in",
      "name":  "req",
      "methods":  "get"
    },
    {
      "type":  "http",
      "direction":  "out",
      "name":  "res"
    }
  ],
  "disabled":  false
}

```
**note the error `methods` being a string rather than an array.**

getting the function errors through `/admin/functions/{name}/status` returns 

```
Invalid cast from 'System.String' to 'Newtonsoft.Json.Linq.JArray'.
```

which is correct, but not very clear as to what's wrong. a nicer error message that refers to the problematic property would be more meaningful for the users

**Comment by paulbatum** [comment]
@ahmelsayed I wonder what the best way to go about this is... should we do runtime validation of the JSON against our schema? I suspect that is challenging from a binding extensibility perspective (unless we enforce every binding extension to be explicit about its schema).

**Comment by ahmelsayed** [comment]
yeah I agree it won't be easy to support these various bindings and schema. 

Maybe a simpler compromise would be to just categorize the error with something like 

```
Error parsing function.json: Invalid cast from 'System.String' to 'Newtonsoft.Json.Linq.JArray'.
```

It's obviously not as nice as a full schema validation error, but it at least points to where the error is. 
The problem now with the `/admin/functions/{name}/status` api is that it returns a string array. Then the UX takes every string and turns it into an error message that looks like 

```
Function ({functionName}): {error}
```

These errors are sometime indexing errors, dll binding errors, function.json parsing errors, etc. So at least a category would be helpful.

**Comment by paulbatum** [comment]
That makes a great deal of sense and should be straightforward.

**Comment by mhoeger** [comment]
@paulbatum - I think @MikeStall has already written code to do validation on function.json's! It looks like there is a bug though where we should be catching an "InvalidCastException" instead of a "FormatException". 

https://github.com/Azure/azure-functions-host/blob/03e7c2993fac214f4835ccc6ad3d507bdd347f8c/src/WebJobs.Script/Binding/Extensibility/ScriptBindingContext.cs#L113
