### ISSUE TITLE
ServiceBus trigger could not connect. Connection Attempt timeout.

### ISSUE THREAD

**Issue by MadsJakobsenDK** [Azure/azure-functions-host#2404]
Hi,

I am not sure if this is the place to ask this question, if not maybe someone could point me to a place where I can get help.

We are developing a service for several customers. For each customer we set up a resource group (see below) and deploy our application to the Azure Functions in the resource group.  The functions/application hook into some of the customers systems

With the latest release of the application (v5) on new resource group deployments the application starts throwing errors like these and is not functioning properly:

_Could not connect to net.tcp://xxxxtestservicebus.servicebus.windows.net:9354/. The connection attempt lasted for a time span of 00:00:21.0242898. TCP error code 10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond xx.xxx.127.37:9354._

Tests:
- If I deploy the same release (v5) on to an old installation (resource group), it works without errors. 
- If I deploy a release version 4 on to a new resource group it works. If a roll up to release v5, it fails.
- Nothing has changed in the resource group deployment scripts.

ResourceGroup:
- App Service Plan (S1: Standard)
-- Azure Function (trigger): ~130 service bus triggered functions
-- Azure Function (timers): ~10 timer trigger functions
- ServiceBus (Standard)
- App Insights
- Storage
- KeyVault

Azure Functions Dependencies (partial):
- Microsoft.Azure.WebJobs.ServiceBus 2.1.0-beta1
- Microsoft.NET.SDK.Functions 1.0.2
- WindowsAzure.Storage 8.3.0
- Microsoft.ApplicationInsights 2.4.0
- Microsoft.ApplicationInsights.SnapshotCollector 1.0.10

I have tried the following:
- Go through all the changes in the code from v4 to v5. Found nothing criminal :/
- Finding the commit that breaks the system, but it seems just adding more very simple functions does the trick.
- Compare a working and non-working resource group.
- Scale the app service plan to an S2 – to get more resources (mostly more sockets). Not working.
- Splitting the Azure Functions Trigger app into two Apps. Not Working
- Adding another Servicebus, splitting the topics between the two servicebusses. Not working.
- Splitting the Azure Functions Trigger app into two Apps and adding another Servicebus. Not working.

Questions:
- The last working resource group set up and working with v5 was set up in November, another resource group was set up in December. The latter one is not working with v5. 
- Has anything happened to resource group deployments using templates that could affect this?
- Has anything happened to any of the Azure Components used that could affect this?
- In particular we received an email about Azure change app service plans to run on Windows Server 2016. This started from around dec. 4th 2017.
- Are there any limitations as to how many servicebus triggered functions you can run on one app service plan?

Any suggestions how to investigate this bug is very much appreciated 😊

Thank you

Non-working resource group/Azure Function:
- Timestamp: 2018-02-08T13:46:24.075Z
- Function App version (1.0 or 2.0-beta): ~1
- Invocation ID: 0db3aca8-4ae4-41f7-b075-2b264559143b
- Region: West Europe

Working resourcegroup/Azure Function:
- Timestamp: 2018-02-01T01:01:30.982Z
- Function App version (1.0 or 2.0-beta): ~1
- Invocation ID: 016829d4-0578-4de0-ab68-a14e346ef178
- Region: West Europe

(The function invoked by the id in the working resource group are not the same as in non-working, it is merely meant to id the resourcegroup).

**Comment by MadsJakobsenDK** [comment]
Update:
---

I have tried splitting the Azure Functions Trigger App into two separate apps running on separate App Service Plans. That seems to work (we are doing a full set of tests now). That means that my working resource group looks something like this:

- App Service Plan (S1: Standard)
-- Azure Function (trigger): ~75 service bus triggered functions
-- Azure Function (timers): ~10 timer triggered functions
- App Service Plan 2 (S2: Standard)
-- Azure Function (trigger2): ~55 service bus triggered functions	
- ServiceBus (Standard)
- App Insights
- Storage
- KeyVault

I can not really work out why this works, while simply scaling to an S2 app service plan does not resolve the problem. I guess it suggests that it is not the number of sockets available on the host that is causing the problem.

**Comment by alrod** [comment]
Probably we have reached connection limit if you are using Standard plan: https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#cross-vm-numerical-limits

**Comment by MadsJakobsenDK** [comment]
Alrod
>Probably we have reached connection limit if you are using one Standard plan: https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#cross-vm-numerical-limits

MJ Initial post
> I have tried the following:
> ...
> - Scale the app service plan to an S2 – to get more resources (mostly more sockets). Not working.

Should I not be able to resolve the problem then by scaling to an S2 then? I have tried that and it does not change anything, the application breaks at the exact same place/azure function. It only works if I use two app service plans (in this case two S1s), though that actually gives fewer connections combined than an S2.

Thank you  :)

**Comment by alrod** [comment]
Sorry for late reply. Adding S1 instances is right way to solve the issue as S1 and S2 have the same number of active listen sockets:
https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#per-sandbox-per-appper-site-numerical-limits

Closed as answered.
