### ISSUE TITLE
How to do error Handling in Azure function 

### ISSUE THREAD

**Issue by mihirkadam** [Azure/azure-functions-host#2405]
I have created a simple Azure function to read data from Queue and write into Cosmos DB.  I have few queries regarding error handling. How to read data from Dead letter queue using the Azure function? Is there any better way to do error handling?
![azure queue](https://user-images.githubusercontent.com/10244487/36022275-86d48da8-0dae-11e8-9532-e47a21d1973c.png)

**Comment by pragnagopa** [comment]
Here is the documentation on error handling: [Azure Functions error handling](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages).  Retries are built into queue triggers and if there are failures, messages are moved to Poison-queue. You can setup [an azure function to process poison queue messages](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue#trigger---poison-messages). Same goes for dead letter queue.

**Comment by mihirkadam** [comment]
Thanks @pragnagopa for sharing information. 👍

**Comment by pragnagopa** [comment]
@mihirkadam - closing this issue. Please reactivate if you still need help with a specific scenario
