### ISSUE TITLE
What is the purpose of eventHub.prefetchCount?

### ISSUE THREAD

**Issue by tobiasb** [Azure/azure-functions-host#2423]
The purpose of the configuration value `eventHub.prefetchCount` is not clear to me. The [documentation ](https://github.com/Azure/azure-functions-host/wiki/host.json) of host.json says "The default PrefetchCount that will be used by the underlying EventProcessorHost." but that isn't very helpful either.

What is it used for?

**Comment by christopheranderson** [comment]
This is passed to the Service Bus SDK for Event Hubs - https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.messagereceiver.prefetchcount?view=azure-dotnet#Microsoft_ServiceBus_Messaging_MessageReceiver_PrefetchCount

It's effectively how many messages can be read off at once. (this doesn't mean we'll run them all, as we still process batches in order, but it's a tuning knob for how much to fetch before the next batch starts)
