### ISSUE TITLE
Function Proxy not found when using a route variable for the server segment of the backendUrl 

### ISSUE THREAD

**Issue by shannoncarver** [Azure/azure-functions-host#2432]
Function Proxies:

I’m trying to use a variable in my backend url for the server segment that is defined in the Function Proxy route template.  On the portal it seems to accept  this setup by when I try to run locally using “func host start” in the azure-functions-core-tools, the function proxy is not found and fails to establish a listener for it.  

Here is my proxies.json file:

{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
        "testproxy": {
            "matchCondition": {
                "route": "testapp/api/{host}/{controller}/{action}"
            },
            "backendUri": "http://{host}/testapp/{controller}/{action}"
        }
    }
}

Where {host} is the variable for the backend url server segment

**Comment by paulbatum** [comment]
@safihamid any ideas on this one?

**Comment by safihamid** [comment]
This is by design, we do not support variables in host section of the backendUri address. in your example above http://{host var}/... is not supported. 

I agree, we should return a better error here. you should see the error in AppInsights and we are working on a better error reporting in V2.
