### ISSUE TITLE
Fix flaky hosthealthmonitor test

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#2441]
The test `ScriptHostManagerTests.HostHealthMonitor_TriggersShutdown_WhenHostUnhealthy` flaked out here:
https://ci.appveyor.com/project/appsvc/azure-webjobs-sdk-script-y8o14/build/1.0.11539/tests

**Comment by brettsam** [comment]
Also it looks like `IsHostHealthy_ReturnsExpectedResult` is having issues: https://ci.appveyor.com/project/appsvc/azure-webjobs-sdk-script-y8o14/build/20180223-0600/tests.

Lumping these together since they seem related, but we can split them out into separate issues if needed.

**Comment by mathewc** [comment]
IsHostHealthy_ReturnsExpectedResult was broken by my last commit and I'm checking in a fix presently. This issue can remain open for the original flaky test though.

**Comment by brettsam** [comment]
I have a fix for this one as well, so stealing it away (#2533)
