### ISSUE TITLE
Fix flaky StandbyManager test

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#2442]
The test `StandbyManagerTests.StandbyMode_EndToEnd` flaked out here:
https://ci.appveyor.com/project/appsvc/azure-webjobs-sdk-script-y8o14/build/20180213-1531/tests
https://ci.appveyor.com/project/appsvc/azure-webjobs-sdk-script-y8o14/build/20180213-0000/tests

**Comment by brettsam** [comment]
I'm going to steal this; I think I may know what's going on. I've added some logging to verify. Feel free to steal back if you had already looked at it.

**Comment by brettsam** [comment]
Closed with #2508
