### ISSUE TITLE
Provide a lock file with V1 dependencies

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#2446]

**Comment by forki** [comment]
In https://github.com/fsprojects/Paket/pull/3062 I will try to implement Paket's part in that story.

**Comment by fabiocav** [comment]
@forki finally got around to drafting something up. Can you take a look at this and provide some feedback?

https://gist.github.com/fabiocav/8fcccd4d54ec298e3b120cbc1230c02a

**Comment by forki** [comment]
cool. 

I added docs for the new paket feature: https://fsprojects.github.io/Paket/dependencies-file.html#External-lock-files 

Next steps: 

1) test in real project (will do that soon)
2) put the file on some trusted resource (and rename packet to paket ;-) )
3) make it official with some nice post where we explain it together (cc @isaacabraham)

**Comment by fabiocav** [comment]
Great!

> put the file on some trusted resource (and rename packet to paket ;-) )

My fingers kept going back to "packet", I got it right most of the time, just not where it mattered :) I'll put this up on the repo once we validate (with the right name) so you can consume it from there.

**Comment by fabiocav** [comment]
@forki I'm assuming you've had a chance to validate the lock file. I'll move ahead and add this to the host repo so we can close this issue.

**Comment by forki** [comment]
Our CI found inconsistencies in the lock file. I hope I can validate that later today.

**Comment by fabiocav** [comment]
Closing as done in #2674 

Will follow up if you manage to find any issues.
