### ISSUE TITLE
Azure Function on Consumption plan quits triggering off of Azure Blob Storage Trigger

### ISSUE THREAD

**Issue by shudson302** [Azure/azure-functions-host#2462]
The name of my app is generatethumbs. It triggers off of a storage account when a blob is created, it calls computer vision api to generate a thumb and outputs that image back to the storage account under a different container.

It works fine while I have the azure portal open. But if I close the azure portal and quit inserting blobs, then after a while it will quit triggering off of new blobs in the storage account. If I then open the azure portal and look at the logs, then all of the ones that didnt run will start and run successfully.

#### Investigative information

Please provide the following:

- Timestamp: 2018-02-25T16:02:48 plus or minus an hour
- Function App name: generatethumbs
- Function name(s) (as appropriate): BlobTriggerCSharp1
- Invocation ID:
- Region: Central US

Here is a log from one that ran successfully
2018-02-25T17:07:32.416 [Info] Function started (Id=214cc962-eb03-4ac6-995f-8c4708d00c75)
2018-02-25T17:07:32.963 [Info] C# Blob trigger function Processed blob
 Name:bdd43bfe-c709-4990-97ec-fee86a552c01 
 Size: 88752 Bytes
2018-02-25T17:07:34.416 [Info] Function completed (Success, Id=214cc962-eb03-4ac6-995f-8c4708d00c75, Duration=1995ms)

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a consumption mode function app
2. Create a function that triggers off of Azure Blob Storage with parameter name= inputBlob and Path= images/{name}
3. Create an output for the function of Azure Blob Storage with parametername=thumbnailBlob, use function return value off, and path=thumbs/{name}
4. Code is below

#### Expected behavior

When I save a blob to my storage account in the images container, this function should run and create a thumbnail and save it to my storage account in the thumbs container

#### Actual behavior

The function works properly for a time period.  However if there is a period of inactivity, like over the weekend where no blobs are saved, then the function stops running when a blob is uploaded to the images container

#### Known workarounds

If I open the azure portal and look at the function and open the logs,  It will then run all of the triggers that didnt run, and  I will then see a log that all of the missing triggers ran

#### Related information 

Provide any related information 

code is in C#

<details>
<summary>Source</summary>

```
using System.IO;
using System.Net.Http;
using System.Net.Http.Headers;
public static void Run(Stream inputBlob, string name, Stream thumbnailBlob, TraceWriter log)
{

        log.Info($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {inputBlob.Length} Bytes");


        string SubscriptionKey = "6f708b7a816745588b88b595c8ab293a";
        string uriBase = "https://eastus.api.cognitive.microsoft.com/vision/v1.0/generateThumbnail";


        

        HttpClient client = new HttpClient();

        // Request headers.
        client.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", SubscriptionKey);

        // Request parameters.
        string requestParameters = "width=150&height=150&smartCropping=true";

        // Assemble the URI for the REST API Call.
        string uri = uriBase + "?" + requestParameters;

        HttpResponseMessage response;

        // Request body. Posts a locally stored JPEG image.
    
        byte[] thumbnailImageData = null;
        using (HttpContent content = new StreamContent(inputBlob))
            {
            // This example uses content type "application/octet-stream".
            // The other content types you can use are "application/json" and "multipart/form-data".
            content.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");

            // Execute the REST API call.
            response = client.PostAsync(uri, content).Result;

            if (response.IsSuccessStatusCode)
            {
                // Display the response data.
                Console.WriteLine("\nResponse:\n");
                Console.WriteLine(response);

                // Get the image data.
                thumbnailImageData = response.Content.ReadAsByteArrayAsync().Result;
                    thumbnailBlob.Write(thumbnailImageData, 0, thumbnailImageData.Length);
            }
            else
            {
                // Display the JSON error data.
                        log.Info($"C# Blob trigger function Error:{response.Content.ReadAsStringAsync().Result} \n ");
                        }
        }

}
```

</details>

**Comment by davidebbo** [comment]
Is 2018-02-25T16:02:48 the time where a blob was added and the function didn't get called? From the logs, there were a bunch of calls to BlobTriggerCSharp1 around that time.

**Comment by shudson302** [comment]
No, that is just the timestamp of when one ran successfully.  I do not have a timestamp of when one was not added.  Maybe by tomorrow I can reproduce the issue and get you a timestamp when it did not function properly and I will post it here.

**Comment by davidebbo** [comment]
That will be helpful, thanks.

**Comment by davidebbo** [comment]
From our logs, the function was triggered 4 times around 2018-02-26 13:22:32. Note that there can be a delay with Blob triggers. See [doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob) for details on this.
