### ISSUE TITLE
EndToEndTimeoutTests Hanging

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#2463]
These tests currently hang indefinitely when run. I can see this when trying to run them locally via VS, and it also looks like they may be hanging on AppVeyor, even though the tests runs are coming back green.

E.g. here's a [v1.x test run](https://ci.appveyor.com/project/appsvc/azure-webjobs-sdk-script-y8o14/build/1.0.11562), and if do a search in the tests for "TimeoutTest_UsingToken_CSharp" you'll see it ran to completion. If you do the same search on [a v2 test run](https://ci.appveyor.com/project/appsvc/azure-webjobs-sdk-script-y8o14/build/2.0.11554) you won't find the test.

I think timeouts may be broken in v2. I've disabled the tests, referencing this issue.

**Comment by mathewc** [comment]
These are still hanging. @fabiocav's theory is that AppVeyor machines are not very robust, and these tests block the calling thread and xunit is running in a single threaded context, causing hangs.

**Comment by fabiocav** [comment]
This seems to be resolved. Closing again.
