### ISSUE TITLE
Function is shown as disabled while its disabled property is mapped to an application setting

### ISSUE THREAD

**Issue by huangyingting** [Azure/azure-functions-host#2471]
Repro steps

Create an azure function in visual studio 2017. It does not matter what sort of azure function and use Disable attribute like below code:

        [Disable("FunctionDisabled")]
        public static async Task Run(
            BrokeredMessage message,...)
        {
...
        }

And define the FunctionDisabled application setting inside the app settings with value false. When you publish it, you will get a compiled function.json like below:
{
  ...,
  "disabled": "FunctionDisabled"
}

While this work as expected (if you set FunctionDisabled=true, it disables the function and if false or not present, the function is enabled), it causes the UI to show the function as disabled all the time like the image below

**Comment by MrGlenThomas** [comment]
I have 2 timer triggered functions, each disabled using their own disabled app setting, I have one set to "False" and one set to "True", both are showing as "(disabled)" in the portal, but both are executing...

**Comment by mathewc** [comment]
Related to https://github.com/Azure/azure-functions-ux/issues/949. Portal doesn't currently support this feature properly.
