### ISSUE TITLE
What do UnableToLoadExpressionAssembly traces mean?

### ISSUE THREAD

**Issue by simonness** [Azure/azure-functions-host#2481]
Hi,

I have a Function App with just 4 proxies (no other functions).  When creating the proxies manually in the portal or publishing a `proxies.json` from Visual Studio I always see the Error level trace message `UnableToLoadExpressionAssembly` in Application Insights every time the Function warms up (i.e. shortly after the Information trace `Starting Host`).

I've set up some Availability Tests and see no issue with the expected behaviour of the underlying application, all HTTP requests are served with a 200 response.  Should I be concerned with this error level message?

#### Investigative information

Please provide the following:

- Timestamp: 2018-03-04T15:52:19.001 (UTC) (Trace timestamp)
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name: -
- Function name(s) (as appropriate): -
- Invocation ID: can't provide this as no functions to execute
- Region: West Europe

#### Repro steps

The `proxies.json` file contents:

```
{
    '$schema': 'http://json.schemastore.org/proxies',
    'proxies': {
        'WebApp': {
            'matchCondition': {
                'route': '/{*restofpath}'
            },
            'backendUri': 'https://someblobstorage.blob.core.windows.net/public/index.html',
            'responseOverrides': {
                'response.headers.X-Frame-Options': 'DENY'
            }
        },
        'WebFavIcon': {
            'matchCondition': {
                'route': '/favicon.ico'
            },
            'backendUri': 'https://someblobstorage.blob.core.windows.net/public/favicon.ico'
        },
        'WebStaticContent': {
            'matchCondition': {
                'route': '/static/{*restofpath}'
            },
            'backendUri': 'https://someblobstorage.blob.core.windows.net/public/{restofpath}'
        },
        'WebAppIFrame': {
            'matchCondition': {
                'route': '/iframe/{*restofpath}'
            },
            'backendUri': 'https://someblobstorage.blob.core.windows.net/public/index.html'
        }
    }
}
```

#### Expected behavior

No Error level trace messages in Application Insights.

#### Actual behavior

`UnableToLoadExpressionAssembly` Error level trace messages in Application Insights.

#### Known workarounds

None known.

#### Related information 

n/a

**Comment by brettsam** [comment]
Is that the full error message that you see? Are there any other traces?

**Comment by simonness** [comment]
Hi @brettsam, thanks for taking a look!

Yeah `UnableToLoadExpressionAssembly` is the entire trace message:

```
customDimensions | {"prop__{OriginalFormat}":"UnableToLoadExpressionAssembly","LogLevel":"Error","Category":"Host.Startup"}
```

It comes out around other info level cold start traces...

```
2018-03-20T07:15:38.642 | Function completed (Success, Id=e941acac-d706-413e-aa7e-04bceae0c073, Duration=492ms)
2018-03-20T07:15:38.171 | Job host started
2018-03-20T07:15:38.171 | Executing request via Azure Function Proxies
2018-03-20T07:15:38.161 | Function started (Id=e941acac-d706-413e-aa7e-04bceae0c073)
2018-03-20T07:15:38.142 | Found the following functions: Host.Functions.*** Host.Functions.*** Host.Functions.*** Host.Functions.*** Host.Functions.*** Host.Functions.***
2018-03-20T07:15:38.111 | Generating 6 job function(s)
2018-03-20T07:15:36.908 | UnableToLoadExpressionAssembly
2018-03-20T07:15:36.648 | Initializing Azure Function proxies
2018-03-20T07:15:36.238 | Loaded custom extension 'BotFrameworkConfiguration'
2018-03-20T07:15:36.238 | Loaded custom extension 'SendGridConfiguration'
2018-03-20T07:15:36.238 | Loaded custom extension 'EventGridExtensionConfig'
2018-03-20T07:15:36.143 | Host configuration file read: {}
2018-03-20T07:15:36.143 | Reading host configuration file 'D:\home\site\wwwroot\host.json'
2018-03-20T07:15:36.125 | Starting Host (HostId=***, Version=1.0.11612.0, InstanceId=25680c5f-d437-4651-ad8d-ed96375922b6, ProcessId=6036, AppD 
```

Hopefully, it should be easily reproducible (I get it with several Function Apps with only proxies).  I suspect the error trace isn't important, but can be a bit annoying for alerting / monitoring purposes.

**Comment by brettsam** [comment]
@safihamid -- have you ever seen this message logged with proxies?

**Comment by safihamid** [comment]
This error can be ignored. It is trying to load System.IO.FileSystem in Proxy code but can't find it in the Functions runtime's bin folder. However this dll is no longer needed.

I have updated the Proxy code for this but doesn't justify a new release. it will be released, if there are other proxy changes in v1 needed.

**Comment by simonness** [comment]
Thanks very much for the confirmation @safihamid, happy to close this one.
