### ISSUE TITLE
Using an input table binding with a SAS connection string fails with message: No blob endpoint configured

### ISSUE THREAD

**Issue by CarlosSardo** [Azure/azure-functions-host#2483]
When using an input table binding with a SAS connection string fails with:

The following 1 functions are in error:
[5-3-2018 15:38:58] TableInput: Microsoft.Azure.WebJobs.Host: Error indexing method 'ImporterFunctions.TableInput'. **Microsoft.Azure.WebJobs.Host: No blob endpoint configured**.

#### Investigative information

Please provide the following:

- Timestamp: 5-3-2018
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name: (running locally)

```csharp
[FunctionName("TableInput")]
        public static void TableInput(
            [QueueTrigger("xxx")] string input,
            [Table("xxx", Connection = "InputTableStorageSAS")] IQueryable<SomeType> items,
            [DocumentDB("xxx", "xxx", Id = "xxx", ConnectionStringSetting = "CosmosDb", CreateIfNotExists = true)] ICollector<dynamic> cosmosData,
            TraceWriter log)
        {

        }
```

```json
"InputTableStorageSAS": "TableEndpoint=https://xxx.table.core.windows.net;SharedAccessSignature=st=2018-03-04T16%3A38%3A00Z&se=2018-03-07T16%3A38%3A00Z&sp=r&sv=2017-04-17&tn=xxx&sig=XXXXXXXXXXXXXX"
```

**Comment by pragnagopa** [comment]
You need to provide a connection string with full permissions to the storage account, because tables and queues in the account will also be used - From issue [#199](https://github.com/Azure/Azure-Functions/issues/199)
