### ISSUE TITLE
Malformed JSON input causes the function to never complete

### ISSUE THREAD

**Issue by JunyiYi** [Azure/azure-functions-host#2490]
#### Investigative information

Please provide the following:

- Function App version (1.0 or 2.0-beta): 2.0-beta (Java)

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a function app (in Java)
2. Create an HTTP Trigger function
3. Invoke it using a malformed JSON: `{ "hello": "world", `

#### Expected behavior

At least return some useful error code, even 500 is acceptable.

#### Actual behavior

The runtime just timed out without any error messages.

#### Known workarounds

N/A

#### Related information 

* Java
* Http Trigger

**Comment by Clockwork-Muse** [comment]
Please note (I'm the poster of the original issue): I don't consider 500 to be the correct error code for invalid JSON.  The system was given invalid input, it needs to properly blame the caller for this (that is, return 400).  Importantly, _this is not behavior that the function can handle_ (at the time of reporting) - the parsing is/was happening before the function is called.

**Comment by pragnagopa** [comment]
This is fixed: https://github.com/Azure/azure-functions-host/commit/31d00498e305451cb360942515f98f695c7d85bf
