### ISSUE TITLE
ServiceBus Triggered Functions Overprovisioning

### ISSUE THREAD

**Issue by tohling** [Azure/azure-functions-host#2494]
When a ServiceBus triggered Function has scheduled/deferred messages, over-provisioning may occur.

#### Investigative information

Please provide the following:

- Timestamp: **2018-03-07 22:48:56.6519521**
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name: 
- Function name(s) (as appropriate): **PerformHardDelete**
- Invocation ID: **e36a3e06-231f-4a89-9a45-e24ab2d25bab**
- Region: **West US**

#### Repro steps
Over-provisioning is currently ongoing as customer has scheduled messages in the queue.

#### Expected behavior
New workers should be provision based on active actionable messages and not scheduled/deferred messages.

#### Actual behavior
Through Application Insights, customer is seeing a large number of servers provisioned for despite their Function App having only very low expected execution count.  I have communicated with the customer that they will only be charged for the resources consumed and not the over-provisioning.

#### Known workarounds
None.

#### Related information 
https://github.com/Azure/Azure-Functions/issues/454#issuecomment-324785962

**Comment by tohling** [comment]
We are investigating alternative approaches to address the over-scaling issue. I will update this thread with more information on the progress and ETA once I have more information.

**Comment by fabiocav** [comment]
This issue was moved to Azure/Azure-Functions#715
