### ISSUE TITLE
Code Signature Invalid

### ISSUE THREAD

**Issue by antstanley** [Azure/azure-functions-host#2495]
Downloaded the new azure-functions-host (v 2.0.1-beta.23-1) via NPM, and the code signature is invalid... causes significant issues due to the security setup on my Mac. 

The previous version had a valid signature. If I revert back to the previous version VS Code keeps telling me there is a new version available. The alternative is allow unsigned code to run on my machine.

Please update with a signed version.

**Comment by fabiocav** [comment]
This issue was moved to Azure/azure-functions-core-tools#405
