### ISSUE TITLE
C# - Calling extension method in application startup results in crash

### ISSUE THREAD

**Issue by felpel** [Azure/azure-functions-host#2502]
#### Investigative information

**Note: Local development**
- Timestamp: 01:50:00PM EST - 2018-03-09
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name: Not disclosed
- Function name(s) (as appropriate): Not disclosed
- Invocation ID: Not disclosed
- Region: Not disclosed

#### Repro steps

1. Create local Azure function project in VS;
2. Create a new C# library and reference it in the functions project;
3. Create new static class and add new public extension method;
4. Use extension method in application startup;
5. Run functions project without debugging;
6. The following error happens:

<details>
<summary>Logged exception</summary>

```bash
A ScriptHost error has occurred
[2018-03-09 6:58:05 PM] AutoVu.SaaS.Ptms.Dss.AzureFunctions: Method not found: 'Void AutoVu.SaaS.Common.AzureStorage.Extensions.ServiceCollectionExtensions.AddAzureStorage(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
```
</details>

#### Expected behavior

I should be use extension methods provided by local projects (inside my C# solution) or NuGet packages without any complication.

#### Actual behavior

The Azure functions application is unable to start and is stuck in a infinite loop trying to restart correctly.

#### Known workarounds

I was able to start correctly by directly using the code that was called in the extension method without referencing it. 

#### Related information 

* Programming language used - Only C# with:
   - .NET Framework 4.6.1 for the functions project; 
   - .NET standard 1.4 / .NET framework 4.6.1 libraries)
* Links to source - Private repository
* Bindings used - HTTP and service bus triggers

**Comment by fabiocav** [comment]
Can you share a simple repro on GitHub? Our default templates make use of extension methods, so it would be good to see exactly what you're doing.

**Comment by felpel** [comment]
Actually, we solved the problem by replacing the following references in our referenced projects:
- `Microsoft.Extensions.Caching.Memory@1.1.2` for `Microsoft.Extensions.Caching.Abstractions@1.1.2`;
-  `Microsoft.Extensions.DependencyInjection@1.1.1` for  `Microsoft.Extensions.DependencyInjection.Abstractions@1.1.1`  

We don't know why, but it seems that the resulting DLL that was used to locate those extension methods in our configuration providers wasn't at the appropriate version.

**Comment by paulbatum** [comment]
Thanks for the details. We suspected that there was not a general problem with extension methods as originally reported and that the issue was specifically about the assemblies being used in this project. Closing this as its now confirmed.
