### ISSUE TITLE
Regular 404's when call API Key Management API

### ISSUE THREAD

**Issue by DVaughan** [Azure/azure-functions-host#2507]
I'm adding API keys to one function from another (in a different functions app) by performing a PUT to:
{baseUrl}/admin/functions/{function name}/keys/{keyName}

It sometimes works. But invariably I receive a 404.

#### Investigative information

Please provide the following:

- Timestamp: Sunday 11 March 9.20 am CET
- Function App name: devices01
- Region: Western Europe

**Comment by pragnagopa** [comment]
I could not repro this issue.  our logs do not show 404's on the Function App: devices01. Can you share the app name where we you were trying to set the key?

**Comment by DVaughan** [comment]
I tried to set one just now (11.37 AM CET) using:
https://licensee.azurewebsites.net/admin/functions/AssignedLicense/keys/testlicenseeAdmin

The app name from where I was attempting to set the key is: licensor. But it was debugging locally.

**Comment by pragnagopa** [comment]
I can see the logs and can repro this issue.  I think issue would repro if admin api are being hit before scripthost finishes function indexing. Opened issue #2530. 
As a workaround, for now can you please retry on 404?

**Comment by pragnagopa** [comment]
Closing this issue as there is a tracking item
