### ISSUE TITLE
Investigate issue with NodeEndToEndTests.QueueTriggerByteArray

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#2511]
The `NodeEndToEndTests.QueueTriggerByteArray` is currently in a bad state and does not pass in CI. The issue needs to be investigated and resolved. The test is being disabled in the meantime

For more context, see:
https://github.com/Azure/azure-functions-host/pull/2503

**Comment by mhoeger** [comment]
Fails with:
"Message: System.AggregateException: One or more errors occurred. (Could not find part of the path 'c:\xxxxx\AppData\Local\Temp\Functions\Function\QueueTriggerByteArray'.)
