### ISSUE TITLE
Canceling the token passed to RunAndBlock() should wait for host to fully stop before exiting

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#2517]
Our Update/Rename and Restart tests were failing at a pretty high rate. I've fixed them (I hope) with #2498.

If you start the `ScriptHostManager` with:

`manager.RunAndBlock(cancellationToken);`

And then cancel that `cancellationToken`, the method will fire-and-forget a background task to dispose of the current `JobHost` and then exit almost immediately. You can't be certain that everything was shut down and disposed. By contrast, if you call `manager.Stop()`, the call to `Stop()` exits after the host has fully shut down.

This hurt the tests b/c the next test would start up before the previous test had actually shut down its host. In this case, it meant that the Timer Singleton locks weren't released so the expected firing of the TimerTrigger didn't occur.

We also use this pattern when running in production, so there's a chance that we're not properly releasing resources when the hosting environment signals for a shutdown.

**Comment by fabiocav** [comment]
This is not currently impacting production scenarios, and only applies to V1. Closing as "won't fix"
