### ISSUE TITLE
Invoking binding extention webhook URLs writes debug_sentinel file to disk

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-host#2520]
My understanding of the **debug_sentinel** file is that it puts the functions host into "debug" mode, enabling extra logging, etc. It seems that whenever *any* API under the /admin/ URL gets hit, we create this file. This seems bad because web hook extensions live under the /admin/ URL prefix and invoking those will put the function app into debug mode, which is not desired.

#### Investigative information

- Timestamp: **2018-03-13T17:15:00Z**
- Function App version: **1.0**
- Function App name: **dfperf-dedicated**
- Region: **West US 2**
- Hosting Plan: **Dedicated**

#### Repro steps

1. Create and deploy function app with the [Durable Functions extension.](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-overview)
2. Close all instances of the Azure Portal
3. Delete the debug_sentinel file
4. Set `"fileLoggingMode": "never"` in host.jon
5. Kill w3wp.exe
6. Ping an endpoint on the extension, e.g. 
```
https://dfperf-dedicated.azurewebsites.net/admin/extensions/DurableTaskExtension/instances/foo?taskHub=DFPerfHub&connection=Storage&code=systemkey
```

#### Expected behavior
My expectation is that the debug_sentinel file will stay deleted.

#### Actual behavior
As soon as I send the HTTP request to my endpoint, I see the debug_sentinel appear.

**Note that the request doesn't even need to be authorized**. I tried sending an invalid `code` parameter and the debug_sentinel file was still written to disk. I wonder if there is a security risk there.

**Comment by fabiocav** [comment]
@mathewc has a PR out for V1, so I'm assigning this to the current sprint. 

@mathewc, not sure if we want to have a separate issue or keep this open until a similar change is made in V2. Your call.

**Comment by mathewc** [comment]
I'll merge it to dev branch today.

**Comment by mathewc** [comment]
Corresponding dev branch commit here: https://github.com/Azure/azure-functions-host/commit/3f70b16418a67af84846a6bb50f2386824e1a475
