### ISSUE TITLE
[V2] Running on Windows .NET Core 32bit throws an access violation exception

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#2525]
Run an x86 build from here https://github.com/Azure/azure-functions-core-tools/releases/tag/2.0.1-beta.24 or using dotnet.exe 32bit throws the following exception

```
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

on this line https://github.com/Azure/azure-functions-host/blob/65183c837f3017615c184ecc45ccdb9f9ae6b2c9/src/WebJobs.Script/Rpc/ProcessManagement/JobObjectRegistry.cs#L18

**Comment by pragnagopa** [comment]
I was able to repro this. Thanks for reporting. Sent a PR with the fix.

**Comment by russgove** [comment]
So I upgraded all my azure function packages to latest version and  I still get this error . Is this supposed to be fixed?
