### ISSUE TITLE
Admin Api's on functions can cause 404's

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#2530]
Issue reported in #2507 . I think issue would repro if admin api are being hit before scripthost finishes function indexing. 
Repro:
- Create new key on an inactive funtion app (cold start)

Workaround:
Retry on 404

Here is the code that returns 404
- Function [NotFound](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/KeysController.cs#L164)

- OperationResult [NotFound](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/KeysController.cs#L192)

It would be helpful to log the reason for 404

**Comment by DVaughan** [comment]
Retry doesn't appear to help.

**Comment by pragnagopa** [comment]
@DVaughan - Can you share a simple repro?

**Comment by DVaughan** [comment]
It's happening across 3 of my function applications.
Use an HttpClient and perform a Put for a new key for a function that hasn't been recently running.

**Comment by pragnagopa** [comment]
can you try pinging any non admin api just to wake up the app before using keys api?

**Comment by brettsam** [comment]
Is this a v1 or v2 app?

**Comment by DVaughan** [comment]
How do I find that out?
It's a class library project using .NET 4.6.1, if that helps.

**Comment by pragnagopa** [comment]
V1. @DVaughan - Creating [Functions V2](https://blogs.msdn.microsoft.com/appserviceteam/2017/12/05/announcing-azure-functions-runtime-preview-2/) App is explicit action as we are still in beta.

**Comment by paulbatum** [comment]
@pragnagopa so we know this repro's on V1, what about V2?

**Comment by pragnagopa** [comment]
This reproes in V2 as well.

**Comment by mathewc** [comment]
Addressed by fix for https://github.com/Azure/azure-functions-host/issues/2861.
