### ISSUE TITLE
Add hooks for extending save/deploy operations

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-host#254]
From #234 - @isaacabraham:  

> # Developer hook
> 
> I'm assuming that you don't do a nuget restore on every function invocation, and that there must be some affinity across multiple function so that the Nuget restore only happens once? If so - expose a "hook" at the same point where this happens, that the Functions developer can do whatever they want. In this case, immediately on this hook they would then manually do what is being proposed above.
> 
> Pros: hopefully only a little work to do from the Functions side.
> Cons: every developer that uses Paket needs to do this, so the same issue as if there was no project.json support.
> WIthout either of these options, Paket might not really be viable as every invocation of every function would need to this in order to get all the dependencies. Even if they were cached on the machine, this would still adversely affect performance.

Supporting an extensible hook model for saving would allow things like Paket to be supported by the community in an easy way and also allow us to reliably add other platforms package managers like PIP for Python. It would also potentially allow for TypeScript/CoffeScript support in the portal editor.

We need to come up with a design proposal for this feature still.

**Comment by mathewc** [comment]
Related to #281 which calls for the ability to run user code on host startup/shutdown.

**Comment by christopheranderson** [comment]
I'd like us to think about this as a "should have" for rc. I think it could help address npm/package issues which we're close to punting unless we can solve them in a 1 stone N birds kind of way.

**Comment by fabiocav** [comment]
Closing this issue as we're not currently tracking this work.
