### ISSUE TITLE
Force Functions host to only use a single specified language

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-host#2541]
We need to be able to enable only 1 language at a time.

Problem:
 - We want linux containers to only support 1 language at a time
 - Today, Java provider yells when Java isn't installed (even if no java Functions are provided)

**Comment by davidebbo** [comment]
The App Setting we'll use to drive this is called `FUNCTIONS_LANGUAGE`. When it's missing, we'll continue to allow multiple languages to avoid a short term breaking change (but we should tighten this later).

**Comment by ahmelsayed** [comment]
we also need to agree on what the values will be. `c#` vs `csharp`?  I'm working on the cli now and thinking of making it accept `c#, csharp, js, javascript, py, python` and normalize them to one of `csharp, javascript, python` to go into `FUNCTIONS_LANGUAGE`

**Comment by pragnagopa** [comment]
I have submitted a [PR ](https://github.com/Azure/azure-functions-host/pull/2646)for this. 
@ahmelsayed - [languages ](https://github.com/Azure/azure-functions-host/pull/2646/files#diff-4b683e83b1bc333d908d93000ecd81f6R69)in runtime would match the language workers: node, java and dotnet

**Comment by MisinformedDNA** [comment]
I've tried 

```json
{
  "Values": {
    "FUNCTIONS_LANGUAGE": "dotnet",
  }
}
```

and

```json
{
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
  }
}
```

and I still get the error.

**Comment by gorillapower** [comment]
We have a scenario where we actually require `node` and `dotnet` function runtimes to operate simultaneously. Context: We have a function in node that is user defined and we have some other C# durable functions that manage its execution. Is there no way we could be able to allow multiple runtimes going forward?

**Comment by MisinformedDNA** [comment]
@gorillapower You should create a new issue for that and detail what you are trying to do. This seems like a very edge scenario. But notwithstanding this issue, I don't see how two runtimes would ever be possible, from a project standpoint at least.

I'd recommend just creating two separate function apps, one for C# and one for Node. Then have a C# Function call a Node Function.

**Comment by gorillapower** [comment]
Thanks @MisinformedDNA. We are using Durable Functions with a C# orchestration client that calls a nodejs activity function. So far this has worked for us, AFAIK you cannot call durable functions between separate function apps.

Without going into too much detail, we are trying to create an app the 'extends' our customers functionality by injecting custom code into their processing pipeline and so want to give them choice of using C# script or Javascript  to do this. In the background we are using C# orchestration functions to manage this processing and execute the 'users' function.

Does this mean that going forward, you will only be able to create functions in one language? For instance, currently in the Portal you can create functions across multiple languages and this is allowed.

**Comment by pragnagopa** [comment]
@gorillapower - So far this restriction only applies to Linux Function Apps. In future, we have plans to enforce one language per function app. Can please open a different issue with more details on your scenario? This will give us more understanding on requirements for multiple languages in a single app.

**Comment by gorillapower** [comment]
Thank you i have opened this issue https://github.com/Azure/azure-functions-host/issues/3161
