### ISSUE TITLE
Provide helpful error message when language isn't available

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-host#2542]
We should provide a helpful error message when we can't determine a given Function's language

Problem:
 - We don't always have all languages installed and enabled anymore
 - Users might have two languages while only 1 is enabled
 - Users might be using a language which hasn't been installed yet

**Comment by pragnagopa** [comment]
Addressed in commit #[561fc95c968b949df68ac7b790c5c5e0f13ab393](https://github.com/Azure/azure-functions-host/commit/561fc95c968b949df68ac7b790c5c5e0f13ab393)
