### ISSUE TITLE
Improve file copy reliability on extension installation process

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#2548]
When installing extensions, we need to improve the reliability of file copy/move operations to account for the possibility of locked files at the destination.

**Comment by paulbatum** [comment]
this will cause significant customer impact. needs to be fixed prior to V2 GA.

**Comment by paulbatum** [comment]
Somewhat related to https://github.com/Azure/azure-functions-host/issues/2700 (perhaps both issues will be resolved with the same solution).

**Comment by paulbatum** [comment]
Blocked on #2700.
