### ISSUE TITLE
Azure functions triggered by time triggers stoped after update them with kudu

### ISSUE THREAD

**Issue by kastwey** [Azure/azure-functions-host#2551]
#### Investigative information

- Timestamp: 2018-03-19 10:00 Z.
- Function App version 1.0
- Function App name: jmontiel-timmertrigger
- Function name all created functions, from test1 to test200
- Region: Central US

#### Repro steps

1. Download the publishing profile from azure portal.
2. Use the ftp username and password and kudu function app URL to create 200 functions of type timmer trigger, with a TimeSpan of 10 minutes:
```csharp
var response = await _httpClient.PutAsync($"https://jmontiel-timmertrigger.scm.azurewebsites.net/api/functions/test{i}", .....);
```
3. The functions are created successfully and executed each 10 minutes uninterrupted since today at 10:00 when I performed the step 4.
4. Update all functions, keeping the interval, and changing the run.csx file by using kudo (as before):
```csharp
var response = await _httpClient.PutAsync($"https://jmontiel-timmertrigger.scm.azurewebsites.net/api/functions/test{i}", ....);
```
5. After update the functions, all functions stoped working.

#### Expected behavior

After step 4, The functions should be updated and continue running executing the new csx file.

#### Actual behavior

The functions stoped working.

#### Related information 

* Programming language used: c#
* Bindings used: timmer trigger

#### explanation

A few days ago, I deployed two hundred functions using kudu, and the two hundred functions have been running without interruption until this morning.

This morning, I updated those 200 functions (also using kudu), and since I updated them, those functions have been stoped.
I haven't changed TimeSpan (all of them keep running every ten minutes, as they were before), although I imagine Kudu will update both the run.csx file and the function.json file, even if the bindings and the interval don't change.

In the documentation, I have read that if I change the function execution interval, I have to call SyncTriggers to make the functionapp aware of the new interval, but in this case, the function maintains its interval, only the contents of the run.csx file have changed.

Anyway, I understand that, in case I don't call SyncTriggers, the only thing that would happen is that the functions would maintain their previous execution intervals, but not stop working, isn't it?

Best regards,

Juanjo.
Juanjo.

**Comment by pragnagopa** [comment]
Our logs show following exception starting: around 2018-03-19 10:20:00
```
Microsoft.Azure.WebJobs.Script.Description.CompilationServiceException : C# compilation service error: Could not load file or assembly '0 bytes loaded from Microsoft.Azure.WebJobs.Script, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format. ---> System.BadImageFormatException : Could not load file or assembly '0 bytes loaded from Microsoft.Azure.WebJobs.Script, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format. ---> System.BadImageFormatException : Bad IL format. 
```
Can you please restart the app?

**Comment by pragnagopa** [comment]
Closing as this is a known issue and restarting the app should work.
