### ISSUE TITLE
User specified "content-type" for Http response not always correct for non-.NET languages (V2)

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#2552]
In V2, content-negotiation for HTTP objects from non-.NET languages can fail if [ObjectResult](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.objectresult?view=aspnetcore-2.0) chooses the wrong content type for response (details [here](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/formatting)).

We should prioritize honoring the user-specified "content-type" property if set, especially if where there are known gaps in content negotiation logic from ObjectResult.

This is the root cause of this and similar issues: #2491

**Comment by mhoeger** [comment]
As a first step, we can set content-type to always be primarily honored by changing the boolean check here. (Note that we will still see issues with content-type for non UTF-8 characters.)

https://github.com/Azure/azure-functions-host/blob/b0cf84d7e27ac9a37d183a966e9ef7369f50914a/src/WebJobs.Script/Binding/Http/HttpBinding.cs#L164-L176

**Comment by paulbatum** [comment]
Until this is fixed, this is basically a break for v2 users.

**Comment by mhoeger** [comment]
^above issue gives context on issue too. "isRaw" should be defaulted to "true" for RpcHttp objects. This isn't completely trivial because proto3 [doesn't allow for default primitives](https://developers.google.com/protocol-buffers/docs/proto3#default).

**Comment by Fluent-Faolan** [comment]
Why has this issue been closed? Any progress with this? Still experiencing this issue...

**Comment by paulbatum** [comment]
@Fluent-Faolan it was closed because a fix was merged. Please provide details of what your code is doing and what version you're running so we can figure out why you're still having issues.

**Comment by Fluent-Faolan** [comment]
Was having trouble with it earlier, but it seems to be related to hosting the Azure function on a Linux server. Switched to hosting on Windows and works fine now.

For reference, if I sent the response header Content-Type to text/html the server would only return 406 errors, setting the isRaw flag seemed to make it ignore this header and always return plain text.

**Comment by mhoeger** [comment]
isRaw is deprecated - we should make that clearer - although setting it to true shouldn't have made a difference in your code. What language are you using?

**Comment by Fluent-Faolan** [comment]
JavaScript

**Comment by goofballLogic** [comment]
+1 We need this and have to use the isRaw hack for now

**Comment by goofballLogic** [comment]
Also note that the docs still show it as current: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#response-object

**Comment by mhoeger** [comment]
Thanks for the doc link! I'll be sure to update that once we've resolved your issue!
@goofballLogic - just to confirm, you're also only seeing this issue when running JavaScript on a Linux server? (Our recommendation is to run on a Windows server with JavaScript)
