### ISSUE TITLE
ILogger does not log when exception parameter included

### ISSUE THREAD

**Issue by MrGlenThomas** [Azure/azure-functions-host#2556]
#### Investigative information

Please provide the following:

- Timestamp: 2018-03-19T21:43:15.272
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: 3b79f7d4-58c4-4adb-ac78-c5ec17444ac0
- Region: Europe North

#### Repro steps

Provide the steps required to reproduce the problem:

Use the ILogger extension methods with an Exception parameter

#### Expected behavior

I expect to see a log entry in application insights.

#### Actual behavior

No log entry exists when these method signatures are used, but when the exception parameter is not used the log entries appear.

#### Known workarounds

Use the method signatures that don't include an exception parameter.

#### Related information 

Provide any related information 

* Programming language used 
C#

**Comment by brettsam** [comment]
Can you share your logging code?

**Comment by MrGlenThomas** [comment]
```
[FunctionName("TestFunc")]
public static void Run([TimerTrigger("*/10 * * * * *")]TimerInfo myTimer, ILogger log)
{
    // does not write to log:
    log.LogError(new EventId(123), "Error {errorCode}", new Exception(), 123);
    // logs ok:
    log.LogError(new EventId(123), "Error {errorCode}", 123);
}
```
Not the exact code that I am using but demonstrates the general idea. The line executes without an exception being thrown but the log entry does not appear in application insights.
At first I thought it might be a problem with the application insight logging provider not flushing the logs, so added a delay and tried configuring host.json but that didn't make any difference. Then I added the exact same logging code on the line below but removed the exception parameter and those logs were appearing in application insights.

**Comment by MrGlenThomas** [comment]
I have just realised that there are some logs in the exceptions table, but should also be logs in the trace table too?

**Comment by MrGlenThomas** [comment]
The same behaviour with Microsoft.Azure.WebJobs.Script.Diagnostics.FileLogger.

No log entries appear in the log file when the exception parameter is used.

**Comment by MrGlenThomas** [comment]
I am using Microsoft.NET.Sdk.Functions 1.0.13 and my function app is running on runtime version 1.0.11612.0 (~1). Is there any update on why it doesn't log correctly?

**Comment by MrGlenThomas** [comment]
I have just checked the commit again and looks like it is tagged for release v3.0.0-beta5. Will this release be available to ~v1 functions?

**Comment by brettsam** [comment]
You're absolutely right. This was done in the `dev` branch but not to our `v2.x` branch. We need to port this back (it should just be a couple lines of code plus test updates).

**Comment by somefella123** [comment]
+1 request for this...

**Comment by brettsam** [comment]
Fixed by https://github.com/Azure/azure-webjobs-sdk/pull/1789

**Comment by sandeepiiit** [comment]
@brettsam Do you know which version of Azure Functions Sdk I should be using to get this fix. I am currently using Microsoft.NET.Sdk.Functions 1.0.28

**Comment by brettsam** [comment]
This should be fixed everywhere. Can you share what you're doing and what isn't working as you expect?

**Comment by sandeepiiit** [comment]
@brettsam I have a HTTP triggered function with a catch-all block that catches exceptions and logs it, and then returns a 500.
```
                catch (Exception ex)
                {
                    log.LogError(ex, "Exception invoking MyFunction");
                    // Code to return 500.
                }
```

When looking at the app insights logs, I only see the error message, and nothing about the exception (screenshot below).
![image](https://user-images.githubusercontent.com/13448362/64210143-5b416600-ce57-11e9-84dd-cb794e789bd9.png)

I also tried using the "Run in application insights" to see if there is more info available there, but I seem the same thing.

Some info about the run in case it's useful:
`Invocation id: 'c24c7b2f-a3fd-46b7-a000-3dd5e4842588'`
`operation_Id: '510851c7782ecb4ab2504e396a1c0ed1'`

Please let me know if this is not clear, and I can put together a short demo example.

**Comment by sandeepiiit** [comment]
@brettsam I was able to see it in app insights by modifying the query a little bit. So I think it gets logged, it just doesn't show in the default view. It is a little hard to modify the query. It would be nice to show the exceptions in the default view. If it sounds like a reasonable feature request, I can file one.
