### ISSUE TITLE
Support OAuth

### ISSUE THREAD

**Issue by nzthiago** [Azure/azure-functions-host#2559]
Just like in "Support EasyAuth #33", Functions should also support regular OAuth. 

Currently, if it's not an EasyAuth supported auth type, we need to set the Functions auth setting to Anonymous and write OAuth related code inside the functions to handle OAuth (and repeat this code for all the functions we write), or write code to call a third party like Auth0. 

This should ideally be handled by the platform, by allowing for OAuth config in the HTTP based triggers settings or some other way, and pass in the resulting auth claims into the context object. 

Note: If it is decided that this won't be implemented, there should be documentation and samples on the recommended approaches for OAuth + Functions.

**Comment by xiaoyang-connyun** [comment]
With the newly released Dependency Injection, I would even hope that OAuth is supported via DI.

**Comment by nzthiago** [comment]
The have now been published on official azure samples.
There are now Azure Samples published for Azure Functions and Identity scenarios, discoverable at https://docs.microsoft.com/en-us/samples/browse/ 
Here are the direct links:
* [Dotnet](https://github.com/Azure-Samples/ms-identity-dotnet-webapi-azurefunctions)
* [NodeJS](https://github.com/Azure-Samples/ms-identity-nodejs-webapi-azurefunctions)
* [Python](https://github.com/Azure-Samples/ms-identity-python-webapi-azurefunctions)
* [On Behalf Of](https://github.com/Azure-Samples/ms-identity-nodejs-webapi-onbehalfof-azurefunctions) 

The samples target generic OpenID, or can be easily extended to target any auth provider that supports OpenID.

Additionally, the following documents have been updated: 
* The [Protected Web API scenario](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-overview)
The [Web API that calls web APIs scenario](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-api-call-api-overview) 
List of [sample applications](https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code) with the new Functions sample apps
Functions in the Web APIs section in [application types](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-app-types)
Functions in the web API sections in [authentication flows and app scenarios](https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-flows-app-scenarios)
