### ISSUE TITLE
HttpTrigger webHookType should be an enum?

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#2563]
_From @JonathanGiles on March 20, 2018 3:11_

It appears that there are only three valid values for the webHookType on HttpTrigger: genericJson, github, and slack (https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#trigger---configuration). If this is the case, and if it is not possible for developers to augment this with additional functionality, it seems wise to instead provide an enum rather than use a String argument?

_Copied from original issue: Azure/azure-functions-java-worker#75_

**Comment by pragnagopa** [comment]
_From @JunyiYi on March 20, 2018 18:24_

@pragnagopa , are you able to confirm that only these options are available for HttpTrigger webhook?

**Comment by pragnagopa** [comment]
Need to update [function.json](http://json.schemastore.org/function) schema to use enum instead of string

**Comment by JonathanGiles** [comment]
Is the plan to introduce an enum for this in Java API?

**Comment by paulbatum** [comment]
The list of possible webhook types supported is open as its based on what implementations of asp.net webhooks are pulled in. We're not going to update an enum every time this list is extended. In the future it might even be possible for users to pull in their own webhook implementation through binding extensibility.
