### ISSUE TITLE
V2: Integrate cosmosDB trigger

### ISSUE THREAD

**Issue by gauraviitr** [Azure/azure-functions-host#2565]
The trigger exists and easy to integrate in v1:
<img width="1279" alt="1 x nodejs 6" src="https://user-images.githubusercontent.com/12062597/37683252-38e0bb08-2c49-11e8-9d10-460db69c43da.PNG">

It's missing in v2:
<img width="1113" alt="2 0 nodejs 8 9 4" src="https://user-images.githubusercontent.com/12062597/37683261-42b25d30-2c49-11e8-8d1b-7116d0d1519f.PNG">

**Comment by paulbatum** [comment]
@soninaren whats the status on the cosmos template for v2 appearing in the portal? I can't find an open issue or PR.

**Comment by gauraviitr** [comment]
Any eta??

**Comment by soninaren** [comment]
This is complete. There is cosmosDB trigger template in portal for v2.
