### ISSUE TITLE
Why Azure function not working with Generics?

### ISSUE THREAD

**Issue by viveknuna** [Azure/azure-functions-host#2569]
I have a requirement that I have to use TEntity with the class. But Azure function not working when using Generics with class. It's not even showing on the console also. But If I remove TEntity from class declaration it's showing in the console. So is this not supported? or is there any workaround for this? I have searched on internet but found nothing related to this.

```
public static class DataFilesIngestJobs<TEntity>
{
    [FunctionName("IngestDataFilesScheduled")]
    public static async Task RunScheduleAsync(
        [TimerTrigger("%DataFiles:IngestJob:ScheduleExpressionTrigger%")] TimerInfo timer,
        ExecutionContext context,
        TraceWriter log)
    {
        await RunAsync(context, log);
    }

    [FunctionName("IngestDataFilesOnDemand")]
    public static async Task RunOnDemandAsync(
        [QueueTrigger("%DataFiles:IngestJob:OnDemandQueueNameTrigger%", Connection = "ConnectionStrings:BlobStorageAccount")] string queueItem,
        ExecutionContext context,
        TraceWriter log)
    {
        await RunAsync(context, log);
    }
}
```
**Console output on removing TEntity from class.**

> Found the following functions: [3/21/2018 6:52:41 AM] MyCompany.MyProject.DataFilesIngestJobs.RunScheduleAsync [3/21/2018 6:52:41 AM] MyCompany.MyProject.DataFilesIngestJobs.RunOnDemandAsync

**Comment by pragnagopa** [comment]
This is answered on SO:
- [what-is-the-reason-for-host-lock-lease-acquired-by-instance-id-in-azure-function](https://stackoverflow.com/questions/49383833/what-is-the-reason-for-host-lock-lease-acquired-by-instance-id-in-azure-function)
- [why-azure-function-not-working-with-generics](https://stackoverflow.com/questions/49400065/why-azure-function-not-working-with-generics)
