### ISSUE TITLE
Cannot install Microsoft.Azure.WebJobs.Extensions.EventGrid

### ISSUE THREAD

**Issue by michaeldaw** [Azure/azure-functions-host#2584]
I'm attempting to create a Function (v1) in Visual Studio 15.7.0 preview 2 that uses an EventGrid trigger. According to [this page](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid), I need to install the package **Microsoft.Azure.WebJobs.Extensions.EventGrid**. 
However, if I try to install that package, I get the following error:
```
NU1107: Version conflict detected for Microsoft.Azure.WebJobs. Reference the package directly from the project to resolve this issue. 
 MyProject -> Microsoft.Azure.WebJobs.Extensions.EventGrid 1.0.0-beta3 -> Microsoft.Azure.WebJobs (>= 2.1.0) 
 MyProject -> Microsoft.NET.Sdk.Functions 1.0.2 -> Microsoft.Azure.WebJobs (= 2.1.0-beta1).
```
I'm not really sure what "Reference the package directly" means. Is the documentation incomplete? Is there a workaround?

**Comment by pragnagopa** [comment]
This is a known issue. Please install latest version of Microsoft.NET.Sdk.Functions 1.1.10. Tooling would soon be updated to use the latest version of Microsoft.NET.Sdk.Functions as well.

**Comment by michaeldaw** [comment]
Okay thank you.

**Comment by mevansdev** [comment]
Did you mean version >=1.0.10 rather than 1.1.10.  As of 2018/05/22 1.0.13 is the latest version and this error is still showing.  I'm using 2.0.0-beta1 and still seeing this error
https://www.nuget.org/packages/microsoft.net.sdk.functions/

**Comment by mevansdev** [comment]
I stand corrected, using the newer project type for azure functions (2.0 preview) works fine.
