### ISSUE TITLE
Errors in the azure portal when IP restriction added

### ISSUE THREAD

**Issue by MrGlenThomas** [Azure/azure-functions-host#2587]
I was instructed to add an IP restriction to the function app of 10.0.0.0 255.255.255.0 to only allow connections from internal azure clients (i.e. portal, etc.)

When using the azure portal to manage my function I am now seeing lots of errors and broken functionality.

How can I add IP restrictions to the function app but allow the portal to function as normal?

#### Investigative information

Please provide the following:

- Timestamp: Any time
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region: Europe North

#### Repro steps

Provide the steps required to reproduce the problem:

Go to a function's main page (where function.json is displayed). See error:
> Error:
> The function runtime is unable to start.
> Session Id: c29d1fa147a147d3a6ffad5524c4cf88
> Timestamp: 2018-03-27T10:16:42.861Z

Click the Run button. See error:
> Status: 403 Forbidden
> You do not have permission to view this directory or page.

Go to a function's manage page (where host keys are displayed). See error:
> Error:
> Forbidden - https://asos52-dev-eun-cmc-subscriptions-options-fcn-app.azurewebsites.net/admin/host/keys
> Session Id: c29d1fa147a147d3a6ffad5524c4cf88
> Timestamp: 2018-03-27T10:17:45.359Z

#### Expected behavior

Provide a description of the expected behavior.

Portal functionality should work as normal.

#### Actual behavior

Errors as listed above

#### Known workarounds

Remove IP restriction

**Comment by paulbatum** [comment]
This issue was moved to Azure/azure-functions-ux#2471
