### ISSUE TITLE
Catchall routes will override admin routes

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#2590]
In 2.0, catchall routes when the base route prefix is removed break the admin APIs routing. Admin routes must be respected.

**Comment by safihamid** [comment]
This will also make /admin/* endpoints to fail if there is a proxy similar to this:
{
    "proxies": {
                "proxy_test": {
                    "debug": true,
            "matchCondition": {
                "route": "/admin/{*test}"
            },
            "backendUri": "https://somehost.azurewebsites.net/admin/{test}"
        }
   }
}

**Comment by paulbatum** [comment]
Here's another example repro:

host.json:
```javascript
{
  "version": "2.0",
  "extensions": { "http": {"routePrefix": ""}}
}
```

Function definition:
```csharp        
public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = "{*test}")] HttpRequest req,
            ILogger log)
```

Make a request to `/admin/host/status` and the function will intercept it.

**Comment by safihamid** [comment]
@paulbatum Yes, I have verified the fix will also address the example above you provided.
