### ISSUE TITLE
Setting console logging mode in host.json does not work

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#2596]
specifying console logging mode in host.json
```
 "logger": {
    "fileLoggingMode": "always",
    "consoleLoggingMode": "always"
  },
```
Runtime needs to parse host json correctly [here](https://github.com/Azure/azure-functions-host/blob/bafab95344edf81ff100b2bb0f76ea5681ca57be/src/WebJobs.Script/Diagnostics/DefaultLoggerProviderFactory.cs#L44)

Workaround:
set host:logger:consoleLoggingMode=always in the environment variabels

**Comment by paulbatum** [comment]
is it important to fix this, considering the workaround? Environment variables seem like a nicer way to specify this type of thing. I am wondering if we should just yank these file based settings for logging as part of V2... 

cc @mathewc @brettsam

**Comment by brettsam** [comment]
I think we should be using IConfiguration so it doesn't matter where the value comes from. When we get there, both of these will work. Our DI work is getting us closer to that.

**Comment by paulbatum** [comment]
makes sense.

**Comment by paulbatum** [comment]
@brettsam is this still an issue now that DI is in?

**Comment by brettsam** [comment]
https://github.com/Azure/azure-functions-host/pull/3263 changed how this works. The code that covers this is now here: https://github.com/Azure/azure-functions-host/blob/94779d58d342d6c50a342823cb2c80c225d356d8/src/WebJobs.Script/ScriptHostBuilderExtensions.cs#L171-L189

```
{
  "logging": {
    "console": {
      "isEnabled": "true"
    }
  }
}
```
