### ISSUE TITLE
API to provide a list of supported languages for Functions on Linux

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-host#2607]
Currently, the list of supported runtimes on Linux are: 

- Dotnet (C#, F#)
- JavaScript
- Python

We need an API to provide this list to the clients along with the metadata about corresponding docker images.

**Comment by asavaritayal** [comment]
\cc @ahmelsayed @davidebbo

**Comment by pragnagopa** [comment]
@asavaritayal - Can you add more details? Is this required for the CLI? Portal?

**Comment by pragnagopa** [comment]
@asavaritayal - Can you fill in more details? Is this still required?

**Comment by pragnagopa** [comment]
We now have app setting to select functions language. Closing this.
