### ISSUE TITLE
Massive discrepancy between Function and Host.Aggregator log count

### ISSUE THREAD

**Issue by kczelusniak** [Azure/azure-functions-host#2616]
My team has noticed a huge discrepancy between custom logs from my Function and the built-in logs from Host.Aggregator. Host.Aggregator seems much more accurate and has an accurate count of the number of times my function has executed, whereas my Function logs seem to get throttled and get lost somewhere along the way.

![Function logs](https://i.imgur.com/cfpNUTx.png)

![Host.Aggregator logs](https://i.imgur.com/ntkR7Sm.png)

As you can see from these pictures, I'm logging about 400 messages per second. Host.Aggregator shows these logs perfectly, while my Function logs have a peak right after starting the function, and then seem to get throttled. My custom log count from my Function never actually hits zero. I'm attempting to log one or multiple messages per function invocation, but these logs seem to be missing.

#### Investigative information
The following is the information from a Function Invocation from the beginning of the time range of the pictures above.
- Timestamp: `2018-04-02T23:30:43.054`
- Function App version (1.0 or 2.0-beta): `1.0.9`
- Function App name: `telemetry-message-blob-router`
- Function name(s) (as appropriate): `RouteTelematicsStandardFormatMessage`
- Invocation ID: `2f016afb-4a3a-4ddc-a4c9-d49beae86929`
- Region: `North Central US`

#### Repro steps
1. Use `ILogger.LogInformation` to log something once per function invocation at 400 invocations per second
2. Observe that the count of these logs seems to match `Host.Aggregator` at the beginning, and then fall off drastically

#### Expected behavior
The count from `ILogger.LogInformation` should match the counts from `Host.Aggregator`

#### Actual behavior
`ILogger.LogInformation` shows a huge peak at function start, and then slows to a trickle

#### Known workarounds
Use `Host.Aggregator` counts instead of being able to rely on the customized counts from my Function

#### Related information 

Provide any related information 

* Programming language used: `C#`
* Bindings used: `EventHubTrigger`, `ServiceBusTrigger`, `Blob`
<details>
<summary>Source</summary>

```csharp
internal static async Task Upload(
            string json, 
            string payloadId,
            string messageId,
            MessageTypeConfiguration configuration,
            ILogger logger)
{
    var message = new StringContent(json, Encoding.UTF8, "application/json");
    HttpResponseMessage response = null;
    try
    {
        logger.LogInformation(LogFormat, messageId, payloadId, Event.UploadStart);
        response = await Client.PutAsync(ConfigurationManager.AppSettings["Url"], message);
    }
    catch (HttpRequestException exception)
    {
        logger.LogError(
            LogFormat + ",statusCode={statusCode}",
            messageId,
            payloadId,
            Event.UploadException,
            ((WebException)exception.InnerException).Status);
        throw exception;
    }
    catch (TaskCanceledException exception)
    {
        logger.LogError(LogFormat, messageId, payloadId, Event.UploadTimeout);
        throw exception;
    }

    logger.LogInformation(LogFormat, messageId, payloadId, Event.UploadOk);
}
```
</details>

**Comment by paulbatum** [comment]
I believe you're getting this behavior because sampling is on by default. See here for some info:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#configure-sampling

I would try disabling sampling and then see how closely the counts match.

**Comment by kczelusniak** [comment]
That fixed it, thank you!
