### ISSUE TITLE
Ability to abort and stop new function instance to start

### ISSUE THREAD

**Issue by btardif** [Azure/azure-functions-host#2619]
_From @suwatch on March 30, 2016 17:23_

Not sure if it belongs in this git repo.   

My scenario is I originally wrote a timer trigger function with a buggy C# script that ran for hours.  Once it started, I realized the issue.   I fixed the bug and save the C# script.  However the new compiled codes would not take effect until the currently running (buggy) one stopped.   I could go to portal and restart the whole container.

It would be great to have a button (on function portal) to abort all running instances of this function and, perhaps, disable it from starting up.   Then a way to restart/enable it back.     

_Copied from original issue: Azure/azure-functions-ux#278_

**Comment by btardif** [comment]
_From @davidebbo on March 30, 2016 17:29_

There is both some backend and portal work to achieve this. It's a fairly hard problem since the function could be running on multiple instances (multiple times on each).

**Comment by btardif** [comment]
_From @suwatch on March 30, 2016 23:1_

could this be addressed the same way as [Kudu WebJob](https://github.com/projectkudu/kudu/blob/54a200dbbb67939bf53b4604915331d8690b16cb/Kudu.Core/Jobs/BaseJobRunner.cs#L336) (using file to communicate such)?

**Comment by btardif** [comment]
_From @davidebbo on March 30, 2016 23:3_

Instead of file, it would probably be storage based. There may already be something like this in SDK. @mathewc ?

**Comment by btardif** [comment]
_From @mathewc on March 31, 2016 0:23_

Yes, if you look at the WebJobs Dashboard (classic Dashboard, not FastLogging Dashboard) you can see running functions and abort them with the click of a button. This is storage based - all hosts are monitoring a queue and the Dashboard writes an abort message to the queue.

We can do the same thing in Functions, since it's build on the core SDK. The Function ScriptHost is already monitoring the right queues.

**Comment by btardif** [comment]
_From @davidebbo on March 31, 2016 0:42_

Good, so technically, if user goes to dashboard they can already do this. Suwat, something to try if you have cycles.

**Comment by btardif** [comment]
_From @paulbatum on April 5, 2016 22:8_

So assuming you can do this via the webjobs dashboard, we do have a discoverability issue.

**Comment by btardif** [comment]
@suwatch there is a per function disable toggle in UX, my expectation is that this would stop any running instance of a function after a reasonable timeout.

This might not be a UX issue if you agree with the above sentence, Can you confirm this is not what is happening?

**Comment by btardif** [comment]
@jeffhollan  this should be moved to runtime

**Comment by paulbatum** [comment]
We've actually addressed this already in functions V2. Disabling is done via an app setting, and changing this setting causes the application to restart, which will halt function execution (including any running timer functions). So the net effect is that disabling the function through the UX stops the current execution. 

Since its resolved in V2 and we don't plan on any improvements to this scenario for V1, I'm closing this issue.

**Comment by chaheti29** [comment]
@paulbatum Is there any specific setting that should be used.
I want to abort a timer based function current run based on certain condition. How can I achieve that. It should again run on scheduled time.

**Comment by paulbatum** [comment]
This thread was discussing the usage of the disable flag to stop a current function execution. The documentation for disabling functions is here: https://docs.microsoft.com/en-us/azure/azure-functions/disable-function#functions-2x---all-languages

I will note however, that this method would interrupt other function executions in the same function app. If that behavior is not desirable, you'll need to implement your own mechanism for detecting that you want a given execution to abort and abort execution yourself.
