### ISSUE TITLE
Azure Functions Node.Js app fails when using web3.js

### ISSUE THREAD

**Issue by agnnn** [Azure/azure-functions-host#2625]
#### Investigative information

Please provide the following:

- Timestamp: 04-04-2018
- Function App version (1.0 or 2.0-beta): 2.0-beta
- Websockets: ON
- Hosting Plan: App Service Plan
- Function App name:(not shared)
- Function name(s) (as appropriate): HTTPTRIGGER
- Invocation ID: 25fbc2c8-ecde-4ede-92bf-bd92393de69d
- Region: Central US

#### Repro steps

Provide the steps required to reproduce the problem: 
Step A:

1. Configure an Ethereum Private Blockchain network using Azure MarketPlace template.
2. Configure an Azure HTTP trigger Function to connect to the above instance using the code below.

#### Expected behavior

Provide a description of the expected behavior.
1. Function should connect to the ethereum blockchain network
2. Then it should create a new eth account.

#### Actual behavior

Provide a description of the actual behavior observed.
The following error is logged.
```
2018-04-04T13:33:24  Welcome, you are now connected to log-streaming service.
2018-04-04T13:33:28.033 [Information] Executing 'Functions.HttpTriggerJS1' (Reason='This function was programmatically called via the host APIs.')
2018-04-04T13:33:28.130 [Error] System.Private.CoreLib: Exception while executing function: Functions.HttpTriggerJS1. System.Private.CoreLib: One or more errors occurred. (Worker process with pid 4400 exited with code 1) (Worker process with pid 2124 exited with code 1) (Worker process with pid 5852 exited with code 1). Worker process with pid 4400 exited with code 1.
2018-04-04T13:33:28.147 [Error] Executed 'Functions.HttpTriggerJS1' (Failed, Id=)
```

#### Suggested workarounds

Provide a description of any known workarounds.
[https://stackoverflow.com/questions/47054564/call-ethereum-using-web3-js-on-azure-function?rq=1](url)
1. Run under Functions 2.0 beta runtime
2. Run as an App Service Plan.
3. Enable WebSockets.
**I DID TRY THE WORK AROUND AND IT DID NOT WORK**
#### Related information 

Provide any related information 

<details>
<summary>Source</summary>

```
'use strict';

module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function for BlockChain processed a request.');
    var Web3 = require('web3');
    var web3 = new Web3();
    web3.setProvider(new web3.providers.HttpProvider("http://BLOCKCHAIN_IP:8545"));
    var newAccount=web3.eth.personal.newAccount("@superpassword")=>{
      context.log(newAccount);
    })
    context.log('Function should work');
    context.res = {
        body: "Hello"
    };
    context.done();
};
```
</details>

**Comment by brettsam** [comment]
Note that this is not supported in v1. 
See this issue for when it was working in v2 (at some point): https://github.com/Azure/azure-functions-host/issues/2166

**Comment by mhoeger** [comment]
Closing issue as given code does not compile and is currently showing the appropriate messages about not compiling.
