### ISSUE TITLE
Orchestration Replay calls activities twice

### ISSUE THREAD

**Issue by AMSoftwareNL** [Azure/azure-functions-host#2629]
#### Investigative information

Please provide the following:

- Timestamp: 2018-04-05 02:25:00 (CET)
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name: amsdurablefunctiontest
- Function name(s) (as appropriate): FunctionStarter, OrchestrationStart, DoFanOut, ForceReplay
- Invocation ID:
- Region: west europe

#### Repro steps

Provide the steps required to reproduce the problem:

Step 1: Start a durable function orchestration
Step 2: Fan-out to a 100 activities
Step 3: The activity writes a record to table storage using IASyncCollector (with a predetermined PartitionId and RowKey)
Step 4: Add a fan-in activity after the fan-out to force a replay of the orchestration

#### Expected behavior

The fan-out activity adds a TableEntity to table storage
The fan-in activity is executed and the orchestration completes

#### Actual behavior

The fan-out activity adds a TableEntity to table storage
The fan-in activity triggers a replay of the orchestration and instead of 'skipping' the fan-out activity and just taking the result (which is void), the fan-out activity is executed again and tries to write new entities to table storage. 
Result is errors in the log (HTTP 409 Entity already exists) as PartitionId and RowKey are fixed. 

The orchestration continues and completes succesfully. 
**NOTE:** If not a fixed rowkey is used some records are created twice.

#### Known workarounds

None

#### Related information 

* Programming language used is C# (VS2017 - 15.6.4)
<details>
<summary>Source</summary>

```csharp
public class TestTableEntity : TableEntity
    {
        public string Name { get; set; }
    }

    public static class FunctionAwaiterTest
    {
        [FunctionName("FunctionStarter")]
        public static async Task Run([HttpTrigger]HttpRequestMessage req,
                                     [OrchestrationClient] DurableOrchestrationClient starter,
                                     TraceWriter log)
        {
            int awaitCounter = await req.Content.ReadAsAsync<int>();
            string instanceId = await starter.StartNewAsync("OrchestrationStart", awaitCounter);
            log.Info($"Started orchestration with ID = '{instanceId}'.");
        }

        [FunctionName("OrchestrationStart")]
        public static async Task RunOrchestrationStart([OrchestrationTrigger]DurableOrchestrationContext context, TraceWriter log)
        {
            log.Info($"Entering function 'OrchestrationStart'.");

            int awaiterCount = context.GetInput<int>();

            List<Task> awaiters1 = new List<Task>();
            for (int i = 0; i < awaiterCount; i++)
            {
                Task awaiter = context.CallActivityAsync("DoFanOut", i);
                awaiters1.Add(awaiter);
            }
            await Task.WhenAll(awaiters1);

            await context.CallActivityAsync("ForceReplay", null);
        }

        [FunctionName("DoFanOut")]
        public static async Task RunDoFanOut([ActivityTrigger]DurableActivityContext context, [Table("test")]IAsyncCollector<TestTableEntity> tableEntities, TraceWriter log)
        {
            log.Info($"Entering function 'DoFanOut'.");

            int counter = context.GetInput<int>();

            TestTableEntity t = new TestTableEntity()
            {
                PartitionKey = context.InstanceId,
                //RowKey = $"{context.InstanceId}_{counter:00#}",
                RowKey = $"{Guid.NewGuid()}",
                Name = $"Awaiter {counter:00#}"
            };
            await tableEntities.AddAsync(t);

            log.Info($"Exiting function 'DoFanOut'.");
        }

        [FunctionName("ForceReplay")]
        public static async Task RunForceReplay([ActivityTrigger]DurableActivityContext context, TraceWriter log)
        {
            log.Info($"Entering function 'ForceReplay'.");

            await Task.Delay(1);

            log.Info($"Exiting function 'ForceReplay'.");
        }
    }
```
</details>

**Comment by paulbatum** [comment]
This issue was moved to Azure/azure-functions-durable-extension#231
