### ISSUE TITLE
IP Restriction intermittently starts and stops working

### ISSUE THREAD

**Issue by giemch** [Azure/azure-functions-host#2647]
I've got IP restriction enabled for my public IP and APIM that sometimes works for brief moments then suddenly stops working and then I get 403 errors. This behavior continues to cycle with no apparent pattern.

**Comment by btardif** [comment]
Based on what I'm seeing I think we should disable this feature for Function apps until we figure out what is going on. I suspect the ip restriction rules are not being propagated across scale units when a function scales out.

**Comment by giemch** [comment]
@btardif Were you able to repro? I wasn't sure if my Function app somehow got into a weird state. This Function is just something in our sandbox environment, so it's getting very little traffic.

**Comment by btardif** [comment]
@giemch I would recommend clearing out any ip restriction rules. We plan to disable this feature for function apps while we do investigation and figure our a solution.

**Comment by c-lombardi** [comment]
Is there an update to when this service might return?

**Comment by securityvoid** [comment]
I agree, this would be really useful to have available.

**Comment by paulbatum** [comment]
Please use https://github.com/Azure/azure-functions-ux/issues/2471 to discuss this further as it is not an issue with the functions host.

**Comment by giemch** [comment]
@paulbayum #2471 is fixed for me when I add my public IP, but this is a different issue.

**Comment by giemch** [comment]
@paulbatum 2471 is fixed for me when I add my public IP, but this is a different issue.

**Comment by paulbatum** [comment]
@giemch multiple issues have been discovered with the IP restriction feature that do not work right for function apps:
https://github.com/Azure/azure-functions-ux/issues/2526
