### ISSUE TITLE
Proxy JSON property with '{' and '}' is not properly escaped

### ISSUE THREAD

**Issue by btardif** [Azure/azure-functions-host#2648]
_From @nertim on March 28, 2018 18:17_

### OS and Browser
Windows 10, Chrome 

### Repro steps
> Create a proxy in the function app.
> Select GET as HTTP Allowed Method
> In the Response override, set the status to '200' and body to '{ "error/{foo}": "bar"}'
> Save
> Copy the proxy URL and access either from a tool such as fiddler and/or through the browser. Notice '{foo}' is missing.

**Proxy UI**
![image](https://user-images.githubusercontent.com/493476/38048131-6b251736-3279-11e8-9270-b0997e7b23bb.png)

**Proxies.json in Advanced Editor**
![image](https://user-images.githubusercontent.com/493476/38048165-7ffba65c-3279-11e8-908a-ca5e5fbe50e7.png)

**Output from browser**
![image](https://user-images.githubusercontent.com/493476/38048202-959e3b78-3279-11e8-8e41-69bc5c7b3240.png)

### Any error messages
>

### Mention any other details that might be useful.
This came up when some vendors were using Functions Proxy to return swagger for LA tests. Not really a blocker on any mainline scenarios.. but just an FYI.

_Copied from original issue: Azure/azure-functions-ux#2488_

**Comment by btardif** [comment]
This needs to be moved to runtime

**Comment by btardif** [comment]
hey @paulbatum we triage this during UX planning and belie it to be a backend issue, can you guys take a look?

**Comment by paulbatum** [comment]
Not sure I understand this issue... maybe @safihamid does?

**Comment by paulbatum** [comment]
@safihamid ping

**Comment by safihamid** [comment]
@vfedonkin another one you can work on. but less pri than the other two.

**Comment by vfedonkin** [comment]
We can escape "{" symbol with "{{"  so "{foo}" will mean "use the foo parameter" when "{{foo}}" will result as "{foo}". But this can break some existing customers.
Can we introduce the fix in V2 only?

**Comment by safihamid** [comment]
@vfedonkin yes, V2 is fine.

**Comment by safihamid** [comment]
PR here: https://github.com/Azure/azure-functions-host/pull/2732

**Comment by vfedonkin** [comment]
fixed in v2
