### ISSUE TITLE
Implement HTTP max limits and document for v2 similar to Functions v1 

### ISSUE THREAD

**Issue by nzthiago** [Azure/azure-functions-host#2652]
The current Functions V1 have the HTTP trigger limits documented here:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#trigger---limits 

And implemented as per:
https://github.com/Azure/azure-functions-host/blob/v1.x/src/WebJobs.Script.WebHost/Web.config#L43

We should implement similar settings for V2 (or better - make it configurable?), and add documentation for it if necessary.

**Comment by paulbatum** [comment]
We need to implement these limits prior to GA as it would likely be a breaking change to add them later.
