### ISSUE TITLE
Azure Function is not able to load `EntityFrameworkCore`

### ISSUE THREAD

**Issue by mamodom** [Azure/azure-functions-host#2658]
#### Repro steps
[Here](https://github.com/mamodom/AzureFunctionEFErrorRepro) is a vs project which exhibits the issue in hand 

1. Visual studio > Create new project > Azure Functions > Http Trigger (any kind of function will have the same behavior)

2. Install the nuget package `Microsoft.EntityFrameworkCore 2.0.2`

3. Use a class or method from said nuget package
    In my case I used `log.Info(typeof(DbContext).AssemblyQualifiedName);`

4. Ensure the azure storage emulator is running

5. Locally run the function ( F5 in vs )

6. Go to the url printed in the console

#### Expected behavior

The function should print out `Microsoft.EntityFrameworkCore.DbContext, Microsoft.EntityFrameworkCore, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60` and keep running.

#### Actual behavior

The function fails to run. Here's the output:
```
[11-Apr-18 6:33:59 AM] Executing 'Function1' (Reason='This function was programmatically called via the host APIs.', Id=6faabfd8-eb96-4d71-906c-940028a7978a)
[11-Apr-18 6:33:59 AM] Executed 'Function1' (Failed, Id=6faabfd8-eb96-4d71-906c-940028a7978a)
[11-Apr-18 6:33:59 AM] System.Private.CoreLib: Exception while executing function: Function1. FunctionApp1: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```

#### Known workarounds

None

#### Related information 

* VS community 15.6.5
* Azure App Service Tools v3.0.0 - 15.0.40215.0
* Azure Functions and Web Jobs Tools - 15.0.40405.0
* Common Azure Tools - 1.10
* OS Name	Microsoft Windows 10 Home
* Version	10.0.16299 Build 16299
* System Type	x64-based PC

```
> dotnet --info
.NET Command Line Tools (2.1.104)

Product Information:
 Version:            2.1.104
 Commit SHA-1 hash:  48ec687460

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.104\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

>dotnet --version
2.1.104
```
* Programming language used : C#
* Repro repo: https://github.com/mamodom/AzureFunctionEFErrorRepro

**Comment by vkuzin** [comment]
Currently experiencing same issue running slightly different version
dotnet --version 
2.1.103

EF Version 2.0.1, also tried EF Version 2.0.2 with no luck. 
Removing all folders in bin as suggested in other threads is not helping.

**Comment by fabiocav** [comment]
@mamodom the version currently deployed to Azure (2.0.11776) should work as expected. Local tools are also being updated. Please let us know if you continue to experience issues.
