### ISSUE TITLE
C# Event Hub trigger function can't process message

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-host#2660]
Ibiza portal URL: https://portal.azure.com
App runtime version: 1.0.11612.0 (~1)
Beta runtime version: 2.0.11651.0 (beta)
Browser: Chrome

Expected result:
Send message to the Eventhub that our function corresponds to will trigger the function.
Actual result:
Send message to the Eventhub and nothing happens.

Repro steps:

Open or create a v2(beta )function app.
Open +New Functions Page Task and select Event hub template.
Click "install", create Event hub- C# template after installation successfully.
Send a message and Verify logs for the function.

**Comment by paulbatum** [comment]
I investigated, and I see this error in the logs:
`Could not load file or assembly 'Microsoft.Azure.Amqp, Version=2.1.0.0 `

Digging further, it looks like this is because the nuget fallback folder is missing the lib for this nuget:

```
D:\Program Files (x86)\FuncNuGetFallback\1.0.1\microsoft.azure.amqp\2.1.1>dir
 Volume in drive D is Windows
 Volume Serial Number is 3437-3114

 Directory of D:\Program Files (x86)\FuncNuGetFallback\1.0.1\microsoft.azure.amqp\2.1.1

04/19/2018  05:13 PM    <DIR>          .
04/19/2018  05:13 PM    <DIR>          ..
04/19/2018  05:13 PM                88 microsoft.azure.amqp.2.1.1.nupkg.sha512
04/19/2018  05:13 PM               708 microsoft.azure.amqp.nuspec
               2 File(s)            796 bytes
               2 Dir(s)   7,945,494,528 bytes free

D:\Program Files (x86)\FuncNuGetFallback\1.0.1\microsoft.azure.amqp\2.1.1> 
```

Naren is investigating.

**Comment by paulbatum** [comment]
FYI @fabiocav when investigating assembly load failures, be aware that this issue exists and it could exist for other libraries (so some assembly load failures may be legit due to the assembly not being present). Naren is double checking to see if any other packages in the fallback folder are in this state.

**Comment by soninaren** [comment]
Should be fixed when the updated v2 runtime + new fall back folder is released.

**Comment by SimonGuo009** [comment]
Verified on 05/10, it has been fixed in Staging environment. 
V2 Runtime: 2.0.11651.0

@soninaren 
I do not have permission to close bugs, please help to do that. Thanks
