### ISSUE TITLE
ISO datetime strings unexpectedly change in Http responses 

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#2665]
For 2.0-beta functions in non-.NET languages, ISO datetime strings unexpectedly change in Http responses from Newtonsoft.Json deserialization (root cause: https://github.com/JamesNK/Newtonsoft.Json/issues/862).

Example: 
    context.res.body = {
        'test_time': '2026-04-20T00:00:00.**000Z**',
        'test_bool': true
    };

Yields:
{
  "test_time": "2026-04-20T00:00:**00Z**",
  "test_bool": true
}

Current workaround is to return the datetime string as a JSON.stringify'd string

**Comment by mhoeger** [comment]
This is the class we do deserialization on the HTTP response content.
https://github.com/Azure/azure-functions-host/blob/b0cf84d7e27ac9a37d183a966e9ef7369f50914a/src/WebJobs.Script/Binding/Http/HttpBinding.cs#L60

We could either add explicit handling per call or apply the default settings to the whole app (I think option 2 makes more sense). @fabiocav, could you weigh in?

_Per .DeserializeObject call:_
`content = JsonConvert.DeserializeObject(stringContent, new JsonSerializerSettings() { DateParseHandling = DateParseHandling.None });`

_For whole app:_ 
`JsonConvert.DefaultSettings = () => new JsonSerializerSettings
{
    DateParseHandling = DateParseHandling.None
};`

**Comment by paulbatum** [comment]
@mhoeger for this issue as its currently written, I don't really see a huge problem. The email thread I saw about this talks about how this behavior occurs even once the user specifies 'raw'. To me, that's the main issue.

**Comment by fabiocav** [comment]
For the proposed fix, if we move forward with it, it would be a better call to go with a variation of #1 that is a bit more efficient; create and cache an instance of a `JsonSerializerSettings` in that class and pass into the deserialization call. We don't want to set the global default static as that would impact a lot of other areas in the application. 

We already follow that pattern in a few different areas, [here's an example ](https://github.com/Azure/azure-functions-host/blob/89a296247b1763f81c59d989f47074bba3940908/src/WebJobs.Script/Rpc/LanguageWorkerChannel.cs#L50-L58)of that.

**Comment by mhoeger** [comment]
@paulbatum - There are two points where .NET content magic kicks in for an Http output binding. The first is when we deserialize a JSON object (such as body). The second is from the type of IActionResult we return as an Http response (with no content negotiation, if "isRaw"). 

I linked to the wrong .DeserializeObject call in my previous comment, but we want to change behavior when we are converting an RPC object to a typed C# object (which is why isRaw flag doesn't make a difference).

**Comment by mhoeger** [comment]
I think that regardless of the "isRaw" flag, we always want to set DateParseHandling to DateParseHandling.None for javascript/python/java, since manipulating strings that look like a datetime appears to be Json.NET-specific behavior.

We may also want to change that behavior for all Http responses, but I'm not positive if that's the behavior we want.

**Comment by willmorgan** [comment]
As an aside I've noticed this behaviour is different (and still slightly buggy) in 1.x - ISO-date-formatted strings get converted to Date objects if you send them as a JSON body.

**Comment by fabiocav** [comment]
@mhoeger  that makes sense. We'd follow the approach I mentioned above in order to scope to those scenarios and avoid applying that change to completely unrelated areas of the runtime and, more importantly, potentially impacting customer code as well.

When you say "all HTTP responses", I'm assuming you're also talking about the responses from language workers only, correct? The .NET behavior is what is expected today and the ability to control that behavior is already surfaced to users.

**Comment by mhoeger** [comment]
@fabiocav makes sense on scoping!

I actually did mean all HTTP responses (not just language worker responses), so thanks for the clarification. I'll leave that unchanged :)
