### ISSUE TITLE
Functions V2 Runtime errors on F5 for a Functions project in Visual Studio

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#2668]
_From @bzhu94 on April 12, 2018 16:33_

Please provide a succinct description of the issue.

#### Repro steps

INSTALL STEPS
1. Clean machine: Win 8.1 x64 ENU

2. Install  15.7 Preview 3 VSC (Web + Azure workload) from : \\\cpvsbuild\drops\VS\d15.7\products\27602.00\bootstrappers 

3. Select Web + Azure workload

4. Install the VSIX: \\\vwdbuild01\Drops\WTA\AzureFunctions-Dev15-OOB.Nightly\Dev15\2018-04-04_b5536\Release\Signed\VSIX\enu\Microsoft.VisualStudio.Web.AzureFunctions.vsix

#### Expected behavior

This error message should not appear when the runtime is started.

#### Actual behavior

The following error shows up upon starting the runtime: 

Unable to configure java worker.Could not find JAVA_HOME app setting.

Could not configure language worker Java

![attachments](https://user-images.githubusercontent.com/8541576/38690928-33e8609a-3e34-11e8-9bff-f18a54551bf0.png)

_Copied from original issue: Azure/azure-webjobs-sdk#1661_

**Comment by paulbatum** [comment]
@pragnagopa Do we already have a bug tracking this somewhere or do you have context on it? It repro's simply for me by just using the latest V2 tooling experience (i.e. you don't need to install a nightly build to repro).

**Comment by pragnagopa** [comment]
Runtime starts ok. It just complains Java environment variables are not set as we try to configure all the workers as part of initialization.  PR #2646 should fix it. Will close this issue as Dup of  #2541
