### ISSUE TITLE
Feature to configure Batch Size for External File Trigger

### ISSUE THREAD

**Issue by baskar3078** [Azure/azure-functions-host#2672]
Currently external file triggers which are in experimental mode do not have the feature to configure batch size using host.json file. 

#### Investigative information
External File Triggers to Drop Box, One Drive, SFTP which are in experimental mode, do not have the support to fetch files or documents in a batch. 

#### Expected behavior
By configuring the size in host.json functions should be able to read the configured number of documents from One Drive, Drop Box or SFTP.

**Comment by paulbatum** [comment]
No further development is happening on ExternalFileTrigger (see note in docs [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-external-file)). We recommend using logic apps for scenarios like this.
