### ISSUE TITLE
Message size for GRPC limited to 4MB

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#2677]
https://github.com/Azure/azure-functions-nodejs-worker/issues/60

Should try to increase max or handle appropriately

**Comment by mhoeger** [comment]
@pragnagopa - did we already know about this limit? Or should we look into try to do something about it?

**Comment by pragnagopa** [comment]
Fix coming soon #2651

**Comment by mhoeger** [comment]
Cool :) closing as dupe of #2301
