### ISSUE TITLE
cannot create HTTP triggered functions with Azure Function Runtime 2 Preview

### ISSUE THREAD

**Issue by helloguo** [Azure/azure-functions-host#2678]
I followed this link https://docs.microsoft.com/en-us/azure/azure-functions/functions-runtime-install to install Azure Function Runtime 2 Preview and run timer triggered functions and queue triggered functions successfully. However, I cannot create HTTP triggered functions with it. Based on https://github.com/Azure/azure-functions-host/wiki/Azure-Functions-runtime-2.0-known-issues , the HTTP trigger should be enabled in Azure Function Runtime 2. Can anyone share how to create HTTP triggered functions? Thanks.

**Comment by paulbatum** [comment]
Theres some really confusing terminology here. Basically Azure Functions Runtime is the marketing name for the ability to run functions on-premise, but we have internally used the term runtime to refer to the azure functions host. That doc page you linked is for the functions host and is not about on-prem. My understanding is that the on-prem offering of azure functions does not support HTTP triggered functions.

Closing this as answered.
