### ISSUE TITLE
Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator contains an expression that causes some projects to fail to load

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#2681]
_From @davkean on April 16, 2018 8:39_

I do not have a repro, only telemetry data. Looking through the top causes that a project failures to load in Visual Studio, Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator package is one of the top causes due to the following failure:

```
The result "" of evaluating the value "$(_FunctionsExtensionsTaskAssemblyFullPath)" of the "AssemblyFile" attribute in element <UsingTask> is not valid. C:\Users\[UserName]\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.0.0-beta2\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets
```

Can you please look at that UsingTask construct and figure out under what circumstances `_FunctionsExtensionsTaskAssemblyFullPath` is empty and fix that? We've seen hits of this error from January to last week.

_Copied from original issue: Azure/azure-webjobs-sdk#1663_

**Comment by fabiocav** [comment]
@davkean curious, do you have more details than just the message above with the telemetry information you receive? I did find an issue, but want to validate this is the same thing.

**Comment by fabiocav** [comment]
Thanks. Wanted to check just in case. 

I was a bit confused because we do have that property being set to a default value, if it is empty, but just realized that we made those fixes a while back, published to our internal feed and never pushed it to NuGet.

Will push this out first thing on Monday! Thanks again for bringing this to our attention!

**Comment by davkean** [comment]
Thanks!
