### ISSUE TITLE
Update Microsoft.Rest.ClientRuntime to latest patch release

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#2682]
This issue goes into the details of a problem that has been addressed in 2.3.4 and is impacting customers: https://github.com/Azure/azure-sdk-for-net/issues/2501

We should consider updating to the latest patch on the next release.

**Comment by paulbatum** [comment]
@fabiocav Did you mean 3.3.4?

**Comment by fabiocav** [comment]
No... 2.3.4 is the version that fix was applied to. The latest is 2.3.11

**Comment by paulbatum** [comment]
I'm confused by this comment then: https://github.com/Azure/azure-sdk-for-net/issues/2501#issuecomment-262320144

**Comment by paulbatum** [comment]
Was it backported and its just not mentioned on that issue?

**Comment by paulbatum** [comment]
nevermind, i'm confusing `Microsoft.Rest.ClientRuntime.Azure` and `Microsoft.Rest.ClientRuntime`.

**Comment by fabiocav** [comment]
Closed by #2701
