### ISSUE TITLE
AzureWebJobsStorage does not appear to get used

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-functions-host#2685]
After running some functions in the container, so Blob container named 'azure-webjobs-hosts' gets created in the storage account. Things still run probably because we're only using http, but would probably blow up quickly beyond that.

That is also probably the reason that setting `AzureWebJobsSecretStorageType` to `Blob` did not have any effect (secrets were still on file system and lost on restart).

**Comment by mathewc** [comment]
Addressed by Ahmed's Assign work and the below PRs.

https://github.com/Azure/azure-functions-host/pull/2736
https://github.com/Azure/azure-functions-host/pull/2728
