### ISSUE TITLE
Json serialization error right out of the box.

### ISSUE THREAD

**Issue by BowserKingKoopa** [Azure/azure-functions-host#2688]
I create a new Function app in Visual Studio (Azure Functions v2 Preview (.NET Core)) with a Queue Trigger. It gives me:

```
[FunctionName("Function1")]
public static void Run([QueueTrigger("testqueue")]string myQueueItem, TraceWriter log)
{
     log.Info($"C# Queue trigger function processed: {myQueueItem}");
}
```
I throw a plain text test message into that queue. I get an Exception immediately.  

"Newtonsoft.Json.JsonReaderException: 'Error parsing boolean value. Path '', line 1, position 1.'

What's it doing? Why is it trying to JSON anything? Is there a way to fix this?

**Comment by BowserKingKoopa** [comment]
Yes, mine match yours on both.

**Comment by paulbatum** [comment]
Are you getting fooled by having something like break on all errors enabled? Perhaps its just an internal exception that is caught and swallowed.

**Comment by BowserKingKoopa** [comment]
Quite possibly!  This is what I'm seeing.

![error](https://user-images.githubusercontent.com/11095411/38903165-9cde3534-4271-11e8-9d7d-cf97a6391265.jpg)

**Comment by BowserKingKoopa** [comment]
It looks like that's it. It's an internal exception. I'm not sure why the debugger was breaking on it. "Just my code" is checked. And nothing in the Exception Settings window looked like it should trigger it. But I was able to turn off breaking on that exception using the little 'view details' link.  Thank you for your help.
