### ISSUE TITLE
Function stops working after every couple of hours

### ISSUE THREAD

**Issue by gauraviitr** [Azure/azure-functions-host#2689]
The azure functions app works fine on restart. But after a couple of hours it starts throwing this error and stops working. This is what appears on log

2018-04-17T17:04:41.113 [Information] (node:8876) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 139): MongoNetworkError: failed to connect to server [ds012538.mlab.com:12538] on first connect [MongoNetworkError: connect EACCES 104.42.98.42:12538 - Local (undefined:undefined)]

I first thought it was a mongoose issue. However it is working as expected when called from all other places. Even the same function app starts working fully on restart / redeploy. Can you please help out on whats going on here. Additional info: On opening the function on portal I get this message on right edge:

Error:

Bad Gateway - https://[my function app name].azurewebsites.net/admin/host/keys
Session Id: ce5e7d8535604c43ad74fa161f28dff2

Timestamp: 2018-04-17T18:19:07.548Z

**Comment by paulbatum** [comment]
My first guess is that you might be running into an outbound connection exhaustion issue. The consumption plan (if thats what you're running on) has a [limit](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#numerical-sandbox-limits). Have you tried tweaking your mongoose connection pool settings?

**Comment by gauraviitr** [comment]
Yes I'm on a consumption plan (pay as you go). Can you elaborate on what settings should I change in the mongoose connection pool.. I barely have 8 invocations of the function within a span of a minute, each of which attempts to read a specific document from a mongodb database via mongoose (NodeJS)

**Comment by gauraviitr** [comment]
I ended up switching over to CosmosDB and that works better (more reliable than using drivers to connect to an external mongo database). Closing this ticket.
