### ISSUE TITLE
Build.cmd fails at Unit tests phase

### ISSUE THREAD

**Issue by isaacabraham** [Azure/azure-functions-host#269]
Running build.cmd on latest dev branch (once the CA issues in #264 are fixed) gives the following error:

```
RestoreSkipStrongNames:
  "tools\NuGet.exe" restore .nuget\packages.config -PackagesDirectory packages -NonInteractive -Verbosity quiet -ConfigFile .nuget\NuGet.Config
C:\Users\Isaac\Source\Repos\azure-webjobs-sdk-script\WebJobs.Script.proj(48,5): error : Unit tests will not run correctly unless SkipStrongNames is Enabled. Current status: Disabled. Run the EnableSkipStrongNames target to fix this problem.
Done Building Project "C:\Users\Isaac\Source\Repos\azure-webjobs-sdk-script\WebJobs.Script.proj" (default targets) -- FAILED.

Build FAILED.

"C:\Users\Isaac\Source\Repos\azure-webjobs-sdk-script\WebJobs.Script.proj" (default target) (1) ->
(CheckSkipStrongNames target) -> 
  C:\Users\Isaac\Source\Repos\azure-webjobs-sdk-script\WebJobs.Script.proj(48,5): error : Unit tests will not run correctly unless SkipStrongNames is Enabled. Current status: Disabled. Run the EnableSkipStrongNames target to fix this problem.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:21.68
```

**Comment by christopheranderson** [comment]
@mathewc - quality issue for rc? Closable?

**Comment by isaacabraham** [comment]
Do these unit tests still fail? If so - depends on your teams' idea of what a passing build is :)

**Comment by mathewc** [comment]
Not closable, since we are aware of issues with our build script that makes it hard for people to run. The tests are all passing of course on our [AppVeyor CI project](http://ci.appveyor.com/project/appsvc/azure-webjobs-sdk-script-y8o14?branch=master) as well as via VS xunit test runs. We just need to work the kinks out of the script that prevent people "in the wild" from getting clean runs.

**Comment by kashimiz** [comment]
A lot of the build infrastructure has changed significantly since this issue was filed. This is unlikely to still be applicable. @isaacabraham , if you still have problems with this issue, please open a new issue.
