### ISSUE TITLE
Log messages do not show up in Application Insights but do show in logging

### ISSUE THREAD

**Issue by JunyiYi** [Azure/azure-functions-host#2692]
#### Investigative information

I have both http triggers and storage queue triggers that do logging.

The log messages and exceptions logged end up in the normal logging but not in Application Insights.

What is the magic trick to make this happen?

#### Repro Steps

```Java
 
 /** [...snip...] **/
 @FunctionName("test")
  public HttpResponseMessage<?> test(//
      @HttpTrigger(//
          name = "req", //
          methods = { "get" }, //
          authLevel = AuthorizationLevel.FUNCTION) //
      final HttpRequestMessage<String> req, //
      final ExecutionContext context) {

    requireNonNull(context, "Context should not be null in " + CREATE_TEST_DI_SESSION_METHOD_NAME);
    final Logger logger = context.getLogger();
    // logger.setLevel(environment.logLevel());
    // TODO: remove custom logging.
    // addVersionPrefix(logger);
    final LogRecord record = new LogRecord(Level.SEVERE, "hi, ignore this, it is a test");
    logger.log(record);
    logger.log(Level.SEVERE, "this is a test too");
    logger.severe("This is also a test");
// [...snip...]
}
```

#### Actual behavior

When triggered this ends up in the log:
```
hi, ignore this, it is a test
this is a test too
This is also a test
[...snip...]
```

Query for application insights
Limited for the last 24 hours

```
requests
|where name == "test"
| limit 1000
```

Output in Application insights

the customDimensions contains:

LogLevel | Information
-- | --
 Category | Host.Results
| TriggerReason | This function was programmatically called via the host APIs.
 Succeeded | True
 FullName | Functions.test
 EndTime | 2018-04-17T14:54:11.9830000Z

Nothing else in AP seems to to contain my jolly log messages.

**Comment by paulbatum** [comment]
@brettsam Can you take a look at this once you have some time
