### ISSUE TITLE
Service Bus Topic Trigger goes to Sleep - Consumption plan

### ISSUE THREAD

**Issue by yogsgit** [Azure/azure-functions-host#2697]
Hi,

My Azure function with a Service Bus Topic trigger goes in sleep mode and wakes up only on accessing it via the portal or calling a HTTP triggered function in the same app.

The function was working fine since last 1 month and the issue started since 2018-04-16.

The app is on a consumption plan. I deploy the consumption plan and the function app using ARM templates and VSTS continuous deployment.

Function Details:

- Timestamp: 2018-04-18T10:14:47.138 
- Function App version 1.0 or 2.0 :1.0
- Function App name: 
- Function name(s) (as appropriate):
- Invocation ID: b4aeca9c-3775-490d-a466-da4f17d48065
- Region: North Europe

Thanks.

**Comment by paulbatum** [comment]
@mhoeger can you take a look at this?

**Comment by mhoeger** [comment]
@yogsgit - It looks like your service bus topic trigger did not sync correctly with Azure infrastructure (our central listener). Can you either open the Azure Portal and click the Refresh button or make a API call to the sync triggers endpoint: https://github.com/davidebbo/AzureWebsitesSamples/blob/master/ARMTemplates/FunctionsWebDeploy.json#L90

Note that the following deployment options will not sync triggers on a Consumption Plan, aside from HTTP triggers:
 - Editing using App Service Editor, Kudu, or Visual Studio Cloud Explorer
 - Modifying files directly using Azure Storage
 - FTP

Further details can be found here:
https://github.com/Azure/Azure-Functions/issues/210

**Comment by yogsgit** [comment]
@mhoeger Thanks for the solution and clicking refresh on the portal worked.

What i don't get is why this sync issue should have occurred as i am deploying the app using VSTS continuous deployment?

**Comment by paulbatum** [comment]
Can you check whether your VSTS deployment task is using webdeploy?

See this for some context:
https://github.com/Microsoft/vsts-tasks/issues/6759#issue-307334346

**Comment by yogsgit** [comment]
'Publish using Web Deploy' was not selected and i have selected it now.

As per the link in your comment, ZipDeploy is a better option than Web Deploy. Do you suggest using ZipDeploy or Web Deploy is good enough?

Thanks.

**Comment by mhoeger** [comment]
ZipDeploy is better, but Web Deploy is good enough (key shortcoming of Web Deploy being that it can’t be used from non-Windows clients).
