### ISSUE TITLE
Azure Function is returning 404

### ISSUE THREAD

**Issue by TonyHenrique** [Azure/azure-functions-host#2703]
Hi, I am trying to add Authentication to my Azure Function (v2) in C#

My function is a GET or POST on 
http://*secret*.azurewebsites.net/api/SendScreenshot

<br>
I was unable to make Azure AD work with Azure Function. (Please make a blog posting on how to do that)

Then I tried to add Auth0,
I tried this article and created the Security.cs class as described here
https://liftcodeplay.com/2017/11/25/validating-auth0-jwt-tokens-in-azure-functions-aka-how-to-use-auth0-with-azure-functions/

1) Add these Nuget Packages:

Microsoft.IdentityModel.Protocols
Microsoft.IdentityModel.Protocols.OpenIdConnect
System.IdentityModel.Tokens.JWT

2) Publish, access the azure function endpoint

3) Then remove these packages, 
Microsoft.IdentityModel.Protocols
Microsoft.IdentityModel.Protocols.OpenIdConnect
System.IdentityModel.Tokens.JWT

4) publish, access the azure function endpoint. 404
Then my function started to give 404

These extra NuGet packages, I can add, and remove, the Project should run without problem, as long as it builds sucessfully. But when I publish I am getting the 404 error.

**Comment by TonyHenrique** [comment]
[FunctionApp2.zip](https://github.com/Azure/azure-functions-host/files/1928975/FunctionApp2.zip)
This Project causes this 404 error when try to access
http://{function}.azurewebsites.net/api/SendScreenshot

**Comment by paulbatum** [comment]
This doesn't look like an azure functions issue. I suggest you follow up further on understanding the code in the blog post you're referring to.
