### ISSUE TITLE
Regression: function exception information no longer returned in HTTP response body

### ISSUE THREAD

**Issue by elprans** [Azure/azure-functions-host#2706]
We have lots of tests in azure-functions-python-worker that rely on exception information being returned in the HTTP response body.  Recent Host builds seem to return an empty string with 500 response code.

**Comment by pragnagopa** [comment]
You should see an exception stack on invocation.  This was done in commit  [89a296247b1763f81c59d989f47074bba3940908](https://github.com/Azure/azure-functions-host/commit/89a296247b1763f81c59d989f47074bba3940908).

**Comment by pragnagopa** [comment]
@elprans - can you confirm if this is still an issue?

**Comment by pragnagopa** [comment]
Closing this it is dup of https://github.com/Azure/azure-functions-host/issues/2811
