### ISSUE TITLE
Verify synctriggers updates triggers and that app is activated when there is pending work

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-functions-host#2719]
Just doing `POST /admin/host/synctriggers` consistently fails with 500 for me.

**Comment by davidebbo** [comment]
Also, let's make sure the the synctriggers ARM API does the right thing and doesn't try to send the request to the scm site!

**Comment by bala16** [comment]
This is due to ssl errors on private stamp. Fixed by d34db45807435f546b82a19f53c6d2b66a7bade4
