### ISSUE TITLE
Unable to create or run F# functions

### ISSUE THREAD

**Issue by aaronpowell** [Azure/azure-functions-host#2725]
When using VS Code there doesn't appear to be any way to create an Azure Function that uses F# against the `beta` target, and when swapping back to the `~1` target the functions don't get discovered.

#### Investigative information

Please provide the following:

- Timestamp: 2018-04-24 09:46 GMT+10
- Function App version (1.0 or 2.0-beta): Both
- Region: local development
- VSCode: 1.23.0-insider
- Extension: 0.8.1
- OS: Windows 10

#### Repro steps

1. Create a new Azure Function project using the VS Code extension
 * Expect an option to select F#, only C#, Java and JavaScript are available
2. Select C#
3. Create a new Azure Function
4. Change Language type to `F#Script`
 * Expect to see a list of templates
5. Change the runtime from `beta` to `~1`
6. Change the template filter to `All`
7. Select `HTTP Get` and provide a name
8. Launch the function from VS Code
 * Function host does not discover the function

#### Expected behaviour

1. Ability to select F# as an initial language
2. F# templates available for `beta` runtime
3. `~1` templates to work with the function host

#### Actual behavior

1. No ability to select F# initially
2. No F# templates available under the `beta` runtime
3. `~1` templates don't get discovered

#### Known workarounds

The only workaround I can find so far is to use the Azure Portal to create and edit the functions, but the editing experience there isn't as rich and there isn't debugging support.

#### Related information 

Here is a recording of the above repo steps and the problems encountered.

![F# repo steps](https://user-images.githubusercontent.com/434140/39158769-48ae18d8-47a5-11e8-8a7d-9d4e68362243.gif)

**Comment by paulbatum** [comment]
This issue was moved to Microsoft/vscode-azurefunctions#338
