### ISSUE TITLE
Provide way to access the OpenAPI 'documentation' page externally

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#2733]
Customer would like a way to make the OpenAPI documentation page (the right pane in the 'Api Definition') visible publicly, without needing to go through the portal.

**Comment by brettsam** [comment]
@alexkarcher-msft -- FYI, this is what I mentioned to you earlier today

**Comment by paulbatum** [comment]
You can use an external tool/site to render a UX from the exposed swagger/openapi json. Here's an example tool: https://swagger.io/swagger-ui/
