### ISSUE TITLE
Look for language workers through environment variable `WORKERS__<language worker>__PATH` 

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#2739]
We should be able to configure the workerPath via _config variable (workers:<language worker>:path; ex: "workers:node:path") for local development. Described here: https://github.com/Azure/azure-functions-host/wiki/Language-Extensibility

https://github.com/Azure/azure-functions-host/blob/8cf5398c804e92a1cadd23252e6580458e47a2d6/src/WebJobs.Script/Rpc/Configuration/WorkerConfigFactory.cs#L33

**Comment by mhoeger** [comment]
@pragnagopa yep - that did work! I was looking at documentation here that configures by `$env:WORKERS__NODE__PATH`. I think that was working before as well (i think it still works with current CLI). Should I update the documentation to resolve this bug?

https://github.com/Azure/azure-functions-host/wiki/Language-Extensibility

**Comment by pragnagopa** [comment]
Yes. Let’s update documentation
