### ISSUE TITLE
Inconsistent log counts in Application Insights between requests, traces, and customMetrics

### ISSUE THREAD

**Issue by kczelusniak** [Azure/azure-functions-host#2742]
I turned on my function between `2018-04-24T21:25Z` and `2018-04-25T03:06Z`. These are the log counts from this run:

Source | Count
------------ | -------------
requests | 4,548,278
traces (started) | 4,695,295
traces (completed) | 4,512,500
customMetrics (aggregated counts) | 4,654,954
Custom logging (should be one per function invocation) | 4,512,593

Why are these counts inconsistent? I understand that the WebJobs SDK writes to `requests` and that Functions Host writes to `traces` and `customMetrics`. But I have the following questions:
1. Why are the log counts from WebJobs SDK less than log counts from Functions Host?
2. Why is there a difference between `traces (started)` and `customMetrics (aggregated counts)` if Functions Host is responsible for writing both of these logs?

Is there a reason that these logs are inconsistent? Are logs being dropped somewhere? Can I rely on logging to log all failures so that I can take the appropriate action on those failures?

#### Investigative information

This is the first invocation of my function from the run:

- Timestamp: `2018-04-24T21:25:12.377Z`
- Function App version (1.0 or 2.0-beta): `1.0.11612.0`
- Function name(s) (as appropriate): `RouteAssetStructureMessage`
- Invocation ID: `536db463-c987-4c9e-b1f1-2304b9c510ea`
- Region: `South Central US`

This is the last invocation of my function from the run:

- Timestamp: `2018-04-25T03:05:13.238Z`
- Function App version (1.0 or 2.0-beta): `1.0.11612.0`
- Function name(s) (as appropriate): `RouteTelematicsStandardFormatMessage`
- Invocation ID: `872dc04b-3103-4dce-8399-72b90487ce9e`
- Region: `South Central US`

#### Related information 

* Programming language used: C#
* Bindings used: `ServiceBusTrigger`, `EventHubTrigger`, `Blob`

**Comment by paulbatum** [comment]
You can't always assume that these numbers will line up exactly. Some of the logging is best-effort (this can be at the app insights client layer sometimes).

One thing to check is whether you have adaptive sampling enabled:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#configure-sampling

**Comment by kczelusniak** [comment]
We have sampling disabled.

Thank you, though.
