### ISSUE TITLE
CLI doesn't work if node 9.x is installed 

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#2758]
_From @Knaackee on November 27, 2017 17:34_

I try to run the function emulator on my mac but get the following error on start.
Any ideas ?

```
$ func host start

......

info: Worker.Node.3dce2ab7-8ac1-43e8-97f0-88c8b2a8554d[0]
      Couldn't require bundle, falling back to Worker.js. Error: Cannot find module '/Users/myUsername/.azurefunctions/bin/workers/node/grpc/src/node/extension_binary/node-v59-darwin-x64/grpc_node.node'
info: Worker.Node.3dce2ab7-8ac1-43e8-97f0-88c8b2a8554d[0]
      module.js:544
info: Worker.Node.3dce2ab7-8ac1-43e8-97f0-88c8b2a8554d[0]
          throw err;
info: Worker.Node.3dce2ab7-8ac1-43e8-97f0-88c8b2a8554d[0]
          ^
info: Worker.Node.3dce2ab7-8ac1-43e8-97f0-88c8b2a8554d[0]
      Error: Cannot find module './Worker.js'
```

_Copied from original issue: Azure/azure-functions-core-tools#326_

**Comment by ahmelsayed** [comment]
_From @nagytech on November 27, 2017 19:23_

Try installing with this: `npm i -g azure-functions-core-tools@core --unsafe-perm`

**Comment by ahmelsayed** [comment]
_From @Knaackee on November 28, 2017 9:41_

I did that already and did it again. I have to use `sudo` though.
Sadly, this changes nothing.

**Comment by ahmelsayed** [comment]
_From @Knaackee on November 28, 2017 9:46_

Found the problem. I had node version 9.2 installed. After downgrading to 8.9 its working now.

**Comment by ahmelsayed** [comment]
_From @compulim on December 11, 2017 3:40_

The tool looks pretty broken now. @ahmelsayed are you looking at this?

**Comment by ahmelsayed** [comment]
_From @nelak on December 11, 2017 12:8_

It looks like newer versions of node need a newer grpc extension, that's why going back to v8.9.0 is working. Node v9.2.0 would require `node-v59-darwin-x64/grpc_node.node` to work.

The Azure functions cli install only provides support for these extensions:
```
node-v48-win32-ia32
node-v57-darwin-ia32
node-v57-darwin-x64
node-v57-linux-ia32
node-v57-linux-x64
node-v57-win32-ia32
node-v57-win32-x64
```

**Comment by ahmelsayed** [comment]
Thank you @Knaackee and @nelak for find the root cause of the issue. I'll update package.json to set 8.x as the upper bound of node, though for actual support of node 9.x the issue should go on the runtime repo here https://github.com/Azure/azure-webjobs-sdk-script/issues

**Comment by ahmelsayed** [comment]
_From @snobu on January 3, 2018 10:11_

Just saving a few minutes for folks with Macs - to revert to Node 8.x:

```
% brew link node@8 --force                                                                        ~
Linking /usr/local/Cellar/node@8/8.9.4... 7 symlinks created

% node -v                                                                                         ~
v8.9.4
```

**Comment by ahmelsayed** [comment]
_From @jhealy on February 8, 2018 14:36_

Any timeline for when this will work with node 9.x?

**Comment by ahmelsayed** [comment]
_From @jhealy on February 8, 2018 14:37_

You can also fall back to the non-core version of cli by using the non-core version of node.
Install via "npm i -g azure-functions-core-tools" instead of "npm i -g azure-functions-core-tools@core".

**Comment by ahmelsayed** [comment]
_From @ntomsic on April 17, 2018 21:50_

Any update on this? Huge hassle for Macs.

**Comment by ahmelsayed** [comment]
_From @PoisonousJohn on April 20, 2018 17:16_

@ntomsic  For linux as well

**Comment by ahmelsayed** [comment]
_From @ntomsic on April 26, 2018 14:53_

And now we are at Node 10 for LTS.

**Comment by harmonicradius** [comment]
Why is this closed?

**Comment by ahmelsayed** [comment]
@harmonicradius it's not closed

**Comment by pragnagopa** [comment]
Thanks for reporting. Here are tracking issues to update grpc:

- host https://github.com/Azure/azure-functions-host/issues/2747
- nodej worker https://github.com/Azure/azure-functions-nodejs-worker/issues/65

Closing this as dup.
