### ISSUE TITLE
"Unable to configure java worker. Could not find JAVA_HOME app setting." in the C# Azure Function v2

### ISSUE THREAD

**Issue by JunyiYi** [Azure/azure-functions-host#2765]
#### Investigative information

Please provide the following:

- Function App version: 2.0-beta
- Function App language: C#

#### Repro steps

1. Create Azure Function v2 in Visual Studio 2017
2. Select C# language

#### Expected behavior

I can start writing a Functions app using C#.

#### Actual behavior

Error messages show in the console:
- "Unable to configure java worker. Could not find JAVA_HOME app setting."
- "Could not configure language worker Java."

#### Known workarounds

-  Add JAVA_HOME to system variables and restart computer.

#### Related information 

@m-demydiuk noticed that azure function works with this error in the console. So this red error doesn't break function on the local machine. But I am afraid it may cause any problems in other environments.

Before this customer goes live, he needs to know, why this error occurs. He does not use java worker, he does not use durable functions lib and also he does not use Java in this project. So why this occurs?

**Comment by pragnagopa** [comment]
We have fixed the host to not show error message if Java_home is not set and there are not java fucntions.
Closing this as Dup of #2668

**Comment by JohnReeson** [comment]
@FlippieCoetser  Latest version of Azure Functions and Web Jobs Tools is 15.10.2046.0. After update, check whether you can see latest CLI and host version when debugging project.
```
Azure Functions Core Tools (2.1.748 Commit hash: 5db20665cf0c11bedaffc96d81c9baef7456acb3)
Function Runtime Version: 2.0.12134.0

**Comment by petrce** [comment]
ok fixed with this trick:
https://github.com/Azure/azure-functions-vs-build-sdk/wiki/How-to-manually-update-the-Azure-Functions-Core-Tools
but I think latest Azure Functions and Web Jobs Tools are broken

**Comment by JohnReeson** [comment]
@petrce Probably related to this tracking [issue](https://github.com/Azure/azure-functions-core-tools/issues/694).
