### ISSUE TITLE
Disabled property not honored locally

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#2767]
_From @ssougnez on March 4, 2018 13:57_

Hello,

I have the following function:

```
{
    "disabled": true,
    "bindings": [
        {
            "name": "CalculateDonationPoints",
            "type": "timerTrigger",
            "direction": "in",
            "schedule": "0 * * * * *"
        }
    ]
}
```

However, when I launch `func host start` locally, this function gets executed despites the `disabled` flag. 
I'm using the following version of the package:

Azure Functions Core Tools (2.0.1-beta.22)
Function Runtime Version: 2.0.11415.0

_Copied from original issue: Azure/azure-functions-core-tools#396_

**Comment by pragnagopa** [comment]
disabled property does not apply to V2. Disabled property is now an AppSetting at the function level. Here is a tracking issue to update doucumentation: [Azure/Azure-Functions/issues/736](https://github.com/Azure/Azure-Functions/issues/736). Closing this issue.

**Comment by ahmelsayed** [comment]
so it can no longer be a boolean value?

**Comment by pragnagopa** [comment]
This property is ignored by the runtime. @alrod - Can you please confirm?
@soninaren - Do we have a tracking item to fix function.json schema?
