### ISSUE TITLE
Non-string header values on http response throws error 

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#2768]
_From @graham-sportsmgmt on February 17, 2018 3:49_

azure-functions-core-tools@2.0.1-beta.22
JavaScript HttpTrigger 
Local function emulator on Windows 10 x64

I am trying to set a response header in order to flag the length of the result set to our front end code.

This method throws an error:

```
context.res = {
  "headers" : { "length": response.length },
  "body": response
};
```

> invocationResponse.outputData.data.http.headers: string{k:string} expected

This method doesn't throw an error, but adds no header to the response:

`context.res.setHeader('length', response.length);`

_Copied from original issue: Azure/azure-functions-core-tools#386_

**Comment by ahmelsayed** [comment]
_From @pilot4u on February 22, 2018 11:55_

I'm struggling with this issue as well, has anyone managed to overcome this issue?

**Comment by pragnagopa** [comment]
@mhoeger  - here is the test that might be throwing the same error [BadContentType_ThrowsExpectedException_Conneg](https://github.com/Azure/azure-functions-host/blob/dev/test/WebJobs.Script.Tests.Integration/ScriptHostEndToEnd/NodeContentTests.cs#L63)

**Comment by pragnagopa** [comment]
This issue was moved to Azure/azure-functions-language-worker-protobuf#9
