### ISSUE TITLE
Multiple cli instances causing lots of cpu usage when app is idle if each instances does not define a unique node debug port.

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#2775]
_From @johlrich on January 5, 2018 16:37_

I noticed when I would launch multiple cli instances that some of the func.exe processes were consuming a lot of CPU resources even when the application was still idle after startup.

Since I don't use node with azure functions, I originally did not bother ensuring that each instance had a unique port and just ignored the address in use error.

Workaround: 
After profiling I noticed node.dll was consuming a lot of resources on the pids that showed the address in use error. Once I modified my scripts to include the `--nodeDebugPort` on each app with unique ports, I no longer noticed this behavior.

![func-cpu](https://user-images.githubusercontent.com/1655793/34618191-f5f29590-f20b-11e7-8efe-c1e2afe181e0.png)

_Copied from original issue: Azure/azure-functions-core-tools#346_

**Comment by pragnagopa** [comment]
Need investigation on how host launches language workers with multiple CLI instances.

**Comment by pragnagopa** [comment]
This is fixes in https://github.com/Azure/azure-functions-core-tools/commit/e89a00b36f76a23608c42239665f467798b6a7a3 CLI no longer hardcodes node debug port.
