### ISSUE TITLE
libgrpc csharp contains native binaries that are not available for arm platform

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#2778]
The csharp grpc package brings in some native binaries for amd64 and x86 arch only. 
To run on arm devices, it needs to include an arm32v7 and arm64v8

**Comment by pragnagopa** [comment]
As of now binaries for arm are not included in the grpc nuget package. Here is an active issue on grpc: [grpc/issues/1620](https://github.com/grpc/grpc/issues/1620). If this is a blocking issue we need to compile for arm from grpc source

**Comment by ahmelsayed** [comment]
That's what I do now. I have them cross-compiled and committed here https://github.com/Azure/azure-functions-docker/tree/master/host/2.0/stretch/arm32v7/python3.6 but ideally we would either compile them in the docker image, or provide arm builds in the nuget package.

**Comment by ahmelsayed** [comment]
looks like we have to do the same thing for python grpcio package. I'll move this to the docker repo since we probably can just automate the build for arm dependencies all in docker.

**Comment by pragnagopa** [comment]
Will keep an eye for grpc nuget updates that will include libraries for arm.
