### ISSUE TITLE
C# Time trigger doesn't fire when set schedule to every hour

### ISSUE THREAD

**Issue by johnnyzhang82** [Azure/azure-functions-host#2783]
I am new to Function app and here is my issue. I created and publish a time trigger(C#) and set time trigger to one hour in VS2017. Next day when I check the logs in portal and there are nothing recorded after app published. As you can see in attached screenshot, nothing is being logged before red line. I tried to set my time trigger with different time interval. I realize the time trigger will fire when schedule is set to 5 minutes ("0 */5 * * * *") as you can see after redline in attached screenshot, but it will fail when it is set to a larger time(Ex.  one hour "0 0 */1 * * *"). I wonder what might be the issue here.  Thanks for any help.

![image](https://user-images.githubusercontent.com/26984399/39541147-ad3af168-4df9-11e8-86ae-8bbef4513a09.png)

#### Investigative information

Please provide the following:

- Timestamp: 2018-05-02
- Function App version (1.0 or 2.0-beta): 2.0.11651.0 (beta)
- Function App name: GithubJobTimeTriggerDev
- Function name(s) (as appropriate): TimeTrigger
- Invocation ID: 
- Region: Central US

**Comment by pragnagopa** [comment]
Please see CRON expression examples [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer#cron-examples). To run every hour, set it to: 

"0 0 * * * *"

**Comment by johnnyzhang82** [comment]
The job schedule still doesn't trigger even after set vlaue to "0 0 * * * *".
