### ISSUE TITLE
Update CI builds to use x86 dotnet.exe

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#2800]
Azure uses x86 by default. CI needs to be updated to x86 as well. Related info in #2799

**Comment by pragnagopa** [comment]
cc: @fabiocav 
x86 dotnet sdk exists on AppVeyor but is a older version: 2.0.0 vs x64 version: 2.0.5 
We need to install same version as x64

**Comment by pragnagopa** [comment]
Assigning to fabio as the is working on updating the build script to preview version of dotnet

**Comment by brettsam** [comment]
@fabiocav -- can you weigh in here on whether we need to do this anymore?

**Comment by fabiocav** [comment]
@pragnagopa , meant to chat about this but didn't have a chance.

Will move this to the next sprint so we have time to discuss.

**Comment by fabiocav** [comment]
@pragnagopa removing the spring assignment for this as I don't believe this is a priority anymore. Will leave it open, but in backlog.
