### ISSUE TITLE
Disabled functions won't disappear in Portal once source has been removed

### ISSUE THREAD

**Issue by lukasvosyka** [Azure/azure-functions-host#2805]
Hi,

I had a function in my function app that I disabled using Attribute "Disable". After deployment to Azure it correctly showed "(disabled) FunctionName".
When I removed the function from the source and redeployed, I was expecting that the function "FunctionName" wouldn't appear in  Portal at all, but it does (still in mode (disabled)).

**Comment by pragnagopa** [comment]
Is this function app using V1 or V2?

**Comment by lukasvosyka** [comment]
V1

**Comment by pragnagopa** [comment]
You need to set "Remove additional files at destination" in Manage Profile Settings --> Profile Settings
![removeadditionalfiles](https://user-images.githubusercontent.com/1874279/39724025-6b84217a-51fc-11e8-83ae-5ca922c24b60.png)
