### ISSUE TITLE
Linux: timestamp in logs don't have precise enough resolution

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-functions-host#2806]
All the timestamps I see have a 1 second resolution, e.g.

    2018-05-07 01:06:03.0000000
    2018-05-07 01:06:04.0000000

We need the full resolution as we have on Windows to properly investigate issues (in particular perf issues).

**Comment by mathewc** [comment]
The issue I believe is that the PreciseTimeStamp column is being populated based on when the import components process the log files. I'll confirm with them.

The EventTimestamp column is populated by the runtime directly and should contain the precise time when each event was emitted. It is UtcNow at the point the event was logged.

**Comment by davidebbo** [comment]
Yes, `EventTimestamp` does have better granularity. Do we completely control what it looks like? Right now it's using AM/PM format, so if possible, would be good to use a 24 hour clock like all the other time columns.

Also, right now Kusto doesn't view it as being a time, and trying to compare it to one fails with "Cannot compare values of types string and datetime. Try adding explicit casts". Not sure how to achieve the right format.

**Comment by dariagrigoriu** [comment]
No repro.
