### ISSUE TITLE
Linux: cold start is too slow

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-functions-host#2808]
Despite using a placeholder site and doing assignment, I'm seeing cold start averaging 4.5s over 10 runs.

Here are all the timings: 4.25, 3.74, 5.92, 4.74, 4.74, 4.16, 4.50, 4.96, 4.44, 3.96

We need to figure out where the time is being spent.

**Comment by mathewc** [comment]
I recently added detailed logging on the specialization path, which should allow us to determine where the time is spent. Not sure if you're running that version in your test stamp yet. The changes were made in this commit: https://github.com/Azure/azure-functions-host/commit/c078c43056725c7bcc4fdd862584726413849620.

**Comment by davidebbo** [comment]
@bala16 can you check if you have this changeset right now?

**Comment by davidebbo** [comment]
As we found, a huge part of the problem is the slow file system, and an upcoming platform change should help a lot.

**Comment by rauchg** [comment]
@davidebbo @mathewc curious about what those numbers look like now? How did you measure them?

**Comment by balag0** [comment]
closing stale issue.
