### ISSUE TITLE
Azure Function Proxy adding Expect header to my requests

### ISSUE THREAD

**Issue by eggm0n** [Azure/azure-functions-host#2816]
#### Investigative information

- Timestamp:
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name: https://expect100proxy.azurewebsites.net
- Function name(s) (as appropriate): HttpTriggerJS1
- Invocation ID:
- Region: westeurope

I haven't added a specific invocation as it is so easy to reproduce.

#### Repro steps

Create a new function app (expect100app) to act as our application which will simply return the headers it receives in the response body. Create it with a default function such as HttpTriggerJS1:
 
function.json
``` 
{
  "disabled": false,
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}
```

index.js
``` 
module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    context.res = {
        body: req.headers
    };

    context.done();
};
``` 
 
Create a new function app (expect100proxy) to act as a Proxy, with the following example proxies.json. Note how it proxies the `/test` request to the app we created previously:
 
proxies.json
``` 
{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
        "expect100proxy": {
            "matchCondition": {
                "route": "/test"
            },
            "backendUri": "https://expect100app.azurewebsites.net/api/HttpTriggerJS1?code=8osqwi5D7SxOM3WHFLPgWK8..."
        }
    }
}
```
Send a POST request to the proxy using curl (insert your own proxy url):
 
`curl -i -X POST --data {} https://expect100proxy.azurewebsites.net/test`
 
Note the data included in the response which is a copy of the headers which were received by the application.

#### Expected behavior

To receive a response containing the headers which were sent to my application, NOT including an `Expect` as I did not explicitly add it.

#### Actual behavior

Receive a response body showing that the app received the `Expect` header:

```
HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 1010
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
X-Powered-By: ASP.NET
Date: Tue, 08 May 2018 12:27:35 GMT

{"connection":"Keep-Alive","accept":"*/*","expect":"100-continue","host":"expect100app.azurewebsites.net","max-forwards":"6","user-agent":"curl/7.54.0","x-waws-unencoded-url":"/api/HttpTriggerJS1?code=8osqwi5D7SxOM3WHFLPgW...","client-ip":"10.151.144.47:38652","is-service-tunneled":"0","x-arr-log-id":"3e82220c-223e-4748-bc8f-19c277faa09b","disguised-host":"expect100app.azurewebsites.net","x-site-deployment-id":"expect100app","was-default-hostname":"expect100app.azurewebsites.net","x-original-url":"/api/HttpTriggerJS1?code=8osqwi5D7SxOM3WHFLPgW...","x-forwarded-for":"156.67.248.14:38013, 156.67.248.14,156.67.248.14, 104.40.212.192:28784, 10.151.144.47:38652, 10.151.144.47","x-arr-ssl":"2048|256|C=US, S=Washington, L=Redmond, O=Microsoft Corporation, OU=Microsoft IT, CN=Microsoft IT TLS CA 4|CN=*.azurewebsites.net","x-forwarded-proto":"https","x-ms-coldstart":"1","content-length":"2","content-type":"application/x-www-form-urlencoded"}
```

#### Known workarounds

Sending the request without any data in the request body will not reproduce this issue, but is not a workaround as we need to be able to send data in the request body.

#### Related information 

I could not find a duplicate of this issue. Also please let me know if I should post this issue in another repo.

Is this a known issue? Is it fixed in 2.0? What is the timeline for supporting proxies in 2.0?

Thanks

**Comment by paulbatum** [comment]
@vfedonkin @safihamid can you help with this one?

**Comment by vfedonkin** [comment]
@eggm0n , I tried to repro the issue without the curl and don't have 100-continue header.
Could you please try to call your proxy from other client or disable 100-continue in curl explicitly like described here: https://gms.tf/when-curl-sends-100-continue.html

**Comment by eggm0n** [comment]
@vfedonkin thanks for looking. I probably should have been clearer, I already have a full system which has this problem, I added these reproduction steps for simplicity. The issue is specific to POST, PUT, PATCH requests which have a value in the request body (hence why I specify those in the curl). I can reproduce this in other clients such as Postman. This is not an issue I am having with curl that I am trying to solve, this issue is seen in the browser when using our actual system.

**Comment by vfedonkin** [comment]
![proxycall_no100continue](https://user-images.githubusercontent.com/19784224/39882991-18208908-5475-11e8-93a3-079d8006d1b7.png)

Hi @eggm0n , I tried to repro the issue with the same index.js and proxy config. I sent the request using fiddler, so I can be sure that no additional headers were attached to the request. Response doesn't contain any 100 continue headers (please see attached screenshot). I believe it's your client (browser or postman, or even some firewall) adds additional headers in the request.

**Comment by eggm0n** [comment]
@vfedonkin it looks to me like you are sending a request directly to your application in this case e.g. in my example I send the request to the proxy. In my example the response contains `"host":"expect100app.azurewebsites.net"`, and I sent the request to `expect100proxy.azurewebsites.net`. In your example both `host` and original request are the same. The setup to reproduce should be

client -> proxy -> app

It is at the point where the proxy proxies the request that the header gets added. This is why I get the app to simply put all the request headers in the response body, to demonstrate the request headers it received. Hope this helps.

**Comment by vfedonkin** [comment]
Hi @eggm0n ,  no, I called the proxy, but I found the difference: you have proxy and app installed on different function apps, I have them on the same function app. So I could repro the issue, thank you. Investigating. As I know, it should be already fixed in V2.
As a workaround, is it possible for you to use proxy and app on the same function app?

**Comment by eggm0n** [comment]
Hi @vfedonkin thanks for looking. Interesting that it can't be reproduced when proxy and app are in the same function app! Unfortunately it's not a workaround for my case as my app is not actually a function app in my real system. Good to know it's fixed in V2 already. Do you know if there is a timeline for this as I understood that Proxies were not yet supported in V2?

**Comment by vfedonkin** [comment]
Hi @eggm0n, proxies are not supported in V2 yet but the release is currently going and we expect it to be completed this week.

**Comment by safihamid** [comment]
proxies are supported in V2 now and this is addressed in V2.
