### ISSUE TITLE
Azure Function Gets in Hung State With No Helpful Logs and Information (Memory Leak)

### ISSUE THREAD

**Issue by aeghbal1** [Azure/azure-functions-host#2817]
Azure Function Gets in Hung State With No Helpful Logs and Information.

Basically after a few hours my function gets into a hung state with no useful log.   I am not seeing any error/exception/warning in the logs and actually the logs stop flowing into application insight as well.

**Comment by paulbatum** [comment]
Please provide the information in the issue template, otherwise this issue is not actionable.

**Comment by aeghbal1** [comment]
+ Nikelesh

Nikelesh,
Did you follow up on how we can proceed putting further details on this?  Could you add the exception in the ticket?

Thanks,
Arash

**Comment by aeghbal1** [comment]
This looks like a memory leak to me in Azure functions.  As time goes by the committed memory increases, up to a point that causes hung.

I have 2 Azure Functions (one Time Triggered and one Queue Triggered).
I also make sure that I dispose any client that I manually (non binding) create at the end of my functions. (client like Cosmos DB client)
I added some additional logs and found out at some point calling Dispose (on line my Cosmos DB client) would take a really long time.

Feel free to IM me and I would be glad to provide you more information on my App.

Thanks,
Arash

**Comment by paulbatum** [comment]
Please take a look at this document - we have found in general that creating and disposing of a document client per function invocation can be problematic:
https://github.com/Azure/azure-functions-host/wiki/Managing-Connections

**Comment by aeghbal1** [comment]
Thank you Paul,
This is really helpful. This should for sure solve my memory leak problem.  I'll report, by Tuesday, the final result, and then we can close this ticket.

BTW, I think, an article like this should be one of the first documents one should read when getting started with Azure Functions.  Have you thought about incorporating this information in a get started page like the following?
https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function

Thanks,
Arash

**Comment by aeghbal1** [comment]
Thank you again Paul,
Your advise fixed my problem and I no longer see memory leak or function hung.
We can close this.
Thanks,
Arash

**Comment by paulbatum** [comment]
@aeghbal1 Glad to hear this resolved your issue. I agree with you that this information needs to be easier to find through the official documentation and there is a work item for it to be moved there.
