### ISSUE TITLE
Cron expression for 15 min increments does not fire on the 15th min of the hour

### ISSUE THREAD

**Issue by stevenwilliamsmis** [Azure/azure-functions-host#2823]
I am using durable functions framework, if needed I can post this over in the durable functions git hub as well....not sure if this is a core issue with timer functions or a result of the durable functions framework. 

When using a cron expression as below, I would expect that a timer function would fire every 15mins on the min. So 00,15,30,45.  It appears that this expression is only firing on minutes 00, 30, and 45 but not on 15. 

This is the expression that I am having issues with.....
> 0 */15 * * * *

I also experienced the same issue with the following expression...
> 0 0,15,30,45 * * * *

I have other functions with the following expressions that are firing as expected
Every ten minutes on the minute
> 0 */10 * * * *

Every thirty minutes on the minute
> 0 */30 * * * *

Every hour on the hour
> 0 0 * * * *

At 15:11 UTC I changed the every 15 min expression to 0 */5 * * * * (every 5 mins) and it fired at 15:15 UTC as expected.  I switched it back to 0 */15 * * * * and at 16:15 UTC the timer was not fired.

#### Investigative information

Please provide the following:

- Timestamp: 2018-05-09 12:00:00.021 UTC - 2018-05-09 17:30:00.036 UTC
- Function App version (1.0 or 2.0-beta): 2.0-beta 
- Function App name: would rather not share
- Function name(s) (as appropriate): SQLMRTTimerQuarterHour
- Invocation ID: bdb15ad9-c916-4365-b28a-8ad9174da5f7
- Region: Central US

#### Repro steps

Provide the steps required to reproduce the problem:

Create a Timer function with the following bindings

```
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.13",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "timerTrigger",
      "schedule": "0 */15 * * * *",
      "useMonitor": true,
      "runOnStartup": false,
      "name": "myTimer"
    }
  ],
  "scriptFile": "../bin/Insights.Orchestration.SQLMRT.Functions.dll",
  "entryPoint": "Insights.Orchestration.SQLMRT.SQLMRT.RunQuarterHour"
}
```
watch the execution times over a period of and hour or two.  You will notice that the 15th min of every hour is skipped.

#### Expected behavior

After the 00 min 15th min, 30th min 45th min.  I would expect the timer to fire.

#### Actual behavior
Timer fires on minutes 00, 30 and 45.

Timer does not fire on 15th min

#### Known workarounds

no known work around

#### Related information 

Provide any related information 

* Programming language used : .Net C#
<details>
<summary>Source</summary>

```csharp
        [FunctionName("SQLMRTTimerQuarterHour")]
        public static async Task RunQuarterHour([TimerTrigger("0 */15 * * * *")]TimerInfo myTimer,
            [OrchestrationClient] DurableOrchestrationClient starter,
            ILogger log)
        {
            LoggingBuilder logB = new LoggingBuilder();
            ILogging _log = logB.GetInstance(log);

            IOrchestrationArgs args = new OrchestrationArgs();
            args.TimerType = (int)TimerTypeEnum.Every_15_Minutes;
            args.TaskType = (int)TaskTypeEnum.SQL;

            string functionName = "SQLMRTOrchestrater";
            string instanceId = await starter.StartNewAsync(functionName, args);
            _log.WriteLog($"Started 15 Minute SQLMRT orchestration with ID = '{instanceId}'.");
        }
```
</details>

**Comment by paulbatum** [comment]
@soninaren Can you help route this one? Not sure if its a timer issue or durable issue.

**Comment by stevenwilliamsmis** [comment]
upon further research, it appears that my logs were sampling, I do see instances of it firing now.  Apologies, thanks for taking the time to look into it.
