### ISSUE TITLE
Timer Stopped Scheduling

### ISSUE THREAD

**Issue by logandersen** [Azure/azure-functions-host#2825]
I have an azure function that has been running every half hour. It has been running fine for a couple of months but all the sudden on 5/7/2018 it stop scheduling the timer. The last update to the function was made 5/1/2018. I have found that if I open the monitor and refresh the view then it notices that it missed an execution and runs but only if i keep refreshing the monitor. I have tried restarting the function and it will schedule the first half hour increment but then it stops scheduling.

I am using the azure function visual studio extension to publish the function. Here is the timer code and the function.json that is rendered after the publish.

![image](https://user-images.githubusercontent.com/13840113/39838597-13c4b85e-5397-11e8-9f4c-29ad4d4e6589.png)

![image](https://user-images.githubusercontent.com/13840113/39838571-fa9dbf56-5396-11e8-89ce-b27a84e114fa.png)

- Timestamp: 2018-05-09T20:21:48.196
- Function App version: 1
- Function App name: Would rather not provide
- Function name(s) (as appropriate): Would rather not provide
- Invocation ID: 76bdf5c9-e485-416e-bb72-de82f3906aac
- Region: Central US

**Comment by peppi-scaleforce** [comment]
Same problem with our functions as from yesterday 08.05.2018 , 20:06. The functions have been running for months without any issues. From yesterday the functions stop frequently as you can see on the image. We have Timer triggers, CosmosDB triggers etc.
![image](https://user-images.githubusercontent.com/26489507/39839234-317ca076-53e4-11e8-9a6f-38a70ff6ace4.png)

Timestamp: 2018-05-09T21:10:00.013 UTC
Function App version (1.0 or 2.0-beta): 1.0
Function App name:  Would rather not provide
Function name(s) (as appropriate): UndeferScheduler
Invocation ID: 92cf9e85-9687-42c1-812f-0b1d762af155
Region: Central India

Please investigate.

**Comment by paulbatum** [comment]
@alrod can you take a look?

**Comment by alrod** [comment]
We found a bug when scheduler is crashed and never started. The fix will be deployed to PROD in 2 weeks approximately. As workaround you can write a timer triggered function that triggers every minute and ping your function app to keep it warm.

**Comment by fabiocav** [comment]
Closing as resolved/stale
