### ISSUE TITLE
App Insights feature parity on Linux

### ISSUE THREAD

**Issue by alexkarcher-msft** [Azure/azure-functions-host#2826]
Currently it looks like App Insights doesn't support a few different features on linux apps:

* JS Functions don't write traces
* All executions set HTTP status code to 500 in logs
* Live metrics stream does not work on linux

**Comment by ahmelsayed** [comment]
@alexkarcher-msft Did you update your docker image after creating a linux app, or did you just use the app as is after creating it from portal?

**Comment by paulbatum** [comment]
@alexkarcher-msft ping on the question above - you might be using out of date bits

**Comment by alexkarcher-msft** [comment]
I was just using the defaults from the portal. On the portal my runtime version is listed as 2.0.1.0. Where are the instructions to update the image? The only thing I could find online was this doc for a custom image. https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image

**Comment by dariagrigoriu** [comment]
Obsolete.
