### ISSUE TITLE
ServiceBus Config Options have changed

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#2828]
After the v2 extension migration, the underlying SB SDK has changed, but we haven't updated our schema files and/or documentation. E.g. autoRenewTimeout no longer exists in SB, so our schema is out of date [here](https://github.com/Azure/azure-functions-host/blob/3407d8bca5da44cbe3114c9fd7f0a8133d2fa876/schemas/json/host.json#L131).

We actually need to verify that SB configuration works in v2 from Functions host.json. We used to do this [here](https://github.com/Azure/azure-functions-host/blob/v1.x/src/WebJobs.Script/Binding/ServiceBusScriptBindingProvider.cs#L44) in v1. Where does this logic exist now? In v2 I believe we're relying on the new generalized logic [here](https://github.com/Azure/azure-webjobs-sdk/blob/897b9f75400e58faaea0beaf39510190e1e81d6f/src/Microsoft.Azure.WebJobs.Host/Config/ExtensionConfigContextExtensions.cs#L85).  That suggests a new config format like:

```javascript
{
    "serviceBus": {
        "messageOptions": {
            "maxAutoRenewDuration": "00:05:00"
            "maxConcurrentCalls": 5
        }
    }
}
```
We need to make sure this logic correctly handles string -> TimeSpan conversions, etc.

**Comment by paulbatum** [comment]
Retest this after the DI work is merged.

**Comment by mathewc** [comment]
As part of reviewing/fixing service bus configuration, we should also look at https://github.com/Azure/azure-functions-host/issues/2828 and see what other options if any we should add.

**Comment by jonbjo** [comment]
This issue being resolved, does that mean that the next release will pick up maxAutoRenewDuration maxConcurrentCalls if they are defined in host.json according to https://github.com/Azure/azure-functions-host/blob/dev/schemas/json/host.json#L261?

Will it make it into next release of azure-functions-core-tools (2.0.1-beta.36)? ETA?
What is the ETA for this to work in production?

**Comment by paulbatum** [comment]
To make it more explicit - see the example here:
https://github.com/Azure/azure-functions-host/wiki/host.json-(v2)
