### ISSUE TITLE
Azure Function Fails to Compile a call to CloudBlockBlob::UploadFromFile(string)

### ISSUE THREAD

**Issue by rabrahamOpti** [Azure/azure-functions-host#2830]
- Timestamp: 2018/05/10 at ~19:01 EST 
- Invocation ID: a606581d-741b-41a9-9527-f3b486dadab3
- Region: Central US

I'm trying to write to a block blob from an Azure Function. This code worked on my desktop:

> CloudBlockBlob localBlob = **cloudBlobContainer.GetBlockBlobReference(testFileName);
> localBlob.UploadFromFile($"{filepath}{localBlob.Name}", FileMode.Open);

But the Azure function threw an exception

> Method not found: 'Void Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.UploadFromFile(System.String, System.IO.FileMode, Microsoft.WindowsAzure.Storage.AccessCondition, Microsoft.WindowsAzure.Storage.Blob.BlobRequestOptions, Microsoft.WindowsAzure.Storage.OperationContext)'.

I realized that locally, I am using `Microsoft.WindowsAzure.Storage version 4.3.0.0`, but the Azure Function App is using `Microsoft.WindowsAzure.Storage is 7.2.1.0`

[It looks like the function signature changed](https://github.com/Azure/azure-storage-net/blob/v7.2.1/Lib/ClassLibraryCommon/Blob/CloudBlockBlob.cs#L864), and only the filepath is required. So I deleted the FileMode variable, and the call looks like this:

> localBlob.UploadFromFile($"{filepath}{localBlob.Name}");

I triggered the Azure Function with this update at ~19:06 EST, and saw an error that said the function app failed to compile.

> Microsoft.CodeAnalysis.Scripting.CompilationErrorException : Script compilation failed.

Here are the relevant directives and includes I'm using:

> #r "Microsoft.ServiceBus"
> #r "Microsoft.WindowsAzure.Storage"
> #r "System.Runtime.Serialization"

> using Microsoft.ServiceBus;
> using Microsoft.ServiceBus.Messaging;
> using Microsoft.WindowsAzure.Storage;
> using Microsoft.WindowsAzure.Storage.Blob;
> using System;
> using System.IO;
> using System.Runtime.Serialization;
> using System.Threading.Tasks;

**Comment by rabrahamOpti** [comment]
In the text editor in the dashboard, I'm getting an error highlighted:

![uploadfromfileerror](https://user-images.githubusercontent.com/28309959/39927458-45c2366e-5500-11e8-9498-60fa0fbd8f58.png)

I added this line to verify the assembly version:
> log.Info($"{typeof(CloudBlockBlob).Assembly.GetName()}");

and saw this:

> Microsoft.WindowsAzure.Storage, Version=7.2.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

Again, the "mode" argument shouldn't be required by ClloudBlockBlob in version 7.2.1.0, so I don't understand why I'm getting these errors.

**Comment by rabrahamOpti** [comment]
Here's what happens when I add the FileMode argument back in:

> Invocation ID: fba0958f-b65c-4b48-9fae-d95240b15e2e
> Exception while executing function: Functions.inputPdfSanitizer
> Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.inputPdfSanitizer ---> System.AggregateException : One or more errors occurred. ---> Method not found: 'Void Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.UploadFromFile(System.String, System.IO.FileMode, Microsoft.WindowsAzure.Storage.AccessCondition, Microsoft.WindowsAzure.Storage.Blob.BlobRequestOptions, Microsoft.WindowsAzure.Storage.OperationContext)'.

**Comment by rabrahamOpti** [comment]
I just realized that I have a custom library that I've uploaded to the site's bin folder, and am referencing via an #r directive, and that library may be referencing an older version of Microsoft.WindowsAzure.Storage. I'm verifying this now.

**Comment by rabrahamOpti** [comment]
My custom library did have a reference to `Microsoft.WindowsAzure.Storage version 4.3.0.0`. I removed it and re-uploaded it, although I'm having trouble getting the function to compile for some inscrutable reason, so I can't test to see if this resolves the issue.

That said, I'm still at a loss over why I wasn't able to use either version of the function signature. If the function was using version 4.3.0.0 of the dll, then my original call should have worked. If it was using 7.2.1.0, then my subsequent call (sans the FileMode argument)should have worked.

**Comment by fabiocav** [comment]
Closing this as a stale issue. This problem was addressed in the 2.0 release.
