### ISSUE TITLE
[Question] How to configure the language extensions?

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-host#2835]
I create a Hello World host to understand this repo. 

I create a .Net Core console app and write a code which is identical with Scripts.Host Program.cs. Also, I install Microsoft.Azure.WebJobs.Script (v2.0.0-beta2-11737), Microsoft.Azure.Functions.JavaWorker (v1.1.0-beta2-10028), Microsoft.Azure.Functions.NodeJSWorker(v1.0.0-beta1-10031) then  set environment variables. Then I create a simple node.js Queue trigger functions. And specify the path of the app. 

However, it emit error. The root cause is, they said `Could not found part of the path ...` they require workers directory in here. 

```
C:\Users\MYUSERNAME\.nuget\packages\microsoft.azure.webjobs.script\2.0.0-beta2-11737\lib\netstandard2.0
````

I needed to copy the `workers` directory  from here manually.

```
C:\Users\MYUSERNAME\.nuget\packages\microsoft.azure.functions.nodejsworker\1.0.0-beta1-10031\contentFiles\any\any\workers
```

Maybe I might missing configuration of the workers directory for the language extension. However, I don't know where can I configure that. 

Could you explain where to configure it?

**Comment by pragnagopa** [comment]
You can set environment variable key: "workers:node:path" value: "{YourWorkersDirectory}\node\dist\src\nodejsWorker.js"

**Comment by TsuyoshiUshio** [comment]
Thank you, @pragnagopa !

**Comment by pragnagopa** [comment]
There is an update in the config. You new to set environment variable key: "languageWorkers:node:workerDirectory" value: "{YourWorkersDirectory}"
