### ISSUE TITLE
Exception on GRPC write stream is swallowed

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#2840]
Here, we subscribe to write messages
https://github.com/Azure/azure-functions-host/blob/3f54f80a447e9330cb11b6a4ff203bcfdd6ba0ab/src/WebJobs.Script/Rpc/FunctionRpcService.cs#L49-L55

However, if an exception is thrown within the `.Subscribe( () => ... )` code path, that [error is not caught](https://stackoverflow.com/questions/9240239/why-is-the-catch-block-not-hit-in-the-following-rx-code).

I think the proper fix also involves addressing this TODO, as actually calling WorkerErrorEvent with "null" fails.
https://github.com/Azure/azure-functions-host/blob/3f54f80a447e9330cb11b6a4ff203bcfdd6ba0ab/src/WebJobs.Script/Rpc/FunctionRpcService.cs#L66-L67

**Comment by mhoeger** [comment]
@pragnagopa - moving this issue from https://github.com/Azure/azure-functions-nodejs-worker/issues/51 after debugging a bit. I think this may be addressed with the stream support or other changes you're working on?

**Comment by pragnagopa** [comment]
Fixed as part https://github.com/Azure/azure-functions-host/issues/2963
