### ISSUE TITLE
[Question] Receive multiple/batch messages for Storage Queue Trigger?

### ISSUE THREAD

**Issue by gorillapower** [Azure/azure-functions-host#2841]
I have not been able to find a similar question posted in this repo, if otherwise please redirect if possible :)

Is it possible to receive multiple/batch messages for a storage queue trigger? We currently have a single process that gets 32 queue messages using the Storage Queue APIs.  

Would it be possible and or useful to be able to have something like a **message count per trigger** setting, allowing for an array of queue messages to be processed by a function?

**Comment by mathewc** [comment]
Not possible currently. Tracked by issue https://github.com/Azure/azure-webjobs-sdk/issues/625
