### ISSUE TITLE
Errors after first post to Event Grid

### ISSUE THREAD

**Issue by stevenlivz** [Azure/azure-functions-host#2842]
This issue happens on my local runtime as well as any test functions I create so it's not specific to a function ... i can create one and make it available if needed but it is easy to test on the local runtime where i am doing my dev work.

#### Investigative information

Please provide the following:

- Timestamp: Sat, 12 May 2018 22:53:23 GMT
- Function App version (1.0 or 2.0-beta): 2.0-beta
- Function App name: local functions runtime as well any test functions i create

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create an Event Grid Topic
2. In an Azure Function, using http client to post to its endpoint.
3. Run (2) more than once.

#### Expected behavior

Each event is added to the event grid.

#### Actual behavior

The first event is published. Subsequent events (until a function restart) return the following error:

```
{StatusCode: 400, ReasonPhrase: 'The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. . Report 'cdd5c15c-d96d-49f1-a787-2bb9bc1e9484:5/12/2018 10:53:23 PM (UTC)' to our forums for assistance or raise a support ticket.', Version: 1.1, Content: System.Net.Http.NoWriteNoSeekStreamContent, Headers:
{
  Server: Microsoft-HTTPAPI/2.0
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  x-ms-request-id: cdd5c15c-d96d-49f1-a787-2bb9bc1e9484
  Date: Sat, 12 May 2018 22:53:23 GMT
  Content-Length: 771
  Content-Type: application/json; charset=utf-8
}}
```

#### Known workarounds

Best practice in Azure Functions says use a static HttpClient instance.

The Dispose() method can be called on this before creating a new HttpClient() and making the call each time. This "fixes" the problem ... but obviously causes other issues at scale with a new instance every time.

My suspicion if the stream buffer needs reset but not sure how to accomplish that.

**Comment by stevenlivz** [comment]
Thanks Paul. That makes sense but is it not best practice in Azure functions not to reuse the http client ... Set it as a static? 

https://github.com/Azure/azure-functions-host/issues/1806

May of course make it an http client error, prob not grid.

**Comment by paulbatum** [comment]
Yes to be clear we absolutely recommend you reuse client library instances within functions to improve performance. So you're doing the right thing. My point was more that once you reproduce it outside of functions, we know that the bug should be tracked elsewhere (and I can close this issue).

**Comment by stevenlivz** [comment]
Ah yes Paul. Makes sense. Should I repost this somewhere else. If you can give me a pointer i will do that. thanks.

**Comment by sowsan** [comment]
@stevenlivz  I tried to reproduce the issue  in .net core console app but it was not and i was able to successfully push the messages to eventgrid. Can you check this code below and see any changes needed to reproduce the issue ?

`public static HttpClient client = new HttpClient();

      static void Main(string[] args)
        {
            try
            {
                string serviceURL = "<eventgrid-topic-url>";

                client.DefaultRequestHeaders.Add("aeg-sas-key", "<key>");

                var orderData = new
                {
                    name = "testdata"
                };

                for(int i=0; i<10; i++)
                {
                    EventGridEvent orderEvent = new EventGridEvent()
                    {
                        Id = System.Guid.NewGuid().ToString(),
                        EventType = "orderRecieved",
                        Subject = $"mydocs/",
                        EventTime = System.DateTime.UtcNow,
                        Data = orderData
                    };

                    List<EventGridEvent> events = new List<EventGridEvent>();

                    events.Add(orderEvent);

                    var eventGridEvents = JsonConvert.SerializeObject(events);

                    var response = client.PostAsync(new Uri(serviceURL), new StringContent(eventGridEvents, Encoding.UTF8, "application/json"));
                    
                }

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            finally
            {
                Console.WriteLine("Done");
                Console.ReadLine();
            }
        }`

**Comment by dachou** [comment]
Also, have you tried the EventGridClient API? I tried it in an HTTP trigger Function and saved the instance in a variable to reuse across invocations, and have not seen this issue.
https://docs.microsoft.com/en-us/dotnet/api/overview/azure/eventgrid?view=azure-dotnet
