### ISSUE TITLE
Error creating a local Functions project

### ISSUE THREAD

**Issue by nahue97** [Azure/azure-functions-host#2843]
When I execute this command: "func init MyFunctionProj" I should get an output like this:
Writing .gitignore
Writing host.json
Writing local.settings.json
Created launch.json
Initialized empty Git repository in D:/Code/Playground/MyFunctionProj/.git/

But I get this output:
Writing .gitignore
Writing host.json
Writing local.settings.json
Writing C:\Users\nahue\dev\MyFunctionProj\.vscode\extensions.json
El sistema no puede encontrar el archivo especificado

Note: My Windows is in Spanish. That message means "File not found" or "The System couldn't find the specified file".
What should I do now? I've already followed the instructions and I cannot continue...

**Comment by nahue97** [comment]
Update: I followed the instructions in my brother's computer and it worked. Could it be related to an installation of Visual Studio 2015 I made months ago? I still cannot make it work in my computer.

**Comment by paulbatum** [comment]
This issue was moved to Azure/Azure-Functions#804

**Comment by paulbatum** [comment]
This issue was moved to Azure/azure-functions-core-tools#478
