### ISSUE TITLE
Bump dependencies to latest

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#2848]
In preparation for cutting 2.x we want to get our dependencies up to date. Couple of examples:

- Json.NET 10.x -> 11.x
- Storage 8.x -> 9.x

See also this tracking item for the equivalent on the webjobs side:
https://github.com/Azure/azure-webjobs-sdk/issues/1699

**Comment by fabiocav** [comment]
Most of the dependencies have been updated with the move to .NET Core 2.1 (including Json.NET). Storage is still pending as we need to finish the DI work and bring the isolated extensions. This will bleed into the next sprint.

**Comment by fabiocav** [comment]
Moving due to the same reason described above.

**Comment by fabiocav** [comment]
Done as part of the latest release.
