### ISSUE TITLE
Default to using azure storage for storing functions keys

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#2849]
Right now functions supports storing keys either using the app service file system or azure storage. Today the default is files, and the user ops into storage by setting `AzureWebJobsSecretStorageType` to `blob`. The problem is that files based storage does not work well at all with slots. Since a bunch of scenarios require a storage account anyway, making storage the default makes more sense.

Need to check: does kudu support this yet? See:
https://github.com/Azure/azure-functions-host/issues/1752
https://github.com/projectkudu/kudu/issues/2515

**Comment by fabiocav** [comment]
This will be pushed to the next milestone as we're introducing a migration feature first.

**Comment by paulbatum** [comment]
waiting for logic apps update to support keys

**Comment by fabiocav** [comment]
This was done in https://github.com/Azure/azure-functions-host/pull/3325
