### ISSUE TITLE
Can't get any functions to run in v2 runtime in Azure -- work fine locally

### ISSUE THREAD

**Issue by rogersmj** [Azure/azure-functions-host#2855]
I have a set of functions I can run successfully in a local environment (using 2.x runtime on a Mac), but absolutely refuse to run once published to Azure. Even a fresh, "virgin" HTTP trigger function template will not run. They all produce 500s with unhelpful messages like:

```
2018-05-16T14:59:54.872 [Information] Executing 'Functions.HttpTriggerJS1' (Reason='This function was programmatically called via the host APIs.', Id=d819275e-00bf-40cd-9147-25b0f0554307)
2018-05-16T14:59:55.034 [Error] System.Private.CoreLib: Exception while executing function: Functions.HttpTriggerJS1. System.Private.CoreLib: One or more errors occurred. (Worker process with pid 5056 exited with code 1) (Worker process with pid 2204 exited with code 1) (Worker process with pid 8056 exited with code 1). Worker process with pid 5056 exited with code 1.
2018-05-16T14:59:55.424 [Error] Executed 'Functions.HttpTriggerJS1' (Failed, Id=d819275e-00bf-40cd-9147-25b0f0554307)
```

Most of these functions run just fine in the 1.x environment as well, but recently I am leveraging functionality that requires me to use a Node version newer than 8.x, thus now I must switch to 2.x.

#### Investigative information

Please provide the following:

- Timestamp: 2018-05-16T14:59:54.872 (most recent...I've been working on this for a couple days now)
- Function App version (1.0 or 2.0-beta): 2.0-beta
- Function App name: analyticli-dev-pbimanager2
- Function name(s) (as appropriate): HttpTriggerJS1
- Invocation ID:
- Region: East US

#### Repro steps

1. Spin up new Function app
2. Set to beta runtime
3. Create new HTTP trigger function from template
4. Click "run"

#### Expected behavior

Provide a description of the expected behavior.

The function runs successfully.

#### Actual behavior

Provide a description of the actual behavior observed.

500 error with above non-specific error messages.

#### Related information 

Using Node (8.11.1).

Example code that produces this error:

```
module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');

    if (req.query.name || (req.body && req.body.name)) {
        context.res = {
            // status: 200, /* Defaults to 200 */
            body: "Hello " + (req.query.name || req.body.name)
        };
    }
    else {
        context.res = {
            status: 400,
            body: "Please pass a name on the query string or in the request body"
        };
    }
    context.done();
};
```

**Comment by mhoeger** [comment]
@rogersmj are you using any npm packages by chance?
