### ISSUE TITLE
Cannot see function key in the portal during cold start

### ISSUE THREAD

**Issue by watashiSHUN** [Azure/azure-functions-host#2861]
before we finish indexing all methods, portal will display 404 when trying to retrieve function keys. Reproducible with cold starts (ie, after fresh deployment)
#### Repro steps
1. To mimic cold start, first, break the host by providing a malformed `host.json`
![image](https://user-images.githubusercontent.com/6531400/40150987-f22bc142-5931-11e8-814d-cf529fb62040.png)
2. Go to portal, function key is missing
![image](https://user-images.githubusercontent.com/6531400/40151097-c148cccc-5932-11e8-8ad1-d2b0452b0fb0.png)
![image](https://user-images.githubusercontent.com/6531400/40151146-1606e492-5933-11e8-945a-b4ba26527eea.png)

in order to retrieve function key, we don't need to wait for indexing, instead we can do everything at file system level:
https://github.com/Azure/azure-functions-host/blob/13769982b62bc7c3865fcd3d9b5a699e009454cd/src/WebJobs.Script.WebHost/Controllers/KeysController.cs#L91-L99

**Comment by mathewc** [comment]
Likely related to the work we did for https://github.com/Azure/azure-functions-host/issues/2114. Though that was done long ago.
