### ISSUE TITLE
Add OpenAPI support to Functions 2.x runtime

### ISSUE THREAD

**Issue by alexkarcher-msft** [Azure/azure-functions-host#2874]
I'd like the OpenAPI definition feature set moved along to the 2.x runtime. This includes the ability to host an OpenAPI definition, the API definition generator, and all of the portal UI. 

This is a well requested preview feature will give the 2.x runtime more complete feature parity with the 1.x runtime.

**Comment by mithunshanbhag** [comment]
Without the OpenAPI definitions, we currently cannot import the serverless APIs (HTTP-triggered azure functions) on 2.x runtime into Azure API Management (API gateway). 

![image](https://user-images.githubusercontent.com/2327905/43953914-36d4f600-9cb8-11e8-9e97-174cda04313f.png)

twitter thread: https://twitter.com/MithunShanbhag/status/1025052593221820417

**Comment by alexkarcher-msft** [comment]
You can continue to import APIs into Azure APIM using the custom API option in API Management. You will need to hand transcribe your API surface over, but that scenario is still possible.

The same is true of importing a Functions API into PowerApps and Flow. You no longer get a fast import via OpenAPI, but you can still manually define the API on the PA and Flow side.

We're taking all these integrations into consideration and have this work prioritized to begin shortly after GA.

**Comment by rikvandenberg** [comment]
@alexkarcher-msft Do you have any update on this?

We have several planned upgrades for our current Azure Functions which are all still running V1. Through the openAPI endpoint we have a powershell script to automatically import the open API specification into an APIM instance using the Azure APIM REST API.

This is blocking our upgrade path for several azure functions as we now have to create an "utility" Azure Function that uses [Swashbuckle.AspNetCore.AzureFunctions](https://github.com/bherila/Swashbuckle.AspNetCore.AzureFunctions)

Here is what our scenario/script does
1. Find Function App based on name.
2. Get Function App Deployment credentials
3. Get master key from Function App
4. Request /admin/host/swagger/default/ with master key
5. [Import into APIM use REST](https://docs.microsoft.com/en-us/rest/api/apimanagement/api/createorupdate)

And we have APIM instances for test/acceptance/production where we run these scripts to automate our deployment of our new API's. It is unfortunate that this postponed for after the GA 😞

**Comment by rogersmj** [comment]
This is blocking quite a lot of our integration efforts and making the management of our Functions-based services needlessly burdensome. I thought the v2 runtime was out of beta now? When will OpenAPI be supported?

**Comment by Runamok81** [comment]
Okay, we still don't have this?  What can we do to help?

**Comment by shelbaz** [comment]
1 year later any updates?....

**Comment by alexkarcher-msft** [comment]
Adding @eamonoreilly who is the new owner of this feature. 

At this time all new OpenAPI work is being targeted at APIM and will be leveraged through integration with Functions. See this uservoice item for more detail: https://feedback.azure.com/forums/355860-azure-functions/suggestions/35737768-openapi-from-function-app-v2

And this document: https://docs.microsoft.com/en-us/azure/azure-functions/functions-openapi-definition#generate-the-openapi-definition
