### ISSUE TITLE
Beta Runtime's Request Body is a Buffer instead of Object

### ISSUE THREAD

**Issue by danfsd** [Azure/azure-functions-host#2875]
Request's body is a `<Buffer>` instead of object in **Azure Function's Runtime Beta**. This works fine in the Cloud (which I suppose is running **Runtime 1.x**

#### Repro steps

Try to run the boilerplate Javascript code in the **Runtime beta**:

```
module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');
    context.log(context.req.body.name);
    if (req.query.name || (req.body && req.body.name)) {
        context.res = {
            // status: 200, /* Defaults to 200 */
            body: "Hello " + (req.query.name || req.body.name)
        };
    }
    else {
        context.res = {
            status: 400,
            body: "Please pass a name on the query string or in the request body"
        };
    }
    context.done();
};
```

#### Expected behavior

The `context.log(context.req.body.name)` should log:
```
2018-05-21T17:41:12.509 [Info] daniel
```

#### Actual behavior

Instead, it's logging:
```
<Buffer 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 33 30 38 32 35 30 31 33 36 35 39 30 36 31 38 38 37 30 38 32 36 32 ... >
```

#### Known workarounds

This scenario works just fine under the **Runtime 1.x** running on Azure Functions.

**Comment by pragnagopa** [comment]
This issue was moved to Azure/azure-functions-nodejs-worker#76

**Comment by mhoeger** [comment]
I'm not able to repro this..! On a V2 function app, I am observing the correct behavior.
![image](https://user-images.githubusercontent.com/8888531/40387151-b4c17e76-5dc0-11e8-8d98-f10b4c3a1814.png)

Could you tell me which runtime version you are using (see below)? Could you also make sure that your WEBSITE_NODE_DEFAULT_VERSION under application settings is set to an 8.x version (such as 8.4.0)?
![image](https://user-images.githubusercontent.com/8888531/40386834-af4af4fa-5dbf-11e8-8b36-4d59eec0894a.png)
