### ISSUE TITLE
Node debug port can't attach to process

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#2878]
When using the CLI (version 2.0.1-beta.26), setting "port" within a configuration in launch.json no longer works to attach a debugger. Example of launch.json that no longer works:
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Attach to JavaScript Functions",
			"type": "node",
			"request": "attach",
			"port": 5858,
			"protocol": "inspector",
			"preLaunchTask": "runFunctionsHost"
		}
	]
}
```

It looks like this PR introduced a change in the way we check for debug port: https://github.com/Azure/azure-functions-host/commit/980107fb13e18f75be545948ede20933ea93a590. 

Reported here: https://github.com/Microsoft/vscode-azurefunctions/issues/387

**Comment by mhoeger** [comment]
As a workaround, you can add this snippet to your tasks.json: `"options": { "env": { "workers:node:debug": "5858" } }`

_For example:_
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "runFunctionsHost",
            "type": "shell",
            "command": "func host start",
            "options": {
                "env": {
                    "workers:node:debug": "5858"
                }
            }
        }
    ]
}
```

**Comment by mhoeger** [comment]
@ahmelsayed - the runtime made a change so that it now doesn't "int.TryParse" on the debug port anymore (https://github.com/Azure/azure-functions-host/commit/980107fb13e18f75be545948ede20933ea93a590). Users have reported the VS Code debugger not attaching correctly anymore when the port is defined in launch.json. 

It looks like something changed in the runtime that makes it incompatible with the CLI's [DebuggerHelper](https://github.com/Azure/azure-functions-core-tools/blob/7b80b08cbd6432a14c4f98c156824b6df04da9c2/src/Azure.Functions.Cli/Helpers/DebuggerHelper.cs). Does this theory make sense? Do you have any insights on what assumptions might have been broken with the latest runtime?

**Comment by pragnagopa** [comment]
This was a regression introduced on how runtime load configsettings. Issue was addressed in CLI: https://github.com/Azure/azure-functions-core-tools/commit/b8ba594734c65f12e082d93c0a8553fea484808f
