### ISSUE TITLE
Javascript promise doesn't work since last Sunday(May.20th) from azure function app runtime 2.0

### ISSUE THREAD

**Issue by huangyingting** [Azure/azure-functions-host#2880]
Javascript promise doesn't work since last Sunday(May.20th) from azure function app runtime 2.0.
Sample code is below
1. Create an empty azure function
2. Paste below code
module.exports = function (context, req) {
return Promise.resolve({
res: {
status: 200,
body: [{ a: 1 }, { b: 2 }]
}
});
};
3. Run it, it returns System.Collections.Generic.List`1[System.Object] instead of json result.
4. The issue starts happening from last Sunday(May.20th), before that, everything is good.

Need to know if anything changed from backend which breaks the code and how to fix this problem.

**Comment by FinVamp1** [comment]
This issue can be resolved for now by setting FUNCTIONS_EXTENSION_VERSION to 2.0.11651-alpha 
This is as discussed at https://github.com/Azure/app-service-announcements/issues/106 @mhoeger can investigate further.

**Comment by mhoeger** [comment]
@huangyingting - Promises still work, but we did make a change to stop supporting some of the black-box magic and limited assumption making that was happening with content negotiation when you say that you want an http response. (see this PR: https://github.com/Azure/azure-functions-host/pull/2696)

You can also restore your previous behavior by adding the flag `enableContentNegotiation`:
```
res: {
status: 200,
body: [{ a: 1 }, { b: 2 }],
enableContentNegotiation: true
}
```

You could also try something like this, where you're explicitly setting the response based off of the resolved promise (note that it's still a promise being returned):
```
module.exports = function (context, req) {
    var promise1 = Promise.resolve({status: 200, body: [{ a: 2 }, { b: 2 }]});

    return promise1.then(function(value) {
    context.log(value);
    context.res = value;
    });
}
```

**Comment by mhoeger** [comment]
@huangyingting - closing this issue as I believe it is resolved. Please feel free to re-open and @ tag me if there's more we can do!
