### ISSUE TITLE
Java language worker doesn't seem to be loading in latest release

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-host#2886]
Been working on a Java project tonight using the latest Java plugin published today.  That appears to be working great - the problem is when I run the app the triggers fire but the code never runs.  I think it's something with the language worker getting mixed up. During `func start` I see this message:

[5/23/18 6:05:31 AM] Will load worker provider for language: python

and nothing about Java anywhere to be seen.  It results in a bunch of these:

5/23/18 6:05:40 AM] Executing 'Functions.kafkaFunction' (Reason='', Id=dd63028d-dbc0-46b5-bddb-18755cc224ca)
[5/23/18 6:05:40 AM] Executing 'Functions.kafkaFunction' (Reason='', Id=55c976a6-f6f0-480d-98fc-48ec65f9ab93)
[5/23/18 6:05:40 AM] Executing 'Functions.kafkaFunction' (Reason='', Id=dfd8d3ec-339e-43d3-adf6-be3008d2b0a0)

without any "succeeded" or "failed" or logs or anything

**Comment by pragnagopa** [comment]
This is a known issue with the maven plugin version <=0.2.1. Workaround is to delete
this file: "JavaFunctionFolder\target\azure-functions\JavaFunctionFolder\lib\azure-functions-java-core-1.0.0-beta-2.jar" which has the old annotations and is incompatible with the current release Functions 2.0.11776-alpha
