### ISSUE TITLE
2.0.1-beta.26 - Error reading Darwin Kernel Version

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#2899]
_From @trydis on May 22, 2018 9:14_

Getting this on MacOS after upgrading to 2.0.1-beta.26:

[22.05.2018 08:03:59] System.Private.CoreLib: Exception while executing function: SendActivity. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'client'. Microsoft.Azure.DocumentDB.Core: The type initializer for 'Microsoft.Azure.Documents.UserAgentContainer' threw an exception. Microsoft.Azure.DocumentDB.Core: Error reading Darwin Kernel Version. Microsoft.Azure.WebJobs.Script: Object reference not set to an instance of an object.

Downgrading from 2.0.1-beta.26 to 2.0.1-beta.25 fixes it.

_Copied from original issue: Azure/azure-functions-core-tools#485_

**Comment by fabiocav** [comment]
@ealsur moved this here for further investigation in the runtime, but this is happening in the utility class in the Comos DB code where it attempts to read the kernel version on macOS. Internally, this just uses the `RuntimeInformation` methods.

Will spend a bit of time to identify the root cause and ensure this is not something related to the runtime, but I wanted to make you aware.

**Comment by ealsur** [comment]
@kirankk I'm not familiar with that Kernel detection mechanism, looks like it's part of the Core SDK.

**Comment by fabiocav** [comment]
Are you referring to the DocumentDB Core SDK? If so that’s the where the call originated from, but ultimately, this is a .NET Core API method that is failing.

**Comment by mikhailshilkov** [comment]
I get the same on Windows with Core Tools (2.0.1-beta.28)

**Comment by fabiocav** [comment]
@mikhailshilkov puzzling. Based on what I'm looking at, that code path should never be hit if the platform is Windows, and if it did, it would indeed be hopeless.

**Comment by fabiocav** [comment]
Do you have a repro you'd be able to share?

**Comment by mikhailshilkov** [comment]
@fabiocav I deleted my comment because I managed to get rid of it somehow, and I think the error was slightly different. There was definitely `Microsoft.Azure.DocumentDB.Core: The type initializer for 'Microsoft.Azure.Documents.UserAgentContainer' threw an exception. ` and `Object reference not set to an instance of an object.` but maybe not the Kernel part. I'll try to repro it again tomorrow.

**Comment by ChristianWeyer** [comment]
Do you still have this issue @mikhailshilkov ? I am also running into it .

**Comment by mikhailshilkov** [comment]
@ChristianWeyer Just checked and yes, still getting it on `CosmosDBTrigger`:

`Microsoft.Azure.WebJobs.Host: Error indexing method 'Bla.Run'. Microsoft.Azure.WebJobs.Extensions.CosmosDB: Can not create Collection Information for Items in database ToDoList with lease leases in database ToDoList : The type initializer for Microsoft.Azure.Documents.UserAgentContainer' threw an exception. Microsoft.Azure.DocumentDB.Core: The type initializer for Microsoft.Azure.Documents.UserAgentContainer' threw an exception. Object reference not set to an instance of an object.`

**Comment by fabiocav** [comment]
@mikhailshilkov to confirm, that's on Windows, right? Would it be possible to package up the root of the function app and share that? I'd like to look at the artifacts.

**Comment by fabiocav** [comment]
@ChristianWeyer are you seeing this on Windows as well?

**Comment by fabiocav** [comment]
Thank you @JohnReeson . Very helpful. I’ll be blocking some time to look at this issue this week. @mikhailshilkov was scenario in VS or an NPM installed CLI?

**Comment by mikhailshilkov** [comment]
@fabiocav Windows, CLI. VS works like charm.

**Comment by ChristianWeyer** [comment]
This is on Windows, yes @fabiocav

**Comment by fabiocav** [comment]
Found the problem. This is related to the native assets resolution changes in the latest release. I'm working on a fix and hope to catch the current release train.

**Comment by maciejgos** [comment]
Same issue here. Using CLI 2.0.1-beta.28
`System.Private.CoreLib: Exception while executing function: CreateTask. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'document'. Microsoft.Azure.DocumentDB.Core: The type initializer for 'Microsoft.Azure.Documents.UserAgentContainer' threw an exception. Microsoft.Azure.DocumentDB.Core: Error reading Darwin Kernel Version. Microsoft.Azure.WebJobs.Script: Object reference not set to an instance of an object.`

**Comment by fabiocav** [comment]
Resolved by: https://github.com/Azure/azure-functions-host/pull/2958/files

Release in progress: https://github.com/Azure/app-service-announcements/issues/112

**Comment by divgo** [comment]
Similar issue here:
System.Private.CoreLib: Exception while executing function: Functions.AddQuestion. Microsoft.Azure.DocumentDB.Core: The type initializer for 'Microsoft.Azure.Documents.UserAgentContainer' threw an exception. Microsoft.Azure.DocumentDB.Core: Error reading Darwin Kernel Version. System.Private.CoreLib: The given key 'osx.10.14-x64' was not present in the dictionary.
