### ISSUE TITLE
Python - support requirements.txt

### ISSUE THREAD

**Issue by edevil** [Azure/azure-functions-host#290]
Currently in order to use Python modules one must hack the sys.path variable in order to point it to a certain directory and compile them in a specific environment (windows 32bits).

It would be great if we could simply include a requirements.txt file in the project or, at least, be able to to a "pip install -r requirements.txt" in the functions console and it would fetch and compile the modules locally, and make them available to the Python runtime.

**Comment by edevil** [comment]
Ticket #335 may be a better place to track this.

**Comment by asavaritayal** [comment]
We will no longer be adding new features to Functions 1.0. 

Python support has been reintroduced on Functions 2.0 and `requirements.txt` is supported. You can follow the discussion here - https://aka.ms/functions-python-preview
