### ISSUE TITLE
Can not use VSTS client libs with latest version of the functions

### ISSUE THREAD

**Issue by vsadams** [Azure/azure-functions-host#2900]
I am trying to update to the latest version of the function runtime (2.0.11776-alpha) but I am running into a blocker.

It looks to be another assembly loading error. I have encountered this before in other upgrades and was able to get around it by downgrading my dependencies.  This time, that does not seem to fix it. I have tried a few other things, and am now out of ideas.

I have some example code below.  It is working in the 2.0.11651-alpha version of the runtime. I am currently using the FUNCTIONS_EXTENSION_VERSION config in my production instance so that my functions can still run.

```
using Microsoft.Azure.WebJobs;
using Microsoft.VisualStudio.Services.Common;
using Microsoft.VisualStudio.Services.WebApi;
using System;

namespace XXX.Services.Functions
{
	public static class Test
	{
		[FunctionName("Test")]
		public static void Test([TimerTrigger("0/1 * * * * *")]TimerInfo timer)
		{
			try
			{

				var creds = new VssBasicCredential(string.Empty, "XXX");

				var vssConnection = new VssConnection(new Uri("https://xxx.com"), creds);

			}
			catch
			{
				throw;
			}

		}
	}


}
```

Here is the error that I am getting when invoking the VssConnection constructor...
Microsoft.Azure.WebJobs.Host.FunctionInvocationException
  HResult=0x80131500
  Message=Exception while executing function: Test
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__15.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 275

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

Inner Exception 2:
FileNotFoundException: Could not load the specified file.

Any help would be greatly appreciated!

**Comment by vsadams** [comment]
I might have gotten around this issue by doing something like the following. I am going to push to azure and run some tests

```
public class StartupConfigProvider : IExtensionConfigProvider
	{
		/// <summary>
		/// This is invoked by the function framework at startup
		/// </summary>
		/// <param name="context"></param>
		public void Initialize(ExtensionConfigContext context)
		{
			//other initialize code...

			AssemblyLoadContext.Default.Resolving += SystemNetHttpPrimitivesHandler;

		}


		private static Assembly SystemNetHttpPrimitivesHandler(AssemblyLoadContext context, AssemblyName assemblyName)
		{
			const string system_net_http_primitives = "System.Net.Http.Primitives";
			if (assemblyName.Name == system_net_http_primitives)
			{
				var codeBase = Assembly.GetExecutingAssembly().CodeBase;
				var uri = new UriBuilder(codeBase);
				var path = Uri.UnescapeDataString(uri.Path);
				var directory = Path.GetDirectoryName(path);

				var assembly = Assembly.LoadFile($"{directory}/{system_net_http_primitives}.dll");
				return assembly;
			}

			return null;
		}
...
}
```

**Comment by mathieumack** [comment]
Hello,
I've the same issue, I've tried many fixes.
@vsadams could you share a sample solution that fix the issue ?
Thanks

**Comment by vsadams** [comment]
I stripped out all the extra stuff in my project and posted an [Example](https://github.com/vsadams/AzureFunctionV2DI) on how to get the assembly loading working.  You have to have a custom binding so that you can trigger the invocation of an implementation of IExtensionConfigProvider on startup.  At least, thats the only way I know how to get a handle into the startup code of the runtime. If there is another way then you could strip out a lot of the example project.

My custom binding is how I do DI with the functions.  If you dont need that then you could strip out most of the logic in it and just register a simple binding.

**Comment by mathieumack** [comment]
It works !! You saved my week ! Thank you.

**Comment by fabiocav** [comment]
Warning: This approach will likely cause issues moving forward. Just subscribing to the default domain resolve event and loading assemblies into _no context_ may have undesirable results (e.g. type mismatches, etc.)

A lot of work is going into 2.0 to mitigate those types of problems and while 2.0.11776 introduced the foundation for that functionality, it did have some limitations and restrictions that caused the issue you were seeing here (particularly, binding/unifying System assemblies). This has been addressed in 2.0.11857, which is the version that is currently rolling out, so you shouldn't need this workaround with that.

**Comment by vsadams** [comment]
@fabiocav  Thats awesome news. I figured this would be fixed in the future. Ill remove my hack and test it out on the latest version!.

**Comment by vsadams** [comment]
It looks like the latest version works. Closing issue. Thanks function team!
