### ISSUE TITLE
Application Insights is not showing execution

### ISSUE THREAD

**Issue by robinhalabicki** [Azure/azure-functions-host#2903]
I have a Logic App : ExtractCredentialStatementsZip
It extracts an incoming zip file to blob storage and inserts a message into a queue "fetch-credential-household-id" in the same blob storage account the file was extracted to.

The function after completion writes another queue message to trigger another function (in same app) that IS logged to insights.

the logic app has a correlation id :08586740791669776628589400877

It triggered at: Monday, May 28, 2018, 1:22:33 PM EDT

Queue Input from Logic App:
{
    "host": {
        "connection": {
            "name": "/subscriptions/99015b92-aab4-40ff-8b8c-f8c8e5b1ebf1/resourceGroups/VPI-RG-CanCen/providers/Microsoft.Web/connections/azurequeues-1"
        }
    },
    "method": "post",
    "path": "/fetch-credential-household-id/messages",
    "body": "{\"OriginalFolder\":\"5413_201804_CLIENT_STATEMENTS\",\"Type\":\"Statement\"}"
}

#### Investigative information

Please provide the following:

- Timestamp:  Monday, May 28, 2018, 1:22:33 PM EDT
- Function App version 1.0 or 2.0-beta): 1
- Function App name: vpiProdETL
- Function name(s) (as appropriate): FetchCredentialHouseholdID
- Invocation ID:
- Region: Canada Central

#### Expected behavior

Provide a description of the expected behavior.

The function should trigger a run in monitoring

#### Actual behavior

we see no logging in application insights

**Comment by brettsam** [comment]
Do you have sampling enabled? That could cause function invocations to not appear in App Insights: https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#configure-sampling

**Comment by robinhalabicki** [comment]
Yes, sampling in Application Insights was set to 50%.  However, other functions in the same App show results in monitor, and in App Insights .   This one particular function ran 152 times on that day and there is nothing in monitor, like 0 runs (0/152).   I have reset the sample to 100.

**Comment by brettsam** [comment]
How are you setting it to 50% -- is that server-side sampling? 
Try updating your host.json (see link above) to turn off client-side sampling completely and give it another try.

**Comment by robinhalabicki** [comment]
I have no host.json on any of my functions (those logging or not).  The data sampling is set in the insights blade -> Data Usage -> Data Sampling button.

**Comment by brettsam** [comment]
A [host.json file](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json) is for the entire application -- it's not per-function. By default you will have client-side sampling enabled. So try disabling all server-side sampling, and then add this to your host.json to disable client-side sampling. That should allow all telemetry to flow.

```
{
  "applicationInsights": {
    "sampling": {
      "isEnabled": false
    }
  }
}
```

**Comment by robinhalabicki** [comment]
Changing the app insights sampling in the insights blade -> Data Usage -> Data Sampling button resolved
