### ISSUE TITLE
Managed Memory Leaks

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#2907]
Looks like we've regressed again. Similar to previous issue https://github.com/Azure/azure-functions-host/issues/2059.

To repro, put the host into a tight restart or error loop and monitor memory. E.g. in my recent test, where the host was restarting every few seconds or so, after 3 minutes the ScriptHost instance count went from 1 to 43. During that time, memory went from 12MB to 110MB. After waiting for 2 minutes these objects still were not collected and memory was not reclaimed. Looks like we're leaking a ScriptHost on every restart.

Granted the tight restart loop is an extreme case. In the wild, the memory leak would be much slower since restarts happen less often. But we should fix this. I tested this in v1 - likely have the same issues in v2 (need to verify).

**Comment by brettsam** [comment]
Going to leave this open as I need to investigate for v2.

**Comment by brettsam** [comment]
I did some manual investigation here in a v2 csx project and opened a separate issue to track what I found: #3894.

I'm also spawning follow-up tasks for v2 that we'll work into future sprints: #3895, #3896, #3897.

Closing this as it was mostly focused on v1 and it's now split up into smaller chunks.
