### ISSUE TITLE
Experiencing Inconsistent Azure Function Proxy Issues

### ISSUE THREAD

**Issue by dkershner6** [Azure/azure-functions-host#2929]
- Timestamp: Many
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name: listsregistries/listsregistriestest
- Function name(s) (as appropriate): ListAdminPage - Proxy Name: AdminList
- Invocation ID: Many
- Region: West US

#### Repro steps

Provide the steps required to reproduce the problem:

Create HTTP trigger function.  Create Proxy that references the function in the backendUri and a piece of the Uri that creates a query parameter {parameter} - "backend.request.querystring.parameter": "{parameter}".

#### Expected behavior

The function Uri and the proxy Uri give similar responses given similar inputs.

#### Actual behavior

In some cases, both the function and proxy URI will 404.  This can be solved by deleting the proxy, deploying, changing the name and route of the function, deploying, then re-creating the proxy with the new URI.  However, if I create any HTTP trigger with the same route as the original ones I created, it will still 404, even without a proxy present.

Once this is solved, in some cases the function URI will work correctly, but the proxy will still 404.

Troubleshooting attempts:
* I read in places in github that restarts can help.  Many have been attempted with no changes witnessed.
* I created a second, duplicate Azure function (test).  It exhibited the same behavior.
* I have tried using one less nested directory in the proxy route, no change.
* I have tried using no variables in the URI, to just get a simple redirect, still 404s.
* I have a second, nearly identical proxy/function pair in the same function app working properly.  I have been unable to discern a difference between the two other than names.  The two proxies appear nearly identical in the portal as well.
* I have switched the function to the "Hello, world" HTTP function.  No change.

#### Known workarounds

Partial workarounds included in description.

#### Related information 

Using C#.

Here is the proxy entry for the problem proxy:
```json
"AdminList": {
      "matchCondition": { "route": "/adminlist/{listId}" },
      "backendUri": "https://localhost/listAdminPage",
      "requestOverrides": {
        "backend.request.querystring.listId": "{listId}",
        "backend.request.querystring.shop": "{request.querystring.shop}",
        "backend.request.querystring.path_prefix": "{request.querystring.path_prefix}",
        "backend.request.querystring.timestamp": "{request.querystring.timestamp}",
        "backend.request.querystring.signature": "{request.querystring.signature}"
      }
    }
```

Here is the nearly identical working proxy:

```json
"List": {
      "matchCondition": { "route": "/list/{listId}" },
      "backendUri": "https://localhost/listPage",
      "requestOverrides": {
        "backend.request.querystring.listId": "{listId}",
        "backend.request.querystring.shop": "{request.querystring.shop}",
        "backend.request.querystring.path_prefix": "{request.querystring.path_prefix}",
        "backend.request.querystring.timestamp": "{request.querystring.timestamp}",
        "backend.request.querystring.signature": "{request.querystring.signature}"
      }
    }
```

I have wracked my brain as to why this is happening and come up with nothing.  Any help you can provide would be appreciated (anyone).

Thank you,
Derek

**Comment by dkershner6** [comment]
I decided to use my own "router" rather than rely on many proxies.  I like this approach better for many reasons.

**Comment by gvikei** [comment]
Hi Derek, would you mind sharing how you used your own router? Thanks a lot.

**Comment by dkershner6** [comment]
Sure.  I created a simple proxy that routes everything in a directory to a single function, and includes the rest of the path as a query parameter.  Then, inside that function, I split the path and use the values to return the correct page.

Basically, my own proxy, but within my control entirely.
