### ISSUE TITLE
Add support for blob secrets using a storage SAS URL

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-functions-host#2938]
Today, you can use `AzureWebJobsInternalSasBlobContainer` to use a SAS URL instead of the full `AzureWebJobsStorage` connection string. But that doesn't affect `AzureWebJobsSecretStorageType="Blob"`, which still needs `AzureWebJobsStorage`.

We need blob secrets to instead use a subfolder under the `AzureWebJobsInternalSasBlobContainer` container to store secrets.

This way, a single App Settings is all it takes to move away from full connection strings (plus Run-From-Zip for the files).

**Comment by fabiocav** [comment]
Obsoleted by #4650
