### ISSUE TITLE
Cli 2.0.1-beta.28/26 throws exception `Object reference not set to an instance of an object` when using CosmosDB bindings

### ISSUE THREAD

**Issue by JohnReeson** [Azure/azure-functions-host#2941]
Issue is from [SO thread](https://stackoverflow.com/questions/50681158/cannot-connect-to-cosmosdb-from-vs-code-azure-function).

Debug a pre-compiled c# httptrigger with CosmosDB output binding, using cli 2.0.1-beta.28/26, function host starts successfully. 

However once function triggered, error occurs.

> System.Private.CoreLib: Exception while executing function: Function1. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'document'. Microsoft.Azure.DocumentDB.Core: The type initializer for 'Microsoft.Azure.Documents.UserAgentContainer' threw an exception. Object reference not set to an instance of an object.

#### Repro steps

1. Create a c# http trigger template 
2. Replace function content  with code below

```csharp
[FunctionName("Function1")]
public static void Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequest req, TraceWriter log,
    [CosmosDB(
        databaseName: "db",
        collectionName: "coll",Id = "id",
        ConnectionStringSetting = "CosmosDBConnection")]out dynamic document
    )
{
    document = new { Text = "hahhah", id = Guid.NewGuid() };
}
```
3. Run function using cli 2.0.1-beta.28/26(installed by npm)
#### Known workarounds

1. Run the project directly in VS, it works. I find VS uses 2.0.1-beta.26 `no-runtime` version. While cli installed by npm is `win-x64` version on my side. See [release note](https://github.com/Azure/azure-functions-core-tools/releases/tag/2.0.1-beta.26).
2. Publish to Azure, works.
3. npm install cli 2.0.1-beta.25, works.

**Comment by fabiocav** [comment]
Resolved by: #2958 

Release in progress: https://github.com/Azure/app-service-announcements/issues/112
