### ISSUE TITLE
[V2][JavaScript] - Twilio and SendGrid bindings not working locally

### ISSUE THREAD

**Issue by ltouro** [Azure/azure-functions-host#2943]
_From @ltouro on June 1, 2018 15:53_

Could not send Twilio SMS or SendGrid Email on Azure using V2 beta runtime. Tried with the samples from docs and SendGrid  function template (as Twilio does not seem to have a template yet).

```
Azure Functions Core Tools (2.0.1-beta.28)
Function Runtime Version: 2.0.11776.0
```

function.json
```JSON
{
  "bindings": [
    {
      "name": "sendGridExample",
      "type": "httpTrigger",
      "methods": ["post"],
      "direction": "in",
      "authLevel": "function"
    },
    {
      "type": "sendGrid",
      "name": "message",
      "direction": "out",
      "apiKey": "SendGridKey",
      "from": "Azure Functions <samples@functions.com>",
      "to": "{customerEmail}"
    }
  ]
}
```

index.js
```javascript
module.exports = function (context, req) {
  context.log('JavaScript function triggered', req.body.orderId);

  context.done(null, {
    message: {
      to: req.body.customerEmail,
      subject: `Thanks for your order ${req.body.orderId}!`,
      content: [{
        type: 'text/plain',
        value: `${req.body.customerName}, your order ${req.body.orderId } is being processed!`,
      }]
    }
  });
};
```

local.settings.json
```javascript
{
  "IsEncrypted": false,
  "Values": {    
    ...otherSettings,
    "SendGridKey": "SG.af_nNtbHQvWdDWJUFy05Kw.Qj21u2...",
  },
  "ConnectionStrings": {}
}

```

Test payload
```JSON
{ "orderId": 12345, "customerName": "Joe Schmoe", "customerEmail": "putyouremail@here.com" }
```
Test response
```
{
  "message": {
    "to": "putyouremail@here.com",
    "subject": "Thanks for your order 12345!",
    "content": [
      {
        "type": "text/plain",
        "value": "Joe Schmoe, your order 12345 is being processed!"
      }
    ]
  }
}
```

References

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-sendgrid
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-twilio

_Copied from original issue: Azure/azure-functions-core-tools#507_

**Comment by mhoeger** [comment]
@soninaren - this issue only appears to repro locally. I think this is an extension install issue.

Locally, I did `func init` to create a node function app, then `func new` with a SendGrid template. Running `func host start` results in the host immediately dying.

Could you take a look at this? It runs fine locally with C# and the same function code runs with node in the portal.

```
~/twilio-sendgrid-node> func host start

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Function host is not running.
Application is shutting down...
```

**Comment by mhoeger** [comment]
@ltouro - looking at this again, it looks like my issue was an extension installation issue that was resolved by using the latest core tools (`npm i -g azure-functions-core-tools@core`).

Is the same true for you? Or are you still experiencing issues?

**Comment by ltouro** [comment]
@mhoeger is `@core` tag related to V2 runtime? I'm using `beta.34` right now. Should I try on it?

**Comment by mhoeger** [comment]
Yes, that's the command for [installing the latest V2 runtime](https://github.com/Azure/azure-functions-core-tools#installing) (which is linked to `beta.34` right now). Could you try with `beta.34`?

**Comment by soninaren** [comment]
You may also want to do `func extensions install` at the root of the function app. This will make sure you have the latest version of extensions installed.

**Comment by ltouro** [comment]
@mhoeger Confirmed that SendGrid is working on `@core` / `beta.34`. There is a small issue with the provided function template. The second parameter received by the function is now the request object, and not the request body object.

```js
module.exports = function(context, order) {}
```
should be
```js
module.exports = function(context, request) {}
```

Please advise if I should open a new issue to keep track of that. 

Also, I haven't tested the Twillio integration, as I have lost the code sample I used to do the test and there is no sample provided for that. Maybe we should add a sample, like SendGrid? 

@soninaren Thanks for the tip. As I created a new func to test, the SDK already checked I had the extension installed.

**Comment by soninaren** [comment]
@ltouro the [SendGrid JS template](https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/Templates/SendGrid-JavaScript) has a [queue trigger](https://github.com/Azure/azure-functions-templates/blob/dev/Functions.Templates/Templates/SendGrid-JavaScript/function.json#L4), if you put the following data in the queue trigger message, replace `joeschmoe@foo.com` with destination email address, it would work as expected.
`{ "orderId": 12345, "customerName": "Joe Schmoe", "customerEmail": "joeschmoe@foo.com" }`

Closing the issue, Please re-open if you are still seeing errors.

**Comment by ltouro** [comment]
@soninaren You are correct. I'm sorry about that.
