### ISSUE TITLE
'Microsoft.WindowsAzure.Storage.StorageException' in System.Private.CoreLib.dll

### ISSUE THREAD

**Issue by awernick** [Azure/azure-functions-host#2957]
I'm experiencing issues deploying / executing an Azure Function triggered by Azure Queue Storage.
Upon deployment, I'm able to see that the azure webhost shutsdown every time a new queue item is enqueued. No other execution logs are generated, and there is no sign anywhere in Kudu that the function is actually executing.

I'm able to attach a debugger to the running process, and various errors are being thrown by the Functions host, but no relevant information is actually displayed.

#### Investigative information

- Timestamp: 2018-06-07T01:44:02.506
- Function App version (1.0 or 2.0-beta): 2.0-beta
- Function App name: dinero-functions-test
- Function name(s) (as appropriate): TenantWalletStatusTrigger
- Invocation ID:
- Region: West US 2

#### Repro steps

- Deploy Azure Function code using azure-functions-core-tools -v 2.0.1-beta.28

#### Expected behavior

- Execution of Queue Trigger Function when new item is added to 'tenant-wallet-status' queue.

#### Actual behavior

- Upon deployment, various exceptions are thrown in the VS debugger. 
```
Exception thrown: 'System.InvalidOperationException' in Microsoft.Azure.WebJobs.Script.WebHost.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in Microsoft.Azure.WebJobs.Host.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll
```
#### Known workarounds

None, but possibily related to issue Azure/azure-functions-core-tools#335
Might also be related to the following: Azure/azure-webjobs-sdk#1715

#### Related information 

Provide any related information 

Platform: netstandard2.0
Language: C# using precompiled assembly
Deployed using: azure-functions-core-tools in Linux, Windows 10, and Visual Studio 2017

#### Kudu stdout log
```
Hosting environment: Production
Content root path: D:\Program Files (x86)\SiteExtensions\Functions\2.0.11776-alpha
Now listening on: http://localhost:25802
Warning: Only got partial types from assembly: D#####, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Exception message: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.Azure.WebJobs.Host.Indexers.DefaultTypeLocator.FindTypes(Assembly assembly, IEnumerable`1 extensionAssemblies) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\DefaultTypeLocator.cs:line 120
```

**Comment by pragnagopa** [comment]
@fabiocav - Can you please take a look?

**Comment by fabiocav** [comment]
@awernick can you please try that with beta.29?

**Comment by fabiocav** [comment]
Closing as no response. This should be working on the latest releases, but please let us know if you continue to run into issues.
