### ISSUE TITLE
Disable file watcher

### ISSUE THREAD

**Issue by arichiardi** [Azure/azure-functions-host#2976]
Hello folks!

This is more like a feature request. I was wondering whether there is a way to disable file watching.

A workaround is to point to a folder that never changes but maybe there is a cli switch for doing that which I cannot find, apologize if already there.

The use case would be to be able to work with a REPL without losing runtime state every time the files are changing.

I tried the following in `host.json` but no dice:

```
"watchDirectories": null
```

Thanks a lot!

**Comment by farrukh-normuradov** [comment]
We use Nodejs + VSCode and the Function Host is just picking every change in the workspace.
The function is reloaded with every test file update.

The setting in `host.json`
```
  "watchDirectories": ["Shared"]
```
does not limit the number of watched directories to one.

**Comment by mathewc** [comment]
Yes, my recollection was correct. Turns out there is a `fileWatchingEnabled` setting that you can set in host.json. Set it to `false` and all file watching will be disabled. E.g.:

```javascript
{
    fileWatchingEnabled: false
}
```

**Comment by arichiardi** [comment]
This is awesome thank you.

**Comment by Jaffacakes82** [comment]
@mathewc this doesn't appear to be documented anywhere, is there a reason for that or should the following [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json) be updated?
