### ISSUE TITLE
Update supported extesions in workerDescription to an array

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#2984]
[WorkerDescription.cs#L16](https://github.com/Azure/azure-functions-host/blob/ca3e1f2ef965d6bc4ab57eb35655c4b38a58d9c0/src/WebJobs.Script.Grpc/Abstractions/WorkerDescription.cs#L16) should be be an array. E.g. for Node in v1, we supported both .js and typescript https://github.com/Azure/azure-functions-host/blob/1e38fafa4410cc60720c1a680f3b104244b6a473/src/WebJobs.Script/Description/Node/Compilation/JavaScriptCompilationServiceFactory.cs#L17

**Comment by pragnagopa** [comment]
Fix checked in commit https://github.com/Azure/azure-functions-host/commit/a5a9b0d79a17670ba8e5b4a6f019637aaf1bfa42

**Comment by tylerl0706** [comment]
Awesome!
