### ISSUE TITLE
Investigate Debugging Java functions with JAVA_OPTS

### ISSUE THREAD

**Issue by jdneo** [Azure/azure-functions-host#2986]
#### Investigative information

Here are logs I got:

```
2018-06-12T02:02:24.571 [Information] Executing 'Functions.hello1' (Reason='This function was programmatically called via the host APIs.', Id=99ab4a88-959f-4702-8141-e8a2c520a30c)
2018-06-12T02:02:24.754 [Error] System.Private.CoreLib: Exception while executing function: Functions.hello1. System.Private.CoreLib: One or more errors occurred. (Worker process with pid 5716 exited with code 2) (Worker process with pid 5232 exited with code 2) (Worker process with pid 5508 exited with code 2). Worker process with pid 5716 exited with code 2.
2018-06-12T02:02:24.836 [Error] Executed 'Functions.hello1' (Failed, Id=99ab4a88-959f-4702-8141-e8a2c520a30c)
```

- Function App version:  `2.0-beta`
- Function App name: `remote-debug-test6`
- Function name(s) (as appropriate): `hello1`
- Region: `Southeast Asia`

#### Repro steps

1. Provision a new Function App
2. Change runtime to beta
3. Deploy the Jars(A HTTP-triggered function) using zipPushDeploy
4. Add `JAVA_OPTS: -Djava.net.preferIPv4Stack=true -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=127.0.0.1:8898` to the app settings
5. Add `HTTP_PLATFORM_DEBUG_PORT: 8898` to the app settings
6. Trigger the Function

#### Expected behavior

The Function should be triggered successfully.

#### Actual behavior

Get 500 error.

#### Known workarounds

Restart the function.

#### Related information 

* Programming language used: Java
* Links to source:
```java
package com.function;

import java.util.*;
import com.microsoft.azure.serverless.functions.annotation.*;
import com.microsoft.azure.serverless.functions.*;

/**
 * Azure Functions with HTTP Trigger.
 */
public class Function {
    /**
     * This function listens at endpoint "/api/hello". Two ways to invoke it using "curl" command in bash:
     * 1. curl -d "HTTP Body" {your host}/api/hello
     * 2. curl {your host}/api/hello?name=HTTP%20Query
     */
    @FunctionName("hello1")
    public HttpResponseMessage<String> hello(
            @HttpTrigger(name = "req", methods = {"get", "post"}, authLevel = AuthorizationLevel.ANONYMOUS) HttpRequestMessage<Optional<String>> request,
            final ExecutionContext context) {
        context.getLogger().info("Java HTTP trigger processed a request.");

        // Parse query parameter
        String query = request.getQueryParameters().get("name");
        String name = request.getBody().orElse(query);

        if (name == null) {
            return request.createResponse(400, "Please pass a name on the query string or in the request body");
        } else {
            return request.createResponse(200, "Hello, " + name);
        }
    }
}

```
* Bindings used: HTTP Trigger

**Comment by svickers** [comment]
I am having this same issue but for a javascript function.  Has been running without issue for a few months and just this morning started getting 100% failure rate, have not made any code changes.  Tried restart, rebuild, redeploy, no luck on fixing.

**Comment by pragnagopa** [comment]
@svickers  - Please see breaking change annoucement here https://github.com/Azure/app-service-announcements/issues/112
@jdneo - I will investigate. Renaming to title to reflect that this issue is regarding debugging

**Comment by jdneo** [comment]
@pragnagopa Can you repro this on your side?

**Comment by pragnagopa** [comment]
@jdneo - Functions runtime has been updated to accept debugging options from the CLI, instead of hardcoding them in the functions host itself.  CLI will be udpated soon - https://github.com/Azure/azure-functions-core-tools/pull/550

Will investigate after all the changes are incorporated into host and CLI. Do attach a GIF or any other info that might help investigation

**Comment by jdneo** [comment]
@pragnagopa Does that mean user can start the remote-debug session by triggering a function cli command?

**Comment by selvasingh** [comment]
Related doc is - https://code.visualstudio.com/docs/java/java-serverless

**Comment by TurtleBeach** [comment]
JAVA_OPTS no longer seems to be recognized for anything (at least in Java functions)
For what it's worth, the  approach below currently works with 2.0.11933 local runtime and maven beta-2 tools / beta-4 libraries:

W10: add an environment variable named: languageWorkers:java:arguments
Add a value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
configure debugger in VisualStudio to use port 5005

NOTE this is the same approach needed to define properties that can be read using System.getProperty("propertyName") in a Java function (add -Dname=value along with -agentlib...

BUT @pragnagopa needs to confirm this will continue to work!

**Comment by jdneo** [comment]
@pragnagopa 

Is `AppSetting languageWorkers:java:arguments` used to local debug? How about remote debugging a Java function. The tutorial here is not workable anymore, is there any server side change happened?

**Comment by pragnagopa** [comment]
Yes, I will investigate and update this issue when I have more information.

**Comment by darewreck54** [comment]
@pragnagopa Hi, has the issue been address which allows you to remote debug an azure function?  If not what is the ETA for it?

Thanks,
Derek
