### ISSUE TITLE
[v2] Error when using the latest Microsoft.Extensions.Configuration version.

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#2987]
**repro:**

1- Create a new v2 project in VS
2- install latest stable `Microsoft.Extensions.Configuration` (2.1.0)
3- Create a `var cb = new ConfigurationBuilder();`
4- invoke the function

**Result:**

```
System.Private.CoreLib: Exception while executing function: Function1.Run: Could not load file or assembly 'Microsoft.Extensions.Configuration, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. System.Private.CoreLib: Could not load the specified file.
```

**Workaround:**

Downgrade to 2.0.0

Reported on SO: https://stackoverflow.com/a/50785403/3234163

**Comment by paulbatum** [comment]
@fabiocav think this is already resolved with the current bits in dev. Will confirm and close.

**Comment by fabiocav** [comment]
Validated this against the latest bits and it works as expected. Closing as resolved.
