### ISSUE TITLE
Configure number of instances per Linux Function App

### ISSUE THREAD

**Issue by dariagrigoriu** [Azure/azure-functions-host#2990]
Add ability to configure the number of instances per Linux Function App as part of the preview.

**Comment by dariagrigoriu** [comment]
@davidebbo to retry.

**Comment by davidebbo** [comment]
I set the to 20, but I couldn't get it to scale past 5 instances, despite massive load and lots of 500 errors.

**Comment by balag0** [comment]
fixed.
