### ISSUE TITLE
Node.js native module fails to load

### ISSUE THREAD

**Issue by kylefurlong** [Azure/azure-functions-host#2995]
When trying to load the `appdynamics` Node.js module within an Azure Function, the execution fails with an exception:

> Error: Module did not self-register.
>     at Error (native)
>     at Object.Module._extensions..node (module.js:597:18)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at Module.patchedRequire [as require] (D:\home\site\wwwroot\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
>     at require (internal/module.js:20:19)
>     at tryRequire (D:\home\site\wwwroot\node_modules\appdynamics-libagent\index.js:16:10)
>     at requireBinding (D:\home\site\wwwroot\node_modules\appdynamics-libagent\index.js:29:15)
>     at Object.<anonymous> (D:\home\site\wwwroot\node_modules\appdynamics-libagent\index.js:62:14)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at Module.patchedRequire [as require] (D:\home\site\wwwroot\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
>     at require (internal/module.js:20:19)
>     at LibagentConnector.initLogger (D:\home\site\wwwroot\node_modules\appdynamics\lib\libagent\libagent-connector.js:92:29)
>     at Logger.init (D:\home\site\wwwroot\node_modules\appdynamics\lib\core\logger.js:87:30)
>     at LibAgent.initializeLogger (D:\home\site\wwwroot\node_modules\appdynamics\lib\libagent\libagent.js:147:21)

#### Investigative information

Please provide the following:

- Timestamp: N/A
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name: N/A
- Function name(s) (as appropriate): N/A
- Invocation ID: N/A
- Region: N/A

Azure details not available as I'm with the vendor support team, not the end-user.

#### Repro steps

1. Start a free trial with AppDynamics
2. Install the latest Node.js module using `npm appdynamics@4.4.9`, being sure that this npm exactly matches the target environment through the user-agent config value
3. Add the require statement and profile call to the Azure Function per https://docs.appdynamics.com/display/PRO44/Install+the+Node.js+Agent#InstalltheNode.jsAgent-install_nodejsInstallingtheNode.jsAgent
4. Add logging to the `node_modules/appdynamics/lib/core/agent.js` file around line 315, dumping any error to the filesystem
5. Note that running the function leads to the exception in the summary

#### Expected behavior

Honestly, I'm not sure. In earlier interactions with Microsoft support it was implied that native modules might not work, especially with runtime 1.0.

If they are intended to work, the module should load with no exceptions.

#### Actual behavior

The `appdynamics` module fails to load with an exception when trying to load a native module.

#### Known workarounds

No known workarounds with Azure Functions runtime 1.0 on Windows. We're investigating whether runtime 2.0 or Linux would work.

#### Related information 

Typically when we see these native module loading errors in other environments, it is due to a mismatch between the Node.js major version, architecture, or platform. We have tried to rule this out as best as possible. We know that the module version as reported by `process.versions` matches between the downloaded module and the runtime, as do the `process.arch` and `process.platform`, as reported by the `file` command in the Kudu console.

This led us to think it was a problem with loading dynamic libraries in this environment, as this native module has one dependency on the VC++ 2015 runtime. All other native dependencies that we know of at the time of writing are bundled with the module.

**Comment by paulbatum** [comment]
There is no native module support in functions V1. Please try this on the V2 beta. If you still have problems comment on this issue and I'll reopen.
