### ISSUE TITLE
NewtonSoft.Json 10.0.3 needed, but getting 11.0.0.* - Breaking Durables

### ISSUE THREAD

**Issue by GregLevenhagen** [Azure/azure-functions-host#2998]
Yesterday our Durables started producing 500s because of the following NewtonSoft.Json reference on the assembly version. We are not including nor using any NewtonSoft.Json within our own code.

#### Investigative information

- Timestamp: 2018-06-13T20:50:33.457
- Function App version (1.0 or 2.0-beta): 2.0.11857-alpha
- Invocation ID: 71dd8324-4e48-485d-bad1-08078082a159, fbbf76fb-448d-4d2b-84e5-ed17da5d587d
- Region: Central US

#### Repro steps

Run any Durable Function

#### Expected behavior

For the Durable Function to correctly use NewtonSoft.Json 10.0.3

Starting Host (HostId=*-test-funcapp-tripgen, InstanceId=d5048ba1-7a5b-46c1-a22b-e29bb61b9ec2, Version=2.0.11776.0, ProcessId=5340, AppDomainId=1, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=beta) 

#### Actual behavior

Exception while executing function: TripProcessingOrchestrator_HttpStart Could not load type 'Newtonsoft.Json.SerializationBinder' from assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. 

From the Portal Log window

2018-06-13T20:50:33.457 [Error] System.Private.CoreLib: Exception while executing function: TripProcessingOrchestrator_HttpStart. DurableTask.Core: Could not load type 'Newtonsoft.Json.SerializationBinder' from assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.
2018-06-13T20:50:33.509 [Error] Executed '*ProcessingOrchestrator_HttpStart' (Failed, Id=fbbf76fb-448d-4d2b-84e5-ed17da5d587d)

#### Known workarounds

No known work-arounds

We've tried manually including the 10.0.3 version of NewtonSoft.Json package.
We've tried manually setting the FUNCTIONS_EXTENSION_VERSION to a previous version, but all combinations of the value for previous versions fail. It detects the custom version, but says it's not valid. What is the format for the value to specify an exact version? I haven't found documentation other than (~1 or beta).

#### Related information 

* Programming language used - C#

**Comment by GregLevenhagen** [comment]
Workaround 
`FUNCTIONS_EXTENSION_VERSION ~2.0.11776`
will show 

>Runtime version loaded from Application Settings: ~2.0.11776
>Warning Unsupported Runtime Version Your custom runtime version is not supported. As a result 2.0.11776.0 runtime is being used. 

but works for now.

**Comment by pragnagopa** [comment]
This issue was moved to Azure/azure-functions-durable-extension#347
