### ISSUE TITLE
webhooks/incoming doesn't work if defined in routePrefix

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#3000]
_From @sonumalik1990 on June 13, 2018 9:16_

I have created an azure function as below:

```csharp
[FunctionName("Test")]
public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Anonymous, WebHookType = "genericJson")]HttpRequestMessage req, TraceWriter log)
{
}
```

and host.json:

```json
{
    "functions": [ "Test" ],
    "http": {
        "routePrefix": "api/webhooks/incoming",
        "maxOutstandingRequests": 20,
        "maxConcurrentRequests": 10,
        "dynamicThrottlesEnabled": true
    }
}
```

 "routePrefix": "api/webhooks/incoming", is mandatory to use.

Url : http://localhost:7071/api/Product/incoming/Test is working

Url: http://localhost:7071/api/webhooks/incoming/Test is not working

Please suggest.

_Copied from original issue: Azure/Azure-Functions#839_

**Comment by ahmelsayed** [comment]
_From @xscript on June 13, 2018 14:10_

Have you checked this [doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#customize-the-http-endpoint)?

**Comment by ahmelsayed** [comment]
a host.json with 

```json
{
    "http": {
        "routePrefix": "api/webhooks/incoming"
    }
}
```
Gives 404 for any function 

It might be a reserved route by the webhooks library

**Comment by fabiocav** [comment]
needs to be investigated.

**Comment by alrod** [comment]
`https://<host>/api/webhooks/incoming/<receiver>/{id}` is reserved route in ASP.NET WebHooks.
https://docs.microsoft.com/en-us/aspnet/webhooks/receiving/receivers#webhook-receiver-uris

In this case it's expected behavior. Closed.

**Comment by jovansnevress** [comment]
I'm trying and. I can't. Cyber bullying, big time,  can't even report this
hellllpppp

Johan Nevress
323-406-0557

**Comment by fabiocav** [comment]
Reopening this for validation. We handle all of the routing and explicitly call the WebHooks framework, so I'm not sure their route restrictions are causing the issue here.

**Comment by alrod** [comment]
This is only reproducible for V1. For V1 we explicitly load WebHooks receivers:
https://github.com/Azure/azure-functions-host/blob/v1.x/src/WebJobs.Script.WebHost/App_Start/WebApiConfig.cs#L73
