### ISSUE TITLE
Extension WebHook provider doesn't support linux

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#3003]
IWebHookProvider implementation by default returns null when running on linux (dedicated). apps The [code looks up](https://github.com/Azure/azure-functions-host/blob/5e04b953944e17e965a33e83173d92c6ba5993ca/src/WebJobs.Script.WebHost/WebHooks/WebJobsSdkExtensionHookProvider.cs#L56) WEBSITE_HOSTNAME app setting which is not set for linux apps. This causes the [GetWebhookHandler](https://github.com/Azure/azure-webjobs-sdk/blob/5140983cb163b20bf6af60afccebb705bc80ad80/src/Microsoft.Azure.WebJobs.Host/Config/ExtensionConfigContext.cs#L46) method to return null.  This in turn causes durable (and other) extension to return 500, here is the [durable functions](https://github.com/Azure/azure-functions-durable-extension/blob/e07877ab13b900fd3325eab27ab9889af1e810a5/src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs#L345) code path returning 500 caused by this error.

Here is a related issue for local environment https://github.com/Azure/azure-functions-host/issues/2024

**Comment by pragnagopa** [comment]
@mathewc  - Please triage

**Comment by dariagrigoriu** [comment]
Please validate with Event Grid for Linux preview.

**Comment by dariagrigoriu** [comment]
Closed following validation from @asavaritayal .
