### ISSUE TITLE
Node.js Http Function - request body undefined unless content-type specified.

### ISSUE THREAD

**Issue by dustensalinas** [Azure/azure-functions-host#3004]
- Timestamp: 201806013
- Function App version: 2.0.11857

Node.js Http Function - request.body on POST/PUT is now undefined unless Content-Type: application/json is passed vs previous functionality of it being a json object by default.

All prior 2.0 versions did not exhibit this behavior.

Example raw body:
{
  "foo":"bar"
}

request object

{
    "method": "POST",
    "url": "<url>",
    "originalUrl": "<url>",
    "headers": {
...
    },
    "query": {},
    "params": {}
}

content-type would be no issue however due to IE 11 support on our particular application, we then cannot support these headers unless we also have a reverse proxy.

**Comment by pragnagopa** [comment]
@mhoeger  - PR https://github.com/Azure/azure-functions-host/pull/3016 addresses this issue?

**Comment by mhoeger** [comment]
Yes - this is a regression that will be fixed with our next deployment

**Comment by mhoeger** [comment]
Closing the issue as it is now merged. @dustensalinas - an issue will be created in https://github.com/Azure/app-service-announcements that tracks our next V2 release. You can expect the deployment to start rolling out this week.
