### ISSUE TITLE
Can FSharp.Core be removed from runtimeassemblies.json?

### ISSUE THREAD

**Issue by johlrich** [Azure/azure-functions-host#3005]
Since [FSharp.Core is binary compatible](https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#fsharpcore-is-binary-compatible), I was wondering if the functions runtime should always take the latest available between the runtime and user supplied versions instead of the minorMatchOrLower?

Thanks

**Comment by fabiocav** [comment]
This has been done and will be deployed with the next release.

**Comment by johlrich** [comment]
@fabiocav super exciting news! thank you!
