### ISSUE TITLE
Function app on a consumption plan has large gaps in application logs

### ISSUE THREAD

**Issue by cortlun** [Azure/azure-functions-host#3009]
#### Investigative information

- Timestamp: 2018-06-14T19:29:10.472
- Function App version (1.0 or 2.0-beta): 1.0.11820.0
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: 76922c70-6d7a-4540-ad7b-5d72e87b4d8a
- Region: East US 2

#### Repro steps

Provide the steps required to reproduce the problem:
	1.  Instantiate the function via its blob trigger - update some metadata for existing blobs
	2.  Wait for the function to start/finish leveraging the WebJobs interface, eg https://hello-world.scm.azurewebsites.net/azurejobs/#/functions/invocations/
	3.  Once the function invocation shows as success in the WebJobs interface, check logs on the function's ftp site
	4.  Check for both 'Function started' and 'Function completed' entries, eg Function started (Id=3e855cd1-e2f0-418b-95b5-18f217ce1e08) and 2018-06-14T19:25:52.281 [Info,FileIngestorFunction] Function completed (Success, Id=3e855cd1-e2f0-418b-95b5-18f217ce1e08, Duration=173506ms)
	5.  Observe that, even for function invocations which show as successful in the WebJobs sdk, there are log entries missing

#### Expected behavior
I would expect application logs to be consistent with the WebJobs UI.  I also would expect application logs to be the most reliable source of truth while troubleshooting.  For every function invocation (especially for successful ones) I would expect a 'Function started' and 'Function ended' entry to show up in logs.

#### Actual behavior

In the following log file, you can clearly identify the gap in the logs.  At 2018-06-14T19:29:10.472, function invocation 76922c70-6d7a-4540-ad7b-5d72e87b4d8a started.  Unrecorded in the logs, around 4 minutes later the function completed successfully.  This was validated by checking the WebJobs UI and the target database (this function inserts into an Azure SQL single instance).  Following function start, the next entry in the logs is much later at 2018-06-14T19:48:17.054 and it shows only HTTP access information.  The 'Function ended' log entry for 76922c70-6d7a-4540-ad7b-5d72e87b4d8a is nowhere to be found in logs.

ftp://waws-prod-ch1-009.ftp.azurewebsites.windows.net/LogFiles/Application/Functions/Host/2018-06-14T19-11-27Z-5638fec2b6.log

Additionally, you can see the gap within the function directory: ftp://waws-prod-ch1-009.ftp.azurewebsites.windows.net/LogFiles/Application/Functions/function/

#### Known workarounds

I have no known workarounds for troubleshooting effectively if gaps are inexplicably present in application logs.

#### Related information
I've also had issues with the reliability of other diagnostic components with regards to functions on a consumption plan.  These include App Insights showing as Not Available and the 'Monitor' page for the function showing no data despite function invocations showing up on the WebJobs UI.  This is based on experience only, I have yet to document the issues.

**Comment by brettsam** [comment]
The file logs are only written when you are in an active debug session via the portal. You can tweak this behavior in host.json: https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#tracing. 

However, we'd recommend that you start writing to Application Insights as a more performant way to monitor your function: https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring
