### ISSUE TITLE
Timer triggers not firing reliably

### ISSUE THREAD

**Issue by paaland** [Azure/azure-functions-host#3029]
#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0-beta): 1.0.11820.0 (~1)
- Function App name: yt3-prod-app-functions
- Function name(s) (as appropriate):  VirtualSitePredictor
- Invocation ID: 541a3053-93c0-43ec-9094-2b5f1bb7a219
- Region: West Europe

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a function  with a time trigger
2. Let it run for a while
3. Inspect the invokation history in Azure Portal

#### Expected behavior

Provide a description of the expected behavior.

That the function actually runs at the intervals specified.

#### Actual behavior

This is the invocation log from a function that should run every 30 minutes:

> DATE (UTC) 			RESULT CODE 	DURATION (MS) 	OPERATION ID 
> 2018-06-19 21:30:00.006		0		65946.824	da4e6c36-519d-4472-8ea7-66abf3fcd4a5
> 2018-06-19 20:30:00.012		0		76095.467	7df00611-2efe-4ca9-bba9-6806ed6f6993
> 2018-06-19 18:34:22.266		0		100089.478	6aa123c5-5512-493f-8f64-fa130c797b3f
> 2018-06-19 16:00:00.011		0		73194.0098	1dce762c-c130-4e53-af28-38a665a96ec9
> 2018-06-19 15:00:00.005		0		73070.0466	2bff0427-4ba7-4961-af4c-ebabd1067a23
> 2018-06-19 14:30:00.003		0		77492.1787	3f2ab0f1-2f6c-433d-bef4-6d944c6379f2
> 2018-06-19 13:30:00.016		0		63312.7085	17f80b15-a6d0-40a6-811e-411045e450d5
> 2018-06-19 10:00:00.010		0		68219.5376	6cdfeaed-be34-4ee5-a8de-3c59dcf0deb1
> 2018-06-19 00:30:00.012		0		63105.3592	7948ba6b-269c-4583-8e4d-09c01592f2c8
> 2018-06-18 21:30:00.013		0		61554.3184	34535104-a6d6-4625-85fe-79203e6b8d82
> 2018-06-18 12:00:00.005		0		65245.3066	05502e35-df75-42a7-9f89-92973357006f
> 2018-06-18 08:00:00.010		0		88080.2679	e333703c-b036-4e68-b8cb-8a1a791a6873
> 2018-06-18 05:00:00.011		0		56681.0976	a8725cb1-a2f7-4d02-b72c-c17c701af80f
> 2018-06-18 02:00:00.006		0		83553.8917	59bbac25-67fd-4331-8fec-1f172e4862a0
> 2018-06-17 20:30:00.008		0		69329.3267	98498a0e-307d-43ad-a020-36856df1bcfa
> 2018-06-17 16:00:00.006		0		76588.0255	41e8af5e-0d96-49dc-9195-54af7e07697d
> 2018-06-17 15:00:00.003		0		93325.3133	6aac0ce6-aa48-4e7a-835d-b6d022ff423e
> 2018-06-17 12:59:59.998		0		97819.9509	c7f9b49a-da44-4b65-8d32-cf989c83a047
> 2018-06-17 08:59:59.320		0		101491.3719	0e182b67-79f1-4bc9-a0ed-6ab2d70352fb
> 2018-06-17 08:00:00.013		0		97493.665	a2515b52-9003-4397-860a-62b04da0b6df`

As you can see there are large gaps in there.

#### Known workarounds

Provide a description of any known workarounds.

None

#### Related information 

Provide any related information 

* Programming language used: C#
* Links to source
* Bindings used: EventHub, ServiecBus, Storage Queue and Timer

> {
>   "generatedBy": "Microsoft.NET.Sdk.Functions-1.0.13",
>   "configurationSource": "attributes",
>   "bindings": [
>     {
>       "type": "timerTrigger",
>       "runOnStartup": false,
>       "schedule": "0 */30 * * * *",
>       "useMonitor": true,
>       "name": "myTimer"
>     }
>   ],
>   "disabled": false,
>   "scriptFile": "../bin/YT3.Functions.dll",
>   "entryPoint": "YT3.Functions.VirtualSitePredictor.Run"
> }

**Comment by dieterhowest** [comment]
i think i have the same problem my timer start at 0 */60 * * * * and normally it takes 20 min. to finish , but during the execution the timer fires again without any reason. I am using a app plan, not consumption model.

**Comment by MisinformedDNA** [comment]
I had this issue recently. The workaround was to disable `RunOnStartup`.

```csharp
public static async Task Run([TimerTrigger("0 */30 * * * *", RunOnStartup = false)]TimerInfo myTimer...
```

My guess is that the host keeps getting reset, though I don't know why that would happen so frequently.

**Comment by mhoeger** [comment]
@MisinformedDNA RunOnStartup should be false by default. Are you finding that you have to define the attribute explicitly? That would definitely be a bug!

**Comment by MisinformedDNA** [comment]
@mhoeger Nope, I set it to true. I expected it to fire once at deployment and then, maybe, occasionally as Azure span up and down servers. But it was executed every minute, instead of every hour. Changing it back to false, made the CRON expression be honored.

**Comment by MisinformedDNA** [comment]
@mhoeger Was this fixed?

**Comment by mhoeger** [comment]
@MisinformedDNA - I closed this due to inactivity from the OP. 

I think I may have misinterpreted your comment - I thought that the inconsistency other folks chimed in on was due to "runOnStartup" being set to "true". For consumption functions, runOnStartup = true, will cause unwanted but expected behavior (from [docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer#configuration)):

> If true, the function is invoked when the runtime starts. For example, the runtime starts when the function app wakes up after going idle due to inactivity. when the function app restarts due to function changes, and when the function app scales out. So runOnStartup should rarely if ever be set to true, especially in production.

Are you still experiencing issues not related to runOnStartup?
