### ISSUE TITLE
Could not load file or assembly 'Microsoft.Rest.ClientRuntime.Azure, Version=3.0.0.0'

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#3043]
_From @travisnielsen on June 19, 2018 1:9_

I have a [Function that uses Azure Resource Manager APIs to automate resource tagging](https://github.com/travisnielsen/azuretagsync). After upgrading to .Net Core 2.1 and Functions Core Tools 2.0.1-beta 29 I get the infamous 'Could not load file or assembly' error that others have reported in other scenarios (like #473). I'm having trouble finding the magic Nuget package versions to correct this.

```
Could not load file or assembly 'Microsoft.Rest.ClientRuntime.Azure, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.Azure.Management.ResourceManager.Fluent, Version=1.0.0.60, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
```

Here are my current references:
```
<PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.1.0-preview" />
<PackageReference Include="Microsoft.Azure.Management.Fluent" Version="1.11.1" />
<PackagageReference Include="Microsoft.Azure.Management.ResourceManager.Fluent" Version="1.11.1" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.13" />
```
I tried various downgrades and other combinations but to no avail. Does anyone have suggestions on how I can get past this?

_Copied from original issue: Azure/azure-functions-core-tools#540_

**Comment by pragnagopa** [comment]
@fabiocav - Any ideas?

**Comment by pragnagopa** [comment]
@fabiocav - Another one related to assembly loading

**Comment by fabiocav** [comment]
@travisnielsen a few questions:

- Does this  happen on Azure **and** local? Or local only?
- Have you tried this against the latest, `beta.30` release? There were fallback fixes in that release that may help with your scenario
- If you continue to run into the issue with `beta.30`, can you please provide a small repro on GitHub so we can validate and investigate what is going on? If this continues to be an issue, it is definitely something we'd like to address.

**Comment by fabiocav** [comment]
Thanks for the update, @travisnielsen! Love closing things like these as resolved :)

**Comment by Chinney** [comment]
So what is the official fix for this error?

I am experiencing this very error frequently in all my c# functions. My workaround for now is manually removing or adding the line `"Microsoft.Rest.ClientRuntime.Azure": "3.0.0.0"`, from or to the corresponding project.json, waiting for the NuGet packages to be installed and re running the function. While this is a possible thing to do while I am manually testing my function I cannot count on them when being triggered automatically in production. I've built a complete processing pipeline with these functions. This error renders the entire pipeline unreliable.

My project.json usually looks like this:

```
{
  "frameworks": {
    "net46":{
      "dependencies": {
        "Microsoft.Azure.Batch": "8.1.2",
        "Microsoft.Azure.KeyVault": "3.0.0",
        "Microsoft.Azure.Services.AppAuthentication": "1.0.3",
        "Microsoft.Rest.ClientRuntime.Azure": "3.0.0.0"
      }
    }
  }
}
```

**Comment by leroibeukes** [comment]
Anyone ?

**Comment by fabiocav** [comment]
@leroibeukes thanks for sharing. Just for context, what @Chinney reported and what you're describing are V1 behavior, which is different than what the original issue was tracking. Please open a separate issue with details if you continue to run into problems. Thanks!
