### ISSUE TITLE
System.Private.CoreLib: ReflectionOnly loading is not supported on this platform.

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#3046]
_From @grahamehorner on June 11, 2018 18:21_

Is there any reason why AzureFunctions aren't able to use **ReflectionOnly** loading? what alternative is available? 

_Copied from original issue: Azure/azure-functions-core-tools#527_

**Comment by pragnagopa** [comment]
Assigned to @fabiocav as he has more context

**Comment by fabiocav** [comment]
`ReflectionOnlyLoad` is not supported on .NET Core. This is not an Azure Functions specific issue. The recommendations here would be the same that apply to standard .NET Core applications (e.g. using `MetadataReader`/`System.Reflection.Metadata`)
