### ISSUE TITLE
Remove hardcoded java version when running in Azure

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#3048]
Java version zulu8.23.0.3-jdk8.0.144-win_x64 is hardcoded [here](https://github.com/Azure/azure-functions-host/blob/d95653b8fda05e9a0b0c7b48196e555135a80257/src/WebJobs.Script/Rpc/Configuration/JavaWorkerProvider.cs#L85)

Need to move this to worker.config.json

**Comment by paulbatum** [comment]
@pragnagopa which version of java is going to be used now? I filed https://github.com/Azure/azure-functions-host/issues/3081 and I have a theory that just-in-time download of java is causing this. We need to make sure that whatever version of java we default to is on the worker by default and not download just in time
