### ISSUE TITLE
`WinHttpHandler is only supported on .NET Framework and .NET Core runtimes on Windows` in v2 function

### ISSUE THREAD

**Issue by JohnReeson** [Azure/azure-functions-host#3052]
#### Repro steps

Locally create a v2 function httptrigger (host version `2.0.11857`), install `System.Net.Http.WinHttpHandler` package and new a `WinHttpHandler` object, `WinHttpHandler handler = new WinHttpHandler();`

#### Expected behavior

Works without error

#### Actual behavior

System.Private.CoreLib: Exception while executing function: TestWinHttpHandler. System.Net.Http.WinHttpHandler: WinHttpHandler is only supported on .NET Framework and .NET Core runtimes on Windows. It is not supported for Windows Store Applications (UWP) or Unix platforms.

#### Known workarounds

V1 works.

**Comment by mathewc** [comment]
You are running on Windows, correct? (Not Linux). Can you [share your app](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately) name info with us?

**Comment by JohnReeson** [comment]
Yes, on Windows and also test in host 2.0.11888, same error.

**Comment by AdrianPell** [comment]
Any update on this issue?  I've just run into it (using Google Ads API), and before I try to roll back to using Functions V1 - which is going to be painful reference-wise - I'd like to see if there's any workaround.

**Comment by AdrianPell** [comment]
As a workaround, it's possible to put a local copy of the appropriate System.Net.Http.WinHttpHandler.dll file in the functions directory, and add the following to the csproj file:
```
  <ItemGroup>
    <None Update="System.Net.Http.WinHttpHandler.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Target Name="CopySPSM" BeforeTargets="Build">
    <Copy SourceFiles="System.Net.Http.WinHttpHandler.dll" DestinationFolder="$(OutputPath)\bin" />
  </Target>
```

**Comment by andrei-m-code** [comment]
@AdrianPell  @JohnReeson which one is "appropriate"? I am having exactly the same issue and I need this workaround to work. Where can I find the DLL that will work? 

Thanks!

**Comment by AdrianPell** [comment]
@andrei-m-code Yes, the .NET Standard one would most likely be what you needed (assuming your project is targeting that of course).  See @fabiocav comments here #3568 for more color on what's actually happening.
