### ISSUE TITLE
Azure Function suddenly stopped being triggered by events from Event Hub

### ISSUE THREAD

**Issue by murugend** [Azure/azure-functions-host#3054]
I have an event triggered Azure Function with non-default consumer group running on an app service plan. On 2018-06-21 it suddenly stopped being triggered by events from the Event Hub, until restarted some hours later. I am unable to find the cause of this.

Incoming/Outgoing messages to event hub:
![image](https://user-images.githubusercontent.com/20225583/41910240-66f57b76-7949-11e8-9689-a8aba5baf0e7.png)
As you can see, the events come in continuously. But, around noon they stop flowing out. When the Function App is restarted the events flow out again. There are no errors on the Event Hub.

Server requests for Function App:
![image](https://user-images.githubusercontent.com/20225583/41910275-7ba07526-7949-11e8-9ca3-4973f2d534c1.png)
Even though the events flow into the Event Hub continuously, the Azure Function stops being invoked, until restart some hours later. There are no failures in the Function App.

I need to find the cause of this.

- Timestamp: 2018-06-21 10:16 UTC - 2018-06-21 13:36 UTC
- Function App version: 1.0
- Invocation ID: b5ae49c1-5ea4-4a15-a681-e81abe91dffd (last invocation before triggering stopped)
- Region: North Europe

**Comment by murugend** [comment]
@grahamehorner The bindings in the function.json file are:
"bindings": [
    {
      "type": "eventHubTrigger",
      "path": "EventHubName",
      "consumerGroup": "eventingestgroup",
      "connection": "EventHubConnectionString",
      "name": "eventMessages"
    }
  ]

**Comment by mathewc** [comment]
Servicing loop - can you please investigate this ASAP @pragnagopa @ConnorMcMahon

**Comment by ConnorMcMahon** [comment]
I couldn't find a function app with an invocation around 6/21 with invocation Id = b5ae49c1-5ea4-4a15-a681-e81abe91dffd in North Europe. @murugend, could you please share another invocation id?

**Comment by murugend** [comment]
Sorry, must have made a mistake.
Here is the correct Id: 20a31720-ffe7-4561-80b4-30cb387f5c46

**Comment by murugend** [comment]
I am however able to find the above-mentioned ID in application insights as well. Maybe I'm misunderstanding something?

![image](https://user-images.githubusercontent.com/20225583/42693386-433d2b48-86af-11e8-97f6-8196e927c27a.png)

I'm also certain the azure function is running on an North Europe ASP.

**Comment by ConnorMcMahon** [comment]
I believe that RequestId is actually tied to EventHub, and we don't have that information in our logs. To give us a function invocation Id, click on that item in Application Insight, and on that event's details, click on the "All available telemetry for this root operation". From there, you should see an "Executing 'Functions.<FunctionName>', etc". Can you provide us the Id field from one of these logs?

**Comment by jeffhollan** [comment]
Not a ton of detail left in this thread and is quite old.  Is there an issue still here anyone is facing before I close?

**Comment by samvanbrussel** [comment]
It still seems to be the case for me. It got introduced some weeks ago, after I did an update of NuGet packages. Might be a coincidence.

Sometimes it resumes automatically, now and then I manually restart the Function App.

![image](https://user-images.githubusercontent.com/2074393/57524735-036f7400-7329-11e9-8c2b-c78f1b30b7bb.png)

When it is not working any more, I can see 3 servers in the Live Metrics Screen in Application Insights. One of them has 0% cpu usage, 2 have high 60-80% cpu usage. All of them handle 0 requests per second.

What are these doing? Fighting for some resource?

**Comment by hannesaqua** [comment]
It happened to me as well today. Had a function that uses an Event Hub trigger, it stopped consuming the Event Hub until I manually restarted the function. Nothing had changed in the function, binding or event hub.
![image](https://user-images.githubusercontent.com/55734535/68843616-b64dcf80-06c8-11ea-83b8-27fd78b603fb.png)

**Comment by jeffhollan** [comment]
@hannesaqua can you share the name of the app or an execution ID so I can look into this?

**Comment by hannesaqua** [comment]
I have an invocation ID, is that enough? Obviously it's from an actual invocation of the function and the problem here is that it was not invoked, but can you infer the application from the invocation ID?

InvocationId: 18af9715-79e6-4e94-9f35-8f33c2abd503

**Comment by kashimiz** [comment]
@hannesaqua, can you also provide the region your app is running in (i.e. North Europe)? With that + invocation ID we can track down your application.

**Comment by hannesaqua** [comment]
Yes, it's in North Europe. I also find an appID in Log Analytics if that helps: 867bd41d-ba33-4af7-96af-437842ea4bb7

**Comment by jeffhollan** [comment]
This is one of those issues that can have a number of different causes, but just tested and I don't believe there is something systematic here.  A few common gotchas:
1. Confirm the connection string in the app setting and referenced in the trigger is valied
2. Confirm you haven't enabled service endpoints or restricted access to the event hub (unless you have also joined function to VNet and enabled VNet triggers)
3. Confirm you haven't deleted / recreated the same event hub / event hub name.  We store checkpionts in a blob of `AzureWebJobsStorage` based on event hub name. If you recreate with the same name the checkpoints may be invalid and you would need to manually delete the blobs we create in the `AzureWebJobsStorage` account.

If all else fails I'd check out app insights.  If you look at the "Exceptions" table it should surface any exceptions your app may be throwing

**Comment by samvanbrussel** [comment]
@jeffhollan , how do you explain a restart of the function app to be fully functional for hours or days? If these settings were incorrect, nothing would happen then.

Might be correct to close this issue, as infrastructure might have been changed and libraries updated. But your _few common gotchas_ indicate you're not getting the point.
