### ISSUE TITLE
Unable to establish a FTP connection from function

### ISSUE THREAD

**Issue by FrederickRies** [Azure/azure-functions-host#3063]
Hello here,

I try to send a document to a FTP server from a CSharp library Azure Function.
This is working perfectly on my local machine, but it always fail when it's deployed and running on Azure. I have the same behavior from a AppService plan or a consumption plan.
I have tried different librairies (like FlientFTP) and I have different errors :
- Proxy FTP is not allowed on this server.
- Can't open data connection
- The remote server returned an error: (421) Service not available, closing control connection.

Is there something preventing thoses connection to be established within Azure ?

#### Information
- Function App version : 1.0
- Function App name : keyplworkers-weu
- Function name(s) (as appropriate) : ConnectorFtp
- Invocation ID : 14842089-89d8-4dc2-baec-a7bd3ec4e585
- Region: West Europe

#### Related information 
Here is my last attempt with a basic FtpWebRequest wich fail with the error : " The remote server returned an error: (421) Service not available, closing control connection.". Again, this code is working perfectly in local.
the uri comes from the settings and the stream comes from a storage account blob.

```csharp
            var client = (FtpWebRequest)FtpWebRequest.Create(uri);
            client.Method = WebRequestMethods.Ftp.UploadFile;
            client.KeepAlive = false;

            int buffLength = 2048;
            byte[] buff = new byte[buffLength];
            int contentLen;
            contentLen = stream.Read(buff, 0, buffLength);
            
            using (Stream requestStream = client.GetRequestStream())
            {
                while (contentLen != 0)
                {
                    requestStream.Write(buff, 0, contentLen);
                    contentLen = stream.Read(buff, 0, buffLength);
                }
            }
```

Thank you very much for your assistance on this case

**Comment by mathewc** [comment]
Perhaps the libraries you're using are being blocked by our sandbox https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox. Servicing loop, can you take a look? @pragnagopa @ConnorMcMahon

**Comment by ConnorMcMahon** [comment]
I noticed in the stacktraces by at least one of the libraries you were using that they were trying to open a TCP client, which likely was trying to create a socket to communicate. As @mathewc mentioned, Azure Web Apps (including Azure Functions), run in a sandbox that prevents certain operations for security purposes, and one of those is opening raw sockets. 

NOTE: these sandbox restrictions do not apply to all of Azure, just many of the PaaS offerings.

**Comment by paulbatum** [comment]
The sandbox prevents listening on other ports, but not outbound traffic. I don't think the port restrictions are in play here.

**Comment by paulbatum** [comment]
I was able to get FTP working fine from a consumption function app. I used https://www.nuget.org/packages/FluentFTP/19.2.2. Here is the code and the output:

```csharp
        [FunctionName("Function1")]
        public static async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequest req, ILogger log)
        {
            var client = new FtpClient(
                Environment.GetEnvironmentVariable("FTP_HOST"),
                Environment.GetEnvironmentVariable("FTP_USERNAME"),
                Environment.GetEnvironmentVariable("FTP_PASSWORD"));

            var items = await client.GetListingAsync();

            foreach (var i in items)
            {
                log.LogInformation($"{i.Name} {i.Size}");
            }

            return new OkResult();
        }
```

```
2018-10-11T18:32:16.703 [Information] Executing 'Function1' (Reason='This function was programmatically called via the host APIs.', Id=acc180da-72b2-4d3e-bb8b-39a2292e1b93)
2018-10-11T18:32:17.458 [Information] .ssh 0
2018-10-11T18:32:17.458 [Information] ASP.NET 0
2018-10-11T18:32:17.458 [Information] data 0
2018-10-11T18:32:17.459 [Information] LogFiles 0
2018-10-11T18:32:17.459 [Information] site 0
2018-10-11T18:32:17.459 [Information] SiteExtensions 0
2018-10-11T18:32:17.467 [Information] Executed 'Function1' (Succeeded, Id=acc180da-72b2-4d3e-bb8b-39a2292e1b93)
```

**Comment by FrederickRies** [comment]
Thank you all for for your response,

I had put this topic aside, but I've just try again with the latest release of v1 and v2 runtime and i'm not able to reproduce this issue anymore.

Again thank you for you help.
I close this issue.
