### ISSUE TITLE
function app stops responding after few hours.

### ISSUE THREAD

**Issue by saipuli** [Azure/azure-functions-host#3064]
I have a function app with two functions one http trigger and another a queue trigger which worked fine when deployed. After few hours (overnight) it stopped working and restarting the app didn't help. The function app is built in dotnet core C# class library method, and I'm deploying from VSTS. I had to completely delete the fn-app from consumption plan and re-deploy on an app service plan. It worked for a few hours and then stopped again. I can't open the console from the portal, can't even see the list of functions in the portal view.

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0-beta): beta
- Function App name: beyond-storage-sas
- Function name(s) (as appropriate): GenerateSAS, StoreDataToTable
- Invocation ID: Not applicable as I can't even see the functions.
- Region: EastUS

#### Repro steps
Not sure if it is reproducible but here are the steps that got the app into non-responsive state twice.

1. Create a new function app using dotnet core C# class library method. Or clone [sample](https://github.com/lindydonna/CSharpHttpCore) and expand on it.
2. Wrote two functions one exposed as HttpTrigger and the other QueueTrigger.
3. Both functions have table input/output bindings to a Azure Storage Table.
5. Deployed using VSTS and made sure its working.
5. Wait for few hours (overnight) without any requests to the app, to kind of let it go into idle. 

#### Expected behavior

When I make a new http request next morning after idle, the trigger should respond with a 200 status code and a string response. Possibly a few second delay for cold start.

#### Actual behavior

The functions are completely disappeared no where to be found. Portal shows the app, but no functions under it. Can't access the function app settings, app settings or console.

<img width="565" alt="screen shot 2018-06-27 at 9 41 22 am" src="https://user-images.githubusercontent.com/2796555/41978149-3277ebc6-79ef-11e8-9a85-ffe7dcaded50.png">

<img width="1456" alt="screen shot 2018-06-27 at 9 19 24 am" src="https://user-images.githubusercontent.com/2796555/41978163-39cd7c74-79ef-11e8-802e-63a33830cb01.png">

**Comment by saipuli** [comment]
Ok, after a long 45 minute call with MS tech, we found that this is an issue with 64 bit vs 32 bit. Once we rolled back the app settings to 32 bit, it started working.

MS might have pushed the "Functions 2.0.11888-alpha" last night breaking the 64 bit. 

Will monitor it for another night or two and report again.

**Comment by davidebbo** [comment]
This was the announcement for the change: https://github.com/Azure/app-service-announcements/issues/117. Please make sure to monitor the announcement repo if you use the Preview, so you know of important changes that are coming before it affects you.
