### ISSUE TITLE
Container Fails To Start on RunContainer

### ISSUE THREAD

**Issue by nickmza** [Azure/azure-functions-host#3070]
The Functions Runtime fails to start. The following messages appear in the trace:

2018/06/28 1:13:26 PM [WIN-KK51GMUASQB] Executing task: RunContainer (Total elapsed time: 00:00:30.0288070)
2018/06/28 1:13:56 PM [WIN-KK51GMUASQB] Executing task: RunContainer (Total elapsed time: 00:01:00.0637894)
2018/06/28 1:14:26 PM [WIN-KK51GMUASQB] Executing task: RunContainer (Total elapsed time: 00:01:30.0943046)
2018/06/28 1:14:56 PM [WIN-KK51GMUASQB] Executing task: RunContainer (Total elapsed time: 00:02:00.1269624)
2018/06/28 1:15:26 PM [WIN-KK51GMUASQB] Executing task: RunContainer (Total elapsed time: 00:02:30.1583489)

#### Investigative information

We are running on Windows Server 2016 VM with HyperV Enabled. 

When we try to start the container (or any container) manually the container stalls in the 'Creating' state. For examplem 'docker run hello-world' also fails. 

There are no logs under ProgramData\Docker\<containerId>.
There are no logs under the AzureFunctionsRuntime in event viewer. 

It would seem there is something not right with the install but I am at a loss for what to try next. 

Here is the docker inspect for one of the stalled containers:

[
    {
        "Id": "3c3ba31f32958b5a366a09473203a6b8ee358e05e0070a7d05c33a7e9ff64a28",
        "Created": "2018-06-28T08:09:53.0998702Z",
        "Path": "C:\\ServiceMonitor.exe",
        "Args": [
            "w3svc"
        ],
        "State": {
            "Status": "created",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "0001-01-01T00:00:00Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:22349412b6717165761766c8568b61f78531a89aac15c974aa7b7c61b8421a84",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "",
        "Name": "/sad_goldwasser",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                32,
                149
            ],
            "Isolation": "process",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\Program Files\\Azure Functions Runtime\\docker\\windows\\windowsfilter\\3c3ba31f32958b5a366a09473203a6b8ee358e05e0070a7d05c33a7e9ff64a28"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "3c3ba31f3295",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "ROSLYN_COMPILER_LOCATION=c:\\RoslynCompilers\\tools",
                "AzureWebJobsScriptRoot=C:\\home\\site\\wwwroot",
                "AzureWebJobs_NuGetPath=c:\\bin"
            ],
            "Cmd": null,
            "Image": "azfuncrun/azure-functions-runtime:preview2-latest-servercore",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "C:\\ServiceMonitor.exe",
                "w3svc"
            ],
            "OnBuild": null,
            "Labels": {
                "VENDOR": "Microsoft Corporation"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by mathewc** [comment]
So to confirm - you're using https://docs.microsoft.com/en-us/azure/azure-functions/functions-runtime-overview? @jvano

**Comment by nickmza** [comment]
Hi.

Yes. We have figured it out though. There were a number of different issues we needed to contend with. Will post the full list here shortly for anyone else that encounters this.

Regards

NIck

**Comment by devpsi** [comment]
what happened to posting the list?
