### ISSUE TITLE
Fix casing sensitivity for languageWorkers:*:arguments on non-Windows platforms.

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#3080]
As reported here https://github.com/Azure/azure-functions-core-tools/issues/557 

It seems that the runtime accepts `languageWorkers:*:arguments` on Windows but it has to be `languageWorkers:*:Arguments` on non-Windows. ideally `Arguments` should be lower case as well or at least do case insensitive matching. I know the latter probably breaks linux conventions, so I'm not sure

**Comment by pragnagopa** [comment]
Configuration section names are not case sensitive according to documentation [aspnetcore basicconfiguration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1&tabs=basicconfiguration)
