### ISSUE TITLE
Runtime failure - Additional logging during Host startup + Improved Error mesage + AppLens

### ISSUE THREAD

**Issue by cts-shrahman** [Azure/azure-functions-host#3082]
CSS gets lots of cases on function failed to start, runtime failed, admin keys are not available
<br><br>

**Ask** <br>

1. Additional logging during Host startup to troubleshoot Host startup issues. <br>
2. Improved error messaging on the portal. Include steps for mitigation. <br>
3. can possibly added to AppLens.

**Comment by jeffhollan** [comment]
@brettsam @fabiocav do you feel this is well understood enough we could act on it and help alleviate customer pain?

**Comment by brettsam** [comment]
This is something that we're actively working on with detectors and will probably be an ongoing effort. I'd suggest that we close this and instead tackle the items more specifically as we find them.
