### ISSUE TITLE
Messages getting processed twice - additional logging in AI and/or FunctionsLogs

### ISSUE THREAD

**Issue by cts-shrahman** [Azure/azure-functions-host#3083]
**Scenario**: Same message got processed twice <br>

**Ask**: Can we add additional logging in AI and/or FunctionsLogs like message id and other message metadata for function triggers. This information is very helpful in support cases where customer is asking why messages are getting processed twice. Once we have the message ID, we can tell if this is same message or same message data. <br>

Might be related to https://github.com/Azure/azure-functions-host/issues/2796

**Comment by paulbatum** [comment]
@cts-shrahman  this is work to do per service (service bus, azure queues, etc). Can you give us which scenario would be highest pri to do first?

**Comment by cts-shrahman** [comment]
@Prashant Pratap<mailto:ppratap@microsoft.com>, @Finbar Ryan<mailto:Finbar.Ryan@microsoft.com> any thoughts on this?

**Comment by paulbatum** [comment]
Lets start with Service Bus and Azure Queues.

**Comment by maiqbal11** [comment]
Will be fixed in https://github.com/Azure/azure-webjobs-sdk/pull/1993

**Comment by maiqbal11** [comment]
Checked in and should go as part of the next release.

**Comment by paulbatum** [comment]
@maiqbal11 Awesome - can you share a quick example of what this message ID logging looks like?

**Comment by maiqbal11** [comment]
Including details on the messages below:

1. Queues: `Trigger Details: MessageId: d5cb38e8-9d38-4714-a372-cdb50e5a0bbd, DequeueCount: 1, InsertionTime: 11/7/2018 5:13:56 PM +00:00`

2. Service Bus: `Trigger Details: MessageId: f287f2c23002469a94c4fbdcfe569129, DeliveryCount: 1, EnqueuedTime: 11/7/2018 5:15:31 PM, LockedUntil: 11/7/2018 5:16:01 PM`

3. These properties also exist in AppInsights so users would be able to filter by them.

![appinsights](https://user-images.githubusercontent.com/42051041/48148353-64c96400-e26e-11e8-914c-cdf3c1b7dcde.png)
