### ISSUE TITLE
Running Azure CLI in Azure Functions

### ISSUE THREAD

**Issue by amang2205** [Azure/azure-functions-host#3087]
Hi,
I want to run a PowerShell-based Azure Function based on an HTTP trigger. At this point, whether PowerShell is experimental or not is out of the scope of this issue - I could simply work around it and have a C# function triggered which invokes the execution of the PowerShell script and also not use shell execution when I invoke the script so that the Standard Output and Standard Error can afterwards be queries and written as traces to Application Insights.
Anyway, the problem is as follow: how do I get prerequisites for my runtime installed? Specifically, how do I get Azure CLI installed on the runtime?

**Comment by amang2205** [comment]
I've posted this issue on the Azure/Azure-Functions repo too, since that is probably more appropriate.

**Comment by fabiocav** [comment]
There isn't an option to install those pre-requesites on the worker today, but we are actively on PowerShell support and features that will address this requirement as well. 

You can follow the PowerShell development and get more information on how to try it here: https://github.com/azure/azure-functions-powershell-worker


/cc @pragnagopa
