### ISSUE TITLE
Provide error messages when the storage account is deleted

### ISSUE THREAD

**Issue by alexkarcher-msft** [Azure/azure-functions-host#3088]
The portal UI, and entire function runtime breaks when the storage account connected to a Function is deleted, or the connection string is overwritten by a deployment or site swap.
Please add a big error message in the portal stating that the function app is inoperable because it has no storage.

**Comment by jeffhollan** [comment]
Related to this: https://github.com/Azure/azure-functions-host/issues/3032

**Comment by alexkarcher-msft** [comment]
I'm not sure which you're referring to, but this is the blob storage account created alongside a function app. The account that customers can get into a bad state if they delete or roll their connection strings.

There is currently a portal error message, but it only accounts for a narrow set of possible broken storage states and causes false positives any time the run-time is down, or suffering a 30+ second cold start.

**Comment by jeffhollan** [comment]
Assigning as a P1 under the assumption that it's the `AzureWebJobsStorage` OR the `WEBSITE_FILECONNECTIONSTRING` (which sounds like it may have been addressed)

**Comment by alexkarcher-msft** [comment]
This is actually already done :)

https://docs.microsoft.com/en-us/azure/azure-functions/functions-recover-storage-account
