### ISSUE TITLE
Provide clear feedback when platform limits cause failed executions

### ISSUE THREAD

**Issue by alexkarcher-msft** [Azure/azure-functions-host#3089]
When the function hits a platform limit, like memory, TCP connections, or time limit, that execution should have an extremely clear error message, and the entire function should persist some state in the portal that makes it very clear that the user should change their code to ensure this never happens again. 
Most of the issues related to this are due to the customer not knowing why executions were failing.
I suggest popping an Ibiza notification `“Function [name] recently had failed executions due to [platform limit]”`
Then, in the portal, present some sort of warning icon on the particular function that was generating the error, as if it was a code compilation error that should be fixed before the function will work properly.

**Comment by fabiocav** [comment]
This is already surfaced as a host level error. Associating the message/limit to a function is not feasible.

Are the current error messages not sufficient? Do we need to open something to just track improvements to host level errors?

**Comment by alexkarcher-msft** [comment]
As a user, I'd expect any executions in flight to have some error message associated with that individual execution if they are terminated due to platform limits. Without something prompting customers to look up at platform logs they tend to view Functions as independent units, and we'll need to prompt them to look higher up.

Also, I'd love to know what else is logged only at the host level? We currently don't have any built in view to see host logs out of App Insights in the Functions portal, and that would be a logical place to direct users with a per-execution error message.

**Comment by fabiocav** [comment]
This could be confusing as it could be interpreted as the function causing the issue, when in reality, there's no mechanism that allows us to detect that today. This is truly a host level issue that needs to be properly surfaced. Individual function invocations will be reported as failures, and we could add a reason, popping the notification for every function in a function app for a host issue would be problematic.

The other issue you bring up (and I touch on above) is host log/error visibility. That's something we've discussed quite a bit in the past and haven't properly addressed.

**Comment by fabiocav** [comment]
@alexkarcher-msft following up on this as I see the update with the label after my last comment. As I mentioned, associating those issues with a function can't be done accurately (the most we'd be able to do with the current design is indicate which functions were in flight when the issue occurred, but that may be a bit misleading and give the impression those functions caused the issue, if we're not careful about how this is communicated), but we should discuss the appropriate design (which will likely involve portal enhancements) to bring this information to the surface.

**Comment by alexkarcher-msft** [comment]
Looping in @jeffhollan to drive this further. I'd like to keep pursuing this, as platform limits is persistently one of our top supportability hits. It will probably take a decent amount of work, but these are hit often enough that we need to be giving customers the right signals back.

**Comment by fabiocav** [comment]
Moving this to triaged, pending discussion/planning with @jeffhollan

**Comment by kulkarnisonia16** [comment]
@jeffhollan - anything you'd like to add here?
