### ISSUE TITLE
Provide notifications when an app service plan Function needs to scale out

### ISSUE THREAD

**Issue by alexkarcher-msft** [Azure/azure-functions-host#3091]
We should pop Azure notifications if an App Service plan is at high CPU or memory for a prolonged amount of time. These users just needed to scale up or out their App Service plan.

**Comment by alexkarcher-msft** [comment]
This has potentially already been implemented in the form of an email notification. I'm investigating.

**Comment by fabiocav** [comment]
@alexkarcher-msft did you find any information on this? Is this still relevant?

**Comment by kulkarnisonia16** [comment]
Keeping this open for investigation on right approach - follow up with the Antares team.

**Comment by kulkarnisonia16** [comment]
@alexkarcher-msft - any updates here that you can share?

**Comment by alexkarcher-msft** [comment]
There are automated emails that alert customers to plans that are low on CPU / memory and need to be scaled. Those notifications were broken when this issue was opened, but have since been fixed.

If we see recent support tickets related to this it's worth double checking our "azure advisor" notifications.
