### ISSUE TITLE
[V2][QueueTrigger] Remove references to getting data through bindingData in docs/samples

### ISSUE THREAD

**Issue by Rickaro** [Azure/azure-functions-host#3105]
I've discovered, that json message passed to Queue trigger function via bindingData parameter converted to camelCase, but passed as argument to function - not.

Is it correct behavior? If so - I think documentation need to be updated.

#### Investigative information
- Timestamp:2018-07-05T05:45:37.973
- Function App version (2.0-beta):
- Invocation ID:eac35ff1-cd76-46b3-963d-b8d9a3c6351c
- Region:West Europe

Same function on local Azure Functions Core Tools (220.0.0-beta.0), working properly

#### Repro steps

1. create simple queue triggered function
**function.json**
```
{
   "bindings": [
     {
       "name": "queueData",
       "type": "queueTrigger",
       "direction": "in",
       "queueName": "some-test-queue"
     }
   ]
 }
```
**index.js**
``` 
module.exports = async function (context, workItem) {
    context.log(context.bindingData.queueTrigger);
    context.log(workItem);
  }
```
2. Place message to queue
` { "Foo": { "BAR": "10" } }`

#### Expected behavior
Messages in log
```
[Information] { Foo: { BAR: '10' } }
[Information] { Foo: { BAR: '10' } }`
```
Both lines are same

#### Actual behavior
Message in log
```
[Information] { foo: { bAR: '10' } }
[Information] { Foo: { BAR: '10' } }
```

First object in camelCase

There are two example how to process message from queue trigger via bindingData and parameter to function call, without information about differences
1) [Azure documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue#trigger---javascript-example)
2)  [github samples](https://github.com/Azure/azure-functions-host/blob/master/sample/QueueTrigger/index.js)

**Comment by mhoeger** [comment]
Thanks for this, that's a great point. @paulbatum / @mathewc.

When we camelCase bindingData, we do this without knowing if the param names come from our code or the user's data. So we end up altering the user's data. Do you know why we have two ways of accessing data? Can we keep bindingData as pure metadata?

**Comment by mhoeger** [comment]
That sounds good! Re-titling

**Comment by mhoeger** [comment]
Closing to track change here: https://github.com/Azure/azure-sdk-for-net/issues/32638

**Comment by fabiocav** [comment]
@mhoeger is there a documentation issue to track the suggested improvement as well?

**Comment by mhoeger** [comment]
Doc change here: https://github.com/MicrosoftDocs/azure-docs-pr/pull/70178
