### ISSUE TITLE
Malformed JSON returns wrong HTTP Status code

### ISSUE THREAD

**Issue by Clockwork-Muse** [Azure/azure-functions-host#3106]
This is a followup to #2490, because while the timeout error no longer occurs due to malformed JSON input, I do not feel the correct HTTP Status code is being returned. 

#### Repro steps

Provide the steps required to reproduce the problem:

 1. Create a function app (in Java, but should affect all)
 1. Create an HTTP Trigger function
 1. Invoke it using a malformed JSON: { "hello": "world", or missing a required field, with the proper content-type header.

#### Expected behavior

The function returns an HTTP Status of 400

#### Actual behavior

The function returns an HTTP Status of 500

#### Known workarounds

None - this is handled before the function itself is actually called, so no way for developers to change this behavior.

#### Related information 
The problem is that an HTTP Status in the 5XX range means "the server did something wrong, the client was fine", which, if the runner is receiving malformed JSON, is demonstrably **NOT** the case.  The proper HTTP Status should be something in the 4XX range, probably 400 itself.  

For that matter, even just a JSON payload missing a required field results in an HTTP Status of 500.  This again is clearly a client issue (HTTP Status 400) - the request is not, and will not be, valid, and the server isn't in need of "fixing".  It makes troubleshooting difficult because it makes it appear that the server is at fault, when it is not, and with an error that may sometimes reinforce that impression - `"Cannot locate the method signature with the given input"`.

**Comment by mhoeger** [comment]
Unable to repro with JavaScript. I don't believe this is an issue with the functions host, if it is still reproing.

**Comment by Clockwork-Muse** [comment]
Still repros, but looks like it might be specific to the Java runner, yes.  Going back to bugging them.
