### ISSUE TITLE
Consider adjusting Performance defaults

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#311]
Currently we run with the WebJobs SDK defaults for Queue processing BatchSize/NewBatchThreshold, etc. We know that to achieve maximum throughput on a single instance, these values have to be adjusted. We should therefore set them up like this out of the box.

While cranking these up does increase maximum throughput, we need to consider whether there any potential drawbacks of this before we do so (e.g. pressure on queue as the instance count is dialed way up).

E.g two important ones are:

**batchSize**: This is the number of messages we retrieve at a time from the queue. The default is 16, max (dictated by Azure Queues) is 32.

**newBatchThreshold** : This is the threshold number at which we'll fetch another batch of messages. This one is important - it directly controls the level of parallelism you'll achieve. It defaults to half the batch size, meaning if we fetch a batch of 16 messages, we'll process all those in parallel and we won't fetch another batch until the outstanding invocation count drops below 8. So if you increase this to say 100 along with setting batchSize to 32, you'll be allowing 100 + 32 messages to be processed in parallel.

**Comment by pchowdhry** [comment]
Hi Guys, we are currently testing the suitability of Azure functions for one of our processing jobs.  We'd like to ensure that only a single message is processed at a time per function(consumption unit), but with 100s of messages processed in parallel. I'm a little confused as to how we would use the above mentioned parameters to ensure this sort of scalability. Any suggestions?

Thanks

-pc

**Comment by christopheranderson** [comment]
Should discuss this in relation to perf and user experience for rc.

**Comment by fabiocav** [comment]
Closing this issue as it is stale and has not come up since opened
