### ISSUE TITLE
[v2] code query string is printed to the logs

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#3110]
Enable verbose logging:

* set `consoleLoggingMode = always`
* in `host.json` set 

```json
{
  "logger": {
    "categoryFilter": {
      "defaultLevel": "Trace",
      "categoryLevels": {
        "Host": "Trace",
        "Function": "Trace",
        "Host.Aggregator": "Trace"
      }
    }
  }
}
```

Send `GET https://app.azurewebsites.net/api/function?code=.....................`

the code is logged in clear text in the log.

**Comment by brettsam** [comment]
This was fixed in https://github.com/Azure/azure-functions-host/pull/3412, where we now filter out the default ASP.NET core logs.
