### ISSUE TITLE
App Insights not recording response code when used with Functions V2

### ISSUE THREAD

**Issue by HShather** [Azure/azure-functions-host#3114]
I have a javascript http trigger function running on runtime 2.0.11857-alpha with standard app insights integration
Http response code is not being captured by app insights, it is always zero

![image](https://user-images.githubusercontent.com/38656315/42446949-631a7fd6-8378-11e8-9a43-5b713eca7881.png)

#### Investigative information

- Timestamp: 7/9/2018, 10:56:18 AM UTC
- Function App version (1.0 or 2.0-beta): 2.0.11857-alpha
- Function App name: hamada2.azurewebsites.net
- Function name: HttpTriggerJS1
- Invocation ID: 2da6af3a-37cb-4ba9-9003-4bfc5efe5316
- Region: Central US

#### Repro steps

Create a function app and a js http trigger
Upgrade to 2.0.11857-alpha  and node 8.9.4
Create app insights instance and integrate to function app
Call the js http trigger
Observe response code is logged as zero

#### Expected behavior

Response code should be logged in app insights

#### Actual behavior

Response code is always logged as zero

**Comment by HShather** [comment]
Any update on this? Still an issue with 2.0.11933.0

**Comment by fabiocav** [comment]
Indeed, this is about the same issue tracked by https://github.com/Azure/azure-functions-host/issues/2447. Please follow that issue for updates.
