### ISSUE TITLE
Populate FunctionName and InvocationId for system logs coming from language workers

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#3117]
Standard IO and Error logs coming from language worker processes at
https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/LanguageWorkerChannel.cs#L346

https://github.com/Azure/azure-functions-host/blob/58291067a499f66d1cb91f2500837cb646881002/src/WebJobs.Script/Rpc/LanguageWorkerChannel.cs#L354

 do not have FunctionName and FunctionInvocationId fields populated.  
Worker process Logger needs to be fixed to include all the fields

**Comment by pragnagopa** [comment]
System Logs from LanguageWorkers are written using console.log and are captured in the functions runtime via stderr and stdout streams. This needs to be improved by specifying a SystemLog message similar to [RpcLog](https://github.com/Azure/azure-functions-language-worker-protobuf/blob/dev/src/proto/FunctionRpc.proto#L298) in the proto file.  This will allow us to capture more details on the system logs coming from language workers

**Comment by pragnagopa** [comment]
@paulbatum @mathewc  FYI this is for system logs

**Comment by pragnagopa** [comment]
@yojagad - Will you be able to look into this?

**Comment by yojagad** [comment]
Sure thing!

**Comment by fabiocav** [comment]
@pragnagopa / @yojagad moving this back to triage so we can close this milestone. Let's discuss this item today.

**Comment by fabiocav** [comment]
Closing as resolved.
