### ISSUE TITLE
Old code still running intermittently after a deployment

### ISSUE THREAD

**Issue by simonness** [Azure/azure-functions-host#3119]
#### Investigative information

Please provide the following:

- Timestamp: 2018-07-09T20:05:15.279 UTC
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: f4ed0d7c-2c5f-436d-9178-fec340c02e54
- Region: West Europe

#### Repro steps

Perform a deployment.  However this is the first time I've noticed this issue after over a hundred deployments.

#### Expected behavior

New code always runs.

#### Actual behavior

I performed a deployment at 09-Jul-18 19:37 UTC replacing version 1.0.195 of my service with 1.0.196.  I noticed up to an hour afterwards 1.0.195 was intermittently running as it was causing issues for a dependant service that relied on changes made in 1.0.196.

#### Known workarounds

I resolved the issue by restarting the Function App Service in question manually via the portal.  I assume this killed any 1.0.195 instances / containers.

#### Related information 

The deployment was performed using a VSTS release pipeline.

I print the dll assembly version number in trace logs sent to Application Insights and can see 1.0.195 traces after 1.0.196 traces.

**Comment by fabiocav** [comment]
@simonness since this is an old issue (apologies for the lack of response here), I wanted to follow up to see if this is still an issue you're experiencing. Do you still have this problem?

**Comment by simonness** [comment]
Hi @fabiocav I think this one can be closed as the main discussion around the issue seems to be on #2636, it's the same symptoms as @ghills describes on [20 Nov 2018](https://github.com/Azure/azure-functions-host/issues/2636#issuecomment-440125335).

I haven't seen the issue since, although I haven't been systematically testing for its occurrence.  If the issue still exists I'm sure it could be reproduced with Azure DevOps Build and Release pipelines that continually update a version number, deploys the function and calls a http endpoint to check that version number is as expected.  I suspect the function may also have to be under some load, perhaps even something as simple as a periodic http health check, for the issue to occur.
