### ISSUE TITLE
I wanted to change "Connection Security" of iot-hub and iot-device (Connection Security: Ensuring all data transmitted between the IoT device and IoT Hub is confidential and tamper-proof),using wolfssl certificates.

### ISSUE THREAD

**Issue by PRAVEENBADIGER** [Azure/azure-functions-host#3130]
Hi Team,

I wanted to change "Connection Security" of iot-hub and iot-device (Connection Security: Ensuring all data transmitted between the IoT device and IoT Hub is confidential and tamper-proof),using wolfssl certificates. 

Questions:

1) Is it possible to change Connection Security Certificate between IoT hub and devices connection ?

2) Azure providing Connection Security by " certs " certificates as default,is it possible to change these certificates based on own requirements (ex : wolfssl certificates )  ?

3) If its possible can you explain the steps .how certificates can be added on HUB and DEVICE end to make it work ?

Thanks in advance ......

**Comment by fabiocav** [comment]
@PRAVEENBADIGER can you please move this question to the MSDN forums for IoT Hub?
