### ISSUE TITLE
Azure Functions don't allow Azure Storage v9+ NuGet packages 

### ISSUE THREAD

**Issue by aaronpowell** [Azure/azure-functions-host#3144]
_Moving [this conversation](https://twitter.com/slace/status/1016848471737810944?s=17) from Twitter to GitHub._

I have an Azure Functions v2, code [here](https://github.com/dddsydney/dddapi/tree/functions-v2) (and [this](https://github.com/dddsydney/dddapi/tree/ae7ee6989a36b336d36171a6eab5dc4b3d058ad0) is the latest commit at time of writing), that I want to use a NuGet package, `FSharp.Azure.Storage@3.0.0` which has a dependency on `WindowsAzure.Storage@9.0.0`.

You can run the code by pulling from GitHub, doing a `dotnet build` and `dotnet publish`, running `npm install` (I use a local dependency of the Azure Functions cli) and then running it. There is a VSCode task `run func` that does it all.

When running the Azure Functions cli to start the following errors appear:

![image](https://user-images.githubusercontent.com/434140/42666161-bf9f208e-8686-11e8-92b0-98ae25c5d484.png)

Azure Functions version:

> Azure Functions Core Tools (2.0.1-beta.31)
> Function Runtime Version: 2.0.11888.0

`dotnet --version`:

> 2.1.400-preview-009063

OS: Windows 10 (Fast Ring)

My investigation led me to find that the error message comes from [this line in the WebJobs SDK](https://github.com/Azure/azure-webjobs-sdk/blob/73d07a8953d09b698f2494d3b14549cb53260946/src/Microsoft.Azure.WebJobs.Extensions.Storage/Tables/TableAttributeBindingProvider.cs#L60) and the work in [this issue](https://github.com/Azure/azure-webjobs-sdk/issues/1683) I think will address it, or at least make it easier to address. I think that the fundamental problem is that [this logic](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.Storage/Tables/TableExtension.cs#L35-L63) doesn't work properly (I was going to have a crack at debugging it but with the rework to pull Storage into an extension DLL made it a bit hard and I gave up 😝).

Happy to provide whatever additional info is needed as this is blocking me from moving off v1 functions.

**Comment by kashimiz** [comment]
Thanks for submitting this issue! Users being limited to referencing the same version of the AzureStorage SDK that the Functions runtime uses is a known issue and one that's being actively worked on as part of a larger restructuring. The changes have been merged into the WebJobs SDK, as Fabio's comment in [this issue](https://github.com/Azure/azure-webjobs-sdk/issues/1683) notes, but they haven't yet made it into a release of the Functions runtime. This is part of the work that will be completed as we move towards the Functions v2 GA release.

**Comment by aaronpowell** [comment]
It's been a couple of months, I just wanted to look at what the status of this now is, is it any closer to having the extraction of the Storage dependencies into extensions and freeing up a function to use a newer version of the Azure Storage API's?

**Comment by JohnReeson** [comment]
@aaronpowell  It has been achieved since [runtime 2.0.12050-alpha releases](https://github.com/Azure/app-service-announcements/issues/129), latest runtime is 2.0.12115.

**Comment by maiqbal11** [comment]
The current storage extension in v2 is utilizing WindowsAzure.Storage 9.3.1. There is a known issue where users are unable to specify versions higher than this and is being tracked here: https://github.com/Azure/azure-webjobs-sdk/issues/1942. Closing this issue in favor of the one currently tracking.
