### ISSUE TITLE
Functions invoked randomly between 1 AM and 3 AM UTC.

### ISSUE THREAD

**Issue by mithunshanbhag** [Azure/azure-functions-host#3154]
I have a couple of time-triggered functions in a function app (consumption plan). CRON for these is set for hourly triggering ("0 0 */1 * * *"). They generally get triggered as intended. However during 1 AM to 3 AM UTC everyday, I see some bizarre invocations (screenshot below). 

![image](https://user-images.githubusercontent.com/2327905/42869119-d431ed2e-8a91-11e8-9b9e-47b9b3ed84ee.png)

#### Investigative information

Please provide the following:

- Timestamp: 2018-07-18T02:59:12.3237012+00:00
- Function App version (1.0 or 2.0-beta): 2.0.11888.0 (beta)
- Function App name: Please see invocation ID below.
- Function name(s) (as appropriate): Please see invocation ID below.
- Invocation ID: 24387574-d175-4711-bf14-b37487dedcd5
- Region: South India

#### Repro steps

1. CRON is set for hourly triggering ("0 0 */1 * * *").
2. Deploy function app directly from visual studio using the publish step (this uses msdeploy I believe)

#### Expected behavior

The functions should trigger every hour (on the hour). 

#### Actual behavior

The functions trigger hourly as expected for most parts of the day. However during the 1 AM to 3 AM window (all UTC time) we see some bizarre issues:
  - not triggered at 1 AM UTC
  - not triggered at 2 AM UTC
  - triggered twice around 3 AM UTC (2:59 AM and 3 AM)

#### Known workarounds

None that I know of.

#### Related information 

* C# library (authored and deployed from visual studio 2017 community edition)
* Bindings used: 
![image](https://user-images.githubusercontent.com/2327905/42870147-a773b88c-8a94-11e8-94b2-7ec6cbe8b4c4.png)

* I have disabled the built-in logging (deleted the ```AzureWebJobsDashboard``` app setting) and rely solely on app-insights logging (via the ```APPINSIGHTS_INSTRUMENTATIONKEY``` app setting). 
* I do NOT use the ```WEBSITE_TIME_ZONE``` app setting.
* I've disabled app-insights sampling via host.json. So this wouldn't be a case of missing AI logs
![image](https://user-images.githubusercontent.com/2327905/42871429-0175cf0c-8a98-11e8-97f8-4f9996482e2f.png)

Please let me know if there is any additional information that I can provide to help with the investigation.

**Comment by mhoeger** [comment]
Hi @mithunshanbhag - sorry about the lack of response on this issue. We've made a lot of changes to V2 functions while moving from preview => GA. Are you still seeing issues of this class? If so, are the details still relevant for investigation?

**Comment by mithunshanbhag** [comment]
Closing this issue as it no longer repro'es for me.
