### ISSUE TITLE
System.Runtime.Caching is not supported on this platform

### ISSUE THREAD

**Issue by Badabum** [Azure/azure-functions-host#3155]
Faced with the issue while using the `MemoryCache` from `System.Runtime.Cache` in function with service bus trigger. When running locally and in Azure I always get an Exception in runtime `System.Runtime.Caching is not supported on this platform`. Is there any workaround for that?

#### Investigative information

- Timestamp: 7/18/2018
- Function App version: 2.0-beta

**Comment by iBalag** [comment]
I have faced with the same issue. Any comments about it from develop team?

**Comment by Badabum** [comment]
> I have faced with the same issue. Any comments about it from develop team?

You should use [this package](https://www.nuget.org/packages/Microsoft.Extensions.Caching.Memory/) instead.

**Comment by Badabum** [comment]
I'm closing this issue since there is a dedicated package for memory cache for .NET Core
