### ISSUE TITLE
Messages never move to poison queue incase of timeout exceptions

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#3157]
#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0-beta): 1.0.11913.0 and V2 Beta
- Function App name: pgopafunctestprod
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

#### Repro steps

Update functionTimeout in host.json to 30secs - to repro issue faster than the default timeout of 5 minutes

```
using System;

public static void Run(string myQueueItem, TraceWriter log)
{
    log.Info($"C# Queue trigger function processed: {myQueueItem}");
   // Intentionally sleep for 40 secs to trigger timeout exception
    System.Threading.Thread.Sleep( 40000);
   log.Info($"C# Queue trigger done function processed: {myQueueItem}");
    
}

```

#### Expected behavior

Queue message moves to poison-queue after 5 retries

#### Actual behavior

ScriptHost keeps restarting and continues to retry

#### Known workarounds

none

#### Related information 

Provide any related information 

Kusto logs:

FunctionsLogs
| where PreciseTimeStamp >= datetime(2018-07-17 15:15:00)
| where AppName == "pgopafunctestprod" 
| project PreciseTimeStamp ,  AppName , FunctionName , Details , Summary , HostVersion, HostInstanceId  , Source, FunctionInvocationId

**Comment by pragnagopa** [comment]
This came up in two CRI investigations.

**Comment by pragnagopa** [comment]
Logging dequeueCount shows that it does go up:
```
2018-07-18T21:24:05.445 [Info] C# Queue trigger function processed: {"id" : 90}
queueTrigger={"id" : 90}
expirationTime=7/24/2018 10:24:26 PM +00:00
insertionTime=7/17/2018 10:24:26 PM +00:00
nextVisibleTime=7/18/2018 9:34:04 PM +00:00
id=2c44b8be-1767-4f1c-9d54-8f43a3fab2d0
popReceipt=AgAAAAMAAAAAAAAAamkyDd8e1AE=
dequeueCount=133
2018-07-18T21:24:35.458 [Error] Function completed (Failure, Id=5eae84b1-efdc-45ed-96dc-d0b3477f79ac, Duration=30452ms)
2018-07-18T21:24:35.521 [Error] Microsoft.Azure.WebJobs.Host: Timeout value of 00:00:30 was exceeded by function: Functions.QueueTriggerCSharp1.
```
In this case, runtime has been retrying over and over

**Comment by pragnagopa** [comment]
Note from @mathewc 
we only validate the dequeue count AFTER invoking the function (code [here](https://github.com/Azure/azure-webjobs-sdk/blob/v2.x/src/Microsoft.Azure.WebJobs.Host/Queues/QueueProcessor.cs#L118).

Timeouts bring the host down before that poison queue code is run, resulting in trying over and over. This would also happen in a classic WebJobs SDK WebJob if TimeoutAttribute is used.

To address, we might also do the dequeue count check BEFORE invoking the function.

**Comment by mathewc** [comment]
I'll point out that this issue actually belongs in the SDK repo.

I see now that this issue (and fix) was actually pointed out in an old related issue [here](https://github.com/Azure/azure-webjobs-sdk/issues/1045). The following text is from one of the comments on that issue:

_The second and very similar problem is when you have an OutOfMemory or "Never finished" job.
The solution could be very easy to implement (for us, users, or better for the SDK it self): the dequeue count have to be checked even before pass it to the job (before or in BeginProcessingMessageAsync default impl)._

We should fix this.

**Comment by pragnagopa** [comment]
This issue was moved to Azure/azure-webjobs-sdk#1809
