### ISSUE TITLE
Frequent error in EventGridClient.PublishEventsAsync(). Method is part of Microsoft.Azure.EventGrid.EventGridClientExtensions and used in my Azure Function

### ISSUE THREAD

**Issue by S-Gurpreet** [Azure/azure-functions-host#3160]
I get this issue frequently (say after every 10-20 calls) on my local as well as azure cloud environment. My azure function is calling EventGridClient.PublishEventsAsync() method to publish events to event grid. All post calls work fine but it suddenly starts failing after every 10-20 calls. It is not related to a specific function but a general issue I think.

**Investigative information**

- Timestamp: Thu, 19 Jul 2018 16:06:00 IST
- Function App version: 1.0
- Function App name: any function app

**Error details from local environment (Detailed Stacktrace received while debugging is given at end):**
 Function completed (Failure, Id=0b2e9641-1d14-4969-aa6e-3cb3fc0ecf0a, Duration=100136ms)
 A ScriptHost error has occurred
 mscorlib: A task was canceled.
 Executed 'FunctionName' (Failed, Id=0b2e9641-1d14-4969-aa6e-3cb3fc0ecf0a)
 mscorlib: A task was canceled.
   Function had errors. See Azure WebJobs SDK dashboard for details. Instance ID is '0b2e9641-1d14-4969-aa6e-3cb3fc0ecf0a'
 mscorlib: A task was canceled.

**Repro steps**
1. Create any event grid topic
2. In Azure Function, post to event grid using HttpClient or EventGridEvent.PublishEventsAsync()
3. Execute step 2 multiple times at varying intervals between 1 to 5 seconds (I executed via fiddler, posted 5 events in burst and then 5 more at interval of 3 seconds. Repeated this 5 to 10 times and got around 5 errors)

**Expected behavior**
Event should be pushed to event grid.

**Actual behavior**
Event post operations failing randomly again and again after successfully posting, lets say, around 10 to 20 events and throwing following errors:
**_Error as shown in Azure Cli (Detailed Stacktrace received while debugging is given at end)_**
 Function completed (Failure, Id=0b2e9641-1d14-4969-aa6e-3cb3fc0ecf0a, Duration=100136ms)
 A ScriptHost error has occurred
 mscorlib: A task was canceled.
 Executed 'FunctionName' (Failed, Id=0b2e9641-1d14-4969-aa6e-3cb3fc0ecf0a)
 mscorlib: A task was canceled.
   Function had errors. See Azure WebJobs SDK dashboard for details. Instance ID is '0b2e9641-1d14-4969-aa6e-3cb3fc0ecf0a'
 mscorlib: A task was canceled.

**Known workarounds**
Tried HttpClient as well as EventGridClient using static as well as local objects. Getting error in all scenarios.

**Related information**

Programming language used: C#
Links to source: Used sample code given here: [https://docs.microsoft.com/en-us/dotnet/api/overview/azure/eventgrid?view=azure-dotnet](url)

<details>
<summary>Source</summary>

```csharp
string topicHostname = new Uri(eventGridEndpoint).Host;
TopicCredentials topicCredentials = new TopicCredentials(eventGridKey);
using (EventGridClient eventGridClient = new EventGridClient(topicCredentials))
{
      List<EventGridEvent> customEventGridEvents = new List<EventGridEvent>() { this };
      await eventGridClient.PublishEventsAsync(topicHostname, customEventGridEvents).ConfigureAwait(false);
}
```
</details>

**_Error as shown in Azure Stacktrace_**
"Message":"Processing of the request was cancelled.","ExceptionMessage":"A task was canceled.","ExceptionType":"System.Threading.Tasks.TaskCanceledException","StackTrace":"   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.Azure.EventGrid.EventGridClient.<PublishEventsWithHttpMessagesAsync>d__38.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.EventGrid.EventGridClientExtensions.<PublishEventsAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\r\n   at Project.EventPublisher.Core.MyProjectEventGridEvent.<PublishAsync>d__8.MoveNext() in C:\\XXX\\Projects\\MyProject\\Source Code\\Development\\Project\\Project.EventPublisher\\Project.EventPublisher.Core\\MyProjectEventGridEvent.cs:line 57\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\r\n   at Project.EventPublisher.Api.MyProjectEvents.<Run>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.<InvokeAsync>d__9.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<InvokeAsync>d__24.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__23.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__22.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__16.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__16.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.Azure.WebJobs.Host.Executors.ExceptionDispatchInfoDelayedException.Throw()\r\n   at Microsoft.Azure.WebJobs.JobHost.<CallAsync>d__36.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.Azure.WebJobs.Script.ScriptHost.<CallAsync>d__92.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostManager.<HandleRequestAsync>d__32.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Azure.WebJobs.Script.Host.FunctionRequestInvoker.<ProcessRequestAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.<>c__DisplayClass3_0.<<ExecuteAsync>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Azure.WebJobs.Extensions.Http.HttpRequestManager.<ProcessRequestAsync>d__8.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.<ExecuteAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Azure.WebJobs.Script.WebHost.Handlers.WebScriptHostHandler.<SendAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Azure.WebJobs.Script.WebHost.Handlers.SystemTraceHandler.<SendAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.SelfHost.HttpSelfHostServer.<SendAsync>d__5.MoveNext()"

**Comment by mevansdev** [comment]
We are having the same issue in our Azure environment as well, intermittent issues that result in the publish method hanging and then timing out.  The only difference is that we are calling this from within a web app rather than a function.  We are using;

<PackageReference Include="Microsoft.Azure.EventGrid" Version="1.2.0" />

Stack trace;

{System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass11_0.<<SendAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.EventGrid.EventGridClient.<PublishEventsWithHttpMessagesAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.EventGrid.EventGridClientExtensions.<PublishEventsAsync>d__0.MoveNext()

...

System.Exception {System.Threading.Tasks.TaskCanceledException}

**Comment by fabiocav** [comment]
This seems to be an issue with the EventGrid client (also repros outside of Azure Functions). Could you please open an issue for investigation here? https://github.com/Azure/azure-sdk-for-net/issues

Thanks!

**Comment by kalyanaj** [comment]
I have added some guidance related to this issue at: https://github.com/Azure/azure-sdk-for-net/issues/4575#issuecomment-536108307
