### ISSUE TITLE
Allow Simultaneously Language Runtimes 

### ISSUE THREAD

**Issue by gorillapower** [Azure/azure-functions-host#3161]
We want to allow users to create their own NodeJS functions using a code editor. To execute the business logic of our app, we require some pre and post processing of the users code. Our idea was to use Durable functions to create a single Function App to do this.

Broadly, the execution would look like this
1. C# Orchestration Starter (Queue Message)
2. C# Orchestration Client 
3. NodeJS Activity Function (Custom user function)
4. C# Activity Function (Does post processing)

Using this approach, it allows us to leverage our existing C# libraries and skill set to build a 'wrapper' around the users code snippet.

So far this has worked for us, but we are receiving this warning `your worker runtime is not set. As of 2.0.1-beta.26 a worker runtime setting is required.` 

1. Would it be possible to remove the restriction of a single runtime manually perhaps? AFAIK, the function host runtime uses RPC (as of V2) to offload any javascript function executions. I think this is why the above mentioned flow still works, how is this changing going forward?

2. Does this mean that going forward, you will only be able to create functions in one language? For instance, currently in the Portal you can create functions across multiple languages.

Code Illustration
```
[FunctionName("TestRunner")]
public static async Task<List<Dictionary<string,string>>> TestRunnerFunc(
   [OrchestrationTrigger] DurableOrchestrationContext context,
   Microsoft.Azure.WebJobs.ExecutionContext ctx,
   TraceWriter log)
{
	object data = context.GetInput<List<Dictionary<string, string>>>();
	try
	{
		string funcLanguage = Environment.GetEnvironmentVariable("userFunctionLanguage");
		if (funcLanguage == "javascript")
		{
			data = JsonConvert.SerializeObject(data);
		}

                //This is NodeJS function!
		List<Dictionary<string, string>> outData =
					await context.CallActivityAsync<List<Dictionary<string, string>>>("UserFunction", data);

		return outData;
	}
	catch (Exception ex)
	{
		throw;
	}
}
```

**Comment by pragnagopa** [comment]
@gorillapower - Restricting to single language is not enforced in the functions runtime yet. If update this issue if it changes.  JS functions will continue to run via grpc. No changes there

@kashimiz - Is this scenario possible across multiple function apps?

**Comment by gorillapower** [comment]
@pragnagopa, it seems the restrictions is now being enforced in the latest version of the runtime. Is there a work around for this? It seems we can 'pin' a version, but it looks like its only possible for 30 days. Can you confirm this? I am referring to the service announcement here - https://github.com/Azure/app-service-announcements/issues/129

**Comment by pragnagopa** [comment]
@gorillapower - Yes. Starting with functions runtime 2.0.12050-alpha we will start enforcing single language per function app. Moving this issue to https://github.com/Azure/azure-functions-durable-extension as durable functions need to support invoking orchestrations across function apps.

**Comment by pragnagopa** [comment]
This issue was moved to Azure/azure-functions-durable-extension#427
