### ISSUE TITLE
SecurityTrim function - Use SaS for QueueTrigger

### ISSUE THREAD

**Issue by texascanadasean** [Azure/azure-functions-host#3167]
I have a c# function that uses a Queue to trigger invocation.  I am using SAS to access other storage resources, but I have to have the accountkey as part of the connectingstring for the queue trigger to work.  

Is there a way to store only the SAS signature for the trigger?  I have not see a way to do this currently.

**Comment by fabiocav** [comment]
This is not currently supported, but we've opened https://github.com/Azure/azure-sdk-for-net/issues/32639 to track as this is a commonly requested feature.
