### ISSUE TITLE
Log a precise timestamp to Application Insights

### ISSUE THREAD

**Issue by alexkarcher-msft** [Azure/azure-functions-host#3175]
The timestamp emitted to Application Insights is truncated at the millisecond level, we should attach a separate precise timestamp to all logs to enable accurate sorting of logs by timestamp. This work will be attached to UI work to update our queries to sort the monitoring page by this new precise timestamp.

**Comment by alexkarcher-msft** [comment]
This looks to be very close to deployed on the App Insights side. Hold off for at least a week. I should be able to close this on Wednesday of next week.

**Comment by alexkarcher-msft** [comment]
Hi @andreesteve , 

When App Insights updated their side we realized there was an additional bug in the Functions runtime that was causing us to log an imprecise timestamp. We've been working on a solution, but it's a somewhat involved implementation to get this right. It's at least 2 months out at the moment, to give you some sense of timing.

Hopefully this clears up the confusing message from July when I had thought we were close to shipping this!

**Comment by bluephoton** [comment]
Any updates on this guys?

**Comment by alexkarcher-msft** [comment]
We have no immediate plans to do this. I'm closing the issue, as we've resolved the ordering issue in app insights logs. If you need precise timing I'd recommend emitting it as a custom metric inside your running application.
