### ISSUE TITLE
Any gains from fronting function host with nginx?

### ISSUE THREAD

**Issue by snobu** [Azure/azure-functions-host#3184]
Up until very recently `func host start` (or `dotnet Microsoft.Azure.WebJobs.Script.WebHost.dll`) listened on localhost only so the natural approach was to reverse into it with nginx.

Is this still the advised way to run it in PROD now that it binds on `0.0.0.0` by default? Any gains from nginx over the naked built-in Kestrel? Not talking features, just basics, for example would nginx do a better job if the load goes up? Let's assume we're talking single moby container instance, not orchestration (which will have its own ingress path anyway).

**Comment by fabiocav** [comment]
Using the CLI/Coret Tools for production workloads is not supported today. An approach I would recommend would be to use one of our container images for this scenario. @ahmelsayed @balag0 can you please link to our container images?
