### ISSUE TITLE
Switch to ASP.NET config patterns

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-functions-host#3189]
For .NET Functions, please use consistent config files and access as ASP.NET Core.

This would mean removing `local.settings.json` and replacing it with the standard config files in ASP.NET Core, such as `appsettings.json` and `appsettings.Developer.json`.

I know you guys want to protect developers from themselves by not using `local.settings.json` in PROD and not checking the file in, but it would be a lot simpler if you just copied the mature and well-used patterns already established in ASP.NET.

**Comment by fabiocav** [comment]
This is something we've wanted to do for a while. We're triaging so we can discuss how this will be surfaced.

**Comment by jwisener** [comment]
@fabiocav any status update on this?

**Comment by jwisener** [comment]
The documentation and information around this really bad with no clear or concise guidance, one thing you read "we are dropping support for "appsettings.json" in azure functions from @lindydonna and in this open ticket [122,](https://github.com/Azure/azure-functions-core-tools/issues/122) talks about adding support for it and in this ticket [3189,](https://github.com/Azure/azure-functions-host/issues/3189) talks about switching to it.

**Comment by SaebAmini** [comment]
Azure functions handling appsettings unconventionally has been a great source of headache for us during recently. Whatever the original reason for it was, I think support for appsettings.json files should be added as a priority, especially since there isn't any clear documentation on how to publish your local.settings.json values easily into your function app as part of your CD pipeline.

**Comment by fabiocav** [comment]
@ahmedelnably could we track documentation improvements to address what @SaebAmini mentioned above?

**Comment by MisinformedDNA** [comment]
In the meantime, for anyone who wants ASP.NET config now, take a look at my [project](https://github.com/MisinformedDNA/AzureFunctions.AspNetConfiguration) and [NuGet package](https://www.nuget.org/packages/AzureFunctions.AspNetConfiguration/). This will let you use the patterns you are used to.

**Comment by MisinformedDNA** [comment]
Good news: https://github.com/Azure/azure-functions-host/issues/4761

**Comment by SaebAmini** [comment]
I wouldn't be too happy for that announcement @MisinformedDNA. As mentioned by fabio, hooking up your own IConfiguraion to use an appsettings file is currently trivial. The real challenge and issue to be tackled is the platform as a whole supporting file-based settings with no nasty surprises, as opposed to environment variables.

**Comment by MisinformedDNA** [comment]
24 days ago, you wanted this to be a priority. Not you don't care?

> I think support for appsettings.json files should be added as a priority

Yes, there may be lots they can do in the future, but it's a step in the right direction.

**Comment by SaebAmini** [comment]
I think you're missing my point. Yes, _proper_ support should be added as a priority. 

Reading a file into IConfiguraion currently takes 3 lines of code, which isn't what I was referring to by support.

I actually think adding appsettings at the surface without proper platform support would be dangerous.

**Comment by MisinformedDNA** [comment]
I'm reading #4761 as "we are adding _proper_ support".

**Comment by IanKemp** [comment]
This should probably be closed as #4761 is done.
