### ISSUE TITLE
System.Private.CoreLib: Exception while executing function - Error running Azure Functions v2 locally with ML.NET

### ISSUE THREAD

**Issue by ChristianWeyer** [Azure/azure-functions-host#3190]
Hey all, I have used the ML.NET tutorial here https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare and wrapped the logic into an Azure Function.

I am using 2.0.1-beta.31 CLI tools and 1.0.14 from NuGet.

When executing the Function, I get this error
```
Http Functions:

        TaxiFarePredictor: http://localhost:7071/api/TaxiFarePredictor

[26/07/2018 06:54:15] Executing 'TaxiFarePredictor' (Reason='This function was programmatically called via the host APIs.', Id=234649db-5a6c-4d91-92ed-2af4f125a96b)
[26/07/2018 06:54:15] C# HTTP trigger TaxiFarePredictor function processed a request.
Duplicate loading of the assembly 'Microsoft.ML.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
Duplicate loading of the assembly 'Microsoft.ML.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
Duplicate loading of the assembly 'Microsoft.ML, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
Duplicate loading of the assembly 'Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
Duplicate loading of the assembly 'TaxiFarePrediction, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
[26/07/2018 06:54:19] System.Private.CoreLib: Exception while executing function: TaxiFarePredictor. Microsoft.ML.Data: Entry point'Transforms.CategoricalOneHotVectorizer' not found.
[26/07/2018 06:54:19]
[26/07/2018 06:54:19] Executed 'TaxiFarePredictor' (Failed, Id=234649db-5a6c-4d91-92ed-2af4f125a96b)
[26/07/2018 06:54:19] System.Private.CoreLib: Exception while executing function: TaxiFarePredictor. Microsoft.ML.Data: Entry point'Transforms.CategoricalOneHotVectorizer' not found.
```

Repro:
https://github.com/ChristianWeyer/azure-functions-ml-net

This is the input JSON I am using to test the Function with:
```
{
   "VendorId": "VTS",
   "RateCode": "1",
   "PassengerCount": 1,
   "TripDistance": 10.33,
   "PaymentType": "CSH"
}
```

Any ideas what could be wrong here?
.cc @fabiocav 

Thanks!

**Comment by ChristianWeyer** [comment]
Updated Core Tools to latest 2.0.1-beta.33 - still the same result.

**Comment by fabiocav** [comment]
Will take a look at this as soon as possible. At a first glance, it does look like something coming from the code in those assemblies, but this needs some investigation

**Comment by fabiocav** [comment]
@ChristianWeyer we're investigating some improvements and working with the ML.NET team to address this, but in the meantime, can you try adding the following to the beginning of your function to see if that unblocks you:

``` csharp
            if (typeof(Microsoft.ML.Runtime.Data.LoadTransform) == null ||
                typeof(Microsoft.ML.Runtime.Learners.LinearClassificationTrainer) == null ||
                typeof(Microsoft.ML.Runtime.Internal.CpuMath.SseUtils) == null ||
                typeof(Microsoft.ML.Runtime.FastTree.FastTree) == null)
            {
                log.Error("Error loading ML.NET");
                return new StatusCodeResult(500);
            }
```
You may still see the duplicate loading logs, but those should be harmless.

**Comment by ChristianWeyer** [comment]
This works, thanks @fabiocav - should we leave this issue here open for tracking?

**Comment by lqdev** [comment]
Same issue here. Still not working in v 0.4.0.

**Comment by chrismckelt** [comment]
Related closed issue https://github.com/dotnet/machinelearning/issues/559

says this will be fixed via https://github.com/dotnet/machinelearning/issues/371 by no longer front loading assemblies, as the API usage will be directly against the underlying C# assemblies.

**Comment by fabiocav** [comment]
@ChristianWeyer we've worked with the ML.NET team and they were working on improvements to address this issue (as much of the problem was because of how they were loading dependencies). Closing this as there's no action to be taken on this repo.
