### ISSUE TITLE
Docker Hub images naming out of date

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-host#3197]
We have 3 automated docker images to use with functions:

```
azure-functions-dotnet-core2.0
azure-functions-node8
azure-functions-python3.6
```

However some of them are already outdated and others potentially missing.  `dotnet-core2.0` should likely be `dotnet-core2.1`, and `node8` should have a `node10` variant.

Wondering if right future-proof pattern would be just to have `dotnet-core`, `node`, and `python` and rely on tagging to specify versions so can be rev'd a little easier?  not sure

**Comment by jeffhollan** [comment]
@ahmelsayed to comment and as FYI

**Comment by ahmelsayed** [comment]
Yes, I have a thread with the owners of the Microsoft org under docker hub to create these images, i.e
```
azure-functions-dotnet-core
azure-functions-node
azure-functions-python
```

But they have a new process now that I haven't had the chance to read all the documentation for yet

**Comment by jeffhollan** [comment]
Awesome thanks @ahmelsayed sounds good.  Not urgent just wanted to make sure we had our eye on it which you do.

**Comment by fabiocav** [comment]
Can this be closed?

**Comment by fabiocav** [comment]
Closing this as I believe it is resolved. Please reopen if needed.
