### ISSUE TITLE
Fixing version to avoid breaking changes: Fails

### ISSUE THREAD

**Issue by jazzyray** [Azure/azure-functions-host#3198]
I am trying to fix the run-time version as described here:

https://github.com/Azure/app-service-announcements/issues/122

Using:
FUNCTIONS_EXTENSION_VERSION 2.0.11933-alpha 

However, I get the following error:

Runtime version
Runtime version loaded from Application Settings: 2.0.11933-alpha

Warning
Unsupported Runtime Version
Your custom runtime version is not supported. As a result runtime is being used. 

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0-beta): 2.0-beta
- Function App name: emb-api-prod-20180614
- Function name(s) (as appropriate):
- Invocation ID:
- Region: West Europe

#### Repro steps

Provide the steps required to reproduce the problem: 

Look at an existing deployed function with the correct Runtime App setting: 

 2.0.11933-alpha

#### Expected behavior

Provide a description of the expected behavior.

2.0.11933-alpha should be a supported run-time as described in the breaking change ticket.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

None

#### Related information 

Provide any related information 

* Programming language used 
Java

**Comment by jazzyray** [comment]
@pragnagopa Can you advise how/what I should set the run-time setting to in order to avoid the breaking change?

**Comment by pragnagopa** [comment]
@fabiocav  - I tried this and i do see the warning message **Unsupported Runtime Version** is this expected?

**Comment by pragnagopa** [comment]
@jazzyray - We have investigated and this is a UI issue on the portal. Setting the FUNCTIONS_EXTENSION_VERSION to 2.0.11933-alpha does work. You can verify by pinging status endpoint https://{YourAppName}.azurewebsites.net/admin/host/status?code={YourMasterKey}

**Comment by pragnagopa** [comment]
This issue was moved to Azure/azure-functions-ux#2947
