### ISSUE TITLE
Language workers: blob data is always sent as string in the protobuf message.

### ISSUE THREAD

**Issue by peterhuene** [Azure/azure-functions-host#3203]
#### Investigative information

Function App Host: running locally with latest out of dev branch (SHA a22350900cd5812e5bb5297e99e82acb8682fe50)

#### Repro steps

1. Enable Trace logging level in `host.json`:

```json
{
    "logger": {
        "categoryFilter": {
            "defaultLevel": "Trace"     
        }
    }
}
```

2. Create a 'foo' function with the following `function.json`:

```json
{
    "bindings": [
        {
            "name": "myBlob",
            "type": "blobTrigger",
            "direction": "in",
            "path": "test/{name}"
        }
    ]
}
```

3. Implement the function with a worker-implemented language (here is an example in node, `run.js`):

```javascript
module.exports = function(context) {
    context.log('Node.js Blob trigger function processed', context.bindings.myBlob);
    context.done();
};
```

4. Create an Azure Storage blob at the specified path (e.g. `test/example`) that would contain invalid UTF-8 sequences.  I used a small file with all 0xFF bytes:

```
$ hexdump ~/example
0000000 ffff ffff ffff ffff                    
0000008
```
#### Expected behavior

The data of the blob should be passed as bytes and not as a string because blobs are not always UTF-8 encoded.

#### Actual behavior

The data of the blob is passed as a string.  It appears the serialization into the protobuf message by the Azure Functions Host is sending replacement characters instead.

In the trace output, you should see the following serialized for the `InvocationRequest` message:

```
...
        "InputData": [
              {
                "Name": "myBlob",
                "Data": {
                  "String": "��������",
                  "Json": "",
                  "Bytes": [],
                  "Stream": [],
                  "Int": 0,
                  "Double": 0.0,
                  "DataCase": "String"
                }
              }
            ],
...
```

Blobs should probably always be passed via "bytes" (or ideally "stream" when that has meaning as a gRPC stream).

#### Known workarounds

N/A

#### Related information 

This was discovered during my work to implement blob storage triggers in [Azure Functions for Rust](https://github.com/peterhuene/azure-functions-rs).  Here's the bytes I receive in the message (all UTF-8 encoded replacement characters):

```
[239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189, 239, 191, 189]
```

**Comment by pragnagopa** [comment]
@mhoeger - Can you please investigate. We should add some unit tests.

**Comment by JohnReeson** [comment]
Met this problem before, it seems the default [binding data type](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#binding-data-type) is string, hence we need to add `"dataType": "binary"` in `function.json`. Is it better to add `dataType` in js `function.json` template so that it can come to our mind once meet data type problem?

**Comment by peterhuene** [comment]
Will the `binary` data type in the binding translate to having the host pass it as `Bytes` in the language worker protocol buffer?  I'll investigate.  If so, then I can fix this on my end where I generate blob bindings.

**Comment by peterhuene** [comment]
Something appears to have changed since I last tried this, as now the data is coming through as `Bytes` on the protobuf message when uploading binary files, even without specifying `"dataType": "binary"` in the binding.  Closing this issue as no repro.
