### ISSUE TITLE
Functions proxy response header "X-Powered-By" doesn't get overwritten and is duplicated instead

### ISSUE THREAD

**Issue by shahiddev** [Azure/azure-functions-host#3204]
I'm using a functions proxy to add headers to the response. In particular I'm overwriting some of the existing headers to redact them and add some other headers. This works fine for all the headers except X-Powered-By. 
This header seems to duplicate, with my functions proxy header being added to the headers but the once I'm trying to overwrite still being present.

#### Investigative information

Please provide the following:

- Timestamp: n/a
- Function App version (1.0 or 2.0-beta): 2.0-beta
- Function App name: hfcwebsite (consumption)
- Function name(s) (as appropriate): proxy: index
- Invocation ID: n/a
- Region: West Europe

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a v2 FunctionApp and add a proxy for route / to a static html page in storage.
2. In the proxy responses add response headers for X-Powered-By : redacted
3. Add header for  Server: redacted

#### Expected behavior
Provide a description of the expected behavior.
The response headers should read
X-Powered-By : redacted
Server: redacted

#### Actual behavior

Provide a description of the actual behavior observed.
response 
The Server header is shown as redacted but the X-Powered-By is duplicated, one is shown as redacted and the other one showing ASP.NET
![image](https://user-images.githubusercontent.com/11890711/43367747-08c3dab4-934a-11e8-9433-a1badad0467b.png)

#### Known workarounds

Provide a description of any known workarounds.

None
#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used
```
{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
        "index": {
            "matchCondition": {
                "route": "/",
                "methods": [
                    "GET",
                    "HEAD",
                    "OPTIONS",
                    "TRACE"
                ]
            },
            "backendUri": "https://<redacted>.blob.core.windows.net/website/Index.html",
            "responseOverrides": {
                "response.headers.strict-transport-security": "max-age=31536000; includeSubDomains",
                "response.headers.X-Powered-By": "redacted",
                "response.headers.X-Content-Type-Options": "nosniff",
                "response.headers.X-XSS-Protection": "1; mode=block",
                "response.headers.x-ms-blob-type": "redacted",
                "response.headers.x-ms-lease-state": "redacted",
                "response.headers.x-ms-lease-status": "redacted",
                "response.headers.Server": "redacted",
                "response.headers.x-frame-options": "SAMEORIGIN",
                "response.headers.Content-Security-Policy": "script-src 'self'",
                "response.headers.Upgrade-Insecure-Requests": "1",
                "response.headers.Referrer-Policy": "same-origin",
                "response.headers.Feature-Policy": "payment 'self'; geolocation 'self'"
            }
        }
    }
}
```

**Comment by shahiddev** [comment]
Duplicate is not an issue per se but I want to redact the value of the header in the same way the others are being

**Comment by mathewc** [comment]
Related to https://github.com/Azure/azure-functions-host/pull/2355

**Comment by fabiocav** [comment]
This should be resolved with the release that is currently rolling out (2.0.12353), which should be fully deployed by the end of the week.
