### ISSUE TITLE
Known Issues for 2.0 runtime could use an update

### ISSUE THREAD

**Issue by KirkMunro** [Azure/azure-functions-host#3206]
The [Known Issues](https://github.com/Azure/azure-functions-host/wiki/Azure-Functions-runtime-2.0-known-issues#known-issues) list for the 2.0 runtime includes some issues that are marked as resolved. If someone could update the current list of known issues, that would be appreciated.

**Comment by fabiocav** [comment]
Sorry about the lack of response. With GA, the documentation has been updated and this is no longer applicable. Closing as resolved.
