### ISSUE TITLE
Problem when running eventhub trigger locally

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#3209]
_From @jdneo on July 24, 2018 10:50_

Related issue: https://github.com/Microsoft/azure-maven-plugins/issues/277

The function can be triggered correctly both at local and on cloud. But can see some errors in the output.
![image](https://user-images.githubusercontent.com/22470312/43133559-c6c1bdc4-8f71-11e8-8da6-6b98c0c4dacd.png)

_Copied from original issue: Azure/azure-functions-core-tools#591_

**Comment by jdneo** [comment]
Just verified in the newest function cli - 2.0.1-beta.33. Problem seems solved.
