### ISSUE TITLE
Problem running locally on macOS 10.14 Mojave developer beta

### ISSUE THREAD

**Issue by lmrisdal** [Azure/azure-functions-host#3211]
So I'm getting this after upgrading to macOS 10.14 developer beta:

`[31/07/2018 10:28:45] System.Private.CoreLib: Exception while executing function: Function1. FunctionApp1: The type initializer for 'FunctionApp1.Function1' threw an exception. Microsoft.Azure.DocumentDB.Core: The type initializer for 'Microsoft.Azure.Documents.UserAgentContainer' threw an exception. Microsoft.Azure.DocumentDB.Core: Error reading Darwin Kernel Version. System.Private.CoreLib: The given key 'osx.10.14-x64' was not present in the dictionary.`

Is there a fix for this, or anything I can do myself to fix it?

**Comment by peterhuene** [comment]
This may be a .NET Core RID issue.  Does it work if you set `DOTNET_RUNTIME_ID=osx-x64` in your environment?

**Comment by lmrisdal** [comment]
Well that did something. I’m no longer getting the same exception, but I’m
now getting another error:
"2018-08-02 09:40 func[8742] (FSEvents.framework) FSEventStreamStart:
register_with_server: ERROR: f2d_register_rpc() => (null) (-21)"

tor. 2. aug. 2018 kl. 03:09 skrev Peter Huene <notifications@github.com>:

**Comment by lmrisdal** [comment]
```
This may be a .NET Core RID issue. Does it work if you set
DOTNET_RUNTIME_ID=osx-x64 in your environment?
```

Well that did something. I’m no longer getting the same exception, but I’m
now getting another error:
"2018-08-02 09:40 func[8742] (FSEvents.framework) FSEventStreamStart:
register_with_server: ERROR: f2d_register_rpc() => (null) (-21)"

> This may be a .NET Core RID issue. Does it work if you set
> DOTNET_RUNTIME_ID=osx-x64 in your environment?

**Comment by paulbatum** [comment]
Reactivating this, I want to explore whether there is anything we can do such that setting DOTNET_RUNTIME_ID explicitly is not required.

**Comment by fabiocav** [comment]
We'll be addressing this with enhancements to our RID fallback logic

**Comment by sm1th** [comment]
Still having an issue with this. I have to put DOTNET_RUNTIME_ID in my local.settings.json
