### ISSUE TITLE
V2 Private Site Extension builds dont work right now

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#3224]
There are a few issues:
1. Private site extensions can't modify global modules, so the changes to run using ancm in-proc dont work
2. The no-runtime build appears to be screwed up because it:
 a) has a physical path based on bitness but the zip layout does not have bitness folders
 b) has the xdt in the same folder as all the binaries (perhaps this is fine, but its unusual, none of the other builds are like this)

**Comment by fabiocav** [comment]
Fixed by #3268
