### ISSUE TITLE
How to troubleshoot function when function method doesn't even run

### ISSUE THREAD

**Issue by KirkMunro** [Azure/azure-functions-host#3227]
#### Investigative information

- Timestamp: 2018-08-06 06:00:44.482
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name: ghWebhookFx20180806
- Function name(s) (as appropriate): pop (invoked by push)
- Invocation ID: d4011b6a-64c3-4263-a821-a8d59a2ab840
- Region: East US

#### Repro steps

I have an Azure function that is invoked by another Azure function, and the invocation of the 2nd function fails before it even enters into the HTTP method that does the work. The logging that is provided to me (below) for this failure doesn't give me enough information to troubleshoot.

Message | Log Level
-- | --
Function started (Id=d4011b6a-64c3-4263-a821-a8d59a2ab840) | Information
Executed '{FullName}' (Failed, Id={InvocationId}) | Error
Function completed (Failure, Id=d4011b6a-64c3-4263-a821-a8d59a2ab840, Duration=308ms) | Error

Can someone point me in the right direction on how I can troubleshoot this?

Aside: note that the second log message comes from a string that should be defined as an interpolated string (this is a bug in the Azure Function runtime).

#### Expected behavior

I expected at least to see the opening log message inside of my pop function.

#### Actual behavior

It doesn't enter the pop method body at all.

#### Known workarounds

None

#### Related information 

None

**Comment by paulbatum** [comment]
I found the error in the logs in my side, and you should absolutely see this error in your logs too so if its not appearing we need to investigate.

The actual error is:
```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: pop ---> System.MissingMethodException : Method not found: 'System.IO.Compression.ZipArchive System.IO.Compression.ZipFile.OpenRead(System.String)'.
   at async GitHubWebhook.Functions.PopFunction.Run(HttpRequestMessage req,TraceWriter log)
```

So it looks the code in your pop function is calling an API that does not exist? The documentation for ZipFile does not show an overload that only takes a string:
https://msdn.microsoft.com/en-us/library/system.io.compression.zipfile

I'm assuming you're using App Insights. Can you double check the exceptions table? There really should be an error log with this error message.

**Comment by KirkMunro** [comment]
@paulbatum The documentation you linked to shows the API I'm invoking (**OpenRead(string archiveFileName**). It does exist, at least according to the docs and it works fine locally, just not in Azure Function workers. Can you comment on that?

I'll have a look at the exceptions table. Part of my question came from me not having this type of error before, so I wasn't sure where to go for more information.

**Comment by KirkMunro** [comment]
@paulbatum I've confirmed that I can see the error details by adding the innermostMessage property to the default output I get from the error query linked to from Invocation Details in my Azure Function. It's too bad that I have to add the extra fields, and that instead that view doesn't present that information to me so that I can recognize the error from the start.

That aside, I would like some investigation into why this occurs, because the method I am invoking [does exist](https://msdn.microsoft.com/en-us/library/system.io.compression.zipfile.openread).

Also, just calling it out so that it's not lost, there is something wrong with the second error message due to a bug in how the "Executed '{FullName}' (Failed, Id={InvocationId})" string is defined (it's missing the leading $ to make it an interpolated string.

**Comment by KirkMunro** [comment]
Now that I know what the error is, I bet the accepted answer here is the root cause:
https://stackoverflow.com/questions/44318777/system-missingmethodexception-when-trying-to-read-zipfile-from-ziparchive-c-shar

**Comment by KirkMunro** [comment]
Sure enough, that workaround fixed it. So the issue/limitation seems to be the version of .NET that is used in the Azure Function runtime, although I'm a little surprised, because the methods I was invoking were added in 4.5.

**Comment by paulbatum** [comment]
My bad, I missed that there are both Open and OpenRead methods. 

Yeah I still don't understand why you're getting that error, because in Azure, you're running on .NET Framework 4.7.2. What version of .NET framework is your application targeting?

**Comment by KirkMunro** [comment]
.NET 4.7.2.

**Comment by paulbatum** [comment]
OK I have a much better idea of what is going on now.

First off - are you aware of this issue, and are you using the workaround specified in this issue?
https://github.com/Microsoft/dotnet/blob/master/releases/net472/KnownIssues/613745%20-%20Single-name%20references%20are%20removed%20by%20the%20SDK%20when%20targeting%204.7.2.md

If you take the following function, I bet you'll find that it compiles and works as long as you target 4.7.1 or earlier. You won't have to do any strange workarounds and you should not notice any inconsistency between local and Azure. Everything should be 👌 

```csharp
        [FunctionName("ZipFileTest")]
        public static HttpResponseMessage Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequestMessage req, 
            TraceWriter log,
            ExecutionContext ec)
        {
            var path = Path.Combine(ec.FunctionAppDirectory, "example.zip");
            using (var archive = ZipFile.OpenRead(path))
            {
                var message = $"Archive contains {archive.Entries.Count} entries.";
                log.Info(message);
                return req.CreateResponse(HttpStatusCode.OK, message);
            }
        }
```

Now, if you put this function into a project that targets 4.7.2, then you'll run into the issue that I linked and the code won't compile. You'll get errors like:

```
1>------ Rebuild All started: Project: TestV1, Configuration: Debug Any CPU ------
1>Function1.cs(16,118,16,136): error CS0246: The type or namespace name 'HttpRequestMessage' could not be found (are you missing a using directive or an assembly reference?)
1>Function1.cs(16,23,16,42): error CS0246: The type or namespace name 'HttpResponseMessage' could not be found (are you missing a using directive or an assembly reference?)
1>Done building project "TestV1.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

And:

```
1>------ Rebuild All started: Project: TestV1, Configuration: Debug Any CPU ------
1>Function1.cs(21,34,21,50): error CS0012: The type 'ZipArchive' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
1>Done building project "TestV1.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

 In order to get that compiling, I had to add the following to my csproj (using the workaround mentioned in the issue):

```xml
  <ItemGroup>
    <PackageReference Include="System.Net.Http" Version="4.3.3">
      <ExcludeAssets>All</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="System.IO.Compression" Version="4.3.0">
      <ExcludeAssets>All</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="System.IO.Compression.ZipFile" Version="4.3.0">
      <ExcludeAssets>All</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />    
    <Reference Include="System.IO.Compression" />
  </ItemGroup>
```

Now that workaround gets everything compiling and running locally, but deploy THAT to Azure and it'll blow up with a `MethodMissingException`. I don't know exactly why, but it seems like its got to have something to do with the workaround.

**Comment by paulbatum** [comment]
Anyway, I think we have two workarounds - the one you found, using a different overload, and alternatively, going back to targeting 4.7.1.

**Comment by paulbatum** [comment]
Also I looked at the issue you called out regarding the string `Executed '{FullName}' (Failed, Id={InvocationId})`. I do not think its an issue with a missing $, because if you look at the code we are using structured logging:

https://github.com/Azure/azure-webjobs-sdk/blob/447a67bb6af15b80485ea71603a4448515e22c12/src/Microsoft.Azure.WebJobs.Host/Loggers/Logger/LoggerExtensions.cs#L42-L47

```csharp
            string logString = $"Executed '{{{LogConstants.FullNameKey}}}' ({result}, Id={{{LogConstants.InvocationIdKey}}})";
            object[] values = new object[]
            {
                logEntry.FunctionName,
                logEntry.FunctionInstanceId
            };
```

So I think its a problem with propagation of the function name and instance ID in the case of this method missing.

Its unfortunate that the monitor tab doesnt show the actual bit of information you need. I think the UX could be updated to address this, filed the following to track:
https://github.com/Azure/azure-functions-ux/issues/2974

**Comment by KirkMunro** [comment]
@paulbatum Thank you for taking the time to provide all of these extra details. I was not aware of that known issue. Also thanks for logging the additional issue with the monitor tab not showing the root cause of the error. All of this is very much appreciated.

With the issue about the error message logged, and the extra details about the .NET 4.7.2 issue + the workarounds, I don't need anything else on this, so I'll close the issue.
