### ISSUE TITLE
Function app stopped processing queue messages until it was restarted

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#3230]
I've been trying to get to the bottom of an issue this customer is facing with functions on dedicated linux. It seems that their function app was running fine for a long time then suddenly stopped processing queue messages. I have the logs, but the last error reported from the host is this one below. After that the host process remained responsive, but no new executions. I see a bunch  of `[Information] Executing 'Functions.name' (Reason='New queue message detected on ..." but with no execution or temination.`

The customer had to restart their app to get it back into a working state. I have the full log

```
[Information] Executing 'Functions.name' (Reason='New queue message detected on 'name'.', Id=00000000-0000-0000-0000-000000000000)
[Information] Worker 00000000-0000-0000-0000-000000000000 encountered event stream error:  { Error: Exception was thrown by handler.
[Information] at ClientDuplexStream._emitStatusIfDone (/azure-functions-host/workers/node/worker-bundle.js:22585:19)
[Information] at ClientDuplexStream._receiveStatus (/azure-functions-host/workers/node/worker-bundle.js:22563:8)
[Information] at /azure-functions-host/workers/node/worker-bundle.js:23087:12 code: 2, metadata: Metadata { _internal_repr: {} } }
[Information] Worker 00000000-0000-0000-0000-000000000000 uncaught exception:  { Error: Exception was thrown by handler.
[Information] at ClientDuplexStream._emitStatusIfDone (/azure-functions-host/workers/node/worker-bundle.js:22585:19)
[Information] at ClientDuplexStream._receiveStatus (/azure-functions-host/workers/node/worker-bundle.js:22563:8)
[Information] at /azure-functions-host/workers/node/worker-bundle.js:23087:12 code: 2, metadata: Metadata { _internal_repr: {} } }
[Information] Worker 00000000-0000-0000-0000-000000000000 exited with code 1
[Information] Executed 'Functions.name' (Succeeded, Id=00000000-0000-0000-0000-000000000000)
[Error] Worker encountered an error.
```

**Comment by pragnagopa** [comment]
@mhoeger  - Can you please look into this? Could be related to https://github.com/Azure/azure-functions-host/issues/2919

**Comment by mhoeger** [comment]
The errors here are related to RPC stream errors. Specifically, [here](https://github.com/grpc/grpc/blob/b74e050112fbdcb2cfdf475a167aa326e9bf26b9/src/csharp/Grpc.Core/Internal/ServerCallHandler.cs#L340) in the c# GRPC server code.

The fact that it didn't restart is either related to #2919 or because there was an irrecoverable issue with the GRPC server, I'm not quite sure which. Still investigating.

**Comment by pragnagopa** [comment]
Closing as this issue is addressed as part of https://github.com/Azure/azure-functions-host/issues/4231
