### ISSUE TITLE
No F# language support in beta version

### ISSUE THREAD

**Issue by tforkmann** [Azure/azure-functions-host#3231]
In the beta version there is no language support for F# anymore.

### Investigative information
Please provide the following:

Function App version (1.0 or 2.0-beta): beta
Function App name: dpemailimportaf
Function name: none yet
Region: Europe West

### Repro steps
go to portal an try to add a new function 

### Expected behavior
Available functions shows F# Functions

### Actual behavior
Language F# is not available

### Known workarounds
Create a C# Function. Delete run.csx and add a new run.fsx file

@forki 

![image](https://user-images.githubusercontent.com/4168951/43799250-4881fc7c-9a8d-11e8-8f56-d1dbb749d869.png)

**Comment by paulbatum** [comment]
The language support is present in the functions host (this repo). Whats missing is templates that are usable from the portal. I filed this to track:
https://github.com/Azure/azure-functions-templates/issues/716
