### ISSUE TITLE
API to provide list of supported runtimes

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-host#3232]
We've decided to pivot to a single language/runtime per Function App. Currently this list is hardcoded in the portal and CLI. We need an API to ensure consistency across the board for all hosting platforms (Windows/Linux) and tools (Portal, VS Code, Core Tools). 

```
.NET
JavaScript
Python
```

**Comment by paulbatum** [comment]
I think this issue is in the wrong place, because you're going to need to have this list BEFORE the function app is created, and therefore there is no provisioned runtime.

**Comment by paulbatum** [comment]
First we need to figure out what component should be hosting this API...

**Comment by asavaritayal** [comment]
Closing as this seems to be tracked elsewhere now.
