### ISSUE TITLE
Update NodeJS and JavaWorker for console logs

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#3240]
Tracking item to release and update NodeJS and Java workers for the next release.

**Comment by mhoeger** [comment]
Cool :) Is this solved with #3235 though? I know for nodejs worker, this PR consumes the console logging change

**Comment by pragnagopa** [comment]
Right we have all the changes for the nodejs worker. I published to myget from dev branch to get a green build for the PR: https://github.com/Azure/azure-functions-host/pull/3235 . This issue is to track creating release nuget packages following our release process moving bits to master and publishing to myget.

**Comment by mhoeger** [comment]
Cool, makes sense :)

**Comment by pragnagopa** [comment]
Also need to release version 1.0.0 of [azure-functions-language-worker-protobuf](https://github.com/Azure/azure-functions-language-worker-protobuf/)

**Comment by paulbatum** [comment]
@pragnagopa Can we close this?

**Comment by pragnagopa** [comment]
Both the workers are updated.
