### ISSUE TITLE
Key cache failing to refresh

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#3252]
We've had a site run into an issue where:
1. They've added new keys via the portal and also via the keys API directly.
2. API returns successfully (verified via request traces).
3. Key disappears from the portal quickly after being entered.

Refreshing the site fixed it as the cache was reloaded.

It appears there's a scenario where the in-memory key cache can fail to refresh after a new key is entered.

This was using the File (not Blob) secret repository.

**Comment by fabiocav** [comment]
@brettsam is this still an issue?

**Comment by brettsam** [comment]
It was a an issue that a customer saw in a handful of sites while I was on servicing (incident number **79726500**). I've only ever heard of one instance but it sounds like we may be failing to invalidate the in-memory cache of keys, even though things are stored correctly. So when calling ListKeys, it's wrong. Some details from customer:

[PROBLEM DESCRIPTION]
- Customer has a several function apps in a different subscriptions all hosted on app service plan function app "dedicated asp", starting this morning customer is trying to add a new host key or function key through the portal and API using the 'https://(appname).azurewebsites.net/admin/host/keys/(keyname)?code=(masterkey)
- its showing a successful operation but then its just disappears from the portal.
- no traces shows that there is writes on customer host or function keys at on cx side.

Repro steps on cx side as i'm unable to make a repro is:
- In the portal I click the 'Add new function key' or 'Add new host key' buttons in the Manage pane of the function app.
- Then I add a name and click 'Save'. 
- The browser looks like it saves the key for a few seconds, but afterwards it is gone.
- Doing it through the http API using the 'https://(appname).azurewebsites.net/admin/host/keys/(keyname)?code=(masterkey)'  URL is similar. The API returns a new key - it doesn't fail  - but afterwards the key is nowhere to be seen.
- checked Har logs its seems that the Post request is returning 200 but then the Get request does not show the new function or host keys, logs in the attachments.
- The host keys are present in the host.json and functionname.json files in d:\home\data\Functions\secrets.
- They are not shown in the portal, and they are also not returned when querying them via the http management API.
- As far as I can tell in the network capture, the portal DOES call the function management API to create the new key, and it does get a response (the POST operation to https://(appname).azurewebsites.net/admin/host/keys/test%20key%20for%20support).
- But then, the subsequent call to https://(appname).azurewebsites.net/admin/host/keys does not return the new key.
- for the new function keys we have tried to call functions using function keys but it was throwing 401, attached fiddler traces for that calls.

**Comment by alrod** [comment]
Closed as not reproducible.
The issue was opened a while back. Most likely it was already fixed.
