### ISSUE TITLE
TimerTrigger not updating schedule and running in incorrect schedule

### ISSUE THREAD

**Issue by klesouza** [Azure/azure-functions-host#3261]
I have a azure function trigger by a timer. I've changed the schedule configuration, but It's running in weird times. It took a very long time to update the schedule after deployment (WEBSITE_RUN_FROM_ZIP deployment), and when it changed the schedule, it was not correct.
Previous schedule `(0 */5 * * * *)`
New Schedule `(0 0 */4 * * *)`

It's currently triggering every 1,25 hours.

#### Investigative information

Please provide the following:

- Timestamp: 2018-08-15T09:15:21.5559824+00:00
- Function App version (1.0 or 2.0-beta): Runtime version: 2.0.11961.0 (beta)
- Invocation ID: 99dcb156-0097-4ad8-9ed3-5308a3faba76
- Region: West Europe
- Plan: Consumption

#### Repro steps

Provide the steps required to reproduce the problem:

1. Have a running timer function using a certain schedule
2. Deploy new version for the function using WEBSITE_RUN_FROM_ZIP with a different schedule

#### Expected behavior

The schedule for the function is updated and the function is triggered accordingly

#### Actual behavior

The schedule is updated but the function is triggered not accordingly

#### Related information 

Provide any related information 

* Using C# 
* Trigger by timer
* Deployed via WEBSITE_RUN_FROM_ZIP
* I've gonna through this to check https://github.com/Azure/azure-functions-host/wiki/Investigating-and-reporting-issues-with-timer-triggered-functions-not-firing

**Comment by pragnagopa** [comment]
Closing this is an older runtime. Please reopen if you it still reproes with the latest functions runtime
