### ISSUE TITLE
Service Bus Queue Trigger fires for awhile then function needs to be restarted to continue processing

### ISSUE THREAD

**Issue by stevenwilliamsmis** [Azure/azure-functions-host#3262]
Over the past few weeks we have been trying unsuccessfully to identify why our Service Bus Trigger stops firing. We have application insights tied to the function, and while we do see an occasional error from our data we don't see any errors leading up to the point when the trigger stops firing.  Restarting fixes the issue however the function stops listening to the messages either in a few days or some days it stops multiples times a day....The function is operating as expected otherwise.

#### Investigative information

Please provide the following:

- Timestamp: 
       2018-08-15 05:27:50.541 UTC last successful run
       2018-08-15 11:40:50.541 UTC current time
- Function App version (1.0 or 2.0-beta):  1.0
- Function App name: <prefer not to share>
- Function name(s) (as appropriate): FileProcessor
- Invocation ID: 3445d03b-7ab0-4e15-bf92-94204be785df
- Region: Central US

#### Repro steps

Unknown - Service Bus Trigger randomly stops pulling messages.

#### Expected behavior

Trigger should pick up messages on the queue when they are available.

#### Actual behavior

Azure Function Randomly stops picking up messages from the Service Bus Queue.

#### Known workarounds

Restarting the Azure function fixes the issue temporarily.

#### Related information 

* Programming language used - C#

<details>
<summary>Bindings</summary>
{
  "generatedBy": "Microsoft.NET.Sdk.Functions.Generator-1.0.8",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "serviceBusTrigger",
      "direction": "in",
      "connection": "AzureWebJobsQueue",
      "queueName": "processfiles",
      "accessRights": "Manage",
      "name": "processfile"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/Insights.Orchestration.SBProcess.Functions.dll",
  "entryPoint": "Insights.Orchestration.SBProcess.Functions.FileProcessor.Run"
}
</details>

**Comment by pragnagopa** [comment]
Unfortunately, we did not get a chance to investigate issue. Please re-open with the latest timestamps if the issue still reproes.
