### ISSUE TITLE
Missing extension metadata generator package repository information

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#3282]
The metadata generator package is currently missing the repository type and URL. We need to add that information to the project file so it's added when packing:

https://github.com/Azure/azure-functions-host/blob/d9924c886d76a6c3fcd60818205e9e099517cf96/build/common.props#L16-L17

**Comment by paulbatum** [comment]
Resolved by https://github.com/Azure/azure-functions-host/pull/3287
