### ISSUE TITLE
Azure function monitor portal always show 0 success

### ISSUE THREAD

**Issue by zhangruiskyline** [Azure/azure-functions-host#3284]
Hi

I am checking Azure function app portal monitor sections. and always got "0 success in last 30 days. when I check the corresponding Appinsight query I found the query is
`requests | project timestamp, id, name, success, resultCode, duration, operation_Id | where timestamp > ago(1d) | where name == 'IDmappingNewdata' | order by timestamp desc `

so looks like all requests fails. however, I believe most of my functions are still successfully processed if I use query

`
let timeframe = ago(24h);
traces
| where operation_Name == "IDmappingNewdata" and timestamp >= timeframe
| summarize blob_started = countif(message startswith "Function started") , blob_success = countif(message startswith "Function completed (Success"), blob_failed = countif(message startswith "Function completed (Fail")
| project blob_started , blob_success, blob_failed
`

My function is MediationIDsync-Prod-WUS, and some of the failed operation id are

369ba2e7-71e2-4520-a84f-b58a4100e91c, 
e83e5fe3-2b4d-49c4-b9ae-5f1761845cdb,
efd5e2af-0312-4cf7-a405-77e898c65867

To be clear, I understand why it fails and work to resolve it. My question is why I got 0 success for request query? I still have most of my functions success

Thanks
Rui
--

**Comment by pragnagopa** [comment]
Closing this issue as the log timestamps are too old. Please re-open if this is still an issue with the latest timestamps
