### ISSUE TITLE
Event Hubs binding data test failing since 2.1 update

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#3289]
The EventHub end-to-end test has been failing since the update to the EH SDK 2.1. The failure seems to be happening when retrieving the binding data for the system properties.

Opening this for investigation and to track the skipped test. Once the issue is found, it would be good to have a test in the extension (SDK) repo to catch that early.

**Comment by pragnagopa** [comment]
I will look into it.
