### ISSUE TITLE
Getting function admin token throws error on linux function apps

### ISSUE THREAD

**Issue by erwelch** [Azure/azure-functions-host#3292]
This error is thrown consistently only on linux function apps, I am able to run the same commands and get the token without errors for windows function apps. I've tested this across 5 different linux function applications and all of them throw the same error. 

- Timestamp: 2018-08-20 08:54:45,464 (and various other times)
- Function App version (1.0 or 2.0-beta): linux in beta
- Function App name: test-linux-token
- Function name(s) (as appropriate): HttpTriggerJS1 (N/A)
- Invocation ID: N/A
- Region: West Us 2

Provide the steps required to reproduce the problem:

Example: 

1. Create a linux function web application in the portal (we've used both Javascript and  Python runtimes)
2. Since I was calling the token endpoint from a Python app I used the azure Python SDK to call the token API: 
```jwt = web_client.web_apps.get_functions_admin_token('test-linux-token', 'test-linux-token')```
(web_client is the azure.mgmt.web.WebSiteManagementClient client)
That client calls the admin token endpoint:
 ```https://management.azure.com/subscriptions/<removed>/resourceGroups/test-linux-token/providers/Microsoft.Web/sites/test-linux-token/functions/admin/token```

#### Expected behavior

Provide a description of the expected behavior.
After I perform step 2 I should receive a jwt that enables me to call the endpoint to get the keys (https://github.com/Azure/azure-functions-host/wiki/Key-management-API)

#### Actual behavior

Step 2 actually causes an error to be thrown when it's for a linux function app: 
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/<removed>/resourceGroups/test-linux-token/providers/Microsoft.Web/sites/test-linux-token/functions/admin/token?api-version=2016-08-01 (Caused by ResponseError('too many 500 error responses',)

This exact same error is thrown on every single linux function app I've tested it against. 

Step 2 works as expected for all windows function apps I've tested. 

#### Known workarounds

No known work arounds.

#### Related information 
Linux VMs

**Comment by paulbatum** [comment]
cc @ahmelsayed, @fabiocav 

The /admin/token API is implemented in kudu which I believe is running on mono in the linux scenario and I'm not sure if this API works in that case. There were some changes to these APIs for functions V2 and I suspect that the python SDK is not aware of these changes. I am asking around internally to understand what needs to happen here.

**Comment by ahmelsayed** [comment]
that API isn't there in Linux functionapps. 

For any v2 function app you can do 

```
GET  /subscriptions/{subId}/resourceGroups/{rgName}/providers/Microsoft.Web/sites/{appName}/hostruntime/admin/host/systemkeys/_master
```
