### ISSUE TITLE
http trigger scaling for CPU intensive operations

### ISSUE THREAD

**Issue by grickettsnz** [Azure/azure-functions-host#3305]
Burst of http triggered CPU intensive functions causes response time to blow out and never recover.

#### Investigative information

- Timestamp: 2018-08-22 03:24:10.516
- Function App version (1.0 or 2.0-beta): 2.0-beta, but also tried 1.0 with little change
- Function App name: *
- Function name(s) (as appropriate): RunBenchmarks
- Invocation ID: a2f0fa97-9c0c-4649-8f66-a859e035feb5
- Region: Australia East

#### Repro steps

Running a single instance of this function the results returns in ~3seconds
Calling this function multiple times in quick succession will result in response times of 3-30 seconds.
Using artillery or some other load testing software to keep a continuous load on the function then we see response times in the range of 30s - 2minutes.

e.g.
artillery quick --count 500 -n 20 *.azurewebsites.net/api/RunBenchmarks

I have tried:
Setting WEBSITE_HTTPSCALEV2_ENABLED=1
Setting maxConcurrentRequests = 1

#### Expected behavior

Testing an identical function in an AWS lambda we see consistent response times of 600-2500ms no matter what load is put on the endpoint.

**Comment by Francisco-Gamino** [comment]
Hi @grickettsnz,
A lot has changed since this issue was opened in the scale controller and in the Functions Host runtime. If you are still experiencing problems in this area, please reopen a new issue.  Thanks.
