### ISSUE TITLE
CosmosDB extension - failed to install

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-host#3312]
_From @zivraf on August 20, 2018 20:18_

Failed to install the CosmosDB extension for Python 3.6.6 running Windows10
(I managed to repo this on two seperate machines) 

(env) PS <C:\Users\zivr\OneDrive - Microsoft\LocalGit\Functions-Python\ServerlessAzureMgmt>> func extensions install --package Microsoft.Azure.WebJobs.Extensions.CosmosDB --version 3.0.0-beta7
Please specify one package reference to add.
Usage: dotnet add <PROJECT> package [options] <PACKAGE_NAME> 

Python 3.6.6
Functions App core v2

Any thoughts ? 

_Copied from original issue: Azure/azure-functions-python-worker#184_

**Comment by asavaritayal** [comment]
@zivraf can you share your `function.json` file? 

What happens when you run `func extensions install` ? 

/cc @soninaren

**Comment by brettsam** [comment]
A lot has changed since August wrt extension installation. I'm going to close this one out -- please re-open if you come across this issue again.
