### ISSUE TITLE
AzureFunction c# meta class

### ISSUE THREAD

**Issue by grahamehorner** [Azure/azure-functions-host#3321]
the current experience when developing Azure functions the attribution of static classes, methods, property for triggers and binding is somewhat limited when needing multiple triggers of the same code with different function names.

Please consider an alternative method to ease the development cycle via tools to create function.json and/or decorating/generation using code marked with meta classes similar to POCO and data annotation validations.

**Comment by paulbatum** [comment]
Do you think you could post some sample code of what you imagine this looking like? Generally our answer for reusing code between functions is for you to refactor your logic into a shared library that is used by each function. For cases where you need to define a large number of similar functions (perhaps based on some data source), I think code generation is your best bet.

**Comment by grahamehorner** [comment]
public static class AzFunc
{
[AzureFunctionMetaData(TypeOf(A))]
[AzureFunctionMetaData(TypeOf(B))]

    public static async Task EntryPoint(...)
    {   }

}

public class A {
    public string FunctionName { get; set; ) ="AzF01A";
    public Attribute[] Trigger { get; set; } = new Attribute[] { ... }

   public IDictionary<string,Attribute[]> Bindings { get; set; }
}

class A and B would have the same structure & types but with different values for triggers and bindgs ie code as config for creating the function.json 

e.g.where a function has multiple timer schedules or queue triggers with different storage contianer sources/targets but performs the same operations

**Comment by grahamehorner** [comment]
@paulbatum as i understand your suggestion would then introduce the need for exposing the ability of creating function.json server side from a data source? and the need for some type of data source management/tools ? for function registration outside of the code attribution ?

**Comment by paulbatum** [comment]
Well function.json is actually generated for you by the build tools. So I am thinking you could have an automated setup that uses something like T4 to generate the code for your functions based on some data source you have that lists your timer schedules, queues, etc.

I understand that codegeneration is often a less appealing flavor of metaprogramming but I'm trying to think of approaches you can use to make your life easier today as this is not a particularly common feature request and we would not prioritize it any time soon.

**Comment by grahamehorner** [comment]
understood, I will produce something possibly as an extension with example use cases for review; the general idea was that a function shouldn't have a limit on its invocation it should be able to have multiple names with different trigger values and/or binding values that relate to the named function (in a similar way to data annontations) without the need for a developer to create additional folders that contain handcrafted function.json files.

**Comment by paulbatum** [comment]
So one thing to be aware of is that we have other infrastructure that reads these function.json files to figure out what queues to monitor, etc. This allows us to start the function app when there is work to do and it also enables our scaling logic. So even if you found some way deploy these functions without function.json files and have them run, our scaling infrastructure would have issues when it is unable to find those files.

**Comment by grahamehorner** [comment]
I'm thinking I'd add a new FunctionConfigurationAttribute, this could be used to generate the appropriate folder and the function.json for the metadata class and/or function configuration provider at build/run time, the function.json file  "configurationSource" would be set to "config" thus allowing the code to be run under different function names; with different binding attribute values.

can you foresee any issues with this approach ?

**Comment by grahamehorner** [comment]
@paulbatum thanks could you point me in the direction of any github issues related to the issues you have highlighted, and do you know if these are awaiting a review/fix or is the concept of c# functions.json configuration source going to be dropped?

**Comment by paulbatum** [comment]
Take a look at some of the bugs linked from https://github.com/Azure/azure-functions-host/issues/1508 as that was the main change that introduced config source "attributes". Here is one example:
https://github.com/Azure/azure-functions-vs-build-sdk/issues/54

So the gist is that combining "config" with attributes is problematic. Config source "config" is supported for csx and that support will continue because we do not expect attributes to be used in csx.

**Comment by grahamehorner** [comment]
@paulbatum thanks again, I’m now thinking (if possible) that adding custom binding expressions may be the way to go? where a developer can register keywords that supply a value that can be injected into the.binding similar to the datetime,guide etc.

Eg. container/{expr:funcName}/{queueTrigger}
