### ISSUE TITLE
System.Threading.Tasks.TaskCanceledException for substantial number of functions

### ISSUE THREAD

**Issue by zhangruiskyline** [Azure/azure-functions-host#3328]
#### Investigative information

- Timestamp:  example errors happen between 2018-08-26T11:47:43.761 to  2018-08-26T12:19:06.793 UTC
- Function App name: MediationIDsync-Prod-WUS
- Function name(s) (as appropriate): EventhubIDSync
- Invocation ID:   
problems looks same for all failure. some failed operation ids are

003f0830-5624-4abe-9ff2-b088422816a3,
ef3c9c19-4570-41aa-bf07-8e6c6c49e806,
2b6bc52d-83e8-4c9c-bef1-dc96d1212f70
- Region: WUS

#### Stack Trace

[{"parsedStack":[{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":0,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__16.MoveNext","level":1,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":2,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":3,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryExecuteAsync>d__13.MoveNext","level":4,"line":0}],"outerId":"0","message":"Exception while executing function: EventhubIDSync","type":"Microsoft.Azure.WebJobs.Host.FunctionInvocationException","severityLevel":"Error","id":"44302393"},{"parsedStack":[{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Threading.Tasks.Task.ThrowIfExceptional","level":0,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Threading.Tasks.Task`1.GetResultCore","level":1,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Threading.Tasks.Task`1.get_Result","level":2,"line":0},{"assembly":"IDmapping, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","method":"IDmapping.EventhubIDSync.GetSecret","level":3,"line":0},{"assembly":"IDmapping, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","method":"IDmapping.EventhubIDSync+<>c.<.cctor>b__12_0","level":4,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Lazy`1.CreateValue","level":5,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":6,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Lazy`1.get_Value","level":7,"line":0},{"assembly":"IDmapping, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","method":"IDmapping.EventhubIDSync.Run","level":8,"line":0},{"assembly":"Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null","method":"lambda_method","level":9,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`2.InvokeAsync","level":10,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2+<InvokeAsync>d__9.MoveNext","level":11,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":12,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":13,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<InvokeAsync>d__24.MoveNext","level":14,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":15,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":16,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithWatchersAsync>d__23.MoveNext","level":17,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":18,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":19,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__22.MoveNext","level":20,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":21,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":22,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd","level":23,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__16.MoveNext","level":24,"line":0}],"outerId":"44302393","message":"One or more errors occurred.","type":"System.AggregateException","severityLevel":"Error","id":"6221131"},{"outerId":"6221131","message":"A task was canceled.","type":"System.Threading.Tasks.TaskCanceledException","severityLevel":"Error","id":"59827613"}]

#### Expected behavior

Functions runs correctly
#### Actual behavior

around 1% percentage of functions have this System.Threading.Tasks.TaskCanceledException at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw issue. functions triggered and immediately failed (most of them 1-2ms after function trigger)

#### Related information 

Looks like the stack trace this code has failure.

 {"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Threading.Tasks.Task.ThrowIfExceptional","level":0,"line":0}

{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Threading.Tasks.Task`1.GetResultCore","level":1,"line":0}
{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Threading.Tasks.Task`1.get_Result","level":2,"line":0}
 {"assembly":"IDmapping, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","method":"IDmapping.EventhubIDSync.GetSecret","level":3,"line":0}
{"assembly":"IDmapping, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","method":"IDmapping.EventhubIDSync+<>c.<.cctor>b__12_0","level":4,"line":0}

```csharp
        public static string GetSecret(string secretId)
        {
            var secretUri = KeyvaultUrl + '/' + secretId;
            var kvToken = new KeyVaultClient(GetToken);
            var kvSecret = kvToken.GetSecretAsync(secretUri).Result;
            return kvSecret.Value;
        }
```

this problem seems never happen before, until I recently explicitly set Minthread in my code. not sure whether it is related

</details>
-->

**Comment by pragnagopa** [comment]
Is this still an issue? If yes, can you please share invocation ids from the latest failures?
