### ISSUE TITLE
Migrate WebHooks from HttpRequest/ResponseMessage

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#3329]
Currently our WebHook support requires an extension to implement `IAsyncConverter<HttpRequestMessage, HttpResponseMessage>`. In addition to being a little strange as a contract, this requires a conversion layer to convert from HttpRequest/HttpResponse (code [here](https://github.com/Azure/azure-functions-host/blob/86d9664dd0c5637017befa73fdacf6c013363f2b/src/WebJobs.Script.WebHost/Controllers/HostController.cs#L232)). This introduces overhead.

We should move to the new http APIs before GA. We should either:

- Add a new interface that takes an HttpContext. Because the interface needs to live in WebJobs core SDK, it probably shouldn't be http specific - we don't want to bring in http dependencies into core.
- Introduce a convention rather than an interface - the extension would expose an `Action<HttpContext>` handler

**Comment by ConnorMcMahon** [comment]
[This PR](https://github.com/Azure/azure-functions-host/pull/3165) partially addresses this, but I tried to design it to avoid breaking changes. If we wanted to do a hard break on this, we could simplify it considerably.

**Comment by pragnagopa** [comment]
Added 3.x label as this can be a breaking change.

**Comment by ConnorMcMahon** [comment]
This is technically possible to support in a backwards compatible way. [This PR](https://github.com/Azure/azure-functions-host/pull/4391) was rather close, but I abandoned it as I managed to make the changes I needed to within Durable without the changes to the runtime.

I wouldn't completely remove support for HttpRequestMessage and HttpResponseMessage, as the Durable Functions API surface still exposes those types, and I remember running into some difficulties when trying to use `IConverter<HttpRequest, IActionResult>()`, as the [compatibility shim](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.WebApiCompatShim) didn't expose some functionality that would have made it easier.

**Comment by brettsam** [comment]
Trying to triage anything labeled 3.x -- is this on the table for v3.x?

**Comment by ConnorMcMahon** [comment]
I originally thought there was a lot of value here, but after trying it from the Durable side, it seemed to make life harder rather than easier.

My other concern is if we make this a breaking change, that adds complexity to extensions that want to support all the Functions runtime versions.

**Comment by fabiocav** [comment]
Moving this out for now as there are some unintended consequences of doing that as well (it becomes a bit more fragile with the dependency on those types)
