### ISSUE TITLE
Function not triggered automatically

### ISSUE THREAD

**Issue by Geert-V** [Azure/azure-functions-host#3356]
The function I created is not triggered unless I opened the `function.json` in the portal recently.

I created a function using a Visual Studio solution (C#) and deployed it using a Publish Profile to my Azure Function App, which therefore uses `Run-From-Zip` and `WEBSITE_RUN_FROM_ZIP = 1`. Upon sending an event to the event hub, the function is not triggered unless I have opened the `function.json` in the Azure portal recently.

If I open the `Log streaming` functionality of the Function App, then I can see that the host is started when I open the `function.json` file in the portal. Therefore, it appears that the host is is not started automatically and shuts down after a certain amount of time. (The status of the Function App remains equal to `Running`.)

The logging that I see after opening the `function.json` file:
```
2018-08-27T05:57:39.391 [Info] Loaded custom extension 'BotFrameworkConfiguration'
2018-08-27T05:57:39.391 [Info] Loaded custom extension 'SendGridConfiguration'
2018-08-27T05:57:39.407 [Info] Loaded custom extension 'EventGridExtensionConfig'
2018-08-27T05:57:40.516 [Info] registered EventGrid Endpoint = https://<function app name>.azurewebsites.net/admin/extensions/EventGridExtensionConfig
2018-08-27T05:57:41.485 [Info] Generating 1 job function(s)
2018-08-27T05:57:42.829 [Info] Found the following functions:
<Full name of start method>
2018-08-27T05:57:42.829 [Info] Host initialized (7488ms)
2018-08-27T05:57:43.501 [Info] Host lock lease acquired by instance ID '48cfef3239b55a368ed2ccc58b5f6848'.
2018-08-27T05:57:44.361 [Info] Executing HTTP request:
<some successfully HTTP requests related to keys>
2018-08-27T05:57:51.924 [Info] Host started (16586ms)
2018-08-27T05:57:51.924 [Info] Job host started
```

If I sent an event relatively quick after the host has started, then I see:
<pre>
<b>2018-08-27T05:57:54.126</b> [Info,<Function Name>] Function started (Id=d3144b3c-80b4-44e9-a8b7-a3855d5a22e6)
2018-08-27T05:57:54.595 [Info,<Function Name>] Executing '<Function Name>' (Reason='', Id=d3144b3c-80b4-44e9-a8b7-a3855d5a22e6)
2018-08-27T05:57:54.126 [Info] Function started (Id=d3144b3c-80b4-44e9-a8b7-a3855d5a22e6)
2018-08-27T05:57:54.783 [Info] Processing event (1/1).
2018-08-27T05:57:55.423 [Info] Created [...] event [...] date time '<b>2018-08-27T05:56:23.2231822Z</b>'.
2018-08-27T05:57:57.284 [Info,<Function Name>] Function completed (Success, Id=d3144b3c-80b4-44e9-a8b7-a3855d5a22e6, Duration=3133ms)
2018-08-27T05:57:57.345 [Info,<Function Name>] Executed '<Function Name>' (Succeeded, Id=d3144b3c-80b4-44e9-a8b7-a3855d5a22e6)
2018-08-27T05:57:57.284 [Info] Function completed (Success, Id=d3144b3c-80b4-44e9-a8b7-a3855d5a22e6, Duration=3133ms)
</pre>
If you look at both bold timestamps, then you can see that the function was executed as expected. (The date time that is shown is the moment on which the event was instantiated in code. Immediately after instantiation it was sent to the event hub.)

If I wait for some time (without doing or changing anything), then I see messages like this:
```
2018-08-27T05:59:21  No new trace in the past 1 min(s).
2018-08-27T06:00:21  No new trace in the past 2 min(s).
[...]
2018-08-27T06:23:22  No new trace in the past 25 min(s).
2018-08-27T06:24:22  Stream terminated due to timeout 30 min(s).
2018-08-27T06:24:26  Welcome, you are now connected to log-streaming service.
2018-08-27T06:25:26  No new trace in the past 1 min(s).
[...]
2018-08-27T06:53:26  No new trace in the past 29 min(s).
2018-08-27T06:54:26  Stream terminated due to timeout 30 min(s).
2018-08-27T06:54:35  Welcome, you are now connected to log-streaming service.
2018-08-27T06:55:36  No new trace in the past 1 min(s).
[...]
2018-08-27T07:20:36  No new trace in the past 26 min(s).
```
Nothing indicates that the host has been stopped or a function has been triggered. I also don't see any event appearing in the event hub that is the output of the function. However, I did sent an event at approximately `2018-08-27T06:43:55.8911822Z`, as is shown once I open the `function.json` again. By opening the `function.json` file again, I see the same messages that indicate the starting of the host as shown at the top, followed by:
<pre>
<b>2018-08-27T07:21:36.357</b> [Info,<Function Name>] Function started (Id=cd369e99-9d28-4413-a17c-45bf038db81b)
2018-08-27T07:21:36.688 [Info,<Function Name>] Executing '<Function Name>' (Reason='', Id=cd369e99-9d28-4413-a17c-45bf038db81b)
2018-08-27T07:21:36.357 [Info] Function started (Id=cd369e99-9d28-4413-a17c-45bf038db81b)
2018-08-27T07:21:36.919 [Info] Processing event (1/1).
2018-08-27T07:21:37.284 [Info] Created [...] event [...] date time '<b>2018-08-27T06:43:55.8911822Z</b>'.
2018-08-27T07:21:37.863 [Info,<Function Name>] Function completed (Success, Id=cd369e99-9d28-4413-a17c-45bf038db81b, Duration=1488ms)
2018-08-27T07:21:37.904 [Info,<Function Name>] Executed '<Function Name>' (Succeeded, Id=cd369e99-9d28-4413-a17c-45bf038db81b)
2018-08-27T07:21:37.863 [Info] Function completed (Success, Id=cd369e99-9d28-4413-a17c-45bf038db81b, Duration=1488ms)
</pre>
So, the function actually triggered approximately 40 minutes after I created the event in the event hub. Immediately after I opened the `function.json` in the portal again. At this point the event is indeed created in the output event hub.

#### Investigative information
- Timestamp: 2018-08-27T07:21:36.357
- Function App version: 1.0
- Invocation ID: cd369e99-9d28-4413-a17c-45bf038db81b
- Region: West Europe

#### Expected behavior
After sending an event to the event hub, the Azure function should be triggered and run automatically.

#### Actual behavior
The Azure function is not triggered unless I have opened the `function.json` in the portal recently.

#### Known workarounds
1. Open the App Service in the Azure portal.
2. Expand the `Functions` in the left part of the menu.
3. Click the name of the function that is to be run. This opens the `function.json` after some loading.

#### Related information 
- Language: C#
- Created using: Visual Studio
- Deployed with: `Run-From-Zip` using a publishing profile.
- Application Setting: `WEBSITE_RUN_FROM_ZIP = 1`
- Input binding: `[EventHubTrigger]EventData[]`
- Output binding: `[EventHub]IAsyncCollector<EventData>`

**Comment by mikhailshilkov** [comment]
One remark that could help troubleshoot this:

The function is using a non-default consumer group, which used to be a problem but should have been fixed long time ago (?)

Please investigate.

**Comment by forki** [comment]
Not sure if related but we are seeing similar issues with queue trigger on v2. If there is a long pause in queue then function app seems to go idle and needs manual bashing

**Comment by tohling** [comment]
@Geert-V it seems like no triggers were synced for your Function App. The last recorded `TriggerLastModifiedTime` was `08/25/2018 7:58:51 PM UTC`. How was your Function App deployed?

Here is a post on why your triggers may not have sync'ed correctly and how to fix it: https://github.com/Azure/Azure-Functions/issues/210#issue-213933172

Please feel free to reach out if there are still issues and we will help investigate.

**Comment by forki** [comment]
I'm always using functions cli v2 npm version. It should do that
automatically AFAIK. Still see the issue

Ling Toh <notifications@github.com> schrieb am Do., 30. Aug. 2018, 19:28:

**Comment by tohling** [comment]
@forki not sure what if the cause for your Function App. I was only able to investigate @Geert-V 's issue since I had details of the Function App to check out logs. Perhaps you should open another issue to track yours. https://github.com/Azure/azure-functions-host/issues/new Thanks!

**Comment by Geert-V** [comment]
@tohling That is the last time I published the function to Azure. I haven't immediately created this issue, but I had the problem already at that point in time. I don't think it has to do with the publishing method as it does work for small periods of time after opening the `function.json` file in the portal.

For deployment I use the `Publish` functionality in *Visual Studio 217 (Professional)*, with the following publish profile:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <UserName>{username}</UserName>
    <WebPublishMethod>ZipDeploy</WebPublishMethod>
    <PublishProvider>AzureWebSite</PublishProvider>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <SiteUrlToLaunchAfterPublish>http://{function app name}.azurewebsites.net</SiteUrlToLaunchAfterPublish>
    <LaunchSiteAfterPublish>False</LaunchSiteAfterPublish>
    <ResourceId>/subscriptions/{subscription ID}/resourceGroups/{resource group name}/providers/Microsoft.Web/sites/{function app name}</ResourceId>
    <_SavePWD>True</_SavePWD>
    <PublishUrl>https://{function app name}.scm.azurewebsites.net/</PublishUrl>
    <TargetFramework>net462</TargetFramework>
    <SkipExtraFilesOnServer>False</SkipExtraFilesOnServer>
  </PropertyGroup>
</Project>
```
This publish profile was generated by Visual Studio and appears to be working as the function is actually deployed to Azure.

I used the `Refresh` button in the portal, as mentioned in the link that you posted, to synchronize the triggers. This logs similar host starting messages. However, it also results in the same issue after some time has passed. (Events logged to the event hub don't trigger the function.)

**Comment by tohling** [comment]
@Geert-V , I searched our log for the last 5 days and no triggers were sync'ed up to my previous post yesterday. 

Your clicking of the `Refresh `button worked as now I see that 2 attempts were made to sync the triggers were at the following times:

```
2018-08-31 06:02:21.7227061
2018-08-31 06:17:30.1301539
```
Your Function App currently has only 1 EventHub trigger sync'ed for the Function named `****Data***` that is supposed to trigger on `**aw-d***` EventHub and `***data***` consumer group.

However, there is very little traffic on this EventhHub+consumerGroup. Our logs indicate that there was only 1 event detected sporadically since your last successful sync (see log snapshot below).

![geert-v](https://user-images.githubusercontent.com/14911331/44901153-782ee080-acbb-11e8-83e9-e8f9e06b2e4c.PNG)

This would explain why your Function does not execute very often. 

**Additional comments**
Separately, I would like to clarify what is going on when you observe the behavior where you Function is only triggering when you are interacting with it in the Portal. 

For Functions created in Consumption Plan, there is a service called ScaleController that monitors your EventHub 24/7 for new events. The ScaleController's job is to detect the presence of new events, collect metrics on these events and determine if a worker needs to be allocated/deallocated to your Function App (a.k.a. scale out/in operations). Once a worker is allocated, a Function App host process is loaded and all its content (Function App Host runtime code + your Function code) is loaded into the Function App host process and your Function code will executed immediately.  ScaleController will only be aware of your Function's existence if the trigger for your Function is sync'ed with the system.

When you visit the Azure Portal, your Function App has to be forcibly loaded on a worker VM so that you can interact with it, thus by-passing ScaleController. Again, once the Function Host runtime + your Function code is loaded into the host process, your Function code will run immediately start processing those events. 

Once your browser session ends, we will have to rely solely on ScaleController to trigger your Function. Because your Function's trigger was not sync'ed with ScaleController, it will not run until you interact with it in the Portal again.

**Comment by mikhailshilkov** [comment]
@tohling Thanks for thorough explanation. The mail question from my side would be why publishing from Visual Studio doesn't cause the trigger sync? That's probably the most popular way to publish while experimenting with Functions, so it should just work...
Is that related to Run-from-Zip, and its preview status?

**Comment by tohling** [comment]
@mikhailshilkov there is a link that has some follow-up that may shed some light on this, https://github.com/Azure/Azure-Functions/issues/210#issue-213933172

I can follow-up with the team in the morning to see if there are any known issues.

**Comment by Geert-V** [comment]
My bad. If I look in the `Monitor` of the function it actually shows that it did execute. However, the `Log streaming` screen that I had open didn't. So it does appear to be working after I pressed the `Refresh` button. I tried sending another event, which was immediately picked-up and processed.

I'll close the issue for now as it appears to be working as expected. Thanks for the help!
