### ISSUE TITLE
Imperative binding of Service Bus

### ISSUE THREAD

**Issue by KeirSweeney** [Azure/azure-functions-host#3357]
#### Investigative information

- Function App version (1.0 or 2.0-beta): 2.0.1-beta.35
- Microsoft.Azure.WebJobs.ServiceBus : 3.0.0-beta5

#### Repro steps

Send a POST request to the Azure function, tested locally and in Azure. Please see the source for the code that handles the binding.

#### Expected behavior

I should be able to bind ServiceBusAttribute to the IBinder. To allow me to specify a Service Bus Topic at run time.

#### Actual behavior

An exception is thrown and I cannot bind the topic at runtime. It is thrown when we attempt to bind `var collector = await binder.BindAsync<IAsyncCollector<string>>(attribute);`

```
[30/08/2018 13:14:21] PostUser HTTP trigger function processed a request.
[30/08/2018 13:14:21] System.Private.CoreLib: Exception while executing function: PostUser. Microsoft.Azure.WebJobs.Host: No binding found for attribute 'Microsoft.Azure.WebJobs.ServiceBusAttribute'.
[30/08/2018 13:14:21]
[30/08/2018 13:14:21] Executed 'PostUser' (Failed, Id=1e1de564-eb01-4d43-ae36-ca2f07d9954b)
[30/08/2018 13:14:21] System.Private.CoreLib: Exception while executing function: PostUser. Microsoft.Azure.WebJobs.Host: No binding found for attribute 'Microsoft.Azure.WebJobs.ServiceBusAttribute'.
```
#### Related information 

* Programming language used - C# 
* Bindings used - HttpTriggerInputBinding, Service Bus Output binding
<details>
<summary>Source</summary>

```csharp
[FunctionName("PostUser")]
        public static async Task<IActionResult> RunAsyncPost(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = "v1/users")]HttpRequest req,
            TraceWriter log,
            IBinder binder)
        {
            log.Info("PostUser HTTP trigger function processed a request.");

            var requestBody = new StreamReader(req.Body).ReadToEnd();
            var user = User.FromJson(requestBody);

            switch (user.UserMetadata.Brand)
            {
                case BrandEnum.BrandA:
                    var attribute = new ServiceBusAttribute("brandA-users", EntityType.Topic){Connection = "ServiceBusConnection" };
                    var collector = await binder.BindAsync<IAsyncCollector<string>>(attribute);
                    await collector.AddAsync("test");
                    await collector.FlushAsync();
                    break;
                case BrandEnum.BrandB:
                    break;
            }
            return new OkObjectResult("Hello");
        }
```
</details>

**Comment by LukaszFluder** [comment]
Gorzycxki Raciborska 65/3
44-350 Polska

30.08.2018 15:17 "Keir Sweeney" <notifications@github.com> napisał(a):

**Comment by LukaszFluder** [comment]
Łukasz Fluder
Gorzyczki
Raciborska 65/3
44-350
Polska Adress

04.09.2018 11:37 "Keir Sweeney" <notifications@github.com> napisał(a):

**Comment by KeirSweeney** [comment]
After changing from my Laptop to my Desktop, the issue somehow resolved. Not really sure how this happened, however, It is now working
