### ISSUE TITLE
Missing a operation executed log in Monitor

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-functions-host#3358]
#### Investigative information

- Timestamp: 2018-08-30 17:10:10.840
- Function App version: 2.0.12050-alpha
- Function App name: function-v2-test
- Function name(s) (as appropriate): HttpTriggerCSharp1
- Invocation ID: b90f7029-ef92-4de7-b2ca-e69a4596da59
- Region: West US 2

#### Repro steps

1. Create Azure Functions using V2 runtime
2. Add HttpTrigger function
3. Run it

#### Expected behavior

Executed log can be confirmed in Monitor.

```
2018-08-30T17:10:11.431 [Information] Executing 'Functions.HttpTriggerCSharp1' (Reason='This function was programmatically called via the host APIs.', Id=b90f7029-ef92-4de7-b2ca-e69a4596da59)
2018-08-30T17:10:11.472 [Information] C# HTTP trigger function processed a request.
2018-08-30T17:10:11.772 [Information] Executed 'Functions.HttpTriggerCSharp1' (Succeeded, Id=b90f7029-ef92-4de7-b2ca-e69a4596da59)
```

#### Actual behavior

Missing a operation executed log.

![image](https://user-images.githubusercontent.com/1356444/44868036-803f4e00-acc4-11e8-91a2-0c5af713b1e0.png)

#### Related information 

Missing a `operation_Id` and `operation_ParentId` in Executed log

![image](https://user-images.githubusercontent.com/1356444/44868140-e5933f00-acc4-11e8-8538-470868bd9428.png)

**Comment by shibayan** [comment]
When outputting executed log, `Activity.Current` is null.

**Comment by pragnagopa** [comment]
Please let us know if this is still an issue?

**Comment by shibayan** [comment]
I confirmed that the problem was fixed. Thank you.
