### ISSUE TITLE
The host should not go into a running state when there are multiple languages

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#3359]
If a function app has functions from multiple languages and there is no FUNCTIONS_WORKER_RUNTIME setting, then an error will occur saying that we cant load any functions. This behavior is correct. However, when this error occurs it does not prevent the host from starting, and so the experience is that the app is running but no functions are loaded. Instead what should happen is that the host should fail to start, and this should be reported as a host error so that it appears in the portal as an error bubble.

**Comment by fabiocav** [comment]
Closing as completed.
