### ISSUE TITLE
Please provide better information of V2 in wiki

### ISSUE THREAD

**Issue by mkontula** [Azure/azure-functions-host#3366]
While you have more important things in hand than updating the official documentation to match host.json schema, it would be worth mentioning in this page: https://github.com/Azure/azure-functions-host/wiki/host.json-(v2) that the new schema as whole can be found inside this repo here: https://github.com/Azure/azure-functions-host/blob/dev/schemas/json/host.json. The first paragraph is misleading as it states that the schema of elements under extensions would be found from now outdated official documentation.

**Comment by fabiocav** [comment]
@mkontula thank you for the feedback! We have updated the wiki reference and the official documentation [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json) has also been updated. 

Closing this as resolved, but please let us know if you feel this still doesn't address the issue.

Thanks again!
