### ISSUE TITLE
Wrong generation of "extensions.json" file

### ISSUE THREAD

**Issue by Dona278** [Azure/azure-functions-host#3379]
I have a solution with three referenced projects by the main project that contains c# functions (in short, I use Azure functions v2 with compiled c# code)

I've installed these NuGet packages:
- Microsoft.Azure.WebJobs v3.0.0-beta
- Microsoft.Azure.WebJobs.Extensions.Storage v3.0.0-beta8
- Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator v1.0.0

and I have 7 functions (v2) which I called for instance Function 1, Function 2, etc..
Well, if I compile the solution I see into `bin/Debug/netstandard2.0/`
- bin (folder)
- Function 1 (folder)
- Function 2 (folder)
.....
- extensions.json
- host.json
- local.settings.json
- ProjectName.deps.json

It seems to be ok but if I open `extensions.json` I see that it is empty and if I try to execute function I get binding error for the type "queueTrigger". I tried to read the source of the package `Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator` and I saw that it read all *.dll files present into the output path.
So I tried to move the *.dll (relative to the WebJobs extensions) files from `bin/Debug/netstandard2.0/bin` into `bin/Debug/netstandard2.0/` and I launched a new compilation. The result is that the `extensions.json` file now contains
```json
{
  "extensions": [
    {
      "name": "AzureStorage",
      "typeName": "Microsoft.Azure.WebJobs.Extensions.Storage.AzureStorageWebJobsStartup, Microsoft.Azure.WebJobs.Extensions.Storage, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null"
    }
  ]
}
```
At this point if I tried to execute the functions I get the same binding error described above.
As the last I tried to move `extensions.json` file from `bin/Debug/netstandard2.0/` path on which was generated into `bin/Debug/netstandard2.0/bin` and the functions work without any problems!

I think that there is a problem with the path on which `ExtensionsMetadataGenerator` search *.dll files and the path on which the `extensions.json` file is generated / read.

This issue occurre only in local, on the Azure portal I've deployed all functions without problem after updated `host.json` without `extensions.json` file generated somewhere

**Comment by fabiocav** [comment]
How are you compiling your project? through VS? Are you referencing the `Microsoft.NET.Sdk.Functions` package? Do you mind sharing a repro project and steps so we can take a closer look?
Thanks!

**Comment by Dona278** [comment]
@fabiocav sorry, I forgot to write the most important part! Yes I compile function throught Visual Studio (v15.8.2). You can replicate the issue by creating a new function v2 from Visual Studio directly (so without any other projects referenced) without write any other code into the function source file.
This is the result:
FunctionApp3.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.0-beta8" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.0-beta8" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.0.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.19" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```
Function1.cs:
```cs
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Logging;

namespace FunctionApp3
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static void Run([QueueTrigger("myqueue-items", Connection = "MYStorageSetting")]byte[] myQueueItem, ILogger log)
        {
            log.LogInformation($"C# Queue trigger function processed");
        }
    }
}
```
bin folder contents:
![image](https://user-images.githubusercontent.com/10567243/45075134-63e94a00-b0e6-11e8-99b7-8a10084f5305.png)

extensions.json:
```
{
  "extensions":[
  ]
}
```
Azure functions environment:
```
Azure Functions Core Tools (2.0.1-beta.36)
Function Runtime Version: 2.0.12050.0
```

If you execute function from Visual Studio you will get the error
`Function1: The binding type(s) 'queueTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.`

**Comment by bryceba** [comment]
I was getting the same queueTrigger binding error in VS Code. I eventually resolved it by creating a new function app locally using the latest azure function tools. After moving my Functions code to the new function app folder, I was able to locally build and run my functions. I noticed, as you had pointed out, that the extensions.json file of the new function app was in a different location in the bin folder than where it was located in the old function app and the content was populated as expected. That definitely seems to be the problem with trying to move to the new version of the runtime with an existing function app. 

Finally, deploying the new function app folder locally to the existing function app in Azure resolved the issues I was also experiencing running the functions in the cloud.

**Comment by isaac2004** [comment]
This seems to be an issue with dotnet publish, if you dotnet build a functions project, the right extensions.json is created, however if you dotnet publish, it is empty

**Comment by fabiocav** [comment]
@isaac2004 are you just running `dotnet publish` against your project? Do you mind opening a separate issue with the details as this differs a bit from the original problem.

@Dona278 the original issue was opened for an older version of the generator and packages and those issues have been addressed since then, so I'm closing this, but please let us know if you continue to run into problems with the released version and we'll investigate.
