### ISSUE TITLE
Host and worker logs are missing for long durations of time

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#3384]
_From @pambardekar on September 4, 2018 5:49_

#### Investigative information

Please provide the following:

- Timestamp: 2018-09-03T05:24:00.509Z
- Function App version (1.0 or 2.0-beta): 2.0-beta (2.0.12050-alpha)
- Function name(s) (as appropriate): 
- Invocation ID: Operation ID gjlG5NmWiiI= which took ~ 2 minutes to complete at 2018-09-03T17:28:29.876. Host/worker logs around this timestamp are not seen.
- Region: South India

#### Repro steps

My functions are getting used round the clock. I also have a timer function that runs every 4 minutes to keep the function warm. 

#### Expected behavior

Host and worker logs from debug console should be present for the entire duration.

#### Actual behavior

Last log message (in host logs) on Sept 3, 2018 is of timestamp 2018-09-03T05:24:00.509. There is no log message after that for this day. But from Application Insights I can see that the functions are getting executed during this duration. Right now I am debugging intermittent function execution delays. It is not possible to debug it without host or worker logs.

#### Known workarounds

None

#### Related information 

* Programming language used: Node JS
* Links to source
* Bindings used HTTP Trigger

_Copied from original issue: Azure/azure-functions-ux#3069_

**Comment by pragnagopa** [comment]
cc: @mhoeger 
@pambardekar - Please share app name.

**Comment by pambardekar** [comment]
@pragnagopa 

Hello, I am hitting this issue consistently. I cant debug sudden server restarts (which is the real issue), due to missing logs.  App name is plezmoapi-v1.

**Comment by fabiocav** [comment]
@pambardekar are you looking at file logs? Those are not used at runtime, and are only in place to support the log streaming used by the portal.
