### ISSUE TITLE
Cannot run EventGrid triggered function locally anymore

### ISSUE THREAD

**Issue by Zordid** [Azure/azure-functions-host#3387]
Since the latest update, our FA that uses EventGrid Trigger simply won't execute locally.

When you sent an event using Postman (Header: Content/Type: application/json and aeg-event-type: Notification) the local log of the FA says:

```
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
Listening on http://0.0.0.0:7071/
Hit CTRL-C to exit...
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "ExtensionWebHookHandler", controller = "Host"}. Executing action Microsoft.Azure.WebJobs.Script.WebHost.Controllers.HostController.ExtensionWebHookHandler (Microsoft.Azure.WebJobs.Script.WebHost)
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Microsoft.Azure.WebJobs.Script.WebHost.Controllers.HostController.ExtensionWebHookHandler (Microsoft.Azure.WebJobs.Script.WebHost) with arguments (EventGridExtensionConfig, System.Threading.CancellationToken, Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptWebHookProvider) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method Microsoft.Azure.WebJobs.Script.WebHost.Controllers.HostController.ExtensionWebHookHandler (Microsoft.Azure.WebJobs.Script.WebHost), returned result Microsoft.AspNetCore.Mvc.NotFoundResult in 4.8802ms.
[05.09.2018 12:02:51] Executing HttpStatusCodeResult, setting HTTP status code 404
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Microsoft.Azure.WebJobs.Script.WebHost.Controllers.HostController.ExtensionWebHookHandler (Microsoft.Azure.WebJobs.Script.WebHost) in 338.9936ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2121.0703ms 404
info: Microsoft.AspNetCore.Server.Kestrel[32]
      Connection id "0HLGJ4U00GVOJ", Request id "0HLGJ4U00GVOJ:00000001": the application completed without reading the entire request body.
[05.09.2018 12:02:56] Host lock lease acquired by instance ID '000000000000000000000000F452E89C'.

```

This happens as well when I create a completely new Project from scratch. Create an Azure Functions project without a function (because EventGrid Trigger is missing in the first wizard...), then in the project Add / New Azure Function... / Event Grid trigger - leave everything as is and start the Function App locally.

This is the generated function code:
```
    public static class Function1
    {
        [FunctionName("Function1")]
        public static void Run([EventGridTrigger]EventGridEvent eventGridEvent, ILogger log)
        {
            log.LogInformation(eventGridEvent.Data.ToString());
        }
    }
```

Try to send a request to the URL.

- Function App version: 2.0-beta
- Trigger: Event Grid trigger

Your function method will not run.

Instead I see these two interesting pieces in the log:
`Executed action method Microsoft.Azure.WebJobs.Script.WebHost.Controllers.HostController.ExtensionWebHookHandler (Microsoft.Azure.WebJobs.Script.WebHost), returned result Microsoft.AspNetCore.Mvc.NotFoundResult in 4.8802ms.
`
and this one:
`Connection id "0HLGJ4U00GVOJ", Request id "0HLGJ4U00GVOJ:00000001": the application completed without reading the entire request body.`

Why is that and what should I do?

**Comment by sigbjornlo** [comment]
What URL are you posting to?

With the release of function host version 2.0.1.12050 and associated supporting packages, the endpoint for EventGridTriggered functions changed from:

http://localhost:7071/runtime/webhooks/EventGridExtensionConfig?functionName={FunctionName}

to 

https://localhost:7071/runtime/webhooks/eventgrid?functionName={FunctionName}

**Comment by Zordid** [comment]
Where on earth did you get this information? I was not informed about this anywhere. This is a breaking major change.

How should one derive this from the log I provided? Could the logging be any worse?

Thank you so much!

**Comment by sebader** [comment]
The logging actually contains the information ;-) Just a bit above the part that you posted above.

> Azure Functions Core Tools (2.0.1-beta.38)
Function Runtime Version: 2.0.12050.0
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\xxxx\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Host.Startup[0]
      Reading host configuration file 'C:\Users\xxxx\source\repos\TestEventGridFunction\TestEventGridFunction\bin\Debug\netstandard2.0\host.json'
info: Host.Startup[0]
      Host configuration file read:
      {
        "version": "2.0"
      }
[07.09.2018 10:31:37] Initializing Host.
[07.09.2018 10:31:37] Host initialization: ConsecutiveErrors=0, StartupCount=1
[07.09.2018 10:31:42] registered EventGrid Endpoint = https://0.0.0.0:7071/runtime/webhooks/eventgrid
[07.09.2018 10:31:42] Starting JobHost
[07.09.2018 10:31:42] Starting Host (HostId=sbsurfaceb-359680194, InstanceId=64ea5294-2576-4113-95da-bc88057a3957, Version=2.0.12050.0, ProcessId=33424, AppDomainId=1, Debug=False, FunctionsExtensionVersion=)
[07.09.2018 10:31:42] Generating 1 job function(s)
[07.09.2018 10:31:43] Found the following functions:
[07.09.2018 10:31:43] TestEventGridFunction.Function1.EvaluateRules
[07.09.2018 10:31:43]
[07.09.2018 10:31:43] Host initialized (807ms)
[07.09.2018 10:31:43] Host started (836ms)
[07.09.2018 10:31:43] Job host started
Hosting environment: Production
Content root path: C:\Users\xxxxx\source\repos\TestEventGridFunction\TestEventGridFunction\bin\Debug\netstandard2.0
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
Listening on http://0.0.0.0:7071/
Hit CTRL-C to exit...
[07.09.2018 10:31:48] Host lock lease acquired by instance ID '0000000000000000000000009007D9B5'.
