### ISSUE TITLE
Provide a way to see raw logging

### ISSUE THREAD

**Issue by arichiardi** [Azure/azure-functions-host#3389]
Hi all!

We follow the 12-factor Logging principle here at my company and just stream JSON payloads to stdout using `bunyan` on node. Bunyan or other tools do the aggregation downstream usually.
Now, when I tail the output of `func host start`, I see:

```
Hit CTRL-C to exit...

Http Functions:

	commit-event: http://localhost:3000/api/commit-event

[9/5/18 4:17:29 PM] Worker 187fe3fb-b0a3-405e-9a32-122872fff941 connecting on 127.0.0.1:35855 []
[9/5/18 4:17:30 PM] Loading environment variables...
[9/5/18 4:17:31 PM] {"name":"registry","hostname":"...","pid":14368,"...,"time":"2018-09-05T16:17:31.113Z","v":0}
```

Bunyan can display correctly non-JSON payloads, but identifies them probably with some heuristic that does not detect the last as JSON (I can understand why actually).

I am here to ask if and where to start looking for adding an option that disable the dates (e.g.: `[9/5/18 4:17:31 PM]`) emitted by the logger.

#### Investigative information

Please provide the following:

- Function App version (1.0 or 2.0-beta): `2.0-beta`

Thank you very much for you answers in advance!

**Comment by arichiardi** [comment]
Any hint/comment on this, I really would like to contribute this feature but need some ack/hint :smile:

**Comment by arichiardi** [comment]
I am digging in some deep corner of ASP.net looking for needle. Not an ASP.net dev and I might misunderstanding this but maybe an option would be to turn off any custom log formatter (if any) or allow to modify them somehow?

I was reading basically this: https://github.com/aspnet/Logging/issues/483

**Comment by arichiardi** [comment]
I might have found the needle - https://github.com/Stonefinch/AzureWebServerLogsToSql/blob/master/README.md

**Comment by arichiardi** [comment]
Also this is useful but I wonder if Serilog would help me here and how to install it: https://andrewlock.net/writing-logs-to-elasticsearch-with-fluentd-using-serilog-in-asp-net-core/

**Comment by arichiardi** [comment]
After some more digging I ended up here: can this be the place that needs tweaking? Seeking confirmation.

https://github.com/Azure/azure-functions-host/blob/master/src/WebJobs.Script/Diagnostics/FileLogger.cs

**Comment by arichiardi** [comment]
After some more digging I ended up here: can this be the place that needs tweaking? Seeking confirmation.

https://github.com/Azure/azure-functions-host/blob/master/src/WebJobs.Script/Diagnostics/FileLogger.cs

**Comment by arichiardi** [comment]
FIY, This is the workaround I found, which is a hack:

```shell
func host start |  sed -e 's/\[.*\][ \t]*/''/g' | yarn bunyan
```

**Comment by pragnagopa** [comment]
@brettsam - can we support this?

**Comment by brettsam** [comment]
Your best bet is to use our [new DI functionality](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#register-services) and wire up an ILoggerProvider that sends logs wherever you want. You can do 
```
builder.Services.AddLogging(b =>
{
   // register your logger provider here.
});
```
We use the .NET Core logging system so this should be a good starting point: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#add-providers

**Comment by brettsam** [comment]
This was pretty old so I'm going to mark this as closed, but let me know if you need more help. Feel free to re-activate if needed.
