### ISSUE TITLE
Async Javascript functions timeout unless done is called

### ISSUE THREAD

**Issue by hoovercj** [Azure/azure-functions-host#3391]
Continuing conversation from #3363.

[Source repo](https://github.com/hoovercj/strava-weather-azure-functions)

After the latest host update, my javascript functions began timing out due to "done" not being called automatically for async functions. I can show 3 async scenarios, only 1 of which works.

I would expect all 3 to work based on [the docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#contextdone-method) which say 

> If your function uses the async function declaration (available using Node 8+ in Functions version 2.x), you do not need to use `context.done()`. The `context.done` callback is implicitly called.

#### Investigative information

- Timestamp: 2018-09-05 16:13:18.681 (around this time)
- Function App version (1.0 or 2.0-beta): beta
- Function App name: strava-weather (slot: test)
- Function name(s) (as appropriate): [wakeup](https://github.com/hoovercj/strava-weather-azure-functions/tree/master/wakeup), [get-processed-activities](https://github.com/hoovercj/strava-weather-azure-functions/tree/master/get-processed-activities), (and every other function)
- Invocation ID:  r2orhyYJt6Y= (However, Azure portal does not show any of the timed out invocations here)
- Region: East US
- Node Version: 10.6.0

#### Repro steps

I will note that I am writing in typescript and was previously targeting es6, but I've switched to targeting es2018 for this so that the output is cleaner. The code below is the generated javascript that the functions are running.

## Scenario 1: Don't call done, return promise
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
async function run(context, req) {
    context.res = {
        status: 200,
        body: '',
    };
    return Promise.resolve();
}
exports.run = run;
```

This worked before upgrading to the newest runtime. Why am I returning a promise? At the time, I thought all async functions had to return promises. Apparently that is false. But the important thing is, this code worked before and now it doesn't.

## Scenario 2: Don't call done, don't return anything
```
Object.defineProperty(exports, "__esModule", { value: true });
async function run(context, req) {
    context.res = {
        status: 200,
        body: '',
    };
}
exports.run = run;
```
I thought that perhaps the extra promise I was returning was causing problems so I removed it. It did not fix things. 

I would expect this scenario to work. It is my preferred scenario.

## Scenario 3: Call done, don't return anything
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
async function run(context, req) {
    context.res = {
        status: 200,
        body: '',
    };
    context.done();
}
exports.run = run;
```

This scenario is the only one that works. I thought I had issues in an earlier runtime where calling done in an async function resulted in an exception with done being called twice but I am not getting that now. Perhaps that is because the new version is not actually calling done for async functions at all, and if that bug is fixed than this code will again start throwing exceptions.

**Edit:** Added links to source code.

**Comment by ltouro** [comment]
@hoovercj are you using funcpack? Just noted that my func behaviour is different it. 

Below, the function only call ```context.done``` without funcpack. 
```
const service = {};

service.doSomething = function() {
  return new Promise(function(f) {
    f();
  });
};

module.exports = function(context) {
  return service
    .doSomething()
    .then(() => {
      context.log('done.');
    })
    .catch(function(err) {
      context.log('err' + err);
    });
};
```

**Comment by ygnr** [comment]
Facing same issue after upgrading to latest version. It used to work previously. I have my code according to Scenario 1. @hoovercj Were you able to find a work around?

**Comment by hoovercj** [comment]
@ygnr call done and don't return a promise.

**Comment by ygnr** [comment]
@hoovercj Thanks! Yep got it working by calling done instead of returning promise.

**Comment by hoovercj** [comment]
Glad it worked.

It looks like [this code](https://github.com/Azure/azure-functions-nodejs-worker/blob/0096e92863bee72341346c00af93d4dc0e29037e/src/WorkerChannel.ts#L151) is where done is being called for functions which return a promise.

Hopefully @mhoeger can clarify if [azure-functions-nodejs-worker](https://github.com/Azure/azure-functions-nodejs-worker/tree/0096e92863bee72341346c00af93d4dc0e29037e) is still being used or if the new runtime is backed by a different worker which doesn't share this functionality.

**Comment by mhoeger** [comment]
@hoovercj - thanks for the detailed issue, this was a bug introduced when I added support for using 'this' in user code (original issue here: https://github.com/Azure/azure-functions-nodejs-worker/issues/37).

Huge thanks to @irnc who put out [a PR](https://github.com/Azure/azure-functions-nodejs-worker/pull/127) to resolve this issue. I'm going to pull this change through to the functions host, and the new bits will be deployed this week.

**Comment by mhoeger** [comment]
Closing this issue as an updated version with the fix has been deployed.
