### ISSUE TITLE
2.0 javascript function: eventhubtrigger binding type not registered

### ISSUE THREAD

**Issue by larsonmpdx** [Azure/azure-functions-host#3396]
#### Investigative information
![image](https://user-images.githubusercontent.com/12436438/45112861-b2561300-b0fd-11e8-9f72-6119267080c5.png)
I tried installing the extension by adding a new function with an event hub binding, but the install button doesn't do anything
![image](https://user-images.githubusercontent.com/12436438/45113648-c4d14c00-b0ff-11e8-8bc5-46c497b6f5a8.png)

- Timestamp: this error prevents any invocations
- Function App version (1.0 or 2.0-beta): 2.0-beta
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: this error prevents any invocations
- Region: us east 2

#### Repro steps
set up a windows 2.0 function and upload a javascript function with bindings similar to this:

```
{
  "bindings": [
    {
      "type": "eventHubTrigger",
      "name": "eventHubMessages",
      "direction": "in",
      "path": "iothub",
      "connection": "[generated name after setting up binding]",
      "cardinality": "many",
      "consumerGroup": "intake",
      "eventHubName": "unused"
    }
  ]
}
```

#### Expected behavior
function is invoked by iot hub events.  I don't want to have to manually set up this binding type, or if I do I don't want to have to refresh it when it hiccups.

#### Actual behavior
not invoked, and a warning about the binding type being missing

#### Known workarounds
it worked last week after I got lucky installing the extension through the web portal (the install button in the above screenshot worked)

**Comment by larsonmpdx** [comment]
saw this page, got logs from kudu
https://github.com/Azure/azure-functions-host/wiki/Updating-your-App-(portal)

````
{"Id":"91e4914c-1ce0-4317-b765-876529c82dfa","Status":1,"StartTime":"2018-08-21T03:45:00.4347064+00:00","EndTime":"2018-08-21T03:45:38.1946073+00:00","Error":null,"Properties":{"id":"Microsoft.Azure.WebJobs.Extensions.EventHubs","version":"3.0.0-beta5"}}
````

tried a fresh host and the install button hung with a new error:

![image](https://user-images.githubusercontent.com/12436438/45235160-dac04780-b28c-11e8-8620-a5665095ddee.png)

**Comment by larsonmpdx** [comment]
I updated extensions using the instructions in the above link and the warnings went away but the function doesn't trigger.  I get 503 service unavailable now when trying a test run with the "run" button

**Comment by paulbatum** [comment]
@soninaren can you take a look at this?

**Comment by pandres95** [comment]
I got the same error as @larsonmpdx. Created a new function today and copied code, but still doesn't work.

**Comment by larsonmpdx** [comment]
I won't be much help at this point, I only needed runtime 2.0 for a higher javascript version and I switched to runtime 1.0 with a simple babel setup instead

**Comment by pandres95** [comment]
Actually, I solved that [error](https://github.com/Azure/azure-functions-host/issues/3396#issuecomment-425263431) by deleting `app_offline.htm`. This is a file related to #3269 and I guess it should be accordingly documented.

> I got the same error as @larsonmpdx. Created a new function today and copied code, but still doesn't work.
> 
> > I updated extensions using the instructions in the above link and the warnings went away but the function doesn't trigger. I get 503 service unavailable now when trying a test run with the "run" button

**Comment by soninaren** [comment]
@pandres95  Thank you for reporting this back. There were a few issues with extension installation, that have been resolved as a part of V2 GA release. The portal and runtime should not cause anymore installation issues. Please re-open or create another issue if you still run into installation issues.
