### ISSUE TITLE
Function App secrets storage change.. When ?

### ISSUE THREAD

**Issue by jepzen** [Azure/azure-functions-host#3398]
Im reading this section in the breaking changes announcement (https://github.com/Azure/app-service-announcements/issues/129)

> Function App secrets storage change

> Function App secrets (function, system and master keys) will be stored in blob storage by default.

> Previously they were stored in the file system and we are automatically migrating them to blob storage as part of this change, so keys should not change, but if you relied on direct file access or SCM APIs to manage those secrets, that will no longer work.

I am depending on that I can obtain the keys through the solution provided here 

https://stackoverflow.com/questions/51492408/retreive-the-host-key-from-within-my-azure-function

If the host keys are moved to Blob Storage I suspect I need to change the way of obtaining them?

Can you confirm or not if this will break and if it will break when  will the "automatically migration" occur?

I updated the runtime to  2.0.12050 and the SDK.Functions to 1.0.19 and so far it still working

**Comment by mathewc** [comment]
The keys APIs that you referenced will continue to work. Just the backing default store has changed for the keys. You say you have already migrated to 2.0 - as part of your upgrade to 2.0 we migrated your keys from file storage to Azure storage. If you look in the storage account for your Function App you should see a new blob container containing your keys.
