### ISSUE TITLE
Issues with Queue triggers - 2.0.12050.0

### ISSUE THREAD

**Issue by trydis** [Azure/azure-functions-host#3403]
We're experiencing issues with queue triggers after upgrading to the latest version.

New queue messages are not detected by the functions until we restart the app.

Platform: .NET

**Comment by mathewc** [comment]
I think this is caused by https://github.com/Azure/azure-webjobs-sdk/issues/1869

**Comment by trydis** [comment]
That only affects things when running locally? We're experiencing it when running in Azure. Messages are still queued after 30+ minutes.

**Comment by mathewc** [comment]
Ah then you have a different problem - the issue I linked to would only cause delays of up to 2 minutes.

Can you share your app name using [these instructions](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately) and provide a timestamp of when you're seeing this?

**Comment by trydis** [comment]
2018-09-07T06:49:34.550, Id=9c990054-9a40-4da9-91f6-f888b016ae8d

A test message was "stuck" in the queue at that time.

**Comment by trydis** [comment]
Couldn't wait any longer, so we ended up deleting the function app. Will try to recreate it and see if that helps.

**Comment by trydis** [comment]
Pinning to `2.0.11961-alpha` and reverting the changes needed for `2.0.12050.0` fixed the issues. 

Not sure if it's a bug in `2.0.12050.0` or if it's some other combination of things...

**Comment by trydis** [comment]
Another observation is that Application Insights seems to be working again as well. When running 
 `2.0.12050.0` things would be visible in the filesystem logs, but not in the portal.

**Comment by trydis** [comment]
We recreated everything running on 2.0.12115.0 and initial tests are 👍, so I'm closing this.
