### ISSUE TITLE
Node version cannot be changed in Linux Function App

### ISSUE THREAD

**Issue by hxlnt** [Azure/azure-functions-host#3406]
- Function type: Hosted Linux Function App (not Docker)
- Function App version: 2.0.00001.0 (beta)
- Region: East US

#### Repro steps

1. Create a Linux Function App and JavaScript TimerTrigger function from the Azure Portal.
2. Change WEBSITE_NODE_DEFAULT_VERSION to a different value such as 8.0.0, 8.1.0, or 10.1.0 and hit Save.

![ss1](https://user-images.githubusercontent.com/9647195/45180432-01c13f80-b1e1-11e8-90c1-df3bf076b76f.png)

#### Expected behavior

Function should run in specified version of Node.

#### Actual behavior

Function is executed in Node v. 6.11.0 as confirmed by the function failing on an async method (not supported in Node v. 6.x.x) and by running `node -v` in the console.

![ss2](https://user-images.githubusercontent.com/9647195/45180445-0a197a80-b1e1-11e8-8da3-fd682d4cb2d9.png)

This works in Windows Functions but not Linux Functions. This is a big blocker for being able to use Linux Functions.

#### More investigation

Using the console, I am able to see that multiple versions of Node exist in `/opt/nodejs`, but Node 6.11 is on $PATH, and node symlink points to Node 6.11.0 despite updating Node version in App Settings.

![ss4](https://user-images.githubusercontent.com/9647195/45180505-3cc37300-b1e1-11e8-935c-58bee803cc36.png)

Perhaps related: When digging into the settings, I can see that the container behind the Linux App has the correct Node version passed in at the time of `docker run`, but it is built on a deprecated Azure Functions base image (https://hub.docker.com/r/microsoft/azure-functions-runtime/).

**Comment by hxlnt** [comment]
Update: I tried building a Docker-based Function, and was also unable to update the Node version. I used `microsoft/azure-functions-node8` as the base image this time, yet `node -v` on Kudu console still returns Node version 6. I'm puzzled.

**Comment by mhoeger** [comment]
@hxlnt - if your v2 function app is running, it definitely isn't using node 6 (node 6.x is not supported in v2). Can you try adding `context.log(process.version);` to see what node version you are actually running?

@dariagrigoriu - this feels like a UI / expectation bug in linux. Could you weigh in please?

**Comment by hxlnt** [comment]
After experimenting with a few things this week, here's what I found:

- In a Linux hosted Function, the Node version as set in App Settings is respected only after the platform is switched from 32-bit to 64-bit. When the function is using the version 2 runtime and remains in 32-bit mode, the console will report the wrong version of Node, and `context.log(process.version)` does not produce any result. (Instead, I just see a notice that the process was started and then that the process was terminated.)

- There seem to be some bugs with the Azure Functions Portal UI in Edge. Switching to Chrome, while probably unrelated to this issue, helped. It seems not possible at the present time to create a new Function through the Portal in Edge.

So, my immediate issue is resolved. However, I wonder if there's some incompatibility between the version 2 runtime and the 32-bit setting, which was the default. If so, this might be worth investigating.

**Comment by hxlnt** [comment]
(Deleted previous comment, as I was mistakenly referring to a previously-built Windows Function.)

I deleted my previous Linux hosted function and have not been able to create a new function all week to do the testing you recommend. I can create the app, just not a new function within it.

I've been getting error messages like this:
![capture3](https://user-images.githubusercontent.com/9647195/45392238-05433500-b5ec-11e8-8093-e1bda5f9cc75.PNG)

The browser dev tools are showing dozens of 404s. Have tested in both Edge and Chrome, logged in and out of the Portal, restarted the app, created a whole new app... same results each time.

**Comment by hxlnt** [comment]
I created another Linux hosted Node.js function in the portal. The Hello World sample does not run or show anything in the logs/console. (Adding `context.log(process.version);` doesn't yield any result, since the function doesn't run properly.) The page flashes a lot and racks up lots of 500 server errors. 

If Node v6 is indeed running (which is indicated via `node --version` in the console), it does not support `async`, which is part of the sample.

```
module.exports = async function (context, myTimer) {
…
}
```

To recreate this issue, simply create a Linux Node.js function and run the sample function provided.

**Comment by mhoeger** [comment]
Hi @hxlnt - I'm not able to repro your issue, although it should be noted that `node --version` deceptively returns v6.11.0, although logging process.version in my function app returns v8.12.0. (@bala16 for comments on this mismatch in expectation).

Can you provide more exact details? For my repro attempt, I created a Linux OS function using an App Service plan. Runtime stack = JavaScript and Publish = Code. I then created a plane HTTP-triggered function (next, a timer-triggered function). Did you do anything different from this? 

I believe your issue is not related to node version, as changing and deleting the app setting on this brand new linux app does nothing to the node version.

**Comment by hxlnt** [comment]
That said, why can't I access Node v.8 at the console? When I run my function in the console via `node index.js`, I get an error on async, presumably because of the node version.

![nodefail](https://user-images.githubusercontent.com/9647195/46435330-bafd3180-c71b-11e8-90ac-e146fd022768.png)

**Comment by mhoeger** [comment]
@bala16 - reassigning to you since I don't have as much context. This issue is mainly about confusion around node versions in a Linux function app:
- WEBSITE_NODE_DEFAULT_VERSION does not work for Linux
-  `node --version` deceptively returns v6.11.0, although logging process.version in my function app returns v8.12.0 (it's a bit confusing if the two should match)

**Comment by balag0** [comment]
Prerequisite:  https://github.com/Azure/azure-functions-host/issues/4476

**Comment by benc-uk** [comment]
Still an issue in 2020, any progress or workaround we can use
Node v8 is *ancient* and out of support

**Comment by mhoeger** [comment]
@pragnagopa do you know what the status of UI plans were for Node version selection? 
cc: @dariagrigoriu

**Comment by pragnagopa** [comment]
Backend changes needed to portal updates are currently in progress. Until tooling is updated, To use node 10, for consumption apps, please use [resource explorer](https://www.hanselman.com/blog/IntroducingAzureResourceExplorerForTheAzureResourceManagementAPIs.aspx) or ARM template and update `linuxFxVersion` site config property to `node|10`

**Comment by pragnagopa** [comment]
related issue - https://github.com/Azure/azure-functions-host/issues/4948

**Comment by benc-uk** [comment]
I found another soluton:

From the portal go to the container settings, from there change the image tag.  
The major snag, is getting the supported & available tag names of the various supported Node versions, I had to go here https://mcr.microsoft.com/v2/azure-functions/node/tags/list to list them all and pick one

As a user experience it's horrific. The resource explorer option is about the same on the user friendliness scale :(

**Comment by PriceChild** [comment]
To clarify, updating `linuxFxVersion` will only work for linux app services on consumption based plans and not those on app services/ise's?

**Comment by pragnagopa** [comment]
cc @ankitkumarr 

@PriceChild - Updating linuxFxVersion should work for all Skus. Closing this issue as all the backend changes are deployed. Please reopen if you still cannot update node version by udpating linuxFxVersion.

**Comment by PriceChild** [comment]
Thanks @pragnagopa I'll give it a go.

I'm surprised the ticket has been closed though - is it not still a bug that the standard setting `WEBSITE_NODE_DEFAULT_VERSION` (documented [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#node-version)) can't be used on Linux apps?

Or should I raise bugs/pr's on those documentation pages that they need to add these extra settings and mark the originals as not working for Linux hosts?

**Comment by pragnagopa** [comment]
We do not intend to support  app setting `WEBSITE_NODE_DEFAULT_VERSION` for linux Apps. Please do open doc issues. Thanks!
