### ISSUE TITLE
Not clear how to make Functions extension model to work again after beta breaking changes

### ISSUE THREAD

**Issue by jdvor** [Azure/azure-functions-host#3410]
#### Context

Related to breaking changes in extension model announced [here](https://github.com/Azure/app-service-announcements/issues/129)
It basically requires update of `Microsoft.NET.Sdk.Functions`, `Microsoft.Azure.WebJobs.Host` and in some cases (not in ours as **we do not use blob, queue, or table binding**) installing new dependencies. Details are [here](https://github.com/Azure/azure-functions-host/wiki/Updating-your-App-(portal)#update-your-extensions).

#### Issue

However the pre-scribed package update does not seem to be sufficient. From version **2.0.12050.0** of the Function Runtime the implementation of `Microsoft.Azure.WebJobs.Host.Config.IExtensionConfigProvider.Initialize(ExtensionConfigContext context)` **is not invoked** thus rendering the extension model unusable.

**DOES NOT WORK:**
Azure Functions Core Tools 2.0.1-beta.36
Function Runtime Version **2.0.12050.0** (locally after update forced by VS) or `FUNCTIONS_EXTENSION_VERSION = ~2` (in Azure environment)

**WORKS:**
When runtime is downgraded to following, it will invoke implementation of `IExtensionConfigProvider.Initialize` successfuly:
Azure Functions Core Tools 2.0.1-beta.35
Function Runtime Version: **2.0.11960.0** or FUNCTIONS_EXTENSION_VERSION = 2.0.11961-alpha (in Azure environment)

The issue affects both already deployed functions when the runtime upgrade is attempted by setting environment variable FUNCTIONS_EXTENSION_VERSION or during local development, when the runtime upgrade is **forced** by Visual Studio.

Relevant (installed) nuget packages in the solution:
Microsoft.Azure.WebJobs.Host **3.0.0-beta8**
Microsoft.NET.Sdk.Functions **1.0.19**

#### Investigative information

Please provide the following:

- Timestamp: 2018-09-07T09:25:14.6589003Z
- Function App version (1.0 or 2.0-beta): 2.0.1-beta.36
- Function App name: SmartGridApiStage
- Function name(s) (as appropriate): GetDeviceInfo
- Region: West Europe

#### Known workarounds

- with FUNCTIONS_EXTENSION_VERSION stay at 2.* alpha releases; this is a temporary solution as alphas will not be available infinitely

**Comment by robdmoore** [comment]
See https://github.com/Azure/app-service-announcements-discussions/issues/64

**Comment by robdmoore** [comment]
See also https://github.com/Azure/azure-functions-host/issues/3386
