### ISSUE TITLE
Do not restart language worker processes as part scripthost restarts

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#3415]
LangaugeWorkers are initialized inside scriptHost
https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Host/ScriptHost.cs#L262

This results in language worker processes restarting when scripthost restart for example, when user updates function code.

**Comment by mhoeger** [comment]
This also causes functions host to crash on file save when debugging node functions: https://github.com/Azure/azure-functions-host/issues/3543

**Comment by alrod** [comment]
Customer report:
https://stackoverflow.com/questions/53599053/azure-process-terminates-when-javascript-function-is-changed

**Comment by fabiocav** [comment]
@jeffhollan @pragnagopa @mhoeger  Assigning this as a P1, but this issue should be addressed by the placeholder work being done, so it would make sense to close this in favor of the issues tracking that work if we want to go that route.

**Comment by ahmedelnably** [comment]
Closing per @fabiocav comment
