### ISSUE TITLE
Dependency Call Failures in App Insights for V2 C# HttpTrigger

### ISSUE THREAD

**Issue by bcnzer** [Azure/azure-functions-host#3417]
Under load, a V2 Azure Function HTTP Trigger (written in C#) will log a slew of Dependency Call Failure Rate messages in Application Insights. 

According to App Insights, once traffic has completely stopped it will continue to emit 1 Dependency Call Failure per second for about 23 minutes. 

Note that I don't see any issues in the function's Monitor tab and, while this is happening, I often can't publish my app.

![2018-09-08_16-24-59](https://user-images.githubusercontent.com/13621876/45250387-13901780-b386-11e8-9b23-8158361a616c.png)

It emits a variety of errors the but the one that shows up after the traffic has stopped is a 409

![image](https://user-images.githubusercontent.com/13621876/45252010-329da200-b3a4-11e8-9e34-62ef8b605c20.png)

#### Investigative information
- Timestamp: 2018-09-08 04:23:24.128
- Function App version (1.0 or 2.0-beta): 2.0.1-beta.38
- Function App name: dependencyrepro
- Function name(s) (as appropriate): Function1
- Invocation ID: 5089fade-61ea-425d-907c-fcbd1638ac69
- Region: Australia South East

#### Repro steps
Summary: create a new AF in the portal and a sample project
1. Setup a brand new Function app in Azure with Application Insights
2. Create a branch new v2 C# Azure Function project in Visual Studio (v15.8.3 using the latest runtime 2.0.12050.0)
3. Create an HTTP trigger called `Function1`. I simplified it
```csharp
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;

namespace FunctionApp2
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static IActionResult Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequest req, ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            return new OkObjectResult("hi");
        }
    }
}
```
4. Right-click Publish to the app you created to your Function App. You'll be asked to Update Functions Version on Azure. Click Yes
5. Go into the portal, open your function app and find your function to get the URL
6. Go into Application Insights, Live Metrics stream
7. Send some load to your URL. I was using artillery.io. My script is below

#### Expected behavior
I expected my application to run without Application Insights identifying these Dependency failures. 

It doesn't happen with v1 functions.

#### Actual behavior
Once the app gets under a non-trivial amount of load, the Dependency Call Failures start mounting. Long after traffic stops, there's a steady one dependency call failure per second for 23+ minutes. 

#### Known workarounds
No known workaround

#### Related information 
* The function project is written in C#
* I used [artillery.io](https://artillery.io/) to create this basic load script. Over 10 seconds it simulates three users hitting the URL once per second (aka 30 hits in 10 seconds)
```
config:
  target: 'https://dependencyrepro.azurewebsites.net/api'
  phases:
    - duration: 10
      arrivalRate: 3
      name: "Sustained max load"
scenarios:
  - flow:
    - get:
        url: "/Function1?code=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=="
```

**Comment by brettsam** [comment]
We've enabled dependency tracking with v2, which is where these are coming from. The failures you're seeing are (usually) background host-level storage calls that return error codes that App Insights treats as errors. They've always been there, but we've never tracked them as dependencies like this in the past.

For example, a host attempting to grab a lease will return a 409 if it's already taken. Or checking if a blob exists can return a 404 or a 409 (depending on the client implementation). These are perfectly normal in the context of the call, but App Insights doesn't know this and reports them as failures.

They're nothing to worry about, but they are ugly and we're looking at ways to suppress them. I'm going to close this as we're tracking it over at https://github.com/Azure/azure-webjobs-sdk/issues/1876. If anyone comes cross this and has more to add, please do so at that issue.

**Comment by ozanbora** [comment]
I don't understand why this issue is closed. It might be normal to receive these Dependency Call Failures, but if you try to reproduce the issue, you'll see that all requests are started to be handled only one server after a while. Any other server only tries to acquire host lease lock. It's much more scaling problem I think. 

Meantime, I thought that it's all about the v2 breaking changes. I went through all of them, adjusted all extensions, host file configurations etc. 

I also tried the create a new function app from scratch, none of these fix the scaling problem. I really appreciate if you can provide some additional info or at least a workaround for the issue. 

![image](https://user-images.githubusercontent.com/6598224/45697588-675ce680-bb66-11e8-9c1f-0f5fad8cae0b.png)

**Comment by brettsam** [comment]
It's closed b/c it's a duplicate. We're going to fix it, but it's actually in another repo so we want to direct everyone there: https://github.com/Azure/azure-webjobs-sdk/issues/1876
