### ISSUE TITLE
WEBSITE_NODE_DEFAULT_VERSION validation against available versions

### ISSUE THREAD

**Issue by btardif** [Azure/azure-functions-host#3420]
_From @mhoeger on August 1, 2018 21:17_

WEBSITE_NODE_DEFAULT_VERSION can only be one of a fixed number of options (found here: appName.scm.azurewebsites.net/api/diagnostics/runtime).

Ideally, picking WEBSITE_NODE_DEFAULT_VERSION would be as a dropdown instead of a blank text box as it is today in App Settings.

If this is not possible/too expensive, a cheaper alternative would be to add a warning when a user's WEBSITE_NODE_DEFAULT_VERSION is not valid. (Azure Functions V2 options should further be limited to the subset of major version 8.x and 10.x).

This is a bad bug because when WEBSITE_NODE_DEFAULT_VERSION is invalid, the default version is 0.10.40, which is an absurdly old version. When this happens with the functions runtime, the version is so old that the language worker fails to be able to execute and yields a confusing error message.

_Copied from original issue: Azure/azure-functions-ux#2962_

**Comment by btardif** [comment]
This issue is a result of node version being persisted as an app setting.

If the customer changes this value outside of the UX, there is no way to do validation on this.

This is not a UX issue, the fix here would be to have runtime default to a less old version when the setting is missing or malformed.

Additionally if this could be made as a proper value that is set on the site object through API, there could be additional validation done by the backend when the value is being set.

**Comment by btardif** [comment]
@jeffhollan & @paulbatum can you guys triage?

**Comment by paulbatum** [comment]
@byron This is a platform issue and not at all functions specific. Doesn't make sense to track here.
