### ISSUE TITLE
Function App constanly crashes

### ISSUE THREAD

**Issue by mikhailshilkov** [Azure/azure-functions-host#3421]
I have a Node.js Function App with some npm modules (notably, `@azure/cosmos`). The app seems to constantly crash, both when looking at it from the portal or trying to load Kudu:

![image](https://user-images.githubusercontent.com/1454008/45279476-8954ca00-b4d1-11e8-8614-2bb316b41ec9.png)

#### Investigative information

Please provide the following:

- Timestamp: since September 5 onwards
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name: mygeofn-appfixed90d532b9
- Region: West Europe

#### Repro steps

Provide the steps required to reproduce the problem:

Open Function App in the portal, or in Kudu, or try HTTP request... it's always down

#### Known workarounds

Removing `npm_modules` folder fixes the app startup (obviously, the function won't work because of missing modules).

#### Related information 

@tohling was helping me and asked to create this issue.

**Comment by tohling** [comment]
@mikhailshilkov , there are duplicate files in the path *****geo****\node_modules\stream-http\node_modules\process-nex*****-****gs that is causing the libraries to stop loading. Could you kindly remove the duplicate files in your zip and retry?

**Comment by mikhailshilkov** [comment]
Thanks @tohling, this fixed the problem.
I was creating ZIP file with an automation script, which seems to have an error which causes duplicated files inside the ZIP.
Any chance you could handle the problem more gracefully?
Feel free to close the issue otherwise.

**Comment by tohling** [comment]
@mikhailshilkov , thanks for confirming that the temporary workaround works. 

Yes, we have a fix already but it has not been pushed to production yet. I will close this issue for now.
