### ISSUE TITLE
Default metrics are no longer collected (HTTP trigger)

### ISSUE THREAD

**Issue by jdvor** [Azure/azure-functions-host#3431]
Application Insights **default function metrics** (SuccessRate, Failures, Successes, MinDurationMs, MaxDurationMs, AvgDurationMs, Count) are no longer collected (or sent upstream) when Functions runtime is upgraded to beta (~2).
Telemetry of custom metrics, logs and exceptions work as expected.

#### Investigative information

- Timestamp: since 2018-09-07T10:23:42.117
- Function App version (1.0 or 2.0-beta): 2.0.12050.0 (~2)
- Function App name: SmartGridApiStage
- Function name(s) (as appropriate): GetDeviceInfo
- Region: West Europe

Relevant (installed) nuget packages in the solution:
Microsoft.Azure.WebJobs.Host 3.0.0-beta8
Microsoft.NET.Sdk.Functions 1.0.19

#### Repro steps

1. Create new Azure function (HTTP trigger) and deploy to environment with ~2 runtime.
2. (alternatively) Migrate existing function from 1 or 2.alpha to 2.beta runtime.
3. Send few request to HTTP endpoint.
4. Check the metrics in Analytics dashboard (Azure portal) for example like so:
```
customMetrics
| where timestamp > ago(6d)
| order by timestamp desc nulls last
| take 250
```

You will see that from the upgrade or from the start (depending on point 2.) the SuccessRate, Failures, Successes, MinDurationMs, MaxDurationMs, AvgDurationMs, Count are no longer there.

**Comment by brettsam** [comment]
The fix for issue #3632 should fix this. Are you able to repro it on the latest v2 version?
