### ISSUE TITLE
[V2] Duplicate logs on Node runtime

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#3432]
_From @ltouro on September 3, 2018 20:53_

_From @ltouro on September 3, 2018 14:38_

Logs are duplicated when running Node runtime on localhost

#### Investigative information

- Function App version: 2.0.1-beta.37

#### Repro steps

Execute the below function. Observe the "duplicate log" in the console

```js
module.exports = async function(context, req) {
  context.log('Dupplicate Log.');
  if (req.query.name || (req.body && req.body.name)) {
    context.res = {
      // status: 200, /* Defaults to 200 */
      body: 'Hello ' + (req.query.name || req.body.name)
    };
  } else {
    context.res = {
      status: 400,
      body: 'Please pass a name on the query string or in the request body'
    };
  }
};
```

```sh
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:7071/api/testjs?date=2018-08-26  0
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
[03/09/2018 14:38:24] Executing 'Functions.testjs' (Reason='This function was programmatically called via the host APIs.', Id=8e140c1f-1b11-4484-8fbf-17415986d016)
[03/09/2018 14:38:24] Dupplicate Log.
Dupplicate Log.
[03/09/2018 14:38:24] Executed 'Functions.testjs' (Succeeded, Id=8e140c1f-1b11-4484-8fbf-17415986d016)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 514.2981ms 400 text/plain; charset=utf-8
[03/09/2018 14:38:26] Host lock lease acquired by instance ID '0000000000000000000000000FF3F168'.
```

_Copied from original issue: Azure/azure-functions-host#3376_

_Copied from original issue: Azure/azure-functions-nodejs-worker#123_

**Comment by pragnagopa** [comment]
_From @mhoeger on September 10, 2018 20:6_

@pragnagopa - do you know if this is related to fabio's changes or if this is related to grpc server changes? either way, we may want to re-open the original issue in funcitons-host.

**Comment by pragnagopa** [comment]
Investigating.

**Comment by brettsam** [comment]
We're registering a `ConsoleFunctionOutputLogger` if you have the dashboard disabled. This is a legacy logger and we really should be using a `NullOutputLogger` here.

https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Hosting/WebJobsServiceCollectionExtensions.cs#L73
