### ISSUE TITLE
Failure: Failed to start language worker for: node

### ISSUE THREAD

**Issue by Meyce** [Azure/azure-functions-host#3449]
Azure Functions Runtime Version: Runtime version: 2.0.12050.0
Function Langauge: Node/javascript
Binding: serviceBusTrigger/queue, timerTrigger
WEBSITE_NODE_DEFAULT_VERSION: 8.11.1

Receiving this error on  serviceBusTrigger queue triggers and timer triggers. I noticed the queues that the functions are monitoring occassionally have messages in the deadletter queue. The messages will have 2 custom header properties of

"DeadLetterReason": "MaxDeliveryCountExceeded"
"DeadLetterDescription": "Message could not be consumed after 10 delivery attempts"

Through Kudu/(webjobs/functions) dashboard, I can find the corresponding error for the function. The invocations details `Failure: Failed to start language worker for: node`.

Also the errors are occurring in slots.  So far I have not seen this error in the main app service but will continue to monitor and see if they occur in the main app service as well.

**Comment by Meyce** [comment]
This is occurring on the (main/non-slot) app service as well.

**Comment by mhoeger** [comment]
@Meyce - can you post some logs from "Worker/Node" around the same time as your failures? This will give us a better sense of why you're seeing the language worker fail to start.

**Comment by Meyce** [comment]
@mhoeger there are no log files in worker/node from the dates they last occurred.  I assume those logs may get cleaned up.  I will post log files the next time the error occurs.

**Comment by mhoeger** [comment]
Would you mind sharing your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us track down logs on our end as well. Thanks!

**Comment by Meyce** [comment]
Is the below enough?

2018-09-18T13:39:34.025 [Information] Executing '' (Reason='This function was programmatically called via the host APIs.', Id=738985f3-cf60-44f3-85d2-83623d386b6f) 

North Central US

**Comment by Meyce** [comment]
I never heard back on this error.  We haven't had the issue since Functions v2 when GA.

**Comment by Meyce** [comment]
I take it back.  This has been occurring quite a bit.  I just noticed it on some timer jobs.  It turns out the frequency they run at was covering up the fact it was occurring.  Is there any feedback on the issue?

**Comment by mhoeger** [comment]
@Meyce - I'm sorry I didn't get a hold of your app name by invocation ID before it left our system. Could you send me another id? @jsiler, an app name shared directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly) would also be helpful.
