### ISSUE TITLE
context.done() does not write to response body in Functions V2

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-host#3454]
When ending a node function with `context.done(null, {body: "hello world"}`, I would expect to get a 200 response with "hello world" as the response body. However, the actual response body is empty.
#### Investigative information

- Timestamp : 2018-09-14T00:40:07.418
- Function App version (1.0 or 2.0-beta): 2.0-beta
- Function App name: jsv2tester
- Function name(s) (as appropriate): HttpTriggerJS1
- Invocation ID: 3158babd-6c14-45e1-b7c1-30e463074e82
- Region: West US

#### Repro steps
index.js
```
module.exports = function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');
    var res;
    if (req.query.name || (req.body && req.body.name)) {
        res = {
            // status: 200, /* Defaults to 200 */
            body: "Hello " + (req.query.name || req.body.name)
        };
    }
    else {
        res = {
            status: 400,
            body: "Please pass a name on the query string or in the request body"
        };
    }
    context.done(null, res);
};
```

function.json:

```
{
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}
```

#### Expected behavior

Hitting this function with a POST body of 

```
{
    "name": "Azure"
}
```

would return a 200 response with a body of "Hello Azure";

#### Actual behavior

The above returns an empty 200 response.

#### Known workarounds

Using an async function and setting context.res directly.

**Comment by ConnorMcMahon** [comment]
Note that I don't see this behavior when running locally from the dev branch. However, I do see this behavior when running in Azure on runtime version 2.0.1.0

**Comment by mhoeger** [comment]
@ConnorMcMahon - if using [context.done(null, result)](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#contextdone-method), the expectation is that the object you pass either has the name of your output binding as a key **or** that you name your output "$return". 

This change will make your existing code work:
```
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
```

This will also work:
```
context.done(null, { res });
```

Here's another option:
```
context.done(null, { httpResponse: res });
```
```
    {
      "type": "http",
      "direction": "out",
      "name": "httpResponse"
    }
```

Did you used to be able to directly pass in `res` to `context.done` and have it work? (If this was a breaking change we should note that in our release!) And just to confirm - you are seeing the code you posted working with dev branch code?

**Comment by ConnorMcMahon** [comment]
@mhoeger, this was my bad, not a breaking change. I missed the difference in the function.json between my local function and the function in Azure. The [JavaScript developer reference ](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node) even mentions exactly what you pointed out.

**Comment by mhoeger** [comment]
@ConnorMcMahon - sounds good! appreciate you checking out node things and filing issues!!!
