### ISSUE TITLE
Blob/queue triggers pulling logs for app service plan

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-host#3462]
For consumption apps we can check ScaleController logs and see if we are pulling for new items. Add pulling logs for app service plan managed by app setting.

**Comment by mathewc** [comment]
We can add verbose level logs to our queue polling loop to give insights in to queue activity, etc. We need to be sure to log at a level that doesn't swamp our system logs or app insights user logs.

**Comment by FinVamp1** [comment]
@brettsam has added Functionality for this. @alrod and @mathewc  can we close this one?

**Comment by mathewc** [comment]
Yes, thanks Finbar.
