### ISSUE TITLE
v2 Functions do not support extensions in the same project.

### ISSUE THREAD

**Issue by vsadams** [Azure/azure-functions-host#3465]
This might be by design, if it is, Ill close this ticket. 
I am also unsure whether or not to post this ticket here or in the [Web Jobs Extensions Github](https://github.com/Azure/azure-webjobs-sdk-extensions/issues/new). I am going to post here in case this helps someone else upgrading.

When upgrading to the latest version of the v2 functions. I noticed a weird issue. I converted to using the webjob extension framework per the docs. I was using the ExtensionConfigProvider.  
The important piece here is that **the code for the extension was in the same project as the functions**.
All was pretty seamless. I tested the functions in Visual Studio and they ran great. I then deployed them and found that my extensions.json file was not generated with a reference to my extension.

I ran a few tests and it turn out doing a dotnet publish against a v2 function project with an extension in the same project will not generate an extensions.json file with the reference to the custom extension. **The fix is to extract the extension code to a separate project and reference it by the function project.** 

The thing that threw me off was that testing locally in visual studio worked fine... Im not sure how that happened. I still have to go back and run some tests to see if I can figure out what all is different between doing a dotnet publish and just running the functions locally in visual studio.

**Comment by mathewc** [comment]
Are you on the latest version 2.0.12115? There were some late breaking changes in the area of extension registration/discovery. Recommend looking at the extensions in the extensions repo, e.g. the CosmosDB extension here: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.CosmosDB.

The host no longer scans for ExtensionConfigProvider Types, and instead use a new WebJobsStartup type, example here: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.CosmosDB/CosmosDBWebJobsStartup.cs.

**Comment by jnevins-gcm** [comment]
This is something different. I posted a workaround in another thread. 

There is a bug in the build order of extension metadata generator/functions.sdk custom targets when doing a publish. 

Specifically when doing a publish, the metadata generator target runs after all reference assemblies have been copied but before the output assembly has been copied. Accordingly, extensions.json doesn’t include an entry for webjobsstartup classes that are in the function app itself. 

Build target order doesn’t suffer from the same bug.

**Comment by brettsam** [comment]
There were quite a few bugs fixed around this recently in the `Microsoft.Net.Sdk.Functions` package so I'm going to go ahead and close this. Please feel free to reopen a new issue if you continue to see issues around this.
