### ISSUE TITLE
Unsupported Runtime Version

### ISSUE THREAD

**Issue by abjorck** [Azure/azure-functions-host#3475]
This may no be the place to ask this, but I'll try anyway

How can one know which runtime versions are supported for pinning to? What's the point of pinning if it suddenly gets unpinned by itself?

I get this in the portal currently: (not the first time, but at least this time it doesnt seem to break anything for me)

```
Runtime version
Runtime version loaded from Application Settings: 2.0.12050.0
```

```
Warning
Unsupported Runtime Version
Your custom runtime version is not supported. As a result 2.0.12095.0 runtime is being used. 
```

Thankful for any insights

**Comment by mhoeger** [comment]
We were recommended people pin versions as we introduced breaking changes to the V2 runtime while it was in preview. Pinned versions last for ~1 month. The idea is that although we were in preview and reserved the right to make breaking changes, we wanted to give people time to update, validate, and deploy new versions. 
 
We just moved our V2 from preview => GA ([announcement here](https://azure.microsoft.com/en-us/updates/azure-functions-functions-runtime-2-0-ga)), which means that we won't be introducing breaking changes as we were before.

Could you close this issue if that answers your question?

**Comment by abjorck** [comment]
Cool, I missed the GA announcement - a bit surprised! Great, thanks!
