### ISSUE TITLE
Proxies redirecting to local function will return 401 if local function is not anonymous

### ISSUE THREAD

**Issue by safihamid** [Azure/azure-functions-host#3489]
This happens only in V2.

Current workaround is to add this app setting until fix is deployed:

AZURE_FUNCTION_PROXY_DISABLE_LOCAL_CALL: true

Setting this app setting will have a perf impact and should be removed once fix is deployed.

**Comment by cmatskas** [comment]
@safihamid  this is still an issue btw. Do we have an ETA on the fix?

**Comment by safihamid** [comment]
@cmatskas this is just merged and will be released with next v2 runtime release. Later this week or next week.
