### ISSUE TITLE
There is no any logs when execute Event hub function on V2 function app

### ISSUE THREAD

**Issue by sunxinhuan** [Azure/azure-functions-host#3491]
**Environment URL**: http://aka.ms/canary
**App runtime version**:  1.0.11959.0 (~1)
**Beta runtime version**:   2.0.12095.0 (~2)
**Browser**: Chrome
**Hosting Plan**: Consumption

Please refer to the snapshot:
![eventhub](https://user-images.githubusercontent.com/39791546/45811274-3f54bb00-bcff-11e8-9563-b9edd1edc48b.PNG)

**Repro steps**:
	1. Create v2 function app;
	2. Add Event hub function;
	3. Click on "Run" and verify the logs.

**Comment by ankitkumarr** [comment]
@sunxinhuan, apologies for the long delay here. We made several improvements recently on logs in a Consumption plan. Using [Application Insights](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring) is now the recommended approach for viewing logs. 

Closing the issue, but please feel free to re-open if you continue seeing the problem.
