### ISSUE TITLE
The function runtime is unable to start. Microsoft.Azure.WebJobs.Extensions.CosmosDB: Method not found:

### ISSUE THREAD

**Issue by niko619** [Azure/azure-functions-host#3492]
I've created a Function that has a HTTP trigger and CosmosDB attribute input. Everything works fine locally and deploys. However, the Function gets the following message within the portal:

> The function runtime is unable to start. Microsoft.Azure.WebJobs.Extensions.CosmosDB: Method not found: 'Microsoft.Azure.WebJobs.IWebJobsExtensionBuilder Microsoft.Azure.WebJobs.WebJobsExtensionBuilderExtensions.ConfigureOptions(Microsoft.Azure.WebJobs.IWebJobsExtensionBuilder, System.Action`3<Microsoft.Extensions.Configuration.IConfiguration,System.String,!!0>)'.

**Nuget:**
Microsoft.Azure.WebJobs.Extensions.CosmosDB - 3.0.1
Microsoft.NET.Sdk.Functions - 1.0.22
NETStandard.Library - 2.0.3

- Timestamp: 2018-09-20T16:07:16.481Z
- Function App version: 2.0
- Region: Australia Southeast
- SessionId: 0ee67cc6f0c849c3be0e5f81d75cbb7e

**Comment by amindong** [comment]
I am getting the same error. I do get error locally in my development machine though.

fail: Host.General[0]
      A host error has occurred
System.MissingMethodException: Method not found: 'Microsoft.Azure.WebJobs.IWebJo
bsExtensionBuilder Microsoft.Azure.WebJobs.WebJobsExtensionBuilderExtensions.Con
figureOptions(Microsoft.Azure.WebJobs.IWebJobsExtensionBuilder, System.Action`3<
Microsoft.Extensions.Configuration.IConfiguration,System.String,!!0>)'.
   at Microsoft.Extensions.Hosting.CosmosDBWebJobsBuilderExtensions.AddCosmosDB(
IWebJobsBuilder builder)
   at Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBWebJobsStartup.Configu
re(IWebJobsBuilder builder) in C:\azure-webjobs-sdk-extensions\src\WebJobs.Exten
sions.CosmosDB\CosmosDBWebJobsStartup.cs:line 16
   at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseWebJobsStartup(IWebJob
sBuilder builder, Type startupType) in C:\projects\azure-webjobs-sdk-rqm4t\src\M
icrosoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderExtensions.cs:line 72
   at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseExternalStartup(IWebJo
bsBuilder builder, IWebJobsStartupTypeDiscoverer typeDiscoverer) in C:\projects\
azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderE
xtensions.cs:line 103
   at Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions.UseScriptExtern
alStartup(IWebJobsBuilder builder, String rootScriptPath) in C:\azure-webjobs-sd
k-script\src\WebJobs.Script\ScriptHostBuilderExtensions.cs:line 172
   at Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions.<>c__DisplayCla
ss2_0.<AddScriptHostCore>b__0(IWebJobsBuilder webJobsBuilder) in C:\azure-webjob
s-sdk-script\src\WebJobs.Script\ScriptHostBuilderExtensions.cs:line 103
   at Microsoft.Extensions.Hosting.WebJobsHostBuilderExtensions.<>c__DisplayClas
s2_0.<ConfigureWebJobs>b__1(HostBuilderContext context, IServiceCollection servi
ces) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hos
ting\WebJobsHostBuilderExtensions.cs:line 36
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.Azure.WebJobs.Script.WebHost.DefaultScriptHostBuilder.BuildHost(
Boolean skipHostStartup, Boolean skipHostConfigurationParsing) in C:\azure-webjo
bs-sdk-script\src\WebJobs.Script.WebHost\DefaultScriptHostBuilder.cs:line 59
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.BuildHost(
Boolean skipHostStartup, Boolean skipHostJsonConfiguration) in C:\azure-webjobs-
sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs:line 267
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.StartHostA
sync(CancellationToken cancellationToken, Int32 attemptCount, JobHostStartupMode
 startupMode) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsS
criptHostService.cs:line 134
Listening on http://0.0.0.0:7071/
Hit CTRL-C to exit...
Value cannot be null.
Parameter name: provider
Press any to continue....info: Host.General[0]
      Building host: startup suppressed:False, configuration suppressed: False
info: Host.Startup[0]
      Reading host configuration file 'C:\Users\momir\source\repos\Orsted.IO\Ors
ted.IO.Functions\bin\Debug\netstandard2.0\host.json'
info: Host.Startup[0]
      Host configuration file read:
      {
        "version": "2.0"
      }

**Comment by TejaKommineni** [comment]
It can be resolved by downgrading Microsoft.Azure.WebJobs to 3.0.0-beta4.
func extensions install -p Microsoft.Azure.WebJobs.Extensions.CosmosDB -v 3.0.0-beta4

**Comment by ankitkumarr** [comment]
Sorry for the late response here. Currently the stable version is 3.0.3, which should include our latest fixes. I will go ahead and close this issue, but please re-open if you continue to see similar problems with the new version of the extension.
