### ISSUE TITLE
ScopedResolver in V2 is not thread safe.

### ISSUE THREAD

**Issue by mlankamp** [Azure/azure-functions-host#3494]
#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0): 2.0.12115.0
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region: local emulator

#### Repro steps

1. Inject ```IServiceProvider``` into a custom Extension
2. In the ```IBinding.BindAsync``` call the ```CreateScope``` on the IServiceProvider
3. Use the custom Extension in function (for instance an httptrigger)
4. Make sure the function is called multiple times, this will cause an error in the CreateChildScope.

The pattern to call CreateScope is used in various Dependency Injection extensions:
- https://github.com/cResults/azure-functions-v2-dependency-injection/blob/master/InjectBinding.cs
- https://github.com/DibranMulder/azure-functions-v2-dependency-injection/blob/master/AzureFunctionsV2.DependencyInjection/InjectBinding.cs

All these extensions are based on a solution for V1, because in V1 the problem didn't exist.

#### Expected behavior

The ```ScopedResolver``` from the host uses a ```HashSet<ServiceScope>```, this is not thread safe.

#### Actual behavior

```csharp
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Function1 ---> System.InvalidOperationException: Exception binding parameter 'sampleRepo' ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.HashSet`1.SetCapacity(Int32 newSize)
   at System.Collections.Generic.HashSet`1.IncreaseCapacity()
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at System.Collections.Generic.HashSet`1.Add(T item)
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedResolver.CreateChildScope(IServiceScopeFactory rootScopeFactory) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\ScopedResolver.cs:line 55
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.CreateScope() in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs:line 101
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateScope(IServiceProvider provider)
```

#### Known workarounds

- None

**Comment by doggy8088** [comment]
Azure Functions 2.0 is just GA. https://github.com/Azure/app-service-announcements/issues/138

Is there any workaround on this issue for now?

**Comment by mlankamp** [comment]
Only use singleton and don't call CreateScope

**Comment by jnevins-gcm** [comment]
I don't think that qualifies as a "workaround" by the word's very definition.

**Comment by jeromekol** [comment]
Are you seeing these exceptions in AI? Because we receive random 500s which are not logged to AI.

**Comment by fabiocav** [comment]
A targeted fix for this was just made. There's ongoing work for a set of tests exercising this code path.

Just something to keep in mind with the implementations linked to above; you should exercise some care when exposing the runtime service provider. We have work in progress right now to expose DI capabilities built into the host (which would eliminate the need for a custom extension to address those scenarios), including support for constructor injection. As part  of that work, we'll be adding some runtime validation and documenting types you can safely depend on (services and their lifetime scope). The V1 approach used by many extensions would be a safer alternative for now (with an extension scoped service provider only) and would also avoid the bug you just hit.
