### ISSUE TITLE
Failed to trigger eventgrid function by manually post the request

### ISSUE THREAD

**Issue by btardif** [Azure/azure-functions-host#3496]
_From @sunxinhuan on August 22, 2018 10:20_

**Portal Environment**: https://ms.portal.azure.com
**Browser**: English/Chrome
**Runtime Version**: 2.0.12007.0 (beta) (Private Site Extension)
**Hosting Plan**: Consumption

**Expected result:**
Eventgrid should be triggered successful.

**Actual result:**
It shows 500 Internal Server Error when post the request.

Please refer to the snapshot:
![eventgrid](https://user-images.githubusercontent.com/39791546/44457940-3ce73e80-a637-11e8-9bb5-c9a1aebe3b07.PNG)

**Repro steps:**
	1. Open a function app (V2) and install eventgrid extension;
	2. Create a eventgrid function;
	3. Post to the URL and verify the result.

_Copied from original issue: Azure/azure-functions-ux#3017_

**Comment by btardif** [comment]
This is not a UX bug, its a runtime issue.

@paulbatum can you please triage?

**Comment by paulbatum** [comment]
@sunxinhuan Can you please make sure that your app is updated to be running the latest runtime version (2.0.12115) and referencing the latest event grid extension (https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventGrid/2.0.0) and then if this still repros, share your logs? You can access the logs either by having the function open in the portal and viewing the streaming logs, or by getting them from app insights.

**Comment by mathewc** [comment]
Also note that the webhook URL changed - see https://github.com/Azure/azure-functions-host/pull/3322. So after moving to the latest release, you should use /runtime/webhooks/eventgrid.
