### ISSUE TITLE
Add more logging to understand host secrets regeneration

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#3503]
This is one instance where Functions runtime regenerted secrets at the exact same time w3wp process was recycling while moving file shares

```
AntaresRuntimeWorkerEvents
| where (TIMESTAMP >= datetime(2018-09-07T11:42:29Z) and TIMESTAMP < datetime(2018-09-07T11:50:29Z)) 
| where Details == "File server path changed, likely due to file storage failover."  
| where RoleInstance == "LargeDedicatedWebWorkerRole_IN_43"
```

Since app did not move to secondary storage, we expect keys to remain the same

**Comment by pragnagopa** [comment]
@alrod - can please take a look?

**Comment by alrod** [comment]
@pragnagopa, Actually you already have all required logs are in place:

https://github.com/Azure/azure-functions-host/blob/v1.x/src/WebJobs.Script.WebHost/Security/SecretManager.cs#L78

https://github.com/Azure/azure-functions-host/blob/v1.x/src/WebJobs.Script.WebHost/Security/SecretManager.cs#L91

https://github.com/Azure/azure-functions-host/blob/v1.x/src/WebJobs.Script.WebHost/Security/SecretManager.cs#L102

**Comment by pragnagopa** [comment]
cc: @paulbatum in case he has any other ideas where we can log

Looks like all of them are debug/verbose logs. Can we change them warning/info? Also, can you please check if adding any logs in LoadSecretsAsync would help? 
As of now, from Kusto logs it is really difficult to understand why secrets are regenerated. We need a disctinction on:
- Are we generating on function app creation or
- Runtime tried to look up and did not find. We need to log where did the function look up? Perhaps logging the URL might help

**Comment by alrod** [comment]
cc: @fabiocav 

**Can we change them warning/info?**
yes, we can

**can you please check if adding any logs in LoadSecretsAsync would help**
This willn't help as LoadSecretsAsync returns valid keys or null. In "null" case a log will be added:
https://github.com/Azure/azure-functions-host/blob/v1.x/src/WebJobs.Script.WebHost/Security/SecretManager.cs#L78

**from Kusto logs it is really difficult to understand why secrets are regenerated**
there are 4 cases when keys can be regenerated:
1. There are no host keys found (new app or customer manually delete the keys). Logs are existed.
2. The host keys are non-decrypted. Logs are existed.
3. The keys are stale. Logs are existed.
4. KeysController changes the host keys. I will add these logs.

**Are we generating on function app creation or
Runtime tried to look up and did not find. We need to log where did the function look up? Perhaps logging the URL might help**
From the code this is not possible to determinate if customer just created the app or removed the keys.  We can add repository type to the logs (Azure Storage or File System)

So the scope of the change will be:
1. Change debug -> info for logs.
2. Logs for keys changes from KeyController (Put/Post/Delete).
3.  Logs for repository type.

**Comment by paulbatum** [comment]
@alrod Can you take a quick look at this:
https://github.com/Azure/azure-functions-host/issues/3605

I'd like to have a good way to filter logs to key related events.

**Comment by alrod** [comment]
https://github.com/Azure/azure-functions-host/commit/7aa72290a0e3e00f161cf2dd80dbdf0f4b74b100
