### ISSUE TITLE
Host.json Sanitize/Log needs update

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#3507]
After all the recent v2 changes, we never went back and updated the "well known" properties we log here: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Config/HostJsonFileConfigurationSource.cs#L45.

We need to revisit this. I'm thinking that rather than do this json based approach based on reading host.json, we could instead do options Type based logging for the various options classes. Everything we specify in host.json maps to options properties. A benefit here is that we could potentially use metadata attributes like [ConnectionString] etc. on the options types to automatically sanitize.

@brettsam FYI

**Comment by brettsam** [comment]
I agree we should move this to the options-level. We really only care about what is finally resolved from IConfiguration, not necessarily what is in host.json. And that prevents us from chasing down changes to this list every time some extension makes a change.
