### ISSUE TITLE
Microsoft.Extensions.Logging.Abstractions not found on latest beta version upgrade

### ISSUE THREAD

**Issue by mieliespoor** [Azure/azure-functions-host#3511]
I am trying to upgrade my function app to the latest beta version available but face the following exception:

If the Microsoft.Extensions.Logging.Abstractions 2.1.1 package is not installed:
`System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'`

If the Microsoft.Extensions.Logging.Abstractions package is not installed:
`System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'`

I have tried to following options:

- Not have the package reference
- Install version 2.1.0
- Install version 2.1.1
- Install version 2.2.0-preview1-35029
- Install version 2.2.0-preview2-35157

With every version I tried to install I get the error mentioned with the only difference the version number changes to the installed version of the package.

- Function App version: 2.0
- Function App name: Oneref-Functions
- Region: North Europe

I started the discussion in this thread: https://github.com/Azure/app-service-announcements-discussions/issues/64#issuecomment-418454418

**Comment by codingdiva** [comment]
I have encountered this same issue. Have you found a resolution yet?

**Comment by mieliespoor** [comment]
@codingdiva No I haven't been able to resolve the issue. Doesn't matter what version I reference, I get this issue so at this point I am blocked which is highly annoying as there are some update that I want to push out.

**Comment by PureKrome** [comment]
@mieliespoor when you say "double check that you are using the latest cli" can you please confirm what that exact tool is, please? (screen shot?)

**Comment by mieliespoor** [comment]
Have a look at #3759 . I'm also on that same version and Visual Studio don't seems to update the cli to the latest version.

**Comment by mieliespoor** [comment]
I'm closing this in favour of #3759
