### ISSUE TITLE
Azure function timer triggering stops firing for schedule configured by Timestamp value

### ISSUE THREAD

**Issue by arkoc** [Azure/azure-functions-host#3512]
#### Repro steps

Provide the steps required to reproduce the problem:

1. Create Azure function with provided source code.
2. Add application setting with key "TimerSchedule" and value "0.00:00:10" (Timestamp)

#### Expected behavior

Function should trigger every 10 second.

#### Actual behavior

Function starts triggering for a while, but then stops. After refreshing function from portal, function start triggering again, but stops after some time.

#### Known workarounds

Workaround is to use following CRON expression. `*/10 * * * * *`

#### Related information 

* Programming language used : C#
* Function App version: 2.0

**Source Code:**
```csharp
[FunctionName("myFunction")]
public static async Task RunAsync([TimerTrigger("%TimerSchedule%")]TimerInfo timer, CancellationToken token)
{
}
```

**Comment by basilfx** [comment]
We have the same problem. When the schedule is provided via an application setting, the function stops after a while (interval one hour). Our work-around is to use an additional timer trigger that runs every five minutes, and then it keeps running.

**Related information**
* Programming language used : C#
* Function App version: 2.0

**Comment by ankitkumarr** [comment]
Apologies for the later follow-up here. Are you on a Consumption plan? 

Currently Timespan is only supported for App Service plans ([docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer#timespan)). For Consumption plan, you'd have to use Cron schedule for it to work properly.

**Comment by basilfx** [comment]
@ankitkumarr from the [docs](https://docs.microsoft.com/nl-nl/azure/azure-functions/functions-bindings-timer#configuration)

> You can put the schedule expression in an app setting and set this property to the app setting name wrapped in % signs, as in this example: "%ScheduleAppSetting%".

In our case, we were using a `%ScheduleAppSetting%` provided via the key vault (loaded dynamically via an extension). Whenever the host starts (on consumption plan), it is not able to resolve the value of `%ScheduleAppSetting%`, and therefore unable to schedule a `TimerTrigger` function properly.

We have moved away from this approach, but I would recommend to either throw an error (from the host whenever it cannot resolve the value) and list this method as not possible in the documentation.

**Comment by ankitkumarr** [comment]
@basilfx, the docs say
> A CRON expression or a TimeSpan value. A TimeSpan can be used only for a function app that runs on an App Service Plan. You can put the schedule expression in an app setting and set this property to the app setting name wrapped in % signs, as in this example: "%ScheduleAppSetting%".

Given that you are on a Consumption plan, you cannot use a `Timespan`. Are you using a Cron expression in that environment variable?

**Comment by basilfx** [comment]
I am using a CRON expression in that variable. But that variable is resolved dynamically via an extension, AFTER the host started. In other words, the host cannot know the CRON schedule, and the end-user is not informed.

**Comment by ankitkumarr** [comment]
@basilfx, ok I see. So, your problem is different than the original issue. The issue created here is about the inability to use TimeSpan (by design for Consumption plan) and the workaround being a Cron expression.

In your case, you want to dynamically modify the schedule. I am not sure if we have a way to do that. If it was set via an Application Setting, and that setting was changed, then the Host would automatically restart updating the schedule.

**Comment by arkoc** [comment]
Thank you for replies. Yes, I can confirm that I was using consumption plan.

**Comment by Geertvdc** [comment]
> @basilfx, the docs say
> 
> > A CRON expression or a TimeSpan value. A TimeSpan can be used only for a function app that runs on an App Service Plan. You can put the schedule expression in an app setting and set this property to the app setting name wrapped in % signs, as in this example: "%ScheduleAppSetting%".
> 
> Given that you are on a Consumption plan, you cannot use a `Timespan`. Are you using a Cron expression in that environment variable?

We're using the Cron expressions  which we define in an appsettings.json file. this works perfectly for an hour or so and then the function stops triggering. @ankitkumarr You said you cannot use `Timespan` notation but can you use `CRON` expressions?
