### ISSUE TITLE
Application Insights not recording new executions in Azure Portal "Monitor" tab

### ISSUE THREAD

**Issue by a-silva** [Azure/azure-functions-host#3516]
Hey guys, first ever issue raised so bear with me any mistakes I make! Congrats on the GA launch btw.

#### Investigative information

Please provide the following:

- Timestamp: Anytime after 10th or 11th September 2018
- Function App version (1.0 or 2.0): 2.0
- Region: Australia SouthEast
- ID: 4a235c9b-ec62-43e2-9628-4f0d5f7ce4fc

#### Repro steps

Provide the steps required to reproduce the problem:

Basically (and this was working up until this month, probably when the new updates started kicking in and I started updating to the new libraries) the "Monitor" tab for my function stopped updating, if I use log streaming I can see everything executing and working fine, but a new record never appears on that tab, so it is still showing the last execution being on Sept 11 UTC time.

More details about my project, it's using the latest v2 libraries, see below:

```  <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Core" Version="3.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="3.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Logging" Version="3.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Logging.ApplicationInsights" Version="3.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.0.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Redis" Version="2.1.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="2.1.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.22" />
```

Also, my hosts's startup code (based on the new recommended code showing how it's setting up the App Insights key properly.

```
var builder = new HostBuilder()
    .UseEnvironment("Development")
    .ConfigureWebJobs(b =>
    {
        b
            .AddServiceBus()
            .AddTimers();
    })
    .ConfigureLogging((context, b) =>
    {
        b.SetMinimumLevel(LogLevel.Debug);
        // If this key exists in any config, use it to enable App Insights
        string appInsightsKey = context.Configuration["APPINSIGHTS_INSTRUMENTATIONKEY"];
        if (!string.IsNullOrEmpty(appInsightsKey))
        {
            b.AddApplicationInsights(o => o.InstrumentationKey = appInsightsKey);
        }
    })
    .UseConsoleLifetime();
var host = builder.Build();
using (host)
{
await host.RunAsync();
}
```

And you can verify key is actually set in that function. Also, I am not pinned to any function version, I am using `FUNCTIONS_EXTENSION_VERSION` as `~2`

There is a link to Application Insights in my Function, which means it is hooked up to some degree, I can see real-time metrics and stuff like that flowing through, that's all fine, it's just the history of execution that doesn't seem to update.

#### Expected behavior

Pretty much have the invocations record as they were before, they provide very useful information when doing investigations or debugging issues.

#### Actual behavior

Monitor tab not updating (as I said it's 2 weeks behind so I'm not talking about the usual 5min wait time here)

#### Related information 

Not sure what else to add here, really hope you can assist me and hope it's not a setting I forgot or piece of code I didn't hook up. I have 3 apps (using various versions), the one using the newest version of the libraries doesn't work but the others do without issue.

Thank you!

**Comment by aleksigron** [comment]
I also have had this issue of the monitor tab not loading at all. The loading indicator overlay disappears, but the execution list is empty and success and error counts show "loading..." text. We are using classic monitoring (not Application Insights) and runtime v1.

This has happened on 2 of our Function App projects. These are the 2 latest ones we've created. They have never received any logs in the monitor view, and I verified that the WebJobsHostLog tables haven't even been created in the associated storage accounts. The functions themselves work fine and the logs come through to Log Streaming view.

We've tried with Microsoft.NET.Sdk.Functions package versions 1.0.14 and 1.0.22 and no difference.

**Comment by aleksigron** [comment]
We found the cause for our problem: AzureWebJobsDashboard connection string was missing in application settings. To my knowledge, we haven't deleted that value ourselves. It could mean that there is a bug in the Function App deployment process, and that's why the connection string was missing.

**Comment by a-silva** [comment]
Thank you for replying and sorry for not getting back to you before - it's an internal issue with Microsoft that's being fixed in the next version of Microsoft.Azure.WebJobs - had to raise a ticket with them internally to get them to track it. There's nothing I can do on my end to get it to work until they release the new package.

**Comment by a-silva** [comment]
I didn't get a reply but it's been addressed in the latest version of Azure Webjobs and Azure Functions
