### ISSUE TITLE
Function Route (Node) Binding for HttpTrigger now incorrectly assigning an empty object

### ISSUE THREAD

**Issue by dustensalinas** [Azure/azure-functions-host#3517]
Example:
Function.json
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "route": "entity/{id:alpha?}"
    },

Code:
        var id= context.bindingData.action;

Scenario A:
Http Request: <...>/entity

id is assigned to {} (change in behavior from undef)

Scenario B:
Http Request: <...>/entity/234
id is assigned 234 correctly

**Comment by paulbatum** [comment]
@fabiocav thinks this might be fixed. Chat with him.

**Comment by mhoeger** [comment]
Confirmed that the regression is fixed with our latest bits.
