### ISSUE TITLE
502 error when submitting files greater than 4 mb in size to HttpTrigger function

### ISSUE THREAD

**Issue by rewbotV86** [Azure/azure-functions-host#3520]
I have an HttpTrigger function that receives .xls files and parses the content into a json string. The deployed function errors out with `502 - Web server received an invalid response while acting as a gateway or proxy server` whenever a file greater than 4 mb in size is sent with the post. In the Azure logs I see this error `Exception of type 'System.OutOfMemoryException' was thrown`. When I run the function locally I don't have any problems processing a larger file. I have only see the error occur when I run the deployed function. Running the function (both locally and deployed) with a file less than 4 mb in size works without issue.

I have been able to reproduce it with files other than .xls, as long as that file is greater than 4 mb.

#### Investigative information

- Timestamp: 2018-09-25T19:34:00.236
- Function App version: 2.0.12115.0 (local and deployed)
- Invocation ID: 353be2e5-9fa6-4e4c-bb05-8f51f1d505d5
- Region: West US

#### Repro steps

1. Run the function with a file that is larger than 4 mb.

#### Expected behavior

Function is executed and returns processed file result.

#### Actual behavior

Deployed function is not executed and returns `502 - Web server received an invalid response while acting as a gateway or proxy server.`

#### Known workarounds

None.

#### Related information 

* Language: Java 

<details>
<summary>Source</summary>

```java
    public HttpResponseMessage split(
            @HttpTrigger(name = "content", methods = {HttpMethod.POST}, authLevel = AuthorizationLevel.FUNCTION, dataType = "binary") HttpRequestMessage<Optional<byte[]>> request,
            final ExecutionContext context
    ) {
        Logger logger = context.getLogger();
        logger.info("Data message split started.");
        if (request.getBody().isPresent()) {
            byte[] contents = request.getBody().get();
            logger.info("File contents acquired.");
            try (ByteArrayInputStream inputStream = new ByteArrayInputStream(contents)) {
                Workbook workbook = WorkbookFactory.create(inputStream);
                Splitter splitter = new Splitter(workbook);
                logger.info("Begin file processing.");
                String groupedData = splitter.split();
                return request.createResponseBuilder(HttpStatus.OK).header("content-type", "application/json").body(groupedData).build();
            } catch (Exception e) {
                return request.createResponseBuilder(HttpStatus.BAD_REQUEST).body(e.getMessage()).build();
            }
        }

        return request.createResponseBuilder(HttpStatus.BAD_REQUEST).body("Data message split failed. No data file was provided.").build();
    }
```
</details>

**Comment by ankitkumarr** [comment]
@rewbotV86, I apologize for such a long delay in the follow-up. Since then, we have made a lot of improvements on memory leaks and issues on our host. At the moment I am not aware of any open customer reports on `OutOfMemoryException`. So, I am assuming that this bug was fixed since then.

I will go ahead and close this issue. If you do continue to see the issue again, please definitely re-open the issue, and if you could also provide new Timestamp and Invocation ID, that would help us to debug. :)
