### ISSUE TITLE
Timer trigger not firing unless the Function App is opened in the portal

### ISSUE THREAD

**Issue by mikhailshilkov** [Azure/azure-functions-host#3522]
Timer trigger not firing unless the Function App is opened in the portal.

- Timestamp: 2018-09-25 throughout the day
- Function App version (1.0 or 2.0): 1.0
- Function App name: e.g. schedulev2js2e565301 ( I have 2)
- Function name(s) (as appropriate): schedulev2js
- Region: West Europe

#### Repro steps

I created 2 Function Apps with Run-from-Zip and a single Javascript Timer function with schedule = "0 */30 * * * *".

#### Expected behavior

The function fires every 30 minutes.

#### Actual behavior

The function fires only when I open it in the portal:

![image](https://user-images.githubusercontent.com/1454008/46044403-91884880-c112-11e8-836b-25608804080f.png)

#### Related information 

Javascript function deployed with Pulumi.

**Comment by davidebbo** [comment]
I do think there is an issue if you use the flavor of Run Form Package that points to an external URL (as opposed to the internal zip flow). In that case, triggers don't get synced correctly.

You can work around by doing an explicit sync from Portal (refresh button next to app name), or by calling the `syncfunctiontriggers` ARM action on the App.

**Comment by tohling** [comment]
Could you double-check your deployment process? Unfortunately, I am not familiar with using Pulumi.

I checked and we are not seeing any triggers sync'ed for your Function App, hence your Timer-Trigger will not be triggered on schedule. Here's what I am seeing on our end.

<img src="https://user-images.githubusercontent.com/14911331/46045631-0e93cd80-c0d3-11e8-9198-ee8ff0a83e0c.png" width="300">

Try restarting the Function App and update this thread. I will verify if we are seeing the trigger for your Function.

**Comment by mikhailshilkov** [comment]
@davidebbo @tohling Thanks for your replies. I clicked all Refresh buttons that I could find in the portal just now, so let's see if it helps...

**Comment by tohling** [comment]
Thanks! We are seeing the Timer-Trigger now (see snapshot below) and ScaleController logs is confirming this for your Function App. Let us know if you are still experiencing issues.

![image](https://user-images.githubusercontent.com/14911331/46048943-bb287c00-c0e0-11e8-976f-44096961df07.png)

**Comment by davidebbo** [comment]
@mikhailshilkov it will not break, but it will not trigger a new trigger sync. Concretely, this means that as long as your triggers are the same, it is fine. But if you were to change the schedule or add additional triggers, you would need to manually sync triggers again.

**Comment by mikhailshilkov** [comment]
Hmm... now I have the same issue with a Storage Queue trigger. Is it the universal problem for most bindings? Any ETA for a fix?

**Comment by davidebbo** [comment]
@mikhailshilkov part of the solution is now tracked by https://github.com/Azure/azure-functions-host/issues/3565.

**Comment by ankitkumarr** [comment]
Sorry for the late follow-up here. This should be fixed as part of the work-item tagged here.
With that, any update in Run-From-Package URL will trigger the host to perform a sync for all the triggers.

**Comment by thedoupub** [comment]
This seems to be still an active issue with python and time triggers.
