### ISSUE TITLE
Random 500 responses on heavy load

### ISSUE THREAD

**Issue by peterbomers** [Azure/azure-functions-host#3526]
Hi there,

Im using the new azure function runtime (2.0.12115.0) for executing a .net function.
This function is a HttpTrigger loading a record from a AzureCloudTable.

On heavy load (several 100 request per minute) the azure function runtime returns random 500 responses. There is invocation ID because the function is not executed. (the function has a try catch logging block at its entry point)
Eventually the runtime dies and the function only returns 500 response.

I've enabled detailed errors, request logging and even collected crash reports but I can't find the cause of the error. 

#### Investigative information

Please provide the following:

- Function App version: 2.0
- Function App name: https://function-documents-prod.azurewebsites.net
- Function name(s) (as appropriate):  GetSettings
- Invocation ID: -
- Region: West Europe

attached: detailed error & request event logging (removed bearer token for security reason)

[detailed error](https://github.com/Azure/azure-functions-host/files/2418714/IIS.Detailed.Error.-.500.0.-.Internal.Server.Error.txt)
[request log](https://github.com/Azure/azure-functions-host/files/2418717/https___function-documents-prod_80_api_settings_name.FertilityProtocol.scopes.installation_10372.scopes.global.STATUS_CODE.500.94.ms.GET.txt)

Any advice to find my problem?

Peter

**Comment by mlankamp** [comment]
Do you use any kind of dependency injection extension?

**Comment by peterbomers** [comment]
No, the only references used in the project are: 
`  <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.22" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.2.4" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.2" />`

System.IdentityModel.Tokens.Jwt is necessary to validate a bearer token.
WindowsAzure.Storage is necessary for the CloudTableClient.

Besides that, there are static initializers (constructors) to read connection strings from the environment.

**Comment by jeromekol** [comment]
@mlankamp we have the same issue, but we are using a dependency injection extension. Did you experience any issue with that?

**Comment by murdockcrc** [comment]
+1, we are observing this behavior in another project too.

**Comment by mlankamp** [comment]
@jeromekol this is my problem with DI
https://github.com/Azure/azure-functions-host/issues/3494

**Comment by pragnagopa** [comment]
@paulbatum - From the logs, it does look similar to #3527 
There are **7631** ActivityIds reported in WorkerTable

```
AntaresIISLogWorkerTable
| where PreciseTimeStamp >= datetime(2018-09-26T06:00:00Z) and PreciseTimeStamp <= datetime(2018-09-26T07:00:00Z)
| where Tenant == "36b2ac88b0ed4d80be33635734ac5fbe"
| where RoleInstance == "MediumDedicatedWebWorkerRole_IN_14"
| summarize count(ActivityId)
```
But only **7348** invocations in FunctionsLogs
```
FunctionsLogs
| where PreciseTimeStamp >= datetime(2018-09-26T06:00:00Z) and PreciseTimeStamp <= datetime(2018-09-26T07:00:00Z)
| where Tenant == "36b2ac88b0ed4d80be33635734ac5fbe"
| where RoleInstance == "MediumDedicatedWebWorkerRole_IN_14"
| summarize dcount(FunctionInvocationId) 
```

**Comment by ankitkumarr** [comment]
@peterbomers, apologies for the long delay here. 
Is this still a reproducible issue? If so, would you mind providing the new function app info facing that problem.
