### ISSUE TITLE
cuales son las limitaciones de una cuenta gratuita?

### ISSUE THREAD

**Issue by Dennis0095** [Azure/azure-functions-host#3529]
#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0):
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by pragnagopa** [comment]
Dup of #3530
