### ISSUE TITLE
WebJobs.Script.Host throwing InvalidOperationException when run

### ISSUE THREAD

**Issue by maiqbal11** [Azure/azure-functions-host#3531]
Seeing the following error when trying to run WebJobs.Script.Host for local development. Have not made any changes to the project. 

System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to resolve service for type 'Microsoft.Azure.WebJobs.DistributedLockManagerContainerProvider' while attempting to activate 'Microsoft.Azure.WebJobs.Extensions.Timers.StorageScheduleMonitor'.
  Source=Microsoft.Extensions.DependencyInjection
  
#### Investigative information

Please provide the following:

- Timestamp: 9:30 am, 09/27/2018
- Function App version (1.0 or 2.0): N/A
- Function App name: N/A
- Function name(s) (as appropriate): N/A
- Invocation ID: N/A
- Region: N/A

#### Repro steps

Build and run the latest WebJobs.Script.Host project.

#### Expected behavior

The project should start up the host locally for development.

#### Actual behavior

Failing currently with invalid operation exception.

#### Known workarounds

Use WebJobs.Script.WebHost for local development instead.

**Comment by brettsam** [comment]
Yeah, I'm guessing its dependencies are not set up correctly. It's just good enough to build, but none of us really run it as we all run the WebHost, which is what we ship for Functions.

**Comment by fabiocav** [comment]
Yes. This is something we've run into before and wasn't fixed. I'll update the console host. I had removed that, as its need has been diminished, but will update for now.
