### ISSUE TITLE
Queue settings are not respected with function app version 2.0.11961-alpha on an App Service plan

### ISSUE THREAD

**Issue by scott-lin** [Azure/azure-functions-host#3532]
**I'm observing two issues:**

1. My function is running on an App Service plan that I have restricted to 1 VM instance. I have configured my host.json queue settings with `"batchSize": 1` and `"newBatchThreshold": 0`. I am observing more concurrency than expected (8+ items at a time). I expected to see one item at a time processed from my queue per instance given these settings.

2. In addition, messages are being retried more than the `"maxDequeueCount": 5` setting I have configured. I expect messages to be sent to the poison queue when retried beyond this setting, but they are not.

#### Investigative information

- Timestamp: 10:48:34.093 AM PST
- Function App version: 2.0.11961-alpha
- Function App name: devautorest-functions
- Function name: autorestprocessor
- Invocation ID: 43ee596e-033a-40a6-9f75-39d3de49a659 (there are many more invocations at the same timestamp)
- Region: west us 2

#### Repro steps

1. Set function version to the above.
2. Configure host.json to:
```
{
  "version": "2.0",
  "functionTimeout": "00:10:00",
  "extensions": {
        "queues": {
            "maxDequeueCount": 5,
            "batchSize": 1,
            "newBatchThreshold": 0
        }
    }
}
```
3. Restart the function
4. Clear all messages in the queue
5. Pump a bunch of messages into the queue to trigger processing
6. Many messages from the queue are processed concurrently

#### Expected behavior
At step six, I expect one item to be processed concurrently instead of multiple.

#### Actual behavior
At step six, multiple items are processed concurrently.

#### Related information

Javascript
Bindings used
```
{
    "bindings": [
        {
            "name": "clientLibraryId",
            "type": "queueTrigger",
            "direction": "in",
            "queueName": "clientlibraryrequest",
            "connection": "STORAGEACCOUNT_CONNECTIONSTRING"
        }
    ],
    "disabled": false
}
```

**Comment by paulbatum** [comment]
Hi @scott-lin, sorry it took me so long to look at this. I took at look at the logs at the details you shared and the logs in our system and its pretty clear to me what is going on here. Your app is running on `2.0.11961-alpha` and this was the release prior to the host.json changes where you specify settings under "extensions". So your host.json is mismatched with the version you're running.

If you're still able to reproduce this issue on the GA bits (2.0.12115 or newer), then please share updated details (also if you could make sure you include a *full* UTC timestamp that would help save me time).

**Comment by scott-lin** [comment]
Thanks. I'd love to confirm, but I'm blocked on https://github.com/Azure/azure-functions-host/issues/3719. Will update this thread once I'm unblocked.

**Comment by shilsmarty** [comment]
@paulbatum i am facing the same issue as above on Version 2.0.12115.
Function works fine when changing it to batchSize 2 or more.
i get below error on batchSize 1  - System.Private.CoreLib: Exception has been thrown by the target of an invocation. Microsoft.Azure.WebJobs.Extensions.Storage: Specified argument was out of the range of valid values.

**Comment by scott-lin** [comment]
Confirmed @paulbatum's suggestion worked, so closing this issue thread. However, I did find another bug linked in the issue above.
