### ISSUE TITLE
ServiceBus autoRenewTimeout: better handling for invalid TimeSpan strings

### ISSUE THREAD

**Issue by i-movo** [Azure/azure-functions-host#3535]
#### Investigative information

Please provide the following:
2018-09-28T08:59:33.721 [Info] Function started (Id=c906f690-ed9c-4c12-9bfb-aefba2463fd3)
- Timestamp: 2018-09-28T08:59:33.721
- Function App version (1.0 or 2.0): 1
- Function App name: 
- Function name(s) (as appropriate):
- Invocation ID: c906f690-ed9c-4c12-9bfb-aefba2463fd3
- Region: UK South

#### Repro steps

Provide the steps required to reproduce the problem:

1. Update host.json and set serviceBus timeout settings to below:
```
{
  ...
  "serviceBus": {
    "autoRenewTimeout": "00:60:00" //error only after 60 minutes of inactivity
  }
}
```

#### Expected behavior

I would expect the function to understand 60 mins as a valid timeout,
or the config regex should reject 60 mins if its not happy about value.

#### Actual behavior

The function fails to run at all!

#### Known workarounds

Change the config to 1hr instead of 60minutes.

```
{
  ...
  "serviceBus": {
    "autoRenewTimeout": "01:00:00" //error only after 60 minutes of inactivity
  }
}
```

**Comment by brettsam** [comment]
We're using `TimeSpan.Parse()` on this value, and it may be failing on us when we parse 60 -- as the valid values are 0-59. I've re-titled this issue and we can provide a better experience here.

**Comment by i-movo** [comment]
Many thanks for the update Brett

**Comment by alrod** [comment]
https://github.com/Azure/Azure-Functions/pull/1098
