### ISSUE TITLE
Azure function proxies returning 500 until restart - No information in logs

### ISSUE THREAD

**Issue by AndreaCuneo** [Azure/azure-functions-host#3538]
#### Investigative information

- Timestamp: 2018-10-01T07:00:00 UTC => 2018-10-01T07:22:00 UTC
- Function App version (1.0 or 2.0): 2.0
- Function App name: prod-arkive-proxy-mgezi6a2xnxhm
- Function name(s) (as appropriate): all proxies
- Invocation ID:
- Region: North Europe

#### Repro steps

Cannot be reproduced deterministically.

#### Actual behavior

The behaviour is that from a certain moment in time requests return 500.
On 2018-09-27T14:15:00 UTC some requests were returning 500, others working fine.
On 2018-10-01T07:00:00 UTC all requests were returning 500.

The backend wasn't receiving the failing requests and was working fine (tested issuing requests directly).

Some requests were returning a Json payload with an activity ID, others didn't.
This is from 2018-09-27:
```
{
    "statusCode": 500,
    "message": "Internal server error",
    "activityId": "24cc7bce-3997-4f4a-946a-122b084aa25f"
}
```

Couldn't capture one this morning.

On 2018-09-27 I enabled diagnostic logs, and enabling them fixed the issue, I supposed due to the restart (confirmed this morning).

Logs this morning were showing only 200s, and were stopped on late Friday (last day the proxy was used). This morning nothing until the restart.

Auto heal was not kicking in even if we were seeing tens of 500.

[Logs](https://pastebin.com/j9qhBWFV)

#### Known workarounds

Restart the site. 

#### Requests

Is there something we can enable at least for auto-restarting it in the short-term? 
This is a production proxy and is currently impacting customers.

**Comment by ankitkumarr** [comment]
@AndreaCuneo, I sincerely apologize for not getting back to you until now. Is this still a reproducible bug? if so, would you mind providing recent logs / function details so I can look on our back-end to see what's going on.
