### ISSUE TITLE
Feature Planning: first class Go support

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-host#354]
This is a tracking item for first class Go support. We'll be tracking the requirements and issues for first class Go support via this item. Feel free to leave comments about features/design patterns. 

Initially from https://feedback.azure.com/forums/355860-azure-functions/suggestions/13758003-support-for-go
## Function format

**TBD**
## Data Type formats

**TBD**
## Version & Package management

**TBD**
## Testing/CI

**TBD**

**Comment by yvele** [comment]
I don't know how this can help you but here is a brand new and trending open source project that brings Go native support to AWS Lambda : https://github.com/eawsy/aws-lambda-go
It's quite interesting.. Maybe you can learn from it..

**Comment by radu-matei** [comment]
Hi, everyone!
Just wanted to let you know I've been working on a Go worker for Azure Functions - https://github.com/radu-matei/azure-functions-golang-worker

Any feedback is appreciated 😄

**Comment by fabiocav** [comment]
@esell there is no plan for Go support at the moment. The recommendation is to use the custom handlers feature for this (https://learn.microsoft.com/en-us/azure/azure-functions/functions-custom-handlers)
