### ISSUE TITLE
Generate CLI artifact as part of host build

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#3546]
VSCode and mvn azure functions plugin CI testing need to run tests on latest functions host build.
Easiest way for tooling to consume runtime is via CLI.

Generating CLI artifact as part of functions host build will enable E2E testing for Java, Python and VSCode on Functions Host nightly builds

**Comment by soninaren** [comment]
This is not complete https://github.com/Azure/azure-functions-core-tools/pull/913
