### ISSUE TITLE
Three of my v1.0 function apps stopped working last night

### ISSUE THREAD

**Issue by npiasecki** [Azure/azure-functions-host#3550]
So last night, around 9:45 PM EDT, three of my v1.0 Azure Functions apps simply stopped running. The three effected ones were all running an App Service Plan -- the other ones running in Consumption mode seem to be fine. Websites in the App Service Plan seemed to be running fine, and two other function apps in the same App Service Plan were fine. I restarted the three effected apps via the portal, and they came back to life.

In the error logs, I noticed a lot of name resolution errors (in the function app code, trying to resolve names like fedex.com and netsuite.com as part of its tasks) right before everything stopped working. And the next morning, when I logged into the Portal with my hair on fire, clicking on a function yielded a nasty red box with text such as the following:

`Function (RefreshTrackings) Error: The listener for function 'Functions.RefreshTrackings' was unable to start. mscorlib: One or more errors occurred. Microsoft.Azure.WebJobs.Host: Invalid storage account 'stsvlabelsprod'. Please make sure your credentials are correct. Microsoft.WindowsAzure.Storage: The remote name could not be resolved: 'stsvlabelsprod.blob.core.windows.net'. System: The remote name could not be resolved: 'stsvlabelsprod.blob.core.windows.net'. The listener for function 'Functions.RefreshTrackings' was unable to start. mscorlib: One or more errors occurred. Microsoft.Azure.WebJobs.Host: Invalid storage account 'stsvlabelsprod'. Please make sure your credentials are correct. Microsoft.WindowsAzure.Storage: The remote name could not be resolved:  ...`

The three function apps that were effected happen to be ones that make a lot of network calls and run quite frequently (i.e., every minute): refreshing tracking numbers, polling for orders, checking e-mails.

So right now my theory is somewhere in the East US datacenter, there was a DNS blip and all name resolution just stopped working. This seemed to cause the Functions Host to fail in a nonrecoverable way: the Portal said it was "Available", but nothing was actually executing until I restarted the process.

Any clues as to what could cause this behavior and how I can make the process more resilient? Would pinging a function in the app from an external source like Pingdom "wake it up" should this kind of event occur again in the future? Thank you.

- Last timestamp 2018-10-02T01:46:00.0068809+00:00
- Effected apps: fn-sv-labels-prod, fn-sv-sync-prod, fn-sv-tickets-prod
- App Service Plan: app-sv-shared-prod
- Location: East US

**Comment by mathewc** [comment]
In the logs you can see that the host was continually trying to recover, but was unable to connect to your storage account for some reason. This auto recovery mechanism is intended to heal from transient issues, however it looks like your app was stuck in this state for a very long time.

**Comment by npiasecki** [comment]
Thank you for responding! Yes, the three apps stayed in this state until I pressed Restart on the Function App about 9 hours later (why do these things always seem to happen during the night), then they immediately came back to life. While two of the apps get new deployments often, one of them hadn't been touched in months, so I don't think it was a recent change on my side.

The 'The remote name could not be resolved' errors extended to the last logging throes of the application code, failing to resolve external names like "fedex.com". It seems it also extended to the storage account domain name as well, and I'm guessing that's why the host was unable to recover. 

What I'm at a loss to explain is what could cause a process to fail to resolve domain names and is solved by kicking the process. As far as I can tell, App Service didn't boot us to a new VM so there wasn't any funny business going on there, either.

**Comment by mathewc** [comment]
Yes, I'm not sure yet either. I have seen this happen before and we have a work item tracking further improvements to our auto-recovery. See https://github.com/Azure/azure-functions-host/issues/2972.  I mention a case similar to yours in that issue description - where listeners were unable to start and we never recovered. The idea is to apply a heuristic to identify such cases and recover automatically by doing a hard restart.

**Comment by ankitkumarr** [comment]
Closing this issue as it looks like the tagged issue for improvements on auto-recovery was fixed and closed. 

Please feel free to re-open the issue if you continue to see issues with recent logs.
