### ISSUE TITLE
[DI] extensions.json missing starup class entry

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#3554]
Posted on SO:
https://stackoverflow.com/questions/52583637/azure-function-publish-not-creating-startup-class-entry-in-extensions-json

@soninaren / @fabiocav  any ideas?

**Comment by pragnagopa** [comment]
Dup of https://github.com/Azure/Azure-Functions/issues/972

**Comment by gaikovoi** [comment]
https://github.com/Azure/Azure-Functions/issues/928#issuecomment-427036687
