### ISSUE TITLE
Test 'premium' sku on linux 

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-host#3556]
There's been some indication that this should work OOB. Starting an issue to track the E2E testing.

/cc @dariagrigoriu @jeffhollan

**Comment by mhoeger** [comment]
@asavaritayal - would you mind assigning and adding a milestone to the issue? (context: trying to clean up untriaged bugs!)

**Comment by fabiocav** [comment]
@jeffhollan is this done?

**Comment by jeffhollan** [comment]
In progress. Should complete this week

**Comment by fabiocav** [comment]
Sounds good. Moving this to Sprint 36

**Comment by fabiocav** [comment]
Did you manage to finish this? Should this be closed?

**Comment by jeffhollan** [comment]
Closing as we aren't tracking out of the host repo.  There is an issue in VSTS around this.  If there should be a corresponding GitHub one it's likely out of the Azure-Functions repo. @dariagrigoriu is leading this effort and is progressing.
