### ISSUE TITLE
Bindings error after deployment

### ISSUE THREAD

**Issue by GuyHarwood** [Azure/azure-functions-host#3557]
#### Investigative information

- Timestamp: 2018-10-03T16:29:26.054Z
- Function App version (1.0 or 2.0): 2.0
- Function App name: devfuncmtc
- Function name(s) (as appropriate): completed-checks, check-started
- Invocation ID: unable to provide, cannot run function
- Region: West Europe

#### Repro steps

Provide the steps required to reproduce the problem:

1.  Deploy Javascript functions from Azure DevOps to Azure
2. Open functions app in Azure Portal
3. Navigate to any one of the functions in the list and receive the following error in red box on right hand side of screen...

```
Function (completed-checks) Error: The binding type(s) 'queueTrigger, table' are not registered. Please ensure the type is correct and the binding extension is installed.
```

During the build & deployment phase i am performing the following tasks (as javascript function deployment is currently undocumented)....

- npm install
- `func pack`
- `func extensions install`
- delete node_modules folder
- publish

#### Expected behavior

Function opens in portal without an error

#### Actual behavior

receive error message...

```
Function (completed-checks) Error: The binding type(s) 'queueTrigger, table' are not registered. Please ensure the type is correct and the binding extension is installed.
```

#### Known workarounds

None

#### Related information 

* Programming language: Javascript 
* Source-code: https://github.com/DFEAGILEDEVOPS/MTC/tree/master/functions
* Bindings used: storage-queues, storage-tables

**Comment by mhoeger** [comment]
@GuyHarwood - was this issue the result of the deployment issues you were having with Linux (https://github.com/Azure/azure-functions-host/issues/3579)? From the information provided, it does look like your bin folder doesn't contain all the needed artifacts.

Please let me know if deploying to a Windows machine fixes your issue, and if I can close this!

**Comment by GuyHarwood** [comment]
@mhoeger possibly.  i think it's best to close this now, and i will start fresh on a windows function app

**Comment by mhoeger** [comment]
Sounds good - thanks!
