### ISSUE TITLE
[VNET]Do not require setting IPV4 flag for using point to site vpn tunnel

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#3559]
_From @mccoyer001 on July 11, 2018 4:58_

Java Azure function does not allow http client post/get through point to site vpn tunnel

**Step 1**: Configure site to site vpn vnet to on-premise infrastructure 
**Step 2**: Configure azure function app to use point to site tunnel to the site to site vnet.  (Used https://docs.microsoft.com/en-us/azure/app-service/web-sites-integrate-with-vnet as reference)
**Step 3**: Validate transport from azure function app using Kudu Console link under platform features-> development tools using tcpping to an ip in the on-premise server.
We see this working fine and traffic is seen on on-premise server.
```
tcpping a.b.c.d:443
Connected to a.b.c.d:443, time taken: 156ms
Connected to a.b.c.d:443, time taken: 15ms
Connected to a.b.c.d:443, time taken: 15ms
Connected to a.b.c.d:443, time taken: 15ms
Complete: 4/4 successfull attempts (100%). Average success time: 50.25ms
```
**Step 4**: From azure function establish http or https connection with on-premise machine
Sample java code for connecting is below
```
//a.b.c.d is used here to hide the real ip we are using
URL url = new URL("https://a.b.c.d/);
HttpURLConnection connection = (HttpURLConnection) url.openConnection();
connection.setRequestMethod("GET");
connection.setReadTimeout(30000);
connection.connect();
```
What we see is that the connection times out and nothing is sent through the tunnel when run from the function. We attempted to do the following as debug steps
**test 1:** Added code to the existing java function to do a tcp based ping to port 7 on the on premise machine. Used the following code 
```
InetAddress address = InetAddress.getByName("a.b.c.d");
boolean reachable = address.isReachable(10000); // send via tcp port 7
```
This works! We can see the packets to tcp port 7 on our on-premise machine. Tcp port 7 is used by default to do the ping according to the InetAddress class. So we know the java function itself is capable of sending traffic over vpn. 
**test 2:** Added new code to do a plain socket connection to port 443 and port 7 to see if a basic socket will work. 
`Socket clientSocket = new Socket("a.b.c.d", 443);`
This does not work. Connection times out and not a single packet gets to the on-premise machine. So it seem like there is definitely something different with how java is trying to establish the connection.  
**test 3:** Repeated the same above test with tcp port 7 to see if that works since the InetAddress class can send a ping to port 7 successfully.
`Socket clientSocket = new Socket("a.b.c.d", 7);`
 This fails which is odd with the same behavior. Either InetAddress is doing something completely different to establish the connection compared to using a basic socket or the http client.
**test 4:** Finally we added a different azure function that is apart of the same function app that is C# based. It does a http client get. Sample code is here
`HttpClient client = new HttpClient();
HttpResponseMessage response = await client.GetAsync("https://a.b.c.d/");
`
This works and I can see packets through the tunnel arrive at a.b.c.d port 443.  So C# has no problems with sending traffic from the azure function via the tunnel. 

So it seems like only java functions have an issue with using the vpn if using a http client lib or doing a basic socket connect but the InetAddress class does not seem to have an issue sending traffic.

_Copied from original issue: Azure/azure-functions-java-worker#139_

**Comment by pragnagopa** [comment]
Can be addressed by updating worker.config.json reactivated issue in java worker repo

**Comment by njwilloughby** [comment]
Was having issues with this exact issue and eventually resolved it by adding this application setting to the function app

APP SETTING NAME | VALUE | 
-- | -- 
languageWorkers:java:arguments | -Djava.net.preferIPv4Stack=true   

Note that other examples of this have a capital 'V4' which didn't work when I used it. The lower case 'v4' works for me.
