### ISSUE TITLE
Use extensions bundles instead of installing individual extensions

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#3562]
The flexibility provided by installing and managing exact extension versions comes at a cost to the non .NET developer experience. Extension bundles can be a compromise that gives up some flexibility but drastically simplifies the use of platform features that rely on extensions.

**Comment by soninaren** [comment]
related issue on core tools
https://github.com/Azure/azure-functions-core-tools/issues/367

**Comment by paulbatum** [comment]
Hey @soninaren can you start adding the breakdown for this work to the issue?

**Comment by soninaren** [comment]
Have added a few related issues. Will be adding more.
https://github.com/Azure/azure-functions-host/issues/3710
https://github.com/Azure/azure-functions-host/issues/3711
https://github.com/Azure/azure-functions-host/issues/3712
https://github.com/Azure/azure-functions-host/issues/3713

**Comment by soninaren** [comment]
https://github.com/Azure/azure-functions-host/issues/3714

**Comment by soninaren** [comment]
https://github.com/Azure/azure-functions-host/issues/3715
