### ISSUE TITLE
Functions Class library project proxies not working once deployed to Azure. 

### ISSUE THREAD

**Issue by thivy** [Azure/azure-functions-host#3567]
#### Investigative information

- Timestamp: 5th October 2018
- Function App version (1.0 or 2.0): 2.0
- Function App name: Not able to prove the name
- Function name(s) (as appropriate): Not able to prove the name
- Invocation ID: 
- Region: East South East Asia

#### Repro steps

1. Create a new C# V2.0 Functions app on Visual Studio 2017
2. Create a new proxies.json file and add it to the solution
3. In the proxy file, create a simple proxy to an external api https://docs.microsoft.com/en-us/azure/azure-functions/functions-proxies

4. Commit the code to Azure DevOps and deploy using Azure DevOps release pipeline
5. Navigate to the proxy yourfucntion.azurewebsites.net/proxy from Azure Functions url, the response is **404**
6. Go to the azure portal and open Azure Functions proxies, using the Advance editor. 
7. Update the file by adding a space and save it
8. Navigate to yourfucntion.azurewebsites.net/proxy and the response is successful
9. Once the functions cools down, proxy url is lost again

**Comment by davidebbo** [comment]
Dup of #3533

**Comment by davidebbo** [comment]
The fix is now deployed worldwide in Azure.

**Comment by thivy** [comment]
Yes it works!!
