### ISSUE TITLE
Backport host keys thread synchronization fix to 1.0

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#3570]
We recently fixed a race condition with host keys management in https://github.com/Azure/azure-functions-host/commit/08cb762e8c091e0b7c5ebdfefd35df6c82db7975

That fix should be back-ported to 1.0 as we have customers impacted by the same issue there.

**Comment by alrod** [comment]
https://github.com/Azure/azure-functions-host/issues/3570

**Comment by alrod** [comment]
https://github.com/Azure/azure-functions-host/commit/6ebe1e0403aea6be39b8fd5db96000e1e45d14c8
