### ISSUE TITLE
Restore special handling for site/tools directory 

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#3576]
We used to have special handling for the site/tools directory in v1 (see [here](https://github.com/Azure/azure-functions-host/blob/0dc5ffdddd739cebc41fc9e55d31fe4a2161d4b8/src/WebJobs.Script.WebHost/App_Start/WebHostResolver.cs#L322)). We put this directory on the PATH and also set up a file watcher on that directory. This supported scenarios where user have a custom shared tool they need to run from their functions. We should add this capability back.

**Comment by ankitkumarr** [comment]
@mathewc, at this point, do you think this is still something we should add? I was wondering if we have customer asks for this capability.
