### ISSUE TITLE
Manual change required to use node runtime in consumption plan function app

### ISSUE THREAD

**Issue by GuyHarwood** [Azure/azure-functions-host#3584]
#### Investigative information

Please provide the following:

- Timestamp: None given
- Function App version (1.0 or 2.0): v2
- Function App name: mtc-test
- Function name(s) (as appropriate): guy
- Invocation ID: none given
- Region: UK South
- Host Type: Consumption plan (windows)
- Language: Javascript
- Node Runtime: 10.6.0

#### Repro steps

- create boilerplate HttpTrigger and set language to Javascript
- create Function App set to consumption plan
- deploy function as package via dropbox
- open console from portal, observe that function package has been extracted correctly into wwwroot and functions within app are listed in portal
- go to HttpTrigger function
- go to 'test' panel and set HTTP VERB to 'get'
- run function
- observe 404
- try function from raw URL, in this instance it would be https://mtc-test.azurewebsites.net/api/guy?name=roger
- observe 404

#### Expected behavior

returns 200 OK and 'Hello roger'

#### Actual behavior

Provide a description of the actual behavior observed.

returns 404 not found

#### workaround

 manually change `FUNCTIONS_WORKER_RUNTIME` from `dotnet` to `node`

**Comment by mhoeger** [comment]
@hartra344 - can you comment on the logic used to choose FUNCTIONS_WORKER_RUNTIME? Would FUNCTIONS_WORKER_RUNTIME have to be defined in local.settings.json, or does a Dropbox deployment even look for this?

**Comment by GuyHarwood** [comment]
@mhoeger according to [the documentation on host.json](https://docs.microsoft.com/en-gb/azure/azure-functions/functions-host-json), there appears to be nowhere to define the runtime.  

It would make sense to do so, given that you can only use one language across the function app

**Comment by ChristianWeyer** [comment]
I have a similar issue with a freshly created JavaScript HTTP trigger function in VS Code, and then deployed to Azure.
Also always gives me a 404 - and there is no error showing up in App Insights.

**Comment by mhoeger** [comment]
I'm going to be closing this issue in favor of this tracking issue: https://github.com/Azure/azure-functions-host/issues/3120

Adding the FUNCTIONS_WORKER_RUNTIME setting to host.json (and therefore source controlled and deployed code) will solve this. Thanks!
