### ISSUE TITLE
Protobuf Contract download link broken

### ISSUE THREAD

**Issue by harlecin** [Azure/azure-functions-host#3586]
Hey there,

just read the wiki of [Azure Functions Language Extensibility](https://github.com/Azure/azure-functions-host/wiki/Language-Extensibility) and wanted to download the Protobuf Contract, but the link is broken (here is the [Link](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.Grpc/Proto/FunctionRpc.proto))

Best
Christoph

PS.: Really looking forward to Azure Functions v2 with Docker getting a Consumption Plan:)

**Comment by mhoeger** [comment]
@harlecin - thanks for the heads up! Fixed to point to here: https://github.com/Azure/azure-functions-language-worker-protobuf/blob/dev/src/proto/FunctionRpc.proto
