### ISSUE TITLE
Azure Function Blob Trigger not firing

### ISSUE THREAD

**Issue by bonggoy** [Azure/azure-functions-host#3592]
#### Investigative information

Please provide the following:

- Timestamp: 2018-11-10
- Function App version (1.0 or 2.0): 1.0
- Function App name: tikitingproductionfapp2
- Function name(s) (as appropriate): BlobTriggerManifestUpload, BlobTriggerStatusUpdate
- Invocation ID: west-europe
- Region:

#### Repro steps

Provide the steps required to reproduce the problem:

Not applicable. This is an investigation as to why the activity in triggers did not cause their corresponding Functions to run.

#### Expected behavior

Provide a description of the expected behavior.

CSV files are dropped to blob storage(s).  Function apps are supposed to be triggered when this happens.  These Function apps is to call an Azure SQL SP which will handle the uploading of it's content into a sql table.  The CSV file is then deleted after a succesful upload.

In theory, no CSV files should be in those blob storage since they should be processed and deleted right away.

#### Actual behavior

For the last few weeks now, every morning EST, I will see a few CSV files (as much as a few hundreds of them) sitting in the blob containers.  

#### Known workarounds

I manually force the function app to fire by either renaming the csv (if it's only a few of them) or by manually uploading these CSV files.  I have been doing these for a few weeks now - daily.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by bonggoy** [comment]
Is this the correct forum for bugs or should I go somewhere else?

**Comment by meixger** [comment]
I have the same problem.
Blob trigger was working for week.
Stopped working last weekend.
After re-starting the function app the blob trigger picked up again.
Nothing interesting in the log files.

**Comment by dikokob** [comment]
Any help with this as yet?

**Comment by ankitkumarr** [comment]
@bonggoy, I apologize for not getting to you sooner. Unfortunately, our logs go stale after a few days, so it will be very difficult for me to investigate. If you do see this issue again, please provide the updated details on the Function App and we will be happy to look into what's going on.

As for others, please open separate issues as we need to deal with these on a case by case basis. There could be several reasons for why a trigger may not fire. So for each case, we need the specific inovcation/function app information required in our issue template.
