### ISSUE TITLE
Deployment center: VSTS deployment fails every time with javascript functions

### ISSUE THREAD

**Issue by GuyHarwood** [Azure/azure-functions-host#3594]
#### Investigative information

Please provide the following:

- Timestamp: n/a
- Function App version (1.0 or 2.0): 2.0
- Function App name: mtcfunctest
- Function name(s) (as appropriate): n/a
- Invocation ID: n/a
- Region: West Europe
- Type: Consumption plan
- OS: Windows
- Runtime stack: Node
- Node version: 10.6.0
- WEBSITE_RUN_FROM_PACKAGE=1 (have also tried without this setting)
- WEBSITES_ENABLE_APP_SERVICE_STORAGE=false (have also tried without this setting)

#### Repro steps

1. Create function app as per specifics above
2. Go to deployment center (preview)
3. Choose VSTS as source
4. Select account, repository and branch
5. Click deploy
6. Wait for deployment center to indicate success
7. refresh function app
8. observe functions node refreshing, and then stopping
9. observe no functions have appeared
10. go to console
11. navigate to `wwwroot`
12. list contents of folder using `ls` command
13. observe a `host.json` file and `functions` folder.
14. navigate to `functions` folder and list contents
15. observe `node_modules` folder, and nothing else.
16. navigate to `node_modules` folder and list contents
17. observe lots of npm modules

#### Expected behavior

A deployed set of functions

#### Actual behavior

A broken functions app with no functions.

**Comment by ankitkumarr** [comment]
@GuyHarwood, I apologize for not getting back to you in time. I see that your function app no longer exists. If this is still an issue, would you mind providing the app details experiencing this problem? I would be happy to take a look. Once again, sorry for not getting to you sooner.

**Comment by GuyHarwood** [comment]
this was nearly a year ago.  





a year
