### ISSUE TITLE
+0

### ISSUE THREAD

**Issue by harsha-nairy** [Azure/azure-functions-host#3595]
#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0):
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by mhoeger** [comment]
@harsha-nairy - I think you opened this on accident... Closing!
