### ISSUE TITLE
Performance Related Issues

### ISSUE THREAD

**Issue by grahamehorner** [Azure/azure-functions-host#3596]
The design and implementation of the AzureFuction UX suffers from perfomance issues that seem to stem from how it is using the current implementation of the azure-functions-host webhost API; while the UX is caching the response of the webhost api calls response only partly addresses the issue; the webhost API and the UX should be better aligned to avoid performance issues.

### Repro steps
create a functions app with 10, 50, 100, 1000 functions and watch the performance degrade. 

### Any error messages
UI can freeze and fail to recover

### Mention any other details that might be useful.
webhost API should cache the response (or use http caching) to improve performance of APIs that read/generate reponses by scanning/reading from file system and/or using reflection or triggering a function/host warmup or offload the data used by the UX to some common storage

https://github.com/Azure/azure-functions-ux/issues/3287

**Comment by grahamehorner** [comment]
@ehamai wondering if signalR as a service would be better for the communication between the UI and API, providing a loosely coupled async event push interaction between the components of the webhost and UI thus avoiding performance impact where possible ?

**Comment by ankitkumarr** [comment]
@grahamehorner, apologies for the late follow-up here.

We understand your concerns regarding the performance of the UX and the host. So far, we have not seen or recommend customer scenarios with such high number of functions in a function app. Was there a specific number of functions when you think the performance degrades enough to have an impact on the use?

At the moment, we do not foresee considerable impact on customers by changing the communication design. However, if things change in the future, we would be happy to reconsider the communication flow.
