### ISSUE TITLE
VSTS pipeline Deployment succeeds but functions fail to load 

### ISSUE THREAD

**Issue by GuyHarwood** [Azure/azure-functions-host#3597]
#### Investigative information

Please provide the following:

- Timestamp: n/a
- Function App version (1.0 or 2.0): 2.0
- Function App name: mtcfunctest2
- Function name(s) (as appropriate): check-started, check-complete, feedback and a few others
- Invocation ID: n/a
- Region:  West Europe
- Type: Consumption plan
- OS: Windows
- Runtime stack: Node
- Node version: 10.6.0
WEBSITE_RUN_FROM_PACKAGE=1

#### Repro steps

1. create a function app with the above settings
2. create a new pipeline in VSTS from [the same as this yaml definition](https://github.com/Azure/azure-functions-host/files/2469323/deploy.yaml.txt) or do it manually (as i did)
3. run the pipeline and observe how it succeeds
4. go to your functions app, refresh the functions app
5. watch the functions node spin around as if its refreshing and going to list all your functions.
6. watch in dismay as nothing appears
7. go to the console, navigate to `wwwroot` and list the contents
8. observe `host.json` and a `functions` folder
9. navigate to the `functions` folder and list the contents
10. see all your functions and repo content and wonder why it never works. 

#### Expected behavior

Javascript functions deploy and work

#### Actual behavior

Broken functions app

#### Known workarounds

the steps above were [supposed to be a workaround](https://github.com/Azure/azure-functions-host/issues/3579#issuecomment-428228146) as recommended by @davidebbo 

@mhoeger i am really struggling here.  for 3 weeks we have been unable to deploy our javascript functions app.  This is intended to be part of a national UK education solution and i am out of ideas.  Why can we not get a successful deployment of javascript functions?  are they actually GA? or was that just for dotnet?

**Comment by GuyHarwood** [comment]
its probably also worth mentioning that i have tried this with a bare-bones HTTP trigger function that has no node modules dependencies and i had the exact same experience

**Comment by GuyHarwood** [comment]
turns out that a setting on the zip creation task in VSTS `Prepend root folder name to archive paths` needs to be unchecked (it is checked by default).  Otherwise this puts everything in a folder which is carried through on deployment.

**Comment by davidebbo** [comment]
Ah yes, having an extra folder level will indeed mess things up on the server. Typically, the way to investigate these is to go into Kudu console under wwwroot, and make sure that the files are exactly what you expect to be. Anyway, glad you figured it out, and sorry it had to be so painful!
