### ISSUE TITLE
Use unique source in system logs for key management operations

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#3605]
Looking at a V2 app (2.0.12115.0), I see log entries `Non-decryptable function ('vms') secrets detected. Refreshing secrets.` with source "Host.General". We should have some sort of unique source for key related logs.

**Comment by alrod** [comment]
https://github.com/Azure/azure-functions-host/commit/7aa72290a0e3e00f161cf2dd80dbdf0f4b74b100
