### ISSUE TITLE
Port not getting released

### ISSUE THREAD

**Issue by bherila** [Azure/azure-functions-host#3612]
Seemingly randomly, after I exit my function app, I am no longer able to open it for a few minutes because func.exe is failing to bind to the port. I'm seeing an error like: 

> func start
> Port 7071 is unavailable. Close the porcess using that port, or specify another port using --port [-p].

(p.s. "process" is spelled incorrectly)

If I change the port, it works, but it's really inconvenient to have to keep changing the port! Please advise how I can debug this or if there's some shadow process I can kill to release the port?

**Comment by JohnReeson** [comment]
Dup of [this](https://github.com/Azure/azure-functions-core-tools/issues/806), can be closed.
