### ISSUE TITLE
Failed to start language worker process for node

### ISSUE THREAD

**Issue by sunxinhuan** [Azure/azure-functions-host#3614]
**Ibiza portal URL**:   https://aka.ms/antuxstage
**Runtime version**:   2.0.12134.0 (~2)
**Browser**: Chrome
**Hosting Plan**: Consumption

For V2 function app, failed to start language worker process for node.

Please refer to the snapshot:
![nodefailed](https://user-images.githubusercontent.com/39791546/46943508-5f7b5e00-d0a2-11e8-928a-6f892147030d.PNG)

**Repro steps**:
	1. Open a V2 function app;
	2. Add the app setting to running JS scenarios in Azure: FUNCTIONS_WORKER_RUNTIME=node
	3. Add a HttpTrigger template;
	4. Click "Run" button and Verify the Logs.

**Comment by agruning** [comment]
@sunxinhuan what is the value of your app setting: WEBSITE_NODE_DEFAULT_VERSION ?

**Comment by RudyLu** [comment]
+1,
The value of `WEBSITE_NODE_DEFAULT_VERSION` for my setup is `6.5.0`.
But if I changed it into `8.12.0`, it would show a different error msg.

**Comment by stillnet** [comment]
I'm getting this error. My node version (by default, I haven't changed it), is 11.something. I don't think the solution is to change it back to 8.11.1, right? That was the solution for people who where on an older version (6.x).  Any other ideas?

**Comment by brunoogata** [comment]
@stillnet I changed it to 8.11.1 and started working again.

**Comment by rene78** [comment]
Same problem here.
Funnily after one more successful call of the function from my webapp it stopped working with "Error: Failed to start language worker process for: node. node exited with code -1". Node default version: 8.11.1
![image](https://user-images.githubusercontent.com/36115705/53277666-4e53f500-3705-11e9-8255-2aa913b1068e.png)

**Comment by tobybrad** [comment]
For the brave souls who have gone the Linux route:

ls /opt/nodejs from the console or Kudu will show you available versions. At the time of writing 10.1.0 is the highest available version and this once works for me.

**Comment by brunoogata** [comment]
Every time this error appears, I change the node version and refresh the page. This is a efemerous repair but allows me to keep working.

**Comment by oreporan** [comment]
What a stupid bug...
Changing the version and refreshing fixed for me as well

**Comment by ChrisL108** [comment]
Same thing here. Refreshing Node version did the trick. 
Agree with @rene78, this would be unacceptable for a production level app.

**Comment by A142838** [comment]
Same happens for us after each deployment
Runtime version of function
Runtime version: 2.0.12382.0 (~2)
Node Version set : WEBSITE_NODE_DEFAULT_VERSION  -> 8.11.1
Runtime versions on the app service plan has 8.11.1 available
Error message : error failed to start language worker process for node. the operation has timed out

**Comment by tsmorton** [comment]
I've started seeing this as well post deploy for one of my function apps.  Changing _any_ application setting appears to resolve this which is easier than messing around with the set of valid values for WEBSITE_NODE_DEFAULT_VERSION.  Just restarting the function app doesn't appear to work.

**Comment by soninaren** [comment]
Several folks are having different issues from different symptoms. Please open a new issue if you can still reproduce the issue. The supported node versions are version 8.x and 10.x. As of today we have support for WEBSITE_NODE_DEFAULT_VERSION -> `~8` and `~10` as version values.
