### ISSUE TITLE
Docker container functions do not honor host.json batchSize

### ISSUE THREAD

**Issue by Void-Barrie** [Azure/azure-functions-host#3616]
#### Investigative information

Please provide the following:

- Timestamp: 10/15/2018, 11:40:23 AM
- Function App version 2.0
- Function App name: -redacted--builder
- Function name(s) (as appropriate): Function.-redacted-File
- Invocation ID: 3e8ff5da-ff0f-49ea-93e9-4a9d4d999123, 30b89dc2-0504-4dd2-bcaa-5ed6cab28143, 87d5a062-c89f-4836-aa7f-ec21ba4ce06d, etc...
- Region: WestUS

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a container-based function triggered by a blob
2. Configure container host.json to "batchSize": 1
3. Deploy, and trigger with more than 1 file

#### Expected behavior

Provide a description of the expected behavior.

- I would expect the function to process one file at-a-time, per app service plan instance (VM)

#### Actual behavior

Provide a description of the actual behavior observed.

- Containers attempt to process all new files concurrently, regardless of 'batchSize' setting

#### Known workarounds

Provide a description of any known workarounds.

-  none

#### Related information 

Provide any related information 

* C# function, blob trigger in and out
* host.json
```javascript 
{
    "version": "2.0",
    "queues": {
        "batchSize": 1,
        "maxDequeueCount": 1
    }
}
```

**Comment by soninaren** [comment]
The host.json config is incorrect. The queue related config should be under extensions object.

```Javascript
{
    "version": "2.0",
    "extensions": {
        "queues": {

        }
    }
}


Please refer to this page for more information:
https://github.com/Azure/azure-functions-host/wiki/host.json-(v2)

**Comment by soninaren** [comment]
Resolving as answered, please re-open the issue if the host.json change does not fix the issue or you.
