### ISSUE TITLE
Repeat $ for category of EventGrid in metadata.json

### ISSUE THREAD

**Issue by sunxinhuan** [Azure/azure-functions-host#3633]
**Ibiza portal URL**:  https://portal.azure.com/?websitesextension_ext=appsvc.env=next
**Runtime version**:   2.0.12134.0 (~2)
**Browser**: Chrome
**Hosting Plan**: Consumption

Please refer to the snapshot:
![category](https://user-images.githubusercontent.com/39791546/47146262-4ec72400-d2fe-11e8-85d0-27b8327f96c7.png)

**Repro steps**:
1.Open a V2 function app;
2.Navigate to template picker page;
3.Verify the Scenario dropdown list.

**Comment by soninaren** [comment]
Fixed https://github.com/Azure/azure-functions-templates/commit/1fdda8246a82211b8144cbdc0bea1c46ac576136
