### ISSUE TITLE
ARM call to get admin token on Linux Consumption app fails

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Azure/azure-functions-host#3635]
We are calling this rest api: 
https://docs.microsoft.com/en-us/rest/api/appservice/webapps/webapps_getfunctionsadmintoken

Which works well on a Windows Function App. But on a Linux Consumption function app this is the response I get:
```
<!DOCTYPE html><html><head>    <title>Your Azure Function App is up and running.</title>...
```

No token. Not even an error. Just the default "up and running" page.

#### Investigative information

- Function App version (1.0 or 2.0): 2.0
- Function App name: emjpy1
- Function name(s) (as appropriate): HttpTrigger
- Region: West US

For more context, we're using the admin api to get keys for Http Triggers in VS Code. We would call the ARM api to listkeys directly, but it's not working as explained here: https://github.com/Azure/azure-functions-host/wiki/Changes-to-Key-Management-in-Functions-V2#arm-impact

**Comment by EricJizbaMSFT** [comment]
ping @asavaritayal @dariagrigoriu

**Comment by amclin** [comment]
This is causing Azure Functions to show up in VSCode as invalid:
![screen shot 2019-01-31 at 7 18 41 pm](https://user-images.githubusercontent.com/105728/52100652-31585600-258d-11e9-96ca-34291ce289c2.png)

**Comment by mathewc** [comment]
Will be addressed by https://github.com/Azure/azure-functions-host/issues/3994. Specifically there will be a new API for listing function keys that will work regardless of runtime version.

**Comment by mathewc** [comment]
The new keys APIs are now live.
