### ISSUE TITLE
Extensions.json empty on publish

### ISSUE THREAD

**Issue by isaac2004** [Azure/azure-functions-host#3638]
I have a custom extension that uses Dependency Injection via WebJobsStartup. When I attempt to publish my function via Visual Studio, the function does not run. After some research, the culprit is extensions.json in Kudu is not populated with my custom extension. 

Digging into this more, it seems that dotnet publish (which VS fires under the hood) does not populate extensions.json with my custom extension, but dotnet build does

Here is a repo and steps to reproduce

https://github.com/isaac2004/missingextensionfunction

```bash
git clonehttps://github.com/isaac2004/missingextensionfunction.git
cd misssingextensionfunction
dotnet build -c Release
 cat .\bin\Release\netstandard2.0\bin\extensions.json

dotnet publish -c Release -o pub
cat .\pub\bin\extensions.json
````

As you can see, the published json file is empty. Is there an additional step that needs to be done to get this working. I tried with other extensions (ServiceBus for example) and did not have this issue. The same experience occurs publishing in Visual Studio

@fabiocav

**Comment by isaac2004** [comment]
@cecilphillip @anthonychu

**Comment by fabiocav** [comment]
@isaac2004 sorry about the delay on this. Dealing with a few issues and finally assigning this for investigation. Will update once I have some information to share.

**Comment by fabiocav** [comment]
@isaac2004 there's a known issue with the publish path and that is what is impacting you here. We'll keep https://github.com/Azure/azure-functions-host/issues/3386 open to track this. In the meantime, some of the workarounds mentioned on that thread may help you.

**Comment by fabiocav** [comment]
Closing in favor of https://github.com/Azure/azure-functions-host/issues/3386. We'll have that work prioritized and assigned.

**Comment by aliqaryan2** [comment]
I'm still having the same issue after publishing function v2.
