### ISSUE TITLE
Remove public HTTP endpoints

### ISSUE THREAD

**Issue by dariagrigoriu** [Azure/azure-functions-host#3669]
This is a customer request especially relevant in the context of Linux Consumption and applicable to non-HTTP triggered functions.

For this customer scenario the expectation is that functions deployed should not be publicly accessible. For example currently the management SCM endpoint is public. The request is to avoid any public endpoints including storage. 

The implication is that event sources like Event Grid should be capable to use altrenatives to public endpoints to create trust.

**Comment by mathewc** [comment]
Please add a better description for this issue - remove what public http endpoints?

**Comment by paulbatum** [comment]
We do not intend to remove the public HTTP endpoints from the functions host itself. If there is a need to create function apps that are not publicly addressable, that need is best addressed through networking technology or specific environments, such as an [ILB ASE](https://docs.microsoft.com/en-us/azure/app-service/environment/create-ilb-ase), or through additional platform work that would prevent frontend infrastructure from routing traffic to certain function apps, as discussed [here](https://github.com/Azure/Azure-Functions/issues/1005).
