### ISSUE TITLE
409 Errors With Consumption Apps

### ISSUE THREAD

**Issue by rowana16** [Azure/azure-functions-host#3672]
#### Investigative information

Please provide the following:

- Timestamp: 10:42:45 PM EST
- Function App version (1.0 or 2.0): 2.0 Consumption
- Function App name: 
- Function name(s) (as appropriate):
- Invocation ID: 194d3a29-ef2a-4da3-953c-ea9df2a6296e
- Region: East US 2

#### Repro steps

Provide the steps required to reproduce the problem:
1. Step A => Trigger the function via the queue message displayed in the logs

#### Expected behavior

Provide a description of the expected behavior.
Lots of this: 
ResultCode  409
https://*****.blob.core.windows.net:443/azure-webjobs-hosts/locks/cloudparsetoblob-demo/host?comp=lease 

Should Parse.  Should handle scaling.  Should do *anything*.  I don't know if it's V2 or the new limitless scaling, but nothing's been working since Ignite.

<!--
Example:
... Parsing

**Comment by soninaren** [comment]
Please open another issue if you still facing this. 

Please provide more detailed repro steps. a sample queue message would be helpful. Also please add date as a part of the `Timestamp`.
