### ISSUE TITLE
Deployment Center Doesn't Find Associated VSTS Account

### ISSUE THREAD

**Issue by rowana16** [Azure/azure-functions-host#3673]
#### Investigative information

Please provide the following:

- Timestamp:  Constant
- Function App version (1.0 or 2.0):  All
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region: East US2

#### Repro steps

Provide the steps required to reproduce the problem:
Try to use deployment center.
Try to link a VSTS repo.
Get this: 
![image](https://user-images.githubusercontent.com/19420223/47403471-a529cd80-d717-11e8-8b0c-9061098c8500.png)

#### Expected behavior

Provide a description of the expected behavior.
The old deployment system worked.  Please bring it back.

It should display my vsts account and populate the project, repo, etc as appropriate.

#### Actual behavior

Provide a description of the actual behavior observed.
No account is found.

**Comment by soninaren** [comment]
This is not the right repository for filing deployment center issues.
