### ISSUE TITLE
ServiceBusTrigger: prefetchCount not respected when prefetchCount > maxConcurrentCalls

### ISSUE THREAD

**Issue by TynThordin** [Azure/azure-functions-host#3675]
Running a Azure Function 2.0.12134 with the following _host.json_ config:
```json 
{
  "version": "2.0",
  "extensions": {
    "serviceBus": {
      "prefetchCount": 10,
      "messageHandlerOptions": {
        "maxConcurrentCalls": 1,
        "maxAutoRenewDuration": "00:05:00"
      }
    }
  }
}
```
And the following code:
```csharp
public static class Function
{
    [FunctionName("Function")]
    public static async Task Run([ServiceBusTrigger("myQueue", Connection = "MyBusConnectionString")]Message queueMessage, ILogger logger)
    {
                logger.LogInformation("Fetching queueMessage");
    }
}
```
Only prefetches 1 message, rather than 10 (as specified in the host.json file). This does not seem to be the expected behaviour. However if I change  **maxConcurrentCalls** to 5, i get 5 prefetched messages.
It seems like the **maxConcurrentCalls** overrides the **prefetchCount**

**Comment by koenvanderlinden** [comment]
The underlaying 'servicebusclient' will fetch 10 message (and will lock them). However the function will receive 1 message at the time as you set maxConcurrentCalls to 1.

**Comment by TynThordin** [comment]
@koenvanderlinden makes sense. Thank you!
