### ISSUE TITLE
AF can't load System.IdentityModel.Tokens.Jwt dlls from nuget while running locally

### ISSUE THREAD

**Issue by LukeMagill** [Azure/azure-functions-host#3702]
[TempAF2.zip](https://github.com/Azure/azure-functions-host/files/2517874/TempAF2.zip)

I’m trying to use System.IdentityModel.Tokens.Jwt nuget in a V2 Azure Functions project which doesn’t work. This issue occurs when **running locally**, I have not tried to publish yet.

#### Investigative information

- Timestamp: [10/26/2018 5:40:24 AM]
- Function App version (1.0 or 2.0): 2.0
- Function App name: TempAF2 (Running locally)
- Function name(s) (as appropriate): Function1 (running locally)
- Invocation ID: Id=8fc8f0ab-2173-4d33-9351-cefce1fd1869
- Region: Running on my machine (in East US)

#### Repro steps

1. Create a V2 AF using Visual Studio 2017
1. Add a nuget reference to System.IdentityModel.Tokens.Jwt
1. Add a line of code which uses JWT. I did: `log.Info(JsonConvert.SerializeObject(new TokenValidationParameters()));` 
1. Hit this url in a web browser: http://localhost:7071/api/Function1

#### Expected behavior

Code should be able to use JWT dlls.

#### Actual behavior

Code is not able to use JWT dlls. When you run the code it fails with this error:

```
System.Private.CoreLib: Exception while executing function: Function1. TempAF2: Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=5.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=5.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

#### Known workarounds

No known work arounds

#### Related information 

Provide any related information 

* Programming language used: C#
* Links to source: In zip file
* This bug appears to be related, but does not have sufficient information for me to proceed (and does not appear to be strictly identical): https://github.com/Azure/azure-functions-host/issues/2146

Further investigation: I went to the build output directory and ran the following powershell:

```powershell
Get-ChildItem -Filter *identity*.dll -Recurse |
    ForEach-Object {
        try {
            $_ | Add-Member NoteProperty FileVersion ($_.VersionInfo.FileVersion)
            $_ | Add-Member NoteProperty AssemblyVersion (
                [Reflection.AssemblyName]::GetAssemblyName($_.FullName).Version
            )
        } catch {}
        $_
    } |
    Select-Object Name,FileVersion,AssemblyVersion
```

Which returned this output:

```
Name                                      FileVersion AssemblyVersion
----                                      ----------- ---------------
Microsoft.IdentityModel.JsonWebTokens.dll 5.3.0.51005 5.3.0.0
Microsoft.IdentityModel.Logging.dll       5.3.0.51005 5.3.0.0
Microsoft.IdentityModel.Tokens.dll        5.3.0.51005 5.3.0.0
System.IdentityModel.Tokens.Jwt.dll       5.3.0.51005 5.3.0.0
```

So the file is there and it's being binplaced and it has the right version. AF runtime just can't load it

<details>
<summary>Source</summary>

```csharp
namespace TempAF2
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static IActionResult Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequest req, TraceWriter log)
        {
            log.Info("C# HTTP trigger function processed a request.");

            string name = req.Query["name"];

            string requestBody = new StreamReader(req.Body).ReadToEnd();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name = name ?? data?.name;

            // Simple example line. My full use case is more complex but uses this class
            log.Info(JsonConvert.SerializeObject(new TokenValidationParameters()));

            return name != null
                ? (ActionResult)new OkObjectResult($"Hello, {name}")
                : new BadRequestObjectResult("Please pass a name on the query string or in the request body");
        }
    }
}
```
</details>

**Comment by LukeMagill** [comment]
Appears to be the same as: https://github.com/Azure/azure-functions-core-tools/issues/322

**Comment by maiqbal11** [comment]
Hi Luke,

Going by the zipped code that you've sent, it looks like the binaries are currently being places in the netcoreapp2.0 folder while your .csproj is targeting netstandard2.0: 

```
<PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
</PropertyGroup>
```
I was unable to run your code out of the box as namespaces could not be resolved. However, I was able to go to the project folder and use `dotnet restore` to pull the appropriate packages into the right place. This got the app running. Attaching a zip of my output for comparison:
 
[TempAF2.zip](https://github.com/Azure/azure-functions-host/files/2530292/TempAF2.zip)

**Comment by LukeMagill** [comment]
Hi Maheer,

It looks like you didn't read the instructions carefully (or perhaps I was unclear in my writing). In any case, you have not fixed the problem. You must actually hit the endpoint for the problem to occur.

This is the output when I run your code:
![image](https://user-images.githubusercontent.com/1325512/47745930-1d295380-dc42-11e8-8058-ec3dbbeaf885.png)

**Comment by maiqbal11** [comment]
Hi Luke, 

I was able to successfully hit the endpoint when running locally: 
![successfulexecution](https://user-images.githubusercontent.com/42051041/47746904-5bc00d80-dc44-11e8-97c7-14d7732c3dee.png)

But it looks like this is a different issue from the one I had noted earlier for your case. I noticed that you are using an older version of the runtime (2.0.11353 as compared to 2.0.12134). You can update this by going to Tools -> Extensions and Updates -> Azure Functions and Web Jobs Tools. Reading through the thread that you had linked, some people were experiencing issues because they were running different versions of the tools. This is not a root cause for the issue, but might help mitigate your scenario.

**Comment by LukeMagill** [comment]
This appears to fix the issue, thanks!
