### ISSUE TITLE
Handle extension bundling related configuration

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#3710]
Extension bundling related configuration. 
```JAVASCRIPT
"extensionsBundle" : {
"id": "Microsoft.Azure.Functions.ExtensionBundle"   // Required
"version": "[1.0.0,2.0.0)"                                              // Required
"location" : "C:\\data\\bundle"                                  // Not Required
}
```

**Comment by fabiocav** [comment]
@soninaren this moved a couple of times. Should we put this back in triaged for now?

**Comment by soninaren** [comment]
I think i should be able to finish it before Sprint 40, If not finished before that i would move it to triage.

**Comment by fabiocav** [comment]
Sprint 40 is the current sprint, so I'm assuming you want to move it there, so I'm doing that. Please move it back to triage if not.
