### ISSUE TITLE
Add Language and ScriptType column to System logs

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#3717]
As single language is now enforced at app level, a column indicating the language for a given app in System Logs will make it easier for aggregating analytics per language

Also, need to investigate where  "Unknown" is set to the language Kusto query
```
  WawsAn_omgsitefunctionsentity
| where pdate == datetime(2018-10-26 00:00:00.0000000)
| where Language == "Unknown" or Language == ""
| join
(
WawsAn_omgfunctionappsentity
| where pdate == datetime(2018-10-26 00:00:00.0000000)
| extend Version = substring(HostVersion, 0, 1) 
) on ServiceName , SiteName
| summarize count() by Language, Version

```

**Comment by pragnagopa** [comment]
cc : @maiqbal11 
We also need to track scritpType of a function as multiple scriptTypes can map to a single `FUNCTIONS_WORKER_RUNTIME` for example, `.csx`  and  `.dll` map to worker runtime `dotnet`

**Comment by fabiocav** [comment]
Should this be in sprint 38 as opposed to Triaged?

**Comment by pragnagopa** [comment]
closing this as a dup of #3826
