### ISSUE TITLE
invalid host.json provides no warning/feedback when run on Azure

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-host#3718]
## Environment
* Visual Studio 2017.15.8.8
* Functions extension v15.10.2046
* Functions CLI 2.10.1 (Core tools 2.1.748)
* Functions v2 app

### Repro steps

I had the following host.json defined in my Function app project:
```json
{
  "version": "2.0",
  "http": {
    "routePrefix": ""
  },
  "applicationInsights": {
    "sampling": {
      "isEnabled": false
    }
  },
  "extensions": {
    "durableTask": {
      "HubName": "LeanHttpOrchestrator",
      "extendedSessionsEnabled": true,
      "extendedSessionIdleTimeoutInSeconds": 30,
      "maxConcurrentActivityFunctions": 1000,
      "maxConcurrentOrchestratorFunctions": 500
    }
  }
}
```

**I was able to successfully test my HTTP-triggered function without issue locally with this setup**

However, when I deployed the function to Azure, trying to trigger with the "Get function url" consistently gave me an HTTP 404 for seemingly no reason.

I attached the debugger to the function running in the cloud and it never even got in to my http function.
Live Stream metrics showed no errors spinning up the host.

I knew we'd changed some schema on 2.0 for the host.json - hence why I knew to put `durableTask` inside an `extensions` property - so I decided to take a closer look at the other definitions I had in there. Sure enough, the ones for `http` and `applicationInsights` weren't defined correctly. I fixed the host.json to be:

```json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "sampling": {
        "isEnabled": false
      }
    }
  },
  "extensions": {
    "http": {
      "routePrefix": ""
    },
    "durableTask": {
      "HubName": "LeanHttpOrchestrator",
      "extendedSessionsEnabled": true,
      "extendedSessionIdleTimeoutInSeconds": 30,
      "maxConcurrentActivityFunctions": 1000,
      "maxConcurrentOrchestratorFunctions": 500
    }
  }
}
```

and everything worked correctly in Azure.

### Expectation
1. My local test environment should behave the same as Azure.
1. Azure should tell me when I do something wrong, not give me a non-descript error that leaves me to guess until I come up with a solution.

**Comment by fabiocav** [comment]
@brandonh-msft is this still valid? I'm assuming this is no longer the case and the configuration should be consistent between local and Azure, but please let us know if that isn't the case.

**Comment by brandonh-msft** [comment]
No I believe we still have a problem; I don't believe we should be able to have this experience:
![image](https://user-images.githubusercontent.com/20270743/61395395-32025180-a87a-11e9-8520-1f98f28ccda4.png)

**Comment by fabiocav** [comment]
I just want to make sure this is still consistent with what was originally reported. The key thing with the original issue was the discrepancy between local and hosted experiences, where you were able to run and test your function when running locally, but they were broken when deployed. That's the issue I wanted to make sure was solved.

Today, there's no runtime schema validation for the configuration. Each extension is responsible for its validation section and they don't perform validation of other sections in the config file.

**Comment by brandonh-msft** [comment]
ok i'll deploy this to azure and see what happens. standby!

**Comment by brandonh-msft** [comment]
indeed. getting same behavior between local & azure now. Closing 👍
