### ISSUE TITLE
Guidance for referencing external dll's in PowerShell

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-functions-host#372]
Since PowerShell doesn't have "real" NuGet support, it would be great to have some guidance around how to ref custom dll's (which I guess would have to be manually uploaded)

**Comment by johnnliu** [comment]
http://stackoverflow.com/a/39985646 by @tohling  this remains the best answer I came across, and was able to manually pull apart several powershell modules and put the DLLs together to get what I needed.

**Comment by fabiocav** [comment]
For guidance on using external modules, please see https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-powershell and https://www.github.com/Azure/azure-functions-powershell-worker
