### ISSUE TITLE
Queue Triggered Function not picking up messages from queue

### ISSUE THREAD

**Issue by kapilmehtagit** [Azure/azure-functions-host#3721]
Hi, I have been having issues with a queue triggered function that doesn't seem to be not up the queue messages for several hours, until I logon to the portal and have a poke at the logs, and then suddenly (in a few seconds or sometimes minutes), it springs to life. After this, it is happy to continue processing any new messages.

It is a Visual Studio based C# queue triggered function, which is deployed from Visual Studio to the function app. The queue name is parameterised and picked up from App Settings. I was wondering if it would help to hard code this name in the function trigger definition rather than parameterising it, but it is a difficult one to test and prove as it could take a few days for the issue to resurface.

Always On is On

Function details:
2018-10-31T12:06:08.478 Id=d548e7d7-89ec-4cbd-b5dc-5963e05edf53. UK South

Also, if this is of interest, I have a timer function (again pre-compiled C#) which runs every 3 minutes or so in the same function app to do some processing, which theoretically, keeps the host loaded and warmed up. There is also an http triggered function in the same function app that stays pretty responsive across days.

Happy to help with any troubleshooting.
Thanks for your help.

**Comment by kapilmehtagit** [comment]
Hi, my host.json is quite simple actually. I believe the maxPollingInterval format is as per the new timespan one.

{
  "queues": {
    //The maximum interval between queue polls.
    "maxPollingInterval": "00:00:02",
    // The number of queue messages to retrieve and process in
    // parallel (per job function). The default is 16 and the maximum is 32.
    "batchSize": 1,
    // The number of times to try processing a message before
    // moving it to the poison queue. The default is 5.
    "maxDequeueCount": 3,
    // The visibility timeout that will be applied to messages that fail processing
    // (i.e. the time interval between retries). The default is zero.
    "visibilityTimeout": "00:00:30"
  }
}

**Comment by maiqbal11** [comment]
And the "queues" label lies is under the "extensions" label?

```
"extensions": {
    "queueus": {
        ...
     }
}
```

**Comment by kapilmehtagit** [comment]
Hi, no, that's my entire host.json. Should I move the queues label under the extensions label? Thanks.

**Comment by maiqbal11** [comment]
Yes, you would need a little more. You can check the formatting of the host.json here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#sample-hostjson-file.

**Comment by kapilmehtagit** [comment]
Hi, I have now amended the host.json as below and re-published the update to the function app from Visual Studio. However, this now causes the queue messages to be processed in parallel, and seems to ignore the batchSize setting. This would be an issue as we do require the messages to be executed one by one. Reverting to the original setting resolves this issue. 

`{
    "version": "2.0",
    "extensions": {
      "queues": {
        //The maximum interval between queue polls.
        "maxPollingInterval": "00:00:02",
        // The number of queue messages to retrieve and process in
        // parallel (per job function). The default is 16 and the maximum is 32.
        "batchSize": 1,
        // The number of times to try processing a message before
        // moving it to the poison queue. The default is 5.
        "maxDequeueCount": 3,
        // The visibility timeout that will be applied to messages that fail processing
        // (i.e. the time interval between retries). The default is zero.
        "visibilityTimeout": "00:00:30"
      }
    }
}`

I've also tried adding ` "newBatchThreshold": 0` setting to the above host,json, but this doesn't seem to have any effect. How can I ensure the threads are restricted to just 1?

Thanks,
Kapil

**Comment by kapilmehtagit** [comment]
Hi, I have also tried adding the singleton setting, but still get multiple thread invocations for the function.
`{
  "version": "2.0",
  "extensions": {
    "queues": {
      "maxPollingInterval": "00:00:02",
      "batchSize": 1,
      "maxDequeueCount": 3,
      "visibilityTimeout": "00:00:30",
      "newBatchThreshold": 0
    }
  },
  "singleton": {
    "lockPeriod": "00:00:15",
    "listenerLockPeriod": "00:01:00",
    "listenerLockRecoveryPollingInterval": "00:01:00",
    "lockAcquisitionTimeout": "00:01:00",
    "lockAcquisitionPollingInterval": "00:00:03"
  }
}`

Thanks,
Kapil

**Comment by maiqbal11** [comment]
Could you share the name of your FunctionApp?

**Comment by kapilmehtagit** [comment]
Sure, 

2018-11-09T16:53:22.926 [Info] (Id=39e9dc33-cb7c-4e10-a049-3096f3b9cda7). UK South

I have now replaced the host.json with the original configuration though. Would you like me to re-apply the new one?

**Comment by maiqbal11** [comment]
This is the invocation ID for the function itself. The function is placed in a function app that has just a plain text name attached to it. I wanted to check our logs to see what version of the runtime you have since your issue seems similar to this one: https://github.com/Azure/azure-functions-host/issues/3532#issuecomment-435276412. This would explain why the original configuration is working but not the new one. You can update your runtime by going to Visual Studio -> Tools -> Extensions and Updates -> Updates.

**Comment by kapilmehtagit** [comment]
Hi, the name for the function app is fedfunctions. Thanks,

**Comment by maiqbal11** [comment]
You're running a v1 function. Upgrading to the 2.0 runtime might fix the issue but could also you require you rewrite some of the code since the SDK has changed between the two versions. The host.json [reference](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json-v1#sample-hostjson-file) for v1 is different and seems to be in line with what you had included previously.

**Comment by kapilmehtagit** [comment]
Yes, I have tried to upgrade to 2.0 (.net core) runtime, but have a number of dependencies that are not yet ported to .net core such as OfficeDevPnP.Core, just looks like this is not an option at this stage. I believe the work is in progress to port the assembly, but in the meantime it will need to be the 1.x runtime.

**Comment by maiqbal11** [comment]
The `maxPollingInterval` format for 1.x should actually be an integer rather than `hh:mm:ss`. This is noted here in1.x docs: https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json-v1#queues. Does changing it to integer make a difference?

**Comment by kapilmehtagit** [comment]
Thanks, I have redeployed with the host.json as below. I will test the outcome over the next few days.

`{
  "queues": {
    //The maximum interval between queue polls.
    "maxPollingInterval": 2000,
    // The visibility timeout that will be applied to messages that fail processing
    // (i.e. the time interval between retries). The default is zero.
    "visibilityTimeout": "00:00:30",
    // The number of queue messages to retrieve and process in
    // parallel (per job function). The default is 16 and the maximum is 32.
    "batchSize": 1,
    // The number of times to try processing a message before
    // moving it to the poison queue. The default is 5.
    "maxDequeueCount": 3

  }
}`

**Comment by yojagad** [comment]
Closing the issue due to lack of activity. If you have any more issues, please let us know.
