### ISSUE TITLE
The Functions v2 Runtime does not log Functions Triggers information to AntaresFunctionSdkEvents

### ISSUE THREAD

**Issue by cts-shrahman** [Azure/azure-functions-host#3725]
The Functions v2 Runtime does not log Functions Triggers information to AntaresFunctionSdkEvents which prevents additional detector work. 
a.	E.G for v1 this works https://applens.azurewebsites.net/subscriptions/65b55da0-6b91-4547-bb21-3f48978ec56f/resourceGroups/syneron_general_function_app_resource_group/providers/Microsoft.Web/sites/SyneronGeneral/detectors/functiontype?startTime=2018-10-29T23:10&endTime=2018-10-30T23:10 
b.	Try the same thing for a v2 app and nothing is returned.

**Comment by FinVamp1** [comment]
Closing this as we have Detectors that help on this and this will not be reverted to the v1 logic.
