### ISSUE TITLE
Proxy requests timeout if backend is taking more than 60 seconds

### ISSUE THREAD

**Issue by safihamid** [Azure/azure-functions-host#3730]
This can be repro'd with V2 functions and all default settings.

**Comment by safihamid** [comment]
It should use the same value as defined in here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#functiontimeout

Currently the timeout is hard coded to 60 seconds.

**Comment by fabiocav** [comment]
Do we want to have an explicit setting for this? I think it would be helpful to be able to set the proxy timeout to something shorter than the function execution timeout. Thoughts?

**Comment by safihamid** [comment]
I think we should  just remove the 60 seconds timeout for proxies which was left behind. proxy execution is a function execution at the end of the day. and I rather not add yet another config knob at this point.

**Comment by vfedonkin** [comment]
That was the plan, to remove the proxy timeout. Talking about timeouts, did you ever have issues with load balancer 4 minutes timeout? https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-idle-timeout .

**Comment by fabiocav** [comment]
@safihamid this might end up becoming a requirement, but I'm fine with that  for now.

**Comment by mikesitch** [comment]
Hi,
When will this be available to test? Thanks

**Comment by safihamid** [comment]
@mikesitch it should be available within the next week or so. the runtime version of 2.0.12175 or higher will have the fix, thanks!

**Comment by mikesitch** [comment]
@safihamid Functions runtime has updated to version 2.0.12175 but I'm still getting the same issue? 

I've tried a few times today, e.g. "traceId": "49ce056be46c4d1082c8c85f7222291a", 

      {
        "source": "forward-request",
        "timestamp": "2018-11-14T16:37:08.3656680Z",
        "elapsed": "00:01:00.1376180",
        "data": {
          "messages": [
            "Error occured while calling backend service.",
            "The operation has timed out.",
            "The operation has timed out."
          ]
        }
      }

region is west europe

Thanks

**Comment by safihamid** [comment]
@mikesitch hmm it should have the fix. did you make PUT request to a url which ends with /NOT+FOUND? if yes, how long does it usually take to complete?

**Comment by fabiocav** [comment]
This fix has not been released yet (it wasn't part of the last release payload). The release containing this fix should start this week. We'll have an announcement [here](https://github.com/Azure/app-service-announcements/issues) and will have the details in the release notes [here](https://github.com/Azure/azure-functions-host/releases)

**Comment by mikesitch** [comment]
OK thanks.
