### ISSUE TITLE
MetadataGenerator fails to discover internal IWebJobsStartup types during build on netcoreapp2 project

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#3731]
Create a new Function App project, which should default to netcoreapp2 with the latest bits. 
Create a class and wire up an `IWebJobsStartup` class and build.

```
using FunctionApp35;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Hosting;

[assembly: WebJobsStartup(typeof(MyStartup))]

namespace FunctionApp35
{
    public class MyStartup : IWebJobsStartup
    {
        public void Configure(IWebJobsBuilder builder)
        {
        }
    }
}
```

It should be generating an extensions.json file in the build output, that contains the class -- but it's stopped working. This does work if the project is netstandard2.

**Comment by jeromekol** [comment]
We got the same issue

**Comment by vludax** [comment]
Is using netstandard2.0 and pinning the version to 2.0.12246 the best workaround for now?

**Comment by brettsam** [comment]
Can you try using netcoreapp2.0 as your platform (with no pinning)? And a fix is coming soon...

**Comment by brettsam** [comment]
This version of the package is now released: https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator/1.0.2.

If you add 1.0.2 as a nuget reference, your extensions.json should be generated now, no matter which framework you are targeting.

**Comment by jmezach** [comment]
I just switched my project back from targetting netstandard2.0 to netcoreapp2.2, but even without this new package installed it seems to be working fine. So I'm a little confused as to whether I need to install this package or not.

**Comment by brettsam** [comment]
I've not seen that workaround before, so I can't speak to that. But you shouldn't need to do anything special anymore with this new package. I'm not sure why it would be working without it, as it was pretty broken when targeting anything other than a 2.0 framework. Have you tried a full clean and build?

But, in general, if it works, that's good :-)

We'll be moving the Microsoft.NET.Sdk.Functions package to depend on this new ExtensionsMetadataGenerator version soon, so you'll get the new package anyway if you ever move that package forward.

**Comment by jmezach** [comment]
Interesting, because what I'm seeing is that it doesn't work, unless apply the workaround I mentioned. I see the extensions.json being generated when doing dotnet build (either Debug or Release), but when doing dotnet publish the output folder does not contain the extensions.json?

**Comment by brettsam** [comment]
And this happens both with and without ExtensionsMetadataGenerator 1.0.2 being referenced?

**Comment by jmezach** [comment]
Sorry, should have mentioned that. Yes, it seems to do that both with or without.

**Comment by brettsam** [comment]
@jmezach -- would you possible be able to try the solution here? https://github.com/Azure/azure-functions-host/pull/4059. I'm trying to determine if this is going to fix a whole bunch of problems of if we've got more lurking behind this.

**Comment by jmezach** [comment]
Okay, so what I said before wasn't entirely correct. The extensions.json is being generated, but in the out/bin folder when doing dotnet publish -c Release -o out (it was just being hidden by VS Code). Unfortunately the generated file isn't complete. For example, it does list the Durable Functions extension, but it doesn't list my own Startup class. So I tried adding this to my Functions project file:

```xml
<PropertyGroup>
  <_IsFunctionsSdkBuild>true</_IsFunctionsSdkBuild>
</PropertyGroup>
```

But that doesn't seem to fix the issue. Only applying the Directory.Build.targets file workaround I described earlier seems to fix the issue for me.

Also, it might be worth mentioning that I'm doing this on a Mac with the latest azure-functions-core-tools installed.

**Comment by brettsam** [comment]
Thanks @jmezach. This sounds like a separate issue (mostly since it also happens with 1.0.1). I've opened https://github.com/Azure/azure-functions-host/issues/4133 to track. I'll work with you over there to try to get a repro and fix going. Thanks!
