### ISSUE TITLE
Host.json seems invalid for v2?

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-host#3733]
Looks like it's been updated because I see extensions has moved, but I still see things like `logger` which I believe were changed in v2 to `logging` and things like `applicationInsights` should be children of `logger`.  I'm fine if this is assigned to me but not sure if auto generated or was manually created.  

Not sure what the schema URL VS Code and VS are pointing to but also makes the autocomplete broken in those tools.

**Comment by fabiocav** [comment]
Our schema needs to be updated. Leaving this open to track the work

**Comment by brettsam** [comment]
FYI - the schema is now live: http://json.schemastore.org/host.

Create a new issue if we see any problems with the schema and I can see what I need to tweak.
