### ISSUE TITLE
DryIoc.ContainerException : Container is disposed and should not be used: Container is disposed.

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#3744]
Likely a very similar issue to #3743, but creating a separate issue for discoverability. It looks like in-flight HttpRequests can access a disposed container. This seems to happen while the job host is in the process of restarting.

**Comment by brettsam** [comment]
@fabiocav as FYI. Found this a while ago and we've seen a couple customers hit it.

**Comment by jeffhollan** [comment]
P2 but we should flag if this pops up from supportability

**Comment by brettsam** [comment]
We've determined that this is a generic error that ecompasses a number of individual scenarios. If you're seeing this, please open a separate issue and we can investigate each one independently.
