### ISSUE TITLE
Breaking change between SDK and Runtime

### ISSUE THREAD

**Issue by rasmustherkelsen** [Azure/azure-functions-host#3761]
With the latest deployment of the functions runtime (V2), my code now breaks.

Scenario:
I have some scheduled jobs (TimerTrigger) and a HttpTrigger function that for convenience can kick off the scheduled jobs if I want them to. The HttpTrigger functions instantiates an instance of the TimerSchedule and passes this to the Run method of my scheduled job. The instance is my own class inherited from TimerSchedule as it is a public abstract class.

Using the latest web jobs SDK (Microsoft.Azure.WebJobs.Extensions 3.0.0.0) I only have to override a single method: GetNextOccurence). This has worked fine until now.

With the latest release, 2.0.12165.0, I now get a runtime error stating 

> Function (XXX) Error: Unable to load one or more of the requested types.
 Method 'get_AdjustForDST' in type ‘XXX.XXXFunctions.Extensions.TimerScheduleInvoker' from assembly ‘XXX.XXXFunctions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

If I look at the source code for the SDK in GitHub here: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/9feb4f2ad6f70e443a036a135b58121c70dbdaf3/src/WebJobs.Extensions/Extensions/Timers/Scheduling/TimerSchedule.cs I can see that the TimerSchedule class has indeed been extended with property AdjustForDST.

This leaves me with the impression that you have compiled your runtime using the code directly and not shipped a new SDK thus introducing a breaking change. Please advice. For now I have to change my code, but it has caused my functions to completely stop working.

Best regards,
Rasmus

**Comment by dallancarr** [comment]
It looks that work is still in beta.

**Comment by rasmustherkelsen** [comment]
@dallancarr Ok but I find it strange to ship a runtime that breaks compatibility with existing code that uses the only available SDK without warning. I am talking real production code here using a GA Azure Service.

**Comment by fabiocav** [comment]
@rasmustherkelsen, you're absolutely right. This was a breaking change that really shouldn't have shipped the way it did (even if the SDK was shipped at the same time, as it would have still impacted you and forced you to update). We're in the process of releasing the SDK so you can address this issue but referencing the latest bits. We're also looking at better checks in place to ensure this doesn't happen again. Apologies for the issue!

**Comment by fabiocav** [comment]
We also just pushed the packages. Again, apologies for this issue. We're very careful with those kinds of changes and this one slipped by us. As I mentioned, we're looking into better checks to catch these kinds of problems in the future.
