### ISSUE TITLE
Do not append defaultWorkerPath in DefaultWorkerProcessFactory 

### ISSUE THREAD

**Issue by maiqbal11** [Azure/azure-functions-host#3763]
Currently `worker.config.json` does not support passing arguments to the worker. Arguments can be passed to the language executable (e.g. `python`, `node` or `java`) using the `arguments` but there is no equivalent for passing argument to the worker entry point.

**Comment by fabiocav** [comment]
@pragnagopa did you have a chance to review/triage this?

**Comment by pragnagopa** [comment]
Following needs to be updated to not append defaultWorkerPath but replace the value
https://github.com/Azure/azure-functions-host/blob/4f6c0e9090b8ca0609e2fe7ffcb688127f0c3a9e/src/WebJobs.Script/Rpc/ProcessManagement/DefaultWorkerProcessFactory.cs#L35

This will give the ability to customize ordering for arguments passed to language worker process

Sample upsates to node worker.config.json
```
{
    "description":{
        "language":"node",
        "extensions":[".js"],
        "defaultExecutablePath":"node",
        "defaultWorkerPath":"dist/src/nodejsWorker.js"
	"arguments": ["{defaultWorkerPath} "]
    }
}
```
NOTE: this needs to be backward compatible i.e if arguments does not include defaultWorkerPath, then append it

**Comment by pragnagopa** [comment]
This is addressed in commit #https://github.com/Azure/azure-functions-host/commit/b79be7496308bb789a3e6cad9c57f6d0e813a2e4#diff-654541726e0b624e96edd60b6d7ab23e , `WorkerDescription` now has a list `WorkerArguments` that can be used specifically for worker args
