### ISSUE TITLE
Transfer-Encoding chunked appears to be the default since build 2.0.12161

### ISSUE THREAD

**Issue by joeljeffery** [Azure/azure-functions-host#3765]
#### Investigative information

- Timestamp: 2018-11-12 17:55 GMT
- Function App version (1.0 or 2.0): 2.0.12161, 2.0.12165
- Region: UK South

#### Repro steps

Steps required to reproduce the problem:

Create an HTTP triggered function.
Invoke via Postman, ARC, PowerShell Invoke-RestMethod, custom code, anything.
Review the response headers and body content.

#### Expected behavior

Prior to release 2.0.12161, content was encoded with identity, and content-length is set accordingly.

#### Actual behavior

Transfer-Encoding is set to chunked, no content-length header is returned.
Attempts to set Transfer-Encoding in a request header fails with error 501.

#### Known workarounds

Pinning version to 2.0.12134 makes the old behaviour return (transfer-encoding: identity, content-length correctly set).

#### Related information 

* Programming language used 

Reproduced in C# (in-portal) and .NET Core 2.1 (VS.NET).

```csharp
#r "Newtonsoft.Json"

using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Newtonsoft.Json;

public static async Task<IActionResult> Run(HttpRequest req, ILogger log)
{
    log.LogInformation("C# HTTP trigger function processed a request.");

    string name = req.Query["name"];

    string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
    dynamic data = JsonConvert.DeserializeObject(requestBody);
    name = name ?? data?.name;

    return name != null
        ? (ActionResult)new OkObjectResult($"Hello, {name}")
        : new BadRequestObjectResult("Please pass a name on the query string or in the request body");
}

```

**Comment by fabiocav** [comment]
@alrod can you verify if this is caused by an ANCM change?
