### ISSUE TITLE
Key Vault secret repository

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-host#3766]

**Comment by fabiocav** [comment]
Moving to sprint 40. 

@mattchenderson do you have any feedback from the testing you've done?

**Comment by fabiocav** [comment]
@mattchenderson is working on validation, so we're blocked until that is complete. Moving to next sprint.

**Comment by fabiocav** [comment]
@mattchenderson , marking this as blocked, pending validation. Moved to sprint 42, but please let us know if it should be moved to another sprint

**Comment by fabiocav** [comment]
Moving this to Triaged until unlblocked

**Comment by alrod** [comment]
https://github.com/Azure/azure-functions-host/commit/2b8c2b851e2a415d70b40e7d47bc415a0a82475a
