### ISSUE TITLE
Unable to Retrieve the Azure function keys for functions created in version 2.0

### ISSUE THREAD

**Issue by ashokkhurana** [Azure/azure-functions-host#3767]
Scenario: We have an Ibiza blade (Iot hUB) )where we are showing a list of all the azure functions in a selected subscription. When selecting the azure function, we are fetching the azure function key. Here is the URI we are using to fetch the key https://myfunctionAppName.scm.azurewebsites.net/api/functions/admin/masterkey

This worked perfectly with the Azure function runtime version 1.0. 

But recently with the runtime version 2.0 we started getting 409 error.

_{"Message":"An error has occurred.","ExceptionMessage":"Runtime keys are stored on blob storage. This API doesn't support this configuration. Please change Environment variable AzureWebJobsSecretStorageType value to 'Files'. For more info, visit https://aka.ms/funcsecrets","ExceptionType":"System.InvalidOperationException","StackTrace":"   at Kudu.Core.Functions.FunctionManager.<GetKeyObjectFromFile>d__9`1.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Functions\\FunctionManager.cs:line 141\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Core.Functions.FunctionManager.<GetMasterKeyAsync>d__11.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Functions\\FunctionManager.cs:line 213\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Services.Functions.FunctionController.<GetMasterKey>d__11.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Services\\Functions\\FunctionController.cs:line 121"}_

I came across this document https://github.com/Azure/azure-functions-host/wiki/Key-management-API but realize that these API requires some auth token, may be because with 2.0 we are moved to a blob storage for keys.

 After more finding I found there is a KUDU API to generate the auth token before retrieving the keys. So now I am making following calls
1. Kudu Auth: -https://myfunctionAppName.scm.azurewebsites.net/api/functions/admin/token
2. Get KEY:- https://myfunctionAppName.azurewebsites.net/admin/functions/myfunctionName/keys

Kudu API calls work fine and I GET the token. But when passing the token to second API, I am seeing **following** error.

**Security issue: Request to send auth token to untrusted domain 'askhura-custom-allocation-app.scm.azurewebsites.net'. Only a fixed set of domains should be configured to receive auth tokens.**

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0): 2.0
- Function App name: askhura-custom-allocation-app
- Function name(s) (as appropriate): HttpTrigger1
- Invocation ID:
- Region:

#### Repro steps

Provide the steps required to reproduce the problem:

Getting the error pasted above from my Ibiza blade.
Tried to do the same steps in a C# console app. The error I got an unhandled exception that the connection was forcibly closed by the remote host. So didn't get the exact error.

**Note: I am able to run the above two APIs without any issue in a POSTMAN.**
#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used - C#
* Links to source - I am trying to replicate the steps from this blog post https://markheath.net/post/managing-azure-function-keys
* Bindings used

**Comment by fabiocav** [comment]
Closing this as there was a direct follow up.

**Comment by matt2323** [comment]
https://xkcd.com/979/

**Comment by danielstocker** [comment]
@fabiocav @paulbatum 

Could you share the recommended workaround that was shared offline here, please?

**Comment by ashokkhurana** [comment]
Pasting below the response I got from Paul Batum.

Here is a copy of the workaround instructions we shared with logic apps. The gist is that we introduced new APIs in functions V2, and we recommended that logic apps attempt to use those APIs first (that’s what is detailed below), as those are the ones that work with blob based key storage. If they get errors that likely indicates they are dealing with a V1 app, in which case they would fall back to their existing logic. The same approach is likely applicable for your scenario.

We are still working on a revised set of APIs. Our intention is for the revised APIs to have better reliability (the APIs that are listed below rely on making a call to the customer's function app, and so they can get failures if the function app is in a bad state due to customer error).


Proposed updates to Logic Apps
 
So, to work with V2, Logic Apps could make the following API calls (use https://resources.azure.com/raw for the queries below):
 
List Functions:
They can change the behavior to call this API first, if they get a 400 or 404 or 405, that means they’re talking to a V1 app and can fallback to the current behavior (using the Kudu API):
## List functions
GET https://management.azure.com/subscriptions/ef90e930-9d7f-4a60-8a99-748e0eea69de/resourceGroups/functions-facaval-westus2/providers/Microsoft.Web/sites/functiondev-facaval-westus2/hostruntime/admin/functions?api-version=2016-08-01
 

Retrieve keys:
 
They could also use these APIs by default, in V1, this would return a 401, as the APIs exist there, but the runtime doesn’t know how to authenticate an ARM token (we could add that there, not sure if we ever would).
 
Note from Paul: try these APIs first, and if they fail with 401, fallback to existing behavior
 
## Get host master key
GET https://management.azure.com/subscriptions/ef90e930-9d7f-4a60-8a99-748e0eea69de/resourceGroups/functions-facaval-westus2/providers/Microsoft.Web/sites/functiondev-facaval-westus2/hostruntime/admin/host/systemkeys/_master?api-version=2016-08-01
 
Template: https://management.azure.com/subscriptions/<SUBID>/resourceGroups/<rg_name>/providers/Microsoft.Web/sites/<function_app>/hostruntime/admin/host/systemkeys/_master?api-version=2016-08-01
 
## Get host keys
GET https://management.azure.com/subscriptions/ef90e930-9d7f-4a60-8a99-748e0eea69de/resourceGroups/functions-facaval-westus2/providers/Microsoft.Web/sites/functiondev-facaval-westus2/hostruntime/admin/host/keys?api-version=2016-08-01
 
Template: https://management.azure.com/subscriptions/<SUBID>/resourceGroups/<rg_name>/providers/Microsoft.Web/sites/<function_app>/hostruntime/admin/host/keys?api-version=2016-08-01
 
## Get function keys
GET https://management.azure.com/subscriptions/ef90e930-9d7f-4a60-8a99-748e0eea69de/resourceGroups/functions-facaval-westus2/providers/Microsoft.Web/sites/functiondev-facaval-westus2/hostruntime/admin/functions/DeviceInvokeIssue/keys?api-version=2016-08-01
 
Template: https://management.azure.com/subscriptions/<SUBID>/resourceGroups/<rg_name>/providers/Microsoft.Web/sites/<function_app>/hostruntime/admin/functions/<function_name>/keys?api-version=2016-08-01

**Comment by paulbatum** [comment]
@ashokkhurana I have deleted your comment, it included references to private APIs.

**Comment by paulbatum** [comment]
Anyone on this issue that recieved those details - please don't use those APIs unless you're on another Microsoft team and are in touch with me. Otherwise you might find that they randomly start breaking at some point in the future.

**Comment by paulbatum** [comment]
I should add, the original issue filed here is about some details around the implementation of some Azure portal UX. Some of the other replies on this issue are "me too" replies, but I assume the scenario is different. If you can reply here and explain your actual scenario, I can try to help.

**Comment by Gayathri92** [comment]
Hello Paul,

I'm trying to link azure alerts to my azure function App. When I click on
save, Throws me this error:

[image: Screen Shot 2019-02-05 at 1.38.18 PM.png]

Regards!
Gayathri Muralidharan.
Never. Stop. Learning.

**Comment by paulbatum** [comment]
@Gayathri92 your image did not make it. Can you reshare? Also I am not familiar with the process of linking azure alerts to a function app, so if you can include some more detail it might help.

**Comment by Gayathri92** [comment]
Hello Paul,

Steps to reproduce:
1) Click on Monitoring
[image: Screen Shot 2019-02-05 at 2.35.53 PM.png]
2) Click on Alerts
3) Click on "Create New Alert"
4) In the action Group, you can link your azure function( To perform some
computation when the alert is raised). That's when I get the issue.
[image: Screen Shot 2019-02-05 at 2.36.14 PM.png]

[image: Screen Shot 2019-02-05 at 1.38.18 PM.png]

Regards!
Gayathri Muralidharan.
Never. Stop. Learning.

**Comment by SamVanhoutte** [comment]
I am facing a similar issue, when referencing a deployed function (v2) and reading the API key from the listkeys function in my arm template deployment.  It used to work when my function was in v1.

This is the piece of arm template:
`[listsecrets(resourceId('Microsoft.Web/sites/functions', variables('site_name'), variables('function_trigger_name')),'2015-08-01').key]`

The error I get is the following:

```
"error": {
    "code": "Conflict",
    "message": "System.InvalidOperationException: Runtime keys are stored on blob storage. This API doesn't support this configuration. Please change Environment variable AzureWebJobsSecretStorageType value to 'Files'. For more info, vi
sit https://aka.ms/funcsecrets\r\n   at Kudu.Core.Functions.FunctionManager.<GetKeyObjectFromFile>d__9`1.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Functions\\FunctionManager.cs:line 141\r\n--- End of stack trace fro
m previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task
)\r\n   at Kudu.Core.Functions.FunctionManager.<GetFunctionSecretsAsync>d__12.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Functions\\FunctionManager.cs:line 220\r\n--- End of stack trace from previous location where e
xception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Services.Fu
nctions.FunctionController.<GetSecrets>d__12.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Services\\Functions\\FunctionController.cs:line 141"
}
```

**Comment by paulbatum** [comment]
If you follow the link in the error message, most of it is explained there:
https://aka.ms/funcsecrets

Until we release ARM API updates, the best workaround is to switch the key storage back to files mode. Be aware that if you do this all your keys will be reset and you won't be able to use the slots feature set (the incompatibility between file based key storage and slots is the main reason that we changed the default).

**Comment by M0ns1gn0r** [comment]
@paulbatum So when will it be implemented in ARM API?
