### ISSUE TITLE
Azure Functions queue scaling

### ISSUE THREAD

**Issue by laukotomi** [Azure/azure-functions-host#3772]
We have an image processing logic which we would like to use in an Azure Function. The function itself can process one request in 30 seconds, and can process only 3 in parallel, because after that we exceed the 5 minute timeout. So we set the batchSize to 3 and newBatchThreshold to 0 of the queue trigger in host.json. The problem is that Azure stops scaling after starting 6 server instances or doesn't even scale up if batchSize is less than 3. But CPU usage is always between 70 and 100% (but usually 90+) and memory usage is between 600MB and 1GB and there are many requests in the queue. We are using consumption plan (so we don't know anything about the scaling logic)

#### Investigative information

- Timestamp: 2018-11-13 00:30:00.003
- Function App version (1.0 or 2.0): 2.0
- Region: West Europe

#### Repro steps

After putting many requests into the queue only one Function instance will work on them or at most 6.

#### Expected behavior

Azure scales up the Function because there are many requests in the queue and workers can't process them fast enough.

#### Actual behavior

Scaling stops at 6 server instances or doesn't even happen when batchSize is less than 3.

#### Related information 

* Programming language used: C#
* Bindings used: QueueTrigger

**Comment by fabiocav** [comment]
@mathewc for investigation

**Comment by laukotomi** [comment]
It turned out that scaling is based on memory usage and not the cpu usage.
