### ISSUE TITLE
HEAD requests via Azure Function Proxy return Content-Length Zero

### ISSUE THREAD

**Issue by sdhamilton6** [Azure/azure-functions-host#3774]
#### Investigative information

- Timestamp: 2018-11-14T11:22:28.168z
- Function App version: 2.0.12175.0
- Invocation ID: a4f233c3-18ef-4d97-a59d-4d3e6b728df9 5e324137-e6ba-4ecd-8288-0b79980edd60
- Region: West Europe

#### Repro steps

With a Proxy supporting HEAD and GET with a backend URL;

1. Request GET and note Content-Length.
2. Request HEAD and not zero Content-Length.

#### Expected behavior

http HEAD request via an Azure Function Proxy would return the Content-Length header of the backend URL.

#### Actual behavior

http HEAD request Content-Length header always returns with a value of zero.

#### Known workarounds

1. Use an Azure Function on the same route to handle HEAD requests, which mimics the proxy.
or
2. Set a response override, reading the backend header and set a custom header for the Content-Length.

**Comment by fabiocav** [comment]
@safihamid @vfedonkin can you take an initial look at this?

**Comment by vfedonkin** [comment]
I think it's proxy who sets it to 0. Will investigate and fix it.
