### ISSUE TITLE
Azure Functions Proxies running locally giving 500s all the time - works in the Cloud

### ISSUE THREAD

**Issue by ChristianWeyer** [Azure/azure-functions-host#3793]
My setup:

- macOS 10.13.6
- VS Code Version 1.28.2
- Azure Functions Core Tools (2.2.70 Commit hash: 1f1f77a71c5517b00401aa0ebf00a4f16857a94c)
- Function Runtime Version: 2.0.12175.0 

I have a `proxies.json` file like this:
```
{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "api": {
        "matchCondition": {
            "route": "/api/{*restOfPath}"
        },
       "backendUri": "https://%WEBSITE_HOSTNAME%/api/{restOfPath}"
    },
    "spa": {
        "matchCondition": {
            "route": "/{*restOfPath}"
        },
       "backendUri": "https://foobarbaz.z6.web.core.windows.net/{restOfPath}"
     }
  }
}
```
Calling the SPA at / works fine  - locally and in Azure.

However, trying to run the function app locally and calling any of the APIs like `/api/status/ping`, I get a 500:
```
[18/11/2018 21:46:13] Executing HTTP request: {
[18/11/2018 21:46:13]   "requestId": "f8a75cd0-83f1-4d88-9fab-241c4f6d7246",
[18/11/2018 21:46:13]   "method": "GET",
[18/11/2018 21:46:13]   "uri": "/api/status/ping"
[18/11/2018 21:46:13] }
[18/11/2018 21:46:13] Executing 'Functions.api' (Reason='This function was programmatically called via the host APIs.', Id=e455576b-9c35-499a-957e-32cde098744c)
[18/11/2018 21:46:13] Executing request via Azure Function Proxies
[18/11/2018 21:46:13] Executed 'Functions.api' (Succeeded, Id=e455576b-9c35-499a-957e-32cde098744c)
[18/11/2018 21:46:13] Executed HTTP request: {
[18/11/2018 21:46:13]   "requestId": "f8a75cd0-83f1-4d88-9fab-241c4f6d7246",
[18/11/2018 21:46:13]   "method": "GET",
[18/11/2018 21:46:13]   "uri": "/api/status/ping",
[18/11/2018 21:46:13]   "identities": [],
[18/11/2018 21:46:13]   "status": 500,
[18/11/2018 21:46:13]   "duration": 307
[18/11/2018 21:46:13] }
```

No more logs than this.

When running it to Azure, everything is fine there - for all the API paths.

I cannot see any workaround for getting it to work locally.
@safihamid 

Thanks!

**Comment by safihamid** [comment]
Do you have the WEBSITE_HOSTNAME app setting defined locally?

**Comment by ChristianWeyer** [comment]
I do not have it in my local.settings.json.
When I add it, this error shows up:
```
Azure Functions Core Tools (2.2.70 Commit hash: 1f1f77a71c5517b00401aa0ebf00a4f16857a94c)
Function Runtime Version: 2.0.12175.0
An item with the same key has already been added. Key: WEBSITE_HOSTNAME
The terminal process terminated with exit code: 1
```

Thanks.

**Comment by ChristianWeyer** [comment]
Small update - just added a `Startup.cs` class:
```
[assembly: WebJobsStartup(typeof(Startup))]

namespace Serverless
{
    public class Startup : IWebJobsStartup
    {
        public void Configure(IWebJobsBuilder builder)
        {
            Console.WriteLine("*** STARTUP...");
            Console.WriteLine("*** WEBSITE_HOSTNAME: {0}", 
                Environment.GetEnvironmentVariable("WEBSITE_HOSTNAME"));
        }
    }
}

```
When running locally the output looks like this:
```
*** STARTUP...
*** WEBSITE_HOSTNAME: 0.0.0.0:7071
```

**Comment by ChristianWeyer** [comment]
This worked - thanks!

Did I miss anything obvious in the official docs wrt to this?

**Comment by safihamid** [comment]
So was this working fine for you in V1? What’s the value of that app setting for you in V1? Was it just 127.0.0.1? Also which doc were you looking at? We will probably need to update something here if it’s confusing...

**Comment by safihamid** [comment]
@vfedonkin we will need to update proxy code where we determine if it’s local call or not.
And ideally update one of the CI tests to have this app setting rather than localhost.

**Comment by ChristianWeyer** [comment]
Hm - I think this worked in V1. Sorry, I do not have a v1 function app to test right now.

The docs I was reading are here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-proxies

... and yes: WEBSITE_HOSTNAME is not mentioned there.
Seems like my sample code and all the Google-able samples are wrong ;-)

Thanks a ton for your help.

**Comment by ChristianWeyer** [comment]
Interestingly, if I use the proxies on a node.js application I get this:

`Infinite loop detected when trying to call a local function or proxy from a proxy.`

This is the proxies config:
```
{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
        "letsencryptapi": {
            "matchCondition": {
                "route": "/.well-known/acme-challenge/{code}"
            },
            "backendUri": "https://localhost/api/letsencrypt/.well-known/acme-challenge/{code}"
        },
        "api": {
            "matchCondition": {
                "route": "/api/{*restOfPath}"
            },
            "backendUri": "https://localhost/api/{restOfPath}"
        }
    }
}
```

Above error happens when e.g. calling
`http://localhost:7071/.well-known/acme-challenge/AH4hh8_whatever`

**Comment by fabiocav** [comment]
@safihamid are there follow up actions on this item?

**Comment by safihamid** [comment]
@fabiocav I looked at the code again. we check for localhost or the site host must match %WEBSITE_HOSTNAME% env variable to call a local function. This is the same as in docs as well. nothing needs to be done here.
