### ISSUE TITLE
Log files in dedicated linux are not written under /home/LogFiles/

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#3796]
With this change 35cf323fa3464a08b410a518bcab006e801301fe the log path for the file logging changed from `/home/LogFiles/Application/Functions/....` to `FUNCTIONS_LOGS_MOUNT_PATH` which is somewhere under `/var` and isn't accessible from Kudu container. 

The UI relies on Kudu for log streaming for dedicated linux scenarios and that goes directly after the `/home/LogFiles/Application/Functions/Function/{functionName}`

/cc @balag0

**Comment by fabiocav** [comment]
@balag0 wasn't this fixed in a recent PR?

**Comment by ahmelsayed** [comment]
yes it was fixed in https://github.com/Azure/azure-functions-host/pull/3799
