### ISSUE TITLE
Failed to create Linux Consumption function app in region "West US"

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Azure/azure-functions-host#3800]
I used to be able to create a Linux Consumption function app using VS Code, but sometime in the past few days it changed. Now I get an error even with location "West US". It also reproduces in the portal:

#### Repro steps

1. Follow this link to the portal: http://aka.ms/functions-consumptionlinux-portal
1. Create new Function App with the following settings:
<img width="261" alt="screen shot 2018-11-20 at 8 25 59 am" src="https://user-images.githubusercontent.com/11282622/48779751-ef15bd00-ec9d-11e8-8aff-cf99e086ffef.png">

#### Error details

operationId: "472E9A00E1F0746F",
provisioningOperation: "Create",
provisioningState: "Failed",
timestamp: "2018-11-20T14:10:17.2658894Z",
trackingId: "3e534d3d-35ab-4df1-af6e-56ffa6b05375",
statusCode: "BadRequest",
Message: "Requested features are not supported in region."

@balag0 @ahmelsayed the flag mentioned [here](https://github.com/Microsoft/vscode-azurefunctions/issues/641#issuecomment-429401251) also started working recently (the list of locations is filtered down to just 4). Maybe something else changed at the same time that was deployed?

**Comment by ahmelsayed** [comment]
This should be fixed now.
