### ISSUE TITLE
Increase default sampling limits

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-host#3806]
We have discussed this before but given the number of CRIs we get where people are missing traces from app insights sampling we should look at increasing the default minimum.  I believe right now it's 5 logs a second?  I think even 50 logs a second is ok for a minimum.  Anyway not sure on number does result in a  of some noisy support tickets.

/cc @paulbatum @brettsam

**Comment by paulbatum** [comment]
My suggestion is that we up this to 20 per second. This is already a potential 4x increase in the default amount of data we send.
