### ISSUE TITLE
Warning about async void functions does not have function name in logs

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#3812]
Found some log entries in our system logs that have a message that looks like this:
`Function 'RunAsync' is async but does not return a Task. Your function may not run correctly.`

There are two problems:
1. RunAsync is the method name, not the function name. So the log message needs to include the actual function name.
2. The FunctionName column is not populated.

We need this information to be able to display relevant dynamic help when customers start the support ticket flow.

**Comment by mathewc** [comment]
Yes - we need to use the [Utility.GetFunctionName](https://github.com/Azure/azure-webjobs-sdk/blob/0dd21b28ae749cc5000339b1d24a4955d39f0395/src/Microsoft.Azure.WebJobs.Host/Utility.cs#L32) helper in the core SDK [here](https://github.com/Azure/azure-webjobs-sdk/blob/0dd21b28ae749cc5000339b1d24a4955d39f0395/src/Microsoft.Azure.WebJobs.Host/Indexers/FunctionIndexer.cs#L313), which takes the FunctionNameAttribute into account. We should check for other instances of this as well (places where we're using MethodInfo.Name) and fix them.

**Comment by pougetat** [comment]
Hey,
I opened a PR for this : https://github.com/Azure/azure-webjobs-sdk/pull/2051
:)

**Comment by soninaren** [comment]
Added a new PR with fixes to the unit tests
https://github.com/Azure/azure-webjobs-sdk/pull/2054

**Comment by soninaren** [comment]
@pougetat thanks for sending this one, Azure/azure-webjobs-sdk#2051. Not sure why the build for your PR was not running properly.
