### ISSUE TITLE
Replace connection string with MSI (AAD)

### ISSUE THREAD

**Issue by MaartenArits** [Azure/azure-functions-host#3820]
#### Investigative information

Please provide the following:

- Timestamp: 27-11-2018
- Function App version (1.0 or 2.0): 2.0
- Function App name: /
- Function name(s) (as appropriate): /
- Invocation ID: / 
- Region: EU-west

#### Related information 

I'm new to this and I don't feel this is the correct place for a feature request. Nevertheless, I already figured out it is not possible to use vault for the connection string because you cannot set the environment variable before startup is a framework-independant way. Is it possible to do this using MSI? I did look on the web for more info but did not find a lot.
</details>
-->

**Comment by yojagad** [comment]
MSI is supported. Please refer to the documentation here.

https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity
