### ISSUE TITLE
Emit language on invocation metric

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/azure-functions-host#3827]
When we emit a log to FunctionsMetrics on invocation of a function, we should include the language of the function.

**Comment by jeffhollan** [comment]
Wondering if for flexibility we add a new column called like `payload` or something that has JSON we can easily modify in the future. That way we don't have to create new columns whenever we want to enrich our metrics.  So the column could be the invocation summary and then payload:

```json
{ "languages": {
   "javascript": {
         "suceeded": 124,
         "failed": 12
    }
}
```

Or something

**Comment by ColbyTresness** [comment]
@jeffhollan

**Comment by fabiocav** [comment]
Completed.
