### ISSUE TITLE
Proxy.json parsing fails on json values

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#3830]
The following proxy.json will result in a parse failure, due to the escaped json value for the Reply-To header:

```javascript
{
  "proxies": {
    "MockProxy": {
      "matchCondition": {
        "route": "/mymockhttp",
        "methods": [
          "GET"
        ]
      },
      "responseOverrides": {
          "response.statusCode": "200",
          "response.headers.Reply-To": "{{ \"TEST\":0 }}"
      }
    }
  }
}
```

This is valid json, and passes JObject.Parse. However [ProxyClientFactory.Create](https://github.com/Azure/azure-functions-host/blob/086d0ec18b64048f48cd1bae198814938cffbe53/src/WebJobs.Script/Host/ProxyMetadataManager.cs#L122) chokes on this. See SO post [here](https://stackoverflow.com/questions/53524420/azure-functions-proxy-unable-to-set-a-http-header-if-value-contains-json).

**Comment by fabiocav** [comment]
@vfedonkin moving this to Triaged.

**Comment by fabiocav** [comment]
@vfedonkin  If this is in progress, please move to the appropriate milestone

**Comment by vfedonkin** [comment]
The workaround is to provide this line, escaping \ with the \\\: 
 "response.headers.Reply-To": "{{ \\\"TEST\\\":0 }}"

Now the question: do we want to add fix for automatic replacement of " to \"  if    " missing a slash?
Since it may lead to confusion (since  \\\"boo\\\" and \"boo\" will result the same), I suggest to not change the logic.

@mathewc, what do you think?

**Comment by mathewc** [comment]
No, we don't want to get into the business of modifying their proxy.json. What I don't understand is why this is blowing up in ProxyClientFactory.Create, while the json actually parses in other parsers (e.g. JObject.Parse)?

**Comment by mathewc** [comment]
Agreed, we don't want to get into the business of modifying their proxy.json. 

What I don't understand is why this is blowing up in ProxyClientFactory.Create, while the json actually parses in other parsers (e.g. JObject.Parse)?

**Comment by vfedonkin** [comment]
So the rule is:    use {{ instead of { and \\\" instead of \"
