### ISSUE TITLE
Fix SecretManager log statements

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#3834]
Several of the new log statements added in https://github.com/Azure/azure-functions-host/commit/7aa72290a0e3e00f161cf2dd80dbdf0f4b74b100 aren't being formatted at runtime, e.g.:

"Function ('{0}') keys are loaded."

**Comment by alrod** [comment]
30ab611ef1daf6ba7e5cdd881e4db24769ce7a1b
