### ISSUE TITLE
Detector for function app health check

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#3838]
Tracking issue for the work to create a detector for compilation failures. Ideally would then be able to be moved to "Diagnose and solve problems."

Create a detector for latest compilation failure occurrences, function name and date/times. The top log text from the failure and link to full logs for that instance.

**Update:**
We really want to know what the current state of the function app is. This is useful for both customers who want to know if their errors are fixed and for us to know if there may be confounding errors.

(Script compilation errors are something that may happen once and then may be fixed immediately)

**Comment by fabiocav** [comment]
@mhoeger is this still pending? Should this move to triaged?
