### ISSUE TITLE
Access to XMLHttpRequest at 'http://localhost:8080/register' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

### ISSUE THREAD

**Issue by slim-souissi** [Azure/azure-functions-host#3839]
I have two requests : get and post . 
The GET Request is working fine via the browser but when i try the POST it mentions  CORS error 403 unauthorized . 
is it normal that CORS appears only in the post request ?

PS : i tried   the POST with postman and it working fine 

Here is the error : 
"Access to XMLHttpRequest at 'http://localhost:8080/register' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status. "

**Comment by fabiocav** [comment]
@slim-souissi how are you running the host in your scenario?

**Comment by slim-souissi** [comment]
i configured my back to support cors and it fixed it  . thanks for replying @fabiocav

**Comment by kadiyamram** [comment]
Can you please explain how the issue is fixed..I am also facing same issues
