### ISSUE TITLE
Update host.json schema

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#3847]
PR # https://github.com/Azure/azure-functions-host/pull/3824 removes maxMessageLength settings from host.json

Need to publish update host.json schema in schema store

**Comment by brettsam** [comment]
FYI -- host.json schema has moved to Azure-Functions repo: https://github.com/Azure/Azure-Functions/tree/master/schemas. It still needs to be committed to schema store, but our copy lives there.

**Comment by brettsam** [comment]
SchemaStore PR is here: https://github.com/SchemaStore/schemastore/pull/597
