### ISSUE TITLE
Performance Counters are not present in App Insights for Functions V2

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#3852]
We need to bring back the performance counter functionality that functions V1 had. I believe it was a point-in-time issue that App Insights did not have a performance counters package that ran on .NET Core, but hopefully that is now resolved. We should investigate.

**Comment by brettsam** [comment]
@lmolkova -- do perf counters work in .NET Core now?

**Comment by lmolkova** [comment]
They do work on Windows hosts (but not linux). They actually [come from AppService](https://github.com/projectkudu/kudu/wiki/Perf-Counters-exposed-as-environment-variables) and captured by PerformanceCollector. I've tried to enable it and it works!

For linux, this is on our backlog, but not prioritized. 

/cc @cijothomas.

**Comment by lmolkova** [comment]
This is fixed and can be closed

**Comment by paulbatum** [comment]
@lmolkova do we need an appinsights SDK update for this to work?

**Comment by lmolkova** [comment]
it's updated and rolled out already on Windows. Do you want to track Linux here as well? It seems 
we have a separate issue for Linux -  https://github.com/Azure/Azure-Functions/issues/1148.

**Comment by paulbatum** [comment]
I totally missed that, sorry! We can close this one since there is a separate issue about Linux.
