### ISSUE TITLE
JS Function host v2: serviceBus trigger - DateTime fields are passed as strings

### ISSUE THREAD

**Issue by lazyruss** [Azure/azure-functions-host#3871]
we developed JS functions using runtime V1.
considering function triggered by service bus topic, this worked perfectly
```
function run(context, message) {
            const operation = {
                // bunch of properties skipped
                Timestamp: message.End.getFullYear() < new Date().getFullYear() ? message.Start : message.End,
            };
}
```

message.End and message.Start were Date objects

however, when we switch to runtime V2,
message.Start and message.End are now strings.

i wonder if this is a bug, or by design?

**Comment by alrod** [comment]
@lazyruss, sorry for late reply. What are `Start` and `End`? Are you serialize some object to message? How do you send an message to the service bus topic?

**Comment by lazyruss** [comment]
@alrod Im sure its already irrelevant. however here are some details.
Message is sent from C# as JSON using regular SB assemblies. Data is defined as struct, Start and End being Datetime fields. 
It seems that in V1 runtime SB trigger recognized fields as Datetime and passed them to JS runtime as Date objects. In V2 those fields are being passed as strings. no big deal though.

**Comment by alrod** [comment]
@lazyruss, thanks for reply. Closed as irrelevant.
