### ISSUE TITLE
HTTP payloads get modified by Function when content-type is application/json

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-host#3875]
_From @brettcannon on December 10, 2018 19:46_

#### Investigative information

Please provide the following:

- Timestamp :2018-11-28 20:25:05.885
- Function App name: pvscbot
- Function name(s) (as appropriate): github

#### Repro steps

POST an `application/json` HTTP payload with a body of `b'{"action": "opened"}'`.

#### Expected behavior

Get the exact HTTP payload in the Function.

#### Actual behavior

Get a POST payload of `b'{\n  "action": "opened"\n}'` (notice the pretty-printing).

#### Known workarounds

None.

#### Related information 

This pretty-printing of JSON breaks HTTP payload signatures. In my specific case, this breaks the [HMAC signature provided by GitHub webhooks](https://developer.github.com/webhooks/#payloads). This is critical as it prevents malicious users from trying to force a bot to do something it shouldn't (as bots typically have write access and can do things like commit and deploy code). It also breaks checking for any man-in-the-middle attacks by verifying the signature against the HTTP payload.

You could theoretically add a key as a GET parameter, but then that exposes the shared secret in logs (compared to an HMAC signature which pulls a secret from an environment variable that Key Vault stores on the Function's behalf), so that is not a tenable solution when security is the aim here.

_Copied from original issue: Azure/azure-functions-python-worker#260_

**Comment by asavaritayal** [comment]
_From @elprans on December 10, 2018 20:4_

I'm pretty sure this is a host issue.  The worker passes the body exactly as received from the host:

https://github.com/Azure/azure-functions-python-worker/blob/e03026773f57145530224ab3a918e321a2c3efb9/azure/functions_worker/bindings/http.py#L129-L131

**Comment by asavaritayal** [comment]
_From @brettcannon on December 10, 2018 20:18_

@elprans I actually know that it is a host issue, but @asavaritayal told me to file it here for tracking purposes  (along with all of the other issues I filed today).

**Comment by fabiocav** [comment]
Assigning this to sprint 39 for investigation.

**Comment by fabiocav** [comment]
@mhoeger; moving this to sprint 40 for investigation. Feel free to reassign if a different sprint would be more appropriate.

**Comment by asavaritayal** [comment]
I think `rawBody` should actually be the default. With the pretty printing in the current HTTP request  body, other fields such as `Content-Length` become inaccurate as well, leaving the users to decipher these fields all over from the raw input. 

Adding a few others to ack in case there is v1 history here :) @fabiocav @mathewc @pragnagopa @maiqbal11

**Comment by mhoeger** [comment]
@asavaritayal - for other languages, we can't change the behavior (since it's a breaking change). For python, you probably could, although I'm also not sure if there were other reasons for pretty-ing the body that the people you tagged earlier would know :)

**Comment by asavaritayal** [comment]
This issue was moved to Azure/azure-functions-python-worker#313

**Comment by fabiocav** [comment]
@asavaritayal need to follow up with you on this as we have an internal issue tracking this problem.
