### ISSUE TITLE
Entry point was not found. Microsoft.Extensions.Logging.Abstractions when using Log4Net with Azure function app 

### ISSUE THREAD

**Issue by joseclament** [Azure/azure-functions-host#3884]
Hi,
I am using Microsoft.Extensions.Logging.Log4Net.AspNetCore in my function app for DI and I am getting the following exception on my function app V2.
Entry point was not found. Microsoft.Extensions.Logging.Abstractions
  at Microsoft.Extensions.Logging.ILoggerFactory.AddProvider(ILoggerProvider provider)
   at Microsoft.Extensions.Logging.Log4NetExtensions.AddLog4Net(ILoggerFactory factory, Log4NetProviderOptions options)
   at Microsoft.Extensions.Logging.Log4NetExtensions.AddLog4Net(ILoggerFactory factory, String log4NetConfigFile, Boolean watch)
   at Microsoft.Extensions.Logging.Log4NetExtensions.AddLog4Net(ILoggerFactory factory, String log4NetConfigFile)

The code for DI

	var configurationBuilder = new ConfigurationBuilder().AddEnvironmentVariables();
            Configuration = configurationBuilder.Build();

            var services = new ServiceCollection();

            var logFileConfig = SetupLogFileLocation();
            var loggerFactory = new LoggerFactory();
            loggerFactory.AddLog4Net(logFileConfig);---> exception throwing here.
            services.AddSingleton(loggerFactory);
            services.AddSingleton(typeof(ILogger<>), typeof(Logger<>));

Please help.

**Comment by fabiocav** [comment]
@joseclament what version of the Log4Net.AspNetCore are you using and where are you building your container? If you can provide a link to a repro on GitHub, that would be helpful.

**Comment by joseclament** [comment]
@fabiocav  I have resolved the issue.

I was using this on a function app, and I have to register couple more additional things to resolve the Logger properly.The following code helped me to resolve it.

            var services = new ServiceCollection();

            var logFileConfig = SetupLogFileLocation(); // The Log4Net file location

            ILoggerFactory loggerFactory = new LoggerFactory();
            loggerFactory.AddLog4Net(logFileConfig);
            services.AddSingleton(loggerFactory);
            services.AddSingleton(typeof(ILogger<>), typeof(Logger<>));

            services.AddSingleton(Configuration);

Also I was using the AppInsight integration, so I have to add Microsoft.ApplicationInsights.Log4NetAppender nuget package too.
