### ISSUE TITLE
Consumption Plan with Storage Queue trigger goes idle on NetCore Functions v2

### ISSUE THREAD

**Issue by oatsoda** [Azure/azure-functions-host#3900]
I have a Storage Queue triggered v2 Function running a netcoreapp 2.1 function.  This is on a consumption plan.

Recently a message was added on 2018-12-13 and it did not get processed until I opened the Function App in the Azure portal (2018-12-17)

Here is a manual run I just did. The function is hosted in West Europe:

> 2018-12-17T14:45:04.238 [Information] Executing 'Functions.ProvisionRequests' (Reason='This function was programmatically called via the host APIs.', Id=949d3ab8-ae83-464e-93a4-853866a52f71)

My function.json:

    {
        "scriptFile": "..\\bin\\<assemblyname>.dll",
        "entryPoint": "<full namespace of static run method>",
        "bindings": [
            {
                "name": "triggerArgs",
                "type": "queueTrigger",
                "direction": "in",
                "queueName": "provisioning",
                "connection": "AzureWebJobsStorage"
            }
        ],
        "disabled": false
    }

In the Azure Portal, here are some of my settings:

`AzureWebJobsStorage` :  Connection String of the storage account 
`WEBSITE_CONTENTAZUREFILECONNECTIONSTRING`: Connection String of the storage account
`FUNCTIONS_WORKER_RUNTIME`: "dotnet"
`FUNCTIONS_EXTENSION_VERSION` : "~2"

The function works fine, it just seems that inactivity on the queue causes it to permanently go idle.

The function is deployed using VSTS/DevOps App Service deployment.

**Comment by oatsoda** [comment]
Here is, I believe, the trigger for the queue item that had been waiting for 4 days until I kicked things in to life by opening the Azure Portal:

> Executing 'Functions.ProvisionRequests' (Reason='New queue message detected on 'provisioning'.', Id=f8ac1ebf-a44f-418d-92e0-3d289e27de84)

**Comment by Rangoric** [comment]
This isn't a fix, but as this is a known issue (wish I had a link to why) I do have some workarounds I use to deal with it.

My usual fix: I make sure the add to queue endpoint is in the same function app as the things that will consume the queue. (Calling the http endpoint will wake up the other functions).

You can have something like a timer that triggers once / time period that is shorter than the idle timeout (10 or 20 minutes).

If you don't use the consumption and use the app service, they will stay on.

ServiceBus, Storage Queue, and CosmosDB triggers have this issue for sure, as do many others that are not HTTP. Http can be triggered when the app is off, because it will turn it on automatically.

**Comment by Rangoric** [comment]
After investigation on my end, my workarounds are not working for Azure Storage Queue. For some reason the storage queue trigger functions will shut down (on a service plan) while the HTTP endpoint remains active.

**Comment by oatsoda** [comment]
Response from Microsoft support:

> I received the response of the product team. The issue was caused by a legacy implementation of the “IP Restrictions” feature (go to the function app on the portal à Platform features à Networking à Configure IP Restrictions). This legacy implementation was at the web worker level, which was causing all requests from the frontend to be rejected, if IP restrictions are configured (I’m assuming that this is the case for you). The implementation was improved so that it is now at the frontend level. Note: If you are not familiar with the terms “web worker” and “frontend”, please take a look at the following documentation:
https://msdn.microsoft.com/en-us/magazine/mt793270.aspx
 
Now, you are actually still running with the legacy implementation. In order to move to the new implementation, you need to just go to the “IP Restrictions” blade; the update will be done automatically. And I would be grateful if you let me know when you do this, so as I can confirm the new implementation is the active one.
