### ISSUE TITLE
Kudu endpoint not registered for Linux Consumption plan Function

### ISSUE THREAD

**Issue by jcbrooks92** [Azure/azure-functions-host#3906]
#### Investigative information

Please provide the following:

- Timestamp: 7:50 PM EST 12/17/2018
- Function App version (1.0 or 2.0): 2.0
- Function App name: jebrook-linuxfunctionapppython.azurewebsites.net
- Function name(s) (as appropriate): NA
- Invocation ID: NA
- Region: West Europe

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a function using the CLI
az functionapp create --resource-group jebrook-functionappRG --os-type Linux --consumption-plan-location westeurope  --runtime python --name jebrook-linuxfunctionapppython --storage-account  function014ecbf88a04
2. Check in observer or navigate to appname.scm.azurewebsites.net. There is no URL registered. Example is seen here.

https://www.digwebinterface.com/?hostnames=jebrook-linuxfunctionapppython.scm.azurewebsites.net&type=&ns=resolver&useresolver=8.8.4.4&nameservers= 

#### Expected behavior

Should Kudu show up for a Azure Function running in the Linux consumption plan?

**Comment by bsnithin44** [comment]
Is there any update on this?
