### ISSUE TITLE
Ambiguous match found error if multiple methods have the same name

### ISSUE THREAD

**Issue by val-janeiko** [Azure/azure-functions-host#3909]
#### Investigative information

- Function App version: 1.0
- Runtime Version: 1.6.0 x64 (Build 1.1.132)

#### Repro steps

1. Create a class with two methods with the same name: one marked with [FunctionName] attribute, other is not. (In the provided example one of the functions is an activity function, the other is just a regular extension method).
2. Launch the function app (locally or in Azure).

```csharp
public static class MyFunctions
{
    [FunctionName("ACustomFunctionName")]
    public static async Task AFunction([ActivityTrigger] DurableActivityContext context)
    {
        // Do stuff here
    }

    public static async Task AFunction(this DurableOrchestrationContext context, Object request)
    {
        await context.CallActivityAsync("ACustomFunctionName", request);
    }
}
```

#### Expected behavior

Function app launches correctly without any errors.
Function with `[FuctionName]` attribute is treated as an activity function.

#### Actual behavior

After launching the app the following error is displayed:
> The following 1 functions are in error:
> ACustomFunctionName: Ambiguous match found.

#### Known workarounds

Rename one of the two methods.

#### Related information 
* Programming language used: C#

**Comment by zippy1981** [comment]
I'm ok with this behavior on azure, but it should also be the behavior when running the azure function runtime locally.

**Comment by kashimiz** [comment]
Hi @zippy1981, this is not a supported pattern and not something that we intend to modify v1.x functions to support. It's recommended that you choose alternate names for your extension methods that aren't overloads of your functions' method names.
