### ISSUE TITLE
Storage Queue Trigger does not pass dequeued message to Azure Linux Consumption Function

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-host#3914]
_From @aluong on January 2, 2019 19:9_

I am testing with the auto-generated Python Storage Queue trigger template. When I publish the function to a **Linux Consumption Function App**, the messages are dequeued but don't appear to get "passed" into the Function for processing. Eventually the message will move to the "dead letter" queue after 5 unsuccessful dequeues.  However, this issue does not reproduce locally.

#### Repro steps

- https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python
- function core tools version 2.3.199

## Setup

1. az group create --name myResourceGroup --location eastus
2. az storage account create --name pythonfuncstorage12345 --location eastus --resource-group myResourceGroup --sku Standard_LRS
3. az storage queue create -n python-queue-items --account-name pythonfuncstorage12345
4. az functionapp create --resource-group myResourceGroup --consumption-plan-location westus --os-type Linux \
--name pyfunc12345 --storage-account pythonfuncstorage12345 --runtime python
5. func init MyFunctionProj (**Python**)
6. func new (**"Azure Queue Storage trigger"**)
7. func extensions install -p Microsoft.Azure.WebJobs.Extensions.Storage -v 3.0.2

## Local Testing
Messages that enqueued are dequeued and processed by the Python Function as expected.

1. Update AzureWebJobsStorage setting with connection string for `pythonfuncstorage12345`
2. func host start
3. Enqueue up a message with message body `hello` from Storage Explorer.

```
[1/2/19 2:46:11 PM] Trigger Details: MessageId: 1191b523-8791-45e7-815a-3cfdcd4eae01, DequeueCount: 1, InsertionTime: 1/2/19 2:46:10 PM +00:00
[1/2/19 2:46:11 PM] Python queue trigger function processed a queue item: hello
```

## Azure Testing with Linux Consumption Function App
Messages are dequeued but they don't seem to be passed into the Python Function. There are no logs in App Insights indicating that any attempt to dequeue the message is processed by the Function. Eventually after 5 dequeues there is a log about the message being moved to the "dead letter" queue in Application Insights.

1. func azure functionapp publish pyfunc12345

```
Getting site publishing info...
pip download -r ../MyFunctionProj/requirements.txt --dest /var/folders/dr/ql9c1rws01104nx4x35592ch0000gn/T/azureworkerdt6t_ivl
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest /var/folders/dr/ql9c1rws01104nx4x35592ch0000gn/T/azureworkermog3kk2i protobuf==3.6.1
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest /var/folders/dr/ql9c1rws01104nx4x35592ch0000gn/T/azureworkermog3kk2i azure_functions==1.0.0a5
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest /var/folders/dr/ql9c1rws01104nx4x35592ch0000gn/T/azureworkermog3kk2i grpcio_tools==1.14.2
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest /var/folders/dr/ql9c1rws01104nx4x35592ch0000gn/T/azureworkermog3kk2i azure_functions_worker==1.0.0a6
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest /var/folders/dr/ql9c1rws01104nx4x35592ch0000gn/T/azureworkermog3kk2i grpcio==1.14.2
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest /var/folders/dr/ql9c1rws01104nx4x35592ch0000gn/T/azureworkermog3kk2i setuptools==40.6.3
pip download --no-deps --only-binary :all: --platform manylinux1_x86_64 --python-version 36 --implementation cp --abi cp36m --dest /var/folders/dr/ql9c1rws01104nx4x35592ch0000gn/T/azureworkermog3kk2i six==1.12.0

Preparing archive...
Uploading 76.55 MB [##############################################################################]
Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Functions in pyfunc12345:
    QueueTrigger - [queueTrigger]
```

2. After enqueuing a message using Storage Explorer I eventually see the following logs in Application Insights:

```
Message has reached MaxDequeueCount of 5. Moving message to queue 'python-queue-items-poison'.
```

#### Expected behavior

I expect that the Function to output a log with the contents of the enqueued message.

#### Actual behavior

The message gets dequeued 5 times and does not get processed or even seen by the Function.

```
Message has reached MaxDequeueCount of 5. Moving message to queue 'python-queue-items-poison'.
```

_Copied from original issue: Azure/azure-functions-python-worker#272_

**Comment by asavaritayal** [comment]
_From @aluong on January 2, 2019 20:10_

The issue seems to go away when I use an earlier version of the Storage extension.
`func extensions install -p Microsoft.Azure.WebJobs.Extensions.Storage -v 3.0.0.`

I presume there are some assembly issues with what is installed in the Linux Consumption worker environment.

**Comment by dariagrigoriu** [comment]
No repro at this time, please reopen if needed.
