### ISSUE TITLE
Cannot set daily usage quota in initial ARM template deployment

### ISSUE THREAD

**Issue by markheath** [Azure/azure-functions-host#3918]
I'm trying to deploy a function app (consumption plan) via an ARM template. I've specified the `dailyMemoryTimeQuota` property on the function app, but when I deploy the ARM template, the quota does not get applied (looking in the portal or via resource manager at the dailyMemoryTimeQuota property).

However, if I then redeploy **the same template** again over the existing function app, then the quota **does** get applied.

Here's a snippet of my ARM template showing the quota (which is an Int parameter in the template)
```
    {
      "apiVersion": "2015-08-01",
      "type": "Microsoft.Web/sites",
      "name": "[variables('functionAppName')]",
      "location": "[parameters('location')]",
      "kind": "functionapp",
      "dependsOn": [
        "[resourceId('Microsoft.Web/serverfarms', variables('hostingPlanName'))]",
        "[resourceId('Microsoft.Storage/storageAccounts', variables('storageAccountName'))]"
      ],
      "properties": {
        "serverFarmId": "[resourceId('Microsoft.Web/serverfarms', variables('hostingPlanName'))]",
        "dailyMemoryTimeQuota": "[parameters('dailyMemoryTimeQuota')]",
        "siteConfig": {
          "appSettings": [
```

And I deploy it like this with the Azure CLI:

```
az group deployment create -g $resourceGroup --template-file $armTemplate `
    --parameters "appName=$functionAppName" "dailyMemoryTimeQuota=12000"
```

Another way I've found that does work is to set it after deployment with the following Azure CLI command:

```
az functionapp update -g $resourceGroup -n $functionAppName --set dailyMemoryTimeQuota=12460
```

**Comment by kashimiz** [comment]
Hi @markheath, apologies for the delayed response. Are you still experiencing this issue? If so, can you provide the most recent version of the following information?

- Timestamp:
- Function App version (1.0 or 2.0):
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

If you don't want to share your Function App name or Functions names on GitHub, please be sure to provide your Invocation ID, Timestamp, and Region - we can use this to look up your Function App/Function. Provide an invocation id per Function. See the [wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) for more details.
