### ISSUE TITLE
Expose binding "dataType" in FunctionRpc.proto

### ISSUE THREAD

**Issue by elprans** [Azure/azure-functions-host#3921]
Per discussion in https://github.com/Azure/azure-functions-python-worker/issues/66, we need the host to expose the "dataType" setting from "function.json" in order to bind the argument data correctly. /cc @pragnagopa @asavaritayal

**Comment by daxian-dbw** [comment]
Today, the `FunctionLoadRequset` message doesn't contains anything related to the `dataType` setting defined for a input binding in `function.json`. This really not convenient for the worker to do some pre-validation on the scripts. It would be great if we can have this information baked in the protocol.

**Comment by maiqbal11** [comment]
Completed in https://github.com/Azure/azure-functions-language-worker-protobuf/pull/23. Also updated for host in https://github.com/Azure/azure-functions-host/pull/4008 and Python worker in 
 https://github.com/Azure/azure-functions-python-worker/pull/300
