### ISSUE TITLE
Language worker processes not killed on host restart from content change

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#3923]
On host restart due to changes in watched directories (by default, the root of the function app), a new language worker process is spun up. However, the previous language worker process is not killed. I believe that this doesn't bring us closer to the desired behavior here https://github.com/Azure/azure-functions-host/issues/3415, because the process that receives messages can be (or may always be) different (noting because fixing this regression should not regress other behavior).

cc: @fabiocav and @pragnagopa

**Comment by fabiocav** [comment]
This would only apply to `JobHost` scoped workers, so it's not the behavior tracked by #3415 and a bug instead. We need to make sure the worker is properly shutdown and disposed on the disposal path.
