### ISSUE TITLE
Error compiling csx function for SendGrid binding

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#3927]
### Repro Steps:
1. Create a function app that uses csx files
2. Create function using the timertrigger template
3. Add `#r "SendGrid"` at the top of the file. 

### Error
Function app throws the following exception in the scenario above
`Metadata file 'SendGrid' could not be found`

Source code for an App in Error state: https://github.com/soninaren/sendGridRepro/tree/2a2597f161a20cdf4c90e5836f6e5a0c7db57b41
- Run `func extensions sync` to restore the binaries

### Workaround
Installing Storage extension seems to resolve the above issue for some reason.

Source code for an App in Error state with workaround:
https://github.com/soninaren/sendGridRepro/tree/34b77f9c6a1a791e0d48d7ff739304848a0f0453
- Run `func extensions sync` to restore the binaries

**Comment by JohnReeson** [comment]
Link a duplicate #3637  for reference.

**Comment by fabiocav** [comment]
@soninaren do you see this issue if you're referencing the metadata file/assembly with the file extension? (i.e. `#r "SendGrid.dll")

**Comment by soninaren** [comment]
> @soninaren do you see this issue if you're referencing the metadata file/assembly with the file extension? (i.e. `#r "SendGrid.dll")

yes, I get the following error if i do so.
```
run.csx(1,1): warning AF006: The reference 'SendGrid.dll' is invalid. If you are attempting to add a framework reference, please remove the '.dll' file extension.
run.csx(1,1): error CS0006: Metadata file 'SendGrid.dll' could not be found```

**Comment by soninaren** [comment]
This is not happening anymore
