### ISSUE TITLE
Improvements to system key handling

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#3929]

**Comment by alrod** [comment]
@fabiocav, can you please add some details for this one?

**Comment by alrod** [comment]
The scope of his work essentially is to validate that we’re adding the key ID claim for system keys.
I validated the we are adding key ID here:
https://github.com/Azure/azure-functions-host/blob/06913c48a043e33c19776fde7795bb256579f31c/src/WebJobs.Script.WebHost/Security/Authentication/Keys/AuthenticationLevelHandler.cs#L67

**Comment by fabiocav** [comment]
Are we OK to close this?

**Comment by alrod** [comment]
https://github.com/Azure/azure-functions-host/commit/b770e7123acd5c9ecfc32042c674c351f8656595
