### ISSUE TITLE
User console logs not working from Language Worker

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#3930]
With the refactoring of the Language Worker up to the Web Host, we're no longer getting logs from `console.log()`. Note that `context.log()` (from Node for example) continues to work.

**Comment by arichiardi** [comment]
Same here.

I am actually thinking of reverting back the worker host and pinning to a working version. This has had (of course) a huge impact on our workflow so I'd rather be on an old version and keep doing our things.

@brettsam do you happen to know the last working version? We are now on `2.0.12246.0`

**Comment by brettsam** [comment]
A workaround is to use `context.log()` instead of `console.log()`. Is that possible in your scenarios?

It looks like 12238 was the first version to include this change, so 12210 would be the last release without it. @pragnagopa does that look right? https://github.com/Azure/azure-functions-host/releases

**Comment by arichiardi** [comment]
This is what Microsoft support also said, but both are not working in my case, unless I do not see where these logs are outputted, they certainly are not showing up on the "Log Streaming" at the moment

**Comment by pragnagopa** [comment]
> It looks like 12238 was the first version to include this change, so 12210 would be the last release without it. 

Yes. Please pin to 2.0.12210

**Comment by brettsam** [comment]
This is JavaScript? I have a sample running on 12246 with:
```
module.exports = async function (context, myTimer) {
    var timeStamp = new Date().toISOString();    
  
    context.log('This is from the context', timeStamp);   

    console.log('This is from the console');
};
```

And I see the `context` logs in the streaming logs (but not the `console` one):
![image](https://user-images.githubusercontent.com/1089915/51060787-c0cda300-15a5-11e9-8e4f-046702633593.png)

Do you have any settings in your host.json that could be hiding these?

**Comment by arichiardi** [comment]
I think I have 

```
logging 
    default: trace
```

Not a the keyboard now I will post the full `host.json`

**Comment by arichiardi** [comment]
@brettsam  which Service Plan are you using? Support said it matters - Windows not working at the moment

**Comment by arichiardi** [comment]
Also @brettsam what do you mean by the "`console` one" ? I am just using Log Stream from the function in Platform Features

**Comment by arichiardi** [comment]
So it seems like: `2.0.12210.0` is showing also stdout - this is great, this is what we want.

Above that only `context.log` is shown. We are using structured output (JSON) to stdout, following the 12 factor app predicaments.

I have question though, my trials also involved `host.json`, and at some point I had:

```
  "logging": {
    "logLevel": {
      "Function": "Information",
      "default": "Error"
    }
  }
```

I could not see anything with it. Is it because `default` is kind of indicating the "root" logger and therefore takes precedence?

Thank you!

**Comment by brettsam** [comment]
When I said `console` -- I mean't the call to `console.log()`. I don't think the service plan you're would matter -- did Support give any more details than that?

I just copied your exact `logging` section into my app and I see the logs as expected. The `default` is the fallback if no other match is found. In your case, you should be seeing the logs coming from your function.

Can you share what your logging code looks like? And exactly where you're looking for them? There's a few places to try to view logs and I want to make sure I'm looking in the right place to try to repro this.

**Comment by arichiardi** [comment]
So I spent some time on this, settings and all, on Friday. Thanks for your feedback, which is way more than what I got from support.

It turns out that `context.log` indeed prints out with the latest version, `console.log` only in `2.0.12210.0`.

What tripped me is that it takes a while here for seeing them displayed and it is of course be taken as a symptom while you try to debug.

**Comment by arichiardi** [comment]
I see there is a new version, `2.0.12285`, is this problem fixed in there?

**Comment by arichiardi** [comment]
Yeah well that would require a revamp on our side :smile: I guess we will stick with the old version for now

**Comment by arichiardi** [comment]
It also would seem like the format of the messages would change with `context.log` and this means I would need to tweak the Application Insights queries as well. It all adds up.

**Comment by arichiardi** [comment]
Apparently my pin has been unpinned (like in chess!). @brettsam do you happen to know what happened?

The only thing I can see is:

![2019-01-24-154609_751x153_scrot](https://user-images.githubusercontent.com/1724788/51716045-08195200-1ff0-11e9-9443-b69c32e8d04f.png)


It stopped working around an hour ago, which is the time I spent trying to understand if I was doing something wrong on my side.

**Comment by brettsam** [comment]
Unfortunately, it looks like this build was removed last week (I wasn't aware) and it must have just hit you.

Can you share your App Insights queries that may break? The way we log console.log() has a different Category name, but the log details should be very similar.

**Comment by arichiardi** [comment]
Thank you for your answer, you might be right, it might be not that much work but it definitely is extra work that our team didn't anticipate for such a basic functionality that IMHO any platform should provide without a hitch.

Sorry for venting out to you, we are in contact with support so I will stop flooding this thread. 

Cheers
