### ISSUE TITLE
Successful and Failed Execution metric

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/azure-functions-host#3943]
The metric we're planning to move to for executions aggregation, function.invoke.latency, regresses a part of our pipeline, since it doesn't tell us whether the execution was successful. We should either add to this metric a field for whether the execution was successful, or add a new metric to give us this information.

**Comment by paulbatum** [comment]
Yes, I need this for some detectors (otherwise have to parse strings in the functions logs table).

**Comment by ColbyTresness** [comment]
@jeffhollan

**Comment by fabiocav** [comment]
Adding this to sprint 47 for scoping/investigation. May not be completed until 48.

**Comment by fabiocav** [comment]
This is done.

Duplicate of #3640
