### ISSUE TITLE
Could not load file or assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

### ISSUE THREAD

**Issue by vinguan** [Azure/azure-functions-host#3944]
I am trying to upgrade azure functions to V1 to V2 and .NET Core i am getting the following error

![image](https://user-images.githubusercontent.com/6222878/51084164-84688700-170c-11e9-9082-5b1215731e7b.png)

Azure Functions Tools version : 15.10.2046
Visual Studio 2017 version : 15.9.4
Azure Functions SDK : 1.0.24

**Comment by hisuwh** [comment]
@vinguan did you find a solution?  I am experiencing the same problem under the same scenario

**Comment by vinguan** [comment]
@hisuwh I solved by forcing VS to update Azure Functions Tools, which were massively outdated and VS had a [bug](https://github.com/Azure/azure-functions-core-tools/issues/694) on not updating it. You try [this](https://medium.com/@tsuyoshiushio/solving-azure-functions-and-webjobs-tools-update-issue-with-visual-studio-could-not-load-file-or-fee9f8d30136), or [this](https://github.com/Azure/azure-functions-tooling-feed/wiki/Fixing-Azure-Function-Core-Tools-download-issues-for-Visual-Studio#execute-an-automated-script) to fix it.

**Comment by vinguan** [comment]
Closing, fixed with this [fix](https://github.com/Azure/azure-functions-tooling-feed/wiki/Fixing-Azure-Function-Core-Tools-download-issues-for-Visual-Studio#execute-an-automated-script).

**Comment by hisuwh** [comment]
Clearing the nuget cache worked for me
