### ISSUE TITLE
Publish show double slash in Invoke url when routePrefix is empty

### ISSUE THREAD

**Issue by JohnReeson** [Azure/azure-functions-host#3953]
With `"routePrefix":""` set in host.json, after publishing the url displays `//`

![capture](https://user-images.githubusercontent.com/35160013/51024249-fed9bf80-15c3-11e9-9d2e-d0dc65660ab9.JPG)

**Comment by ahmelsayed** [comment]
Closed in https://github.com/Azure/azure-functions-host/pull/4171
