### ISSUE TITLE
AppLens: check for host startup issues and change logging level

### ISSUE THREAD

**Issue by cts-shrahman** [Azure/azure-functions-host#3957]
> We are seeing error in FuncitonsLogs but not in the applens detector. Can you please add the code to check for host startup issues. 
 
And also we need to change the logging Level. I believe 5 is verbose…we should change it to Level 2 or 3.
  
https://applens.azurewebsites.net/subscriptions/ff0b4d40-5bc2-4085-9dcf-2f2a484a31f6/resourceGroups/Dev-Ops-East2-RG/providers/Microsoft.Web/sites/SwaggerDef/detectors/functionsinerror?startTime=2018-10-28T16:03&endTime=2018-10-29T16:03
 
[Execute Query](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdataexplorer.azure.com%2Fclusters%2Fwawseus%2Fdatabases%2Fwawsprod%3Fquery%3DH4sIAAAAAAAAA3MrzUsuyczPK%2FbJTy%2Fm5apRKM9ILUpVCPH0dQ0OcfQNULBTSEzP1zBM0VRAyDoWFPgl5qYq2NYpKAWXJ6anpxa5pKYpgVWUJGanKhgagJgFRflZqcklCj6pZak5OgrBpbm5iUWVvFy8XAAJWekbdgAAAA%3D%3D&data=02%7C01%7Cshrahman%40microsoft.com%7C08af69496b95417d244608d63dbbe05e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636764274496201531&sdata=mtWykgdlXHyhDfSTxc4Nw%2FJjXrploFEpjwF1nprgA2o%3D&reserved=0)

`FunctionsLogs
| where TIMESTAMP > ago(1d) 
| where AppName =~ "SwaggerDef" 
| take 10
| project Level, Summary
`

**Comment by FinVamp1** [comment]
I don't think this is needed any longer.
