### ISSUE TITLE
Improved error message for "unable to access due to IP restrictions".

### ISSUE THREAD

**Issue by cts-shrahman** [Azure/azure-functions-host#3960]
When IP restrictions block the client's IP, they are unable to access the Function execution blade in the Azure portal. And they see a misleading error:
 
1. Customer is requesting a user friendly error message in this scenario.
2. The alternative would be to allow the clients to access the blade, through having the controller proxy the requests or similar.

(Even If the other team members of the Admin have Contributor role on the Function app they are unable to access the app just because of the IP restriction rule).

**Comment by paulbatum** [comment]
Since this is a portal issue, here is the internal bug link:
https://msazure.visualstudio.com/Antares/_workitems/edit/4191597/

**Comment by jeffhollan** [comment]
Per linked issue this is now merged in. Are we good to close?

**Comment by fabiocav** [comment]
Closing to reflect the state of the issue. Please reopen if needed.

**Comment by cts-shrahman** [comment]
Not yet resolved.

**Comment by FinVamp1** [comment]
This should be fixed. Just tested and see this.
![image](https://user-images.githubusercontent.com/1410302/60622492-6e44a500-9dd8-11e9-92eb-32f5c9f797a2.png)

**Comment by FinVamp1** [comment]
Closing
