### ISSUE TITLE
Function apps do not log malformed json data

### ISSUE THREAD

**Issue by cts-shrahman** [Azure/azure-functions-host#3962]
Function apps do not log malformed json data.

Currently have a customer who was attempting to log malformed json data in one of his function apps in order to identify an issue on the devices sending these malformed json.
 
1- We attempted to log this through application insights changing the trace level to Trace however although we saw the failed requests the malformed json data was not there.
2 - The only other way to capture this malformed data is through event hub but this has to be on initial setup if there is an existing environment that is already running this cannot be added.
3- The only way customer has to do this is actually print the malformed json in the function app which has to go through a lengthy political process in order to modify the code. Some other customers may experience similar issues.

Ask: Log the body of the malformed message by default in Application Insight

**Comment by cts-shrahman** [comment]
Here are the steps to reproduce it :

1.	Create IoT Hub
2.	Create a Function App 
3.	Add portal based function 
4.	Add an IoT Hub triggered function and connect to the above IoT Hub
5.	Change the default code as shown below


Default   Code
--
`
public static void Run(string myIoTHubMessage, ILogger log)
{
    log.LogInformation($"C# IoT Hub trigger function processed a message: {myIoTHubMessage}");
}
`

Change To
--
`public static void Run(MyTemp myIoTHubMessage, ILogger log)
{
log.LogInformation($"C# IoT Hub trigger function processed a message: {myIoTHubMessage}");
}

public class MyTemp
{
double  temperature {get;set;}
double  humidity {get;set;}
}
`
6.	Now hit the test
7.	Leave the “Test Message” as it is
8.	You should see following error

> 2019-01-15T23:03:27.186 [Information] Executing 'Functions.IoTHub_EventHub1' (Reason='This function was programmatically called via the host APIs.', Id=a5466486-2570-4942-80b8-11166836e584)
> 2019-01-15T23:03:27.343 [Error] Executed 'Functions.IoTHub_EventHub1' (Failed, Id=a5466486-2570-4942-80b8-11166836e584)
> Binding parameters to complex objects (such as 'MyTemp') uses Json.NET serialization. 
> 1. Bind the parameter type as 'string' instead of 'MyTemp' to get the raw values and avoid JSON deserialization, or
> 2. Change the queue payload to be valid json. The JSON parser failed: Unexpected character encountered while parsing value: T. Path '', line 0, position 0.
> 
9.	In the application insights also, you should see same error with callstacks
10.	So customer is interested in logging the actual message “Test Message” , so that we can correct it.
11.	They can change the parameter type to string to get the “Test Message” value. But this needs code deployment, stopping/swapping slots etc. Customer website was high load and cannot afford for downtime.
12.	It will be great help to customers if we can log the actual message  “Test Message” so that can fix the client code without any server downtime.
13.	Now change the test data as below to make function to work
`{
    "temperature":90.0,
    "humidity":19.9
}
`

**Comment by FinVamp1** [comment]
Resolving this as a corner case that should be caught in Unit Testing.
