### ISSUE TITLE
Profiling C# compiled functions

### ISSUE THREAD

**Issue by chuchuva** [Azure/azure-functions-host#3964]
It would be great to be able to profile a C# compiled function to see why it is slow.

Perhaps we could use App Insights Profiler? See https://stackoverflow.com/q/49449113/14131

**Comment by safihamid** [comment]
Profiling works for functions in App Service plan, you can use Kudu, Diagnose and Solve problems or AI Profiler. Profiling is not currently supported in Consumption plan.

**Comment by kashimiz** [comment]
Closed as answered.
