### ISSUE TITLE
No logs when 500 caused by issue preventing function from being loaded

### ISSUE THREAD

**Issue by maiqbal11** [Azure/azure-functions-host#3975]
_From @brettcannon on December 10, 2018 19:48_

If you have something like an unhandled `ImportError` that occurs at load time of your function code, the user gets a 500 (which is correct), but there is no log produced anywhere for that 500. In my case I had to realize that trying to execute the function manually may show some traceback issue. But otherwise nothing shows up in the streaming logs, Application Insights, etc. to help debug this or even notify the user that the 500 is occurring.

_Copied from original issue: Azure/azure-functions-python-worker#261_

**Comment by maiqbal11** [comment]
_From @priyaananthasankar on December 10, 2018 19:53_

Yes the logging.info isnt showing up even when functions is run inside a container,

**Comment by maiqbal11** [comment]
_From @elprans on December 10, 2018 20:11_

Errors like the `ImportError` are reported by the worker via `FunctionLoadResponse`:

https://github.com/Azure/azure-functions-python-worker/blob/e03026773f57145530224ab3a918e321a2c3efb9/azure/functions_worker/dispatcher.py#L333-L340

We can double the `FunctionLoadResponse` with a `logger.exception()` there if that makes sense.

**Comment by maiqbal11** [comment]
_From @asavaritayal on January 9, 2019 21:48_

Needs to be tested on both Linux consumption and dedicated.

**Comment by maiqbal11** [comment]
The issue here is that we are not logging exceptions at the point where a function fails to load.  We log exceptions when the failed function is **invoked**. @brettsam is working on a fix that will allow logging to ApplicationInsights when these kinds of exception occur - currently the logger design has limitations that prevent this from happening.

**Comment by jeffhollan** [comment]
@brettsam I think you mentioned in standup the other day that you were looking at potentially going to re-work when or how certain logging gets registered to capture exception or errors that may occur on something like the very first request.  Does that apply to this as well?  I know you have dependency injection in flight but wondering if this / that could be picked up in a sprint this month still?

**Comment by brettsam** [comment]
Yeah, I had something partially working but it stalled due to a lot of complications with placeholders/specialization and DI. The issue: we need a way to log to the customer's loggers before we know what the customer's loggers are. We do this in some places already with a "deferred logger" that caches logs and flushes when the customer's logging is initialized. I don't really like it (mainly due to the timestamp/ordering of logs being incorrect) but it may be our only option without revamping a bunch of stuff.

I'll grab some people in a room so we can brainstorm other ideas and see if there's an approach I haven't tried yet.

**Comment by fabiocav** [comment]
@brettsam we need to pick this back up. We had a conversation about this last week and more and more scenarios are impacted by this. Let's plan on a design review so we can move this forward.

**Comment by jeffhollan** [comment]
@asavaritayal / @brettsam any updates here?  See it's had a nice bump from sprint to sprint but curious if we can get an ETA for some of the "day 1" experience reporting

**Comment by brettsam** [comment]
@maiqbal11 / @asavaritayal -- can you help me with a repro here? I tried adding an `import dummy` to the top of my python script but I don't see any errors thrown anywhere at all until I call the function (i.e. -- there's nothing for us to log). Is there something special that I have to do to cause the `ImportError` upon load that's mentioned?

**Comment by brettsam** [comment]
Duh... as soon as I looked in the `LoadResponse()`, I see what you mean. We store the error to log it upon invocation, but never actually write it out. @pragnagopa -- do you know why that is? Can we log the load response error right there?

**Comment by fabiocav** [comment]
In PR. Moving to 52

**Comment by pragnagopa** [comment]
Discussed this offline. Adding notes here:
Errors on LoadResponse are currently cached as there was no function level logger. One of the goals of this issue is to be able to see function load errors on the portal. This would improve getting started experience for out-of-proc languages.
