### ISSUE TITLE
SyncTriggers fails for function apps with proxies

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-host#3978]
System.ArgumentException : Could not determine JSON object type for type \u003c\u003ef__AnonymousType7`1[System.String].
    at Newtonsoft.Json.Linq.JValue.GetValueType(Nullable`1 current,Object value)
    at Newtonsoft.Json.Linq.JContainer.CreateFromContent(Object content)
    at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index,Object content,Boolean skipParentCheck)
    at Newtonsoft.Json.Linq.JContainer.Add(Object content)
    at Newtonsoft.Json.Linq.JObject..ctor(Object content)
    at async Microsoft.Azure.WebJobs.Script.WebHost.Management.WebFunctionsManager.TrySyncTriggers() at /azure-functions-host-dev-seabreeze/src/WebJobs.Script.WebHost/Management/WebFunctionsManager.cs : 218

  |   |   |   |  
-- | -- | -- | -- | --
  | t | Summary | Details | Level
  | 2019-01-18 00:16:44.4740000 | An unhandled host error has occurred. | System.ArgumentException : Could not determine JSON object type for type \u003c\u003ef__AnonymousType7`1[System.String].    at Newtonsoft.Json.Linq.JValue.GetValueType(Nullable`1 current,Object value)    at Newtonsoft.Json.Linq.JContainer.CreateFromContent(Object content)    at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index,Object content,Boolean skipParentCheck)    at Newtonsoft.Json.Linq.JContainer.Add(Object content)    at Newtonsoft.Json.Linq.JObject..ctor(Object content)    at async Microsoft.Azure.WebJobs.Script.WebHost.Management.WebFunctionsManager.TrySyncTriggers() at /azure-functions-host-dev-seabreeze/src/WebJobs.Script.WebHost/Management/WebFunctionsManager.cs : 218    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.HostController.SyncTriggers() at /azure-functions-host-dev-seabreeze/src/WebJobs.Script.WebHost/Controllers/HostController.cs : 150    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at async Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper,ObjectMethodExecutor executor,Object controller,Object[] arguments)    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Threading.Tasks.ValueTask`1.get_Result()    at async Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at async Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.Co... | 2
  | 2019-01-18 00:17:19.0480000 | An unhandled host error has occurred. | System.ArgumentException : Could not determine JSON object type for type \u003c\u003ef__AnonymousType7`1[System.String].    at Newtonsoft.Json.Linq.JValue.GetValueType(Nullable`1 current,Object value)    at Newtonsoft.Json.Linq.JContainer.CreateFromContent(Object content)    at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index,Object content,Boolean skipParentCheck)    at Newtonsoft.Json.Linq.JContainer.Add(Object content)    at Newtonsoft.Json.Linq.JObject..ctor(Object content)    at async Microsoft.Azure.WebJobs.Script.WebHost.Management.WebFunctionsManager.TrySyncTriggers() at /azure-functions-host-dev-seabreeze/src/WebJobs.Script.WebHost/Management/WebFunctionsManager.cs : 218    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.HostController.SyncTriggers() at /azure-functions-host-dev-seabreeze/src/WebJobs.Script.WebHost/Controllers/HostController.cs : 150    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at async Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper,ObjectMethodExecutor executor,Object controller,Object[] arguments)    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Threading.Tasks.ValueTask`1.get_Result()    at async Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at async Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.Co... | 2
  | 2019-01-18 00:17:59.7650000 | An unhandled host error has occurred. | System.ArgumentException : Could not determine JSON object type for type \u003c\u003ef__AnonymousType7`1[System.String].    at Newtonsoft.Json.Linq.JValue.GetValueType(Nullable`1 current,Object value)    at Newtonsoft.Json.Linq.JContainer.CreateFromContent(Object content)    at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index,Object content,Boolean skipParentCheck)    at Newtonsoft.Json.Linq.JContainer.Add(Object content)    at Newtonsoft.Json.Linq.JObject..ctor(Object content)    at async Microsoft.Azure.WebJobs.Script.WebHost.Management.WebFunctionsManager.TrySyncTriggers() at /azure-functions-host-dev-seabreeze/src/WebJobs.Script.WebHost/Management/WebFunctionsManager.cs : 218    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.HostController.SyncTriggers() at /azure-functions-host-dev-seabreeze/src/WebJobs.Script.WebHost/Controllers/HostController.cs : 150    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at async Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper,ObjectMethodExecutor executor,Object controller,Object[] arguments)    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Threading.Tasks.ValueTask`1.get_Result()    at async Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at async Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.Co... | 2
  | 2019-01-18 00:19:22.0650000 | An unhandled host error has occurred. | System.ArgumentException : Could not determine JSON object type for type \u003c\u003ef__AnonymousType7`1[System.String].    at Newtonsoft.Json.Linq.JValue.GetValueType(Nullable`1 current,Object value)    at Newtonsoft.Json.Linq.JContainer.CreateFromContent(Object content)    at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index,Object content,Boolean skipParentCheck)    at Newtonsoft.Json.Linq.JContainer.Add(Object content)    at Newtonsoft.Json.Linq.JObject..ctor(Object content)    at async Microsoft.Azure.WebJobs.Script.WebHost.Management.WebFunctionsManager.TrySyncTriggers() at /azure-functions-host-dev-seabreeze/src/WebJobs.Script.WebHost/Management/WebFunctionsManager.cs : 218    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.HostController.SyncTriggers() at /azure-functions-host-dev-seabreeze/src/WebJobs.Script.WebHost/Controllers/HostController.cs : 150    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at async Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper,ObjectMethodExecutor executor,Object controller,Object[] arguments)    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Threading.Tasks.ValueTask`1.get_Result()    at async Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at async Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.Co... | 2

**Comment by ahmelsayed** [comment]
fixed in https://github.com/Azure/azure-functions-host/pull/3815
