### ISSUE TITLE
Returning a RedirectResult with a URL causes NullReferenceException

### ISSUE THREAD

**Issue by rob-hendrickx** [Azure/azure-functions-host#3986]
#### Investigative information

Please provide the following:

- Function App version (1.0 or 2.0): 2.0

#### Repro steps

1) Create a function app with a HTTP triggered function that returns a RedirectResult.
2) Run it on runtime version 2.0.12275.0

#### Expected behavior

Receive an HTTP redirect.
(it still works like this on version 2.0.12246.0)

#### Actual behavior

Receive an HTTP InternalServerError caused by a NullReferenceException in the UrlHelperBase.
(issue on 2.0.12275.0)

#### Known workarounds

Return a custom ActionResult like this:

```
public class CustomRedirectResult : StatusCodeResult
    {
        public string Url { get; set; }

        public CustomRedirectResult(string url) : base(307)
        {
            Url = url;
        }

        public override void ExecuteResult(ActionContext context)
        {
            base.ExecuteResult(context);
            context.HttpContext.Response.Redirect(Url, false);
        }
    }
```
#### Related information 

Exception details:

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.AspNetCore.Mvc.Core
  StackTrace:
   at Microsoft.AspNetCore.Mvc.Routing.UrlHelperBase..ctor(ActionContext actionContext) in /_/src/Microsoft.AspNetCore.Mvc.Core/Routing/UrlHelperBase.cs:line 31
   at Microsoft.AspNetCore.Mvc.Routing.UrlHelperFactory.GetUrlHelper(ActionContext context) in /_/src/Microsoft.AspNetCore.Mvc.Core/Routing/UrlHelperFactory.cs:line 64
   at Microsoft.AspNetCore.Mvc.Infrastructure.RedirectResultExecutor.ExecuteAsync(ActionContext context, RedirectResult result) in /_/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/RedirectResultExecutor.cs:line 48
   at Microsoft.AspNetCore.Mvc.RedirectResult.ExecuteResultAsync(ActionContext context) in /_/src/Microsoft.AspNetCore.Mvc.Core/RedirectResult.cs:line 110
   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.FunctionInvocationMiddleware.<Invoke>d__2.MoveNext() in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Middleware\FunctionInvocationMiddleware.cs:line 70
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\243\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132

**Comment by jsmith50-sc** [comment]
Getting the same here as well after the 2.16 update possibly.

**Comment by trydis** [comment]
We have a similar issue when returning a `RedirectResult` with a string, ends up with an internal server error. It works when pinning to `2.0.12246.0`.

**Comment by tjgalama** [comment]
yep, also are running into this problem.

**Comment by tjgalama** [comment]
it looks like Type *UrlHelperBase* in *Microsoft.AspNetCore.Mvc.Core, 
Version=_2.2.0.0_* (previous runtime used 2.1.0.0) requires the `ActionContext.RouteData` to be set.
Since this property is null the `NullReferenceException` occurs.

This *ActionContext* instance is passed within the call-stack, but is created within method:
*Microsoft.Azure.WebJobs.Script.WebHost.Middleware.FunctionInvocationMiddleware.Invoke(HttpContext context)* within Microsoft.Azure.WebJobs.Script.WebHost.dll (File V. 2.0.12265.0). In this method the property *RouteData* is clearly not set.

For me adjusting the Function Runtime version is disturbing for our CI process. 
Therefore, I added the following quick fix within my *RedirectResult* derived type; 

``` csharp
public override Task ExecuteResultAsync(ActionContext context)
{
   ....
   if (context.RouteData == null)
      context.RouteData = new RouteData();
   return base.ExecuteResultAsync(context);
}
```

**Comment by rob-hendrickx** [comment]
@tjgalama Indeed, we noticed that that was the origin of the exception aswell. We created a workaround by creating a derived type of StatusCodeResult and generating a Redirect there. But your workaround is cleaner IMO. Well it works, so we'll leave it as is.

**Comment by rob-hendrickx** [comment]
Closed by accident

**Comment by brettsam** [comment]
@mathewc / @fabiocav -- could one of you look at this? Seems to be hitting a few people. @tjgalama's investigation above indicates it's a breaking change in ASP.NET 2.2. Is there any way we can work around this?

**Comment by pakrym** [comment]
cc @pranavkm
