### ISSUE TITLE
Please clarify how to install current functions runtime in local tools

### ISSUE THREAD

**Issue by forki** [Azure/azure-functions-host#3987]
When I download the core tools it seems to ship with an outdated functions runtime:

![image](https://user-images.githubusercontent.com/57396/51479746-77443b80-1d8f-11e9-9950-529feb4f3347.png)

https://github.com/Azure/azure-functions-host/releases/tag/v2.0.12265 states that "This release has been made available to Visual Studio users." - how can we install it locally?

discussion in https://github.com/Azure/azure-functions-host/issues/3854 suggests I'm not the only one who does not see how to install the runtime patch locally.

**Comment by 7sharp9** [comment]
@JohnGalt1717  Maybe use your Azure Support Plan if this is of critical importance and you need an SLA.  Shouting to the wind achieves nothing.

**Comment by JohnGalt1717** [comment]
@7sharp9 this isn't azure now. This is the Functions development team...

**Comment by 7sharp9** [comment]
Yeah I know, but like it or not if you read the repos readme they are pretty clear there is no SLA to fix anything :-(

**Comment by JohnGalt1717** [comment]
@7sharp9 I know, but this isn't really fixing anything. This is keeping the platform in sync with the .NET Core runtime which is a non-optional requirement for this tool to be useful.

**Comment by tommyk** [comment]
man, azure functions has been wasting my time for quite some time.  i decided to update to the official 2.0 runtime and i been debugging problems for a few days now.  i got my very simple extension code booting up and it runs locally, but when i push to azure its not working.  after lots of poking, here i am in a thread about a mismatch currently between the CLI tools and azure.  i am running the cli tools from master (which isn't even pointing to the same version as azure, but its closer) and now at least locally i see the same behavior.  

trying to unwind the difference between the runtime and the sdk is quite hard.  it would appear something has changed somewhere with the 2.2 upgrade as using the code from [here](https://www.tpeczek.com/2018/12/alternative-approach-to-httpclient-in.html) no longer works and throws the exception below when trying to setup the `HttpClient`.

```
System.Private.CoreLib: Exception while executing function: DeploymentSlackNotification. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'client'. Microsoft.Extensions.DependencyInjection.Abstractions: No service for type 'Microsoft.Extensions.Http.HttpMessageHandlerBuilder' has been registered.

**Comment by fabiocav** [comment]
The latest release is now up for VS/VS Code, NPM and Homebrew. 

@tommyk can you please open a separate issue if you continue to run into problems there?

**Comment by forki** [comment]
@fabiocav thanks for releasing it, but this issue was more about asking for docs on how to install the bits manually in order to test the runtime before it ships.
