### ISSUE TITLE
Functions no longer working under WSL (Ubuntu 18.04) gRPC errors

### ISSUE THREAD

**Issue by benc-uk** [Azure/azure-functions-host#3988]
Using WSL and Ubuntu 18.04. Running func start results in gRPC errors
```
 Error: gRPC client connection info is missing or incorrect ('port' is 0).
```
This happens in my existing Function project (Node.js) and also creating a empty new project with func init and immediately running func start

Versions
Function CLI version: 2.3.199 (Installed with apt package)
Node version: 8.15.0
Dotnet Core version: 2.1.503
Windows 10 version: 1809
WSL distro: Ubuntu 18.04.1 LTS

#### Investigative information

Full investigation done here:
https://github.com/Azure/azure-functions-core-tools/issues/995#issuecomment-456083668

#### Repro steps
Use functions core tools under WSL
[Full reproduction steps](https://github.com/Azure/azure-functions-core-tools/issues/995)

#### Expected behavior

Functions host starts

#### Actual behavior

Functions host dies with above gRPC error

#### Known workarounds

None - However root cause has been fixed in grpc here https://github.com/grpc/grpc/pull/17193
Updating Core.Grpc package to 1.17.0 will fix this

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by wpwoodjr** [comment]
> ## Resolution: Please upgrade the gRPC Core version to 1.17.0

Sorry, but how do you do this upgrade in the context of Azure Functions?

**Comment by ahmelsayed** [comment]
@wpwoodjr this will be in the `2.0.12303` release which hasn't started rolling out yet. Unfortunately I'm not aware of a workaround for WSL. @benc-uk has a detailed investigation here https://github.com/Azure/azure-functions-core-tools/issues/995 (thanks Ben!) and that issue will be closed once this release is completed.

**Comment by benc-uk** [comment]
I just upgraded to version 2.4.317 of the core tools, I noticed that this release updated the version of azure-functions-host to version 2.0.12303, and that version has the updated gRPC version (1.18.0) to fix this.

However when I start my functions I see the runtime version is still **2.0.12285.0** and I still get the same gRPC errors as before.

```
$ func start
Azure Functions Core Tools (2.4.317 Commit hash: 63e1996b6c281079427e7c9b8a0a1c633988a195)
Function Runtime Version: 2.0.12285.0
```

```
throw new Error(`gRPC client connection info is missing or incorrect (${debugInfo.join(", ")}).`);,Error: gRPC client connection info is missing or incorrect ('port' is 0).
```

**Comment by wpwoodjr** [comment]
Any update?  The the runtime version is still **2.0.12285.0**
