### ISSUE TITLE
Profile language worker function dispatching

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#3990]
Opening this track the performance analysis work on for out-of-proc language worker invocations to help us understand and prioritize improvements in this area.

**Comment by fabiocav** [comment]
FYI @mhoeger @pragnagopa @alrod 
We'll likely have this assigned to the next sprint to help us scope the work.

**Comment by pragnagopa** [comment]
Issue https://github.com/Azure/azure-functions-powershell-worker/issues/127 has more details from @daxian-dbw

**Comment by fabiocav** [comment]
We need to profile this code in isolation as well, to identify problems impacting all language workers. We'll likely start there.

**Comment by pragnagopa** [comment]
grpc has some guidance on benchmark testing: https://grpc.io/docs/guides/benchmarking.html

**Comment by alrod** [comment]
https://github.com/Azure/azure-functions-host/issues/4076

**Comment by daxian-dbw** [comment]
> **For further analysis, we need to capture invocation metrics on the host measuring time from sending the invocation request to the worker to receiving the invocation response from the worker.**

Now, is there a way to get the mentioned metric with a specific worker? If not, shall I open a new issue to track this work?

**Comment by alrod** [comment]
@daxian-dbwI, I was investigating using JS worker. If you want me measure the time for PS please create an issue and assign it to me.
