### ISSUE TITLE
Send grpc large messages in chunks

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#3992]
Recommended approach to send large messages via grpc is to send messages in smaller chunks.  There is a known perf impact when sending a single large message even though not officially documented.

Note: This is a prerequisite for adding stream support for out-of-proc languages.

**Comment by jeffhollan** [comment]
Could use some help on understanding priority here - wondering if any of the streaming stuff is adjacent to this, more, or less priority?  Let me know.  Thanks!

**Comment by pragnagopa** [comment]
cc: @fabiocav 
This is a tracking item to figure out if we would get performance benefits sending large messages like a blobtrigger input in chunks compared to sending the whole file at once over grpc from host to language worker.

So far, I haven't seen any performance gain. Modified sample here: https://grpc.io/docs/quickstart/csharp.html to send file in chunks

| File Size |Chunk Size |Transfer Time|
| ------------- | ------------- |------------- |
| 200 MB  | 4MB  | 00:00:03.55
| 200 MB  | -| 00:00:02.13
| 200 MB  | 64KB  | 00:00:25.11
| 200 MB  | - | 00:00:01.99
 
It is possible chunking does not matter when running on the same machine. Will investigate further. If chunking does not help with performance, will increase message length to maximum allowed.

**Comment by ahmedelnably** [comment]
@pragnagopa is this still applicable?

**Comment by pragnagopa** [comment]
Initial investigation did not show any perf improvement. Closing this as rich bindings support should include scenario to support streaming from event sources such as blob trigger that support streaming blob content.
