### ISSUE TITLE
Http function content encoding not working

### ISSUE THREAD

**Issue by synercoder** [Azure/azure-functions-host#4000]
We created a small function to serve some images (logo's) and some scripts for cookie notice purposes. This we deployed to Azure Functions so it can serve multiple websites from a single endpoint. But now the site take a hit in page speed because the content from Azure Functions is not served using content-encoding (for example GZIP).

We tried to look for an answer and the closed we could find was https://stackoverflow.com/questions/49339268/how-can-i-enable-gzip-compression-on-azure-functions-v2 but this states that gzip should automatically work. Which is not the case (for us).

#### Investigative information

- Timestamp: 2019-01-24T11:37:51.607
- Function App version (1.0 or 2.0): 2.0
- Function App name: privacy-consent
- Function name(s) (as appropriate): logo
- Invocation ID: 9c0e6a6c-be66-44b1-b529-2b73e0ae0f4d
- Region: eu-west

#### Repro steps

Call the [function](https://privacy-consent.azurewebsites.net/api/logo/printapi) using any browser or postman, providing a "Accept-Encoding" header.

Chrome example request:
```
GET /api/logo/printapi HTTP/1.1
Host: privacy-consent.azurewebsites.net
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,nl;q=0.8,en-GB;q=0.7,de;q=0.6
```

#### Expected behavior

We expect the function to return an HTTP result that has a "Content-Encoding" header, and an encoded body.

#### Actual behavior

The function returns a raw body.

Response to example request:
```
HTTP/1.1 200 OK
Cache-Control: public, max-age=604800
Content-Length: 2808
Content-Type: image/png
Last-Modified: Fri, 05 Oct 2018 07:50:24 GMT
ETag: "0x8D62A973585D1AA"
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
Date: Thu, 24 Jan 2019 11:44:01 GMT
```

#### Known workarounds

There are no known workarounds.

#### Related information 

The function is created in the portal with the following source:

<details>
<summary>function.json</summary>

```json
{
  "bindings": [
    {
      "authLevel": "anonymous",
      "name": "req",
      "type": "httpTrigger",
      "direction": "in",
      "methods": [
        "get"
      ],
      "route": "Logo/{shop}"
    },
    {
      "name": "$return",
      "type": "http",
      "direction": "out"
    }
  ],
  "disabled": false
}
```
</details>

<details>
<summary>run.csx</summary>

```csharp
#r "Microsoft.AspNetCore.Http.Extensions"
#r "Microsoft.Extensions.Configuration"
#r "Microsoft.Extensions.Configuration.Abstractions"
#r "Microsoft.Extensions.Configuration.EnvironmentVariables"
#r "Microsoft.WindowsAzure.Storage"
#r "Newtonsoft.Json"

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Net.Http.Headers;
using Microsoft.WindowsAzure.Storage;
using System;
using System.Linq;
using System.Threading.Tasks;

public static async Task<IActionResult> Run(HttpRequest req, string shop, ILogger log)
{
    shop = shop.ToLowerInvariant().Trim();

    var configBuilder = new ConfigurationBuilder();
    configBuilder.AddEnvironmentVariables();
    var configuration = configBuilder.Build();
    var azureAccount = CloudStorageAccount.Parse(configuration.GetConnectionString("BlobStorage"));
    var blobClient = azureAccount.CreateCloudBlobClient();

    var fileRef = blobClient.GetContainerReference("files")
        .GetDirectoryReference("storage")
        .GetDirectoryReference(shop)
        .GetBlockBlobReference("logo.png");

    if(!await fileRef.ExistsAsync())
    {
        log.LogError($"logo.png not found on storage in folder: {shop}!");
        return new ContentResult() { Content = "Not found", ContentType = "text/plain", StatusCode = 404 };
    }

    return await _blobResult(fileRef, req.HttpContext, new MediaTypeHeaderValue("image/png"));
}

private static async Task<IActionResult> _blobResult(Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob blockBlob, HttpContext context, MediaTypeHeaderValue mediaTypeHeader)
{
    await blockBlob.FetchAttributesAsync();

    bool notModified = false;

    var typedRequestHeaders = context.Request.GetTypedHeaders();
    if (typedRequestHeaders.IfNoneMatch != null && typedRequestHeaders.IfNoneMatch.Any(m => m.Tag == blockBlob.Properties.ETag))
        notModified = true;
    if (typedRequestHeaders.IfModifiedSince != null && typedRequestHeaders.IfModifiedSince != blockBlob.Properties.LastModified)
        notModified = true;

    var typedResponseHeaders = context.Response.GetTypedHeaders();
    typedResponseHeaders.CacheControl = new CacheControlHeaderValue
    {
        Public = true,
        MaxAge = TimeSpan.FromDays(7)
    };
    if (!string.IsNullOrEmpty(blockBlob.Properties.ETag))
        typedResponseHeaders.ETag = new EntityTagHeaderValue(blockBlob.Properties.ETag);
    if (blockBlob.Properties.LastModified != null)
        typedResponseHeaders.LastModified = blockBlob.Properties.LastModified;

    if (notModified)
        return new StatusCodeResult(304);
    else
        return new FileStreamResult(await blockBlob.OpenReadAsync(), mediaTypeHeader);
}
```
</details>

**Comment by ishepherd** [comment]
@synercoder Does your raw response have an incorrect `Content-Encoding: gzip` header?
That's what I'm seeing.

----

Functions Team - ASP.NET Core has middleware for transparent compression. If you're setting it up yourself (in a web app) you have the option to plug these in to the request handling pipeline. Can we get access to this pipeline in the functions host?

**Comment by synercoder** [comment]
@ishepherd I don't think you understood my post, the postman issue you linked was an issue about that the "Accept-Encoding" header was send without the author setting that header.

My issue is: The header is send, but Azure Functions doesn't reply with a "Content-Encoding" header.

For example, a request to another server which does implement gzip encoding:

Request (note the Accept-Encoding header):
```
GET / HTTP/1.1
Host: www.printapi.nl
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,nl;q=0.8,en-GB;q=0.7,de;q=0.6
```

Response (again note the Content-Encoding header):
```
HTTP/1.1 200 OK
Cache-Control: private,public
Content-Type: text/html; charset=utf-8
Content-Encoding: gzip
Vary: Accept-Encoding
Date: Fri, 01 Feb 2019 08:11:54 GMT
Content-Length: 4728
```

**Comment by synercoder** [comment]
Working in latest azure functions online (did not change anything on my side). Seems fixed.

**Comment by jjxtra** [comment]
HttpClient eats content-length and content-encoding headers, you can find them if you debug and inspect the httpclient and go to the Content property, and find the _originalContent private variable.
