### ISSUE TITLE
Lots of admin/host/ping HTTP 405 errors in /LogFiles/DetailedErrors

### ISSUE THREAD

**Issue by artemious7** [Azure/azure-functions-host#4001]
#### Investigative information

- Timestamp: **Jan 15, 2019 until Jan 23, 2019, 21:56 UTC**
- Function App version (1.0 or 2.0): **1.0**
- Function App name: **jwtelegabotbeta**
- Function name(s) (as appropriate): -
- Invocation ID: -
- Region: **North Europe**

#### Repro steps

Enable detailed logging in the Function app
1. Go to Function app portal on Azure. 
2. "Platform features" tab. Go to Resource Explorer. 
3. Expand "config" section
4. Click "logs". Properties section is set as follows:
    "properties": {
        // ... other properties are listed below - in Details
    "detailedErrorMessages": {
      "enabled": true
    }

the **detailedErrorMessages** property is **enabled**

#### Expected behavior

I don't expect _many_ irrelevant to my code _errors_ appearing in logs. I don't expect any errors at all, actually.

#### Actual behavior

I go to FTP of the Function app. Navigate to /LogFiles/DetailedErrors
Over time I see many files created
![image](https://user-images.githubusercontent.com/16724889/51692549-d1e6cd00-2005-11e9-8822-a0d01a2c7105.png)

I noticed that the files are created with this pattern:
1 file in 2 minutes
3 files per 1 min
6 files per 1 min
and it repeats

The content of the error log file is all the same:
![image](https://user-images.githubusercontent.com/16724889/51692849-6ea96a80-2006-11e9-8fee-0a92104aca9e.png)

This folder auto-erases older files, so I can see only around 20 recent files.

#### Known workarounds

The workaround is to disable detailed logging to file system. 

#### Related information 

I don't understand where do the requests to ping endpoint come from. And why they are wrong.
As a result, **I pay a few times more** for this _simple_ Function app because each File write operation is billed. This happens not only in this app, but here the cost is noticeable. I didn't see this before Jan 15, 2019, maybe because of lower costs (meaning less file write operations of the log files). I was working with the app this day and previous days, by I didn't anything to /admin/host/ping, so I don't know why suddenly this problem began. 
Also it took me much time to discover the source of sudden costs raise. It was not an obvious thing to look into the log files, and it is still a mystery for me - how this is related to the /admin/host/ping API.

* Programming language used C#

<details>

```json
"properties": {
    "applicationLogs": {
      "fileSystem": {
        "level": "Off"
      },
      "azureTableStorage": {
        "level": "Off",
        "sasUrl": null
      },
      "azureBlobStorage": {
        "level": "Off",
        "sasUrl": null,
        "retentionInDays": null
      }
    },
    "httpLogs": {
      "fileSystem": {
        "retentionInMb": 35,
        "retentionInDays": null,
        "enabled": false
      },
      "azureBlobStorage": {
        "sasUrl": null,
        "retentionInDays": null,
        "enabled": false
      }
    },
    "failedRequestsTracing": {
      "enabled": false
    },
    "detailedErrorMessages": {
      "enabled": true
    }

```
<summary>Resource Explorer: other properties of config.logs </summary>

</details>

**Comment by kashimiz** [comment]
Hi @artemious7, apologies for the delayed response. Are you still experiencing this issue if you turn detailedLogging back on? If so, can you also look at your HTTP logs to get the client IP address of these requests?

**Comment by artemious7** [comment]
I reenabled it and will wait for result. Thanks for your reply

**Comment by artemious7** [comment]
I checked. No, I am not experiencing this issue when I turn detailedLogging back on. Thanks
