### ISSUE TITLE
Azure function referencing a project with System.Net.Http - compilation failure - version mismatch

### ISSUE THREAD

**Issue by nidewa** [Azure/azure-functions-host#4010]
Hi team,

I am seeing a strange behavior while working on an Azure function.

Project 1 – Web API project (target framework - .NET 4.6.1) that has reference to System.Net.Http version from the VS2017 build extension path as below

 
![p1](https://user-images.githubusercontent.com/29931952/51734669-12f8d480-203a-11e9-92bb-0fce657df022.png)

Project 2 – Azure Function (target framework - .NET 4.6.1) that has a project reference to Project 1. If I try to point access any System.Net.Http class in this project, it refers to default nuget package path as below:

 
![p2](https://user-images.githubusercontent.com/29931952/51734704-2b68ef00-203a-11e9-85f0-a1431efbba9a.png)

On compilation I am getting an error: 
CS1705  Assembly 'Project1' with identity 'Project1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Net.Http' with identity 'System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

I couldn’t find any way to specify same path for assembly in both these projects, nor I couldn't find a way to set the binding redirect in Azure function

Any idea/pointers to resolve this error would be great. It’s really blocking our development and project deliverable.

<b>Temp Workaround</b>: Rename the System.Net.Http file to some other name in the MSBuild extension path. Now I am able to compile, run it locally and deploy to Azure manually.
However, the Azure Dev Ops Build fails with the same error while compiling the solution.

**Comment by fabiocav** [comment]
@nidewa do you have an explicit NuGet package reference for both of those projects?
