### ISSUE TITLE
ILB ASE deployment: "The Function Runtime is Unable to Start"

### ISSUE THREAD

**Issue by CreditDataResearch** [Azure/azure-functions-host#4011]
Cross-posted from https://stackoverflow.com/questions/54351036/what-would-prevent-the-azure-function-runtime-from-starting-in-an-ilb-ase-deploy/54358222#54358222

- ILB ASE with function app.
- JumpBox configured with the custom domain in its HOSTS file and set up to trust my self-signed certificate for both the _function.custom_ and _function.scm.custom_ domains
- Function storage accessible
- CORS set to * for testing
- Kudu console for the function app accessible with deployment credentials
- But accessing function url returns `Function host is not running`

And there is a popup error:
![image](https://user-images.githubusercontent.com/47025186/51734785-6e988180-207d-11e9-9002-958d029d273a.png)

And another:
![image](https://user-images.githubusercontent.com/47025186/51736996-693e3580-2083-11e9-9b6d-df5e880c177c.png)

Multiple 500 and 503 errors in the F12 Dev Console

Please provide the following:

- Timestamp: 2019-01-25T09:25:12.567Z
- Function App version (1.0 or 2.0): 2.0
- Function App name: ratings
- Function name(s) (as appropriate): GetRating
- Invocation ID: **Session ID**  b7d7410324a748d1b85277b10d5b79d2
- Region: UK South (Isolated ILB ASE)

Expected behaviour is to be able to test the function in the portal from the JumpBox.

Fails due to errors shown above in portal.

**Comment by tohling** [comment]
@CreditDataResearch, thank you for opening the issue. I will investigate and update the thread when I have more information.

**Comment by kashimiz** [comment]
@CreditDataResearch, are you still experiencing this issue?
