### ISSUE TITLE
Add retries when downloading blob contents during specialization

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-host#4017]
Accessing the zip from storage blob fails with 
System.Net.Http.HttpRequestException : Resource temporarily unavailable ---\u003e System.Net.Sockets.SocketException : Resource temporarily unavailable

  Need the retry in 2 places. 

https://github.com/Azure/azure-functions-host/blob/986f6fe60d6017ed11a74fe7ebace29e7b5120d2/src/WebJobs.Script.WebHost/ContainerManagement/LinuxContainerInitializationHostService.cs#L89

https://github.com/Azure/azure-functions-host/blob/9b7c0fa24b604a9c840415247a97944967c78300/src/WebJobs.Script.WebHost/Management/InstanceManager.cs#L88

**Comment by fabiocav** [comment]
@balag0 this issue was opened back in January, is this still applicable?
