### ISSUE TITLE
EventGridExtension can return 404 if called before host is fully started

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#4021]
Similar to #3825, but opening a new issue to reduce confusion.

Note that this affects v1 and v2.

Specifically, the EventGrid extension can return a 404 on the initial request if the host is only `Initialized` and not yet `Started`. My notes from the incident:

------
 This looks like a race in the EventGrid extension. For this specific incident (https://icm.ad.msft.net/imp/v3/incidents/details/101998394/home) -- they see the same thing with App Service Plan, so it’s not related to host specialization: 
- Function app is deployed on V1 and using consumption plan , also can reproduce the issue on app service plan.

I’m seeing this log on some of the first requests to a newly-started host: `cannot find function:  'DevicePacketMonitor', available function names: []`

That’s followed by a 404. Then, subsequent requests succeed and are correctly routed to DevicePacketMonitor.

That log comes from here: https://github.com/Azure/azure-functions-eventgrid-extension/blob/v1.x/src/EventGridExtension/EventGridExtensionConfig.cs#L63  

It looks like the list of available functions is initialized in the listener’s StartAsync() method: https://github.com/Azure/azure-functions-eventgrid-extension/blob/v1.x/src/EventGridExtension/EventGridListener.cs#L23.

Could Http requests be getting routed to the ProcessAsync method *before* all listeners are actually started? I’m not sure how the EventGrid flow works…

------

I bet that’s it. Our WebHook routing has `[RequiresRunningHost]`
-	https://github.com/Azure/azure-functions-host/blob/v1.x/src/WebJobs.Script.WebHost/Controllers/AdminController.cs#L213

But that only guarantees that the host has been *Initialized* -- not that it’s necessarily running or that listeners have been started:
-	https://github.com/Azure/azure-functions-host/blob/v1.x/src/WebJobs.Script.WebHost/Filters/RequiresRunningHostAttribute.cs#L37
-	https://github.com/Azure/azure-functions-host/blob/v1.x/src/WebJobs.Script.WebHost/WebScriptHostManager.cs#L474
-	https://github.com/Azure/azure-functions-host/blob/v1.x/src/WebJobs.Script/Host/ScriptHostManager.cs#L145-L148
-	https://github.com/Azure/azure-functions-host/blob/v1.x/src/WebJobs.Script/Host/ScriptHostManager.cs#L443-L450

With the current design of the EventGridExtension, it looks like we cannot try to invoke it until the listener has been started. If we do, we get a 404 on that first invocation.

**Comment by jcbrooks92** [comment]
Is there a workaround in the meantime to get past this error? We have one more occurrence of this on a v2 function with similar symptoms.

**Comment by mathewc** [comment]
The fix for this was v1 only - no changes were made for v2, because based on my analysis the issue I fixed for v1 didn't exist for v2. 

In v2 we have [RequiresRunningHost] applied to the route, and that requires the host to be at least Initialized. However, the value ScriptHostState.Initialized is not used anywhere in the v2 codebase, so we don't ever set State to Initialized, meaning we don't let WebHooks through until AFTER the listeners are started.

However the fact that we're not setting Initialized is a problem/inconsistency on its own which should be fixed, since it can result in unecessary cold start invocation delays.

**Comment by mathewc** [comment]
Addressed by the fixes for https://github.com/Azure/azure-functions-host/issues/3825.

@jcbrooks92 likely the issue you're seeing is a different issue.
