### ISSUE TITLE
Handle jobhost restarts on specialization even if jobhost is in middle of restarting

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#4022]
If a call for specialization comes while the jobhost is restarting,  site continues to use placeholder content instead of user site content.

This results in 404s on any httptriggers if worker runtime is not set. 503s if worker runtime is set to any language other than dotnet as we explicitly throw HostInitialization exception if there are no functions that match worker runtime.

**Comment by mathewc** [comment]
Potentially related to https://github.com/Azure/azure-functions-host/issues/4015? @balag0 tested and verified that it seems this regressed recently.
