### ISSUE TITLE
Log function metadata at host startup for better ScaleController correllation

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#4039]
Right now the ScaleController logs trigger details in JSON whenever it syncs a trigger. It's difficult to correlate that to what the host sees because we don't explicitly write any of these details in the host logs. If we wrote a very similar JSON string out for each trigger we have at host startup (and perhaps all function metadata), it would make it much easier to write a detector and alert customers when they need to run "sync triggers".

**Comment by fabiocav** [comment]
According to @mathewc, this might have been done with the recent sync triggers work. @brettsam may just need to validate

**Comment by mathewc** [comment]
Whenever we sync triggers (direct call or background) we log the sync payload [here](https://github.com/Azure/azure-functions-host/blob/71a6ab35770c33165f1543c51397013d0446a32f/src/WebJobs.Script.WebHost/Management/FunctionsSyncManager.cs#L358).

**Comment by brettsam** [comment]
@FinVamp1 -- were you working on the ScaleController-related detector? Would the payload here work for that?

**Comment by FinVamp1** [comment]
@Brettsam will look and verify by next week.

**Comment by mathewc** [comment]
Be aware that the format of this log will be changing. Currently it is an array of triggers, but after https://github.com/Azure/azure-functions-host/pull/4145 is activated, it can also be an object.

**Comment by brettsam** [comment]
Gonna go ahead and close this as it looks like everything we need is there. @FinVamp1 -- feel free to open back up if that's not the case.
