### ISSUE TITLE
[V2] Azure Functions runtime tries to link wrong assembly version

### ISSUE THREAD

**Issue by Volwerston** [Azure/azure-functions-host#4045]
Hello,

In my FunctionApp1 project I am referencing class library Common.Infrastructure.HealthCheck, which is referencing NuGet package Microsoft.AspNetCore.Diagnostics.HealthChecks 2.2.0-preview2-35157.

FunctionApp1.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.24" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common.Infrastructure.HealthCheck\Common.Infrastructure.HealthCheck.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

Common.Infrastructure.HealthCheck.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Common.Infrastructure.HealthCheck</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.HealthChecks" Version="2.2.0-preview2-35157" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
  </ItemGroup>
</Project>
```

host.json
```json 
{
    "version": "2.0"
}
```
local.settings.json
```json
{
    "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=true",
        "FUNCTIONS_WORKER_RUNTIME": "dotnet"
    }
}
```

When I call HTTP-triggered Function1 locally, I am receiving following error message:
[2/4/2019 4:38:50 PM] Executed 'Function1' (Failed, Id=b0850d79-f72d-45f3-9228-d1d669059e3e)
[2/4/2019 4:38:50 PM] System.Private.CoreLib: Exception while executing function: Function1. FunctionApp1: Could not load type 'Microsoft.Extensions.Diagnostics.HealthChecks.HealthCheckStatus' from assembly 'Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

When I opened bin directory, I found Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions.dll with version 2.2.0-preview2-35157.
However, looks like runtime is searching for version 2.2.0.0 instead of 2.2.0-preview2-35157. 
Can you think of any workaround for this issue?

UPD:
Microsoft.Extensions.Diagnostics.HealthChecks depends on Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions. However, as you see, Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions has version 2.2.0-preview2-35157, not 2.2.0.0, as the error message states.
![image](https://user-images.githubusercontent.com/15079159/52223873-4ac01180-28af-11e9-91b1-e0a47c23f12d.png)

**Comment by dallancarr** [comment]
Do you have the latest runtime on your local?

**Comment by Volwerston** [comment]
@dallancarr 

My current Azure function runtime is 2.0.12285.0:
![image](https://user-images.githubusercontent.com/15079159/52234574-ab107c80-28ca-11e9-8ea8-93d4830a3744.png)

Looks like this is quite similar issue: https://github.com/Azure/Azure-Functions/issues/801, but they say that the problem is fixed for Azure functions 2.x

**Comment by dallancarr** [comment]
Certainly feels like we are mixing versions here or unsupported. But functions supports 2.x but health checks is a 2.2 feature. So maybe get off preview or target netstandard.

**Comment by Volwerston** [comment]
The same problem remains when I target netstandard2.0 in my Azure function app.
However, when I removed reference to Common.Infrastructure.HealthCheck and directly referenced Microsoft.AspeNetCore.Diagnostics.HealthChecks 2.2.0.0 in function app, it actually worked!
The problem is that I reference my library Common.Infrastructure.HealthCheck in another web app which targets netcoreapp2.1, and it does not support Microsoft.AspeNetCore.Diagnostics.HealthChecks 2.2.0.0, only preview version.
Is there anyway to explicitly tell Azure function runtime which version of assembly to load?
Maybe some function.json configuration can be helpful.

**Comment by Volwerston** [comment]
I added sample Azure function with preview package in order to reproduce the issue: https://github.com/Volwerston/AzureFunction_WrongAssemblyIssue_Reproduce

Steps to reproduce:
1. Run function app from VS 17 in debug mode (F5)
2. Call 'http://localhost:7071/api/Function1' from your browser

Expected behaviour:
1. Plain text "Health check result: Healthy" should be returned

Actual behaviour: 
1. Internal Server Error (500) is returned
2.  Exception is thrown
System.Private.CoreLib: Exception while executing function: Function1. FunctionApp1: Could not load type 'Microsoft.Extensions.Diagnostics.HealthChecks.HealthCheckStatus' from assembly 'Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**Comment by DAllanCarr** [comment]
Can not reproduce from vscode. so not sure if this vs specific.  Using rtm 2.2.100 and tools version 2.4.317
