### ISSUE TITLE
Set up the extension manager endpoints to resolve the extensions from extension bundle.

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#4061]
Portal uses extension management API's to call List, Install and Uninstall Extensions through extension manager API. Update the host to use extension bundle as the source for these operations.
- Get should list all the extensions in the bundle
- delete should return 400
- post / put should return 409

**Comment by jeffhollan** [comment]
Is this a must have to ship bundles? Also could use a description on what functionality this will provide

**Comment by soninaren** [comment]
@jeffhollan have update the description to accurately capture the expected behavior. The work needed for this is minimal in nature and i already have a PR open for change.
