### ISSUE TITLE
Support for configuring HSTS

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#4069]
HSTS is typically enabled via web.config settings, which is not possible in the case of Azure Functions. Perhaps it would make sense to expose this as a configurable functions setting? It looks like there is ASP.NET Core middleware that could be used by the functions runtime, see:
https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio#http-strict-transport-security-protocol-hsts

**Comment by paulbatum** [comment]
Lets use sprint 47 to evaluate whether this is straightforward to implement.

**Comment by fabiocav** [comment]
Work in PR, this will not make sprint 49.
