### ISSUE TITLE
Linux timer-triggered function stopped firing

### ISSUE THREAD

**Issue by maiqbal11** [Azure/azure-functions-host#4073]
_From @swt2c on February 11, 2019 14:28_

I have a Linux (Python) function that is timer triggered to fire once an hour on the :15 mark:
`"schedule": "0 15 * * * *"`

This was working fine until 2019-02-09 00:15:00.217, but the timer has not fired since.  Is this a known issue?

_Copied from original issue: Azure/Azure-Functions#1124_

**Comment by swt2c** [comment]
It fired again at 2019-02-11 21:15:00.104.  Something seems very wrong here.

**Comment by swt2c** [comment]
Ping.  It sure would be good if someone could investigate this.

**Comment by swt2c** [comment]
Magically, my function seems to have started firing again at `2019-02-15 05:15:00.030`

**Comment by gbowerman** [comment]
+1 My scheduled app designed to run at 8am UST (midnight PST) failed to run (2/27/19). Manual trigger from portal today was successful.
Project name: guyfunc
Function name: twitreport

**Comment by balag0** [comment]
@swt2c Is this still happening? Could you share the appname. 

@gbowerman I don't see a app named guyfunc anymore. Were you able to deploy to a different app? If you are still seeing this issue, please share the appname.

**Comment by swt2c** [comment]
@balag0 yes.  I have two apps that are still unreliable: `nexrad-updater` and `usgs-updater`.

**Comment by gbowerman** [comment]
@balag0 I tore down app and rebuilt it after latest functions runtime came out. No timer tigger issues so far.

**Comment by balag0** [comment]
@gbowerman thanks for confirming.

@swt2c There was a transient issue in the platform causing failures with the site usgs-updater. Its been fixed since yesterday and I don't see any failures with that site in the last 24h. Please update if you see any more issues.
I am still investigating the issue with nexrad-updater and will provide an update soon.

**Comment by balag0** [comment]
@swt2c I dont see any more errors with nexrad-updater for the last 2 days. I opened an issue to track the bug you were hitting earlier - https://github.com/Azure/Azure-Functions/issues/1144

Let me know if you are still seeing this/ any other issue.

**Comment by swt2c** [comment]
@balag0 nexrad-updater hasn't fired since 3/6 at 22:00 and it only fired once on 3/6.

**Comment by swt2c** [comment]
![screenshot from 2019-03-07 20-37-09](https://user-images.githubusercontent.com/971544/54001307-d3cda100-4118-11e9-86b5-71a7fb7d7cc1.png)

**Comment by dariagrigoriu** [comment]
No repro, closing for now.
