### ISSUE TITLE
Optimize grpc to get rid of a throughput bottleneck 

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-host#4076]
We are using a bidirectional streaming RPC which cause a bottleneck on writing to response steam:
https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/FunctionRpcService.cs#L59

Here is documentation on how to optimize grpc: https://grpc.io/blog/optimizing-grpc-part-1 which can be helpful

**Comment by pragnagopa** [comment]
Relevant discussion: https://groups.google.com/forum/#!topic/grpc-io/FKeg4yfB-Jo

**Comment by pragnagopa** [comment]
grpc bechmark tests: https://github.com/grpc/grpc/tree/master/src/csharp

**Comment by pragnagopa** [comment]
Here is the current the baseline measured with tool [WCAT](https://www.iis.net/downloads/community/2007/05/wcat-63-x86) with a simple HttpTrigger

**C#**
```
 Duration : 60
 RPS(spot): 164
 RPS(avg): 148
 Status_200: 8934
 Status_3xx: 0
 Status_4xx: 0
 Status_5xx: 0
 Average Response Time: 670
```

**Java Script**
```
 Duration : 60
 RPS(spot): 82
 RPS(avg): 71
 Status_200: 4315
 Status_3xx: 0
 Status_4xx: 0
 Status_5xx: 0
 Average Response Time: 1285
```

**Java**
```
 Duration : 60
 RPS(spot): 77
 RPS(avg): 61
 Status_200: 3694
 Status_3xx: 0
 Status_4xx: 0
 Status_5xx: 87
 Average Response Time: 1585
```

Average response time for JavaScript or Java is almost double the response time for a C# function.

**Comment by pragnagopa** [comment]
Here is a related issue describing the flow the control https://github.com/grpc/grpc/issues/18205, if messages are not read from the channel at some point grpc will start blocking the writes.

**Comment by pragnagopa** [comment]
PR - https://github.com/Azure/azure-functions-powershell-worker/pull/214 addresses throughput issue with powershell functions.

**Comment by pragnagopa** [comment]
Moving to next sprint as this is an ongoing investigation.

**Comment by fabiocav** [comment]
Assigning this to 52. This will likely become an epic and broken down into smaller tasks.

**Comment by pragnagopa** [comment]
cc @amamounelsayed

**Comment by fabiocav** [comment]
Closing this as @mgravell is working on a number of gRPC/worker communication improvements.
