### ISSUE TITLE
Error: OK - https://functions.azure.com/api/passthrough

### ISSUE THREAD

**Issue by christyharagan** [Azure/azure-functions-host#4081]
Hi all,

I have created a new Functions App (Windows, Consumption plan, UK South). I then tried to create a new function and it threw an error: Error: The function runtime is unable to start.

Looking at previous issues reporting this error I followed the steps to check the runtime version: I go to "Function App Settings" and now I get a new error (described in the title of this issue) and the "Runtime version" never loads (instead it gets stuck at "Loading")

My Function name is "finygo-v3-dev". I have no other resources set-up on my account, no IP restrictions, nothing. This is a clean subscription and I have only performed the above steps.

(If it helps, I did try starting off with a Linux version of the Functions App, and that also bombed out straight away, so I deleted everything, and switched to Windows assuming a lack of maturity on the Linux version).

**Comment by fabiocav** [comment]
@maiqbal11 can you please investigate and route?

**Comment by maiqbal11** [comment]
Was the Function App created through Portal, VSCode, Visual Studio or Core Tools?

**Comment by christyharagan** [comment]
@maiqbal11 

I tried re-creating them, and it seems to work now. I followed exactly the same steps (created via the portal) and now it works. Tried different region, then the same.

I can only assume it was a transient error. So closing. Thanks!

**Comment by user0604** [comment]
I'm having the same problem stated in the topic, i.e. 
> Error: The function runtime is unable to start 
and 
> Error: OK - https://functions.azure.com/api/passthrough
messages are displaying as popups.

My situation doesn't allow me to recreate the Function app (it's loaded with settings out of my scope, and more importantly, company policy). The app was created on portal, then I imported it into VS, do the coding locally, then publish back to Azure. The code and code-based settings of it is extracted from another Function App that is running perfectly on the same sub, same storage acc.

I have no problem with setting the App version, but my problem is that the Function App won't run manually or automatically (on timer trigger). I have to make it run and take the log. Anyone has an idea how I can make this disappear?
