### ISSUE TITLE
Azure functions not triggering

### ISSUE THREAD

**Issue by yoliva** [Azure/azure-functions-host#4088]
Hi, we have a bunch of AzureFunctions (v1) deployed about 4months ago and everything was working ok until yesterday. For some reason, the azure functions stop being triggered by the scheduler. When we restart the functions directly in the portal or make a re-deployment everything works ok for about 45 minutes. Not sure what's the cause of the issue. We haven't deployed an update in the last 4 months.

#### Expected behavior
I would expect the functions to run every X minutes (each one has a different cron expression)

#### Actual behavior
The functions does not run unless I restart in the portal or redeploy the functions

**Comment by swt2c** [comment]
I'm seeing my functions not firing also, see #4073.

**Comment by yoliva** [comment]
@swt2c any luck so far?

**Comment by swt2c** [comment]
Unfortunately not.  One of my functions has been running for over a week.  It is supposed to fire once an hour but it has only fired 4 times.  :(  We really need someone from Microsoft to look into this.

**Comment by ielcoro** [comment]
Could be related to #4152 ? We solved a similar problem by following the instructions there.

**Comment by mhoeger** [comment]
@yoliva - Are you still having this issue? If so, can you share your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by hannmtz85** [comment]
we still having this issue, any of the guys know haw to resolve it???

**Comment by yoliva** [comment]
we will provide indirectly our function name so you can investigate this further

**Comment by hannmtz85** [comment]
@mhoeger this is the info that you asked to @yoliva 

```
Subscription: ba90...7266
Site: lab...ons
```

**Comment by mhoeger** [comment]
@hannmtz85 - Are your functions not being triggered except when you navigate to the portal as the issue describes? On our end, we see 4 functions always succeed and 6 functions failing intermittently. In particular, we see this exception message: `A task was canceled. at FunctionsApp.Shared.LHApi.ExecuteRequest(String url)`

If it is a separate issue, please open a new one.

For everyone looking at this issue too, I suggest going to the Azure Portal => Platform features => Diagnose and solve problems => Availability and Performance for some helpful diagnostic dashboards
