### ISSUE TITLE
V2 ScriptHost not applying ScriptHostState.Initialized

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#4095]
In working on my fix for https://github.com/Azure/azure-functions-host/issues/3825, I realized that this issue doesn't exist in v2 due to the fact that v2 isn't setting State to Initialized when it should be. We should fix this, since this can result in cold start first request delays, based on the way [RequiresRunningHost] works.

[RequiresRunningHost] requires the host to be at least Initialized. However, the value ScriptHostState.Initialized is not used anywhere in the v2 codebase, so we don't ever set State to Initialized, meaning for example that we don't let WebHooks through until AFTER the listeners are started.

Ideally we should fix this, and also apply the same fixes for made for https://github.com/Azure/azure-webjobs-sdk/pull/2104 to v2.

**Comment by paulbatum** [comment]
This was fixed in 2.0.12763
