### ISSUE TITLE
Do not track jobhost language worker channels in LanguageWorkerChannelManager

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#4104]
Problem: CRI  ICM# 104918155
During rapid JobHost restarts, which happens if a function is pinged while function app is being deployed, node language worker is not restarting as part of jobhost restarts. This results in timeout exceptions for all the function invocations because node process is not running.

Root cause:
LanguageWorkerChannelManager keeps track of language worker channels started at the application level here: [LanguageWorkerChannelManager.cs#L206](https://github.com/Azure/azure-functions-host/blob/b99edf799d532304ddcf4fd37328f0289594d512/src/WebJobs.Script/Rpc/LanguageWorkerChannelManager.cs#L206).

This list should not track language worker channels started inside the jobhost here: [FunctionDispatcher.cs#L62](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/FunctionRegistration/FunctionDispatcher.cs#L62)

Commit #[47e51dfc83e9730389d981a534d995b6a028179f](https://github.com/Azure/azure-functions-host/commit/47e51dfc83e9730389d981a534d995b6a028179f) was added to track all the processes started by the host. This had the side affect for tracking language worker channels started in jobhost layer in langaugeworkerchannel manager. This resulted in node process not restarting as part of JobHost restarts.

**Comment by pragnagopa** [comment]
cc: @mhoeger

**Comment by Bomret** [comment]
This should hopefully also help with Javascript-based functions? Because currently our function apps die regularly with (node exited with exit code -1) when a function is triggered during or shortly after deployment.

**Comment by fabiocav** [comment]
Resolved by #4102
