### ISSUE TITLE
Do not dispose webhost language worker channels as part of JobHost restart

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#4105]
Problem: CRI ICM# 104731378
During rapid JobHost restarts:
- Function is pinged while function app is being deployed,
- Application is starting and setting up java language worker
- Multiple jobhost restarts are triggered as part of the deployment.
- Java Language worker channel started at the webhost level gets disposed
- Call to function invocation results in timeout

Root cause:
Java process disposed but the LanguageWorkerChannelManager's state is not cleaned up. [FunctionDispatcher.cs#L102](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/FunctionRegistration/FunctionDispatcher.cs#L102) uses orphaned language worker channel even though it is disposed

[FunctionDispatcher.cs#L193](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/FunctionRegistration/FunctionDispatcher.cs#L193) should not dispose webhost channel.

Note: This only reproes when the file system is being rapidly updated while the application is trying to start up.

**Comment by pragnagopa** [comment]
Fixes #4104 , Fixes #4105

**Comment by fabiocav** [comment]
Resolved by #4102
