### ISSUE TITLE
Missing FunctionName in some logs

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#4113]
There are a few areas where "FunctionName" is missing from our logs:
 - where Source contains "Host.Triggers.Timer"
 - where Source contains "Script.Host" and where Summary contains "updated status: Last="
 - where Summary contains 'functions are in error' and Summary contains ".Run"

**Comment by brettsam** [comment]
If we wrap wrap Trigger.StartAsync() with a logging scope that injects the function name, that should allow FunctionName to be added during startup.

**Comment by jeffhollan** [comment]
I believe I may have created a dupe of this one in regards to analytics work as well:
https://github.com/Azure/azure-functions-host/issues/4745

**Comment by fabiocav** [comment]
@jeffhollan I don't believe your issue covers all the cases mentioned here, so I'm keeping this open, but given the fact this has been moving for a while, it would be good to understand whether we need to break this up and close this issue.

**Comment by fabiocav** [comment]
@brettsam thoughts?

**Comment by fabiocav** [comment]
Closing as resolved.
