### ISSUE TITLE
system key not generated for linux event grid function

### ISSUE THREAD

**Issue by JohnReeson** [Azure/azure-functions-host#4125]
#### Repro steps

1. Create a c# event grid function using CLI 2.4.317
2. Build the image and push it to Azure container registry
3. Create a function app on OS linux with the custom image
4. Get system key for creating subscription, according to the [doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid#get-the-system-key).

#### Expected behavior

See sysetm key in response

#### Actual behavior

See 404 NOT FOUND

See `"systemKeys":[]` in host.json under `azure-webjobs-secrets`

#### Known workarounds

Use master key to create subscription instead.

### Related Info

For eventgrid functions on windows service plan, system keys are generated as expected.

**Comment by alrod** [comment]
@ahmelsayed, is it known issue?

**Comment by ahmelsayed** [comment]
I don't know. Who creates that key? would you expect it to work differently based on the OS?

**Comment by alrod** [comment]
> I don't know. Who creates that key? would you expect it to work differently based on the OS?

@JohnReeson, said: For eventgrid functions on windows service plan, system keys are generated as expected.

**Comment by ahmelsayed** [comment]
Doesn't really answer my questions. Can you try it on linux and see if it works as expected since this issue is from February?

**Comment by alrod** [comment]
@JohnReeson, are you still experiencing the issue?
