### ISSUE TITLE
Functions V2 .net core Timer Trigger Executes After App Stop

### ISSUE THREAD

**Issue by mwwski** [Azure/azure-functions-host#4128]
I've noticed that at some times after stopping Azure Function another instance is created that continues to execute the timer function. This instance stops after approx 20 minutes. At first I've assume it was due to me upgrading the app to .net Core 2.2 but after downgrading to 2.1 the issue persisted.

#### Investigative information
- Timestamp: 18:58:58
- Function App version: 2.0
- Function App name: FunctionApp120190222062649
- Function name(s) (as appropriate):
- Instance ID: 20326fba7b0b24b00085d3d90c9d455a
- Region: UK West

#### Repro steps

1. Create a new Azure Functions V2 project with Timer Triggered Function.
2. Deploy to a Consumption Plan App.
3. Stop the App from the portal

#### Expected behavior

The App stops and the function host stops execution of all timed functions.

#### Actual behavior

The App stops but a new host is created that continues to execute timed function. The host stops on it own after approx. 20 minutes.

![af](https://user-images.githubusercontent.com/5913470/53265883-35cce600-36d7-11e9-9dbc-e9ba6aba634f.PNG)

**Comment by alrod** [comment]
@mwwski, are you still experiencing the issue with the latest function runtime?

**Comment by mwwski** [comment]
@alrod I'm not seeing this behavior any more.

**Comment by alrod** [comment]
The issue was already fixed in new function runtime 2.0.
