### ISSUE TITLE
Visual studio template Deployment Requires extension installation 

### ISSUE THREAD

**Issue by MegoCs** [Azure/azure-functions-host#4131]
I have created azure function from Visual studio template in V2 
with service bus queue trigger and i works locally when deploying this project to azure and visit function portal it gives me an error says "Error: The binding type(s) 'serviceBusTrigger' are not registered. Please ensure the type is correct and the binding extension is installed."

#### Investigative information

Please provide the following:

- Timestamp: 2019-02-23T15:27:13.071Z
- Function App version 2.0:
- Function App name: FunctionAppTest3
- Function name(s) Function1:
- Invocation ID:
- Region: west Europe  

#### Repro steps

Provide the steps required to reproduce the problem:

1. open visual studio create new project Azure Function -> V2 service bus trigger 
2. validate connection strings ..etc , run the project locally -.>> it runs correctly with me 
2. publish it to azure 

#### Expected behavior

the function expected to start listening for the queue but it's not . 
the function app url says the function is working
but navigating to the function in azure portal shows an error related to extension installation 

#### Actual behavior

Error: The binding type(s) 'serviceBusTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.

**Comment by soninaren** [comment]
Can you share the contents of `host.json` file?

**Comment by MegoCs** [comment]
{
  "version": "2.0"
}

**Comment by MegoCs** [comment]
![image](https://user-images.githubusercontent.com/14217594/61257558-e795ad80-a771-11e9-8e9c-66fb76d68039.png)
 here is a new image of same issue i had that time.
but i notice it was created using an older version of .Net.Sdk.Function -1.0.13 
i have tried re produce that issue now on VS 2019 but i works and the generated function.json had .Net.Sdk.Functions -1.0.24

**Comment by soninaren** [comment]
@MegoCs Thanks for the update. I am think that the `extension.json` file responsible for registering the extension may not generated correctly for the publish flow. We had a few bugs around that which were fixed in the new versions of `Microsoft.Net.Sdk.Functions` package. Please re-open / create a new issue if you reproduce this in the future. I would recommend moving to the latest version of `Microsoft.Net.Sdk.Functions` which is `1.0.29`. It has a few more fixes in the same area.
