### ISSUE TITLE
dotnet publish is missing custom extensions in extensions.json

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#4133]
@jmezach has brought up a new issue here: https://github.com/Azure/azure-functions-host/issues/3731#issuecomment-466768987. Splitting this out into its own issue for tracking.

**Comment by jmezach** [comment]
I just tried this again with the latest release of the azure-functions-core-tools from Homebrew and I was now able to get the extensions.json generated correctly after removing my Directory.Build.targets workaround. I still needed to set the _IsSdkFunctionsSdkBuild property in my project file though.

**Comment by shibayan** [comment]
I tried it with the latest `Microsoft.NET.Sdk.Functions` (1.0.25), but it seems that the issue of extensions.json being empty with `dotnet publish`, did not seem to be fixed.

**Comment by brettsam** [comment]
Is anyone seeing this able to share the full build command they're using when they hit it?

**Comment by jmezach** [comment]
I'm using the following command:

```bash
dotnet publish -c Release -o out
```

Then looking into the out/bin folder I see an extensions.json, which lists the Durable Functions extension since I'm using that, but it doesn't list my own IWebJobsStartup implementation class.

**Comment by brettsam** [comment]
I'm guessing that running the command twice (without cleaning in between) will work? 

It looks like we're importing the target that generates the extensions.json file *before* we put the function assembly in the folder, so it doesn't find your class. I've got a PR out that puts things in the correct order.

**Comment by shibayan** [comment]
When updating the local `Microsoft.NET.Sdk.Functions.targets` file with the contents of Pull Request, `extensions.json` is correctly created by `dotnet publish`.

Great work!

**Comment by brettsam** [comment]
FYI -- I've just pushed https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/1.0.26.
