### ISSUE TITLE
All triggered function executions stopped after rollout of v2.0.12332 today

### ISSUE THREAD

**Issue by dan-v-elevate** [Azure/azure-functions-host#4152]
We are running v2 functions on the consumption plan with nodejs runtime with an event hub trigger, with a function that essentially reads in batches of data, transforms it, and outputs it to another event hub. We were excited to see a fix for issue #4079 was being released in v2.0.12332, but when it got rolled out today all of our functions stopped processing data. A large portion of our functions stopped executing around 3pm PST (2/27/2019). And we saw a few more over the past few hours that stopped as well. I'm really hoping this is not expected behavior and that something just went poorly with the rollout today? We had to manually stop and restart all functions to get them to start executing again.

#### Investigative information

Please provide the following:

- Timestamp: 3PM PDT
- Function App version (1.0 or 2.0): 2.0
- Function App name: rules1-prod
- Function name(s) (as appropriate): iot_rules
- Invocation ID: ---
- Region: East US 2
- Plan type: Consumption
- Node version: 8.11.1

#### Repro steps
1. Wait for a deployment of a new version of function host to roll out (e.g. v2.0.12332)

#### Expected behavior
 - After auto updating to latest version of function host, function triggers and functions executions should continue to work.

#### Actual behavior
- After auto updating to latest version of function host, function triggers and function executions completely stopped.

#### Known workarounds
- Disabling functions in this state, stopping the underlying function apps, and restarting.

**Comment by dan-v-elevate** [comment]
We are continuing to see this issue on v2.0.12332 and restarting continues to be the only way to fix it. @pragnagopa @mhoeger  - any idea if this is related to new version? We are going to try to rollback to 2.0.12309 in the meantime as we'd prefer to have issue #4079 rather than all of our functions going offline constantly.

**Comment by dan-v-elevate** [comment]
Reverting back to 2.0.12309 did not help. We are still seeing this issue. Not sure what changed, but we continue to keep having function triggers sporadically stop and not recover without manual intervention. Prior to yesterday we have never seen this issue before.

**Comment by mhoeger** [comment]
@dan-v-elevate - thanks for all of the details. Did you deployed any code updates before you saw this issue? We have seen in the past certain deployment methods causing this issue, so we just want to see if we can eliminate some confounding factors. Thanks!

**Comment by dan-v-elevate** [comment]
@mhoeger - we didn't deploy any new code here since Feb 25th, but we did an make an update to environment variables (specific to our app - not Azure) around 2:30PM PDT, so 30 mins before this issue started happening and this would have caused underlying hosts to restart.

**Comment by mhoeger** [comment]
@dan-v-elevate - Thanks for the details! We're looking into this issue. It looks like your function app is running for now, but we'll dig around and find out what happened.

**Comment by dan-v-elevate** [comment]
@mhoeger - we have a support case open now for this issue, and it does appear to be related to the new runtime 2.0.12309. The theory is we still saw this issue after rollback to previous runtime because there may have been an underlying host that had not reverted back yet. But since rollback to 2.0.12309.0 we have not seen this issue any longer. We obviously want the fix for #4079 but if it causes our function app to shutdown and stop processing/firing then its not really a fix for us.

**Comment by mhoeger** [comment]
@dan-v-elevate - we've found a bug in the way placeholder performance optimizations interact with a change in v2.0.12332. If you want, you can use v2.0.12332 and disable placeholders using the App Setting `WEBSITE_USE_PLACEHOLDER` = 0. We're rolling out a fix that will be completed by end of next week. I'm so sorry you've been impacted by this issue, I'll update you on this thread as well when your app can use placeholders again as well!

**Comment by dan-v-elevate** [comment]
@mhoeger - we decided to roll forward again to v2.0.12332 and try this setting. Really appreciate this help late on a Friday, and if this works you've saved my weekend. So far it is looking better after deploying this change.

**Comment by dan-v-elevate** [comment]
@mhoeger - we ran with this configuration over the weekend and it appears to be working as expected now. We saw a number of `Microsoft.Azure.WebJobs.Script.Rpc.LanguageWorkerProcessExitException` that in the previous runtime resulted in it never recovering and in new runtime caused the function app to shutdown and stop triggering. With new runtime and `WEBSITE_USE_PLACEHOLDER = 0`, we just saw individual exceptions and everything continued to run without problems.

As a precautionary measure, we are still running a cron job that runs every 5 minutes that just calls /admin/host/status API (`curl "https://${function_name}.azurewebsites.net/admin/host/status" -H 'Accept: application/json, text/plain, */*' -H "Authorization: Bearer ${BEARER_TOKEN}”`) as that 100% of the time seems to wake up our functions apps to start triggering again. With `WEBSITE_USE_PLACEHOLDER = 0` workaround in place, I'm thinking this is no longer needed?

**Comment by mhoeger** [comment]
@dan-v-elevate Good to hear!! With `WEBSITE_USE_PLACEHOLDER = 0` in place, you won't see the issue of having messages to process but no running functions. So I agree that it's safe to stop your cron job with the workaround in place!

**Comment by mhoeger** [comment]
@dan-v-elevate - The fix is rolled out, you can remove the App Setting now. Closing this issue!

**Comment by mhoeger** [comment]
Fix here: https://github.com/Azure/azure-functions-host/commit/283114581dddb53d7d072265cfbca4c8154770ea
