### ISSUE TITLE
Add Event Id (HostEventId) to logs and Kusto

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#4154]
Instead of querying for specific messages, we should have the ability to log event id codes. This would help queries run faster and introduce consistency across queries as the messages change.

Example of logging method: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Description/DotNet/DynamicFunctionAssemblyLoadContext.Log.cs

Example of logger extension: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Extensions/IMetricsLoggerExtensions.cs

SystemLogger: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Diagnostics/SystemLogger.cs#L59

Consideration around performance, uniqueness of id, and potentially backporting to v1?

**Comment by fabiocav** [comment]
@jeffhollan need to follow up on this item. Moving to Triage backlog for now

**Comment by jeffhollan** [comment]
Sounds good. If I understand right the feature is around emitting more Ids into Kusto and such so when we have to match an event Id to a trace it's easier.  I'm not sure exactly which event Ids this is in reference to. We can chat offline but I'm open to your recommendations in terms of what the priority should be. Is this still a P1, just triaged? Or should this be a P2?

**Comment by alrod** [comment]
PR: https://github.com/Azure/azure-functions-host/pull/4427

**Comment by fabiocav** [comment]
Merged.
