### ISSUE TITLE
Add MetricsLogger at the Webhost/Application level

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#4155]
Currently metrics logger is a JobHostLevel service:

[WebHostMetricsLogger.cs](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Diagnostics/WebHostMetricsLogger.cs) is added here [WebScriptHostBuilderExtension.cs#L98](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/WebScriptHostBuilderExtension.cs#L98)

Services that start at application level do not have access to metrics logger. This effects language workers that start in placeholder mode.

**Comment by jeffhollan** [comment]
@pragnagopa any thoughts to priority of this? Is it a “we should do this sometime” P2/3 or “we should do this soon” P1?

**Comment by pragnagopa** [comment]
Added P2 label. So far we only emit latency metric for process startup.

**Comment by pragnagopa** [comment]
cc @fabiocav @yojagad

**Comment by yojagad** [comment]
I'm closing this issue because IMetricsLogger seem to be available at the application level already.

**Comment by pragnagopa** [comment]
This issue is resolved in commit #https://github.com/Azure/azure-functions-host/commit/8b08e7db3e60d4b245296a83e4b67647fe80f807#diff-63b8db68182a9377a43bd2e17bbf60f1
WebHostMetrics loggers is now added to WebHostServiceCollectionExtensions.cs

**Comment by yojagad** [comment]
Upon further investigation , it was found that WebHostMetricsLogger is being registered twice

**Comment by fabiocav** [comment]
Updating the sprint target. Please adjust if needed.
