### ISSUE TITLE
Azure Function does not pickup CosmosDB from the function.json file

### ISSUE THREAD

**Issue by kichinsky** [Azure/azure-functions-host#4169]
I'm using the following flow:
1. Create a new function, using the template in the VSCode.
2. Update the code. Edit `function.json` file to add bindings to the CosmosDB database.
3. Deploy app to the cloud using Azure DevOps Pipeline.

1. **Manually create CosmosDB account connection.**
It turns out I need to manually go the `Integrate` section and create a new account connection. The generated string is the same as I defined on the step 2.

2. **No extension for CosmosDB are installed**
Then when I go back to the function editor, I get a notification that no extensions are installed:
```
Function (storeConversationReference) Error: The binding type(s) 'cosmosDB' are not registered. Please ensure the type is correct and the binding extension is installed.
Session Id: 5a5241dc49ac4d65ad364273528ff9bf
Timestamp: 2019-03-06T15:28:12.777Z
```
It is not clear from the UI, what should be my next steps in such case.

3. If I remove the binding with CosmosDB and recreate it through the interface, I finally get this message:
```
⚠ Extensions not Installed
This integration requires the following extensions.
⚠ Microsoft.Azure.WebJobs.Extensions.CosmosDB
```

But I can't install the extension:
```
Error:
Host Error: [object Object]
Session Id: 30c582c877224ffc8186520343f40cea
Timestamp: 2019-03-06T16:08:03.768Z
```

*The workaround for such experience is to create Azure Functions and CosmosDB integrations from the portal first.*

**Comment by mhoeger** [comment]
@kichinsky - what version of the azure functions core tools are you using?

**Comment by mhoeger** [comment]
@kichinsky - did you run your VS Code function locally before you deployed it (through F5)? On F5, VS Code runs `func extensions install` which registers the bindings. This document may also be helpful: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register. Note that you may have to add a build step in your DevOps pipeline. If this resolves your problem, could you also give us more details on where it was not made explicit that you need to register your binding (ex: if you were following a tutorial or default integrations with DevOps and Azure Functions)

**Comment by kichinsky** [comment]
Sorry for long response. Nope, I didn't run it locally. But I will test it and return back to you.

**Comment by mhoeger** [comment]
@kichinsky - any updates on this issue?

**Comment by kichinsky** [comment]
Hi, 
1. It seems that to run `func extensions install` locally I also need to install `dotnet`. 
`Extensions command requires dotnet on your path. Please make sure to install dotnet (.NET Core SDK) for your system from https://www.microsoft.com/net/
download`

I get this error message from running the command above. It is not something I would expect from a node.js perspective, but it is ok for me personally. By the way, I think we should include that dependency to the Azure Function Tools instalation or at least mention it in the docs. 

2. I was able to run that command and after that I got the `extensions.csproj` file with references to CosmosDB extension and the 'bin' folder with dependencies.

3. I pushed that change to my repo (**by default the `bin` folder is ignored**, so I kept it this way).

4. I created a new Azure Function from the portal and set up the new ADO Pipeline to build from my repo, including addint the step to compile typescript source code. No errors shown during deployment.

5. In the "integrate" section I still have the `Azure Cosmos DB account connection` empty, meanwhile I have it my .json files. After I manually chose the database, it seems like it was picked up by all the functions. 

6. After that I again got the error message:
```
Function (getConversationReferences) Error: The binding type(s) 'cosmosDB' are not registered. Please ensure the type is correct and the binding extension is installed. 
```
7. After checking the app service editor, it seems like the `bin` folder wasn't recreated during setup. I'm not sure how I should edit my ADO Pipeline for that.

Now...
1. Do you think that I should copy the 'bin' folder to the repo? It doesn't seem to be a good practice. If no, how do I run `func extensions install` in ADO Pipeline? 
2. I'm not sure how to workaround that empty `Azure Cosmos DB account connection` state. Any thought?

**Comment by mhoeger** [comment]
We're working to remove the dotnet dependency very soon with a new feature: https://github.com/Azure/azure-functions-host/issues/3562. Unfortunately, this isn't available yet, but we're moving to a system where configuration is only needed instead of the installation too.

Can you try adding the following step?
```
- script : |
  dotnet restore
  dotnet build --output \'./bin/\'
```

Here is a reference file we are working on integrating automatically with ADO (but again, it's not quite there yet): https://github.com/Azure/azure-functions-devops-build/blob/master/sample_yaml_builds/windows/node-windows.yml

For the integrate tab, you should only have to use that if you are developing from the portal. If you add those commands with your project that has an extensions.csproj, you should be good to go!

**Comment by mhoeger** [comment]
Please let me know if this issue is resolved for you!

**Comment by kichinsky** [comment]
Thanks, works for me.
