### ISSUE TITLE
Filesystem-based secret keys don't work in recent host versions

### ISSUE THREAD

**Issue by elprans** [Azure/azure-functions-host#4172]
When switching azure-functions-python-worker to 2.0.12303, the `<host-dir>/Secrets/host.json` no longer works, and this breaks our CI: https://azfunc.visualstudio.com/Azure%20Functions%20Python/_build/results?buildId=147&view=logs&jobId=d2485948-8adf-52e1-e3c2-1e4aab54c093&taskId=e9aedb70-5aa6-5cb4-da55-d8d5052fa21f&lineStart=154&lineEnd=164&colStart=1&colEnd=2

\cc @pragnagopa

**Comment by mhoeger** [comment]
@elprans - is this still an active issue?

**Comment by elprans** [comment]
@mhoeger, yes, we had to disable the test that depends on this.

**Comment by fabiocav** [comment]
@elprans is running from files a requirement? If so, can you confirm that you have the app setting `AzureWebJobsSecretStorageType` set to `files`?
