### ISSUE TITLE
Azure Functions V1.0 EF DBContext gives exceptions after deployement to Azure

### ISSUE THREAD

**Issue by AmitSawnt** [Azure/azure-functions-host#4175]
#### Investigative information

Please provide the following:

- Timestamp: 08-03-2019 3PM
- Function App version (1.0 or 2.0): 1.0
- Function App name: Sample Function
- Function name(s) (as appropriate): Sample Function
- Invocation ID:
- Region: Asia

#### Repro steps

I'm using the following flow for creating & deploying azure function:
1. Create a new function V1, using the template.
2. Added metadata ConnectionString & providerName auto generated by DB First method in EDMX DBContext.
3. When running the code default constructor of DbContext is called, which picks up values from local.settings.json
```
 "ConnectionStrings": {    
    "DBContextName": {
      "ConnectionString": "metadata=res://*/dbmodel.csdl|res://*/dbmodel.ssdl|res://*/dbmodel.msl;provider=System.Data.SqlClient;provider connection string='data source=**************;initial catalog=*****;user id=userName;password=password;MultipleActiveResultSets=True;App=EntityFramework'",
      "ProviderName": "System.Data.EntityClient"
    }
  }
```
4. So everything works fine when ran locally. but I am facing problem when deploying function to azure.
5. Can you tell me how to configure ConnectionString & AppSettings on Azure Application Settings option? Because we can't specify both ConnectionString & ProviderName at the same time in ConnectionString Section.

![screenshot_4](https://user-images.githubusercontent.com/48350583/54024119-d1248780-41bc-11e9-831e-66c580f37b48.jpg)

6. When running on azure with these settings, I always get following exception -
```
2019-03-08T16:48:03.772 [Info] Exception Occurred: System.InvalidOperationException: The connection string 'DBContextName' in the application's configuration file does not contain the required providerName attribute."
```

#### Expected behavior

I want the function to be running on azure with default DBContext without any constructor parameter.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Here is Snapshot of my DBContext -

![screenshot_5](https://user-images.githubusercontent.com/48350583/54024739-8e63af00-41be-11e9-9a5b-ec1f6715b203.jpg)

#### Related information 

Provide any related information 

* Programming language used - C#
* Links to source 
* Bindings used

**Comment by mhoeger** [comment]
@AmitSawnt - could you try naming your app settings `DBContextName:ConnectionString` and `DBContextName:ProviderName`?

**Comment by bartdk-be** [comment]
@mhoeger - Can we reopen this issue ? I did try to use the same naming convention as you proposed, but without any luck. Reading lots of workaround to get an entity framework connectionstring to work inside a V1 function, but none of them seem to work ?

**Comment by AmitSawnt** [comment]
@bartdk-be I have solved my issue finally. Here are the steps you can follow to make it work with EF :-
1. In your "ConnectionStrings" section of LocalSettings.json file, add dbcontext name & your EF generated complete metadata connection string.
2. In your DbContext class where you have 
`public DBContextName() : base("name=ConnectionStringName")
        {
        }`
add one more constructor ` public DBContextName(string connectionString) : base(connectionString)
        {
        }`
What this will do is, it will allow passing entire connection string from azure function also.
3. Then in your code in function where you are trying to create object of DBContext, 
use this approach to access DBContext :
`string connectionString = ConfigurationManager.ConnectionStrings["DBContextName"].ConnectionString;
  using (var context = new DBContextName(connectionString))
                {
//Your DB operations
}
`
4. In Azure Deployed function, in the ApplicationSettings section -> ConnectionStrings section -> add your "DBContextName" which will be key of connection string you specified in LocalSettings.json. Set connection string Type to "Custom" & put the complete metadata connection string as value for that field. This would enable the function to extract actual connection string from metadata connection string & access database as expected.
5. This worked for me to fix DBContext issue. Try it for you & let me know if you need more help.

**Comment by ponchautf** [comment]
Hi,

We are also looking for a solution about the providerName.
We are sharing some Project from our main application to create the Azure Function, and as our main application is Database First with EDMX, we can't update our DbContext, this file is recreated each time the model is updated.

And we don't like the idea to update .tt file template. 
The way the Azure function work with connection string should be fixed.
It's always bad practice to update library or generated code.

**Comment by AmitSawnt** [comment]
Hi @ponchautf ,
My project is also a EF Database first approach based project. I agree that there is no meaning in updating DbContext, but what you can do is:
1. Within the same namespace where you have your DbContext, you can create another partial class like this-
 public partial class DBContextName: DbContext
    {
        public DBContextName(string connectionString) : base(connectionString)
        {
        }                
    }
2. What this does is, it allows your existing DBContext to have one more constructor which accepts connection string as input & this constructor can decode connectionString & provider name from metadata connection string. 
3. This class will not get affected by any EF EDMX regenerations & your DBContext will always have this overloaded constructor available.

**Comment by bartdk-be** [comment]
@AmitSawnt 
Thanks, was able to fix our issue the way you described.

**Comment by AmitSawnt** [comment]
One more thing related to queue triggered azure functions: 
Queue Triggered Function will delete the incoming message automatically at the end of function execution,
so if you want to make sure that your message should stay in the queue until you remove it, then at the end of the function's Run method throw an exception like this:
` throw new FunctionException("Failed to process message. Retrying " + msg.DequeueCount + " time.");`
This is required because the only condition when function will not remove the message from the queue, is when it throws any exception else the function will always delete the message once it completes execution.
