### ISSUE TITLE
Azure Functions when high concurrency - singleton Cosmos DB client starts failing with: A task was canceled

### ISSUE THREAD

**Issue by zmarty** [Azure/azure-functions-host#4179]
Azure Functions v2

We have a function which is triggered by an Event Grid incoming message.

That function makes a query to Cosmos DB, using a **singleton** Cosmos DB client.

**Symptom**: When we have a sudden spike of many Event Grid messages received in parallel, and thus many concurrent runs of the same function that accesses the same singleton Cosmos DB client, the Cosmos DB client starts failing within milliseconds with this error: A task was canceled.

I believe this problem is not related only to the Cosmos DB client itself, as others have reported similar problems sending our Event Grid messages.

As you can see from the image below, when this happens the call within literally a couple of milliseconds:

![image](https://i.imgur.com/uEwFfvd.png)

Related issues: 
https://github.com/Azure/Azure-Functions/issues/1127
https://github.com/Azure/azure-functions-host/issues/3160

**Comment by mhoeger** [comment]
Hi @zmarty , I'm seeing that when you were experiencing issues with Task cancellations, you had a high number of outbound TCP connections. Just to confirm, are you initializing the document client outside of the scope of function execution (here's [a great example](https://medium.com/microsoftazure/azure-cosmos-db-functions-cookbook-static-client-874072aef28e), and here are some docs on [managing connections](https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections)).

**Comment by zmarty** [comment]
> Hi @zmarty , I'm seeing that when you were experiencing issues with Task cancellations, you had a high number of outbound TCP connections. Just to confirm, are you initializing the document client **outside of the scope of function execution** (here's [a great example](https://medium.com/microsoftazure/azure-cosmos-db-functions-cookbook-static-client-874072aef28e), and here are some docs on [managing connections](https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections)).

Yes, the client is a singleton. It gets created whenever a function first accesses it, and there is a single instance. Yet.

**Comment by mhoeger** [comment]
Is there anything else that could be causing the high outbound connections we were seeing then? Even another app on the same machine? I also see a few `Microsoft.Azure.Documents.RequestRateTooLargeException` exceptions which suggest that something is going on with cosmos db receiving too many requests or the sdk sending requests in a non-optimal way.

For the full stack trace, you can see this data too on the Azure Portal if you go to Platform features => Diagnose and solve problems => Availability and performance => Function App Down or Reporting Errors => Function Executions and Errors. You will likely have to scroll back and hit "Last 1d" many times to get to the right time window. You can also email me at mahoeger@microsoft.com if you would like me to privately give you the full stack trace we're seeing.

**Comment by zmarty** [comment]
Hi again. Thanks, I can check that. 

We generally do not really see many RequestRateTooLargeException exceptions, that should be rare.

What I don't get is how this translates into this generic error where a bunch of outbound requests seem to be cancelled at the same time. Why can't I see a more specific error other than just "A task was canceled"?

**Comment by fabiocav** [comment]
@zmarty are you still experiencing this? Closing as resolved since there wasn't a follow up, but please let us know if you're still having problems.

Thanks!
