### ISSUE TITLE
Expired CreateTimer() events aren't processed at scheduled time

### ISSUE THREAD

**Issue by apsteger** [Azure/azure-functions-host#4180]
#### Investigative information
Timers created with CreateTimer() don't seem to be triggered at the scheduled times. I noticed this running locally. I posted this question on StackOverflow

[Why doesn't my Durable Function Orchestrator awaken at the time specified in DurableOrchestrationContext.CreateTimer()?](https://stackoverflow.com/questions/55033603/why-doesnt-my-durable-function-orchestrator-awaken-at-the-time-specified-in-dur)

Why does my orchestrator function sleep for longer than the time I specify with CreateTimer()? I am calling it like this: 

var resumeAt = context.CurrentUtcDateTime.AddSeconds(60);
await context.CreateTimer(resumeAt, CancellationToken.None);

You can see from the logs below that it actually resumes after 80 seconds rather than 60 seconds:

[03/06/2019 10:41:47 PM] 0021fd6e-1055-4f3b-ba42-34301c7affed: Function 'Dps_Orchestrator (Orchestrator)' is waiting for input. Reason: **CreateTimer:2019-03-06T22:42:47.3037098Z**. IsReplay: False. State: Listening. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.7.1. SequenceNumber: 9096.

**[03/06/2019 10:43:07 PM]** 0021fd6e-1055-4f3b-ba42-34301c7affed: Function 'Dps_Orchestrator (Orchestrator)' was resumed by a timer scheduled for **'2019-03-06T22:42:47.3037098Z'**. IsReplay: False. State: TimerExpired. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.7.1. SequenceNumber: 9098.

What is going on?

**Comment by mhoeger** [comment]
Transferring to durable repo
