### ISSUE TITLE
Metadata generation fails consistently on Mac during build when targeting netcoreapp2.1+

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#4181]
From @rogeralsing [here](https://github.com/Azure/Azure-Functions/issues/928#issuecomment-471255755):
> I'm getting metadata generation failure on my Mac.
> 
> This is a gist containing the full error message https://gist.github.com/rogeralsing/a9b1acd0fd650f4d35cb8667c7d4e5a7
> 
> The final bit is:
> 
> ```
> /Users/rogerjohansson/.nuget/packages/microsoft.azure.webjobs.script.extensionsmetadatagenerator/1.0.1/build/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(20,5): error : Metadata generation failed. [/Users/rogerjohansson/Git/FunctionLabb/FunctionLabb.csproj]`
> ```
> I've tried countless of times to recreate my functions using vs code from scratch, but I hit this issue 100% of the times.

See that thread for all details, but summary:
- Building on Mac
- Still fails using 1.0.26 of Microsoft.NET.Sdk.Functions
- works on netcoreapp2.0 but not 2.1 or 2.2
- csproj looks simple: https://gist.github.com/rogeralsing/8ff5d79e75ddf9587374b7badc92680e

**Comment by rogeralsing** [comment]
Some additional context:

Swedish regional settings on the machine.

One of the warnings showing up is:
```
/Users/rogerjohansson/.nuget/packages/microsoft.azure.webjobs.script.extensionsmetadatagenerator/1.0.2/build/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(20,5): warning : Description: Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: IO_FileLoad [/Users/rogerjohansson/Git/fun3/fun3.csproj]
```

Which seems to be the same as: 
https://github.com/dotnet/corefx/issues/24718

**Comment by fabiocav** [comment]
@rogeralsing thank you for the additional context. I have tried to repro this on a Mac but was unable to, the language is region/language settings are likely the culprit.

Yes, this is likely related to the issue you've linked to, though they had another issue they were tracking and that was closed as resolved:
https://github.com/dotnet/corefx/issues/23608

Can you share the information you see from `dotnet --info` ?

**Comment by rogeralsing** [comment]
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.104/

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.1.504 [/usr/local/share/dotnet/sdk]
  2.2.104 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by rogeralsing** [comment]
I just found that adding this reference:

```
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.0" />
```

In a 2.0 project, cause the exact same issue for 2.0

**Comment by rogeralsing** [comment]
Resolved.

I deleted all previously installed runtimes, not just the SDK's and nuget caches.
That solved it. now 2.1+ compiles correctly.

**Comment by fabiocav** [comment]
Thank you for the update! Closing as resolved

**Comment by alexkyse1** [comment]
@rogeralsing solution worked out. Deleted 2.0 runtime & 2.1 runtime, using sdk 2.2.15
