### ISSUE TITLE
Decouple languageworkerchannel and worker process

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#4182]
If a language worker is stated at application level, as part of job host restarts language worker needs to reload functions before accepting function invocations.

Note: Impact of this can be reduced if using run from zip as Job host does not have to restarted multiple times which happens incase of any changes in the file system.

Sample log file:

```
Summary
Found initialized language worker channel for runtime: 0
Adding Function descriptor provider for language java.
Creating function descriptors.
Function descriptors created.
Generating 1 job function(s)
Found the following functions:
Host.Functions.EnbDeploymentMicroService

Host initialized (55ms)
Host started (55ms)
Job host started
Debug file watch initialized.
Diagnostic file watch initialized.
File event source initialized.
Host restarted.
Stopping JobHost
Job host stopped
Host instance '808639562f684e4526ca8d6f4b3b6433' released lock lease.
Executing HTTP request: {
  "requestId": "d1d0080e-64f0-46d5-9d99-330339c84f0e",
  "method": "POST",
  "uri": "/runtime/webhooks/EventGrid"
}
Initiating host availability check.
Host availability check succeeded.
AuthenticationScheme: WebJobsAuthLevel was successfully authenticated.
Executing 'Functions.EnbDeploymentMicroService' (Reason='EventGrid trigger fired at 2019-03-05T22:42:32.3601201+00:00', Id=b76c4570-96b8-47e9-b5ec-dded1409e627)
Executing HTTP request: {
  "requestId": "a37289de-7aa6-42ea-9dba-bf9eb05fe094",
  "method": "POST",
  "uri": "/runtime/webhooks/EventGrid"
}
Initiating host availability check.
Host availability check succeeded.
AuthenticationScheme: WebJobsAuthLevel was successfully authenticated.
Executing 'Functions.EnbDeploymentMicroService' (Reason='EventGrid trigger fired at 2019-03-05T22:42:32.3719102+00:00', Id=7da8e98a-8d15-4b78-9296-808c4af57416)
Executed 'Functions.EnbDeploymentMicroService' (Failed, Id=b76c4570-96b8-47e9-b5ec-dded1409e627)
```

Note: there are no messages indicating function loaded after jobhost restarted.

**Comment by pragnagopa** [comment]
[Dispose](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/LanguageWorkerChannel.cs#L487) method in LanguageWorkerChannel - Handles disposing process attached to the languageworkerchannel and all the subscriptions.
For a language worker that is started at webhost level, when jobhost restarts, all the subscriptions need to be disposed but the process should not be disposed.
Fix is to refactor the code - Decouple process and languageworkerchannel

**Comment by pragnagopa** [comment]
Changing the priority to P2 as this only effects 
- WebHost level language workers a.k.a language workers started in placeholder mode
- When multiple jobhost restarts are triggered due changes in the file system. Mitigation is to switch to run from zip.

**Comment by fabiocav** [comment]
Closing as resolved
