### ISSUE TITLE
[V2 cold start] Enabling AppInsights is increasing functions cold start by 500-800 milliseconds 

### ISSUE THREAD

**Issue by safihamid** [Azure/azure-functions-host#4183]
Create a function v2 app then add this app setting: 
APPINSIGHTS_INSTRUMENTATIONKEY={some value}

Cold start jumps by 500-800 milliseconds with this callstack:

  + Anonymously Hosted DynamicMethods Assembly!dynamicClass.lambda_method(pMT: 13A80B0C,pMT: 13A597E8)16.3
  + microsoft.azure.webjobs.script.webhost!DryIoc.Registrator+<>c__DisplayClass27_0.<RegisterDelegate>b__0(DryIoc.IResolverContext)16.3
  + microsoft.azure.webjobs.script.webhost!DryIoc.Microsoft.DependencyInjection.DryIocAdapter+<>c__DisplayClass3_0.<RegisterDescriptor>b__0(DryIoc.IResolverContext)  16.3
  + microsoft.azure.webjobs.logging.applicationinsights!Microsoft.Extensions.DependencyInjection.ApplicationInsightsServiceCollectionExtensions+<>c.<AddApplicationInsights>b__1_2(System.IServiceProvider) 16.1
  + microsoft.azure.webjobs.logging.applicationinsights!ApplicationInsightsServiceCollectionExtensions.SetupTelemetryConfiguration  8.4
  + microsoft.azure.webjobs.script.webhost!JobHostServiceProvider.GetService  5.1
  + microsoft.applicationinsights!TelemetryConfiguration.get_Active  1.2
  + microsoft.applicationinsights!TelemetryConfiguration.CreateDefault  0.5
  + microsoft.extensions.dependencyinjection.abstractions!ServiceProviderServiceExtensions.GetRequiredService  0.5
  + microsoft.extensions.options!?  0.3
  + microsoft.applicationinsights!TelemetryConfigurationFactory.get_Instance  0.1
  + coreclr!ThePreStub0.2

**Comment by fabiocav** [comment]
Closing this as resolved.

**Comment by alexgman** [comment]
Is there proof that this has actually been resolved?

**Comment by brettsam** [comment]
Our internal telemetry indicates that it has been resolved. Are you seeing something different? If so, could you share your repro?
