### ISSUE TITLE
[V2 cold start] Cache Expression compilation results during placeholder mode to avoid recompiles during specialization mode

### ISSUE THREAD

**Issue by safihamid** [Azure/azure-functions-host#4184]
This is accounting for ~50% of the cold start time in function host itself(~30% overall) across all languages. 
Call stack here:

![image](https://user-images.githubusercontent.com/1000764/54162423-aa5f8e80-4412-11e9-86e3-ed86fd65ee8d.png)

**Comment by fabiocav** [comment]
Closing this as we'll no longer be taking this approach after the recent changes.
