### ISSUE TITLE
Null ref in background sync triggers path

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#4200]
To reproduce:

1. Make a new C# V2 function app in VS. Pick the service bus queue template.
2. Set the Connection property to some value e.g. "myconnection"
3. Do NOT add "myconnection" to local.settings.json
4. F5. Make sure you're running 2.0.12332.0 or later.

Expected result:

Functions host displays an error saying it was not able to index the function because the connection string is missing.

Actual result:

VS breaks on this line with a null ref exception:
_syncTimer.Change(Timeout.Infinite, Timeout.Infinite);

I suspect there is a race condition where stop is called before start is called. This code should be defensive - StopAsync should be a no-op if Start wasn't called.

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Azure.WebJobs.Script.WebHost
  StackTrace:
   at Microsoft.Azure.WebJobs.Script.WebHost.FunctionsSyncService.StopAsync(CancellationToken cancellationToken) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\FunctionsSyncService.cs:line 63
   at Microsoft.Extensions.Hosting.Internal.Host.<StopAsync>d__10.MoveNext()
```

**Comment by paulbatum** [comment]
Update - looks like this was already fixed, but there hasn't been a local tooling release yet. I'll close this once the fix is live.

**Comment by doguva-msft** [comment]
is there a workaround ?

**Comment by paulbatum** [comment]
@doguva-msft As far as I know this error only occurs when there is some other error. So resolving the original error should let you move forward.

**Comment by mathewc** [comment]
Tooling release is live.
