### ISSUE TITLE
Depdency Injection and Logging start failing on 2.0.12353

### ISSUE THREAD

**Issue by PingPongSet** [Azure/azure-functions-host#4203]
have a project that is using dependency injection via constructor and MS Logging from ASP.NET Core with Azure Function 2.0, which was working under 2.0.12333 locally and on Azure, and now have two issues below:

1) Exception thrown for dependency injection via constructor, which was working before.

2) Logging is no longer writing to a text file, which was working before.

https://stackoverflow.com/questions/55174543/depdency-injection-and-logging-start-failing-suddently-without-code-changes-when/55199041

**Comment by josemnbcamacho** [comment]
I'm having the same problem, manually switching to 2.0.12342.0 seems to solve the issue.

**Comment by kemmis** [comment]
> I'm having the same problem, manually switching to 2.0.12342.0 seems to solve the issue.

Same here. I can confirm that setting FUNCTIONS_EXTENSION_VERSION to 2.0.12342.0 fixed the issue for me. **2.0.12332.0 did not work, so you might want to look at that release's changes** to see what's up rather than the 2.0.12353 version listed in the title.

**Comment by fabiocav** [comment]
This is confirmed as a defect and we're currently working on a fix. In the meantime, reverting to the previous version is the mitigation step that should be taken.

**Comment by fabiocav** [comment]
The fix for this is currently rolling out to azure and a Core Tools update will be made available once deployment is completed.

**Comment by jvossers** [comment]
Eagerly awaiting this fix. Any news on progress? Thanks!

**Comment by fabiocav** [comment]
The fix has been released to Azure and the Core Tools update is rolling out right now. Should already be available from VS and is being pushed to the othe channels. Thanks for the patience with this!
