### ISSUE TITLE
Unable to use CosmosDB input binding

### ISSUE THREAD

**Issue by galvesribeiro** [Azure/azure-functions-host#4204]
Trying to use CosmosDB binding get a `DocumentClient` as state on [this document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2#http-trigger-get-multiple-docs-using-documentclient-c) as the Function parameter breaks the host and the function is not indexed wit this error:

![image](https://user-images.githubusercontent.com/4714040/54482712-ac688980-4826-11e9-8ffa-8e2d33d72bd3.png)

The function code is basically this (it is empty just to illustrate the failure):

```
public class AppendEvent
    {
        private readonly ILogger _logger;

        public AppendEvent(ILoggerFactory loggerFactory)
        {
            this._logger = loggerFactory.CreateLogger<AppendEvent>();
        }

        [FunctionName("Append")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = null)] HttpRequest req,
            [CosmosDB(
                databaseName: Constants.EVENT_STORE_DATABASE,
                collectionName: Constants.EVENTS_COLLECTION)] DocumentClient client)
        {
            this._logger.LogInformation("C# HTTP trigger function processed a request.");

            return new OkResult();
        }
    }
```

The startup class is:

```
[assembly: WebJobsStartup(typeof(AzureFunctionsAppStartup))]
namespace GP.EventStore
{
    public class AzureFunctionsAppStartup : IWebJobsStartup
    {
        public void Configure(IWebJobsBuilder builder)
        {
            builder.AddHttp(opt =>
            {
                opt.RoutePrefix = "";
            });

            builder.AddCosmosDB(opt =>
            {
                opt.ConnectionMode = ConnectionMode.Direct;
                opt.Protocol = Protocol.Tcp;
                opt.ConnectionString = Environment.GetEnvironmentVariable(Constants.EVENT_STORE_CONNECTION);

            });
            builder.Services.AddLogging(logging =>
            {
                logging.AddFilter(level => true);
                logging.AddConsole();
            });

            builder.Services.AddTelemetry(opt =>
            {
                opt.ServiceName = "GP.EventStore";
                opt.Version = "1.0";
            });
        }
    }
}
```

The project file is:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.3" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.0.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.24" />
    <PackageReference Include="Microsoft.Azure.DocumentDB.Core" Version="2.2.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="2.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.2" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GP.Telemetry\GP.Telemetry.csproj" />
  </ItemGroup>
</Project>
```

Function tools installed (Mac OSX):
```
Azure Functions Core Tools (2.4.419 Commit hash: c9c1724d002bd90b2e6b41393915ea3a26bcf0ce)
Function Runtime Version: 2.0.12332.0
```

Steps to reproduce:

1. Create the function project
2. Add code, binding and startup classes
3. Run `func extensions install` from the project directory
4. Run the project

Is there anything am I missing to get it to work?

**Comment by mhoeger** [comment]
cc: @fabiocav as it's related to using extensions & DI

**Comment by galvesribeiro** [comment]
Folks I've found the problem...

```
[CosmosDB(
                databaseName: Constants.EVENT_STORE_DATABASE,
                collectionName: Constants.EVENTS_COLLECTION)] 
```

That is missing the _Connection_ field in it. Even if I add `AddCosmosDB()` and set the 
 "main" connection strings for all the functions on that app, the runtime fail to bind because that property is null on the attribute.

If that is by design, I think we can just close the issue but the ambiguity of use the `AddCosmosDB()` extension should be solved by removing that connection string option there.

**Comment by fabiocav** [comment]
@galvesribeiro closing this as resolved, but we're curious about the pattern being used here. Is there a reason why you're explicitly wiring the extensions with a startup type? This is automatically done by the extensions and they properly use the various configuration sources in those cases.

**Comment by galvesribeiro** [comment]
@fabiocav we thought that by calling `AddCosmosDB(options)` on the startup class, we could add a service-level connection string that wasn't required to be added on every function.

I think that we should have that option for all the parameters on that attribute. If the user specify it on the startup class, then use it. If not, require the attribute. And if it was on startup and also set on the attribute, use thee attribute as override.

**Comment by fabiocav** [comment]
Was trying to better understand the use case as that is normaly not required, same with HTTP.

So, to comfirm, this was done to avoid havint to add the connection string reference to the acutal functions using the attribute model, correct?

**Comment by fabiocav** [comment]
@brettsam can you share more information on the default connection string setup?

**Comment by galvesribeiro** [comment]
Yep. So if you set it "globally" (both connections, collection, db) in the startup class, I think the attribute should not require any parameters. The parameters would be an exception to override the global settings. Totally optional. However if both parameters and the startup hasn't set, it should throw.

**Comment by brettsam** [comment]
We'll fallback to the `CosmosDB` connection string if we can't find anything else. 

Locally you can set that in local.settings.json like:

```
{
  "IsEncrypted": false,
  "Values": {
    "ConnectionStrings__CosmosDB": "",
    ...
  }
}
```

In the your deployed app, add a `CosmosDB` connection string in the `Configuration` tab.

Or if you'd prefer to set this globally and not use the default `CosmosDB` connection string, you can override the options by calling `PostConfigure<CosmosDBOptions` in your `IWebJobsStartup` (note that we're not calling `AddCosmosDB()` again here):

```
public void Configure(IWebJobsBuilder builder)
{
    builder.Services.PostConfigure<CosmosDBOptions>(opt =>
    {
        opt.ConnectionMode = ConnectionMode.Direct;
        opt.Protocol = Protocol.Tcp;
        opt.ConnectionString = Environment.GetEnvironmentVariable("WHATEVER");
    });
}
```

**Comment by galvesribeiro** [comment]
@brettsam that is somehow what I did.

However, that also means the current binding will not work and we should inject the `DocumentClient` ourselves.

**Comment by brettsam** [comment]
What scenario didn't work for you? I tried the scenarios above using the binding and verified that it worked.

FYI -- my function looked like this and I verified that the db was created:
```
[FunctionName("Function1")]
public static async Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
    [CosmosDB(databaseName: "db1", collectionName: "coll1")] DocumentClient client,
    ILogger log)
{
    var db = new Database()
    {
        Id = "db1"
    };

    await client.CreateDatabaseIfNotExistsAsync(db);
    ....
```

**Comment by galvesribeiro** [comment]
That is weird... Look at the original issue... The only difference I see is that I'm not using a static function...

**Comment by brettsam** [comment]
Can you look in your /bin folder of your function app (the /bin folder that is a peer to host.json when you build) and tell me what the extensions.json looks like?
