### ISSUE TITLE
Python Func App returning 429

### ISSUE THREAD

**Issue by sinaakhtar** [Azure/azure-functions-host#4206]
I have a python func app on a dedicated app service plan which is receiving requests from a streaming analytics job. The streaming analytics job fails with this error:

 "properties": {
        "Message Time": "2019-03-18 10:04:09Z",
        "Error": null,
        "Message": "A 429 (429) error was return from Azure functions. Error encountered after writing [2] batches.",
        "Type": "AzureFunctionOutputAdapterClientError",
        "Correlation ID": "48fe19d5-420f-4ef4-b6aa-26d43e5f2da6"
    },

According to the documentation, there is no limit on a HTTP python app when using a dedicated app service plan. Since that doesn't seem to be true, I defined the max throttles in the host.json as:
    "http": {
        "routePrefix": "api",
        "maxOutstandingRequests": 999999,
        "maxConcurrentRequests": 5000,
        "dynamicThrottlesEnabled": false
    }

The streaming analytics job runs a little longer before it fails again with the same 429 error. Is there a way to circumvent this problem?

My entire function is contained with the main function in the python package:

def main(req: func.HttpRequest) -> func.HttpResponse:

**Comment by asavaritayal** [comment]
Moving issue to the host repo for investigation.
