### ISSUE TITLE
[National Cloud] Failed to execute QueueTrigger for Node in v2 Function app

### ISSUE THREAD

**Issue by sunxinhuan** [Azure/azure-functions-host#4208]
**Ibiza portal URL**:   https://aka.ms/antuxstage-mooncake 
**App runtime version**:  1.0.12299.0 (~1)/2.0.12309.0 (~2)
**Browser**: Chrome
**Hosting Plan**: App Service Plan (S1)

Just QueueTrigger-JavaScript is failed, others templete work as normal

Please refer to the snapshot:
![NodeQueue](https://user-images.githubusercontent.com/39791546/54594936-a1069f80-4a6c-11e9-84d8-d83c0c76dedc.PNG)

**Repro steps**:
	1. Open a v2 function app;
	2. Make sure the FUNCTIONS_WORKER_RUNTIME setting value is 'node';
	3. Add  a Queue Trigger function;
	4. Click on 'Run' and verify the logs

**Comment by agruning** [comment]
No repro
