### ISSUE TITLE
Feature Request: Proxies: Route regexes

### ISSUE THREAD

**Issue by damienwebdev** [Azure/azure-functions-host#4209]
#### Investigative information

- Function App version: v2.0

#### User Story
As a developer, I would like to create an Angular Universal (Server Side Rendered) app that runs on Azure functions. Currently, without regex support this is way more difficult than it needs to be.

#### Expected behavior
I would like to be able to define `proxies.json` that looks like this:

```json
{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "api": {
      "matchCondition": {
          "route": "/api/{*url}"
      },
      "backendUri": "https://%WEBSITE_HOSTNAME%/api/{url}"
    },
    "static": {
      "matchCondition": {
        "methods": ["GET", "OPTIONS"],
        "route": "/{filePath:regex(^[^.]*.[^.]*$)}"
      },
      "backendUri": "SOME_STORAGE_CONTAINER_{filePath}"
    },
    "renderer": {
      "matchCondition": {
        "methods": ["GET"],
        "route": "{*angularPath}"
      },
      "backendUri": "https://%WEBSITE_HOSTNAME%/api/{angularPath}"
    }
  }
}
```

This proxy setup would run all "non-file-ending" paths through the server-side renderer running as a single Azure Function. On the other hand, "File-ending" paths would instead be handed-off as static content to a storage container. 

#### Actual behavior
When trying to do anything like this it just seems impossible. There's some info on [an older issue](https://github.com/Azure/azure-functions-host/issues/1988) indicating that this MAY have been possible at some point, but currently I get the following:

```
[3/19/19 6:01:05 PM] Loading proxies metadata
[3/19/19 6:01:05 PM] Initializing Azure Function proxies
[3/19/19 6:01:05 PM] Error processig configuration of Function Proxies
[3/19/19 6:01:11 PM] 2 proxies loaded
```

Additionally, @safihamid posted on [stackoverflow](https://stackoverflow.com/questions/51730993/azure-function-proxy-regex-match-condition-route) that this isn't supported at all. Clarification on why this isn't supported, and what we can do as a work-around would be nice.

#### Known workarounds

There don't appear to be any known work-arounds for this, it just seems like a strange limitation compared to Zeit Now, AWS Lambda, or Google Cloud functions. I was able to achieve the same goal very easily on every other major serverless provider excluding Azure functions. 

#### Related information 

Provide any related information 

* Programming language used: Node.js v8.10
* Bindings used

cc @safihamid

**Comment by fabiocav** [comment]
@safihamid can you comment on this? is the recommendation to use APIM for features like this moving forward?

**Comment by safihamid** [comment]
Yes, all future feature requests should go to APIM serverless. https://azure.microsoft.com/en-us/blog/announcing-azure-api-management-for-serverless-architectures/

**Comment by fabiocav** [comment]
Thank you for the confirmation.

@damienwebdev I'm closing this based on the recommendation above, but please let us know if you have any additional questions.

**Comment by Amthieu** [comment]
@damienwebdev have you managed to find a solution with Azure? I have the same use-case for hosting a SPA in Azure storage.
