### ISSUE TITLE
Only load extensions from bundle if used by app

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-host#4223]
Depends on https://github.com/Azure/azure-functions-host/issues/3714

We should not load assemblies included in a bundle unless the runtime actually needs them.

**Comment by fabiocav** [comment]
@mattchenderson FYI - moving to 52

**Comment by fabiocav** [comment]
@mattchenderson FYI... moving this back to triaged, we'll discuss sprint allocation when @soninaren is back

**Comment by soninaren** [comment]
Fixed in https://github.com/Azure/azure-functions-host/pull/4980
