### ISSUE TITLE
Do not log language metric in placeholder mode

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#4227]
Do not log language metric in placeholder mode
https://github.com/Azure/azure-functions-host/blob/af7257614166ef36c06e185b471d5f7718c18f62/src/WebJobs.Script/Host/ScriptHost.cs#L277

**Comment by pragnagopa** [comment]
cc @mhoeger @paulbatum

**Comment by pragnagopa** [comment]
Metric `host.startup.runtime.language.dotnet` is being emitted for non dotnet apps. This appears to be race condition during specialization. Needs investigation

**Comment by paulbatum** [comment]
I confirmed this by looking at a day's worth of telemetry from our cold start runners. This is going to be screwing up our analytics pipeline.

**Comment by pragnagopa** [comment]
cc - @brettsam 
PR # https://github.com/Azure/azure-functions-host/pull/4356 fixes race condition during specialization.

**Comment by brettsam** [comment]
Do you have an example of the erroneous log? Are we logging this with the customer's app name and `dotnet`, even though it's not a dotnet app?

**Comment by pragnagopa** [comment]
An example of error metric: A Java  app gets two metrics host.startup.runtime.language.dotnet and host.startup.runtime.language.java. Similarly a node app gets two metrics: host.startup.runtime.language.dotnet and host.startup.runtime.language.node

I will share kusto queries offline.

**Comment by pragnagopa** [comment]
PR #4210 addresses not logging language metric in placeholder mode. We still need to keep this issue active for investigating duplicate language metric logs

**Comment by fabiocav** [comment]
@pragnagopa can this be closed now?

**Comment by pragnagopa** [comment]
Yes. Thanks to @brettsam for fixing races during specialization!
