### ISSUE TITLE
Access metadata for Python BlobTrigger

### ISSUE THREAD

**Issue by svartkanin** [Azure/azure-functions-host#4232]
I'm using Python for my function apps and I've created a `BlobTrigger` which works fine. Hoever the created endpoint doesn't seem to have an option to have the metadata as a parameter:

```
def main(myblob: func.InputStream):
    logging.info(f"Python blob trigger function processed blob \n"
                 f"Name: {myblob.name}\n"
                 f"Blob Size: {myblob.length} bytes")
```

Accodirng to the documentation and the examples for C# and JS this seems to be possible:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob#trigger---metadata.

Is there also an option to get the metadata of the blob with the endpoint call right away or would I have to do a manual call to azure to retrieve the metadata for the blob?

**Comment by mhoeger** [comment]
@asavaritayal / @maiqbal11 - i thought `myblob.name` and `myblob.length` would be defined? Does metadata come from somewhere else or is this a bug?

**Comment by maiqbal11** [comment]
`myblob.name` and `myblob.length` should be accessible without any issues. @svartkanin, I believe you'd want to access something like `myblob.metadata` where `metadata` is a dictionary? Currently, this isn't supported for the InputStream type that we have defined for blobs (https://github.com/Azure/azure-functions-python-worker/blob/dev/azure/functions_worker/bindings/blob.py). 

The CloudBlob object (https://docs.microsoft.com/dotnet/api/microsoft.windowsazure.storage.blob.cloudblob?view=azure-dotnet) that C# uses is a much richer binding that provides metadata along with other properties as well. We've intended to keep our binding implementations minimal for Python. You should be able to use the blob information provided to call into the Azure Python Storage SDK to retrieve the metadata. More info on that here: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python.

**Comment by fabiocav** [comment]
Closing as answered. Please let us know if you have any additional questions.
