### ISSUE TITLE
Register IHttpContextAccessor in ASP.NET Core configuration

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-functions-host#4245]
ASP.NET Core provides access to the current HttpContext via IHttpContextAccessor. 
Different components (e.g. ApplicaitonInsights) can access it at any point to enhance telemetry.

The context accessor feature has to be registered: 
https://adamstorr.azurewebsites.net/blog/are-you-registering-ihttpcontextaccessor-correctly

Functions don't do it now and proposal is to register it so everyone can use HttpContext.Current if they want (and we can stop using MS_HttpRequest scope property).

AFAIK, the downside of it is a very small perf hit because of using another AsyncLocal  (HttpContext.Current) and if someone uses HttpContext.Current – there is actually a lock on it – but in the majority of cases, nobody should use it.

cc @brettsam

**Comment by murdockcrc** [comment]
cc: @cmenzi what we talked about this morning.
