### ISSUE TITLE
How to detect host shutdown using CancellationToken (aka Graceful shutdown)

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-functions-host#4251]
#### Is your question related to a specific version? If so, please specify:

- Azure Functions Runtime 2.0.12382
- Azure Functions Core Tools 2.5.553
- Azure Functions SDK 1.0.26

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 

C#

#### Question

I want to use the CancellationToken to safely perform the restart that takes place during the execution of the Function.

I wrote the following code and tried the behavior of CancellationToken, but it seemed that cancellation was not performed when Function Host shutdown.

```csharp
public static class Function1
{
    [FunctionName("Function1")]
    public static async Task<IActionResult> Run(
        [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
        CancellationToken cancellationToken,
        ILogger log)
    {
        log.LogInformation("C# HTTP trigger function start.");

        try
        {
            // simulate excessive cpu time process
            await Task.Delay(TimeSpan.FromSeconds(30), cancellationToken);
        }
        catch (OperationCanceledException)
        {
            log.LogInformation("C# HTTP trigger function canceled.");

            return new BadRequestResult();
        }

        log.LogInformation("C# HTTP trigger function end.");

        return new OkResult();
    }
}
```

The following is the log when trying to restart from Azure Portal while Function is running.

![image](https://user-images.githubusercontent.com/1356444/55272803-a7ff9e80-5305-11e9-89dc-e4ea45187e18.png)

It seems that forced shutdown is performed while executing Function. Not only restart but also deployment has the same result.

On the other hand, at Function Timeout, it was confirmed that CancellationToken was working.

![image](https://user-images.githubusercontent.com/1356444/55272832-54418500-5306-11e9-8387-0356481b8195.png)

Is there a way to run Graceful shutdown like WebJobs?

**Comment by mhoeger** [comment]
@alrod - can you help answer this question?

**Comment by fabiocav** [comment]
@shibayan the approach you're using is correct. We do depend on the shutdown signaling flowing from IIS so we can correctly signal that token, and that should be happening in that scenario.

Assigning this for investigation as it looks like a defect.

**Comment by alrod** [comment]
PR: https://github.com/Azure/azure-functions-host/pull/4460
