### ISSUE TITLE
Function app name prefix in key name in keyvault secret repository

### ISSUE THREAD

**Issue by funcfan** [Azure/azure-functions-host#4252]
#### What problem would the feature you're requesting solve? Please describe.
It allows me to share one keyvault instance between many function apps - it provides possibility to store many keys to various functions(apps) in one place. 
My case: 
I have many function apps, some of them call others via http(I know, I know, use queues ;-) ), so I need function's keys - currently, I manually upload keys to KeyVault and when function wants to call other function - it downloads secret. New secret storage allows me to avoid manual uploading(thanks!), but currently it forces me to use many keyvault - one per function app - and add function's identity to many keyvaults. 

#### Describe the solution you'd like
Now:
for example
`host--masterKey--master `
Propose:
`host--FUNCTIONAPPNAME--masterKey--master`

same prefix for other key types.

#### Describe alternatives you've considered
n/a

#### Additional context
Azure Functions Runtime 2.0.12382 introduces possibility storing function/host key in keyvault. It's brilliant! But keys don't have prefix - so every function app uses the same secret name - so it's impossible to share one keyVault instance between multiple function apps. I think sharing one keyVault instance between many apps is common scenario.

**Comment by fabiocav** [comment]
Thanks for sending this. The current behavior is by design after considering some of the issues around key management in Key Vault, so we don't plan on addressing this at this point.
