### ISSUE TITLE
Logic App designer throws the famous "Request to obtain the keys for function failed." when saving.

### ISSUE THREAD

**Issue by VictorioBerra** [Azure/azure-functions-host#4253]
```
Failed to save logic app ABC. Request to obtain the keys for function '/subscriptions/ABC/resourceGroups/ABC/providers/Microsoft.Web/sites/ABC/functions/ABC' failed. Error details: 'System.InvalidOperationException: Runtime keys are stored on blob storage. This API doesn't support this configuration. Please change Environment variable AzureWebJobsSecretStorageType value to 'Files'. For more info, visit https://aka.ms/funcsecrets
   at Kudu.Core.Functions.FunctionManager.<GetKeyObjectFromFile>d__9`1.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Functions\FunctionManager.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Core.Functions.FunctionManager.<GetFunctionSecretsAsync>d__12.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Core\Functions\FunctionManager.cs:line 220
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kudu.Services.Functions.FunctionController.<GetSecrets>d__12.MoveNext() in C:\Kudu Files\Private\src\master\Kudu.Services\Functions\FunctionController.cs:line 141'.
```

This happens when I try and save my Logic App when it has a V2 .csproj style function in it.

I have read a ton of articles and posts. The problem is, i am unable to revert to File storage. If I set the suggested app setting, my Function app wont even start.

![image](https://user-images.githubusercontent.com/2934507/55411146-baa6ed00-552a-11e9-87ff-0cbd591e23a6.png)

**Comment by VictorioBerra** [comment]
Sorry, I saved my issue prematurely. I added the appropriate info now.

**Comment by VictorioBerra** [comment]
Somehow it finally started working with "Files". Before when I set `AzureWebJobsSecretStorageType` to `Files`, my function would refuse to start. My Logic App would get an access denied error as well.

**Comment by VictorioBerra** [comment]
I think I fixed it by switching my storage account to a V2 account.

**The CLI defaults to a V1 storage account, even though the UI seems to now default to 2. I propose we change the CLI `--kind` flag to default to V2!** https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#az-storage-account-create

**Comment by mhoeger** [comment]
@VictorioBerra - Glad you found a resolution! Can you tell us what steps were involved to get to this state? Which UI are you referring to and what azure CLI commands did you run? (Sorry, my context is purely azure functions so I'm not quite sure what all the steps run to integrate with logic apps are!)

**Comment by VictorioBerra** [comment]
I meant the portal. But I am not able to reproduce or remember everything I did at this point since I was trying so many things to resolve the issues. Sorry I can't be more help.

I think the final resolution involved blowing away my function and creating a new one via the az cli but this time specifying v2 storage.
