### ISSUE TITLE
AI: Local storage access has resulted in an error (User: ) (CustomFolder: ).

### ISSUE THREAD

**Issue by michael-chi** [Azure/azure-functions-host#4263]
Using Python for Azure Function with Application Insights Integration enabled to log trace messages.
Not all logs were written to application insights, I've also found an error message in application insights.
```
AI: Local storage access has resulted in an error (User: ) (CustomFolder: ). If you want Application Insights SDK to store telemetry locally on disk in case of transient network issues please give the process access to %LOCALAPPDATA% or %TEMP% folder. If application is running in non-windows platform, create StorageFolder yourself, and set ServerTelemetryChannel.StorageFolder to the custom folder name. After you gave access to the folder you need to restart the process. Currently monitoring will continue but if telemetry cannot be sent it will be dropped. Error message
```

#### Investigative information

Please provide the following:

- Timestamp: 2019-04-04T00:48:49.189 (UTC)
- Function App version (1.0 or 2.0): 2.0
- Function App name: michi-hactl-func
- Function name(s) (as appropriate): StagingHandler or DevHandler
- Invocation ID: N/A
- Region: East Asia

#### Repro steps

Provide the steps required to reproduce the problem:

Sample codes
```python
# ...
import logging
# ...
logging.info("some logs...")
```
1. Deploy to Function Apps
2. Enable Application Insights integration
3. Start Function
4. Check logs in Application Insights
5. As we are using Python, there is no way to set StorageFolder in codes.

#### Expected behavior

Should have all trace messages in application insights

#### Actual behavior

Some trace messages are missing, and an error indicates required folder were not created/no permission to access

#### Known workarounds

N/A

#### Related information 

Provide any related information 

* Programming language used : Python
* Links to source : Please PM if required
* Bindings used : Blob Trigger, Service Bus Queue Trigger, Service Bus Queue binding
<!-- Uncomment this if you want to include your source (wrap it in details to make browsing easier)

**Comment by mhoeger** [comment]
@maiqbal11 , @ahmelsayed - looks like this is linux related?

**Comment by maiqbal11** [comment]
@brettsam as well to see if we he has seen this kind of issue before

**Comment by michael-chi** [comment]
It's Python for Azure Function, and we are using Application Insights integration feature instead of coding with Application Insights SDK. We've been using C# and Node before but this is first time see this.

**Comment by brettsam** [comment]
This is likely due to our usage of the App Insights ServerTelemetryChannel, which will store logs locally if there's an issue with flushing them to the service. It'll then pick them up and try again later. It looks like this requires the path to exist so that those logs can go somewhere. But this is likely a rare scenario.

The reason you're missing logs is likely due to sampling. Disable sampling if you want to see everything: https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#configure-sampling. If that doesn't work, let me know and we can keep investigating.

**Comment by ahmelsayed** [comment]
what is that folder? Is this something you can create before using or should the platform provide it?

**Comment by brettsam** [comment]
@lmolkova -- is this something we'll need to handle ourselves on Linux workers? We could auto-create the folder and set that property...

**Comment by lmolkova** [comment]
@brettsam indeed, I forgot to configure telemetry channel to support temp storage.

Here is the doc that explains it (FAQ 6) - this is just one line
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core-no-visualstudio#frequently-asked-questions

You probably have more insights on which tmp folder to use in Functions.

**Comment by abkeble** [comment]
@lmolkova I seem to be having the same issue with my Azure Python Function App. I have followed the link to the FAQ you provided and see that I need to configure a local folder for the telemetry channel, however I am unsure how I would convert the C# example into Python. Were you able to do this in Python?

**Comment by dtxrich** [comment]
I am also seeing this issue. Any ideas how to fix this for python?

**Comment by Josh-a-e** [comment]
Any progress here? I'm seeing this too.

**Comment by amtandon** [comment]
So this happens in a C# function also. I am running a BLOB trigger function in docker with app insights enabled. I get the error below. The function then terminates at which point the container restarts.

_AI: Local storage access has resulted in an error (User: ) (CustomFolder: ). If you want Application Insights SDK to store telemetry locally on disk in case of transient network issues please give the process access to %LOCALAPPDATA% or %TEMP% folder. If application is running in non-windows platform, create StorageFolder yourself, and set ServerTelemetryChannel.StorageFolder to the custom folder name. After you gave access to the folder you need to restart the process. Currently monitoring will continue but if telemetry cannot be sent it will be dropped. Error message: ._

**Comment by macrogreg** [comment]
I am also seeing this in a C# Function running on a Linux Consumption Plan.

**Comment by shayannyc25** [comment]
i am getting same kind of error in the App Insights dashboard of  my azure java function. the log level of my azure function host is Information.  Error i get in the App Insights is:

AI: Local storage access has resulted in an error (User: app) (CustomFolder: ). If you want Application Insights SDK to store telemetry locally on disk in case of transient network issues please give the process access to %LOCALAPPDATA% or %TEMP% folder. If application is running in non-windows platform, create StorageFolder yourself, and set ServerTelemetryChannel.StorageFolder to the custom folder name. After you gave access to the folder you need to restart the process. Currently monitoring will continue but if telemetry cannot be sent it will be dropped. Error message:

**Comment by GustavoAmerico** [comment]
[See this doc](https://docs.microsoft.com/pt-br/azure/azure-monitor/app/telemetry-channels#configuration-in-code-for-aspnet-core-applications).
it's worked for me.

**Comment by older** [comment]
@GustavoAmerico This is workaround, but ideally you shouldn't be doing it yourself in azure functions, as telemetry configuration is done by azure functions host for you.

**Comment by mhoeger** [comment]
+@Hazhzeng and @vrdmr for error with application insights on linux workers

**Comment by divyagandhisethi** [comment]
I have another CRI with this same issue on Linux. @fabiocav / @brettsam does this issue need to be assigned to an owner?

**Comment by brettsam** [comment]
I'll assign this to our next sprint so we can find an owner. We'll need to take these steps: https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#if-i-run-my-application-in-linux-are-all-features-supported. 

@divyagandhii -- is there a write-able temp storage location we can use on the Linux workers (for both consumption and dedicated)? If so, we can create a folder there and point to it.

@lmolkova -- do you know what folder the ServerTelemetryChannel writes to by default in Windows? Ideally we'd mimic the naming for Linux.

**Comment by divyagandhisethi** [comment]
For linux dedicated, it should be easy enough once we discuss it with the Linux team. For linux consumption, I will have to look more, I will get back to you on this.

**Comment by petrkoutnycz** [comment]
I'm seeing the same issue for App service running on Linux.

**Comment by infact** [comment]
`AI: Local storage access has resulted in an error (User: ) (CustomFolder: ). If you want Application Insights SDK to store telemetry locally on disk in case of transient network issues please give the process access to %LOCALAPPDATA% or %TEMP% folder. If application is running in non-windows platform, create StorageFolder yourself, and set ServerTelemetryChannel.StorageFolder to the custom folder name. After you gave access to the folder you need to restart the process. Currently monitoring will continue but if telemetry cannot be sent it will be dropped. Error message: .   `   I see this error in app insights. I am trying to execute python code from azurefunction.

**Comment by FinVamp1** [comment]
On Windows it should write to %LOCALAPPDATA%\Microsoft\ApplicationInsights\ as per my local testing. 

With the release 2.15.0-beta3 and greater local storage is now automatically created for Linux, Mac, and Windows. For non Windows systems the SDK will automatically create a local storage folder based on the following logic:

${TMPDIR} - if ${TMPDIR} environment variable is set this location is used.
/var/tmp - if the previous location does not exist we try /var/tmp.
/tmp - if both the previous locations do not exist we try tmp.

From  https://docs.microsoft.com/en-us/azure/azure-monitor/app/telemetry-channels#configurable-settings-in-channels 

Here's the PR https://github.com/microsoft/ApplicationInsights-dotnet/pull/1860

**Comment by chadleong** [comment]
I'm getting this error too on a simple Azure Function test. This also resulted in a prop_status failed, not entirely sure if its related.

_**Executed 'Functions.update_data' (Failed, Id=xxxx-xxxxx-xxxx-xxxx, Duration=38ms)**_

```
from typing import List
import logging
import azure.functions as func

def main(events: List[func.EventHubEvent]):
    for event in events:
        logging.info('Python EventHub trigger processed an event: %s',
                        event.get_body().decode('utf-8'))
```

`AI: Local storage access has resulted in an error (User: app) (CustomFolder: ). If you want Application Insights SDK to store telemetry locally on disk in case of transient network issues please give the process access to %LOCALAPPDATA% or %TEMP% folder. If application is running in non-windows platform, create StorageFolder yourself, and set ServerTelemetryChannel.StorageFolder to the custom folder name. After you gave access to the folder you need to restart the process. Currently monitoring will continue but if telemetry cannot be sent it will be dropped. Error message: .`

**Comment by jochenvw** [comment]
Hi - I'm getting the same error in a C# Azure Durable function. Not sure whether I can tag along in this issue or whether you want me to create a new one.

```
AI: Local storage access has resulted in an error (User: ) (CustomFolder: ).  ... etc
--
```
For context - I'm using Azure Durable functions to work through 1 million items. I see approx. 70 K function executions per minute and then after 2 minutes things stop working and this is the last trace message I find in App Insights. Am I getting this error because the local buffer of AppInsights messages is full or stops responding because of the number of telemetry messages that are generated? 
If that is so - I can probably do something with tweaking the [host.json](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json) file and modifying these:

```
  "logging": {
        "fileLoggingMode": "debugOnly",
        "logLevel": {
          "Function.MyFunction": "Information",
          "default": "None"
        },
        "applicationInsights": {
            "samplingSettings": {
              "isEnabled": true,
              "maxTelemetryItemsPerSecond" : 20,
              "evaluationInterval": "01:00:00",
              "initialSamplingPercentage": 100.0, 
              "samplingPercentageIncreaseTimeout" : "00:00:01",
              "samplingPercentageDecreaseTimeout" : "00:00:01",
              "minSamplingPercentage": 0.1,
              "maxSamplingPercentage": 100.0,
              "movingAverageRatio": 1.0,
              "excludedTypes" : "Dependency;Event",
              "includedTypes" : "PageView;Trace"
            },
            "enableLiveMetrics": true,
            "enableDependencyTracking": true,
            "enablePerformanceCountersCollection": true,            
            "httpAutoCollectionOptions": {
                "enableHttpTriggerExtendedInfoCollection": true,
                "enableW3CDistributedTracing": true,
                "enableResponseHeaderInjection": true
            },
            "snapshotConfiguration": {
                "agentEndpoint": null,
                "captureSnapshotMemoryWeight": 0.5,
                "failedRequestLimit": 3,
                "handleUntrackedExceptions": true,
                "isEnabled": true,
                "isEnabledInDeveloperMode": false,
                "isEnabledWhenProfiling": true,
                "isExceptionSnappointsEnabled": false,
                "isLowPrioritySnapshotUploader": true,
                "maximumCollectionPlanSize": 50,
                "maximumSnapshotsRequired": 3,
                "problemCounterResetInterval": "24:00:00",
                "provideAnonymousTelemetry": true,
                "reconnectInterval": "00:15:00",
                "shadowCopyFolder": null,
                "shareUploaderProcess": true,
                "snapshotInLowPriorityThread": true,
                "snapshotsPerDayLimit": 30,
                "snapshotsPerTenMinutesLimit": 1,
                "tempFolder": null,
                "thresholdForSnapshotting": 1,
                "uploaderProxy": null
            }
        }
    },

```
Right? I don't want to do sampling because I need to see whether everything has executed - so perhaps raise the log level.

**Comment by brettsam** [comment]
This appears to have wilted without an owner. I'm going to assign to myself for next sprint.

**Comment by cormacpayne** [comment]
@brettsam Hey Brett -- do you happen to know when this fix will be published to the set of `Microsoft.Azure.WebJob` packages on NuGet? We're looking to pick up this fix in the 3.0.26 version of `Microsoft.Azure.WebJobs.Logging.ApplicationInsights` as soon as it's released ☺️

**Comment by Gamecock** [comment]
Still seeing in python function app
`

AI: Local storage access has resulted in an error (User: app) (CustomFolder: ). If you want Application Insights SDK to store telemetry locally on disk in case of transient network issues please give the process access to %LOCALAPPDATA% or %TEMP% folder. If application is running in non-windows platform, create StorageFolder yourself, and set ServerTelemetryChannel.StorageFolder to the custom folder name. After you gave access to the folder you need to restart the process. Currently monitoring will continue but if telemetry cannot be sent it will be dropped.
--


`

**Comment by emanuel-virca** [comment]
I am experiencing the same issue using service bus queue triggered function on Linux Consumption plan with azure function written in c#.
