### ISSUE TITLE
Passing a `Stream` TypedData for a blob output binding doesn't create the blob correctly.

### ISSUE THREAD

**Issue by daxian-dbw** [Azure/azure-functions-host#4264]
This happens in the PowerShell worker.
In the function script, a file stream is created from a local file, and the stream object is returned as the output value for the blob output binding.

```powershell
$outStream = [System.IO.FileStream]::New("$env:TEMP\expand\text.txt", "Open", "Read")
push-outputbinding -name outBlob -value $outStream
```

The PowerShell worker creates a `Stream` TypedData object from the file stream:
![image](https://user-images.githubusercontent.com/127450/55597319-d6182080-5701-11e9-9d1a-4fc49d6527d0.png)

And as you can see in the screenshot below, the TypedData object does have its `Stream` property correctly populated:
![image](https://user-images.githubusercontent.com/127450/55597349-fd6eed80-5701-11e9-8d42-b0c0062f22df.png)

After the response is sent to the Host, the blob gets created, but with no content at all:
![image](https://user-images.githubusercontent.com/127450/55597399-432bb600-5702-11e9-8ade-ac8384a67583.png)

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0): 2.0
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

#### Repro steps

Provide the steps required to reproduce the problem:

function.json
```json
{
    "bindings": [
        {
            "authLevel": "function",
            "type": "httpTrigger",
            "direction": "in",
            "name": "req",
            "methods": [
                "get",
                "post"
            ]
        },
        {
            "type": "blob",
            "name": "inBlob",
            "direction": "in",
            "dataType": "binary",
            "path": "samples-input/text.zip"
        },
        {
            "type": "blob",
            "name": "outBlob",
            "direction": "out",
            "path": "samples-output/string.txt"
        }
    ]
}
```
run.ps1:
```powershell
param($req, [byte[]] $inBlob)

"Blob size (bytes): $($inBlob.Length)"
$tempFile = Join-Path -Path $env:TEMP -ChildPath "text.zip"
Remove-Item $tempFile -ErrorAction SilentlyContinue
Set-Content -Path $tempFile -Value $inBlob -AsByteStream

$tempFolder = "$env:TEMP\expand"
Remove-Item $tempFolder -Recurse -Force -ErrorAction SilentlyContinue

Expand-Archive -Path $tempFile -DestinationPath $tempFolder
Get-ChildItem "$env:TEMP\expand"

$outStream = [System.IO.FileStream]::New("$env:TEMP\expand\text.txt", "Open", "Read")
push-outputbinding -name outBlob -value $outStream
```

#### Expected behavior

The blob content should be the same as the local file since the stream is created using that file.

#### Actual behavior

The blob has no content.

#### Known workarounds

Provide a description of any known workarounds.

It works as expected if I use the byte array of the local file content as the output value.

#### Related information 

Provide any related information 

* Programming language used: PowerShell
* Links to source
* Bindings used: blob output binding

**Comment by mhoeger** [comment]
@daxian-dbw - can you try debugging into the functions host and see what the content becomes when sent over the wire? In particular, I would recommend stepping into [this code](https://github.com/Azure/azure-functions-host/blob/743089948f6d6212fa0374b40a1a9c323ec204c6/src/WebJobs.Script/Rpc/LanguageWorkerChannel.cs#L447-L462) where the invocation response is processed and [this code](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/MessageExtensions/RpcMessageConversionExtensions.cs#L29-L31) where the rpc message is deserialized.

It's also worth noting that we don't properly support stream messages yet, so they should be handled the exact same way as a byte[]!
