### ISSUE TITLE
Timer Triggers no longer sync between functions using the same storage account since migrating to V2

### ISSUE THREAD

**Issue by luthus** [Azure/azure-functions-host#4265]
We have the following function apps:
AzureFunctionProd - North Europe
AzureFunctionDR - West Europe

These apps both share the same underlying storage account and have the same id (e4d7158f548949738591b79574453212) set in the host.json file. This is based on the documentation here:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer#function-apps-sharing-storage

Using Azure Functions V1, this all worked fine, only one of the apps triggered on the timer at a time. We've since migrated the apps to Azure Functions V2 using the exact same setup, but the timers have been triggering on both apps since migrating. We've had to stop the DR apps.

I've had a look at the storage account to try to figure out why this was happening. It appears that the singleton locks are no longer saving to the correct location. 

For Azure Functions V1 the following folder was used:
azure-webjobs-hosts/timers/e4d7158f548949738591b79574453212

For Azure Functions V2 the following folders were used:
azure-webjobs-hosts/timers/AzureFunctionProd
azure-webjobs-hosts/timers/AzureFunctionDR

It appears to be ignoring the id value that we're setting in the host.json file altogether.

**Comment by mathewc** [comment]
Yes, in V2 we've removed host ID config from host.json, because for most scenarios this causes problems for people. However, you can still set it via app settings. Try setting the host ID in your Function App settings. the setting name to use is **AzureFunctionsWebHost:hostid**. @fabiocav that's the correct setting path, right?

**Comment by luthus** [comment]
@mathewc looks like this worked. In that case it appears that the linked documentation is just out of date. 

Thanks

**Comment by alrod** [comment]
AzureFunctionsWebHost:hostid is worked fro V2
