### ISSUE TITLE
Proxy a website

### ISSUE THREAD

**Issue by AnassKartit** [Azure/azure-functions-host#4266]
#### Is your question related to a specific version? If so, please specify:
No
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question
How to use Azure function proxies to proxify a full website and rewrite the URL?

**Comment by mhoeger** [comment]
What do you mean by "proxify"? Here is the official documentation on [functions proxies](https://docs.microsoft.com/en-us/azure/azure-functions/functions-proxies) as well as a few fleshed out examples in [this documentation](https://docs.microsoft.com/en-us/sandbox/functions-recipes/proxies). If you are looking to map a custom domain to a function app, (i.e. map your domain name => function app), [this documentation](https://docs.microsoft.com/en-us/azure/azure-functions/scripts/functions-cli-configure-custom-domain) will show you how.
