### ISSUE TITLE
Duplicate Application Insights traces

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#4268]
From @TobiasBengtsson [here](https://github.com/Azure/azure-functions-host/issues/1627#issuecomment-479853326):

> I am facing the same issue when checking the logs in Application Insights.
> 
> I know that 901 actual requests were sent to the Function HTTP endpoint.
> 
> The Kusto query in Application Insights traces | where operation_Name == "MyHttpTriggerFunction" | where message startswith "Executing" | count returns 911 responses. I've tracked down 10 duplicates that have the exact same timestamp, Id and operation_Id.
> 
> Even worse, under Home > App Services > MyFunction - MyHttpTriggerFunction, under the "Monitor" tab, I see 961 executions.
> 
> I'm worried that we'll have to pay for the higher amount of shown executions which would be a 7% extra cost compared to reality.
> 
> (The names of the app and function are fictitious)

**Comment by brettsam** [comment]
@TobiasBengtsson -- we've seen people have duplicate traces before, but they were always doing it themselves accidentally. Are you doing anything custom with dependency injection or logging in your Functions?

Some additional questions:
- Can you share some of the traces that you're seeing duplicates of? Are all properties exactly the same?
- In the Monitor tab, the query is for Requests (there's a link to the exact query in the tab itself). If you look at the raw kusto query results, do you see those additional Requests? Are there duplicates there?
- Can you share your function app name with us ([privately if you'd like](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)) and let us know the timeframe you're looking at?

**Comment by TobiasBengtsson** [comment]
Thank you for opening a new ticket @brettsam .

Below are some of the details of one of the executions that was logged twice, enough for you to identify the function that was called. All the properties in Application Insights are the same, including all ID:s. All 901 requests were sent at around the same time (+- a minute or so). From what I can see I'm not doing any fancy stuff with logging, it's still a fairly simple function at this stage.

- Timestamp: 2019-04-03T19:39:15.427
- Id: 974be49a-f21c-40e3-9c7c-e41b7e66466c
- Region: West Europe

All Kusto queries that I try seems to tell the same thing, for example I get 10 rows with the query

`traces | where operation_Name == "MyHttpTriggerFunction" | project message, operation_Id  | where message contains "Executing" | summarize count(operation_Id) by operation_Id
| where count_operation_Id > 1`

**Comment by TobiasBengtsson** [comment]
When it comes to querying requests in Kusto, I get 60 duplicates with the following query which seems logical considering that the count in the Monitor tab was 60 too high.

`requests | project timestamp, id, operation_Name, success, resultCode, duration, operation_Id, cloud_RoleName | where timestamp > ago(30d) | where cloud_RoleName =~ 'my-function-app' and operation_Name == 'MyHttpTriggerFunction' | order by timestamp desc | summarize count(id) by id | where count_id > 1`

**Comment by brettsam** [comment]
@lmolkova could App Insights be retrying an upload of telemetry that it thought had failed, resulting in dupes?

@TobiasBengtsson I see no indication that the Id you provided was actually run twice. There's only one log for the invocation in our backend logs, but checking the counts like Paul suggested in the other thread will give you the true answer.

**Comment by TobiasBengtsson** [comment]
@brettsam That is positive, also viewing Function Execution Units in the Metrics Explorer seems to give a correct count. So it seems to be an issue with logging.
I checked the code that is deployed and it is very simple indeed:
`        [FunctionName("MyHttpTriggerFunction")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "POST", Route = "foo/bar/endpoint")] HttpRequest req,
            ILogger log)
        {
            string requestBody = await
                new StreamReader(req.Body)
                .ReadToEndAsync();

            log.LogInformation(requestBody);
            return new OkResult();
        }`

**Comment by lmolkova** [comment]
@TobiasBengtsson 

Can you check a few things, please?

1.  Check that duplicates have the same itemId
2. check that it is common for requests and dependencies
3. Are there any specific timestamp ranges when it was happening?

It seems there could be some intermittent issues on the ingestion of ApplicationInsights that create this duplication. But it does not seem to be constant and might be related to specific incidents.

May I ask you to create Azure Support ticket for this? Please refer to this github issue and ask to forward to ApplicationInsights Ingestion team?

Please provide attach  the result of this query:

```requests | where timestamp >= ago(30d) | project timestamp,  id | summarize count(id) by id| where count_id > 1
| join (requests | where timestamp >= ago(30d)) on id | project timestamp, id, itemId```

**Comment by brettsam** [comment]
Since it looks like this is being handled via a separate Support ticket, I'm going to close. Please feel free to re-open if we need more investigation on the Functions side.
