### ISSUE TITLE
WEBSITE_LOAD_CERTIFICATES setting breaks Install-PackageProvider

### ISSUE THREAD

**Issue by alunmj** [Azure/azure-functions-host#4269]
#### Investigative information

Please provide the following:

- Timestamp: April 3-5, 2019
- Function App version (1.0 or 2.0): 1.0
- Function App name: azsubmon
- Function name(s) (as appropriate): TestAssumptions
- Invocation ID:
- Region: Central US

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create PowerShell function
2. Include the command "Install-PackageProvider NuGet -Scope CurrentUser -Force" in the function.
3. Run the function.
4. Set the Application Setting "WEBSITE_LOAD_CERTIFICATES" to "*", or a certificate thumbprint.
5. Run the function.
6. Remove or rename the WEBSITE_LOAD_CERTIFICATES application setting and rerun the function.

#### Expected behavior

With or without WEBSITE_LOAD_CERTIFICATES setting, this should work. I'm pretty sure it worked for me prior to April 3.
Steps 3, 5, and 6 should result in the same output, indicating that Install-PackageProvider works independently of the WEBSITE_LOAD_CERTIFICATES setting.

#### Actual behavior

At step 5,  Install-PackageProvider now fails with an exception indicating that the Destination Path has not been set. There is no parameter for Destination Path in Install-PackageProvider.
Steps 3 and 6 work as expected.

#### Known workarounds

Removing the WEBSITE_LOAD_CERTIFICATES setting seems to work around this issue, but since I'm trying to authenticate to an SPN with this certificate in this function, that doesn't seem right.

#### Related information 

Provide any related information 

* Programming language used 
Powershell
* Links to source
None needed - just the one command.
* Bindings used
Default

**Comment by mhoeger** [comment]
Hi @alunmj , I'm going to mark this as a "wontfix" item because we aren't investing in our 1.0 powershell support (note its [experimental status](https://docs.microsoft.com/en-us/azure/azure-functions/supported-languages)).

Although I can't give an exact date, powershell support for functions 2.0 is coming very soon, and I hope that resolves any issues you have :) 

See work in progress here: https://github.com/Azure/azure-functions-powershell-worker

**Comment by alunmj** [comment]
OK, thanks - at least I'm not doing anything obviously wrong, then, which was most of my concern.
