### ISSUE TITLE
Python placeholders

### ISSUE THREAD

**Issue by maiqbal11** [Azure/azure-functions-host#4273]
Enable Python placeholders in Linux.

**Comment by fabiocav** [comment]
Blocked on breaking changes announcement period

**Comment by fabiocav** [comment]
@maiqbal11 we should be able to move forward with this. Deployment would only happen at the end of sprint 49

**Comment by maiqbal11** [comment]
We are messaging with a 25th May deadline for this breaking change: https://github.com/Azure/app-service-announcements/issues/169. Including this as part of the Sprint 50 release.
