### ISSUE TITLE
All functions return 'The operation has timed out.' after deploy

### ISSUE THREAD

**Issue by sylvaingirardbe** [Azure/azure-functions-host#4275]
#### Investigative information

- Timestamp: 2019-04-08 17:57:29.250Z
- Function App version (1.0 or 2.0): 2.0
- Function App name: 
- Function name(s) (as appropriate): validate-url, aggregator
- Invocation ID: 1a649072-8a7b-40e7-a300-2a37baa158df
- Region: West Europe

#### Repro steps

Not sure if it is reproducible, it happened after a deploy from vscode on mac. Seems that only the production app was affected, which makes it even more of a bummer. Trying a new deploy on the staging environment didn't cause any problems.

#### Expected behavior

After I deploy from vscode, I expect that functions keep working like they were doing just before.

#### Actual behavior

Functions started to return 500 errors, even the ones that weren't affected by the deploy. Upon further investigation, the 500 was caused by a 'The operation has timed out.' error.

#### Known workarounds

I thinks it was solved by restarting the app service or it was a coincidence.

#### Related information 

* Programming language used: typescript
* Bindings used: http trigger

**Comment by brettsam** [comment]
Hi @sylvaingirardbe -- I'm just looking at this, sorry for the delay. It looks like the deployment you did may have taken a long time to unpack and get running again, which could explain the errors you were seeing. Have you enabled "run from package" on your site? It can help with issues like this. You'd set an app setting of `WEBSITE_RUN_FROM_PACKAGE` to `1`.

https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#enabling-functions-to-run-from-a-package

**Comment by alrod** [comment]
@brettsam already explained  'The operation has timed out.' errors.
@sylvaingirardbe, feel free to reopen the issue if you still have the issue.
