### ISSUE TITLE
Generic approach for performance tests

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-host#4278]
This change will allow easy way to add/run a new performance scenario:
1. Add new scenario code, scenario config, JMeter test definition (jmx file).
2. Check in the change to scenario repository.
3. New scenario will be picked up automatically on next performance tests run.

Scenarios (https://github.com/Azure/azure-functions-performance-scenarios)
* add a config for each scenario (id, runtime, description, threshold, function app name to deploy). 
* add a jmx file for each scenario .

Modify the VM agent run PS script (https://github.com/Azure/azure-functions-host/blob/dev/tools/WebJobs.Script.Performance/WebJobs.Script.Performance.App/Artifacts/PS/run.ps1:
* clone scenarios repository
* build "run-from-zip" for the scenario (or for all scenarios)
* upload"run-from-zip"s to blob storage
* generate "run-input" for the performance app (https://github.com/Azure/azure-functions-host/tree/dev/tools/WebJobs.Script.Performance/WebJobs.Script.Performance.App)

**Comment by fabiocav** [comment]
This has been done.
