### ISSUE TITLE
Disabling TimeTrigger Singelton

### ISSUE THREAD

**Issue by batizar** [Azure/azure-functions-host#4288]
Is there a way to disable `Singleton` for `TimerTrigger` and make it run on all instances? 

Thanks.

**Comment by mhoeger** [comment]
@batizar - what's the use case?

**Comment by mhoeger** [comment]
Also related: https://github.com/Azure/azure-webjobs-sdk-extensions/issues/428

**Comment by batizar** [comment]
@mhoeger thanks. Ended up just adding `IHostedService` implementation with `AddHostedService`, just wanted run a code on every instance periodically. It was actually better this way because I am not getting the default information log noises from trigger this way.

**Comment by fabiocav** [comment]
@batizar please be aware that injected `IHostedService` instances in functions is not a supported scenario and not guaranteed to work. This may be disabled in the future as we can not ensure reliable operation of those services.
