### ISSUE TITLE
Microsoft.EntityFrameworkCore.SqlServer 2.2.2+ -- Error indexing method

### ISSUE THREAD

**Issue by espray** [Azure/azure-functions-host#4290]
Fail to index when using EFCore 2.2.2 or greater.

- Azure Functions Core Tools (2.5.553 Commit hash: b63f2d6f5479718ca276f7b585a8cc6b9bc57c4f)
- Function Runtime Version: 2.0.12382.0
```
[4/9/2019 1:21:42 PM] Error indexing method 'TokenFunction'
[4/9/2019 1:21:42 PM] Microsoft.Azure.WebJobs.Host: Error indexing method 'TokenFunction'. IdentityServer: Method Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.AddDbContext: type argument 'IdentityServer.HostDbContext' violates the constraint of type parameter 'TContext'.
```

```
    <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.9.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.ApplicationInsights" Version="2.9.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="2.2.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.4.0" />
  </ItemGroup>
```

**Comment by mhoeger** [comment]
The workaround is to downgrade to 2.2.0 (although users have noted that there are security issues in 2.2.0). 

Dupe of https://github.com/Azure/azure-functions-host/issues/4006, where we will track any updates!

**Comment by espray** [comment]
@mhoeger Thanks for the reply! Slightly different in that Microsoft.EntityFrameworkCore.SqlServer Version="2.2.1" appears to be working. Otherwise the same. Feel free to close.

**Comment by fabiocav** [comment]
Will likely keep this one open and close the other issue as the the issue with 2.2.1 should be resolved. Will follow up there.

**Comment by espray** [comment]
@fabiocav - Assembly loading has been a sore spot, similar issues with Newtonsoft.Json being stuck on 11.0.2. Assembly loading has gotten better, will/can this get better over time? Or are we are just going to have to deal with some incompatibility/lag with a few package?

**Comment by fabiocav** [comment]
@espray can you expand with more details about the challenges you're facing? 

JSON.NET is not locked from a runtime perspective (if you're referring to package requirements, we're about to relax that as well).

The key limitation that exists today is for framework releases (.NET Core/ASP.NET Core), where you can't adopt those until functions does. And we're responding to those as quickly as possible and improving that turnaround.
