### ISSUE TITLE
Aggressive scaling?

### ISSUE THREAD

**Issue by NickMoores** [Azure/azure-functions-host#4294]
#### Is your question related to a specific version? If so, please specify: 
Azure Functions 2

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All): 
C#, .NET Core

#### Question
Hi,

I noticed recently, via AppInsights, that the performance of our Azure Functions have decreased on average by about 200-400%. In trying to investigate this a bit further, I've found that a lot more cold starts are occurring than I was previously used to seeing, and I believe that this is caused by some aggressive scaling out of the hosts running our functions.

I'm trying to narrow down when I think this may have started, but believe it's within the past couple of months.

For example, over the past 10 minutes our application has scaled to 13 instances processing incoming Event Grid messages, with approximately one message arriving every 5 seconds, and each message being processed in under 100ms (when warm). I am a little surprised to see it scale like this, especially as my understanding after reading some of the documentation is that the scale controller makes scaling decisions based on the incoming queue lengths and the length of time that the messages sit in the queues. I would expect the queue lengths to be 0, and for the messages to be dispatched immediately and processed in around a tenth of a second. Based on this I'm surprised that, with our current message rate, the controller has decided that 13 instances are required.

Are there any other factors that are considered by the scale controller? The only other thing I can think of is that our application usually receives events at a rate of exactly one per minute, but it receives bursts of messages during sporting events for about two hours - which tonight is peaking at about an event every 5 seconds - but I'm still surprised to see it scale out to 13 instances.

Thanks,
Nick

**Comment by fabiocav** [comment]
@NickMoores would you be able to share an invocation id, region and a timeframe so we can take a deeper look at the issue?

**Comment by NickMoores** [comment]
Hi @fabiocav , sure can!

Invocation ID:  f085c3de-9c3b-41f6-aee4-30aae942437b
Region: North Europe
Timeframe: 1940->2000 (BST)

In this timeframe, it scaled from 1 instance to 13 as the message rate increased.

Thanks for taking a look!
Nick

**Comment by NickMoores** [comment]
Hi there,

Interestingly, this seems problem seems to have rectified itself some time between the 14th and 19th April...

On the 13th April, we had 27 different roles processing our events, but on 19th (with events being generated even more frequently) we had just a single role processing the events, with the average performance improving considerably in the latter case.

Unsure if a release has caused this change, but it has been markedly improved recently.

Thanks,
Nick

**Comment by fabiocav** [comment]
@NickMoores that's great to hear. Closing this as resolved.
