### ISSUE TITLE
Rethrow RpcException on invocation as InvocationException

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#4296]
Related incident #4192 
RpcException on invocation failure is confusing. Need to rethrow it as InvocationException instead.

**Comment by liliankasem** [comment]
When an `RpcException` is logged in Application Insights, the exception starts with `Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException`, this makes it seem like a platform error but in almost every case it is an unhandled user code exception. The suggestion here is to create a new exception to make it clear that this is a user code issue, i.e. `InvocationException`. Whilst creating this new exception, it is also a good opportunity to add more information to the exception we throw. This will be a breaking change and should be put behind a flag.

Anyone picking up this issue should flesh out the design for the new exception before implementation.

> Worth noting [FunctionInvocationException](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/FunctionInvocationException.cs) already exists in the WebJobs SDK. Part of this issue will be to determine if we reuse that or create a new one

**Comment by JustinGrote** [comment]
Thank you @liliankasem,

I really want the full exception details in Application Insights one way or the other, if the worker has a way to hook and deliver the worker-specific exception to application insights before it also ends up showing up as an invocationexception, that is ideal.

The story I want is that when I go to Application Insights and click the Exceptions tab, whether I am in the Powershell worker or another worker, that my specific exception types show up in the list and I don't have to deal with filtering for an innerexception. Just replacing 5000 "RPCException" with 5000 "InvocationException" doesn't meet this need, I expect to see "HttpRequestException" alongside "NullPointerException", etc. at the code level here.

This is not helpful;
![image](https://user-images.githubusercontent.com/15258962/161317143-824df5ae-340e-4e31-a915-1e1d2cb1f166.png)

I need those 123k exceptions broken down by their specific exception type.



These work items you linked doesn't seem to explicitly address this issue.

**Comment by ijagberg** [comment]
I would also like to see something like what JustinGrote [mentions](https://github.com/Azure/azure-functions-host/issues/4296#issuecomment-1086185108). It seems pretty pointless to just replace RpcException with InvocationException if you still have to do a bunch of custom query stuff to see what the actual exception being logged is.

I have code like the following:

```
try
{
    // Do stuff
} catch (Exception ex)
{
    if (ex is MyOwnCustomExceptionType customException)
    {
        _logger.LogError(customException, "I am logging my own custom exception");
    }
}
```

And all of these show up like this:
![image](https://user-images.githubusercontent.com/4225887/166922535-7f34e55b-0fef-4ee9-a162-b4fb83200f6a.png)

To be clear, these are not _unhandled_ exceptions, I catch the exceptions and log them, then continue running. So the description of this issue "RpcException on invocation failure is confusing" is not even correct, it's an issue regardless of whether the invocation fails or not.

**Comment by liliankasem** [comment]
We already have plans to address the concerns that Justin has mentioned, this is a two part feature. 

For the first part, we are redesigning how we log exceptions that come from user code in the host. The new approach will log the exception type and clean up the call stack so it will no long show up as an RpcException in the first place. The type will be the original exception type.

The second part will be moving the logging to the worker so that user code exceptions are logged directly, as they are with the full detail, to application insights instead of getting parsed by the host. That issue is tracked in the worker:

https://github.com/Azure/azure-functions-dotnet-worker/issues/846

**Comment by fabiocav** [comment]
The task here changed as we looked at the details, but work is currently in progress and expected in sprint 122. Moving to reflect that.

**Comment by fabiocav** [comment]
Work for this is in progress. Implementation mostly complete, but does require coordination with other language worker owners. Moving to sprint 123 to continue the work there.

**Comment by fabiocav** [comment]
PR is out and being iterated on. Moving to sprint 124.
