### ISSUE TITLE
[Supportability] Capture a memory dump on Consumption

### ISSUE THREAD

**Issue by cts-shrahman** [Azure/azure-functions-host#4300]
#### What problem would the feature you're requesting solve? Please describe.
How to capture a memory dump on Consumption? (CPU or memory)

#### Describe the solution you'd like
Need a profiler for Functions similar to what we have for Windows (puneetg)

**Comment by ankitkumarr** [comment]
@cts-shrahman, there is already an option to capture a memory dump on Windows Consumption. Are you talking specifically for Linux?

**Comment by ishepherd** [comment]
@ankitkumarr

> there is already an option to capture a memory dump on Windows Consumption

where?

* Kudu has a specific message saying cannot do a dump on consumption plan
* App Insights tries but doesn't seem to work
* Azureserviceprofiler.com I haven't tried lately, but I doubt it works

**Comment by ankitkumarr** [comment]
@ishepherd, I think you might be thinking about profiling instead of memory dump?

For memory dump, if you go to Kudu, click on "Process Explorer". Then find the process you need the dump for (probably w3wp.exe), click on "Properties", scroll down and click "Download memory dump".

**Comment by ishepherd** [comment]
Thanks @ankitkumarr, I had indeed confused the two. (Profiling would be very useful too! Any chance?)

I can get a memory dump file that way, but it's small and doesn't have anything of interest. VS says, "Process heap information is not present in the dump file".

**Comment by yeahsicy** [comment]
To get a full memory dump on Consumption, it's possible but indirect - Would need to leverage Application insights > Live Metrics Stream to locate the servers. 

For example, 
![image](https://user-images.githubusercontent.com/34499027/62904902-fcd40c80-bd1c-11e9-98e8-d6a6c5a9f333.png)

Previously, the server name was an actual ARRAffinity value that it's very easy to point to the specific instance. However, it was changed - more steps are needed to achieve this. 

**Keys:** 
1. Go to the app > App Service logs; Turn on Web server logging with “File system”. Go to Kudu Debug console; Navigate to D:\home\LogFiles\http\RawLogs where each log contains an ARR Affinity value (ARRAffinity=xxxxxx) for each function instance. 

2. Go to Kudu Environment > System info where you’d see Machine name and Instance id. Machine name is the current instance you're accessing via Kudu; Instance id is the ARRAffinity value of this instance. 

3. Use the browser Dev tool (F12) to specify the ARRAffinity value. You can specify the ARRAffinity cookie to change the instance as below. 
![image](https://user-images.githubusercontent.com/34499027/62905292-a4057380-bd1e-11e9-8b09-af88dbf79412.png)

**Here're the steps using above keys to get a full memory dump:** 
1. Find out what is the instance you want to investigate further in Application insights > Live Metrics Stream. Typically, it's with high CPU / Memory. 

2. Go to Kudu and try to access the instance by specifying ARRAffinity in Key 3 and checking the Machine name in Key 2 to make sure you're on the right one. 

3. Once you're on the right one, follow below links to get the full memory dump. 
https://blogs.msdn.microsoft.com/jpsanders/2017/02/02/how-to-get-a-full-memory-dump-in-azure-app-services/
https://docs.microsoft.com/en-us/sysinternals/downloads/procdump#using-procdump

**Comment by ishepherd** [comment]
Thanks so much for this @yeahsicy! Github did not notify me of your comment and I did not happen back onto this issue till today.
