### ISSUE TITLE
Detector: Outbound connections/Networking

### ISSUE THREAD

**Issue by cts-shrahman** [Azure/azure-functions-host#4302]
#### What problem would the feature you're requesting solve? Please describe.
Detector for outbound connections/networking

#### Describe the solution you'd like
Clarify what is the limit for example ([300 ](https://github.com/Azure/azure-functions-host/wiki/Host-Health-Monitor)or [1920
](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#per-sandbox-per-appper-site-numerical-limits))

**Comment by alrod** [comment]
cc: @ankitkumarr, this is already done
