### ISSUE TITLE
Security Issue:  httpOnly is ignored

### ISSUE THREAD

**Issue by cbailiss** [Azure/azure-functions-host#4303]
I have deployed a basic Azure function (AF v2 runtime).
In the portal I set HTTPS Only to "On".

However, I can still call the function over HTTP.

In the exported ARM template, I can see "httpsOnly": true.
I have tried restarting the function.
I can still call the function over HTTP.

Surely this is a security issue?
Is this similar to / a recurrence of https://github.com/Azure/Azure-Functions/issues/647  ?

**Comment by ahmelsayed** [comment]
Which OS/Platform are you running on in Azure? (Windows Dedicated, Windows Consumption, Linux Dedicated, Linux Consumption)?

**Comment by cbailiss** [comment]
Windows, .Net project (C#), Consumption plan.

**Comment by cbailiss** [comment]
Looks like this is now redirecting to HTTPS so closing the issue.
