### ISSUE TITLE
Allow DELETE verb for extension webhook routes

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-host#4308]
#### What problem would the feature you're requesting solve? Please describe.
The Durable Functions extension uses extension webhook routes to provide an HTTP API for the management of orchestrations. One management operation purges an orchestration instance's history from the underlying storage provider at the user's request. This is implemented as a DELETE endpoint in the extension. However, the Functions host does not recognize this endpoint during registration, leading to a 404 response, per azure/azure-functions-durable-extension#707

#### Describe the solution you'd like
Add logic to register DELETE endpoints from extension webhooks.

#### Describe alternatives you've considered
The purge webhook could be given an alternate route, such as `POST /instances/{id}/purge`. However, this is not in the spirit of a RESTful service, which the Durable HTTP API tries to be.

#### Additional context

**Comment by fabiocav** [comment]
Closed by #4311
