### ISSUE TITLE
Document DB error : Authorization token doesn't present sufficient permission to serve the request

### ISSUE THREAD

**Issue by JishnuSidh** [Azure/azure-functions-host#4312]
While trying to insert 50000 records into cosmos db using azure data factory or data bricks the error : 'Authorization token doesn't present sufficient permission to serve the request' is thrown from cosmos DB. This occurs at random point. Sometimes around this occurs after inserting 4000 records or 30000 records and at times the the job is successful and all 50000 records are inserted cosmos DB.

**Comment by soninaren** [comment]
@JishnuSidh can you share the most recent app name and timestamp when this occurred?

Additionally could you provide the following information
#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0):
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

> If you don't want to share your Function App name or Functions names on GitHub, please be sure to provide your Invocation ID, Timestamp, and Region - we can use this to look up your Function App/Function. Provide an invocation id per Function. See the [wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) for more details. 

@brettsam and @ealsur any idea what could be causing this?

**Comment by ealsur** [comment]
Either the Cosmos DB Auth Key is read only, or it's a Token without permissions to operate on that particular container is the most common source of this message.

A stack trace would help determine where is it coming from.
