### ISSUE TITLE
Time trigger not working as expected

### ISSUE THREAD

**Issue by Raspbier** [Azure/azure-functions-host#4313]
Hello Github Community,

Currently i'm working with Azure Function version 2.5.553. My task is to create a time triggered Azure Function.
I am working locally.

#### Repro steps
I am working with Python 3.6.8 and VS Code 1.33

I followed this tutorial, to create the new function.
https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python

I created a TimeTriggerd function.

In function.json, i changed existing schedule to:
`"schedule": "* * * * * *"`

After run the function, it triggers every second. So everything is as expected.
If i change the schedule to:
`      "schedule": "0 * * * * *"	
`
The trigger stops instantly...
Is this a known issue or is there a fail at my side?

#### Expected behavior
Should run every minute.

#### Actual behavior
It is not triggering with schedule `"0 * * * * * *"`

#### Known workarounds
It triggers with schedule `"* * * * * * *"`
In the moment there is a digit in the schedule, no more trigger will run.

<summary>Source</summary>

```
import datetime
import logging

import azure.functions as func


def main(mytimer: func.TimerRequest) -> None:
    utc_timestamp = datetime.datetime.utcnow().replace(
        tzinfo=datetime.timezone.utc).isoformat()

    if mytimer.past_due:
        logging.info('The timer is past due!')

    logging.info('Python timer trigger function ran at %s', utc_timestamp)
```

#### Additional Information
https://docs.microsoft.com/de-de/azure/azure-functions/functions-bindings-timer#cron-expressions

**Comment by soninaren** [comment]
@Raspbier 
if you want timer trigger to run every minute the correct chrone expressions is : `0 */1 * * * *`
