### ISSUE TITLE
Check for null when parsing functionTimeout from host.json

### ISSUE THREAD

**Issue by jijohn14** [Azure/azure-functions-host#4332]
#### Investigative information
Same issue: https://github.com/Azure/azure-functions-host/issues/2468

Please provide the following:

- Timestamp: 04-18-2019 1000
- Function App version (1.0 or 2.0): 2x
- Function App name: Any
- Function name(s) (as appropriate): Any
- Invocation ID:
- Region:

#### Repro steps

Provide the steps required to reproduce the problem:

Set below attribute in host.json
"functionTimeout": null,

#### Expected behavior

Provide a description of the expected behavior.

Based on code, it should fail at  "if (value != null)" condition and set default timeout.
Based on 1x behavior, have unlimited timeout.
Documentation should be clear on the behavior.  Seems it was not addressed in https://github.com/Azure/azure-functions-host/issues/3603

#### Actual behavior

Provide a description of the actual behavior observed.

Gives start error: 
String was not recognized as a valid TimeSpan.

#### Known workarounds

Provide a description of any known workarounds.

Avoid setting null

**Comment by pragnagopa** [comment]
Copying the documentation from : https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#functiontimeout

Indicates the timeout duration for all functions. In a serverless Consumption plan, the valid range is from 1 second to 10 minutes, and the default value is 5 minutes. In an App Service plan, there is no overall limit and the default depends on the runtime version. In version 2.x, the default value for an App Service plan is 30 minutes. In version 1.x, it's null, which indicates no timeout.


Closing this issue as resolved. If still unclear, please open documentation issue : https://github.com/MicrosoftDocs/azure-docs with specific corrections to content you think are unclear.

**Comment by pragnagopa** [comment]
reopening as this an improvement issue to parse functionTimeout properly
