### ISSUE TITLE
Limitations for accessing the current user's name

### ISSUE THREAD

**Issue by chrsmith** [Azure/azure-functions-host#4337]
#### Is your question related to a specific version? If so, please specify:
No.

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
All

#### Question
I'd like to know what restrictions exist around accessing information about the current user or current disk when running within the Azure Functions host environment.

If you spawn a Golang process which calls the [user.Current](https://golang.org/pkg/os/user/#Current) API, it returns what appears to be a generic file not found error. (`The system cannot find the file specified.`) Similarly, the `%USERPROFILE%` env var is empty.

I assume this is by design, as part of locking down the runtime environment. But is there some documentation calling out the specific limitations of the Azure Functions Host? Specifically, what things are supported and what isn't? Is creation of a temp file allowed? What about writing to the current user's home directory?

Ultimately I'm trying to figure out what would be a reasonable thing to do for a tool if it is ran as part of the Azure Functions Host (https://github.com/pulumi/pulumi/issues/2636#issuecomment-482451768). What can I expect to work "like normal", and what things are restricted by the runtime?

**Comment by brettsam** [comment]
The functions host runs in the App Service sandbox -- the details of which you can find here: https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox. There are some differences depending on whether you're running in Consumption plan vs App Service plan, and I believe those differences are called out in that document. There's a section on file access here, for example: https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#file-system-restrictionsconsiderations.

For the %USERPROFILE% question, specifically -- if you go to {site}.scm.azurewebsites.net, you'll be able to see all the Environment variables available to you. On one of my sites, I see USERPROFILE = D:\local\UserProfile. How are you trying to access that variable?

**Comment by chrsmith** [comment]
Thanks for the info @brettsam.  I don't know how exactly the Golang libraries are trying to get the current user's information, but this is enough information for me to make progress on the issues on my end. (And if I see any differences in how the runtime differs from the documentation, I can open a new issue. But I'll assume that all the behavior I'm seeing is all correct by-design.)
