### ISSUE TITLE
Eventhub binding: The listener for function 'Functions.EventhubTrigger' was unable to start.

### ISSUE THREAD

**Issue by joal42** [Azure/azure-functions-host#4340]
My function is running locally in my docker container. The function runtime language is python. The function is binding with eventhub as input. It also crashed after a couple of hours with following exception:

```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.EventhubTrigger ---> Microsoft.Azure.WebJobs.Script.Rpc.LanguageWorkerChannelException: Failed to start language worker for: python ---> System.AggregateException: One or more errors occurred. (The operation has timed out.) (bash exited with code 137
 ) (The operation has timed out.) (bash exited with code 137
 ) ---> System.TimeoutException: The operation has timed out.
```
Or
```
fail: Host.Startup[0]
      The listener for function 'Functions.EventhubTrigger' was unable to start.
Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException: The listener for function 'Functions.EventhubTrigger' was unable to start. ---> Microsoft.Azure.EventHubs.Processor.EventProcessorConfigurationException: Encountered error while fetching the list of EventHub PartitionIds ---> System.TimeoutException: The operation did not complete within the allocated time 00:00:00 for object svc2.
```
Or:
```
fail: Host.Startup[0]
      The listener for function 'Functions.EventhubTrigger' was unable to start.
Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException: The listener for function 'Functions.EventhubTrigger' was unable to start. ---> Microsoft.WindowsAzure.Storage.StorageException: The client could not finish the operation within specified timeout. ---> System.TimeoutException: The client could not finish the operation within specified timeout. ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
```

#### Investigative information

Please provide the following:

- Timestamp: 
- Function App version (1.0 or 2.0): 2.0
- Function App name: running locally in my docker container
- Function name(s) (as appropriate): EventhubTriggerred
- Invocation ID:
- Region: multi-regions

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.
Throw exceptions as listed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used : Python 3.6
* Links to source
* Bindings used "Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.1", "Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="3.0.0", "Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.0.1"

**Comment by brettsam** [comment]
Does this ever succeed? Or is it always failing for you?

// cc @maiqbal11 for the Python question. Maheer, have you seen the first error above?

**Comment by joal42** [comment]
> Does this ever succeed? Or is it always failing for you?
> 
> // cc @maiqbal11 for the Python question. Maheer, have you seen the first error above?

It always succeed for 2 -4 hours. And then, it failed. I host my containers in AKS. I scale up my AKS agent nodes number. It become better. But, it still restart frequently. Do you have any idea for how to debug with this error?

**Comment by brettsam** [comment]
@joal42 -- and this occurs every time after a couple of hours?

@ahmelsayed -- have you seen containers having problems connecting to other services after some time? Any idea how we can debug what's happening?

**Comment by ahmelsayed** [comment]
I don't know of anything special about the container environment that would cause that. 

It could be related to the python deadlock issues @maiqbal11 was looking into since all the errors seem to be timeouts.

**Comment by maiqbal11** [comment]
Hard to say anything about the deadlocks issue without getting more into the details of what the scenario is. @joal42, what is your app trying to accomplish? Do you have multiple functions in the same function app that might be calling each other?

**Comment by joal42** [comment]
@maiqbal11 
My function is to get input streaming data from Azure eventhub and do some data transformation and then write to CosmosDB. So, I binding function input with evnethub and output binding is cosmosdb.

Eventhub streaming incoming message avg is ~4 messages per min. Function host.json is 
```
{
    "version": "2.0",
    "logging": {
    "fileLoggingMode": "always",
      "console": {
        "isEnabled": "true"
      }
    },    
    "functionTimeout": "00:05:00",
    "extensions": {
        "eventHubs": {
            "batchCheckpointFrequency": 5,
            "eventProcessorOptions": {
                "maxBatchSize": 64,
                "prefetchCount": 128
            }
        },
        "cosmosDB": {
            "connectionMode": "Direct",
            "protocol": "Https"
        }
    }
}
```
I run this eventhub triggered function in my docker container. The container is managed by AKS. Initially,  I use the default AKS configuration, the agentnode is 3. After running 2-4 hours, the function crashed with this timeout exception. Then, I scale up the AKS agent node to 6 now. It is still getting some timeout exceptions. 

I don't have multiple functions. This is the only function in my AKS cluster.

**Comment by joal42** [comment]
@brettsam Yes. I tried push function to containers managed by AKS in multiple regions. And, I monitor it for several days. It always throws lot of timeout exception after 2-4 hours. The function is running locally inside the container in my AKS cluster.

**Comment by maiqbal11** [comment]
Hi @joal42, I looked into one of the error codes that you're receiving: https://success.docker.com/article/what-causes-a-container-to-exit-with-code-137. The link suggests that one of the reasons for this might be that you are running out of memory. This is at least plausible given that you are seeing this failure after 2-4 hours during which you might be leaking memory. Is there a way for you to obtain memory dumps and check the status?

**Comment by joal42** [comment]
@maiqbal11 Thanks for pointing to memory leaking here. I increase my container memory to 1G and 2G. Over 1 day, I only see 1 function timeout error. Do you have an idea for how to set container memory based on function input data size?

**Comment by maiqbal11** [comment]
I believe memory allocation for your container will need to happen before running the function app? In that case, it would be difficult to dynamically allocate memory based on the input that you are receiving. @ahmelsayed might have thoughts on whether it is possible to dynamically allocate memory.

**Comment by brettsam** [comment]
@maiqbal11 -- transferred assignment to you since it sounds like you're investigating. Feel free to re-assign if you want me to take it back.

**Comment by maiqbal11** [comment]
Closing this for now as there is no further action that we can take. There is a lingering question about how to configure container memory based on function input size. I don't know of a way that this can be done on the fly since containers are likely provisioned *before* execution (might be more of a question for AKS folks about dynamic scaling). @ahmelsayed if he has anything to add here.
