### ISSUE TITLE
Local clean project with durable functions not working

### ISSUE THREAD

**Issue by ScoutmanPt** [Azure/azure-functions-host#4343]
I'm having issues with  Durable Functions in a clean project with VS2017

My current configuration:

Visual Studio 15.9.11
Azure Functions and WebJobs tools 15.10.2058.8969
Microsoft.NET.Sdk.Functions 1.0.24
Microsoft.Azure.WebJobs.Extensions.DurableTask 1.8.0

The code

```
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.Extensions.Logging;

namespace temp
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static async Task<List<string>> RunOrchestrator(
            [OrchestrationTrigger] DurableOrchestrationContext context)
        {
            var outputs = new List<string>();

            // Replace "hello" with the name of your Durable Activity Function.
            outputs.Add(await context.CallActivityAsync<string>("Function1_Hello", "Tokyo"));
            outputs.Add(await context.CallActivityAsync<string>("Function1_Hello", "Seattle"));
            outputs.Add(await context.CallActivityAsync<string>("Function1_Hello", "London"));

            // returns ["Hello Tokyo!", "Hello Seattle!", "Hello London!"]
            return outputs;
        }

        [FunctionName("Function1_Hello")]
        public static string SayHello([ActivityTrigger] string name, ILogger log)
        {
            log.LogInformation($"Saying hello to {name}.");
            return $"Hello {name}!";
        }

        [FunctionName("Function1_HttpStart")]
        public static async Task<HttpResponseMessage> HttpStart(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")]HttpRequestMessage req,
            [OrchestrationClient]DurableOrchestrationClient starter,
            ILogger log)
        {
            // Function input comes from the request content.
            string instanceId = await starter.StartNewAsync("Function1", null);

            log.LogInformation($"Started orchestration with ID = '{instanceId}'.");

            return starter.CreateCheckStatusResponse(req, instanceId);
        }
    }
}


```
The log when hitting F5

```

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.6.666 Commit hash: 2ea98edb55cd2fc249765fcf3f5e30829c7c9932)
Function Runtime Version: 2.0.12408.0
[23.04.2019 10:20:32] Starting Rpc Initialization Service.
[23.04.2019 10:20:32] Initializing RpcServer
[23.04.2019 10:20:32] Building host: startup suppressed:False, configuration suppressed: False
[23.04.2019 10:20:32] Reading host configuration file 'C:\work\temp\bin\Debug\netcoreapp2.0\host.json'
[23.04.2019 10:20:32] Host configuration file read:
[23.04.2019 10:20:32] {
[23.04.2019 10:20:32]   "version": "2.0"
[23.04.2019 10:20:32] }
[23.04.2019 10:20:33] Initializing Host.
[23.04.2019 10:20:33] Host initialization: ConsecutiveErrors=0, StartupCount=1
[23.04.2019 10:20:33] LoggerFilterOptions
[23.04.2019 10:20:33] {
[23.04.2019 10:20:33]   "MinLevel": "None",
[23.04.2019 10:20:33]   "Rules": [
[23.04.2019 10:20:33]     {
[23.04.2019 10:20:33]       "ProviderName": null,
[23.04.2019 10:20:33]       "CategoryName": null,
[23.04.2019 10:20:33]       "LogLevel": null,
[23.04.2019 10:20:33]       "Filter": "<AddFilter>b__0"
[23.04.2019 10:20:33]     },
[23.04.2019 10:20:33]     {
[23.04.2019 10:20:33]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[23.04.2019 10:20:33]       "CategoryName": null,
[23.04.2019 10:20:33]       "LogLevel": "None",
[23.04.2019 10:20:33]       "Filter": null
[23.04.2019 10:20:33]     },
[23.04.2019 10:20:33]     {
[23.04.2019 10:20:33]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[23.04.2019 10:20:33]       "CategoryName": null,
[23.04.2019 10:20:33]       "LogLevel": null,
[23.04.2019 10:20:33]       "Filter": "<AddFilter>b__0"
[23.04.2019 10:20:33]     }
[23.04.2019 10:20:33]   ]
[23.04.2019 10:20:33] }
[23.04.2019 10:20:33] FunctionResultAggregatorOptions
[23.04.2019 10:20:33] {
[23.04.2019 10:20:33]   "BatchSize": 1000,
[23.04.2019 10:20:33]   "FlushTimeout": "00:00:30",
[23.04.2019 10:20:33]   "IsEnabled": true
[23.04.2019 10:20:33] }
[23.04.2019 10:20:33] SingletonOptions
[23.04.2019 10:20:33] {
[23.04.2019 10:20:33]   "LockPeriod": "00:00:15",
[23.04.2019 10:20:33]   "ListenerLockPeriod": "00:00:15",
[23.04.2019 10:20:33]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
[23.04.2019 10:20:33]   "LockAcquisitionPollingInterval": "00:00:05",
[23.04.2019 10:20:33]   "ListenerLockRecoveryPollingInterval": "00:01:00"
[23.04.2019 10:20:33] }
[23.04.2019 10:20:33] Starting JobHost
[23.04.2019 10:20:33] Starting Host (HostId=bsstationqs-1625424794, InstanceId=3fb82ae1-dcef-48b7-a1c0-86d3c2b1a8ba, Version=2.0.12408.0, ProcessId=18400, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=)
[23.04.2019 10:20:33] Loading functions metadata
[23.04.2019 10:20:33] 3 functions loaded
[23.04.2019 10:20:33] WorkerRuntime: dotnet. Will shutdown other standby channels
[23.04.2019 10:20:34] Generating 1 job function(s)
[23.04.2019 10:20:34] Error indexing method 'Function1_HttpStart'
[23.04.2019 10:20:34] Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1_HttpStart'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'starter' to type DurableOrchestrationClient. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
[23.04.2019 10:20:34] Function 'Function1_HttpStart' failed indexing and will be disabled.
[23.04.2019 10:20:34] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
[23.04.2019 10:20:34] Host initialized (1354ms)
[23.04.2019 10:20:34] Host started (1367ms)
[23.04.2019 10:20:34] Job host started
[23.04.2019 10:20:34] The following 2 functions are in error:
[23.04.2019 10:20:34] Function1: The binding type(s) 'orchestrationTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.
[23.04.2019 10:20:34] Function1_Hello: The binding type(s) 'activityTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.
[23.04.2019 10:20:34]
Hosting environment: Production
Content root path: C:\work\temp\bin\Debug\netcoreapp2.0
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.

Http Functions:

        Function1_HttpStart: [GET,POST] http://localhost:7071/api/Function1_HttpStart

[23.04.2019 10:20:40] Host lock lease acquired by instance ID '00000000000000000000000086FC67D4'.
```

Im keep getting this : 
"Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1_HttpStart'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'starter' to type DurableOrchestrationClient. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.)."

... and can't understand what's happening. Seems like a dotnet core issue 

I've tryed to run the same project in one of my clients machines 1 out of  12 is working.

Help?

**Comment by brettsam** [comment]
Can you try moving to Microsoft.NET.Sdk.Functions 1.0.26 and running again? 
If that doesn't work, can you share what is in the extensions.json file in your function apps /bin directory?

**Comment by ScoutmanPt** [comment]
Hi , already try it. Still same result. Regarding extensions.json i dont have that file in the solution  neither in bin or obj.

Here's the complete list of the files


\FunctionApp3\FunctionApp3.sln
\FunctionApp3\FunctionApp3\bin
\FunctionApp3\FunctionApp3\Function1.cs
\FunctionApp3\FunctionApp3\FunctionApp3.csproj
\FunctionApp3\FunctionApp3\host.json
\FunctionApp3\FunctionApp3\local.settings.json
\FunctionApp3\FunctionApp3\obj
\FunctionApp3\FunctionApp3\bin\Debug
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\Function1
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\Function1_Hello
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\Function1_HttpStart
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\FunctionApp3.deps.json
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\host.json
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\local.settings.json
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\DurableTask.AzureStorage.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\DurableTask.Core.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Dynamitey.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\FunctionApp3.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\FunctionApp3.pdb
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\ImpromptuInterface.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.Authentication.Abstractions.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.Authentication.Core.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.Authorization.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.Authorization.Policy.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.Hosting.Abstractions.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.Http.Abstractions.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.Http.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.Http.Extensions.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.Http.Features.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.JsonPatch.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.Mvc.Abstractions.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.Mvc.Core.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.Mvc.Formatters.Json.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.Mvc.WebApiCompatShim.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.ResponseCaching.Abstractions.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.Routing.Abstractions.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.Routing.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.AspNetCore.WebUtilities.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Azure.WebJobs.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Azure.WebJobs.Extensions.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Azure.WebJobs.Extensions.DurableTask.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Azure.WebJobs.Extensions.Http.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Azure.WebJobs.Host.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Azure.WebJobs.Host.Storage.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Build.Framework.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Build.Utilities.Core.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.DotNet.PlatformAbstractions.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.Configuration.Abstractions.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.Configuration.Binder.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.Configuration.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.Configuration.EnvironmentVariables.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.Configuration.FileExtensions.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.Configuration.Json.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.DependencyInjection.Abstractions.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.DependencyInjection.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.DependencyModel.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.FileProviders.Abstractions.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.FileProviders.Physical.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.FileSystemGlobbing.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.Hosting.Abstractions.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.Hosting.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.Logging.Abstractions.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.Logging.Configuration.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.Logging.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.ObjectPool.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.Options.ConfigurationExtensions.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.Options.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Extensions.Primitives.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.Net.Http.Headers.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Microsoft.WindowsAzure.Storage.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\NCrontab.Signed.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Newtonsoft.Json.Bson.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\Newtonsoft.Json.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\runtimes
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\System.Net.Http.Formatting.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\System.Runtime.CompilerServices.Unsafe.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\System.Text.Encodings.Web.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\runtimes\unix
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\runtimes\win
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\runtimes\unix\lib
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\runtimes\unix\lib\netstandard1.3
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\runtimes\unix\lib\netstandard1.3\System.Text.Encoding.CodePages.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\runtimes\win\lib
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\runtimes\win\lib\netstandard1.3
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\bin\runtimes\win\lib\netstandard1.3\System.Text.Encoding.CodePages.dll
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\Function1\function.json
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\Function1_Hello\function.json
\FunctionApp3\FunctionApp3\bin\Debug\netcoreapp2.1\Function1_HttpStart\function.json
\FunctionApp3\FunctionApp3\obj\Debug
\FunctionApp3\FunctionApp3\obj\FunctionApp3.csproj.nuget.cache
\FunctionApp3\FunctionApp3\obj\FunctionApp3.csproj.nuget.g.props
\FunctionApp3\FunctionApp3\obj\FunctionApp3.csproj.nuget.g.targets
\FunctionApp3\FunctionApp3\obj\project.assets.json
\FunctionApp3\FunctionApp3\obj\Debug\netcoreapp2.1
\FunctionApp3\FunctionApp3\obj\Debug\netcoreapp2.1\FunctionApp3.AssemblyInfo.cs
\FunctionApp3\FunctionApp3\obj\Debug\netcoreapp2.1\FunctionApp3.AssemblyInfoInputs.cache
\FunctionApp3\FunctionApp3\obj\Debug\netcoreapp2.1\FunctionApp3.assets.cache
\FunctionApp3\FunctionApp3\obj\Debug\netcoreapp2.1\FunctionApp3.csproj.CopyComplete
\FunctionApp3\FunctionApp3\obj\Debug\netcoreapp2.1\FunctionApp3.csproj.CoreCompileInputs.cache
\FunctionApp3\FunctionApp3\obj\Debug\netcoreapp2.1\FunctionApp3.csproj.FileListAbsolute.txt
\FunctionApp3\FunctionApp3\obj\Debug\netcoreapp2.1\FunctionApp3.csprojAssemblyReference.cache
\FunctionApp3\FunctionApp3\obj\Debug\netcoreapp2.1\FunctionApp3.dll
\FunctionApp3\FunctionApp3\obj\Debug\netcoreapp2.1\FunctionApp3.pdb
\FunctionApp3\FunctionApp3\obj\Debug\netcoreapp2.1\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs
\FunctionApp3\FunctionApp3\obj\Debug\netcoreapp2.1\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs
\FunctionApp3\FunctionApp3\obj\Debug\netcoreapp2.1\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs

**Comment by brettsam** [comment]
Can you share your project file? Is this a single-project solution, or is it many?

**Comment by ScoutmanPt** [comment]
Hi again, sure.
Here it is:
http://bit.ly/ExampleFx3

**Comment by brettsam** [comment]
Hi @ScoutmanPt -- I wasn't able to get to your link; it said I wasn't found in the directory.
