### ISSUE TITLE
Issue with HttpClient via Dependency Injection via Contructor, Cannot access a disposed object

### ISSUE THREAD

**Issue by PingPongSet** [Azure/azure-functions-host#4344]
HttpClient is used like below, the error below occurs from second request onwards unless the runtime is restarted.

Cannot access a disposed object.
Object name: 'System.Net.Http.HttpClient'. 

```
public sealed class MyFunction()
{
    private readonly HttpClient _httpClient;

    public MyFunction(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public void Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "v1/resource/{resourceId}")] HttpRequest httpRequest, string resourceId)
    {
         return OkObjectResult($"Found resource {resourceId}");
    }
}
```

```
[assembly: WebJobsStartup(typeof(Startup))]

public sealed class Startup : IWebJobsStartup
{
    public void Configure(IWebJobsBuilder webJobsBuilder)
    {
        webJobsBuilder.Services.AddHttpClient();
    }
}
```

Azure Functions Core Tools (2.6.666 Commit hash: 2ea98edb55cd2fc249765fcf3f5e308
29c7c9932)
Function Runtime Version: 2.0.12408.0

**Comment by brettsam** [comment]
Can you try asking for an `IHttpClientFactory` in the constructor? https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#basic-usage

It looks like you need to use the "Typed client" approach if you want an `HttpClient` injected: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#typed-clients

Please re-open if you still bump into issues with this.

**Comment by codermrrob** [comment]
I have same issue. Startup class is this:

```
[assembly: FunctionsStartup(typeof(Orders.Collector.Startup))]
namespace Orders.Collector
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddHttpClient<OrdersCollector>();
        }
    }
}
```
```
{
    public class OrdersCollector
    {

        private readonly HttpClient _client;

        public OrdersCollector(HttpClient client)
        {
            _client= client;
        }


        [FunctionName("OrdersCollector")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = null)] HttpRequest req,
            ILogger log)
        {
        //Do some processing
         return (ActionResult)new OkObjectResult("Data collection completed");
        }
}
```
runs fine in the emulator and runs perfectly well the first time in my Function App. Subsequent executions result in an error:  Cannot access a disposed object. Object name: 'System.Net.Http.HttpClient'.

Predictably restarting the Function App resets everything and it will run one time again.
