### ISSUE TITLE
IHttpClientFactory intermittent error: An error occurred while sending the request

### ISSUE THREAD

**Issue by PingPongSet** [Azure/azure-functions-host#4350]
The error below occurs intermittently when `_httpClientFactory.CreateClient()` is used to send request to external resources.
  

> System.Net.Http.HttpRequestException : An error occurred while sending
> the request. ---> System.IO.IOException : The server returned an
> invalid or unrecognized response.    at async
> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage
> request,CancellationToken cancellationToken)     End of inner
> exception    at async
> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage
> request,CancellationToken cancellationToken)    at
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at
> async
> System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection
> connection,HttpRequestMessage request,Boolean
> doRequestAuth,CancellationToken cancellationToken)    at
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at
> async
> System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage
> request,Boolean doRequestAuth,CancellationToken cancellationToken)   
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   
> at async System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage
> request,CancellationToken cancellationToken)    at
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at
> async System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage
> request,CancellationToken cancellationToken)    at
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at
> async
> Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage
> request,CancellationToken cancellationToken)    at
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at
> async
> Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage
> request,CancellationToken cancellationToken)    at
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at
> async System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1
> sendTask,HttpRequestMessage request,CancellationTokenSource
> cts,Boolean disposeCts)    at
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at
> async
> IdentityModel.Client.HttpClientTokenRequestExtensions.RequestTokenAsync(??)

  
  

  
  
 ```
 public class WebHttpClient {
  
        private readonly IHttpClientFactory _httpClientFactory;

        public WebHttpClient(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<string> WebRequestAsync(string url)
        {
            return await _httpClientFactory.CreateClient().WebRequestAsync(url);  //intermittent error: An error occurred while sending the request.
        }
        
    }
	
	[assembly: WebJobsStartup(typeof(Startup))]
public sealed class Startup : IWebJobsStartup
{
    public void Configure(IWebJobsBuilder webJobsBuilder)
    {
        webJobsBuilder.Services.AddHttpClient();
    }
}

```
Any solution?

**Update**

static HttpClient has issues with DNS. This is why I try to avoid static if possible and if using IHttpClientFactory can resolve all issues.

But I am not sure if my issue is caused by DNS or something else.

Would a typed httpclient (or wrapper around httpclient) fix this issue? It is intermittent so it is not easy to reproduce.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#typed-clients

**Update 2**

Please see the updated exception at the top.

**Comment by PingPongSet** [comment]
Please see the updated exception at the top.

Any update?

**Comment by ankitkumarr** [comment]
@PingPongSet, do you think the URL server could maybe closing the connection soon or having other issues? It doesn't look like the issue has to do with functions / webjobs. I would recommend looking at the `HttpClient` docs to see why this error is thrown. I found this case study with a similar issue and conclusion - https://4lowtherabbit.github.io/blogs/2018/11/CaseStudy. 

I will close this issue, but if you are still unable to troubleshoot and think it's related to Functions, please do not hesitate to reopen, and we can have a further look.
