### ISSUE TITLE
Specific series of events can lead to Host being in a specialized limbo state 

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-host#4355]
If a specialization request is made when the application host is starting up, there's a chance of a race condition. 

From @brettsam -
We do two things in the application host, before starting up the job host:
1.	Check if we’re in standby mode and if so, set up the paths to be temporary\functions\standby\... 
2.	Later, again check if we’re in standby mode and if so, add all the standby services (which will refresh these options when we’re specialized).

If we get specialized in between 1 and 2, we’ll end up with Options set up for standby mode, yet have nothing running to ever specialize us. So we’d be stuck there forever.

**Comment by brettsam** [comment]
#4356 closed this.
