### ISSUE TITLE
Issue introduced with version 2.0.12408.0 of the runtime which was not present with 2.0.12382.0

### ISSUE THREAD

**Issue by lee-garrington** [Azure/azure-functions-host#4369]
I have detailed the issue here...
https://stackoverflow.com/questions/55839514/intermittent-dependency-injection-failure/55847358#55847358

**Comment by fabiocav** [comment]
@lee-garrington provided some information in the SO thread. What you're doing there is not Functions specific and doesn't use the DI capabilities we're introducing.

Do you have the same experience with the latest runtime version?
