### ISSUE TITLE
Azure Function (Linux/Node.js) often returns ECONNREFUSED

### ISSUE THREAD

**Issue by LarryKlugerDS** [Azure/azure-functions-host#4378]
My Linux / Node.js function works fine most of the time. But testing with single threaded requests one immediately after the next sometimes results in a `ECONNREFUSED` error.

The rate of these errors so far is 6 ECONNREFUSED errors for 56 HTTP POST attempts. Not good.

I ran a test for 8 hours. Out of 2,330 connection attempts to the function, 150 (6%) failed with `ECONNREFUSED`.

**Update:** I create a new Azure function on Windows OS. The Node.js code is the exact same.
I ran the same test as above for 8 hours. 

Result: Out of 1,433 connect attempts to the function, 153 (11%) failed on sending. Most errors were `ECONNREFUSED`. Some were `ETIMEDOUT`.

**Tentative conclusion** A common system or front-end is a causing the problem, not the Linux vs Windows OS. I will do another test with a non-consumption-based plan.

#### I'm using the WestUSLinuxDynamicPlan (Consumption) plan.

Are there any switches or settings I should check?

#### Investigative information
- Timestamp: Thu, 02 May 2019 08:21:10 GMT  (I'm in Israel)
- Function App version (1.0 or 2.0): 2.0
- Function App name:
- Function name(s) (as appropriate): ConnectMessage
- Invocation ID: f95c126f-7587-4e61-a058-d0b72a019e4c (Note this is the invocation Id of a successful transaction. The issue are the ECONNREFUSED responses)
- Region: West US

**Additional info**
I set up a new Azure Function App for Node.js. It's using the WestUSLinuxDynamicPlan (Consumption) plan.

My Node.js function is triggered via HTTP. It creates a Service Bus message from the HTTP call's payload. That's it.

#### Repro steps
Make HTTP POST requests to `https://xxx.azurewebsites.net/api/ConnectMessage?test=1` repeatedly.  No delay from one to the next. Single threaded--not multiple requests at the same time.

#### Expected behavior
Result should be "enqueued" or (since you don't have the HTTP BASIC AUTH credentials,
you will receive a 401 error. )

#### Actual behavior
I receive `ECONNREFUSED`

#### Known workarounds

None.

#### Related information 
* Programming language used: Node.js
* Links to source: Attached as index.txt
[index.txt](https://github.com/Azure/azure-functions-host/files/3137204/index.txt)

* Bindings used:  Attached as function.txt
[function.txt](https://github.com/Azure/azure-functions-host/files/3137201/function.txt)

**Comment by soninaren** [comment]
@mhoeger any idea what is causing this?

**Comment by LoW0lf** [comment]
Are there any updates on this? 

We are also using Azure Functions with Node.js on Linux Consumption Plan and do get ECONNREFUSED errors quite often. Our Scenario is the following:
- Getting ManagedIdentityCredentials from localhost:8018 (via official @azure/identity SDK)
`Error: ManagedIdentityCredential authentication failed. Message request to http://localhost:8081/msi/token?resource=https%3A%2F%2Fservicebus.azure.net%2F&api-version=2017-09-01 failed, reason: connect ECONNREFUSED 127.0.0.1:8081`

In a second scenario of the same Function App we also get some ECONNRESET from time to time: 
- Fetching blobs from our own storage account (via official @azure/storage-blob SDK) 
`request to https://XXX.blob.core.windows.net/XXX/XXX.json failed, reason: read ECONNRESET`

We have already invested quite some time together with the Azure Support to tackle this down but never found a proper solution.

**Comment by LarryKlugerDS** [comment]
I ran similar tests with the serverless functions features of the valued competition (Axx and Gxxxxx) results were 0.00% error rates over equivalent 8 hour test periods. Your mileage may vary.

**Comment by balag0** [comment]
@LoW0lf Could you share your app name using
https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

Thanks

**Comment by LoW0lf** [comment]
@balag0 
`TimeGenerated [UTC]: 2021-09-14T01:00:32Z`
`FunctionInvocationID: 61acafc9-c93c-4a76-9832-cf07d2e6d0b6`
`Region: SwitzerlandNorth`

**Comment by balag0** [comment]
@LoW0lf Thank you. The full exception seems to be 

Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: ---> Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: Failure Exception: AggregateAuthenticationError: undefined  Error: EnvironmentCredential is unavailable. Environment variables are not fully configured. Error: ManagedIdentityCredential authentication failed. Message request to http://localhost:8081/msi/token?resource=.. failed, reason: connect ECONNREFUSED 127.0.0.1:8081 Error: Azure CLI could not be found.  Please visit https://aka.ms/azure-cli for installation instructions and then, once installed, authenticate to your Azure account using 'az login'. Error: Visual Studio Code credential requires the optional dependency 'keytar' to work correctly

I am not sure what this exception means, but doing a quick check for this signature, I dont see any other app logging this exception. Do you have any ideas on why this app might be experiencing this exception?
Are there any differences in how you fetch the token? Also if you have app insights enabled you might have these errors logged there as well.
