### ISSUE TITLE
Exception binding parameter 'log' Cannot access a disposed object. Object name: 'LoggerFactory'. 

### ISSUE THREAD

**Issue by fusionet24** [Azure/azure-functions-host#4379]
#### Investigative information

Please provide the following:

- Timestamp: 3:14:00 PM BST
- Function App version (1.0 or 2.0): 1.0
- Invocation ID:2d27fe39-9a4d-44a5-8537-a37df5641239 
- Region:North Europe

#### Repro steps

Provide the steps required to reproduce the problem:
1. We deployed our code to 4 function apps from Azure Dev ops Function Deployment Task
2. We were processing a lot of transactions (around 10-40k per minute) and we started seeing around 30k errors of the below type.:

Exception while executing function: MatchCustomers Exception binding parameter 'log' Cannot access a disposed object. Object name: 'LoggerFactory'. 

I can see a lengthy discussion about this being a host issue [here](https://github.com/Azure/azure-functions-host/issues/1690) 

#### Expected behavior:

- For the function to continue to run with code that is loaded in memory then to use new code once all existing executions.  To continue at the exact same point in the event hub, event stream and carry on processing transactions as is.

#### Actual behavior

- Functions failed and exceptions were thrown:
Exception while executing function: MatchCustomers Exception binding parameter 'log' Cannot access a disposed object. Object name: 'LoggerFactory'.  Unknown whether we are at the same point in the event stream.

#### Related information 

Event Hub Binding to Cosmos output bindings.

My main question is, do we think this will of effected our functions pointers in the event hub stream?

**Comment by fabiocav** [comment]
What language is your function written in?

@brettsam FYI (this is also in 1.0)

**Comment by fusionet24** [comment]
@fabiocav C#

**Comment by fusionet24** [comment]
FYI - I'm raising a P1 ticket via Azure as we had other issues related to the global DNS outage which caused us to have another 30k execution failures over several hours due to failing to retrieve app settings from blob underlying storage.

I think they're similar in the sense they're both host level exceptions and hopefully the behavior for all is to not lose the pointer in the event hubs even stream. 🤞

**Comment by JasperKeijzer** [comment]
Having a similar error:

`"Failed to deserialize exception from TaskActivity: Unhandled exception while executing task: System.ObjectDisposedException: Cannot access a disposed object.Object name: 'LoggerFactory'.at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)at Microsoft.Azure.WebJobs.Script.WebHost.ScriptLoggerFactory.CreateLogger(String categoryName) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Diagnostics\ScriptLoggerFactory.cs:line 26at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 101at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance instance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 87at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor 1.TryExecuteAsync(TriggeredFunctionData input, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\TriggeredFunctionExecutor.cs:line 56at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskActivityShim.RunAsync(TaskContext context, String rawInput) in C:\GitHub\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskActivityShim.cs:line 57at DurableTask.Core.TaskActivityDispatcher.<>c__DisplayClass12_1.<<OnProcessWorkItemAsync>b__1>d.MoveNext() in C:\source\durabletask\src\DurableTask.Core\TaskActivityDispatcher.cs:line 135at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)at Microsoft.Azure.WebJobs.Script.WebHost.ScriptLoggerFactory.CreateLogger(String categoryName) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Diagnostics\ScriptLoggerFactory.cs:line 26at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 101at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance instance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 87at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor 1.TryExecuteAsync(TriggeredFunctionData input, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\TriggeredFunctionExecutor.cs:line 56at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskActivityShim.RunAsync(TaskContext context, String rawInput) in C:\GitHub\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskActivityShim.cs:line 57at DurableTask.Core.TaskActivityDispatcher.<>c__DisplayClass12_1.<<OnProcessWorkItemAsync>b__1>d.MoveNext() in C:\source\durabletask\src\DurableTask.Core\TaskActivityDispatcher.cs:line 135`

Behaviour seems random

**Comment by alrod** [comment]
cc: @brettsam

**Comment by brettsam** [comment]
@fusionet24 -- Sorry for the delay here. Have you continued to see this issue? This log is almost always a symptom, rather than the cause, of other issues. For example, the host is shutting down already and some services are disposed and cannot be accessed -- LoggerFactory is always the first one that gets hit b/c it's used so often in our code. If you have a more recent occurrence of this, I can take a deeper look. If you could share your Function App name (either explicitly or [privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)), I can see if I find anything from the backend logs.

@JasperKeijzer -- yours looks like a v2 app (I don't think `ScriptLoggerFactory` exists in v1). Have you seen this recently? We fixed quite a few race conditions in v2 over the last couple of months so your scenario may have been fixed. But similarly, if you have a more recent occurrence, please share the timeframe and app name (link above) and I can dig in.
