### ISSUE TITLE
CORS enabled in portal, but not sending Access-Control-Allow-Origin in reponse

### ISSUE THREAD

**Issue by alexjamesbrown** [Azure/azure-functions-host#4381]
In the portal, I've enabled CORS

![image](https://user-images.githubusercontent.com/437743/57121903-5453fb00-6d72-11e9-90e2-f57767428cc5.png)

However it's not returning the `Access-Control-Allow-Origin` header in the response?

![image](https://user-images.githubusercontent.com/437743/57121909-62098080-6d72-11e9-8e72-f5ebe28d6174.png)

Am I missing something?

**Comment by soninaren** [comment]
You need add the header `Origin: https://functions.azure.com` to the request to get `Access-Control-Allow-Origin: *` in response header.
