### ISSUE TITLE
[App Insights] Warm-up requests correlate all host startup traces and all TimerTrigger traces to that request

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#4389]
App Insights will automatically correlate all traces made during a request to that request. This doesn't work well when a request comes in that triggers the host to start. All host startup requests are then correlated to that request, when they should be independent (i.e. uncorrelated).

**Comment by brettsam** [comment]
There's a side bug here as well -- it appears that all TimerTrigger invocations will also have the same operation id.

**Comment by sreevani2203** [comment]
Hi - Is there any mitigation for this issue?

**Comment by brettsam** [comment]
The only real mitigation means that cold start will get worse. Set an app setting with `WEBSITE_USE_PLACEHOLDER` to `0`, which will remove any placeholder logic that we use (which is where the problem is).

**Comment by rkbalu** [comment]
@brettsam Is this fix released?

**Comment by brettsam** [comment]
No -- it'll be part of the release after https://github.com/Azure/azure-functions-host/releases/tag/2.0.12493. I hope to kick that release off later this week.

**Comment by sreevani2203** [comment]
any tentative date on when the fix will be released?

**Comment by brettsam** [comment]
I'm hoping it's everywhere by mid next-week.

**Comment by brettsam** [comment]
This is part of https://github.com/Azure/azure-functions-host/releases/tag/v2.0.12507, which will be rolling out over the next couple of days.

**Comment by rkbalu** [comment]
@brettsam Is this something available in all region now?

**Comment by brettsam** [comment]
As of a couple minutes ago, yes :-)

If you're not seeing the new version yet, try restarting your app.

**Comment by nikagarwal25** [comment]
@brettsam For me, my function doesn't log anything in the monitor. It is a time trigger, v2 app.

**Comment by nikagarwal25** [comment]
> @brettsam For me, my function doesn't log anything in the monitor. It is a time trigger, v2 app.

Runtime version: 2.0.12507.0 (~2)

**Comment by brettsam** [comment]
@nikagarwal25  -- If you could share your Function App name (either explicitly or [privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)), I can see if I find anything from the backend logs.
