### ISSUE TITLE
Looking for right host.json config for EventHubTrigger host function (Linux Consumption Function)

### ISSUE THREAD

**Issue by mguglani** [Azure/azure-functions-host#4421]
I am using Azure CLI to create an Azure function for EventHub trigger. I did the HTTP trigger and moved on to EventHub Trigger:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python

I keep getting the following error when I click on the function in Azure portal after publishing it using the following command:

func azure functionapp publish <func-appname>

**Is this supported?** 

I was able to successfully create a Javascript EventHubTrigger with Windows Consumption Function.

Function (EventHubTrigger) Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.EventHubTrigger'. Microsoft.Azure.WebJobs.EventHubs: Value cannot be null. Parameter name: receiverConnectionString.
Session Id: f74f25952dcc4be7a37ae91e16c158c3

Timestamp: 2019-05-14T01:15:49.486Z

I used the template available through "func new". Chose Option 4:

└─ $ func new
Select a template: 
1. Azure Blob Storage trigger
2. Azure Cosmos DB trigger
3. Azure Event Grid trigger
4. Azure Event Hub trigger
5. HTTP trigger
6. Azure Queue Storage trigger
7. Azure Service Bus Queue trigger
8. Azure Service Bus Topic trigger
9. Timer trigger

Here is my function.json bindings:
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "type": "eventHubTrigger",
      "name": "event",
      "direction": "in",
      "eventHubName": "*****",
 "connection":"Endpoint=amqp://<eventhubnamespace>.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=****",
      "cardinality": "many",
      "consumerGroup": "$Default",
      "path":"%eventHubName%"
    }
  ]
}

**Comment by brettsam** [comment]
For `connection` you need to use an app setting *name*, not the actual connection string. We'll use that key to look up the value in app settings (or env variables if running locally). This allows you to commit the host.json to source control without exposing secrets.

See the Event Hub config details here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs#trigger---configuration.

I'll close this but let me know if you have more questions around this.

**Comment by mguglani** [comment]
thanks changing to app setting name as well as updating the App settings to include the app setting name and value in Azure portal was needed to make it work.

**Comment by kradecki** [comment]
OK, I'm having exactly the same issue and I simply can't find a way to locate my connection name. I could really use a walkthrough on how to find it guys. 

How can I locate the app setting name? Is it a function property or event hub property? A click-through would be really, REALLY appreciated.

And yes, I've googled a lot here.

**Comment by mguglani** [comment]
check the document Brett pointed. Specifically check this note on connection (you can check this from Azure portal):


connection | Connection | The name of an app setting that contains the connection string to the event hub's namespace. Copy this connection string by clicking the Connection Information button for the namespace#create-an-event-hubs-namespace), not the event hub itself. This connection string must have at least read permissions to activate the trigger.
-- | -- | --

**Comment by kradecki** [comment]
Yes, I've seen this post. And yet after clicking through the entire Azure
Portal i seriously can't find that parameter.

Where exactly in the portal should I look for it?

pon., 5 sie 2019, 17:41 użytkownik Manoj Guglani <notifications@github.com>
napisał:

**Comment by mguglani** [comment]
click on Resources. You will see a list of all your resources. Click on the resource under which you created your Event Hub Namespace. If you need more details please open a new issue and someone from Microsoft should reply.
