### ISSUE TITLE
Consume the new index endpoint for extension bundle

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#4438]
Function runtime right now consumes https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json, to look up existing extension bundles. This endpoint only contains bundle versions. 
We need an new endpoint which contains array of objects and each object includes template information, minimum required runtime and CLI version. The runtime needs to consume this new endpoint.
related to #4437

**Comment by fabiocav** [comment]
Can you add a brief description here?

**Comment by soninaren** [comment]
This is not needed for template change.
