### ISSUE TITLE
Getting error when using function dependency injection

### ISSUE THREAD

**Issue by AnunnakiSelva** [Azure/azure-functions-host#4452]
#### Is your question related to a specific version? If so, please specify:
Am using function v2 with .net core 2.2 
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C# 
#### Question
I have replaced all my static functions into non static function to support latest DI supported function version. 

while doing so am getting these error ---> No idea where am going wrong. It was working well 
with my custom DI which i build over .net core 2.0.

"reuse CurrentScopeReuse {Lifespan=100} lifespan shorter than its parent's: singleton ". Can anyone help me to resolve this please.

 Executed 'TimeTrigger' (Failed, Id=abefd9b7-8678-4de5-bdf7-c097c66e2d1f)
 Microsoft.Azure.WebJobs.Script.WebHost: Dependency ITelemetryTracker {ReturnDefault} as parameter "telemetry" reuse CurrentScopeReuse {Lifespan=100} lifespan shorter than its parent's: singleton BingMapsGeoCodingService: ICloudGeoCodingService {ReturnDefault} as parameter "cloudService" #214
in singleton GeocodingService: IGeocodingService {ReturnDefault} as parameter "geoCodeService" #206
in scoped ReProfileService: IReProfileService {ReturnDefault} #194
 from scoped container with {no name}
 To turn Off this error, specify the rule with new Container(rules => rules.WithoutThrowIfDependencyHasShorterReuseLifespan()).

**Comment by mikebollanddp** [comment]
![image](https://user-images.githubusercontent.com/52451126/61789459-a99d2700-ae0c-11e9-952b-1826f39148fd.png)

**Comment by AnunnakiSelva** [comment]
"Never resolve a scoped service from a singleton service." --> resolve lower lifetime with higher life time.

 https://blog.markvincze.com/two-gotchas-with-scoped-and-singleton-dependencies-in-asp-net-core/
