### ISSUE TITLE
Function fails to start with Microsoft.WindowsAzure.Storage: An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by slaharip** [Azure/azure-functions-host#4457]
#### Investigative information
Exception while trying to start the function:
Microsoft.WindowsAzure.Storage: An attempt was made to access a socket in a way forbidden by its access permissions. System.Net.Http: An attempt was made to access a socket in a way forbidden by its access permissions. System.Private.CoreLib: An attempt was made to access a socket in a way forbidden by its access permissions."

Please provide the following:

- Timestamp: 2019-05-16T20:16:41.3072097Z
- Function App version (1.0 or 2.0): 2.0
- Function App name: baselinefnapp
- Function name(s) (as appropriate):
- Invocation ID:
- Region: east us 2
Run time : .NET 

#### Repro steps

Provide the steps required to reproduce the problem:
After deploying the function through visual studio code to azure, I am seeing this exception. The function fails to start due to this exception.

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by gzuber** [comment]
@slaharip Sorry for the delay on this -- are you still experiencing this issue? If so, do you have a more recent timestamp? Thanks!
