### ISSUE TITLE
NodeJs time triggered azure function v2 occasionally gives timeout error when interacting with azure SQL table (npm used mssql)

### ISSUE THREAD

**Issue by sohailbujhs** [Azure/azure-functions-host#4473]
'use strict';

const Promise = require('bluebird');
const { getSqlCollection } = require('../db/sqldb');
const utils = require('../utils');
const moment = require('moment');
const { getMongodbCollection } = require('../db/mongodb');
const { selectVouchersAboutToBeExpire } = require('../db/sqldb/scripts');
const { updateVoucherAboutToExpire } = require('../db/sqldb/scripts');

module.exports = async context => {
    try {
        context.log('Find vouchers about to expire within 30 days');
        const sqlConnection = await getSqlCollection();
        const query = selectVouchersAboutToBeExpire();

        const date = moment().add(30, 'days')
            .toDate();
        const result = await sqlConnection.request()
            .input('Date', date)
            .input('TodayDate', moment().startOf('day')
                .toDate())
            .input('isExpiryWarningSent', false)
            .query(query);
        const voucherToExpire = result.recordset;// no of vouchers

        context.log(`Found ${voucherToExpire.length} expired vouchers`);

        if (!Array.isArray(voucherToExpire) || !voucherToExpire.length) {
            return Promise.resolve();
        }
        const passTokens = voucherToExpire.map(x => x.passToken);
        let voucherIDs = voucherToExpire.map(x => x.voucherID.toLowerCase());
        const collection = await getMongodbCollection('Vouchers');
        const voucherOptions = {
            _id: { $in: voucherIDs },
            passToken: { $in: passTokens },
            partitionKey: { $in: passTokens },
            docType: 'vouchers',
            isExpired: false,
        };
        const vouchersCosmoDB = await collection.find(voucherOptions).toArray();

        await Promise.map(vouchersCosmoDB, async voucher => {
            if (voucher && voucher.notificationSubscribers && Array.isArray(voucher.notificationSubscribers)) {
                voucher.notificationSubscribers.forEach(async element => {
                    if (element.walletID) {
                        const notificationDoc = utils.createNotificationDoc(element.walletID, voucher.voucherTitle, 'voucher-about-to-expire');
                        console.log(notificationDoc);
                        utils.sendMessageToAzureBus(process.env.AZURE_BUS_TOPIC_NOTIFICATION_EMAIL, notificationDoc);
                        
                    }
                });

            }
        });

        voucherIDs = voucherToExpire.map(x => x.voucherID);
        let voucherIDForQuery = '';
       
        if (voucherIDs && voucherIDs.length) {
            voucherIDs.forEach(element => {
                voucherIDForQuery = voucherIDForQuery + ',\'' + element + '\'';
            });
            const updateQuery = updateVoucherAboutToExpire(voucherIDForQuery.slice(1));
            const result = await sqlConnection.request()
                .input('isExpiryWarningSent', true)
                .query(updateQuery);

            context.log(result);

        }

    } catch (error) {
        context.log(error);
    }
};

**Comment by gzuber** [comment]
@sohailbujhs is the timeout coming from the function timing out or is it originating from the attempt to interact with SQL? You should be able to find more information about the cause of the timeout through Application Insights.

**Comment by sohailbujhs** [comment]
Hi @gzuber the time out issue has been occurred randomly when function tries to run select statement on sql table. Although tables doesn't have many records and app insight shows only time out issue

**Comment by gzuber** [comment]
@sohailbujhs can you provide the name of the function app and function so we can try to look at the error on our end?
