### ISSUE TITLE
Placeholder pooling in Linux consumption apps AB#4658987

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#4476]
Each app now has a new property `PlaceholderId` that indicates a pool id the app can be assigned to
Sample PlaceholderPool Ids:
-   V2 x86 app  `v=1,k=f,e=~2,a=1`
-   V2 x86 app  using a pinned version runtime `v=1,k=f,e=2.0.12342.0,a=1`
-  V2 x86 Node app using node 8.11.1 `v=1,k=f,e=~2,a=1,r=node,rv=~8` . Note default node version is ~8
- 	V2 x86 Node app using node 10.14.1 `v=1,k=f,e=~2,a=1,r=node,rv=~10`

Need to investigate work items needed to use similar strategy for placeholders on linux consumption plan

**Comment by pragnagopa** [comment]
@balag0  - Please open any follow up work items needed.

**Comment by anirudhgarg** [comment]
#AB4658987

**Comment by pragnagopa** [comment]
Following are the tracking items to enable users to pick a runtime version:
- https://github.com/Azure/azure-functions-host/issues/4639

**Comment by pragnagopa** [comment]
cc @paulbatum @ahmelsayed

**Comment by divyagandhii** [comment]
Placeholder pooling is enabled for Linux consumption. It follows the same schema as Windows placeholders.
