### ISSUE TITLE
Support remaining ASP.NET WebHook Receiver types

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#448]
We currently only support GitHub and GenericJson flavors. We need to decide which of the others we want to also support in the runtime and via templates/portal.

This is related to issue https://github.com/Azure/azure-webjobs-sdk-script/issues/270, in that we need to ensure that our secrets management design handles all the requirements of the various WebHook types.

**Comment by christopheranderson** [comment]
Chris owes figuring out which ones should be supported, the work left to support them, etc.

**Comment by fabiocav** [comment]
@christopheranderson have you had a chance to compile a list of receivers we want to support?

**Comment by fabiocav** [comment]
@christopheranderson  Pinging on this. If we need more time to look at this issue, let's move it out of this milestone.

**Comment by fabiocav** [comment]
This is no longer planned. Closing.
