### ISSUE TITLE
AzureFunction fails when deployed from VS2019

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-functions-host#4487]
When using VS2019 AzFunc template, getting following error:

![image](https://user-images.githubusercontent.com/1756871/58202015-d03cc580-7cd6-11e9-9210-8034356c3e55.png)

### AppSettings

![image](https://user-images.githubusercontent.com/1756871/58201960-ac797f80-7cd6-11e9-8726-085a6308272b.png)

### Host file
```

{
    "version": "2.0"
}
```

### Dependencies
```

 <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="3.1.0-beta2" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.28" />
  </ItemGroup>
```

**Comment by gzuber** [comment]
@ddobric Are you still experiencing this issue? If so, do you have an updated time frame of when this has happened most recently?
