### ISSUE TITLE
"map" types to not contain empty values for node

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#4488]
Null or empty values on protobuf `map` types cause buffer overruns on Node.js: https://github.com/Azure/azure-functions-language-worker-protobuf/issues/21

The ultimate goal is to get rid of any `map` types that allow for empty values (ex: `string`): https://github.com/Azure/azure-functions-host/issues/4482

For now, we may need to implement host changes that filter out empty-valued pairs. This is true for http headers as well as environment variables (which will cause apps with empty-valued environment variables to fail when we implement placeholders).

cc: @pragnagopa and @fabiocav

**Comment by pragnagopa** [comment]
Note: Do not have to specialize this fix for node worker as the guidance for handling reload requests on the worker is to clear environment variables and replace

**Comment by pragnagopa** [comment]
Verfied [Environment.GetEnvironmentVariables](https://docs.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariables?view=netcore-2.2) does not include empty or null values.
