### ISSUE TITLE
Time triggered function stopped firing

### ISSUE THREAD

**Issue by portTack** [Azure/azure-functions-host#4490]
#### Investigative information

Please provide the following:

- Timestamp: 2019-05-21T17:00:05.709
- Function App version (1.0 or 2.0): 2.0
- Function App name: https://adcbugtagger.azurewebsites.net
- Function name(s) (as appropriate): ADBugTagger
- Invocation ID: bbea9ad3-5391-4ac7-8d73-897ffc115fa4
- Region:  West US

#### Repro steps

The last time the function was fired was 5/21/2019/ 17:00 UTC. It has stopped firing starting from 5/21/2019 23:00 UTC. And it's still not firing up to this point.

#### Expected behavior
The function is scheduled to run every day at 17:00 and 23:00 UTC.
CRON: 0 0 17,23 * * *
App Service Plan and Always On is enabled
WEBSITE_TIME_ZONE is not set

#### Actual behavior
The function has stopped firing starting from 5/21/2019 23:00 UTC.

#### Known workarounds
I can run the function locally on my dev machine.

#### Related information 

Provide any related information 

* Programming language used: C#
* Links to source
* Bindings used

**Comment by mhoeger** [comment]
@portTack - We see that the timer-triggered function has executed correctly for the past three days.

We do see that you are running with the default setting of logging sampling enabled for Application Insights though. This could cause missing execution logs from your monitor logs. 

Enabling the application insights logging sampling might lead to:
 - Timer Trigger executions missing from your monitor logs
 - Other data log missing

You may just need to adjust the sampling settings to fit your particular monitoring scenario. 
Please review this guidance to [configure sampling](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#configure-sampling).

Note that the next time you have problems with your function app, our first recommendation is to go to the portal, pick "Platform features" => "Diagnose and solve problems" => "Availability and performance" and then the relevant area. In this case, it was "Timer trigger issue analysis"

We'll update our GitHub issue template to have this guidance too 🙂

Please let us know if this doesn't resolve your issue!
