### ISSUE TITLE
What is the intention of AZURE_FUNCTIONS_ENVIRONMENT variable?

### ISSUE THREAD

**Issue by sandeepiiit** [Azure/azure-functions-host#4491]
#### Is your question related to a specific version? If so, please specify:
Function runtime v2
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question
When running a C# function in Visual Studio, I notice that an environment variable called "AZURE_FUNCTIONS_ENVIRONMENT" is set to Development? How is this variable used? Is AZURE_FUNCTIONS_ENVIRONMENT to functions what ASPNETCORE_ENVIRONMENT is for asp dotnet core web apps?
I am planning to use on those two variables to load an environment specific settings file: appsettings.{environmentname}.json, and I am wondering which one is the right approach?

**Comment by kashimiz** [comment]
You'll want to use `AZURE_FUNCTIONS_ENVIRONMENT`. The Functions runtime that powers a Function app on Azure is the WebHost project in this repo. As the host is initializing, it looks for the `AZURE_FUNCTIONS_ENVIRONMENT` app setting (as `EnvironmentSettingNames.EnvironmentNameKey`) and [passes it to the IWebHostBuilder](https://github.com/Azure/azure-functions-host/blob/bb15fba262572a9af1aff7f57edfaeb0f9f9b9de/src/WebJobs.Script.WebHost/Program.cs#L43).
