### ISSUE TITLE
Custom attributes are not working in Azure Functions

### ISSUE THREAD

**Issue by kyallanum** [Azure/azure-functions-host#4494]
When using custom attributes in Azure Functions they evaluate once when the function is started, but after that each subsequent call does not evaluate the custom attribute. This has been tested on both local environment and the ARM environment. The goal is to have code such as:

`        [FunctionName("Function1")]`
`        [MyTest]`
`        public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequestMessage req, TraceWriter log)`

This works once the properly libraries are imported, but the [MyTest] attribute only evaluates once during the function creation. After that every function call does not evaluate [MyTest]

Is there any way that this can be fixed?
Thank you.

**Comment by kyallanum** [comment]
This is on a Function v1. Should it be on a Function v2 or does that matter?

**Comment by kyallanum** [comment]
Bumping post for visibility.

**Comment by ahmelsayed** [comment]
As mentioned on the internal email thread. Attributes don't get evaluated in C#. Attributes are metadata to attach to classes, methods, properties, etc to allow you, or other libraries to do metaprogramming operations on these constructs. They are not decorators. AOP programming in C# using attributes is a framework or a library feature, not a language feature.

If they are using a library that does that or If you have a repro of someone working in a console app but not in functions, please feel free to reactivate this issue and share your repro.

**Comment by PinoEire** [comment]
> 
> 
> As mentioned on the internal email thread. Attributes don't get evaluated in C#. Attributes are metadata to attach to classes, methods, properties, etc to allow you, or other libraries to do metaprogramming operations on these constructs. They are not decorators. AOP programming in C# using attributes is a framework or a library feature, not a language feature.
> 
> If they are using a library that does that or If you have a repro of something working in a console app but not in functions, please feel free to reactivate this issue and share your repro.

Actually, I suppose we are talking about different things. We are porting from API App to Function. All our endpoints on API App have two attributes declared as follows:

**AuthorizeTenantKeyAttribute : AuthorizeAttribute
AuthorizeJWTTokenAttribute : AuthorizeAttribute**

So that APIs look like this:

**[AuthorizeTenantKey]
[AuthorizeJWTToken]
public IHttpActionResult SomeAPI(int someData)**

As it is evident, we implemented a custom API Key management and a specialised JWT token. This just doesn't work on Azure Function... so how do we port it if that pattern doesn't work?

**Comment by ahmelsayed** [comment]
I see, the original issue made it sound like it's for a generic custom attribute. `AuthorizeAttribute` is an aspnet specific attribute. It won't work outside of aspnet framework. Functions shares some similar aspects to aspnet (like datatypes, base hosting framework, etc) but not all aspnet features will work in Functions. 

/cc @fabiocav in case he has some thoughts on the subject, in particular around `AuthorizeAttribute`

**Comment by fabiocav** [comment]
@ahmelsayed response is accurate.

The ASP.NET authorization attributes are not supported in Azure Functions, and the closest thing we expose would be the WebJobs function filters, which is a preview feature at the moment https://github.com/Azure/azure-webjobs-sdk/wiki/Function-Filters

**Comment by PinoEire** [comment]
@fabiocav Ok, thanks for the pointer. So filters are all we can expect to have to implement such custom authorization, or there will be more to come?
