### ISSUE TITLE
IoT Hub trigger - Higher epoch already exists

### ISSUE THREAD

**Issue by frnk01** [Azure/azure-functions-host#4498]
I'm receiving a lot of exceptions in the applications insights log regarding epoch on a function app using the IoT Hub trigger. Is this something with the implementation of the trigger? Will it be able to cause data loss, or should all "missing" events be picked up on the next trigger run?

#### Investigative information
Error from AI logs:

```
A receiver with a higher epoch '258' already exists. A new receiver with epoch 257 cannot be created. Make sure you are creating receiver with increasing epoch value to ensure connectivity, or ensure all old epoch receivers are closed or disconnected. 

TrackingId:9db1d671-92ee-4acf-8ef9-e2154f6b29ea_B13, 
SystemTracker:182408-UsageMessagingComponentManager, 
Timestamp:2019-05-26T07:00:20 
Reference:e530f0b9-0c33-4bef-bc02-7401780742d5, 
TrackingId:f0b74bd1-7971-4ede-bc80-a797dda6afcb_B13
```

Region: West Europe

**Comment by gzuber** [comment]
@frnk01 Sorry about the delay getting back to you -- do you have a more recent time frame of this happening and an App Name for us to be able to take a look?

**Comment by frnk01** [comment]
@gzuber Look below for latest exception.

_New receiver with higher epoch of '1070' is created hence current receiver with epoch '1069' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:294f1eed0003c88b005c3b6b5d312e00_G17_B31_

I`m also recieving a storage exception, not sure if related but here is the message for that one.
_The lease ID specified did not match the lease ID for the blob. The lease ID specified did not match the lease ID for the blob._

AppId: 3f21850e-6824-4862-8a72-233df8a95912
Region: West Europe

**Comment by gzuber** [comment]
@frnk01 Is this a v2 function? If so, this is part of normal operations and shouldn't affect your app. We'll look into lowering this from an error message.
