### ISSUE TITLE
Multiple Linux consumption apps sharing the same storage account interfere with each other

### ISSUE THREAD

**Issue by Arnavion** [Azure/azure-functions-host#4499]
I have two Linux function apps on the Consumption plan. Both have the same "script path" (path to dotnet core DLL) and are set to use the same storage account. The apps contain one timer-triggered function each with the same timer setting on both, so they almost always get started within milliseconds of each other.

I routinely see one app (let's call it `A`)'s functions start and complete successfully, while the other (let's call it `B`) prints this log and nothing else after that:

```
Job host started
```

`A` prints this log after that one:

```
Host lock lease acquired by instance ID '00000000000000000000000076443FE3'.
```

I figured this meant that `B` failed to acquire the lease. Looking through the code, I see the lease path is derived using the host ID. However the logs also indicate that both apps have the same host ID, since both apps print this message with the same `HostId` value:

```
Starting Host (HostId=none-2137340777, InstanceId=...
```

Based on the implementation in `ScriptHostIdProvider.GetHostIdAsync`, the format suggests that `environment.IsAppServiceEnvironment()` is `false`, so it's falling back to `$"{sanitizedMachineName}-{Math.Abs(GetStableHash(scriptOptions.ScriptPath))}"`. Below are the `WEBSITE_*` env vars, as detected with `System.Environment.GetEnvironmentVariables()` inside the function, so indeed `WEBSITE_INSTANCE_ID` is not set, so `IsAppServiceEnvironment()` would be `false`:

<details>
<summary>Click here</summary>

```
WEBSITE_AUTH_AUTO_AAD
WEBSITE_AUTH_ENABLED
WEBSITE_AUTH_ENCRYPTION_KEY
WEBSITE_AUTH_LOGOUT_PATH
WEBSITE_CONTAINER_READY
WEBSITE_HOME_STAMPNAME
WEBSITE_HOSTNAME
WEBSITE_OWNER_NAME
WEBSITE_PLACEHOLDER_MODE
WEBSITE_RUN_FROM_PACKAGE
WEBSITE_SITE_NAME
WEBSITE_SLOT_NAME
WEBSITE_STAMP_DEPLOYMENT_ID
```

</details>

`System.Environment.MachineName` returns `(none)` which is sanitized into `none`, and of course the script path is identical for both apps as I said above, so the host ID is identical for both apps and only one gets to run.

I assume this also means that when `A` marks its timer-triggered function "completed", future starts of `B` mistakenly believe that `B`'s own timer-triggered function completed successfully last time, so it will not even run it to catch up.

#### Investigative information

Please provide the following:

- Timestamp: `2019-05-28 00:58:00` is just before the host starts for each app. The function itself has a timer trigger of `01:00:00` every day.
- Function App version (1.0 or 2.0): 2.0
- Function App name: `acme-functions-www-arnavion-dev` (didn't run) and `acme-functions-blog-veranon-dev` (ran successfully)
- Function name(s) (as appropriate): `UpdateCdnCertificate`
- Invocation ID: `9718d98d-e06f-44a9-b2c6-f86e20e0c896` for `acme-functions-blog-veranon-dev`
- Region: West US

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used: F# / dotnet core. App is compiled locally (`dotnet publish --configuration Release`) and then I run `func azure functionapp publish` from inside the publish directory.
* Links to source
* Bindings used

<details>
<summary>Source</summary>

```fsharp
[<Microsoft.Azure.WebJobs.FunctionName("UpdateCdnCertificate")>]
[<Microsoft.Azure.WebJobs.Singleton>]
let Run
    ([<Microsoft.Azure.WebJobs.TimerTrigger("0 0 1 * * *")>] timerInfo: Microsoft.Azure.WebJobs.TimerInfo)
    (log: Microsoft.Extensions.Logging.ILogger)
    (cancellationToken: System.Threading.CancellationToken)
    : System.Threading.Tasks.Task =
```
</details>

**Comment by Arnavion** [comment]
On second thought, this should probably go in https://github.com/Azure/Azure-Functions Sorry for the noise.

**Comment by Arnavion** [comment]
Actually, that repo's issue template sends me back here, so I guess this is right after all. (Though this is more of a service-side issue that a problem with the function host.)

**Comment by ggirard07** [comment]
Closing then reopening your issue removed the tag the teams is using to triage issues. Not sure they are going to catch it...

**Comment by Arnavion** [comment]
Looks like this was fixed at some point. The `Starting Host` trace now has a `HostId` that is the function app name, not `none-...` as it was before.
