### ISSUE TITLE
Development work against one Function App mirrored to another in a separate subscription

### ISSUE THREAD

**Issue by marmightygood** [Azure/azure-functions-host#4503]
I created two Powershell Function Apps via the portal, one in a development subscription and one in a production subscription. When I create functions against one app, the functions also show up in the other immediately. Any development work completed on one function is also immediately mirrored in the other. 

#### Investigative information

Please provide the following:

- Timestamp: 2019-05-29 11:00
- Function App version (1.0 or 2.0): 2.0
- Function App name: ma-gdxmanager-dev and ma-gdxmanager-prd
- Function name(s) (as appropriate): PublishGDX
- Invocation ID: N/A
- Region: Autralia East

#### Repro steps

Provide the steps required to reproduce the problem:

1. Open development app ma-gdxmanager-dev
2. Click on PublishGDX to open the editor
3. Add some text (e.g a comment) to the code editor and click "save"
4. Open development app ma-gdxmanager-prd
5. Click on PublishGDX to open the editor

#### Expected behavior

Text added at 3. above should not appear in ma-gdxmanager-prd

#### Actual behavior

Provide a description of the actual behavior observed.

Anything added at 3. appears in ma-gdxmanager-prd

#### Known workarounds

Unknown

#### Related information 

Provide any related information 

* Programming language used - Powershell

**Comment by gzuber** [comment]
@marmightygood Are they sharing the same storage account? Can you check your app settings and make sure the File Connection String and Content Share are different?

**Comment by marmightygood** [comment]
> @marmightygood Are they sharing the same storage account? Can you check your app settings and make sure the File Connection String and Content Share are different?

This would be configuration settings WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and WEBSITE_CONTENTSHARE? 

Yep they're the same.

**Comment by gzuber** [comment]
`WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` being the same is fine if they're sharing the same storage account. However, `WEBSITE_CONTENTSHARE` being the same means both functions are looking at the same files/directories in that storage account for code/config files -- that's why they both update when you only change one.

The most common case for this happening is when there's a mistake in the ARM deployment logic that results in using the same values for that app setting. Are you using ARM deployments?

**Comment by marmightygood** [comment]
No ARM templates, this was just stopgap stuff being done via the GUI. I’ll check when I have access later but it’s possible the configuration file was copied from one function to the other. 

> On 18/07/2019, at 10:09 AM, Graham Zuber <notifications@github.com> wrote:
> 
> WEBSITE_CONTENTAZUREFILECONNECTIONSTRING being the same is fine if they're sharing the same storage account. However, WEBSITE_CONTENTSHARE being the same means both functions are looking at the same files/directories in that storage account for code/config files -- that's why they both update when you only change one.
> 
> The most common case for this happening is when there's a mistake in the ARM deployment logic that results in using the same values for that app setting. Are you using ARM deployments?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
This message has been scanned for viruses and
dangerous content by MailScanner, and is
believed to be clean.
