### ISSUE TITLE
Microsoft.Azure.Documents.Client does not supports latest System.Net.Http version 4.3.4

### ISSUE THREAD

**Issue by ArunRajiv** [Azure/azure-functions-host#4504]
We have component governance policy of security issues for all solutions in our project. Under which, all the nuget packages should be of latest version in all the projects. 

We have an Event Triggered Azure Function where we use **Microsoft.Azure.Documents.Client**  nuget  package which has dependency on **System.Net.Http**

while upgrading the System.Net.Http to latest version, we get the build error as captured in the below screenshot. It looks like, **Microsoft.Azure.Documents.Client** does not support latest version of **System.Net.Http**.  Any help is appreciated?

![image](https://user-images.githubusercontent.com/19972139/58543071-4e8bf100-821c-11e9-9c14-63b4f08f7a6d.png)

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0): 1.0
- Function App name: Event Triggered
- Function name(s) (as appropriate): 
- Invocation ID:
- Region:

**Comment by fabiocav** [comment]
@ArunRajiv is upgrading to Azure Functions 2.0 an option? There, you have a lot more flexibility when it comes to the dependencies used. Different extensions are also frequently updated.
