### ISSUE TITLE
Emit GBSecond metric from host

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/azure-functions-host#4507]
GBSeconds should be tracked at the host level such that linux metrics flow as well.

**Comment by fabiocav** [comment]
We need to discuss this item.

/cc @paulbatum

**Comment by jeffhollan** [comment]
This came up today during our UX sync.  One of the common tasks customers want to assess is the number of GbSeconds an app has consumed over some period of time.  However, the UX team doesn't have a metric to use to render a graph or chart that shows this.  I see this as needs discussion but would be great to know if there are any major blockers that would prevent us from prioritizing this.

//cc @btardif @ehamai

**Comment by paulbatum** [comment]
@jeffhollan Not sure I follow. The metric that the UX team would graph for that scenario is the Function Execution Units metric in MDM (see [here](https://github.com/Azure/Azure-Functions/wiki/Consumption-Plan-Cost-Billing-FAQ#how-can-i-access-execution-count-and-gb-seconds-programmatically) for more info)

**Comment by jeffhollan** [comment]
Ah thank you! Does this issue track something different?  I was looking for a metric called GBSeconds but great if this covers it.  @btardif @ehamai would be good if we could show this in the app overview of the new UX

**Comment by paulbatum** [comment]
This issue is not very descriptive.. instead of describing the problem it just says to do X.  Not sure what its referring to about linux metrics either, because I just double checked and the MDM metric works fine for linux too.

**Comment by ColbyTresness** [comment]
I don't remember the context but if MDM works fine for linux then I don't think we need a host metric.
