### ISSUE TITLE
Graph QL using Dot net core on azure functions

### ISSUE THREAD

**Issue by klogan12** [Azure/azure-functions-host#4518]
I am implementing Graph QL on Dot net core using Azure function. 
How do i add graphQL middleware in azure function?

How to call this configure method?

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();
            **app.UseGraphQL<StarWarsSchema>();
            app.UseGraphQLPlayground(new GraphQLPlaygroundOptions()) ;**
        }

**Comment by espray** [comment]
@klogan12 I am not aware of anyway to use MVC middleware in AzFunc. For GraphQL, I am current hosting GraphQL and GraphiQL in AzFunc and I dont use the middleware. I only used the middleware as a guide.

**Comment by espray** [comment]
Looks like some form of middleware might be coming #4449

**Comment by klogan12** [comment]
@espray  - How did u implement GraphQL without middleware? Did you use dot net core? Any pointers will be helpful.

**Comment by espray** [comment]
@klogan12 I have gone through several revisions. But this is a good base https://github.com/graphql-dotnet/examples/blob/master/src/AspNetWebApi/WebApi/Controllers/GraphQLController.cs also used the middleware as a guide. From there I added features/tweaks, UserContext, Authorization, Instrumenting, GraphiQL, etc as needed. Right now I have it worked down to an IActionResult, where configuration is all done via the .NET Core dependency injection, builder pattern, configuration, and options patterns.

I will do my best to at least get it up on Git this week. No promises :)

**Comment by yojagad** [comment]
@klogan12 We do not have the kind of middleware support you mentioned. Were you able to get around it?

**Comment by yojagad** [comment]
I'm assuming you have gotten around this , so closing this issue for now. Please feel free reopen/open a new issue if there's anything else needed.
