### ISSUE TITLE
Reset offline state when extension installation fails

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#4526]
If the extension installation process triggered over the API fails, the runtime should switch back to an online state to prevent having the application left in offline mode.

**Comment by patricklee2** [comment]
https://icm.ad.msft.net/imp/v3/incidents/details/124149471/home

**Comment by fabiocav** [comment]
Moving to sprint 54 as we need to close on feedback from @soninaren, who is currently out.
