### ISSUE TITLE
Functions corrupt json input when values are in ISO 8601 date format

### ISSUE THREAD

**Issue by IvanAlekseev** [Azure/azure-functions-host#4529]
#### Investigative information
- Function App version (1.0 or 2.0): 2.0

#### Repro steps
Having a http function accepting a json with a single string property I got this string corrupted when the value is in ISO 8601 date format

Send a post request:
```
{
  "EatMe" : "2019-06-04T16:08:22+00:00"
}
```

#### Expected behavior

Receive this response:
```
2019-06-04T16:08:22+00:00
```

#### Actual behavior

Receiving this response:
```
06/04/2019 17:08:22
```

#### Related information 
Looks like corruption happens in this [class](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/src/WebJobs.Extensions.Http/Utility.cs)

<details>
<summary>Source</summary>

```csharp
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;

namespace FunctionApp1
{
    public class Food
    {
        public string EatMe { get; set; }
    }

    public static class Function1
    {
        [FunctionName("Function1")]
        public static string Run([HttpTrigger(AuthorizationLevel.Function, "post")] Food food)
        {
            return food.EatMe;
        }
    }
}
```
</details>

**Comment by fabiocav** [comment]
@yojagad should this be moved to sprint 55?

**Comment by yojagad** [comment]
@IvanAlekseev  Can you check if the workaround provided here addresses your issue? https://github.com/Azure/azure-functions-host/issues/3370

Basically, you should be able to use DI (by adding a reference to Microsoft.Azure.Functions.Extensions) to configure some of the behavior around JSON formatting

```csharp
[assembly: FunctionsStartup(typeof(FunctionApp1.Startup))]
namespace FunctionApp1
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddTransient<IConfigureOptions<MvcOptions>, MvcJsonMvcOptionsSetup>();
        }
    }
}
```

**Comment by IvanAlekseev** [comment]
@yojagad just tried that workaround and it worked perfectly. It can even parse guid properties now
Thank you!

**Comment by yojagad** [comment]
@IvanAlekseev no problem. Glad it worked!
