### ISSUE TITLE
Binding context using DI

### ISSUE THREAD

**Issue by peterbomers** [Azure/azure-functions-host#4535]
#### Question
Is it possible to access the binding context (for example the service bus message, or the http request) during dependency injection. Something like the IHttpContextAccessor  in asp.net core framework? 

We're building dynamic database connections based on function parameters and DI is a really nice feature for this.

**Comment by brettsam** [comment]
`IHttpContextAccessor` should now be available (it'll be injected into your function class constructor)-- but there's not really an equivalent for other binding triggers. 

Most of those details should be available, however -- for example, you can ask for the SB message directly (or a bunch of the metadata values -- https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#trigger---message-metadata).

Is there a scenario where this isn't working like you'd want?
