### ISSUE TITLE
Suspected issue with latest Azure Functions host run time (2.0.12493)

### ISSUE THREAD

**Issue by Jaffacakes82** [Azure/azure-functions-host#4536]
We use Azure Functions with INodeServices to generate PDFs in our application. The function uses a simple queue trigger to read new items from an Azure Storage Queue. Over the last couple of days, we've noticed a number of our generation jobs hang indefinitely (function run state in WebJobs dashboard is 'Never finished') even though there's been no changes to this area of the code base for a while.

The only thing that's changed is the Azure Functions runtime version to 2.0.12493 as we redeploy our infrastructure quite regularly. Without redeploying the infrastructure or changing any code, and simply downgrading the runtime version back to 2.0.12438.0 has resulted in the jobs succeeding again.

#### Investigative information

Please provide the following:

- Timestamp: 2019-06-05 13:06:49.619
- Function App version (1.0 or 2.0): 2.0
- Function App name: Private.
- Function name(s) (as appropriate): PDFExport
- Invocation ID: 837d7ee60deaf04392329ca8545dd951
- Region: UK South

_Bear in mind, the invocation ID above is of the successful run after downgrading host runtime version. Hopefully this will allow you to identify my function?_

I wish I could provide more information, but unfortunately the Azure Function isn't logging anything useful to application insights.

#### Known workarounds

Downgrade the Azure Functions runtime to 2.0.12438.0.

#### Related information 

Provide any related information 

* Programming language used - C#
* Bindings used - Queue Trigger

**Comment by Jaffacakes82** [comment]
Since I raised this a new version of the host run-time has been released which seems to have fixed the issue.

It would be good to know what was broken before 😄.

**Comment by Jaffacakes82** [comment]
Sorry, re-opening this - still broken in 2.0.12507. Had to revert back to 2.0.12438.0.

**Comment by brettsam** [comment]
@Jaffacakes82 -- sorry for the delay here. Are you continuing to see this? If so, do you have a more recent invocation id and timeframe that I can look at? I can check our backend logs to see what may be happening.

**Comment by Jaffacakes82** [comment]
Hi @brettsam, I think I've narrowed this down to the host runtime restarting every time my function was invoked due to file system changes being detected.

We use a node library that uses PhantomJS to generate PDFs from within our function and I believe this binary was triggering the file watcher to kill the function invocation and restart the function.

Interestingly, I'm pretty sure I wasn't experiencing this behaviour with the version I mention above (2.0.12438.0) but looking through the changes in newer versions to the runtime I couldn't see anything particularly related to file watcher.

**Comment by brettsam** [comment]
That's very interesting -- I'm not sure why it'd be changing from one version to another. It could have been some kind of race condition you were seeing and it wasn't really related to the host versions at all. I'm not sure that code has changed much in a while.

I'm curious -- which folder were the PDFs going to?

(going to close this as it's no longer an active issue)

**Comment by Jaffacakes82** [comment]
> That's very interesting -- I'm not sure why it'd be changing from one version to another. It could have been some kind of race condition you were seeing and it wasn't really related to the host versions at all. I'm not sure that code has changed much in a while.

Very possible. If I cast my mind back, I'm pretty sure it was working consistently as we hard coded the runtime version in our ARM templates to address the issue. Unfortunately, version 2.0.12438.0 then became unavailable in Azure and auto-rolled itself forward to the latest version and we started seeing issues again.

It's a .NET Core function that invokes Node through INodeServices, the PDFs were just being spat out in a folder underneath `D:\home\site\wwwroot` so makes sense that changes were being detected. Happy to assume a race condition on the basis that disabling file watching has got us working with the latest versions 🙂.
