### ISSUE TITLE
Could you show how to configure Azure Function with Azure Active Directory?

### ISSUE THREAD

**Issue by ranouf** [Azure/azure-functions-host#4539]
#### What problem would the feature you're requesting solve? 
I m interested to find a sample code explaining how to secure a Azure Function using Active Directory. Most of the explanations I found use the Portal Azure interface. Is it possible to that by code.
My main purpose is to be able to authenticate my azure function using login/password or Facebook, and other social account available

#### Solution
I would like a sample code explaining how to secure the Azure Function using Active directory

#### Alternatives
At least an article where someone explain how to do that.

#### Additional context
I read how to do that with WebApi (ie: https://www.youtube.com/watch?v=30B7efdpNxI), but most of the explanation I found are for Web Api.

Thank for your help!

**Comment by brettsam** [comment]
Azure Functions can use App Service Authentication (Easy Auth). 

Some resources that should help:
- https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization (contaisn links at the bottom for more details)
- https://blogs.msdn.microsoft.com/stuartleeks/2018/02/19/azure-functions-and-app-service-authentication/

**Comment by brettsam** [comment]
I'm going to close this as it's not an active issue -- but let me know if you have more questions. Thanks!

**Comment by ranouf** [comment]
Thanks, sorry for the delay, your answer helped me
