### ISSUE TITLE
Proxies - Missing x-forwarded headers

### ISSUE THREAD

**Issue by iyerusad** [Azure/azure-functions-host#4542]
Need additional x-forwarded headers when passing through proxy. X-Forwarded-Host, X-Forwarded-Proto, X-Forwarded-OriginalURL

I have some azure functions that use values from `request` to build base host URL. That URL is then is used to call other functions on same host. 

```js
base = `${req.originalUrl.split(":")[0]}://${req.headers.host}`
url = `${base}/api/blahblah`

axios(url)
```

When request to azure function passes through proxy, headers are rewritten. 

Unfortunately, in local dev the rewritten values are theoritical (e.g. `originalURL: httpS://localhost/api/promos` is not real, as actually only running http on port 7071).

Hosting on `https` in localhost is achievable, but still would be missing port info. Would rather avoid `https` in local dev, quicker visibility (no need to MITM https, etc). Also, no certs to deal with (multiple team members on same repo - each may have different machine config/OS).

#### Investigative information

- Timestamp: n/a - local dev
- Function App version (1.0 or 2.0): 2.0.12438.0
- Function App name: n/a - local dev
- Function name(s) (as appropriate): n/a - local dev
- Invocation ID: n/a - local dev
- Region: n/a - local dev

#### Repro steps

1. Hit `http://localhost:7071/api/promos`
2. Request goes through proxy and ends up at expected `http://localhost:7071/api/test`
3. Observe request headers rewritten with theoretical values, e.g. `req.headers.host = localhost`
4. Seek out x-forwarded headers, find only `x-forwarded-for` which is missing: protocol and port.
5. Unable to ascertain original host.

#### Expected behavior

req.headers:
```
<snip>
x-forwarded-host: "localhost:7071"
x-forwarded-proto: "http"
x-forwarded-originalurl: "http://localhost:7071/api/promo"
</snip>
```

#### Actual behavior

req.headers:
```
  "host": "localhost",
  "x-forwarded-for": "127.0.0.1"
```

#### Known workarounds

Wouild prefer to avoid having to add manually (as have multiple proxies), but can partially workaround by adding [requestOverrides](https://docs.microsoft.com/en-us/azure/azure-functions/functions-proxies#requestOverrides) to proxy definition. Can mimic some, but not all info (specifically missing protocol, but wouldn't mind originalURL either):
```
    "promos_default": {
      "matchCondition": {
          "route": "/api/promos",
          "methods": ["GET","POST"]
      },
      "backendUri": "https://localhost/api/test",
      "requestOverrides": {
        "backend.request.headers.x-forwarded-host": "request.headers.host"
      }
    }
```

[Additional request parameters](https://docs.microsoft.com/en-us/azure/azure-functions/functions-proxies#additional-request-parameters) doesn't have option for "request.originalurl" only:

> request.method
> request.headers.HeaderName
> request.querystring.ParameterName

#### Related information 

* Programming language used: **Javascript/node**
* Links to source: **Added**, expand below
* Bindings used: skipped

Ref: https://github.com/MicrosoftDocs/azure-docs/issues/25891

<details>
<summary>Source</summary>

proxies.json
```json
{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "promos_default": {
      "matchCondition": {
          "route": "/api/promos",
          "methods": ["GET","POST"]
      },
      "backendUri": "https://localhost/api/test",
      "requestOverrides": {
        "backend.request.headers.x-forwarded-host": "request.headers.host"
      }
    }
  }
}
```

test/index.js
```js
module.exports = async function (context, req) {
    context.res = {
      body: req.headers
    }
};
```
</details>

**Comment by brettsam** [comment]
@iyerusad -- this is only for the local dev scenario? Do things work when deployed? 

@safihamid -- assuming this is only for local dev, is there something we can do to fix this?

**Comment by safihamid** [comment]
Don't think there is a quick fix here, +@vfedonkin in case he has some thoughts...

**Comment by iyerusad** [comment]
Applies in local dev and hosted/prod. Technically in Prod you can with a degree of certainty assume https but thats just not great logic. Since proxies rewrite traffic, these x-forwarded headers seem key as part of proxy functionality.

**Comment by fabiocav** [comment]
@vfedonkin @safihamid any thoughts on how we want to proceed here?

**Comment by stevewithey** [comment]
Still no progress on setting X-Forwarded headers on App Proxies???

**Comment by ThejaChoudary** [comment]
@safihamid @vfedonkin can you please look into this further.

**Comment by v-anvari** [comment]
These changes are not expected to be made anytime soon. For this concern, it is suggested to use APIM
