### ISSUE TITLE
Build Pipeline Failed on Azure DevOps after updating to V 1.0.28

### ISSUE THREAD

**Issue by sakibbinsharif** [Azure/azure-functions-host#4545]
After updating to V 1.0.28 build pipeline failed for us. 
Solution is building without having any issue in local visual studio. Build starts to fail when the build agent tries to build in Azure DevOps.

received the following error from build agent log:
##[error]C:\Users\VssAdministrator\.nuget\packages\microsoft.net.sdk.functions\1.0.28\build\netstandard1.0\Microsoft.NET.Sdk.Functions.targets(74,5): Error : The ExtensionsMetadataGenerator package was not imported correctly. Are you missing 'C:\Users\VssAdministrator\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.1.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets' or 'C:\Users\VssAdministrator\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.1.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.props'?

**Comment by brettsam** [comment]
Can you share how you're building on your build machine? If you reference 1.0.28, it should be pulling in the ExtensionsMetadataGenerator package -- is that path in the error message correct?

If someone hitting this would be okay with running the build and appending the "/bl" command-line switch and emailing me the "msbuild.binlog" file that's generated, that'd be a big help in tracking it down. My Microsoft email is in my github profile.

**Comment by klogan12** [comment]
This is the error i got. I checked the files do exist in that folder.

Severity	Code	Description	Project	File	Line	Suppression State
Error		The ExtensionsMetadataGenerator package was not imported correctly. Are you missing 'C:\Users\kloganathan\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.1.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets' or 'C:\Users\kloganathan\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.1.1\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.props'?	TurinFunctionApps	C:\Users\kloganathan\.nuget\packages\microsoft.net.sdk.functions\1.0.28\build\netstandard1.0\Microsoft.NET.Sdk.Functions.targets	74

**Comment by SteveLockley** [comment]
I have this issue, just build a blank project with the version 1 functions template in visual studio 2017. Then update the version of the functions sdk to 1.0.28 and you will see this error.

**Comment by TynThordin** [comment]
Same error for me after updating to Functions SDK 1.0.28 from 1.0.27 in a .NET Framework 4.8 project.

**Comment by brettsam** [comment]
@SteveLockley (and really anyone else seeing this) -- would you be able to run `msbuild {project file} /bl` and email me the msbuild.binlog file? My email is in my github profile.

I'm not seeing this when I try to do a simple repro, so there must be some subtle difference that I'm missing. Thanks in advance!

**Comment by brettsam** [comment]
I see it now. I had to clear my nuget cache and I get the same error. I was too aggressive in validating imports in my last change and it affects .NET 4.x projects.

The workaround is to directly reference ExtensionsMetadataGenerator 1.1.1. I'm working on the fix now. Thank you all for the report!
