### ISSUE TITLE
FunctionLoadRequest.Metadata.Directory is empty when the function app has a proxy

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-host#4549]
#### Investigative information
FunctionLoadRequest.Metadata.Directory is empty when the function app has a proxy

#### Repro steps
* Create a PowerShell Function App 2.0
* Create a HttpTrigger Function
* Add proxies.json file: https://github.com/Azure/azure-functions-host/blob/dev/test/WebJobs.Script.Tests.Integration/TestScripts/ProxiesOnly/proxies.json

#### Expected behavior

FunctionLoadRequest.Metadata.Directory should not be empty.

**Comment by icpenguins** [comment]
This is a blocking issue as proxies are required for the application architecture. Is there an ETA to when this will be resolved as the function has not worked for over 2 weeks?

**Comment by brettsam** [comment]
@pragnagopa -- any idea on this one? Sounds like a bug but wasn't sure whether it's in proxies or lang worker...

**Comment by Francisco-Gamino** [comment]
This issue was fixed by 

https://github.com/Azure/azure-functions-host/pull/4582
https://github.com/Azure/azure-functions-powershell-worker/pull/261
