### ISSUE TITLE
Azure Functions runtime slow since 2.0.12408.0 

### ISSUE THREAD

**Issue by adobedoe** [Azure/azure-functions-host#4551]
**Describe the bug**
I have around 15k orchestration instances running daily with sub-orchestrators and many activity functions that was running very fast on sdkVersion=2.0.12382.  My function host had FUNCTIONS_EXTENSION_VERSION=~2 so it automatically took the latest version of the runtime.

I can see in App Insights that the execution time increased significantly when the runtime went to 2.0.12427 and is still slow on the latest version 2.0.12438

**Investigative information**

- Durable Functions extension version: > 2.0.12382
- Function App version (1.0 or 2.0): 2.0
- Programming language used: C#

***If deployed to Azure***

- Timeframe issue observed: From 19th April to today
- Function App name: fnPP-Processor
- Function name(s): Orchestrators_ProcessEventPayload <-- entry point
- Region: UK South
- Orchestration instance ID(s): f2b6f571-3fc1-4b1a-9efd-2d00789fe6f7 (slow), cc1d0173-0391-4da9-96a0-3418c97bc2d3 (fast)

I have seen that the control queues grow very large with the later version of the runtime and are not evenly distributed.  They also take a very long time to clear.  This does not happen with the earlier version of the runtime.

**Comment by brettsam** [comment]
@lmolkova -- is there anything tracking this issue on the App Insights side?

**Comment by lmolkova** [comment]
@brettsam we are tracking this in internal VSO backlog. I also created github issue https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/900

**Comment by brettsam** [comment]
Has anyone else hit this recently I'm trying to track down repros so we can check our mitigations. Thanks in advance.

**Comment by ericsampson** [comment]
I think this could be closed now as it was resolved AFAIK?

**Comment by brettsam** [comment]
Agreed.
