### ISSUE TITLE
No Log Information when Java Function Fails

### ISSUE THREAD

**Issue by TurtleBeach** [Azure/azure-functions-host#4552]
A Java function which fails (I believe due to timeout, though with NO log information I am not certain) does not appear in AppInsights Log. If the same function succeeds, an appropriate Log entry appears.

The function accesses blob storage, creates a zip file package of several files, and returns a link for downloading the zip file. SAS is used for authentication. I believe the issue is that it is taking to long to create the zip package (a lot of large files). I need to fix that, but it is disappointing that with all the traffic about logs in the function host issues, that NOTHING is generated when an error occurs. In this case I was unfortunately expecting an error, but now I have ZERO confidence that I can believe any logs.

#### Investigative information

Please provide the following:

- Timestamp: Approximately 20:30 UTC on June 9 2019
- Function App version (1.0 or 2.0): 2.0.12493.0
- Function App name: neuralstudio-get-download-link
- Function name(s) (as appropriate):
- Invocation ID: NOT AVAILABLE BECAUSE NO LOG ENTRY GENERATED
- Region: EastUS

#### Repro steps

Provide the steps required to reproduce the problem:

Trigger function from PRODUCTION web site (user clicks "Download" link).

#### Expected behavior

Files related to operation corresponding to the specific "Download" should be marshalled, streamed to a zip file, and made available for download. If an error occurs, an Http error code should be returned and a failure should be logged by AppInsights.

#### Actual behavior

If an error occurs (e.g., function execution timeout), no error is returned and no AppInsight log entry is generated.

#### Known workarounds

Move to a perfect world.

#### Related information 
Java function

**Comment by ankitkumarr** [comment]
@TurtleBeach, I looked at our logs and I do not see any function invocation between 2019-06-09 01:42 UTC and 2019-06-10 01:42. 

Additionally, I only see an HttpTrigger function in the app, contrary to any Timer Trigger you mentioned. Perhaps you were seeing issues in some other function app?

**Comment by TurtleBeach** [comment]
@ankitkumarr. The function in question is in fact an HttpTrigger function. Not sure why you interpreted anything I said as being relate to a timer trigger. I believe the function failed due to timing out (running longer than 10 minutes), though there could have been another cause, And that is why the lack of log information was/is frustrating. I caused the function to be executed multiple times with the potentially problematic payload, and none of the executions were recorded in logs; and in only one case was an error returned to our GUI. Interspersed with the problematic executions were successful executions (where the files to be zipped and downloaded were known to be small). That said, after identifying the issue on June 10 I have been distracted with other activities and have not performed further investigation, But I do emphasize that I am certain that around the times I noted above the function should have executed (but failed with some kind of error) multiple times, in addition to the several times that it succeeded.
Jack

**Comment by ankitkumarr** [comment]
@TurtleBeach, sorry somehow I read "Trigger function" as "Timer function". I apologize.

I expanded the timeframe and I do see a failed timeout execution on June 8 instead of June 9 around 20:30.

We do turn on sampling on Application Insights logs by default. That might be why you are not seeing all the logs. To turn off sampling or read more about it, you can visit [this doc page]( https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#configure-sampling).

@brettsam for fyi.
