### ISSUE TITLE
Remote Debugging - Break points does not resolve symbols

### ISSUE THREAD

**Issue by klogan12** [Azure/azure-functions-host#4562]
I tried Remote Debugging using Attach process method on port 4022.
I selected CoreCLR code , and w3wp.exe. But breakpoints are not hit due to symbol issues.
I am using Visual Studio 2019. Did not work from Cloud explorer as well.

**Comment by brettsam** [comment]
@gzuber -- can you see if you can reproduce this?

**Comment by gzuber** [comment]
@klogan12 I was able to publish a TimerTrigger .NET Core C# app to Azure and successfully remote debug it from Visual Studio 2019 -- is there something more specific to your scenario that I should try to reproduce? Did you deselect `Require source files to exactly match the original version` and `Enable just my code` under `Debug -> Options`?
