### ISSUE TITLE
DI and Custom Binding configuration in Startup.cs

### ISSUE THREAD

**Issue by PiotrWachulec** [Azure/azure-functions-host#4566]
#### Is your question related to a specific version? If so, please specify:
Yes - the current version - that supports DI.
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All)
C#
#### Question
In my function app I would like to use new Dependency Injection feature and Custom Input Binding. So for now for Custom Binding the configuration in Startup class looks like below:
~~~~
[assembly: WebJobsStartup(typeof(Startup))]
namespace MyNamespace
{
    public class Startup : IWebJobsStartup
    {
        public void Configure(IWebJobsBuilder builder)
        {
            builder.AddMyCustomInputBinding();
        }
    }
}
~~~~
For the DI the configuration should look like below:
~~~~
[assembly: FunctionsStartup(typeof(MyNamespace.Startup))]
namespace MyNamespace
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddSingleton<IService, MyService>();
        }
    }
}
~~~~
So my question is that is there any possibility to implement configuration for Custom Input Binding using IFunctionsHostBuilder? Or is there any workaround for that?

Thanks in advance!

**Comment by brettsam** [comment]
Do you already have an input binding written and want to use it? If so, you can continue to use `IWebJobsStartup` -- it will work. Or you can add a new extension that allows you to call `.AddMyCustomInputBinding()` on `IFunctionsHostBuilder`. The mechanism behind the scenes is exactly the same.

**Comment by PiotrWachulecChmurowisko** [comment]
@brettsam Thanks a lot, I'll try to do it.

**Comment by PiotrWachulec** [comment]
Thanks! I'll try to do it in this way.

**Comment by brettsam** [comment]
Gonna go ahead and close this issue -- let me know if you run into any issues and feel free to re-open if needed.
