### ISSUE TITLE
Cant access advanced tools (Kudu) with Linux Function app using Python

### ISSUE THREAD

**Issue by MCL-Fulljames** [Azure/azure-functions-host#4567]
#### Investigative information
- Timestamp: 13/6/2019 - 08:52am
- Function App version (1.0 or 2.0): 2.0
- Region: West Europe

#### Repro steps
Deploy a Linux Python Function app, in the platform features try at open the "advanced tools (Kudu)"

#### Expected behavior
Open Kudu console when clicked within the platform features of the function app.

#### Actual behavior
When the Kudu link is clicked within the platform features nothing happens as seen in below image:
<img width="421" alt="kudu" src="https://user-images.githubusercontent.com/51404084/59414326-32aa5280-8db9-11e9-86ce-48e765824d5d.PNG">

#### Related information 
* Programming language used 
    Python with Linux OS

**Comment by ankitkumarr** [comment]
@MCL-Fulljames, I am guessing you are on a Consumption plan. Advanced Tools (Kudu) is currently not supported for Linux Consumption plans. 

Closing this issue, feel free to re-open if you have further questions.

@dariagrigoriu as fyi that it does not show as disabled in the portal.
