### ISSUE TITLE
1.x: Errors when adding nuget package for multiple Functions in a single App?

### ISSUE THREAD

**Issue by dawwa** [Azure/azure-functions-host#4568]
Would you please help to understand how we can add nuget package reference for multiple functions in an app?

As seen in the screenshot.
Initially I added the project.json on my first function, when I do the same for my second function, the NuGet folder does not get created, and I also **get the error below and my second function cannot run.** 

**If my function need reference nuget package, do I have to create dedicate app for each single function?**

![Capture](https://user-images.githubusercontent.com/44714043/59450644-82d7e380-8dbe-11e9-8ce5-fd3ea30f9add.PNG)

**Comment by brettsam** [comment]
Can you share what is in your `project.json` file? I'd also recommend trying to develop locally using VS or VS Code -- it'll allow you to test locally and share packages in a way that may be more familiar than using the in-portal experience.
