### ISSUE TITLE
Refresh language worker options after specialization

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#4574]
WorkerConfigs are initialized here:
https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/Configuration/LanguageWorkerOptionsSetup.cs#L25

Worker configs need to refreshed after specialization to allow customizing any language worker processes that start inside jobhost

cc @christopheranderson

**Comment by pragnagopa** [comment]
Language worker options can only be configured at the application level. These options are not exposed in 'host.json`. Need to remove https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/ScriptHostBuilderExtensions.cs#L165 and Jobhost services need to read cached values from webhost level

**Comment by pragnagopa** [comment]
cc @divyagandhii 
This issue is also causing noise in the logs during specialization for python linux apps:
```
Version ~2 is not supported for language python
System.NotSupportedException:
   at Microsoft.Azure.WebJobs.Script.Rpc.RpcWorkerDescription.ValidateRuntimeVersion (Microsoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: /src/azure-functions-host/src/WebJobs.Script/OutOfProc/Rpc/RpcWorkerDescription.csMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 141)
   at Microsoft.Azure.WebJobs.Script.Rpc.RpcWorkerDescription.ValidateWorkerPath (Microsoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: /src/azure-functions-host/src/WebJobs.Script/OutOfProc/Rpc/RpcWorkerDescription.csMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 115)
   at Microsoft.Azure.WebJobs.Script.Rpc.WorkerConfigFactory.GetHydratedWorkerPath (Microsoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: /src/azure-functions-host/src/WebJobs.Script/OutOfProc/Rpc/Configuration/WorkerConfigFactory.csMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 253)
   at Microsoft.Azure.WebJobs.Script.Rpc.WorkerConfigFactory.AddProvider (Microsoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: /src/azure-functions-host/src/WebJobs.Script/OutOfProc/Rpc/Configuration/WorkerConfigFactory.csMicrosoft.Azure.WebJobs.Script, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null: 142)
```
related issue #5211

**Comment by thelgevold** [comment]
@pragnagopa 
We are seeing the `Version ~2 is not supported for language python` message in our .Net functions. 

It appears to log this error every time the .Net host starts up. Will the proposal to remove language worker options setup at Jobhost level fix this?

**Comment by pragnagopa** [comment]
@thelgevold - this error is causing noise in the logs. App it self is functionally OK.

Can you tell us more about your function app environment? Windows or linux? Consumption or dedicated? It would be great if you can share region for your app and approximate time range when you see this error.

**Comment by thelgevold** [comment]
@panchagnula  We are running Linux in the consumption tier (East US). The error seems to be happening very reliably. I should point out that we have multiple function apps sharing a common storage account,

**Comment by panchagnula** [comment]
@thelgevold the functions folks should be able to help you out here.

**Comment by divyagandhii** [comment]
> 
> 
> @panchagnula We are running Linux in the consumption tier (East US). The error seems to be happening very reliably. I should point out that we have multiple function apps sharing a common storage account,

@thelgevold , as @pragnagopa  said above, that error is noise. If your functionality is impacted, it is not due to this error.

**Comment by thelgevold** [comment]
@panchagnula @panchagnula Yeah, it doesn't seem to impact the app, but I think it would make sense to remove this log message since it is creating some amount of confusion and registers as errors in the logs.

**Comment by tomkerkhove** [comment]
We are impacted by this as well on Linux-based consumption functions which is causing our alerts to go off all the time.

Is there an ETA to resolve this?

**Comment by tomkerkhove** [comment]
Any update on this? This is still causing production alerts to go off without a reason

**Comment by pragnagopa** [comment]
Referenced issue #5279 is fixed and should not throw errors any more. 
@tomkerkhove - Can you please share the error message you are seeing now?

**Comment by tomkerkhove** [comment]
We are still seeing the same error message in West Europe 🤔

**Comment by pragnagopa** [comment]
Fix to eliminate noise in the logs is part of https://github.com/Azure/azure-functions-host/releases/tag/2.0.12949 

@tomkerkhove  - Can you please check functions runtime version your app is using?

**Comment by tomkerkhove** [comment]
We are seeing this on function apps with version `2.0.12888.0 (~2)`.

How do we force an upgrade, probably not possible :(

**Comment by pragnagopa** [comment]
Apologies. Runtime 2.0.12949 is not released to linux yet.  Please see: https://github.com/Azure/app-service-announcements-discussions/issues/132 for update on the release.

cc @divyagandhii @gzuber

**Comment by pragnagopa** [comment]
fyi @mhoeger

**Comment by tomkerkhove** [comment]
Thank you for the heads up, I'll subscribe to that repo to see what the new runtime version is since it was rolled back.

Small question, how can we know where it's being rolled out to and what OS? The issue doesn't really clarify this? 🤔

**Comment by pragnagopa** [comment]
Please do subscribe to repo: https://github.com/Azure/app-service-announcements/ as well. For each runtime release we post an annoucement on this repo. Issue is closed after roll out completes to production for both windows and linux. If not, you can ping on discussion issue linked to the runtime release for latest updates.

**Comment by anirudhgarg** [comment]
We are in the process of releasing the later runtime to Linux Consumption as we speak.

**Comment by tomkerkhove** [comment]
Awesome, thanks @anirudhgarg

**Comment by pragnagopa** [comment]
cc @AnatoliB 
Assigning this to Sprint 74 as this is a blocker for Powershell placeholders.

**Comment by AnatoliB** [comment]
@pragnagopa Assuming that:

- this issue is not resolved, **and**
- https://github.com/Azure/azure-functions-host/pull/5831 is **not** merged, **and** 
- PowerShell-specific placeholder pools are **not** configured,

would PS7 apps still hit the problem? Do you know if PS7 apps will still find a generic Functions v3 placeholder and start a PS6 worker because the correct FUNCTIONS_WORKER_RUNTIME_WORKER variable is not injected yet?

**Comment by pragnagopa** [comment]
Apologies for the delayed response on this issue. I will prioritize a fix for this during this sprint.

> would PS7 apps still hit the problem? 

I will verify and get back to you on this.
