### ISSUE TITLE
Publish from VS 2019 fails

### ISSUE THREAD

**Issue by klogan12** [Azure/azure-functions-host#4578]
Publish from VS 2019 fails with below error. It works when i try to publish to newly created function app. Any insights or logs to check?

System.AggregateException: One or more errors occurred. ---> System.Exception: Publishing failed.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<>c__DisplayClass26_0.<IsBuildCompletedSuccessfully>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.Model.DefaultPublishSteps.<DefaultCorePublishStep>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__176.MoveNext()
---> (Inner Exception #0) System.Exception: Publishing failed.<---

===================

**Comment by PureKrome** [comment]
@klogan12 

> newly created function app

- Did you create this function app before? How did you create it? Did someone else create it?
- Are you trying to publish to an _existing_ Azure function? (refer to above, also)
- What version of the azure function tools/cli etc are you using?

The team will probably require heaps more info to help you.

**Comment by klogan12** [comment]
@PureKrome  I created function app from Azure portal. it used to work when i publish function code from VS 2019.
Lately it started throwing this error.  Publishing same project to different function app is working fine. So i guess it is issue on the function app side.

Azure function core tools version : 2.7.1158

**Comment by fabiocav** [comment]
@klogan12 if this failure is only happening to one Function App, could you please share the app name? Or, you can also share an invocation ID, region and timeframe so we can take a closer look at the logs.

Based on the stack above, I'm also curious... have you tried to reconfigure the deployment target/re-download the publish profile?

**Comment by klogan12** [comment]
@fabiocav  Function app: turinfunctionapps
I tried reconfig/redownload. IT did not help.

Today i tried to push several times around 12:00 to 12:10PM EST.

**Comment by klogan12** [comment]
@fabiocav  I created new function app and deployed the code there and it worked. I am going to delete the function app that had this issue.  Let me know if you need any further information.

**Comment by TehWardy** [comment]
I tihk i'm hitting this too. 
everyhtng builds and runs fine. 
Left a working deployable solution on friday, came in this morning to fix something completely unrelated and it's unable to publish. 

This is what my VS output window has to say about the matter ...

> 1>------ Build started: Project: Workflow, Configuration: Debug Any CPU ------
> 1>Workflow -> D:\tfs\clx\Dev\v3\Workflow\bin\Debug\netcoreapp2.2\bin\Workflow.dll
> 2>------ Publish started: Project: Workflow, Configuration: Debug Any CPU ------
> 2>Restore completed in 893.78 ms for D:\tfs\clx\Dev\v3\Core.Objects\Core.Objects.csproj.
> 2>Restore completed in 893.07 ms for D:\tfs\clx\Dev\v3\Workflow\Workflow.csproj.
> 2>Restore completed in 893.31 ms for D:\tfs\clx\Dev\v3\Core.B2B.Objects\Core.B2B.Objects.csproj.
> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /unsafe- /checked- /nowarn:1701,1702,1701,1702,2008 /nostdlib+ /platform:x86 /errorreport:prompt /warn:4 /define:TRACE;DEBUG;NETCOREAPP;NETCOREAPP2_2 /errorendlocation /preferreduilang:en-US /reference: ... <long list of references cut for readability reasons>
> 2>Workflow -> D:\tfs\clx\Dev\v3\Workflow\bin\Debug\netcoreapp2.2\win-x86\bin\Workflow.dll
> 2>System.IO.FileLoadException: Could not load file or assembly 'Workflow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
> 2>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
> 2>   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
> 2>   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
> 2>   at MakeFunctionJson.FunctionJsonConverter.TryGenerateFunctionJsons()
> 2>   at MakeFunctionJson.FunctionJsonConverter.TryRun()
> 2>Error generating functions metadata
> 2>
> 2>Metadata generation failed.
> ========== Build: 1 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========
> ========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

Things i've tried ...
 - Deleted my entire local copy of the repo, and all nuget packages.
 - Flushed out VS temp files and rebooted the machine.
 - Fetched solution, built and run the azure function locally to confirm it's all good.
 - Right click > publish

I can confirm ...
 - I'm running .Net Core 2.2 latest assemblies 
 - Latest .29 release of Azure Functions
 - VS2019 fully patched.
 - Problem only seems to be with the cloud deploy, everything else is fine.

**Comment by Ali-Rizwan-Ashraf** [comment]
What's the solution?

**Comment by RLittlesII** [comment]
@Ali-Rizwan-Ashraf In the folder where your Azure Function .csproj file lives there is a `Directory.Build.targets` file.  This seems to only exist for azure functions that are upgraded.  If you do File => New Project and start a new one (from vs v16.3.8 at least), this file doesn't seem to exist.

![image](https://user-images.githubusercontent.com/6969701/70544560-e22a6c80-1b31-11ea-96e7-16c1b02f8176.png)

There is the following `PropertyGroup` node is in that file

```
    <PropertyGroup>
        <_IsFunctionsSdkBuild Condition="$(_FunctionsTaskFramework) != ''">true</_IsFunctionsSdkBuild>
        <_FunctionsExtensionsDir>$(TargetDir)</_FunctionsExtensionsDir>
        <_FunctionsExtensionsDir Condition="$(_IsFunctionsSdkBuild) == 'true'">$(_FunctionsExtensionsDir)bin</_FunctionsExtensionsDir>
    </PropertyGroup>
```

remove the extra `bin` at the end of the `_FunctionsExtensionsDir` and all should be good.
