### ISSUE TITLE
Azure function timer trigger is running mysteriously

### ISSUE THREAD

**Issue by baterphq** [Azure/azure-functions-host#4593]
Hello,

regarding to my question on StackOverflow and Katy Shimizu I'm posting my question also here:
https://stackoverflow.com/questions/56478013/azure-function-timer-trigger-is-running-mysteriously?noredirect=1#comment99646680_56478013

I've got one Azure function with a timer trigger for 01:00. The function is V1 and I use c#-script for it. The function is doing an post request to another API.

Actually the function and the timer trigger works but sometimes I see that the function is triggered two times.

![xoexR](https://user-images.githubusercontent.com/51989010/59748173-cd53d700-927a-11e9-965a-fbe113cbab35.png)

So as you can see the timer triggers my function every day on 01:00 but on the 4th of July it triggers the function also on 01:59. At this time everybody sleeps so I can exclude that the function was triggered manually at the portal or something else.

Where can I also check why the function has been triggerd? In the eventlog I only found this a few seconds before the second run:
`
<Data>
Recycling application MACHINE/WEBROOT/APPHOST/MY-TIMER-TRIGGER [TID 22456][PID 27328]
</Data>`

Here is the function.json of the function, if it is necessary:

```
{
  "bindings": [
    {
      "name": "myTimer",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 0 1 * * *"
    },
    {
      "type": "table",
      "name": "outTable",
      "tableName": "myTableStorage",
      "connection": "myTableStorage_STORAGE",
      "direction": "out"
    }
  ],
  "disabled": false
}

```

Yesterday we had the exact behaviour. I have started the function now again to get the function ID.
FunctionID: 02603585-9d94-4ede-b570-ed890c9b5b70
UTC: 2019-06-19T08:09:58.222
The function is running on an AppServicePlan in WestEurope.

**Comment by ankitkumarr** [comment]
@baterphq, This happened because the execution that started at 01:00 failed and never completed successfully. The failure at 01:59 caused Functions host to restart and it realized that it hadn't yet ran 01:00 to completion. So, it ended up running the function again.

I noticed that you have multiple timer triggers in your function app. Do all those functions are expected take a while to run? 

Please keep in mind that only one timer trigger can run at a time. So if you have an ongoing function that is long running, it can cause issues if functions interfere with each others schedules.

**Comment by baterphq** [comment]
Hi @ankitkumarr and thanks for your investigation.
Yes, the API which is called by this timer function can run for a long time (2hours and more). Are there best practices to get this problem solved?

**Comment by ankitkumarr** [comment]
@baterphq, I think you'd want to make sure there's no overlap in the schedules of your functions. So, if you have too many functions, each taking a while to run (such that there is a chance of overlap), I would suggest splitting them up in multiple function apps.
You just want to take into consideration that only one timer function can run at one time per function app. :)

Hope that solves your issue.

**Comment by baterphq** [comment]
Hi @ankitkumarr, I've checked the schedules and also checked how long the other functions in this function app are running. The last function before is finished ~1 hour before the this function is triggered, so I think that this can't be the reason for this behaviour.

**Comment by brettsam** [comment]
@baterphq -- have you seen this more recently? I see a log stating `Function 'Host.Functions.booking' is past due on startup. Executing now.`, which explains why we're running the function again.

When I look at the previous invocation (`fd35acaa-98aa-418b-90d3-6fafc6896bd4`), I see the function beginning but never completing. That means that we'd not record this as a successful invocation, and we'd try again the next time the host starts. Do you see the same thing?
