### ISSUE TITLE
DI Exception when trying to resolve service in the Run function

### ISSUE THREAD

**Issue by andronachev** [Azure/azure-functions-host#4594]
Hi,

I implemented the Startup class for adding my business services to the initial ServiceCollection (so that I don't lose for example all the logging services that come with the framework).

My function needs to resolve different services (EventHandlers) based on the event type that it receives, so I thought of making use of the ServiceCollection, call BuildServiceProvider() and then get the service by Type, however, I see it throws an exception:

`System.Private.CoreLib: Exception while executing function: PingHttpTrigger. Microsoft.Extensions.DependencyInjection: Unable to resolve service for type 'Microsoft.Azure.WebJobs.Script.IEnvironment' while attempting to activate 'Microsoft.Azure.WebJobs.Script.Configuration.ScriptHostOptionsSetup'.
`

This only happens if my service/eventhandler has an` ILogger<T> `as a dependency

To be able to resolve the service in the Run method, I saved the IServiceCollection from the Startup method in a static property, then accessed it in the Run() method, like so:

`var eventHandlerInstance = DependencyResolution.ServiceCollection.BuildServiceProvider().GetService(eventHandlerInterfaceType);`

Maybe that's the issue, but I don't think so.

Thoughts ?

The whole point of this is so I can later on configure the Logging to use NLog, but till then, I hit this wall. Previously resolving the EventHandler in the Run function worked, because I was creating my own ServiceCollection, but that left out the framework stuff.

Thanks for your feedback,
Vlad

**Comment by sec** [comment]
Getting the same error - it's linked with using "IHttpClientFactory' in copnstructor of my custom service that's being injected into "Run" method.

**Comment by fabiocav** [comment]
@andronachev can you please share a repro so we can better understand how you're performing the service registration.

Also, you've mentioned you're seeing the issue when taking a dependency on `ILogger`, which isn't a service type that will be available (it is a binding, but not a registered service). Do you see the issue if you instead use an `ILogger<T>` or take a dependency on `ILoggerFactory`?

**Comment by andronachev** [comment]
Hi,

Sorry, I meant to say ILogger<T> , so that remark is fine.. not using ILogger, but ILogger<T>. 

I created this repository here: https://github.com/andronachev/FunctionDependencyResolution , it is based on @Dave76 answer, where he provides a link to his repository, on this separate thread (https://github.com/MicrosoftDocs/azure-docs/issues/31278) .  

What I've done is added the ILogger<T> to the constructor of LocalTimestampService , and we can see that the LocalTimestampService is successfully resolved by the runtime, when it's added to the Function cosntructor, but we get the Exception I mentioned, if we try to resolve it using the ServiceProvider. 

This is exactly what I'm trying to do.. I have my custom services (event handlers) in a separate assembly, and want to add I:Logger<T> to them, and be able to resolve them dynamically in the function.

Thanks ! 
Vlad

**Comment by espray** [comment]
My guess its related to this DI injected IServiceProvider is not the currently scoped provider - https://github.com/Azure/azure-functions-host/issues/4576

I have seen similar issues injecting the 'IServiceProvider' and trying to resolve services with it.

**Comment by fabiocav** [comment]
@espray not sure that is related to that issue here. 

@andronachev  The pattern shown in the code is a bit fragile, and holding onto a reference of a `ServiceCollection` provided during the service registration step may not be giving you a full view of the services that are ultimately built into the service provider. Using the approach you've shared will also not work correctly with scoped services.

Can you please try updating your code to the following:

``` csharp
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Extensions.DependencyInjection;
using ObjectSharp.Seminar.Serverless.Domain.Services;

namespace ObjectSharp.Seminar.Serverless
{
    public class HealthFunctions
    {
        private readonly ITimestampService _timestamps;
        private readonly IServiceProvider _serviceProvider;

        // Dependency resolution works if done in constructor
        public HealthFunctions(ITimestampService timestamps, IServiceProvider serviceProvider)
        {
            _timestamps = timestamps;
            _serviceProvider = serviceProvider;
        }

        [FunctionName(nameof(PingHttpTrigger))]
        public IActionResult PingHttpTrigger(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "ping")] HttpRequest req)
        {
            var now = _timestamps.Now();

            // This should now work, using the service provider injected into the class
            var serviceInstance = _serviceProvider.GetService<ITimestampService>() as ITimestampService;

            return new OkObjectResult(new { timestamp = now });
        }
    }
}
```

**Comment by PureKrome** [comment]
@fabiocav Why are you injecting an `IServiceProvider` into the ctor, only to then retrieve the `ITimestampService` from the service provider? Shouldn't `startup` correctly define the _scope_ of the interface?

vs

registering the `ITS` in `startup` and then injecting that directly?
```
public HealthFunctions(ITimestampService timestampservice)
{ ... }

[FunctionName(nameof(PingHttpTrigger))]
        public IActionResult PingHttpTrigger(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "ping")] HttpRequest req)
        {
           // instance provided via ctor DI 
            var now = _timestampService.Now();
         
            return new OkObjectResult(new { timestamp = now });
        }

**Comment by fabiocav** [comment]
> Why are you injecting an IServiceProvider into the ctor, only to then retrieve the ITimestampService from the service provider? Shouldn't startup correctly define the scope of the interface?

Yes. That would be the common thing to do. The code above is not mine, I just updated the repro provided by @andronachev to make it work (which I found using the link he provided above, here: https://github.com/andronachev/FunctionDependencyResolution/blob/9bc88aa272d637114f6067a853a238fb8d25ccbf/ObjectSharp.Seminar.Serverless/Functions/HealthFunctions.cs)

I didn't want to make assumptions about his requirement, as it is possible that in his case, he may be getting type information dynamically, so I didn't want to change his code beyond the fix. 

The above isn't a reference/sample, just an attempt to show the difference between his broken repro and a working one. I should have clarified that :)

**Comment by PureKrome** [comment]
Thanks for the reply @fabiocav  - really appreciate it!

**Comment by andronachev** [comment]
@fabiocav thanks a lot for the input - I haven't got to testing it yet, but it should work. And yes, I get the Type dynamically, so that's why I need the IServiceProvider. I'll update this thread once I test

**Comment by andronachev** [comment]
Sorry for the very late response... I have tested this and it works. Making the function's class non-static and injecting the IServiceProvider via the constructor is the way to go.

Thanks a lot,
Vlad
