### ISSUE TITLE
Questions about local.settings.json / configuration files with Azure Functions.

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-functions-host#4597]
#### Is your question related to a specific version? If so, please specify:
Version 2.

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question

:wave: Hi team! I have a few questions about Azure Functions and configuration file(s) with respect to .NET core (in general):

- why `local.settings.json` was named that, instead being called that instead of `appsettings.json`
- why `local.settings.json` is not being published by default
- why there's no `local.settings.development.json` / `local.settings.production.json` (assuming the Azure Functions naming standard of the file was used).

### Context

When myself and colleagues move from ASP.NET core (think, web api's .. not so much MVC websites with razor, etc) over to Azure Functions we assumed that Azure Functions under .NET Core followed the conventions of .NET core also, like DI/IOC, configuration, Host etc. Now we understand that AF are a very specialised type of Host (compared to Generic Host, etc) but we at least thought that other more generic conventions would pass across, like DI/IoC (which has recently arrived, even though it's still not the same-same) and Configuration.

Is there any reason for the difference of conventions?

Was this decision made early on because of the different language types (c# vs the rest) where the conventions are different / probably don't apply to the other langs outside of .NET Core?

**Comment by willdaviesdevelops** [comment]
[i'm just a regular dev, not affiliated with MS] 
In my opinion, the likely reason for the drift is that Azure Functions was originally not .net core.  The original run time (1.0) was .net framework only (apart from the other non-MS languages).  That .net implementation did not offer those conventions (DI, IoC) by default either.  I hope that explains the potential drift.  
Now that it _does_ support .net Core these feature are coming online slow and steady as to not break existing implementations.  I'm not sure why they named the file "local.settings.json", but I believe they don't want you to publish by default because of the local nature of the file.  For example, a connection string to your local data store is not likely the same data store you would use if deployed to Azure.  Microsoft would also (likely) recommend using Azure Key Vault for secrets.

Keep in mind that Azure Functions is closer to the WebJobs of Azure's Past than it is to an MVC app.
Think of how you might use Azure Funcitons to replace the compute portion of your apps (beyond the Web App).

**Comment by PureKrome** [comment]
> In my opinion, the likely reason for the drift is that Azure Functions was originally not .net core. The original run time (1.0) was .net framework only (apart from the other non-MS languages). That .net implementation did not offer those conventions (DI, IoC) by default either. I hope that explains the potential drift.

ah yeah - forgot that it was .net-old. fair point then.

>  I'm not sure why they named the file "local.settings.json", but I believe they don't want you to publish by default because of the local nature of the file.

And .. how is this different to:
- `appsettings.json`  <-- local
- `appsettings.developer.json`  <-- dev server
- `appsettings.production.json` <-- prod server

I guess the more I work through this issue (after opening it) I'm _hoping_ that the AzF team will migrate their configuration story, over.

**Comment by espray** [comment]
See below for history on local.settings.json
https://github.com/microsoft/vscode-azurefunctions/issues/327#
Azure/azure-functions-core-tools#122

**Comment by PureKrome** [comment]
Cheers @espray for the links. that info does help.

Summary: I'm part of the group that must be in the minority. bummer and sadness.

> We've gotten feedback from customers that the name appsettings.json is confusing. I did a poll on the Advisors group. We got 50+ responses, with most voting for the name local.settings.json.

I'm guessing these customers must have been pre .Core peeps. oh well ... more challenges :/

**Comment by jwisener** [comment]
@PureKrome I guess I am in the minority as well, as it's a pia to go thru many different sites we have and set by hand every setting we need in each environment and microservice we have.

**Comment by PureKrome** [comment]
Same. Also @jwisener -> I'm very biased with respect to working with .NET core apps 2.* and even playing with Preview 3.* stuff ... so the conventions there are very ingrained in our "web api projects. Then jumping back to functions feels like it's _trying_ to look like those conventions but it's not and is all a sorta hack.

I guess I was expecting functions to follow/re-use the exact same subsystems from writing an ASP.NET Core 2.* app (`Configure` / `ConfigureServices` / DI / Logging / Configuration / Health Metrics / etc) so it's just that the underlying _host_ is tweaked differently to handle the "Functions" hosting model.

Obviously this is not the case and they are two totally separate beasts but share _some_ similar conventions but are executed differently and most importantly (from a developers perspective) coded/consumed differently too. No tooooooo differently, but enough to notice and scratch your head at times.

That's been my experience in the last 24 months at least.

**Comment by jwisener** [comment]
@PureKrome  just opened this issue: 

https://github.com/microsoft/vscode-azurefunctions/issues/1365
