### ISSUE TITLE
Failed to deploy web package to App Service

### ISSUE THREAD

**Issue by somsekhar** [Azure/azure-functions-host#4601]
Getting error every time while deploying azure function through CI-CD pipeline and manually. 
We tried all the possible ways like setting MSDEPLOY_RENAME_LOCKED_FILES = 1, app offline service = true.
Also tried to delete the files from the folder before deployment. 
Target framework : .Net Framework 4.6.1

The following is the error. 
Failed to deploy web package to App Service.
Error Code: ERROR_FILE_IN_USE
More Information: Web Deploy cannot modify the file 'ME_D2D.dlm' on the destination because it is locked by an external process.  In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.
Error count: 1.
Error: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe failed with return code: 4294967295

Any suggestion highly appreciated.

**Comment by brettsam** [comment]
What release pipeline are you using, and how are you managing the deployment?

My first suggestion would be to move your deployment to use "Run from package": https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package -- this removes a lot of these locked-file scenarios completely.
