### ISSUE TITLE
Fix logging in ScriptStartupTypeLocator

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#4609]
We're always using a `NullLogger.Instance` in `ScriptStartupTypeLocator`, which means we're missing a bunch of good logs. We need to fix this.

https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/ScriptHostBuilderExtensions.cs#L207
https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs#L36

**Comment by fabiocav** [comment]
@brettsam do you have evidence of cases impacted by the unavailability of this data?

**Comment by brettsam** [comment]
We've got logs all over that type that aren't going anywhere today -- bundle errors, logs about loading extensions, errors loading types, etc. I came across it b/c during a race condition on startup it was a black hole -- I couldn't tell if anything had successfully executed in this code or not.

**Comment by fabiocav** [comment]
@brettsam we still have this flagged as a supportability issue, should we bring it into the next sprint?

**Comment by brettsam** [comment]
@kashimiz actually fixed this a long time ago -- https://github.com/Azure/azure-functions-host/issues/4615

**Comment by brettsam** [comment]
Whoops -- that was the issue it closed. The PR is https://github.com/Azure/azure-functions-host/pull/4756.
