### ISSUE TITLE
Investigate missing system logs

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#4611]
Logs are missing for any traces that use 

workerChannelLogger : https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/LanguageWorkerChannel.cs#L75  and 

workerProcessLogger: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/LanguageWorkerProcess.cs#L49

**Comment by pragnagopa** [comment]
cc @brettsam

**Comment by fabiocav** [comment]
Can this be closed now?

**Comment by pragnagopa** [comment]
Yes. Fix is merged to master
