### ISSUE TITLE
Host thresholds exceeded: [Threads] for azure queue storage

### ISSUE THREAD

**Issue by iamsuresha** [Azure/azure-functions-host#4619]
I am storing around 20000 messages in a queue and fetching it one by one using azure queue trigger and trying to update the message and adding the updated messages to another queue. For example, adding 20000 products in Products Queue and using azure queue trigger i am adding the categeries to the every incoming message and add it to Categories queue. after processing some 1000 records i am getting exception Host thresholds exceeded: [Threads].

**Comment by brettsam** [comment]
Are you using any libraries or running any code that could be spawning threads? The typical usage pattern shouldn't be creating any extra threads. If you have some function code to share that could help as well.
