### ISSUE TITLE
Feature request: support Functions with entry point in .cs files

### ISSUE THREAD

**Issue by mmaitre314** [Azure/azure-functions-host#462]
Using .csx to write functions is promising but support in Visual Studio is not there yet. In particular, there is no good way to get Intellisense, write unit tests, or create csx projects (unlike for Python or Powershell for instance). Development and local testing would be improved if function entry points could live in .cs files too.

The current workaround is to create a .csx that loads .cs files and forwards the entry point:
- Function.cs

```
using System;
using Microsoft.Azure.WebJobs.Host;

public static class Function
{
    public static void Run(string input, TraceWriter log)
    {
        log.Info($"Called at {DateTimeOffset.Now} with input {input}.");
    }
}
```
- Run.csx

```
#load "function.cs"

public static void Run(string input, TraceWriter log)
{
    Function.Run(input, log);
}
```

**Comment by fabiocav** [comment]
Are we simply talking about supporting the additional file extension (.cs) or adding support for regular C# syntax parsing?
It's worth pointing out that in the example above, although the file has a .cs extension, it is still parsed using the C# scripting syntax, and all of its features and limitations still apply (e.g. you'd see a compilation error if you had the code in your .cs file defined in a namespace).

If the goal is simply to support files with the .cs extension, that's a pretty trivial change, but I do have concerns about the confusion this might introduce, as customers not previously exposed to Azure Functions would, reasonably, assume they could use regular C# syntax in their functions and have a poor experience once they started running into compilation errors.

If, on the other hand, we're talking about supporting regular C# syntax in addition to C# scripting, we'd need to understand how we'd support things like the ability to have additional function files and external references. Would we need to support project files? Some file and assembly loading convention? Another mechanism (which would likely be something custom to Functions, which we should avoid)? Having two models would also be pretty confusing.

I think a better option would be to address the root problem, which is poor tooling support, by investing in that area, that way we could provide an experience where developers would be able to write unit tests and have full Intellisense support in their function (.csx) files. This is something we already plan on doing to enable a local debugging experience and there's some active work at the moment that may actually get us some of those things in VS Code pretty soon. We've also seen some improvements in regards to .csx in VS with better C# Interactive support.

I like your approach above. I think we could also, with a small amount of effort, enhance the experience in VS with a quick custom tool, templates and/or some guidance on how to do what you've done or a mix of custom build events/tasks and compiler directives.

I do want to keep the discussion going, as this is an important issue and I really appreciate you getting this started and sharing your initial ideas.

Thoughts?

**Comment by mmaitre314** [comment]
Lack of tooling support is the main issue. VS also seems to have limitation when it comes to managing Nuget packages in .csx. If support for .csx was on par with Python this would be a non-issue.

The workaround to have some .csx code bootstrap more .cs files might be good enough for now. An alternative I was thinking about was to let WebJobs run in the Dynamic Service Plans. That would avoid introducing a new programming model, but I don't know the impact on Azure Functions design.

Another path might be to have all the .cs code compiled in some assembly DLL and the .csx just reference that. The code mentioned some way to upload private assemblies. That did not seem to work great with Git push but I might be missing something or there might be a simple way to improve that process.

**Comment by fabiocav** [comment]
This has been obsoleted by the pre-compiled function support.
