### ISSUE TITLE
Domain root does not trigger HttpTrigger function

### ISSUE THREAD

**Issue by martinfletcher** [Azure/azure-functions-host#4638]
#### Investigative information

Please provide the following:

- Function App version (1.0 or 2.0): 2.0

#### Repro steps

Create a new function app project
Update host.json (extensions.http.routePrefix = "")
Update local.settings.json (Values.AzureWebJobsDisableHomepage = true)
Create a new HttpTrigger function
Set Route = ""
Run function
Send request to localhost:7071

#### Expected behavior

HttpTrigger function for the domain root (localhost:7071/) should be executed

#### Actual behavior

HttpTrigger function not executed, console log as follows:

Executing HTTP request: {
    "requestId": "45ee62be-f45a-44d4-9699-8f0f49348f65",
    "method": "GET",
    "uri": "/"
}
Executed HTTP request: {
    "requestId": "45ee62be-f45a-44d4-9699-8f0f49348f65",
    "method": "GET",
    "uri": "/",
    "identities": [],
    "status": 204,
    "duration": 334
}

#### Known workarounds

N/A

#### Related information 

* Programming language used: C#
* Bindings used: HttpTrigger

```csharp
[FunctionName("CreateWorkflowHttpFunction")]
public static async Task<IActionResult> Run([HttpTrigger("GET", Route = "")] HttpRequest request, CancellationToken cancellationToken)
        {
            string name = request.Query["name"];

            string requestBody = await new StreamReader(request.Body).ReadToEndAsync();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name = name ?? data?.name;

            return name != null
                ? (ActionResult)new OkObjectResult($"Hello, {name}")
                : new BadRequestObjectResult("Please pass a name on the query string or in the request body");
        }
```

**Comment by fabiocav** [comment]
This behavior is currently by design. In order to override the root, the recommended approach would be to use the [Functions Proxies feature](https://docs.microsoft.com/en-us/azure/azure-functions/functions-proxies)
