### ISSUE TITLE
Use LinuxFxVersion site config properties to select docker image for a function app

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#4639]
Sample site properties on Node Web APP
```
 "siteProperties": {
      "metadata": null,
      "properties": [
        {
          "name": "LinuxFxVersion",
          "value": "NODE|10.14"
        },
        {
          "name": "WindowsFxVersion",
          "value": null
        }
      ],
      "appSettings": null
    },
```

Function App should use LinuxFxVersion to pick the right runtime version. I will open follow up tooling update issues that set this property

**Comment by pragnagopa** [comment]
cc @anirudhgarg  @ahmelsayed

**Comment by pragnagopa** [comment]
CLI issues:
- https://github.com/Azure/azure-functions-core-tools/issues/1428
- https://github.com/Azure/azure-functions-core-tools/issues/1428

**Comment by pragnagopa** [comment]
cc @divyagandhii

**Comment by divyagandhii** [comment]
This is done. Assigning to Ankit to close this issue when deployment is over.

**Comment by ankitkumarr** [comment]
The deployment is complete. I am going to close this
