### ISSUE TITLE
Allow Wamup API in placeholder mode for non C# template sites

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#4642]
For placeholder pools, each runtime gets a template site with FUNCTIONS_WORKER_RUNTIME set to a runtime.

For warmup C# api to continue working, dotnet FunctionDescriptor needs to be added.

**Comment by fabiocav** [comment]
Do we want to continue executing those functions in the runtime specific placeholders? Is this so those are good candidates for .NET functions as well?

**Comment by pragnagopa** [comment]
> Do we want to continue executing those functions in the runtime specific placeholders?
Yes. This is to ensure invocation code path is warmed up.

> Is this so those are good candidates for .NET functions as well?
Yes. Any template site can be used for .Net functions. Once the placeholder pools are enabled everywhere, we should only start language worker process when the runtime is set.
