### ISSUE TITLE
Key management V2 ARM impact because of listkeys action

### ISSUE THREAD

**Issue by ronnelsantiago** [Azure/azure-functions-host#4647]
#### Is your question related to a specific version? If so, please specify:
Function Runtime Version: `2.0.12507.0`
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
All
#### Question
Got an ARM template that is calling `listkeys` action on Function App and as with this [docu](https://github.com/Azure/azure-functions-host/wiki/Changes-to-Key-Management-in-Functions-V2#arm-impact) states switching to blob will be problematic, do we have any updates on this one? It will be good to get a feel of where things are.

**Comment by mathewc** [comment]
New ARM APIs for key management are now live - see https://github.com/Azure/azure-functions-host/issues/3994. You should use these new APIs (the new "listkeys" APIs) rather than the old "listsecrets" API.
