### ISSUE TITLE
'I' character in function name gives invalid function name error

### ISSUE THREAD

**Issue by utekau** [Azure/azure-functions-host#4648]
Hi all,

We created **node js & http triggered** based several function apps in portal and then decided to continue development process through visual studio code. After downloading the content as zip file, we opened the folder in vs code and configured debug stuff that we needed to run.  By the way, we are using function app version as 2.0. 

When we push the debug button, there is no problem occurring at the beginning, the hosting starts. However, for one of the functions that we have gives the following error:

...
Host started (455ms)
Job host started
The following 1 functions are in error:
createIsolationCertificate: 'createIsolationCertificate' is not a valid function name.
...

All the other endpoints like login, createXYZ are working without any issue. Then, we made many tests and realized that the 'I', the first char of 'Isolation' keyword, caused the issue. If we remove it, everything goes fine.

I know it is a really strange and disturbing issue. There is no any additional stuff in function bindings.

Thanks.

**Comment by mhoeger** [comment]
@utekau - I'm not able to reproduce this issue in my environment
![image](https://user-images.githubusercontent.com/8888531/60840217-dce08480-a183-11e9-8350-c6f4e258c150.png)

Is there a chance that the "I" that you named is with is not an ASCII character (character values 0-127)? We have validation logic to not allow this.

**Comment by utekau** [comment]
Hi @mhoeger ,

I printed out the ascii values of the function and all of them were valid, 'I' was 73. I even altered my keyboard settings to English and wrote 'I' character in that way but still faced the same issue.

**Comment by mhoeger** [comment]
Can you share your deployed function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? 

Also - are you only having these issues when you download the content as zip file?

**Comment by utekau** [comment]
This is the subscription id: e638.....9120 and the name is sa.....oc.azurewebsites.net.
Apart from that, only I use azure portal for development but I gave the downloaded zip file to my collague and we tried same process, it failed at the same step.
Thanks.

**Comment by mhoeger** [comment]
@utekau - it looks like your function is working in Azure, and the exact same code for function name validation will be running in Azure vs. locally. This means that the filename was likely corrupted when you decompressed the downloaded content. 

Can you try renaming the file to exactly these characters: "createIsolationCertificate"? And if the character is still not ok, can you send a screenshot as well as the copy-pasted output?

Also, how exactly did you unzip the content (what OS are you running on, what's the system language, and what unzip tool)? All of these will play into how the content was unpacked.

**Comment by utekau** [comment]
Hi @mhoeger ,
I'm adding the screenshot below. I copied and pasted what you wrote but it didn't work. 

Regarding your requests, I'm using Windows 10. My Windows display language is English (United States). For the zip file, I'm not using any third part tool like 7zip or winrar. I'm using default zip opener of Windows. I just right clicked file and select "Extract All..."

![image](https://user-images.githubusercontent.com/3055148/61303989-1a32bb00-a7f1-11e9-8269-79aac25269ec.png)

**Comment by mhoeger** [comment]
@utekau - looking at our code for [function name validation](https://github.com/Azure/azure-functions-host/blob/3b1b0dd0a0f54098f72d6a284d485bf671a76280/src/WebJobs.Script/Host/FunctionMetadataManager.cs#L24), it looks like we aren't doing a invariant culture comparison. It's likely that your system culture is set to something that's not English (note: in [this documentation](https://github.com/Azure/azure-functions-host/blob/3b1b0dd0a0f54098f72d6a284d485bf671a76280/src/WebJobs.Script/Host/FunctionMetadataManager.cs#L24), different behavior with the character `I` in Turkish-Turkey is specifically called out.

This will be a quick fix, thanks for reporting!
