### ISSUE TITLE
VSTO 2019 Azure Function build/deploy errors

### ISSUE THREAD

**Issue by vijayrkn** [Azure/azure-functions-host#4649]
Creating the bug on behalf of the VS customer. Details here - 
https://developercommunity.visualstudio.com/content/problem/627078/vsto-2019-azure-function-builddeploy-errors.html

This issue may be related to - https://github.com/Azure/azure-functions-host/issues/4055

**Comment by soninaren** [comment]
@vijayrkn yes, Updating to the latest version of https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/ should resolve this issue. Have responded to the VSO issue as well. Going to close this an answered. Would urge the user to re-open / create an issue if they can still reproduce after updating the nuget pacakge.
