### ISSUE TITLE
Visual Studio debugger stepping into non user code on azure functions projects

### ISSUE THREAD

**Issue by HalidCisse** [Azure/azure-functions-host#4654]
Visual Studio debugger stepping into non-user code on Azure functions projects.

- Just my code is checked.
- Reinstalled visual studio.
- Resetted my whole windows machine.
- My azure functions projects are currently not debuggable due to this annoying dialog in stepping - into azure function assembly code.
- StackOverflow link [stackoverflow](https://stackoverflow.com/questions/56856353/visual-studio-debugger-stepping-into-non-user-code-on-azure-functions-projects)
- Developer community link [Developer community ](https://developercommunity.visualstudio.com/content/problem/632127/visual-studio-debugger-stepping-into-non-user-code.html)

![usercode 1](https://user-images.githubusercontent.com/6313791/60674226-946a5380-9e71-11e9-95e6-a773764577ba.PNG)
![usercode 2](https://user-images.githubusercontent.com/6313791/60674228-946a5380-9e71-11e9-8595-f0898e83bf3f.PNG)
![usercode 3](https://user-images.githubusercontent.com/6313791/60674230-9502ea00-9e71-11e9-9f72-76a6961fa32b.PNG)
![usercode 4](https://user-images.githubusercontent.com/6313791/60674231-9502ea00-9e71-11e9-9cfc-abfa0137f008.PNG)

Please advise.

**Comment by fabiocav** [comment]
Tracking the change to address the root cause here: https://github.com/Azure/azure-functions-host/issues/4572

Please follow that issue for updates.

**Comment by HalidCisse** [comment]
Hi @fabiocav I'm targetting .NET core only, i dont see how this is related.
`    <TargetFramework>netcoreapp2.2</TargetFramework>
`
