### ISSUE TITLE
Logs correlation for queue triggered functions

### ISSUE THREAD

**Issue by Badabum** [Azure/azure-functions-host#4655]
#### Is your question related to a specific version? If so, please specify:
Azure Function V2
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question
Consider the following setup: `TimeTriggeredFunction -> HttpTriggeredFunction -> Storage Queue -> QueueTriggeredFunction`. In this environment correlation for part `TimeTriggeredFunction -> HttpTriggeredFunction -> Storage Queue` is done automatically. But to correlate logs form `QueueTriggeredFunction` with others we need to know the request identifier. One way of achieving this is to pass `requestId` in the queue message and do smth like this at the beginning of the `QueueFunction` :
```
Activity activity = new Activity(context.FunctionName);
activity.SetParentId(requestId);
activity.Start();
```
Is there any natural way to do this kind of correlation without loosing telemetry collected by the host?

**Comment by brettsam** [comment]
@lmolkova is the expert on this -- can you do `Activity.Current.SetParentId(requestId)`?

**Comment by lmolkova** [comment]
@brettsam 
unfortunately no.

`Activity.Current.SetParentId(requestId)` is not possible: SetParentId works only before activity is started. And activity has to be started to become Current.

@Badabum 
If you do this (below), the function execution (request telemtery) will not be correlated to anything else that you report under the scope of new activity.

```
Activity activity = new Activity(context.FunctionName);
activity.SetParentId(requestId);
activity.Start();
```

As a workaround:
1. on the producer side, put two identifiers into the queue message: the operationId and parentId
2. on the consumer side do `telemteryClient.StartOperation<RequestTelemetry>(name, operationId, parentId)`
3. when function execution ends, stop/dispose AI operation 

It will track another requesttelemtery that will be correlated to queue message and everything that happens in the scope of this operation will be correlated to the context in the message.

There is an article about it: https://docs.microsoft.com/en-us/azure/azure-monitor/app/custom-operations-tracking#queue-instrumentation.

Also, to create telemtery client, use this approach: https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#version-2x-3

The downside of this approach that you are effectively duplicating 2 telemetry items (sending to queue and function execution).
We don't have good out-of-the box solution for storage queues (as they don't have message metadata) but we may have at least some solution if we establish a contract on how context is passed through the message. 

BTW, how you send messages to the queue with another Function i.e. how did you configure queue output bindings? what is the data format of the message payload? Is it json?
If I recall correctly, functions can only update the message and add tracing context if it's a json or dynamic type and never touches byte[] or string messages.

**Comment by fabiocav** [comment]
Thank you @lmolkova ! Closing this as answered.

**Comment by Badabum** [comment]
Thanks a lot @lmolkova! The really informative answer. To answer your question, I just defined a common event object structure in a form like this:
```

class SystemEvent<T>
{
    T Data {get;set;}
    CorrelationMetadata CorrelationMedatata {get;set;}
}

class CorrelationMetadata
{
     string OperationId {get; set;}
}

```
Then it is converted to json string. So the payload of queue message contains correlation information in my case. Based on your answer it should be relatively easy to add `ParentId` property to `CorrelationMetadata` object.

**Comment by richardszalay** [comment]
@lmolkova Forgive my ignorance, but why would you pass the OperationId and the ParentId? My (limited) understanding was that each piece (http, queue processing) was its own request operation and correlated via their parent.
