### ISSUE TITLE
Deployment of 12562 BREAKS functions that are running (JAVA)

### ISSUE THREAD

**Issue by TurtleBeach** [Azure/azure-functions-host#4656]
#### Investigative information

Please provide the following:

- Timestamp:  2019-07-10T15:50:53.5674569Z
- Function App version (1.0 or 2.0):   2
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:  71db38b5-329e-4246-a404-23b7c6fb85b2
- Region: eastus

#### Repro steps

Function has been running for months - and was running 10 minutes prior to when error occurred. It appears runtime 12562 was rolled out and killed the function.

#### Expected behavior

Function should continue to run. Java functions are now GA

#### Actual behavior

Function crashed; AppInsights error was "Did not find any initialized language workers"

#### Known workarounds

Manual restart and function is running again.

#### Related information 

This is, to say the least, extremely aggravating.

**Comment by fabiocav** [comment]
@TurtleBeach we'll investigate the issue on our side with the information you've provided.

Have you been able to confirm this continues to impact your app after a restart? We don't expect this issue to be something related to the new version of the runtime, but will look at your app to confirm.

**Comment by TurtleBeach** [comment]
@fabiocav I have not seen this happen again, and other Java functions transitioned to the new runtime without interruption. I would be curious to know what you find in the MS logs.

**Comment by fabiocav** [comment]
That's good to hear. Based on what we're seeing, this is due to a race condition that had been in the runtime for a while. That has been recently identified and the fix is being rolled out in the next release.

Apologies for the inconvenience!
