### ISSUE TITLE
Explanation about what exactly happens during swap of deployment slots

### ISSUE THREAD

**Issue by sandeepiiit** [Azure/azure-functions-host#4662]
The documentation of [deployment slots in azure functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies#deployment-slots) consists of a brief explanation and then points to the [Azure App Service Slots](https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots) for details. I love the details there.

My question is: Do the details mentioned about [What happens in during a swap](https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots#what-happens-during-a-swap) accurate for functions as well?

I am asking this because I have noticed some differences between the app service slots and what I see in azure portal for the slots for my function under app service plan.

For example, app service slots are able to route some portion of production traffic to staging slot as described [here](https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots#add-a-slot).
![image](https://user-images.githubusercontent.com/13448362/61019175-1369fb00-a34e-11e9-8e56-28071f8597c5.png)

However, I don't see such capabilities in azure function app in the portal.
![image](https://user-images.githubusercontent.com/13448362/61019271-6a6fd000-a34e-11e9-99a6-76211201c504.png)

I understand this is in preview for now, and differences are probably expected :) What I am trying to gather is if the underlying slots tech is same, and can I assume the details about one to apply to another, especially the steps related to swapping. Sorry if it sounds too generic. I can provide more specific questions if needed.

**Comment by fabiocav** [comment]
@ahmedelnably do you have any additional information/documentation you can share (if required)

**Comment by ahmedelnably** [comment]
Yes, the underlying tech for Dedicated hosting option is the same.
Currently the http traffic routing is not available through the portal for function apps.

That's said, you can still configure traffic routing through the webapp cli command
https://docs.microsoft.com/en-us/cli/azure/webapp/traffic-routing?view=azure-cli-latest#az-webapp-traffic-routing-set

Note:
- This is scenario is not a supported scenario, we can not verify it's working exactly as webapps
- If it worked as expected, it will only route HTTP traffic, not other types of triggers

**Comment by kashimiz** [comment]
Closing this as answered. @sandeepiiit, please open a new issue if have further questions.

**Comment by sandeepiiit** [comment]
@ahmedelnably @kashimiz  Thanks for the response. I have some more specific questions, which would be nice to get answered in the same thread (if possible).

* Does the swap slot operation make sure that requests are not dropped?
* Does the warmup during swap support [WEBSITE_SWAP_WARMUP_PING_PATH](https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots#Warm-up)?
* If the swap operation fails in one of the steps, does it revert the changes? For example, appsettings & connection strings gets updated as part of swap operation. Do those get rolled back to the initial state?

**Comment by ahmedelnably** [comment]
* Yes, the swap mechanism make sure that request will get processed by one of the two slots, and none get dropped
* @shubDhond should be able to confirm
* Yes, everything get rolled back to initial state

**Comment by fabiocav** [comment]
Closing this as answered.

@shubDhond please add to this, if needed.

**Comment by sandeepiiit** [comment]
@ahmedelnably What is the behavior around functions with triggers _other than_ `HTTPTrigger`. Specifically, Queue, EventGrid & Timer triggered functions. If such a function happens to be processing an input, does it get aborted during a swap?

**Comment by ahmedelnably** [comment]
@sandeepiiit the request will finish, note that it is your responsibility to manage the settings for your app. and the connection strings through slot settings
