### ISSUE TITLE
Unable to resolve service for type 'Microsoft.AspNetCore.Hosting.IHostingEnvironment' while attempting to activate 'Microsoft.AspNetCore.Hosting.DefaultApplicationInsightsServiceConfigureOptions'.

### ISSUE THREAD

**Issue by alin-devnet** [Azure/azure-functions-host#4663]
I'm getting the following exception with the latest version (2.0.12562.0)

> Unable to resolve service for type 'Microsoft.AspNetCore.Hosting.IHostingEnvironment' while attempting to activate 'Microsoft.AspNetCore.Hosting.DefaultApplicationInsightsServiceConfigureOptions'.

This happens when trying to resolve an EntityFramework Core DbContext instance:

`services.AddDbContextPool<SomeDbContext>()`

Forcing it to version 2.0.12507.0 seems to work for now.

I can see there were some DI changes in the latest release so I'm guessing it must be related to that(?)

**Comment by fabiocav** [comment]
Thanks for reporting this! Can you please share a small repro on this? Just want to make sure we have the right scenario to test, is adding a DB context with the call above sufficient to repro the issue?

@brettsam FYI, as the AI bits moved forward with the last release.

**Comment by fabiocav** [comment]
Also @pragnagopa - FYI as you're driving the next release.

**Comment by brettsam** [comment]
@alin-devnet -- are you calling `AddApplicationInsightsTelemetry()` (or anything App Insights related), by chance? I don't see any reference to ApplicationInsights in the EF Core github repo, so I don't think they're registering this service. 

When I look for this type in App Insights, the only place I see it registered is in a call to `AddApplicationInsightTelemetry()`: https://github.com/microsoft/ApplicationInsights-aspnetcore/blob/4c037ea3b0ec96a3f177b983101336c441a207b1/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L237-L239

**Comment by alin-devnet** [comment]
@brettsam 

I do call that indeed and that seems to be the cause.

I created a new function to reproduce this and have only this in my startup:

```
services.AddDbContextPool<SomeDbContext>(options => options.UseSqlServer(connectionString));
services.AddApplicationInsightsTelemetry(instrumentationKey));
```

With that in place it works on version 2.0.12507.0, but not on latest. 

I'm using the following library for DI: 
https://github.com/BorisWilhelms/azure-function-dependency-injection
Willezone.Azure.WebJobs.Extensions.DependencyInjection 1.0.1

I'm also using the following if it helps: 

Microsoft.AspNetCore.All 2.2.1
Microsoft.NET.Sdk.Functions 1.0.23

**Comment by brettsam** [comment]
And what version of App Insights are you referencing?

`AddApplicationInsightsTelemetry()` doesn't work when mixed with our built-in ApplicationInsights functionality. They have services they register that overwrite (and sometimes break) the ones that we use internally. We note in our documentation for the built-in DI that you should not call this: https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#logging-services.

It likely worked (or at least, didn't throw) before b/c you were using version 10 of their package before we had moved forward -- now that we have, you're getting conflicts and things are breaking.

Is there some functionality that you need from this call that you weren't getting from the built-in telemetry? If so, there may be a more targeted way we can make that work for you.

**Comment by brettsam** [comment]
Going to close this as I believe it's due to an unsupported scenario of calling `AddApplicationInsights()` during startup. Feel free to reopen (or even ask more questions).
