### ISSUE TITLE
What happens if multiple function apps bind to the same storage queue for input?

### ISSUE THREAD

**Issue by sandeepiiit** [Azure/azure-functions-host#4666]
#### Is your question related to a specific version? If so, please specify:
Function 2.0

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
I have function apps running in two different regions for redundancy i.e. there are two separate apps in azure portal (deployed from the same code). So both apps have the function that input binds to the same storage queue. Would all messages be delivered to both or would the messages get split between the two?

**Comment by mathewc** [comment]
These are competing consumers - each message would only be delivered once to one of the Function apps. The app that dequeues the message will process it then delete it.
