### ISSUE TITLE
Function host is not running

### ISSUE THREAD

**Issue by adrianknight89** [Azure/azure-functions-host#4670]
Over the course of a year, I've had all kinds of issues running my app in production. This morning, I'm getting "503 Service Unavailable" response from my API endpoints running in consumption plan. I'm also getting "Function host is not running" message when I hit the azurewebsites.net URL.

My `host.json` file looks like this:

```
{
    "version": "2.0"
}
```

and I'm using SDK 1.0.29. Seems like some kind of configuration is wrong even though I haven't made any changes recently.

**Comment by adrianknight89** [comment]
I was able to fix this issue by resetting my publish profile on the Azure portal. Seems like there was an issue with the old profile that I've kept using. There were no changes to the old profile, so I don't know what went wrong. Do you have an explanation for this?

**Comment by paulbatum** [comment]
@adrianknight89 Can you fill out the issue template? We need the details listed there to investigate.

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0):
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

If you don't want to share your Function App name or Functions names on GitHub, please be sure to provide your Invocation ID, Timestamp, and Region - we can use this to look up your Function App/Function. Provide an invocation id per Function. See the [wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) for more details.

**Comment by adrianknight89** [comment]
Unfortunately, I had to delete all Azure resources and create them again as I need to meet my development milestones. This issue does not exist for me as of now, but if it happens again, I'll be sure to provide the information you need.

**Comment by willdewhust** [comment]
Hello I am experiencing the same issue.
Was working perfectly then over the weekend it decided to just fall over.

Function App version (1.0 or 2.0): 2.0
Function App name: backupAutomationDev-func
Function name(s) (as appropriate): backend-get-customerList, backend-update-protectedDB, backend-update-vaultDB to name a few
Region: UK South
