### ISSUE TITLE
remove easy auth for non http triggers

### ISSUE THREAD

**Issue by CastleArg** [Azure/azure-functions-host#4674]
#### Is your question related to a specific version? If so, please specify:
2.0
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
All
#### Question
I feel non http tiggers should be exempt from 'easy auth' turned on via portal.
This is great for http, but I'm using an app which goes on to use durable functions and blob triggers, and these fail on lack of auth.  The app is essentially forbidding itself.  Am I missing something here or should this be applied to http functions only?

**Comment by fabiocav** [comment]
When you enable Easy Auth, you're protecting the entire App, not just the host. The infrastructure components that need to communicate with the host over HTTP should be able to deal with Easy Auth being enabled and properly authenticate.

What exact scenarios are you running into problems with? Can you describe where you're seeing the calls being blocked?

**Comment by CastleArg** [comment]
I have an http trigger that returns a sas url to post a file to blob storage.
I then have a blob storage trigger that starts an orchestrator function.
This fails with "you cannot view this page.", I think when durable-orchestrator.js is trying to post metadata via axios.

**Comment by CastleArg** [comment]
stack trace here:
Exception: Error: You do not have permission to view this directory or page.
Stack: Error: You do not have permission to view this directory or page.
    at DurableOrchestrationClient.<anonymous> (D:\home\site\wwwroot\node_modules\durable-functions\lib\src\durableorchestrationclient.js:284:43)
    at Generator.next (<anonymous>)
    at fulfilled (D:\home\site\wwwroot\node_modules\durable-functions\lib\src\durableorchestrationclient.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by fabiocav** [comment]
/cc @kashimiz 

Interesting. Could you please follow the steps outlined here so we can get some information about your app and take a look at the logs? https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately

**Comment by CastleArg** [comment]
Excuse the soliloquy but I managed to workaround using authorization.json, something I had not come across before.  I ended up with this, based on page here: https://social.msdn.microsoft.com/Forums/en-US/80bad646-a8ec-411b-8549-7446e419f167/azure-ad-authentication?forum=AzureFunctions


{
    "routes": [
        {
            "path_prefix": "/api", //Need to protect backend api
            "policies": {
                "unauthenticated_action": "RejectWith401"
            }
        },
        {
            "path_prefix": "/", // thisis proxy to my SPA UI
            "policies": {
                "unauthenticated_action": "RejectWith401"
            }
        },
        {
            "path_prefix": "/runtime/webhooks/",   //this is endpoint for blob, event grid triggers etc. 
            "policies": {
                "unauthenticated_action": "AllowAnonymous"
            }
        }
    ]
}


I feel this is still a bit of a kludge and function app should always be allowed to talk to different parts of itself and set up orchestrator func.

**Comment by fabiocav** [comment]
I'm glad this you found a workaround, but this is something that shouldn't be required. We'll keep this open to investigate. The app information I've requested above would be helpful, if you can provide that. Thanks!

**Comment by kashimiz** [comment]
@fabiocav, I believe this is an instance of a known limitation of the Durable Functions JavaScript, as described in Azure/azure-functions-durable-js#62. See also the current workaround detailed in that issue, which is to use an orchestrationClient output binding to start orchestrations.

**Comment by CastleArg** [comment]
hmm that does look like the same problem.  Would that workaround be any better than the one above?  So the .NET host does not use http to orchestrate?  It looks like the best solution would be to port js host to whatever .NET uses.  I've had other problems with maxing out body size of the http request.
Cheers for the help.

**Comment by fabiocav** [comment]
Will chat with @kashimiz . But for now, closing this issue in favor of the one in the Durable JS repo.
