### ISSUE TITLE
default configuration provider appsettings.json

### ISSUE THREAD

**Issue by johnayoub** [Azure/azure-functions-host#4680]
#### Check for a solution in the Azure portal
The default JsonFile configuration provider seems to be configured to load appsettings.json however the directory path is incorrect. Locally this is not working haven't check if it does in Azure

#### Investigative information

![image](https://user-images.githubusercontent.com/9760128/61342922-f041be80-a819-11e9-9ffe-f5390593877b.png)

Please provide the following:

- Timestamp: N/A
- Function App version (1.0 or 2.0): 2.0
- Function App name: N/A
- Function name(s) (as appropriate): N/A
- Invocation ID: N/A
- Region: N/A

#### Repro steps

Provide the steps required to reproduce the problem:

1. Add appsettings.json to project
2. Get value via IConfiguration (DI)
3. Value is always null

#### Expected behavior

Value should be returned 

#### Actual behavior

Value is always null

#### Known workarounds

N/A

#### Related information 

Provide any related information 

dotnet 2.2
C#
macOS 10.14.5

**Comment by fabiocav** [comment]
`appsettings.json` is not a supported source for function configuration. The path you see there is for the actual CLI/Host. The supported configuration options are host.json, App Settings and environment variables at the moment. This is something we intend to support in the future.
