### ISSUE TITLE
Cold start times excessively long for v2 Function running on a slot

### ISSUE THREAD

**Issue by jameshowe** [Azure/azure-functions-host#4683]
#### Investigative information

- Timestamp: 2019-07-17 10:06:49 to 2019-07-17 13:07:26 (UTC)
- Function App version (1.0 or 2.0): 2.0
- Invocation IDs: 
  - 50aca2c7-cf90-4a3a-b4ff-24d38af75b17 <sup>2019-07-17T12:55:39.794</sup>
  - 2189024a-ea85-4180-90b2-47600e763d85 <sup>2019-07-17T10:15:45.395</sup>
  - f9720f10-5a5d-4c87-be42-27aae54a7b12 <sup>2019-07-17T10:15:45.350</sup>
  - fa1efa17-cb6c-421b-8bae-cb2bf0f5bb35 <sup>2019-07-17T10:15:45.009</sup>
  - 2189024a-ea85-4180-90b2-47600e763d85 <sup>2019-07-17T10:15:45.395</sup>
- Region: UK South

#### Repro steps

1. Create a 2/3 JS Http Trigger functions sharing a `node_modules` folder of approx. ~37mb
2. ~Deploy to a different slot (not the primary)~
3. ~Stop the primary instance (keeping the slot instance enabled)~
4. Trigger functions on the slot after 20 mins to initiate a cold start
5. Trigger functions on the slot within 20 mins to initiate a warm start

*Note - doesn't appear as though steps 2/3 matter, I've tried various combinations and it doesn't seem to matter if it's on a slot / primary or whether one or both are running.*

#### Expected behavior

I would expect each function to execute within ~5s from a cold start, and ~200-300ms from a warm start

#### Actual behavior

Cold starts take approx. ~3m! Warm starts are as expected.

By analyzing the log output from the functions, I can see that all this time is consumed before the function itself is actually run. Take `50aca2c7-cf90-4a3a-b4ff-24d38af75b17` for example:

Here is the record in the monitor log:

<img width="721" alt="Screenshot 2019-07-17 at 15 07 25" src="https://user-images.githubusercontent.com/1737713/61382874-78b97100-a8a5-11e9-8242-67b47c48fb6d.png">

And here's the invocation details:

<img width="541" alt="Screenshot 2019-07-17 at 15 08 43" src="https://user-images.githubusercontent.com/1737713/61382915-8c64d780-a8a5-11e9-8f71-d7c0fdbc7f3e.png">

So if I understand those logs correctly, we lose ~5s from the function being triggered to it actually being executed. If we then look at invocation details, we can see that it's taking just shy of 3 minutes to hit the first log in the Function - here's a snippet of the important parts of that Function

```js
const Knex = require('knex');
const db = Knex({ ... }); // this will initiate a DB connection pool
...

module.exports = async function(context, req) {
  const { x, y } = req.query;
  const z = req.params.z;
  if (!x || !y || !z) {
    return context.res = _jsonResponse(400, {
      message: 'xxxxxx'
    });
  }

  try {
    context.log(`Fetching ${x}...`); // First non-system message we see in the log
    const result = await getX(x);
    ...
``` 

In terms of the DB setup, there isn't really any heavy lifting going on at that point, certainly nothing that would take ~3m, and in terms of the actual code itself, as you can see there's nothing in there either that would explain a 3m delay from the start of the function to that log call.

Furthermore, if I compare the same time differences to a _warm_ start, we are talking milliseconds (<100ms).

#### Known workarounds

N/A

#### Related information 

Provide any related information 

* Language: JavaScript 
* Bindings: HTTP trigger
* Plan: Windows Consumption

**Comment by brettsam** [comment]
I suspect this is due to the npm install taking a long time on the worker. 

@jameshowe, how are you doing your deployment?

@mhoeger can correct me if I'm wrong, but I believe the recommendation is to use [Run from Package](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package), which can help with cold start. Combined with [deploying with dependencies](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#deploying-with-dependencies), the packages should all be there at that point.

**Comment by jameshowe** [comment]
@brettsam so that would make sense, I didn't consider the idea that on every cold start `npm i` runs.

This is currently setup to run as part of an Azure Pipelines integration, is there a means of deploying as a package through Azure Pipelines?

**Comment by mhoeger** [comment]
@jameshowe - yep! Check out our docs here on [deploying with Azure pipelines](https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-azure-devops). Closing this issue as resolved, but feel free to ping me in an issue if the docs are unclear or you run into an issue!

**Comment by jameshowe** [comment]
@mhoeger so firstly, it's _a lot_ better now with deploying as a package 😃. However, still cold start times of around ~10-12s on occasion, would you say that's expected? I was hoping for less than 10s.

**Comment by mhoeger** [comment]
@jameshowe - Really glad to hear! 10-12 seconds is very high in values we see, but isn't completely out of the norm. I'm working on a change to bring this down a lot for javascript (if you see things about "placeholders", that's what it is). There are underlying platform changes that are making this change slower to make. But just so you know it's a change that's coming soon!

**Comment by ChristianWeyer** [comment]
Are those changes only for node.js or also for other platforms @mhoeger ?
