### ISSUE TITLE
Precise timestamps in Kusto logs on Linux

### ISSUE THREAD

**Issue by jcookems** [Azure/azure-functions-host#4686]
While working with Rodrigo, he noticed that in Linux, the PreciseTimestamp is not a precise time stamp, getting emitted only every 30 seconds. It looks like in that case, it is correct to use EventTimestamp, which is a string and must be converted to a datetime. This has its own set of problems:
•	Kusto is more efficient to filter than transform, so this costs more
           As far as I know, PreciseTimestamp on windows is set by ETW. Since we don’t have ETW on Linux, we always use datetime (EventTimestamp). 

I’d imagine Linux should behave exactly the same as Windows from analytics POV. I’m adding Ani and Daria here so they can comment further. 

Thanks for sharing these details Jason. I know that there are still some changes for linux logs that are rolling out as part of ANT83, Divya and Bala know the details.

It would be good to determine whether some of these problems are occurring on stamps that already have ANT83. If so, we might still have some more issues to investigate.

I'll let the folks with context comment.

@Divya, I’m not sure what the “we” means here
	Since we don’t have ETW on Linux, we always use datetime (EventTimestamp). 
I assume the “we” is whoever is reading the logs. 

The issue here is that all contributors to a Kusto table should adhere to the contact of the logs. In this case, PreciseTimestamp should reflect when the data was emitted (with Windows’ precedent), so Linux should do the same. The burden should not be on reader of the logs to know which column to use determining the OS.

Similarly, the Windows logs to EventTimestamp don’t adhere to the contract of using a format parsable by Kusto. That is what I am showing in the Kusto queries below. If they did, we could fallback to using that column to work around the first issue.

I’ve gone into more details about the Windows EventTimestamp issue here https://github.com/Azure/azure-functions-host/issues/3619. It looks to be a problem with some sites in v1.

Any progress on the Linux PreciseTimestamp part?

Jason can you please file an issue on Github for the Linux timestamp as well?  We can triage it there.

**Comment by brettsam** [comment]
Do we know what the solution is for this? I assume that the logs we emit for Linux should be in a different format? 
@balag0, is the Linux kusto logging something that you added in the past? 
Adding @divyagandhii also.

**Comment by fabiocav** [comment]
I think the solution would be to standardize on EventTimestamp, as that column was added exactly to deal with issues with PreciseTimestamp. If the format is an issue (how impactful is the conversion?) we can look at changing that, but do we know if simply changing the format is sufficient to have Kusto interpret that as a datetime column?

**Comment by jcookems** [comment]
All other Antares log tables in Kusto use PreciseTimeStamp to indicate when the event was emitted. The Linux mechanism that exports the logs should conform to that design. That would be the least disruptive change.

There is at least on issue with EventTimestamp: https://github.com/Azure/azure-functions-host/issues/3619

Kusto, and I assume Geneva's MDS pipeline, already understand this column to be a string. Changing the type of the column is a breaking change and should not be done. You could add a *new* column with the correct type, but that would be wasteful and cause confusion.

**Comment by fabiocav** [comment]
We'll follow up on the problem with `EventTimstamp` using the other issue, but there are problems with `PreciseTimestamp` today (and that is the reason why `EventTimestamp` was introduced). `PreciseTimestamp` shows the time the ETW event was emitted, but in some event batching scenarios, that isn't accurate, so the event itself carries its timestamp.

I understand `PreciseTimestamp` is used today for Andares, but how impactful would it be to use `EventTimestamp` for Functions logs?

**Comment by jcookems** [comment]
We can use EventTimestamp, the issue with that design is that the obvious way to do things is inconsistently wrong. 

Consider a person on servicing that turns to Functions logs to get data. They are familiar with PreciseTimeStamp from looking at the front-end logs. They might have even used PreciseTimeStamp for Functions logs, and it *is* correct there for Windows machines. 

Now it is 2AM, and they are investigating a Sev 2 incident. They see that the functions are only execute ever 30 seconds, and that leads them down the wrong path. Time is wasted before they realize it was the wrong column. They remove the PreciseTimeStamp from their where clause and use EventTimestamp. But that doesn't work, because it is a string value. They use todatetime on the column, and now Kusto has to process rows for all time, which thrashes the cluster and makes the query take a lot longer. Then they remember, to keep almost original where clause on PreciseTimeStamp (but add buffer in either direction), and have to add another where clause on the datetime parsed value of EventTimestamp

```
| where PreciseTimeStamp > datetime(2019-07-19 23:00) and PreciseTimeStamp < datetime(2019-07-20 02:00)
| where totimestamp(EventTimestamp) > datetime(2019-07-20 00:00) and totimestamp(EventTimestamp) < datetime(2019-07-20 01;00)
```

Sure, it is doable, but it is leading users to the pit of failure that they have to claw their way out of. 

It would be much better to fix the batch processing of logs to get the time correct. Or do some processing in the Geneva ingestion layer to fix up the time (perhaps using their stream processing tech), by promoting the EventTimestamp to the PreciseTimeStamp for these tables.

**Comment by divyagandhii** [comment]
We need a fix from a Geneva partner team before we can start overriding PreciseTimeStamp with EventTimeStamp for Linux dedicated.  Currently there is no ETA from Geneva team on their fix. Please continue using EventTimeStamp till then.
