### ISSUE TITLE
What is a Function Execution Lifetime?

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-functions-host#4694]
Another question folks on the topic of scoped services in Azure Functions.

Related to #3399 and #4576 .

[Re: Service Lifetimes, the docs state](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#service-lifetimes) that a scoped service:

> In a functions app, a scoped service lifetime matches a function execution lifetime. Scoped services are created once per execution. Later requests for that service during the execution reuse the existing service instance.

Ok - so this sounds great .. but what defines `a function execution lifetime` ?

Does this mean each time a 'trigger' fires off, a new instance of the function is created and the method is then called? 

What happens if we have the trigger fire off multiple times in _very quick_ succession (e.g. we get 100 requests in a second for an HTTP Trigger, or we have 100 messages on a queue suddenly). Do we create 100 instances of the HTTPTrigger function? [For queues](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue#trigger), there's a batch concept ([default: 16 messages per batch](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue#hostjson-settings)) so when one batch is pulled down, does it use the same scope for each message processed in parallel?

So yeah ... I'm struggling to understand the lifetime of an azure function.

I feel like, once I understand the lifetime of a function I can then understand the lifetime of a _scoped_ service.

cc @fabiocav because you're awesome and can answer this pretty quickly :)

**Comment by fabiocav** [comment]
> Does this mean each time a 'trigger' fires off, a new instance of the function is created and the method is then called?

This full lifetime is from the moment the trigger fires (the invocation is dispatched through WebJobs) to the point the output bindings (if any) execute The following happens within a scope: [`trigger --> input bindings --> function code --> output bindings`]. 

> Does this mean each time a 'trigger' fires off, a new instance of the function is created and the method is then called?

Yes. If using instance methods, each invocation will create a new instance of the function class. All parameters passed into the constructor of that class (if any) are scoped to that invocation.

> What happens if we have the trigger fire off multiple times in very quick succession (e.g. we get 100 requests in a second for an HTTP Trigger, or we have 100 messages on a queue suddenly). Do we create 100 instances of the HTTPTrigger function?

Yes. Unless you're using static methods, each request will have its own instance.

> For queues, there's a batch concept (default: 16 messages per batch) so when one batch is pulled down, does it use the same scope for each message processed in parallel?

The scope is tied to the invocation, not the listener behavior. If you're using a binding that supports passing a batch to an invocation (e.g. Event Hubs, where you can take an array of messages), than you'll have a single invocation for that batch, with a single instance created and a single scope. If you write your function to take a single message instead, even if the listener batches its requests from the underlying service, you'll have multiple invocations (one for each message in the batch), therefore, multiple instances, each with their own scope.

Responding to this while away, but I hope this helps! As always, if anything is still unclear, don't hesitate to ask for clarification.

**Comment by PureKrome** [comment]
Thanks heaps @fabiocav for the answer - really appreciate it! Helps answer my questions and I also feel a bit more relief because I was _hoping_ that's what you were going answer. phew!
