### ISSUE TITLE
Feature Planning: first class R support

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-host#470]
This is a tracking item for first class R support. We'll be tracking the requirements and issues for first class R support via this item. Feel free to leave comments about features/design patterns. 
## Function format

**TBD**
## Data Type formats

**TBD**
## Version & Package management

**TBD**
## Testing/CI

**In progress**
### Remote debugging

 **TBD**
### Local debugging

**TBD**
## Hot runtime

**TBD**
## Compilation

**TBD**

**Comment by pedronahum** [comment]
Is there a plan to support Rcpp?

**Comment by nsulikowski** [comment]
R support. Yes pls. ASAP.

**Comment by stephlocke** [comment]
This would be incredibly handy for me too! Happy to guinea pig, contribute as much as I can, write docs etc! (MVP, R bod)

**Comment by fabiocav** [comment]
Closing this issue as we're not currently tracking this work
