### ISSUE TITLE
Add more explicit documentation around logging

### ISSUE THREAD

**Issue by IanKemp** [Azure/azure-functions-host#4701]
There are a large number of issues filed against this project regarding how to correctly perform logging in Azure function - in particular, the fact that your function's method is provided an already-instantiated `ILogger` object, whereas any DI-injected loggers have to be of type `ILogger<T>`, which is somewhat confusing.

Furthermore, there is the additional issue whereby logs are filtered by default: https://github.com/Azure/azure-functions-host/issues/4345

It also appears that there is no need to call `IFunctionsHostBuilder.Service.AddLogging()` if using `Startup.cs`, but again this doesn't seem to be called out anywhere in particular.

These caveats should be documented [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#logging-services), preferably with a link to the [.NET Core fundamentals of logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/) for reference.

**Comment by fabiocav** [comment]
@brettsam can you comment? Should this be moved to docs?

As a side note, I'm really considering just supporting `ILogger` as an injected service with a pre-defined category as it seems to be a common source of confusion.

**Comment by brettsam** [comment]
For discoverability, I've been linking all of these to this comment: https://github.com/Azure/azure-functions-host/issues/2720#issuecomment-503627355

We definitely need a deeper logging sample, for example you can call `AddLogging()` and wire up new providers. A good example using some external provider would go a long way.

If we can decide on a category for the `ILogger`, I now think we should just make it work. People may get confused why this doesn't work in other .NET Core apps, but at least it'd work for Functions.

**Comment by jeffhollan** [comment]
Just opened a docs PR that includes showing how to use `ILogger<T>` or `ILoggerFactory` and modifying the `host.json` to opt-into those new filters.
