### ISSUE TITLE
Function App 2.0 suddenly stopped working tonight

### ISSUE THREAD

**Issue by simonlegeek** [Azure/azure-functions-host#4708]
We have a FunctionApp v2 running since a while. Everything was working fine until tonight. Between 6:02PM (UTC-4) and 9:18PM (UTC-4), the function recorded absolutely no hit at all. Azure App insight was completely empty for that time period, no exceptions, no requests. It started working again after restarting the FunctionApp using the portal. I am clueless about how to start troubleshooting this issue so far. Can you help us?

This function is mostly triggered by HTTP request, but I don't have on hand the exact response we received when we poked the function.

I saw that a new version of the runtime started rolling out today, but it does not seem to match the runtime of our FunctionApp

Reference [https://github.com/Azure/azure-functions-host/releases/tag/v2.0.12590](url)

Actual runtime: 
```
{
    "id": "<hidden>",
    "state": "Running",
    "version": "2.0.12562.0",
    "versionDetails": "2.0.12562.0 Commit hash: 557678059e699fc61f298d226ccd91c1302d1388"
}
```

**Comment by yojagad** [comment]
@simonlegeek Can you please share the application information as specified in the issue template? This could help us take a closer look.
