### ISSUE TITLE
Whitelist Node.js for placeholders

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#4713]
1. Whitelist node (Windows and Linux) https://github.com/Azure/azure-functions-host/blob/f1d0536afa45855a5150abebbf26b9b1b4210f41/src/WebJobs.Script/Rpc/RpcInitializationService.cs#L30 https://github.com/Azure/azure-functions-host/blob/f1d0536afa45855a5150abebbf26b9b1b4210f41/src/WebJobs.Script/Rpc/RpcInitializationService.cs#L34
2. Cache node version (`WEBSITE_DEFAULT_NODE_VERSION` from App Settings) in Placeholder mode to be accessed later. Probably best here: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Rpc/WebHostLanguageWorkerChannelManager.cs (backup: check with Brett if this is ok) https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Standby/StandbyOptions.cs  https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Standby/StandbyOptionsSetup.cs
3. Update logic for IsSupportedRuntime to figure out if we should kill placeholder node.exe https://github.com/Azure/azure-functions-host/blob/f1d0536afa45855a5150abebbf26b9b1b4210f41/src/WebJobs.Script/Rpc/FunctionRegistration/FunctionDispatcher.cs#L176
4. Run from zip only? (Verify if Portal editing will work.)

**Comment by fabiocav** [comment]
In review moving to Sprint 59
