### ISSUE TITLE
Add telemetry for DI usage

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-host#4714]
Would be good to understand (in priority order):

- How many people are using DI in their function
- The types of services they are registering (ILogger? ISomeService?)

/cc @fabiocav not sure if this is the best repo for this but adding here

**Comment by fabiocav** [comment]
@jeffhollan this was originally (before transfer) labeled as a P1. I'm labeling this a P2, but let me know if you want to raise the priority.

**Comment by fabiocav** [comment]
This work depends on https://github.com/Azure/azure-webjobs-sdk/issues/2329

**Comment by jeffhollan** [comment]
Whether it's this item or another my hope would be from a supportability standpoint if we could easily write a detector to let us know if any core services were being overwritten, or at the very least if they had their own custom dependencies setup so we could use that in investigation

**Comment by madelinegordon** [comment]
Closed via [#5179](https://github.com/Azure/azure-functions-host/pull/5179)
