### ISSUE TITLE
Dependency Injection and the default IConfiguration service

### ISSUE THREAD

**Issue by kawazoe** [Azure/azure-functions-host#4726]
#### Is your question related to a specific version? If so, please specify:
Any version (as of today) targeting netcoreapp2.1

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#, but probably others as well

#### Context
I have noticed a lack of guidance on how configurations should be passed to an Azure Functions app when using dependency injection and the Microsoft.Extensions.Configuration nuget package for local testing.

In the [MSDN documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#function-app-provided-services), you mention that the IConfiguration service is pre-configured in the DI container. By inspecting its configuration with a debugger, we can see 6 configuration providers. In all of those providers, the [usual local.settings.json file](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#local-settings-file) is never loaded. There is also no fallback for `appsettings.<environement>.json` like you would see in an asp.net core project.

I have seen many people online [suggesting to use the IConfigurationBuilder to load the file](https://www.koskila.net/how-to-access-azure-function-apps-settings-from-c/) but these examples never consider DI and the potential conflict between this new IConfigurationRoot and the one registered automatically by the tooling.

#### Question
I can see that environment variables are still the go to solution to configure deployed functions. What is the new recommended way to load local settings (including secrets) into our functions to test them with the emulator if the `local.settings.json` file is no longer loaded?

**Comment by espray** [comment]
See
- https://github.com/Azure/azure-functions-host/issues/4464
- https://github.com/Azure/azure-functions-host/issues/4577
- https://github.com/Azure/azure-functions-host/issues/4597

**Comment by kawazoe** [comment]
Hi @espray, That's great info you linked there. Thanks!

Also, I kinda answered my own question as well. It turns out that the `local.settings.json` file is not loaded through a standard provider at all. Instead, it is loaded via the `Azure.Functions.Cli.ExtensionBundle.JsonFileConfigurationSource.JsonFileConfigurationProvider`. It still works but only with flat configurations. That will require a custom files to be loaded like in #4464  .

I'm going to close this task as the ones you've linked already have more info in them.

**Comment by jasoncoding** [comment]
Not to necro this thread but I can't find anything else on point.  In order to read the _provided_ IConfiguration wired up by the host/runtime I am resorting to this in a functions startup class configure routine:

```
var descriptor = builder.Services.FirstOrDefault(d => d.ServiceType == typeof(IConfiguration));
var config = descriptor?.ImplementationInstance as IConfiguration;
string = config["mySettingFromValuesInAppsettingsJsonOrRealAzureSettings"]
```

This feels hacky yet I don't see a way to read configuration data during DI startup any other way.  Will this have any side affects?  Is there guaranteed to always be an instance of IConfiguration in the services collection during startup?
