### ISSUE TITLE
Log Streaming tab doesn't work

### ISSUE THREAD

**Issue by sandeepiiit** [Azure/azure-functions-host#4727]
#### Investigative information
- Timestamp: 2019-07-27 06:17:54.094 (UTC)
- Function App version (1.0 or 2.0): 2.0
- Function App name: N/A
- Function name(s) (as appropriate): N/A
- Invocation ID: 8b2f0d54-3241-46e3-ba05-0e82ab06e261
- Region: Central US

#### Repro steps
I have a function that receives messages from a service bus. I am able to see the logs in application insights, and I can see that it's processing the requests as expected. The problem is that I don't see any logs in the "Log Streaming" tab in the portal. See image below:

![image](https://user-images.githubusercontent.com/13448362/61990936-525ea880-affe-11e9-9498-20fa89955b66.png)

The above image indicates that no lines were logged between 6:17:46 and 6:18:46. However, see the below image from application insights logs, and you can see there were clearly several requests that were processed during this time (and several log lines written).

![image](https://user-images.githubusercontent.com/13448362/61990887-93a28880-affd-11e9-8915-7d01c19be013.png)

![image](https://user-images.githubusercontent.com/13448362/61990879-6ce45200-affd-11e9-846b-7dc1eef63688.png)

I tried Edge browser and Chrome, and also private tab in Edge, but I see the same behavior.

Note that I end up seeing this for extended period of time, and then sometimes it resolves itself. For example, I noticed it not work for weeks in June. Then, surprisingly I saw it work for at least a week in the beginning of July. But now I noticed it is not working.
Also, I see this behavior across all the function apps that I currently have. (So it's not limited to just one app).

#### Expected behavior
Expect to see live logs in the `Log Streaming` tab.

#### Actual behavior
No logs show up in `Log Streaming` tab.

#### Related information 
* Programming language used : C#
* Links to source
* Bindings used : ServiceBusTrigger
<details>
<summary>Source</summary>

```csharp
    public static class Function1
    {
        static int counter=0;
        [FunctionName("PrintServiceBusMsgs")]
        public static void Run([ServiceBusTrigger("<queue name>", Connection = "ConnectionString")]string myQueueItem, ILogger log)
        {
            TimeZoneInfo pstZone = TimeZoneInfo.FindSystemTimeZoneById("Pacific Standard Time");
            DateTime pstTime = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, pstZone);
            log.LogWarning($"[{DateTime.UtcNow}] [{pstTime}]C# ServiceBus queue trigger function processed message: {myQueueItem}");
            log.LogWarning($"This is message number: {counter} since the app start. If it's 0, then it's the first message after deallocation.");
            ++counter;
        }
    }
```
</details>

**Comment by brettsam** [comment]
What does your `host.json` look like? Those logs come from our file logger -- so if we're not logging to the file, you won't see anything. By default, we do this only when you are actively using the portal -- but you can also disable it with `fileLoggingMode: never`. https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#logging

**Comment by sandeepiiit** [comment]
host.json below:

```
{
  "version": "2.0",
  "logging": {
    "logLevel": {
     // Below line is needed due to https://github.com/Azure/azure-functions-host/issues/4345
      "<namespace of my app>": "Information"
    }
  }
}

```
Also, note that it works sometimes, and sometimes doesn't.

Interesting to know that it only logs when actively using portal - I think that's a nice feature!

**Comment by brettsam** [comment]
I bet the portal is timing out the "debug mode". Most of the time that you navigate in the portal, we update a `debug_sentinel` file. After 15 minutes of that file not being touched, we'll stop writing to the files. I suspect that's what you're seeing.

You can see this file in kudu under `D:\home\LogFiles\Application\Functions\Host`

**Comment by fabiocav** [comment]
Closing as answered. Please open an issue and reference this one if you continue  to see problems.
