### ISSUE TITLE
Logging with Azure function

### ISSUE THREAD

**Issue by klogan12** [Azure/azure-functions-host#4739]
I have several API's implemented with Azure Functions , I want to have a common logger for all APIs. What is the best way to achieve it?
My APIs calls several utility classes and i do not want to pass ILogger to all my utility classes.

**Comment by brettsam** [comment]
How do you create your utility classes? If you're using Dependency Injection, you can request an ILogger<T> (or ILoggerFactory) in any of them and they'll be injected when they're created.

**Comment by klogan12** [comment]
@brettsam  Can u share doc on how to consume logger object via DI? I can do that..

**Comment by fabiocav** [comment]
@klogan12 you should be able to take a dependency on ILogger<T> or ILoggerFactory from any injected service.
