### ISSUE TITLE
How to intercept outgoing HTTP(S) traffic in Fiddler?

### ISSUE THREAD

**Issue by ethanroday** [Azure/azure-functions-host#4743]
I have a function that makes some API calls before returning. When I'm debugging locally and I turn on Fiddler, though, I don't see those outgoing requests.
Is there any configuration change I can make to monitor that outgoing traffic when debugging?
I am already decrypting HTTPS traffic in Fiddler, and I've tried the instructions [here](https://www.telerik.com/blogs/capturing-traffic-from-.net-services-with-fiddler), but to no avail.

Information:
- Windows 10
- Functions V2
- Typescript

**Comment by brettsam** [comment]
Did you try this? https://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/ConfigureDotNETApp#configure-net-core-applications

**Comment by brettsam** [comment]
Closing as I believe that'll work for you.

**Comment by ethanroday** [comment]
@brettsam just tried that and it doesn't seem to have worked.

**Comment by brettsam** [comment]
Oh wait -- this is TypeScript. @mhoeger -- do you know if there's anything special that needs to be done to enable TypeScript and Fiddler?

**Comment by securityvoid** [comment]
@brettsam I've done this with NodeJS functions quite a bit. Typically it depends on what JavaScript library you're utilizing to make the HTTPS call. 

e.g. I've used "request", which if you search for Proxys it has this here:
https://github.com/request/request/tree/master/examples

Unless the underlying system utilizes the system proxy settings you'll always have to configure something. I haven't found any JavaScript to utilize any system level settings and I'd imagine TypeScript would be the same.

**Comment by ethanroday** [comment]
Thanks @securityvoid. I'm using `request-promise-native` so I figured I'd have the same issue.

I tried the instructions here and they worked: https://stackoverflow.com/questions/17383351/how-to-capture-http-messages-from-request-node-library-with-fiddler

**Comment by brettsam** [comment]
Thanks @securityvoid!

**Comment by securityvoid** [comment]
@ethanroday Glad to hear it worked for you! Azure Functions are fun ;-).
