### ISSUE TITLE
The function name isn’t included in execution status metrics for v2

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-host#4745]
For v2 apps, the function name isn’t included in the metrics where the status of an execution is measured making it difficult to analyze and correlate correctly.

// @paulbatum

**Comment by jcookems** [comment]
In particular, 
```
FunctionsMetrics
| where TIMESTAMP >= ago(1h)
| where EventName == 'function.invoke.succeeded' or EventName  == 'function.invoke.failed'
| summarize count() by FunctionName
```
gives

 FunctionName | count_
 -- | --
   | 620763

**Comment by fabiocav** [comment]
Adding this to sprint 60 as a stretch goal
