### ISSUE TITLE
[Question] Why does this repo has its own implementation of DI?

### ISSUE THREAD

**Issue by IdeaHunter** [Azure/azure-functions-host#4752]
#### Is your question related to a specific version? If so, please specify:
V2 host, net core 2.2 
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
c#
#### Question
I see, my asp.net core 2.2 app uses https://github.com/aspnet/Extensions/blob/a58a80bdf5ad971167f73e501661131c3e34a901/src/DependencyInjection/DI/src/ServiceLookup/ServiceProviderEngineScope.cs but this repo uses its own handmade implementation for some reason?

**Comment by brettsam** [comment]
We need multiple containers. We have a parent container and can have many child containers. We create/destroy child containers when the host needs to restart and we also allow for dependencies to flow in a custom manner between these containers. All of that required us to implement some of these classes differently than the default. We use [DryIoC](https://github.com/dadhi/DryIoc) internally to give us the base container behavior we needed.

**Comment by brettsam** [comment]
Going to close this as it's not really an issue -- but hopefully that added some details for you.
