### ISSUE TITLE
Option to disable auto-delete of message for Queue-triggered Functions

### ISSUE THREAD

**Issue by craiglytle** [Azure/azure-functions-host#4758]
Problem: 
For long-running tasks Azure is recommending using a Queue to trigger Functions to launch a container in Azure Container Instances (ACI).  A good example is recommended by Azure here:
https://github.com/Azure-Samples/aci-event-driven-worker-queue

But this approach won't work as the Functions will delete the queueMessage after it successfully launches the ACI container.  This means that if the task fails within the ACI container, then task is silently lost as the queueMessage has already been deleted and will not be put back into the Queue.

Desired Solution:
Add an option to the host.json for 'autoDeleteMesage': 'False'.
e.g.
```
{"extensions": 
     {"queues": 
         {"autoDeleteMessage": False}
     }
}

```

Alternatives:
- Tried raising error in Functions after launching ACI to avoid auto-delete.  But not only is that ugly, it doesn't seem to work.

**Comment by brettsam** [comment]
If auto-delete is false, the queue message will never disappear and the function will continue to fire forever. I'm not sure that'd be a better solution.

I wonder if Durable Functions is a better approach here -- triggered by the queue but it can check repeatedly for failures in startup. If there are any, it inserts a new message to try again. Or even from within the Durable function it can retry (no new queue message needed).
