### ISSUE TITLE
ServiceBusTrigger breaks Dependency Injection

### ISSUE THREAD

**Issue by h3rmanj** [Azure/azure-functions-host#4760]
Adding a ServiceBus triggered function to an app currently breaks Dependency Injection locally. I haven't tested deploying the function project, but I don't want to do that before it works locally.

```
Azure Functions Core Tools (2.7.1505 Commit hash: eb8182995562240ca83dd0e0e3394586cf5fdfa3)
Function Runtime Version: 2.0.12590.0
```

#### Repro steps
1. Create an Azure Function project in Visual Studio
2. Set up DependencyInjection Startup and inject something (eg. Greeter)
3. Add a HttpTrigger which uses the injected service.
4. Everything works as expected.
5. Add a ServiceBusTrigger function.
6. Now if you call the HttpTrigger it breaks because DI can't resolve the service.

#### Expected behavior
Adding a ServiceBus trigger function should not break Dependency Injection.

#### Actual behavior
Adding a ServiceBus trigger function breaks Dependency Injection.

#### Related information 
Environment: Local development in Visual Studio .NET Core.

Reproduction repository: https://github.com/h3rmanj/azure-functions-host-repro

**Comment by h3rmanj** [comment]
I also tried using a live Storage Account, in case the host didn't like a mix of local Storage Account and live ServiceBus. Still didn't work though, but at least that's off the table.

**Comment by brettsam** [comment]
This has something to do with the extensionsBundle, but I don't know what it is. When I remove that section from host.json, it all works. @soninaren -- any idea on this one? The repro project is above.

**Comment by soninaren** [comment]
@brettsam you are right. This is because extension bundles is not designed to be used with pre-compiled C# functions. Adding bundles configuration will break DI since the runtime is not loading extension and other related binaries from the bin folder. Instead it will load the the binaries from the extension bundle. 

@h3rmanj Please remove the following configuration from host.json.
```
"extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 3.0.0)"
  }

You can find more information on extension bundles here:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register

**Comment by h3rmanj** [comment]
Oh, my bad, must have misunderstood the docs. Thanks!
