### ISSUE TITLE
Add RuntimeSiteName to FunctionsLogs and FunctionsMetrics

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#4767]
For an app with slots, there is a version of the app name that looks like this: "myapp__f1de". This is typically referred to as "RuntimeSiteName". Some of the other system tables log in this format, but FunctionsLogs and FunctionsMetrics do not. This prevents correlation across the tables.

**Comment by divyagandhii** [comment]
We will have to make the same change for Linux consumption logging as well.

**Comment by divyagandhii** [comment]
Is this change done for windows?

**Comment by paulbatum** [comment]
No, I don't think anyone has looked at this yet.

**Comment by divyagandhii** [comment]
Thanks. I will open another one for Linux Consumption after it's done for windows.

**Comment by paulbatum** [comment]
I have an owner for this work item, I'll update once I have their github username

**Comment by paulbatum** [comment]
So I think APP_POOL_ID is probably not going to work, because of placeholders. This can be confirmed by inspecting the APP_POOL_ID for a slot in a function app in the consumption plan.

Some more digging might be required to find a reliable way of getting the runtime site name.
