### ISSUE TITLE
Azure Function Blob Trigger stops firing

### ISSUE THREAD

**Issue by meixger** [Azure/azure-functions-host#4784]
As @ankitkumarr stated in [Azure/azure-functions-host#3592](https://github.com/Azure/azure-functions-host/issues/3592#issuecomment-511606606) i open a separate issue:

#### Investigative information

- Timestamp: 2019-08-09T09:43:51.750
- Function App version (1.0 or 2.0): 2.0
- Function App name: not-disclosed-here
- Function name(s) (as appropriate): not-disclosed-here
- Invocation ID: 7c0375d4-06c7-4cc4-a1f6-f4bc5dd4c371
- Region: West Europe

#### Repro steps

A simple blobtrigger function.

#### Expected behavior

Function gets triggered by new blobs created from a HttpTrigger.

#### Actual behavior

Works fine for several weeks, but suddenly stops.

#### Known workarounds

After restarting the App Service manually it recovers.

#### Related information 

* Programming language used 
C# .NET Core 2.1

* Bindings used
BlobTrigger from Microsoft.Azure.WebJobs.Extensions.Storage 3.0.0

**Comment by alrod** [comment]
I see consistent executions in your function app every day. I do not see executions in period: 21:00 UTC ~ 04:00 UTC each day during last 4 days. Why do you think the function app was stopped? What time did the function app stop?

By the way the premium plan function app is always running.

**Comment by meixger** [comment]
Looking in AppInsights i see that from `invocation 9e208afa-bff5-4d98-a61c-3259a106cdf6 at 2019-07-16T21:04:22.476Z` until `invocation 687604b4-04c4-4051-9554-3d5b5f53d61a at 2019-07-29T01:14:33.908Z` there is a gap of ~13 days w/o infocations of the blob trigger.
But in this time range ~1300 blobs created piled up.

I didn't restart the app purposely to allow better diagnosing but now the blob trigger picked up by itself.

PS: The nightly period w/o invocations from 21 UTC to 4 UTC is OK.

**Comment by alrod** [comment]
Yes, I see your function `******s` started to process new blobs right after restart 2019-07-29 01:14:16
We have a regression which causes blob/queue triggers sometime getting stuck.

Workaround:

1.Open portal -> Restart the function app.
2.After the app has restarted. Go to Platform Features -> Function app settings tab -> Verify that the function runtime version is 2.0.12625.0 or newer
3.Open the function app project on the dev box
4.Follow the steps here to add the NuGet feed to the project https://github.com/Azure/azure-5.webjobs-sdk/wiki#latest-builds
Update the Microsoft.Azure.WebJobs.Extensions.Storage extension version to 3.0.8-11642
o	https://www.myget.org/feed/azure-appservice/package/nuget/Microsoft.Azure.WebJobs.Extensions.Storage/3.0.8-11642
6.Redeploy the app. Monitor for any signs of it getting stuck.
The same fix will be included in the next function runtime release, for now you can use 3.0.8-11642. Please let us know if you still seeing the issue. Sorry for inconvenience.

**Comment by meixger** [comment]
Thanks, i updated Microsoft.Azure.WebJobs.Extensions.Storage to 3.0.8-11642 and deployed successfully. The function runtime version is 2.0.12641.0.

I will monitor if blob triggers get stuck again and report.

**Comment by alrod** [comment]
Closing as 3.0.8 has the restart code

**Comment by derekrprice** [comment]
Not sure if I am looking at a regression or a separate issue, but this is still happening to me with a scaled-up set of the latest 2.0 azure functions runtime docker image.  This image appears to be more recent than the versions tagged both "2.0.12673" and "2.0.99999".  In any case, there was an error message in the logs just before processing stopped: 
```
Singleton lock renewal failed for blob '***-functions/host' with error code 409: LeaseIdMismatchWithLeaseOperation. The last successful renewal completed at 2019-10-27T16:12:10.853Z (17048 milliseconds ago) with a duration of 4 milliseconds. The lease period was 15000 milliseconds.
```
Restarting 1 of the 8 functions contianers did not cause processing to resume, though the restarted container did not issue any error messages, about locks or otherwise.  Picking another 3 of the 8 functions containers, effectively at random, and restarting them caused new blob processing to resume.

**Comment by derekrprice** [comment]
Anyone have any idea what may be causing this?  We're still seeing it.  It appears to occur pretty consistently on a daily basis and once we see the error, processing in our 6 concurrently running containers stops, usually for many hours.
