### ISSUE TITLE
Is there a way to disable a function dynamically? (specifically a service bus triggered function)

### ISSUE THREAD

**Issue by rajrao** [Azure/azure-functions-host#4785]
I have an AZ Function that picks up messages delivered to a subscription and does work against a web-api. Sometimes that web-api goes down. What I would like to do is disable my trigger for some period of time, so that messages dont get delivered (as otherwise, it can get deadlettered because of too many retries).

Essentially what I want is a circuit breaker pattern. Messages get picked up as long as the circuit is closed, and when the circuit is open, no messages get delivered. I would then close the circuit after some time or potentially via some other Az function being triggered within the same function app.

**Comment by alrod** [comment]
Disabled/Enabled state is controlled by the app setting:
`AzureWebJobs.<FUNCTION_NAME>.Disabled` (it works also for V1, document is not updated yet)
https://docs.microsoft.com/en-us/azure/azure-functions/disable-function

You can change app setting using Kudu REST API:
https://github.com/projectkudu/kudu/wiki/REST-API#settings

**Comment by alrod** [comment]
Closed as no active.
