### ISSUE TITLE
Azure Functions: Node.js Request@2.88.0 not working

### ISSUE THREAD

**Issue by LoliLin** [Azure/azure-functions-host#4787]
- Timestamp: 2019-08-10T06:13:34.148
- Function App version (1.0 or 2.0): 2.0
- Invocation ID: db7ea1a9-7b0e-4dbe-8d90-6e8d3fd6b2df
- Region: East Asia

```javascript
return new Promise((resolve, reject) => {
  context.log('Promise inside');
  request.get({url: fileurl, encoding: null, headers: {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36',
    'cache-control': 'max-age=0',
  },timeout:10000},(error, response, body) => {
    context.log('Request inside');
    if (error)
    {
      context.log(error.toString());
      reject();
    }
    ...
    context.log(filemetadata);
    ....
    resolve(sendRespone(body,filemetadata,settings.expireTime));
  });
});
```

The above code works fine at some point, but it doesn't work in some cases. The specific behavior is that the entire program will freeze when accessing error, respone or body objects.

Normally, the output of the program should be like this:
```
[Information] File url: https://secure.gravatar.com/avatar/b5637829ffde7725999757c7dfb6696c?s=512&d=mm&r=g&1
[Information] Promise inside
[Information] Request inside
[Information] image/png
[Information] [200] [object Object]
[Information] Sent
```

However, when using another URL, the log will always stop at the last line, and will not be updated, the page will remain in the waiting state, and finally return a 500 or 502 error.
```
[Information] File url: https://xiaolin.in/wp-content/themes/c7v5/js/prism.js?ver=4
[Information] Promise inside
[Information] Request inside
```
If I put the `if (error)` statement at the first line of the callback function, then "Request inside" will not output.

It seems that the request request has been sent because there is such a line on the log of my web server:
```
168.63.209.xx - - [10/Aug/2019:14:11:04 +0800] "GET /read/portainer.html HTTP/1.1" 200 39223 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36" "-"
```

I am not sure if this is a problem with the Request module or a problem with the Azure Function, but this code is passable in my native test environment.

**Comment by alrod** [comment]
cc: @mhoeger

**Comment by mhoeger** [comment]
@LoliLin - I believe your request appears to hang because there is an uncaught exception in your code on the error path execution (ex: if I replace `context.log(error.toString());` with something that clearly won't work like `context.log(error.missingProperty.toString());`, I will see an uncaught exception and the same hanging behavior from the client.

My recommendation is to restructure your code to something like this to avoid uncaught exceptions:
```javascript
const request = require("request");
const util = require('util');
const getRequestAsync = util.promisify(request.get);

module.exports = async function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');
    let fileurl = "https://secure.gravatar.com/avatar/b5637829ffde7725999757c7dfb6696c?s=512&d=mm&r=g&1";
    let response;
    try {
        response = await getRequestAsync(
            {
                url: fileurl, 
                encoding: null, 
                headers: {
                    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36',
                    'cache-control': 'max-age=0',
                },
                timeout:10000
            });
    } catch (error) {
        context.log(error.toString());
        // Re-throwing this because Azure functions automatically catches this exception and will mark your execution as "failed"
        throw error;
    }

    context.log(response);
    context.log(response.body);
    ...
    return sendRespone(body,filemetadata,settings.expireTime);
};
```
This way, you can do a try/catch around getRequestAsync if you'd like. Any exceptions raised 


On our end, I realize that uncaught exceptions don't surface in a useful way if you're developing/running in the portal... it only shows up in an obvious way in local development. Issue filed here to surface those in a better way: https://github.com/Azure/azure-functions-host/issues/4787
