### ISSUE TITLE
AF for IoT Hub. Error after publishing from VS2017: Value cannot be null. Parameter name: receiverConnectionString.

### ISSUE THREAD

**Issue by niliand** [Azure/azure-functions-host#4788]
C#

I created a new c# project for IoT HUB Function in VS2017. When I run it on my PC the function works - it receives messages for the iot hub. But when I published the function on Azure Cloud it always prints:
-------------------------------------------------
Error:

Function (FunctionApp120190808020849/scheiotFunction1) Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'scheiotFunction1'. Microsoft.Azure.WebJobs.EventHubs: Value cannot be null. Parameter name: receiverConnectionString.
Session Id: acaf3c0a1772484db6927e2f33ab365a

Timestamp: 2019-08-12T07:00:09.621Z
----------------------------------------------------

I found the file local.settings.json is missing, I created it manually using "New file" - but result the same. 

Where I must specify the connection string?

**Comment by alrod** [comment]
Did you specify `receiverConnectionString `in the function app settings in azure?

**Comment by niliand** [comment]
Specified it here:

![image](https://user-images.githubusercontent.com/31726996/62997762-f3a88400-be71-11e9-83a2-9328e210dcc3.png)

Is it correct?

**Comment by niliand** [comment]
the string must be provided here: 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-use-azure-function-app-settings#settings

**Comment by niliand** [comment]
the string must be provided here: 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-use-azure-function-app-settings#settings
