### ISSUE TITLE
QueueTrigger function stopped firing on consumption plan

### ISSUE THREAD

**Issue by jasoncoding** [Azure/azure-functions-host#4789]
After successfully deploying a function on 8-9-2019 the function suddenly stops processing queue messages around 4am on 8-11-2019.  This is a very active queue but I can see that time period being a lull in the action.

After the last message was processed at 4am on 8-11-2019 I see nothing, no errors, zero.  Wake up this morning and I have thousands of messages back up in the queue.

I reviewed https://github.com/Azure/azure-functions-host/issues/3356 and https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies.  If this is related to a trigger sync thing shouldn't the deployment task from Azure DevOps be handling that?  And why wouldn't it have failed soon after the deployment instead of a day and a half later?

This is a core part of our messaging infrastructure and we need to have this working.  Please advise and thank you for any insight!

**Investigative information**
When this occurred: 2019-08-11 around 4am EDT
Region: USWest2
Functions version: 2

**Expected behavior**
With messages in the azure storage queue, the Azure function should be triggered and run automatically.

**Actual behavior**
The Azure function is not triggered unless I manually bash Refresh in the portal.

**Related information**
Language: C#
Deployed with: Azure DevOps release functions task
Application Setting: WEBSITE_RUN_FROM_PACKAGE = 1
Input binding: [QueueTrigger]MessageData

**Comment by alrod** [comment]
can you please share your function app name privatly

**Comment by jasoncoding** [comment]
Hi @alrod ,

When I follow the instructions in the link I get a log screen with text flying by pretty fast.  This is a very active function.  Even when I pause the log I don't see anything like what is in your link.  I did look into app insights and found a host started event:

event time: 2019-08-14T16:40:22.955Z   HostInstanceId: 307395d4-c48b-4810-9873-40cc837f0506

Does this help?

**Comment by alrod** [comment]
Yes, I see your queue trigger was hanged from 2019-08-11 08:49:53 UTC to 2019-08-12 13:28:02 UTC despite new messages in the queue. We have a regression which causes queue triggers getting stuck.

Workaround:
1.	Open portal -> Restart the function app.
2.	After the app has restarted. Go to Platform Features -> Function app settings tab -> Verify that the function runtime version is 2.0.12625.0 or newer
3.	Open the function app project on the dev box
4.	Follow the steps here to add the NuGet feed to the project https://github.com/Azure/azure-webjobs-sdk/wiki#latest-builds
5.	Update the Microsoft.Azure.WebJobs.Extensions.Storage extension version to 3.0.8-11642
o	https://www.myget.org/feed/azure-appservice/package/nuget/Microsoft.Azure.WebJobs.Extensions.Storage/3.0.8-11642
6.	Redeploy the app. Monitor for any signs of it getting stuck. 

Same fix will be included in the next function runtime release, for now you can use 3.0.8-11642. Sorry for inconvenience.
