### ISSUE TITLE
The requested app service plan cannot be created in the current resource group because it is hosting Linux apps

### ISSUE THREAD

**Issue by JeanBaptisteScellier** [Azure/azure-functions-host#4790]
I am trying to deploy a Windows Function app on my resource group. My function app contains 2 databases, a data factory and a logic app. No Linux based function app... Though I've got this error message: "The requested app service plan cannot be created in the current resource group because it is hosting Linux apps. Please choose a different resource group or create a new one"

I found sb with the same problem: https://stackoverflow.com/questions/54577245/the-requested-app-service-plan-cannot-be-created-in-the-current-resource-group-b
The solution given is: creating a new Linux App Service Plan and deleting it. This did not work for me.

Any advise is welcome :)

I give you all the details about the deployment:

Function app with Windows OS, Node.js, Consumption Plan
Start time: 8/12/2019, 5:16:51 PM
Correlation ID: a9dd2307-731d-467f-a310-e8afcafeade7
Region: West Europe

{ "id":***, "operationId": "27E98B9DCCF7D3D9", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2019-08-12T15:17:17.8664597Z", "duration": "PT1.2004004S", "trackingId": "e3c62cc9-c2ed-4a2e-8f6d-3a0097eb7634", "statusCode": "BadRequest", "statusMessage": { "Code": "BadRequest", "Message": "The requested app service plan cannot be created in the current resource group because it is hosting Linux apps. Please choose a different resource group or create a new one.", "Target": null, "Details": [ { "Message": "The requested app service plan cannot be created in the current resource group because it is hosting Linux apps. Please choose a different resource group or create a new one." }, { "Code": "BadRequest" }, { "ErrorEntity": { "ExtendedCode": "59314", "MessageTemplate": "The requested app service plan cannot be created in the current resource group because it is hosting Linux apps. Please choose a different resource group or create a new one.", "Parameters": [], "Code": "BadRequest", "Message": "The requested app service plan cannot be created in the current resource group because it is hosting Linux apps. Please choose a different resource group or create a new one." } } ], "Innererror": null }, "targetResource": *** }}

**Comment by alrod** [comment]
cc: @balag0

**Comment by alrod** [comment]
@JeanBaptisteScellier, can you please try to use [resource explorer](https://azure.microsoft.com/en-us/blog/azure-resource-explorer-a-new-tool-to-discover-the-azure-api/
) to see if you have linux resources in the resource group and delete them.

Is creating new resource group works for you?

**Comment by JeanBaptisteScellier** [comment]
Thanks for answering.
I checked via Resource Explorer and I confirm you there is no Linux Resource in the resource group.
I do not have rights to create a new resource group. That is why I post here the problem. But if you cannot solve the bug, I will ask for a new one.

**Comment by balag0** [comment]
@JeanBaptisteScellier Looks there is another linux function app ending in "-api" in the same resource group where the new windows app is being created which is causing the validation to fail.  Creating the new windows app in a different / new resourcegroup should resolve the issue.

**Comment by JeanBaptisteScellier** [comment]
Right now there is one (it was not the case when i answered you) because I need to code, but I would like a Windows one. And every time I delete my Linux app (and the linked app service plan, app insight and storage account) to create a Linux app function, I've got this problem.

**Comment by ThejaChoudary** [comment]
@JeanBaptisteScellier 
You can't run both Linux and Windows function apps in the same App Service plan. If you still want both the Linux and Windows Functions apps in the same Resource group it is possible only when you use different app service plans.Hope this could help you resolve the problem.
Closed this as resolved/answered ,but please let us know if you need any additional information. Thank You !

**Comment by ecaron** [comment]
@ThejaChoudary, the unresolved error in https://github.com/Azure/azure-functions-host/issues/6014 is making the above situation unavoidable. There are workarounds, but they are unpleasant.
