### ISSUE TITLE
Host is offline

### ISSUE THREAD

**Issue by armanio123** [Azure/azure-functions-host#4791]
The Azure function is reporting ` Status: 503 Service Unavailable` when trying to run it.
I went to troubleshoot the function and is reporting that the host if offline. Logs also show this but I niether found a description about why the host is offline nor I have discovered myself.

My host.json file looks like this: 
```js
{
    "version": "2.0"
}
```

#### Investigative information

Please provide the following:

- Timestamp: 8/12/2019 4:53 PM PT
- Function App version (1.0 or 2.0): 2.0
- Function App name: PostExceptionStacks
- Function name(s) (as appropriate): PostExceptionStacksFunction
- Invocation ID: Can't provide since it doesn't run or shows in the log.
- Region: East US

#### Repro steps

1. Go to Azure function.
2. Click run.

#### Expected behavior

Runs the function.

#### Actual behavior

Doesn't run.

#### Related information 

Provide any related information 

* Programming language used: TypeScript

**Comment by alrod** [comment]
Did you try to restart the function app through the portal?

**Comment by armanio123** [comment]
Yes. I tried restarting, creating a new function, checking logs, appinsights, etc.

**Comment by ankitkumarr** [comment]
Can you check if there is an `app_offline.htm` file in you site directory? If so, would you mind removing it and retrying?

You can use the kudu website (<appname>.scm.azurewebsites.net), then navigate to Debug Console. From there, go to `home/site/wwwroot`. 

How had you deployed your Function App last? We advise using [RunFromPackage](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package) as a deployment method.

**Comment by armanio123** [comment]
Removing the `app_offline.htm` did the trick. Funny the file is there, my local code doesn't have it.

I have used VSCode's Azure Function extension for deployment and Zip Deployment.

**Comment by alrod** [comment]
Zip Deployment will now create a temporary app_offline.htm in the site's wwwroot folder before starting the deployment. Zip Deployment then takes care of deleting the file after deployment is complete. The effect is that while deployment is happening, the app will be kept offline. It looks something went wrong with your deployment and app_offline.htm was not deleted.

Try to use RunFromPackage as a deployment method.
