### ISSUE TITLE
"System.Runtime.Caching not supported" workaround not working

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-host#4795]
#### Check for a solution in the Azure portal
Initially described in issue #4581, related to azure/azure-functions-vs-build-sdk#271. [The suggested workaround](https://github.com/Azure/azure-functions-host/issues/4581#issuecomment-510630802) is not working locally. [kashimiz/functions-memorycache-repro](https://github.com/kashimiz/functions-memorycache-repro) is a simple repro with instructions.

#### Investigative information

Please provide the following:

- Timestamp: N/A
- Function App version (1.0 or 2.0): 2.0
- Function App name: N/A
- Function name(s) (as appropriate): N/A
- Invocation ID: N/A
- Region: N/A

#### Repro steps

1. F5 solution.
2. In Postman or other tool, send the following request:

```GET http://localhost:7071/api/Function1```

3. Host output should resemble the following:

```diff
# [8/13/2019 10:11:55 PM] Executing HTTP request: {
# [8/13/2019 10:11:55 PM]   "requestId": "db88457a-9355-4cb7-824d-409a061d6686",
# [8/13/2019 10:11:55 PM]   "method": "GET",
# [8/13/2019 10:11:55 PM]   "uri": "/api/Function1"
# [8/13/2019 10:11:55 PM] }
# [8/13/2019 10:11:56 PM] Executing 'Function1' (Reason='This function was programmatically called via the host APIs.', Id=5a07c664-ff0b-4b17-bdc2-d11e7a625271)
# [8/13/2019 10:11:56 PM] C# HTTP trigger function processed a request.
- [8/13/2019 10:11:56 PM] Executed 'Function1' (Failed, Id=5a07c664-ff0b-4b17-bdc2-d11e7a625271)
- [8/13/2019 10:11:56 PM] System.Private.CoreLib: Exception while executing function: Function1. System.Runtime.Caching: System.Runtime.Caching is not supported on this platform.
# [8/13/2019 10:11:58 PM] Executed HTTP request: {
# [8/13/2019 10:11:58 PM]   "requestId": "db88457a-9355-4cb7-824d-409a061d6686",
# [8/13/2019 10:11:58 PM]   "method": "GET",
# [8/13/2019 10:11:58 PM]   "uri": "/api/Function1",
# [8/13/2019 10:11:58 PM]   "identities": [
# [8/13/2019 10:11:58 PM]     {
# [8/13/2019 10:11:58 PM]       "type": "WebJobsAuthLevel",
# [8/13/2019 10:11:58 PM]       "level": "Admin"
# [8/13/2019 10:11:58 PM]     }
# [8/13/2019 10:11:58 PM]   ],
# [8/13/2019 10:11:58 PM]   "status": 500,
# [8/13/2019 10:11:58 PM]   "duration": 2226
# [8/13/2019 10:11:58 PM] }
```

#### Related information 

Provide any related information 

* Programming language used: C#
* Links to source: [kashimiz/functions-memorycache-repro](https://github.com/kashimiz/functions-memorycache-repro)
* Bindings used: HTTP trigger

**Comment by leniency** [comment]
The workaround suddenly stopped working in production on a dedicated Azure App Service. The function.deps.json file is in the bin folder.

I wasn't referencing System.Runtime.Caching, but doing pdf rendering, so System.Drawing. It was working a few days ago.

**Comment by brettsam** [comment]
@fabiocav -- do you know if something changed here?

**Comment by fabiocav** [comment]
@leniency thank you for the update. Nothing changed in prod, so it's good to understand what was causing the issue (and that it was related to the deployed payload). 

As a side note, the next release has a fix that will address the problem with the consumption apps, so that will work there as well.
Closing this as resolved.
