### ISSUE TITLE
Azure Function not triggering unless accessed via Azure portal

### ISSUE THREAD

**Issue by rolnikrolnik** [Azure/azure-functions-host#4799]
During the weekend 2 functions from the Function App stopped triggering. One of them (SendMail) is ServiceBusTrigger function, another one (AdminRequestSynchronizationOfOrganisationsAndUsers) is TimerTrigger function, despite messages on the queue and due timer schedules. Once Function App was visited in the Azure Portal, functions started to immediately run.

Function app was last deployed on 8 Feb via copying zip to wwwroot directly and restaring app to manually sync triggers. I am aware that it is not an optimal way of deploying and we plan on changing that. However, it is working for a long time (at least 1.5-2years) and the problem like this popped up just now.

Last correct invocations are as follows:
- **AdminRequestSynchronizationOfOrganisationsAndUsers** (cron: **0 15 6 * * ***)
![image](https://user-images.githubusercontent.com/6923351/63016263-81489b80-be93-11e9-913e-28cdf2a8f348.png)

last correct - 2019-08-10 06:15:00.101 - c121d806-068f-4c58-bb04-e541da19a38e
next - 2019-08-13 13:03:23.968 - 5d62e422-e8ce-4bb0-ac76-04854460509d

- **SendMail** - this invocation is pulled from host logs
`2019-08-13T13:03:26.502 [Info,SendMail] Function started (Id=e0be9b29-3500-4682-aaf0-e6ba8e2d5bd2)
2019-08-13T13:03:26.581 [Info,SendMail] Executing 'SendMail' (Reason='New ServiceBus message detected on 'mails'.', Id=e0be9b29-3500-4682-aaf0-e6ba8e2d5bd2)
2019-08-13T13:03:26.581 [Info,SendMail] Trigger Details: MessageId: 0e0e0661c1bd4943a1679e22a52a9600, DeliveryCount: 1, EnqueuedTime: 8/10/2019 4:51:22 PM, LockedUntil: 8/13/2019 1:08:26 PM
`

#### Investigative information

Please provide the following:

- Timestamp: 
AdminRequestSynchronizationOfOrganisationsAndUsers - 2019-08-13 13:03:23.968 
SendMail - 2019-08-13T13:03:26.581
- Function App version (1.0 or 2.0): 1.0
- Function App name:  *********-prod-af
- Function name(s) (as appropriate): AdminRequestSynchronizationOfOrganisationsAndUsers , SendMail 
- Invocation ID: AdminRequestSynchronizationOfOrganisationsAndUsers 5d62e422-e8ce-4bb0-ac76-04854460509d , SendMail e0be9b29-3500-4682-aaf0-e6ba8e2d5bd2
- Region: West Europe

#### Expected behavior

Functions run when the trigger happens.

#### Actual behavior

Functions does not run on expected schedule/service bus message, only when accessed via portal.

#### Known workarounds

Restarting app via portal works for a bit but then host terminates again and is up ony after accessing the app via portal.

#### Related information 

* Bindings used
ServiceBus and Timer

**Comment by alrod** [comment]
We had a regression in West Europe.
Impact: The function apps in West Europe region using consumption plan can be stopping triggering despite new items in azure resources.
Start: 2019-08-09T22:02:00 UTC.
End: 2019-08-13T20:10:00 UTC.

Your sub `x-x-4axx-x-x` was affected by the regression. 
Closing as the regression is already fixed. Sorry for inconvenience.
