### ISSUE TITLE
Typescript Container not building in Function App

### ISSUE THREAD

**Issue by dougmolineux** [Azure/azure-functions-host#4803]
#### Is your question related to a specific version? If so, please specify:
Yes, Function Apps 2.0

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
Typescript

#### Question
I have set up a Linux container-based Function App. I initially used the func init command (chose typescript option), and added some code using the service bus topic trigger template. When I run `npm start` locally, i can get it to work. There is a "prestart" command that builds the typescript, inside the package.json, it looks like
```
"prestart": "npm run build && func extensions install",
```
The build creates a dist directory so when it starts, I can see this:
```
[8/14/19 8:45:43 PM] 1 functions loaded
```
All is good. The problems start when I deploy this function to my function app. I am deploying from the Azure Container Registry. 

Via Kudu, I can see the container error logs:
```
2019-08-14T20:51:05.870505061Z       The following 1 functions are in error:
2019-08-14T20:51:05.870515162Z       ehmTopicTrigger: Invalid script file name configuration. The 'scriptFile' property is set to a file that does not exist.
2019-08-14T20:51:05.870540263Z       
```
When I run `func start` locally and my dist directory doesn't exist, I get the exact same error. This leads me to believe that when the docker container starts in the Function App, it is not running `npm start` (or for whatever reason, its not building and creating `dist`).

I'm not entirely sure if this is a bug, or if I'm doing something wrong. Could you please advise?

Thank you.

**Comment by alrod** [comment]
cc: @balag0

**Comment by dougmolineux** [comment]
@brettsam so I managed to get this to build by modifying the Dockerfile. I added `npm run build`. In its entirety, the Dockerfile looks like this:
```
FROM mcr.microsoft.com/azure-functions/node:2.0

 ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

 COPY . /home/site/wwwroot

 RUN cd /home/site/wwwroot && \
    npm install && \
    npm run build 
```
This created the `dist` folder and the function is running. So I'm going to close this now, thank you!
