### ISSUE TITLE
Azure Functions Core Tools "cold start" experience locally

### ISSUE THREAD

**Issue by andrewb273** [Azure/azure-functions-host#4806]
### OS and Browser

- macOS 10.14.6 Beta (18G48f)
- Postman/Brave
- Azure Functions Core Tools (2.7.1373 Commit hash: cd9bfca26f9c7fe06ce245f5bf69bc6486a685dd)
- VS Code Version 1.36.1 (1.36.1)

### Repro steps

1. Create simple function in .Net:
```
[FunctionName("Test")]
public static HttpResponseMessage Test(
	[HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "Test")] HttpRequest req,
	ILogger log
)
{
	return Responses.OK("Success");
}
```
2. Run functions, wait till list of Http Functions is printed in console.
3. Call `GET http://localhost:7071/api/Test` anywhere, such as in Postman
Expected: Quick response (< 1 second)
Actual: Slow response (~10 seconds to execute)

4. Call another function
Expected: Quick response (< 1 second)
Actual: Slow response (~10 seconds to execute)

5. Call either of the two previous functions again without stopping Functions:
Expected & Actual: Quick response

### Mention any other details that might be useful.

This is a major frustration for us, as the added startup time slows down our development. It has me wanting to pull as much of our logic out into a .Net Standard library, and using a traditional .Net Core MVC app to host that logic just for local development. I suspect this also greatly slows down the operation of our integration tests.

I don't quite understand why this is occurring - I see neither a spike in my CPU usage nor network usage. It feels very much like a cold start. I'm not well-versed with the production hosting of these functions, but I understand there are options for keeping functions always warm. Can there be such an option for local development?

**Comment by ahmelsayed** [comment]
The slowness in the invocation is a mix of dotnet JIT, storage emulator slowness, and the runtime blocking execution until a bunch of keys and storage stuff are initialized. 

The ~1.3 second difference between first call and second call you're seeing is almost entirely JIT. dotnet seems to delay JIT at all costs until it's time to actually invoke your code. So even if you run the process, wait for 10 minutes, then invoke the function, that's when dotnet will decide to JIT it.

**Comment by alrod** [comment]
Closed as answered. @andrewb273 feel free to reopen if you think the question is not fully answered.

**Comment by andrewb273** [comment]
@ahmelsayed ok thanks for the info. So we could reduce that JIT time by reducing the size of the codebase I presume?
