### ISSUE TITLE
Timer trigger fired twice

### ISSUE THREAD

**Issue by nardieu** [Azure/azure-functions-host#4808]
My function has timer trigger to call it once each 15 minutes. But yesterday it was called twice. It caused errors in DB requests because it supposed to be written only by one function.

![image](https://user-images.githubusercontent.com/3143121/63175099-f9f25800-c04b-11e9-9ea0-709d9c2c935f.png)
_Don't pay attention on canceled HTTP request_

#### Check for a solution in the Azure portal

Diagnostic didn't found anything suspicious. But as you can see function was called twice.
![image](https://user-images.githubusercontent.com/3143121/63173932-95ce9480-c049-11e9-8984-42664e2ed0d7.png)

#### Investigative information

Please provide the following:

- Timestamp: `2019-08-15T10:00:00.021105Z` and `2019-08-15T10:00:00.0879999Z`
- Function App version (1.0 or 2.0): 2.0.12625.0
- Function App name: I'd like to keep it private
- Function name(s) (as appropriate): I'd like to keep it private
- Invocation ID: `0ed21ca3-787a-426e-8b01-b9355ccaa806` and `0b48a14d-7aee-4c38-be76-cca820383a89`
- Region: `West Europe`

#### Repro steps

I don't have it. Problem appeared only once for few months of usage.

#### Expected behavior

Timer trigger must trigger strictly to cron rule.

#### Actual behavior

Timer trigger fired twice instead of one.

#### Known workarounds

Doesn't have.

#### Related information 

Here is how function is defined in code
```csharp
        [FunctionName("FunctionName")]
        public static async Task Run(
            [TimerTrigger("0 */15 * * * *")]TimerInfo myTimer,
            ExecutionContext context,
            ILogger log)
```
_`FunctionName` is not real function name. It's used to hide real name._
`runOnStartup` is `false`.

And some more information from logs:
![image](https://user-images.githubusercontent.com/3143121/63175493-c7952a80-c04c-11e9-8c29-cb24b0e8bbc7.png)
![image](https://user-images.githubusercontent.com/3143121/63175503-cfed6580-c04c-11e9-8d51-325394aa1bca.png)

**Comment by alrod** [comment]
In kusto logs I see the timmer trigger was once executed twice on different workers in the same time.

**Comment by brettsam** [comment]
I see that one host grabs the lease ~30 minutes earlier. And then the next host grabs it as well, but it's never been released. I wonder if this API has a deadlock issue just like some of the other storage ones that we've been seeing lately.

**Comment by NiekGr** [comment]
Are there any updates available?
I have the same problem with a TimerTrigger in a WebJob.

**Comment by lonpalmer** [comment]
Is this issue getting fixed?  No word since Nov 13 almost a year ago.

**Comment by brettsam** [comment]
@lonpalmer -- are you still seeing the issue? If you could share your **Function App name** (either explicitly or [privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)), and a **time frame for when you saw this**,  I can see if I find anything from the backend logs.

If this was indeed related to the deadlock, that issue has been resolved a few months ago with a fix in the Storage SDK: https://github.com/Azure/azure-webjobs-sdk/pull/2486. If it's something else, we'll need to try to gather more details.

**Comment by shengdamao** [comment]
> Is this issue getting fixed? No word since Nov 13 almost a year ago.

https://github.com/Azure/azure-functions-host/issues/2968 

You could check this issue. There is a solution provided in that one.
Hope this would be helpful.

**Comment by v-bbalaiagar** [comment]
Hi @nardieu , Can we know if you are seeing this issue still and requires further follow up.

**Comment by tsimafei-mazouka** [comment]
Hi @v-bbalaiagar. Didn't face this bug anymore.
I discovered it because it caused issues with Storage Table. I monitor all errors in my Azure Functions, but didn't notice this bug anymore. Furthermore, I switched to runtime version 3, and maybe it doesn't have such problem.

**Comment by v-bbalaiagar** [comment]
Thank you for the update. Closing this issue here, please feel free to reach back to us in case of any further queries related to this issue.
