### ISSUE TITLE
Add to context the logging level config

### ISSUE THREAD

**Issue by katlimruiz** [Azure/azure-functions-host#4815]
Since Azure Functions in NodeJs SDK is only limited to console and file, we need to send the logs to papertrail too.
Therefore I created a winston object with a syslog transport.

My issue now comes that my winston logger log level cannot make it match against host.json log level information (logging config), therefore now I have to match both by hand.

**Comment by brettsam** [comment]
+@mhoeger 

Can you elaborate on your scenario a bit? You're logging directly via a winston logger directly in node -- but you want to be able to grab the host configuration from within your function so you can apply it to your internal logger?

Also note that with nodejs you can use context.log() -- which will use the logging system wired up with functions (which can include App Insights). https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#contextlog-method

**Comment by katlimruiz** [comment]
I think the core problem here is that there is no way (or no documentation) how to inject the context.log by my own logger or winston or pino. It seems to be closed right now for only appinsights or console.

Yet, if this is not possible now, at least a shortcut would be to be able to read the host.config from within the function.

This way I could at least do the following:
```
                mylogger = winston.createLogger({
                    level: getContextLoggerLevelFromHostFile(), 
                    format: winston.format.json(),
                    transports: [
                        ...
                    ]
                });
```

**Comment by ThejaChoudary** [comment]
@mhoeger any thoughts on how we want to proceed here?

**Comment by v-anvari** [comment]
@katlimruiz , are you still facing an issue here?

**Comment by katlimruiz** [comment]
already had a workaround, by creating a winston logger and merging it with the ctx.log, however, it would be nice if we could have a better solution out of the box.

**Comment by v-anvari** [comment]
@brettsam/ @mhoeger , is this feature feasible?

**Comment by brettsam** [comment]
I'm not sure if it's feasible -- the logging system used by Functions is the .NET Core logging system, and it uses [those filtering mechanics](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#configure-logging). It's not as simple as supplying one log level -- it uses categories and even code to determine if a log should be created or not. I'm not sure that this will translate to other logging systems like the one mentioned here.

We'd need to think through it and see if there's enough benefit to warrant doing this.

We could expose the host.json directly to workers, which could then expose this to customer code. They could parse and manage this however they want, then.

**Comment by katlimruiz** [comment]
Yes I think if at least providing host info would work.

Yet I do think azure functions engine should be thought out to be more stack agnostic.

**Comment by pragnagopa** [comment]
Closing in favor of #6879
