### ISSUE TITLE
QueueTrigger function stopped firing on App service plan

### ISSUE THREAD

**Issue by grimmersnee** [Azure/azure-functions-host#4818]
We are also experiencing failed queue triggering in our .net function app, hosted using an app plan.

It seems to stop every 5 days or so, sometimes more frequent.

We have other queue driven functions in node and they don't experience this (although they are on the consumption base model.)

App insights don't show any exceptions, so this is pretty hard to troubleshoot.

#### Investigative information

- Timestamp: sometime during 21/08/2019
- Function App version (1.0 or 2.0): 2.0.12641.0 (~2)
- Function App name: prodiqfyanalytics
- Function name(s) (as appropriate): TableProcessor
- Region: Austraila southeast

#### Expected behavior

TableProcessor function is triggered by queue messages

#### Actual behavior

Every 5 or so days,  the TableProcessor function stops being triggered by queue messages.

As a result messages are not processed and expire on queue.

#### Known workarounds

Restart functions app

#### Related information 

* Programming language used  c#

<details>
<summary>Source</summary>

```csharp
[DependencyInjectionConfig(typeof(Autofac))]
    public static class TableProcessor
    {
        [FunctionName("TableProcessor")]
        public static void Execute(
            [QueueTrigger("queuename", Connection = "QUEUE_CONNECTIONSTRING")]Message message,
                [Table("analytics", Connection = "TABLE_CONNECTIONSTRING")] out EventFact tableStorageMessage,
                    [Queue("queuename2", Connection = "ANALYTICS_TABLE_CONNECTIONSTRING")] out Message sqlQueueMessage,
                        [Inject] IMapper mapper,
                            ILogger log)
        {
            var messageJson = JsonConvert.SerializeObject(message, new JsonSerializerSettings { Formatting = Formatting.Indented });

            log.LogInformation($"Message: { messageJson }");

            try
            {
                var rowKey = DateTimeOffset.Now.Ticks;

                message.RowKey = rowKey.ToString();

                var eventFact = mapper.Map<Message, EventFact>(message);

                log.LogInformation($"RowKey: {rowKey}");

                eventFact.PartitionKey = $"{message.id}_{message.Payload.Event.Timestamp.Month}_{message.Payload.Event.Timestamp.Year}";
                eventFact.Json = messageJson;

                tableStorageMessage = eventFact;

                sqlQueueMessage = message;
            }
            catch (Exception e)
            {
                log.LogError(e.Message + e.StackTrace);
                throw;
            }
        }
    }
```
</details>

**Comment by grimmersnee** [comment]
I saw the recent reply https://github.com/Azure/azure-functions-host/issues/4789, so I have tried that to see if it fixes the problem

**Comment by brettsam** [comment]
Thanks @grimmersnee -- please let us know if you see this again. I'm going to close this as (hopefully) it is handled now. But please re-open if you need to.

**Comment by fabiocav** [comment]
@brettsam did you mean to close this issue?
