### ISSUE TITLE
Update Extensions to support new Runtime Scale Monitor interfaces

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#4821]
See parent issue https://github.com/Azure/azure-functions-host/issues/4657 for details. This includes the following extensions: EventHubs, ServiceBus, CosmosDB, DurableFunctions

**Comment by jeffhollan** [comment]
@gzuber we're looking to pull this issue into an "epic" that branches into a seperate issue per trigger. do you know which triggers (if any) you've started on? If not I can add this to epic milestone and have @alexkarcher-msft start creating sub-issues and communicating relative priority (I expect based on usage)

**Comment by alexkarcher-msft** [comment]
The priority of these triggers is as follows based on usage

1. Cosmos
2. Durable
3. Service Bus
4. Event Hub

**Comment by gzuber** [comment]
@jeffhollan Yes, most of the CosmosDB trigger work is done I just need to make some fixes based on the review here: https://github.com/Azure/azure-webjobs-sdk-extensions/pull/588

**Comment by fabiocav** [comment]
Moving this into the epic milestone. Issues for the individual extensions will be created and assigned to milestones.

**Comment by gzuber** [comment]
Individual issues created. Tracking their progress:

- [ ] Service Bus
- [ ] Event Hub
- [ ] Durable
- [ ] CosmosDB ([PR](https://github.com/Azure/azure-webjobs-sdk-extensions/pull/588))

**Comment by gzuber** [comment]
All of the listed extension work has been checked in! 🎉
