### ISSUE TITLE
Investigate throughput drop

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-host#4823]
Performance tests indicates throughput drop from 145 rps to 115 rps (C# Ping) 2.0.12555.0 staring from 7/15

Need to set up private site extension and get perf snapshot

**Comment by pragnagopa** [comment]
cc @safihamid  as fyi

**Comment by safihamid** [comment]
@alrod please use private stamp without private site extension and get perfview profiles.

**Comment by alrod** [comment]
it's was bad worker
