### ISSUE TITLE
Azure functions app gets offline  python

### ISSUE THREAD

**Issue by thedoupub** [Azure/azure-functions-host#4833]
#### Investigative information

Please provide the following:

- Timestamp:  2019-08-22T17:24:25.5881276Z
- Function App version (1.0 or 2.0): 2
- Function App name: 
- Function name(s) (as appropriate): 
- Invocation ID: 93112b7923d3364fae2c3dd6034dd82e
- Region: West - Europe

#### Repro steps

Provide the steps required to reproduce the problem:

We have an app that runs through emails and we want this to happen in a CRON of every 20 seconds.

Every time we process only 1 email.
We have some models which run tensorflow and keras, or regex.
Then we do take these data that are processed and we try to create an email response.
The problem is that when we use the ML models that load tensorflow and keras packages we see that after the 3rd email that is getting a reply the server crashes on the 4th one. 
I saw that on the telemetry that the indication says "No servers online". 
I checked the logs various times. There is no error at all. There is no problem with weird timeouts ( sometimes we get such an error but it makes no sense since it is there to just to say that 30 minutes passed, which is even more confusing because the function app is supposed to run for 300 seconds amirite ? ) . There is not a problem with wrong code from the processing because we test everything first on the emulator locally and we see this only when we deploy on azure. 

My only worry is memory leak. But there is no clue as to where the memory leak is as we are in consumption plan and memory and cpu are not available in telemetry. So i do not know how to handle this problem.

When the server got offline the first time i thought it might be an azure issue. But i saw this was not happening when i was running regex. 

I need some help on that please. There is no clue as to what is causing the server to go off other than plain assumptions and testing in a black box...

#### Known workarounds

Provide a description of any known workarounds.

There is no workaround.

#### Related information 

Provide any related information 

* Programming language used Python

**Comment by brettsam** [comment]
@pragnagopa -- can you route to a python expert that can help diagnose the problem here?

**Comment by thedoupub** [comment]
Update:

We found out after some long debugging hours with some extra logging we added in our app that there is a specific call that needs to be done on Tensorflow. 

apparently you have to call the clear_session() once you are done with Tensorflow. This thing might seem simple but there were various reports that were confusing us with various versions of Tensorflow claiming that this call was not even working. What we did to find out is that we run some performance tests on multiple notebooks ( jupyter ) with instantiating and trying to decomission the resources the classes were using. Apparently we found out that if you do not call the aforementioned function then it adds some more time in processing the same context with the same model. So because we know our case is deterministic ( same input same result ) at least for now and this scenario serves us well we realized that there is a problem there. 

It would help a lot if in telemetry we could have memory and CPU consumption as it was really confusing what was happening and it took us much more time than expected. 


I will close the issue now. Obviously there was something on our side. But tooling needs more work guys. @brettsam

**Comment by thedoupub** [comment]
Hello i am back because we are having a problem of unknown nature for sure.

We started experiencing again the same issue with the app going offline yesterday. 

I did quite much of debugging, checked every page of live metrics possible, no error again.

After quite some tests we said ok lets go to the extreme solution. 

I did disable ALL of our code and left some logging.infos to print while the app is running. The only code that is there is the official MS template code for an app function. Nothing else.

The host goes off at a stable 30 minutes after it is first triggered. 

What i found is that if i open the url of my app ( note down please that this is a timertrigger app function ) it takes 2 minutes and it restarts the application. If i select the aforementioned function app or the function itself from the azure portal i experience the same. 

The only errors that i was able to find were ClientOtherError and that is on the azurestorage that is connected with the aforementioned app. 

Also something extra interesting is that both our production and staging envs are affected by the issue. It all started yesterday at 10:30 AM CEST. Note down that on production we did not touch anything. Nothing at all.

**Comment by thedoupub** [comment]
We managed to find the solution to the latest issue. 

We just deleted the function apps and we recreated them. Once we had installed the latest version of azure function core tools and we redeployed then the issue was resolved.

**Comment by brettsam** [comment]
Thanks @thedoupub. Let us know if you run into this again and we can take a deeper look.
