### ISSUE TITLE
Updated function app settings with kudu is not reflected on the azure portal

### ISSUE THREAD

**Issue by pavitrag123** [Azure/azure-functions-host#4840]
Hi,

I'm working on Azure function v2.0 and requirement is to update it's application settings. I'm able to use KUDU rest api with c# webclient and update the value. I can see value changed at Kudu url https://*.scm.azurewebsites.net/api/settings but at the Azure portal ->Function app->application settings value is not updated. Can someone please let me know if I'm missing anything

Code
`string credentials = Convert.ToBase64String(Encoding.ASCII.GetBytes(_username + ":" + _password));

_webClient.Headers[HttpRequestHeader.Authorization] = string.Format("Basic {0}", credentials);			
_webClient.Headers["If-Match"] = "*";

_webClient.Headers.Add("Content-Type", "application/json");

_webClient.UploadString("api/settings", "POST", JsonConvert.SerializeObject(settingsJson));	`

**Comment by brettsam** [comment]
@ankitkumarr -- are you the Kudu expert?

**Comment by ankitkumarr** [comment]
Unfortunately, I don't think that's possible at the moment. Kudu is hosted on the same machine as your app, and it does not have direct access to our databases to update your global Application Settings.

If you have to use REST APIs to change App Settings, you could use ARM to do that. I can post instructions for that in a little bit.

And @brettsam, definitely not the expert but I have worked a little on it so I do have a decent idea.

**Comment by iriahk89** [comment]
I also need to update app setting daily. what is the best way to do that? any reference to use ARM in C# code to automate the process? thanks in advance

**Comment by pavitrag123** [comment]
@ankitkumarr Thank you for the update. could you please give me some information about ARM to update app settings?

**Comment by ankitkumarr** [comment]
I will close this issue as the question seemed to have been answered. If you still have questions or concerns, please feel free to re-open.

**Comment by pavitrag123** [comment]
@ankitkumarr : thank you for the information. Able to update appsetting values with ARM APIs provided
