### ISSUE TITLE
Do not accept invocations until one instance of language worker is ready

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#4852]
As of now, function dispatcher buffers invocation requests until language worker process starts and initializes. If a language worker process never starts, this might lead to loss of data as invocations already started by the host but never completed.

Related Issue #4817 - addresses finishing invocations that were already started

cc @yojagad

**Comment by liliankasem** [comment]
There shouldn't be loss of data as we have retry mechanisms in place, either through host level retry (i.e. http, timers) or through built-in retries through the trigger services (i.e. service bus, blob).

[Retry documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp)
