### ISSUE TITLE
Function App /status endpoint strange behaviour

### ISSUE THREAD

**Issue by SaebAmini** [Azure/azure-functions-host#4854]
#### Is your question related to a specific version? If so, please specify:

Function Apps V2

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 

C#

#### Question

I'm seeing some behaviour I can't explain and I couldn't find any documentation regarding it which could be something to improve.

I've added a custom Health Check endpoint to my Function App. It's basically an `[HttpTrigger]` function, which does some internal dependency check, to make sure the other functions can start up correctly.

When running this locally with Visual Studio, all is as expected. However, when I deploy everything to Azure, I'm seeing an unexpected behavior.

Every 5 ~seconds~ minutes, I'm seeing an item in my logs that says:

   > Executing HttpStatusCodeResult, setting HTTP status code 200

   With the source context being `Microsoft.AspNetCore.Mvc.StatusCodeResult` and an `EventId` of `1`.

   This only started happening after I added the HttpTrigger function, which leads me to believe this is somehow being called internally by the Azure function host?

**Comment by SaebAmini** [comment]
I'm using Seq.

Thanks for the explanation. Makes sense.

Not doing any log filtering in this environment and this is the entirety of my host.json file:

```
{
	"version": "2.0"
}
```

Something I have to confirm is, sorry, I verified it's not calling _my_ status endpoint. But it seems to be doing something similar/internal.

Not a big deal but, I guess what was really confusing for me, is that for all the other Microsoft/Host generated logs, there are either complete individual log items (e.g. `Executed blah`) or the individual ones part of a fuller story together with related log items(e.g. `Loading functions` and then `1 functions loaded` etc.). However, this one is just out of nowhere and doesn't seem to be accompanied by any related logs, even when I turn on the logging levels to Debug. Just one ` Executing HttpStatusCodeResult, setting HTTP status code 200` with no useful context about what it relates to:

![image](https://user-images.githubusercontent.com/6758734/63896220-cabced00-ca34-11e9-9297-435aa1d3f1c5.png)


Since it happens every 5 minutes consistently, it really seems like it's a healthcheck sorta thing.

**Comment by fabiocav** [comment]
As @brettsam mentioned, there are infrastructure components issuing requests to the host.

To better understand how those requests are showing up, can you share more details on how you're configuring seq?

**Comment by SaebAmini** [comment]
Thanks Fabio. I'm happy to close this issue as it turned out my initial assumption for opening it was incorrect and knowing this is an internal infrastructure healthcheck is good enough, although I believe the log message could be improved to hint at that.
