### ISSUE TITLE
ERROR: unhandled error in functions worker

### ISSUE THREAD

**Issue by t-nipha** [Azure/azure-functions-host#4857]
#### Investigative information

Please provide the following:

- Function App version (1.0 or 2.0): 2.0
- Function App name: funcapp2electricboog
- Session Id: 9b2dfb456cdd43f4b16bd61ba082d734
- Timestamp: 2019-08-28T18:29:56.861Z
- Region: Central US

#### Repro steps

Provide the steps required to reproduce the problem:

Just try to start the function app.

#### Expected behavior

Provide a description of the expected behavior.

The function app should start running and be viewable in Azure Portal.

#### Actual behavior

The function app attempts to start, but none of the function runtimes are able to start. Error message states that asyncio does not have the attribute _get_running_loop().

#### Known workarounds

Add PYTHON_VERSION variable and set to a version of Python 3.6 in Dockerfile. I would have assumed the base Python image would have handled this, but it doesn't.
```
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true \
    PYTHON_VERSION='3.6.5'
```

#### Related information 

Provide any related information 

* Programming language used: Python (running in docker image)
![msedge_UIVpRtjnoc](https://user-images.githubusercontent.com/52218808/63883245-9986e300-c988-11e9-8b14-d64446517d6d.png)

**Comment by brettsam** [comment]
@maiqbal11 -- Is `PYTHON_VERSION` required as an env var in order to run? From above:

>Add PYTHON_VERSION variable and set to a version of Python 3.6 in Dockerfile. I would have assumed the base Python image would have handled this, but it doesn't.

**Comment by maiqbal11** [comment]
It isn't required. I've been able to build custom images in the past using the following instructions: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image. @t-nipha, are you following the steps in the link above?
