### ISSUE TITLE
How to inject ILogger at constructor level

### ISSUE THREAD

**Issue by lommez** [Azure/azure-functions-host#4858]
Is possible to inject ILogger at constructor level?

I've tried to do something like this:

```
[assembly: WebJobsStartup(typeof(Startup))]

namespace HelloFunc
{
    internal class Startup : IWebJobsStartup
    {
        public void Configure(IWebJobsBuilder builder)
        {
            builder
                .Services
                .AddSettings()
                .AddLogging();
        }
    }
}
```

But didtn work.

**Comment by brettsam** [comment]
No need to call `AddLogging()`. If you request an `ILogger<T>` in your constructor, you'll get one. More long-winded answer with more links here: https://github.com/Azure/azure-functions-host/issues/2720#issuecomment-503627355.
