### ISSUE TITLE
After stopping Function App, instance with TimerTrigger is still running in background, executing code.

### ISSUE THREAD

**Issue by SimonLuckenuik** [Azure/azure-functions-host#4861]
#### Investigative information

Please provide the following:

- Timestamp: 8/29/2019, 8:38:00 AM (EST)
- Function App version (1.0 or 2.0): 2.0
- Function name(s) (as appropriate): KeepAlive
- Invocation ID: f68655ae-8d9a-44bd-bae5-3580073be660.
- Region: Central US

#### Repro steps

Provide the steps required to reproduce the problem:
1. Use repro steps of #4859
2. When done, go in the portal to the Function App and press [Stop] so that the Function App will stop and all instances will be removed.
3. Go inside Application Insights for that new Function App and reach the Live Metrics Stream section. Wait until you can see KeepAlive logs inside the server instance running.

#### Expected behavior

Provide a description of the expected behavior.
- After step 2, I would expect all functions to stop to stop executing, and all instances to stop.

#### Actual behavior

Provide a description of the actual behavior observed.
- After step 2, some code is still executing from the TimerTrigger in a remaining instance.

After stop function execution Invocation Ids (stop was done around 8:35):
- f68655ae-8d9a-44bd-bae5-3580073be660:
	- Function: KeepAlive 
	- When: 8/29/2019, 8:38:59 AM (EST)
	- WEBSITE_INSTANCE_ID: 8d5f2fbcda79bdbeac68d075d0681ea1fe93cdb6a27bb25163e4b042ec9271f5 
	- App Insights OperationId: 2e56fe8901f8f74bb8f8d94efc0a14f1

- c0d3eefa-8dcb-466a-a5cb-383e769f551b:
	- Function: KeepAlive 
	- When: 8/29/2019, 8:42:00 AM (EST)
	- WEBSITE_INSTANCE_ID: 8d5f2fbcda79bdbeac68d075d0681ea1fe93cdb6a27bb25163e4b042ec9271f5
	- App Insights OperationId: b4c52c98bc498445a4ff58e067cfa642

At around 8/29/2019, 8:42:51 AM, the instance was finally released (Host instance '8d5f2fbcda79bdbeac68d075d0681ea1' released lock lease.)

#### Known workarounds
None.

#### Related information 

Provide any related information 

* Programming language used : C#
* Links to source: https://github.com/SimonLuckenuik/azure-repro-samples/tree/master/FunctionAppReproColdStartIssue 
* Bindings used: HttpTrigger, TimerTrigger

**Comment by brettsam** [comment]
I see a STOP request issued by you at `2019-08-29T12:37:09.6897526` UTC and it stops one instance. But then another instance takes over the timer and runs for 5 minutes until it is also stopped. Then you start things back up a little while later.

I see a log in the platform logs that indicates that something went wrong during shutdown (not related to your code) and it was allowed to time out naturally. I'll follow up internally to get more details.

**Comment by fabiocav** [comment]
@brettsam is there any additional follow up required here? any additional information to share or collect?

**Comment by brettsam** [comment]
@SimonLuckenuik -- I know this is old -- but have you seen this issue again?

**Comment by SimonLuckenuik** [comment]
@brettsam I cannot confirm, I am not working anymore on the project where it was occurring.

**Comment by ThejaChoudary** [comment]
@SimonLuckenuik proceeding to close the case ,please feel free to reach out to us if you have any further queries.

**Comment by SimonLuckenuik** [comment]
It's sad to see that the problem was acknowledged, identified internally but followed-up one year later. I believe that when you have customers investing time to reporting an issue in order to enhance a paid product, the minimum is to follow-up or acknowledge the problem in a timely manner.

**Comment by ThejaChoudary** [comment]
@SimonLuckenuik Sorry for the delay,we missed it somehow to follow up will make sure not to repeat it again.
