### ISSUE TITLE
'func host start' not generating function.json file

### ISSUE THREAD

**Issue by mmchome** [Azure/azure-functions-host#4863]
I am running on windows and have installed the npm module for cli version - 2.7.1480.  I am working on http triggered c# functions. When I create a function project and a function , building it does not generate the expected configs like function.json so I am unable to run functions locally. I get an error that 0 functions where found. This is happening even on vanilla functions I create and even existing functions that I checkout locally. Everything worked fine and suddenly just stopped working.

**Comment by brettsam** [comment]
Are you using Visual Studio to build? If so, what does your project file look like?
