### ISSUE TITLE
Use %PROGRAMFILES% for pointing to different drives

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-host#4866]
Current configs are pointed to "D:\":
https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/web.InProcess.win-x64.xdt
https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/web.InProcess.win-x86.xdt

We need to generate a new zip with dotnet.exe pointed to "C:\" for Azure Stack

**Comment by jvano** [comment]
We don't need a new runtime zip, you just need to use environment variables like %ProgramFiles% and %ProgramFiles(x86)% in the xdt files that will work with Azure and Azure Stack.

@alrod can you give us an ETA for this?

**Comment by fabiocav** [comment]
Agree with @jvano . @alrod I'm moving this to sprint 59, but please let us know if you don't feel comfortable with the date.

**Comment by alrod** [comment]
We are using absolute path for cold start: 
https://github.com/Azure/azure-functions-host/issues/3505

cc: @safihamid

**Comment by safihamid** [comment]
I agree with what @jvano said, this is how it should for VMSS as well, not sure how it’s working there right now because dotnet.exe is on C: drive as well.
