### ISSUE TITLE
Support an InstanceCount metric in the metric dasboard

### ISSUE THREAD

**Issue by sandeepiiit** [Azure/azure-functions-host#4867]
#### What problem would the feature you're requesting solve? Please describe.
In the metrics tab of a function app (Platform Features -> Metrics), there is no way to see the _number of instances the app scaled to over time_. One can use the `Apply splitting` option to chart all the instances, but there doesn't seem an easy way to see the count of instances over time.

#### Describe the solution you'd like
A new metric called "InstanceCount" should appear in the Metrics column. See image below:
![image](https://user-images.githubusercontent.com/13448362/63984928-35484a00-ca82-11e9-8da7-595e9d2f2110.png)

Also see this [stackvoverflow question](https://stackoverflow.com/questions/57333406/how-can-i-monitor-number-of-instances-of-a-function-app-when-it-scales-out) from a month ago for more context.

**Comment by brettsam** [comment]
This would be nice -- or even if we could include a pre-canned view of instance count. @paulbatum -- any idea if App Service does this to show instances running at any point?

**Comment by paulbatum** [comment]
As far as I know, there is no equivalent implemented by App Service. I think all the metrics that are currently emitted are done on a per-VM level. 

I suspect the easiest way to get this information visualized is through an app insights query based on the cloud_RoleInstance column:

```
requests
| summarize dcount(cloud_RoleInstance) by bin(timestamp, 1m)
| render timechart
```
![image](https://user-images.githubusercontent.com/10663/64278587-f68f1580-cf01-11e9-8488-937bded8dc2b.png)

You can then pin this to a dashboard:
![image](https://user-images.githubusercontent.com/10663/64278779-656c6e80-cf02-11e9-85fa-1732d3cb0094.png)


Does this address your need?

**Comment by sandeepiiit** [comment]
That works for me. Thanks for the help!

**Comment by paulbatum** [comment]
Great, closing this issue as I do not think there is any work we need to do in the functions host for this scenario.
