### ISSUE TITLE
NU1202: Package Microsoft.EntityFrameworkCore 3.0.0-preview8.19405.11 is not compatible with netcoreapp2.1

### ISSUE THREAD

**Issue by adrianknight89** [Azure/azure-functions-host#4872]
I'm trying to update `Microsoft.EntityFrameworkCore` and `Microsoft.EntityFrameworkCore.SqlServer` packages to v3 from 2.2.6, but I get the following error:

`NU1202: Package Microsoft.EntityFrameworkCore 3.0.0-preview8.19405.11 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package Microsoft.EntityFrameworkCore 3.0.0-preview8.19405.11 supports: netstandard2.1 (.NETStandard,Version=v2.1)`

I see no option in VS2019 to change my target framework to .NET Standard for my functions app. Does the Functions SDK work only with .NET Core? Not sure if this issue needs to be raised with the EF team.

**Comment by brettsam** [comment]
.NET Core 3 bits will be released at a later date so updating to preview. I'm guessing that those packages need a newer version of the framework that we do not currently support. That work is in progress. https://github.com/Azure/azure-webjobs-sdk/issues/2286#issuecomment-519636632
