### ISSUE TITLE
Evaluate usage of HasStarted() in v3.x

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#4875]
With the removal of ResponseBufferingMiddleware (#4865), calls to `request.Body.Length` now throw exceptions. I've removed calls to our internal extension method `HasStarted()` and changed them to the built-in `HasStarted`. We'll need to re-evaluate if this needs to be changed.

**Comment by NickCraver** [comment]
Noticed this independently and comment brought me here - cleanup in #7966!
