### ISSUE TITLE
About Azure Function Timer Trigger Mechanism

### ISSUE THREAD

**Issue by ahmetsyildirim** [Azure/azure-functions-host#4888]
I have a timer based Azure Function (V2) developed using C#.
When I set the schedule in **function.json** using the portal, the function never gets triggered. (Actually it ignores the function.json and triggers based on the value in the **Run** method)

But if I set the schedule from the C# code  (Run method), it works without any issues.
`public static void Run([TimerTrigger("0 0 15 * * *")]TimerInfo myTimer, ILogger log)`

I would like to ask if there is a flag which tells function host to bypass the schedule in function.json and use the one in the Run method (C#)

Identifiers about my function are below:
Time of Execution: 2019-09-05T02:18:20.109
Id=36288f19-28bb-4485-816d-692a88d55df3
Region: Australia Southeast

Thanks

**Comment by fabiocav** [comment]
In pre-compiled scenarios, modifying the information in `function.json` is not supported. If you need to dynamically change the schedule value, you can place the schedule in an app setting as described here:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer#configuration
