### ISSUE TITLE
Remove nextTick workaround when Edge issue resolved

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#489]
PR #486 introduced a temp fix to set nextTick = setImmediate. This works around Edge issue https://github.com/tjanczuk/edge/issues/325. When that issue is resolved, we need to remove the workaround.

**Comment by christopheranderson** [comment]
Impact: this might make some node modules not work properly until addressed if they use nextTick

**Comment by mathewc** [comment]
The workaround we have in place for this no longer involves replacing nextTick. here is the latest: https://github.com/Azure/azure-webjobs-sdk-script/commit/0f32127767cc14012dab036c91a5fe8d37e857d9. However when the Edge issue is fixed, as before, we should be able to revert this.

**Comment by fabiocav** [comment]
We're no longer tracking this issue. Closing.
