### ISSUE TITLE
Azure Functions Blob trigger does not fire off unless i open the function app

### ISSUE THREAD

**Issue by abhishekbhatt002** [Azure/azure-functions-host#4901]
The Azure Blob function not fire off unless i open the function app.
my function App name is "FunctionApp120190905054059". 
I have setup Appinsights as well but nothing is coming over logs.

**Comment by brettsam** [comment]
Is this a Consumption Plan or App Service Plan? Are you using the latest Microsoft.Azure.WebJobs.Extensions.Storage? We had a bug around this that 3.0.8.0 has a workaround for something similar to this.

**Comment by abhishekbhatt002** [comment]
> Is this a Consumption Plan or App Service Plan? Are you using the latest Microsoft.Azure.WebJobs.Extensions.Storage? We had a bug around this that 3.0.8.0 has a workaround for something similar to this.

Hi Brettsam,

Thanks for your reply. Its Consumption plan and i am using version 3.0.8-11642.

**Comment by snerting** [comment]
I have also this problem. Use Azure Devops to deploy the function app, but must go into portal and activate the function before it work. I'm running function on .net core 3.1, and consumption plan.
My function app are using Microsoft.Azure.WebJobs.Extensions.Storage version 3.0.10

**Comment by v-anvari** [comment]
Apologies for the delay on this. We'll investigate the issue and follow up with additional questions or updates here.

**Comment by v-anvari** [comment]
@abhishekbhatt002 , @snerting, since there were few modifications made for the sync triggers in recent times, please let us know if you are still facing this issue.
