### ISSUE TITLE
"Unable to acquire singleton lock blob lease for blob" exception too frequent in the application logs when using SingletonAttribute

### ISSUE THREAD

**Issue by SimonLuckenuik** [Azure/azure-functions-host#4902]
#### Investigative information

Please provide the following:

- Timestamp: 9/5/2019, 2:02:31 PM EST
- Function App version (1.0 or 2.0): 2.0
- Function name(s) (as appropriate): CommandMessageDispatcherFunction
- Host Instance ID: edcf48c0-403f-4b0f-bd81-06ab66a93c98
- Invocation ID: f7ca74c6-6170-44f6-b118-787e2e58e8ac
- Region: Canada Central
- App Inisigthts end-to-end transaction operation ID: a0f8d8e62781844aaa8e97652be6d435

#### Repro steps

Provide the steps required to reproduce the problem:
1. Create a Function with a QueueTrigger and a Singleon
```csharp
        [FunctionName(nameof(CommandMessageDispatcherFunction))]
        [Singleton(nameof(CommandMessageDispatcherFunction))]
        public static async Task Run(
            CancellationToken ct,
            [QueueTrigger("commands", Connection = "StorageQueueConnectionString")]string jsonMsgData,
            ExecutionContext ctx,
            Microsoft.Extensions.Logging.ILogger logger)
        {
          // ...
        }
```
2. Send several thousands of messages (20K-30K(
3. Wait for it to happen. At some point, the function won't be able to acquire de lock and will just try over and over with following error: Exception while executing function: CommandMessageDispatcherFunction Unable to acquire singleton lock blob lease for blob 'cloud-role-name/FunctionNamesapce.FunctionClass.Method.CommandMessageDispatcherFunction' (timeout of 0:01:00 exceeded). 

#### Expected behavior
Lock should be owned most of the time by the first instance being started and it should never release it. Other instances should try to get it once in a while in case it's released, but that should probably not be an error showing in the logs, since this is a "normal" behavior I guess.

#### Actual behavior
App Insights log filled with TimeoutException errors.

#### Known workarounds
N/A

#### Related information 

Provide any related information 
* Programming language used : C#

**Comment by brettsam** [comment]
Is your goal to only have one of your instances processing this queue? Or only one message being processed at a time, period? Have you tried using `SingletonMode.Listener` with BatchSize of 1?

https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-how-to#singletonmodelistener

**Comment by SimonLuckenuik** [comment]
At high level, we are implementing a Queue Based Load Levelling pattern in order to control the load to a non-scalable data store (Azure SQL Database).  We have basically a few QueueTriggers which are processing data, and once they are done, they are submitting a message in a Queue to be persisted inside the data store.

The Function app has multiple functions using QueueTrigger, only one of those QueueTrigger requires load control, ideally the other triggers would just execute freely since they are not accessing that limited resource data store. 

Since the BatchSize is at the host level and not the trigger level, changing it impact other QueueTriggers that do not require the load control. We had decided that we would not change the batch size but rather have other functions "pay in wait time" for we process write to the data store. Ideally, we wanted to keep everything in the same app for simplicity reasons (we do not want to have the load control function in one app and the other queue triggers in another app).

But in the end, but issue still applies, for someone doing our approach, the lock error logs are a bit annoying considering that this is not really an error but a normal case (lock cannot be acquired because something else is using it).

**Comment by ThejaChoudary** [comment]
@brettsam any thoughts on how we want to proceed here?

**Comment by ThejaChoudary** [comment]
@SimonLuckenuik are you still facing the Issue
