### ISSUE TITLE
QueueTrigger ignores Connection attribute 

### ISSUE THREAD

**Issue by michalchecinski** [Azure/azure-functions-host#4904]
Function with QueueTrigger has option to use `Connection` parameter to provide name of app setting. It's used to get the connection string for Azure storage account from which the queues will be read. But it doesn't work for me. It always gets the queues from storage provided in the `AzureWebJobsStorage` setting.

#### Investigative information

Please provide the following:

- Timestamp: 2019-09-07
- Function App version (1.0 or 2.0): 2.0
- Function App name: n/a
- Function name(s) (as appropriate): n/a
- Invocation ID: n/a
- Region: West Europe

#### Expected behavior

When sb provide `Connection` prop Queue Trigger should look to that storage account, eg. 
```
[QueueTrigger(QueueNames.AddProduct, Connection = "Storage")]
```

#### Actual behavior

QueueTrigger looks for queue in the Azure Storage provided in the `AzureWebJobsStorage` app setting.

#### Known workarounds

Use Queues in the `AzureWebJobsStorage` storage account. But this isn't solution.

#### Related information 

Example C# function that is not triggered by queue from storage account from `Storage` connection string, but from `AzureWebJobsStorage` app setting.

<details>
<summary>Source</summary>

```csharp
[FunctionName(nameof(AddProductToIdentifyService))]
        public void AddProductToIdentifyService([QueueTrigger(QueueNames.AddProduct, Connection = "Storage")]
                                                AddProductMessage message, ILogger log)
        {
            log.LogInformation("AddProductToIdentifyService function called");
        }
```
</details>

**Comment by brettsam** [comment]
I think the issue is that "Storage" is our default string. And our logic is a little tricky -- for backwards-compat reasons, we check "AzureWebJobs" + `ConnectionName` first, then look elsewhere. https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Extensions/IConfigurationExtensions.cs#L17

If you use "MyStorage" -- does that work?
