### ISSUE TITLE
Function will not route when path contains /bin

### ISSUE THREAD

**Issue by lgaud** [Azure/azure-functions-host#4908]
I am trying to use Azure Functions to serve files for a client app which expects /bin/ to be in the URL. It seems that the routing logic is refusing to handle anything with /bin in the URL.

### Investigative information

Please provide the following:
- Function App version (1.0 or 2.0): 2.0
- Region: Canada Central

#### Repro steps

Provide the steps required to reproduce the problem:
1. Deploy a function which gets variables in the Route parameter (v2), e.g. `[HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "BinTest/{name}")]` (source below),
2. Call that function with 'bin' as the parameter

#### Expected behavior
Execute with https://FUNCTION_NAME.azurewebsites.net/api/BinTest/bin
Returns bin
This works with text other than bin, including admin (which was a problem for #2940).

#### Actual behavior
Execute with https://FUNCTION_NAME.azurewebsites.net/api/BinTest/bin 
Returns "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." No logs appear in Application Insights for the request. This seems to be a generic error with routing, e.g. #969. This also occurs when using {*variable} to get multiple segments and one of them is bin, or, if the route has /bin/ hard coded, as in Route = "BinTest/bin/{name}").

#### Related information 
<details>
<summary>Source</summary>

```csharp
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;


namespace My.Functions
{
    public static class BinTest {
        [FunctionName("BinTest")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "BinTest/{name}")] HttpRequest req,
            string name,
            ILogger log)
        {
            return new OkObjectResult(name);
        }
    }
}
```
</details>

**Comment by brettsam** [comment]
@safihamid / @mathewc -- is `bin` a restricted route?

**Comment by safihamid** [comment]
Yes I think this is an IIS default restriction. We have this in the applicationhost.config file:

 <hiddenSegments applyToWebDAV="true">
          <add segment="web.config" />
          **<add segment="bin" />**
          <add segment="App_code" />
          <add segment="App_GlobalResources" />
          <add segment="App_LocalResources" />
          <add segment="App_WebReferences" />
          <add segment="App_Data" />
          <add segment="App_Browsers" />
        </hiddenSegments>

**Comment by fabiocav** [comment]
Closing this as is not something we're currently planning on changing. 

@lgaud please let us know if the impact here is significant and we can re-evaluate.
