### ISSUE TITLE
NodeJS Code: The binding type(s) 'eventHubTrigger' are not registered. Please ensure the type is correct and the binding extension is installed

### ISSUE THREAD

**Issue by Deepak-Babu** [Azure/azure-functions-host#4909]
I'm writing function in Nodejs on VSCode, and use Extension Bundle for EventHub and ServiceBus triggers. This setup used to work before , but I'm unable to run my function app locally today. I have the following error from VSCode:

[9/9/2019 5:19:00 PM] The following 2 functions are in error:
[9/9/2019 5:19:00 PM] <fxn1>: The binding type(s) 'serviceBusTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.
[9/9/2019 5:19:00 PM] <fxn2>: The binding type(s) 'eventHubTrigger' are not registered. Please ensure the type is correct
and the binding extension is installed.

The host.Json is as follows:
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  }
}

The function.json is as follows:
{
  "bindings": [
    {
      "type": "eventHubTrigger",
      "name": "eventHubMessages",
      "direction": "in",
      "eventHubName": "<name>",
      "path": "<name>",
      "connection": "<evt hub connection>",
      "cardinality": "many",
      "consumerGroup": "local_testing"
    }
  ],
  "disabled": false
}

local.settings.json:
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "<storage>",
    "AzureWebJobsDashboard": "<>",
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "<evt hub connection>": "<connection>",
    "my_servicebus": "<connection>"
  }
}

**Comment by brettsam** [comment]
@soninaren / @mhoeger -- any ideas here?

**Comment by Deepak-Babu** [comment]
additional information:
================
Version: 1.38.0 (system setup)
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:49:13.459Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by soninaren** [comment]
@Deepak-Babu what version of core-tools are you using?

**Comment by Deepak-Babu** [comment]
Azure Functions Core Tools (2.7.1585 Commit hash: 9a2b7239b937148e3b76e6f7999798629a82134a)
Function Runtime Version: 2.0.12641.0

**Comment by Deepak-Babu** [comment]
@soninaren  I have provided the information you requested.

**Comment by soninaren** [comment]
Can you delete this folder and try again?
`C:\Users....\AppData\Local\Temp\Functions\ExtensionBundles`

**Comment by Deepak-Babu** [comment]
looks like that worked. I'll check if the function triggers and update this issue
