### ISSUE TITLE
Generate CrossGen images for Extension Bundles

### ISSUE THREAD

**Issue by safihamid** [Azure/azure-functions-host#4912]
We will need to create and load CrossGened bundles to improve cold start. We will need x86 and x64 crossgen bundles to be deployed on Widnows workers instead of the current non-crossgened bundle and Functions runtime will need to load the proper bundle based on the bitness of the process.

**Comment by fabiocav** [comment]
@soninaren can you let me know if you need this moved to a different repo?

**Comment by soninaren** [comment]
We can move this one to https://github.com/Azure/azure-functions-extension-bundles repo if there are no related host changes.

**Comment by soninaren** [comment]
This work is now complete.
