### ISSUE TITLE
Allow for custom http triggers

### ISSUE THREAD

**Issue by Alxandr** [Azure/azure-functions-host#4918]
#### What problem would the feature you're requesting solve? Please describe.
I've created a custom trigger for HTTP requests that all follow a certain format. The requests are all parsed the same way in the binding, and the return value is all handled the same way. In addition, the route is not configurable in the trigger attribute, so all the routes have the same pattern containing the same parameters. The parameter/query parsing is also done centrally. Using it looks like this:

```csharp
public async Task SuccessCallbackAsync(
    [CallbackTrigger("success")]ICallbackContext context)
{
    ....
}
```

When I initially started looking at how to implement this, it seemed really straight forward. Just create an `IRouter`, inject `IWebJobsRouter` (which is available in the DI container), and call `AddFunctionRoutes` on it. The issue is that the host clears all the routes before processing the `HttpTriggerAttribute`s:
https://github.com/Azure/azure-functions-host/blob/2986ab411cc1addd8cea77dd9e2c6ddc438bc3ae/src/WebJobs.Script.WebHost/HttpInitializationService.cs#L51

#### Describe the solution you'd like
Today I work around that by subscribing to the application started event, and then registering the route (which happens after the clear call), but this is definitely hacky. I suggest either just removing the `.Clear()` call, or providing some way to get custom attributes processed when collecting routes. Maybe have all attributes implementing an interface be collected for route generation, or something like that.

#### Describe alternatives you've considered
The only alternative I can imagine is creating a function which accepts all the callback requests, does the parsing of the request/path, and then calls the correct function given the input.

**Comment by fabiocav** [comment]
There is already a pattern for what you're trying to accomplish, which is used by extensions like Event Grid (https://github.com/Azure/azure-functions-eventgrid-extension/blob/dev/src/EventGridExtension/EventGridExtensionConfigProvider.cs)

By implementing `IAsyncConverter<HttpRequestMessage, HttpResponseMessage>` your extension will have a dedicated extension trigger route that will also not collide with any customer defined route.

**Comment by Alxandr** [comment]
That seems a bit silly though, given that there's MVC routing at the bottom of this, no? Because this way, first you have to convert the http request into a `HttpRequestMessage`, then pass it through a `converter`, and do the whole dance on your way back again. Not to mention, the APIs needed to implement this are marked with `[Obsolete("preview")]`...
