### ISSUE TITLE
Define message converters for http invoker

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#4928]
part for #4887 
- Define converter from [ScriptInvocationContext](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Description/Rpc/ScriptInvocationContext.cs) to HttpRequest

- Define converter from to HttpResponseMessage to  [ScriptInvocationResult](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Description/Rpc/ScriptInvocationResult.cs)

**Comment by fabiocav** [comment]
I'm assuming this is planned for sprint 60, so I'm moving. Please adjust if needed.
