### ISSUE TITLE
Add Python worker to host for each platform 

### ISSUE THREAD

**Issue by maiqbal11** [Azure/azure-functions-host#4935]
Currently, we do not package the Python worker with the host (inconsistent with other languages). We will need to add the workers built for Python 3.6/3.7 and different platforms/architectures. 

Also see https://github.com/Azure/azure-functions-core-tools/issues/1534, https://github.com/Azure/azure-functions-python-worker/issues/450

/cc @pragnagopa

**Comment by pragnagopa** [comment]
@maiqbal11  - can you please share proposed design for this change?
cc @divyagandhii  - incase there is any platform changes are needed for this issue. For example, if this change relies on environment variables we should make sure Antares is updated to inject right environment variables into the runtime.

**Comment by fabiocav** [comment]
Moving this out of sprint 59 since it wasn't closed on that sprint.
