### ISSUE TITLE
How to get active connections used by the function host?

### ISSUE THREAD

**Issue by Badabum** [Azure/azure-functions-host#4940]
#### Is your question related to a specific version? If so, please specify:
Function version: 2.0
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question
We are currently hitting max connections limits on the function app that does batch processing, and it's highly unclear where the leak happens. We use singleton HttpClient and reuse it across different libraries(Azure Search SDK etc) but of course, I cannot be sure there is not misconfiguration somewhere in thirdparty lib. So the main question - Is there any way to get active connections used by the host?

**Comment by AartBluestoke** [comment]
I recently had to diagnose a max connections issue:
in the azure portal - the function "diagnose and solve problems" - use "TCP"
![image](https://user-images.githubusercontent.com/1892829/65299396-b80c8280-dbb2-11e9-8579-dc9ce690974b.png)
you can get the first pass report based on the state of the connections: 
![image](https://user-images.githubusercontent.com/1892829/65299460-fdc94b00-dbb2-11e9-9d48-2b34eb25a396.png)

If you are hitting max connections, you will probably receive a report there of the function usage
 
![image](https://user-images.githubusercontent.com/1892829/65299696-e76fbf00-dbb3-11e9-89f7-ea60c85ba1bf.png)

**Comment by Badabum** [comment]
@AartBluestoke thanks, but unfortunately `consumption` plan based functions do not have this feature :(

**Comment by alrod** [comment]
@Badabum, there is no way to diagnose connections  exhaustion for consumption plan yet.
As workaround you can try to create a test app with app service plan and reproduce the issue.

Can you please share you function app name and timestamp when you experienced the issue?
https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by Badabum** [comment]
@alrod Thanks for the reply! Fortunately, I managed to find the issue, it was not the leak of connections, but incorrect `HttpClient` tasks cancellation. Btw, are there any plans on improving connections monitoring fo functions on consumption plan? It would be good to have the possibility to see the connections used at least on the single host level. Anyway, closing this issue
