### ISSUE TITLE
Support of log analytics for Linux dedicated

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-functions-host#4945]
tracking item for the Linux dedicated part of #4828

**Comment by ankitkumarr** [comment]
Moving to Triaged as this item needs (blocked on) platform level changes (mostly) and will not be part of this Functions Sprint.

**Comment by ankitkumarr** [comment]
This change cannot be completed until related platform deployment is completed. It will keep moving Sprints for tracking purpose.

**Comment by fabiocav** [comment]
Moving this back to `Triaged`. Will assign to a sprint when we're unblocked.
