### ISSUE TITLE
Support different major versions of Node.js on production Linux

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#4948]
Support different major versions of Node.js on Linux. Right now, we only support a version of Node.js v8, regardless of what the `WEBSITE_NODE_DEFAULT_VERSION` is set to.

We want to start allowing user-selected major versions (although not through this App Setting - Portal UX and tooling work is already in progress).

To do this, the Linux hosting environment (ex: LWAS) must tell the host and worker process where the desired node executable is. 

If we have different pools of workers for each major version, this is a no-op problem, because "node" will be the correct version based off of the image from placeholder app => specialization => user app.

If a given container image can switch node versions throughout its lifetime (from placeholder mode through specialization), then the hosting environment has to inject node executable path or other command (such as `nvm run 10`) for the host to read and use.

The way executable is currently targeted is through [worker.config.json](https://github.com/Azure/azure-functions-nodejs-worker/blob/dev/worker.config.json), which relies on PATH defaults.

Deadline: ANT 86
cc: @divyagandhii and @pragnagopa

**Comment by divyagandhii** [comment]
This is already done for linux consumption through the LinuxFxVersion site config. Currently we support node v8 and node v10 in all regions and we have plans to support node v12 as well soon.  To target a particular major version of node, please set linuxfxversion to 'node|<version>.0' For ex: node|8.0 or node|10.0. Soon we will also support 'node|10' or 'node|8' strings as linuxfxversion as well.
