### ISSUE TITLE
Custom logging and function app name

### ISSUE THREAD

**Issue by lciocci** [Azure/azure-functions-host#4950]
#### Is your question related to a specific version? If so, please specify:
v2
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
.net core/C#
#### Question
We're looking to migrate some applications to Azure Functions/.net core 2.2. Our existing applications use custom logging to Application Insights where we currently have the ability to log info such as the application's name (e.g. Assembly.GetEntryAssembly().FullName). Is there support for this in Azure Functions? We looked at the ExecutionContext class but that seems to have limited functionality.

**Comment by fabiocav** [comment]
@lciocci Azure Functions provides built in integration with Application Insights, logging a lot of the application details automatically for you (while allowing you to log custom metrics/entries). Have you taken a look at the document [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring)? Does that meet your requirements?

**Comment by lciocci** [comment]
We use Application Insights in our existing services to write custom log entries (Web APIs, Service Fabric apps, etc.). Retrieving and logging the currently-executing program is currently done via Assembly.GetEntryAssembly().FullName for Service Fabric/console applications or BuildManager.GetGlobalAsaxType().BaseType.Assembly.FullName  for web apps.

We're now exploring Azure Functions and the current mechanisms we use do not apply as they return WebHost (partial name) as the executing app. I recently found (earlier today) that the Azure Function App Name can be found in Environment variables, specifically WEBSITE_SITE_NAME. This may suffice for our purposes.

**Comment by fabiocav** [comment]
Indeed. The environment variables in Functions will give you information that will be relevant to what you need. Keep in mind that much of that information is automatically logged for you when you enable Application Insights. 

Closing this as answered, but let us know if you need any additional information.
