### ISSUE TITLE
Load functions that are disabled last to not block on loading

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#4963]
Functions that are disabled are still being sent to the out-of-proc language worker, even though they will not be executed.

We should not send disabled functions to be loaded, as it can affect perf of other functions unnecessarily.

(Thank you for reporting @FinVamp1 !)

**Comment by mhoeger** [comment]
Update: (per Fabio): disabled functions are still "invocable" using the portal and admin endpoints, this changes that behavior.

Instead of not loading disabled functions, we will load them last to prioritize active functions

**Comment by FinVamp1** [comment]
Thanks Marie, this customer verified that removing the disabled functions meant that the timeout stopped happening for the enabled function. It's worth noting that some of the Functions had JavaScript errors when loading them.
