### ISSUE TITLE
[Question] .NET Core 3.0 Support

### ISSUE THREAD

**Issue by DrBarnabus** [Azure/azure-functions-host#4966]
#### Is your question related to a specific version? If so, please specify:
v3?

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All):
C#

#### Question
With the full release of .NET Core 3.0 now being released, does Azure Functions support using netcoreapp3.0 in a Functions Project? I can see there is a v3 branch with changes for .NET Core 3.0 being made as recently as yesterday but is it possible at present to use 3.0 on Azure Functions now or will we need to wait for a functions host update?

**Comment by fabiocav** [comment]
@DrBarnabus we're targeting a release supporting .NET Core 3.0 soon. You can see the details here: https://github.com/Azure/app-service-announcements/issues/200
