### ISSUE TITLE
Error: Did not find any initialized language workers

### ISSUE THREAD

**Issue by szymon3** [Azure/azure-functions-host#4974]
#### Investigative information

Please provide the following:

- Timestamp: 9/23/2019, 4:56:35.164 PM
- Function App version (1.0 or 2.0): 2.0
- Invocation ID: e0a383e6-f004-4fdc-9617-02ad0da478d2
- Region: northeurope

#### Repro steps

Provide the steps required to reproduce the problem:

1. Change `WEBSITE_NODE_DEFAULT_VERSION` value to different node.js version (e.g. from 8.11.1 to 10.15.2)
2. Save changes
3. Trigger function

#### Expected behavior

Function should start using new node.js version

#### Actual behavior

Function is not starting and there's `Did not find any initialized language workers` error in logs.

| Date (UTC) | Message | Log Level |
|---|---|---|
| 2019-09-23 14:56:35.164 | Executing 'Functions.ImageResizer' (Reason='New queue message detected on '---'.', Id=e0a383e6-f004-4fdc-9617-02ad0da478d2) | Information |
| 2019-09-23 14:56:35.464 | Did not find any initialized language workers | Error |
| 2019-09-23 14:56:35.464 | Executed 'Functions.ImageResizer' (Failed, Id=e0a383e6-f004-4fdc-9617-02ad0da478d2) | Error |
| 2019-09-23 14:56:35.466 | Did not find any initialized language workers | Error |

#### Known workarounds

I'm not aware of any. Only changing back to previous version helps, but it's not a solution.

**Comment by fabiocav** [comment]
@pragnagopa / @mhoeger can you please take a look?

**Comment by maxtheman33** [comment]
I have exactly same issue in the East US region. Using ElasticPremium (EP1)  app service plan.

**Comment by maxtheman33** [comment]
setting node version to 10.14.1 for instance solves the issue but 10.15.0 works locally

**Comment by pragnagopa** [comment]
As of now latest version of node available on Azure Functions is `10.15.2`. Specifying a version that is not available in Azure will not work. To avoid this, please set appsetting `WEBSITE_NODE_DEFAULT_VERSION` to `~10`

**Comment by szymon3** [comment]
But if `10.15.2` is latest available version of node then why I can't change my node version from `8.11.1` to `10.15.2`?

**Comment by maxtheman33** [comment]
8.11.1 works
10.14.1 works
10.15.0 doesn't work 

Makes no sense.

**Comment by maxtheman33** [comment]
~10?  do we really want  node version to upgrade at will?

**Comment by mhoeger** [comment]
@maxtheman33 - ~10 will only upgrade minor versions, so by contract established by Node.js, there will be no breaking changes that affect code. We see many users developing with a different minor version before deploying, and have not seen any issues come up. We believe the benefits of having Node.js minor version updates managed are worth it (benefits being optimizing performance for specific versions of Node.js and not having to manually check what version to pin to to get the latest non-breaking updates).

**Comment by szymon3** [comment]
@pragnagopa 
I see `10.15.2` in Kudu Console. Functions are still not working. I checked that before creating this issue.
