### ISSUE TITLE
Support for .NET Core 3.0 / EF Core 3.0

### ISSUE THREAD

**Issue by gabosistvanpwc** [Azure/azure-functions-host#4975]
The latest release (2.0.12701) has the following note: "Updated to support .NET Core 2.2.7". 

**Does this mean that there is no support yet for .NET Core 3.0 ? If there isn't support for .NET Core 3.0 then can you please give an estimated release date for supporting it?** 

When deploying a function (created with the latest VS template) with references to EF Core 3.0 Nuget packages the following error is shown when trying to execute the function:

Error:

Function (XXX/Function1) Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'log' to type ILogger. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
Session Id: 7e30d56e95b64135824f864416d5d91c

Timestamp: 2019-09-25T11:17:26.676Z

The same error is thrown in the local development with the Azure Functions Core Tools.

Thank you

**Comment by espray** [comment]
https://github.com/Azure/app-service-announcements/issues/200

**Comment by fabiocav** [comment]
Thanks @espray . Yes, this is planned and the information will continue to be shared in the issue/announcement above.
