### ISSUE TITLE
Setting WEBSITE_TIME_ZONE breaks local development

### ISSUE THREAD

**Issue by SaebAmini** [Azure/azure-functions-host#4994]
### Repro steps

1. Create function app V2 in visual studio.
2. Add a function with a `TimerTrigger` that takes a Cron schedule from environment variables:
   ```
   [FunctionName("Foo")]
   public async Task Run([TimerTrigger("%CronSchedule%")]TimerInfo timerInfo)
   ```
3. Add [`WEBSITE_TIME_ZONE`](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer#ncrontab-time-zones) from the documentation to your `local.settings.json` file
   ```
   {
	"IsEncrypted": false,
	"Values": {
		"AzureWebJobsStorage": "UseDevelopmentStorage=true",
		"FUNCTIONS_WORKER_RUNTIME": "dotnet",
		"WEBSITE_TIME_ZONE": "E. Australia Standard Time",
		"CronSchedule": "0 */1 * * * *"
	}
   }
   ```

### Actual

The function fails to load correctly when you run it locally:

```
The listener for function 'Foo' was unable to start. Microsoft.WindowsAzure.Storage: Server encountered an internal error. Please try again after some time.
```

When I remove `WEBSITE_TIME_ZONE` from `local.settings.json`, the error goes away.

### Expected

Should be able to set `WEBSITE_TIME_ZONE` and debug/test the setting locally.

**Comment by TroyWitthoeft** [comment]
Does this bug still exist?   I was not able to repro it.   I doing local development TimerTrigger development using 

- VS Code 1.38.1 + Azure Functions Extension
- Azure Functions Core Tools 2.7.1948
- Function Runtime Version: 2.0.12888.0
- Azure Storage Emulator 5.10

My steps.  Launch VS Code.  Use the Azure Functions extension to `Create New Project`.  Step through the command pallet questions to create a new C# TimerTrigger function.  Launch local storage emulator.  Press debug.  So far, no errors?   Below is my entire `local.settings.json` file.   

```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",  
    "WEBSITE_TIME_ZONE": "Eastern Standard Time",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
  }
}

```

**Comment by v-bbalaiagar** [comment]
Hi @SaebAmini, Please let us know if the issue still persists.
