### ISSUE TITLE
Cannot create Function App

### ISSUE THREAD

**Issue by CentriqTraining** [Azure/azure-functions-host#5003]
My steps to reproduce....always fails for me.
Click Create a resource
Type Function App into "Search the Marketplace" textbox.
On the function App Create page, click Create button.
On the "BASICS" tab, 

-    I choose an existing Resource Group
-    I choose centriqfunc in the function app Name
-    I choose .net core in runtime stack
-    I chose both East US and Central US

On the hosting Tab.

- I choose to create a new storage account.  
-  Regardless of how many times I try, the new storage account name I type does not show in the dropdown.  But if I leave the currently randomized Storage account name in, it is the same.
- Windows os
- Consumption Plan for Plan type.

On the Monitoring Tab:

- NO to application insights

Click Review and Create

Validation fails 
"The  template deployment 'Microsoft.Web-FunctionApp-Portal-569bbb3b-acab' is not valid according to the validation procedure.  The tracking id is 5dd36329-b2a9-4e68-9995-9f73187e4b94.'  See inner errors for details" with an arrow seemingly indicating that you can see more details...but you can't.

Trying to figure this out by myself
When I searched for Function App, I saw 2 items with the same name.  I discovered I'd accidently "SAVED" the  old "Create Function App" at some point in time.  Clicked the old one (It still came up) and it worked!  I got a function created.  Unsaved it...and now I can only get to the normal one and it still fails every time with the same error.

**Comment by agruning** [comment]
Hey @CentriqTraining thanks for reporting. Are you still seeing this issue? The new function app creation experience is still in Preview, so we are actively making updates.

**Comment by CentriqTraining** [comment]
It appears not.  I didn’t actually create the resource, but it validated

**Comment by ddelella** [comment]
Why did this get closed?  I am experiencing this same issue as of today.  I cannot create any Function Apps in my Azure account.

**Comment by susingh** [comment]
I am hitting the same issue today. I was able to create the function app just a couple days ago. Some part has regressed. Please fix!

**Comment by susingh** [comment]
I was able to find a workaround this Azure portal issue by creating the resource from the Visual Studio 2017 publish dialog.

**Comment by dougmolineux** [comment]
This is still broken. I'm unable to create function apps.

**Comment by ammanifold** [comment]
Hey @dougmolineux sorry you are running into this. Can you email me a screenshot and network trace for debugging.

@mhoeger can you please reopen this issue?

**Comment by dougmolineux** [comment]
I managed to figure out the reason why mine was failing. My existing resource group already had a Linux based service, and this portal wizard must default to creating a Function App with Windows. 

After creating a new resource group, it worked.

Hopefully, this will help someone in the future, when they come from google (like i did).

**Comment by ammanifold** [comment]
Default OS is then determined by the Runtime stack, location, and plan type. The defaults can be adjusted in the Hosting tab.

**Comment by dougmolineux** [comment]
Ah gotcha, yeah I was just clicking Create after the first step.

**Comment by FibonacciSpiral** [comment]
Yeah I'm having problems as well. Creating a new resource group doesn't seem to help at all. What's going on? Why is this broken?

**Comment by Aerdanel** [comment]
I have the same issue. Even when trying to create all new elements (resource group, storage account etc.).

**Comment by mhoeger** [comment]
@FibonacciSpiral and @Aerdanel - can you please open new issues with your specific details for us to investigate? You can link those back to this issue too. Thanks!

**Comment by HayHiTee** [comment]
Same issues

**Comment by HayHiTee** [comment]
Same issues

**Comment by mhoeger** [comment]
@HayHiTee - same guidance please, can you open a new issue with your specific details for us to investigate? It would be helpful if you can link those back to this issue too. Thanks!
