### ISSUE TITLE
Investigate options to send byte[] payload over http

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#5016]
Options:
 - Convert byte[] to base64 encoded string
       - Add new 'dataType:base64' in webjobs sdk for users to opt in to base64 encoding
- Stream invocation payload if input is binary data

**Comment by pragnagopa** [comment]
cc @mhoeger 
We also, need to investigate how to handle headers with various media types and char sets such as:
- application/octet-stream
- text/html; charset=utf-8

**Comment by anthonychu** [comment]
@pragnagopa Is this still an issue? What happens when we get a binary payload to an HTTP function?

**Comment by pragnagopa** [comment]
cc @yojagad 

If `enableForwardingHttpRequest` is `false` - binary data is sent as base64 encoded string. Users can choose to receive `byte[]` by setting `dataType` to `binary` in function.json

https://github.com/Azure/azure-functions-host/blob/1eb9589f663e293b882fa65e71c7ceabf52d1db5/src/WebJobs.Script/Workers/MessageExtensions/ScriptInvocationContextExtensions.cs#L168-L175

We can close this issue.
