### ISSUE TITLE
SignalR Extension causes startup failure

### ISSUE THREAD

**Issue by JamesRandall** [Azure/azure-functions-host#5029]
The SignalR web job extension allows you to pass it a connection string setting name however during extension discovery on startup the extension requires the presence of the default _AzureSignalRConnectionString_ setting.

Functions version: 2.0
Runtime version: 2.7.1158
Microsoft.Azure.WebJobs.Extensions.SignalR: 1.0.1
Language used: C#
Runtime: .NET Core 2.2

#### Repro steps

You can replicate this quite easily:

1. Create a new empty Function App.
2. Add v1.0.1 of Microsoft.Azure.WebJobs.Extensions.SignalR (the latest version)
3. Run the app

You will see errors in the console:

    Microsoft.Azure.SignalR.Common: Object reference not set to an instance of an object.
    Value cannot be null.

If you have functions in the app they can never run as the host never starts - it just cycles round on this error.

#### Expected Behaviour

It shouldn't check for connection strings at this point - or if it does it should use the ones discovered on SignalR functions (note: adding a SignalR function and setting the connection string setting name makes no difference).

#### Known workarounds

You have to add the setting.

**Comment by JialinXin** [comment]
Hi @JamesRandall,
Thanks for reporting the issue. We've already fixed it in PR: https://github.com/Azure/azure-functions-signalrservice-extension/pull/72. And the fix will be in the coming release 1.0.2 in a short time.

**Comment by JamesRandall** [comment]
Great - thanks!

**Comment by g2mula** [comment]
> #### Known workarounds
> You have to add the setting.

@JamesRandall 
What setting is this?
How do you add it? (local.settings.json?)
What name do you give it?
