### ISSUE TITLE
Azure function not processing message in queue

### ISSUE THREAD

**Issue by CRSnyder** [Azure/azure-functions-host#5043]
- Timestamp:  2019-10-07T18:47:23.193
- Function App version (1.0 or 2.0): 1.0
- Function App name: 
- Function name(s) (as appropriate): 
- Invocation ID: 92ac4a87-81c8-446b-bc7a-b2ad7f6165a6
- Region: North Central US

#### Repro steps

queue trigger is not processing messages in the queue.

#### Expected behavior

trigger should run when there are messages in the queue

#### Known workarounds

Restarting the function makes it run for a while but it stops after less than a day.

**Comment by CRSnyder** [comment]
Do you need anything else from us to address this?  According to azure, the trigger last ran on 10/18 and there are almost 13k messages in the queue.  This is important to our workflow!

**Comment by SamJarmanPP** [comment]
+1 we're seeing this, we're running the runtime in a docker container on Azure kubernetes and the function stops receiving messages until the pod is restarted or recreated.

Are we able to hook up a liveness probe to anything under the hood for this? Eg the underlying streaming receiver state etc

**Comment by soninaren** [comment]
@CRSnyder  Sorry for the delay in responding to this. Are you still running into this issue?

**Comment by CRSnyder** [comment]
It's hard to say.  Right now it looks like the function has processed all the messages, so it might be resolved.  I did open a support ticket about this on October 30 and we're still in the middle of troubleshooting.  I might wait and see if I see messages pile up again.

Let me know if you're interested in the support email thread and I'll provide it.

**Comment by soninaren** [comment]
I am happy to assist in the investigation if the investigation is stuck. Closing this issue for now. Re-open the issue if you see it happen again.
