### ISSUE TITLE
Invoke functions support

### ISSUE THREAD

**Issue by IgorHalfeld** [Azure/azure-functions-host#5062]
[AWS Lambda](https://aws.amazon.com/pt/lambda/) provides another way to call them. [Invoke](https://docs.aws.amazon.com/pt_br/lambda/latest/dg/API_Invoke.html)(as it is known).
Is there a way to do this with Azure Functions or is it not yet supported?

**Comment by fabiocav** [comment]
@IgorHalfeld some work is currently in progress to expose a simpler invocation model (compared to the existing language extensibility feature.

Please follow https://github.com/Azure/azure-functions-host/issues/4887 for updates.

**Comment by IgorHalfeld** [comment]
Wow!
