### ISSUE TITLE
Add functionTimeout = -1 to host.json schema

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-host#5068]
The [host.json reference](http://json.schemastore.org/host) needs to be updated to indicate that functionTimeout now supports a value of `-1` (for folks who love to read schemas 😊).

https://github.com/MicrosoftDocs/azure-docs/issues/37952

**Comment by ankitkumarr** [comment]
Looks like it was updated -- https://github.com/Azure/Azure-Functions/pull/1251

I am not sure what the process is / when it gets updated in the docs.

@fabiocav, do you know how can we get the host.json reference to match the schema in our repository?

**Comment by brettsam** [comment]
The schema needs to be updated in the schema store. https://github.com/Azure/azure-functions-host/blob/dev/schemas/json/README.md

**Comment by pmozbert** [comment]
this is still a problem 2 years later

**Comment by ggailey777** [comment]
@pmozbert looks like this fell through the cracks. I've opened a PR against the SchemaStore repo, but I've not done this before, so let's cross our fingers 🤞

**Comment by ggailey777** [comment]
This fix was merged in the SchemaStore, so I'll assume it's now fixed.
