### ISSUE TITLE
Remove references to HttpRequestMessageFeature 

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#5085]
HttpRequestMessageFeature is being used by HttpWorker. As this will be deprecated in AspNet Core 3.0 need to figure out alternative approaches

**Comment by pragnagopa** [comment]
cc @fabiocav

**Comment by brettsam** [comment]
It looks like this works via the WebApiCompatShim. Are we okay with depending on that going forward?

**Comment by pragnagopa** [comment]
cc @yojagad 
Flagging this as P1 as we should investigate alternative approaches to forwarding a HttpTrigger invocation to HttpWorker.

**Comment by yojagad** [comment]
Fixed by https://github.com/Azure/azure-functions-host/pull/6126
