### ISSUE TITLE
EventHubTrigger not working - was working earlier 

### ISSUE THREAD

**Issue by smitabajaj** [Azure/azure-functions-host#5094]
Hi team,
I have an EventHubTrigger Function developed in Azure Portal. The eventhubtrigger was being triggered earlier, however now i notice that the trigger is not working. 

The plan is a consumption plan, US East. 

The corresponding binding in function.json looks like this - 

{
      "type": "eventHubTrigger",
      "name": "events",
      "direction": "in",
      "cardinality": "many",
      "connection": "EnterpriseAnalytics-USE-EventHubNamespace_policy_1_EVENTHUB",
      "consumerGroup": "$Default",
      "eventHubName": "bomtesteventhub"
}

Request help in resolution on priority as I need to deploy soon. Can provide further information as required for investigation

**Comment by brettsam** [comment]
Do you get any errors logged with your site when it starts up?
