### ISSUE TITLE
Key Vault references inaccessible as environment variables in Python

### ISSUE THREAD

**Issue by sazarubin** [Azure/azure-functions-host#5118]
- Timestamp: 2019-10-19T10:12:28.4409266Z
- Function App version: 2.0
- Invocation ID: a713b519-6d2b-4c39-a967-934c2afd71a4
- Region: West Europe

#### Repro steps
1. Set application setting `STORAGE_ACCOUNT_KEY`* using azure portal as a keyvault reference
2. Save application settings
3. Trigger function via HTTP

*This is not the function's storage account, but another storage account that is used to serve static files for our web applications.

#### Expected behavior

Function reads application setting from `os.environ['STORAGE_ACCOUNT_KEY']` and returns 200.

#### Actual behavior

Attempt to read application setting results in KeyError and 500 status code with the following stack trace:
```
Result: Failure
Exception: KeyError: 'STORAGE_ACCOUNT_KEY'
Stack:   File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/dispatcher.py", line 309, in _handle__invocation_request
    self.__run_sync_func, invocation_id, fi.func, args)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/azure_functions_worker/dispatcher.py", line 426, in __run_sync_func
    return func(**params)
  File "/home/site/wwwroot/OnTranslationApproved/__init__.py", line 20, in main
    uploadFile(fileContent, fileName, language)
  File "/home/site/wwwroot/OnTranslationApproved/__init__.py", line 34, in uploadFile
    (account_name, account_key) = getAccountDetails('ru')
  File "/home/site/wwwroot/OnTranslationApproved/__init__.py", line 27, in getAccountDetails
    return (os.environ['STORAGE_ACCOUNT'], os.environ['STORAGE_ACCOUNT_KEY'])
  File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
```

#### Known workarounds
When storage account key is set directly in application settings it is accessible via `os.environ['STORAGE_ACCOUNT_KEY']` and function is working ok.

#### Related information 

* Key Vault reference is resolved according to status in Azure portal (green checkmark and secret details in the setting editing form)
* Application identity has full access to keyvault (Key Vault -> Access Policies)

The function is a webhook listener for localization service. It downloads the updated translations file and uploads it to blob storage.

<details>
<summary>Function source</summary>

```python
import logging
import os
import azure.functions as func
import os.path as path
import requests
from azure.storage.blob.blockblobservice import BlockBlobService

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')
    try:
        message = req.get_json()
    except ValueError:
        logging.error('Invalid request')
        return func.HttpResponse(status_code=400)
    
    fileName = message['file']
    language = message['language']
    project = message['project']
    fileContent = downloadFile(project, fileName, language)
    uploadFile(fileContent, fileName, language)
    return func.HttpResponse(status_code=200)

def getCrowdinKey():
    return os.environ['CROWDIN_KEY']

def getAccountDetails(country):
    return (os.environ['STORAGE_ACCOUNT'], os.environ['STORAGE_ACCOUNT_KEY'])

def downloadFile(project, fileName, language):
    r = requests.get(f'https://api.crowdin.com/api/project/{project}/export-file?key={getCrowdinKey()}&file={fileName}&language={language}&export_approved_only=1')
    return r.content

def uploadFile(content, fileName, language):
    (account_name, account_key) = getAccountDetails('ru')
    svc = BlockBlobService(account_name, account_key)
    [file, extension] = path.splitext(fileName)
    svc.create_blob_from_bytes('admin-frontend', f'{file}.{language}{extension}', content)
```
</details>

**Comment by ragulramj** [comment]
Facing the same issue. Cant retrieve secrets using keyvault uri configured in function app settings for python app

**Comment by balag0** [comment]
If the function app is running in Linux consumption , support for keyvault references will start deploying end of this month.

**Comment by sazarubin** [comment]
@balag0, yes function is on Linux consumption. I can't find any info about partial support in the docs on the key vault references, is it there?

**Comment by balag0** [comment]
Yes. Its noted on this page - https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references

**Comment by sazarubin** [comment]
Yeah, I see now. Thanks!
