### ISSUE TITLE
Connection issue with Azure

### ISSUE THREAD

**Issue by klogan12** [Azure/azure-functions-host#5123]
From Azure funciton , i am making a call to enque a json string to azure queue in blob storage. It works most of the time but failed once with below error. 

A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

One or more errors occurred. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)

Code:
CloudStorageAccount storageAccount = CloudStorageAccount.Parse(
                System.Environment.GetEnvironmentVariable("xyz")); 

            // Create the queue client.
            queueClient = storageAccount.CreateCloudQueueClient();

            // Retrieve a reference to a container.
            queue = queueClient.GetQueueReference(QueueName);

            // Create the queue if it doesn't already exist
            queue.CreateIfNotExists();

CloudQueueMessage message = new CloudQueueMessage(info);
            queue.AddMessage(message);

**Comment by pragnagopa** [comment]
Issue is not with azure functions as creating resources using Azure Storage queueClient are timing out. If this is a consistent problem please open an issue https://github.com/Azure/azure-storage-net.

Closing this issue. Please reopen if needed.
