### ISSUE TITLE
Problem with function scaling out

### ISSUE THREAD

**Issue by pzbyszynski** [Azure/azure-functions-host#5132]
Hi,

I have a problem with a service bus queue triggered azure functions scaling out (consumption plan). From time to time functions stop to scale, even though active message count in queue keeps increasing.

For the last few days, I had ~ 30 instances running and now I have 4 (messages count keeps increasing and from time to time I have to turn on app service-based backup function to keep up)

Please provide the following:

- Function App version (1.0 or 2.0): 2
- Invocation ID: b6c24eca-c536-44d1-9d35-20876e99ecb8
- Region: West Europe

#### Expected behavior
I would expect runtime to scale queue triggered functions to scale based on queue active messages count

#### Actual behavior
The function stops scaling and active messages count keeps increasing

**Comment by mhoeger** [comment]
Hi @pzbyszynski - really sorry for the delay in getting to this issue. Could share a more recent invocation ID? Or share your function app name either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)?
