### ISSUE TITLE
Azure function app host.json settings doesn't apply to the functions

### ISSUE THREAD

**Issue by Darktaelb** [Azure/azure-functions-host#5133]
Hi. 

I wrote two functions (QueueTrigger and TimeTrigger) and publishing them to the one Azure Function App via App Service Plan. (I'm working in visual studio.)
I have this host.json in the root:
[host.json.txt](https://github.com/Azure/azure-functions-host/files/3763041/host.json.txt)

And this .csproj:
[csproj.txt](https://github.com/Azure/azure-functions-host/files/3763031/csproj.txt)

I have Startup class with DI. Maybe it is important.
Also I tried to set '"AzureWebJobsStorage": "UseDevelopmentStorage=true"'.
I'm working with the latest version of the libs and also tried to change .net core sdk version to 2.2.

It seems that host.json file is loading by the sdk (because when I change host.json content to something wrong, for example add "kjg\1t" - it causes into parsing errors when starting the functions) but its settings don't apply to the functions. Functions still use default settings.
Here is the image with parsing errors that proves that this file was parsed by the azure functions sdk.
![image](https://user-images.githubusercontent.com/23211927/67407475-3ac49b00-f5c0-11e9-8200-6e79d241b8fa.png)

I tried to create an empty function from the empty timer trigger template. It works good. All settings are applying from host.json. But when I trying to work the same way in my functions - host.json settings don't apply as locally, as on Azure.

If it will be needed to provide more information - I'll provide.

Could someone help?

**Comment by brettsam** [comment]
Which settings aren't being applied? Do you see the logs being written out for "QueueOptions", for example? What do those settings show?
