### ISSUE TITLE
Remove any calls to Azure Files outside of wwwroot during cold start

### ISSUE THREAD

**Issue by safihamid** [Azure/azure-functions-host#5134]
I have narrowed down these calls to 3 call stacks:

1)	First call to LogFiles\Application\Functions\Host
Code is here: \git\azure-functions-host\src\WebJobs.Script\Host\ScriptHost.cs Line 433

        /// <summary>
        /// Set up any required directories or files.
        /// </summary>
        private void InitializeFileSystem()
        {
            FileUtility.EnsureDirectoryExists(_hostLogPath);

            if (!_environment.IsFileSystemReadOnly())
            {
                FileUtility.EnsureDirectoryExists(ScriptOptions.RootScriptPath);
            }
        }

2)	Call to LogFiles\Application\Functions\Function
Code is here: git\azure-functions-host\src\WebJobs.Script\Host\ScriptHost.cs Line 524

        private void PurgeOldLogDirectories()
        {
            try
            {
                if (!Directory.Exists(this.ScriptOptions.RootScriptPath))
                {
                    return;
                }

                // Create a lookup of all potential functions (whether they're valid or not)
                // It is important that we determine functions based on the presence of a folder,
                // not whether we've identified a valid function from that folder. This ensures
                // that we don't delete logs/secrets for functions that transition into/out of
                // invalid unparsable states.
                var functionLookup = Directory.EnumerateDirectories(ScriptOptions.RootScriptPath).ToLookup(p => Path.GetFileName(p), StringComparer.OrdinalIgnoreCase);

                string rootLogFilePath = Path.Combine(ScriptOptions.RootLogPath, "Function");
                if (!Directory.Exists(rootLogFilePath))
                {
                    return;
                }

3)	Other calls to LogFiles\Application\Functions\Host
Code is here:  git\azure-functions-host\src\WebJobs.Script\IO\AutoRecoveringFileSystemWatcher.cs Line 53

        private void InitializeWatcher()
        {
            if (!Directory.Exists(_path))
           {
                throw new DirectoryNotFoundException($"The path '{_path}' cannot be found.");
            }

+   microsoft.azure.webjobs.script.webhost!FileMonitoringService.StartAsync
+   microsoft.azure.webjobs.script.webhost!FileMonitoringService.InitializeFileWatchers
+   microsoft.azure.webjobs.script!Microsoft.Azure.WebJobs.Script.IO.AutoRecoveringFileSystemWatcher..ctor(System.String,   System.String, Boolean, System.IO.WatcherChangeTypes,   Microsoft.Extensions.Logging.ILoggerFactory)
+   microsoft.azure.webjobs.script!AutoRecoveringFileSystemWatcher.InitializeWatcher
+   system.io.filesystem!Directory.Exists

**Comment by safihamid** [comment]
@brettsam @fabiocav any plans to add this to an incoming sprint?

**Comment by brettsam** [comment]
We haven't discussed it but we can for the next sprint. @ankitkumarr -- I know you were looking to take more items, maybe you could start getting familiar with this one?

**Comment by ankitkumarr** [comment]
Looks like `PurgeOldLogDirectories` https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Host/ScriptHost.cs#L530 only runs in the background and shouldn't have an impact.

**Comment by safihamid** [comment]
Let's delay it by 5 seconds so it doesn't do it during cold start. even if background everything runs on one core and will have impact on cold start.

**Comment by ankitkumarr** [comment]
Right, that makes sense. Thanks!
