### ISSUE TITLE
Functions v2 and v3 fails on CloudQueueMessage triggers

### ISSUE THREAD

**Issue by msft-mw** [Azure/azure-functions-host#5143]
Attached a small repro project.

**Language**: C#, netcoreapp3.0 / netcoreapp2.2
**Package versions**:
- Microsoft.Azure.WebJobs.Extensions.Storage - 3.0.10
- Microsoft.NET.Sdk.Functions - 1.0.30-beta2 / 1.0.29
- Microsoft.Azure.WebJobs.Extensions.EventHubs - 4.0.1

A function referencing the Storage extension and the EventHubs extension triggers on new queue messages, but immediately throws an exception that the message content is not JSON:
```
System.Private.CoreLib: Exception while executing function: Function1. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'myQueueItem'. Microsoft.Azure.WebJobs.Extensions.Storage: Binding parameters to complex objects (such as 'CloudQueueMessage') uses Json.NET serialization.
1. Bind the parameter type as 'string' instead of 'CloudQueueMessage' to get the raw values and avoid JSON deserialization, or
2. Change the queue payload to be valid json. The JSON parser failed: Unexpected character encountered while parsing value: a. Path '', line 0, position 0.
```

Making the body valid JSON still fails (test content: `{"yo": "blah"}`)

```
System.Private.CoreLib: Exception while executing function: Function1. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'myQueueItem'. System.Private.CoreLib: String reference not set to an instance of a String. (Parameter 's')
```

The specific trigger signature is: `public static void Run([QueueTrigger("myqueue", Connection = "queue-connection")]CloudQueueMessage myQueueItem, ILogger log)`

Converting to a string instead of the `CloudQueueMessage` does succeed.
[tinyrepro.zip](https://github.com/Azure/azure-functions-host/files/3765441/tinyrepro.zip)

**Comment by msft-mw** [comment]
Edited the title because I was just able to repro this on functions v2 using the 1.0.29 SDK

**Comment by rdmagm062699** [comment]
@msft-mw What was your solution here?
