### ISSUE TITLE
Current directory of Function app is D:\Program Files (x86)\SiteExtensions\Functions\2.0.12808\64bit for 64bit apps instead of it's wwwroot folder directory

### ISSUE THREAD

**Issue by metu** [Azure/azure-functions-host#5148]
#### Investigative information

Please provide the following:

- Timestamp: 2019-10-25T05:17:06.202 
- Function App version (1.0 or 2.0): 2.0 (x64)
- Function App name: FA-DTPW-ITIH-ImageAnalysisObjectDetection
- Function name(s) (as appropriate): ProcessImage
- Invocation ID: 
- Region: South Africa North

#### Repro steps

Create a function app aimed at 64bit architecture.
Configure the function app in the portal to 64bit.
Try and perform a find on a file that should be in your wwwroot folder i.e. `File.Exists("sometextfile.txt")`.

#### Expected behavior

`File.Exists("sometextfile.txt")` should return true if the file `sometextfile.txt` exists in your wwwroot folder.

#### Actual behavior

`File.Exists("sometextfile.txt")` returns false because `Directory.GetCurrentDirectory()` would return `D:\Program Files (x86)\SiteExtensions\Functions\2.0.12808\64bit` instead of `D:\home\site\wwwroot\`

#### Known workarounds

Use an explicit reference to the wwwroot folder to locate your files. This hardcoded environment specific file reference would break on different environments.

**Comment by istoff** [comment]
Hi Matthew,

Are you certain you are using the correct NameSpace to locate the file?  Is it not possible you should be using an something other than System.IO.File??  Also, during your debug, can you inspect the contents of both the File and Directory objects to see if it is giving you the wrong context?

**Comment by metu** [comment]
Hi @istoff the way I figured that this must be a bug is that for a conventional web app I would expect Directory.GetCurrentDirectory() to give me the working directory of the website. However you could be onto something because maybe I should then be using Path.GetCurrentDirectory instead.

The issue I'm having though is that the relative path I use locally which is just the file name doesn't work in the cloud. For me that implies that Path.GetCurrentDirectory does not contain the same files locally that what is does in the cloud. And I've made 100% certain that my build artefact looks exactly the same as my output build folder of when I run locally.

Maybe I'm completely off with how I should be doing things.

I'll debug with Path.GetCurrentDirectory in a moment and see what it yields in the cloud.

**Comment by metu** [comment]
This definitely indicates that I should NOT use Directory.GetCurrentDirectory. https://stackoverflow.com/questions/15653921/get-current-folder-path

However I only used it to try and debug my issue. In my project I'm using a 3rd party library that requires a config file. I simply pass the name of the config file to the class and make sure that the config file is in the wokring directory of the built app which would be in wwwroot.

I'm not certain how the 3rd party library references the file though.
