### ISSUE TITLE
Trigger sync should not run if there were file system failures

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#5151]
Had a customer case come up where a transient file system failure resulted in the function app loading up without any functions. Background trigger sync then ran, and deleted all the trigger metadata from the system (because it thought there were not functions). This caused the scale controller to stop monitoring the app.

If the functions host is going to perform a trigger payload update, we need to be very confident that there are no current filesystem issues. Here is one of the errors that were thrown when the app came up with a bad filesystem:

```
System.IO.IOException : The network path was not found : 'D:\home\LogFiles\Application\Functions\Host'
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at System.IO.Abstractions.DirectoryWrapper.CreateDirectory(String path)
   at Microsoft.Azure.WebJobs.Script.FileUtility.EnsureDirectoryExists(String path) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Extensions\FileUtility.cs : 38
   at Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeFileSystem() at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 433
   at Microsoft.Azure.WebJobs.Script.ScriptHost.PreInitialize() at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 425
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeAsync() at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 256
```

**Comment by paulbatum** [comment]
There are platform improvements planned that should prevent the application from running at all when it enters this bad file system state. However as a shorter term fix and more defense in depth, the runtime can also check for the presence of this file:
`"D:\home\site\wwwroot\FAILED TO INITIALIZE RUN FROM PACKAGE.txt"`

**Comment by paulbatum** [comment]
Did some more research - I think it makes sense to crash the runtime when we detect this condition. The platform has rapid fail protection (will limit how many process starts are attempted), and run-from-zip is retried on each process start. So I think crashing maximizes our chances of recovery, without much risk of excessive log spamming.

**Comment by paulbatum** [comment]
One interesting scenario that might be worth testing with this fix in place is a run from package blob SAS that is invalid for the first 5 minutes of deployment (I believe you can set a start/end time on the SAS). If the system repeatedly crashes until the SAS is valid and only performs a background trigger sync once the filesystem is in a valid state, then that will prove this fix is working as expected.

**Comment by TynThordin** [comment]
Is this in production? 
We have many issues with ServiceBus Trigger functions that stops consuming messages past couple of weeks, because of the errors mentioned in this issue.

**Comment by paulbatum** [comment]
Not in production yet. The fix was merged yesterday. Should be deployed globally in 2-3 weeks.

**Comment by petermichael69** [comment]
We also face this issue on regular basis.
Please let me know how to see / get notified when the assumed fix hits the productive environment. Thx
