### ISSUE TITLE
Long Http call apparently fails silently

### ISSUE THREAD

**Issue by christian-vorhemus** [Azure/azure-functions-host#5158]
I've written an Azure Function in C# that pulls messages from a Service Bus Queue, sends a HTTP request to a webservice and writes the results to another service. The problem: The webservice is a legacy system and takes some time until it sends data back (7-8 minutes). It only works synchronously which means, it requires the calling service to keep the HTTP connection alive until the response comes back.

I've read there is a 230 seconds limit for idle HTTP connections in Azure App Service (I guess the same applies to Azure Function?). If so, I would expect that the HttpClient throws an exception once this timeout occurs. I've wrapped the client in a try/catch block to get the exception, the relevant part of the code looks like this:

```csharp
[FunctionName("Worker")]
public static void Run([ServiceBusTrigger("defaultqueue", Connection = "ServiceBusConnectionString")]string queueMessage, ILogger log)
{
    var client = new HttpClient()
    {
        Timeout = TimeSpan.FromMinutes(10)
    };
    var content = new MultipartFormDataContent();
    // Add some content here
    try
    {
        log.LogInformation("Call started");
        HttpResponseMessage response = client.PostAsync("http://legacyservice.com/web/...", content).Result;
        log.LogInformation("Success");
    }
    catch (Exception e)
    {
        log.LogError(e.Message);
    }
 ...
}
```

When I run this function locally, I get a HTTP 200 as response after 7 minutes. However, when I run this function on Azure, I see the following log:

```
2019-10-27T10:43:32.587 [Information] Call started
2019-10-27T10:45:19  No new trace in the past 1 min(s).
2019-10-27T10:46:19  No new trace in the past 2 min(s).
2019-10-27T10:47:19  No new trace in the past 3 min(s).
2019-10-27T10:48:19  No new trace in the past 4 min(s).
2019-10-27T10:49:19  No new trace in the past 5 min(s).
2019-10-27T10:50:19  No new trace in the past 6 min(s).
2019-10-27T10:51:19  No new trace in the past 7 min(s).
2019-10-27T10:52:19  No new trace in the past 8 min(s).
2019-10-27T10:53:19  No new trace in the past 9 min(s)
2019-10-27T10:54:19  No new trace in the past 10 min(s)
...
```

My expectation is, that I would see an error in the logs after the 230 seconds timeout. But as you see, nothing happens. 

Some questions arise here:
1) Does the 230 seconds timeout also apply to Azure Functions? Does the function host pass this exception up to my code? If yes, how can I get it? If no, how should I know what's going on?
2) What Azure services can I use to perform HTTP requests that take a long time without running into platform timeout limits?

**Comment by brettsam** [comment]
Incoming Http connections cannot take longer than 230 seconds, but I don't believe there are restrictions on outgoing requests. Do you have evidence that the request returned from the service you are calling (are there logs on that end)?

Also -- you should be able to use async here, and I would highly recommend it. It's possible you're blocking threads with the call to `.Result` and that is causing problems.

**Comment by christian-vorhemus** [comment]
Hello Brett, thank's for your response! Yes, the service is sending back data. I've changed the code to run asynchronously but still no success. I've sent you the full code sample, let me know if you find time to look into it.

**Comment by ThejaChoudary** [comment]
@christian-vorhemus Apologies for the late reply
Is this something your still experiencing with the latest version of Azure .

Thanks for the Patience!

in CC: @brettsam
