### ISSUE TITLE
Default collection serialization behavior in v3

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-functions-host#5165]
Is there an update on a fix for this or a pull request that is in progress at least? This workaround doesn't work with .net core 3.0. You get an error stating a provider is null on startup. Seems that something else needs to be defined in order for this to be injected as a workaround.

`Could not load type 'Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.MvcJsonMvcOptionsSetup' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Value cannot be null. (Parameter 'provider')`

_Originally posted by @zpittmansf in https://github.com/Azure/azure-functions-host/issues/3370#issuecomment-545519209_

**Comment by brettsam** [comment]
@fabiocav -- need more context on this one. What settings are we trying to support and why doesn't this work in v2 today? Do we just never register any options and the default just doesn't work?

**Comment by brettsam** [comment]
Oh I think I get it -- because `IConfigureOptions<MvcOptions>` isn't an unknown service, our resolver doesn't look into the WebHost to check for setups. So it just uses the one we register in the Http extension, which means it skips all the default Json formatters.

**Comment by fabiocav** [comment]
Correct

**Comment by brettsam** [comment]
So I guess the question -- should the resolver be combining JobHost services with WebHost services if someone asks for an IEnumerable<Service> from within the JobHost? My thinking is yes, but I'm not sure if that was our original intention. If we want that to happen, v3 is a good place for it (and if it's in compat mode, this won't happen).

If not, this OptionsSetup is now internal so it looks like we'd need to either call .AddMvc().AddNewtonsoftJson() in the JobHost, or copy the service setup ourselves and call it directly. Both of those seem less-than-ideal.

**Comment by brettsam** [comment]
We discussed in person. Opening up the IEnumerable<> services like that could be tricky. Instead, we're going to try to create our own IMvcBuilder, passing our ServiceCollection, so we can call AddNewtonsoftJson on the JobHost and register these services without registering all of Mvc.
