### ISSUE TITLE
Listener errors should have function name in system logs

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#5171]
Had a customer case with the following error:

`The listener for function 'Functions.foo' was unable to start.`

The function name column was not populated. Our detector tooling was unable to show these function specific errors because the column is not populated.

Observed this behavior on host version `2.0.12808.0`.

**Comment by paulbatum** [comment]
Behavior still happening in `2.0.12858.0`. e.g. found system logs with no function name with summary 
`The listener for function 'SendPhone' was unable to start.`

**Comment by fabiocav** [comment]
@kashimiz this was still assigned to sprint 76. Was this addressed, or should I move it?

**Comment by fabiocav** [comment]
Work currently in progress, moving to sprint 96.

**Comment by sidkri** [comment]
Once this is done, we should identify Detectors that can benefit from the Function name column having a valid value.
