### ISSUE TITLE
System.Data.SqlClient cannot be used with Functions v3

### ISSUE THREAD

**Issue by NickDarvey** [Azure/azure-functions-host#5191]
#### Repro steps

Use Azure Functions v3-preview and try to use System.Data.SqlClient (tested on versions >= 4.5.1).

See this [repro repo](https://github.com/NickDarvey/sqlclient-and-functions).

#### Expected behavior

Connects to database and logs `Plz`.

#### Actual behavior

Throws PlatformNotSupportedException: 
`System.PlatformNotSupportedException: 'System.Data.SqlClient is not supported on this platform.'`

#### Known workarounds
Using v2 might work for some people, [however you are limited to version 4.5.1 only](https://github.com/Azure/azure-functions-host/issues/3903#issuecomment-548207876).

I am using libraries which depend on System.Text.Json [which cannot be used in v2](https://github.com/Azure/azure-functions-host/issues/5031), so **I have no workarounds**.

#### Related information 

* TargetFramework netcoreapp2.1
* AzureFunctionsVersion v3-preview
* Microsoft.NET.Sdk.Functions 1.0.30-beta2
* System.Data.SqlClient 4.5.1
* Azure Functions Core Tools 3.0.1740 (Commit hash: 0b841ce061d005a05af8bb57a341989788266298)
* Function Runtime Version 3.0.12785.0

**Comment by erick2red** [comment]
Is there any updates here?

**Comment by jamyspex** [comment]
Having similar problem with System.Data.OleDb 4.7.0-preview3.19551.4 using TargetFramework: .netcoreapp3.0.

**Comment by brettsam** [comment]
This should now be fixed. See: https://github.com/Azure/Azure-Functions/issues/1370#issuecomment-555714734
