### ISSUE TITLE
X-Forwarded-Proto overwrites the scheme of HTTP triggers

### ISSUE THREAD

**Issue by NickDarvey** [Azure/azure-functions-host#5198]
#### Repro steps
Call a HTTP-triggered function with the HTTP header:
`X-Forwarded-Proto: https,https`

#### Expected behavior
Calls function.

#### Actual behavior
ArgumentException from System.Private.Uri: `Invalid URI: The URI scheme is not valid.`

#### Known workarounds
None that I'm aware of. In my case, I don't have control of the client that is calling my function.

#### Related information 
I walked through the call stack and found the `HttpContext`'s `Request` was having its `Scheme` changed by `AppServiceHeaderFixupMiddleware`. Is there a way to opt out of this?
You can see the [offending code here](
https://github.com/Azure/azure-functions-host/blob/f9540d6aaafc56ecd3d8d045edfc159a85ea9ba1/src/WebJobs.Script.WebHost/Middleware/AppServiceHeaderFixupMiddleware.cs#L32).

I believe it's a valid header. Here's an appeal to authority anyway:

> **Nick Craver @Nick_Craver 10:57 AM · Apr 15, 2018**
> If you see this...
> 
> if (headers["X-Forwarded-Proto"] == "https") { ... }
> 
> ...it's wrong. For example, these are all valid headers:
> X-Forwarded-Proto: https, https
> X-Forwarded-Proto: http, https
> X-Forwarded-Proto: https, http
> It's <client>, <proxy1>, <proxy2>, etc.

https://twitter.com/nick_craver/status/985321287194210304

```
Azure Functions Core Tools (2.7.1846 Commit hash: 458c671341fda1c52bd46e1aa8943cb26e467830)
Function Runtime Version: 2.0.12858.0

<TargetFramework>netcoreapp2.1</TargetFramework>
<AzureFunctionsVersion>v2</AzureFunctionsVersion>
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.30-beta2" />
```

**Comment by brettsam** [comment]
@ahmelsayed -- looks like you added this middleware, so you have more context than me. It appears that it needs to be able to handle multiple schemes (and choose the first?)

**Comment by ahmelsayed** [comment]
send #5242
