### ISSUE TITLE
How to debug startup errors

### ISSUE THREAD

**Issue by bragma** [Azure/azure-functions-host#5206]
Hi,
I've been in a situation where a C# function starts correctly when hosted locally, but fails to start when deployed in a function app (runtime could not start). What's the suggested way to debug or at least see any thrown exception for code in the startup class? The azure portal just reports "function runtime is unable to start". Is it possible to investigate the root cause of this generic error?

 Thanks!

**Comment by brettsam** [comment]
The logs were not written to App Insights? If it happens early enough during startup, they may not be (we may not have been able to load your App Insights details).

Another option is to enable all file logs via the `fileLoggingMode` setting (https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#logging) and then look for those logs in kudu (via _site_.scm.azurewebsites.net/DebugConsole) under `D:\home\LogFiles\application\functions\Host`. 

Can you give that a try and see if it gives you any more insights? If not, we can try to dig in and we can use this issue as a case study for where we need to add more logging.

**Comment by bragma** [comment]
@brettsam thanks for answering. I'll try again with your suggestion. Basically I am in a strange situation where I have a sample function which runs locally, but when deployed to function apps hosting it just does not run and shows "function runtime is unable to start". I've reduced the problem to a single line: adding Mvc to startup services. What's strange is that I've shared the project on github and with the help oh some other people found out that:

1. I cannot deploy it in West Europe (function runtime is unable to start)
2. I can deploy it in Central US and it works
3. Some people have compiled my project and been able to deploy in West Europe too.

I am puzzled.

**Comment by brettsam** [comment]
That is interesting.... I also wouldn't think that calling `AddMvcCore()` would break things, and that if it did, they'd break *everywhere*, not just in production (and certainly not just in one region). If you're not able to find any logs from my suggestion above, let me know and we can get some more details from you.

**Comment by MyEidos** [comment]
Same issue. 
Error during startup and no logs in App Insights or in LogFiles\application\functions\Host

My host.json 

```
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingExcludedTypes": "Request",
            "samplingSettings": {
                "isEnabled": true
            }
        }
    }
}
```

**Comment by vaibhavramdasi** [comment]
I'm getting following error in portal. But I don't see anything in either appinsights or LogFiles. It works locally just fine.

Error:

The function runtime is unable to start. Microsoft.EntityFrameworkCore: Could not load file or assembly 'System.Interactive.Async, Version=3.2.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The system cannot find the file specified.
Session Id: 8d1c41a7416043f29e0fd4564721261f

Timestamp: 2020-06-10T15:30:32.966Z

**Comment by brettsam** [comment]
@vaibhavramdasi -- I'm investigating this right now. Can you share your csproj file? 

For mitigation -- assuming you're on v3 -- set FUNCTIONS_EXTENSION_VERSION to 3.0.13353.0 in your app settings. This will force you to take the previous version.

**Comment by vaibhavramdasi** [comment]
Thanks @brettsam . This is my csproj file. I have removed some of the project references. Most of those have EFCore 2.2.6 as package refs. I'm deploying to x64 bit FuncApp on S1 tier ASP with VNet integration enabled. 
```

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <LangVersion>7.1</LangVersion>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.16" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.6" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="3.1.3" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.6" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.ServiceModel" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>
  <Target Name="CopySPSM" BeforeTargets="Build">
    <Copy SourceFiles="$(USERPROFILE)\.nuget\packages\system.private.servicemodel\4.5.3\runtimes\win\lib\netstandard2.0\System.Private.ServiceModel.dll" DestinationFolder="$(OutputPath)\bin" />
  </Target>
</Project>
```

**Comment by brettsam** [comment]
Thanks! We know the issue and it's indeed a bug. If you want to run on the latest version, you can add `<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>` to your project file and re-deploy, then set your FUNCTIONS_EXTENSION_VERSION back to ~3. That will include the file you need and things should run as before.

We're investigating a hotfix for this now.

**Comment by vaibhavramdasi** [comment]
After reverting to prior version now getting this : 
Host instance '53281fd3c43bc30f5c8e82250a9485df' failed to acquire host lock lease: Microsoft.WindowsAzure.Storage: An attempt was made to access a socket in a way forbidden by its access permissions. System.Net.Http: An attempt was made to access a socket in a way forbidden by its access permissions. System.Private.CoreLib: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by vaibhavramdasi** [comment]
> After reverting to prior version now getting this :
> Host instance '53281fd3c43bc30f5c8e82250a9485df' failed to acquire host lock lease: Microsoft.WindowsAzure.Storage: An attempt was made to access a socket in a way forbidden by its access permissions. System.Net.Http: An attempt was made to access a socket in a way forbidden by its access permissions. System.Private.CoreLib: An attempt was made to access a socket in a way forbidden by its access permissions.

This is resolved now. There was appsettings.json containing ConnectionStrings:AzureWebJobsStorage pointing to local. It seems that ConnectionStrings:AzureWebJobsStorage has higher precedence than only AzureWebJobsStorage  

https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#local-address-requests

**Comment by vaibhavramdasi** [comment]
@brettsam Has the patch been applied? Is it safe to go back to ~3?

**Comment by ChristopherL-STCU** [comment]
I have found it very challenging to determine the cause and the details of errors which occur during Startup when the Function App is running on Azure. I'm not finding the information anywhere. It would be great if logging could be supported in Startup so that this information could be captured. Perhaps I haven't found the right piece of documentation and so I'm missing an important piece of information to aid me in this. But as of right now I usually have to resort to deploying to a separate slot and then eliminate items from Startup line by line to try to deduce the cause of the error.

**Comment by brettsam** [comment]
Note this was related to https://github.com/Azure/azure-functions-host/issues/6203, which was closed and you should be able to go to ~3 now.

For tracking the logging improvement, let's use #4705. I'll see what I can do to get that one scheduled in an upcoming milestone now that we have some concrete examples.
