### ISSUE TITLE
WEBSITE_TIME_ZONE does not appear to work

### ISSUE THREAD

**Issue by zegor** [Azure/azure-functions-host#5213]
#### Investigative information

- Timestamp: 2019-11-07 13:22:15.215
- Function App version (1.0 or 2.0): 2.0
- Invocation ID: 4da665bd-440a-4505-830e-07dfdaf6215b
- Region: Australia East

#### Repro steps

1. Set `WEBSITE_TIME_ZONE` in Function application settings (in my case, it was set to `W. Australia Standard Time`)
2. Set timer trigger to run at a certain time, specific to the above time zone - time passes, trigger does not get fired
3. As a separate test, execute HTTP trigger to print date time (using Python `datetime.datetime.now()` - prints UTC, not current time as per time zone setting in step 1

#### Expected behavior

After step 1 above, timer trigger should have fired according to the time zone. Additionally, HTTP trigger should have printed current date time within the time zone.

#### Actual behavior

As detailed in repro steps above.

#### Known workarounds

Not using `WEBSITE_TIME_ZONE` - just working in UTC time.

#### Related information 

* Programming language used: Python
* Bindings used: Timer Trigger

**Comment by brettsam** [comment]
@zegor, I'm assuming this is Linux?
@balag0 / @maiqbal11 / @divyagandhii -- any idea if there's an issue with WEBSITE_TIME_ZONE in Linux?

**Comment by yojagad** [comment]
I remember opening an issue in a private repository for adding support for WEBSITE_TIME_ZONE for linux consumption which is not supported today. Please correct me if I'm wrong.

**Comment by balag0** [comment]
Yeah. this doesn't work in Linux consumption. this is enabled by the sandbox which we don't use in linux. 
Opened an issue here to track - https://github.com/Azure/azure-functions-host/issues/5246

Since the fix is outside functions host no specific ETA at this time for this to be fixed/deployed.

**Comment by zegor** [comment]
> @zegor, I'm assuming this is Linux?

Correct. I was following the below Microsoft documentation, so ideally any issues for this would be noted there as I was just banging my head against the wall wondering why it's not working.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer

**Comment by brettsam** [comment]
I've just created a PR to add a note to the doc above (https://github.com/MicrosoftDocs/azure-docs/pull/42816) . 

Thanks for pointing this out @zegor. I'll close this issue when the doc update is merged, and we'll track the actual work for WEBSITE_TIME_ZONE support in #5246.
