### ISSUE TITLE
Permissions for Roslyn / reflection in user code

### ISSUE THREAD

**Issue by TehWardy** [Azure/azure-functions-host#5223]
I've hit some issues with using Roslyns Scripting API in an azure function. 
due to the complex nature of the code, I have the function supplied with a blob of json in the request that tells the function what to build from a set of predefined blocks essentially (think workflow engine).

To help this along I built this utility class that wraps up roslyn ...

```
internal class ScriptRunner : IScriptRunner
{
    static Assembly[] references;

    static ScriptRunner()
    {
        // some of the stack might not have been loaded, lets make sure we load everything so we can give a complete response
        // first grab what's loaded
        var loadedAlready = AppDomain.CurrentDomain
                .GetAssemblies()
                .Where(a => !a.IsDynamic)
                .ToList();

        // then grab the bin directory
        var binDir = Assembly.GetExecutingAssembly().CodeBase
            .Replace(Assembly.GetExecutingAssembly().CodeBase.Split('/').Last(), "")
            .Replace("file:///", "")
            .Replace("/", "\\");

        // from the bin, grab our core dll files
        var stackDlls = Directory.GetFiles(binDir)
            .Select(i => i.ToLowerInvariant())
            .Where(f => f.EndsWith("dll"))
            .ToList();

        // load the missing ones
        stackDlls.Where(assemblyPath => loadedAlready.All(a => a.CodeBase.ToLowerInvariant() != assemblyPath.ToLowerInvariant()))
            .ForEach(assemblyPath => loadedAlready.Add(Assembly.LoadFile(assemblyPath)));

        references = loadedAlready.ToArray();
    }

    public async Task<T> Run<T>(string code, string[] imports, object args)
    {
        try
        {
            var options = ScriptOptions.Default
                .AddReferences(references)
                .WithImports(imports);

            return await CSharpScript.EvaluateAsync<T>(code, options, args);
        }
        catch (CompilationErrorException ex)
        {
            throw new Exception($"Compilation failed:\n{ex.Message}\n{string.Join(Environment.NewLine, ex.Diagnostics)}\nScript:\n{{\n{code}\n}}");
        }
    }
}
```

... My problem is that I get it listing out a ton of diagnostic lines in a compilation exception that rad like this ...

> error CS0009: Metadata file 'D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App\2.2.7\Microsoft.CodeAnalysis.Razor.dll' could not be opened -- Access to the path is denied.
> error CS0009: Metadata file 'D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App\2.2.7\Microsoft.CodeAnalysis.Razor.dll' could not be opened -- Access to the path is denied.

I don't need write access to anyhting I just need to be able to reference "unknown until runtime" various parts of the framework.

this code runs fine locally of course, any suggestions?

Update:

I also notice that this applies to assemblies I pushed as part of the function itself in the web root ...

> error CS0009: Metadata file 'D:\home\site\wwwroot\bin\Core.Objects.dll' could not be opened -- Access to the path is denied.

... this makes me think there's a more general "read permission" or something I need to configure somehow, then I could do a self contianed deploy to include everything if need be to avoid needing to go anywhere near anything in a M$ shared location.

**Comment by brettsam** [comment]
@fabiocav -- any idea why you couldn't load these?

**Comment by TehWardy** [comment]
Ok so this took me some time to dig through and it turns out that running the code above adds (or attempts to) literally every part of .Net it can get it's hands on within the functions host & dependent framework directories.

The net result is that Roslyn doesn't like this and my fix was to examine my script, figure out what was actually needed and then generate a subset of assemblies that I would then in turn give to roslyn to use as references.

To be honest, this is definitely the better way to go but I figured there's no reason Roslyn shouldn't be able to (i guess) load everything if it needed to right?

It's like there's a built in reference count limit or something.

**Comment by mhoeger** [comment]
@TehWardy - closing as resolved, but please ping back if you'd like us to take a deeper look
