### ISSUE TITLE
missingmethod exception when using latest msft stackexchange in azure functions

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/azure-functions-host#5232]
more details here with sample code
https://github.com/aspnet/Extensions/issues/2611

**Comment by brettsam** [comment]
It looks like the https://www.nuget.org/packages/Microsoft.Extensions.Caching.StackExchangeRedis brings in v3 of the DependencyInjection package. We build against 2.2, so it's not going to find it and it won't work correctly. You can try this on our v3 preview and see if it works: https://dev.to/azure/develop-azure-functions-using-net-core-3-0-gcm

**Comment by grahamehorner** [comment]
@brettsam FYI the same occurs with HttpClientFactory; any timeline with regards the (official) release of v3 ? and support in azure deployments ?

**Comment by brettsam** [comment]
Did you move the HttpClientFactory nuget reference forward to 3.0? This will occur with anything that requires .NET Core 3. If you're running on .NET Core 2 (Functions v2), it won't work.

The 3.0 schedule plan is here -- https://github.com/Azure/app-service-announcements/issues/200. If there are updates to this plan, the announcement will be made in that repo.
