### ISSUE TITLE
TelemetryInitializer is not always called

### ISSUE THREAD

**Issue by fgheysels** [Azure/azure-functions-host#5235]
I've an Azure Function which logs to Application Insights.
To make sure that all my traces to App Insights are linked to the correct Function invocation, I'm using a `TelemeteryInitializer` which sets the `Operation.Id` and `Operation.ParentId` based on the current `Activity`.

When I run the function, I notice that my traces are not 'linked' to the function request.
When I put a breakpoint in my `TelemetryInitializer`, I notice that the breakpoint gets hit.  However, when I put a breakpoint on a line of code where I call `TrackTrace`, and put a breakpoint in the `TelemetryInitializer`, I notice that the TelemeteryInitializer is not being hit.

#### Investigative information

Please provide the following:

- Timestamp: 12/11/2019 20:37:00 (UTC)
- Function App version (1.0 or 2.0): 2.0
- Function App name: fg-httplogging
- Function name(s) (as appropriate): LogTester
- Invocation ID: 46ef4ef7-899f-4a0f-a38e-8c08a903765b
- Region: weu

#### Repro steps

I've created a sample Function which demonstrates this behavior.
The sample can be found on github [here](https://github.com/fgheysels/AzureFunction-AppInsightsLogging).

The function has a simple http-trigger that accepts GET requests.  The function expects a `number` querystring parameter.  When the number is odd, the Function calls `TrackTrace` and `TrackException` and I expect that those traces are linked to the Function invocation/request in AppInsights, but that's not the case.

When the number is even, a HTTP request is made to a public endpoint.  In AppInsights, I can see that this request is logged, and tied to the function invocation.
Next to that, I'm also calling `TrackTrace` where I explicitly set the `Operation.Id` and `Operation.ParentId` and for that trace, I see in AppInsights that it is linked to the function invocation.

#### Expected behavior

I expect that a registered TelemetryRetriever is consistently called for each AppInsights log statement, and not that it is being called in some cases and in other cases not.

#### Actual behavior

TelemetryInitializer is not being called on calls to `TelemetryClient.TrackTrace` and `TelemeteryClient.TrackException`

#### Known workarounds

When I explicitly set the `TraceTelemetry` properties explicitly in code (outside a TelemetryInitializer), the traces are correctly linked to the function invocation in AppInsights.

#### Related information 

Provide any related information 

* Programming language used: C#
* Links to source: [click](https://github.com/fgheysels/AzureFunction-AppInsightsLogging/tree/master/src/HttpFunction)
* Bindings used: HttpTrigger but I also have this behaviour when using IoTHubTrigger

**Comment by brettsam** [comment]
The issue is that you're creating a second TelemetryClient in your function class. Instead, request a `TelemetryClient` in your function class constructor. That will pass you the same `TelemetryClient` that we use internally, and the one that has the initializer registered with it. That should get it running as expected.

**Comment by fgheysels** [comment]
Thanks, I didn't know it was possible to have a non-static Azure Function :)  I do wonder now if a non-static Function has some (slight) performance deficit as opposed to a static Function when the Function is under high load.  (For instance an Azure Function that is consuming an IoT Hub which contains lots of messages).

**Comment by brettsam** [comment]
There may be a slight difference, but I don't know that we've ever measured or had any perf complaints from the usage. The benefits with DI make it pretty nice (and that's how things like Controllers run in MVC, for example).
