### ISSUE TITLE
Migrate GRPC implementation to the integrated ASP.NET implementation with .NET Core 3.0

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-host#5237]
- [x] Refactor gRPC out of Webjobs.Script (https://github.com/Azure/azure-functions-host/issues/5419)
- [ ] Migrate the Webjobs.Script.Grpc implementation to use .NET Core 3.0 gRPC (https://github.com/Azure/azure-functions-host/issues/5449)

**Comment by fabiocav** [comment]
Can you please break this up into smaller issues we can use to track the work in progress?

**Comment by fabiocav** [comment]
Closing stale, completed issue.
