### ISSUE TITLE
The output does not appear with using Service Bus Queue Trigger

### ISSUE THREAD

**Issue by alvipeo** [Azure/azure-functions-host#5258]
v ~3:

I was debugging a Function which had Service Bus Queue Trigger. I start Debug and it shows that the host is started, shows "Ctrl+С" message and then never triggers the function. __Until__ I pushed Ctrl+C... and then I see the usual log messages.

**Comment by mhoeger** [comment]
@alvipeo - can you share more details on this? What was your log output? How long did you wait until messages showed up? What did your code look like?
