### ISSUE TITLE
Enforce FUNCTIONS_WORKER_RUNTIME for V3

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#5273]
- Need to update host to throw an error if FUNCTIONS_WORKER_RUNTIME is not set after specialization
- Need to introduce new constant "Custom" to allow workers that are not language bound such as HttpWorker

cc @mhoeger

**Comment by fabiocav** [comment]
This also needs to respect the backwards compatibility mode. That needs to be tracked by this issue.

**Comment by dariagrigoriu** [comment]
@pragnagopa and @mhoeger is it possible to confirm if this is already completed?

**Comment by mhoeger** [comment]
@dariagrigoriu - unfortunately no, it doesn't look like this change made the V3 mark. Since it's a breaking change now, I'm going to go ahead and close it.
