### ISSUE TITLE
ConfigurationBuilder not exposed prevents ability to bootstrap usage of KeyVault

### ISSUE THREAD

**Issue by tsharp** [Azure/azure-functions-host#5274]
Runtime Version: 2.0
Language: .NET Core

I've been trying to bootstrap KeyVault as my secrets storage for some time now without much luck aside from hacking in a static variable to do dependency injection. This seems to be a shift from the way that the traditional dependency injection mechanisms are able to work in asp.net core applications.

Ideally - one would be able to store the Storage Account and lets say, Service Bus queue config, in a KeyVault and one should be able to add a small amount of configuration to use a managed identity to access said secrets.

Currently - I have been able to bootstrap but I haven't been able inject my KeyVault settings into the Services and currently get:
```
 Microsoft.Azure.WebJobs.ServiceBus: Microsoft Azure WebJobs SDK ServiceBus connection string 'xxxxxxxx' is missing or empty.
```

**Comment by sebader** [comment]
Was there ever any progress here? I'm struggling with the same thing. I built the following, but it does not work for settings that are required in bindings, such as a connection string to Event Hub for EH-triggered functions.

````
public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var azureServiceTokenProvider = new AzureServiceTokenProvider();
            var keyVaultClient = new KeyVaultClient(
                new KeyVaultClient.AuthenticationCallback(
                    azureServiceTokenProvider.KeyVaultTokenCallback));

            builder.Services.AddSingleton<IConfiguration>((s) =>
            {
                var config = new ConfigurationBuilder()
               .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
               .AddEnvironmentVariables()
               .AddAzureKeyVault($"https://my-kv.vault.azure.net/",
                                 keyVaultClient,
                                 new DefaultKeyVaultSecretManager())
               .Build();
                return config;
            });

            Console.WriteLine("Config with KeyVault initialized");

            builder.Services.AddHttpClient();
        }
    }
````

**Comment by tsharp** [comment]
Not yet. I suspect we may have to submit a fix in order to resolve this. The behavior I noticed is that it seems to build the service provider prior probably for a bootstrapping process which puts the startup sequence and the runtime sequence happen in a different order than expected.

**Comment by phekmat** [comment]
There's some more discussion in #4464 around custom configuration and bindings, specifically https://github.com/Azure/azure-functions-host/issues/4464#issuecomment-513037126. Outside of bindings, the last comment in that thread seems to offer a solution.

There's always https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references, though I'm not a fan.

**Comment by ericsampson** [comment]
This would be great. Especially if it can include bindings. @jeffhollan any thoughts on this topic?
Not being able to use KV like we do in plain Core webapps is a real bummer.

**Comment by tsharp** [comment]
I've switched to using simple hosted services in a container; however, I'd still love for this to be an option. I dug through several Sdk's to root out where/how this could be effectively/correctly done and it seems that the base WebJobs/ScriptHost will need a bit of attention here and still may take a while longer to get it in since it spans projects.

**Comment by fabiocav** [comment]
Apologies for the late reply here. 

This capability is actually something that is being rolled out with the current Functions deployment. You can find more information in the PR [here](https://github.com/Azure/azure-functions-host/pull/5991) and in the linked issue.

Thank you for the patience!

**Comment by tsharp** [comment]
hey @fabiocav - do you know what nuget package release this will be part of or has that not been determined yet?

**Comment by fabiocav** [comment]
@tsharp this will be published as part of the .NET Extensions package https://www.nuget.org/packages/Microsoft.Azure.Functions.Extensions/
