### ISSUE TITLE
EventGridTrigger failing with "Precondition not met"

### ISSUE THREAD

**Issue by SamVanhoutte** [Azure/azure-functions-host#5276]
I have deployed an Azure function app (tested it in v2 and v3-preview in the portal) that contains several triggers, of which my EventGridTrigger is failing, when an event is retrieved on that subscription.

This is the exception, as shown in the execution logs in the Azure portal:
`2019-11-20T15:24:23.791 [Error] Executed 'TransactionEventHandler' (Failed, Id=0e45d83b-8d65-40c4-a72a-120d9fa8e5c3)
Precondition not met.`

#### Invocation information (sensitive names masked)

- Timestamp: 2019-11-20T15:24:23.791
- Function App version (1.0 or 2.0): 2.0 (also tried 3.0)
- Function App name: *****TransactionEventHandler
- Function name(s) (as appropriate): *****TransactionEventHandler
- Invocation ID: 0e45d83b-8d65-40c4-a72a-120d9fa8e5c3
- Region: West-Europe

#### Related information 

* Programming language used : csharp (netstandard 2.0)
* Bindings used : EventGrid & Http

#### Package references
* Microsoft.Azure.EventGrid v3.2.0
* Microsoft.Azure.Functions.Extensions v1.0.0
* Microsoft.Azure.WebJobs.Extensions.EventGrid v2.1.0
* Microsoft.Extensions.Logging v2.2.0 (also tried 3.0.1)
* Microsoft.NET.Sdk.Functions v1.0.29
* Microsoft.NETCore.App v2.1.0
* Newtonsoft.Json v11.0.2

<details>
<summary>Source code below</summary>

```csharp
public class TransactionEventHandler
{
    private TrxSettings _trxSettings;
    private IStockSearcher _stockSearcher;
    private ILoggerFactory _loggerFactory;

    public TransactionEventHandler(IOptions<TrxSettings> trxSettings, IStockSearcher stockSearcher, ILoggerFactory loggerFactory)
    {
        _trxSettings = trxSettings.Value;
        _stockSearcher = stockSearcher;
        _loggerFactory = loggerFactory;
    }

    [FunctionName("TransactionEventHandler")]
    public async Task Run([EventGridTrigger]EventGrid.EventGridEvent eventGridEvent, ILogger log)
    {
        Guard.For<ApplicationException>(() => eventGridEvent.EventType.Equals(typeof(StockTransactionCreatedEvent).Name));
        if (eventGridEvent.Data is TransactionItem stockTransaction)
        {
            // removed business code for brevity
        }
    }
}
```
</details>

**Comment by SamVanhoutte** [comment]
Any update on this one ?

**Comment by mhoeger** [comment]
Hi @SamVanhoutte - so sorry for the delay and thanks for the details. I'm looking through our logs and it doesn't look like I'm able to find your App's details.
Can you share your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? 

I also haven't been able to find anything around "Precondition not met" in our logs - is there a chance this is an exception message coming from your code?
