### ISSUE TITLE
Creating a Trigger Function from Portal does not work for Linux App Service plans

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-host#5283]
1. Create a new function app (node) from portal.
2. Click `+` next to Functions in portal and create a HttpTrigger function.
3. Hit run, you will see a `404` even though the function code is already there. Even if you call the HttpTrigger function from the API endpoint outside of portal, you will see a 404.

**Comment by ankitkumarr** [comment]
@divyagandhii

**Comment by paulbatum** [comment]
@ankitkumarr in the title it says timer trigger but the instructions say http trigger, is the title wrong?

**Comment by ankitkumarr** [comment]
This was fixed by https://github.com/Azure/azure-functions-host/commit/b94541ffe4e10045ffa0678149d58a10baa0ebb8

A proper fix was applied as well - https://github.com/Azure/azure-functions-host/commit/c1e62dba506302bad51800691da548c3542da484
