### ISSUE TITLE
17s http response times and recommended app size

### ISSUE THREAD

**Issue by JonyTek** [Azure/azure-functions-host#5292]
Hi team!!

I am looking to for some direction on the recommended size of a function app where it is still performant. 

Some background - I wrote a function app (microservice) which contained http, servicebus, queue and durable functions within the same app. Locally this was reasonably performant, a bit slow but I put it down to the fact I was logging to the console. Once I deployed (C# precompiled) I found that the http healthcheck endpoint was consistently taking ~17s to respond and then would fail with a `service unavailable` one in 5 calls (this endpoint did nothing but immediately respond - no db calls etc). The app contains 41 individual functions (mainly to keep supporting aggregates synced up eg `AccountEmailUpdated`). 

These response times are not acceptable for http requests, I'm not concerned about background processes like `AccountEmailUpdated as this is eventual consistency. I know functions should be kept small and figure that this is just too large. It is like I am seeing cold starts on each request, like I mentioned these response times are consistent.

Could I get some direction on this?

Thanks.

**Comment by pragnagopa** [comment]
Please share function app name (or invocationd Id and the region where function app is deployed) and the approximate time range where you saw 17secs response time.
