### ISSUE TITLE
Extensions break on Runtime v2.0.12888

### ISSUE THREAD

**Issue by TimPosey2** [Azure/azure-functions-host#5293]
Hi, 

Our functions host recently was upgraded to 2.0.12888.  This cause a break in loading our extensions necessary for our application, a compiled Functions Application in .NET Core v2.2.  To fix, we created another Azure Functions app with runtime 2.0.12858 and our apps now work perfectly fine.  Attempts to re-deploy the same code to the host with v2.0.12888 did not make a difference.  Re-starting the App didn't make a difference either.

#### Investigative information

Please provide the following:

- Timestamp: **Issue started on 11/23/2019**
- Function App version (1.0 or 2.0): **~2**
- Function App name: _(private)_
- Function name(s) (as appropriate):
- Invocation ID: **Session ID: 8e5f392834c14dfdbd374ac002ea95ae**
- Region: **East US**

Error Message:
 

> 
> Function (myPrivateFunctionsAppName/privateFunctionsName) Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'privateFunctionsName'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'client' to type DocumentClient. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
> Session Id: 8e5f392834c14dfdbd374ac002ea95ae
> 

#### Repro steps

Provide the steps required to reproduce the problem:

**No steps to repro, other than have an app with extensions (ServiceBus Trigger, CosmosDB) on a host with v2.0.12888.  To correct, create a new Azure Functions app and hope you get assigned to a host with the older runtime (2.0.12858 for example), and then deploy your code there.  And it instantly works.**
 

#### Expected behavior

Provide a description of the expected behavior.

**Extensions should load properly on Azure Functions Runtime v2.0.12888 with no changes needed by customer.**

#### Actual behavior

Provide a description of the actual behavior observed.

**Azure Functions app breaks and stops working completely.**

#### Known workarounds

Provide a description of any known workarounds.

**Re-deploy to a host with an older runtime.**

#### Related information 

Provide any related information 

* Programming language used: **dotnet**
* Links to source

My package references:

```
<ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.3" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="3.0.3" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.1.2" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.29" />
    <PackageReference Include="System.Data.SqlClient" Version="4.6.0" />
  </ItemGroup>
```

My extensions.json file that gets generated is:
```{
  "extensions":[
    { "name": "AzureStorage", "typeName":"Microsoft.Azure.WebJobs.Extensions.Storage.AzureStorageWebJobsStartup, Microsoft.Azure.WebJobs.Extensions.Storage, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"},
    { "name": "ServiceBus", "typeName":"Microsoft.Azure.WebJobs.ServiceBus.ServiceBusWebJobsStartup, Microsoft.Azure.WebJobs.ServiceBus, Version=3.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"},
    { "name": "CosmosDB", "typeName":"Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBWebJobsStartup, Microsoft.Azure.WebJobs.Extensions.CosmosDB, Version=3.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}
  ]
}

**Comment by LarsNymand** [comment]
how did you fix this?

**Comment by TimPosey2** [comment]
The root issue is that this newer runtime only loads the extensions with settings specified in the host.json.  It will no longer use the default settings.  Not sure if this is intended or not, but it's was a problem for my app.

For instance, let's say you have a project with the CosmosDB and ServiceBus extensions needed.  However, if you specify settings only for ServiceBus then the CosmosDB extensions will not load, breaking your Functions from loading or running and getting the error described above.  So if your host.json looks something like this, then you'll have an error:

```
{
    "version": "2.0",
    "extensions": {
        "serviceBus": {
            "prefetchCount": 100,
            "messageHandlerOptions": {
                "autoComplete": false,
                "maxConcurrentCalls": 32,
                "maxAutoRenewDuration": "00:55:00"
            }
        }
    }
}
```

To fix this, you have to specify settings **for all extensions that you want loaded**, you can no longer rely on it to load your defaults for you.  Ex:

```
{
    "version": "2.0",
    "extensions": {
        "serviceBus": {
            "prefetchCount": 100,
            "messageHandlerOptions": {
                "autoComplete": false,
                "maxConcurrentCalls": 32,
                "maxAutoRenewDuration": "00:55:00"
            }
        },
		"cosmosDB": {
            "connectionMode": "Gateway",
            "protocol": "Https",
            "leaseOptions": {
                "leasePrefix": "prefix1"
            }
        }
    }
}
```

**Comment by LarsNymand** [comment]
I will try it out. Thank you for your answer!
