### ISSUE TITLE
External provided TraceWriter should not get disposed with Host

### ISSUE THREAD

**Issue by suwatch** [Azure/azure-functions-host#530]
Below pseudo codes, when host is disposed, the trace writer (not owned by host) also get disposed.   I think the rule of thumbs is to dispose only what owned - otherwise, explicitly specified by caller to take ownership.

```
    var traceWriter = new FileTraceWriter(...);
    ScriptHostConfiguration config = new ScriptHostConfiguration
    {
        TraceWriter = traceWriter,
    };
    using (ScriptHost host = ScriptHost.Create(config))
    {
        ...
    };
```

**Comment by fabiocav** [comment]
This has been addressed in 2.0. Closing.
