### ISSUE TITLE
HttpRequest seems to be binding against AspNetCore 2.1 for Functions Preview 3

### ISSUE THREAD

**Issue by cleverguy25** [Azure/azure-functions-host#5304]
For the preview, I was hoping to have access to the new BodyReader on HttpRequest introduced in AspNetCore 3.0.  However it was not there, seems the preview sdk does not reference the 3.0 version.

**Comment by brettsam** [comment]
In your project file, add `<FrameworkReference Include="Microsoft.AspNetCore.App" />`. (and make sure you're targeting `netcoreapp3.0`). That will update your refs and you'll be able to use `BodyReader`.

**Comment by brettsam** [comment]
Feel free to re-open if that doesn't work for you.
