### ISSUE TITLE
Could not load file or assembly 'System.Text.Json, Version=4.0.1.0

### ISSUE THREAD

**Issue by aherrick** [Azure/azure-functions-host#5305]
netcoreapp3.1

Referencing a Project with EF Core 3.0.1 and when retreiving the DB Context I receiving the following error: 

`{"Could not load file or assembly 'System.Text.Json, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.":"System.Text.Json, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"}`

No idea how to get around it. It fails like this no matter which version of EF Core I'm on (Tried 3.1 preview as well)

// fails here;
`            Db.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
`

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3-preview</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.10" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.5" />
    <PackageReference Include="System.Runtime" Version="4.3.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />

    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.0-preview2" />
    <PackageReference Include="System.Text.Json" Version="4.7.0-preview3.19551.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyEfCoreProject.Api.Data\MyEfCoreProject.Api.Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by aherrick** [comment]
I was able to get around this by using Newtonsoft and ensuring my Api Project and no references to System.Text.Json

Not sure why the built in JSON parser wouldn't work with latest Function bits.

**Comment by aherrick** [comment]
I was able to get around this by using Newtonsoft and ensuring my Api Project and no references to System.Text.Json

Not sure why the built in JSON parser wouldn't work with latest Function bits.

**Comment by brettsam** [comment]
We don't yet support netcoreapp3.1. This support is coming soon.

**Comment by brettsam** [comment]
Closing this as expected -- if you see the same error when targeting 3.0, please re-open with those details as well. Thanks!
