### ISSUE TITLE
Max calls Azure Function

### ISSUE THREAD

**Issue by javierrodenas** [Azure/azure-functions-host#5314]
Hello,

I have developed an Azure function that starts working when trigger is actived. This trigger is a blobtrigger actived when new file is added to a container. 
The problem that I have here is the quantity of files added to the blob . For example, if I add 50 files the Azure function is actived 50 times correctly but if I add 200 files an error appears:

![image](https://user-images.githubusercontent.com/50680821/69946981-fac0d400-14ec-11ea-82d2-b3fb44a73fce.png)

I have tried to solve this with the following script in **host.json**:

```
{
  "version": "2.0",
  "extensions": {
    "serviceBus": {
      "maxConcurrentCalls": 500
    }
  }
}
```
After doing this there are no effects.

Could you help me to fix the max calls? I have not found any configuration option.

Thank you in advance.

**Comment by mhoeger** [comment]
@javierrodenas - can you share your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us get some more details on your app. Thanks!
