### ISSUE TITLE
Relax unification rules for System.Data.SqlClient

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#5315]
Anyone attempting to use a recent version of System.Data.SqlClient will run into issues as we unify on 4.3.1. Referencing this will work, but newer versions will not.

**Comment by brettsam** [comment]
@fabiocav -- can we remove unification for this?

**Comment by fabiocav** [comment]
Yes, I'm already tracking this as part of #3903

**Comment by fabiocav** [comment]
For more information, that is the change I'm referring to here: https://github.com/Azure/azure-functions-host/issues/3903#issuecomment-560054013
