### ISSUE TITLE
Test should warn if Envs required for the test are missing

### ISSUE THREAD

**Issue by suwatch** [Azure/azure-functions-host#532]
In general, people just do `build.cmd` and get > 100 errors.  Majority of them have to do with missing prerequisite env for the test (eg. `AzureWebJobsServiceBus`).  

It would be great to turn those types of errors to warning.   This helps developers pre-isolate the regresssion vs missing pre-requisite.  Of course, at the end of the days, we will strike for 0 error and warning.

**Comment by fabiocav** [comment]
Closing stale issue.
