### ISSUE TITLE
Azure Functions v3-preview, NETCore3.1: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=3.1.0.0

### ISSUE THREAD

**Issue by bmeijwaard** [Azure/azure-functions-host#5324]
After upgrading VS2019 to Version 16.4.0 and migrating to .NETCore v3.1  the following error occurs when starting up the Azure Functions app.
Also tried running the app on VS2019 preview Version 16.5.0 Preview 1.0, no luck there.

```
A host error has occurred
System.Private.CoreLib: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Stopping JobHost
```

Previously the functions project worked on preview version 16.4 targeting netcore v3.0. Downgrading netcore doesn't work tho. Project dependencies (which are hidden from the csproj due to privacy reasons) rely on EFCore 3.1 and VS is complaining about downgrade when trying to revert dependencies to version 3.0.1 (NU1605).  Supressing that error doesn't seem to work somehow by adding `<NoWarn>NU1605</NoWarn>` in the PropertyGroup.

This is the .csproj file for the Azure Functions project.

 ```
 <Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3-preview</AzureFunctionsVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.5" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.0-preview2" />
    <PackageReference Include="Microsoft.Azure.EventGrid" Version="3.2.0" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols" Version="5.6.0" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="5.6.0" />    
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.6.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  
</Project>
 ```

Please assist.

**Comment by fabiocav** [comment]
This is currently being worked on and support will be added in the next v3 release. Please see/follow this for updates: https://github.com/Azure/app-service-announcements-discussions/issues/115
