### ISSUE TITLE
Microsoft Azure WebJobs SDK ServiceBus connection string missing or empty error

### ISSUE THREAD

**Issue by SatishRanjan** [Azure/azure-functions-host#5326]
Repro steps:
--Create a Service Bus Queue trigger function app in visual studio, provide the connection string for the service bus and the queue name
--Run the project in visual studio and it'll result into the below error

Microsoft.Azure.WebJobs.ServiceBus: Microsoft Azure WebJobs SDK ServiceBus connection string 'Endpoint=sb://sb-func-v3-bugbash.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;[Hidden Credential]' is missing or empty.

**Comment by dannyhulmston** [comment]
@SatishRanjan Ensure you are declaring the connection property correctly as it's different between queues and topics.

`public void AccountSync([ServiceBusTrigger("Synchronisation:Outbound:AccountQueue", Connection = "Synchronisation:Outbound:Connection")]string myQueueItem, ILogger log)`

You have to state the connection property. I've got this working in Azure Functions v3

**Comment by mhoeger** [comment]
@SatishRanjan - I think this is because the connection should be the app setting name and not the actual connection string. I'm not sure how we could make that obvious though. Any ideas?
