### ISSUE TITLE
Host version 2.0 needs an extra line explaining to differentiate it's not the runt-time version on UI

### ISSUE THREAD

**Issue by SatishRanjan** [Azure/azure-functions-host#5327]
Create a v3 function app, and publish it. The version in host.json remains 2.0. On UI it would help if we can have a single line explaining this is the host.json schema version and not the function run time version. Please see the attached screen shot for the confusion on UI.
![func-v3-version-message](https://user-images.githubusercontent.com/8632540/70093387-1ef7e000-15d5-11ea-8389-492b59ef025e.PNG)

**Comment by mhoeger** [comment]
Closing as an issue to be tracked on ux repo: https://github.com/Azure/azure-functions-ux/issues/4394
