### ISSUE TITLE
Use Profile Guided Optimization(pgo) in dotnet core to PreJIT methods during placeholder mode

### ISSUE THREAD

**Issue by safihamid** [Azure/azure-functions-host#5336]
This feature is merged in .net core 5.0 but we are using a private build of 3.1 to generate a JitTrace file during Functions coldstart and that file will be used to PreJIT the captured method calls during placeholder mode.

**Comment by ahmelsayed** [comment]
.net core 5.0? are they skipping 4.0?

**Comment by safihamid** [comment]
@ahmelsayed yes :-) .net Core 4.0 is being skipped to avoid confusion with .Net Desktop 4.0 currently released. The next major release of .Net Core will be 5.0

**Comment by safihamid** [comment]
This is already done.
