### ISSUE TITLE
Metrics for latency aren't correctly captured when host terminated for timeout

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-host#5341]
While investigating a CRI it looks like the metrics may report latency only for runs that don't hit the timeout.  So even though in the function logs I see a timeout happens, the metrics never show latency for the timeout duration (in this case, 30 minutes for a dedicated plan)

**Comment by jeffhollan** [comment]
Actually LOTS of log messages may be missing when a function terminates because of an execution timeout.  I'd prefer we change the order of things a bit to flush all the logs and wait a few seconds or even a minute before terminating itself.  Makes these investigations super painful

**Comment by paulbatum** [comment]
Can confirm. Was looking at a customer case where they hit a function execution timeout. The details were in docker logs but were not in our system logs or the customer's app insights.

**Comment by brettsam** [comment]
@jeffhollan -- when you say "metrics", you mean FunctionsMetrics in kusto? 

@paulbatum -- do you have an example of which logs were missing from kusto? 

We already pause several seconds (3 I think) to allow things to flush (App Insights isn't a guarantee... there's a longstanding bug on their end around that). But the Kusto ones are puzzling. I'm trying to think through why any logs wouldn't get logged in these cases. We don't actually need to flush kusto as it's written directly as an ETW event...

**Comment by brettsam** [comment]
Turns out we do actually cache then flush metrics... and we're not disposing the service that's responsible for flushing for some reason. I'm debugging trying to figure out why.
