### ISSUE TITLE
Azure function not being triggered by items in queue

### ISSUE THREAD

**Issue by kapilmehtagit** [Azure/azure-functions-host#5345]
Hi,

I have a similar problem to some already reported earlier, but I haven't seen a fix that has worked for me. My queue triggered Azure function stops triggering after a while despite items in the queue, which then build up over time.

- Timestamp: 2019-12-06T12:19:35.549 
- Function App version (1.0 or 2.0): 1.0
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: d9e1da9d-0772-419b-9d0a-d738e20cb6ce
- Region: UK South
App Service plan: S3

#### Repro steps

Provide the steps required to reproduce the problem:

- Add items to queue "%Queue%"
- Some items get processed
- After some time, the processing stops

#### Expected behavior

The processing items in the queue should continue till no items are left in the queue.

#### Actual behavior

Queue processing stops occurring and items start to build up.

#### Known workarounds

Restarting the function triggers the queue processing to occur again, but this stops after a while, could be within minutes or within hours.

#### Related information 

Provide any related information 

* Programming language used : C#, deployed from Visual Studio
* Links to source
* Bindings used

<details>
<summary>Source</summary>

```csharp
 public static class XXXEventProcessing
    {
        [FunctionName("XXXEventProcessing")]
        public static void Run([QueueTrigger("%XXXEventProcessingQueue%", Connection = "AzureWebJobsStorage")] XXXEventProcessingRequest request, 
            TraceWriter log, ExecutionContext executionContext)
        {
            log.Info($"XXX Event Processing Queue trigger called: {request}");
                        
            Helper.ProcessEventRequest(request, log);
        }       
    }
```
</details>

**Comment by yojagad** [comment]
Could you give us the name of the function app so that we can take a closer look into this, please?

**Comment by kapilmehtagit** [comment]
Hi, function app is hmto365infostorefunctionslive and function name is InfoStoreEventProcessing. I am getting a huge build up of items in the queue with the function being idle. Thanks.

**Comment by yojagad** [comment]
Thank you for the info. I checked the logs. Are you certain your function has stopped and not just backlogged? I see items being added to the queue upto 26 messages per second and the function execution itself take from a few seconds upto 33 seconds even. And this is just from looking at a sample 15 minute duration.

**Comment by kapilmehtagit** [comment]
Hi, no, it certainly stops a number of times with no processing occurring for the items in the queue for several hours. A reset of the function app then resumes processing. Interestingly, I set up another function app to process the same queue, and that seems to stop as well. This seems to point to the queue as potentially needing looking into instead of the function app settings. Thanks

**Comment by yojagad** [comment]
Can you give me the most recent time frame where you noticed the function app just stopped processing and you had to restart the app?

**Comment by kapilmehtagit** [comment]
Sure, I have a couple of function apps that are displaying this issue. E.g. hmto365infostorefunctionsmig and hmto365infostorefunctionsmig2 on 19/02/2010 at 11:49AM GMT. They are idle despite having a number of items to be processed in the queues.

**Comment by yojagad** [comment]
Sorry, 19/02/2010? That's too far back and our logs don't go that far back unfortunately. Like I previously mentioned, could you point me to the most recent timeframe when this happened and you had to restart the app for it to continue processing items in the queue ?

**Comment by kapilmehtagit** [comment]
Sorry, I meant 19/01/2020 at 11:49am GMT.

**Comment by yojagad** [comment]
I looked at the logs around that time. Like I previously mentioned, it does look like the queue events are backlogged. I went further back and looked at a timeframe of (19/01/2020 11:00am GMT to 19/01/2020 11:50am GMT). It looks like immediately prior to 11:49 am GMT, the last queue trigger happened at 11:36 am and that particular execution went for 25 minutes. Immediately after it went with the next queue message. I'm attaching the screenshot from the same.

![image](https://user-images.githubusercontent.com/26885664/73215534-1f11e900-4109-11ea-87c6-c2df421dbf32.png)

So I don't see it stopping the execution but only that the execution took a long time. Let me know if you have any other questions, please.
