### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/azure-functions-host#5356]
This is a tracking issue for a bug someone logged in UserVoice about an issue they're having with CORS - pasted below:

"When configuring CORS with multiple/wildcard rules on a storage account any Azure Functions using a storage queue on this account will stop working without any error message.

I was happy that the support team could provide a workaround on this (use only single CORS rule), but it was a waste of time trying to troubleshoot this crazy flaw."

Not sure if this is the Antares implementation or the one in the host, but I'm instructing the user to post more details about their problem here.

**Comment by mhoeger** [comment]
Likely an app service limitation: https://github.com/aspnet/AspNetCore.Docs/issues/7167. @stefsch - could you weigh in?

cc: @kashimiz

**Comment by pragnagopa** [comment]
@ColbyTresness - please follow up get get more details on the repro tol help triage this issue
