### ISSUE TITLE
Unable to register ServiceBus Trigger in V2 using Dependency Injection

### ISSUE THREAD

**Issue by bpt2010** [Azure/azure-functions-host#5363]
I am trying to migrate my existing Azure Functions that were written in V1 to V2 and want to take advantage of Dependency Injection. I cannot seem to register Service Bus Trigger with Dependency Injection. I can reference the HttpClient with no issues. I am not sure what I am missing. Can you help? Thanks

Below are the packages that I have a reference on

<propertygroup>
<targetframework>netcoreapp2.1</targetframework>
<azurefunctionsversion>v2</azurefunctionsversion>
<assemblyname>FunctionSMSCRMWebAPI</assemblyname>
<rootnamespace>SendSMSFunction</rootnamespace>
</propertygroup>
<itemgroup>
<packagereference include="Microsoft.Azure.Functions.Extensions" version="1.0.0"/>
<packagereference include="Microsoft.Azure.WebJobs" version="3.0.14"/>
<packagereference include="Microsoft.Azure.WebJobs.Extensions.Http" version="3.0.2"/>
<packagereference include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" version="4.0.0"/>
<packagereference include="Microsoft.Extensions.Http" version="3.1.0"/>
<packagereference include="Microsoft.NET.Sdk.Functions" version="3.0.1"/>
</itemgroup>

The exception been thrown.

The 'FunctionSendSMSMessage' function is in error: The binding type(s) 'serviceBusTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.

How do I register the Service Bus Trigger with Dependency Injection? Thanks

**Comment by fabiocav** [comment]
Are you using pre-compiled functions in .NET / C#? If so, adding a reference to the Microsoft.Azure.WebJobs.Extensions.ServiceBus package is all you need.
