### ISSUE TITLE
Max function duration timeout when using Azure Functions on Kubernetes with KEDA

### ISSUE THREAD

**Issue by fisapras** [Azure/azure-functions-host#5365]
What is the Max time out duration (min) if we deploy Azure Functions on Kubernetes with KEDA?

I read this [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-kubernetes-keda), but could not find any documentation regarding max. timeout duration.

**Comment by jeffhollan** [comment]
Would be unbounded. Just note you’ll need to make sure host.json is set to enforce whatever timeout you do or don’t want. Also worth checking out guidance for long running jobs. Functions would need to follow the non-job one https://keda.sh/concepts/scaling-deployments/#long-running-executions

**Comment by fisapras** [comment]
Thanks for the information @jeffhollan. Is there any documentation/example around how to handle SIGTERM signal/PreStop handler to extend the life of the process. I am writing python function which will take long time to finish atleast couple of hours (unfortunately it cannot be broken/refactored into smaller functions).

Also as per [this](https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-terminating-with-grace)  article the pod state will be set to Terminating state even before SIGTERM is issued to the pod which is not what the article you sent mentions.

Are there any long term plans to addressing not killing the pods which are doing meaningful/long running work?

**Comment by ThejaChoudary** [comment]
@jeffhollan can you please look into this further

**Comment by ThejaChoudary** [comment]
@fisapras Are you still facing the issue?
