### ISSUE TITLE
Azure Functions v3 Runtime not working on App Service

### ISSUE THREAD

**Issue by DrBarnabus** [Azure/azure-functions-host#5368]
#### Is your question related to a specific version? If so, please specify:
v3

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
.NET Core c#

#### Question
I have updated an app to v3 and netcoreapp3.1, however, after changing the value of FUNCTIONS_EXTENSION_VERSION to ~3 the app no longer loads and instead we have this message in the functions page: 

```
Cannot Upgrade with Existing Functions
Major version upgrades can introduce breaking changes to languages and bindings. When upgrading major versions of the runtime, consider creating a new function app and migrate your functions to this new app.
```

Looking at the runtime version, it is at 2.0.12888.0. So I am unsure why it isn't letting me use v3.

I have tried restarting the app a number of times, but nothing I do will make it update the runtime version.

If it helps, I am running on App Service Linux on UK South.

Any help would be appreciated, thanks 👍

**Comment by Rambalac** [comment]
Same here. Linux Service Plan.
Deployment as Zip Deploy is successful, but no functions displayed.
Server log show Core 2.0
```
2019-12-12 12:20:52.615 INFO  - Pulling image from Docker hub: microsoft/azure-functions-dotnet-core2.0:2.0
2019-12-12 12:20:54.754 INFO  - 2.0 Pulling from microsoft/azure-functions-dotnet-core2.0
2019-12-12 12:20:54.754 INFO  -  Digest: sha256:02f992ba41ff20d3ae804c4379806e40ec70d7d4196eb68b1441c161c78e2ff7
2019-12-12 12:20:54.754 INFO  -  Status: Image is up to date for microsoft/azure-functions-dotnet-core2.0:2.0
2019-12-12 12:20:54.756 INFO  - Pull Image successful, Time taken: 0 Minutes and 2 Seconds
```
Configuration.
```
{
    "name": "FUNCTIONS_EXTENSION_VERSION",
    "value": "~3",
    "slotSetting": false
  },
  {
    "name": "FUNCTIONS_WORKER_RUNTIME",
    "value": "dotnet",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_RUN_FROM_PACKAGE",
    "value": "1",
    "slotSetting": false
  },
```

**Comment by DrBarnabus** [comment]
I resolved my issue yesterday by updating the container image manually since then changing then it has been fine.

The trick was you need to go into the Platform Features -> All Settings and then go into Container Settings as even though its the same menu the values weren't showing for me in the Azure Functions version.

Although, Weirdly it has now reverted back to the wrong container.

For reference the image I am trying to use is: mcr.microsoft.com/azure-functions/dotnet:3.0 which is the one that works, but it keeps changing back to microsoft/azure-functions-dotnet-core2.0:2.0

@Rambalac might be worth manually changing your container image as well too see if that makes yours work?

**Comment by Rambalac** [comment]
Every time it get replaced to microsoft/azure-functions-dotnet-core2.0:2.0

**Comment by DrBarnabus** [comment]
@Rambalac are you using Azure Pipelines or pushing changes to your application?

I have found that every update results in the docker image field being reset to microsoft/azure-functions-dotnet-core2.0:2.0 or is it just that it won't let you change it?

**Comment by Rambalac** [comment]
Azure Devops Pipelines

**Comment by DrBarnabus** [comment]
Yeah, I have noticed the same thing. Its when ever the pipeline deploys on our development environment that the image is being reset and breaking the functions again.

**Comment by DrBarnabus** [comment]
It's a shame no one from Microsoft/Azure has commented on this issue yet.

**Comment by DrBarnabus** [comment]
So the issue, as mentioned in that linked Issue from App Service appears to be related to the Azure Pipelines Task used to publish the function.

As I have a solution, I am going to close this off and for info on fixing it look at: https://github.com/Azure/app-service-announcements-discussions/issues/131
