### ISSUE TITLE
Visual Studio Code does not deploy v3 functions correctly

### ISSUE THREAD

**Issue by springcomp** [Azure/azure-functions-host#5374]
#### Repro steps

I had created a brand new Azure Function App from the portal.
Used Visual Studio Code to deploy an Azure Function App v3 for the first time.
Visual Studio Code offered to upgrade the remote runtime to `~3`.

However, none of the functions appear after deployment. 

It appears that the directory structure on the remote App Service is not correct and does not have the automatically generated folders containing the `function.json` files.

**Comment by gzuber** [comment]
Hey @springcomp I'm having trouble repro-ing, are you still running into this? Do you know what version of azure functions core tools you're using? What language is your function?

**Comment by springcomp** [comment]
@gzuber You are right, I can no longer reproduce this issue.

I seem to notice that my Azure Core Tools prompted me for update this morning, so a sneaky correction might have slipped almost unnoticed 😁.

I retried from scratch, paying attention to all the steps and it works correctly.
In any case, thanks you for your time.
Cheers.
