### ISSUE TITLE
How to add input/output formatters to Azure HTTP functions ?

### ISSUE THREAD

**Issue by Anthony-Breneliere** [Azure/azure-functions-host#5377]
I see Azure function host uses MVC for managing http requests and responses. But I don't see how to configure formatters as I don't have access to the IMvcbuilder.

I would like to add input and output formatters so that a function app could return http responses with CSV, Html or any custom format other than json. 

In the startup of the Function App I'd like to add the following configuration code:

```
        public void Configure(IWebJobsBuilder builder)
        {
            builder.services.Configure<MvcOptions>(o =>
                {
                    o.OutputFormatters.Add(new CsvOutputFormatter(new CsvFormatterOptions()));
                    o.InputFormatters.Add(new CsvInputFormatter(new CsvFormatterOptions()));
                    o.FormatterMappings.SetMediaTypeMappingForFormat("csv", "text/csv");
                });
```

The function would have an attribute that specifies the format output:

```
        [FunctionName("MyFunction")]
        [Produces("text/csv")]
        public static async Task<IActionResult> Run( 
...
```

**Comment by fabiocav** [comment]
@Anthony-Breneliere custom HTTP formatter registration is not currently supported in Functions.
