### ISSUE TITLE
Language worker process crash leaves executing functions unfinished

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#5385]
@amamounelsayed brought up that when a language worker process crashes (ex: uncaught exception), those requests that were outstanding never complete. Specifically, he tested an HTTP request that caused a worker process crash. Then, some time later, a function timeout exception was thrown bringing down the whole WebHost. If a language worker process crashes, we should mark those outstanding executions as failed.

**Comment by mhoeger** [comment]
This PR has work that addresses this issue: https://github.com/Azure/azure-functions-host/pull/5662
However, closing the above PR because it was meant as a hotfix (minimally invasive). Closing above in favor of non-hotfix version and linking above for reference of problem and a solution.

**Comment by fabiocav** [comment]
Moving to sprint 73 where we can prioritize getting #5662 in.

**Comment by fabiocav** [comment]
@mhoeger are you still planning on reopening #5662 ?

**Comment by fabiocav** [comment]
Work currently in PR. Moving to sprint 75 to reflect the current state.

**Comment by fabiocav** [comment]
PR review currently in progress.

**Comment by brettsam** [comment]
Moving this to next sprint for further validation.
