### ISSUE TITLE
Using HttpContextAccessor behaves differently between v2 and v3 when using a proxy

### ISSUE THREAD

**Issue by upta** [Azure/azure-functions-host#5386]
#### Investigative information

Happening in local development with Azure Functions v3

#### Repro steps

Provide the steps required to reproduce the problem:

1.  Inject IHttpContextAccessor
2.  Modify some part of HttpContext.Response (status, cookie, whatever)
3.  Call method via a proxy

https://github.com/upta/AzureFunctionsProxyIssue

When running the 2.1 version, hitting both the "natural" endpoint and the proxy endpoint do the same thing.

In the 3.1 version, the changes to Response are ignored and the "natural" endpoint behaves differently than the proxy endpoint

#### Expected behavior

Proxy version to respect and not overwrite changes to HttpContext.Response

#### Actual behavior

Proxy ignores HttpContext.Response changes and does it's own thing

#### Known workarounds

Haven't found any, been looking at the changes for Asp.Net Core 3.0 to see if there was anything that would explain it, but I haven't found anything obvious.

#### Related information 

https://github.com/upta/AzureFunctionsProxyIssue

**Comment by fabiocav** [comment]
@vfedonkin is this something you can assist with?

**Comment by vfedonkin** [comment]
@fabiocav , I need to investigate but no any ETA, have some urgent work till January

**Comment by fabiocav** [comment]
@vfedonkin, thank you.
