### ISSUE TITLE
Host process should not terminate on function timeout in OOP languages

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#5391]
When running with an OOP language worker, function timeouts should not cause a host process restart. In those cases, we should be able to terminate and recycle the worker without bringing the host down, addressing a class of issues related to host process termination.

**Comment by pragnagopa** [comment]
Moving it to next sprint for more investigation and finding owner.

**Comment by anirudhgarg** [comment]
@fabiocav/@pragnagopa I see that this is a P2. I wanted to request if we can move this up priority and handle this in the upcoming sprint. This can help a lot when they are multiple workers/host.

**Comment by pragnagopa** [comment]
Yes we are tracking this for upcoming sprint. @yojagad has PR out for this.
