### ISSUE TITLE
Functions Support for Data Lake Storage Gen 2 as the main Storage Account for AzureWebJobsStorage

### ISSUE THREAD

**Issue by FinVamp1** [Azure/azure-functions-host#5400]
#### What problem would the feature you're requesting solve? Please describe.
Customers that previously tried to use an Azure Data Lake Storage Gen 2 account for their Azure Web Jobs Storage account ran into issues as this uses a Hierarchical namespace which doesn't support normal blob traffic. 

https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-multi-protocol-access details how multi protocol access has been enabled by default and should mean this restriction is lifted.

#### Describe the solution you'd like
Confirmation this this scenario is supported.

#### Describe alternatives you've considered
No alternatives considered.

#### Additional context
https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-quickstart-create-account

**Comment by mhoeger** [comment]
I had a similar CRI - I can confirm that this works:
![image](https://user-images.githubusercontent.com/8888531/73501328-5e933c00-437a-11ea-8455-9428dd9149cb.png)
![image](https://user-images.githubusercontent.com/8888531/73501347-7074df00-437a-11ea-88c7-41a3465d7794.png)

**Comment by kulkarnisonia16** [comment]
@mattchenderson - were you following up on this one with the data lake team?
