### ISSUE TITLE
Need to update documentation for Python to retrieve information about the currently running function

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-host#5402]
Need to update documentation for Python to retrieve information about the currently running function. 

This information has been added to the Wiki page. For more info, please see example for PowerShell:
https://github.com/Azure/azure-functions-host/wiki/Retrieving-information-about-the-currently-running-function#powershell-on-functions-v2-or-higher

**Comment by Hazhzeng** [comment]
Edited page on https://github.com/Azure/azure-functions-host/wiki/Retrieving-information-about-the-currently-running-function#python
