### ISSUE TITLE
Issue while running Azure Function

### ISSUE THREAD

**Issue by urbanmichal** [Azure/azure-functions-host#5403]
Hi,

Each time I'm running the Azure Function, I'm getting:

```
A host error has occurred
[17/12/2019 08:19:00] Microsoft.Azure.WebJobs.Extensions.Storage: Could not load type 'Microsoft.Azure.WebJobs.Host.Scale.IScaleMonitorProvider' from assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.13.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

Those are the version I'm using:

```
Azure Functions Core Tools (2.7.1633 Commit hash: 45c7d86a3bbc9ed0a80a8f4199aa7ea80ccfb24e)
Function Runtime Version: 2.0.12673.0
Microsoft.Azure.WebJobs.Host, Version=3.0.13.0
Microsoft.NET.Sdk.Functions (3.0.2)
Microsoft.Azure.WebJobs (3.0.14)
```

Any ideas? :(

Best regards,

Michal

**Comment by mhoeger** [comment]
Hi @urbanmichal ,

I saw that your post was answered on this forum: https://social.msdn.microsoft.com/Forums/security/en-US/51b33a4c-addb-4aa3-a081-ff21207b890b/problem-while-running-azure-function?forum=AzureFunctions

Per Dixit:
> When host or CLI tools is out of date. Please make sure you’re running the latest tools.
> The latest version of the runtime (2.0.12858) should be loading 3.0.14.
> If you are running from Visual Studio you should see a similar message printed at the top
> Azure Functions Core Tools (2.7.1846 Commit hash: 458c671341fda1c52bd46e1aa8943cb26e467830) Function Runtime Version: 2.0.12858.0
> or
> Generally we got this when we are using Azure Storage based functionality (blob/queue/tables trigger/input/output) and have some issue in Microsoft.Azure.WebJobs.Extensions.Storage extension.
> Could you try get the Microsoft.Azure.WebJobs.Extensions.Storage Nuget  Package.
> For non-C# apps, running func extensions install  should pull in the right storage extension.
> Do let me know how it goes. 

Any updates?

**Comment by rahulpnath** [comment]
FWIW

When running from Visual Studio it was still getting an older version. I cleaned up all the folders under 'C:\Users\<username>\AppData\Local\AzureFunctionsTools\Releases\' and started again and it worked. Got the path from the console that fires up when running Azure functions
