### ISSUE TITLE
Template downloading stuck

### ISSUE THREAD

**Issue by urbanmichal** [Azure/azure-functions-host#5404]
While creating new Azure Function project from the template, the message "Making sure all template are up to date" seems stuck. I've already tried to delete %LOCALAPPDATA%\AzureFunctionsTools and %USERPROFILE%\.templateengine, restarting VS. Nothing helped. Can I look into some logs? Or do you know what could be done to fix that? Is there are a different way of installing those templates/tools?

**Comment by JAugustusSmith** [comment]
I get the same thing. I reinstalled visual studio from scratch but haven't been able to get the new project templates, it just hangs

**Comment by f2bo** [comment]
Same here. I first had this problem last week. The v3 option was shown in the drop down listing the runtimes that were available but the "Making sure all templates are up to date" message never went away, even after waiting for an hour. I resolved it by following the manual steps described here:

https://github.com/Azure/azure-functions-tooling-feed/wiki/Fixing-Azure-Function-Core-Tools-download-issues-for-Visual-Studio

This downloaded the 3.1.0 tools.

Now it's happening again in a different machine and the manual steps do **NOT** work this time. The original `feeds-3.json` file in the `%localappdata%\AzureFunctionsTools` listed the 3.2.0 tools but the corresponding folder in `%localappdata%\AzureFunctionsTools\Releases` was empty. After I renamed the `%localappdata%\AzureFunctionsTools` and `%userprofile%.templateengine` folders and restarted Visual Studio, it downloaded the v2 tools again. However, the new feeds-3.json file now has **NO** entries for v3, only v1 and v2.

**Comment by mhoeger** [comment]
@soninaren - any ideas?

**Comment by soninaren** [comment]
@f2bo This is definitely strange behavior. The [zip](file) here has the 3.2.0 folder that you can copy into the release folder. This should unblock you. Are you using 2 different version of VS? If yes which versions.

@urbanmichal and @JAugustusSmith  Can you try the following steps, this should mitigate the issue for you, for now.
1.	delete %userprofile%\.templateengine
2.	delete contents of %userprofile%\AppData\Local\AzureFunctionsTools
3.	download and extract the following zip file into %userprofile%\AppData\Local\AzureFunctionsTools
4.	The manifest file in the [zip](https://github.com/soninaren/Workarounds/releases/download/1.0.0/AzureFunctionsTools.zip) points to a different user account. You would have to replace it with the corresponding path.

**Comment by f2bo** [comment]
> @f2bo This is definitely strange behavior. The zip here has the 3.2.0 folder that you can copy into the release folder. This should unblock you. Are you using 2 different version of VS? If yes which versions.

Hi @soninaren

The link to the zip file you mention in the first paragraph is broken. I'm not sure if it's the same zip file that you mention further down in your reply.

And yes, I do have two different versions of VS installed. I still haven't uninstalled VS 2017.

- VS 2017 v15.5.2
- VS 2019 v16.4.2

Thanks

**Comment by soninaren** [comment]
@f2bo it is the same zip file. I have fixed the link. VS 2017 and VS 2019 should work fine together. Not sure what is causing this. Not able to reproduce on my end.

**Comment by soninaren** [comment]
The size of the download is one of the things that we are investigating. From 16.4 VS switched to using x64 version of cli. However the x64 version of CLI being used is not minified like x86. The core tools x64 zip file is `140 mb (x64)` vs `50 mb (x86)` and the same extracted is `350 mb (x64)` vs `112 mb (x86)`.
