### ISSUE TITLE
Add logging for extensions not found in extension bundle

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#5407]
Currently we have error message generate when we see unrecognized binding in function.json. We see the same message if an extension for a give function is not found in extension bundle. We need a different log message that says that `no matching extension was found for a binding in extension bundle`

**Comment by fabiocav** [comment]
Moving this to 69 as it is currently in PR.

**Comment by fabiocav** [comment]
@soninaren can you please link the PR to this? Has this been done?

**Comment by soninaren** [comment]
This was fixed in here https://github.com/Azure/azure-functions-host/pull/5467
