### ISSUE TITLE
Could not load type 'System.Runtime.InteropServices.StandardOleMarshalObject'

### ISSUE THREAD

**Issue by Santhosh0505** [Azure/azure-functions-host#5408]
When I am trying to create a Azure Function App with .Net Core 3.0, I am trying to use a System.Windows.Forms.DataVisualization.Charting dor creating a bar graph chart. But when I am creating an object of chart class, its giving this error as 
Could not load type 'System.Runtime.InteropServices.StandardOleMarshalObject' from assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

And the weird thing is its not going into catch block also, its just stopping the solution.

**Comment by pragnagopa** [comment]
Please share your project references.
