### ISSUE TITLE
Azure Function app with .Net Core 3.1 version not detecting the function app methods!

### ISSUE THREAD

**Issue by Santhosh0505** [Azure/azure-functions-host#5409]
When I am trying to create a .net core Azure function App and change the framework version to .Net core 3.1 its building perfectly,  but its not running the methods as expected, its not at all detecting the function app methods due to which I am not able to hit it.

![image](https://user-images.githubusercontent.com/48650250/71058027-788b0d80-2184-11ea-83f4-7ab1e8dbce64.png)

**Comment by APIWT** [comment]
Can you share your `host.json`? I have a hunch.

**Comment by FabienLavocat** [comment]
I have the exact same problem when I deploy from Azure DevOps, no function were detected. I had to re-run the deployment and everything went fine. Here's my host.json:

`{
  "version": "2.0",
  "serviceBus": {
    "maxConcurrentCalls": 16,
    "prefetchCount": 100,
    "autoRenewTimeout": "01:00:00"
  }
}`

**Comment by Badabum** [comment]
@Santhosh0505 have you changed the `FUNCTIONS_WORKER_RUNTIME` from `~2` to `~3` in function app configuration?

**Comment by Santhosh0505** [comment]
@Badabum  
No I have not changed that, I have just changed the framework version from .net core 3.0 to .net core 3.1
And I am facing this issue. I think I need to configure something when I change the version from .net core 3.0 to .net core 3.1

**Comment by Badabum** [comment]
@Santhosh0505 do you have http triggered functions only? do you use Visual Studio and if so so you what version of AzureFunctionsTools do you have? Pls make sure that you have runtime version `>=3.0.*` installed.

**Comment by mhoeger** [comment]
@Santhosh0505, +1 to Badabum's comment - please make sure you are using the 3.x functions runtime.

In Visual Studio, you can do so by following [these steps]().
Your .csproj should look like [this](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions#version-3x).

**Comment by Santhosh0505** [comment]
@Badabum I have checked to update the version but I was unable to do it.

@mhoeger Let me try using this. I will come back to this later.
