### ISSUE TITLE
BlobTrigger not working, function stuck on '...will wait 2000 ms before polling queue ...'.

### ISSUE THREAD

**Issue by sebastianzur** [Azure/azure-functions-host#5410]
#### Investigative information

- Timestamp: 18-12-2019, 12:44:00
- Function App version (1.0 or 2.0): 2.0
- Function App name: roguecert-test2
- Function name(s) (as appropriate): RunAnalysis
- Region: westeurope

The function never seems to be pulling for a potential BlobTrigger and is always stuck on 
"Function 'RunAnalysis' will wait 2000 ms before polling queue 'azure-webjobs-blobtrigger-ccvm1-2137340777".

I have created another function that uses a blob input and output trigger that worked succesfully (roguecert-test), so I am wondering what went wrong here
#### Related information 

* The function is deployed from VS Code Python 3.7
* function.json:
```json
{
  "bindings": [
    {
      "name": "inputBlob",
      "type": "blobTrigger",
      "path": "input/{blobname}.{blobextension}",
      "connection": "AzureWebJobsStorage",
      "direction": "in"
    },
    {
      "name": "outputBlobData",
      "type": "blob",
      "path": "output/{blobname}-analysed",
      "connection": "AzureWebJobsStorage",
      "direction": "out"
    },
    {
      "name": "outputBlobPlotAll",
      "type": "blob",
      "path": "output/plots/{blobname}-all",
      "connection": "AzureWebJobsStorage",
      "direction": "out"
    },
    {
      "name": "outputBlobPlotExpired",
      "type": "blob",
      "path": "output/plots/{blobname}-expired",
      "connection": "AzureWebJobsStorage",
      "direction": "out"
    }
  ],
  "scriptFile": "__init__.py"
}
```

**Comment by mhoeger** [comment]
Hi @sebastianzur - those log messages just mean that your function app is polling for a new blob every 2 seconds, so I don't think it's stuck! (cc: @brettsam)

Is it possible that the connection you are using (AzureWebJobsStorage) is shared by any other running function app? Only one function app (ex: roguecert-test) will ever trigger per event. So if you had two function apps listening for blob input, on the same storage account, it might look like your other function app (ex: roguecert-test2) is not being triggered

**Comment by sebastianzur** [comment]
Thanks, that was indeed the problem!
