### ISSUE TITLE
Does serviceBus.maxConcurrentCalls applies to all topic at once or topic by topic ?

### ISSUE THREAD

**Issue by jonathanantoine** [Azure/azure-functions-host#5417]
Hello,

I have 2 Azure Functions (AZ1 and AZ2) on the same AppService targeting differents topics (T1 and T2) and I set serviceBus.maxConcurrentCalls to 1. 

What will happen if there is 1 message posted in T1 and T2 at the same time ?
- Sequential : the message from T1 will be processed and then the The message from T2 will be processed .
- Parallel : the messages from T1 and T2 will be processed at the same time.

Thanks.

**Comment by mhoeger** [comment]
Hi @jonathanantoine, the host.json setting `maxConcurrentCalls` applies to each service bus triggered function in the function app. So the messages from T1 and T2 will be processed at the same time. 

One thing to note too is that if your App Service contains more than one VM, you will have more than one instance of the function's host running. So if you have 2 VM's (VM1 and VM2), you could have 4 messages processed sequentially (one message from T1 processed by instance in VM1, one from T1 processed by VM2, one from T2 processed by VM1, one from T2 processed by VM2).

Closing as answered, but let me know if this doesn't answer your question!

**Comment by jonathanantoine** [comment]
Thanks a lot for you answer @mhoeger  it's perfect. Maybe it can be added to the doc ?

**Comment by mhoeger** [comment]
Good suggestion, thanks!
