### ISSUE TITLE
"Microsoft.Data.SqlClient is not supported on this platform" despite function.deps.json

### ISSUE THREAD

**Issue by eastmane** [Azure/azure-functions-host#5423]
I seem to have hit a similar issue to Azure/Azure-Functions#1370 using EF Core, VS 16.4.2, and functions runtime 3.0.12930.0 - I get "Microsoft.Data.SqlClient is not supported on this platform" with or without FUNCTIONS_V2_COMPATIBILITY_MODE. I'm referencing Microsoft.Data.SqlClient 1.1.0 everywhere I can find it and the functions.deps.json and runtimes folder are present in bin.

I noticed that the file size on the Microsoft.Data.SqlClient in the bin folder is different to the filesize in my .nuget and the runtimes version (339KB in bin vs 1241KB in .nuget, despite same versions in properties).

Inspired by https://stackoverflow.com/a/53952815/908 I included this in .csproj:

```
  <!-- For publish -->
  <ItemGroup>
    <None Include="$(USERPROFILE)\.nuget\packages\microsoft.data.sqlclient\1.1.0\runtimes\win\lib\netcoreapp2.1\Microsoft.Data.SqlClient.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <!-- For local debug -->
  <Target Name="CopyToBin" BeforeTargets="Build">
    <Copy SourceFiles="$(USERPROFILE)\.nuget\packages\microsoft.data.sqlclient\1.1.0\runtimes\win\lib\netcoreapp2.1\Microsoft.Data.SqlClient.dll" DestinationFolder="$(OutputPath)\bin" />
  </Target>
```

This copies the .nuget version into bin and it seems to work fine.

Any ideas what's going on here? I've tried a minimal functions app using EF and that seems to work  fine (with the 339KB dll in bin oddly), and I've verified this across a couple of installs so suspect it must be something todo with our solution/projects. The behaviour is exactly the same when deployed to Azure.

Happy to share projects etc via email if that would help

**Comment by hiraldesai** [comment]
I have emailed you the file on your Microsoft email address.

**Comment by fabiocav** [comment]
Thank you.

Actually, looking at what you're describing above, you may be running into a publishing issue.

Can you validate that, in your deployed payload, you have a file named `function.deps.json` in the `bin` folder (as opposed to `{assemblyname}.deps.json`

**Comment by fabiocav** [comment]
There's an updated version of the SDK (3.0.3) that addresses an issue with the publishing process. If the above seems to be the issue, can you please validate that referencing that version from https://www.myget.org/F/azure-appservice-staging/api/v3/index.json works for you?

**Comment by hiraldesai** [comment]
> Thank you.
> 
> Actually, looking at what you're describing above, you may be running into a publishing issue.
> 
> Can you validate that, in your deployed payload, you have a file named `function.deps.json` in the `bin` folder (as opposed to `{assemblyname}.deps.json`

I don't have the file named function.deps.json anywhere in the bin folder. I will try the 3.0.3 tomorrow and let you know how it goes.

**Comment by hiraldesai** [comment]
Hi @fabiocav - I can confirm that referencing 3.0.3 from the App Service staging NuGet feed works. Thank you so much for quick assessment and providing a fix. 

When does it become publicly available?

**Comment by fabiocav** [comment]
This will be available after January 6th. I'll leave this open and update the issue once the package is released.

**Comment by eastmane** [comment]
Hi @fabiocav do you think this fixes the issue I'm seeing also? If so happy to test with the updated version.

**Comment by kfrancis** [comment]
> This will be available after January 6th. I'll leave this open and update the issue once the package is released.

Was that released?

**Comment by fabiocav** [comment]
@kfrancis not yet. As mentioned above, we'll update and close the issue as soon as it is.

**Comment by fabiocav** [comment]
The package has been published to NuGet.
