### ISSUE TITLE
TimerTrigger not firing or firing PastDue

### ISSUE THREAD

**Issue by sthewissen** [Azure/azure-functions-host#5427]
#### Investigative information
Similar to #1534 my Azure Function that is working on a Timer trigger is not always firing. It stops working almost daily. However, it seems that when I log in to the Azure Portal it starts processing the function with `IsPastDue=true`. Not very reliable that way, so if you could help me out with what might be the root cause of this I would be very grateful.

- **Timestamp:** CRON: 30 0 0,4,8,12,16,20 * * * (30 seconds after every 4 hours)
- **App version:** 2.0
- **Function App name:** http://biffy-4h-btc.azurewebsites.net
- **Function name:** Orchestrator4H_Timer (its not actually an orchestrator function)
- **Region:** West Europe
- No WEBSITE_TIME_ZONE setting

Here's some invocation data:

| Type   | Timestamp                   | Invocation ID                        | Remark                           |
|--------|-----------------------------|--------------------------------------|----------------------------------|
| Manual | 2019-12-29T16:22:04.680     | ba21c8b5-6b51-4e01-b708-7899e8832345 | Should've fired at 16:00         |
| Timer  | 2019-12-29T16:18:23.7030637 | 021dc5ac-df8c-4b1c-bd1f-594c2f5c6218 | Apparently ran when I logged in? |
| Manual | 2019-12-29T12:14:45.712     | 325065a2-3c2d-4728-aae2-680bb10e4ebe | Should've fired at 12:00         |
| Timer  | 2019-12-29T12:14:05.7309974 | 4b888c57-6fe7-4937-8ba7-ca5d96f1b470 | Apparently ran when I logged in? |
| Manual | 2019-12-30T08:57:12.468     | 172b8ff2-97bc-4185-96aa-cdab105ce234 | Should've fired at 08:00         |
| Timer  | 2019-12-30T08:57:07.3879061 | ba45595b-8f3b-4211-aec3-10e202d9000b | Apparently ran when I logged in? |
| Timer  | 2019-12-30T00:00:30.0170624 | daa07d91-a405-4982-af2c-667d93859cdc | This ran just fine               |
| Timer  | 2019-12-29T20:00:30.0336272 | 1e69b9a8-8dc1-48d6-8499-b7f425a3918a | This ran just fine               |

Also from time to time, I get the error that the **Functions runtime is not reachable** on the portal. I'm guessing it could be related, but the storage connection string is correct and I can reach it through Azure Storage Explorer. It seems like Functions somewhat randomly drops the connection to it. My guess is this is what happens when the invocation is supposed to happen which is why it doesn't trigger, but I'm not actively doing anything on the environment when it happens so I'm not sure what the root cause of it not being reachable is.

![image](https://user-images.githubusercontent.com/2419439/71575525-8f6b2180-2aed-11ea-9168-798c8de19996.png)

#### Repro steps

There seem to be no consistent repro steps. When I restart the function app and trigger the function manually the next few instances run just fine. It's just a matter of time before it stops working again though, sometimes even within a day.

#### Expected behavior

The timer firing when it should.

#### Actual behavior

The timer not firing at all or firing late (PastDue).

#### Known workarounds

Restart the Function app and it'll work for a while.

**Comment by yojagad** [comment]
I'm taking a look at this. I'm curious, did you make any tweaks to WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and/or WEBSITE_CONTENTSHARE settings recently?

**Comment by sthewissen** [comment]
@yojagad Thanks! I'm pretty sure I've never changed either of those settings. I sometimes do use the Advanced Edit for settings allowing me to edit the entire JSON file, but I haven't changed those settings specifically.

**Comment by yojagad** [comment]
Is the WEBSITE_CONTENTSHARE pointing to a file share in your storage account? There can be inconsistent behaviors if that's not the case

**Comment by sthewissen** [comment]
Yes it is. The file share exists in the storage account.

**Comment by yojagad** [comment]
We have detectors in place which points us to anomalies around these two app settings. And this is what it shows for your function app.

![image](https://user-images.githubusercontent.com/26885664/71632410-4ab1ba00-2bc3-11ea-9f64-17d49211658a.png)

Might be worthwhile to double check just in case. But if everything is configured correctly, it might indicate something else.

**Comment by sthewissen** [comment]
The setting is configured as biffy-4h-btc9154, which exists in the file storage account.

**Comment by yojagad** [comment]
Thanks for confirming that. This might be an issue on our side with a fix coming in. Will keep you posted.

**Comment by sthewissen** [comment]
I'm getting this pretty consistently throughout the function apps in the resource group now and it is becoming very annoying. I'm having to manually run them at least once a day and since some of these are scheduled when I'm sleeping it's a real hassle. Do you need me to provide details on these past due runs for other function apps in the resource group as well? Is there any ETA you can give on the fix you mentioned? Also curious what the issue was :)

**Comment by sthewissen** [comment]
Just now some of them are down again, with a 503: Site Unavailable.

![image](https://user-images.githubusercontent.com/2419439/71779238-a9a57380-2fb5-11ea-879d-c05788ea8187.png)
![image](https://user-images.githubusercontent.com/2419439/71779245-b75af900-2fb5-11ea-8dc6-47364caa86f9.png)
![image](https://user-images.githubusercontent.com/2419439/71779280-d063aa00-2fb5-11ea-8963-2e4aea8069a6.png)

I really do believe these being down at the time the schedule is run is the root cause. But they shouldn't be down in the first place 😅

**Comment by yojagad** [comment]
Sorry about the late response. So the issue particularly had to do with how the scaling logic worked. There was a bug where some stamps' scale requests were not being honored and apps that lived in these stamps were seeing the kind of issues you were seeing.

I think at this point, the update should have been fully rolled out. Do you continue to see issues with the timer trigger with respect to this?

**Comment by sthewissen** [comment]
@yojagad I've seen great improvements over the last few weeks where it's all working like a charm! Massive thanks for the fix 🙏

**Comment by yojagad** [comment]
No worries, glad it worked out :)
