### ISSUE TITLE
Trigger attributes like Queue and Timer info is not configurable when published to Azure Function

### ISSUE THREAD

**Issue by venkatesh-bhupathi** [Azure/azure-functions-host#5438]
#### Investigative information

Please provide the following:

- Timestamp:
- Function App version (1.0 or 2.0): 2.0
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

#### Repro steps

Provide the steps required to reproduce the problem:
1. We have a sample Queue Trigger Azure function with the following definition,
`public static void Run([QueueTrigger("%myqueueitems%", Connection = "")]string myQueueItem, ILogger log)`
And we have the configuration of QueueName in local.settings.json as follows,
```
{
    "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "myqueueitems": "myqueue-items"
  }
}
```
2. When I run the Azure Function locally, it runs fine by reading the configuration from the local.settings.json.
3. But when we publish the Azure Function, then it fails to read the configuration setting. I have added the AppSetting myqueueitems manually on the portal but still, Azure Function fails to start.

#### Expected behavior

When we provide the trigger attribute configuration values with %configkey%, then Azure Function should pick the settings from the Function App Settings. We are seeing this behavior with V2 function.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by pragnagopa** [comment]
Please see [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#publish) for instructions on how to publish settings in local.settings.json to Azure.

Remove `connection` attribute from `Run([QueueTrigger("%myqueueitems%", Connection = "")]string myQueueItem, ILogger log)` if you intend to use default storage connection string which is provided in `AzureWebJobsStorage` app setting.

**Comment by venkatesh-bhupathi** [comment]
My concern is about the %myqueueitems% configuration, Azure Function is able to read the configuration from local settings file, but when I published with local settings or even when I create the configuration on the portal, it does not work.

**Comment by venkatesh-bhupathi** [comment]
We update the Azure Function AppSettings from the Release Pipeline's AppService Deploy task by sending the following configurations -ASPNETCORE_ENVIRONMENT "Development" -AZURE_FUNCTIONS_ENVIRONMENT "Development" -myqueueitems $(QueueName). How come the configuration with % works locally but does not work when published.

**Comment by pragnagopa** [comment]
Can you please share exception stack trace you see in the logs? also, for further investigation please share either function App Name (or invocation id and region where function app is deployed) and approximate time range where you get the errors because trigger is not working
