### ISSUE TITLE
Support Easy Auth in functions runtime.

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-host#5439]
Currently function apps rely on the easy auth middleware provided by app service front end. To support running functions outside app service and skus which don't use the app service front end modules the middleware should be included as part of the functions runtime.

**Comment by jabbera** [comment]
Does this mean this would work during local development as well? It’s impossible to work with the signalr bindings locally because you need authentication.

**Comment by fabiocav** [comment]
@jabbera eventually, yes. This is not the goal of the current work, but completing this paves the way for that.

**Comment by jabbera** [comment]
Thanks. I ended up working around the signal r issue by using a proxy function for development that ADFS the missing header anyway.

**Comment by fabiocav** [comment]
Targeting sprint 70 for validation and completion.

**Comment by fabiocav** [comment]
Closing as resolved.

**Comment by jabbera** [comment]
Is this available in a released v3 version?!?!?? I’m doing my happy dance.
