### ISSUE TITLE
Cannot bind parameter 'log' to type ILogger. 

### ISSUE THREAD

**Issue by grik001** [Azure/azure-functions-host#5441]
All my functions are suddenly giving this error. Did something change since Nov/Dev which might be causing this issue?

Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'ImportFunction'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'log' to type ILogger. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
Session Id: 8caaa86bad0246468d062474d6bcd97b

Timestamp: 2020-01-07T11:00:52.195Z

**Comment by kashimiz** [comment]
Hi @grik001, I can investigate if you share your function app's information. Can you provide the following? (You can also share this information privately with [these instructions](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately).)

- Function App name:
- Function name(s) (as appropriate):
- Invocation ID(s):
- Region:

**Comment by grik001** [comment]
Hi Kash, 

Feel free to close this ticket if you want. Basically a had a library which was causing the issue.
