### ISSUE TITLE
DI not working if deployed before an another function not using DI.

### ISSUE THREAD

**Issue by jonathanantoine** [Azure/azure-functions-host#5451]
#### Is your question related to a specific version? If so, please specify:
I am using the 2.X sdk with these package installed :
```
<PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="7.0.0"/>
<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0"/>
<PackageReference Include="Microsoft.Azure.WebJobs.Host.Storage" Version="3.0.14"/>
<PackageReference Include="Microsoft.Extensions.Logging.ApplicationInsights" Version="2.12.0"/>
<PackageReference Include="MediatR" Version="7.0.0"/>
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.31"/>
```
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
It's all done in C#
#### Question

I have 2 Azure functions, A and B, in two separate projects.

- A uses the Dependency Injection feature by inheriting FunctionStartup.
- B do not uses the Dependency Injection feature.

A and B are deployed using Azure Dev Ops Release Pipeline. They both works fine when deployed lonely. 

When I deploy them together it only works if I deploy B (not using DI) before A(using DI). It looks related to the content of the `extensions.json` not declaring a DI specific extension. 

Is there a way to fix this ? Maybe by declaring something in the B host.json file?

Thanks a lot.

The content of my working extensions.json file :
```
{
  "extensions":[
    { "name": "MyFunctionStartup", "typeName":"AFunction.MyFunctionStartup, AFunctionName, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"},
    { "name": "ServiceBus", "typeName":"Microsoft.Azure.WebJobs.ServiceBus.ServiceBusWebJobsStartup, Microsoft.Azure.WebJobs.ServiceBus, Version=3.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}
  ]
}

```

**Comment by fabiocav** [comment]
Are you atempting to deploy them both to the same Function App?

Combining the output of two distinct projects is not a supported scenario. Each project maps to a function app, so the behavior you're seeing is because the second deployment essentially overrides the configuration and some of the artifacts of the first.
