### ISSUE TITLE
[dotnet azure function on Linux] does not load assembly from function.proj

### ISSUE THREAD

**Issue by sogaani** [Azure/azure-functions-host#5452]
#### Repro steps
Run csharp script azure function with `function.proj` on linux conteiner on docker.

#### Expected behavior
Install assembly by Nuget and load it.

#### Actual behavior
Does not load assembly installed by `function.proj`.

#### Known workarounds
Mount windows directory(which does not distinguish lowercase and uppercase directories) to Nuget cache folder on linux container.

docker-compose.yml
```
        volumes:
            - ./azurefunc/data/:/home/data
```

#### Related information 
Althought Nuget creates a package folder with the lowercase package name and folder path on Linux is usually case sensitive, [here](https://github.com/Azure/azure-functions-host/blob/f9540d6aaafc56ecd3d8d045edfc159a85ea9ba1/src/WebJobs.Script/Description/DotNet/PackageAssemblyResolver.cs#L105) does not seem to convert pakcage name which is used as directory path to lowercase.

**Comment by v-bbalaiagar** [comment]
Hi @sogaani ,  Can we know if you are seeing this issue still and requires further follow up.

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
