### ISSUE TITLE
CosmosDBTrigger binding extension is not registered on my function

### ISSUE THREAD

**Issue by scott-lin** [Azure/azure-functions-host#5464]
CosmosDBTrigger binding is not registered on my function after following these instructions:

- https://github.com/Azure/azure-functions-host/wiki/Binding-Extensions-Management
- https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#vs

Overall, I'm confused as to whether the CosmosDB binding extension should be installed automatically when deploying my function from VS with my setup (see details below), or whether I'm supposed to install it manually.

In addition to fixing my error, plealse let me know if a manual step is always required for installing binding extensions. A manual install step would really be a buzz kill for CI/CD. :(

#### Investigative information

- **Timestamp:** 2020-01-10T19:01:42.201Z
- **Function App version:** 2.0
- **Function App name:** TopicFilterFunction20200110102942
- **Function name:** TopicFilterFunction
- **Region:** West US 2

#### Repro steps

1. Create new C# library function in Visual Studio 2019 with a CosmosDBTrigger binding like so:

```
[FunctionName("TopicFilterFunction")]
        public async void Run(
            [CosmosDBTrigger( databaseName: "databaseNameTodo", collectionName: "collectionNameTodo", ConnectionStringSetting = "", LeaseCollectionName = "leases")]
            IReadOnlyList<Document> documents )
```

2. Update `host.json` with the extensionBundle for CosmosDB like so:

```
{
    "version": "2.0",
    "extensionBundle": {
        "id": "Microsoft.Azure.WebJobs.Extensions.CosmosDB",
        "version": "3.0"
    }
}
```

3. Run from package manager console,

`Install-Package Microsoft.Azure.WebJobs.Extensions.CosmosDB -Version 3.0.5`
`Install-Package Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator`

4. Other dependencies of my project in case it helps:

![image](https://user-images.githubusercontent.com/31644762/72180717-94a55780-339c-11ea-8bb5-83d993e7392c.png)

5. Publish the function to Azure via Visual Studio right-click on project.

6. Navigate to Azure Portal and investigate the successfully deployed function.

#### Expected behavior

At step 6, I expect no error to be reported in the portal.

#### Actual behavior

At step 6, the following error pops up,

```
Function (TopicFilterFunction20200110102942/TopicFilterFunction) Error: The binding type(s) 'cosmosDBTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.
```

#### Known workarounds

I tried to follow the instructions at https://github.com/Azure/azure-functions-host/wiki/Updating-your-function-app-extensions, however, I was unable to continue beyond step 4 because the tooling blocked me. Specifically, I was unable to delete the `bin` directory because of a 409 Conflict error. My function was stopped at the time of trying this.

Also step 5 in the linked instructions mention an "extensions.csproj', which does not exist. I feel like the instructions are out of date. Maybe they're for v1 functions? I don't know. There is no label.

**Comment by soninaren** [comment]
@scott-lin Please remove the extension bundle configuration from host.json. It is not applicable to c# precompiled function apps. I do see some issues with documentation. We are working on updating the documentation. However i am not sure where did you find the instructions for step 2.  

```
"extensionBundle": {
        "id": "Microsoft.Azure.WebJobs.Extensions.CosmosDB",
        "version": "3.0"
    }
```

You only need to install the nuget extension once during the development. For CI/CD you only need to build the project. There is no manual installation step required.

**Comment by scott-lin** [comment]
@soninaren, step 2 instructions for modifying `host.json` are in the same article I linked above. Here is the [bookmark](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#extension-bundles) for the specific section in the article. I was led to believe this was required for local development by the article. It doesn't make mention of it being only applicable to non-precompiled C# functions.

Removing the entry from `hosts.json` helped alleviate the error I was seeing.

**Comment by soninaren** [comment]
@scott-lin Are you able to run the function successfully after removing the bundle configuration or are you seeing additional errors?

**Comment by dan-loup** [comment]
@soninaren I too am having the same issue as above.

I never added the `extensionBundle` section to my `host.json` file put whenever I try publishing directly from VS I get the following error:

`The binding type(s) 'cosmosDBTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.`

**Comment by scott-lin** [comment]
I'm unblocked for the issue I was seeing. Thanks for the help.

I am curious why removing the extension bundle item from host.json makes a difference; it seems like, if it's not applicable for pre-compiled C# functions, it shouldn't have an impact (and certainly not detrimental)?

**Comment by soninaren** [comment]
The reason removing extension bundle makes a difference is because the configuration is still taking effect for C# pre-compiled. Even though it is not designed to be used for C# pre-compiled functions, when you use extension bundle configuration it uses the extensions from the bundle and ignores the extensions installed via the nuget package reference in `.csproj` file.
