### ISSUE TITLE
New requests not all stopped while draining requests

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#5465]
We made a change to have a 5 second grace period to drain currently executing functions: https://github.com/Azure/azure-functions-host/pull/4986/files (thanks @yojagad)! 

However @FinVamp1 has found that new invocations are able to be processed after "Stopping JobHost":
```
Executing   'Functions.ProcessData' (Reason='', Id=86a1)
Sending invocation id:86a1
Posting invocation id:86a1
Writing invocation request invocationId:   86a1d
Shuttingdown Rpc Channels Manager
Shutting down language worker channels   for runtime:node
Stopping host...
Active host changing from '7f6d' to   '(null)'.
Waiting for   RpcFunctionInvocationDispatcher to shutdown
Received invocation response for   invocationId: 76f4
InvocationResponse received for   invocation id: 76f4
Draining invocations from language worker   channel completed. Shutting down 'RpcFunctionInvocationDispatcher'
Executed 'Functions.ProcessData'   (Succeeded, Id=76f4)
Stopping JobHost
Executing 'Functions.ProcessData'   (Reason='', Id=9625)
Sending invocation id:9625
Executed 'Functions.ProcessData' (Failed,   Id=9625) System.InvalidOperationException : Did not find any initialized language workers
Host did not shutdown within its allotted   time.
Shutting down RPC server
```

We should make sure that no new requests are processed while JobHost is recycling, as they will fail with a `Did not find any initialized language workers` error

cc: @fabiocav

**Comment by yojagad** [comment]
@mhoeger How does C# functions behave today during jobhost recycling? Does it stop newer invocations as soon as the recycling starts ?

**Comment by mhoeger** [comment]
Dupe: https://github.com/Azure/azure-functions-host/issues/5624
Both resolved.

**Comment by hkharan** [comment]
@mhoeger @pragnagopa  can you help with status update for fix on Windows
