### ISSUE TITLE
[feature] Show error when deploying v1 code into a v2 or v3 app

### ISSUE THREAD

**Issue by alexkarcher-msft** [Azure/azure-functions-host#5485]
In a recent support ticket a user was able to deploy using azure devops a v2 Java app into a v1 function app in Azure.

https://servicedesk.microsoft.com/#/customer/cases?caseNumber=119112822000211

**Comment by fabiocav** [comment]
@FinVamp1 marking this as triaged, but we need to discuss as part of the supportability triage meeting.

**Comment by kulkarnisonia16** [comment]
Have tooling support that checks extension version for a match.
