### ISSUE TITLE
Azure function isnt triggered continously from event hub stream. 

### ISSUE THREAD

**Issue by avirup-prescriber-360** [Azure/azure-functions-host#5491]
#### Is your question related to a specific version? If so, please specify:
azure function version 2
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
node.js 

#### Question
Hi, 

My scenario is I have an event hub which triggers an azure function. The azure function in this case is a simple rule engine based on which an IoT hub is triggered. 
Currently, the problem that I am facing is, I am initiating 1000+ request to the event hub per 30 seconds. After processing around 400-600 messages, the azure function stops or freezes. After restarting it, it again processes another 400-600 messages and then again freezes. 

I am executing in batches using this block 
`eventHubMessages.forEach((message, index)`

Its hosted on a premium plan.

**Comment by pragnagopa** [comment]
Please provide either function app name or invocationId, function app region and appx time range you see this behavior
