### ISSUE TITLE
Surface more details for storage connection errors 

### ISSUE THREAD

**Issue by dariagrigoriu** [Azure/azure-functions-host#5494]
#### What problem would the feature you're requesting solve? Please describe.
When the Functions host is not able to connect to storage please surface more details for errors directly to help with investigations: e.g. is the storage account not in the same VNET or is there a temporary error?

**Comment by alrod** [comment]
@dariagrigoriu, we can't check if the storage account is in the same VNET from functions runtime but we can extend/improve our error message. can you please provide an aka.ms link with possible reasons why the storage connection can be failed. The error message can be something like this: "Connection to the storage account is failed. For more information please visit http://aka.ms/123"

**Comment by alrod** [comment]
Similar issue:
https://github.com/Azure/azure-webjobs-sdk/issues/2268
