### ISSUE TITLE
Unable to resolve service for type

### ISSUE THREAD

**Issue by miantosca** [Azure/azure-functions-host#5501]
An existing function that has been running for months was redeployed and it started failing on DI issues. The function was pinned to an older version (2.0.12342) of the runtime that is no longer supported so after the deploy I noticed it was changed it to ~2 (2.0.12888.0). The reason I had it pinned was to address DI issues with version 2.0.12353. I never went back and unpinned it.

I updated my local environment to use the same version of the functions host (2.0.12888.0) that the portal specified and I am getting the same exceptions. I tried to put a break point in startup.cs and it never gets hit.

I have a different project that I can run locally and the startup.cs break point is hit as expected.

- Timestamp: 1/16/2020, 7:44:29 PM (Local time)
- Function App version (1.0 or 2.0):2.0
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: 79a6c413-09a6-4708-8635-332f8fa52feb
- Region: East US

#### Repro steps

Provide the steps required to reproduce the problem:
- Register Dependency in Startup
- Specify dependency for a Queue Triggered Function in its ctor
- Execute the function by adding message to queue

#### Expected behavior
- Dependency is injected and function method runs

#### Actual behavior
Exception thrown:
Executed '<function name>'
**Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type '<dependency interface name>' while attempting to activate '<function class name>'.**

All other functions in the same project fail as well - they happen to specify different dependencies in their ctors

#### Known workarounds

none

#### Related information 

Provide any related information 

* Programming language used  C#
* Links to source
* Bindings used

**Comment by miantosca** [comment]
I was able to fix the problem - Azure build pipelines upgraded to .NET Core SDK 3.1 - had to add a global.json file to the solution so that the build process would lock-down the SDK version to 2.1.402. It had the **Use .NET Core** step in the pipeline but it was not honored after the major version upgrade to 3.1.

**Comment by brettsam** [comment]
Thanks for looping back and letting us know this is resolved @miantosca. I'm going to close this now -- let me know if there's anything else we can do here.
