### ISSUE TITLE
Error generating extension metadata 

### ISSUE THREAD

**Issue by Joehannus** [Azure/azure-functions-host#5502]
I'm getting an error when trying to start debugging Function Apps in Visual Studio. This started after upgrading to the latest version of the functions SDK in our V2 Azure Functions (from 1.0.27 to 1.0.31 I think it was - we need 1.0.28 minimally because of the inclusion of Microsoft Dependency Injection, that we used to replace the Wilezone DI package - 1.0.28 has the same issue b.t.w.). 

The same error occurs in the publish step in a build in a Build Pipeline in our DevOps Environment. This is quite a blocking issue for us.

The error I'm getting is as follows:
System.IO.DirectoryNotFoundException: The path `D:\a\1\s\Sitech.Sahc.Functions\bin\Debug\netstandard2.0\binbin` does not exist. Unable to generate Azure Functions extensions metadata file.

For some reason a publish is performed to a "binbin" directory.

Locally I could fix this by changing the targets file in the nuget package folder of the package in question, by removing the string literal "bin" in one place in this targets file. 

This fix is also mentioned in issue #4055 and #340. But these issue has been closed already.

However - as far as I know I can't change the targets file in the nuget package folder on the build server (or correct me if I'm wrong - if this is possible, and if so, how to do that).

Another solution I found was to add a direct reference/dependency to Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator (in this issue: #4545). I've tried this with the latest version (1.1.3). But when starting the function app locally I was getting the old error back (but now for the version 1.1.3).

	<Target Name="_InitializeExtensionMetadataGeneratorProps" AfterTargets="_InitializeFunctionsSdk">
		<PropertyGroup>
			<_IsFunctionsSdkBuild Condition="$(_FunctionsTaskFramework) != ''">true</_IsFunctionsSdkBuild>
			<_FunctionsExtensionsDir Condition="$(_IsFunctionsSdkBuild) == 'true'">$(_FunctionsExtensionsDir)bin</_FunctionsExtensionsDir>
		</PropertyGroup>
	</Target>

	<UsingTask TaskName="GenerateFunctionsExtensionsMetadata"
              AssemblyFile="$(_FunctionsExtensionsTaskAssemblyFullPath)"/>

	<Target Name="_GenerateFunctionsExtensionsMetadataPostBuild"
          AfterTargets="Build">

		<GenerateFunctionsExtensionsMetadata
			SourcePath="$(_FunctionsExtensionsDir)"
			OutputPath="$(_FunctionsExtensionsDir)"/>

		<Move Condition="$(_IsFunctionsSdkBuild) == 'true' AND Exists('$(TargetDir)extensions.json')"
			SourceFiles="$(TargetDir)extensions.json"
			DestinationFiles="$(TargetDir)bin\extensions.json"
			OverwriteReadOnlyFiles="true"
			ContinueOnError="true"/>
	</Target>

I think the error is caused because "bin" is added to "FunctionExtensionsDir", and then "FunctionsExtensionsDir" is used for "OutputPath" and "bin" is also added after the DestinationFiles "TargetDir". Anyway - the issue is solved if you remove the "bin" string literal in the "FunctionExtensionsDir" node.

**Comment by mhoeger** [comment]
So sorry for the delay - I'm glad you've found the solution to this issue. Here's a comment about why that may have been there: https://github.com/Azure/azure-functions-host/issues/4055#issuecomment-505599197
