### ISSUE TITLE
[Question] Understanding "why" our application is being scaled under low resource usage

### ISSUE THREAD

**Issue by SimonLuckenuik** [Azure/azure-functions-host#5504]
Hi! 

Is there any way we can get logs of the reason while we are being scaled out ?

We found that the log "prop__MS_EventName = ColdStart" identify cold starts. We also added a log to each function to detect when the function is being called in the context of a Cold Start (so our own internal Cold Start event). But this gives us only the "when", not the "why".

We have been having issues with cold starts being too frequent for no specific reason according to our observations.

We are using the a 5 minute timer approach to help prevent cold start, along with availability tests at every 5 minutes on an health monitoring endpoint, so in theory cold starts shoud happen only on new deployments or scale out, but we are still getting them too often for no particular reason (almost no load on service). 

Cold starts are so frequent on some of our services that we are being requested to investigate going back to regular App Service/Premium Plan, forcing us to move from a very flexible consumption based Microservices architecture with independent execution resources to a single instance plan sharing all services ti keep cost under control.

Thanks!

**Comment by NickMoores** [comment]
Sounds a bit like an issue we had, which I referenced here #4294 . Our problem went away quite suddenly in that one...

**Comment by SimonLuckenuik** [comment]
It's been like that for a long time for us, we contacted support, but that did not help, they simply told us that cold starts are part of the serverless approach and that we need to move to Premium. The fact is that we dont mind cold starts here and there, but it was just too frequent for no apparent reason. The fact that we don't have a way to know why the scaling is happening makes it hard to investigate as well. We have cold starts taking over 15 seconds sometime, even more considering that we have a microservices architecture with services that call each other for data aggregation, and both services would hit the cold start.

**Comment by gzuber** [comment]
@SimonLuckenuik Sorry it took me a bit to get back to you on this, I've been trying to find an option for you. There is an app setting that might help but fair warning it's in preview and hasn't been exhaustively tested. I also can't guarantee it'll stay active/valid.

`SCALE_CONTROLLER_LOGGING_ENABLED=<Type>:<Verbosity>`
Where Type can be `AppInsights` or `Blob` and Verbosity can be `None`, `Warning`, or `Verbose`
Example: `SCALE_CONTROLLER_LOGGING_ENABLED=AppInsights:Verbose`

If using AppInsights, this would emit logs with the category `ScaleControllerLogs` that have an explanation about the scaling decision.

**Comment by SimonLuckenuik** [comment]
Thank you @gzuber, exactly what we are looking for, we will give that a try!
