### ISSUE TITLE
Durable Function On Kubernetes

### ISSUE THREAD

**Issue by fisapras** [Azure/azure-functions-host#5505]
I am currently developing Azure function application using runtime v2.0 and dotnet core 3. I want to know if the durable function can be deployed to Kubernetes.

- The client function is an http triggered function, which starts an orchestration (durable) function. 
- The orchestration function calls many activity functions and manages the flow. 

I wanted to know whether this scenario is supported on Kubernetes. If so, is there a sample which demonstrates deploying durable function on Kubernetes.

**Comment by cgillum** [comment]
@fisapras Durable Functions should run fine in Kubernetes, just like any other Azure Function should run fine. The only Azure dependency that exists is Azure Storage and Application Insights (if you choose to enable that). As long as your containers have connectivity to public Azure endpoints, then everything should work as you might expect.

We don't have samples (that I'm aware of) that deploy a Durable Functions app to Kubernetes, specifically, but I expect you should be able to take any other Azure Functions sample for Kubernetes and modify by adding Durable Function triggers.

**Comment by fisapras** [comment]
Thanks @cgillum. I will give it a try.

**Comment by yojagad** [comment]
@fisapras I'll go ahead and close this thread since there hasn't been activity. If you have any other questions, please feel free to reopen this or open new thread.
