### ISSUE TITLE
Dropped ITelemetryInitializer DI support in version 3?

### ISSUE THREAD

**Issue by cannehag** [Azure/azure-functions-host#5511]
We are using Azure Functions version 3.

In version 2 we could add a custom AppInsights ITelemetryInitializer to the IServiceCollection in our startup. In version 3 this ITelemetryInitializer is never called.
Did you drop support for this or is it a bug?

According to the documentation, you are NOT supposed to call AddApplicationInsightsTelemetry().
https://docs.microsoft.com/en-US/azure/azure-functions/functions-dotnet-dependency-injection#logging-services

We are relying on some different ITelemetryInitializer's in our system. How/where can I add them to the AppInsights registration in version 3?

**Comment by cannehag** [comment]
When using Microsoft.NET.Sdk.Functions 1.0.29 it works as supposed to, but after updating to version 3.0.2, none of my ITelemetryInitializers registered in the IServiceCollection is used.

**Comment by fabiocav** [comment]
@cannehag can you clarify the version of the Application Insights SDK you're using?

@brettsam this is likely caused by the removal of the version pinning/unification. So the types here are not what the host supports.

**Comment by brettsam** [comment]
I don't think we ever unified on App Insights -- but now that deps file is copied by default it's failing...

**Comment by cannehag** [comment]
@fabiocav I have tried 2.10.0 and 2.12.0
