### ISSUE TITLE
Can no longer retrieve function key via API since 2.0.12888

### ISSUE THREAD

**Issue by restfulhead** [Azure/azure-functions-host#5531]
We're using the Management API to retrieve the function app's host key, e.g. `GET https://management.azure.com/subscriptions/$azure_subscription/resourceGroups/$1/providers/Microsoft.Web/sites/$2/hostruntime/admin/host/systemkeys/_master?api-version=2016-08-01`

This used to work fine, but with v2.0.12888 (https://github.com/Azure/app-service-announcements-discussions/issues/125) we retrieve the following error: `GET requests for this resource via the hostruntime extensions API are not authorized. Please use an alternate first class ARM API.` I believe this is caused by the following commit: https://github.com/Azure/azure-functions-host/commit/9bda97e56be74022734f49a80f8df0a42c27c09d

Is there another way to retrieve the function app host key?

I've tried downgrading the functions app, but saw that older versions have been removed. E.g. Portal shows "Unsupported Runtime Version - Your custom runtime version is not supported. As a result 2.0.12961.0 runtime is being used." Also shouldn't such a breaking change be a major or at least minor version release? With the function app version set to `~2` this just broke for us very unexpectedly...

**Comment by mathewc** [comment]
The "hostruntime" ARM APIs you were calling previously are not part of our public documented ARM API surface. The documented/supported surface is [here](https://docs.microsoft.com/en-us/rest/api/appservice/webapps). Specifically for listing host keys, you can use the [ListHostKeys](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/listhostkeys) api.
