### ISSUE TITLE
Issue with Azure function

### ISSUE THREAD

**Issue by CRSnyder** [Azure/azure-functions-host#5536]
We're still seeing issues with the azure function reported in https://github.com/Azure/azure-functions-host/issues/5043.  Can that bug be reopened or should I submit another issue?

As an update, the queue trigger last ran on 1-21-20. Before that it ran on 1-17-20.  We have thousands of messages in the queue that need to be processed.

**Comment by djjlewis** [comment]
We also have a function that put messages onto an Azure Service Bus Queue using the `[ServiceBus]` attribute binding and noticed it had stopped working recently. It worked locally but we were seeing an error in the Azure Functions blade when going into the functions saying something like "Error indexing method ... Cannot bind ICollector<Message>" 

After updating all the Nuget packages / SDK versions with no luck, I ended up removing the `EntityType.Queue` parameter from the `[ServiceBus]` attribute and lo and behold it started working again.

**Comment by brettsam** [comment]
Sorry for the delay on following up -- did you happen to have Manage rights on the SB access policy that you were using with these apps? There was an issue with scaling that may have been hitting you. 

If you're still seeing these issues, I can look deeper...

**Comment by CRSnyder** [comment]
It seems that the issue is still occurring.  The logs say the function last ran on Feb. 15 but there are still over 2000 messages in the queue.

I'm not sure what "Manage rights on the SB access policy" means....

**Comment by brettsam** [comment]
When you provide a shared access policy for SB, that policy has certain rights. Manage is one of them. You can add this in the SB settings under "shared access policies". Check if the one you're using with your Function app has Manage rights:

![image](https://user-images.githubusercontent.com/1089915/75061968-aba89080-5496-11ea-8cb6-56e2e48d97b0.png)

**Comment by CRSnyder** [comment]
Oh...SB is for Service Bus.  We are not using a service bus, at least not explicitly.  Is a service bus something every function app with a queue trigger uses?  Mention of service bus was from another user who is not associated with my project.

I looked and there's only one service bus on this subscription, and it has manage rights.

**Comment by fabiocav** [comment]
@CRSnyder apologies for the gap here. Is this something you're still experiencing?
