### ISSUE TITLE
[HttpWorker]Startup command may not work for all apps

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-host#5541]
Tried to use the PHP dev server using the command `php -S 0.0.0.0:<port> worker.php` and came across a few issues that likely apply to other types of apps where you don't have full control over the startup command.

- Extra flags `--workerId {WorkerId} --port {Port}` cause an error because they're invalid when used  `php -S`. I think it's better to pass these as environment variables.
- The command requires the port. Not sure how to pass that. Would be great if `FUNCTIONS_HTTPWORKER_PORT` and other environment variables are available to be used here.

**Workaround**

A startup bash script:

```bash
#!/bin/bash
echo "$@"
if [[ "$@" =~ --port[[:space:]]([0-9]+) ]]; then
    port=${BASH_REMATCH[1]}
else
    echo "Could not parse port"
fi
php -S 0.0.0.0:$port worker.php
```

host.json

```json
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  },
  "httpWorker": {
    "description": {
      "defaultExecutablePath": "./start_worker.sh"
    }
  }
}
```

@pragnagopa

**Comment by pragnagopa** [comment]
Thanks for the feedback. I agree adding environment variables instead of command line parameters is a better approach.

`FUNCTIONS_HTTPWORKER_PORT` is already set as an environment variable when functions host launches HttpWorker. 

Do let me know if following does not work:
`php -S 0.0.0.0:$FUNCTIONS_HTTPWORKER_PORT worker.php`

**Comment by anthonychu** [comment]
Cool. I couldn't try the env var from the command because it was failing on the extra parameters. I wonder if there are OS specific ways to use the variable from the command line though. For instance it's `$` in bash, probably something else on CMD or PowerShell.

It'll be interesting to see how often the HttpWorker startup command needs to be OS-specific (e.g., dev on macOS, deploy on Windows). VS Code tasks allows users to specify a [different command](https://code.visualstudio.com/docs/editor/tasks#_operating-system-specific-properties) for each OS and it might be good to support something like this as well.

I'm also interested to see how to specify a different startup command for debugging (related to #5463). This might be a Core Tools ask but perhaps `func start` could take a startup command that overrides host.json so that we can start the worker with debugging enabled. It could also be useful to allow an environment variable to specify a worker startup command.
