### ISSUE TITLE
[HttpWorker]HttpTrigger function responds with ReturnValue when HTTP output not explicitly set

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-host#5542]
Not sure this is a bug or part of the spec, but data sent to `$return` output binding (possibly containing secrets) may inadvertently leak in HTTP response if HTTP response is not explicitly set.

**function.json**

```json
{
  "disabled": false,
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    },
    {
      "type": "signalR",
      "name": "$return",
      "hubName": "chat",
      "direction": "out"
    }
  ]
}
```

If HTTP worker responds with `res` set, it works as expected:
- `res` value is returned in body of the response
- `ReturnValue` is sent to the output binding

HTTP worker response:

```json
{
  "Outputs": {
    "res": "hi"
  },
  "ReturnValue": {
    "target": "newMessage",
    "arguments": [
      {
        "sender": "anthony",
        "text": "hello world"
      }
    ]
  },
  "Logs": []
}
```

Function HTTP response:

```
HTTP/1.1 200 OK
Connection: close
Date: Sun, 26 Jan 2020 01:18:26 GMT
Content-Type: text/plain; charset=utf-8
Server: Kestrel
Content-Length: 2

hi
```

---

If `res` is not set, the `ReturnValue` appears in the response body.

```json
{
  "Outputs": {},
  "ReturnValue": {
    "target": "newMessage",
    "arguments": [
      {
        "sender": "anthony",
        "text": "hello world"
      }
    ]
  },
  "Logs": []
}
```

Function HTTP response:

```
HTTP/1.1 200 OK
Connection: close
Date: Sun, 26 Jan 2020 01:17:20 GMT
Content-Type: text/plain; charset=utf-8
Server: Kestrel
Content-Length: 117

{
  "target": "newMessage",
  "arguments": [
    {
      "sender": "anthony",
      "text": "hello world"
    }
  ]
}
```

If `ReturnValue` contains secrets, it may accidentally be exposed.

@pragnagopa

**Comment by pragnagopa** [comment]
If function.json has only HttpTrigger, such as
```json
{
  "disabled": false,
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}
```

Functions runtime forwards the httpTrigger and also uses the response from the HttpWorker directly without any transformations.

Can you please confirm, in the case where `res` is not set, does it have output bindings or just a httpTrigger?

**Comment by anthonychu** [comment]
The behavior I described is happening when there's another output binding. The return value is sent as the HTTP response when it was intended for the output binding.

**Comment by pragnagopa** [comment]
Thanks for reporting. `$return` value should not be set as response for httpTrigger

**Comment by pragnagopa** [comment]
tagging @mhoeger / @fabiocav / @mattchenderson  for their thoughts

Options to address this issue:
- As `$return` is a special, treat this issue as by design specifically for HttpTrigger. If `$return` is set, and output binding for http out is not set, `$return` takes precedence. This would require users to explicitly set output binding for httpTrigger

- Add handler to convert raw values to Http response similar to node js worker [here](https://github.com/Azure/azure-functions-nodejs-worker/blob/00f08cb62c962532897ae446e8aea272fabbd1e6/src/FunctionInfo.ts#L32-L33)

**Comment by pragnagopa** [comment]
Thinking more about this, it makes sense to build HttpResponse using the output binding value as the content for HttpTriggers.

**Comment by anthonychu** [comment]
I have concerns about `$return` being a special case in the HTTP worker, because I don't think it's special.

Consider the same function.json in a Node or Python app:

```json
{
  "disabled": false,
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    },
    {
      "type": "signalR",
      "name": "$return",
      "hubName": "chat",
      "direction": "out"
    }
  ]
}
```

There are 2 outputs: `res` is the HTTP output, and `$return` causes the function's return value to the SignalR output binding. If `res` is not set in the function code, the HTTP response body is empty. It would be quite unexpected to see the function return value returned in the HTTP response body. This is consistent across the language workers that we have; I don't think HTTP worker should be any different.

With the same function.json, I think this HTTP worker response:

```json
{
  "Outputs": {},
  "ReturnValue": "some value",
  "Logs": []
}
```

should result in an empty response body from the HttpTrigger.

If we want to return the same thing to the HTTP trigger, it should be done explicitly:

```json
{
  "Outputs": {
    "res": "some value"
  },
  "ReturnValue": "some value",
  "Logs": []
}
```

**Comment by pragnagopa** [comment]
> It would be quite unexpected to see the function return value returned in the HTTP response body. 

Yes!  My earlier comment about building HttpResponse using the output binding value would address this. In the example above, if `res` is set, httpTrigger output would include value of `res` in the body. If not, it would be empty.

From implementation point of view, building http response for httpTrigger was handled by language workers but for HttpWorker, host needs to add this conversion
