### ISSUE TITLE
Add profile based startup options for httpWorker

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#5547]
cc @anthonychu

To configure debug options for HttpWorker, arguments need to passed in host.json as detailed here https://github.com/Azure/azure-functions-host/issues/5463

Profile based start up options would help to differentiate between dev and prod environments.
Another option is to introduce a start up environment variable.

**Comment by anthonychu** [comment]
I think both OS-specific commands and an ability to override with environment variables would be great:

* Provide the ability to specify commands for Windows, macOS, and Linux (this would be for non-debug scenarios)
* Allow the ability to override exe path, worker path, and args using environment variables. This allows debug task launchers like VS Code to start the worker with the debugger enabled.

**Comment by pragnagopa** [comment]
cc @yojagad 
@anthonychu  - Would providing documentation on how to override host.json options via environment variables would be enough for this issue?

**Comment by anthonychu** [comment]
Possibly. I'm currently doing this [here](https://github.com/anthonychu/azure-functions-deno-template/blob/bc093af/local.settings.json#L6). It's a bit verbose, but I'd be okay with documenting it to see if there's demand for something better.

Does this work for the `arguments` array as well? This might not be necessary for different OSes, but needed to enable debugging.

**Comment by pragnagopa** [comment]
Good point about arrays. Sent a PR to add support to override arguments list.
Also, added docs label this issue to help us track adding documentation.
