### ISSUE TITLE
Need README for getting started with HTTP worker

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-host#5549]
I'm starting in this repo: https://github.com/pragnagopa/functions-http-worker

I wanted to try using the HTTP worker. I see there are several examples, but there is no `README.md` file that tells me how to get started. At a minimum, my hope is that it would answer the following questions (even if extremely briefly):

* What is the "HTTP worker" feature?
* Why would I use this instead of the other Functions programming models?
* What are the limitations of this feature (e.g. only supports languages that can listen to HTTP)?
* What tooling can I or should I be using to create an "HTTP worker" function app (VS, VS Code, portal, core tools)?
* What do the properties in the `host.json` file correspond to?
* Special instructions for .NET precompiled (should I create a new function app project? Do I need a function.json file? Do I need a `bin` directory?)
* Minimal examples in a few different languages (e.g. .NET, JS, Rust, Go)
* How can I test to see whether my function is working correctly?

Having samples is good, but they are lacking context. A README is needed to provide the right set of context so that the samples can be understood.

**Comment by pragnagopa** [comment]
Thanks! Assigning to @mattchenderson  and myself to add more documentation.

**Comment by pragnagopa** [comment]
cc @anthonychu 
Documentation is now available for the feature: https://docs.microsoft.com/en-us/azure/azure-functions/functions-custom-handlers 

Repo: https://github.com/Azure-Samples/functions-custom-handlers has more sample with ReadMe for each of them.

Closing this addressed.
