### ISSUE TITLE
Function App suddenly fails with unable to resolve type exception

### ISSUE THREAD

**Issue by Smoovsky** [Azure/azure-functions-host#5552]
We have this function app running for quite a while but it suddenly started failing out all requests from 2020-Jan-22.

Exception log shows it can't resolve a dependency when activating, but we haven't deployed any changes to it for quite a while(half a year or so).

#### Investigative information

Please provide the following:

- Timestamp:2020-01-27T23:18:37.8816262Z
- Function App version (1.0 or 2.0): 2.0
- Function App name: GlobirdEmailSendgridEmailEventLogService20190919070934 
- Function name(s) (as appropriate):
- Invocation ID:64f49c40-a546-4c9f-93be-47c89e31215e
- Region:Australia Southeast

**Comment by imran-cefalo** [comment]
This might be related to a latest update in function environment. [#Ref](https://github.com/Azure/azure-functions-host/issues/5414)

**Comment by Smoovsky** [comment]
> This might be related to a latest update in function environment. [#Ref 5414](https://github.com/Azure/azure-functions-host/issues/5414)

I feel the fact that updating the function runtime simply causes the existing code to crash is a really bad idea...
