### ISSUE TITLE
Dependency Injection in Azure Functions results "Unable to resolve service for type..." error

### ISSUE THREAD

**Issue by ThapaMahesh** [Azure/azure-functions-host#5553]
Hi,

I had a azure function running when it suddenly didn't and returned the error:
`Unable to resolve service for type...`
Which is surprising for I have other azure functions with DI running without issue.

All functions work fine in local system.

**Comment by brettsam** [comment]
Can you provide some more details for us?
- Is this a consumption or premium or app service plan?
- Can you share when you saw this error?
- Can you share your Function App name (either explicitly or [privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately))

I can see if I find anything from the backend logs.

**Comment by ThapaMahesh** [comment]
The functions are in **Basic** plan. The error started since Friday.
I created another in **Consumption** plan to test with same result

`2020-01-29T08:35:22.406 [Error] Executed 'Get-current-tickets-from-department' (Failed, Id=16ad1691-350d-4c45-97b1-a5a86a19b88d) North Europe`

**Comment by siji147** [comment]
@ThapaMahesh please confirm that the host.json file in your function app is not empty. I think there is a new update on Function App that enforces function apps to contain host.json file.

**Comment by ThapaMahesh** [comment]
the host file contains
`{
    "version": "2.0"
}`

**Comment by brettsam** [comment]
@ThapaMahesh -- can you check that this host file is being deployed to Azure? It doesn't appear that it is, and you're running into a bug that was introduced recently when a host.json file is missing. It causes us to incorrectly inject the usage of extensions bundles, which means we're not calling your startup class.

We see this in your logs, which means that there was no host.json, so we generated one for you:
```
Host configuration file read:
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  }
}
```

If you make sure to deploy the default host.json from above, it should get back to working again.

//cc @soninaren
