### ISSUE TITLE
Unable to create Function App

### ISSUE THREAD

**Issue by kanth-matsa** [Azure/azure-functions-host#5556]
#### Investigative information

Please provide the following:

- Timestamp: 29-Jan-2020 03:23 AM IST
- Function App version (1.0 or 2.0):Through portal
- Function App name:gm-dev-function
- Function name(s) (as appropriate):
- Invocation ID:
- Region:West US

My steps to reproduce....always fails for me.
Click Create a resource
Type Function App into "Search the Marketplace" textbox.
On the function App Create page, click Create button.
On the "BASICS" tab,

I choose an existing Resource Group
I choose gm-dev-function in the function app Name
I choose .net core in runtime stack
I chose both East US and Central US
On the hosting Tab.

I choose to create a new storage account and given the name gmdevstorage.
Windows os
Consumption Plan for Plan type.
On the Monitoring Tab:
NO to application insights
Click Review and Create

Validation fails
"The template deployment 'Microsoft.Web-FunctionApp-Portal-569bbb3b-acab' is not valid according to the validation procedure. The tracking id is 5dd36329-b2a9-4e68-9995-9f73187e4b94.' See inner errors for details" with an arrow seemingly indicating that you can see more details...but you can't.

But after changing the function app and storage account names then I can able to create. I think the reason might be while giving the names to function app and storage account the unique name validation is not happening properly. This may be the issue in azure portal. It better some from support team from Azure look into this azure.

Real scenario is when first time giving names for function app is "gm-dev-function" and storage account is "gmdevstorage". As per attachment it is showing "gm-dev-function" is valid but actually this name already exist in portal. After changing name to "gm-dev-function-0001" then i can able create it. Same thing happened for storage account also.

![Function App](https://user-images.githubusercontent.com/60366657/73309175-c4cb7200-4247-11ea-809a-67e31d65632a.PNG)
![storage account name for function app](https://user-images.githubusercontent.com/60366657/73309184-c8f78f80-4247-11ea-8364-8337ed6dc309.PNG)

**Comment by pragnagopa** [comment]
I am unable to repro this issue.

@ammanifold  is there way to look up the error details using tracking id is 5dd36329-b2a9-4e68-9995-9f73187e4b94?

**Comment by ammanifold** [comment]
> I am unable to repro this issue.
> 
> @ammanifold is there way to look up the error details using tracking id is 5dd36329-b2a9-4e68-9995-9f73187e4b94?

Yes I will send you the extension analyzer link
