### ISSUE TITLE
Can't change functions version for Linux App Service Plan app V2 => V3

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#5559]
For most function apps, you can change which major version of the functions runtime you run on by the toggle on "Function app settings" (or FUNCTIONS_EXTENSION_VERSION, although Node.js also needs WEBSITE_NODE_DEFAULT_VERSION changed on Windows).

For Linux app service apps, this won't work.

Instead, you need to go to Platform features => Container settings
![image](https://user-images.githubusercontent.com/8888531/73318892-a46fc900-41ef-11ea-9bf0-547f17db041d.png)
And then change the image name:
![image](https://user-images.githubusercontent.com/8888531/73318922-b81b2f80-41ef-11ea-9cb8-462123c9c757.png)
(Ex: mcr.microsoft.com/azure-functions/dotnet:3.0-appservice)

cc: @balag0 @divyagandhii @anirudhgarg

**Comment by jongio** [comment]
I would very much appreciate a fix for this.   It surfaces in Logs as this:
```
Could not load file or assembly 'System.Text.Json, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
```

When using System.Text.Json and it took us a couple of days to figure out what is going on.

Thank you!

**Comment by mhoeger** [comment]
cc: @dariagrigoriu

**Comment by jongio** [comment]
@gzuber Should this be resolved with this PR? https://github.com/Azure/azure-cli/pull/12317/?

**Comment by gzuber** [comment]
@jongio That's a good point, thanks.

@mhoeger is this valid since the changes @pragnagopa made to linuxFxVersion?

**Comment by pragnagopa** [comment]
cc @ankitkumarr 
As of ANT86.2, updating 'FUNCTIONS_EXTENSION_VERSION' will update the functions runtime used.

**Comment by ankitkumarr** [comment]
Yes this is now fixed. Any new function apps that are created, can be upgraded with just the App Setting.
