### ISSUE TITLE
Function returns 404 error when created through portal on Linux dedicated

### ISSUE THREAD

**Issue by gzuber** [Azure/azure-functions-host#5564]
I was able to repro this by using azure cli to create a function app on a linux app service plan, then going to the portal and creating an in-portal js http webhook function. From the logs it looks like status pings return 200 but the created function returns 404.

I haven't yet had the time to try this on other setups/platforms

**Comment by Noituri** [comment]
Same thing happens to me

**Comment by fabiocav** [comment]
Still investigating. Moving to sprint 70.

**Comment by gzuber** [comment]
After an investigation, I believe this is related to File watchers being unreliable in Linux containers. It's worth noting this seems to be contained to *only* when you make a new function in the portal from the default template. As soon as you hit "Save and Run" or restart the app, it should be working. Also, other deployment methods and using Run From Package should work fine as well. @Noituri please let me know if you're still having issues with this or if the above don't work.

I'm opening up another issue to track exploring improving reliability of file watchers on linux
