### ISSUE TITLE
Add task to devops pipeline to validate that changes have been brought in from WebJobs

### ISSUE THREAD

**Issue by gzuber** [Azure/azure-functions-host#5566]
We need some kind of validation before release that a new official version of WebJobs has been released and the newest changes have been brought in to the host.

Should be a task in this pipeline: https://azfunc.visualstudio.com/Azure%20Functions/_releaseDefinition?definitionId=13&_a=definition-pipeline

**Comment by fabiocav** [comment]
Done.
