### ISSUE TITLE
Kudu api does not list functions when using HttpWorker

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#5587]
Kudu Api: `{scmsite}/api/functions` does not return functions list when using httpWorker

**Comment by pragnagopa** [comment]
API: `https://siteName/admin/functions?code=masterkey` works.

@ankitkumarr / @Hazhzeng  - Can you please point me to code for list functions api on kudu?

**Comment by Hazhzeng** [comment]
@pragnagopa https://github.com/projectkudu/kudu/blob/91aa97089b2f4cab997883d2ce902507ddd7e0ec/Kudu.Services/Functions/FunctionController.cs#L86

**Comment by pragnagopa** [comment]
Fixed Kudu Api. Need to add comment in the host.
