### ISSUE TITLE
Scale controller doesn't work for Trigger Sources that are VNet protected, i.e ServiceBus

### ISSUE THREAD

**Issue by davec643** [Azure/azure-functions-host#5592]
I have an Elastic Premium App Service Plan function that is integrated into my VNet using the new VNet Integration feature. The function takes messages from a ServiceBus queue. The queue grew to over 1 million items and the function app did not scale out. The ServiceBus has Firewall rules in place to only accept traffic coming from within the VNet. I removed the Firewall rules from the Service Bus as a test, and the autoscale of the function worked correctly.

Is it possible that wherever the scale controller sits, is outside of our VNet and thus can't monitor the queue depths to determine whether to scale?

Below I will provide 2 invocation IDs, the first is during a period of time where the Firewall Rules are enabled on the Service Bus, the second will be when the Firewall rules are disabled on the Service bus.

#### Investigative information

Please provide the following:

- Timestamp: see beside invocation ID
- Function App version (1.0 or 2.0): **2.0**
- Function App name: 
- Function name(s) (as appropriate): 
- Invocation ID: 
  - **0077a672-cb51-41f5-bd02-70c88fd6f207 - with Firewall rules (2020-02-04T11:25:18.621Z)**
  - **b42d2346-5aed-47e7-896f-26694ebafa3a - without Firewall rules (2020-02-04T14:09:29.022Z)**
- Region: **UK West**

#### Repro steps

Provide the steps required to reproduce the problem:
1. Create Virtual Network
2. Create a Subnet with Service Endpoints enabled for the Service Bus, delegate the subnet to the Microsoft.Web/Serverfarms
3. Create a Service Bus with 1 queue 
4. Add Firewall Rules to the Service Bus so that only traffic from the Subnet within the Virtual Network is allowed.
5. Create a Function App that is hosted on the Elastic Premium app service plan
6. In the Networking settings of the Function App, configure the VNet Integration and assign it to the subnet created earlier.
7. Deploy code to the Function app that listens for messages on the Service Bus queue.
8. Add 1 million (or fewer may do?!) messages to the queue.
9. Observe the number of function host instances in App Insights using the below query:
```
requests | 
where cloud_RoleName =~ 'FUNCTION_APP_NAME' | 
distinct cloud_RoleInstance |
take 100
```

#### Expected behavior

The Scale Controller observes that the queue is growing and determines that it needs to scale.

#### Actual behavior

The Scale Controller cannot get past the Service Bus firewall (presumably) to check queue depth, and never scales past 1 instance.

#### Known workarounds
Turn off the Firewall rules on the Service Bus.

#### Related information 

Provide any related information 

* Programming language used - C#
* Bindings used - ServiceBusTrigger

**Comment by ankitkumarr** [comment]
@alexkarcher-msft, do you have any input on this -- issues with Scale controller not working when service bus only accepts traffic from a VNET? Or do you know who might be able to help here?

**Comment by alexkarcher-msft** [comment]
Hello. This is the setting you're looking for:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-networking-options#virtual-network-triggers-non-http

**Comment by davec643** [comment]
@alexkarcher-msft Thanks for that, can't believe I didn't come across this when trawling through documentation! 

Are you aware of a scenario where a VNet Integrated function app would not want this functionality? It seems strange to have an option for it...?

**Comment by alexkarcher-msft** [comment]
Yep, it's in that note at the bottom of the trigger section:

"When enabling virtual network trigger support, only the trigger types above scale dynamically with your application. You can still use triggers not listed above, however they are not scaled beyond their pre-warmed instance count. See triggers and bindings for the complete list of triggers."

**Comment by ankitkumarr** [comment]
Thanks @alexkarcher-msft and @davec643!

I am going to close this as answered. If there's further questions, please let us know and we can re-open.
