### ISSUE TITLE
Allow custom bindings to index functions by registering `IFunctionProvider`

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-host#5596]
Today Host uses one implementation of `IFunctionMetadataProvider` to index functions.

We want to also enable bindings to register customer instances of `IFunctionMetadataProvider`. Host would then go over all the registered `IFunctionMetadataProvider` and build the functions registry. 

Details TBD.

**Comment by fabiocav** [comment]
Initial design and implementation completed in sprint 69. Targeting sprint 70 for completion.

**Comment by anthonychu** [comment]
This sounds super interesting. Do you have a more detailed design or spec? @fabiocav @ankitkumarr

**Comment by fabiocav** [comment]
Work is almost complete on this, moving to sprint 72 for remaining items.

**Comment by fabiocav** [comment]
Currently blocked on some design details. Moving to sprint 73

**Comment by ankitkumarr** [comment]
Closed by https://github.com/Azure/azure-functions-host/commit/0af7d3682f788441f2cc46c21329b34e8e496673
