### ISSUE TITLE
System.DllNotFoundException

### ISSUE THREAD

**Issue by momolder** [Azure/azure-functions-host#5597]
The issue is related to debugging the function app, as we use Microsoft.EntityFrameworkCore.Sqlite for debugging and Microsoft.EntityFrameworkCore.SqlServer both 3.1.1.

After updating a function app to V3 we get a System.DllNotFoundException for e_sqlite3.dll which is referenced by Microsoft.EntityFrameworkCore.Sqlite.
After further investigation, the dll is located under: netcoreapp3.1\runtimes\win-x64\native\e_sqlite3.dll.
If the dll is moved to netcoreapp3.1\e_sqlite3.dll everything works as expected.
We already upgraded to Microsoft.NET.Sdk.Functions 3.0.3.

#### Investigative information
- Timestamp: 05.02.2020
- Function App version: v3

#### Repro steps

Provide the steps required to reproduce the problem:
Setup a standard httpTrigger function and add Microsoft.EntityFrameworkCore.Sqlite package.
(See sample project (V2 works V3 doesn't))

#### Expected behavior
The Function should work with sqlite

#### Actual behavior
It doesn't work

#### Known workarounds
setup a postbuild event like:
xcopy $(OutDir)\bin\runtimes\win-x64\native $(OutDir)\bin /i /q /y

#### Related information 

Provide any related information 
SampleProject to demonstrate the issue (V2 works V3 doesn't):
[FunctionApp1.zip](https://github.com/Azure/azure-functions-host/files/4158528/FunctionApp1.zip)

**Comment by soninaren** [comment]
@brettsam is this expected?

**Comment by brettsam** [comment]
Not expected; I'd assume they both work the same. Will add it to the next sprint for investigation.

**Comment by fabiocav** [comment]
@momolder are you still experiencing this issue with the latest version of the SDK?

**Comment by momolder** [comment]
> @momolder are you still experiencing this issue with the latest version of the SDK?

Yes, with Microsoft.NET.Sdk.Functions 3.0.6 the issue still exists.

**Comment by yojagad** [comment]
@momolder We took a look at this. It looks like the SqlitePCLRaw.bundle that comes with the 3.x and above version of EntityFrameworkerCore.Sqlite seems to have it's own probing mechanism for assemblies as opposed to relying on the CLR (and consequently the function runtime's AssemblyLoadContext). We'll follow up with them to see if there's a solution to this.

Meanwhile, downgrading the v3 version to 2.2.6 version of EntityFrameworkCore.Sqlite (the one in the v2 sample you provided) seems to work as mitigation.

**Comment by yojagad** [comment]
You can check this link to see if it helps
https://github.com/ericsink/SQLitePCL.raw/blob/4d424abfa1d2423420156940dc5db236b3d209c5/README.md#a-trio-of-packages

Alternatively, you can also consider moving away from SQLLitePCL with respect to functions.

**Comment by fabiocav** [comment]
Closing this in favor of #5940. We may need to collaborate with the team maintaining SQLLitePCL in order to resolve this, as there are some issues with their approach.
