### ISSUE TITLE
DI and Custom Binding configuration in Startup.cs | FunctionsStartup

### ISSUE THREAD

**Issue by vidhyasagarreddy** [Azure/azure-functions-host#5598]
Seems like IFunctionsHostBuilder doesn't support AddExtesion, like IWebJobsStartup does. 

@gynet and @PiotrWachulec were also talking about the same at: https://github.com/Azure/azure-functions-host/issues/4566

**Comment by vidhyasagarreddy** [comment]
@brettsam - any update on this ?

**Comment by brettsam** [comment]
There's nothing stopping you from using `IWebJobsStartup` with functions if you need to add your own extensions. 

This should get called just like a `FunctionsStartup` would:

```
[assembly: WebJobsStartup(typeof(MyWebJobsStartup))]

namespace MyFunctionApp55
{
    public class MyWebJobsStartup : IWebJobsStartup
    {
        public void Configure(IWebJobsBuilder builder)
        {
            // add extension...
        }
    }
}
```
