### ISSUE TITLE
Azure Functions Host debugging

### ISSUE THREAD

**Issue by OneCyrus** [Azure/azure-functions-host#5600]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
I would like to search the root cause of the dependency injection issue outlined here: https://github.com/Azure/azure-functions-dotnet-extensions/issues/34

my question is how can I start the host from the source and start my own function? the E2E tests always give me errors with the storage variable. Do i need need to specify a storage account for the host somehow? When yes, how can I do this? Or is there a simple example where I can run the Host?

**Comment by pragnagopa** [comment]
To debug locally
- Set WebJobs.Script.WebHost as the startup project
- Set the AzureWebJobsScriptRoot environment variable to the full path to the function samples directory.
- Set any necessary environment variables to run your sample functions (see above).
- F5 to run

Please see: https://github.com/Azure/azure-functions-host/wiki#samples for detailed instructions.

@soninaren - Can you please add instructions on how to use bundles when running locally?

**Comment by OneCyrus** [comment]
thanks for the explanation!

the host starts but no functions are registered as far as i can tell. also the issue is probabaly related to the mentioned extenion bundles as i get a handled exception because startupTypes is null. what are extenion bundles and how do i register them? @soninaren 

![image](https://user-images.githubusercontent.com/7747800/79112141-2fd41180-7d7e-11ea-8e75-01b8bd1fef79.png)

**Comment by soninaren** [comment]
Have added the information here.
https://github.com/Azure/azure-functions-host/wiki#extension-bundle-configuration
