### ISSUE TITLE
[HttpWorker]Add configuration flag in opt-out of http trigger request forward

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#5615]
cc @fabiocav @mattchenderson 

Currently, if function has only httpTrigger functions host acts as a proxy forwards request to and from HttpWorker. https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Workers/Http/DefaultHttpWorkerService.cs#L50

If using HttpTrigger with other bindings, request content to HttpWorker  has the format defined here: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Workers/Http/HttpScriptInvocationContext.cs

Need to figure out if we should have two models or just one.

**Comment by anthonychu** [comment]
I think both are valid, depending on what perspective you're coming from.

If I'm authoring a language worker on top of HttpWorker, I do not want the current behavior that changes based on whether there's an output binding. Right now I have to check the function metadata to decide which payload to return and that adds a complexity.

If I am running an express.js or ASP.NET Core app as my HttpWorker and I just want to host HTTP endpoints, having the passthrough is nice and I can run an existing web app with no modifications.

I suggest that we choose a default behavior and allow opting into the other behavior with a configuration. I feel that the current behavior (forwarding the response iff it's an HTTP trigger *and* there are no other output bindings) can cause confusion and it should be explicitly opt-in. This could be for the whole app using a setting in host.json, or per function in the binding metadata.

**Comment by pragnagopa** [comment]
Thanks for the feedback. An opt-in configuration at function level makes sense. I will update this issue with proposed design.

**Comment by anthonychu** [comment]
I think this is a good change and should be done pretty soon before too many apps depend on the proxy behavior.
