### ISSUE TITLE
Registering Typed HttpClient to DI doesn't work

### ISSUE THREAD

**Issue by Peter-Juhasz** [Azure/azure-functions-host#5617]
## Investigative information

https://github.com/dotnet/extensions/issues/2847

Please provide the following:

- Timestamp: 2020. 02. 07.
- Function App version (1.0 or 2.0): 2.x
- VS: Visual Studio 2019 16.5 Preview 2
- .NET Core: 3.1.x

- Function App name: local
- Function name(s) (as appropriate): local
- Invocation ID: local
- Region: local

#### Repro steps

```cs
[assembly: FunctionsStartup(typeof(App.Server.Function.Startup))]
namespace App.Server.Function
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var services = builder.Services;

            services.AddSingleton<SendGridClient>().AddHttpClient<SendGridClient>(client =>
            {
                // this code never runs
                client.BaseAddress = new Uri("https://api.sendgrid.com/v3/", UriKind.Absolute);
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", configuration["SendGridApiKey"]);
            }).AddPolicyHandler(DefaultRetryPolicy);
        }
```

The `HttpClient` is not properly set up:

```cs
    public class SendGridClient
    {
        public SendGridClient(HttpClient httpClient, ILogger<SendGridClient> logger)
        {
            HttpClient = httpClient; // no BaseAddress configured
            Logger = logger;
        }
```

#### Expected behavior

While it is registered exactly the same way in an ASP.NET Core 3.1.1 application and it works as expected. As we use the official DI and Http extension packages, I expect the same behavior at all places. Now, we can't share services/components as they work everywhere else, except in a Function. Also, there is no error message at registration time/DI build time/startup time, we have to try all injected services to find out whether they were registered correctly or not.

#### Actual behavior

DI and Http extension doesn't work in a Function.

**Comment by NatMarchand** [comment]
`services.AddSingleton<SendGridClient>().AddHttpClient<SendGridClient>`
You're registering twice SendGridClient, try removing the AddSingleton.
Also, you can't have SendGridClient as a singleton as it contains a dependency on the httpclient which might have a shorter lifetime. If you want it really as a singleton, consider injecting HttpClientFactory inside SendGridClient instead.

**Comment by brettsam** [comment]
I believe @NatMarchand has provided the correct answer. If you remove `AddSingleton<SendGridClient>()` it should work.
