### ISSUE TITLE
Azure Functions v3 ability to specify RuntimeIdentifier

### ISSUE THREAD

**Issue by vitalybibikov** [Azure/azure-functions-host#5618]
The question is related to:
- Azure Functions v3.x
- TargetFramework : netcoreapp3.1

Is it possible right now to specify concrete Runtime Identifier for the function app?

e.g. 

`   <RuntimeIdentifier>win-x64</RuntimeIdentifier>`

It will allow to use the new features of 3.1, that I believe will drastically improve performance and cold starts.

For Instance, with a runtime specified, output package of my application becomes 2 times smaller
**60 Mb => 33 Mb** due to the amount of runtimes, that are published together with the app, but are not required.

Or to specify the configuration like below in order to:
- reduce the size of the app, 
- make it ready-to-run to save the time on JITting
- publish it as a single file (which might be quicker to load in memory)
- trim everything that is not actively used.

```
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
```
 
Thanks

**Comment by fabiocav** [comment]
Yes. As of the last release, Ready-to-run payloads are now fully supported. We'll have some documentation with guidance on this very soon.

**Comment by vitalybibikov** [comment]
Though, currently if RuntimeIdentifier is specified funcapp wors only locally.
Can you share an example of a valid config?

**Comment by vitalybibikov** [comment]
So, yeah


Currently only this configuration works in prod:

```
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <PublishReadyToRun>true</PublishReadyToRun>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
  </PropertyGroup>
```


While it is imposible to specify the parameters below:

```
<PublishTrimmed>true</PublishTrimmed>
<PublishSingleFile>true</PublishSingleFile>
```

as they require to be specified

`<OutputType>Exe</OutputType>`


Though this is desired, as it will reduce the package size.
