### ISSUE TITLE
unable to add event subscription to the python azure event grid trigger function. error with API management

### ISSUE THREAD

**Issue by gvsireesh** [Azure/azure-functions-host#5622]
Hi,
I have created an azure functionV3 event grid trigger in python. When I try to subscribe event for c# function I can do it easily from portal however for functions written in python it is suggested to use CLI. 
To create event grid subscription I need function **endpoint URL**, to find this I have tried 
`Invoke-RestMethod -Uri "https://{functionAppName}.azurewebsites.net/admin/host/systemkeys/eventgridextensionconfig_extension?code={masterKey}" `
above statement always returns error
**Invoke-RestMethod : The remote server returned an error: (404) Not Found.**

Can somebody let me know how to add event subscription to the azure function written in python.

**Comment by kashimiz** [comment]
Hi @gvsireesh, have you seen this documentation for [creating an Event Grid subscription in the CLI?](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid?tabs=python#azure-cli)

It looks like you're using the system key API for the 1.x runtime. For 2.x (and higher) runtimes, this is system key API:

```http://{functionappname}.azurewebsites.net/admin/host/systemkeys/eventgrid_extension?code={masterkey}```

**Comment by gvsireesh** [comment]
Hi @kashimiz, thank you for the update the command worked to retrieve system key. However I'm having issues in creating event-subscription. When I use the syntax provided in the article you mentioned :
```
az eventgrid resource event-subscription create -g myResourceGroup \
--provider-namespace Microsoft.Storage --resource-type storageAccounts \
--resource-name myblobstorage12345 --name myFuncSub  \
--included-event-types Microsoft.Storage.BlobCreated \
--subject-begins-with /blobServices/default/containers/images/blobs/ \
--endpoint https://mystoragetriggeredfunction.azurewebsites.net/runtime/webhooks/eventgrid?functionName=imageresizefunc&code=<key>
```
I got the below error:
**az eventgrid: 'resource' is not in the 'az eventgrid' command group. See 'az eventgrid --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview**

Then I tried other command provided in [Event Grid Subscription](https://docs.microsoft.com/en-us/cli/azure/eventgrid/event-subscription?view=azure-cli-latest#az-eventgrid-event-subscription-create)

`az eventgrid event-subscription create --name mlEventStub --source-resource-id "/subscriptions/{SubID}/resourceGroups/{rgname}/providers/Microsoft.Storage/storageaccounts/{name}" --subject-begins-with /blobServices/default/containers/images/ --included-event-types "Microsoft.Storage.BlobCreated" --endpoint 'https://{functionname}.azurewebsites.net/runtime/webhooks/eventgrid?functionName=defectdetection&code={code}'`

Now I'm receiving different error  

**Deployment failed. Correlation ID: 148bc204-0bb1-4ffc-9663-dbcc0327d93b. The attempt to validate the provided endpoint https://defectdetection.azurewebsites.net/runtime/webhooks/eventgrid failed. For more details, visit https://aka.ms/esvalidation.**


can you please here.
When I verify event subscription security [page](https://aka.ms/esvalidation)

 **When you use any of the three Azure services listed below, the Azure infrastructure automatically handles this validation:

Azure Logic Apps with Event Grid Connector
Azure Automation via webhook
Azure Functions with Event Grid Trigger**

**Comment by v-anvari** [comment]
Hi @gvsireesh , Apologies for the delayed response, Did you find a solution to the error?

Let us know if you are still facing an issue so that we will look into it.
