### ISSUE TITLE
Document new APPLICATIONINSIGHTS_CONNECTIONSTRING app setting

### ISSUE THREAD

**Issue by gzuber** [Azure/azure-functions-host#5623]

**Comment by ggailey777** [comment]
We're now tracking this in the Docs DevOps here: https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1674832

**Comment by gzuber** [comment]
@ggailey777 I've created a PR for this change if you could take a look. Thanks! https://github.com/MicrosoftDocs/azure-docs/pull/50298

**Comment by fabiocav** [comment]
Closing this issue as we have an open PR and an issue tracking the work.
