### ISSUE TITLE
Do not allow new executions while stopping host

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#5624]
It's possible for executions to be invoked even when the host is shutting down. We should prevent this as any executions will fail (this was from a V2 app, same problem may exist in V3)

Sample order of execution:
| Logs |
| -- |
| Executed   'Functions.EventHubTrigger' (Succeeded,   Id=e38f4220-5676-4275-8fae-7bf34a09cdbf) |
| Shuttingdown Rpc Channels Manager |
| Shutting down language worker channels   for runtime:java |
| Stopping host... |
| Active host changing from   '78f4a98c-b911-4ff9-bf11-e554fe23666b' to '(null)'. |
| Waiting for   RpcFunctionInvocationDispatcher to shutdown |
| Draining invocations from language worker   channel completed. Shutting down 'RpcFunctionInvocationDispatcher' |
| Stopping JobHost |
| Executing   'Functions.EventHubTrigger' (Reason='',   Id=0c0ad75c-5f87-4f23-8758-0fb1b25c9d46) |
| Sending invocation   id:0c0ad75c-5f87-4f23-8758-0fb1b25c9d46 |
| Executed   'Functions.EventHubTrigger' (Failed,   Id=0c0ad75c-5f87-4f23-8758-0fb1b25c9d46) |
| Job host stopped |
| Disposing ScriptHost. |
| Host instance   'f24db492cd0f25952686aa03ae5b98a9' released lock lease. |
| Disposing FunctionDispatcher | 
| Host shutdown completed. |
| Shutting down RPC server |

**Comment by mhoeger** [comment]
cc: @fabiocav - maybe makes sense to take this sprint? Or next?

**Comment by fabiocav** [comment]
Agreed. Feel free to assign it to current if you have the cycles.

**Comment by pragnagopa** [comment]
Adding more context regarding executions in language worker layer. When the host is shutting down, language worker layer is only trying to finish executions that are already started by webjobs sdk. 
@yojagad  improved this case by adding grace period to drain invocations in flight:
https://github.com/Azure/azure-functions-host/blob/e0c370585ffe96ed00fdfd77626cbd7b56dd0a50/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs#L220-L232

We should consider increasing the shutdown timeout as we are seeing it takes more then 10secs to drain inflight invoications specifically for eventhub trigger as number of invocations is typically large for eventhub tigger.

**Comment by mhoeger** [comment]
Fixed with: https://github.com/Azure/azure-functions-host/pull/5668

**Comment by hkharan** [comment]
@mhoeger @pragnagopa  can you help with status update for fix on Windows

**Comment by pragnagopa** [comment]
Please see https://github.com/Azure/app-service-announcements/issues/240 for updates on the release. All releases are currently blocked. Current ETA is end of this month.

**Comment by hkharan** [comment]
@pragnagopa I see a note on https://github.com/Azure/app-service-announcements/issues/240 indicating that the version will not be released. Is there any new ETA or version ?

**Comment by pragnagopa** [comment]
Yes @hkharan - we will have new release announcement by next week.

tagging @mhoeger  and @yojagad - to ensure next release contains this commit.

**Comment by hkharan** [comment]
@pragnagopa @mhoeger @yojagad Do we have any updates on the new release yet? Is there a place to track the new announcement?

**Comment by mhoeger** [comment]
@hkharan - release has been cut and is undergoing testing this week. thanks for your patience!

**Comment by hkharan** [comment]
@pragnagopa  @mhoeger  @yojagad  Hope the testing went as expected. Do we have a release date yet? Thanks!

**Comment by mhoeger** [comment]
Sorry for the delay, this fix has been released. Please create a new issue (with Functions version) if this issue still appears to happen.
