### ISSUE TITLE
Backfill linuxFx version for existing function apps

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#5628]
cc @ankitkumarr @anirudhgarg @divyagandhii 

For consistent UX version selectiongexperience across existing function apps and new function apps, need to update
-  linuxFxVersion to follow format: runtime | version for both consumption and dedicated
- Delete `container` from kind property for dedicated linux apps
- Remove `WEBSITE_NODE_DEFAULT_VERSION` app setting for both consumption and dedicated

**Comment by pragnagopa** [comment]
need to backfill for consumption apps and dedicated apps that use blessed images.

**Comment by ankitkumarr** [comment]
@pragnagopa, today all clients use the older format for LinuxFxVersion. Even after we update the clients, people still may be using older versions of Azure CLI, VS Code extension or mvn.

Is the goal to backfill every single app so portal doesn't have to deal with apps with old format? It might be a bit difficult to have every single app moved to the new format.

**Comment by pragnagopa** [comment]
@ankitkumarr / @Francisco-Gamino  - please update the clients to use new format ASAP. Also, please link the tracking issues here.

@ankitkumarr - Yes, the goal is to avoid special logic on Ux to handle older formats. Backfill will be a one time operation to ensure we provide consistency across all the apps. After backfilling and all the clients are updated to use to new format, if users continue to create using older format they have to correct themselves.

**Comment by pragnagopa** [comment]
az-cli tracking issue to update create flow - https://github.com/Azure/azure-cli/issues/11257

**Comment by Francisco-Gamino** [comment]
@pragnagopa : I have opened an issue for the Az.Functions cmdlets to track this. For more info, please see https://github.com/Azure/azure-powershell/issues/11112

**Comment by pragnagopa** [comment]
Also, need to remove 'container' from kind property for blessed images

**Comment by pragnagopa** [comment]
cc @vijayrkn for updating VS create flow.

**Comment by pragnagopa** [comment]
tagging @EricJizbaMSFT for updating VSCode create flows.

**Comment by EricJizbaMSFT** [comment]
What do you mean "backfill"? What exactly do you want to happen in VS Code?

**Comment by pragnagopa** [comment]
@EricJizbaMSFT - Tagged you as FYI, in case there any changes needed in VS Code. Backend changes needed to support 'linuxFxVersion' have been deployed. az cli and az powershell cli will be updated to set  `linuxFxVersion` site config property following format `runtime | version`.

 @soninaren  - Can you confirm if this is a no-op for VS Code?

**Comment by EricJizbaMSFT** [comment]
When you say "older format" are you talking about `DOCKER|mcr.microsoft.com/azure-functions/...`? We already use a format like `node|12.0` to create consumptions apps, but use the docker format for dedicated/premium apps.

**Comment by pragnagopa** [comment]
Yes, please update for dedicate linux function apps to same format like `node | 12 `
@ankitkumarr  - Can you confirm for premium apps?

**Comment by fabiocav** [comment]
This is expected to span across a couple of sprints

**Comment by pragnagopa** [comment]
After discussing with @divyagandhii and @ankitkumarr  we have decided it is safer to make code changes as part of ANT88 to backfill / update linuxFxVersion and kind properties as of UpdateWebSiteConfig code.

Assigning to @divyagandhii to track this issue in ANT88.

**Comment by pragnagopa** [comment]
closing this issue as it will be tracked as part of ANT88
