### ISSUE TITLE
On worker error, wait for worker initialization if one or more are initializing before sending request

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#5629]
We should not send requests while no worker channels are available AND we're currently trying to start one up. Kindof similar to https://github.com/Azure/azure-functions-host/issues/5624 , but in this case no worker channels are available and were NOT currently trying to start one (because things are shutting down).

In one case, I see a worker process executing find and then run into an uncaught exception (publish WorkerErrorEvent). We dispose the worker channel and go through "Initiating worker Process start up".

The Function Invocation Buffer and all is set up. However, it hasn't started yet and isn't found - likely due to this code: https://github.com/Azure/azure-functions-host/blob/3eb520c7e7946dd2ebaca6fa00ef2562d86fde00/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs#L269

**Comment by pragnagopa** [comment]
cc @yojagad 
Ideally host should never send requests if there are no language workers. Following code:

https://github.com/Azure/azure-functions-host/blob/bd350f348fd48c5ba12d0b540db45003dc915da2/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs#L91-L107

Waits till atlease one language worker starts. If starting worker continues to fail, functions host is shutdown.

Needs more investigation.

**Comment by mhoeger** [comment]
The code above only works if `FunctionInvocationDispatcherState.Initializing`. Maybe if we are down to 0 workers, we set dispatcher state back to "Initializing".

Each language worker channel has an action buffer that delays requests until they're ready too though:
https://github.com/Azure/azure-functions-host/blob/bd350f348fd48c5ba12d0b540db45003dc915da2/src/WebJobs.Script/Workers/Rpc/RpcWorkerChannel.cs#L304

If we remove this check,
https://github.com/Azure/azure-functions-host/blob/3eb520c7e7946dd2ebaca6fa00ef2562d86fde00/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs#L269
requests will go into that queue. One potential error case is if the initializing worker ends up failing to start and we don't modify code to keep those queued requests from being lost or ending in error.

I think either the approach would resolve these issues though

**Comment by pragnagopa** [comment]
Thanks for more details. Check to verify the status of worker channel:
https://github.com/Azure/azure-functions-host/blob/3eb520c7e7946dd2ebaca6fa00ef2562d86fde00/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs#L269

is needed to avoid sending requests even before buffers are setup.

Resetting FunctionDispatcherState is the right approach!
