### ISSUE TITLE
Consume binaries from extension bundle with ReadyToRun enabled

### ISSUE THREAD

**Issue by safihamid** [Azure/azure-functions-host#5630]
To significantly improve Cold Start all extensions need to  built with ReadyToRun enabled.
  <PublishReadyToRun>true</PublishReadyToRun>

We will need to build packages for win-x86, win-x64 and linux-x64 and at runtime load the appropriate  bundles based on the bitness of the process.

**Comment by soninaren** [comment]
related issue, https://github.com/Azure/azure-functions-extension-bundles/issues/9

**Comment by soninaren** [comment]
Extension bundle with ReadyToRun enabled is now available. Need host changes to consume the RR enabled bundle binaries
