### ISSUE TITLE
ARM Deployment of an Azure function app, including a self generated system key, results in an error when the app is in a stopped state

### ISSUE THREAD

**Issue by Joehannus** [Azure/azure-functions-host#5634]
When you try to deploy an Azure function app using an ARM template, which contains a resource section for the app itself and one for the self generated system key, and said function app is in a stopped state, the deployment results in an error. The error in question does not occur when the function app is in a running state.

See also: 
https://github.com/Azure/azure-functions-host/issues/3994#issuecomment-508039025
(@DibranMulder)

The ARM template contains two separate resources sections:
- "type": "Microsoft.Web/sites"
- "type": "host/systemkeys"

And it is deployed using the default Azure CLI deploy statement: "az group deployment create"

The error is as follows:

    {
      "Code": "Unauthorized",
      "Message": "Encountered an error (Forbidden) from extensions API.",
      "Target": null,
      "Details": [
        {
          "Message": "Encountered an error (Forbidden) from extensions API."
        },
        {
          "Code": "Unauthorized"
        },
        {
          "ErrorEntity": {
            "Code": "Unauthorized",
            "Message": "Encountered an error (Forbidden) from extensions API."
          }
        }
      ],
      "Innererror": null
    }

**Comment by brettsam** [comment]
@mathewc -- is this a known issue?

**Comment by mathewc** [comment]
This is by design. Functions ARM APIs ultimately forward to the Function App itself. For some read-only operations the ARM APIs can serve cached info w/o hitting the app, but generally the Function App can't be stopped for the ARM APIs to work properly. If you look in the portal, it should show warnings to this effect if the app is stopped.
