### ISSUE TITLE
High Value Of Private Bytes Metric

### ISSUE THREAD

**Issue by luckerby** [Azure/azure-functions-host#5654]
I'm using some simple C# code on .NET Core to look at how Azure Functions perform. The use case is quite simple: add 10 million int values to an ArrayList as part of an Azure Function, and use a time trigger set to 1 minute to invoke the function. (I know the ArrayList is obsolete and not to be used anymore, but I'm just employing it to get a significant chunk of space allocated on the heap)

Therefore the C# code is this:
```
using System;
using System.Collections;

public static void Run(TimerInfo myTimer, ILogger log)
{
    ArrayList numbers = new ArrayList();
    Random random = new Random(1);
    int noNumbers = 10000000;
    for(int i=0;i<noNumbers;i++) {
        numbers.Add(random.Next(10));
    }

    log.LogInformation($"Created an ArrayList of {numbers.Count} elements");
    log.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");
}
```

For an ArrayList, each boxed int occupies 12 bytes, due to the type object pointer (aka method table address – 4 bytes), the value stored (an int, which takes 4 bytes on either x86/x64) and the sync block index (4 bytes). All these scattered boxed ints total 114.45 MB (12 bytes/object x 10 mil objects). On top of this we have the internal arrays themselves that get allocated in turn, and which take 128 MB (16 bytes + 32 bytes + 64 bytes + … + 32 MB + 64 MB). The total comes up to 242.45 MB. The value can be confirmed by running a similar test method against BenchmarkDotNet.

There's no much else being allocated on the heap aside the value summed above.

Running VMMap against this code (compiled for .NET Framework) shows the private bytes as close to the expected value (I'm assuming one of the GCs gets a chance to free up some of the allocated data up until 242 MB):
![VMMap_ArrayList_10mil_elements_clean](https://user-images.githubusercontent.com/31319583/74615966-b88f5200-512d-11ea-9310-17323abd1300.jpg)

But looking at the performance of the Azure Function, either Function App's "private bytes" or the App Insights' "process private bytes" have considerable higher values (which actually come closer to the overall virtual memory usage as seen in VMMap before):
![AzurePortal_ArrayList_10mil_elements_everyMin_PrivateBytes](https://user-images.githubusercontent.com/31319583/74616087-8500f780-512e-11ea-8fb7-c7cfe8d22f1a.jpg)

As the private bytes go into the cost of the Azure Functions, it's of interest to understand why the value observed is much higher than one would expect it to be. I've expanded on the context of the issue [here](https://mihai-albert.com/2020/02/17/listoft-vs-arraylist-in-azure-functions/#memory-usage).

**Comment by luckerby** [comment]
There are a few more aspects I've been reviewing:
- The "bitness" setting for the Azure FunctionApp that contains the ArrayList Azure function. I was assuming in my original post that the platform target is x86, but haven't really checked. The only such configuration seem to point to x86 code:
![AzurePortal_ArrayListFunctionApp_PlatformBitnessSetting](https://user-images.githubusercontent.com/31319583/74688736-32344800-51e1-11ea-9096-c66cb8990db4.jpg)
- My original VMMap output was based on code targeting .NET Framework, yet the Azure Function that I've been using was using .NET Core. Below is the private bytes data in VMMap for an identical ArrayList code running against .NET Core 3.0, targeting x86. The moment when the code finishes running the code (and as such all the memory allocations) is selected in the timeline, just as in my original post. The private bytes is the metric presumably used ([link](https://github.com/Azure/Azure-Functions/issues/1339#issuecomment-539771855)) in the Azure Function cost calculation
![VMMap_ArrayList_10mil_elements_DotNetCore_PrivateBytes](https://user-images.githubusercontent.com/31319583/74688880-abcc3600-51e1-11ea-9ec3-9211a007a075.jpg)
- Although not the metric we should be interested in - according to the above at least- , the bytes allocated over the lifetime of the function are seen below. The value neither matches the expected memory usage for neither x86 code(~240MB), nor x64 (~500MB). This would suggest x86 code running, but with something extra on top (whose overhead is not negligible), which impacts the private bytes significantly. However, the value observed does come close to the "private bytes" metric measured in the Azure portal for the Azure Function (2nd printscreen in my original post)
![AzurePortal_ArrayList_10mil_elements_AllocatedBytesInCode](https://user-images.githubusercontent.com/31319583/74688983-141b1780-51e2-11ea-8b56-da37dd7c257e.jpg)
- How often is the private bytes metric measured. Assuming this happens rarely, there will probably be just one measurement once the function completes. Assuming the GC recclaims the unused data before the code completes the final memory allocations, for the code sample used the reported private bytes should be around 180 MB(the ArrayList is implemented by allocating object[] arrays whose length double as the number of elements outgrow the current one; for the last such internal array, its length will be 16,777,216 and each object reference is 4 bytes (32-bit platform), thus consuming 67,108,864 bytes (exactly 64 MB); the boxed ints themselves will take 10 mil x 12 bytes = 120,000,000 bytes (~117 MB), yielding a total of ~181 MB, matching quite well the private bytes highlighted in the VMMap output above). If on the contrary, the private bytes values are sampled often, then the "ramping up" in virtual memory usage should be captured as well, and the average metric value should be significantly lower than the ~181 MB above, in order to keep things fair

**Comment by luckerby** [comment]
I've also looked at the assemblies loaded in the AppDomain by the .NET Core local app and the Azure Function respectively, using `AppDomain.CurrentDomain.GetAssemblies()`.

For the .NET Core local app there’s a minimum number of assemblies loaded (code output is [here](https://gist.github.com/luckerby/adc3fc161394072995d50bcbdfa2ce18)) , just as expected, but for the Azure Function one there’s literally a ton (output is  [here](https://gist.github.com/luckerby/42a07aaaec3f65d115609276d401d209)). Judging by the fact that the code one types in the Azure Function actually makes it as an assembly in itself most likely (`f-ArrayList_Function__-1846423553` in the second listing), there’s probably some other piece of code that executes, loads the mentioned assembly and somehow ends up taking up memory in parallel.

**Comment by soninaren** [comment]
cc: @fabiocav , @alrod .

**Comment by v-anvari** [comment]
Hi @luckerby , Apologies for the delayed response. Were you able to find a solution here. Kindly let us know if you are you still facing this challenge?

**Comment by luckerby** [comment]
@v-anvari the only progress I made at the time was to find out from Microsoft Support that the extra memory usage is due to the underling IIS process (as the Azure Function App relies on an App Service). But I don't have a lot of details around that unfortunately. Are there are any pointers you could help with in regards to breaking down the used memory by a Function App?

**Comment by pragnagopa** [comment]
Tagging @mathewc @fabiocav  for further investigation

**Comment by paulbatum** [comment]
@luckerby If you're doing a comparison between a console app versus code running as part of Azure Functions, you'll definitely see a memory usage difference due to the functions runtime itself. Does that explain the main discrepancy you're asking about?

If you compare a locally running function (using functions core tools) to one deployed to Azure, they will be closer as long as you make sure you've got matching process architecture (x86 for example).

Keep in mind that several other factors impact the actual metered usage for consumption functions (some details [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-consumption-costs)). For example, the memory usage is assigned to 128mb buckets, and allocation to those buckets is based on the level of concurrency functions are running at. So its not always the case that increased memory usage translates into a larger bill.

**Comment by paulbatum** [comment]
@luckerby if my comment above didnt answer your question please let me know

**Comment by luckerby** [comment]
@paulbatum Thanks, Paul. I was curious as to what gets allocated inside the AppDomain - that difference from ~248 MB up until ~333 MB in last 2 printscreens of my 2nd post - by the Azure Functions runtime. E.g. how would I be able to see what objects take up that extra memory? Since the ~333 MB value is picked up from within my own code, would there be a way as to see who those "neighbouring" objects are? Would walking the heap be a way forward? Or to take it another way - what are the components inside the runtime that allocate most of that difference?
A lot of questions - I know - and the answers aren't very simple most likely :) I'm simply looking for a starting pointer or some ideas (e.g. go look at this file in the code here, which would be meaningful). I remember looking for documentation around the Azure Functions runtime when I investigated this topic, but there wasn't much talking about what's "under the hood".

**Comment by paulbatum** [comment]
@luckerby You can use Visual Studio's tooling to get more details on this. For example, run the function app and the pause in the debugger and take a memory snapshot:
![image](https://user-images.githubusercontent.com/10663/121937556-a8768b00-ccff-11eb-809f-084abab7fc39.png)

Then click on the snapshot and view the heap:
![image](https://user-images.githubusercontent.com/10663/121937651-c2b06900-ccff-11eb-9682-9e07066c5c23.png)

![image](https://user-images.githubusercontent.com/10663/121938390-9ea15780-cd00-11eb-9dc6-beda21bdd2b2.png)

Do the same for .NET core application and then you'll have details that you can compare.
