### ISSUE TITLE
Cannot create new Azure Function App in Azure Portal

### ISSUE THREAD

**Issue by luthv** [Azure/azure-functions-host#5655]
#### Is your question related to a specific version? If so, please specify:
Azure Functions v3
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question
When I try to create a new Functions App in the Azure Portal the process failed in validation step with this error:
```
"details": {
    "code": "InvalidTemplateDeployment",
    "message": "The template deployment 'Microsoft.Web-FunctionApp-Portal-7c7d33a6-83a2' is not valid according to the validation procedure. The tracking id is '09d6bf7e-eede-4950-a4ec-3e77c1269cd6'. See inner errors for details.",
    "details": [
      {
        "code": "ValidationForResourceFailed",
        "message": "Validation failed for a resource. Check 'Error.Details[0]' for more information.",
        "details": [
          {
            "code": "ServerFarmNotFound",
            "message": "The specified app service plan was not found."
          }
        ]
      }
    ]
  }
```

**Comment by brettsam** [comment]
Some questions that could help us track this down:
1. Was this **Windows** or **Linux**?
2.  What **hosting plan**?
3. What **region**?
4. Does this reproduce if you try again?

**Comment by luthv** [comment]
> Some questions that could help us track this down:
> 
> 1. Was this **Windows** or **Linux**?
Windows
> 2. What **hosting plan**?
Consumption Plan

> 3. What **region**?
I've tried East Asia and Southeast Asia

> 4. Does this reproduce if you try again?
Not always, sometime if I wait and retry the next day I can successfully create the Function App, sometimes it will pass the validation step and failed with server farm not found error during the creation process.

**Comment by pvbchak** [comment]
@luthv , We couldn't find operation in last 7 days. Can you please give more details (time window, any function name in subscription (if you are not comfortable sharing existing function name, please create a function with random name, delete it & then share function name))

**Comment by pvbchak** [comment]
@luthv, Brett helped me locate error and we are looking into this now. Will let you know once we have mitigation / workaround.

**Comment by takyyon** [comment]
@luthv I haven't been able to repro the issue with the above validation error. 
Could you please attach a har file of the issue?  Please follow the steps below to generate the har file.

`Hit F12 on your browser `
	> Refresh browser (F5) - This will clear session caches 
	> Reproduce the issue 
	> Export network trace as HAR file 
         > Zip it up

**Comment by luthv** [comment]
I couldn't reproduce the issue for the past few days either, I'll keep an eye if I encountered it again and post it back here, I'll close the issue in the meantime.
