### ISSUE TITLE
Initial design for E2E Test framework across language worker repos

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#5670]

**Comment by pragnagopa** [comment]
Please see https://github.com/pragnagopa/azure-functions-integration-tests for initial spec and tracking issues.

**Comment by fabiocav** [comment]
Moving to sprint 72 to define scope

**Comment by pragnagopa** [comment]
Assigned this to @Francisco-Gamino as he will be driving this project  and I will continue to collaborate with him.

**Comment by fabiocav** [comment]
Design for this has been done.
