### ISSUE TITLE
Add an admin API to the host to put it in draining mode

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#5672]
We need an API on the function host to put it in a suspended mode, where it stops accepting new incoming traffic / turns off listeners for its trigger. This to facilitate the graceful shutdown. It also needs to have the ability to resume functioning from suspended state.

**Comment by alrod** [comment]
We had an incident related to the issue (internal link https://icm.ad.msft.net/imp/v3/incidents/details/176994970/home):
1. An worker marked as idle, no ping request from scale controller.
2. The worker was able to start a timer execution after 15 mins, the timer trigger listener was not turned off on the worker.
3. After 20 mins the worker was shut down due idle time period but the timer execution was in process.
4. Then another worker started the timer execution immediately due unexpected finishing of the timer execution.

**Comment by fabiocav** [comment]
Closing this as @soninaren will be opening more granular items to track the work.

**Comment by mhoeger** [comment]
Related to https://github.com/Azure/azure-functions-host/issues/5046, I think. @soninaren - I'm going to reopen it for now. Related to another IcM: https://icm.ad.msft.net/imp/v3/incidents/details/190888754/

**Comment by fabiocav** [comment]
@soninaren do you have the decomposed issues to track this work?

**Comment by soninaren** [comment]
Tagging related issues
- https://github.com/Azure/azure-functions-host/issues/6268
- https://github.com/Azure/azure-webjobs-sdk/issues/2527
- https://github.com/Azure/azure-functions-eventhubs-extension/issues/69
- https://github.com/Azure/azure-functions-servicebus-extension/issues/95
- https://github.com/Azure/azure-functions-host/issues/6287

**Comment by Hazhzeng** [comment]
Related to another IcM: https://icm.ad.msft.net/imp/v3/incidents/details/190370140/

**Comment by soninaren** [comment]
This has now been rolled out in release 3.0.14413
