### ISSUE TITLE
ServiceBusTrigger: Consumption Plan Not Scaling Out

### ISSUE THREAD

**Issue by rossbuggins** [Azure/azure-functions-host#5677]
We've got a c# azure function, published from VS in web publish mode (not zip) to consumption based Function Apps.

The function is triggered by service bus queue.

The function takes a few seconds to run (its using tensor flow to complete image classification) - even with 50k items in the queue and new items being added, the function is not scaling above 1 instance. The CPU is showing at 99% and memory at 950mb and doing about 5 requests a second.

Its a v3 function, .net core 3.1, and set as 64 bit.

I've looked through a fair few other posts on here about scaling but can't find an obvious reason to as why this isn't scaling out to more instances.

Thanks,

Ross

**Comment by NatMarchand** [comment]
How many partitions is there in your queue ?
Is the load of messages distributed among all the partitions ?

**Comment by brettsam** [comment]
Does your connection string have Manage rights in SB? We've had an issue with scaling around connection strings that do not have Manage rights...

**Comment by rossbuggins** [comment]
Hi @brettsam, no it didn't, I've given it manage rights, restarted the apps, and straight away its scaled. Did i miss this in documentation anywhere?

**Comment by brettsam** [comment]
No, it's a bug that we're addressing on the Scale Controller as Manage rights shouldn't be required. A fix for this is rolling out but may take a few weeks.
