### ISSUE TITLE
V2 HttpTrigger From Logic App duplicate calls

### ISSUE THREAD

**Issue by njabulomp** [Azure/azure-functions-host#5678]
I am experiencing an issue where the invocation of an http triggered function app from a logic app is happening twice for certain calls, I checked the invocation logs and app insights and did indeed see two calls being made. The logic app is showing one call being made but the function app is being called twice. I am using version 2 (2.0.12961.0) of the functions sdk.

#### Investigative information

Please provide the following:

- Timestamp1: 2020-02-20T14:34:48.7756293Z
- Timestamp2: 2020-02-20T14:34:50.6622581Z
- Function App version (1.0 or 2.0): 2.0.12961.0
- Function App name: SignalROutput20190926101554
- LogicAppRunId: 08586193976182935058877555581CU24
- Invocation ID 1:1e3296eba8beef4e
- Invocation ID 2: b7417074d370b644
- Operation ID 1:293225f0fc49e44bad0a4a4d7a40d1ef
- Operation ID 2: fff2fe1917048743a3d686d9553fab4f
- Region: North Europe

#### Repro steps

An http call from a logic app to the function triggers the double execution

#### Expected behavior

The http trigger should only be executed once per logic app http call.

#### Actual behavior

Http triggered function is being called twice

#### Related information 
Logic app id : c655d84b-2c25-4aee-a330-2703f6c143d8

Http Triggered functon
<details>
<summary>Source</summary>

```csharp
[FunctionName("newAlarmMessage")]
public static Task SendMessage(
[HttpTrigger(AuthorizationLevel.Anonymous, "post")]HttpRequest req,
[SignalR(HubName = "chat")] IAsyncCollector<SignalRMessage> signalRMessages, ILogger log)
{
    dynamic requestBody = JObject.Parse(new StreamReader(req.Body).ReadToEnd());	
   
    return signalRMessages.AddAsync(
        new SignalRMessage
        {
           Target = "newAlarmMessage",
           Arguments = new[] { requestBody }
         });
}
```
</details>

**Comment by brettsam** [comment]
What is the latency of the first call? Is it possible that Logic Apps is timing out and retrying -- and then the first one actually succeeds?

**Comment by njabulomp** [comment]
I'm not sure how to view the latency details for the logic app run. When I view the run details it is showing only one execution. I'm not sure if it is a concurrency setting as well. This issue is happening for one particular execution, for the other messages being sent no duplicate calls are made.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by v-anvari** [comment]
@njabulomp , sorry for the delay in response. We believe that the logic app was making the calls with delay, we recommend you to use "delay time" in the logic app for it to run with certain delay.  Kindly, let us know if the issue still persists.

**Comment by brettsam** [comment]
Logic Apps has an internal timeout retry policy -- so if a request takes longer than some amount of time (https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-limits-and-config#timeout). You should be able to see in App Insights how long your Function App invocation ran -- and from there, determine if it was too long.

I also believe that Logic Apps will give you logs that indicate when it was retried -- but I don't have the details on that.

Closing this as I'm pretty sure this is what happened -- Functions Http requests only run when they're called and I suspect that Logic Apps was simply calling the Function twice because the first call timed out.
