### ISSUE TITLE
MissingMethodException related to ApplicationInsights on 2.0.12998 or 3.0.13130

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#5691]
We're investigating a small number of sites that are seeing errors after upgrading to 2.012998 or 3.0.13130 and now receiving `MissingMethodException` related to ApplicationInsights.

If you see this exception, please let us know here and set `FUNCTIONS_EXTENSION_VERSION` in app setting to 2.0.12961.0 or 3.0.13107.

**Comment by brettsam** [comment]
This is being investigated by App Insights here: https://github.com/microsoft/ApplicationInsights-dotnet/issues/1702

**Comment by TimothyMothra** [comment]
The fix has been published to NuGet and should be generally available within an hour.

- https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.12.2
- https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.13.1
- https://www.nuget.org/packages/Microsoft.ApplicationInsights.AspNetCore/2.14.0-beta2
