### ISSUE TITLE
[HttpWorker]Expand environment variables specified in startup command

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-host#5692]
Some startup commands require `FUNCTIONS_HTTPWORKER_PORT` to be passed to it. Couldn't find a way to do this. The following doesn't seem to work:

```json
"httpWorker": {
	"description": {
		"defaultExecutablePath": "php",
		"defaultWorkerPath": "worker.php",
		"arguments": [
			"-S",
			"0.0.0.0:$FUNCTIONS_HTTPWORKER_PORT"
		]
	}
}
```

**Comment by pragnagopa** [comment]
Overriding `FUNCTIONS_HTTPWORKER_PORT` would not work when running in Azure due to sandbox restrictions and also to avoid a port that is already in use.

For running HttpWorker standalone and locally, you can set the environment.

Can you please add more details on the scenario setting port would be useful?

**Comment by anthonychu** [comment]
I meant provide the ability to pass the port that was selected by the host to the startup command as an argument (or part of an argument). Currently what I have put above doesn't seem to work work.

**Comment by pragnagopa** [comment]
Ahh, I think it would be useful to support expanding environment variables provided in the start up command.

**Comment by pragnagopa** [comment]
PR is now open that supports expanding environment variables provided in httpWorker section using `%EnvVarName%` notation.  Example:

```json
"httpWorker": {
	"description": {
		"defaultExecutablePath": "%TestEnv%",
		"defaultWorkerPath": "%TestEnv%",
		"arguments": [
			"-S",
			"0.0.0.0:%TestEnv%"
		],
               "workerArguments": [
			"0.0.0.0:%TestEnv%"
		]
	}
}
```

_Note: Added `workerArguments` element to differentiate between, exe args and worker args_

**Comment by anthonychu** [comment]
Thanks! Will this work for Linux as well using the same notation?

Do you have an example of how `workerArguments` will work? For instance, will the command that is executed be something like:

```
execPath arg1 arg2 workerPath workerArg1 workerArg2
```

**Comment by pragnagopa** [comment]
> Will this work for Linux as well using the same notation?

Yes. It should work on linux as well. Some discussion here: https://github.com/dotnet/runtime/issues/25792

For workerArguments, yes what you provided will be the command used to launch.
-  List in `arguments` will be appended after `defaultExecutablePath` but before `defaultWorkerPath`
-  List in `workerArguments` will be appended after `defaultWorkerPath` 

```json
"httpWorker": {
	"description": {
		"defaultExecutablePath": "exe/runtime such as node, dotnet etc.",
		"defaultWorkerPath": "worker for the exe provided",
		"arguments": [
			"arg1",
			"arg2"
		],
               "workerArguments": [
			"workerArg1",
                        "workerArg2"
		]
	}
}
```

**Comment by pragnagopa** [comment]
cc @yojagad
