### ISSUE TITLE
FunctionApp stopped working without explanation

### ISSUE THREAD

**Issue by skype007** [Azure/azure-functions-host#5694]
Hello team,

I just discovered that an Azure Function (TimerTrigger to be more specific) was not fired during many days until this morning as you can see in the screenshot below : 

![image](https://user-images.githubusercontent.com/5286548/75090564-589d0f00-5564-11ea-8544-de9f53199277.png)

As a reminder, the Function is supposed to be fired every hour. By the way, we also have an Azure WebJob (NET Framework) deployed on an AppService : I'm telling you this because the WebJob stopped working two days ago....and just like the AzureFunction, the WebJob is back to normal.

![image](https://user-images.githubusercontent.com/5286548/75090618-e7aa2700-5564-11ea-8b1f-c16cde4d0a91.png)

Honestly I don't know if both issues are related to the same root cause but both are plugged to the same AppServicePlan so why not !

#### Investigative information

Here's the information related to the AzureFunction Timer before the "outage":

- Timestamp: 2020-02-14T13:59:59.9954826+00:00
- Function App: 2.0
- Invocation ID: 496253ea-4db4-43c3-aedc-951e77e2b990
- Region: West Europe

Thanks to ApplicationInsights, I manage to found out that the problem was also global (BlobTrigger, ServiceBusTrigger, etc.) because a TypeLoadException was thrown : 

Thanks you in advance for your help :)

**Comment by madelinegordon** [comment]
Hello, so sorry for the long delay in response. Unfortunately, our logs only persist for 30 days. Let me know if this issue has re-occurred, and if so I will be able to investigate. Thank you.
