### ISSUE TITLE
Latest secret cache fixes is still making a call to blob storage during cold start

### ISSUE THREAD

**Issue by safihamid** [Azure/azure-functions-host#5704]
Below is the callstack, This call is adding an extra 200ms to cold start for auth scenarios in my profiles.

 + microsoft.azure.webjobs.script.webhost!Microsoft.Azure.WebJobs.Script.WebHost.Authentication.AuthenticationLevelHandler+<HandleAuthenticateAsync>d__4.MoveNext()
  + microsoft.azure.webjobs.script.webhost!AuthenticationLevelHandler.GetAuthorizationKeyInfoAsync
    + microsoft.azure.webjobs.script.webhost!DefaultSecretManagerProvider.Create
     + microsoft.azure.webjobs.script.webhost!DefaultSecretManagerProvider.CreateSecretsRepository
      + microsoft.azure.webjobs.script.webhost!Microsoft.Azure.WebJobs.Script.WebHost.BlobStorageSecretsRepository..ctor(System.String, System.String, System.String, Microsoft.Extensions.Logging.ILogger)
       + microsoft.azure.webjobs.script.webhost!BlobStorageSecretsRepository.CreateBlobContainer

**Comment by pragnagopa** [comment]
Assigning to Mathew for further investigation.

**Comment by mathewc** [comment]
The StartupCache work removed all the storage access calls to retrieve keys, but there are more it seems.

This particular issue is in the code [here](https://github.com/Azure/azure-functions-host/blob/2d6c40c50de688900ae05fb9ec9b395d2353ad76/src/WebJobs.Script.WebHost/Security/KeyManagement/BlobStorageSecretsRepository.cs#L52). We're eagerly doing a CreateIfNotExists on the blob container. We should change this so the container is only created on demand when needed.
