### ISSUE TITLE
HTTP Trigger Returns 204 But Function Not Invoked

### ISSUE THREAD

**Issue by thehereward** [Azure/azure-functions-host#5710]
#### Issue Summary
Apologies in advance if I missing something obvious but I am rather perplexed by this behaviour.

I have logs of my function's HTTP trigger returning a 204 at the following UTC timestamps:
2020-02-24 16:31:16.261
2020-02-24 16:31:16.745
2020-02-24 16:36:16.900
2020-02-24 16:36:17.764

However, I can only see evidence of the function being invoked for three of these four triggers. This includes the invocation logs in Kudu, custom events recorded in Application Insights and expected downstream effects.

This is a concern because our upstream process things it's request has been accepted when it actually has been silently dropped.

#### Investigative information

Please provide the following:

- Timestamp: 2020-02-24 16:36:17.724
- Function App version (1.0 or 2.0): 2.0
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: b77ffa55-4ad0-4e6b-911b-3ad66d5e3fbb
- Region: West Europe

#### Related information 

Provide any related information 
* C# Function
* v2.0 function
* Consumption plan

**Comment by mathewc** [comment]
Looking at our logs, there were only 3 invocations of your function during the time period 2020-02-24 16:31 to 2020-02-24 16:37. Furthermore, our front end logs only show we received 3 requests as well. So only 3 invocations ran. Your logs showing 4 invocations must be incorrect.

  |   |   |   |   |  
-- | -- | -- | -- | -- | --
  | PreciseTimeStamp | ActivityId | FunctionName | Summary | FunctionInvocationId
  | 2020-02-24 16:31:16.2549094 | 2e6c76f0-fc73-4f1b-bca2-cc6dd4e5c6ef | UploadFile | Executed 'UploadFile' (Succeeded, Id=0b5d375b-0ff8-49dd-8f12-ce67420c3b69) | 0b5d375b-0ff8-49dd-8f12-ce67420c3b69
  | 2020-02-24 16:31:16.7410517 | 0dfe93c2-45ec-402b-b597-2f6b06d5291e | UploadFile | Executed 'UploadFile' (Succeeded, Id=706b8361-75f8-4b36-b412-83ea99627c8a) | 706b8361-75f8-4b36-b412-83ea99627c8a
  | 2020-02-24 16:36:17.7244952 | 00000000-0000-0000-0000-000000000000 | UploadFile | Executed 'UploadFile' (Succeeded, Id=b77ffa55-4ad0-4e6b-911b-3ad66d5e3fbb) | b77ffa55-4ad0-4e6b-911b-3ad66d5e3fbb

**Comment by thehereward** [comment]
Thank you for the reply @mathewc. I appreciate the confirmation that there is definitely something odd going on at our end.
