### ISSUE TITLE
Eventsubscription endpoint type azurefunction does not show any Function app in the drop down. 

### ISSUE THREAD

**Issue by vinodsugur** [Azure/azure-functions-host#5711]
I have a Blob Storage on which we have added a event subscription with an endpoint type as "azurefunction", but for the Azure Function configuration no function app is listed in the Function App drop down. The function app is part of same resource group and has identity on option, and is created by same user.

What could be the issue? This configuration was working fine but now even after trying different options no success.

**Comment by ankitkumarr** [comment]
@vinodsugur, what sku (Consumption, App Service Premium), region and operating system (Windows, Linux) is your function app on?
