### ISSUE TITLE
How to access content files out from bin folder?

### ISSUE THREAD

**Issue by lommez** [Azure/azure-functions-host#5715]
How can i access files that are marked to be copied to output directory to "Copy Always" value?

When trying to execute the following line:

```csharp
var assemblyDirectoryPath = Path.GetDirectoryName(Assembly.GetAssembly(typeof(MyClass)).Location);
```
I got the wrong directory.
In my project I CAN'T use the ExecutionContext. Is there any alternative to access those files?
Also, i`m running Azure Functions V1

Thanks!

**Comment by kashimiz** [comment]
Hi @lommez, sorry for the delayed response. I'd like to understand why you can't use the ExecutionContext object to get this information; could you elaborate?

**Comment by mathewc** [comment]
ExecutionContext.FunctionAppDirectory just takes care of everything for you, handling environment differences, etc. If you're running in App Service, you could just format the path the same way the extension does. Code for that is [here](https://github.com/Azure/azure-functions-host/blob/65cf07688b6974219b90d4fc57d420c5226dc4fb/src/WebJobs.Script.WebHost/Configuration/WebScriptHostConfigurationSource.cs#L50). Basically it uses the root path defined by the HOME environment variable, and adds "site/wwwroot/<function>".

**Comment by lommez** [comment]
@kashimiz I can't use ExecutionContext because i don't have the source to modify the code.
 This behavior of Azure Function isn't Azure Functions design failure? because it's was expected Assembly.Location() to have the same behavior in any type of project.

**Comment by kashimiz** [comment]
@lommez I'm sorry for the delayed response time on this. Can you elaborate a bit more on your project setup? If you don't have the source code of the function you're running, where are you executing the following?

```csharp
var assemblyDirectoryPath = Path.GetDirectoryName(Assembly.GetAssembly(typeof(MyClass)).Location);
```
