### ISSUE TITLE
Investigate V3 placeholder hit percentage in Cold Start Summary email

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#5728]
Tracking item to understand recent Java cold start numbers

**Comment by pragnagopa** [comment]
cc @amamounelsayed FYI

**Comment by pragnagopa** [comment]
cc @anirudhgarg fyi

**Comment by pragnagopa** [comment]
Moving to Sprint 73.

**Comment by fabiocav** [comment]
Some progress made i sprint 73, moving to sprint 74 so we can continue this work.

**Comment by gzuber** [comment]
Java and Node: weight distribution issue
v3 Dotnet: capacity issue
