### ISSUE TITLE
Linux App Service image deployment rollout

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-host#5734]
Tracking issue to track the work that is needed for changing the way Linux App Service images are deployed in the platform.

**Comment by fabiocav** [comment]
Closing as completed. 

@ankitkumarr will be following up with additional documentation items.

**Comment by ankitkumarr** [comment]
Here's the issue tracking internal documentation -- https://github.com/Azure/azure-functions-host/issues/5887
