### ISSUE TITLE
Handle exceptions in LinuxMetricsPublisher

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-host#5736]
Currently any exception thrown from https://github.com/Azure/azure-functions-host/blob/2abd94b579f7693d373809d68bb3a99be7e81b98/src/WebJobs.Script.WebHost/Metrics/LinuxContainerMetricsPublisher.cs#L262

is logged and ignored. 

We should stop ignoring this once health checks are implemented to identify failures here.

**Comment by mathewc** [comment]
@balag0 I think we can close this now?

**Comment by balag0** [comment]
Yes. We can reopen if required.
