### ISSUE TITLE
Code inside queue trigger function does not get executed azure functions - Java 

### ISSUE THREAD

**Issue by adityachowta** [Azure/azure-functions-host#5742]
I'm trying to execute Java based Queue trigger function, The log displays that the function as executed however  any code logic or even Simple Sysout or context.getLogger().info() does not get printed on either the VS Code console or the Application insights. 

Code : 

```
 @FunctionName("QueueTriggerRead")
    public void functionHandler(@QueueTrigger(name = "myQueueItem", queueName = "ede-input-queue", connection = "AzureWebJobsStorage") String myQueueItem, final ExecutionContext executionContext) {
        
        Invoked inv = new Invoked();
        inv.Print(myQueueItem);

        System.out.println("Queue trigger input: " + myQueueItem);
        executionContext.getLogger().info("Queue message: ??? " + myQueueItem);
       
    }

```

Logs: 

3/4/2020 3:26:21 PM] Executing 'Functions.QueueTriggerRead' (Reason='New queue message detected on 'ede-input-queue'.', Id=1b02c579-9d1b-4862-a68a-70c43e0f69e8)
[3/4/2020 3:26:21 PM] Trigger Details: MessageId: 1feb8bac-2e58-4f3c-9dab-b634016fb58e, DequeueCount: 1, InsertionTime: 3/4/2020 3:26:19 PM +00:00
[3/4/2020 3:32:32 PM] Executing 'Functions.QueueTriggerRead' (Reason='New queue message detected on 'ede-input-queue'.', Id=cc392e56-bbc4-4ba2-98dc-0153ae912997)
[3/4/2020 3:32:32 PM] Trigger Details: MessageId: e00230fb-d6e2-474e-9471-923c7e269f10, DequeueCount: 3, InsertionTime: 3/4/2020 12:49:50 PM +00:00

**Comment by amamounelsayed** [comment]
@adityachowta, Thank you so much for your input.

Can you please share your host.json?

Couple of requests, can you please add the executionContext.getLogger().info("Start function") at the first line of the function?
I want to make sure that just static message can be printed.
Second can you F5 using vscode. add debug point at the logger, debug your function that the code reach this debugging line?

For the application insights it usually takes time to populate depends on the way you are using.

Thank you

**Comment by adityachowta** [comment]
@amamounelsayed 

host.json:

```
{
  "version": "2.0",
  "extensionBundle": {
      "id": "Microsoft.Azure.Functions.ExtensionBundle",
      "version": "[1.*, 2.0.0)"
  },
  "logging": {
    "fileLoggingMode": "always",
    "logLevel": {
      "default": "Information",
      "Host.Results": "Error",
      "Function": "Trace",
      "Host.Aggregator": "Trace"
    }
  }
}
```

Output after adding executionContext.getLogger().info("Start function") to the start of the function:
```

Hosting environment: Production
Content root path: i:\Projects\AzureFunctions\ede_java_worker_queue_dev\target\azure-functions\ede-java-worker-queue-dev
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
[3/5/2020 4:36:25 AM] Host lock lease acquired by instance ID '000000000000000000000000BC4C4E5F'.
[3/5/2020 4:37:20 AM] Executing 'Functions.QueueTriggerRead' (Reason='New queue message detected on 'ede-input-queue'.', Id=4574a11e-5449-426b-8487-f752cb3eedb7)
[3/5/2020 4:37:20 AM] Trigger Details: MessageId: 7cfd3d36-741b-4c0c-9218-61cff347853c, DequeueCount: 1, InsertionTime: 3/5/2020 4:37:21 AM +00:00
[3/5/2020 4:41:08 AM] Executing 'Functions.QueueTriggerRead' (Reason='New queue message detected on 'ede-input-queue'.', Id=1a326a1e-3d49-4325-abae-b8feab7a7bd7)
[3/5/2020 4:41:08 AM] Trigger Details: MessageId: e2e91987-4fb1-4dcb-8116-bc21d6c92b48, DequeueCount: 2, InsertionTime: 3/5/2020 4:26:05 AM +00:00
```
As for the Debugging, nothing happens here as well the breakpoints never get hit. Attaching screenshot:
![image](https://user-images.githubusercontent.com/8074739/75949168-6d19c980-5ecb-11ea-8a74-ad004da50c2d.png)

**Comment by amamounelsayed** [comment]
@adityachowta Thank you, can you please remove the logging section in the json file and test again?
Remove,
"logging": {
    "fileLoggingMode": "always",
    "logLevel": {
      "default": "Information",
      "Host.Results": "Error",
      "Function": "Trace",
      "Host.Aggregator": "Trace"
    }

**Comment by adityachowta** [comment]
Tested it and it gave the same result :

![image](https://user-images.githubusercontent.com/8074739/76068974-2b1a8180-5fb8-11ea-83e5-1ad443dbe8f9.png)

**Comment by adityachowta** [comment]
Hello any other suggestions ?

**Comment by amamounelsayed** [comment]
@adityachowta at this moment I need you to share the code, is there any way to upload it to github? Thank you!

**Comment by adityachowta** [comment]
Hi @amamounelsayed i have sent you and invite for the repository: [https://github.com/adityachowta/AzFunctionJavaDemo](https://github.com/adityachowta/AzFunctionJavaDemo)

**Comment by amamounelsayed** [comment]
@adityachowta thank you I will have a look sir and let you know!

**Comment by amamounelsayed** [comment]
@adityachowta I had a look on the project and you are using old settings, example in the POM fileazure-functions-java-library 1.0.0-beta-4 we are now 1.3.1. azure.functions.maven.plugin.version 1.4.1.

Can you please follow the steps in https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli?pivots=programming-language-java&tabs=bash%2Cbrowser?

Thank you!

**Comment by adityachowta** [comment]
Hi I updated it but still the same result

**Comment by amamounelsayed** [comment]
@adityachowta thank you so much can you push the latest code to https://github.com/adityachowta/AzFunctionJavaDemo

Can you also confirm if you followed the steps and having The Azure CLI version 2.0.76 or later.

Really appreciate your cooperation,
Ahmed

**Comment by adityachowta** [comment]
@amamounelsayed Below are the steps followed and observations:

1: Verifying the azure cli version 
![Azure Cli](https://user-images.githubusercontent.com/8074739/79039991-ca0f4a80-7c02-11ea-9369-881b42781607.PNG)

2: I Updated the mvn dependencies to the latest versions, but those don't work for me as it does not create the function folder inside the target folder.
![image](https://user-images.githubusercontent.com/8074739/79040088-b9130900-7c03-11ea-85de-b8e7983c25d1.png)

3: I had followed the same steps as mentioned in the link provided the first time as well. Also I used VS code path to create the function. I have used latest extensions for VS code as well. However when a new function is created the mvn dependency version is not the latest by default why is that so?

Also to mention that I have tried this in C# and JS as well and only C# worked. Howevevr I need to get this running in java.

Really appreciate your help in this

**Comment by adityachowta** [comment]
Update : 

I tried creating the function on a different machine and a different network and was able to successfully run the java based function with expected output. Also to mention that the dependencies auto-added during the creation of the function were the latest ones. 

So i transferred the same project and it seems to runs in the previous setup now.

I'm guessing this is more to do because of the corporate network blocking some urls in the latest dependency.

**Comment by amamounelsayed** [comment]
Thank you so much @adityachowta  for your update and glad that is working. Please if you have any questions let us know.
