### ISSUE TITLE
TimerTrigger too often?

### ISSUE THREAD

**Issue by konrad79** [Azure/azure-functions-host#5745]
I've several timer triggered azure functions.
One should run each day 11:30:
`public void CleanupData([TimerTrigger("0 30 11 * * *", RunOnStartup = true)]TimerInfo myTimer, ILogger log)`

Another should run once a day:
`public void DownloadLiveList([TimerTrigger("0 0 0 * * *", RunOnStartup = true)]TimerInfo myTimer, ILogger log)`

But both are running at about every 5-8 minutes.
Are my TimerTrigger-Time-Strings wrong? Or is this a bug?

Since there are other functions in the class, that should run every 5 minutes. Do they perhaps interfere?

**Comment by mathewc** [comment]
You have `RunOnStartup = true` configured. You should remove that - that's the issue. That setting will cause the function to run any time a new app instance starts (e.g. scale out) or restarts. See the warning on this in doc [here](RunOnStartup = true).
