### ISSUE TITLE
No extensions.json generated with recent update

### ISSUE THREAD

**Issue by pownkel** [Azure/azure-functions-host#5754]
After the most recent update to Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator (version 1.1.5), we no longer see the extensions.json file being generated. When we try to deploy our function app, we get error messages such as:
`The binding type(s) 'cosmosDBTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.`

#### Investigative information

- Timestamp: 3/5/2020, 10:30:55.131 PM
- Function App version: 2.7

While this causes function app deployments to fail, we see the issue even when building locally.

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create an empty function app with vscode using the cosmosDBTrigger
2. Change the host.json to contain the following:
```json
{
  "version": "2.0"
}
```
And create an extensions.csproj file with:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
	<WarningsAsErrors></WarningsAsErrors>
	<DefaultItemExcludes>**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.5" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.1.5" />
  </ItemGroup>
</Project>
```

3. Run `dotnet build` in this directory

#### Expected behavior

An extensions.json file is generated inside the `bin/` directory.

#### Actual behavior

There is no extensions.json file generated. Note that the expected behavior does happen for version 1.1.4.

#### Known workarounds

Keep Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator at version 1.1.4

**Comment by brettsam** [comment]
I believe I broke this recently with another fix to VS projects. I will investigate soon -- but as you mention, the best workaround for now is to stick with 1.1.4

**Comment by brettsam** [comment]
Give 1.1.6 a try. Should now be fixed.
