### ISSUE TITLE
Why does the Startup class have to inherit directly from FunctionsStartup and not a subclass of the latter?

### ISSUE THREAD

**Issue by IanKemp** [Azure/azure-functions-host#5762]
I want to make a class that extends `FunctionsStartup` to encapsulate some bootstrapping that's required by all of my employer's Azure functions, and then simply make all our funcs inherit that class, but my testing has shown that using `[FunctionsStartupAttribute]` on any class that does not inherit **directly** from `FunctionsStartup` results in that class being ignored.

In other words, this works:

```csharp
[assembly: FunctionsStartup(typeof(Foo.Bar.Startup))]
namespace Foo.Bar
{
    public class Startup : FunctionsStartup
    {     
        public Startup() { /* always hit */ }
    }
}
```

But this does not:

```csharp
[assembly: FunctionsStartup(typeof(Foo.Bar.Startup))]
namespace Foo.Bar
{
    public class FunctionsStartupWrapper : FunctionsStartup
    {
    }

    public class Startup : FunctionsStartupWrapper
    {     
        public Startup() { /* never hit*/ }
    }
}
```

I'm assuming that the code that locates the function startup class does so by checking that the class specified by `[FunctionsStartupAttribute]` is the parent of `FunctionsStartup`, but this seems unnecessary. Why is it like this - why doesn't it do the (IMO simpler) check that `FunctionsStartup` is in the inheritance chain of the specified startup class?

Using `Microsoft.NET.Sdk.Functions` NuGet version 3.0.5 (latest at time of this writing).

**Comment by WiredUK** [comment]
I cannot reproduce this error, are you absolutely sure this is what is happening?

**Comment by IanKemp** [comment]
> I cannot reproduce this error, are you absolutely sure this is what is happening?

What version are you using?

**Comment by WiredUK** [comment]
> What version are you using?

I tried with both v1.0.29 and v3.0.5 of `Microsoft.NET.Sdk.Functions`.

**Comment by ghost** [comment]
Do you get an errors / warnings at build time?

**Comment by kashimiz** [comment]
Hi @IanKemp, I'm sorry for the delayed response to this issue. I wasn't able to reproduce this error using the code you'd provided, using v3.0.3 and v3.0.8 of `Microsoft.NET.Sdk.Functions` on the 3.0.13901.0 runtime. In my run, VS breakpoints within the Startup method of the extended Startup class. Are you still experiencing this issue, and if so, what Functions runtime and version of the SDK are you using?
