### ISSUE TITLE
[HttpWorker]Investigate 500s in daily perf runs

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#5763]
Few requests for HttpWorker test:
https://functionsperfst.blob.core.windows.net/dashboard/2020-03-09%2014_22_58/index.html

are failing with 500s. Need to investigate.

**Comment by anthonychu** [comment]
Tagging as P1 for next sprint. Running into this during our perf tests as well (about 5% failing).

**Comment by jeffhollan** [comment]
@fabiocav to potentially see who would make sense to investigate

**Comment by fabiocav** [comment]
Assigning to sprint 76 for investigation

**Comment by yojagad** [comment]
Been doing some analysis. So far, following are the observations

=> Been trying with multiple httpClients but with ASPs with default scale values and the number of 500s do seem to reduce but not to a complete 0 still. This might indicate multiple processes could help.

=> Switched back and tried the experiment on premium plan but with min and max number of instances set to 1. In this case, the number of 500s (with 2 http clients) actually seemed to be more than with just a single httpClient. This is what I'll be focusing on.

All of the above results are for a custom handler with a node app (a simple hello world application)
