### ISSUE TITLE
Queue triggered function stalled midway execution without failure indication

### ISSUE THREAD

**Issue by JayJamieson** [Azure/azure-functions-host#5783]
I have a function app that is triggered by a queque message to perform a nightly sync of data from third party systems into a ticketing system. Part of the processing logic includes a check-in where i save the start time and `isRunning` boolean flag to postgresql database. Upon successful or failure of the job i update the database with failure or completion result as well as reset the `isRunning` flag to false. 

The problem I am encountering is that about half of the triggered functions never complete in that failure condition is never met and database is not updated and azure logs show that the function never completed. 

I cant find and exceptions in application insights or logs indicated what happened.

#### Investigative information

- Timestamp: 2020-03-10T12:19:09.5398834Z (UTC)
- Function App version: 2
- Function App name: N/A
- Function name(s) (as appropriate): N/A
- Invocation ID: 841f9f5b-ff4d-4008-935d-7ab92e717c9d
- Region: Australia East
- Pricing tier: App Service plan

#### Repro steps
1. Queue 100-200 queue messages containing reference data

#### Expected behavior
Function should be triggered by queue message and update database indicating process has started. 
Once process is completed the function should update with completion time and completion results.

Expected log output:
```
Executing 'redacted' (Reason='New queue message detected on 'redacted'.', Id=841f9f5b-ff4d-4008-935d-7ab92e717c9d)
 // other log messages
Executed 'ConnectWiseSync' (Succeeded, Id=841f9f5b-ff4d-4008-935d-7ab92e717c9d)
```

#### Actual behavior
Function is triggered by queue message and updates database indicating process has started. 

Function never updates database indicating completion and processing results. Function invocation log also never indicates function completed at all. No error logs what so ever.
```
Executing 'redacted' (Reason='New queue message detected on 'redacted'.', Id=841f9f5b-ff4d-4008-935d-7ab92e717c9d)
 // other log messages
```

#### Known workarounds

N/A

#### Related information 

**host.json**
```json
{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "Default": "Information"
    }
  },
  "extensions": {
    "queues": {
      "maxPollingInterval": "00:30:00",
      "visibilityTimeout": "01:00:00",
      "batchSize": 32,
      "maxDequeueCount": 1,
      "newBatchThreshold": 16
    }
  }
```

* Programming language used : C#
* Bindings used : Queue Trigger

**Comment by soninaren** [comment]
@JacquesJamiesonLancom Please re-open this issue with latest details if this is still an issue. Sorry we did not get to this in reasonable time.
