### ISSUE TITLE
[Build] Include hashes for each file that are part of the build

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#5787]
cc @fabiocav 

Need to create hardlinks using prebuilt hashes file.

**Comment by pragnagopa** [comment]
Initial version of the code: https://github.com/pragnagopa/SiteExtensionCompressor/

**Comment by mhoeger** [comment]
This is part of a larger body of work, roughly broken down here: https://github.com/Azure/azure-functions-host/issues/6266

**Comment by fabiocav** [comment]
Design in progress. Moving to sprint 81
