### ISSUE TITLE
Change Linux App Service date time format for logs

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-host#5793]
We need to change the format from something like "03/13/2020 11:00:00.014 PM" to "2020-03-13 23:00:00.014".

This is required for Log Analytics support.

cc: @fabiocav

**Comment by fabiocav** [comment]
@kulkarnisonia16 FYI - moving this to `Triaged` for now as we're blocked on ANT 88 and deployment.

**Comment by ankitkumarr** [comment]
Moving to Sprint 74 as a stretch item.

**Comment by ankitkumarr** [comment]
Moving to Sprint 75 (didn't have a chance to stretch in 74).

**Comment by ankitkumarr** [comment]
Fixed by https://github.com/Azure/azure-functions-host/commit/b76871072b4efd512f23a3ad9f14e667f2359a1c
