### ISSUE TITLE
maxPollingInterval value is not read from queue setting in host.json

### ISSUE THREAD

**Issue by vkurmi** [Azure/azure-functions-host#5798]
I have an Azure function which is triggered by storage queue. I updated host.json file to add settings for queue trigger as per [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue-output?tabs=csharp#host-json)

The issue I am facing is that `maxPollingInterval` setting is not taking effect, whereas other settings are read from host.json & work fine. 

Please know that I have not registered any custom `IConfiguration` for my function app.

#### **Investigative information**

It is a .net core 2.1 App and below are the nuget packages it uses.
![image](https://user-images.githubusercontent.com/46264855/76766440-00050e80-67be-11ea-88bc-d296ac3264ce.png)

**host.json**
![image](https://user-images.githubusercontent.com/46264855/76766669-5a05d400-67be-11ea-80df-19cec8001450.png)

**Azure function log**
![image](https://user-images.githubusercontent.com/46264855/76766900-bf59c500-67be-11ea-8fbe-ded821ce8a39.png)

`maxPollingInterval` always remains 2 seconds regardless of what value I set in host.json

#### Repro steps

- Add a Azure function, having queue trigger

- Set configuration settings for queue in host.json file

#### Expected behavior

`maxPollingInterval` configuration should have value as per host.json (00:00:07)

#### Actual behavior

`maxPollingInterval` always has value "00:00:02"

#### Known workarounds

When I configure `QueuesOptions` from Startup class then `maxPollingInterval` takes correct value.

`builder.Services.Configure<QueuesOptions>(configRoot.GetSection("AzureFunctionsJobHost:extensions:queues"));`

**Comment by DumbTechLion** [comment]
Well, that's the same for us on Core 3.1 with v3 !

**Comment by cddev** [comment]
We have this issue too

**Comment by kashimiz** [comment]
My apologies for the delayed response on this one. @Leosamus, @cddev and @vkurmi, when are you observing this issue - does it occur when running locally, and/or deployed to Azure? @ccdev, please also provide more information about your environment, including the Functions host version.

If you're observing this problem on Azure, please provide the following information as well:

- Timestamp:
- Function App version:
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

If you don't want to share your Function App name or Functions names on GitHub, you can [share your function app name privately.](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately)

**Comment by vkurmi** [comment]
I had this issue running function locally, and I overcome it by using the workaround mentioned in my original post.

**Comment by ThejaChoudary** [comment]
@vkurmi Proceeding to close the Issues,please feel free to reach out to us for further queries.
