### ISSUE TITLE
Enable Environment Variables Configuration Provider for host.json

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-functions-host#5805]
#### What problem would the feature you're requesting solve? Please describe.
I would like to override per-function logging settings in production vs. what is in my code, and I cannot do that without modifying host.json.

#### Describe the solution you'd like
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#environment-variables-configuration-provider

Add this configuration provider to the config for host.json, at a precedence level higher than the file. A prefix to be used could be FUNCTIONSHOST_ so env variables would be for instance FUNCTIONSHOST_LOGGING__LOGLEVEL__DEFAULT = 'Warning'

#### Describe alternatives you've considered
CI pipeline to edit host.json on deployment, not ideal at all

#### Additional context
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#environment-variables-configuration-provider

**Comment by brettsam** [comment]
Sorry I'm getting to this so late -- but we do have env var configuration provider enabled. The issue is that you need to use `AzureFunctionsJobHost` as the initial path. So I believe you can accomplish what you want by starting the environment variable with `AzureFunctionsJobHost__Logging`...
