### ISSUE TITLE
[Rpc]Function execution time should be calculated by the language worker

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#5806]
Currently, function invocation time is calculated from the time event is read by the host until host gets a response from a language worker. Most cases this is OK.

Sometimes there might a delay at the language worker before it starts processing an invocation.
For example, if timeout is set to 10mins, if an invocation request is picked by the language worker to process after 8mins, actual function execution will only get 2mins and if it goes over, host throws function timeout exception.

**Comment by pragnagopa** [comment]
cc @mhoeger @yojagad @fabiocav

**Comment by fabiocav** [comment]
@pragnagopa this doesn't sound like the right approach as, among other things, would not account for binding time (e.g. downloading a large payload).

Will flag this as "needs feedback", but it would be good to discuss this item if you feel it is needed.

**Comment by liliankasem** [comment]
The current behavior accurately reports the func execution time inclusive of the time spent in the invocation pipeline (from the moment the trigger raises the event).
