### ISSUE TITLE
HttpTrigger returns 0 result code. 

### ISSUE THREAD

**Issue by vbondaryuk** [Azure/azure-functions-host#5813]
We have a function which called from the ADF pipelines by http, it works correctly, but from time to time, function **returns code 0** and our pipeline failed with exception:

> 502 - Web server received an invalid response while acting as a gateway or proxy server.

But from Function -> Monitor and AppInsight we can see, that function finished successfully
![image](https://user-images.githubusercontent.com/5966463/76418564-e6c02480-63af-11ea-98f1-9ae777c70374.png)

![image](https://user-images.githubusercontent.com/5966463/76418105-17ec2500-63af-11ea-8132-080def597153.png)

What is the reason for that behavior?
How can we handle it except retry logic?

net. core 2.1
sdkVersion: 2.0.13017.0

copied from: [HttpTrigger returns 0 result code.](https://github.com/Azure/Azure-Functions/issues/1522)

**Comment by ankitkumarr** [comment]
@vbondaryuk, sorry for the late response here. Could you share your code or a repro with us that's showing this behavior? Or your app name so we can look at logs on our end to see if anything jumps out.

**Comment by vbondaryuk** [comment]
@ankitkumarr, we moved our functions to v3 and applied retry policy on ADF pipeline, it fixed the problem.

**Comment by ankitkumarr** [comment]
Thanks for the update. I will close this issue.
