### ISSUE TITLE
[Feature] Allow workers to specify exception typename via grpc

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-functions-host#5821]
#### What problem would the feature you're requesting solve? Please describe.
I want exceptions from the Powershell Worker to be typed the same as they were in the worker so that I don't have 50,000 RPCException exceptions in the Application Insights UI and I can actually traige to the appropriate exceptions in the view. 

Today this information is sent via a separate trace which is not ideal because you have to write a complicated inner join to join the exception to its related trace, rather than the information being available directly in the exception.

#### Describe the solution you'd like
Enhance the RPC protobuf definition for exceptions to allow a 'typename' field to override what is reported to application insights so workers can report typed exceptions.

#### Describe alternatives you've considered
As a workaround I currently use`TelemetryClient` to log more detailed exceptions to AI within Powershell and pull the instrumentation key and related operation ids from the environment variables, but this results in duplicate exceptions, and to not have duplicate exceptions results in unexpected behaviors (e.g. logging an exception and exiting 1 doesn't trigger automatic queue retry, etc.). 

Further I shouldn't *have* to do that, part of the appeal of Functions is having things like input bindings and output bindings abstract away a lot of the scaffolding so you can focus on your "business problem" code, so if I throw a typed exception I should just expect that typed exception to show up in application insights.

#### Additional context

**Comment by pragnagopa** [comment]
Related issue: https://github.com/Azure/azure-functions-host/issues/6284

**Comment by liliankasem** [comment]
We'll be addressing the RPCException issues through these two user stories:

- https://github.com/Azure/azure-functions-host/issues/4296
- https://github.com/Azure/azure-functions-dotnet-worker/issues/846

I'd like to close this issue as a dup of the above, let me know if you agree!

**Comment by JustinGrote** [comment]
Thank you @liliankasem[](https://user-images.githubusercontent.com/15258962/161317143-824df5ae-340e-4e31-a915-1e1d2cb1f166.png),

I really want the full exception details in Application Insights one way or the other, if the worker has a way to hook and deliver the worker-specific exception to application insights before it also ends up showing up as an invocationexception, that is ideal.

The story I want is that when I go to Application Insights and click the Exceptions tab, whether I am in the Powershell worker or another worker, that my specific exception types show up in the list and I don't have to deal with filtering for an innerexception. Just replacing 5000 "RPCException" with 5000 "InvocationException" doesn't meet this need, I expect to see "HttpRequestException" alongside "NullPointerException", etc. at the code level here.

This is not helpful;
![image](https://user-images.githubusercontent.com/15258962/161317143-824df5ae-340e-4e31-a915-1e1d2cb1f166.png)


I need those 123k exceptions broken down by their specific exception type.

These work items you linked doesn't seem to explicitly address this issue.

**Comment by liliankasem** [comment]
@JustinGrote https://github.com/Azure/azure-functions-dotnet-worker/issues/846 addresses what you're describing - the story is to log the full exception directly in Application Insights so you should get full exception details. This would need to happen for each worker so we're starting out on the dotnet worker and then applying the same pattern across the other workers.

**Comment by JustinGrote** [comment]
I misunderstood the intention of this issue, thanks! Yes we can close in favor.

**Comment by liliankasem** [comment]
I'll update the description is it's a little more clear! Closing this in favour of:

- https://github.com/Azure/azure-functions-dotnet-worker/issues/846
