### ISSUE TITLE
func host start never works for me.

### ISSUE THREAD

**Issue by graphicsxp** [Azure/azure-functions-host#5822]
Just installed with npm : 
`npm i -g azure-functions-core-tools@3 --unsafe-perm true`

then in VSCode I run : 
`func init`
`func new`
`func host start`

get this error :  

C:\Users\graph\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.1.3\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(33,5): error : Metadata generation failed. Exit code: '-2146232797' Error: 'Assert FailureExpression: [Recursive resource lookup bug]Description: Infinite recursion during resource lookup within System.Private.CoreLib.

What does this mean ?

**Comment by graphicsxp** [comment]
ok, working now after downgraded to .netcore3 . Would not work with latest version of .netcore....

**Comment by soninaren** [comment]
Can you upgrade to version 1.1.6 of Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator and try again.
