### ISSUE TITLE
Function folder not deleted on deleting the function

### ISSUE THREAD

**Issue by takyyon** [Azure/azure-functions-host#5825]
Upon deleting the function from the portal, it gets deleted successfully but the empty folder still remains.
We are making a DELETE call to `/subscriptons/{subscription}/resourceGroups/{resourceGroup}/providers/Microsoft.Web/sites/{site_name}/functions/{function_name}`

**Comment by mhoeger** [comment]
@btardif - can you help identify if this would be a portal issue or maybe kudu?

**Comment by btardif** [comment]
This is an ARM call, so I don't  think it's a portal problem. @takyyon can you provide more details to @mhoeger?

**Comment by v-bbalaiagar** [comment]
Hi @takyyon, Can we know if you are seeing this issue still and requires further follow up.

**Comment by btardif** [comment]
@fabiocav this is an ancient issue, currently assign to someone who is no longer in the functions team. can we re-assign or close?

**Comment by fabiocav** [comment]
Closing as this no longer seems to be an issue.
