### ISSUE TITLE
What magic trick do I need to apply to run code serverless?

### ISSUE THREAD

**Issue by dustinmoris** [Azure/azure-functions-host#5833]
```
Error: The binding type(s) 'queueTrigger' are not registered. Please ensure the type is correct and the binding extension is installed. 
```

Why? Why do I have to register queueTrigger?  I don't want to register anything I just want to deploy my code to a serverless environment.

What magic trick do I have to apply now again to get it working?

**Comment by alrod** [comment]
What do you use for local development? VS, VSCode or Core Tools? for Core tools we need to register the Storage extension:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cbash#register-extensions

**Comment by dustinmoris** [comment]
The issue was to upgrade to v3 of functions after upgrading the NuGet packages.
