### ISSUE TITLE
Azure Timer trigger Functions not triggering and pastDue

### ISSUE THREAD

**Issue by wuzhuoqing** [Azure/azure-functions-host#5836]
#### Investigative information

We have a simple node.js function which is schedule to run every Wednesday and Saturday which trigger another Container Instance to do real work (`"schedule": "0 5 2 * * 3,6"`). The function it self will only run for a few seconds

It should execute 3/25 however it didn't run until I log to portal to check status

2020-03-28 05:35:20.544 UTC Executing 'Functions.ContainerTimerTrigger' (Reason='Timer fired at 2020-03-28T05:35:20.5397130+00:00', Id=391a1eea-6b51-4477-9221-d2bc12682213)

Trigger Details: UnscheduledInvocationReason: IsPastDue, OriginalSchedule: 2020-03-25T02:05:00.0000000+00:00

Executed 'Functions.ContainerTimerTrigger' (Succeeded, Id=391a1eea-6b51-4477-9221-d2bc12682213)

Please provide the following:

- Timestamp:
- Function App version: 3
- Function App name: ewafunc
- Function name(s) (as appropriate): ContainerTimerTrigger
- Invocation ID: 391a1eea-6b51-4477-9221-d2bc12682213
- Region: West US

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

Timer trigger should work

#### Actual behavior

Timer trigger doesn't work until I login to portal and check function status

#### Known workarounds

None
#### Related information 

None

**Comment by kashimiz** [comment]
Hi @wuzhuoqing, I'm very sorry for the delayed response to your issue. Are you still experiencing the same problem with you timer trigger? If so, please provide the app information and invocation ID of the most recent failure to trigger.

Additionally, if you haven't, please take a look at our [timer trigger troubleshooting guide](https://github.com/Azure/azure-functions-host/wiki/Investigating-and-reporting-issues-with-timer-triggered-functions-not-firing) for common possible causes of a timer not firing/firing late.
