### ISSUE TITLE
Improve schedule description for function.json schema

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-host#5840]
_Related to https://github.com/microsoft/vscode-azurefunctions/issues/1989, filed by @PsychoData_

Currently the schema just says this:
![Screen Shot 2020-03-30 at 2 36 48 PM](https://user-images.githubusercontent.com/11282622/77964893-c4c20f80-7294-11ea-9308-284c55b84656.png)

but it'd be great if it had a description more like what the templates have, which shows up like this:
![image](https://user-images.githubusercontent.com/3719116/77452806-c12e1480-6dcc-11ea-9541-9f9e4521e7c7.png)

**Comment by brettsam** [comment]
Agree -- this would be a pretty simple schema update. Will assign it to our next sprint.

**Comment by fabiocav** [comment]
This will actually be bundled with some other changes in sprint 82
