### ISSUE TITLE
Azure function app host.json settings doesn't apply to the functions

### ISSUE THREAD

**Issue by matthew-kirtley** [Azure/azure-functions-host#5842]
I have a function which I publish in an Azure Function App via the App Service Plan (Standard).  I have overridden the functionTimeout in host.json to be 2 hours as below.  This used to work when I **_wasn't_** using the Startup.cs pattern for DI, but now that I've transitioned my function app to use a Startup.cs for DI, this timeout is ignored and the default timeout of 30 minutes is used.  I can see my function times out after 30 mins with a FunctionTimeoutException.  I can also see the host.json in the Azure portal looks correct.  Why is functionTimeout being ignored simply by changing to Startup.cs DI?

`{
  "version": "2.0",
  "functionTimeout": "02:00:00",

  "logging": {
    "logLevel": {
      "Org.Proj": "Information"
    }
  }
}`

**Comment by pragnagopa** [comment]
I cannot repro this. @matthew-kirtley - Can you please attach a simple repro?
