### ISSUE TITLE
Detect if the v2 ApplicationInsights Service for v2 has been replaced by customer dependency injection.

### ISSUE THREAD

**Issue by FinVamp1** [Azure/azure-functions-host#5843]
Customers are mistakenly overwriting the Application Insights dependency in Startup which results in missing data and dependencies not showing up in the Application Map.

This is referred to in the documentation here.
https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#logging-services 

and here

https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#version-2x-3 

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a New Functions Project

2. Add a Startup class.

3. Inject your own instance of TelemetryClient 

serviceCollection.AddSingleton<TelemetryClient>(sp =>
{
var configuration = TelemetryConfiguration.CreateDefault();

configuration.TelemetryProcessorChainBuilder.Use(next =>
{
var qpProcessor = new QuickPulseTelemetryProcessor(next);
qpProcessor.Initialize(configuration);
return qpProcessor;
});

#### Expected behavior

The runtime can log an error indicating that this may be missing and we can build a detector to share the above links with the customer.

#### Actual behavior

The Application Insights data and dependency tracking is affected and currently this needs a code review to detect and fix. 

#### Known workarounds

No workarounds exist.

**Comment by fabiocav** [comment]
@brettsam moving this to 74, but let me know if we need to assign it to a different milestone.

**Comment by brettsam** [comment]
We eventually decided to instead, unify on the Host's version of ApplicationInsights, which means that registering an `ITelemetryInitializer`, etc, in a newer version now does not matter. If we have a need for this again, we can re-enable, but this should get rid of a bunch of these scenarios where a customer moved ahead of what we support.

The PR that changed this: https://github.com/Azure/azure-functions-host/pull/5551
