### ISSUE TITLE
Debug output: Metadata generation failed. Exit code: '-1073741818'

### ISSUE THREAD

**Issue by euo** [Azure/azure-functions-host#5847]
I'm trying a simple Azure Function in VS 2019 but getting the following error when debugging. 

#### Environment:
Microsoft Visual Studio Community 2019
Version 16.5.0
VisualStudio.16.Release/16.5.0+29911.84
Microsoft .NET Framework
Version 4.8.03752

Microsoft.Azure.WebJobs.Extensions.CosmosDB 3.0.5
Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator 1.1.6\
Microsoft.NET.Sdk.Functions 3.0.1

Microsoft Azure Cosmos Emulator 2.9.2.0

#### Repro steps
1. Create new Azure Function project in Visual Studio.
2. Update *local.settings.json* with Cosmos connection string
3. Verify that Cosmos database, collection, connectionString are correct in *Function1.cs*
4. Ensure *MyCosmosDB* database and *Games* collection exists in CosmosDB
5. Hit F5 to debug

#### Expected behavior
Should build and debug without error. 

#### Actual behavior
1>------ Build started: Project: CosmosFunctions, Configuration: Debug Any CPU ------
1>CosmosFunctions -> D:\source\CosmosFunctions\bin\Debug\netcoreapp3.0\bin\CosmosFunctions.dll
1>Debug output from extension.json generator:
1>
1>C:\Users\mario\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.1.6\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(44,5): error : Metadata generation failed. Exit code: '-1073741818' Error: ''
1>Done building project "CosmosFunctions.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

#### Known workarounds
Tried steps and work around made by other developers here: 
[#4055](https://github.com/Azure/azure-functions-host/issues/4055)
[#4578](https://github.com/Azure/azure-functions-host/issues/4578)
[#5229](https://github.com/Azure/azure-functions-host/issues/5229)

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used
<details>
<summary>Source</summary>

```csharp
public static class GamesFunction
    {
        [FunctionName("Games_OnStatusFinalized")]
        public static void Run([CosmosDBTrigger(
            databaseName: "MyCosmosDB",
            collectionName: "Games",
            ConnectionStringSetting = "CosmosDBConn",
            LeaseCollectionName = "leases",
            CreateLeaseCollectionIfNotExists =true,
            LeaseCollectionPrefix ="")]IReadOnlyList<Document> input, ILogger log)
        {
            if (input != null && input.Count > 0)
            {
                log.LogInformation("Documents modified " + input.Count);
                log.LogInformation("First document Id " + input[0].Id);
            }
        }
    }
</details>

<details>
<summary>Source</summary>

```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "CosmosDBConn": "AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
  },
  "Host": {
    "LocalHttpPost": 7071,
    "CORS": "http://localhost:3872",
    "CORSCredentials": true
  }
}</details>

**Comment by kashimiz** [comment]
Hi @euo, thank you for reporting this issue. My apologies for the delayed reply. Can you share your *.csproj file?

**Comment by euo** [comment]
Thanks for the response, @kashimiz. 

here's my project file: 


`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.5" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.1.6" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>`

**Comment by ThejaChoudary** [comment]
@kashimiz can you please look into this further.

**Comment by v-anvari** [comment]
Hi @euo, I have tried to reproduce the scenario with the latest packages, but was able to build successfully. Let us know if you are still facing the same issue with build.

========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
microsoft.net.sdk.functions\3.0.7

**Comment by v-anvari** [comment]
Please feel free to re-open the issue if the issues re-occur
