### ISSUE TITLE
Azure functions crash after upload if authorization.json is present

### ISSUE THREAD

**Issue by ChrisAllisonMalta** [Azure/azure-functions-host#5852]
#### Check for a solution in the Azure portal
After I added an authorization.json file to my project the function in the portal breaks. The webpage that loads after deployment gives the following error "The page cannot be displayed because an internal server error has occurred." and all the functions disappear from the sidebar on the left. 

It only seems to come back after I edit the authorization.json file in the Kudos shell screen. AND then restart the app. I have to do this after every deployment.

#### Investigative information

Please provide the following:

- Timestamp: 1st & 2nd April
- Function App version: 2
- Function App name: stpatricks
- Function name(s) (as appropriate):
- Invocation ID:

Happy to provide more data if needed?

**Comment by ChrisAllisonMalta** [comment]
Just to confirm, if I publish my app it will fail, restart or stop and start won't work but IF I put some whitespace in the Authorization.json file via the Kudo (powershell) screen after a restart the app works immediately

**Comment by brettsam** [comment]
Could your json be invalid? I'm seeing a bunch of parsing exceptions like:

```
System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type Microsoft.Azure.AppService.Routes.RoutesConfig. Encountered unexpected character 'ï'. ---> System.Xml.XmlException: Encountered unexpected character 'ï'.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, XmlException exception)
   at System.Runtime.Serialization.Json.XmlJsonReader.ReadAttributes()
   at System.Runtime.Serialization.Json.XmlJsonReader.ReadNonExistentElementName(StringHandleConstStringType elementName)
   at System.Runtime.Serialization.Json.XmlJsonReader.Read()
   at System.Xml.XmlBaseReader.IsStartElement()
   ... snipped ...
```

**Comment by ChrisAllisonMalta** [comment]
Is that from my function or globally? I'm happy to send you my json but as I say if I put a single whitespace character in the file in the Kudo utility it works?

Maybe its my mac formatting something strangely but my other json files are parsed correctly?

**Comment by brettsam** [comment]
This is for your app specifically. The character it's showing as unexpected is `ï` -- so it's interesting that a whitespace would change that.

If you can send the broken and fixed json files to me that would help. My Microsoft email is in my github profile.

**Comment by brettsam** [comment]
Thanks @ChrisAllisonMalta -- I'll pass this around and see if we can figure out the issue. Will report back here. I'm wondering if this is an encoding issue -- and when you save via Kudu, it re-encodes it to something that we expect.

**Comment by brettsam** [comment]
I think this is an encoding issue -- I see that your file is "UTF-8 with BOM" which I suspect isn't getting read correctly. Can you check how you're saving this file? Maybe there's something you can do on your end to get it working?

**Comment by brettsam** [comment]
Keep in mind also that this feature (using the json file) is still considered in preview and is not considered GA. I don't know if/when that will ever happen, either...

**Comment by ChrisAllisonMalta** [comment]
> I think this is an encoding issue -- I see that your file is "UTF-8 with BOM" which I suspect isn't getting read correctly. Can you check how you're saving this file? Maybe there's something you can do on your end to get it working?

I'm just saving it in Visual Studio Mac like all of my other files, its just set to "copy to output directory". I was thinking it could be an encoding issue

**Comment by ChrisAllisonMalta** [comment]
> Keep in mind also that this feature (using the json file) is still considered in preview and is not considered GA. I don't know if/when that will ever happen, either...

Appreciate that but it would be good to have someway to restrict authenticated or unauthenticated calls to the API

**Comment by inuvano-labs** [comment]
I came across this issue yesterday - uploading the authorization.json file to the root of function app resulted in "The page cannot be displayed because an internal server error has occurred."

The file was UTF-8 encoded, when it should be ANSI. This was caused by me accidentally adding the file as a .js file and renaming it in Visual Studio to .json (.js = utf-8, .json = ANSI). Re-creating the file in VS fixed the issue.

**Comment by brettsam** [comment]
This has been sitting a while -- going to close as this was likely an encoding issue. Please feel free to re-open if this persists.

**Comment by ChrisAllisonMalta** [comment]
The issue hasn't gone away for me at least, this came up in a file new project created in VS (mac). I will check the encoding though, does the Azure runtime normally require ANSI or UTF-8 encoded files?

**Comment by brettsam** [comment]
Someone above claimed that changing it to ANSI worked for them. I'm not entirely sure where this code is so I can't comment on how it is loaded or what encoding it expects. If ANSI doesn't work, I can follow up further.
