### ISSUE TITLE
Azure function build not creating Startup class entry in extensions.json

### ISSUE THREAD

**Issue by miantosca** [Azure/azure-functions-host#5860]
Upgraded existing v2~ function project to v3~ and targeting .NET Core 3.1  with SDK v3.0.5 and now DI is no longer working.

I tracked down the issue and found that the extensions.json file that is created during build does not include an entry for Startup class - where the DI container is configured.

I manually added an extensions.json file that includes an entry for Startup and DI works correctly when running locally. I set it to Copy To Output Always.

When I use Azure devops and deploy to the function app service in Azure - the extensions.json file is not copied to the bin directory. There is a extensions.json in the bin i but it is the one that is automatically (incorrectly) created and does not include the Startup entry.

This is the 3rd time in 2 years I have run into DI issues when upgrading from one version of the SDK to another

I read through issue https://github.com/Azure/Azure-Functions/issues/972 (now closed) but none of the suggestions helped

**Comment by hallidev** [comment]
I've been battling this exact issue for at least a year now. I've been using Zip Deploy with a custom Directory.Build.targets for the entire time since publishing the Zip Deploy screws up extensions.json. This workaround has been good enough until the latest update where it now breaks locally but is still required to run in Azure. I've abandoned Azure Functions for every use case I can away with, but I still have some timer functions I can't get off this mess of an offering.

**Comment by hallidev** [comment]
@miantosca In case this helps, I discovered that in my case, using a Self Contained zip deploy triggers the issue. I'm not sure if this is relevant to your build, but figured I'd put it out there.

**Comment by AndyMDoyle** [comment]
I have been having the same issue with Microsoft.NET.Sdk.Functions 3.0.4, 3.0.5, and 3.0.7 (skipped 3.0.6).

Startup is not added to extensions.json when publishing in Release mode in the following ways:

- Folder - framework dependent or self-contained
- Zip Deploy - framework dependent or self-contained

Using Directory.Build.targets was working, but now causes publishing to fail locally.

Building in Debug mode does correctly create extensions.json.

**Comment by brettsam** [comment]
Can anyone hitting this please share exactly what your publish command is that is broken? Are you using rid like `-r win-x86`?

**Comment by AndyMDoyle** [comment]
I'm targetting win-x86. Here are the settings I've used to test publishing locally:

![image](https://user-images.githubusercontent.com/307719/82248632-633b2a80-9940-11ea-8f33-0ab7093365e9.png)

**Comment by brettsam** [comment]
Does it work if you use win-x64? I'm trying to investigate why win-x86 fails to generate extensions.json correctly, yet win-x64 works.

**Comment by AndyMDoyle** [comment]
Looks like it does work using win-x64.

**Comment by AndyMDoyle** [comment]
Here's a snippet of the diag output for both runtimes that show the startup isn't discovered in our assembly (AzureFunctionsV3.dll) when targeting win-x86:

win-x64:

```
...
Azure.Security.KeyVault.Secrets.dll (TaskId:175)
AzureFunctionsV3.dll (TaskId:175)
        Resolving assembly: 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' (TaskId:175)
        Assembly 'System.Runtime' loaded. (TaskId:175)
        Resolving assembly: 'Microsoft.Azure.Functions.Extensions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f655f4c90a0eae19' (TaskId:175)
        Assembly 'Microsoft.Azure.Functions.Extensions' loaded from 'C:\Users\doyle\Source\BostonVSTS-Repos\Partner Portal\Src\Web\AzureFunctionsV3\bin\Debug\netcoreapp3.1\win-x64\bin\Microsoft.Azure.Functions.Extensions.dll'. (TaskId:175)
        Resolving assembly: 'Microsoft.Azure.WebJobs.Host, Version=3.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' (TaskId:175)
        Assembly 'Microsoft.Azure.WebJobs.Host' loaded from 'C:\Users\doyle\Source\BostonVSTS-Repos\Partner Portal\Src\Web\AzureFunctionsV3\bin\Debug\netcoreapp3.1\win-x64\bin\Microsoft.Azure.WebJobs.Host.dll'. (TaskId:175)
        Found extension: AzureFunctionsV3.Startup, AzureFunctionsV3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (TaskId:175)
CodeFirstStoreFunctions.dll (TaskId:175)
...
```


win-x86
```
...
Azure.Security.KeyVault.Secrets.dll (TaskId:191)
AzureFunctionsV3.dll (TaskId:191)
CodeFirstStoreFunctions.dll (TaskId:191)
...
```
