### ISSUE TITLE
Implement @reboot for TimerTrigger functions to run only once on start-up

### ISSUE THREAD

**Issue by ZippoLag** [Azure/azure-functions-host#5861]
#### What problem would the feature you're requesting solve? Please describe.
For cases when we need some type of initialization to take place when an App Service starts, it could be useful to have this done in an Azure Function that would run only once with the start of the process and then never again (until it is stopped and started or restarted).

In other CRON using servers, this seems to be available using the @reboot value instead of a CRON expression: https://en.wikipedia.org/wiki/Cron#CRON_expression

#### Describe the solution you'd like
Have TimerTrigger functions accept "@reboot" as valid value, signifying that they should be ran only once at start-up.

#### Describe alternatives you've considered
Re-architecture initialization neccesary in other functions; have them done in an HTTPTrigger and fire it manually; have them performed manually by an external process.

#### Additional context
I first noticed a need for something like this while working with a function that keeps an auth token for an external API fresh in a TableStorage. But in cases where the service needs to be stopped for a while, the easiest way to avoid handling expired tokens is to clean up the stored tokens by hand before starting the service again. Althought there are other ways to deal with this issue (actually implement expired token handling) it made me realize this could be a useful feature for other situations as well.

**Comment by v-anvari** [comment]
Hi @ZippoLag , sorry   for the delayed response. From the request we understand that you are looking out for [runOnStartup](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=csharp#configuration) property. Please set the attribute in _function.json_ to   "_**true**_", and set the CRON expression to **_"0 0 0 * * *"_**

The binding will look something like the below:
{
"bindings": [
{
"name": "Timer",
"type": "timerTrigger",
"direction": "in",
"schedule": "0 0 0 * * *",
"runOnStartup": "true"
}
]

Let us know if this helps.
