### ISSUE TITLE
Reading cosmosdb errors in my Azure functions

### ISSUE THREAD

**Issue by ramxis** [Azure/azure-functions-host#5871]
#### Question
Hey , is there a way to access error codes from output binding for cosmos db in azure fucntion, like if i have a binding to cosmosDB which writes a new document to it,
I want to access the error code when this write request is rejected because the document Id already exists. The function throws but never goes in the catch block so i cannot send the error code back to the user. It automatically responds with 500 internal server error.
Note: reqId is added as unique key in cosmos db
```
try {
            context.bindings.createRequestDocument = JSON.stringify({
                reqId: req.body.did + "-" + req.body.reqType,
                did: req.body.did, 
                requestType: req.body.reqType,
                data: req.body.data,
                status: "requested"
            });

        } catch (error) {
            context.log(error)
        }
```

**Comment by fabiocav** [comment]
@ramxis this is not a capability exposed to JavaScript today, but something we're actively tracking.
