### ISSUE TITLE
ReadyToRun support

### ISSUE THREAD

**Issue by galvesribeiro** [Azure/azure-functions-host#5876]
Hello folks!

Is there a way to support [ReadyToRun](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#readytorun-images) assemblies on Azure Functions?

It would help a lot the functions app cold start.

If that is already supported, do I just need to produce the right binary for the target function app host (linux or windows) ?

Thanks!

**Comment by safihamid** [comment]
Yes this is already supported.
Here is an example:

<PropertyGroup>

    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

> 

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.5" />
  </ItemGroup>
 

> 

And then you can publish your project with:
 dotnet publish youproj.csproj -r win-x86 -c release

With -r you can provide your RID or add it to your csproj file

**Comment by petro2050** [comment]
@safihamid Is there a way to publish with RID via VS Publish UI? I'm currently not using the CLI.

![Untitled](https://user-images.githubusercontent.com/62858360/79695200-28f44580-823b-11ea-8471-404ff46306e5.png)

Also, you said that we could add the RID to csproj. What part of the project file should it be added? I can't find code samples.

**Comment by petro2050** [comment]
Nevermind. I was able to add `<RuntimeIdentifier>win-x64</RuntimeIdentifier>`. I noticed this slows down deployment time (which is okay). I will analyze runtime latency and see how RID is helping. Thanks a lot for the suggestion!

**Comment by galvesribeiro** [comment]
@safihamid thanks for getting back! Awesome news!

I'll try that tomorrow. Out development is fully on OSX but our hosts are linux so will just pass the `-r` at the CI servers.

Will keep you posted soon, thanks!

Gutemberg

**Comment by petro2050** [comment]
@safihamid I just published (which was successful), but this shut down the app. I'm getting 503 errors. I restarted the app on Azure portal, but I'm still getting 503 after waiting for a while. If you can share your email, I'll send you info for you to look at the issue.

**Comment by safihamid** [comment]
@petro2050 is your app 32bit or 64bit? If 64bit make sure in azure portal you also pick 64bit. If 32bit make sure you publish with win-x86. My email hamids at MICROSOFT dot com

**Comment by petro2050** [comment]
@safihamid Looks like it was 32bit. Changing it to 64bit fixed the issue!

In the publish UI, does it make a difference if the deployment mode is framework dependent or self contained? 

Also should I check `Produce single file` and `Remove additional files at destination`? If I choose self contained option, then another checkbox appears to `trim unused assemblies`.

![Capture](https://user-images.githubusercontent.com/62858360/79696339-ba66b600-8241-11ea-8aa7-9e8499aa26f4.PNG)

**Comment by safihamid** [comment]
@petro2050 select 'framework dependent'. This option should reduce your zip size.

**Comment by galvesribeiro** [comment]
So, I've added this to the csproj:

```
 <PropertyGroup Condition="'$(BuildType)' == 'publish'">
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
    <UseAppHost>true</UseAppHost>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
  </PropertyGroup>
```

Then `dotnet publish -c Release -o buildoutput`. Besides all the regular build messages, now I have those warnings:

```
/Users/guto/.nuget/packages/microsoft.azure.webjobs.script.extensionsmetadatagenerator/1.1.5/build/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(63,5): warning :     Could not evaluate 'Microsoft.Azure.Cosmos.ServiceInterop.dll' for extension metadata. Exception message: Bad IL format. [/Users/guto/dev/repos/PagoLivre/Gateway/src/PL.Gateway/PL.Gateway.csproj]
/Users/guto/.nuget/packages/microsoft.azure.webjobs.script.extensionsmetadatagenerator/1.1.5/build/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(63,5): warning :     Could not evaluate 'Cosmos.CRTCompat.dll' for extension metadata. Exception message: Bad IL format. [/Users/guto/dev/repos/PagoLivre/Gateway/src/PL.Gateway/PL.Gateway.csproj]
```

I assume the `Bad IL format` is because those are not .net assemblies but instead native libraries, right?

Also, even with that, when I look at the output directory I see the same structure of DLLs that I had before... Is that correct?

**Comment by safihamid** [comment]
@galvesribeiro  make sure you are using sdk 3.0.5 or higher:

> <ItemGroup>

    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.5" />
  </ItemGroup>

> 

Yes the output library structure is same but file sizes are larger becasue they include native code as well. I think you can ignore those warnings.

**Comment by galvesribeiro** [comment]
Hello @safihamid! Sorry for the delay on reply.

Tried with the latest version:

```
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.7" />
```

The build works, but the app doesn't start on Azure:

![image](https://user-images.githubusercontent.com/4714040/82774090-3b553680-9e1a-11ea-8b05-93cab5dfe5e2.png)

Any thoughts?

**Comment by safihamid** [comment]
@galvesribeiro feel free to share the app name and I will take a look.

**Comment by galvesribeiro** [comment]
Hello @safihamid 

I just found out what was the problem. Since Az Func is not really well integrated with Az App Config service, It was failing to start because of a problem on the config side.

I did hacked around the problem (which btw, we should definitively have it solved and get Az Func to play nice with Az App Config) and it worked just fine. 

Thanks!

**Comment by galvesribeiro** [comment]
So, for people that arrived to this issue in the future, this is what you need todo:

1. Add the props to the project (optionally make it to only run when publishing the project):
```
 <PropertyGroup Condition="'$(BuildType)' == 'publish'">
    <PublishReadyToRun>true</PublishReadyToRun>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
  </PropertyGroup>
```

2. Use `dotnet publish` instead of the `dotnet build` which is suggested by other project templates:
```
dotnet publish ./MyFunctionProject/MyFunctionProject.csproj --configuration Release -r linux-x64 --output ./output
```

3. Push the function from the output directory whatever way you want to.

**Comment by safihamid** [comment]
@galvesribeiro glad you are unblocked. here is the list you should be using:

` <PropertyGroup Condition="'$(BuildType)' == 'publish'">
    <PublishReadyToRun>true</PublishReadyToRun>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
  </PropertyGroup>`

 For RuntimeIdentifier you can win-x86, win-x64 or linux-x64 depending where you are hosting your Function app. Also do not use --self-contained. there is no need for that and it just increases the size of your zip file.

**Comment by galvesribeiro** [comment]
Ok cool! Will remove those here. I've also updated the previous comment. Thanks!
