### ISSUE TITLE
Custom handlers - configure working directory for worker process

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-host#5882]
Some applications are happier when you can configure the working directory in which it runs.

For instance:

```json
{
    "version": "2.0",
    "httpWorker": {
        "description": {
            "defaultExecutablePath": "node",
            "defaultWorkerPath": "myapp/server.js"
        }
    }
}
```

Would be great if we could do something like the following instead:

```json
{
    "version": "2.0",
    "httpWorker": {
        "description": {
            "defaultExecutablePath": "node",
            "defaultWorkerPath": "server.js",
            "defaultWorkingDirectory": "myapp"
        }
    }
}
```

**Comment by pragnagopa** [comment]
This is supported now. You can override, `WorkerDirectory` element and this takes precedence over default value which points to function app root directory.  

Please note that,  relative paths for  `defaultExecutablePath` and `defaultWorkerPath` use `WorkerDirectory` as parent directory. 

Right now we only support  `WorkerDirectory`  to be set to full path and not relative to function app  root folder.  Let me know if you think adding support for specifying relative paths is useful.

**Comment by pragnagopa** [comment]
Synced up with @anthonychu 

We can set working directory before launching the process. To be able to figure out Function App root, need to either set an environment variable - `FunctionAppRoot` or look up any existing environment variables that have this value already.
