### ISSUE TITLE
AddAuthentication() as IdentityServer4 throws exception - is that a bug or non-existing feature?

### ISSUE THREAD

**Issue by MichalLechowski** [Azure/azure-functions-host#5886]
Hello,

is authentication/authorization using IS4 possible in Azure Function v3 (.net core 3.1)?

What I mean is this works in a regular WebAPI (code is just a partial example):
```
public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {    
            services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
                    .AddIdentityServerAuthentication(options =>
                    {
                        options.Authority = "https://localhost:1234";
                        options.RequireHttpsMetadata = false;
                        options.ApiName = "APIv1";
                        options.ApiSecret = "mySecret";
                        options.SupportedTokens = SupportedTokens.Both;
                    });
       }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseAuthentication();
            app.UseAuthorization();
        }
}
```  
And I just put **[Authorize(Roles = "admin")]** attribute over endpoints to call the IS4 auth.

What I need is to setup something similar for Azure Function v3 (.net core 3.1) that uses the very same IS4 instance, so the goal is:

```
[assembly: FunctionsStartup(typeof(AzFunction.Startup))]

namespace AzFunction
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {          builder.Services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
                    .AddIdentityServerAuthentication(options =>
                    {
                        options.Authority = "https://localhost:1234";
                        options.RequireHttpsMetadata = false;
                        options.ApiName = "APIv1";

                        options.ApiSecret = "mySecret";
                        options.SupportedTokens = SupportedTokens.Both;
                    });
        }
    }
}
```

and creating something like:
```
       [Authorize(Roles = "admin")]
        [FunctionName("MyPreciousFunction")]
        public async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Function, "post", Route = null)] HttpRequest req, ILogger log)
```

There is no **public void Configure(IApplicationBuilder app, IWebHostEnvironment env)** available in startup to use app.UseAuthentication() (and authorization), also the attributes like [Authorize] are not working for Azure Functions if I've found the correct info. 

Also there's something somewhat related but it didn't help me much:
[ISSUE 4485](https://github.com/Azure/azure-functions-host/issues/4485)

If that's any help, running it locally ends with:
![Annotation 2020-04-15 202512](https://user-images.githubusercontent.com/34692839/79374087-66b14f80-7f57-11ea-9e4a-ddffb540f499.png)

Is there ANY way right now to use IS4 with Azure Function v3 or am I trying to setup something that won't work atm? I report it as a bug but this might be a feature request, as well. I don't know.

Greetings

**Comment by espray** [comment]
No there is not an out-of-box way to get IdentityServer to work with AzFunc.

- `AddAuthentication()` dose not work

- .net core middleware is not supported

- Authorize attributes are not supported.

However, I did get it to get IdentityServer to work a little. Along with issue https://github.com/Azure/azure-functions-host/issues/4485, I had to create a custom `IEndpointRouter` this helped https://stackoverflow.com/questions/39186533/change-default-endpoint-in-identityserver-4. Never tried to get the UI to work. But I quickly abandoned it for `AspNet.Security.OpenIdConnect.Server` it was simpler. So yes you can get it to work, but you might not get the results you are looking for.

**Comment by yojagad** [comment]
@MichalLechowski Apologies for the late response. Were you able to get around this?
