### ISSUE TITLE
Hi, 

### ISSUE THREAD

**Issue by ShreyaRai18** [Azure/azure-functions-host#5888]
I am trying to run azure functions in python. When I run the default hello program, I am getting an error code 500, localhost is currently unable to handle this request.

**Comment by ankitkumarr** [comment]
Hi, can you please add a repro of how you are running, and what code you are trying to run? Also please share the output and the exact error you see.

**Comment by ShreyaRai18** [comment]
<img width="951" alt="azurefun" src="https://user-images.githubusercontent.com/47493022/79555137-b5c4c500-80bc-11ea-8071-cfc29d1ab7b8.PNG">

 Here's is an image of the error I'm facing

**Comment by ankitkumarr** [comment]
Hi @ShreyaRai18, we had some issues with the last Functions Python release. Would you mind updating your local core tools and retrying?

Also I can't really reproduce the issue on my end. Do you have a code sample or a repro that I can run locally and debug?
Thanks!
