### ISSUE TITLE
[Question] Blob Trigger Retries

### ISSUE THREAD

**Issue by blawford** [Azure/azure-functions-host#5890]
I am using a function with a blob trigger, I am trying to find out whether there is a way to tell what number retry the blob being processed is currently on? 

If there isn’t, is there a way to catch execution before it writes the record to the poison queue?

I want to carry out different behaviour whether the blob will be retried or not.

**Comment by blawford** [comment]
Bump.

**Comment by fabiocav** [comment]
@blawford that information is surfaced as part of the trigger data. 

You can see an example that uses the `DequeueCount` here: https://docs.microsoft.com/en-us/sandbox/functions-recipes/queue-storage#retrieving-queue-metadata-from-an-azure-storage-queue-trigger
