### ISSUE TITLE
Compiling with missing connection string creates unsuppressible warning

### ISSUE THREAD

**Issue by paulhickman-a365** [Azure/azure-functions-host#5891]
#### Version Information

- Function App version: 2
- Language: C# Compiled .Net Core Assembly
- Compile-time issue, so app instance not relevant

#### Steps to Reproduce

I have a c# .Net function assembly with a function that uses a service bus trigger:

````
[FunctionName("MyFunction")]
public async Task MyFunction([ServiceBusTrigger(MY_QUEUE_NAME, Connection = "MyConnectionString")]string message)
{
    //...
}
````

This would normally require ````MyConnectionString```` to be defined in ````localsettings.json````. However, I have modified the DI services collection during function startup to inject an alternate ````IConfiguration```` provider that reads from Azure key vault as well as the local settings file so I can avoid having secrets such as connection string in the local file.

This all works fine except during build I get a warning:

````
Warning		Function [MyFunction]: cannot find value named 'MyConnectionString' in local.settings.json that matches 'connection' property set on 'serviceBusTrigger'
````
This comes from microsoft.net.sdk.functions\1.0.34\build\Microsoft.NET.Sdk.Functions.Build.targets, line 41.

I can't complain about the presence of this warning; most people won't have hacked around with the startup like I have, so would be grateful to be warned about this. My problem is I need to suppress the warning so it isn't reported to our code quality tools, but it doesn't have any error code associated - the code column is empty. Therefore, there is noting to key a suppression rule against.

#### Expected behavior

This, and any other build-time errors/warnings generated by the functions app target have error codes, so that a suppression/other severity rules can be created.

**Comment by v-anvari** [comment]
Hi @paulhickman-a365 , We totally Apologize for the delayed response. You can refer the [link](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-suppress-compiler-warnings?view=vs-2019#suppress-warnings-for-visual-basic) to suppress the warnings. Do let us know if you are looking for any other information as well.

**Comment by paulhickman-a365** [comment]
@v-anvari  These warnings are logged with no error code, it is blank column. 

Therefore, it isn't possible to suppress them using the techniques described in those links.

**Comment by v-anvari** [comment]
Adding this issue to triage to find any work around solution to suppress these warnings.

**Comment by v-anvari** [comment]
cc @soninaren , for any workarounds if possible

**Comment by v-anvari** [comment]
Hi @paulhickman-a365 , Can we know where and how are you injecting these values and registering it in DI. For not all scenarios, but, adding or defining a dummy 'MyConnectionString' in local.settings.json can suppress the warning, because the DI will override the value in local.settings.json. Can you try that as a work around and let us know if that worked for you.
