### ISSUE TITLE
Is it possible to deploy an Azure Function in self contained mode ?

### ISSUE THREAD

**Issue by karim007** [Azure/azure-functions-host#5898]
When I try to deploy in self contained mode, I get the following error:

`at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp,Type type,Type requiredBy,Boolean isDefaultParameterRequired) at lambda_method(Closure ,IServiceProvider ,Object[] ) at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IServiceProvider serviceProvider) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs : 37 at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IFunctionInstanceEx functionInstance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs : 32 at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.<>c__DisplayClass1_1.<.ctor>b__0(IFunctionInstanceEx i) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs : 20 at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.Create(IFunctionInstanceEx functionInstance) at C:\projects\azure-webjobs-sdk-`

But when I deploy in framework dependent I have no issue.

So I am wondering if it possible?

Thanks.

**Comment by gzuber** [comment]
Hey @karim007 -- I'd need a little more info to answer definitively. Is your function consumption? dedicated? elastic premium? Is there a specific issue you're trying to fix by deploying self contained (i.e. coldstart time)?

Generic Answer: For the most part (and depending on your hosting setup), deploying in self contained mode is not possible. The runtime that loads and runs your function/dependencies is already deployed to a worker and is potentially also running other functions with other dependencies. However, there are potential fixes we can help you out with depending on the issue you're trying to resolve so let us know and we'll see what we can do.
