### ISSUE TITLE
Default consumption sku function timeout should apply to Linux also

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-host#5902]
Both windows and linux consumption apps should have the same default function timeouts.

https://github.com/Azure/azure-functions-host/blob/ded932ba6de4353bf466e0afb6732d4dba208e5b/src/WebJobs.Script/Config/ScriptHostOptionsSetup.cs#L73

**Comment by v-anvari** [comment]
Hi @balag0 , Just checking if we have any update on this issue. Does this require any fixes to be done

**Comment by balag0** [comment]
Yes. this needs to be tracked and fixed.

**Comment by pragnagopa** [comment]
Tagging @brettsam @fabiocav  for breaking change in V4

**Comment by fabiocav** [comment]
@pragnagopa / @balag0 can you please follow up with a breaking change proposal for this so we can have it tracked? Feel free to follow up offline if needed.

**Comment by pragnagopa** [comment]
Breaking change proposal is submitted and approved. Will be sending a PR soon.

**Comment by fabiocav** [comment]
Closing as resolved.
