### ISSUE TITLE
BlobTrigger firing again on a different machine

### ISSUE THREAD

**Issue by Noxxys** [Azure/azure-functions-host#5910]
#### Is your question related to a specific version? If so, please specify:
no

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
I have a few Azure Functions running every day in production, and one of them is using a BlobTrigger, which is triggered a few hundred times per day.

Whenever I want to debug this Azure Function on my local machine, the BlobTrigger fires for every blob that was added since the last time I ran the function locally on my machine. So I have to add a return statement at the beginning of my function and wait for thousands of triggers to be fired. It takes like 15 minutes. Then I can finally start working.

Is there a way to empty the message queue in one go? Or to change this behavior? Should I do something extra to tell Azure that a blob is handled for all machines?

In the Azure Storage Explorer, I can see that one queue exists for each machine, and each only contains one message at a time. So I can't purge it.

**Comment by fabiocav** [comment]
The state is based on the host ID, which when running locally, is derived from the machine name. There's no tooling to update that state for you, but the recommendation would be to use a different queue (ideally, a different storage account) for local dev/test.
