### ISSUE TITLE
System.UnauthorizedAccessException while adding 'function.proj' file

### ISSUE THREAD

**Issue by mkarthik156** [Azure/azure-functions-host#5911]
For In Portal development on Azure functions, tried installing packages using "function.proj" file.
Following(Attached Error_log.txt) is the error message received.
[Error_log.txt](https://github.com/Azure/azure-functions-host/files/4528444/Error_log.txt)

#### Investigative information

Please provide the following:

- Timestamp: 2020-04-24T10:57:52.006
- Function App version: ~3
- Function App name: 
- Function name(s) (as appropriate): 
- Invocation ID: 68f0d553-1e13-4038-9029-bb263ecebff3
- Region: East US

#### Repro steps

Try to upload function.proj file.

#### Expected behavior
The package restore should start and successfully installs.

#### Actual behavior
Following error is thrown.
System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.

#### Known workarounds

Earlier the same issue happened in Function app version ~2 months back. Got workarounds from github. Following application setting has to be added, which worked back then.

Name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
Value: 1

#### Related information 

Provide any related information 

* Programming language used: C#
* Links to source
* Bindings used

**Comment by leafsy** [comment]
Having the same issue on the portal (trying to install the Microsoft.Azure.Devices package). Tried the previous workaround but no luck either.

**Comment by mkarthik156** [comment]
Below is the workaround provided in error #5893 which works for me
https://github.com/Azure/azure-functions-host/issues/5893#issuecomment-621254026

**Comment by v-anvari** [comment]
Hi @mkarthik156 ,  Let us know if you are still facing the issue

**Comment by mkarthik156** [comment]
> Hi @mkarthik156 , Let us know if you are still facing the issue

@v-anvari  It seems to be resolved now.
Thanks
