### ISSUE TITLE
Ability to Change Host.Json Customer Headers Per Environment

### ISSUE THREAD

**Issue by dsm0880** [Azure/azure-functions-host#5919]
#### What problem would the feature you're requesting solve? Please describe.
I'm deploying a new CSP (Content Security Policy) for my application. The objective is to whitelist all the resources you app will use in a single header. This header changes per deployment slot for our application. The custom headers property in the host.json is great, but I would love to reference the Application Settings to make this variable by slot. To my knowledge influencing a host.json file setting using Application Settings is not possible. The only thought I have is to rip out the file and modify in the Release Pipeline.

#### Describe the solution you'd like
Ability to influence host.json settings in Application Settings or at least the ability to modify custom headers.

#### Describe alternatives you've considered
The workaround is to replace the host.json with the parameters you need through deployment scripts.

**Comment by pragnagopa** [comment]
cc @fabiocav 

You can override `host.json` sections via AppSettings. Please see here: https://stackoverflow.com/questions/59949260/azure-functions-can-you-override-host-settings

Opened doc issue: https://github.com/MicrosoftDocs/azure-docs/issues/55807 to update docs with this info.

Closing this issue.
