### ISSUE TITLE
Settings not getting deployed from VS to Azure

### ISSUE THREAD

**Issue by andrewkittredge** [Azure/azure-functions-host#5930]
I have a .net core Azure function with the settings in local.settings.json.  Copy to Output Directory is set to "Copy Always".  I have remote.settings.json for good measure.

Everything works locally.  When I deploy to Azure none of my settings appear and the function does not work because it is missing configuration data.  Previously some of my settings were deployed, it mysteriously stopped working.

![image](https://user-images.githubusercontent.com/430274/80553568-5c03ab00-8998-11ea-88e8-e3dded32927d.png)

![image](https://user-images.githubusercontent.com/430274/80553705-d03e4e80-8998-11ea-8932-1125d223ecab.png)

![image](https://user-images.githubusercontent.com/430274/80553810-23180600-8999-11ea-9a22-575ada90ed67.png)

I am using version 3.0.1

**Comment by ankitkumarr** [comment]
@andrewkittredge, `local.settings.json` is meant for local development only. For settings in Azure, you'd want to manually set "Application Settings".

You can read about this file [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cbash#local-settings-file).

Please let me know if that answers your question.

**Comment by andrewkittredge** [comment]
The only way supply settings for a function is on portal.azure.com?  That does not seem like very good design.

**Comment by ankitkumarr** [comment]
@andrewkittredge, you could update the Application settings using [Azure Functions Core Tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cbash#project-file-deployment) or [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/functionapp/config/appsettings?view=azure-cli-latest). But the configuration settings do need to come from Application Settings.

Using Azure Functions Core Tools (`func` CLI), you can run --
```shell
func azure functionapp publish <app-name> --publish-settings-only
```
And that will update all your Application Settings in Azure to be settings from `local.settings.json`.

Please let me know if you have further questions on this.
