### ISSUE TITLE
Clean up azure-pipelines.yaml signing

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-host#5934]
Recently we added signing for `WebJobs.Script.Abstractions` (in addition to `ExtensionsMetadataGenerator`) in the pipeline for v2.x. We need to clean them up and consolidate them together.

**Comment by ankitkumarr** [comment]
Moving as we already had to shrink the pipeline and it's not as big of a priority. The `WebJobs.Script.Abstractions` is only in dev and only has a single way to sign.

Moving to the next Sprint.

**Comment by fabiocav** [comment]
@ankitkumarr was this closed?

**Comment by ankitkumarr** [comment]
Closed by https://github.com/Azure/azure-functions-host/commit/52e90eda99710c0761049b7d6083ff09272cf4f6
