### ISSUE TITLE
Creating a blob function / queue function on a few function app puts runtime in a bad state

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#5944]
This is not a wide spread issue, but can be consistently reproduced for an app in a bad state. Will be adding more information to this issue.

**Comment by fabiocav** [comment]
Flagging this as a P1 as we may need to add to the current sprint

**Comment by soninaren** [comment]
Looks like this is caused by incorrect connection string created by the portal. When you create a new function from portal, add a new connections string. It presents you with a drop down to select storage account. Once you select a storage account, portal fetches the connections string and creates a new app setting. The issue is that the key in the connection string does not match the storage account. This is somehow bringing the entire function app down.

**Comment by soninaren** [comment]
Closing this one. Have created a follow up issue here. https://github.com/Azure/azure-functions-host/issues/6030
