### ISSUE TITLE
Asking for .NET Core 3.1; but getting .NET Core 2.1

### ISSUE THREAD

**Issue by WinInsider** [Azure/azure-functions-host#5967]
Azure Functions for Linux (Service Plan)
Azure Functions Runtime version : 3
.NET Core 3.1 / C#
Regions : Central US, East US, Canada East

**Question**: Have created three Azure Functions (in Central US, East US, Canada East)… **with** .NET Core as Platform and Version selected to **.NET Core 3.1** (during Function creation in Azure Portal); however, each time .NET Core Runtime version 2.1.300 is installed on Debian 8 Linux (x64). This is observed by going to BASH console of the Azure Function and entering "dotnet --info"

.NET Core 3.1 is no where to be found

Is this normal?
How can I get .NET Core 3.1 on Azure Function (Linux)?

**Comment by soninaren** [comment]
@balag0 , @ahmelsayed Any ideas?

**Comment by balag0** [comment]
Bash is misleading as it connects to a different container (kudu) that only shares files with the app container. The app is running in a different container based on mcr.microsoft.com/dotnet/core/sdk:3.1.  Are you seeing any runtime failures? 

More details on bash console:
https://techcommunity.microsoft.com/t5/azure-app-service/things-you-should-know-web-apps-and-linux/ba-p/392472#KuduContainer

**Comment by WinInsider** [comment]
cool, good to know...

am getting "Microsoft.Data.SqlClient is not supported on this platform" error; but that is different topic... will close this one.

thanks @balag0
