### ISSUE TITLE
ServiceBusTrigger maxConcurrentCalls

### ISSUE THREAD

**Issue by matthewhancock** [Azure/azure-functions-host#5968]
#### Is your question related to a specific version? If so, please specify:
Azure Functions V3

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
I am trying to set the number of max concurrent calls when running a Function locally, however, the host.json file appears to be ignored. Sessions are enabled and I have 30,000+ messages queued up across many partitions, so I get inundated.

This is my current host.json based on other's I've seen where this has worked.
```
{
  "version": "2.0",
  "extensions": {
    "serviceBus": {
      "prefetchCount": 1,
      "messageHandlerOptions": {
        "maxConcurrentCalls": 1
      },
      "sessionHandlerOptions": {
        "maxConcurrentCalls": 1
      }
    }
  }
}
```

The log output during startup under `Host configuration file read:` does not output anything under the extensions property (when I move serviceBus to the root, the settings are logged but still have no impact - but I at least know the host.json is up to date during execution).

Then further down the startup logs when outputting the configuration it shows the host.json file is ignored:

```
ServiceBusOptions
{
  "PrefetchCount": 0,
  "MessageHandlerOptions": {
    "AutoComplete": true,
    "MaxAutoRenewDuration": "00:05:00",
    "MaxConcurrentCalls": 64
  },
  "SessionHandlerOptions": {
    "AutoComplete": true,
    "MaxAutoRenewDuration": "00:05:00",
    "MaxConcurrentSessions": 2000,
    "MessageWaitTimeout": "00:01:00"
  }
}
```

I keep searching for examples, and follow this documentation: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-output?tabs=csharp#host-json

However, I've had no luck. I'd appreciate any help or tips as to how to resolve this. Thanks!

**Comment by ivan-sam** [comment]
We've got the same issue.
Did try

    func extensions install --package Microsoft.Azure.WebJobs.Extensions.ServiceBus

and adding package Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator with no effect

**Comment by ivan-sam** [comment]
We found what caused the problem in our case.
In method `override void Configure(IFunctionsHostBuilder builder)` of function Startup we replaced `IConfiguration` to add appsettings.json, keyvault, etc like this (it worked for prev version of functions):

```
    var configurationBuilder = new ConfigurationBuilder()
        .SetBasePath(currentDirectory)
        .AddJsonFile("appsettings.json")
        .AddEnvironmentVariables();

    var descriptor = builder.Services.FirstOrDefault(d => d.ServiceType == typeof(IConfiguration));
    if (descriptor?.ImplementationInstance is IConfigurationRoot configuration)
    {
        configurationBuilder.AddConfiguration(configuration);
    }

    config = configurationBuilder.Build();

    // replace the existing config with the new one
    builder.Services.Replace(ServiceDescriptor.Singleton(typeof(IConfiguration), config));
```

The issue is that `IConfiguration` is not listed in `ServiceCollection` at this point. So we effectively injected our version of `IConfiguration` missing some system-level providers like `HostJsonFileConfigurationProvider` (which contains configuration properties for extensions including ServiceBus).

We fixed it by replacing
```
    var descriptor = builder.Services.FirstOrDefault(d => d.ServiceType == typeof(IConfiguration));
    if (descriptor?.ImplementationInstance is IConfigurationRoot configuration)
    {
        configurationBuilder.AddConfiguration(configuration);
    }
```
with
```
    var serviceProvider = builder.Services.BuildServiceProvider();
    var configurationRoot = serviceProvider.GetService<IConfiguration>();
    configurationBuilder.AddConfiguration(configurationRoot);
```

**Comment by TarasGolodnyuk** [comment]
I also have this issue, 

host.json
`"serviceBus": {
    "autoRenewTimeout": "00:08:00",
    "prefetchCount": 0,
    "maxConcurrentCalls": 8
  }`

In logs:
`ServiceBusOptions
{ 
  "MessageHandlerOptions": {
    "AutoComplete": true,
    "MaxAutoRenewDuration": "00:05:00",
    "MaxConcurrentCalls": 16
  }
}`

I don't use startup.cs like @ivan-sam

**Comment by channeladam** [comment]
Having a similar issue, using startup.
Possibly related to https://github.com/Azure/azure-functions-host/issues/4363 (which is also affecting me)?

**Comment by brettsam** [comment]
Sorry for the delay on this. Yes, @ivan-sam, you were effectively overwriting our hostjson configuration which caused the issue.

@TarasGolodnyuk -- can you share your whole host.json? are you sticking that under `extensions`?
