### ISSUE TITLE
Build warning: ExtensionsMetadataGenerator  Could not evaluate 'hostfxr.dll' & 'hostpolicy.dll'

### ISSUE THREAD

**Issue by vkurmi** [Azure/azure-functions-host#5982]
I have .net core Azure function v2 app. I need to create a build for x86 platform but when I run dotnet build -r win-x86 I get build warnings. I don't get these warnings when I run platform independent build (dotnet build). I tried downgrading Azure function sdk to 1.0.31 but no luck.

I'm not sure what these warnings are and if they can be safely ignored.

I have seen issues https://github.com/Azure/azure-functions-host/issues/5119 & https://github.com/Azure/azure-functions-host/issues/5545, which look related.

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a .net core 2.1 Azure function app using Azure function sdk 1.0.35 (sample project attached)
[MyFunctionApp.zip](https://github.com/Azure/azure-functions-host/files/4581262/MyFunctionApp.zip)
2. run dotnet build --runtime win-x86 or dotnet build  --runtime win-x64 command

#### Expected behavior

Build should complete without any warning.

#### Actual behavior

I get build warnings:

`C:\Users\vk\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.1.2\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(33,5): warning :     Could not evaluate 'hostfxr.dll' for extension metadata. Exception message: Bad IL format. [C:\Users\vk\source\repos\MyFunctionApp\MyFunctionApp\MyFunctionApp.csproj]`

`C:\Users\vk\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.1.2\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(33,5): warning :     Could not evaluate 'hostpolicy.dll' for extension metadata. Exception message: Bad IL format.
[C:\Users\vk\source\repos\MyFunctionApp\MyFunctionApp\MyFunctionApp.csproj]`

`C:\Users\vk\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.1.2\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(33,5): warning :     Could not evaluate 'MyFunctionApp.dll' for extension metadata. Exception message: Could not load file or assembly 'MyFunctionApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.`

#### Known workarounds

Run dotnet build command without --runtime parameter.

#### Related information 
- C#
- Visual studion 2017 v15.9.15
- .net 2.1
- Azure function sdk 1.0.35

**Comment by gzuber** [comment]
@vkurmi Sorry for the delay! Building with runtime identifiers is not currently supported.
