### ISSUE TITLE
Could not load file or assmebly Microsoft.IdentityModel.Clients.ActiveDirectory, Version=4.3.0.0

### ISSUE THREAD

**Issue by venkatavijay** [Azure/azure-functions-host#5997]
!-- 
Please provide a succinct description of the issue. Please make an effort to fill in the all the sections below or we may close your issue for being low quality. 
-->

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version: Runtime version ( 1.0.13021.0)
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:West US2

#### Repro steps

Provide the steps required to reproduce the problem:

1. The function app when deployed to portal does not give me this error. 
2. When i run this specifically in my local machine it happens and it does not happen for my other team mates as well.
3. Interestingly there is no reference to 4.3.0.0  version of this dll and still it searches for this version.
4. We have used MSI and during a call to made by keyclient this happens
     var secret = Task.Run(async () => await _keyClient.GetSecretAsync(secretUri)).Result;

this is where the errors comes up

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by ankitkumarr** [comment]
@venkatavijay, I apologize for the long delay here. Is this still happening for you? If so, would you be able to share a repro functions project that I can run and try to repro in my machine? Thanks!
