### ISSUE TITLE
SendGrid output binding

### ISSUE THREAD

**Issue by jordanfinners** [Azure/azure-functions-host#6005]
I've got a HTTP endpoint which will then potentially send an email, summary code below. It completes successfully and the http response works. However no email is every sent from SendGrid, and no information appears in their email activity log.
I've also run the example for SendGrid in the docs in a test function and this also doesn't send an email. https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-sendgrid?tabs=javascript

I've tested the output `message` against the sendgrid api and its valid, and does send an email correctly when using their npm package standalone.

The extension seems to be registered correctly in the UI as well with no errors reported.

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version: ~3
- Function App name: fittrfunctions 
- Function name(s) (as appropriate): HttpWelcomeEmail
- Invocation ID: b99cf635-d401-450d-8ef1-f9a6c217c9a8 
- Region: UK West 

#### Repro steps

Provide the steps required to reproduce the problem:

1. Make a HTTP request to the endpoint
2. Responds correctly with correct status code
3. Wait for email sent from SendGrid but nothing appears

#### Expected behavior

Provide a description of the expected behavior.
Email should be sent from SendGrid.

#### Actual behavior

Provide a description of the actual behavior observed.
Function runs successfully however email is never sent, nothing appears in the email activity log in SendGrid.

#### Related information 

Provide any related information 

* Programming language used: Node JS

<details>
<summary>Bindings</summary>

```json
{
  "disabled": false,
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "post"
      ],
      "route": "welcome"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    },
    {
      "name": "message",
      "type": "sendGrid",
      "direction": "out",
      "apiKey": "EMAIL_KEY"
    }
  ]
}
```
</details>
<details>
<summary>Function Code</summary>

```javascript
const response = require('../Request/response');

const database = new Database();

module.exports = async function run(context, req) {
  if (req.headers['x-ms-client-principal-id'] && req.body && req.body.email) {
    const userId = req.headers['x-ms-client-principal-id'];
    try {
      context.log.info(`Created document for welcome email for '${userId}'.`);
      context.res = response(201);
      context.message = {
        personalizations: [
          {
            to: [
              {
                email: req.body.email,
              },
            ],
          },
        ],
        from: {
          email: 'hi@fittr.pro',
          name: 'Hi from Fittr Pro',
        },
        reply_to: {
          email: 'help@fittr.pro',
          name: 'Fittr Pro Help',
        },
        content: [],
        template_id: 'd-6a35d17bf5784eb594c6f99f32cfbe5a',
      };
      context.log.info(`Welcome Email sent for '${userId}'.`);
    } catch (err) {
      context.log.error(`Error checking if we've sent a welcome email for ${userId}.`, err);
      context.res = response(500);
    }
  } else {
    context.res = response(401);
  }
};

```
</details>

**Comment by jordanfinners** [comment]
Hi, just wondering if anyone has had chance to look into this yet? @fabiocav 
Thank you in advance!

**Comment by jordanfinners** [comment]
Hey @fabiocav just wondered if you have had a chance to check this out? :) Thank you in advance!

**Comment by fabiocav** [comment]
Apologies for the delay on this. Somehow, I've managed to miss the notifications.

Do you have a recent invocation ID we can look at? Also, can you share the HTTP request (with mock information) you're using to test/trigger this?
