### ISSUE TITLE
Custom Handlers - Add support to specify  startup command - cmd

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-host#6020]
This may be a problem specific to Linux. I included the worker binary that was deployed to `/home/site/wwwroot`. However, if I use this startup command:

```
"defaultExecutablePath": "./deno",
```

The worker doesn't start up and there's an error in Kusto that the problem was "No such file or directory".

Then I changed it to the following and it worked!

```
"defaultExecutablePath": "/home/site/wwwroot/deno",
```

This doesn't seem to be a problem on Windows.

**Comment by pragnagopa** [comment]
Relative path for `defaultWorkerPath` should work. Similar question asked here: https://github.com/Azure/azure-functions-host/issues/5812

`defaultExecutablePath` - should either be full path or a runtime that is part of the system path.

Can you please share httpWorker section from host.json? I am curious to understand how this is working on windows. We should see same behavior on windows and linux.

**Comment by anthonychu** [comment]
Yep #5812 is exactly what I’m doing.

Is it possible to simplify how we specify the startup command? It is currently split out into default execution path, args, worker path, worker args. This is going to be difficult to understand and document. Can we instead have a single array for the entire command or have the command in a single string. (I’m thinking of how docker does this work for their [CMD command](https://docs.docker.com/engine/reference/builder/#cmd)).

**Comment by pragnagopa** [comment]
cc @yojagad 

Yes, in addition to what we have today, we can add support for `CMD`  format:  `["executable","param1","param2"]` - easier to understand and document.

- If 'CMD' is specified this will take precedence over existing config
- `executable`  Can be 
         - relative path, using function app root directory as parent folder or 
         -  Full path to the exe or
         -  Runtime that is part of system path without file extension such as `node`, `dotnet`.
**Note: This format cannot support specifying a runtime that is part of the system path with a file extension such as 'node.exe', 'java.exe` as we cannot differentiate if user intention is relative file path or not**
- Environment variables can be used in the array using format `%EnvVarName%`

'

**Comment by anthonychu** [comment]
This is great. Thanks!

I have a couple of suggestions, let me know what you think.

* Make this change *only* in the new `custom` or `customHandler` section of host.json #6080
* Change `CMD` to `command`
* If at all possible, can we come up with a way that this new method can also support this restriction? It would make it much cleaner to use and document.

    > Note: This format cannot support specifying a runtime that is part of the system path with a file extension such as 'node.exe', 'java.exe` as we cannot differentiate if user intention is relative file path or not

    For instance, could we search in the current directory first, then in the path.
* Remove the `description` section

This is what this could look like:

```json
{
    "version": "2.0",
    "customHandler": {
        "type": "http",
        "command": [ "deno", "run", "-A", "worker.bundle.js" ]
    }
}
```

**Comment by pragnagopa** [comment]
> Make this change only in the new custom or customHandler section of host.json

Agreed. Closing this issue as dup. Copied notes over to #6080
