### ISSUE TITLE
API management X-AppService-Proto header causes request body to be empty

### ISSUE THREAD

**Issue by richardweaver** [Azure/azure-functions-host#6021]
#### Investigative information

Please provide the following:

- Timestamp: 2020-05-11T13:10:46.311
- Function App version: 2.0
- Function App name: 
- Function name(s) (as appropriate): 
- Invocation ID: 691624e0-d775-41ad-92d1-579ae6397ceb
- Region: North Europe

#### Repro steps

My function consumes a POST request with Content-Type as x-www-form-urlencoded:
`    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": ["post"]
    },`

In my code I read the posted data using req.rawBody. Posting directly to the function works fine. However, I have this endpoint behind an API Management facade, and when called through that I get an error because req.rawBody is undefined.

Following investigation, when forwarding the request, API Management adds a load of extra HTTP headers. I tried after adding them one at a time to a request in Postman and the one that triggers the issue is X-AppService-Proto: https.

#### Expected behavior

req.rawBody should be populated whether the request is direct or via API Management.

#### Actual behavior

req.rawBody is undefined where the request is forwarded via API Management.

#### Known workarounds

Make requests directly.

#### Related information 

I'm using Javascript, and this function only uses HTTP bindings (trigger and out).

**Comment by richardweaver** [comment]
Possibly related? https://github.com/Azure/azure-functions-host/issues/6013

**Comment by richardweaver** [comment]
Just to update, this happens regardless of the Content-Type, it's also an issue with "application/json" where the body is empty.

**Comment by yojagad** [comment]
Apologies for the late response. We're trying to investigate this, can you log the context object (JSON.stringify(context)) and provide us with what it looks like when called directly vs when called through APIM , please ?
