### ISSUE TITLE
Custom Handlers - Update host.json schema to add customHandler section

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-host#6025]
https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/host.json

**Comment by anthonychu** [comment]
Setting to P1 so it pops up in sprint planning. /cc @pragnagopa

**Comment by pragnagopa** [comment]
@anthonychu /@yojagad / @soninaren - please review https://github.com/SchemaStore/schemastore/pull/1229

**Comment by pragnagopa** [comment]
Closing as addressed.
