### ISSUE TITLE
WEBSITE_RESOURCE_GROUP environment variable

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-functions-host#6032]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C# / Windows

#### Question
We have an Azure Function that receives HTTP triggers. As part of its processing it detects the resource group that it is running through by reading the ```WEBSITE_RESOURCE_GROUP``` environment variable on the host.

We had a spike of errors overnight where that variable appeared not the be populated, or not populated correctly (our telemetry doesn't indicate which). We are wondering whether there is a reason why this might be the case?

Is this more likely a issue with App Service?

(the service had been running smoothly until this occurred, and the behavior disappeared).

**Comment by mitchdenny** [comment]
@brettsam we had another incident of this occur last night. We've inserted additional telemetry so we'll know for sure if the environment variable is missing of malformed (our guess is missing). Have you seen anything like this reported before?

**Comment by balag0** [comment]
Are both the apps where you are seeing these windows function apps? 

Next time you hit this issue can you check if the setting also missing at
https://[FunctionAppName].scm.azurewebsites.net/Env.cshtml

**Comment by mitchdenny** [comment]
Actually its not two apps, its one app, on two separate days. Different nodes. The last incident lasted about 10 minutes before presumably the instance was cleaned up.

If I go into the Kudu will it show me environment variables across all instances, or just one of them? Our telemetry shows that it was just one instance failing:

problemId | cloud_RoleInstance | count_
-- | -- | --
System.UriFormatException at Azure.Sdk.Tools.WebhookRouter.Routing.Router.GetConfigurationUri | 8578d0d779b7e5d54624b20f30277a8baa457f19f90089b1fd5ff5943e42909e | 126

**Comment by mitchdenny** [comment]
Closing this as it hasn't reoccured since it deployed additional telemetry. If it reoccurs I'll reopen.
