### ISSUE TITLE
Always InternalServerError after recreating a function app with the same function app name

### ISSUE THREAD

**Issue by bfederau** [Azure/azure-functions-host#6033]
I have created a function app using a Docker image. It was working weeks without any problems. 2 days ago I deleted the function app and recreate it. Now I have the problem if I use the same name as before the function app always shows

```
Error:
Encountered an error (InternalServerError) from host runtime.
Session Id: b853ccc28c414fa4bcc732d5fed87692
Timestamp: 2020-05-14T10:20:42.626Z
```

If I use the same Docker image but use a different name for the function app everything is working fine again.
If I use the broken function app and add a staging slot the slot is working fine. Its the same code. As soon as I do the swap the production slot shows still the InternalServerError and the staging slot that uses now the Docker image from the previously not working production slot works in the staging slot.

For me it looks like my **function app name is broken** and I can't use it anymore.

Any ideas what is going wrong here? How can I debug such an issue?

**Comment by mhoeger** [comment]
Hey @bfederau - sorry for the delay. 
Can you share your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? Also, if you have any updates on this issue that would be great! Thanks
