### ISSUE TITLE
Target full framework and use Azure func runtime version 3

### ISSUE THREAD

**Issue by hongdai** [Azure/azure-functions-host#6035]
#### Is your question related to a specific version? If so, please specify: 
V3
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question
Can I target full framework, instead of .Net Core?

**Comment by v-anvari** [comment]
Hi @hongdai, [.NET Core 3.1](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions#languages) is supported on Version 3.x, changing that to .Net framework will not be fully compatible with the project. 

Please feel free to reopen the issue in case of any queries.
