### ISSUE TITLE
Function host restarting

### ISSUE THREAD

**Issue by harisubramaniam1** [Azure/azure-functions-host#6037]
#### Is your question related to a specific version? If so, please specify:
Az Func V2
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question
I have an Azure Function V2 with .net core 2.1 deployed on to a dedicated windows app service plan . The function app consists of 2 functions both http triggered. The function app has its Always On enabled as it is on a dedicated service plan. Occasionally, I can see trace level logs in application insights that says the function host has restarted. I believe this is logged by ScriptHost.cs from webjobs SDK. 

What I am trying to understand is, what is causing the host to restart? Certain events, that can cause it to restart are 1. New deployments 2. Slot swaps 3. App setting changes 4. Manual restart of the web app.

But none of those occured and inspite I see restarts with logs like 

Starting Host (HostId=name, InstanceId=63b8e56c-d9b1-4dc4-8cdd-067698cbfd53, Version=2.0.13351.0, ProcessId=8028, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=~2)

**Comment by yojagad** [comment]
@harisubramaniam1 Can you please follow the template and provide us more details about the app so that we can take a deeper look at this?
