### ISSUE TITLE
Documentation: Function App Zipped Deployment page

### ISSUE THREAD

**Issue by IanKemp** [Azure/azure-functions-host#6039]
https://github.com/Azure/azure-functions-host/wiki/Function-App-Zipped-Deployment

> Plans have changed and this document is outdated, so removing it (old text still available in history).

Does this mean that the docs at e.g. https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push are no longer correct?

If not, what does it mean/imply?

**Comment by balag0** [comment]
It just means the github wiki page is outdated and replaced by the docs wiki page. 
https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push is still valid.

Are you finding something is not working as expected?
