### ISSUE TITLE
Azure Function is not working with HttpResponseMessage and HttpRequestMessage.CreateResponse

### ISSUE THREAD

**Issue by anuxps** [Azure/azure-functions-host#6040]
# Azure Function is not working with HttpResponseMessage

I have created an Azure functions and import the nugget package for Durable Functions. The moment I have imported the package, my Azure function start throwing the following error:

 Error	CS0121	The call is ambiguous between the following methods or properties: 'System.Net.Http.HttpRequestMessageExtensions.CreateResponse<T>(System.Net.Http.HttpRequestMessage, System.Net.HttpStatusCode, T)' and 'System.Net.Http.HttpRequestMessageExtensions.CreateResponse<T>(System.Net.Http.HttpRequestMessage, System.Net.HttpStatusCode, T)'

I want to return the HttpResponseMessage output after Function executed. I am not able to do it. Kindly please guide me how to solve this error.

Here is a default sample code which is also throwing the error:

        public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequestMessage req, TraceWriter log)
        {
            log.Info("C# HTTP trigger function processed a request.");

            // parse query parameter
            string name = req.GetQueryNameValuePairs()
                .FirstOrDefault(q => string.Compare(q.Key, "name", true) == 0)
                .Value;

            if (name == null)
            {
                // Get request body
                dynamic data = await req.Content.ReadAsAsync<object>();
                name = data?.name;
            }

            return name == null
                ? **req.CreateResponse**(HttpStatusCode.BadRequest, "Please pass a name on the query string or in the request body")
                : **req.CreateResponse**(HttpStatusCode.OK, "Hello " + name);
        }
## Few Errors from my code:

**Error	CS0121	The call is ambiguous between the following methods or properties: 'System.Net.Http.HttpRequestMessageExtensions.CreateResponse<T>(System.Net.Http.HttpRequestMessage, System.Net.HttpStatusCode, T)' and 'System.Net.Http.HttpRequestMessageExtensions.CreateResponse<T>(System.Net.Http.HttpRequestMessage, System.Net.HttpStatusCode, T)'**

![image](https://user-images.githubusercontent.com/21247262/82065579-2262bd80-9683-11ea-9d75-8f7a5d4dd577.png)

**The type 'HttpRequestMessageExtensions' exists in both 'Microsoft.AspNetCore.Mvc.WebApiCompatShim, Version=1.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'System.Net.Http.Formatting, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'**

![image](https://user-images.githubusercontent.com/21247262/82065695-4b834e00-9683-11ea-8f1d-6a2eb0a1e9a0.png)

**Comment by kashimiz** [comment]
Hi @anuxps, my apologies for the very late reply. Can you provide more information about the environment you're experiencing this issue in, namely:

- Function runtime version
- Durable Functions NuGet package version

Seeing your .csproj file would also be helpful.

**Comment by pradeepsethi** [comment]
Microsoft.NET.Sdk.Functions v1.0.24
Microsoft.Azure.WebJobs.Extensions.DurableTask v2.2.2

<img width="711" alt="DurableTask" src="https://user-images.githubusercontent.com/502600/87845964-2c43af80-c8c4-11ea-8c25-1f76a290e72f.png">
