### ISSUE TITLE
Functions using CustomHandlers show configuration exception

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#6053]
cc @ankitkumarr  - this is a recent regressions

cc @yojagad 

```
The 'HttpTrigger' function is in error: Unable to determine the primary function script.Make sure atleast one script file is present.Try renaming your entry point script to 'run' or alternatively you can specify the name of the entry point script explicitly by adding a 'scriptFile' property to your function metadata.
```

Repro:
Run project: `WebJobs.Script.WebHost` pointing `AzureWebJobsScriptRoot` to `https://github.com/Azure/azure-functions-host/tree/dev/sample/HttpWorker`

Expected:
No configuration errors.

**Comment by pragnagopa** [comment]
Root cause:
Functions are being indexed before HttpWorkerOptions are populated

**Comment by pragnagopa** [comment]
cc @anthonychu as FYI.
@ankitkumarr  investigated the issue.  

Functionally app is still OK. Initially when functions are indexed, we will see errors. This will cause noise in the logs. Not a release blocker.

**Comment by ankitkumarr** [comment]
Closed by https://github.com/Azure/azure-functions-host/commit/784061febe021d752882fb6e68ac3f91dec65050
