### ISSUE TITLE
context.bindingData returns incorrect value

### ISSUE THREAD

**Issue by whakomatic** [Azure/azure-functions-host#6055]
for a Javascript Azure Function using a route
context.bindingData gives incorrect value when it is a passed a 0
(this is not solved by a type constraint on the route, see below)

+ working route binding
    /myfunction/1/2

context.bindingData.param1
=> 1

context.bindingData.param2
=> 2

+ bad route binding
    /myfunction/0/2

context.bindingData.param1
=> { string: '0', data: 'string' }

context.bindingData.param2
=> 2

This of course breaks downstream code.

+ Live Demo

works:
https://routetest.azurewebsites.net/api/routedemo/1/2

incorrect binding:
https://routetest.azurewebsites.net/api/routedemo/0/2

the problem bindings can be with or without route constraints

"route": "routedemo/{param1}/{param2}"
"route": "routedemo/{param1:int}/{param2:int}"

**Comment by nogic1008** [comment]
Same issue occurs in my functions, and I have to take the workaround as below.
```javascript
  const index = typeof context.bindingData.index === 'number' ? context.bindingData.index : 0
```

function.json
```json
      "route": "v1/songs/name/{index:int}"
```

**Comment by v-anvari** [comment]
Hi @whakomatic , We apologize for the delayed response, were you able to find a solution to this problem. Do let us know if you want us to look at this issue further

**Comment by nogic1008** [comment]
Any updates?

**Comment by v-anvari** [comment]
Hi @nogic1008 , Can you explain me this issue in detail and what is the solution you ae looking for. So that, I can follow up with the concerned team accordingly.

**Comment by whakomatic** [comment]
> Hi @nogic1008 , Can you explain me this issue in detail and what is the solution you ae looking for. So that, I can follow up with the concerned team accordingly.

The original post provides all the information you request.

**Comment by v-anvari** [comment]
Hi @whakomatic , Thank you for your feedback! We will review and update as appropriate.

**Comment by v-anvari** [comment]
Sorry for the delay, checking this internally, if this is by-design or requires a fix

**Comment by v-anvari** [comment]
Hi @whakomatic / @nogic1008 , This issue is marked as a potential breaking change for v4, and the tracking issue is here - https://github.com/Azure/azure-functions-nodejs-worker/issues/377

**Comment by v-anvari** [comment]
Closing this issue as a duplicate, any further updates will be given in the tracking issue, please feel free to reach back to us in case of any further queries related to this issue
