### ISSUE TITLE
Azure functions and .Net.Mail

### ISSUE THREAD

**Issue by PatruPePatru** [Azure/azure-functions-host#6059]
#### Is your question related to a specific version? If so, please specify: 
Azure Functions Runtime version : 3.0.13353.0

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
I've open this as a question as I don't know whether I'm doing something or this is a bug:

I a queue trigger that fires a function that sends a email notification.
![image](https://user-images.githubusercontent.com/59825551/82302678-958d6c00-99c2-11ea-8967-72d71bd5740a.png)

The email is sent using System.Net.Mail:
![image](https://user-images.githubusercontent.com/59825551/82302809-c2da1a00-99c2-11ea-893c-9d6aa5a6079b.png)

When I run my code locally it works however when the code runs in Azure it doesn't work.

I've checked Azure logs and noticed that the function is triggered and success is true:
![image](https://user-images.githubusercontent.com/59825551/82303216-527fc880-99c3-11ea-92e2-1fb72c1c3bc2.png)
however the email never reaches the inbox.

Do you know if Azure blocks smtp or the smtp port?

Has anyone else encountered this issues?

Thanks in avance.

**Comment by espray** [comment]
Consumption or Premium plan pricing?

**Comment by PatruPePatru** [comment]
> Consumption

Consumption plan

**Comment by PatruPePatru** [comment]
> Consumption or Premium plan pricing?

Consumption plan.

**Comment by balag0** [comment]
In case you haven't seen this thread before
https://stackoverflow.com/questions/57327119/send-email-from-azure-function-app-without-using-sendgrid-and-office-365

**Comment by PatruPePatru** [comment]
I had my guess that this might be the issue, I just wanted to double check. Thanks you and have a nice day ahead. Cheers!
