### ISSUE TITLE
How to properly set up Azure Functions monitoring and live metrics that has dependency injected instrumentation keys

### ISSUE THREAD

**Issue by qfyra** [Azure/azure-functions-host#6060]
v3, C#

Sometime last week, the monitoring in the old Azure Functions portal interface, as well as the Live Metrics of all our Azure Functions, stopped working across the board. Since neither the Azure Portal nor the Microsoft blog mentions any changes under the hood in Azure Functions or App Insights, I must conclude that we're using some undocumented feature that was not ment to be used in the first place.

The actual Azure Functions in question seems to be working fine from an operational standpoint, i.e. they do what they're supposed to do, but we're unable to watch it live (we rely on live metrics primarily for developing new features, and on metric tracing when transient errors occur). The new "Azure Functions management experience" do show some app insights metrics, but not in real time. The old portal interface for Functions (the one where you can, per method in the Function, click on Integrate, Manage, and Monitor) gives no results for the last 30 days. Clicking on Live Metrics renders the default "Not available: your app is offline or using an older SDK" with some animated demo charts. Clicking on the Get started with Live Metrics button links to https://docs.microsoft.com/en-us/azure/azure-monitor/app/live-stream#get-started which lists 5 steps. I've performed/verified steps 1-4 to the best of my ability (step 1 is extremely unclear though), without effect. 

My guess for the most likely culprit is the dependency injected instrumentation key. We're using a workaround similar to what is mentioned in https://github.com/Azure/azure-functions-host/issues/5353#issuecomment-590147499, because we haven't found any other way of doing it, i.e.:

```
builder.Services.AddSingleton(sp =>
{
	var key = Environment.GetEnvironmentVariable("APPINSIGHTS_INSTRUMENTATIONKEY");
	return string.IsNullOrWhiteSpace(key) ? new TelemetryConfiguration() : new TelemetryConfiguration(key);
});
```

I've verified that the instrumentation key is correct of course.

My question is, what is the actual proper way of setting up dependency injected Azure Functions so that Live Metrics and monitoring works the way it worked a mere 10 days ago?

**Comment by qfyra** [comment]
FYI: Log streaming and invocation traces have also stopped working across the board.

**Comment by peter-bozovic** [comment]
Just wanted to bump in saying I have the same issue.
Old portal I was able to see live log when executing my functions.
New portal just says "Connected!" and nothing more.
Hard to identify issues quickly and see what is happening in real time ...

My Startup Configure is slightly more complicated because of the use of DependencyFilter
```
var configDescriptor = builder.Services.SingleOrDefault(tc => tc.ServiceType == typeof(TelemetryConfiguration));
if (configDescriptor?.ImplementationFactory == null)
	return;
var implFactory = configDescriptor.ImplementationFactory;
builder.Services.Remove(configDescriptor);
builder.Services.AddSingleton(provider => {
	if (!(implFactory.Invoke(provider) is TelemetryConfiguration config))
		return null;
	config.TelemetryProcessorChainBuilder.Use(next => new DependencyFilter(next));
	config.TelemetryProcessorChainBuilder.Build();
	return config;
});

```

I know that Applications Insights is collecting data because I can see Requests and traces in the AI part of the portal.

**Comment by qfyra** [comment]
> New portal just says "Connected!" and nothing more.

Yeah, I've got the exakt same issue. In fact, I've posted more details on StackOverflow about my issues, feel free to chime in there as well. https://stackoverflow.com/q/62300877/971284

**Comment by LXBdev** [comment]
My theory (also posted as an answer to Stackoverflow above) is that the workaround mentioned above is actually breaking the logging with the current function host version, probably related to #5353 which prompted the workaround.

I set up a new function, and everything works great until I add the workaround code mentioned above.

=> `services.AddSingleton(new TelemetryConfiguration(myKey)` breaks all AppInsights logging.

**Comment by qfyra** [comment]
Yep, that was the issue indeed. Everything seems to work as intended after removing the workaround code.

**Comment by peter-bozovic** [comment]
Any idea how to make new Functions portal work with ITelemetryProcessor ?

Since this doesn't seem to work anymore:
https://devblogs.microsoft.com/premier-developer/implement-app-insights-telemetry-processor-in-azure-functions/
