### ISSUE TITLE
Could not load file or assembly...' error... possibly due to Dependent Package binaries not copied to 'bin' 

### ISSUE THREAD

**Issue by alkreddy** [Azure/azure-functions-host#6070]
My Function App has references to the following packages. The local execution runtime doesn't find them resulting in Could not load file or assembly errors
- System.IdentityModel.Tokens.Jwt 6.5.1
- Microsoft.IdentityModel.Tokens 6.5.1

#### Investigative information
Local Execution
Azure Functions Core Tools (3.0.2534 Commit hash: bc1e9efa8fa78dd1a138dd1ac1ebef97aac8d78e)
Function Runtime Version: 3.0.13353.0

#### Repro steps

1. Run the Function App Locally, the Host Starts Up fine.
2. Invoke the function and notice the errors in output and console log.

Error
Executed 'KSNavigation' (Failed, Id=0cc2793a-c137-4b48-a584-b5e31404f0d2)
[21-05-2020 04:16:46] System.Private.CoreLib: Exception while executing function: KSNavigation. AVEVA.DataLake.Function: Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=6.5.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

#### Expected behavior

Functions executes without Assembly Load Errors
#### Actual behavior

Function fails with the following error
Executed 'KSNavigation' (Failed, Id=0cc2793a-c137-4b48-a584-b5e31404f0d2)
[21-05-2020 04:16:46] System.Private.CoreLib: Exception while executing function: KSNavigation. AVEVA.DataLake.Function: Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=6.5.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

#### Known workarounds

Was able to overcome this error by manually copying the dll to the bin folder but then I see it's dependent assembly failure error.

#### Related information 

Provide any related information 

* Programming language used : C#
* Links to source
* Bindings used : HttpTrigger

**Comment by johlrich** [comment]
Just hit the same issue. I first tried limiting version to <6, but 5.6.0 also caused the same exception.

Then I looked in the local tooling's bin folder and saw the 5.5.0.x in there. Locking my project to 5.5.0 version nuget package allowed the function to start.

Edit: it was the System.IdentityModel.Tokens.Jwt version in my case that resolved the issue

**Comment by alkreddy** [comment]
Thanks @johlrich , That version roll backed helped me as well. 
Should this incompatibility be attributed to Azure Runtime Host or the library author?

**Comment by soninaren** [comment]
Closing as resolved.
