### ISSUE TITLE
Updates to profile.ps1 to improve cold start

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-host#6071]
Updates to profile.ps1 to improve in cold start:

* Invoking Disable-AzContextAutosave before Connect-AzAccount saves 2-4 seconds
* Remove unnecessary Get-Module call saves around ~2 seconds

profile template will look like this:

``` poweshell
if ($env:MSI_SECRET) {
    Disable-AzContextAutosave
    Connect-AzAccount -Identity
}
````

**Comment by fabiocav** [comment]
Is this still open? It's currently assigned to sprint 77. Should it be moved to 78?

**Comment by Francisco-Gamino** [comment]
Yes, it is still open. Moving it to 78,

**Comment by fabiocav** [comment]
Moving this back to `triaged`. Let me know if you're still working on this.

**Comment by Francisco-Gamino** [comment]
Please keep it in `triaged`. As soon as I complete the work, I will move it back to the current sprint (I will try to get this done by `Sprint 79`).
