### ISSUE TITLE
Timer function execute not in expected time

### ISSUE THREAD

**Issue by a9261** [Azure/azure-functions-host#6082]
Env :
Azure function V3
C#

Problem :
I have multiple timer function at one project.  
first i saw only minutes level function can find in azure storage  azure-webjobs-hosts/timer/{myfunctionName}/
![AzureFunctionIssue01](https://user-images.githubusercontent.com/3389662/82657906-b4a52b80-9c58-11ea-8881-4f0226878859.jpg)
![AzureFunctionIssue02](https://user-images.githubusercontent.com/3389662/82657910-b66eef00-9c58-11ea-947f-e48e81e15941.jpg)

second i has a function execute every 10 seconds , But i saw monitor it's not execute by every 10 seconds (execute duration not exceed 10 second)

![AzureFunctionIssue](https://user-images.githubusercontent.com/3389662/82657808-93443f80-9c58-11ea-8c4a-35d9057677d7.jpg)

**Comment by ThejaChoudary** [comment]
Able to repro the issue.
@gzuber can you please look into this further.

**Comment by v-anvari** [comment]
Hi @a9261, Few changes have been made to the timer triggers recently. We have gone through the latest logs 
**Dated** - 27-10-2020 for the **Function** - _SyncAccountBalanceBotToCore_ which is set for 10 secs. The functions seems to be working fine in the recent logs. Could you please confirm if you are still facing any difficulties.

**Logs :** 

 2020-10-27T11:09:50.0103353+00:00
 2020-10-27T11:09:40.0211319+00:00
 2020-10-27T11:09:30.0076039+00:00
 2020-10-27T11:09:20.0398011+00:00
 2020-10-27T11:09:10.0103906+00:00
 2020-10-27T11:08:59.9981966+00:00
 2020-10-27T11:08:50.1452421+00:00
 2020-10-27T11:08:39.9948750+00:00
 2020-10-27T11:08:30.0103671+00:00
 2020-10-27T11:08:20.0045238+00:00
 2020-10-27T11:09:15.0009235+00:00
