### ISSUE TITLE
"Unable to resolve service for type ..." in the Cloud

### ISSUE THREAD

**Issue by thehaseebahmed** [Azure/azure-functions-host#6084]
#### Investigative information

- Timestamp: 2020-05-23T02:36:00+05:00
- Function App version: v3
- Function App name: sms-sync-for-wallet
- Function name(s) (as appropriate): All
- Region: North Europe

#### Repro steps

1. Created a new Azure Functions v3 project in VS2019
2. Wrote my logic and tested locally, everything works fine.
3. Ran locally, tested it, works as expected.
4. Deployed to Azure Portal.
5. Keep getting the _"Unable to resolve service for type '...' while attempting to activate 'SMSSync.Functions.AFv3.Main'"_ error.

#### Expected behavior

- I should be able to trigger my HTTP functions.
- My TimeTriggered functions should run automatically.

#### Actual behavior

- I keep seeing the _"Unable to resolve service for type '...' while attempting to activate 'SMSSync.Functions.AFv3.Main'"_ error.

#### Related information 

I have tried all the other solutions mentioned around here.

- I upgraded my "Microsoft.NET.Sdk.Functions" from 3.0.3 to 3.0.7
- I added extensionBundle section to my hosts.json file and it looks like the following:
```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  },
  "logging": {
    "applicationInsights": {
      "samplingExcludedTypes": "Request",
      "samplingSettings": {
        "isEnabled": true
      }
    }
  }
}
```
- I created a new Azure Functions v2 project, moved all my code there, deployed that and still the same issue.

**Comment by nightBaker** [comment]
Any updates regarding this issue ? I ran into the same problem...

**Comment by yojagad** [comment]
@haseebahmed7 Can you share a minumum repro of this so that we can dig into it further?

**Comment by thehaseebahmed** [comment]
> @haseebahmed7 Can you share a minumum repro of this so that we can dig into it further?

It is a private repo, sent you an invite. You can find the code in haseeb\init_work branch.
The DI code is commented out for now, let me know if you need me to uncomment it.

Update: Actually, I've merged my branch into main, so please see that branch.

**Comment by yojagad** [comment]
@haseebahmed7 Apologies for letting this fall through. If this is still an issue, can you share the invite again so that I can take a further look at this, please ?
