### ISSUE TITLE
EventGridTrigger does not create a complete function.json

### ISSUE THREAD

**Issue by panmanphil** [Azure/azure-functions-host#6093]
#### Investigative information

Please provide the following:

- Timestamp: n/a
- Function App version: any
- Function App name: multiple
- Function name(s) (as appropriate):
- Invocation ID: n/a
- Region: us east

#### Repro steps

create a new function in an existing function app with an eventgrid trigger. 
Deploy it to azure. 
In the portal in any of the functions within the function app open the integration menu
a warning is present:
`The following bindings are missing the required direction property and may have been placed incorrectly: eventGridEvent. Please update the bindings in your functions.json `

If you look at the generated function.json. the file is missing the required direction property. 
```
{
  "generatedBy": "Microsoft.NET.Sdk.Functions-3.0.6",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "eventGridTrigger",
      "name": "eventGridEvent"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/xxxxxxxFunctions.dll",
  "entryPoint": "xxxxxx.Functions.xxxxxxx.Run"
}
```

#### Expected behavior

in the binding section there should be 
`"direction": "in"`
#### Actual behavior

missing direction property.

The warning within the integration menu for the event grid function shows the warning given earlier. Other functions withing the app display various message including unable to load bindings

#### Known workarounds

Provide a description of any known workarounds.
i can manually edit function.json in the portal the errors go away, until the next deployment.

#### Related information 

This much of the code, basically what was generated by the func command line tool demonstrates the problem. The function *does work* though. 

```csharp
 
        [FunctionName("LocalPrintSearchSync")]
        public async Task Run([EventGridTrigger]EventGridEvent eventGridEvent, ILogger logger)
        {
            logger.LogTrace($"Local print service starting {eventGridEvent.Subject} : {eventGridEvent.EventType}");
        }
```

**Comment by brettsam** [comment]
This is a known "issue" -- the function.json generation has been this way for several years and this does not impact any function execution. The new Portal UX, however, sees this as an error. We're tracking this elsewhere (https://github.com/Azure/Azure-Functions/issues/1528), so closing this one.
