### ISSUE TITLE
Azure Functions v3 is not logging the Timeout Exception in the Requests, Traces, or Exceptions folder without changes to the log level. 

### ISSUE THREAD

**Issue by FinVamp1** [Azure/azure-functions-host#6096]
#### Investigative information

Please provide the following:

- Timestamp: 2020-05-24T03:09 
- Function App version: v3 (3.0.13353)
- Function App name: EventHubTimeoutBoqian
- Function name(s) (as appropriate): EventHubTriggerCSharp1
- Invocation ID: Executed 'EventHubTriggerCSharp1' (Failed, Id=ca9a9ccb-fd49-47d0-a711-c8d1fd2da267) (This shows up in Kusto but not in the customer AI logs).
- Region: South East Asia

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a new v3 Function App.
2. Add a HTTP Trigger
3. Set the Timeout to 1 minute
4. Add code as below.
5. Add Application Insights if not already configured. 
6. Run the HTTP Request and wait for it to timeout.

#### Expected behavior

Provide a description of the expected behavior.

- After I perform Step 6 the Requests, Traces, and Exceptions table should have the Timeout insights.

#### Actual behavior

Provide a description of the actual behavior observed.

- After I perform Step 6 the Requests, Traces, and Exceptions table should have the Timeout insights.

They don't unless you set the Function Default level to Information.

#### Known workarounds

Set the default host or Function level. 

e.g

{
  "logging": {
    "fileLoggingMode": "debugOnly",
    "logLevel": {
      "default": "Information",
      "Function.Function2: "Information"
    }
  }
}

#### Related information 

Provide any related information 

* Programming language used 
C#
* Links to source
See below
* Bindings used
HTTP (Also tested with EventHub)

This also fails intermittently on v2. 

<details>
<summary>Source</summary>

```csharp
    public static class Function2
    {
        [FunctionName("Function2")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            var rand = new Random();

            int testNum = rand.Next(1, 50);

            log.LogInformation("The Random Number value is {0}", testNum.ToString());

            if (testNum < 50)
            {
                log.LogInformation("Entering Long Sleep");
                Thread.Sleep(18000000);
            }
            else
            {
                log.LogInformation("Entering Short Sleep");
                Thread.Sleep(10000);
            }

            string name = req.Query["name"];

            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name = name ?? data?.name;

            string responseMessage = string.IsNullOrEmpty(name)
                ? "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."
                : $"Hello, {name}. This HTTP triggered function executed successfully.";

            return new OkObjectResult(responseMessage);
        }
    }
```
</details>

**Comment by FinVamp1** [comment]
It looks like this can affect v2 apps as well in the same manner. The timeout is only logged when the log level is set.

**Comment by rraczdw** [comment]
This is still an issue with TimerTrigger as well. The workload of our functions has increased and it started to fail silently (neither successful or failed invocation was logged, we could only tell by looking monitoring info logs)

**Comment by yojagad** [comment]
@FinVamp1 Do you happen to know if this problem is specific to 3.0.13353 ? I just created a new function app with the latest runtime and I could see the timeouts in requests, exception and traces tables in appinsights

![image](https://user-images.githubusercontent.com/26885664/91241646-4316c680-e6fa-11ea-918a-4fa8bf35efe1.png)
![image](https://user-images.githubusercontent.com/26885664/91241689-5f1a6800-e6fa-11ea-85b5-9784d24c248d.png)
![image](https://user-images.githubusercontent.com/26885664/91241819-a143a980-e6fa-11ea-8ec9-c56e0ed2e8fd.png)

**Comment by pragnagopa** [comment]
Closing as no repro. Please reopen if needed.
