### ISSUE TITLE
Support of Keda scaling jobs

### ISSUE THREAD

**Issue by andrejpohlmann** [Azure/azure-functions-host#6103]
Currently Azure Functions on Keda only supports scaling deployments. For short running tasks this is feasible but for long running it would be great to also support scaling jobs. I think the only missing thing in the web host is to restrict the number of messages to consume per functions to one message and then stop the host.

**Comment by yojagad** [comment]
@ahmelsayed Will you be able to provide some input here, please?

**Comment by v-anvari** [comment]
Hi @andrejpohlmann , This is not a supported scenario, the host doesn't have any mode where it consumes a single  message and then stops. 

If you could elaborate on the feature request regarding the purpose of it, then we shall add it as a feature request.
