### ISSUE TITLE
Intermittent duplicates traces in Application Insights

### ISSUE THREAD

**Issue by snuffykl** [Azure/azure-functions-host#6104]
#### Is your question related to a specific version? If so, please specify: 
Azure Function v3 with Azure Durable Function Extensions
azurefunctions: 3.0.13353.0
```
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.2.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.10" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers" Version="0.2.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.5" />
```
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
 C#

#### Question
I am having intermittent issue of duplicates traces in Application Insights. Below is a screenshot of the duplicates: 
<img width="883" alt="Screenshot 2020-05-27 at 9 31 10 PM" src="https://user-images.githubusercontent.com/324180/83028370-e73d9280-a063-11ea-860e-8555a24083ac.png">

I run some load testing and observed there are duplicates traces. I checked the invocation Id for the duplicates are the same.

**Comment by v-bbalaiagar** [comment]
Hi @snuffykl, Can we know if you are seeing this issue still and requires further follow up.

**Comment by snuffykl** [comment]
Hi @v-bbalaiagar thank you for asking. We have another workaround. Let me close this issue.
