### ISSUE TITLE
Input Bindings interference

### ISSUE THREAD

**Issue by ewzluoc** [Azure/azure-functions-host#6108]
#### Investigative information

Please provide the following:

- Timestamp: 2020-05-28T09:58:02.092997798Z
- Function App version: 3.0.13113 (~3)
- Function App name: ----
- Function name(s) (as appropriate): ---
- Invocation ID: c15519ef-9e9b-4736-860d-efcac0149ae7
- Region: West Europe

#### Repro steps

I have two functions that seem to interfere with each other. More accurate, the Bindings of the two function interfere with each other. Both functions are in the same Function App. The functions do completely different things and have nothing to do with each other.

**First Binding:**

`{
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "post"
      ],
      **"route": "{todo:alpha}"**
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    },
    {
      "type": "cosmosDB",
      "name": "inputDocumentIn",
      "direction": "in",
      "databaseName": "Database",
      "collectionName": "Collection",
      **"sqlQuery": "SELECT * from c where c.attribute = {attribute}",**
      "connectionStringSetting": "connectionStringSettingKey"
    }
  ]
}`

**Second Binding:**

`{
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    },
    {
      "type": "cosmosDB",
      "name": "outputDocument",
      "direction": "out",
      "databaseName": "Database",
      "collectionName": "OtherCollection",
      "createIfNotExists": "true",
      "connectionStringSetting": "connectionStringSettingKey"
    }
  ]
}`

1. When running the first function It works fine.

2. When running the second function, I get the error: 
[KeyNotFoundException.log](https://github.com/Azure/azure-functions-host/files/4694905/KeyNotFoundException.log)

?? Why does the first function have a problem, I am not even triggering it. But it still expects the attribute value form the inputtrigger to get the sqlquery.

My work Around: I changed the Binding and filtered the sqlQuery in de index.js
 `{
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "post"
      ],
      "route": "{todo:alpha}"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    },
    {
      "type": "cosmosDB",
      "name": "inputDocumentIn",
      "direction": "in",
      "databaseName": "Database",
      "collectionName": "Collection",
      "sqlQuery": "SELECT * from c,
      "connectionStringSetting": "connectionStringSettingKey"
    }
  ]
}`

3. Running the second function I get: 
[Everythingok.log](https://github.com/Azure/azure-functions-host/files/4694925/Everythingok.log)

But the second function actually didn't run, and I get in the console.output  the self written responses of the firstfunction, saying the request body is missing or that the url is wrong because its missing the route path.

!! I'm triggering the second function, never the first function.

#### Workaround

I had to put the two functions in different Function Apps.

**Comment by v-anvari** [comment]
Hi @ewzluoc, Sorry for the delayed response, are you still facing the issue? If yes, can you please give the repro steps in detail, so as to clone the scenario. Can you provide the updated timestamp as well, for us to capture the logs.
