### ISSUE TITLE
Downtime after a successful slot swap has occured

### ISSUE THREAD

**Issue by jenspettersson** [Azure/azure-functions-host#6109]
We're often experiencing downtime a couple of seconds after a slot has been swapped successfully. We're monitoring the app and see that the swap has happened and all is running fine for a couple of seconds and then suddenly we get 503 Service Unavailable for about 20 seconds... We have minimal to none load on the service we noticed it on, we just wanted to see that the swap worked.

In order to rule out other dependencies we created a new functions app from the azure portal with only one HTTP Trigger that returns a string value of a color. We also create a slot with a HTTP Trigger that returns a different string value of a color and tested to swap between these two while making an HTTP Request every second. Sure enough, it behaves the same way _most_ of the time (not all, but roughly 80% of the time we tested).

Here's a screenshot of the "monitor" console app that tries to make a request every second:

![image](https://user-images.githubusercontent.com/125493/83136301-85bf0780-a0e7-11ea-81a5-0d84fbcacd42.png)

#### Investigative information

We don't really have any "investigative information" as the function app is destroyed, but it can easily be reproduced by creating a new app and function, all in the portal. I'll try to give as much as I can:

Please provide the following:

- Timestamp: 11:18:36 UTC (but it happens almost every time we try)
- Region: West Europe
- Pricing Tier: Consumption
- Windows host

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a new function app in the portal
2. Create a new slot for that function app
3. Create a function in the "production slot" that returns a value
4. Create a function with the same name/route in the "staging slot" that returns another value
5. Issue a HTTP Request every second to the "production" function and log the response
6. Swap the slots

#### Expected behavior

After step 6 is completed, we are expecting the response value to change to whatever the value was in the slot and keep running.

#### Actual behavior

After step 6 is completed, we do indeed see the expected changed value, but after a couple of seconds the service becomes unavailable for a couple of seconds.

#### Related information 

Provide any related information 

* Programming language used: C#
* Links to source
* Bindings used: none, just default HTTP trigger

Code from the portal editor:
```csharp
#r "Newtonsoft.Json"

using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Newtonsoft.Json;

public static async Task<IActionResult> Run(HttpRequest req, ILogger log)
{
    return (ActionResult)new OkObjectResult("YELLOW"); //"GREEN" on the other slot
}

```

If I can do anything more to help, just let me know!

**Comment by APIWT** [comment]
Are you warming up your "YELLOW" slot before the swap by making a request to it? This might be necessary as documented here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-slots

EDIT: Nevermind, I see the issue. You are saying it works for a little while then goes down after like 20s briefly. Sorry! Not sure what the issue is.

**Comment by fabiocav** [comment]
@jenspettersson did you manage to catch the invocation ID for the failure? Thanks!

**Comment by jenspettersson** [comment]
> @jenspettersson did you manage to catch the invocation ID for the failure? Thanks!

No sorry. Might be able to recreate it later if I got time. I'll get back to you.

**Comment by fabiocav** [comment]
Thank you!
