### ISSUE TITLE
InternalServerError from latest V2 runtime (2.0.13616) when calling Create Function API / ARM Template

### ISSUE THREAD

**Issue by bchapeau** [Azure/azure-functions-host#6110]
An ARM template we've previously successfully used to deploy our Function has started failing while deploying a function resource type (`Microsoft.Web/sites/functions`) with an InternalServerError from the host runtime:

```
{
    "Code": "BadRequest",
    "Message": "Encountered an error (InternalServerError) from host runtime.",
    "Target": null,
    "Details": [
        {
            "Message": "Encountered an error (InternalServerError) from host runtime."
        },
        {
            "Code": "BadRequest"
        },
        {
            "ErrorEntity": {
                "Code": "BadRequest",
                "Message": "Encountered an error (InternalServerError) from host runtime."
            }
        }
    ],
    "Innererror": null
}
```

We also get the same error if we directly invoke the [REST API for Create Function](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/createfunction).

The issue occurs whether we create a brand new function app or use an existing one.

We've been able to workaround the error (and successfully deploy the function) by pinning the FUNCTIONS_EXTENSION_VERSION to the last known good one, "2.0.13351".  (As opposed to the version we get from ~2, which currently is 2.0.13616).

- Region: North Central US

#### Repro steps

This seems to be the minimal standalone ARM Template that reproduces the issue (deploying a consumption tier app service plan, function app, single appsetting, and a function):

1. Create a new resource group
2. Deploy the following arm template into it:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
      "functionName": {
        "type": "string",
        "defaultValue": "transformfunction",
        "metadata": {
          "description": "The name of the function."
        }
      }
    },
    "variables": {
      "appServicePlanName": "testappserviceplan",
      "functionAppName": "testFunctionAppName123456"
    },
    "resources": [
    {
      "type": "Microsoft.Web/serverfarms",
      "apiVersion": "2016-09-01",
      "sku": {
        "name": "Y1",
        "tier": "Dynamic",
        "size": "Y1",
        "family": "Y",
        "capacity": 0
      },
      "kind": "functionapp",
      "name": "[variables('appServicePlanName')]",
      "location": "[resourceGroup().location]",
      "properties": {
        "name": "[variables('appServicePlanName')]",
        "computeMode":"Dynamic"
      }
    },
    {
      "type": "Microsoft.Web/sites",
      "name": "[variables('functionAppName')]",
      "apiVersion": "2019-08-01",
      "kind": "functionapp",
      "location": "[resourceGroup().location]",
      "properties": {
        "serverFarmId": "[resourceId('Microsoft.Web/serverfarms', variables('appServicePlanName'))]",
        "httpsOnly": true,
        "siteConfig": {
          "requestTracingEnabled": true,
          "httpLoggingEnabled": true,
          "detailedErrorLoggingEnabled": true
        }
      },
      "dependsOn": [
        "[resourceId('Microsoft.Web/serverfarms', variables('appServicePlanName'))]"
      ]
    },
    {
        "type": "Microsoft.Web/sites/config",
        "name": "[concat(variables('functionAppName'), '/appsettings')]",
        "apiVersion": "2019-08-01",
        "dependsOn": [
        "[resourceId('Microsoft.Web/sites', variables('functionAppName'))]"
        ],
        "properties": {
            "FUNCTIONS_EXTENSION_VERSION": "~2"
        }
    },
    {
        "apiVersion": "2019-08-01",
        "name": "[concat(variables('functionAppName'),'/', parameters('functionName'))]",
        "type": "Microsoft.Web/sites/functions",
        "dependsOn": [
            "[resourceId('Microsoft.Web/sites', variables('functionAppName'))]",
            "[resourceId('Microsoft.Web/sites/config/', variables('functionAppName'), 'appsettings')]"
        ],
        "properties": {
          "config": {
            "bindings": [
              {
                "name": "req",
                "webHookType": "genericJson",
                "direction": "in",
                "type": "httpTrigger"
              },
              {
                "name": "res",
                "direction": "out",
                "type": "http"
              }
            ]
          }
        }
      }
    ]
  }
```

#### Expected behavior
After Step 2, the function app and function should be deployed.

#### Actual behavior
After Step 2, the deployment fails with the mentioned error.

#### Known workarounds

In the ARM Template, changing the line `"FUNCTIONS_EXTENSION_VERSION": "~2"` to `"FUNCTIONS_EXTENSION_VERSION": "2.0.13351"` allows the deployment to succeed without any errors.

Omitting the setting entirely results in a V1 function app, which also succeeds (as does explicitly entering ~1), but is not what we want.  ~3 results in the same error as ~2, so this likely affects the latest V3 version also, though we did not try finding a specific version of V3 that works.

**Comment by v-anvari** [comment]
Hi @bchapeau , I tried to repro the above code and I was able to deploy successfully. 
![image](https://user-images.githubusercontent.com/66122429/97484588-e8f6e380-197e-11eb-8fae-52004d00a4b2.png)

Can you please try again with a new rg and let us know if you are facing the issue. Can you try using the latest [API versions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-resource-manager?tabs=visual-studio-code%2Cazure-cli) for the same,

if you wanna use version 3, then here is the latest version for function - [3.0.14916](https://github.com/Azure/azure-functions-host/releases)
