### ISSUE TITLE
functionTimeout in host.json is not easily configurable

### ISSUE THREAD

**Issue by vllama** [Azure/azure-functions-host#6111]
#### What problem would the feature you're requesting solve? Please describe.
We have a project with multiple azure functions, some of which we need to run on premium app-service-plans because they may run longer than 10 minutes in some instances.
We cannot for example modify the timeout for every deploy to be the same, because the consumpition plan throws a 500 error deep in the runtime somewhere if the value of functionTimeout is > 10 minutes and will not execute the function.   I struggled with this issue for a day before stumbling upon the pink error box in the old function ui.
Also for our dev environment, we are not running dedicated app service plans with always on.

#### Describe the solution you'd like
It would be nice if FUNCTION_TIMEOUT would read from the config variables  just like many other values, so it could be part of configuration instead of build.

#### Describe alternatives you've considered
I have to go into kudu and modify host.json to fix this.  

The other option would be for consumption plans to ignore any values set at greater than it's expected value.

#### Additional context
The new UI for functions is very bad at giving you the actual error that occurred

![image](https://user-images.githubusercontent.com/43180217/83188329-cf334500-a12f-11ea-8e57-c760955ee96c.png)

The old ui ( going in through the consumption based app service plan works)
![image](https://user-images.githubusercontent.com/43180217/83188429-f7bb3f00-a12f-11ea-8892-2bcb45d96def.png)

**Comment by vllama** [comment]
In the consumption plan, I had to go in the storage account share to be able to change the value. Really painful.

**Comment by paulbatum** [comment]
You can already override host.json settings through appsettings. Lets assume you want a 10 minute timeout for consumption and a 1hr timeout for the same app in premium. Then:

1. Remove the timeout configuration from host.json
2. For your consumption function apps, add the following appsetting: `AzureFunctionsJobHost__functionTimeout = 00:10:00`
3. For your premium function apps, add the following appsetting: `AzureFunctionsJobHost__functionTimeout = 01:00:00`

I'm closing this as answered, I will reopen if you have followup questions/issues.
