### ISSUE TITLE
Custom routePrefix not respected in Portal Code + Test lead to 404s always

### ISSUE THREAD

**Issue by drdamour** [Azure/azure-functions-host#6127]
#### Investigative information

Please provide the following:

- Timestamp:
- Function App version: 3
- Function App name: usos1fap01-tecsys-agvance-middleware 
- Function name(s) (as appropriate): *any*
- Invocation ID:
- Region: us west 2

#### Repro steps

Provide the steps required to reproduce the problem:

1, in host.json set routePrefix : "dog"
2. go to portal nav to functions 
3. notice the get function url action in overview uses dog prefix
![image](https://user-images.githubusercontent.com/1514496/83319209-93fd4880-a1f9-11ea-9ac7-b27178e75dee.png)
4. switch to code + test
5. notice the get function url here ignores dog and goes back to the default of api
![image](https://user-images.githubusercontent.com/1514496/83319233-ca3ac800-a1f9-11ea-8c5b-96ed6787329a.png)
6. attempt to execute, method will 404 as it makes call with prefix of /api

#### Expected behavior

I expect the code+test to account for the routePrefix in host.json be it dog or blank ""

#### Actual behavior

code+test does not account for routePrefix in host.json be it dog or blank ""

#### Known workarounds

none known

#### Related information 

this may be related to #4363 but i think it's just a bug in the portal.
unclear if portal issues should be raised here or not.

**Comment by ishepherd** [comment]
This is a long-standing issue.

**Comment by mhoeger** [comment]
@btardif - this is a portal bug, can you help get it to the right place?

**Comment by btardif** [comment]
I don't have enough permissions to move items from this repo.

I have create this other bug: **https://github.com/Azure/Azure-Functions/issues/1614**

And tagged the folks in this thread. I think @mhoeger please close this one and we can use the other one for tracking and progress.

**Comment by mhoeger** [comment]
Thanks Byron!! Closing in favor of Azure/Azure-Functions#1614
