### ISSUE TITLE
Can't update Azure Functions SDK because of JWT

### ISSUE THREAD

**Issue by petro2050** [Azure/azure-functions-host#6129]
I'm currently on Microsoft.NET.Sdk.Functions 3.0.3 and trying to update to **3.0.7**. I'm using System.IdentityModel.Tokens.Jwt 6.6.0. When I update my function sdk, I get a runtime error.

`System.IO.FileNotFoundException: Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=6.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.File name: 'System.IdentityModel.Tokens.Jwt, Version=6.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35`

Please note that if I use Functions Sdk 3.0.7, I need to downgrade my JWT version to 5.5.0. So, the issue happens starting 5.6.0.

**Comment by v-anvari** [comment]
Closing this as its discussed in #1429 and #5894 and the fix has already been made
