### ISSUE TITLE
PowerShell Function App Failes Due To MSI Being Enabled ( Azure China )

### ISSUE THREAD

**Issue by gist901** [Azure/azure-functions-host#6131]
Hi all,

I am currently having an issue with MSI and PowerShell Function App in Azure China. I am creating a Function App that will use PowerShell and deploying it in China East 2. Then I create a new HTTP trigger that accepts POST requests. Once the Trigger is created I test it, and it will return the name 'Azure'.

If I go to Identity, and enable Managed Identity, then the Function App ceases to work and will not return the name 'Azure', but an error: '500'. If I disable the Managed Identity, then the function app will work again. I have been troubleshooting the issue all morning and this is what I have identified as being the culprit. I would like to get his issue resolved so that I can begin deploying my scripts.

#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app => `Platform features` => `Diagnose and solve problems` and the relevant dashboards before opening your issue.

#### Investigative information

Please provide the following:

- Timestamp: 2020-06-01T17:23:12.932
- Function App version: 2.0.13351.0  
- Function App name: testlkskdial2902
- Function name(s) (as appropriate): lalicmql982 
- Invocation ID:
- Region: Azure China

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a function app on consumption plan that uses PowerShell
2. Enable Mangaed Identity for the new Function App
3. Create a new Function
4. Execute the new Function using the sample code

#### Expected behavior

I expect the Function App to authenticate and properly execute. Currently the function app still has the example code, so it should be returning the Name that I am passing in as a variable.

#### Actual behavior

The function app is failing to execute and returns a '500 Internal Server Error'

`2020-06-01T17:12:42.436 [Error] Executed 'Functions.HttpTrigger1' (Failed, Id=4a7e1b75-3bda-4942-a1bf-d6a9f9d23a33)Result: FailureException: Value cannot be null.Parameter name: valueStack:    at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)at Microsoft.Azure.WebJobs.Script.Grpc.Messages.StreamingMessage.set_RequestId(String value) in C:\projects\azure-functions-powershell-worker\src\Messaging\protobuf\FunctionRpc.cs:line 332at Microsoft.Azure.Functions.PowerShellWorker.Utility.RpcLogger.Log(Boolean isUserOnlyLog, Level logLevel, String message, Exception exception) in C:\projects\azure-functions-powershell-worker\src\Logging\RpcLogger.cs:line 45at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellManager.InvokeProfile(String profilePath) in C:\projects\azure-functions-powershell-worker\src\PowerShell\PowerShellManager.cs:line 191at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellManager.Initialize() in C:\projects\azure-functions-powershell-worker\src\PowerShell\PowerShellManager.cs:line 111at Microsoft.Azure.Functions.PowerShellWorker.PowerShell.PowerShellManagerPool.CheckoutIdleWorker(StreamingMessage request, AzFunctionInfo functionInfo) in C:\projects\azure-functions-powershell-worker\src\PowerShell\PowerShellManagerPool.cs:line 93at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessInvocationRequest(StreamingMessage request) in C:\projects\azure-functions-powershell-worker\src\RequestProcessor.cs:line 257`

#### Known workarounds

If I disable Identity or comment out the MSI code in the 'profile.ps1' file, the function app will execute properly and return the name that was sent.

#### Related information 

Provide any related information 

* Programming language used = PowerShell
<details>
<summary>Source</summary>

```using namespace System.Net

# Input bindings are passed in via param block.
param($Request, $TriggerMetadata)

# Write to the Azure Functions log stream.
Write-Host "PowerShell HTTP trigger function processed a request."

# Interact with query parameters or the body of the request.
$name = $Request.Query.Name
if (-not $name) {
    $name = $Request.Body.Name
}

if ($name) {
    $status = [HttpStatusCode]::OK
    $body = "Hello $name"
}
else {
    $status = [HttpStatusCode]::BadRequest
    $body = "Please pass a name on the query string or in the request body."
}

# Associate values to output bindings by calling 'Push-OutputBinding'.
Push-OutputBinding -Name Response -Value ([HttpResponseContext]@{
    StatusCode = $status
    Body = $body
})
```
</details>

**Comment by kevin-secrist** [comment]
I ran into an error like this last week, the exception you're seeing may be related to https://github.com/Azure/azure-functions-powershell-worker/issues/337

The issue that I was having was that user-assigned identities are not supported out of the box (https://github.com/Azure/azure-powershell/issues/9479), so `Connect-AzAccount` within profile.ps1 was failing because I needed to also specify the `AccountId` parameter with the clientId of the identity I was using. However, if you're using a system assigned identity this would not apply.

Since Write-Error, Write-Output, etc within profile.ps1 does not work, you can try moving the `Connect-AzAccount` logic out of the profile and into a function (where logging _does_ work) to test it and see what error you are getting and the logging you get there could be more helpful.

**Comment by gist901** [comment]
Hi Kevin, thanks for the suggestion. I have run the script with moving Connect-AzAccount to the run.ps1 file and commented it out on the profile file. The Get-Module portion is working. It is the Connect-AzAccount that is causing the error. Here is the output:

```2020-06-01T19:57:24.215 [Error] ERROR: Connect-AzAccount : An attempt was made to access a socket in a way forbidden by its access permissionsAt D:\home\site\wwwroot\lalicmql982\run.ps1:25 char:9+         Connect-AzAccount -Identity+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~+ CategoryInfo          : CloseError: (:) [Connect-AzAccount], HttpRequestException+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommandScript stack trace:at <ScriptBlock>, D:\home\site\wwwroot\lalicmql982\run.ps1: line 25System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissionsat System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)at System.Threading.Tasks.ValueTask`1.get_Result()at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)at System.Threading.Tasks.ValueTask`1.get_Result()at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)at System.Threading.Tasks.ValueTask`1.get_Result()at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)at Microsoft.Azure.Commands.Common.Authentication.HttpClientWithRetry.SendAsync(HttpRequestMessage request, CancellationToken token)at Microsoft.Azure.Commands.Common.Authentication.HttpClientOperationsFactory.HttpClientOperations`1.SafeSendRequestAsync(HttpRequestMessage request, CancellationToken token)at Microsoft.Azure.Commands.Common.Authentication.HttpClientOperationsFactory.HttpClientOperations`1.GetAsync(String requestUri, CancellationToken token)at Microsoft.Azure.Commands.Common.Authentication.ManagedServiceAccessTokenBase`1.GetOrRenewAuthentication()at Microsoft.Azure.Commands.Common.Authentication.ManagedServiceAccessTokenBase`1.get_AccessToken()at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass92_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass94_0.<SetContextWithOverwritePrompt>b__0(AzureRmProfile prof, RMProfileClient client)at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()Inner exception: System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissionsat System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: ERROR: Connect-AzAccount : An attempt was made to access a socket in a way forbidden by its access permissionsAt D:\home\site\wwwroot\lalicmql982\run.ps1:25 char:9+         Connect-AzAccount -Identity+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~+ CategoryInfo          : CloseError: (:) [Connect-AzAccount], HttpRequestException+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommandScript stack trace:at <ScriptBlock>, D:\home\site\wwwroot\lalicmql982\run.ps1: line 25System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissionsat System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)at System.Threading.Tasks.ValueTask`1.get_Result()at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)at System.Threading.Tasks.ValueTask`1.get_Result()at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)at System.Threading.Tasks.ValueTask`1.get_Result()at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)at Microsoft.Azure.Commands.Common.Authentication.HttpClientWithRetry.SendAsync(HttpRequestMessage request, CancellationToken token)at Microsoft.Azure.Commands.Common.Authentication.HttpClientOperationsFactory.HttpClientOperations`1.SafeSendRequestAsync(HttpRequestMessage request, CancellationToken token)at Microsoft.Azure.Commands.Common.Authentication.HttpClientOperationsFactory.HttpClientOperations`1.GetAsync(String requestUri, CancellationToken token)at Microsoft.Azure.Commands.Common.Authentication.ManagedServiceAccessTokenBase`1.GetOrRenewAuthentication()at Microsoft.Azure.Commands.Common.Authentication.ManagedServiceAccessTokenBase`1.get_AccessToken()at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass92_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass94_0.<SetContextWithOverwritePrompt>b__0(AzureRmProfile prof, RMProfileClient client)at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()Inner exception: System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissionsat System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)Exception: An attempt was made to access a socket in a way forbidden by its access permissionsStack:    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)at System.Threading.Tasks.ValueTask`1.get_Result()at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)at System.Threading.Tasks.ValueTask`1.get_Result()at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)at System.Threading.Tasks.ValueTask`1.get_Result()at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)at Microsoft.Azure.Commands.Common.Authentication.HttpClientWithRetry.SendAsync(HttpRequestMessage request, CancellationToken token)at Microsoft.Azure.Commands.Common.Authentication.HttpClientOperationsFactory.HttpClientOperations`1.SafeSendRequestAsync(HttpRequestMessage request, CancellationToken token)at Microsoft.Azure.Commands.Common.Authentication.HttpClientOperationsFactory.HttpClientOperations`1.GetAsync(String requestUri, CancellationToken token)at Microsoft.Azure.Commands.Common.Authentication.ManagedServiceAccessTokenBase`1.GetOrRenewAuthentication()at Microsoft.Azure.Commands.Common.Authentication.ManagedServiceAccessTokenBase`1.get_AccessToken()at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass92_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass94_0.<SetContextWithOverwritePrompt>b__0(AzureRmProfile prof, RMProfileClient client)at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()```

**Comment by kevin-secrist** [comment]
Are you using a user-assigned identity or a system-assigned identity?

**Comment by gist901** [comment]
System-assigned identity.

This is the first time I am trying function apps since we stood up our Azure China environment recently.

I am not running into this issue when I create a system-assigned managed identity when I create logic apps

**Comment by gist901** [comment]
If I use user-assigend identity, I get the same response / error messages in the function app as mentioned above.

I tried creating new function app in different regions. Then creating a MSI first before creating the Function. But still run into the same issue.

If I run `Set | grep MSI` in the console window I do see the MSI Secret for the Function App and the following information

```
IDENTITY_ENDPOINT=http://127.0.0.1:41323/MSI/token/
MSI_ENDPOINT=http://127.0.0.1:41323/MSI/token/
MSI_SECRET=*****************************
```

**Comment by kevin-secrist** [comment]
The error you're getting looks like many of the things mentioned in https://github.com/Azure/azure-powershell/issues/7876 however the issue appears to have been "solved". There are some workarounds in that issue you could try in the meantime, but I think maybe someone from MS may have more insight into what is happening here. 🤷 

Another tiny suggestion would be to try `-Verbose` on `Connect-AzAccount` and see if anything useful is logged, though I doubt anything logged will be insightful.

**Comment by yojagad** [comment]
@gist901 I was digging around and found this issue https://github.com/Azure/azure-functions-powershell-worker/issues/235. The error you pointed out looks similar. Could you take a look and see if there's something there that might help you out?
