### ISSUE TITLE
Custom Handler: Allow pre-defined routes to be handled by a custom handler via sub-path

### ISSUE THREAD

**Issue by guibirow** [Azure/azure-functions-host#6132]
#### What problem would the feature you're requesting solve? Please describe.

When `customHandler` is enabled by using the `httpWorker` feature, all requests are forwarded to the handler and ignore any existing functions.

#### Describe the solution you'd like

CustomHandler is an amazing feature that will bring opportunity to do lots of customizations with languages not supported by the runtime.
The current preview does not work alongside other existing functions and force all requests to be handled by the custom handler.

Would be nice if we could enable customHandlers based on a route and keep it working alongside other functions.
A simple example is an API with simple operations and one specific CPU heavy function which could be handled by a C++ or Rust handler to make best use of the resources.

While this is something which would be possible to handle on separate hosts, would be much more convenient if we could keep them together in a single deployment package.

#### Describe alternatives you've considered

Create separate host, which will add more deployment overhead.

#### Additional context

Be able to handle a request from a custom server and be able to define the routes we want to be forwarded to the customHandler and let the other routes be handled via usual function definitions.

We probably should set in the function, the route alongside the handler we want to use, something like:
``` 
function.json
{
  "bindings": [
    {
      "type": "httpTrigger",
      "authLevel": "anonymous",
      "name": "req"
      "methods": [
        "get",
        "post"
      ],
     "route": "subpath/{*path}"     //Will route only requests that matches the subpath
    }
  ],
  "disabled": false,
  "customHandler": "MyCustomHandler"    //will be handled by customHandler defined here
}
```

**Comment by mhoeger** [comment]
@pragnagopa and @anthonychu (I think!) - can you help triage this issue?

**Comment by mhoeger** [comment]
@guibirow - btw, my guess is that we won't enable this feature (either must choose custom handler or functions), similar to how we don't allow a mix of different languages in a single function app.

**Comment by anthonychu** [comment]
That’s correct. We don’t currently have plans to support this as each app is only designed to work with one type of language worker/handler at a time.

**Comment by guibirow** [comment]
Does it mean it will also force queue based trigger to be handled in the custom http handler?

I don't understand why this should be a restriction given the .net will be already loaded in memory to handle the request and forward it to the custom handler.
In this case would be nicer if .net didn't need to handle the request then, and have the custom handler receive all the calls directly, the .net add too much overhead.

**Comment by anthonychu** [comment]
Yes. The main goal of custom handlers is to allow you to write a worker process that is called whenever a function, regardless of trigger type, is invoked. When you use a custom handler, it replaces the language worker (Node, Java, etc). The Functions host happens to use HTTP to communicate with a custom handler, but you can think of that as an implementation detail and it’s not related to the types of triggers it supports.

Triggers and bindings are implemented as extensions that are shipped as .NET assemblies. They run in the host process even if an out of process language worker or custom handler is used.

The fact that the host process is written in .NET and that .NET functions currently run in the same process should also be seen as an implementation detail. .NET functions may one day run in a separate language handler process as well.

Running multiple workers/handlers in the same function app would introduce some complexities and inefficiencies. We have so far decided not to support it.

**Comment by guibirow** [comment]
Got it, thanks for clarifying.
I will close the issue then.
Thanks again
