### ISSUE TITLE
Cannot link Azure Function app to github repo

### ISSUE THREAD

**Issue by dgeisner** [Azure/azure-functions-host#6133]
#### Investigative information
- Timestamp: 6/1/2020 13:30 PST
- Function App version: 1.0.0
- Function App name: Az-StartStopDeploymentPOC
- Function name(s) (as appropriate): N/A
- Invocation ID: N/A
- Region: Central US

#### Repro steps
Provide the steps required to reproduce the problem:
1. Opened 'Deployment center'
2. Selected GitHub
3. Clicked Authorize

#### Expected behavior
App is linked to Github and setup continues.

#### Actual behavior
Redirect message hangs and flow does not proceed.

#### Known workarounds
Attempted to set up using External Repo, but got deployment failure notifications.

#### Related information 
Hangs on this popup:
![image](https://user-images.githubusercontent.com/46330579/83449048-ca101780-a407-11ea-80f8-1c7699aa39f8.png)

**Comment by ankitkumarr** [comment]
@dgeisner, I am unable to repro this. I tried the flow, and login window appeared. What browser and OS are you using? Would you mind trying it with a different browser?
