### ISSUE TITLE
How do I control max instances of an app on Premium Plan?

### ISSUE THREAD

**Issue by ishepherd** [Azure/azure-functions-host#6137]
I can set bounds on scaling of the plan (screenshot)

Is there any way to set bounds on how many instances of the app are running?

(Will the `WEBSITE_MAX_DYNAMIC_APPLICATION_SCALE_OUT` be effective for controlling this on Premium Plan?)

![image](https://user-images.githubusercontent.com/3198421/83481914-52fb8180-a4e2-11ea-991f-c68b57b20c8b.png)

**Comment by fabiocav** [comment]
Those instance bounds define the maximum number of instances you'll be scaling out to, so the setting is not needed.

**Comment by fabiocav** [comment]
Did you find an issue with the settings above?

**Comment by ishepherd** [comment]
> Those instance bounds define the maximum number of instances you'll be scaling out to, so the setting is not needed.

@fabiocav The top 2 settings are for plan scaling right?

We are building an app that shouldn't be scaled out to the entire plan (it will hammer downstream systems).

Does `WEBSITE_MAX_DYNAMIC_APPLICATION_SCALE_OUT` still work on Premium Plan? Is it reliable? [Still says preview](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#website_max_dynamic_application_scale_out), been years :(

**Comment by ThejaChoudary** [comment]
@fabiocav can you please look into this further.

**Comment by ishepherd** [comment]
+ @jeffhollan you might have a quick answer for this

**Comment by jeffhollan** [comment]
The UX has been updated - this "Enforce scale out limit" dial will set a per-app mx

![image](https://user-images.githubusercontent.com/7132626/93146597-183de380-f6a4-11ea-8e09-9f7d0a7548bf.png)

**Comment by ishepherd** [comment]
@jeffhollan Awesome thanks - So that updates ARM functionAppScaleLimit, I'm guessing? https://github.com/MicrosoftDocs/azure-docs/commit/e4e68ce7b50b701bf2c7fc18b32759015dddd8c8

**Comment by stinejohans1** [comment]
Is there any other way then the azure cli to set the app property functionAppScaleLimit (and MaxConcurrentActivityFunctions, MaxConcurrentOrchestratorFunctions) in code or arm template for app services?

**Comment by v-anvari** [comment]
@stinejohans1 , I hope you are looking out for [this link](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#limit-scale-out) and it solves the problem.
