### ISSUE TITLE
[HttpTrigger] DateTimeOffset? binding works when POST but fails with GET

### ISSUE THREAD

**Issue by VividDigital** [Azure/azure-functions-host#6139]
- Function App version: v3
- Region: local development

#### Repro steps

Provide the steps required to reproduce the problem:

post query string with DateTimeOffset?:

?from=2020-06-02T04:00:00.000Z&to=2020-06-03T03:59:59.000Z

#### Expected behavior

DateTimeOffset? fields bind correctly, the same way they do when those values are posted instead of used in the query string

#### Actual behavior

Exception: Invalid cast from System.String to System.DateTimeOffset

#### Related information 

Standard C# HttpTrigger that binds the POCO directly. Nothing in the trigger changes except the HTTP verb used to access it
I've tried encoding the date in different ways according to different specs but it fails with that exception every time no matter how it's formatted.

**Comment by v-anvari** [comment]
Hi @VividDigital , Apology for the delayed response. Are you still facing the same issue, if yes could you provide us the repro steps and repro code for us to understand it better.
