### ISSUE TITLE
Azure Function with nodejs container website can not update after VSTS deployed successfully

### ISSUE THREAD

**Issue by RainWuGuy** [Azure/azure-functions-host#6156]
I have an Azure function with node container image 
> mcr.microsoft.com/azure-functions/node:3.0-node12-appservice-stage5
The function is configured with source control with VSTS repo
1. deployed by VSTS pipeline with a specific branch
2. The kudu site code under the wwwroot/ is updated
3. But azure function portal function list can not be updated

**Comment by mhoeger** [comment]
@RainWuGuy - sorry for the delay. are you still experiencing this issue? 
can you share your function app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? this will help us investigate. thanks!

**Comment by RainWuGuy** [comment]
This is the Azure latest release bug and be fixed bu the support, thanks a lot.
