### ISSUE TITLE
Host.Bindings is very slow

### ISSUE THREAD

**Issue by a-vishar** [Azure/azure-functions-host#6158]
#### Investigative information

Please provide the following:

- Timestamp: 2020-06-04T14:03:34.9962218Z
- Function App version: Latest
- Invocation ID: 8aa3d61f-45a2-4701-a8c3-820aca2e95ea 
- Region: West Europe

#### Repro steps

1) Have a function run a regular timer trigger
2) Call the function via some other HTTP trigger when the function is "warmed" by the timer trigger

#### Expected behavior

The function should return quickly

#### Actual behavior

The function is slow

725 ms is spent in Host.Bindings for COSMOS in the HTTP trigger.  This is a very long time for what I imagine is simple DI.

#### Known workarounds

None

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

![image](https://user-images.githubusercontent.com/7255079/83784558-69434200-a688-11ea-81ff-31276bd4eebd.png)

**Comment by gzuber** [comment]
@a-vishar I see that you repro'd this in West Europe, would you be able to provide the App name? It would help us with looking into this in our logs, thanks!

**Comment by a-vishar** [comment]
@gzuber - I have emailed you the name.  

I should add that the instructions stated that you didn't need the name, but only the InvocationId and region.  If this is not the case, I would suggest that you alter the default text which appears when someone opens a new issue.

**Comment by a-vishar** [comment]
@gzuber - Any update on this?

**Comment by a-vishar** [comment]
Any update on this?

**Comment by fabiocav** [comment]
Following up with @gzuber for an update. Apologies for the delay.

**Comment by a-vishar** [comment]
Any update on this?

**Comment by v-anvari** [comment]
@gzuber , did you get a chance to look into the logs?

**Comment by pragnagopa** [comment]
@a-vishar - apologies for the delay in response. If this is still an issue, please provide latest timestamp and failed invocation id
