### ISSUE TITLE
ServiceBusTrigger - Unable to manually Deadletter and indicate that the Function Invocation has failed

### ISSUE THREAD

**Issue by cmckeegan** [Azure/azure-functions-host#6166]
Using the c# SDK V3

There are certain types of exceptions that may occur that negate the need for the message to be delivered x times. In these cases I want to DeadLetter the message immediately.

 Setting autoComplete to false enables this, but it has the side effect of marking the function invocation as successful which it isn't. For monitoring purposes I'd still want to know that the function failed.

The only way to mark a function as failed is to throw an exception. If I do this after DeadLettering the message, rather than the exception I raised being the cause of the failure a different exception is raised by the underlying runtime attempting to call AbandonAsync with a now expired lockToken due to the DeadLetter.

Are there alternatives for marking a function as failed without raising an exception?

**Comment by fabiocav** [comment]
Not today. This is something we're investigating as a potential new capability.
