### ISSUE TITLE
Azure Function Blob trigger fails to trigger after being idle

### ISSUE THREAD

**Issue by rghkrish** [Azure/azure-functions-host#6169]
#### Is your question related to a specific version? If so, please specify:
Azure Functions Runtime version 3.x
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question

I have an Azure function that gets triggered off a blob storage container. Whenever a new file comes into the container, the function gets triggered, calls out to keyvault and cosmosdb, does a few operations.

The function was working as expected and there were no new files in the blob container for a couple days and when files started coming in again, the function did not get triggered. I have gone through the logs and have found absolutely no exceptions or errors of any kind. The function app simply failed to get triggered.

This is on a Premium plan. People suggest turning the "Always on" option on. But I do not find it anywhere. Is the issue even related to this?

Any help is hugely appreciated.

**Comment by v-anvari** [comment]
@rghkrish sorry for the delay in response, Kindly, let us know if the issue is still persisting? 

If yes, please provide us additional details mentioned in the issue template.
