### ISSUE TITLE
Update Custom Handlers samples and docs

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#6178]
cc @craigshoemaker @anthonychu 

Tracking issue to update docs and samples : https://github.com/Azure-Samples/functions-custom-handlers after #6080 is deployed to prod.

**Comment by anthonychu** [comment]
Thanks. Was just talking to @craigshoemaker about this today. What's a rough ETA?

Since the changes are backwards compatible, we don't have to land the docs exactly on that date. But would be great to get them ready soon after they are available.

**Comment by pragnagopa** [comment]
Changes will be part of the next functions release. Approximate ETA ~3 weeks from now.

**Comment by pragnagopa** [comment]
`customHandler` config changes are rolling out to prod. Assigning issue to current sprint to update samples.

**Comment by anthonychu** [comment]
What's the ETA? I'll work on the docs.

**Comment by pragnagopa** [comment]
Changes are still rolling out ETA ~2weeks. I will update this issue when roll out completes and I have tested updated samples in prod.

**Comment by pragnagopa** [comment]
PR: https://github.com/Azure-Samples/functions-custom-handlers/pull/12 removes unsupported samples

**Comment by pragnagopa** [comment]
PR: updating samples to use customHandler section: https://github.com/Azure-Samples/functions-custom-handlers/pull/13

Verified samples locally. Bits are still rolling out. Moving this issue back to Triaged. Will bring it back when prod roll out completes.

**Comment by yojagad** [comment]
Closing this as this is merged and done.
