### ISSUE TITLE
Storage queue binding fails with latest Microsoft.Azure.WebJobs.Extensions.Storage

### ISSUE THREAD

**Issue by JonCanning** [Azure/azure-functions-host#6186]
`Tried binding to 'Microsoft.Azure.Storage.Queue.CloudQueue, Microsoft.Azure.Storage.Queue, Version=11.1.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' but user type assembly was 'Microsoft.WindowsAzure.Storage.Queue.CloudQueue, Microsoft.WindowsAzure.Storage, Version=9.3.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35`

I can get it to work by pinning to version 3.0.1.1

**Comment by vsadams** [comment]
Check to make sure you replace all using statements for
 ```using Microsoft.WindowsAzure.Storage.***;```
with
```using Microsoft.Azure.Storage.***;```

Class names are the same so if you just updated the nuget package, the compiler wont pick up the difference. You dont want the binder binding to the legacy classes anymore though.

**Comment by JonCanning** [comment]
That was it, thanks @vsadams
