### ISSUE TITLE
Detected host offline in function app

### ISSUE THREAD

**Issue by pradeep-rp** [Azure/azure-functions-host#6189]
Off late, my function apps are going down for few minutes. When I look at the Diagnostics blade, I see the following error.

```
Detected host offline in your function app.
Description
A host error has occurred during startup operation '82fafa6d-aa8c-4526-bee9-04f4fd615f53'.

Last offline at
6/9/2020 7:32:53 AM

Details
System.Net.Sockets.SocketException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

at async System.Net.Http.ConnectHelper.ConnectAsync(String host,Int32 port,CancellationToken cancellationToken)
All running functions in healthy state with execution failure rate less than 0.1%.
Description
Function
(Top 3 by execution count)	Successful Executions	Failed Executions	Failure Rate(%)
DeleteAssessmentsForParty	5495	0	0 %
Healthcheck	1419	0	0 %
AssessmentsTrigger	58	0	0 %
```

I had more than two instances of this with couple of function apps in the last few days. There are no other supporting logs and looking at the Service Health page, everything looks normal.

Could you please review and let me know if you need more details?

**Comment by pradeep-rp** [comment]
Any updates on this?

**Comment by kashimiz** [comment]
Hi @pradeep-rp, my apologies for the late reply. Are you still experiencing this issue? If so, can you provide us with more information about your function app so we can investigate? Namely:

- Timestamp:
- Function App version:
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

If you don't want to share your Function App name or Functions names on GitHub, please be sure to provide your Invocation ID, Timestamp, and Region - we can use this to look up your Function App/Function. Provide an invocation id per Function. See the [wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) for more details.
