### ISSUE TITLE
Azure Functions Execution Count Metrics

### ISSUE THREAD

**Issue by tucane** [Azure/azure-functions-host#6194]
I am writing a function(V2) that calls a REST API endpoint(queue trigger not httptrigger). This endpoint has a threshold that will throttle you if you're calling too many times / min. I would like to keep the peak function execution count below a certain threshold.

There are a few config values that I have set that controls concurrency. However, it does not seem like it's behaving the way that I want it to be.

WEBSITE_MAX_DYNAMIC_APPLICATION_SCALE_OUT = 1
extension.queue.batchSize = 1
extension.queue.newBatchThreshold = 0

According to the documentations, my function will scale to 1 instance and only pull 1 message in the queue per batch, and the next batch won't be done before the current batch is finished.

This is the execution count graph. There are minutes where it's not doing processing at all, and at peak it's doing ~900 executions/min. I'm not sure how my current setting would cause ~900 calls/min for one minute but 0 for another.

![image](https://user-images.githubusercontent.com/14172078/84182787-ce5bb680-aa3f-11ea-9237-c378122832bd.png)

**Comment by brettsam** [comment]
@tucane -- sorry for the delay here. Were you ever able to figure out the behavior? Without knowing how the queue was getting messages, it's hard to tell if this is as-expected or not.

**Comment by tucane** [comment]
Hi @brettsam, I haven't figured out the behavior as I've put a pause on the work. There is a separate app that pushes message into the queue in bulk, and the function gets triggered whenever there are still messages in the queue that are not consumed.

**Comment by brettsam** [comment]
Thanks for getting back to us, @tucane. I'm going to close this but feel free to re-open if you're able to come back to this and continue seeing the issue. Then we can gather more details and do some investigation.
