### ISSUE TITLE
[Regression]Fix proxy behavior

### ISSUE THREAD

**Issue by yojagad** [Azure/azure-functions-host#6198]
Today, ScriptHost.cs iterates through the list of descriptorProviders to try and create the right one for each FunctionMetadata.
https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Host/ScriptHost.cs#L694 

If a function exists with a proxy, as long as the ProxyFunctionDescriptorProvider is evaluated first, invocations for proxy go through the correct invoker. However, if WorkerFunctionDescriptorProvider is evaluated first for some reason, proxy requests would go through the wrong invoker and therefore fail.

**Comment by fabiocav** [comment]
Curious, why was this added to sprint 77? Do we have an incident? How was this detected?

**Comment by yojagad** [comment]
Adding a little more context here as discussed in the call. I verified that the order of evaluation before the commit here 621df2c with a function that has a proxy as well, is the ProxyFunctionDescriptorProvider followed by WorkerFunctionDescriptorProvider. With the afore mentioned commit , WorkerFunctionDescriptorProvider was getting evaluated first thus routing proxies to the wrong route.

I added E2E tests for HttpWorker and RpcWorker scenarios to catch any ordering regression going forward

proxies.json
https://github.com/Azure/azure-functions-host/blob/dev/sample/HttpWorker/proxies.json https://github.com/Azure/azure-functions-host/blob/dev/sample/Node/proxies.json

E2E tests.
https://github.com/Azure/azure-functions-host/blob/dev/test/WebJobs.Script.Tests.Integration/WebHostEndToEnd/SamplesEndToEndTests_HttpWorker.cs#L38
https://github.com/Azure/azure-functions-host/blob/dev/test/WebJobs.Script.Tests.Integration/WebHostEndToEnd/SamplesEndToEndTests_Node.cs#L120

**Comment by pragnagopa** [comment]
Adding more context:

Before this fix, if host.json had `httpWorker` sections with the following proxies:
```json
{
  "proxies": {
    "proxyroute": {
      "matchCondition": {
        "methods": [
          "GET"
        ],
        "route": "/something"
      },
      "responseOverrides": {
        "response.statusCode": "200",
        "response.headers.Content-Type": "text/plain",
        "response.body": "something"
      }
    }
  }
}
```

it would result in creating HttpWorkerDescriptor for proxies. Which is not expected behavior.
