### ISSUE TITLE
[Kudu] tracking item - Forward synctriggers request from kudu to functions runtime

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-host#6209]
Kudu has synctriggers logic that is out of date. We need to update that to forward requests to the Runtime. Here's the work item -- https://github.com/projectkudu/kudu/issues/3113

**Comment by pragnagopa** [comment]
Intial design has been discussed. Moving to next sprint for implementation.

**Comment by ankitkumarr** [comment]
Closed by https://github.com/projectkudu/kudu/commit/5e7f206050e0ec218e5acb9095ee7e62be562ede
