### ISSUE TITLE
Intermittent 502 Bad gateway errors when initially posting requests (Azure Runtime v3)

### ISSUE THREAD

**Issue by imaad-ahmed** [Azure/azure-functions-host#6216]
I have a .netcore 3.1 Azure Function on azure functions runtime version 3.0.13760.0 using a consumption plan. Occasionally when first posting a request I receive a 502 bad gateway response, this happens roughly one in every 2000 requests and when resubmitting the request succeeds. I have gone about the usual troubleshooting methods of checking application insights data around the time the request is processed and there doesn't seem to be any common factor linking them. Generally the app doesn't have a high load when this occurs and we have no application gateway installed for this azure function.

**Comment by kashimiz** [comment]
Hi @imaadzahmed, my apologies for the late reply. Are you still experiencing this issue? If so, can you provide the following information so we can investigate?

- Timestamp:
- Function App version:
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

If you don't want to share your Function App name or Functions names on GitHub, please be sure to provide your Invocation ID, Timestamp, and Region - we can use this to look up your Function App/Function. Provide an invocation id per Function. See the [wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) for more details.
