### ISSUE TITLE
Seeing HttpStatusCodeResult messages every 5 minutes in Application Insights

### ISSUE THREAD

**Issue by ravibha** [Azure/azure-functions-host#6219]
Hi,
I am using timer triggered and service bus triggered Azure functions v2.0 code in C#.

Every 5 mins or so, I see a trace log with the following message:
"Executing HttpStatusCodeResult, setting HTTP status code 200". There are some more system messages that I want to block. This results in a lot of noise. Is there a way to prevent it?
In my startup.cs, I have services.AddLogging(); Not sure if that might be causing this as well.

Please note, I do need to see trace messages I log with logger.LogInformation/logger.LogError, but do not want to see the host generated messages.

My host.json looks like below:
```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingExcludedTypes": "Request",
      "samplingSettings": {
        "isEnabled": true
      }
    },
    "logLevel": {
      "default": "Information",
      "Host": "Error",
      "Function": "Information"
    }
  }
```
Thanks
-Ravi

**Comment by fabiocav** [comment]
@ravibha your logging level seems to be using the incorrect hierarchy. The `logLevel` should be under `logging`.

Can you please follow the information available here to configure this?
https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring?tabs=cmd#version-2x-and-higher

Thanks!
