### ISSUE TITLE
Runtime version status - Azure function not working

### ISSUE THREAD

**Issue by perkops** [Azure/azure-functions-host#6222]
#### Investigative information

I have a function app, that was previously deployed to a subscription/resource-group and its been working fine.

However upon moving this function app to production, I am deploying it to a new subscription and a new resource group - but its the same code being deployed via CI/CD pipeline and AZ CLI scripts.

After deployment, I am getting the following error in the Azure Portal in the "Notifications tab" in the "Overview".

"Runtime version status" - "There are some issues with your runtime version. Click here for details."
![overviewerrornotification](https://user-images.githubusercontent.com/43060445/84491095-504c1980-aca4-11ea-8f5b-e0815e2ba045.png)

When I click this link, i am taken to the "Configuration" tab - where I am not sure what todo?
When i compare the old function app with the new, its the same settings that are deployed.

Also on the overview page i can see the following error:
![overviewerror](https://user-images.githubusercontent.com/43060445/84491238-838ea880-aca4-11ea-91a4-dbf6149fb1f6.png)

Please provide the following:

- Timestamp:  June 12, 2020, 11:33:50 AM GMT+2
- Function App version:  v3
- Function App name: btmstdfdevmlddeliv
- Function name(s) (as appropriate): MachineReasonCodeChangedProcessorFunction
- Invocation ID: (none as the function app is not working)
- Region: West-Europe
- Runtime-Version: 3.0.13760.0 ( I could see this before deploying actual function, when only function app was deployed)

The old function that works perfectly in another subscription/resource group:

- Function App version: v3
- Function App name: btmstdifdevmlddeliv
- Function name(s): MachineReasonCodeChangedProcessorFunction
- Region: West-Europe
- Runtime-Version: 3.0.13760.0

#### Repro steps

Not sure what to write here, since you cant see my CI/CD pipeline.

#### Expected behavior

The function app works and runs as expected as in the old resource group and name.

#### Actual behavior

The function app does not start and reports a runtime error in the Portal.

#### Known workarounds

None - dead in the water.

#### Related information 

Provide any related information 

* Programming language used : .NET / C# core 3
* Bindings used: EventHub Trigger

**Comment by ThiagoDaher** [comment]
Same issue with my Azure Function.
Any workaround?

**Comment by JoelGallagher** [comment]
Same issue - please advise!

**Comment by perkops** [comment]
After removing the following nuget packages from the solution and not invoking KeyVault anymore, I've got it running again.

Removed packages:

<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" /> (use WebJobsStartup instead of FunctionsStartup)
<PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.4.0" />
<PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="3.1.2" />

**Comment by perkops** [comment]
Microsoft.Azure.Services.AppAuthentication" Version="1.4.0"
Microsoft.Extensions.Configuration.AzureKeyVault" Version="3.1.2"
Microsoft.Azure.Functions.Extensions" Version="1.0.0"

**Comment by click2install** [comment]
@perkops What was your resolution?

 - Change `[assembly: FunctionsStartup(...)]` to `[assembly: WebJobsStartup(...)]`
 - What about the `FunctionsStartup` base class which we override `Configure` from. Did you replace that also? If so, which assembly/package does that live in?

**Comment by JoelGallagher** [comment]
@click2install you can change it to
`
using Microsoft.Azure.WebJobs;
[assembly: WebJobsStartup(typeof(Startup))]

namespace x {
public class Startup : IWebJobsStartup`

**Comment by malantin** [comment]
I am facing the same issue. Changing the Startup.cs to use IWebJobsStartup did not solve the problem for me.

**Comment by click2install** [comment]
@n01d If you view your function from the classic view in the portal it will show you the exception message that is occurring which may be more helpful in diagnosing your issue. I did not have to change to `WebJobsStartup` to resolve my issue once I found the root cause.

**Comment by malantin** [comment]
We found the underlying issue on our side and it now works with _WebJobStartup_ as well as _FunctionsStartup_. Thank for you support @click2install. The exception in the classic view helped us find the issue.

I consider the _error_ in the runtime information a bug in the UI for Azure Functions. Also the link to the configuration that was provided in the notifications section wasn't helpful.

**Comment by NatMarchand** [comment]
Same for me, my issue was a coworker changing the function to x86 whereas our code is x64 . I noticed the error when going also to the old experience. Maybe a better message in the UI should be considered ?

**Comment by smgn** [comment]
Same for me, my issue was "The function runtime is unable to start. Microsoft.Azure.WebJobs.Script: FunctionTimeout must be greater than 00:00:01 and less than 00:10:00.". That was running well on the local machine, but failed to start remote. No messages, no errors in the new UI.
Thanks, @click2install
