### ISSUE TITLE
ILogger<T> ctor injection does not log traces to AppInsights

### ISSUE THREAD

**Issue by cannehag** [Azure/azure-functions-host#6229]
Using Azure Functions version 3.

I'm trying to get trace logging to work across my application classes but having some problem.
When using the function method ILogger parameter, my LogInformation() calls ends up as traces in AppInsights.

But what I would like to do is to use ILogger<T> with ctor injection in other services in my application. When doing that, LogInformation() calls are not logged to AppInsights.

Should that work or whatever other approach should I have to accomplish what I'm trying to do ?

**Comment by APIWT** [comment]
We have this issue too. If I remember correctly, there is a workaround: https://github.com/Azure/azure-functions-host/issues/4425#issuecomment-492599644

I think that thread should provide you all the detail you need. To me, it seems like this functionality should "just work" without extra effort. I'm not sure why you should have to modify the host.json file at all.

**Comment by cannehag** [comment]
@APIWT Yeah, that's the workaround I found after some more digging too.

**Comment by v-anvari** [comment]
Closing this issue as the workaround has been mentioned above.
