### ISSUE TITLE
Add a Twilio sample

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#623]
Like we have for SendGrid

**Comment by christopheranderson** [comment]
Punting based on our bar for rc

**Comment by fabiocav** [comment]
Addressed with https://github.com/Azure/azure-webjobs-sdk-extensions/blob/b7aa8f84c2b3c9065861fe955ce8180b9d19f939/src/ExtensionsSample/Samples/TwilioSamples.cs
