### ISSUE TITLE
Update Github docs with Microsoft Q&A

### ISSUE THREAD

**Issue by SamaraSoucy-MSFT** [Azure/azure-functions-host#6232]
The MSDN Functions forums has been migrated to Microsoft Q&A, and customers are no longer able to post questions on MSDN. 
The new forum link is https://docs.microsoft.com/en-us/answers/questions/topics/single/25345.html

There are a couple references to MSDN forums in this wiki that need to be changed out:
https://github.com/Azure/azure-functions-host/wiki/Investigating-and-reporting-issues-with-timer-triggered-functions-not-firing

https://github.com/Azure/azure-functions-host/wiki

https://github.com/Azure/azure-functions-host/blob/72e0f359ecaea73827defc5756dc5ddc96138df9/CONTRIBUTING.md

**Comment by yojagad** [comment]
Thanks for letting us know. We'll be sure to take a look at these.
