### ISSUE TITLE
Http 500 internal server azure functions 

### ISSUE THREAD

**Issue by smanjubashini** [Azure/azure-functions-host#6235]
#### Question
I m preparing for azure 204 certification. I'm working on exercise on Microsoft preparation materials for this certification. I tried creating a http trigger function in azure portal. It worked fine but when I added a cosmos db binding to it it gave me http 500 error also tried creating durable functions.executing that also gave the same error. Can anyone pls guide me on this? I'm totally new to azure .it would be great if anybody can help me move forward

**Comment by balag0** [comment]
Can you share the name of the function app?

**Comment by smanjubashini** [comment]
Thanks for your response. manjuapp is the function app name. I tried executing the durable functions later. It was successful. But with cosmnos db binding im still getting same error.

**Comment by ankitkumarr** [comment]
@smanjubashini, would you also be able to share a repro for us to run on our end and see what might be failing?
