### ISSUE TITLE
Request body intermittently eaten by headers

### ISSUE THREAD

**Issue by Chaosed0** [Azure/azure-functions-host#6236]
#### Investigative information

Please provide the following:

- Timestamp: 6/17/2020, 5:24:06.362 AM
- Function App version: 3.0.13760.0
- Function App name: BreakpointLeaderboard
- Function name(s) (as appropriate): SubmitScore
- Invocation ID: 55332be2-186d-449f-a359-8cb58d8c0b1e
- Region: Unsure

#### Repro steps

Hit the functionapp several times, sending a body. In about 1 out of 5 cases, the function will hit an error saying there is no body (as distinct from "malformed body").

#### Expected behavior

The function should receive a body.

#### Actual behavior

The body contained in the request object received by the function is null, even though a body is sent in the HTTP request.

#### Known workarounds

No known workaround.

#### Related information 

After logging the full context object in the requests, I believe that I've tracked down the culprit. The `x-ms-private-id` header appears to be malformed and is eating parts of the request. Most of the time, it appears that it eats other headers. For example, in the request with invocation ID `b607aa86-9962-4f1c-8930-022ae7a76ee6`, I'm seeing the following in the logs (after expanding headers):

![image](https://user-images.githubusercontent.com/2808430/84862688-7701ab80-b028-11ea-83e2-049ba0d98f32.png)

It's mostly fine when this happens, since our function doesn't really care about the header getting eaten. However, sometimes - maybe 1 out of 4 or 5 times - the body is getting eaten by this header:

![image](https://user-images.githubusercontent.com/2808430/84862745-94367a00-b028-11ea-9892-202fb5245435.png)

This is a critical bug for us as our function depends on receiving the body to interpret the request. We've worked around it for now by trying to read the body from the `x-ms-private-id` header, though this is fragile for obvious reasons.

I've tried function runtimes v2 and v3 to no avail. We are using the Javascript Node runtime.

**Comment by gorillapower** [comment]
I've encountered this in my local nodejs http trigger, but instead of `x-ms-private-id` my body is being eaten by the `x-functions-key` header.

![image](https://user-images.githubusercontent.com/8879065/99225308-84e27500-27f0-11eb-9bc8-468b49b5f9a2.png)

I see the problem disappears when the header has a value other than empty string (on my local machine, i set the value to empty string for development).

![image](https://user-images.githubusercontent.com/8879065/99225604-fde1cc80-27f0-11eb-9ea0-f950a0c5905a.png)

- Core Tools Function Runtime Version: 3.0.13901.0

**Comment by anthonychu** [comment]
@mhoeger Do you know if this might be an issue with the host or Node worker?

**Comment by v-anvari** [comment]
Hi @Chaosed0 , Can you let us know if this scenario is still seen
