### ISSUE TITLE
Weird behavior of Azure Functions on Linux with queuetrigger - missing job executions, no errors in logs, no log output at all even though queue is emptied

### ISSUE THREAD

**Issue by hallgeirl** [Azure/azure-functions-host#6242]
I am developing a function app that is fairly CPU intensive (doing conversions of various file formats into PDF). This app has a queue trigger, where the queue message contains information about which file to convert, and where to store it. 

As part of debugging this, I have reduced batch size to 2, and newBatchThreshold to 1. 
When I populate the queue with items for files to convert (I'm adding about 40 items as a test), here's what happens:
1. Queue and blob storage with source files are populated correctly. Files exist in the source blob storage, and queue items has the correct metadata.
2. Fairly quickly, the queue is emptied completely. Batch size seems to be respected, since two items are disappearing at once. In perhaps half a minute, all 40 items are not shown in the queue. In Azure Storage Explorer, I can see "Showing 0 of 40 messages in queue". So I expect the items have been picked up, but not yet finished processing, since they still ARE there, but not visible.
3. In Azure App Insights live metrics, I do see instances of the function showing up, and they SEEM to do something based on CPU usage (although I don't know if that's just the "warmup" CPU usage).  So far, everything LOOKS fine. **However, now the weird behavior begins to show.**
4. I monitor logs while I start the conversions (the "Monitor" tab for the function). Here I see log output from perhaps 2-3 out of 40 executions(!). And for those executions, I can only see SOME logs. Sometimes, I don't see the first log entry. Sometimes, I don't see what's logged in the middle of the execution, but I see the end log entry. The number of how many items I see logs for, varies for each test. So I'm missing log output for the rest (38 or so) runs. Sometimes, I start seeing some log output for some items perhaps 10-20 minutes AFTER the run was started and the queue was picked up. But I never see ALL items logged here. We might see maybe 2-3 more items being logged over the next half hour or hour. Maybe. And these logs are also incomplete. However I do see the log entries being complete if I do a search in App Insights. But I still only see 5-7 items perhaps, of the 40.
5. The queue is still, after 30 minutes, containing perhaps 35 items. I see output files for those jobs that HAVE run, which by now perhaps are 5-7 items. 
6. Eventually, given enough time the jobs are moved into the poison queue. I cannot find any information about WHY, but I have to assume they time out. Which is strange since the typical job runs for 6-10 seconds, if it runs at all.
7. Before the actual conversion starts, I do log a custom event to app insights. This is logged for the 5-7 jobs that seem to actually start, but not the rest. I see that perhaps 4 of those jobs are actually completed, with the "conversion completed" message and event, which I also log.

So after the initial first few jobs that are run, the rest of the jobs seem to disappear into the void. Some might seem to be stuck (since they log the start of the conversion, but not the end). Some others doesn't have ANY output. 

If I make the function crash intentionally, before the conversion starts, then everything works fine (i.e., I see in the error logs that the app crashed, and files are almost immediately moved to the poison queue).

One more thing I have tried is just queuing a SINGLE job... That sometimes works, sometimes not. Sometimes it's executed, other times there's NO log output at all.

Also, when running locally, everything seems to work exactly as I would expect. THe whole queue is not dequeued at once, and it's processing items two at a time, and correctly saving the output.

Here's some of my hypotheses:
1. Jobs are simply hung, i.e. problem in our code. BUT; if this is the case, I don't see why ALL the queue items are actually picked up (seemingly) but not executed. Or are jobs picked up by the functions runtime long before they are actually executed?
2. The jobs are slow, so it can take time to finish them. BUT, I only see a maximum run time of about 10-11 seconds for those that complete. So either they complete in 11 seconds or less, or they don't complete at all.
3. Function instances run out of memory and crash somehow. BUT, I never see memory usage above 400-500MB looking at LIve Metrics in App Insights. AND, I reduced the batch size to 2 - so only 2 items should be run at a time on the function host, right? Before, I used a batch size of 16. It behaved more or less the same way. 
4. There's a bug in the runtime that prevents the jobs from running (perhaps the runtime crashes after it has dequeued the items?)

#### Investigative information

Please provide the following:

- Timestamp: 09:00 CEST 18.06.2020
- Function App version: v3
- Function App name: hallgeir-new-fc-dev
- Function name(s) (as appropriate): ProcessFileConversion 
- Invocation ID: Unknown
- Region: North Europe

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

I would expect that items that are dequeued from the job queue, are in fact logged and executed. It seems that items that are dequeued are NOT always executed. 

I also would expect the log output in the "Monitoring" tab on the function itself would show the complete log output.

And, I would expect that if a function fails due to some condition (e.g. out of memory, or timed out, or anything) I should see a log entry somewhere.

#### Actual behavior

Jobs that are dequeued are not always run (if looking at the logs).

The Monitoring tab for the function does not show the complete log - just fragments of a small selection of the logs.

Jobs disappear / are moved into the poison queue without any logging.

#### Related information 

Provide any related information 

* Programming language used: C# / dotnet core 3.1
* Links to source: Not public unfortunately but attached a snippet of the outer function itself in below.
* Bindings used: QueueTrigger, IBinder to get source and target blobs.
<details>
<summary>Source</summary>
Here's the function (very much work in progress):

```

        [FunctionName("ProcessFileConversion")]
        public void Run([QueueTrigger("conversion-queue", Connection = "FormatConverterStorageConnectionString")] JobQueueMessage queueItem, IBinder binder, ILogger log)
        {
            try
            {
                Stopwatch sw = new Stopwatch();
                sw.Start();

                log.LogInformation($"Starting conversion of: {queueItem.Source} for tenant: {queueItem.Tenant}. Output path: {queueItem.Target}");

                if (Path.GetExtension(queueItem.Target).ToLowerInvariant() != ".pdf")
                {
                    var msg = "Target file must have a PDF file extension. Actual filename: " + queueItem.Target;
                    log.LogError(msg);
                    return;
                }
                telemetryClient.TrackEvent("FormatConversionStart");
                var sourceBlob = binder.Bind<CloudAppendBlob>(new BlobAttribute(queueItem.Source, FileAccess.Read));
                PerformConversion(queueItem, binder, log, sourceBlob);
                sw.Stop();

                TrackConversionCompleted(queueItem, sw.ElapsedMilliseconds);
                log.LogInformation($"Conversion of {queueItem.Source} completed. Time taken: " + sw.ElapsedMilliseconds);

            }
            catch (Exception ex)
            {
                log.LogError($"Conversion failed. Exception: {ex.ToString()}");
            }
        }

```

And here's the host.json. 
```

{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingExcludedTypes": "Request",
            "enableLiveMetrics": true,
            "enableDependencyTracking": true,
            "samplingSettings": {
                "isEnabled": true
            }
        }
    },
    "extensions": {
        "queues": {
            "maxPollingInterval": "00:00:02",
            "visibilityTimeout": "00:00:05",
            "batchSize": 2,
            "newBatchThreshold": 1,
            "maxDequeueCount": 3
        }
    }
}

```
</details>

**Comment by hallgeirl** [comment]
I just tested EXACTLY the same workload on Azure Functions on Windows - which I set up exactly the same, apart from changing the OS (same host.json, same code, same app settings). That works perfectly well - I see the items are chewed through at a reasonable pace and output are being generated for all jobs.

This must be some odd behavior that only affects Linux function apps...

**Comment by v-bbalaiagar** [comment]
Hi @hallgeirl, Can we know if you are seeing this issue still and requires further follow up.

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
