### ISSUE TITLE
HTTP and Timer triggers stopped to trigger function after 2020-06-18 11:50:00.006

### ISSUE THREAD

**Issue by bessgeor** [Azure/azure-functions-host#6243]
#### Investigative information

- Function App version: latest
- Function App name: tasker-timer
- Function name(s) (as appropriate): tasker_timer (Timer), tasker_callback (HTTP)
- Invocation ID: the issue is in the lack of invocations.
 - Last timer invocation: fd72ca0fca2db64a92822d6089b8d88b (2020-06-18 11:50:00.006)
 - Last HTTP invocation: 38dae7eec690f34199e2e01a4f80571a (2020-06-18 08:57:34.002)
- Region: West Europe

#### Repro steps

Provide the steps required to reproduce the problem:
For timer function, do nothing
For HTTP function, send a request which mimic [telegram API](https://core.telegram.org/bots/api#getting-updates) to function url or use @tasker_timer_bot command `/wuzzup@tasker_timer_bot`. Or just send any request.

#### Expected behavior
For timer function (cron description `0 */1 * * * *`), get an execution every minute
For HTTP function get an execution on request, responding 500 and logging error if request is not in expected Telegram format

#### Actual behavior
No execution occurs (no errors are logged, no messages are sent, no callback to telegram services occurs, 503 on GET request)

#### Known workarounds
Issue still exists. I tried to restart both functions twice, which had no effect

#### Related information 

* Programming language used: C#
* Plan: Consumption (Linux)
* No `WEBSITE_TIME_ZONE` was set intentionally
* No source code is published to provide a link and it's too big to paste here. I believe that this is not application level problem, but I may publish sources if requested
* Azure diagnostics report screenshot is attached below
![Azure diagnostics report screenshot](https://user-images.githubusercontent.com/2414765/85026649-9829df80-b181-11ea-9a42-7578165d0d7d.png)

**Comment by brettsam** [comment]
I can see that the timer stopped firing roughly 3 hours ago (last invocation was 2020-06-18 11:51:02.3630333 UTC) and that calls to your Http trigger are all returning 503s. 

@balag0 / @divyagandhii -- this is Linux consumption app that seems to be getting 503s right now. Is there a recommendation for how to get this running again?

**Comment by bessgeor** [comment]
Seems like both triggers resumed their work about 2020-06-18 23:16:34.3094197 UTC (invocation ID `1c634aca-9b11-43f9-baeb-f43feaed23ca`)

**Comment by bessgeor** [comment]
OK, confirmed, both triggers are working now.
Thank you, if you're the ones who stand behind it.
@brettsam, leaving this issue opened for further investigation if needed, feel free to close it.

**Comment by balag0** [comment]
This was due to an outage in West Europe yesterday. The issue should be mitigated now. Please reactivate if you have any questions or if you are still seeing any issue.
