### ISSUE TITLE
429 error on Linux function app deployment

### ISSUE THREAD

**Issue by CharlesAtDCube** [Azure/azure-functions-host#6244]
When trying to create a new function app, from the azure portal UI, the deployment freezes and runs into a 429 error, while trying to invoke the new consumption plan.

#### Investigative information

Please provide the following:

- Timestamp: 6/18/2020, 5:29:18 PM
- Function App version: Python, 3.7
- Deployment correlation ID : 233a9e1b-6f08-49ed-8bae-94e32e0317b7
- Operation ID : /subscriptions/9f8c1618-a70d-4a1c-ba80-4112c282a26f/resourceGroups/sandbox/providers/Microsoft.Resources/deployments/Microsoft.Web-FunctionApp-Portal-8c76a280-8bdd/operations/3C3AE23B174B6B1A
- Region: West Europe

I cannot provide you with the invocation ID since the problem concerns the invocation itself.

#### Repro steps

1. Go to azure portal
2. Create new function app
3. Select Python
4. Select 3.7
5. Select West Europe
6. Select new storage account
7. Select Consumption (Serveless)
8. Select any option for log analytics

#### Expected behavior

When I pass the validation, and create the resource, it should ... create the resource.

#### Actual behavior

Instead the deployment freezes on the ASP Microsoft.Web/serverfarms aprt, with a 429 error
```
status message : {
    "Code": "429",
    "Message": "Cannot acquire exclusive lock to create or update this server farm. Retry the request later.",
    "Target": null,
    "Details": [
        {
            "Message": "Cannot acquire exclusive lock to create or update this server farm. Retry the request later."
        },
        {
            "Code": "429"
        },
        {
            "ErrorEntity": {
                "ExtendedCode": "59207",
                "MessageTemplate": "Cannot acquire exclusive lock to create or update this server farm. Retry the request later.",
                "Parameters": [],
                "Code": "429",
                "Message": "Cannot acquire exclusive lock to create or update this server farm. Retry the request later."
            }
        }
    ],
    "Innererror": null
}
```

**Comment by mhoeger** [comment]
Hey @CharlesAtDCube - checking in with some of our sister teams to see what might have gone wrong... Sorry for the delay. Have you been able to deploy since then? Was it a transient issue?

Thanks!
