### ISSUE TITLE
Could not load file or assembly 'Microsoft.AspNetCore.Razor.Language, Version=3.1.2.0...

### ISSUE THREAD

**Issue by unt1tled** [Azure/azure-functions-host#6246]
I'm attempting to make an Azure Functions based emailer using a [Razor Class Library (RCL)](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0) with .Net Core 3.1: 

![image](https://user-images.githubusercontent.com/5357052/77119437-d2fa6b00-6a0c-11ea-9502-2cfacd411d84.png)

However, while using the [latest release](https://github.com/Azure/azure-functions-core-tools/tree/3.0.2358), my functions app fails to find the Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation library, even though it's been referenced in my nuget packages. It attempts to load this from the Azure Function Tools cli directory:

![image](https://user-images.githubusercontent.com/5357052/77118219-17383c00-6a0a-11ea-9800-acc60e45f99c.png)

Is there a work-around to force my project find this package?

Sample project attached:
[RazorFunctionsApp.zip](https://github.com/Azure/azure-functions-core-tools/files/4357096/RazorFunctionsApp.zip)

**Comment by anthonychu** [comment]
@fabiocav I tried adding `<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>` to the csproj and it didn't fix the problem. Can you take a look?

**Comment by fabiocav** [comment]
Closing this issue as stale. If you continue to experience similar problems in 4.0, please open a different issue and we'll take a closer look.
