### ISSUE TITLE
00:30 min timeout exceeded, stuck in retry loop?

### ISSUE THREAD

**Issue by SeaDude** [Azure/azure-functions-host#6247]
# Investigative information

Hello,

I was receiving memory errors on the Linux Consumption Plan when trying to move blobs of ~50MB and larger (#6237) so I upgraded to an EP2 SKU. This worked for getting me over 50MB, but the process is now timing out on blobs ~500MB and stuck in a retry loop (each retry costing me $).

If a 500MB blob takes ~3-4 mins to upload to a storage account, what would cause my function to run longer than 30 mins to process it?

I need to understand what I can do to make my python function handle larger workloads without erroring out. I don't want to just up the timeout threshhold, because what happens when I want to move 1GB file? Will it take all day?

Thanks for the insights.

Please provide the following:

- Timestamp: 2020-06-19 16:49:54.634
- Function App version: 2.0
- Function App name: fa06192020test7
- Function name(s) (as appropriate): n/a
- Invocation ID: 27002a504e785f439f5abcb28b2fae89
- Region: westus

#### Repro steps
- Upload ~500MB blob to storage container
- Function App triggers
- Exception: "00:30 min timeout..."

#### Expected behavior

- Function App would process blob as expected

Provide a description of the expected behavior.

#### Actual behavior

- Error as described

#### Known workarounds

N/A

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by balag0** [comment]
I haven't looked through the logs yet, but from the issue description it sounds like the bottleneck is the blob upload from the function to storage. The upload is taking so long that the over all function execution times out. Is my understanding correct?

(Trying to make sure this is not due to the function code or the amount of memory used by the function app)

**Comment by SeaDude** [comment]
Hi @balag0 , 

The Function does not upload a blob. 

**The sequence is:**

Someone uploads blob to storage-->Triggers Function--------------->Function runs--->Function PUT's blob to an external source
|--Takes ~3mins to upload                 |--I see the trigger in the logs  |--30min timeout  |--Does not complete.

**Comment by SeaDude** [comment]
I'd appreciate it if you could look through the logs and reply here with your findings.

**Comment by AartBluestoke** [comment]
if you use an app service host, rather than a consumption plan, you can set the timeout to as many hours as you want (or "never timeout", but i wouldn't recommend that as you want to recover from a hung process eventually)
