### ISSUE TITLE
Ensure ARM host status call returns the same information that the admin status API on the runtime site returns

### ISSUE THREAD

**Issue by apawast** [Azure/azure-functions-host#6254]
We’ve been seeing some customers complaining that we’re not bubbling up enough as much information to them as we used to in the old portal. Our new APIs are not returning the same level of details.

**Comment by fabiocav** [comment]
@mathewc FYI. This is something that has been raised for the next sprint.

**Comment by mathewc** [comment]
The ARM API ([here](https://msazure.visualstudio.com/One/_git/AAPT-Antares-Websites?path=%2Fsrc%2FHosting%2FAdministrationService%2FMicrosoft.Web.Hosting.Administration.Csm.Common%2FHelpers%2FCsmFunctionsManager.cs&version=GBdev&line=372&lineEnd=373&lineStartColumn=1&lineEndColumn=1&lineStyle=plain)) returns whatever the host admin API returns, based on the [HostStatus](https://msazure.visualstudio.com/One/_git/AAPT-Antares-Websites?path=%2Fsrc%2FHosting%2FAdministrationService%2FMicrosoft.Web.Hosting.Administration.Api%2FWebEntities%2FKudu%2FHostStatus.cs&version=GBdev&line=20&lineEnd=21&lineStartColumn=1&lineEndColumn=1&lineStyle=plain) model type.

In the case of errors, the HostStatus.Errors collection is populated based on ScriptHostManager.LastError (code [here](https://github.com/Azure/azure-functions-host/blob/eac1673a597571783f54359cf566281cff322e73/src/WebJobs.Script.WebHost/Controllers/HostController.cs#L91)).

So first I'd verify that errors are being returned correctly by the host via that channel. If they are, then verify that by invoking the ARM API directly you're also seeing them.

**Comment by fabiocav** [comment]
@brettsam did you have an issue tracking this against the portal?

**Comment by mathewc** [comment]
I just did a simple test myself in production for my app. I made my host.json file unparsable, and verified that both the portal and the ARM API return the error. So I'm not seeing a problem here. Can you guys give me some repro steps for the issue you're seeing?

**Comment by mathewc** [comment]
Resolving this since the APIs do in fact return the same info, since the ARM API is just invokes the host API. If you find evidence to the contrary, please reopen this. Related issue https://github.com/Azure/azure-functions-host/issues/6255 remains open and is what we want to focus on.
