### ISSUE TITLE
Using appsettings.json + IConfiguration in a Function app, take 2

### ISSUE THREAD

**Issue by IanKemp** [Azure/azure-functions-host#6256]
Follows on from #4464, in which [this feature was promised](https://github.com/Azure/azure-functions-host/issues/4464#issuecomment-511590422) but then the issue was closed.

It seems like the most correct way to achieve this functionality (correct = it doesn't clobber `IConfiguration`) is with the following code, amalgamated from the above issue:

```csharp
public override void Configure(IFunctionsHostBuilder builder)
{
    ...

    var options = builder.Services.BuildServiceProvider().GetService<IOptions<ExecutionContextOptions>>().Value;
    var configuration = new ConfigurationBuilder()
        .SetBasePath(options.AppDirectory)
        .AddJsonFile($"appsettings.{Environment.GetEnvironmentVariable("AZURE_FUNCTIONS_ENVIRONMENT")}.json")
        .AddEnvironmentVariables()
        .Build();

    ...

    builder.Services.Configure<MyOptionsClass>(configuration.GetSection("MyAppSettingsJsonOptionsSection"));

    ...
}
```

and then use the options as normal:

```csharp
public class MyService
{
    public MyService(IOptions<MyOptionsClass> options) {  }
}
```

Questions:

1. Is this indeed the best way to use additional JSON configuration files? My concern is mainly around manually building an `IServiceProvider` and getting services from it, which I know is discouraged in ASP.NET because all services may not be setup yet - is this true in Azure Functions too, or is this approach safe?
2. Is a less painful way to achieve this (e.g. a one-liner like `builder.Services.AddAppSettingsJson()`) something that is desirable in the Azure Functions host? If so, are there any plans to add it?

**Comment by fabiocav** [comment]
@IanKemp this is a feature that is going live with the current deployment. For more information, please follow this issue: https://github.com/Azure/azure-functions-host/issues/4761
