### ISSUE TITLE
Cannot v3 Function use 'net core 3.1' if we specified it in TargetFramework of 'function.proj'.

### ISSUE THREAD

**Issue by makokui** [Azure/azure-functions-host#6260]
#### Is your question related to a specific version? If so, please specify:
Function Host Version: 3.0.13353.0
Platform: Windows
Hosting Plan: Consumption Plan
Trigger: Http Trigger

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C# Script

#### Question
I am not sure this is bug or not, so I post as general question.
The Function can only uses netstandard2.0 when we use 'function.proj'. Is this a expected behavior?

We are creating V3 Function with following steps and run, then we can see the error.
2020-06-03T11:12:47.769 [Error] run.csx(8,7): error CS0246: The type or namespace name 'Renci' could not be found (are you missing a using directive or an assembly reference?)

- Repro step
Use Azure Portal for all operations (Not using Developer tool like Visual Studio Code.)
1. Create V3 Function with below parameters.
   Publish: Code
   Runtime stack: .NET Core
   Version 3.1
   Region: Japan East (I think any region can repro.)
2. Create HTTP Trigger.
3. Open App Service Editor from Azure Portal.
4. Create 'HTTP Trigger\function.proj' file and update with below.
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Renci.SshNet.Async" Version="1.4.0" />
    </ItemGroup>
</Project>
```

5. Update 'HTTP Trigger\run.csx' file with below.
```
#r "Newtonsoft.Json"
using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Newtonsoft.Json;

using Renci.SshNet;   // only add here.

public static async Task<IActionResult> Run(HttpRequest req, ILogger log)
{
    log.LogInformation("C# HTTP trigger function processed a request.");
    string name = req.Query["name"];
    string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
    dynamic data = JsonConvert.DeserializeObject(requestBody);
    name = name ?? data?.name;
    return name != null
        ? (ActionResult)new OkObjectResult($"Hello, {name}")
        : new BadRequestObjectResult("Please pass a name on the query string or in the request body");
}
```
6. Run function, then the function returns 500 error.
We can see the function log from Kudu site.
```
D:\home\LogFiles\Application\Functions\Function\HttpTrigger1>cat 2020-06-03T11-12-47Z-655a66c92d.log
2020-06-03T11:12:47.500 [Information] Executing 'Functions.HttpTrigger1' (Reason='This function was programmatically called via the host APIs.', Id=08b1421a-0de7-4a48-9bd0-8424c6d14c0b)
2020-06-03T11:12:47.545 [Error] Function compilation error
Microsoft.CodeAnalysis.Scripting.CompilationErrorException : Script compilation failed.
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.CreateFunctionTarget(CancellationToken cancellationToken) at D:\a\1\s\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 314
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionLoader`1.GetFunctionTargetAsync[T](Int32 attemptCount) at D:\a\1\s\src\WebJobs.Script\Description\FunctionLoader.cs : 55
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.GetFunctionTargetAsync(Boolean isInvocation) at D:\a\1\s\src\WebJobs.Script\Description\DotNet\DotNetFunctionInvoker.cs : 183
2020-06-03T11:12:47.769 [Error] run.csx(8,7): error CS0246: The type or namespace name 'Renci' could not be found (are you missing a using directive or an assembly reference?)
2020-06-03T11:12:47.852 [Error] Executed 'Functions.HttpTrigger1' (Failed, Id=08b1421a-0de7-4a48-9bd0-8424c6d14c0b)
Script compilation failed.
```
 
 
- Workaround
Use V2 Function with following 'fuction.proj' file. The point is to specify 'netstandard2.0' on 'TargetFramework' Tag.
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Renci.SshNet.Async" Version="1.4.0" />
    </ItemGroup>
</Project>
```
 
 
- Ask
In my understanding, the function calls 'dotnet restore' when the function first start and create 'project.assets.json'. After that the Function runtime only read 'project.assets.json' which was specified 'netstandard2.0'. So if we use 'netcoreapp3.1', reference error is occures.
Ref. https://github.com/Azure/azure-functions-host/blob/master/src/WebJobs.Script/Description/DotNet/PackageAssemblyResolver.cs#L67
```
                    var target = lockFile.Targets
                        .FirstOrDefault(t => string.Equals(t.TargetFramework.DotNetFrameworkName, FrameworkConstants.CommonFrameworks.NetStandard20.DotNetFrameworkName));
```

Is this a expected behavior? Do you have plan for improvement for using 'netcore3.1'?

**Comment by FinVamp1** [comment]
For C# Scripts Functions we are recommending that you target .Net Standard 2.0 in the Function.proj.
This ensures that you are generating a .Net Standard 2.0 class library.

If you change the Target Framework to netcoreapp3.1 then you are saying build this Function app as a .Net Core Library.
To do this we also need you to specify the AzureFunctionsVersion so that we are building out the right dependency tree.
E.G 

If I want to run this a v3 .NET Core class library for v3 then I need to change the Function.proj to add this in so we parse the dependencies directly. 

> <Project Sdk="Microsoft.NET.Sdk">
>     <PropertyGroup>
>         <TargetFramework>netcoreapp3.1</TargetFramework>
>         <AzureFunctionsVersion>v3</AzureFunctionsVersion>
>     </PropertyGroup>
> 
>     <ItemGroup>
>         <PackageReference Include="Renci.SshNet.Async" Version="1.4.0" />
>     </ItemGroup>
> </Project>

When I do this everything is restored correctly.

**Comment by FinVamp1** [comment]
Dependency resolution for CSX will target .NET Standard 2.0. For netcoreapp3.1, the recommendation is to use precompiled projects.
