### ISSUE TITLE
functionTimeout in hosts.json not recognized by runtime ~3

### ISSUE THREAD

**Issue by lakshmanav** [Azure/azure-functions-host#6276]
With below mentioned host.json, we see that function timeout is set to default of 30 mins. Some of our workflows run beyond 30 mins. This was working in runtime ~2. Also by checking the logs from host startup, there is no way to see the timeout value picked by the runtime. Is it logged ? 

{
  "version": "2.0",
  "functionTimeout": "02:00:00",
  "logging": {
    "logLevel": {
      "Default": "Debug"
    }
  }
}

#### Check for a solution in the Azure portal

After a thorough walk-through of all the options available in azure diagnostics dashboard, I couldn't auto heal the behavior. Adding the results of function app downtime report for reference. 

Function(by failure rate) | Total Executions | Failure Rate(%) | Top Exception
-- | -- | -- | --
StartStopContainerRequestProcessor | 61 | 4.92% | Type : Microsoft.Azure.WebJobs.Host.FunctionTimeoutExceptionTotal Count : 3Message : Timeout value of 00:30:00 was exceeded by function: StartStopContainerRequestProcessor
CreateRequestPostProcessor | 22 | 4.55% | Type : Microsoft.Azure.WebJobs.Host.FunctionTimeoutExceptionTotal Count : 1Message : Timeout value of 00:30:00 was exceeded by function: CreateRequestPostProcessor
CreateRequestApplicationPostProcessor | 23 | 4.35% | Type : Microsoft.Azure.WebJobs.Host.FunctionTimeoutExceptionTotal Count : 1Message : Timeout value of 00:30:00 was exceeded by function: CreateRequestApplicationPostProcessor

#### Investigative information

Please provide the following:

- Timestamp: 6/25/2020, 3:22:36.463 PM, 6/25/2020, 9:39:35.790 PM, 6/25/2020, 11:28:54.715 AM, 6/25/2020, 8:25:39.132 AM
- Function App version: 3.0.13901.0
- Function App name: 2570edc2-7076-4540-baf7-4a446fc65247(app id)
- Function name(s) (as appropriate): StartStopContainerRequestProcessor, CreateRequestPostProcessor, CreateRequestApplicationPostProcessor
- Invocation ID: 57a202608761c9458883324d9ce54d98
- Region: westeurope

#### Repro steps

1. Add below configuration to host.json of the function app
{
  "version": "2.0",
  "functionTimeout": "02:00:00",
    "Console": {
      "LogLevel": {
        "Default": "Debug"
      }
    }
}
2. Run a function with execution time more than 30 minutes
3. Function app host will shutdown and we receive function app timeout exception

#### Expected behavior

Timeout only when execution time of any function is more than 2 hours. This was working in function app runtime ~2. We upgraded to runtime ~3, from then on we have this issue

#### Actual behavior

One of the function with execution time more than 30 minutes, brings down execution of all functions as the host shuts down with Microsoft.Azure.WebJobs.Host.FunctionTimeoutException

#### Known workarounds

No workaround available as many of our workflows run more than 30 minutes. 

#### Related information 

Provide any related information 

Programming language used = C#
Bindings used = Http trigger, Queue

**Comment by yojagad** [comment]
@lakshmanav Could you please follow the template and provide us more information about your app so that we can take a deeper look at this?

**Comment by lakshmanav** [comment]
@yojagad , I have updated relevant details. Hope it helps.

We are currently blocked by this issue in production after the upgrade from runtime ~2 to ~3. Any help on this is much appreciated and more valuable.

After go live, we see timeout incidents at-least 3 times a day which interrupts other functions that are executing and puts them on an inconsistent state.

**Comment by lakshmanav** [comment]
Trying to followup as we are blocked because of this in production

**Comment by lakshmanav** [comment]
Any updates on this that can help us @yojagad  ?

**Comment by yojagad** [comment]
@lakshmanav  We're looking to see if some DI on your side is overriding the IConfiguration object. This could consequently, in some cases, result in functionTimeout not being picked up from host.json. https://github.com/Azure/azure-functions-host/issues/5685 . This could be something worth looking at on your side as well while we investigate this.

**Comment by yojagad** [comment]
@lakshmanav I haven't seen this happening since 07/02. Did you manage to fix whatever was causing the timeout to not be picked up ?

**Comment by jonathanantoine** [comment]
Hello,

Can we have an update on this ?

I still see this happening :(
