### ISSUE TITLE
Powershell Integration tests failing

### ISSUE THREAD

**Issue by vrdmr** [Azure/azure-functions-host#6279]
https://github.com/Azure/azure-functions-host/pull/6275/commits/66cbbe07d038c8d4c1cb537a69da6062686ccbdb

@Hazhzeng and I were trying to get the new Python hotfix deployed and were hitting this issue constantly. We had to skip it, but this needs investigation on why/what could be causing it and how to fix it.

FYI @AnatoliB, @Francisco-Gamino.

/cc @fabiocav

**Comment by Francisco-Gamino** [comment]
Hello @AnatoliB -- Could you please take a look? If not cannot get to this, I will take a look after Monday.

**Comment by AnatoliB** [comment]
PowerShell worker for Functions v2 requires .NET Core 2.2. But the test machine does not have .NET Core 2.2 anymore:
```
The framework 'Microsoft.NETCore.App', version '2.2.0' was not found.
It was not possible to find any compatible framework version
  - The following frameworks were found:
      1.0.16 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.13 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      ...
      2.1.19 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      ...
      3.1.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.2.0&arch=x64&rid=win10-x64
```
As a result, the worker fails to start.

The dependency on .NET Core 2.2 is intentional. Even though it reached end-of-life, upgrading it to 3.* would be a breaking change that we didn't want to take for Functions v2.

**Comment by Francisco-Gamino** [comment]
This issue has been fixed.
