### ISSUE TITLE
 Consumption plan azure functions certificate not found issue 

### ISSUE THREAD

**Issue by caroe2014** [Azure/azure-functions-host#6286]
I haven a customer who has issue this issue as well.

He has a Function App in consumption and has unsuccessfully tried to use a certificate public certificate.

This was has been tried:

Function App on Premium
Create a Premium Linux Python 3.8 app
Upload any cert into TLS/SSL Settings->Public Key Certificates
Go into Kudu:
cd /var/ssl/certs -> ls -la
Result: Find the certificate

Function App on consumption
Create a  Linux Python 3.8 app
Upload any cert into TLS/SSL Settings->Public Key Certificates
Result: certificate not found
Since Kudu is not enabled on this SKU it s necessary to write a simple python function to list the files in the same folder, here is one example that could be used to look for the certificate:

import azure.functions as func
import logging
import os
SSL_FOLDER1 = "/var/ssl"
logging.info(' -------------- START, recursive from /var/ssl, list all CERTS ----------------- ')
// r=>root, d=>directories, f=>files
for path,subdir,files in os.walk(SSL_FOLDER1):
for name in files:
if ".der" in name or ".crt" in name or ".pem" in name:
print(os.path.join(path,name)) # will print path of files
logging.info(' -----------   END, recursive /var/ssl, list all CERTS  -----------------')
The Variable WEBSITE_LOAD_CERTIFICATES = *

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version: v2
- Function App name: v-edcaroconsumption
- Function name(s) (as appropriate):
- Invocation ID:
- Region: East US

#### Repro steps

Function App on consumption
Create a  Linux Python 3.8 app
Upload any cert into TLS/SSL Settings->Public Key Certificates
Result: certificate not found
Since Kudu is not enabled on this SKU it s necessary to write a simple python function to list the files in the same folder, here is one example that could be used to look for the certificate:

import azure.functions as func
import logging
import os
SSL_FOLDER1 = "/var/ssl"
logging.info(' -------------- START, recursive from /var/ssl, list all CERTS ----------------- ')
// r=>root, d=>directories, f=>files
for path,subdir,files in os.walk(SSL_FOLDER1):
for name in files:
if ".der" in name or ".crt" in name or ".pem" in name:
print(os.path.join(path,name)) # will print path of files
logging.info(' -----------   END, recursive /var/ssl, list all CERTS  -----------------')

The Variable WEBSITE_LOAD_CERTIFICATES = *

Provide a description of the expected behavior.

Be able to use the certificate on Function App for Consumption.

Provide a description of the actual behavior observed.

The Certificate is to available in the Function App for Consumption 

#### Known workarounds

Due to the Function App for Consumption doesn't have Kudu, the customer created the program to verify if the Cetificate is install and it shows it is not installed.

#### Related information 

The customer used the following link: https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-certificate-in-code#load-certificate-in-linux-apps
we also followed the recommendation here: https://github.com/Azure/azure-functions-host/issues/2295

* Programming language used 
* Links to source
* Bindings used

**Comment by balag0** [comment]
Loading certificates is not supported on Linux consumption sku currently. I opened this issue for tracking
https://github.com/Azure/Azure-Functions/issues/1644

Please follow that issue for updates.
