### ISSUE TITLE
Create a cancellation notification for OOP workers

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#6287]
The function runtime should notify workers when a function cancellation token is signaled. The worker would have the ability to expose this information in a language specific way (e.g. `CancellationToken` for the .NET worker).

**Comment by nzthiago** [comment]
Related to [#2152](https://github.com/Azure/azure-functions-host/issues/2152)

**Comment by fabiocav** [comment]
Duplicate of #2152
