### ISSUE TITLE
New Azure Functions management experience log stream doesn't log everything

### ISSUE THREAD

**Issue by qfyra** [Azure/azure-functions-host#6302]
The "new Azure Functions management experience" log stream only logs some 30 rows, compared to the "classic experience" which logs everything. This issue is very easy to recreate, as per the instructions below. I've seen this issue across the board for all our functions for as long as the portal has defaulted to the new experience (some time in June 2020 I believe?) I just recreated the problem with a test function that I ran 2020-07-02T09:57:46Z, so the problem is still there.

#### Repro steps

1. Visual Studio 2019 16.6.3
2. Create new project > Azure Functions > Http trigger (authorization level Function)
3. Replace the Function1.cs code with the below. No other changes to the project.
```
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Extensions.Logging;
using System;
using System.Threading.Tasks;

namespace TestOfLogging
{
	public static class Function1
	{
		[FunctionName("Function1")]
		public static async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req, ILogger log)
		{
			for (int i = 0; i < 100; i++)
				log.LogInformation($"{i}: {Guid.NewGuid()}");

			return new OkObjectResult("done");
		}
	}
}
```

4. Publish to Azure (Windows, Consumption, Any CPU, netcoreapp3.1, Framework-dependent, Portable)
5. In Azure Portal, go to Log Stream. "Configure Application Insights to capture invocation logs" > Configure > Create new resource > OK
6. Go back to Log Stream > set Log Level: Information > keep this window open
7. Open new window, go to Azure Portal > "Switch to classic experience" > Platform features > Log streaming > keep this window open
8. Call the Function with e.g. postman

#### Expected behavior

The code above should print 100 lines of Guids in the Log Stream, like this: 

```
2020-07-02T09:57:46.205 [Information] 0: 8b196540-5377-455a-920e-8b31fdd9a6df
2020-07-02T09:57:46.205 [Information] 1: a5e87ad8-b151-4643-8fb1-71319a338198
2020-07-02T09:57:46.205 [Information] 2: 27e5ff2c-dafb-458b-86a4-bf8dff2aaef7
...
```

#### Actual behavior

The classic experience log stream prints all 100 lines. The new experience log stream prints guids 0-27.

![old-xp](https://user-images.githubusercontent.com/59998991/86346776-b271bc00-bc5d-11ea-8b5f-30c225b09b2d.png)

![new-xp](https://user-images.githubusercontent.com/59998991/86346723-9e2dbf00-bc5d-11ea-9106-b40086a2e5a8.png)

**Comment by balag0** [comment]
@ammanifold Would you know if this is customizable (or any other recommendations)?

**Comment by ammanifold** [comment]
We are going to be releasing an update that will let users switch to the filestreaming model

**Comment by pragnagopa** [comment]
Closing as this will be addressed in Ux update. @ammanifold - please link any Ux issues here if any.
