### ISSUE TITLE
Test functions against a APM v2.1 site

### ISSUE THREAD

**Issue by apawast** [Azure/azure-functions-host#6318]
There is no work for us to upgrade to APM v2.1, but we will need to test it once the work is done on the PIE team's end.

**Comment by fabiocav** [comment]
This is currently blocked on the work described above.

**Comment by brettsam** [comment]
Gave this a try yesterday with a workspace-based AI resource and all looked good from a logging standpoint. Found an issue in the portal UX that I've submitted internally to that team.

**Comment by brettsam** [comment]
Update -- I also validated this against a Linux app this week.
