### ISSUE TITLE
Add support for Enable attribute

### ISSUE THREAD

**Issue by Dzoukr** [Azure/azure-functions-host#6324]
#### What problem would the feature you're requesting solve? Please describe.
There is already existing attribute `Disable` which can be used on function / class level, however its switched logic (disabled only if explicitly said in configuration) is difficult for trunk-based development with feature toggles. Any new functions deployed on different environment (like production) are enabled by default, which can be dangerous.

#### Describe the solution you'd like
I'd like to have a new attribute `[Enable("config-key")]` introduced. When function annotated with this attribute, it's enabled *only if config-key set to true in configuration*. If attribute not used at all, the functionality remains as it is (so no breaking change).

#### Describe alternatives you've considered
Existing attribute `[Disable]` has an overload with `Type` parameter, however it's not supported on Azure functions (got error during build - https://github.com/Azure/azure-functions-vs-build-sdk/blob/1922f7d495a8089d8f3293e31dfbca1786e887b0/test/Microsoft.NET.Sdk.Functions.Generator.Tests/HasUnsupportedAttributesTests.cs). If this overload would be supported, I can implement own logic of making functions enabled only if key found in configuration.

**Comment by fabiocav** [comment]
There are a few ways to disable a function based on environment values that I believe would meet your requirement. Those are both documented here: https://docs.microsoft.com/en-us/azure/azure-functions/disable-function

The first approach, is based on an app setting following the format `AzureWebJobs.<FUNCTION_NAME>.Disabled`, which you can manage as described in the docs.

The other, is by using the `Disabled` attribute you've mentioned above, but passing a setting name into its constructor as described here: https://docs.microsoft.com/en-us/azure/azure-functions/disable-function#c-class-libraries

Please let us know if this doesn't meet your requirements, but based on what you've described above, I believe they will.

**Comment by Dzoukr** [comment]
Hi @fabiocav thanks for comment. I am not sure current functionality is sufficient. What I looking for is opt-in mechanism for enabling. In other words, if I set `[Disabled("notexisting")]` and key is not present at all, is function disabled or not? If not, that's opt-out which is dangerous for deploying same functionality to different stages.

That's why I wanted to have Enabled attribute.

**Comment by fabiocav** [comment]
I see. There are some options you could potentially follow with the configuration sources that would give you ability to dynamically enable functions, but one approach that exists today, although not recommended (in favor of what I've shared above) when running on Azure is the `functions` list in configuration/host.json: https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#functions

**Comment by Dzoukr** [comment]
🤔 That should work. Didn't know about this, thank you!
