### ISSUE TITLE
Creation of Function App failing - Unexpected InterServerError

### ISSUE THREAD

**Issue by dominiclapointe** [Azure/azure-functions-host#6331]
#### Investigative information
- Timestamp: 7/8/2020, 9:02:02 PM
- Function App version: n/a
- Function App name: n/a
- Function name(s) (as appropriate): n/a
- Invocation ID: n/a
- Region: East US

#### Repro steps
Create a new function app on Linux using .net core 3.1. 
Use an existing app service plan (Linux - F1). 
Select existing storage 
Select existing AppInsight.

#### Expected behavior
Function app is created

#### Actual behavior
After less than 3 seconds, the deployement get faulted with the error :
There was an unexpected InterServerError. Please try again later . x-ms-correlation-request-id: xxxxx

#### More information
I did try multiple time for the last few hours and it always results in the same results. The error is quite generic so almost impossible to spot the issue...

I can provider correlation-id, trackingID and deployement correlation ID if required. 

Thank you

**Comment by fabiocav** [comment]
Unable to repro this, so having a correlation ID, an app name a a region would help us narrow down what happened with this particular set of requests.

**Comment by dominiclapointe** [comment]
Hi @fabiocav, sorry for not providing them as i did know what was 'public' and what was 'private' as information. 

CorrelationId : 6ea9ec4d-c4b3-47cf-8614-8be969db1ee3
App Name : the provided name was 'uat-my-replication-consumer' but never been create
App Service Plan name : clientPortal
Region: East US
Operation name: 748B08942E3805FE

if you require any more information, let me know.

Thank you

**Comment by dominiclapointe** [comment]
I did retry a few time today and always the same issues : There was an unexpected InterServerError. Please try again later.

We did try on another subscription, i asked someone else to do it in case my user was the problem...

We successfully created multiple app service, appinsight, azure ServiceBus, azure SqlServer without any issues.

**Comment by balag0** [comment]
@dominiclapointe The app creation failed due to the following error

**64 Bit worker processes cannot be used for the site as the plan does not allow it. For more information on pricing and features, please see: https://aka.ms/appservicepricingdetails**

Let us know if you have any questions regarding this error message.
