### ISSUE TITLE
Blob Event Trigger success on python local machine but not invoked on deploy

### ISSUE THREAD

**Issue by humblemat810** [Azure/azure-functions-host#6334]
created blob event trigger on azure function app that automatically log file name and file size
python local machine working,
uploaded file to blob, event logged when debugged on local machine,
never invoked after clicking the deploy on vs code azure function extension
![azure_failure](https://user-images.githubusercontent.com/67593116/87052097-fe5ecb00-c232-11ea-95e1-6172d6cd9806.png)

the uploaded blob can be seen on web portal

import azure.functions as func

def main(myblob: func.InputStream):
    logging.info(f"Python blob trigger function processed blob \n"
                 f"Name: {myblob.name}\n"
                 f"Blob Size: {myblob.length} bytes")

{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "myblob",
      "type": "blobTrigger",
      "direction": "in",
      "path": "hello-container/{name}",
      "connection": "ldshelloworld_STORAGE"
    }
  ]
}

**Comment by humblemat810** [comment]
I found out that the tutorial forget to instruct the user to enable the slot settings, which are disabled by default
Recommendations :
either 
1.  the VS code should sync the app settings instead of leaving those settings unset.
or 
2.  Tutorial instruct the users to enable the slot settings

**Comment by alrod** [comment]
closed as the workaround was found
