### ISSUE TITLE
[Rpc]Expanding env variables needs to be called after worker path is hydrated.

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#6351]
Commit # 0f18eade4b28b8cdde9e6a63dd0b7d4d0a051329  added support to expand env vars specified in worker.config.json

Powershell worker:  specifies worker path as `"defaultWorkerPath":"%FUNCTIONS_WORKER_RUNTIME_VERSION%/Microsoft.Azure.Functions.PowerShellWorker.dll",`

When running in Azure,  `%FUNCTIONS_WORKER_RUNTIME_VERSION%` is set to `7.0`

so looking up worker path fails with:

System.IO.FileNotFoundException : File DefaultWorkerPath: D:\home\SiteExtensions\Functions\32bit\workers\powershell\7.0/Microsoft.Azure.Functions.PowerShellWorker.dll does not exist.
   at Microsoft.Azure.WebJobs.Script.Workers.WorkerDescription.ThrowIfFileNotExists(String inputFile,String paramName) at D:\a\1\s\src\WebJobs.Script\Workers\ProcessManagement\WorkerDescription.cs : 58
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcWorkerConfigFactory.AddProvider(String workerDir) at D:\a\1\s\src\WebJobs.Script\Workers\Rpc\Configuration\RpcWorkerConfigFactory.cs : 152

Fix:
Need to expand env vars after worker path is hydrated to ensure worker specific rules are applied before expanding env vars.

**Comment by pragnagopa** [comment]
Assigned to Sprint 79 as we need to take a hotfix for this issue.

cc @AnatoliB as FYI

**Comment by pragnagopa** [comment]
cc @Francisco-Gamino / @madelinegordon  - fyi - this is an example where nightly build would have caught the issue as soon as the commit when into host.

**Comment by AnatoliB** [comment]
This is a good fix, thank you, but do we know how FUNCTIONS_WORKER_RUNTIME_VERSION became `7.0`? It is supposed to be either `~7` or `~6`, otherwise placeholders will not work. Does this mean the powerShellVersion site config value was `7.0`?

**Comment by pragnagopa** [comment]
> Does this mean the powerShellVersion site config value was 7.0

Yes, This was a test app using site extension. Not consumption. Placeholder Id is not generated for this app.

@AnatoliB  - I verified  stacks: https://github.com/pragnagopa/azure-functions-supported-runtime-stacks/blob/master/WindowsFunctionsStacks.json#L278 , you are right, version should be set to ~7. Must be Ux issue. Can you please repro and follow up with Ux team?
