### ISSUE TITLE
Detect/Warn When Functions write unbound output for HTTP triggers

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#636]
See: https://github.com/Azure/azure-webjobs-sdk-script/issues/631

We should investigate and see if we can help by issuing helpful warnings if we can identify these common error cases.

**Comment by lindydonna** [comment]
For HTTP triggers, the right thing to do is clear (whereas for other triggers, it is much harder).

**Comment by fabiocav** [comment]
Closing stale issue.
