### ISSUE TITLE
Azure functions intermittently stop firing (Queue/Blob triggers)

### ISSUE THREAD

**Issue by patrickbadley** [Azure/azure-functions-host#6381]
This is a (near) duplicate of https://github.com/Azure/azure-functions-host/issues/3493 which @paulbatum and @fabiocav said to open a new issue.

I have several azure functions, some are BlobTriggers and some are QueueTriggers.  We are experiencing intermittent issues with both types where every few days, they'll stop picking up new blobs or queue messages.  I've tried several solutions with varying levels of success:
1. Restarting the function app via the azure portal (this often will pick up a couple new messages then get stuck again shortly after)
2. Go to the function in question > Monitor > logs tab and sometimes it magically starts spitting out logs and the messages get processed
3. Last resort, copy config settings from the app and run the function via visual studio on my machine which has been 100% successful so far, but far from ideal.

#### Investigative information

Please provide the following:

- Timestamp: 7/20/2020, 5:36:19.368 PM UTC
- Function App version: ~3 (3.0.13901.0)
- Function App name: demo-viewtnt-inmapping-functions
- Function name(s) (as appropriate): AdvancedShipNoticeToShipmentCreatedMessageMappingFunction
- Invocation ID: 23b09d0f-dcff-4358-91cb-348dd48e58de
- Region: Central US

*Note the timestamp and invocation id above is for a message that was stuck for over a day in the queue, but after executing workarounds 1 AND 2, the message got picked up and processed at that time.*

#### Repro steps

1. Publish a message to azure storage queue (I can provide more info on queue if needed)

#### Expected behavior

2. Queue Triggered function should trigger automatically without restarting function app, viewing live metrics, or running locally

#### Actual behavior

2. Messages are occasionally processed, but often messages pile up in the queue without getting processed

#### Known workarounds

1. Restarting the function app via the azure portal (this often will pick up a couple new messages then get stuck again shortly after)
2. Go to the function in question > Monitor > logs tab and sometimes it magically starts spitting out logs and the messages get processed
3. Last resort, copy config settings from the app and run the function via visual studio on my machine which has been 100% successful so far, but far from ideal.

#### Related information 

<details>
<summary>Source</summary>

```csharp
[assembly: FunctionsStartup(typeof(Startup))]
namespace VplView.TrackAndTrace.Inputs.Mapping.Functions
{
    public class AdvancedShipNoticeToShipmentCreatedMessageMappingFunction
    {
        private readonly IAdvancedShipNoticeToShipmentCreatedMessageMappingLogic _advancedShipNoticeToShipmentCreatedMessageMappingLogic;
        private readonly ILogger<AdvancedShipNoticeToShipmentCreatedMessageMappingFunction> _logger;

        public AdvancedShipNoticeToShipmentCreatedMessageMappingFunction(
            IAdvancedShipNoticeToShipmentCreatedMessageMappingLogic advancedShipNoticeToShipmentCreatedMessageMappingLogic,
            ILogger<AdvancedShipNoticeToShipmentCreatedMessageMappingFunction> logger)
        {
            _advancedShipNoticeToShipmentCreatedMessageMappingLogic = advancedShipNoticeToShipmentCreatedMessageMappingLogic;
            _logger = logger;
        }

        [FunctionName(nameof(AdvancedShipNoticeToShipmentCreatedMessageMappingFunction))]
        public async Task Run([QueueTrigger(QueueNames.AdvancedShipNoticeImported, Connection = "AzureWebJobsStorage")]AdvancedShipNoticeImportedMessage queueMessage)
        {
            _logger.LogInformation($"{nameof(AdvancedShipNoticeToShipmentCreatedMessageMappingFunction)} trigger function received: {JsonConvert.SerializeObject(queueMessage)}");

            var idList = queueMessage.AdvancedShipNoticeHeaderIds.Split(',', StringSplitOptions.RemoveEmptyEntries);

            foreach (var asnHeaderId in idList)
            {
                await _advancedShipNoticeToShipmentCreatedMessageMappingLogic.ProcessAdvanceShipNoticeHeader(Guid.Parse(asnHeaderId));
            }

            _logger.LogInformation($"{nameof(AdvancedShipNoticeToShipmentCreatedMessageMappingFunction)} trigger function completed: {queueMessage.CorrelationId}");
        }
    }
}
```
</details>

**Comment by patrickbadley** [comment]
@paulbatum and @fabiocav It doesn't look like this issue is getting any attention, You mentioned in another issue to log a new one, any chance you could look into this for us?

**Comment by fabiocav** [comment]
Apologies for the delay on this. We'll investigate the issue and follow up with additional questions or updates here.

**Comment by fabiocav** [comment]
Also, if you have access to support, I would recommend opening a support ticket since this is a production impacting issue. If you take that route, can you please share that ID here?

**Comment by patrickbadley** [comment]
> Also, if you have access to support, I would recommend opening a support ticket since this is a production impacting issue. If you take that route, can you please share that ID here?

Support Request ID: 120081024002920

Thanks!

**Comment by patrickbadley** [comment]
After working with Azure support they pointed out that our functions were hosted in a standard App Service Plan (I thought it was a consumption plan) and the "AlwaysOn" option was not checked for the Function App.  For now I have turned on the AlwaysOn option which appears to have resolved the issue.  We plan to switch the app service plan to consumption soon which we hope will also work.  For now I'll close this ticket.  Thank you!
