### ISSUE TITLE
Getting 'Number of initialized language workers exceeded:2 exceeded maxProcessCount: 1' error

### ISSUE THREAD

**Issue by artisticcheese** [Azure/azure-functions-host#6386]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app => `Platform features` => `Diagnose and solve problems` and the relevant dashboards before opening your issue.

#### Investigative information

Please provide the following:

- Timestamp:
7/20/2020 8:00:00 PM
- Function App version:
2.0.13900.0
- Function App name:
AppServicePlanFunction
- Function name(s) (as appropriate):
PopulateQueuewithTimer
- Invocation ID:
013cab32-0764-4b32-9c4b-8cf7535522dc
- Region:
EastUS

#### Repro steps

Provide the steps required to reproduce the problem:
Not reproducible at will, happened 10 times in last week

#### Related information 

Provide any related information 

* Programming language used 
Powershell
* Links to source
* Bindings used
Timer

![image](https://user-images.githubusercontent.com/13176884/87994903-b6059f80-cab3-11ea-9b87-cf8ef5c4ce85.png)
![image](https://user-images.githubusercontent.com/13176884/87994924-c289f800-cab3-11ea-90de-baa0c5589790.png)

**Comment by soninaren** [comment]
cc: @pragnagopa

**Comment by v-bbalaiagar** [comment]
Hi @artisticcheese, Can we know if you are seeing this issue still and requires further follow up.
