### ISSUE TITLE
[Custom handlers] Provide a way to inspect custom handler requests and responses

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-host#6388]
Log HTTP requests (methods and URLs only) at Debug level.

If possible, when running locally in Core Tools, also log the HTTP request and response payloads (request body, request/response headers).

@pragnagopa @yojagad @fabiocav

**Comment by pragnagopa** [comment]
Thanks for opening this issue. This is very useful when getting started and also to debug issue.

`Trace` level is more appropriate as Debug logs are for system logs. Also, turning on this log will have perf impact as every invocation will now write invocation payload to the logs.

**Comment by anthonychu** [comment]
Yep `Trace` works. Any thoughts on how we can safely do this for the payload without leaking PII and secrets?

**Comment by pragnagopa** [comment]
> Any thoughts on how we can safely do this for the payload without leaking PII and secrets?

These logs will be logged to user logs and user needs to turn on and turn them off explicitly.

**Comment by fabiocav** [comment]
Even if those go into AI only, logging the entire request could be potentially problematic. This is something customers can do from the handler if desired.

**Comment by anthonychu** [comment]
@fabiocav Is there a safe way to do this when running in core tools? I find it really helpful to see the payload easily when building handlers.

**Comment by fabiocav** [comment]
Yes, for local runs, this shouldn't be a problem and it is something we can easily detect.
