### ISSUE TITLE
[CustomHandler] Detectors for custom handlers

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#6392]
Tracking item to add following detectors:
- Process start up errors
- Any errors when host tries to communicate with custom handler endpoint 

cc @anthonychu @fabiocav

**Comment by pragnagopa** [comment]
@anthonychu - Same here. Pushing this out to sprint 84 to focus on higher priority items. Please let me know if there is a date to have this completed.

**Comment by pragnagopa** [comment]
cc @FinVamp1 

1. Added `customHanderProcessStartupErrors` detector - This will show any errors when starting custom hanlder process.
2. Added `customHandlerEndPointNotFoundErrors` detector - This will show errors if api / routes configured do not exist to handle function invocation.
3. Added `customHandlerInvalidResponseErrors` detector - This will show errors if customHandler does not return valid JSON response on function invocation

**Comment by FinVamp1** [comment]
@pragnagopa This is great thank you. Is there any text we could show if the customer does get these errors?

**Comment by pragnagopa** [comment]
@FinVamp1 - if starting custom handler process fails, invocations will end up timing out as there is no process to handle the invocations.

Will discuss with @yojagad  on what other scenarios we can add detectors for.

**Comment by pragnagopa** [comment]
@FinVamp1 - Added more detectors. I will close internal tracking item as well.
