### ISSUE TITLE
System.Data.SqlClient is not supported on this platform

### ISSUE THREAD

**Issue by AbodeSaafan** [Azure/azure-functions-host#6393]
In a functions extension (LAV2 extension), using the SqlClient library causes an error to be thrown: "System.Data.SqlClient is not supported on this platform". 

The repro for this bug is available with @soninaren . 

Workaround found: Placing the extension bundle bin folder in the root of the LA project seems to fix the problem.

**Comment by fabiocav** [comment]
Closing as resolved. There was an issue with the package deployed.

@yojagad and @soninaren can share the details if needed.
