### ISSUE TITLE
Dependency injection on .netcoreapp 3.1 and AzureFunctionsVersion v3 doesn't work when deployed

### ISSUE THREAD

**Issue by jtcc-ms** [Azure/azure-functions-host#6394]
Hello

We're trying to deploy a basic .net core 3.1 app. Dependency injection works when we debug locally, but getting this error when deployed to Azure:
Unable to resolve service for type 'FunctionApp2.ITest' while attempting to activate 'FunctionApp2.Function1'.

Is this a bug or are we doing something wrong?

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version:
- Function App name: jtcc-test
- Function name(s) (as appropriate): Function1
- Invocation ID:
- Region: West US 2

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a new .net core 3.1 Azure Functions project in Visual Studio
2. Publish the project to Azure (self-contained, win-x64)
3. Hit the http trigger endpoint

#### Expected behavior

After I perform step 3, I should get back http status code 200

#### Actual behavior

Step 3 returns error 500, and in application insights I see this exception:
Unable to resolve service for type 'FunctionApp2.ITest' while attempting to activate 'FunctionApp2.Function1'.

#### Related information 

Provide any related information 

<details>
<summary>Source</summary>

Code:

Startup.cs
```
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;

[assembly: FunctionsStartup(typeof(FunctionApp2.Startup))]

namespace FunctionApp2
{
    /// <summary>
    /// Configures services and the app's request pipeline
    /// </summary>
    public class Startup : FunctionsStartup
    {
        /// <summary>
        /// Configure Azure function
        /// </summary>
        /// <param name="builder">IFunctionHostBuilder</param>
        public override void Configure(IFunctionsHostBuilder builder)
        {            
            builder.Services.AddSingleton<ITest, Test>();
        }
    }
}
```

Test.cs
```
namespace FunctionApp2
{
    /// <summary>
    /// aaaaa
    /// </summary>
   public class Test : ITest
   {
   }
}
```

Function1.cs
```using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace FunctionApp2
{
    /// <summary>
    /// ssss
    /// </summary>
    public class Function1
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Function1"/> class.
        /// </summary>
        /// <param name="test">dsdsd</param>
        public Function1(ITest test)
        {
        }

        /// <summary>
        /// aaa
        /// </summary>
        /// <param name="req">aaafw</param>
        /// <param name="log">adaaf</param>
        /// <returns>aaaf</returns>
        [FunctionName("Function1")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            string name = req.Query["name"];

            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name = name ?? data?.name;

            string responseMessage = string.IsNullOrEmpty(name)
                ? "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."
                : $"Hello, {name}. This HTTP triggered function executed successfully.";

            return new OkObjectResult(responseMessage);
        }
    }
}
```
csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
      <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.9" />
      <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```
</details>

**Comment by jtcc-ms** [comment]
Can someone take a look?

**Comment by yojagad** [comment]
I'm taking a look at this. Will get back to you soon.

**Comment by yojagad** [comment]
@jtcc-ms I followed the exact same code that you posted but couldn't get a repro. Can you follow the template and share your function app details so that we can take a further look at this ?

**Comment by jtcc-ms** [comment]
Thanks @yojagad, I've updated the original description.

**Comment by yojagad** [comment]
I'm looking at the logs. The app failed to start up properly due to an error with WEBSITE_RUN_FROM_PACKAGE. I'm curious, how did you deploy this to your function app ? I used visual studio in my attempt to repro this.

**Comment by jtcc-ms** [comment]
I published it from Visual Studio 2019 by right-clicking on the project and selecting "Publish".

**Comment by jtcc-ms** [comment]
I just recreated a new publish profile and unchecking the "Run from package file (recommended)" option. Deployed and it worked. So it looks like the problem stems from running the app from a package file.

**Comment by jtcc-ms** [comment]
Actually, looks like the problem occurs when it's deployed as a self-contained app.

**Comment by yojagad** [comment]
I don't think this is supported today, and ideally this option needs to be hidden while publishing from visual studio. Opened an issue for the same. Feel free to reopen / post a new issue if you need anything else.
