### ISSUE TITLE
Add tests for more HttpTrigger scenarios

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-host#6398]
We recently had a regression where HttpTrigger functions were throwing exceptions if buffering related operations were done by the function code and "Content Typee" was not set to "application/json".

More info here -- https://github.com/Azure/azure-webjobs-sdk-extensions/issues/655

We need to add tests for these type of scenarios to avoid such issues.

**Comment by fabiocav** [comment]
@ankitkumarr should this be assigned to the next sprint?
