### ISSUE TITLE
Azure Functions in Consumption Plan with Timer Trigger Caused App Service Restart

### ISSUE THREAD

**Issue by phil-marino** [Azure/azure-functions-host#6400]
- Function App version: 3.0
- Region: East US 2
- Timestamp: 2020-07-22-13:40:00:022
- Invocation ID: 6BE2DE32-473E-4DB1-8308-F0886EE21C74 (next occurrence after a shutdown)
- Language: C#/.Net Core 3.1

We have a function app that leverages both regular and durable functions.  This function app is using a Consumption plan, since most of the functions only run a few times per day.  These are functions because of the asynchronous nature of their work, as well as the need to schedule them.

Some of these processes are also implemented as durable functions, since they may require user interaction.

We have a function that is timer-triggered every 10 minutes.  This function is designed to check to see if any of the processes that run have taken too long and require someone from production support to investigate.  The timer is set to fire every 10 minutes.

The issue is that every 60 to 70 minutes, the app service appears to restart.  I understand that there's not a single app service, since this is a consumption plan.  However, the problem is that the restart can occur while other functions are running, stopping these processes in the middle of their execution.

I have looked at #https://github.com/Azure/azure-functions-host/issues/4186.  I don't know if this is the same issue because of the Consumption plan.

There are no exceptions in App Insights or in the log streams.  I have set the logging to Verbose, and see the restart, but nothing that shows why the restart occurs.  I also see the shutdown message in the Event Log.  

This occurs in multiple environments, across different function apps.  Note that in one of our environments, the 10-minute timer trigger was disabled, and the issue was NOT happening.  When I enabled this function, the issue started happening.

Is there anything that we can do to help uncover the cause?

Alternatively, is there another approach for running a scheduled job every 10 minutes?  I've looked into having a singleton durable function that runs every 10 minutes (and restarting itself with ContinueAsNew).  The problem here is starting the orchestration; it needs to be done automatically, and a timer trigger does this.

We have an incident with Microsoft Azure support.  Currently, their recommendation is to move to a regular app service plan, instead of trying to find the root cause.  I'm disappointed in this response for several reasons; I would think Microsoft would like to know why this is happening, and this could result in an increase in overall cost.

**Comment by v-anvari** [comment]
Hi @phil-marino , Apologies for the delayed response, Kindly let us know if you are still facing this problem. If yes, we would like to check the backend logs. We would require the latest invocation id and timestamp during of the error
