### ISSUE TITLE
Getting sporadic failures to validate EventGridTrigger function webhook during event grid sub creations via ARM

### ISSUE THREAD

**Issue by gdodd1977** [Azure/azure-functions-host#6402]
I've noticed over the past week or so that I've been getting sporadic failures while creating event grid subs via ARM for functions that have EventGridTriggers. We haven't changed anything here in months and my understanding is that EventGridTrigger validation doesn't require any coding to validate like HttpTriggers used to. I'm wondering if there has been a change to the syntax used in ARM for this?

Arm Resource:

`{
      "name": "[concat(parameters('eventGridTopicName'), '/Microsoft.EventGrid/', 'NotifyOrchestrationStatusEvents')]",
      "type": "Microsoft.EventGrid/topics/providers/eventSubscriptions",
      "location": "[parameters('location')]",
      "apiVersion": "2019-06-01",
      "properties": {
        "destination": {
          "endpointType": "WebHook",
          "properties": {
            "endpointUrl": "[concat(variables('orchestrationNotificationFunctionUrl'), listKeys(resourceId('Microsoft.Web/sites/host/', parameters('orchestrationFunctionAppName'), 'default'),'2016-08-01').systemkeys.eventgrid_extension)]"
          }
        },
        "filter": {
          "includedEventTypes": [
          ]
        }
      },
      "dependsOn": []
    },`

Error being thrown:

Webhook validation handshake failed for https://fa-fulfillment-ticket-orchestration-dev.azurewebsites.net/runtime/webhooks/eventgrid. Http POST request retuned 2XX response with response body {"validationResponse":"CF4921B0-DD66-42. When a validation request is accepted without validation code in the response body, Http GET is expected on the validation url included in the validation event(within 10 minutes). For troublehooting, visit https://aka.ms/esvalidation. Activity id:c851ea57-8cd0-42a6-b7b8-3e8ae887a431, timestamp: 7/22/2020 6:53:58 PM (UTC).

**Comment by madelinegordon** [comment]
Hello, you are correct - no custom code is required for validating HttpTriggers. Would you be able to provide your ARM template? How often is this failure occurring? Thank you.
