### ISSUE TITLE
`Microsoft.Azure.WebJobs.Extensions.ServiceBus` package v3.* and v4.* compatibility issue

### ISSUE THREAD

**Issue by myarotskaya** [Azure/azure-functions-host#6406]
**Azure Functions Runtime:** v3

**Language:** C#

**Setup:** 
- There is a message in the Service Bus topic that was sent by Azure Function output collector with `Microsoft.Azure.WebJobs.Extensions.ServiceBus` package v3.* installed
- There is Azure Function App with a ServiceBus triggered function with `Microsoft.Azure.WebJobs.Extensions.ServiceBus` package v4.* installed

**Expected Behavior:**
Service Bus trigger works without any errors and receives a message

**Actual Behavior:**
`SerializationException` in `Microsoft.Azure.WebJobs.ServiceBus.Triggers.MessageToStringConverter` with message:
`Exception while executing function: [FunctionNAme] Exception binding parameter 'message' The Message with ContentType 'null' failed to deserialize to a string with the message: 'Expecting element 'string' from namespace 'http://schemas.microsoft.com/2003/10/Serialization/'.. Encountered 'Text'  with name '', namespace ''.' Expecting element 'string' from namespace 'http://schemas.microsoft.com/2003/10/Serialization/'.. Encountered 'Text'  with name '', namespace ''. `

**Question:**
Is it supposed to work like this? Is there any workaround to fix this problem except downgrading `Microsoft.Azure.WebJobs.Extensions.ServiceBus` package version on the receiver side?

**Comment by v-anvari** [comment]
Hi @myarotskaya , Are you still facing this issue, we would require additional information to be able to clone the scenario. Can you give us the repro steps to be able to repro the error
