### ISSUE TITLE
Interop with Application Insights SDK option

### ISSUE THREAD

**Issue by jabbera** [Azure/azure-functions-host#6413]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 

C#

#### Question
What, specifically, does this option do? I have some custom dependency tracking in my function that doesn't seem to be working. Will enabling this option solve it?

**Comment by madushans** [comment]
Which option are you referring to?

Is it the one in host.json -> loging.applicationInsights.isEnabled ?
is it something in local.settings.json ?
Enable Application Insights button in Azure portal?
something else?

Basically the integration between Azure Functions (v2 and v3) and Application Insights does the following.

- Allows your calls to `ILogger` and `ILogger<T>` to be logged to application insights as traces
- Your function invocations to be logged as requests
- Each invocation becomes and Operation in appinsights, so you can correlate logs with operation_Id
- Logs a bunch of metrics about your function execution time
- Any HTTP and SQL requests get logged as dependencies in app insights
- Functions host and Scale Controller logs to appear in traces.
- Adds Category in app insights records to match the name of T in ILogger<T>
- Using ILogger.CreateScope(...) will add customDimensions.prop__<your propertyname> and values to all records within the scope 
- probably more stuff

If you have custom telemetry on your codebase using TelemetryClient, they will work as expected, but if you're logging the same stuff, like dependencies, they will double up. You can stop this by using a setting in host.json so only your custom dependencies  are logged to app insights.

For all of the above to work, you need to 
- enable App Insights via host.json
- put the instrumentation key in environment variable (or in local.settings.json)

Hope this helps.

**Comment by Erythnul** [comment]
I believe @jabbera is referring to a new options added to the Azure Functions Application Insight integration page on the Azure portal. [Ref: this image, apologies for the low quality](https://i.imgur.com/InHAPQj.png).
I would also like to know what this option actually does.

**Comment by jabbera** [comment]
Yup! That's it!

**Comment by usnhsa** [comment]
Me Too! What does it do? Cant find any info on it.

**Comment by sakkuntyo** [comment]
Does documentation for the "Interop with Application Insights SDK option" exist?

**Comment by cijothomas** [comment]
https://docs.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps?tabs=net#troubleshooting This has been updated to describve the interop option.

**Comment by v-anvari** [comment]
Closing this issue as the required information is provided.
