### ISSUE TITLE
Version Issue

### ISSUE THREAD

**Issue by Berndinox** [Azure/azure-functions-host#6419]
Startet an  Function from HTTP Template as suggested in azure from local Development.
I do use VS Code (newest Version) + installed the required Tools.

Local Function is v2, Azure is configured for v3.
Template does not run:
http://myURL.com/api/testfunctionm - `Function host is not running.`

i exactly followed those steps:
![image](https://user-images.githubusercontent.com/1122698/88482280-901f4580-cf60-11ea-8c1e-c19170fafabb.png)

**Comment by v-anvari** [comment]
Http template is working as expected when tried to repro from our end. Considering the two different versions of functions in the local function and azure, will not allow function to deploy to the azure with a different version.

By default, core tools download with version 3. To equalize the versions, you can choose either of the two ways:
1.	To change the version of azure locally, install the core tools with version 2. Run the below command to download version 2 of core tools
: **“npm install -g azure-functions-core-tools@2”**

2.	To change the version in the portal. Change the version manually in your function app by following the below path:
: **Function app settings > runtime version to 3 (to match the local version)**

For further understanding on how to change the runtime version, you can also follow [link](https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version#:~:text=%20From%20the%20Azure%20portal%20%201%20In,restart%20the%20app.%20The%20function%20app...%20More%20)

Once the versions are equal, you should be able to “deploy your code to Azure”. It would be helpful if you could provide us additional details of the error logs during debugging of code in vs code. Also, let us know if the error you are seeing is during deployment or while running locally.
