### ISSUE TITLE
Reimplement ability to use Microsoft's HealthCheck library in 3.x version of azure functions.

### ISSUE THREAD

**Issue by Mike-Becatti** [Azure/azure-functions-host#6421]
#### What problem would the feature you're requesting solve? Please describe.
I would like to implement Health Checks using the Microsoft.Extensions.Diagnostics.HealthChecks library like in 2.x.

Current error message when implementing Health Checks:
`A host error has occurred during startup operation 'd582e85f-d970-4653-abc2-4905d0424c17'.
[7/27/2020 6:43:11 PM] func: Invalid host services. Microsoft.Azure.WebJobs.Script.WebHost: The following service registrations did not match the expected services:
[7/27/2020 6:43:11 PM]   [Invalid] ServiceType: Microsoft.Extensions.Hosting.IHostedService, Lifetime: Singleton, ImplementationType: Microsoft.Extensions.Diagnostics.HealthChecks.HealthCheckPublisherHostedService.`

#### Describe the solution you'd like
This issue came up with DataProtection but was resolved.  Can the same solution be implemented for health checks? https://github.com/Azure/azure-functions-host/issues/5447

#### Describe alternatives you've considered
I haven't been able to find one.

#### Additional context
Additional Issues related to this one: https://github.com/dotnet/extensions/issues/2846

**Comment by fabiocav** [comment]
Thank you for opening this. 

We need to investigate whether this is another hosted service we can support.

@brettsam , FYI

**Comment by vaibhavramdasi** [comment]
As a workaround, I'm adding Timer Triggered function that includes the logic from HealthCheckPublisherHostedService.
Also after call to services.AddHealthChecks() this is needed
            services.Remove(services.FirstOrDefault(x => x.ImplementationType?.Name == "HealthCheckPublisherHostedService"));

**Comment by fabiocav** [comment]
Assigning to the next sprint's backlog for review
