### ISSUE TITLE
Azure B2C new UserFlows with error callback

### ISSUE THREAD

**Issue by miqm** [Azure/azure-functions-host#6422]
#### What problem would the feature you're requesting solve? Please describe.
Hello,

I've been recently connecting Azure B2C to FunctionApp Authenthication.

I wanted to use a preview version of SignInV2 (looks nicer) but there's a major problem with Password reset built in there.

From what I found out, instead like in SignInV1 redirecting to a built-in password-reset flow it calls back the application on callback endpoint with an error code to application to decide.

However, it seems, like this flow is not supported by FunctionApp Auth mechanism.

#### Describe the solution you'd like

I know, that this is a preview feature, but it would  be nice if it could be handled and we could specify a link to user flow with password reset.

#### Describe alternatives you've considered
Alternatively we would need to put an endpoint that will handle auth, but the point here is to let FunctionApp control the authorisaiton so we don't need to do that in our code.

#### Additional context

**Comment by v-bbalaiagar** [comment]
Hi @miqm, Apologies for the delayed response, We would like to know if you are still facing the same issue.

**Comment by miqm** [comment]
Hello,

I need to check it again.  But if you didn't make any improvements in the Easy Auth since then, then it's still valid.

**Comment by v-bbalaiagar** [comment]
Hi @ConnorMcMahon, Could you please look into this issue.

**Comment by ConnorMcMahon** [comment]
This is outside of the scope of EasyAuth, and we have no plans to add formal support for AAD B2C user flows beyond OIDC browser login and JWT validation.

**Comment by v-bbalaiagar** [comment]
Thank you @ConnorMcMahon for the update

**Comment by miqm** [comment]
Thanks. That's a bit sad that Easy Auth has no plans to support B2C built-in flows.

I'll proceed then with a custom config and I'll forget about the built in support for authorisation as it's not and will not be compatible with b2c.
