### ISSUE TITLE
FUNCTIONS_WORKER_DIRECTORY env variable not available after specialization

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#6427]
cc @yojagad  - current release owner, @fabiocav  - for visibilty

@amamounelsayed fyi

Commit: https://github.com/Azure/azure-functions-host/commit/24dc6a7f63a3dc754337c62f4777a38132650b2b added new enviornment variable when starting langauge worker process.

But environment variables are reset after specialization by the Java worker process.

**Comment by pragnagopa** [comment]
@fabiocav - this needs a hotfix. Any labels i should add to this issue? also which sprint this should be assigned to?

**Comment by fabiocav** [comment]
We can just link this to the release item.

No other specific labels to track.

**Comment by pragnagopa** [comment]
Java worker improvement work item: https://github.com/Azure/azure-functions-java-worker/issues/392
