### ISSUE TITLE
Provide a mechanism for extensions set additional file extensions to be watched

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#6431]
We need a mechanism to enable extension loaded into the host to define custom extensions that need to be processed by the file monitoring service.

**Comment by ankitkumarr** [comment]
This will have to be moved to the next Sprint as I will be away for a week.

**Comment by ankitkumarr** [comment]
@mathewc suggested that I should attempt to solve this issue in a generic way such that extensions can add to our configuration or option setup.

To do this, I am going to introduce a new "host.json" property "watchFiles" (similar to "watchDirectories").

For extensions to modify the "watchFiles" property, they can leverage the new `IWebJobsStartup2` [[link](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Hosting/IWebJobsStartup2.cs)] interface.

I tried it, and it seemed to work. Here's how it would look like --

```csharp
[assembly: WebJobsStartup(typeof(MyExtensionWebJobsStartup))]

namespace Microsoft.Azure.WebJobs.Extensions.MyExtension
{
    public class MyExtensionWebJobsStartup : IWebJobsStartup2
    {
        public void Configure(IWebJobsBuilder builder)
        {
            builder.AddMyExtension();
        }

        public void Configure(WebJobsBuilderContext context, IWebJobsBuilder builder)
        {
            IConfigurationSection watchedfilesSection = context.Configuration.GetSection("AzureFunctionsJobHost").GetSection("watchFiles");

            IList<string> allWatchedfiles = watchedfilesSection?.Get<List<string>>() ?? new List<string>();
            allWatchedfiles.Add("my_special_file.txt");

            for (int i = 0; i < allWatchedfiles.Count; i++)
            {
                context.Configuration[$"AzureFunctionsJobHost:watchFiles:{i}"] = allWatchedfiles[i];
            }

            Configure(builder);
        }
    }
}
```
