### ISSUE TITLE
 System.Private.Uri: Invalid URI: The hostname could not be parsed. Value cannot be null. (Parameter 'provider')

### ISSUE THREAD

**Issue by rupeshtech** [Azure/azure-functions-host#6443]
#### Error while running a Azure ServiceBusTrigger function(V3)#####
After **upgrading Microsoft.Azure.WebJobs.Extensions.ServiceBus** to 4.1.2 I am not able to run Azure function
Earlier it was running fine.

#### Getting Error
A host error has occurred during startup operation 'xxxxxxxx'.
**System.Private.Uri: Invalid URI: The hostname could not be parsed.
Value cannot be null. (Parameter 'provider')**

#### error screenshot
![image](https://user-images.githubusercontent.com/24852402/89101117-70bf6700-d3fd-11ea-949c-134e4d30db9a.png)

#### Investigative information

Already checked conn string which is in right format
Endpoint=sb://xxxx.servicebus.windows.net/;SharedAccessKeyName=xxx;SharedAccessKey=xxxxxxx;

#### Related information 

following is the function
```csharp
[FunctionName("xxxx")]
        public async Task Run(
            [ServiceBusTrigger("xxx", Connection = "xxxx-conn")]string myQueueItem
            )
        {
            _logger.LogInformation("Message Received {0}", myQueueItem);
            // do something
        }
```
#### local setting
![image](https://user-images.githubusercontent.com/24852402/89101109-6a30ef80-d3fd-11ea-8a38-4a8badccbd9b.png)

#### Packages
![image](https://user-images.githubusercontent.com/24852402/89101139-8df43580-d3fd-11ea-8a3e-b7769744d45d.png)

**Comment by TsuyoshiUshio** [comment]
Hi @rupeshtech 
Sorry for the inconvenience.  We will provide hot fix. by this PR. https://github.com/Azure/azure-functions-host/pull/6478
For the mitigation until then, roll back to your function app to 3.0.13901. For more details. https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version#automatic-and-manual-version-updates

**Comment by fabiocav** [comment]
Resolved by #6478

**Comment by fabiocav** [comment]
@rupeshtech please apply the workaround provided by @TsuyoshiUshio . We're applying a hotfix and that release will be announced here: https://github.com/Azure/app-service-announcements/issues

**Comment by fabiocav** [comment]
The recommendation is to remove the workaround once the hotfix is deployed. Thank you again and apologies for the inconvenience.

**Comment by mathewc** [comment]
@fabio @TsuyoshiUshio The error in this issue doesn't seem related to #6478.
