### ISSUE TITLE
Using wasmtime-dotnet in Azure Functions errors with 'image not found' (native dependencies)

### ISSUE THREAD

**Issue by ChristianWeyer** [Azure/azure-functions-host#6446]
Hi all!

I have tried to use wasmtime-dotnet (https://github.com/bytecodealliance/wasmtime-dotnet) in an Azure Function.
For now, I am running this locally on macOS.
```
➜  ~ func --version
3.0.2245
```

It fails when calling the HTTP-triggered function:

```
Executed 'RunWasm' (Failed, Id=f2ddeb26-1bdc-4f7c-a22c-85315832c10f)
System.Private.CoreLib: Exception while executing function: RunWasm. Wasmtime.Dotnet: Unable to load shared library 'wasmtime' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libwasmtime, 1): image not found.
```

This all works great with a simple.NET Core console application.
As we can see, also for the Azure Functions project, the runtimes are present in the bin folder:

![image](https://user-images.githubusercontent.com/888718/89178631-55379600-d58e-11ea-866a-1cde72aff2de.png)

Any ideas on what could be the issue?

You can see the repro here:
https://github.com/ChristianWeyer/azure-functions-wasmtime-repro

Thanks,
-Christian

**Comment by v-bbalaiagar** [comment]
Hi @ChristianWeyer, Closing this issue as the required information is provided [here](https://github.com/bytecodealliance/wasmtime-dotnet/issues/33), Please feel free to reach back to us in case of any further queries related to this issue.
