### ISSUE TITLE
IFormFile and FormFile conflict

### ISSUE THREAD

**Issue by csalgo70** [Azure/azure-functions-host#6447]
#### Investigative information

Running azure functions locally on windows 10 OS.

**Versions**

dotnet --version: 3.1.302
func --version: 3.0.2630

#### Repro steps

I have installed latest .net core 3.1 

Create new Azure function sample with simple http trigger.

Replace the code with this

```csharp
[FunctionName("HttpExample")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = null)]
            HttpRequest req,
            ILogger log)
        {
            var formData = await req.ReadFormAsync();
        
            var inputFiles = req.Form.Files;

            if (inputFiles == null)
            {
                return new BadRequestObjectResult(new string("Missing Files to upload"));
            }

            var folder = formData["folder"].ToString();

            if (string.IsNullOrWhiteSpace(folder))
            {
                return new BadRequestObjectResult(new string("Missing folder field"));
            }

            foreach (var inputFile in inputFiles)
            {
                var f = inputFile as FormFile;
            }
                
            return new OkResult();
        }
```

#### Expected behavior

I haven't added anything extra. Its just a new azure func code. Shouldn't it work out of the box. I still see the FormFile in Microsoft.AspNetCore.Http.Internal and public. I do need to cast because there is another serilization issue with passing IFormFile to an Activity ( for duarable Functions ) where it needs a concrete implementation.

namespace Microsoft.AspNetCore.Http.Internal
{
public class FormFile : IFormFile
{

#### Actual behavior

Run time excepton is thrown.
[8/3/2020 12:59:54 AM] Executed 'HttpExample' (Failed, Id=a68f691d-2e50-4867-b056-371aa4fa96ad)
[8/3/2020 12:59:54 AM] System.Private.CoreLib: Exception while executing function: HttpExample. HttpFuncExample: Could not load type '**Microsoft.AspNetCore.Http.Internal.FormFile**' from assembly 'Microsoft.AspNetCore.Http, Version=3.1.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### Assembly Info

If I look at the assembly used I see Version 2.1.0.0 but above it says 3.1.5.0 not sure why.

Assembly Microsoft.AspNetCore.Http, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 while it does show the framework as C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0

**Comment by v-anvari** [comment]
Hi @csalgo70 , Please let us know the package reference used in the VS, as we are unable to identify the same. It would be helpful if we could get the .csproj file from your VS, so that we can can repro the issue mentioned above.

**Comment by csalgo70** [comment]
Attached the zip version of my VS solution. Just replace the storage account name / key based on your enviornment or  you remove that in fact as you don't need that for this testing.
[HttpFuncExample.zip](https://github.com/Azure/azure-functions-host/files/5053901/HttpFuncExample.zip)

**Comment by v-anvari** [comment]
Hi @csalgo70 , there were few changes made in the latest releases, I was able to deploy the above app successfully without any error. Please try again and let us know if it is working for you. 

**Package version : Microsoft.NET.Sdk.Functions 3.0.9** 

**VS Output :**

1>------ Build started: Project: HttpFuncExample, Configuration: Release Any CPU ------
1>HttpFuncExample -> C:\Users\v-anvari\Downloads\HttpFuncExample\HttpFuncExample\bin\Release\netcoreapp3.1\HttpFuncExample.dll
2>------ Publish started: Project: HttpFuncExample, Configuration: Release Any CPU ------
2>HttpFuncExample -> C:\Users\v-anvari\Downloads\HttpFuncExample\HttpFuncExample\bin\Release\netcoreapp3.1\HttpFuncExample.dll
2>HttpFuncExample -> C:\Users\v-anvari\Downloads\HttpFuncExample\HttpFuncExample\obj\Release\netcoreapp3.1\PubTmp\Out\
2>Publishing C:\Users\v-anvari\Downloads\HttpFuncExample\HttpFuncExample\obj\Release\netcoreapp3.1\PubTmp\HttpFuncExample - 20201027155204304.zip to https://httpfuncexample20201027154919.scm.azurewebsites.net/api/zipdeploy...
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
