### ISSUE TITLE
Functions v3: req.Content.ReadAsAsync<T>() performs synchronous operation

### ISSUE THREAD

**Issue by chitoiur** [Azure/azure-functions-host#6449]
The issue is quite simple. We recently upgraded to functions v3. We had this code all over the place:

```
public static async Task Func([HttpTrigger(AuthorizationLevel.Anonymous, "get")] HttpRequestMessage req) 
{
    var request = await req.Content.ReadAsAsync<MyRequest>();
    [...]
}
```

The error we were seeing was this: "Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead." Something in inside `ReadAsAsync` is performing a synchronous operation.

The workaround was to call `ReadAsStringAsync()` and then manually deserialize.

**Comment by fabiocav** [comment]
Odd that you were seeing that with ReadAsAsync. A Stack here would be helpful, but you could temporarily also enable synchronous IO with the app setting documented here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#functions_v2_compatibility_mode

**Comment by prabh-62** [comment]
I am having the same issue. Setting `FUNCTIONS_V2_COMPATIBILITY_MODE=true` does help however this is a workaround and we would like a fix for this issue before pushing code to production.

Screenshots below
- Exception
<img width="1030" alt="readasasync_2_exception" src="https://user-images.githubusercontent.com/13006107/89654914-5a9b2600-d897-11ea-9dc4-a1d724be25ab.png">

- Stacktrace
<img width="1028" alt="readasasync_3_stacktrace" src="https://user-images.githubusercontent.com/13006107/89654972-6c7cc900-d897-11ea-99c9-5e8b530f308e.png">

- Jetbrains Decompiler (using Rider IDE)
<img width="1020" alt="readasasync_1_dll_location" src="https://user-images.githubusercontent.com/13006107/89655002-78688b00-d897-11ea-8d71-c5f5d3feaa6f.png">
