### ISSUE TITLE
Storage SDK V12 call timesout every 100 secs in Azure Functions runtime

### ISSUE THREAD

**Issue by rohitgkr** [Azure/azure-functions-host#6456]
This is regarding Azure Functions LOCAL runtime (not associated with App Service Plan).
Fiddler shows that the outgoing HTTP request to storage times out every 100 secs with 408. Various strategies have been tried starting from HttpClient timeout, ServicePointManager MaxServicePointIdleTime, SocketsHttpHandler pooling settings, etc. All changes were applied in the FunctionsStartup class. However the end result is the same with an HTTP 408 every 100 secs both in Functions and Durable Activities.
NOTE - The same code to upload to hierarchical namespace storage works from .NET core console or Xunit test runtimes. It fails only in Azure Functions runtime.
1. How do you override Functions ServicePointManager & HttpClient settings as FunctionsStartup has no impact?
2. This happens for specific file sizes (ex 200 MB) where buffer blocks take longer than 100 secs to commit. Reducing block size to 1KB in StorageOptions still resulted in the timeout. Has anyone been able to use V12 SDK from Functions?
3. While you can add HttpClient as below in FunctionsStartup.Configure, how to add BlobServiceClient? 
```csharp
builder.Services.AddHttpClient("my", http => http.Timeout = TimeSpan.FromMinutes(60));
builder.Services.BuildServiceProvider().AddBlobServiceClient()???
```
![image](https://user-images.githubusercontent.com/5541550/89329694-0f122d80-d687-11ea-95ad-9984bedd0fe2.png)

#### Repro steps
Initialize static instances in Startup class
```csharp
builder.Services.AddHttpClient(HTTP_CLIENT_NAME, httpClient => {
                httpClient.Timeout = TimeSpan.FromMinutes(httpClientTimeoutMinutes);
            }).SetHandlerLifetime(TimeSpan.FromMinutes(HTTP_MESSAGEHANDLER_LIFETIME_MINUTES));
```
Then use the ctor injected factory in the Function run to extract the HttpClient instance and pass it on to the Storage SDK to make outgoing calls. 
```csharp
// Create the blob container client within an Azure Function Run method --->
httpClient = httpFactory.CreateClient(Startup.HTTP_CLIENT_NAME);
			var blobOptions = new BlobClientOptions
			{
				Transport = new HttpClientTransport(httpClient)
				//default => HttpClient timeout = 100 secs
			};			
return new BlobContainerClient(new Uri(containerEndpoint), credential, blobOptions);
// Use that to get a block blob client instance
string blobDestinationPath = $"/{year}/{month}/{model}/{blob.Name}";
var blockClient = containerClient.GetBlobClient(blobDestinationPath);
try
{
  await blockClient.UploadAsync(content: remoteFS, transferOptions: transferOptions);
  log.LogTrace($"Uploaded {remoteFileName} to {blobDestinationPath}");
  successful.Add(remoteFileName);
}
catch (Exception someEx)
{
  log.LogError(someEx, "Failed : {0}", remoteFileName);
  --- retry by Http code
```

#### Expected behavior

Timeouts specified during FunctionsStartup are respected and changed from defaults.

#### Actual behavior
Timeouts are roughly at 100 secs with the HTTP request timing out and being retried again.
Reducing block sizes still resulted in timeout. However HTTP408 is only observed in Azure Functions local runtime & not in .NET Core console or unit test runtimes.
```csharp
var transferOptions = new StorageTransferOptions
{
  MaximumConcurrency = Environment.ProcessorCount * 4,
  MaximumTransferLength = 1 * 1024
};
```
HOST.JSON settings don't help either.
```
"version": "2.0",
  "functionTimeout": "06:00:00",
  "extensions": {
    "http": {"maxConcurrentRequests": -1},
    "durableTask": {
      "extendedSessionsEnabled": true,
      "extendedSessionIdleTimeoutInSeconds": 3600,
      "maxConcurrentActivityFunctions": 500,
      "maxConcurrentOrchestratorFunctions": 500,
      "useGracefulShutdown": true
    }
```

**Comment by petro2050** [comment]
@rohitgkr I was getting timeouts on the client side in Xamarin. I've never tried Functions or .NET Core, but there might be an issue with the Storage SDK itself. See https://github.com/Azure/azure-sdk-for-net/issues/16548.

I too needed to upload very large files and in the end ended up using `BlockBlobClient` with individual blocks which worked like a charm even in v12. See https://stackoverflow.com/questions/65499942/azure-storage-blobclient-keeps-resetting-itself-while-uploading-large-files.

**Comment by v-anvari** [comment]
Hi @rohitgkr , Apologies for the delayed response. Were you able find a solution from https://github.com/Azure/azure-sdk-for-net/issues/16548? If it was a bug it must have been resolved by now. Please let us know if this issue still persists with the latest releases
