### ISSUE TITLE
Advisory of V2 function apps need to be converted to V3 

### ISSUE THREAD

**Issue by buzzaII** [Azure/azure-functions-host#6459]
#### Is your question related to a specific version? If so, please specify:

V2 and V3

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 

C#

#### Question

We currently received an advisory that outlined that v2 functions (built on .net core 2.2) is reaching end of life and will not be supported by PaaS in around the October time frame.

We need clearer information if and how we can 'opt out' of the platform upgrade without setting **FUNCTIONS_V2_COMPATIBILITY_MODE**. 

Unfortunately we don't have the capacity to migrate all our workloads to the new version in the time frame provided.

**Comment by ankitkumarr** [comment]
@anthonychu or @paulbatum, would either of you be able to assist with this question?

**Comment by anthonychu** [comment]
@buzzaII  You can opt out by pinning your app's `FUNCTIONS_EXTENSION_VERSION` to `~2.0`. This will keep your app on .NET 2.x. It'll continue to work after October, but will no longer receive security updates. More details can be found [here](https://github.com/Azure/azure-functions-host/wiki/Platform-upgrade-from-Azure-Functions-runtime-v2-to-v3).

**Comment by pragnagopa** [comment]
Closing this issue.  @buzzaII - please post any questions on announcement discussion issue here: https://github.com/Azure/app-service-announcements-discussions/issues/175 Thanks!
