### ISSUE TITLE
Upgrade PowerShell workers to 3.0.446 (PS6) and 3.0.452 (PS7)

### ISSUE THREAD

**Issue by AnatoliB** [Azure/azure-functions-host#6470]
Upgrade PowerShell workers to 3.0.446 (PS6) and 3.0.452 (PS7)

**Comment by fabiocav** [comment]
Just wanted to confirm; are you still targeting sprint 81 for this?

**Comment by AnatoliB** [comment]
> Just wanted to confirm; are you still targeting sprint 81 for this?

@fabiocav Yes, unless it's too late. The PR is out, we should be able to merge it today.
