### ISSUE TITLE
Keyvault access issues when using both System Assigned Identity and User assigned managed identity for an azure function

### ISSUE THREAD

**Issue by manums** [Azure/azure-functions-host#6477]
#### Repro steps
We have an azure function which is assigned with both system assigned identity (with function name) and user assigned managed identity.

* User identity has(provides) access to shared Keyvault A secrets and keys. Keyvault A access is shared across multiple apps and functions. _Function app has to read secrets from this shared kevault A using User identity*

* Managed identity has(provides) access to other keyvault B's secrets and keys. Keyvault B access is controlled only for this function and can't be used by other apps\functions. _Function app has to read secrets from this keyvault  using system assigned identity_

**How to make function app use MSIs and use both identities to access keyvaults as expected?**

#### Expected behavior

Access keyvault secret successfully from Keyvault A using System Assigned Identity and secret from Keyvault B using User Assigned Managed Identity. Both the identities are assigned to the function app.

Function app should be able to read secrets from both keyvaults A and B. 

Only one of the identity works as MSI at a time and hence only keyvault can be accessed using both identities. 

#### Actual behavior
- When using only managed identity it is able to access to secrets from Keyvault B as expected.
- When using only user assigned identity or _with system assigned identity and by adding `AzureServicesAuthConnectionString` environment varible to run as User assigned identity i.e. `RunAs=App;AppId=<<userAssignedIdentityClientId>>`_ then function app is able to read secret from sharedkeyvault A as expected.

#### Code Snippet and Platform details

* Function Runtime Version - 2
* OS - Windows
* Platform - 64 bit, .net core 3.1
* Bindings used -> **Eventhub, HttpTrigger**

```csharp
var azureServiceTokenProvider = new AzureServiceTokenProvider();
keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));
SecretBundle secretBundle = await keyVaultClient.GetSecretAsync(secretId).ConfigureAwait(false);
return secretBundle.Value;
```

```json
{
"name": "AzureServicesAuthConnectionString",
"value": "RunAs=App;AppId=clientIdGuidHere",
"slotSetting": false
}
```

I created same Issue against Azure SDK. SDK team closed the issue by redirecting to function apps team.

[
[BUG] Forbidden from Keyvault for reading secrets when using User Assigned Managed identity (along with system assigned identity) ](https://github.com/Azure/azure-sdk-for-net/issues/13808)

**Comment by ankitkumarr** [comment]
@mattchenderson, do you know what's the recommendation here?

**Comment by v-bbalaiagar** [comment]
Hi @manums, Apologies for the delayed response. Can you please confirm were you able to figure the solution here. Do let us know if you want us to look at this issue further so that we can follow up with the right team.
