### ISSUE TITLE
HTTP + Timer trigger in function.json results in only Timer trigger being deployed

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-functions-host#6483]
#### Issue Summary

I am trying to apply both a timer and HTTP trigger to an Azure Function. When I add the second timer trigger to the first HTTP trigger, the HTTP trigger is no longer valid. 

I would like both triggers to be supported simultaneously, according to the documentation for triggers and bindings for Azure Functions.

#### Investigative information

Please provide the following:

- Timestamp: n/a
- Function App version: 3
- Function App name: trevorwindow
- Function name(s) (as appropriate): HttpTrigger1
- Invocation ID: n/a
- Region: Central US

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create an Azure Function with HTTP Trigger
2. Add Timer binding in `function.json`
3. Deploy the function project
4. Go into the Azure Portal and observe that only the timer trigger is shown
5. Attempting to manually trigger the function results in HTTP 404 Not Found

#### Expected behavior

Both the Timer and HTTP triggers are enabled side-by-side.

#### Actual behavior

The Timer trigger is active, but the HTTP trigger is missing / disabled.

#### Known workarounds

No known workarounds.

#### Related information 

Provide any related information 

* PowerShell
* Bindings used: only built-in HTTP and Timer bindings

#### Screenshot

Notice how the HTTP trigger is missing from the function triggers.

![image](https://user-images.githubusercontent.com/466713/89666921-718e4800-d898-11ea-8c6d-22c91c6c8986.png)

#### function.json

```json
{
  "bindings": [
    {
      "schedule": "0 * * * * *",
      "name": "myTimer",
      "type": "timerTrigger",
      "direction": "in"
  },
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "Request",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "Response"
    }
  ]
}
```

**Comment by v-anvari** [comment]
hi @pcgeek86 , We have tried to repro the issue you have mentioned, we see that you are trying to add a binding which is a timer trigger and http trigger in the same function.json. Currently Function app do not support this feature which can accommodate two triggers in one function app. 

We are closing the issue since it has answered the query, please feel free to reopen the issue in case of any concerns.

**Comment by pcgeek86** [comment]
Hello,

I appreciate the response. However, shouldn't the Azure Functions platform throw some kind of error message during deployment, and fail the deployment process, instead of silently failing? This is a really bad user experience.

Cheers,
Trevor Sullivan

**Comment by pcgeek86** [comment]
Also, the documentation states the following:

> You can mix and match different bindings to suit your needs. Bindings are optional and a function might have one or multiple input and/or output bindings.

This seems inconsistent with what you posted earlier. Can you please clarify?

https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings

**Comment by pragnagopa** [comment]
@pcgeek86 - thank you for reporting this. Assuming you built the function from UI?

@takyyon / @ammanifold  - can you please take look? This appears to be a UX  issue. Function should not be build with two triggers.

**Comment by pcgeek86** [comment]
Hello @pragnagopa, thank you for getting this re-opened. I am building and deploying the function using Visual Studio Code with the Azure Functions extension. I am not using the Azure web interface to create the function.

My expectation, as a customer / end user, would be to have an appropriate error message thrown at deployment time, indicating that multiple triggers are not supported. Also, the documentation appears to need an update. Thank you!

**Comment by pragnagopa** [comment]
cc @EricJizbaMSFT for VSCode.

Yes. It is strange that tooling allows the users to create invalid functions. We are investigating.

**Comment by pragnagopa** [comment]
@pcgeek86 - can you give exact repro steps on how you created a function with two triggers from VS Code?

**Comment by pcgeek86** [comment]
@pragnagopa I have not spent any time trying to reproduce this from scratch, but I will do so now.

**Comment by pcgeek86** [comment]
@pragnagopa Please provide a contact e-mail for you, so I can send the video link privately.

**Comment by pragnagopa** [comment]
@pcgeek86 - We are trying to understand if creating a function from our tooling allows creating an invalid function. If you edited function.json after function is created, there is no build time validation. You would see errors when executing a function.

please share you repro: pgopa@microsoft.com

@takyyon / @ammanifold  - Function in the portal did have indexing errors on the runtime. Any ideas why portal did not show errors when navigating to the function in portal?

**Comment by pcgeek86** [comment]
@pragnagopa Link to private YouTube video sent. Please report back here with any additional questions you might have.

**Comment by pragnagopa** [comment]
@pcgeek86 - Thanks for sharing the repro. You have edited `function.json` manually to include TimerTrigger binding. A function can only one Trigger. If you using only gestures supported in  VS Code to add more bindings, you will not end up with creating an invalid funcion. We cannot provide errors at deployment time. But running the function locally would have shown you errors.

Documentation you pointed out earlier does state: `a function must have exactly one trigger. `

In the Azure portal - you do see one function that is deployed. As function can only have one trigger, UI is showing the first trigger binding listed in function.json

I will wait for response from @ammanifold  and @takyyon before closing this issue to ensure if there is a follow up UX issue we need here for improvement.

**Comment by pcgeek86** [comment]
In the video, I called out where the Azure Functions extension logs show that the deployment was successful. It should not succeed. Rather, it should fail with an appropriate error message.

Also, as I pointed out earlier, the documentation states:

> You can mix and match different bindings to suit your needs. Bindings are optional and a function might have one or multiple input and/or output bindings.

I'm very confused at all the conflicting information.

**Comment by pragnagopa** [comment]
Deploying a function app is a build time action. Whether the function can is valid or not is a runtime action. I do not think we have any plans to add validation during deployment.

Regarding documentation -  yes, you can mix input and output bindings but a function must have exactly one trigger. If you still believe documentation is not clear - please open a issue here: https://github.com/MicrosoftDocs/azure-docs . Thanks!

**Comment by pcgeek86** [comment]
> We cannot provide errors at deployment time.

Why not? Deployments are successful, even if they aren't? That's probably not a good UX.

> But running the function locally would have shown you errors.

I'm having other problems trying to get `func` to run, but that's outside the scope of this issue.

**Comment by dsghi** [comment]
Jumping in here, because I actually had a need for this scenario, and found that there is a way to call a timer triggered function on-demand via HTTP, just not the same way as a function with an HTTP trigger, see this doc: [Manually run a non HTTP-triggered function](https://docs.microsoft.com/en-us/azure/azure-functions/functions-manually-run-non-http)

BTW where can I submit a feature request? It seems very logical to want to have a timer triggered functions that can also be triggered on-demand via HTTP. Having to craft a custom URL, or create multiple functions, is a bit of a devops pain.

**Comment by v-anvari** [comment]
Hi @dsghi , you can raise a new feature request in [feedback.azure.com-azure-functions](https://feedback.azure.com/forums/355860-azure-functions)

**Comment by sac-cas** [comment]
Currently I am trying to run the timer triggered function manually with a request body as I need some values. The function runs successfully but how can I access the request body?
As it isn't a http triggered function I do not have a request in my context and the event object is (as expected) the timer event.

**Comment by Shubhangi-Priya** [comment]
I am trying to trigger a timer based function on demand. This function is deployed in AKS and currently there seems to be no way to do this. Having this functionality would be really helpful.

**Comment by v-anvari** [comment]
Hi @Shubhangi-Priya , Thank you for the feedback, we would surely consider it. Could you kindly submit a new feature request in [feedback.azure.com-azure-functions](https://feedback.azure.com/forums/355860-azure-functions)

**Comment by v-anvari** [comment]
Closing this issue as the required information is provided, and this is not a supported design. 

Kindly raise a feature request on this here- https://feedback.azure.com/forums/355860-azure-functions.

Please feel free to reach back to us in case of any further queries related to this issue
