### ISSUE TITLE
Http Trigger suddenly starts failing randomly in various function apps

### ISSUE THREAD

**Issue by alejandromelis** [Azure/azure-functions-host#6485]
#### Description

Http Trigger suddenly starts failing randomly in various function apps, the Http requests sent to the function never reach the code, and no app insights information and diagnostic appear.

Could be an App Service ARR problem, but Anonymous http trigger are not affected, maybe internal function key management problem?

#### Investigative information

- Timestamp: randomly from 2020-08-07T08:48:51 to 2020-08-07T09:08:40 approximately
- Function App version: V3
- Function App name: please, ask me in private
- Function name(s): please, ask me in private
- Invocation ID: n/a because the request never reach to the function.
- Region: West-Europe
- Plan: Consumption

#### Repro steps

1. Just call the function (AuthorizationLevel.Function) from your code, browser, or other tools.
2. Randomly you get the response but some times the request never reaches the Http trigger and "never" ends the connection.
3. Call another function (AuthorizationLevel.Anonymous) always work.
4. Wait some minutes or hours, and suddenly stops happening.

#### Known workarounds

No workarounds are known.

#### Related information 

* C#
* Net Core 3.1
* Function V3
* Runtime version: 3.0.14191.0
* HttpTrigger

**Comment by v-anvari** [comment]
Hi @alejandromelis, apologies for the delay, we are trying to reproduce the issue, request you to send us the function app name and function name to v-anvari@microsoft.com, for us to check the logs during that timestamp

**Comment by v-anvari** [comment]
hi @alejandromelis, We have reproduced the scenario, but http trigger worked as expected. The issue you faced might be timely errors. Let me know if you are still facing the same issue. If yes, let me know your app name, region and time stamp to check the logs.
