### ISSUE TITLE
V3: ReadAsAsync<T>() throws exception -> Synchronous operations are disallowed

### ISSUE THREAD

**Issue by prabh-62** [Azure/azure-functions-host#6486]
#### Repro steps

OS: `Mac OS 10.15.6`

Provide the steps required to reproduce the problem:

- Ensure you have Azure Functions V3 `func` CLI from [Github releases](https://github.com/Azure/azure-functions-core-tools/releases) and .NET Core 3.1 SDK
- `> func --version`
   `3.0.2630`
- `> func init ImageService --dotnet`
- `> cd ImageService`
- `> func new -l C#` Create new function with HTTP trigger
- Update code in HTTP trigger with this snippet
```csharp
namespace ImageService
{
    public class Load
    {
        public string LoadNumber { get; set; }
    }
    public static class Hello
    {
        [FunctionName("Hello")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = null)]
            HttpRequestMessage req)
        {
            var load = await req.Content.ReadAsAsync<Load>().ConfigureAwait(false);
            return new OkObjectResult(load);
        }
    }
}
```
- Hit the API with this curl request
```bash
curl -i -d '{"LoadNumber":"FB82444"}' \
	-H 'Transfer-Encoding:chunked' \
	-H 'Content-Type:application/json' \
	http://localhost:7071/api/hello
```

#### Expected behavior

We should get HTTP 200 result back

#### Actual behavior

We get HTTP 500
<img width="1440" alt="readasync_sync_error" src="https://user-images.githubusercontent.com/13006107/89698486-821ddd00-d8ef-11ea-9cb7-b793c247f05e.png">

#### Known workarounds

Add an Environment Variable before starting azure functions
`FUNCTIONS_V2_COMPATIBILITY_MODE=true`

#### Related information 

Provide any related information 

* Programming language used: `C#`
* Bindings used: `HTTPTrigger`

**Comment by ianadavies** [comment]
I am having this problem too. All my functions appear to be async yet I am getting this error, doesn't seem right to have to be in compatibility mode. It doesn't seem to happen on all my functions ( but most ) so maybe its something deeper inside dependencies ?

**Comment by anthonychu** [comment]
@ianadavies It’s likely somewhere in the dependencies, there is code that is reading the request stream synchronously. For instance, I think ReadAsAsync<T>() is not truly async and it is reading the stream synchronously when deserializing the JSON.

**Comment by ianadavies** [comment]
@anthonychu, Ok sounds like it was a little ambitious to switch this requirement on so soon by default?  Are there any compromises or trade offs using Azure Functions v3 when `FUNCTIONS_V2_COMPATIBILITY_MODE=true`?

**Comment by v-anvari** [comment]
Hi @prabh-62 , @ianadavies , Let me know if you have queries unanswered, I can follow up with the team for further investigation.

**Comment by prabh-62** [comment]
We moved off of Azure Functions. You can close the issue
