### ISSUE TITLE
[Custom Handlers - Go] Trigger fails to receive messages from ServiceBus queue with cardinality as many

### ISSUE THREAD

**Issue by ZachTB123** [Azure/azure-functions-host#6487]
I have a single Function App that is using Custom Handlers with Go. There are two functions in the Function App. The first function has a timer trigger. It is responsible for polling an endpoint to see if new content is available. If there is content, it will output an array of notifications to a ServiceBus queue. The second function is triggered by this queue and has cardinality set to many in the `function.json` file. The function that is triggered by messages in the ServiceBus queue is failing with:

Exception while executing function: Functions.content_retriever Exception binding parameter 'messages' Binding parameters to complex objects (such as 'String[]') uses Json.NET serialization or XML object serialization. 
 1. If ContentType is 'application/json' deserialize as JSON
 2. If ContentType is not 'application/json' attempt to deserialize using Message.GetBody, which will handle cases like XML object serialization
 3. If this deserialization fails, do a final attempt at JSON deserialization to catch cases where the content type might be incorrect
The JSON parser failed: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.String[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'key', line 2, position 8.

#### Investigative information

Please provide the following:

- Timestamp: 2020-08-08 01:04:04.646
- Function App version:
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: 94952ea1-8968-4f04-8cf5-2252d47305d5
- Region: Central US

#### Repro steps

Provide the steps required to reproduce the problem:

Create a Function App using Custom Handlers with Go. Create two functions in the Function App. One uses a timer trigger with a SerivceBus output binding that writes one or more messages to a queue. The second is triggered by messages written to the queue by the first function and has cardinality set to many.

#### Expected behavior

Provide a description of the expected behavior.

The second function that is triggered by the ServiceBus queue messages receives an array of messages during each invocation.

#### Actual behavior

Provide a description of the actual behavior observed.

When viewing the second function in the portal that is triggered by the ServiceBus queue messages under `Monitor` I see failed executions with:

Exception while executing function: Functions.content_retriever Exception binding parameter 'messages' Binding parameters to complex objects (such as 'String[]') uses Json.NET serialization or XML object serialization. 

(see full error message above)

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used: Golang with Custom Handlers
* Runtime version: 3.0.14191.0

Please note my code is very similar to the samples [here](https://github.com/Azure-Samples/functions-custom-handlers/blob/master/go/GoCustomHandlers.go). I will be omitting lots of the boilerplate code and calling out the important pieces.

Function 1 (timer trigger with ServiceBus output binding):

function.json:

```
{
  "bindings": [
    {
      "name": "pollingTrigger",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 */5 * * * *"
    },
    {
      "name": "checkpoints",
      "path": "test/checkpoints.json",
      "connection": "AZU_FUNCTION_STORAGE_KEY",
      "direction": "in",
      "type": "blob",
      "dataType": "binary"
    },
    {
      "name": "$return",
      "path": "test/checkpoints.json",
      "connection": "AZU_FUNCTION_STORAGE_KEY",
      "direction": "out",
      "type": "blob"
    },
    {
      "name": "contentQueue",
      "type": "serviceBus",
      "queueName": "content",
      "connection": "CONTENT_QUEUE_SEND_CONNECTION",
      "direction": "out"
    }
  ]
}
```

Code snippet:

```
type notification struct {
	Key  string `json:"key"`
	Date string `json:"date"`
}

...

// Timer trigger function
var notifications []notification
notifications = append(notifications, notification{
	Key:  "key1",
	Date: "date1",
})
notifications = append(notifications, notification{
	Key:  "key2",
	Date: "date2",
})
outputs := make(map[string]interface{})
outputs["contentQueue"] = notifications

returnValue := make(map[string]interface{})
returnValue["checkpoint"] = "12"

invokeResponse := InvokeResponse{Outputs: outputs, Logs: []string{"test log1", "test log2"}, ReturnValue: returnValue}
js, err := json.Marshal(invokeResponse)
if err != nil {
	http.Error(w, err.Error(), http.StatusInternalServerError)
	return
}

w.Header().Set("Content-Type", "application/json")
w.Write(js)
```

Function 2 (ServiceBus queue trigger):

function.json:

```
{
  "bindings": [
    {
      "name": "messages",
      "type": "serviceBusTrigger",
      "direction": "in",
      "queueName": "content",
      "connection": "CONTENT_QUEUE_LISTEN_CONNECTION",
      "cardinality": "many",
      "dataType": "string"
    }
  ]
}
```

Function code is not being invoked because of the errors posted above.

**Comment by pragnagopa** [comment]
cc @anthonychu @yojagad as FYI

`function.json` for ServiceBus trigger explicitly sets `"dataType": "string"` - please remove this and try. If it still does not work, I will set up a repro and try.

**Comment by ZachTB123** [comment]
@pragnagopa 

Updated my `function.json` file to:

```
{
  "bindings": [
    {
      "name": "messages",
      "type": "serviceBusTrigger",
      "direction": "in",
      "queueName": "content",
      "connection": "CONTENT_QUEUE_LISTEN_CONNECTION",
      "cardinality": "many"
    }
  ]
}
```

And am still getting a similar issue:

Binding parameters to complex objects (such as 'Object[]') uses Json.NET serialization or XML object serialization. 1. If ContentType is 'application/json' deserialize as JSON 2. If ContentType is not 'application/json' attempt to deserialize using Message.GetBody, which will handle cases like XML object serialization 3. If this deserialization fails, do a final attempt at JSON deserialization to catch cases where the content type might be incorrect The JSON parser failed: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Object[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly. To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object. Path 'key', line 2, position 8.

**Comment by pragnagopa** [comment]
Thanks @ZachTB123 for the update. 

Assigning this issue to next sprint for further investigation.

**Comment by anthonychu** [comment]
Haven't had a chance to try this out but I have an idea of what might be the issue(s).

When you output an array to the service bus binding (or any binding that can receive a list of stuff), each item gets turned into a service bus message. Each message contains a single notification object.

I think you're getting the error in the trigger because the current version of Service Bus trigger doesn't support batching. It's trying to take a single message and deserialize it into a list (causing the error). So you currently need to set the cardinality to `one` and it should work.

Event Hubs trigger supports batching, which is why you didn't have this problem with it.

Batching support in the Service Bus trigger is in a new version of that binding. That version will be available in extension bundles v2, which is available in a couple of weeks. You'll be able to change the bundle config in host.json to target v2 and use `many` cardinality with the SB trigger.

**Comment by ZachTB123** [comment]
@anthonychu Thanks for the update. Is [this](https://github.com/Azure/azure-functions-extension-bundles) the correct repo to watch for that release?

**Comment by anthonychu** [comment]
@ZachTB123 It is. Although releases appearing there may not necessarily indicate that the bundle is available, as it needs to be deployed to all workers in the platform as well as updated in the feed for Functions Core Tools to consume.

**Comment by pragnagopa** [comment]
Thanks for the follow up on this @anthonychu !

I will leave this issue open until @ZachTB123 verifies the issue is fixed with new version of bundles.

**Comment by pragnagopa** [comment]
@ZachTB123 - extension-bundles v2.0.0 is published: https://github.com/Azure/azure-functions-extension-bundles/releases/tag/2.0.0 , can you please verify?

**Comment by anthonychu** [comment]
Info here on how to upgrade: https://docs.microsoft.com/azure/azure-functions/functions-bindings-register#extension-bundles

**Comment by ZachTB123** [comment]
Looks like that fixed it. Thanks for the update!
