### ISSUE TITLE
Azure Functions runtime is unreachable. https://functions.azure.com/api/passthrough Request Method: POST Status Code: 500

### ISSUE THREAD

**Issue by trivedihimanshu** [Azure/azure-functions-host#6488]
@fabiocav I am facing similar issue regarding this. my issue is that as soon as I navigate to function app it shows me Azure Functions runtime is unreachable.

Function APP is sitting behind ASE and ASE has more then 60 APPs and 5 Isolated APP Service plans

I've raised a SEV A case with Support and so far we have performed following steps.

1. Redeployed Function APP from Kudu using Zip.
2. Redeployed Function APP from Azure DevOps.
3. Verified TCPPING to storage account from kudu and Function app was able to reach to Storage account without any issue.
4. AzureWebJobsStorage has valid connection string to desired Storage account.
5. Storage Account doesn't have Network restrictions.
6. Verified all the mandatory/required appsettings/configuration on Function APP.
7. FUNCTIONS_EXTENSION_VERSION has valid value against it.
8. FUNCTIONS_WORKER_RUNTIME has valid value against it.
9. added https://functions.ext.azure.com to the Function app CORS setting and restarted FUNCTION app.

Request URL: https://functions.azure.com/api/passthrough
Request Method: OPTIONS
Status Code: 200 
Remote Address: 13.107.246.10:443
Referrer Policy: no-referrer-when-downgrade

Request URL: https://functions.azure.com/api/passthrough
Request Method: POST
Status Code: 500 
Remote Address: 13.107.246.10:443
Referrer Policy: no-referrer-when-downgrade

When browser is sending request method as OPTIONS its receive 200 OK but when it send POST it receives 500 on same Request URL.

I believe this issue can't be marked as closed.

_Originally posted by @trivedihimanshu in https://github.com/Azure/azure-functions-host/issues/4855#issuecomment-670854959_

**Comment by roviracarlos** [comment]
I have the same problem, the same error.
In the place the portal call https://functions.azure.com/api/passthrough, before last Friday the portal call the url of the resource, like this functions are in ASE, call the internal name <yourapp>.scm.<yourdomain>, this resolve internally and call the ASE ILB.
If you check the old function portal, you don't have this problem and you see the call to your function domain internally.
Now is calling externally to a Front Door service and fail.

**Comment by roviracarlos** [comment]
This works now, refresh the browser to update the version and the error "Azure Functions runtime is unreachable" not appears again. But the call with the error continue with Status Code: 500.

**Comment by v-bbalaiagar** [comment]
Hi @trivedihimanshu, Apologies for the delayed response, Were you able to find a solution here. Kindly let us know if you could resolve it can we close this issue?

**Comment by trivedihimanshu** [comment]
@v-bbalaiagar, Yes this can be marked as closed, 
Microsoft PG group implemented a fix at the backend in order to fix this issue.

**Comment by v-bbalaiagar** [comment]
Hi @trivedihimanshu, Thank you for the update, Closing this issue as resolved, please feel free to reach back to us in case of any further queries related to this issue.
