### ISSUE TITLE
Relationship between Folder Name and namespace.

### ISSUE THREAD

**Issue by gukz** [Azure/azure-functions-host#6489]
#### Is your question related to a specific version? If so, please specify:
no
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
all
#### Question
I am reading the source of azure-functions-host, I found in some folder the folder name is coincide with the namespace, while some are quite not. It makes me difficult to get the namespace message from the code file's path(I need to check every files if they follow the rule). Is this done on purpose? If so, can I know why?
###### Example:
The folder `src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/` contains 5 kinds of namespace in 6 files!

**Comment by ankitkumarr** [comment]
Yes, I think it's done on purpose. Though, only @fabiocav (away for the next 2 weeks) can confirm :).

I understand namespace and folder structure as two different concepts, even though the default namespace reflects the folder structure.
Folder structure is more for organization of a repository making it easier to navigate. While namespace is more for scoping elements, organizing, and creating unique elements [[source](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/namespace)].

That said, I think some of the `DryIoc` files actually come from the [DryIoc repo](https://github.com/dadhi/DryIoc) and probably is why we didn't change or redo the namespaces.

I will close this issue as answered, if you have follow-up comments, please do not hesitate to ask and I can re-open this. Thanks!
