### ISSUE TITLE
2 way sync with git

### ISSUE THREAD

**Issue by garrardkitchen** [Azure/azure-functions-host#649]
#### Repro steps
1. Create function
2. Use DVCS
3. Rename function
4. Commit & Push changes
#### Expected behavior

Old function should no longer be present
#### Actual behavior

Old function remains and cannot be removed (via portal)
#### Related information

Can observe by either created via portal then moved to DVCS OR creating via nodejs Azure Function CLI.

Warmest regards,

Garrard.

**Comment by lindydonna** [comment]
If you click the Refresh button, does it still show the old function?  If so, please refresh the entire browser. (If it still reproduces, we'll file a new issue in the Portal repo: https://github.com/projectkudu/AzureFunctionsPortal

**Comment by garrardkitchen** [comment]
Hi @lindydonna, yes I did all that and still the same reported outcome.

**Comment by davidebbo** [comment]
Can you share your function app name (that's the **app** name, not function name!), either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by garrardkitchen** [comment]
Hi @davidebbo, the app name is speech-svrless and for completeness, the particular function that doesn't seem to want to go is HttpTrigger_RegisterJob.

Warmest regards,

Garrard.

**Comment by davidebbo** [comment]
Ok, so I *think* I know what's going on:

- At the time you set up source control, that function existed
- The initial repo that you deployed did *not* have this file
- This caused Kudu to treat it as a non-repo file, and leave it alone

Now the reason you can't delete it is that we disable non-readonly operations once you have source control turned on.

Stepping back, can you give more details about exactly how you enabled DVCS? How did you build your repo in the first place? Did you download the files you had created (and if so how)?

Granted, switching to source control is not as simple as it should be, and we'll improve this.

BTW, for now, you should be able to clean things up by just deleting the `D:\home\site\wwwroot\HttpTrigger_RegisterJob` folder from Kudu Console.

**Comment by garrardkitchen** [comment]
Hi @davidebbo, apologies for delay in getting back to you.

I'll do my best to reply this:

I started via the portal and created & edited functions in the portal editor.  I had created a few functions by this point but wanted to developer using editor/IDE with better intellisense / colour coding so I enabled DVCS (bitbucket).  I soon observed it was one-way sync'ing. During this journey of discovery I'd had messed about with App Service Editor (Preview) and tried to sync this way but I got nowhere. I also pushed files from local machine via git so new files & folders appeared.

I followed advice from https://github.com/Azure/azure-webjobs-sdk-script/issues/629 and from that point onward worked locally and pushed to AF via git.  I downloaded code, committed then pushed.  I then deleted the old functions and here we are today.

I hope the above helps.

I will go ahead and delete via kudu console.

Thank you.

Warmest regards,

Garrard.

**Comment by davidebbo** [comment]
Thanks Garrard, that helps clarify. Indeed, there is no easy way today to push changes you make in the App Service Editor back to Bitbucket. Well, it can be done in theory, but the steps are non-trivial.

We'll work to smoothen the experience in the future.
