### ISSUE TITLE
Unreliable Azure functions timer trigger , not firing off every 1 minute

### ISSUE THREAD

**Issue by alpizano** [Azure/azure-functions-host#6499]
#### Investigative information
Hi, we have a function app on Azure that has some Http triggers and a timer-based trigger. The timer trigger , triggers every 1 minute and is supposed to run a suite of our integration tests. The timer trigger calls a method called `handleTimer(String timerInfo)` , which takes a String object of timer info and then checks to see it our tests are able to run.

The problem is , it doesn't seem to be calling that function every minute. When I check the logs, the timer isn't even calling the function, so none of our test our being run. This is how the timer trigger is declared:

```
@FunctionName("genericTimerHandler")
    public void handleTimer(@TimerTrigger(name = "mytimer", schedule = "0 * * * * *")String timerInfo)
    {
        log.trace("Timer fired info={}", timerInfo);

        IntegrationTestRunner.getInstance().handleTimer(timerInfo);
    }
```

I won't write out all of the `handleTimer(String timerInfo)` method because its too verbose, but its signature is as-is:
```
// Timer trigger.
    public void handleTimer(String timerInfo)
    {
        log.info("Timer fired on {}", timerInfo);

       // a lot of logic here to run our test suite and selected times
   
}
```

When I search the logs on azure application insights, as I stated, I _*NEVER*_ see the above log message, so its as-if the function is never called. Of course, the tests we have never run if I don't see that log. When I see that log, (which implies the method is called), the Test _*RUNS*_. Can anyone help please???

Please provide the following:

- Timestamp: 1AM Central Time
- Function App version: ~3
- Function App name: radio2-dev-atg
- Function name(s) (as appropriate): genericTimerHandler (Timer), genericEventHandler (EventGrid), startTest (HTTP), testResults (HTTP)
- Invocation ID: Not sure where to find invocation ID?
- Region: East US

#### Repro steps

Provide the steps required to reproduce the problem:
Monitor the timer trigger that should run our test and watch it never run when the trigger is never called

#### Expected behavior
Test don't run

#### Actual behavior
Test don't run

#### Known workarounds
n/a

#### Related information 
n/a

Provide any related information 
n/a

* Programming language used - Java
* Links to source
* Bindings used

**Comment by soninaren** [comment]
@alpizano Have you tried running your function app locally? If yes can you share the output?
