### ISSUE TITLE
Azure Function with service bus trigger - autoComplete and maxAutoRenewDuration 

### ISSUE THREAD

**Issue by asipras** [Azure/azure-functions-host#6500]
#### Is your question related to a specific version? If so, please specify:
func version 3.0.2630
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
python
#### Question
I have Azure Function with service bus trigger running on AKS. I have few question around configuration settings in host.json. The function can run for longer than 10 mins hence i have set the functionTimeout setting to 01:00:00.

Currently I have set autoComplete = true in my host.json. As per documentation here, [https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=csharp]

> The Functions runtime receives a message in PeekLock mode. It calls Complete on the message if the function finishes successfully, or calls Abandon if the function fails. If the function runs longer than the PeekLock timeout, the lock is automatically renewed **as long as the function** is running.

When i run my function on development machine it runs for over 10 mins without any errors but then i see the following error by Azure function runtime in my terminal window

> Message processing error (Action=Complete, ClientId=MessageReceiver1calculation_requests, EntityPath=calculation_requests, Endpoint=mhservice12.servicebus.windows.net)
[8/11/2020 8:21:33 PM] Microsoft.Azure.ServiceBus: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. Reference:633c9f49-7063-441e-a02f-9e33c2cca04b, TrackingId:9a1f2e8d0000e97b0005ea6a5f32fc40_G11_B26, SystemTracker:mhservice12:Queue:calculation_requests, Timestamp:2020-08-11T20:21:33.

**Do i have to set maxAutoRenewDuration setting?**

 The documentation says that the max value for maxAutoRenewDuration is 5 minutes as per service bus documentation but I cannot find this anywhere.

> The maxAutoRenewDuration is configurable in host.json, which maps to OnMessageOptions.MaxAutoRenewDuration. The maximum allowed for this setting is 5 minutes according to the **Service Bus documentation**, whereas you can increase the Functions time limit from the default of 5 minutes to 10 minutes. For Service Bus functions you wouldn’t want to do that then, because you’d exceed the Service Bus renewal limit.

Also, if we can configure functionTimeout to whatever value when running on AKS shouldn't maxAutoRenewDuration be configurable to whatever value the user wants?

Can anybody explain me how to configure Azure Function runtime with service bus trigger with autoComplete=true setting so that it does not throw exception if the function finishes within functionTimeout value.

**Comment by brettsam** [comment]
That documentation seems wrong. It looks like the *default* is 5 minutes but you can set it to be as long as you need. Also, according to [this comment in the Service Bus code](https://github.com/Azure/azure-sdk-for-net/blob/6bebad4c0f6bd83ac46e9bab11870d1c49f2137b/sdk/servicebus/Microsoft.Azure.ServiceBus/src/MessageHandlerOptions.cs#L67-L68), you may see these errors occasionally in the background:
```
/// <remarks>The message renew can continue for sometime in the background
/// after completion of message and result in a few false MessageLockLostExceptions temporarily.</remarks>
```
I'm trying to find official Service Bus documentation on this and will link back here if I find it...

**Comment by brettsam** [comment]
Can you try extending to longer and see if that works? And I will follow-up with documentation change.

**Comment by asipras** [comment]
> Can you try extending to longer and see if that works? And I will follow-up with documentation change.

@brettsam  I never had maxAutoRenewDuration in my host.json and everything worked fine. The issue started happening recently when function runtime tried to complete the message after function execution (more than 10 mins).

For now I have put maxAutoRenewDuration to same as functionTimeout which is 01:00:00. After applying this setting the function runtime completes the message as expected.

**Comment by asipras** [comment]
@brettsam 

it will be great if you can shed some light on relationship between Message Lock Duration (see the picture below), functionTimeout and maxAutoRenewDuration. With the Message Lock Duration is set to 1 minute, the function is configured to autocomplete the message with functionTimeout set to 00:10:00 (10 minutes) and maxAutoRenewDuration set to 00:5:00 (5 minutes). What does this mean when functionTimeout is greater than maxAutoRenewDuration? 

![image](https://user-images.githubusercontent.com/16964799/90580966-bdda6180-e18f-11ea-83c7-d1bfc4531989.png)

**Comment by brettsam** [comment]
It means you run the risk of losing the lock on the message. You should make sure that `maxAutoRenewDuration` is as long as (or longer) than function timeout. A quick summary:

When Service Bus dequeues a message, it locks it (but leaves it in the queue). This means no one else can access it. The lock will last for `Message lock duration` -- in your case 1 minute. If you do nothing to that message (i.e. never complete it) then the lock will release and someone else can process that message.

The Service Bus SDK (which functions uses) will automatically renew that lock for you if you're not done processing the message. This is what `maxAutoRenewDuration` is for. So even if the SB lock is set to 1 minute -- the client-side SDK will auto-renew the lock for you up to `maxAutoRenewDuration`. If after that time you still haven't marked it as complete (or something else), it will then release the lock.

So you want to make sure that you're renewing the message for as long as your function can run.

**Comment by asipras** [comment]
Thanks for your clear explanation @brettsam. This all makes sense now. 

I would like to comment though that when autocomplete is set to true, the maxautoRenewDuration should be atleast set to be equal to or larger then functionTimeout. The reason being that the user is already expecting the function to run till functionTimeout and if the maxautoRenewDuration is set to smaller value then the function runtime wont be able to complete message when the function execution is finished and will throw exception. Also, depending on the retry setting the same function will be executed again because runtime threw an exception when it is not able to complete the message. There will be a loop till the retry attempts are reached. There should be atleast some kind of warning saying that maxautoRenewDuration is less than functionTimeout and there is chance that the lock will be expired before function execution finishes.

**Comment by brettsam** [comment]
I've gone ahead and filed a doc issue for this -- so we can get this cleared up there. Thanks for pointing this out.

Doc issue: https://github.com/MicrosoftDocs/azure-docs/issues/62110
