### ISSUE TITLE
azure function consumption plan not logging sql queries in application insights since 28-july-2020

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/azure-functions-host#6501]
Earlier this was working but since 28/jul/2020 we are not able to see sql queries in application insights.

please see more details here 
https://github.com/Azure/azure-webjobs-sdk/issues/2548

**Comment by pragnagopa** [comment]
More details https://github.com/microsoft/ApplicationInsights-dotnet/issues/1425

Closing this issue as dup of Azure/azure-webjobs-sdk#2548
