### ISSUE TITLE
HttpRequestMessage vs HttpRequest - Azure Functions Roslyn Analyzer

### ISSUE THREAD

**Issue by prabh-62** [Azure/azure-functions-host#6502]
#### What problem would the feature you're requesting solve? Please describe.
There is no clear documentation on what is the right choice - `HttpRequestMessage` or `HttpRequest` and since both `System.Net.Http.HttpRequestMessage` and `Microsoft.AspNetCore.Http.HttpRequest` request objects are supported, it becomes difficult to migrate when project grows large

#### Describe the solution you'd like
Rosyln code analyzer that detects usage of `HttpRequestMessage` and advices to use `HttpRequest`

#### Describe alternatives you've considered
N/A

#### Additional context
Azure Durable Functions team provide an analyzer as a nuget package: [Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers) to detect usage of not recommended APIs
<img width="654" alt="durable_fn_analyzer" src="https://user-images.githubusercontent.com/13006107/90199034-85a6dd80-dda1-11ea-817a-e3a8de376ae4.png">

Similarly, there should be a roslyn analyzer for Azure Functions raises a warning on usage of HttpRequestMessage
<img width="1378" alt="azure_functiuon_v3_httprequestmessage" src="https://user-images.githubusercontent.com/13006107/90199174-f77f2700-dda1-11ea-997a-e25c02a3aabb.png">

**Comment by ThejaChoudary** [comment]
@prabh-62 you can certainly use one of the other depending on whichever one suits better for your unique requirements.
While HttpRequest [API ](https://docs.microsoft.com/en-us/dotnet/api/system.web.httprequest?view=netframework-4.8&viewFallbackFrom=netcore-2.2)provides more properties & granular info about the request directly,HttpRequestMessage [API ](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessage?view=netcore-2.2)can be more straight-forward to use.

**Comment by prabh-62** [comment]
Does this mean Azure Functions team is keen on fixing these kind of issues? https://github.com/Azure/azure-functions-host/issues/6486

**Comment by v-anvari** [comment]
Hi @prabh-62 , Apologies for the delayed response, Kindy let us know if you are looking for any further information regarding this issue or can this issue be closed. 

Regarding the fixes for 6486, team is making required changes for making the approach better and few cases will be fixed only if the impact is higher.

**Comment by prabh-62** [comment]
Sorry I don't understand this statement "Apologies for the delayed response, Kindy let us know if you are looking for any further information regarding this issue or can this issue be closed."

Initially I asked which one API `HttpRequestMessage` or `HttpRequest` should developers be using? I still haven't received any response.

**Comment by v-anvari** [comment]
Hi @prabh-62 , As suggested in one the earlier comments, you can use either one of them. HttpRequestMessage is legacy and intended for backwards compatibility with Functions v1. New apps should probably use HttpRequest, which was introduced in Functions v2. You might be getting that suggestion due the usage of version 2 or higher. 

So, in short, you can use HttpRequest
