### ISSUE TITLE
Self-Contained Azure Functions app does not have Microsoft.Azure.WebJobs.Script.WebHost.dll

### ISSUE THREAD

**Issue by prabh-62** [Azure/azure-functions-host#6503]
#### Repro steps

Provide the steps required to reproduce the problem:

- Ensure you have Azure Functions V3 `func` CLI from [Github releases](https://github.com/Azure/azure-functions-core-tools/releases) and .NET Core 3.1 SDK
- `> func --version`
   `3.0.2798`
- `> func init ImageService --dotnet`
- `> cd ImageService`
- `> func new -l C#` Create new function with HTTP trigger
- Update nuget [Microsoft.NET.Sdk.Functions](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/) to 3.0.9
- Publish the function app `dotnet publish -c Release --runtime win-x64 --self-contained true` 
- Now navigate to `bin/Release/netcoreapp3.1/win-x64/publish/bin` and there is no DLL named `Microsoft.Azure.WebJobs.Script.WebHost.dll`

- Update code in HTTP trigger with this snippet
```csharp
namespace ImageService
{
    public static class Hello
    {
        [FunctionName("Hello")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = null)] HttpRequest req,
            ILogger log)
        {
            var appDomain = AppDomain.CurrentDomain;
            var allAssembliesArray = appDomain.GetAssemblies().Where(a => !a.IsDynamic);
            var allAssemblySpecs = allAssembliesArray.Select(a => new
            {
                a.FullName, a.Location
            });
            return new OkObjectResult(allAssemblySpecs);
        }
    }
}
```
- Publish the function app again `dotnet publish -c Release --runtime win-x64 --self-contained true`. Zip `bin/Release/netcoreapp3.1/win-x64/publish/bin` folder and deploy it to a azure function app (I used Kudu zip deploy)
- Hit the API endpoint - [https://app.azurewebsites.net/api/Hello](https://hello1debug.azurewebsites.net/api/Hello) (my deployed app but could be taken down)
- We notice that `Microsoft.Azure.WebJobs.Script.WebHost.dll` is loaded from `D:\Program Files (x86)\SiteExtensions\Functions\3.0.14251\64bit\Microsoft.Azure.WebJobs.Script.WebHost.dll` and our project's DLL is loaded from `D:\home\site\wwwroot\bin\ImageService.dll`. The definition of self-contained is that all DLLs should be loaded from `wwwrooot\bin\` folder.

#### Expected behavior
`Microsoft.Azure.WebJobs.Script.WebHost.dll` DLL should be part of publish folder

#### Actual behavior
`Microsoft.Azure.WebJobs.Script.WebHost.dll` DLL is not part of publish folder

#### Known workarounds
None

#### Related information 

Provide any related information 
* Azure Functions Host Runtime Version(when deployed): `3.0.14251.0`
* Programming language used: `C#`
* Bindings used: `HTTPTrigger`
<img width="1436" alt="self_contained_azure_function" src="https://user-images.githubusercontent.com/13006107/90200556-3b742b00-dda6-11ea-9d8e-015ebb352028.png">

**Comment by v-bbalaiagar** [comment]
Hi @prabh-62, Closing this issue as duplicate. For more updates please follow the space -  https://github.com/Azure/azure-functions-host/issues/6504
