### ISSUE TITLE
Always load application DLLs from wwwroot\bin folder

### ISSUE THREAD

**Issue by prabh-62** [Azure/azure-functions-host#6504]
#### Repro steps

Provide the steps required to reproduce the problem:

- Ensure you have Azure Functions V3 `func` CLI from [Github releases](https://github.com/Azure/azure-functions-core-tools/releases) and .NET Core 3.1 SDK
- `> func --version`
   `3.0.2798`
- `> func init ImageService --dotnet`
- `> cd ImageService`
- `> func new -l C#` Create new function with HTTP trigger
- Update nuget [Microsoft.NET.Sdk.Functions](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/) to 3.0.9
- Add [OpenIdConnect](https://www.nuget.org/packages/Microsoft.IdentityModel.Protocols.OpenIdConnect) nuget: `dotnet add package Microsoft.IdentityModel.Protocols.OpenIdConnect --version 5.5.0`

- Update code in HTTP trigger with this snippet
```csharp
namespace ImageService
{
    public static class Hello
    {
        [FunctionName("Hello")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = null)]
            HttpRequest req,
            ILogger log)
        {
            var openIdAssembly = typeof(OpenIdConnectConfiguration).Assembly;
            return new OkObjectResult(new
            {
                openIdAssembly.FullName,
                openIdAssembly.Location
            });
        }
    }
}
```
<img width="1433" alt="openidconnect_550" src="https://user-images.githubusercontent.com/13006107/90202753-927cfe80-ddac-11ea-8322-a337219d5106.png">

- Deploy the azure function app using VSCode [Azure Functions extensions](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurefunctions)
- Hit the API endpoint - [https://open-id-connect.azurewebsites.net/api/Hello](https://open-id-connect.azurewebsites.net/api/Hello) (my deployed app but could be taken down)
- We notice that `Microsoft.IdentityModel.Protocols.OpenIdConnect.dll` is loaded from `D:\\Program Files (x86)\\SiteExtensions\\Functions\\3.0.14251\\32bit\\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll` instead of `D:\\home\\site\\wwwroot\\bin\\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll`. 

#### Expected behavior
`Microsoft.IdentityModel.Protocols.OpenIdConnect.dll` should be loaded from `D:\\home\\site\\wwwroot\\bin\\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll`

#### Actual behavior
`Microsoft.IdentityModel.Protocols.OpenIdConnect.dll` is loaded from `D:\\Program Files (x86)\\SiteExtensions\\Functions\\3.0.14251\\32bit\\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll`

#### Known workarounds
None

#### Related information 

Provide any related information 
* Azure Functions Host Runtime Version(when deployed): `3.0.14251.0`
* Programming language used: `C#`
* Bindings used: `HTTPTrigger`

<img width="1439" alt="dll_program_files" src="https://user-images.githubusercontent.com/13006107/90202965-51d1b500-ddad-11ea-8a17-30f90fa48f03.png">

**Comment by prabh-62** [comment]
I logged another issue on [azure-functions-vs-build-sdk](https://github.com/Azure/azure-functions-vs-build-sdk) repo since azure functions were erroring out while loading `Microsoft.IdentityModel.Protocols.OpenIdConnect.dll`
https://github.com/Azure/azure-functions-vs-build-sdk/issues/460

That is why I added `<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>` msbuild flag in `csproj` file

**Comment by prabh-62** [comment]
We have a large app and we use nuget [Microsoft.AspNetCore.Authentication.JwtBearer 3.1.6](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.JwtBearer/3.1.6) to validate auth tokens which has a dependency on [Microsoft.IdentityModel.Protocols.OpenIdConnect](https://www.nuget.org/packages/Microsoft.IdentityModel.Protocols.OpenIdConnect/)
<img width="776" alt="openIdConnect_jwtbearer" src="https://user-images.githubusercontent.com/13006107/90208043-d9232680-ddb5-11ea-8200-c88c3dba50e6.png">


This is an example code to validate JWT tokens
```csharp
var stsDiscoveryEndpoint = $"{_issuer}.well-known/openid-configuration?p={b2COptions.TokenCustomPolicyId}";
var documentRetriever = new HttpDocumentRetriever { RequireHttps = _issuer.StartsWith("https://") };

var configurationManager =  new ConfigurationManager<OpenIdConnectConfiguration>(
                                stsDiscoveryEndpoint,
                                new OpenIdConnectConfigurationRetriever(),
                                documentRetriever
                                );

var config = await _configurationManager.GetConfigurationAsync(CancellationToken.None).ConfigureAwait(false);

var validationParameters = new TokenValidationParameters
            {
                RequireSignedTokens = true,
                ValidIssuer = _issuer,
                ValidAudience = _audience,
                ValidateAudience = true,
                ValidateIssuer = true,
                ValidateIssuerSigningKey = true,
                IssuerSigningKeys = config.SigningKeys, //this line throws exception
                ValidateLifetime = true
            };
var tokendHandler = new JwtSecurityTokenHandler();
var result = tokendHandler.ValidateToken(value.Parameter, validationParameters, out var jwt);
```

As soon as we upgraded from Azure Functions V2 to Azure Functions V3, we started getting exceptions from this code intermittently in production environment (Not always, sometimes after 4 hours of deployment)
```log
System.MissingMethodException
Method not found: 'System.Collections.Generic.ICollection`1<Microsoft.IdentityModel.Tokens.SecurityKey> Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration.get_SigningKeys()'
```
<img width="513" alt="error_signing_keys_nuget" src="https://user-images.githubusercontent.com/13006107/90208427-d1b04d00-ddb6-11ea-8f98-d3a4a55fa270.png">

**Comment by prabh-62** [comment]
Discussion occurred in another issue: https://github.com/Azure/azure-functions-host/issues/6555

**Comment by v-anvari** [comment]
Hi @prabh-62 , As this issue is being addressed in [#6555](https://github.com/Azure/azure-functions-host/issues/6555), are we good to close this issue as it is a duplicate. Please let us know if you are looking out for a resolution here.

**Comment by prabh-62** [comment]
This issue is more closely related to https://github.com/Azure/azure-functions-host/issues/6503 .You can close this as I am not sure if we can achieve this behavior in Azure Functions

**Comment by v-anvari** [comment]
Thank you for the confirmation
