### ISSUE TITLE
Is there a way to catch Dependency injection issues ?

### ISSUE THREAD

**Issue by jonathanantoine** [Azure/azure-functions-host#6505]
#### Is your question related to a specific version? If so, please specify:
I am using .net core 3.1
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question
Is there a way to catch Dependency injection issues ? For example, if I remove my startup for the extensions.json file, the function will not be able to be instancied and I will see an error in the log telling that it can't create one of the service injected in its constructor.

Is there  a way to catch this kind of errors ?

Thanks !

**Comment by jonathanantoine** [comment]
Any update @ankitkumarr  :) ?

**Comment by ankitkumarr** [comment]
Sorry, @jonathanantoine, I am catching up to all of my assigned issues.

I imagine that you are asking if these issues can be caught during build time, as you can see the error during runtime? Please correct me if I am wrong. I am not sure if there's a way we'd be able to tell ahead of time. @brettsam / @fabiocav (DI experts) do you have thoughts on this one?

**Comment by brettsam** [comment]
Is there a reason that you removed the startup from extensions.json?

That file is auto-generated and tells the functions host where to look for Startups. I'm not sure there's anything we can do here short of re-scanning all assemblies at startup, which is a big hit on startup perf and the reason that extensions.json exists in the first place.

Maybe the error you get is bad so it's hard to debug? Do you just get a null reference or something like that?

**Comment by jonathanantoine** [comment]
Hello,

I have scenarios where the extensions.json files is not correctly generated and I need to do this. I just get an exception (in the logs) telling me that the function can't be instanciated.

**Comment by brettsam** [comment]
We should fix that underlying extensions.json issue -- do you have a repro you can share with us?

**Comment by jonathanantoine** [comment]
Hello,

I don't have a repro I can share but this is just an example. Let's just say there is an exception in a dbcontextoptions builder or a transient db context needed in your function and boom it will crash without being able to catch the exception :(

**Comment by jonathanantoine** [comment]
Hello again,

Right now, I use this (ugly) workaround : 

1. Find the service descriptor of the IJobActivator,
1. Register it as a IJobActivatorEx it also implements.
1. Override the IJobActivator with a wrapper of my own doing some log in case of error.

**Registering overrides :**
```csharp
var jobActivatorServiceRegistration = services.First(s => s.ServiceType == typeof(IJobActivator));
services.Add(
    new ServiceDescriptor(
        typeof(IJobActivatorEx),
        jobActivatorServiceRegistration.ImplementationType,
        ServiceLifetime.Singleton));
services.AddSingleton<IJobActivator, JobActivatorWrapper>();
```

**My own wrapper :**
```csharp
internal class JobActivatorWrapper : IJobActivator
 private readonly IJobActivator _jobActivator;
 private readonly IMyLogger _myLogger;
 public JobActivatorWrapper(IJobActivatorEx jobActivatorReference, IMyLogger myLogger
 {
     _jobActivator = jobActivatorReference;
     _myLogger = myLogger;
 }
 public T CreateInstance<T>()
 {
     try
     {
         return _jobActivator.CreateInstance<T>();
     }
     catch (Exception e)
     {
         var errorMessage = "This is really a bad thing, please contact the support team." +  e;
         // Fire and forget
         _myLogger.SendErrorAsync(
             $"Can't create {typeof(T).Name}",
             errorMessage).ConfigureAwait(false);
         throw;
     }
 }
}
```

**Comment by v-anvari** [comment]
Hi @jonathanantoine , Apologies for the delayed response. Were you able find a solution? do let us know if a follow up is required. I shall follow with the right team members to resolve this issue. The issue was somehow lost in the trace
