### ISSUE TITLE
Extremely poor network performance in azure functions (Azure Blob w/python bindings and with functions blob bindings)

### ISSUE THREAD

**Issue by SamGinzburg** [Azure/azure-functions-host#6510]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app => `Platform features` => `Diagnose and solve problems` and the relevant dashboards before opening your issue.

#### Investigative information

Please provide the following:

Running locally on my machine, as well as virtual machines in azure

#### Repro steps

Using the python sdk for azure blob inside of functions as well as using the blob bindings provided

#### Expected behavior

I have a library for performing network IO (uploading data to azure blob), that is used in both a standard python application as well as an azure function. I have noticed that network performance is severely degraded from inside the azure function host runtime in comparison to running outside of it - despite sharing identical code for one test, and using the azure blob bindings for another.

The azure function is written entirely using async code - so there is no blocking IO anywhere within the function.

I also wrote a test script that runs outside of the functions runtime that shows the library being used has the expected performance when run outside of the functions runtime on the same machine. The machines themselves experience no network performance degradation, only functions within the host runtime are affected.

Provide a description of any known workarounds.
None

#### Related information 

Can repro for Python 3.7.x, Python 3.8.x, functions host v2 & v3, running in both WSL2 & linux VMs in azure

All blob IO in azure functions seems to experience degraded download performance, however the identical blob code runs normally outside of functions.

**Comment by anthonychu** [comment]
@SamGinzburg is it possible to provide a repo with a sample app that reproduces this (including the file it’s uploading) so we can investigate further?

/cc @stefanushinardi @anirudhgarg

**Comment by SamGinzburg** [comment]
Sure here is a very simple example: this function downloads a blob from inside of a very skeletal azure function (env variables omitted)


```

import logging

import azure.functions as func
from azure.storage.blob.aio import BlobServiceClient as AsyncBlobServiceClient
from azure.storage.blob.aio import BlobClient as AsyncBlobClient
from azure.storage.blob.aio import BlobClient as AsyncContainerClient


async def main(req: func.HttpRequest) -> func.HttpResponse:
     logging.info('Python HTTP trigger function processed a request.')

     conn_str = ""
     async_blob_service_client = AsyncBlobServiceClient.from_connection_string(conn_str)
     blob_client = async_blob_service_client.get_blob_client(container="",
                                                             blob="")
     async with blob_client as blob:
          stream = await blob.download_blob()
          result = await stream.readall()
     return func.HttpResponse(
          str(result),
          status_code=200
     )
```

I also have a very primitive setup that I run to test my throughput using the same blob library for azure functions to see if it was a local network issue, and I was able to get between 6x-7x the total throughput on blobs around ~20-23MiB in size. I get similarly poor performance when running using the azure functions blob bindings as well.

I went a bit further to dig into this problem as I have had this issue for several weeks and profiled the demo I attached above.
I use postman to take a closer look at the request and I see a breakdown that looks like this:

3ms  -- Socket Initialization
500ms - DNS lookup
~1ms - TCP Handshake
~4s   - Transfer start/TTFB
104ms - download time


Based on the transfer time/TTFB I can conclude that the function is getting ~5MiB/s of throughput, in comparison to 30MiB/s+ when running in a standard python application. I have also looked at my azure blob metrics in azure itself to see if there were any server latency issues and there were none, so based on all of this, I believe that there must be some sort of networking performance regression (or high runtime overhead) within the function host itself


Benchmarking note: all benchmarks were conducted locally on my laptop connecting to eastus2, to a standard tier blob account - so there should be close to 0 latency between postman/the functions runtime itself since those two were both on localhost.

**Comment by gohar94** [comment]
I think the bottleneck is gRPC between Python worker and C#. It would be good to get this verified by the Function's team but we can also check this on our local setup.
In my experiments, I've found gRPC between Python and C# to be really slow.

**Comment by SamGinzburg** [comment]
![image](https://user-images.githubusercontent.com/9014527/90348756-3d87f500-e005-11ea-992d-599492069f38.png)


I also tested a variant of the repro above returning an empty response instead of the contents - it has no impact on the throughput. Repeated invocations don't help with performance so this isn't a cold start issue either.

**Comment by SamGinzburg** [comment]
I also tested this with the azure functions blob binding API and got similarly poor results: 
![image](https://user-images.githubusercontent.com/9014527/90349618-7fff0100-e008-11ea-8884-88ccdd4ee5ab.png)


```
import logging
import azure.functions as func
import aiohttp
import asyncio
import traceback

async def download(inputkey):
    return inputkey.read()

async def main(req: func.HttpRequest, inputkey: func.InputStream) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')
    logging.info("Performing read on key: {k}".format(k=req.params['inkey']))

    try:
        blob = await download(inputkey)
    except Exception as e:
        logging.info(str(e))
        logging.info (str(traceback.format_exc()))

        blob = str("key not found")

    return func.HttpResponse(
            blob,
            status_code=200
    )

```





This leads me to believe that this is not an issue with any of the python code in the blob SDK, but the azure functions host runtime itself

**Comment by anthonychu** [comment]
My thought initially was the gRPC to host overhead as well, but the fact that an empty response didn’t make a difference appears to rule that out. + @vrdmr @Hazhzeng

**Comment by SamGinzburg** [comment]
Update: we've continued testing things and we aren't sure exactly what is going on - we found that the azure functions bindings perform about twice as well as the python blob IO after controlling for some other factors (still slower than the IO in python code running in our application) - but we are also investigating non-functions host problems 

We will close this ticket until we have further details (we will reopen if we have more specific details)

**Comment by anthonychu** [comment]
@stefanushinardi not sure if you have time to try to repro it. But if you’re able to confirm code runs slower by simply being in a function app, please reopen.

**Comment by SamGinzburg** [comment]
@anthonychu we ended up finding that it was a combination of a few things in our own code, everything should be good!
