### ISSUE TITLE
Fix Flaky Validate_HostLogs Test

### ISSUE THREAD

**Issue by gzuber** [Azure/azure-functions-host#6521]
Microsoft.Azure.WebJobs.Script.Tests.ApplicationInsights.ApplicationInsightsNodeEndToEndTests.Validate_HostLogs

has been failing in devops intermittently lately but passes locally. It was disabled in the meantime but needs to be looked at to improve consistency. This is in v2 and v3.

**Comment by pragnagopa** [comment]
PR needs to be reviewed. Moving next sprint 87.

**Comment by yojagad** [comment]
Discussed with Brett offline. Thought it might be a good idea to first check whether WarmupScenarios not disposing the _testFunctionHost was causing the side effect of the test holding onto the lease.

Made the change and reenabled the test. If it's found that the test starts failing again, then we could potentially bring back the change I originally had (ie., to override the HostIdProvider).

**Comment by alrod** [comment]
@yojagad, @brettsam reactivating the issue
