### ISSUE TITLE
Fix Flaky FunctionLogging_Succeeds Test

### ISSUE THREAD

**Issue by gzuber** [Azure/azure-functions-host#6523]
Microsoft.Azure.WebJobs.Script.Tests.EndToEnd.CSharpEndToEndTests.FunctionLogging_Succeeds

has been failing in devops intermittently lately but passes locally. It was disabled in the meantime but needs to be looked at to improve consistency.

**Comment by pragnagopa** [comment]
Needs more investigation. Moving to Sprint 87.

**Comment by brettsam** [comment]
@alrod actually fixed this with https://github.com/Azure/azure-functions-host/pull/6787.
