### ISSUE TITLE
API to help display important error or misconfigurations on the Fx overview page

### ISSUE THREAD

**Issue by apawast** [Azure/azure-functions-host#6534]
Portal ask: For the Function App Overview page, portal wants to bubble up important errors in the notifications tab. The request is for an update to APIs to get a summary of the most important errors and misconfigurations for all the functions in an app.

**Comment by soninaren** [comment]
Is the expectation here to introduce a new API or update an existing API? If an update is expected which api are we talking about in this case?

The status endpoint currently show error message in case function app is not in running state.

@apawast can you provide a more detailed description, possibly with a sample?

**Comment by brettsam** [comment]
Part of this will be working with @ehamai and @apawast to come up with exactly what we need to be returning and how it will be used. We likely already have this data -- and may just need to surface it through the status calls the portal already makes.

/cc @fabiocav

**Comment by pragnagopa** [comment]
@soninaren  please follow up with @brettsam.

**Comment by brettsam** [comment]
The idea here is that we'd have another bucket of errors/warnings on the status report back to the portal. The first two interesting things specifically around logging that we can store here:
1. You have sampling enabled in App Insights.
2. We're unable to connect to App Insights (either wrong key or some networking/VPN issue) -- need to figure out right way to determine this from App Insights.

@ehamai -- would attaching these details to the /host/status call make sense? I think we now have an Errors field there, but we only ever put the last error the host saw during startup there. And it's also only a string. It seems like we'd want some more metadata about the error, too -- like a timestamp, some error code, whether it's a warning or error, a link to doc, etc?

**Comment by fabiocav** [comment]
It makes sense to augment (not modify) the existing API with those details. One thing we'll need to discuss is persistence for those errors across instances and restarts. Currently, the error information is kept in memory, for a single node only, and that wouldn't be enough to support the scenarios we need to address with this change.

**Comment by ehamai** [comment]
Thanks @fabiocav, I think I agree with you.  Basically we're already calling the /host/default/properties/status API to get a list of runtime statuses which is driving some of the red notifications you see on the Function app overview blade.  I look at this as being the new (and hopefully better) red box that we used to see all the time in the old Functions portal experience.

If we add more error level detail to that API that would be helpful for customers to understand the state of their app, it should just automatically light up for customers without us having to add anything new to absorb it.

**Comment by fabiocav** [comment]
Closing in favor of #6536
