### ISSUE TITLE
Azure Functions v3 Startup does not execute if csproj name starts with "System"

### ISSUE THREAD

**Issue by TOVIRAH** [Azure/azure-functions-host#6549]
I recently created an Azure Function using SDK version 3.0.9 and with v3 specified in the main csproj file. The sln is named "SystemOfRecordContext" and the project containing the http triggered function is named "SystemOfRecordContext.Functions". I added the Microsoft.Azure.Functions.Extensions nuget package to the project to implement dependency injection in the Startup file, but the code in `Startup.Configure(IFunctionsHostBuilder builder)` never executed. The resulting error was displayed in the console window when running locally (this has not been deployed):

```
[8/21/2020 9:55:00 PM] Executed 'Function1' (Failed, Id=9cfa801d-3a17-4ced-b696-2791582b7aa7, Duration=69ms)
[8/21/2020 9:55:00 PM] Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type 'Serilog.ILogger' while attempting to activate 'SystemOfRecordContext.Functions.Function1'.
[8/21/2020 9:55:00 PM] An unhandled host error has occurred.
```

#### Investigative information

Please provide the following:

- Timestamp: 8/21/2020 9:55:00 PM UTC
- Function App version: v3
- Function App name: SystemOfRecordContext
- Function name(s) (as appropriate): Left as "Function1" for testing this issue.
- Invocation ID: n/a
- Region: not deployed yet

#### Repro steps

1. Create a function app and name the project containing the function(s) with any name that begins with "System" (I have not yet tried duplicating this behavior with a name that just _contains_ "System"). 
2. Implement `FunctionsStartup` in the `Startup.cs` file and register a service in the DI container. 
3. Use constructor injection in the function for the registered service and, of course, remove the `static`  keywords from the class header and method header. 
4. Run the function. It will start fine, but not execute any code in the `Configure(IFunctionsHostBuilder builder)` method of the `Startup.cs` class and 
5. Call the http triggered function's webhook and you will receive the error above.

- Changing the `namespace` of the `Startup.cs` file did not fix the issue, **but changing the name of the csproj did**. 
- I copied and pasted the exact same code below into classes in a csproj called "SysOfRecordContext" and the DI worked fine. I also tried changing the name of the original csproj back and forth and perfectly reproduced the error.

#### Expected behavior

`Configure(IFunctionsHostBuilder builder)` in `Startup.cs` to execute and instances of the dependencies to be injected into the Function's class at runtime.

#### Actual behavior

`Configure(IFunctionsHostBuilder builder)` in `Startup.cs` does not execute, and thus, the DI container is unable to resolve services for the types in the constructor of the Function class. The `extensions.json` file generated on build (located in the `{csprojName}/bin/Debug/netcoreapp3.1/bin`) directory was not populated when building with the problematic csproj name, but when building with a name that did not begin with "System", it populated fine. (I tested this building in both debug and release)

#### Known workarounds

Don't use a name for your project that begins with (or possibly contains) the word "System"

#### Related information 

Provide any related information 

* .net core 3.1
* Http Triggered Function

```csharp
using System.IO;
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using SystemOfRecordContext.Injection.Extensions;

[assembly: FunctionsStartup(typeof(SystemOfRecordContext.Functions.Startup))]

namespace SystemOfRecordContext.Functions
{
    
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var configBuilder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
                .AddEnvironmentVariables();
            var configuration = configBuilder.Build();

            var services = builder.Services;
            services.RegisterLogger(configuration);

            services.BuildServiceProvider();
        }
    }
}

// ********************************************************************
// Function class
// ********************************************************************

using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Serilog;

namespace SystemOfRecordContext.Functions
{
    public class Function1
    {
        private readonly ILogger _logger;

        public Function1(ILogger logger)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        [FunctionName("Function1")]
        public async Task<IActionResult> RunAsync([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = null)] HttpRequest req)
        {
            _logger.Information("Running Function1");
            return OkObjectResult("test");
        }
    }
}
```

**Comment by bran-ch** [comment]
Looks like it's probably caused by this method in `ExtensionsMetadataGenerator.cs`

```
private static readonly string[] ExcludedAssemblies = new[] { "Microsoft.Azure.WebJobs.Extensions.dll", "Microsoft.Azure.WebJobs.Extensions.Http.dll" };
...
public static bool AssemblyShouldBeSkipped(string fileName) => fileName.StartsWith("System", StringComparison.OrdinalIgnoreCase) || ExcludedAssemblies.Contains(fileName, StringComparer.OrdinalIgnoreCase);
```

I guess the small fix would be to skip files that start with `System.` instead

**Comment by BitProgress** [comment]
After hours of search, I found out the same!!!
Hopefully only a few people are stupid enough to start a project name with "System"*...

**Comment by jsgoupil** [comment]
I don't have something starting with System, but I'm missing that Startup as well...
But for those searching the reason why this is not being generated. Turn on the Diagnostics log for build in Visual Studio. You will get a good insight what is going on if you search for `extensions.json`

Mine would say something like:
```
  Unable to find fallback for assembly 'Microsoft.AspNetCore.Mvc.Core'. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
2>    File name: 'Microsoft.AspNetCore.Mvc.Core, Culture=neutral, PublicKeyToken=null'
2>       at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
2>       at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
2>       at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark, IntPtr pPrivHostBinder)
2>       at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, StackCrawlMark& stackMark)
2>       at System.Reflection.Assembly.Load(String assemblyString)
2>       at ExtensionsMetadataGenerator.Console.Program.AssemblyLoader.<>c__DisplayClass1_0.<Initialize>b__0(Object sender, ResolveEventArgs args) in d:\a\1\s\tools\ExtensionsMetadataGenerator\src\ExtensionsMetadataGenerator.Console\Program.cs:line 78
2>
2>
2>        Could not evaluate 'HBTI.ServiceTech.AzureFunctions.dll' for extension metadata. If this assembly contains a Functions extension, ensure that all dependent assemblies exist in 'F:\git\clients\hbti\Portal\hbti-web-master\HBTI.ServiceTech.AzureFunctions\bin\Debug\netcoreapp3.1\bin'. If this assembly does not contain any Functions extensions, this message can be ignored. Exception message: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
```

I cloned the Azure Function repo, and I figured that the generator actually works... So maybe they are a little late on shipping their new functionality. So my only recourse right now is to do a post build drop of the extensions.json file.
