### ISSUE TITLE
ServiceUnavailable from host runtime.

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-host#6551]
After the dotnet based consumption plan deployed, then go to General settings and select the .NET Core Version. 
![image](https://user-images.githubusercontent.com/1390976/90961724-be108080-e45f-11ea-97ea-28857047609f.png)
Then the host runtime is be Service Unavailable. 

![image](https://user-images.githubusercontent.com/1390976/90961790-1f385400-e460-11ea-8a56-4cc4f9bd5e8c.png)

#### Investigative information

Please provide the following:

- Timestamp: Sat Aug 22 2020 09:56:51 GMT-0700 - Sat Aug 22 2020 09:58:05 GMT-0700
- Function App version: ~3
- Function App name: tsushicontest
- Function name(s) (as appropriate):
- Invocation ID:  n/a
- Region: Central US

#### Repro steps

1. Deploy a Windows based Consumption Plan with dotnet runtime. 
2. Go to Configuration > General settings   then select .NET Core Version as .NET Core 3.1 then Save.

#### Expected behavior
Runtime Host should be halthy.

#### Actual behavior
Service Unavailable from host runtime. 

As we checked the Export template, `netFrameworkVersion` becomes `v3.0`.  The value might not be available. 
![image](https://user-images.githubusercontent.com/1390976/90961872-ba312e00-e460-11ea-96f3-b637951312bd.png)
It looks prevent to start the w3wp.exe I can see scm's one only.

![image](https://user-images.githubusercontent.com/1390976/90961904-ea78cc80-e460-11ea-9147-c4175b656c79.png)

#### Known workarounds

Don't do this operation. I just to share this issue to improve portal experience.

#### Related information 

This issue is found and detected root cause by @shibayan .

**Comment by fabiocav** [comment]
@TsuyoshiUshio is the goal to drive a portal change? Did you check what the actual error was with this configuration in place?


/cc @pragnagopa

**Comment by pragnagopa** [comment]
This is a known issue on the UX and fix should be rolling out soon. 

@takyyon - is there a issue tracking the fix that can be linked here? Also, ETA for the fix roll out? Thanks!

**Comment by TsuyoshiUshio** [comment]
The UI looks updated. I had one customer who encounters the issue. They asked me to how to recover from this one. 
I can reproduce this by updating netframeorkversion , and found workaround.  

```bash
az functionapp config set --net-framework-version v4.0 --name <Function App Name> --resource-group <Resource Group>
```
https://docs.microsoft.com/en-us/cli/azure/functionapp/config?view=azure-cli-latest
