### ISSUE TITLE
Timer trigger not firing unless the Function App is opened in the portal .

### ISSUE THREAD

**Issue by RengarLee** [Azure/azure-functions-host#6552]
Timer trigger not firing unless the Function App is opened in the portal.

- Function App version : 3.0.14228.0
- Function App name: securityapi
- Function name(s) (as appropriate): PriceDefendEmailSend
- Region: China East 2
- schedule:"0,10,20,30,40,50 * * * *"

**Expected behavior**
The function fires every 10 minutes.

**Actual behavior**
The function fires only when I open it in the portal

![image](https://user-images.githubusercontent.com/23287334/90997987-93583080-e5f5-11ea-8a9c-76c32f0fdfb3.png)

2020-08-24T02:19:59.997 [Information] Executing 'PriceDefendEmailSend' (Reason='Timer fired at 2020-08-24T10:19:59.9967315+08:00', Id=e521696a-4a88-4028-aa60-adfe20bbb02b)
2020-08-24T02:20:00.056 [Information] Executed 'PriceDefendEmailSend' (Succeeded, Id=e521696a-4a88-4028-aa60-adfe20bbb02b, Duration=59ms)
![Snipaste_2020-08-24_10-32-15](https://user-images.githubusercontent.com/23287334/90997802-188f1580-e5f5-11ea-9250-6d1a4e1554ae.png)

**Comment by ThejaChoudary** [comment]
@yojagad Able to repro the issue,Can you please look into this further.

**Comment by yojagad** [comment]
Apologies for the late response. @ThejaChoudary Can you let me know which function app you used to repro this issue so that I can look into this further ? @RengarLee Does the app exist and is this still an issue ? I was not able to find the app when I looked it up to dig into this.
