### ISSUE TITLE
Improvements to FunctionAppLogs

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#6556]
We need to expand the details we send to Azure Monitor Diagnotsic Logs (the FunctionAppLogs). Add the following properties:
1. AppName
2. MachineName (need to figure out what best name is here)
3. LevelId (for better filtering of, for example `LevelId > 2`
4. EventName
5. EventId

**Comment by pragnagopa** [comment]
@brettsam - Will this PR merged today/tomorrow? If not please move this next sprint.

**Comment by brettsam** [comment]
No, doesn't need to make it in for this sprint -- will bump it.
