### ISSUE TITLE
Fix Roslyn assembly unification in v2

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#6558]
In v2, we moved Roslyn packages forward a major version: https://github.com/Azure/azure-functions-host/pull/5948

We also have this configured to unify lower versions to the host version: https://github.com/Azure/azure-functions-host/blob/v2.x/src/WebJobs.Script/runtimeassemblies.json#L489-L492

If customers were using anything Roslyn-related and built against Roslyn 2.x, they were unexpectedly moved to 3.x, which contains some breaking changes.

**Comment by pragnagopa** [comment]
Need to remove  2.0.13351 from RU feed as soon as fix for this issue is rolled out.

**Comment by brettsam** [comment]
We're punting all AssemblyLoadContext changes out a sprint as we already have some significant changes going in this release and don't want to pile them all up in one big release.

**Comment by pragnagopa** [comment]
@brettsam / @fabiocav  - any updates on this issue?

**Comment by pragnagopa** [comment]
Assigning this to next sprint to prioritize fix . As of yesterday 65 apps are pinned to version: 3.0.13353.0
Fix for this issue will help delete version from 3.0.13353.0 RU feed.

**Comment by pragnagopa** [comment]
Moving to sprint 104 to discuss addressing this issue or closing.

**Comment by pragnagopa** [comment]
cc @yojagad

**Comment by fabiocav** [comment]
Flagging this as a design/planning item for the current sprint. I don't expect changes to take place for the next release as we have to decide on how (there are a few options) and if (this may not be relevant) we want to execute on this.

**Comment by pragnagopa** [comment]
Bringing into Functions Sprint 117 for discussion. Shared more details in the email thread regarding side effects of keeping older version on the platform.
