### ISSUE TITLE
azure function 64bit not showing function when deployed

### ISSUE THREAD

**Issue by plaiddk** [Azure/azure-functions-host#6559]
Hi,
When i change the platform to 64bit on both app service plan or consumption plan it does not show the function which i have deployed. It deploys the files fine i can see in Kudo. So it does something.

But i cannot see the function and thereby i cannot trigger it.

It works fine if I select 32bit platform. 

Whats the issue here?

**Comment by jedjohan** [comment]
I am seeing the same problems, the function keys are deleted causing the function to break. I get the issue when saving in "General Settings" for the Function. Workaround is to recreate the Function and absolutely NOT touch anything in "General Settings"

**Comment by plaiddk** [comment]
> I am seeing the same problems, the function keys are deleted causing the function to break. I get the issue when saving in "General Settings" for the Function. Workaround is to recreate the Function and absolutely NOT touch anything in "General Settings"

Is that a workaround? I dont think you can set the platform as 64bit in the start?

**Comment by brettsam** [comment]
Can either of you walk me through the steps to repro this? I assume this is all using the portal? (screenshots would be helpful, if easy enough to keep anonymous)... 

@ehamai / @ammanifold -- have either of you seen reports like this?

**Comment by prabh-62** [comment]
@brettsam You can try deploying a simple hello world app in 64 bit using VSCode Azure Functions extension
In *.csproj, add
```xml
<PropertyGroup>
   <PlatformTarget>x64</PlatformTarget>
</PropertyGroup>
```
<img width="699" alt="deploy_azfunc_vscode" src="https://user-images.githubusercontent.com/13006107/91314786-ef9d8a80-e784-11ea-8455-92297496742e.png">

Related issue: https://github.com/microsoft/vscode-azurefunctions/issues/2326

**Comment by plaiddk** [comment]
> @brettsam You can try deploying a simple hello world app in 64 bit using VSCode Azure Functions extension
> In *.csproj, add
> 
> ```
> <PropertyGroup>
>    <PlatformTarget>x64</PlatformTarget>
> </PropertyGroup>
> ```
> 
> <img alt="deploy_azfunc_vscode" width="699" src="https://user-images.githubusercontent.com/13006107/91314786-ef9d8a80-e784-11ea-8455-92297496742e.png">
> 
> Related issue: [microsoft/vscode-azurefunctions#2326](https://github.com/microsoft/vscode-azurefunctions/issues/2326)

If I add PlatformTarget the runtime stops working and it gives an System.Private.Corelib error. But does it work for you?

**Comment by prabh-62** [comment]
> > @brettsam You can try deploying a simple hello world app in 64 bit using VSCode Azure Functions extension
> > In *.csproj, add
> > ```
> > <PropertyGroup>
> >    <PlatformTarget>x64</PlatformTarget>
> > </PropertyGroup>
> > ```
> > 
> > 
> > <img alt="deploy_azfunc_vscode" width="699" src="https://user-images.githubusercontent.com/13006107/91314786-ef9d8a80-e784-11ea-8455-92297496742e.png">
> > Related issue: [microsoft/vscode-azurefunctions#2326](https://github.com/microsoft/vscode-azurefunctions/issues/2326)
> 
> If I add PlatformTarget the runtime stops working and it gives an System.Private.Corelib error. But does it work for you?

Not in the first try, but it works eventually. We have 10 azure functions deployed in Premium plan and we always host in 64-bit mode

**Comment by plaiddk** [comment]
> Can either of you walk me through the steps to repro this? I assume this is all using the portal? (screenshots would be helpful, if easy enough to keep anonymous)...
> 
> @ehamai / @ammanifold -- have either of you seen reports like this?

Picture 1: An azure function in 32bit mode. Showing the function
![Udklip](https://user-images.githubusercontent.com/20297081/91342037-bdb71300-e7da-11ea-8a08-ac2496af5b00.PNG)

Picture 2: Changing the 32bit function to 64bit in general settings
![Udklip1](https://user-images.githubusercontent.com/20297081/91342089-d32c3d00-e7da-11ea-8110-88062072bd2a.PNG)

Picture 3: Service is now unavailable after re-publishing the project
![Udklip2](https://user-images.githubusercontent.com/20297081/91342136-e3dcb300-e7da-11ea-8c26-c62da40a89a4.PNG)

Picture 4: After re publish you can see the function is now gone. But it is still showing im running from a package file. And the whole project is still in kudu
![Udklip3](https://user-images.githubusercontent.com/20297081/91342215-fbb43700-e7da-11ea-9191-dc60375bee92.PNG)

Picture 5: Here i created a whole new 32bit azure function and set the PlatformTarget x64 /PlatformTarget
As you can see the function host is not running anymore.
![Udklip4](https://user-images.githubusercontent.com/20297081/91342313-21d9d700-e7db-11ea-8b01-d54eaf350935.PNG)

**Comment by prabh-62** [comment]
Yes, this is exactly what I reported on vscode extension repo. https://github.com/microsoft/vscode-azurefunctions/issues/2326

**Comment by plaiddk** [comment]
> Yes, this exactly what I reported on vscode extension repo. [microsoft/vscode-azurefunctions#2326](https://github.com/microsoft/vscode-azurefunctions/issues/2326)

But how did you get the x64 to work then? It doesnt work here as you can see. So im guessing something is wrong with the  functions.

**Comment by jedjohan** [comment]
@plaiddk well no, its not a workaround in that sense :) But as the Function keys somehow gets deleted i spent an hour trying to rescue my function until I gave up and deleted it to start new. That´s how I worked around it

@brettsam sorry for late answer but @plaiddk posted a great explanation. The only thing to add to that is to observe that the function keys dispappears, even the _master key

**Comment by plaiddk** [comment]
@ankitkumarr what happens here? Is this a bug or what should be done?

**Comment by ankitkumarr** [comment]
Brett assigned it to me to continue the investigation, and I didn't get a chance to follow up yet.

Could one of you share your function app name ([you can share it privately](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)) and the time frame when you saw the error? I wonder if something in your application (or some functions extension) doesn't work with 64bit, and is crashing the Functions Runtime. I can take a look at the logs on our end if you share this info to see what's actually going on.

**Comment by prabh-62** [comment]
@ankitkumarr Are you able to deploy a 64 bit Hello world azure function v3 app from your end?
Logged issue on VSCode extension repo as well: https://github.com/microsoft/vscode-azurefunctions/issues/2326

**Comment by v-anvari** [comment]
@ankitkumarr, any thoughts here?

**Comment by ankitkumarr** [comment]
@prabh-62, yes I am able to as long as I update my Function app in Azure to be 64-bit. I think your issue might be that VS Code extension is not automatically updating the bitness in Azure. If so, then the issue you opened in VS Code makes sense. In terms of functions runtime, it seems to be working fine when I make sure in Azure the runtime is set appropriately.

I am unable to repro this. I have tried these steps --
1. Create a function app.
2. Change the Platform to 64 bit.
3. Create a functions project locally with Platform target as 64bit.
4. Publish this project.
At this point, everything seems to work. Maybe I am missing something?

I want to make sure we are on the same page that the target runtime for your app should match the runtime set in Azure Function. So if you have the target set to 32 bit and runtime set to 64 bit or vice-versa, it is expected that you'll see this error.

@plaiddk, does the function app fail for you even when the runtimes match? I notice that you said 
> Picture 5: Here i created a whole new 32bit azure function and set the PlatformTarget x64 /PlatformTarget
As you can see the function host is not running anymore.

So I want to confirm that you also see the issue when both your project and the app is set to the same bitness.

**Comment by prabh-62** [comment]
I created a Pull request https://github.com/microsoft/vscode-azurefunctions/pull/2429 to fix the issue on the VSCode extension.
