### ISSUE TITLE
System.Private.CoreLib: Exception  Value cannot be null. (Parameter 'key').

### ISSUE THREAD

**Issue by mcgjoe** [Azure/azure-functions-host#6562]
#### Is your question related to a specific version? If so, please specify:
Using Azure Functions runtime version 3~
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
python
#### Question
receiving this error:
System.Private.CoreLib: Exception while executing function: Functions.BlobTrigger1. System.Private.CoreLib: Value cannot be null. (Parameter 'key').

when i debug locally I am unable to determine what's causing this.  Any help would be appreciated.  Thanks

**Comment by mcgjoe** [comment]
when step through code last command I get to is :
self._grpc_resp_queue.put_nowait(resp)

of this code block:

 async def _dispatch_grpc_request(self, request):
        content_type = request.WhichOneof('content')
        request_handler = getattr(self, f'_handle__{content_type}', None)
        if request_handler is None:
            # Don't crash on unknown messages.  Some of them can be ignored;
            # and if something goes really wrong the host can always just
            # kill the worker's process.
            logger.error(f'unknown StreamingMessage content type '
                         f'{content_type}')
            return
 
        resp = await request_handler(request)
        self._grpc_resp_queue.put_nowait(resp)

**Comment by mcgjoe** [comment]
this appears in dispatcher.py

**Comment by v-anvari** [comment]
Hi @mcgjoe , Apologies for the delayed response. Were you able find a solution? do let us know if any further help is required
