### ISSUE TITLE
Unable to assign ServiceBus connection string using ServiceBusTriggerAttribute

### ISSUE THREAD

**Issue by amogh79** [Azure/azure-functions-host#6569]
#### Is your question related to a specific version? If so, please specify: 
3.x

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) : 
C#
#### Question
In my scenario I am reading service bus connection string from KeyVault. I want to retrieve SB connection string from KV in startup and assign it to the functon. Following is the code snippet. Unfortunately I get error saying, "Microsoft.Azure.WebJobs.ServiceBus: Microsoft Azure WebJobs SDK ServiceBus connection string '' is missing or empty." I already put a breakpoint  and can see connectionString is retrieved in Configure function.

 public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.ConfigureHostModule();
            string connectionString = SetServiceBusConnectionString(builder.Services);
            builder.Services.PostConfigure<ServiceBusTriggerAttribute>(serviceBusOptions => 
            {
                serviceBusOptions.Connection = connectionString;
            });            
        }
private string SetServiceBusConnectionString(IServiceCollection serviceProvider)
        {            
            var config = serviceProvider.BuildServiceProvider().GetService<IConfigurationProvider>();
            var kvClient = serviceProvider.BuildServiceProvider().GetService<KeyVault>();
            var logProvider = serviceProvider.BuildServiceProvider().GetService<ILogProvider>();
            string serviceBusConnectionString = kvClient.GetSecret(config.GetSetting(OnboardingServicesConfigNames.ServiceBusConnectionStringSecretKey), logProvider);
            return serviceBusConnectionString;
        }

**Comment by ThejaChoudary** [comment]
@amogh79 can you please provide us the repro steps

**Comment by amogh79** [comment]
Hi Theja,

Following are the steps:

01. Create a servicebustriggered function.
02. In this function set the topic name and subscription name for topic
03. Set the connection property to Connection=''
04. In startup.cs write code to retrieve the connection string from KeyVault (see my code snippet above)
05. Override the Configure method and in that method use PostConfigure to set the connection string (see my code snippet above)

Hope this helps.

Thanks
Amogh

**Comment by amogh79** [comment]
Do you have any updates on this please?

**Comment by v-anvari** [comment]
Hi @amogh79 , Only environment variables are supported for app settings and connection strings.

You need to make sure that the environment variable AzureWebJobsAzureSBConnection is set on your Function's app settings in the portal, and then once there, you need to add the AzureWebJobsAzureSBConnection variable with the proper connection string.

Then you can access this via code by:
Environment.GetEnvironmentVariable(name, EnvironmentVariableTarget.Process);

This will obtain the value from either the appsettings.json or the environment variable depending on where the function is being executed from, (local debugging or deployed on Azure)

cc: Tagging @fabiocav / @brettsam for more inputs on this context
