### ISSUE TITLE
provide Service Registry/Discovery as a Service

### ISSUE THREAD

**Issue by ma3yta** [Azure/azure-functions-host#6573]
#### What problem would the feature you're requesting solve? Please describe.
Getting Azure Function endpoint by tag and function name at runtime without specifying it in the configuration.
Azure actually provides this capability in Azure Service Fabric, but it is currently not available for use with Azure Functions.
https://microservices.io/patterns/service-registry.html

#### Describe the solution you'd like
Service Registry as a Service. It as relatively simple; a key-value store with multiple distinct namespaces. But the crux is this: when making a ``Get`` call, the namespace is chosen based on some property of the caller, rather than selected explicitly. Of course, explicit selection would also be available.
To be fully functional as SDaaS, the service would have to allow phase rollouts of changes to the namespace selections. That is, it should support [blue-green updates](https://martinfowler.com/bliki/BlueGreenDeployment.html) to the values that a given caller receives.

More details: https://read.acloud.guru/service-discovery-as-a-service-the-missing-serverless-lynchpin-541d001466f4

#### Describe alternatives you've considered
Another option is a configuration manager like Zookeeper, etcd, or Consul .

#### Additional context
there’s another advantage provided by service discovery mechanisms in traditional microservice architectures: separation of environments.

<figure class="image">
  <img src="https://miro.medium.com/max/1750/1*YwNX6409ZtcQr4bnvj_qNw.png" alt="Serverless deployments without Service Discovery as a Service">
  <figcaption>Serverless deployments without Service Discovery as a Service</figcaption>
</figure>
<br />

> In serverless deployments without Service Discovery as a Service, the functions exist in the same namespace. They are connected to other functions within their deployment through environment variables, which are fixed at deployment time. Updating one function requires an update/deploy to all callers — and every function must be deployed with the full physical resource ids that it uses.
<br /> 
<figure class="image">
  <img src="https://miro.medium.com/max/1750/1*0HgfPPI58OUNoJlzNwTSZw.png" alt="Service Discovery as a Service">
  <figcaption>Service Discovery as a Service</figcaption>
</figure>
<br/>

> Service Discovery as a Service tags functions and make a non-namespaced call to the service discovery service (e.g., Get(“A”)), which uses the tag to index into the namespace (e.g., Env1). At deployment time, the functions need only be tagged with an immutable identifier.

**Comment by brettsam** [comment]
@jeffhollan / @mattchenderson -- curious if either of you have seen this article or have thoughts?

**Comment by mattchenderson** [comment]
The [Azure App Configuration](https://docs.microsoft.com/en-us/azure/azure-app-configuration/overview) service might be of interest. It's not quite what's being asked for here, but it can help with some of the challenges.

Because this is in effect asking for a new service, I'm not sure this repo is the right place to track the issue. My recommendation would be to open something on feedback.azure.com.

**Comment by Ma3yTa** [comment]
@mattchenderson 
environment (QA, staging, prod) separation can be achieved using Azure Service Fabric Mesh but looks like it doesn't support Azure Functions yet
