### ISSUE TITLE
[Doc Issue] Document new 'watchFiles' host.json property

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-host#6580]
Tracking item to document `"watchFiles"` once this is merged and released -- https://github.com/Azure/azure-functions-host/pull/6563

1. Update public docs
2. Update host.json schema

**Comment by fabiocav** [comment]
Currently in PR, waiting for approval.

@ggailey777 - FYI

**Comment by fabiocav** [comment]
Blocked on PR approval.
