### ISSUE TITLE
BUG: Azure Functions 3.0.14287.0 broke local log lines display

### ISSUE THREAD

**Issue by zmarty** [Azure/azure-functions-host#6582]
Azure Functions 3.0.14287.0
C# .Net Core 3.1
Azure Functions v34
Visual Studio 2019 16.7.2
Windows 10

Symptom: When we log using ILogger those log lines do not show up in func.exe console window anymore when debugging in Visual Studio.
I see a new message which says "For detailed output, run func with --verbose flag". I will investigate how to enable this to see if it fixes the issue, but I still consider this a bug.

**Comment by zmarty** [comment]
Adding --verbose under Debug > Application Arguments fails with func.exe saying:

Error: unknown argument --verbose
Azure Functions Core Tools (3.0.2852 Commit hash: d1c2c8e7dc10a94a399246dda94049a7dbf0383d)
Function Runtime Version: 3.0.14287.0
Usage: func [context] [context] <action> [-/--options]

**Comment by zmarty** [comment]
https://github.com/Azure/Azure-Functions/issues/88

**Comment by anthonychu** [comment]
To add the `--verbose` flag, looks like you have to set the application arguments to `start --verbose`.

![image](https://user-images.githubusercontent.com/3982077/91919065-a31ce800-ec79-11ea-8729-85c29bc86858.png)

**Comment by anthonychu** [comment]
Closing this in favor of https://github.com/Azure/azure-functions-core-tools/issues/2184
