### ISSUE TITLE
Support for common libraries such as HealthCheck, Application Insights Profiler and Application Insights for Kubernetes

### ISSUE THREAD

**Issue by buzzaII** [Azure/azure-functions-host#6586]
Would be nice to be able to support the following libraries:

https://github.com/xabaril/AspNetCore.Diagnostics.HealthChecks
https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore
https://github.com/microsoft/ApplicationInsights-Kubernetes

These integrations with in a Dockerised Function App, running in a Keda Environment, in AKS.

**Comment by v-anvari** [comment]
Hi @buzzaII , Apologies for the delayed response, these libraries are already supported. Let us know if you are facing any challenges using any of these packages
