### ISSUE TITLE
Support streams in NodeJS

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-host#660]
Currently we don't support streams in NodeJS, but they are useful for lots of different applications. It would be good to support them natively.

**Comment by yvele** [comment]
@christopheranderson Does this applies to `content.body = stream` in an HTTP Azure Function scenario?

**Comment by mamaso** [comment]
@christopheranderson Thought a little bit about this over the weekend.  In your ideal vision, what would we support?

- Input / output?
- True streaming behavior vs buffered behavior in the C# / node interaction? i.e. hook the C# streams from blob trigger, etc directly into the node stream? An alternative which loses benefits but is probably easier to implement is to fully read stream in C# and then stream that object to node
- Control flow via streams?  i.e. allow returning of streams? finish execution when all output streams have an 'end' event?

**Comment by kshmir** [comment]
@mamaso I'm currently developing a solution for my particular business, which involves analytics processing, and being able to return chunked http requests would be ideal. This is easily done with express, but doesn't seem to be the case inside azure functions. 
#781 is, as you said, a basic wrapper, having that functionality as an express API would probably make it much more useful for serving content and returning streamed data.

As with the other issue I mentioned on, I could lend a hand on this. I'm personally interested on it.

**Comment by yvele** [comment]
@kshmir I agree with you about the basic Express wrapper. And you're welcome to contribute: https://github.com/yvele/azure-function-express it doesn't supports chunks

**Comment by kevinclarkadstech** [comment]
Ughhh got my whole function built and got req.pipe is not a function.  Guess it's back to Digital Ocean for me.

**Comment by ejizba** [comment]
It's a long time coming 😅, but we announced preview support for HTTP streams! 🎉 Learn more in our [blog post](https://aka.ms/AzFuncNodeHttpStreams)

Closing this issue in favor of https://github.com/Azure/azure-functions-nodejs-library/issues/97, if you want to track GA support
