### ISSUE TITLE
HTTPS requests on Linux dedicated and Linux Premium apps appear as HTTP

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-host#6602]
This was brought to my attention by [this issue](https://github.com/Azure/azure-functions-durable-extension/issues/1446) filed in the Durable Functions repo.

In general, the SSL termination for Azure Functions on most of our infrastructures happens at the frontend. For Windows, an IIS module properly translates the request to "https" by looking at the forwarded headers. For Linux Consumption, it looks like the Azure Functions host has [custom middleware](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Middleware/AppServiceHeaderFixupMiddleware.cs) to handle translating the requests based on X-Forwarded-Proto. There is nothing equivalent for Linux dedicated and Linux premium apps.

Repro:
```csharp
        [FunctionName("HttpPrinter")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest request,
            ILogger log)
        {
            string baseUrl = $"{request.Scheme}://{request.Host}{request.Path}{request.QueryString.Value}";
            StringBuilder sbHeaders = new StringBuilder();
            foreach (var header in request.Headers)
                sbHeaders.Append($"{header.Key}: {header.Value}\n");

            string body = "no-body";
            if (request.Body.CanSeek)
            {
                request.Body.Seek(0, SeekOrigin.Begin);
                using (StreamReader sr = new StreamReader(request.Body))
                    body = await sr.ReadToEndAsync();
            }

            string detailedBody = $"{request.Protocol} {request.Method} {baseUrl}\nHTTPS: {request.IsHttps}\n\n{sbHeaders}\n{body}";
            return (ActionResult)new OkObjectResult(detailedBody);
        }
```

Running on a Linux app service plan function app, this function will show HTTPS requests as HTTP.

Workaround:
1. Add the app setting ASPNETCORE_FORWARDEDHEADERS_ENABLED to true.
2. Until ANT89 rolls out, the version of the middleware container that runs the CORS and Authentication/Authorization feature on Linux app service plans consumes the X-Forwarded-Header before it enters the main customer container, so it may be necessary to disable both of these features. This rollout should hopefully finish in the next week or so.

**Comment by cgillum** [comment]
@fabiocav this issue is creating problems for Durable Functions customers running on Linux, and we expect to have more Linux customers when we GA Durable Python. Is there any way we can prioritize this issue?

@ConnorMcMahon if the fix is simple enough, I think we should just create a PR for it ourselves.

**Comment by fabiocav** [comment]
@cgillum it would also be good to validate with the Linux team that this is expected for the App Service Linux flavors. Ideally, the runtime wouldn't be responsible for this.

**Comment by ConnorMcMahon** [comment]
We document for customers [to do this for .NET Core apps](https://docs.microsoft.com/en-us/azure/app-service/configure-language-dotnetcore?pivots=platform-linux#detect-https-session) if they want to detect if traffic is HTTPs or not. It seems like this is something that the runtime should handle on Linux App Service, given the limitations of our architecture. It was not necessary for our Windows architecture because of IIS modules that do the handling of this for us.

**Comment by fabiocav** [comment]
If it is documented behavior, I agree. It's unfortunate, but looks like that's what we need to do. 

I'm assuming the middleware registration here is conditional on the plan (haven't looked yet), so we'd need to apply the same to other Linux flavors, but we need to understand how the change in behavior could impact customers and decide whether this needs to be done as an opt-in thing.

**Comment by ConnorMcMahon** [comment]
I am less concerned about customers seeing HTTPS on their HttpRequest object, as long as we give an out for customers disable this new behavior. I just don't see many customers being broken if HTTP changes to HTTPs.

That being said, I have found that using the default .NET Core middleware that handles this forwarding logic deletes the original X-Forwarded-Proto header, which I could definitely see some customers having some logic built into it. We will need to see if there are settings we can do to change this behavior, or if we need our own custom middleware that leaves the headers intact and just changes the Scheme/Protocol from HTTP to HTTPS.

**Comment by fabiocav** [comment]
> I just don't see many customers being broken if HTTP changes to HTTPs

Neither do I, but the bar wouldn't be _many_, but _any_. If we identify any valid scenarios where a customer would be broken, we can't make a change to the defaults. That's why changes like this, even if we don't immediately think would have customer impact, still need to go through a more thorough investigation/validation. We do this for any changes to defaults.

**Comment by fabiocav** [comment]
And it goes beyond just seeing what's on the request. Any logic base on the scheme (that could be for any component the customer passes the request down to), would be impacted by this change, we we do need to approach this carefully.

**Comment by ConnorMcMahon** [comment]
Hmm, I think then we may need to handle this separately in Durable Functions then (at least for our link creation APIs), as if this is opt-in I think many of our customers will have difficulty finding this setting.

**Comment by mzhukovs** [comment]
For C# function apps it sounds like the fix is as simple as ASPNETCORE_FORWARDEDHEADERS_ENABLED = true in app settings... but what about for a python-based functions app on Linux Elastic Premium? Any advice @fabiocav @ConnorMcMahon ?

**Comment by ConnorMcMahon** [comment]
Since the core runtime is still C#, the same app setting should work for all languages @mzhukovs.

**Comment by mzhukovs** [comment]
Excellent, thanks for the quick response @ConnorMcMahon .

**Comment by fabiocav** [comment]
Pushing this to sprint 106 due to capacity.
