### ISSUE TITLE
Azure function timer triggers aren't working

### ISSUE THREAD

**Issue by adharbert** [Azure/azure-functions-host#6635]
I have 2 functions on the same app service.  I have it so they are supposed to execute one at 3 am and the other 6 am.   

I originally only had one function that worked fine.  Always executed at the same time.  When I added the new function, I find that neither of them execute when they're supposed to run.  Every day, I open up portal to see if they run (under functions / monitor), 

What is very odd, is after I go to the monitor section.  If I wait a minute, both functions then start up together.   It's almost like they are not aware they should execute until I look at them.  

Does anyone know why this happens?  I really don't want to create a whole new app service function just for one function app, but I can't find anything with information on this.

**Comment by v-anvari** [comment]
Hi @adharbert , we tried to reproduce the scenario in "Australia east" and it is working as expected from our side.

We need additional information given in the issue template to understand the root case. Kindly, let us know the location, time stamp, and function app name of your function app. 

It would be helpful if you could give us the repro steps, so that we can clone the scenario.

**Comment by adharbert** [comment]
I will try to describe the setup best I can, I wish I could do a screen share :-)

**First part, Code:**

- I created the functions to use env variables to fire off.  When I have only one, it seems to work fine.  Now that I added 2 more function methods, they appear to 1. not fire off at all at the correct time and 2. Fire off together, even though they are scheduled a few hours apart.

- Here is the code sample (I have two here, but the third is pretty much the same)

`  
public class NightlyFunction
    {

        private readonly IMediator _mediator;
        public NightlyFunction(IMediator mediator)
        {
            _mediator = mediator;
        }


        [FunctionName("NightlyJob1")]
        public async Task Run([TimerTrigger("%ScheduleAppSetting%", RunOnStartup = false)] TimerInfo timer, ILogger log)
        {
			log.LogInformation("Starting Campaign function");
			var result = await _mediator.Send(new Campaign.Command { clientLog = log, campaignType = Timer_Affinity });
        }        
    }

    public class NightlyMortgageFunction
    {
        private readonly IMediator _mediator;
        public NightlyMortgageFunction(IMediator mediator)
        {
            _mediator = mediator;
        }

        [FunctionName("NightlyJob2")]
        public async Task Run([TimerTrigger("%ScheduleMortgageSetting%", RunOnStartup = false)] TimerInfo timer, ILogger log)
        {
            log.LogInformation("Starting Mortgage function");
            var result = await _mediator.Send(new Campaign.Command { clientLog = log, campaignType = Timer_MortVerify });
        }
    }
`

As you can see, each Run method has a env variable for the TimerTrigger.  This was working before, but now it is totally erratic.

**Second part, Azure portal:**


- When I go into the Functions tab, this is how it looks:
![image](https://user-images.githubusercontent.com/5186596/92960864-50db8400-f43c-11ea-8229-506c0c6abc73.png)


I have seen other groups use multiple functions in app without any issue, so I'm not sure why this is so inconsistent.

I guess I can pose the question, this is setup as a consumption app, would that be part of the issue?


Thanks! Let me know if there are other details you need.

**Comment by jabbera** [comment]
Could this be it? https://github.com/Azure/azure-functions-host/issues/2015

**Comment by v-anvari** [comment]
Hi @adharbert , We have tried to use the environment variables to fire off the functions, but they are running as expected. In order to check your function app logs, we require additional information.

Function App name:
Time stamp during error:

**Comment by adharbert** [comment]
Thanks everyone,

Still have the issue, but I wonder if it's because I'm using the consumption plan.  Right now it's only for dev and getting ready to push a prod version of this.  I now have 4 functions, they appear to work correctly, but the timer never fires off by itself.  If I go into Azure portal, go to the app service and click on Functions (after the time they were supposed to launch), then all the functions start up.  It's almost like they were idle and needed to be woken up.

In the prod version, I am using a premium account instead of consumption, I'll be interested to see if this will work better or at least fires off at the correct time.

**Comment by v-anvari** [comment]
Hi @adharbert , I appreciate the details, there shouldn't be a problem due to consumption plan if it has running instances. 

@fabiocav, is there a way we can check the logs here.

**Comment by fabiocav** [comment]
@adharbert the timer should fire as expected in the consumption plan as well. In order to better understand what is happening with your application, it would be helpful to look at the current configuration and logs, but in order to do that, we need your application information. Can you please share your application name or the region and an execution ID, along with a timeframe so we can take a closer look? Thanks!
