### ISSUE TITLE
Enable test ValidateContext_InvalidZipUrl_WebsiteUseZip_ReturnsError

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#6643]
cc @brettsam 

Investigate test failure: ValidateContext_InvalidZipUrl_WebsiteUseZip_ReturnsError

Disabled the test and builds are blocked.

**Comment by brettsam** [comment]
FYI -- I suspect it's b/c http://invalid.com/invalid/dne used to return a 404 and now the site doesn't appear to exist at all.

**Comment by mathewc** [comment]
That is supposed to be an invalid URL - that's what the test is verifying, a download failure. This test passes on my box. What failure do you see when running it @pragnagopa ?

**Comment by brettsam** [comment]
It's specifically testing that the status code returned is `NotFound`. Last week it seemed like something in the request was failing really early (it wasn't even getting a status code back). Clicking that link in the browser also failed with something error code like "name_not_found" (it wasn't that -- but I can't repro it now obviously).

But now it works. I guess the point is -- if possible, we shouldn't have tests that rely on external site error codes if they can change outside of our control.

**Comment by mathewc** [comment]
Ah, I see. The test should probably be updated then to just use a new guid for the host name on each invocation then or something :)

**Comment by balag0** [comment]
For the test scenario, the url has to return 404 specifically and not just be unreachable so random hostnames dont help. I think I got that url from somewhere as an easy way to get 404 status codes. Looks like that site went down temporarily for sometime causing the test to fail differently. I will create a web app in my subscription that returns 404 so we have more control on the endpoint.

**Comment by brettsam** [comment]
Can you mock the Http call?
