### ISSUE TITLE
Deployment of Functions using ARM template gives 'Bad Request' Internal Server Error

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-host#6669]
When trying to publish a Azure Functions app and two functions using ARM template `BadRequest (500)` appears during creation of second function.

We have a race when creating functions using "[Microsoft.Web/sites/functions](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2018-02-01/sites/functions)" thought the ARM template. The thing is that creating the function app + functions in the ARM template isn't atomic operation, the function host restarts during ARM deployment when the function app is created and PUT call to create second functions can be failed due function host restart. As result the ARM deployment is failed but function app + functions are created and work fine. 

ARM templates for reproducing:
[Repro2.txt](https://github.com/Azure/azure-functions-host/files/5247446/Repro2.txt)
[Repro1.txt](https://github.com/Azure/azure-functions-host/files/5247447/Repro1.txt)

Internal [incident](https://portal.microsofticm.com/imp/v3/incidents/details/205483736/home).

**Comment by fabiocav** [comment]
@alrod does this meet the criteria for a P1?
