### ISSUE TITLE
Add support in worker.config to specify number of worker process count or opt-in to set worker count to number of core available on the VM

### ISSUE THREAD

**Issue by safihamid** [Azure/azure-functions-host#6671]
This came up while investigating some CRIs. The current default is one no matter how many cores are available on the VM.
And customers should be aware of the FUNCTIONS_WORKER_PROCESS_COUNT app setting to be able to increase their number of language workers for their specific scenarios.

For better throughput, the default should be set to the number of cores available. For Consumption  this will still be one but this will be different for Premium and App Service plans.

**Comment by anthonychu** [comment]
@anirudhgarg @vrdmr @Hazhzeng @stefanushinardi FYI

**Comment by pragnagopa** [comment]
tagging rest of the language worker owners for any concerns - @mhoeger @AnatoliB @amamounelsayed

**Comment by anthonychu** [comment]
As discussed with the Python functions crew, this is a good idea in general but might need a bit more investigation. There's a chance that an app is using EP2 or EP3 because it needs the extra memory, and increasing to 2 or 4 worker processes might cause it to run out of memory. Understanding the benefits and potential issues could be more complicated if there are multiple apps on the same plan.

**Comment by pragnagopa** [comment]
Each language worker needs to be tested with multiple workers for perf impact - an opt-in for multiple workers by default.
Updated the title to reflect the scope of the issue. 

This issue will track adding support in `worker.config` to opt-in for multiple workers.

**Comment by pragnagopa** [comment]
Also, allow worker to specify - max number of workers and interval to spawn workers

**Comment by vrdmr** [comment]
To lower the time taken to spawn the workers from 10 seconds to 1-2 seconds such that on an EP3 plan, we have the workers ready for load faster - we can discuss the minimum available time that doesn't add to the cold start.

From [functions-app-settings#functions_worker_process_count](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#functions_worker_process_count)
>  Language worker processes are spawned every 10 seconds until the count set by FUNCTIONS_WORKER_PROCESS_COUNT is reached
