### ISSUE TITLE
Use workflow extension bundle when generating default host.json for logic app

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#6672]
Use the following configuration when generating a default host.json in case we recognize the function app to be of kind logic app
```
"extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[1.*, 2.0.0)",
  }
```

**Comment by fabiocav** [comment]
This work item is currently blocked on infrastructure changes.
