### ISSUE TITLE
getting error as ssl.ca.location failed: .\\crypto\\x509\\by_file.c:254: error:0B084002:x509 certificate while consuming message from event hub

### ISSUE THREAD

**Issue by ankurshah12** [Azure/azure-functions-host#6676]
Question: Which IDE are you using? For example, Visual Studio, Visual Studio Code or in the portal?
Answer: vs 2019 professional

Question: If developing locally, have you upgraded to the most current version of the IDE?
Answer: Yes

Question: If developing locally, what version of the 'Azure Functions and WebJobs Tools' are you using?
Answer:

Question: Is the issue happening in the portal? What specific exception are you experiencing?
Answer: Yes

Question: Incident time
Answer: Mon, Sep 21, 2020, 12:00 AM GMT+5:30

Question: Details
Answer: We are Creating azure function, which will consume message from azure event hub, using conflunt kafka and we are using a genric ssl certifacte for that, but when deployed it to azure , we get

ssl.ca.location failed: .\\crypto\\x509\\by_file.c:254: error:0B084002:x509 certificate

Dont know why certifacte location is not accessible

Please help
![Uploading Functionissue.PNG…]()

**Comment by v-bbalaiagar** [comment]
Hi @ankurshah12, Apologies for the delayed response. Were you able find a solution? do let us know if a follow up is required.
