### ISSUE TITLE
Message Processing Order Across Service Bus Queues

### ISSUE THREAD

**Issue by SamNutkins** [Azure/azure-functions-host#6695]
#### Is your question related to a specific version? If so, please specify:
V3

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
I have a single Azure Function app containing multiple ServiceBusTrigger functions, each responding to messages from different queues. I do some throughput limiting using the maxConcurrentCalls and scale limiting (on the Function App itself) to limit load on downstream resources. Because of this, messages are sometimes waiting in queue for a period of time.

In this scenario, how does the function host determine which queues' messages to process first? For example, Queue A receives 10 messages. The function app begins processing them. Then Queue B receives 10 messages. Will Queue B's messages only be processed once Queue A's are fully processed? Or is it done in a round robin fashion?

Any insight or documentation references appreciated - thanks in advance.

**Comment by v-bbalaiagar** [comment]
Hi @SamNutkinsPM360, Apologies for the delayed response, There is no algorithm to check which queue will execute in azure itself as it is a threading system, not only for service bus. Please go through the [document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue#hostjson-settings) for host.json settings.
