### ISSUE TITLE
Linux consumption plans with Origin and Access-Control-Request-Method headers produce 204

### ISSUE THREAD

**Issue by aaltotsky** [Azure/azure-functions-host#6696]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app, select `Diagnose and solve problems` from the left, and view relevant dashboards before opening your issue.

The Linux consumption plan is different from the windows. The same .net core code for the V3 functions may produce different results.
The presence of the two headers  (Origin and Access-Control-Request-Method) may produce 204 No Content with the options HTTP request.

The example: 
Linux Plan: https:// corecaptchaazure .azurewebsites.net/api/CaptchaCreate 
Windows Plan: https:// corecaptchaazurewin .azurewebsites.net/api/CaptchaCreate

The open-source: https://github.com/RenetConsulting/angularcore.net
The Azure Function: https://github.com/RenetConsulting/angularcore.net/tree/master/Services/CoreCaptchaAzure
 

#### Investigative information

Please provide the following:

- Timestamp: 2020-09-23 1:15 PM (PST)
- Function App version: V3
- Function App name: CaptchaCreate
- Function name(s) (as appropriate):
- Invocation ID:
- Region: US WEST 2

#### Repro steps

Provide the steps required to reproduce the problem:

1. Deploy CoreCaptcha from the repo.
2. Use Fiddler to create a request with the presence of the 2 headers.

#### Expected behavior

Provide a description of the expected behavior.

Should produce the "200" result for both plans (Linux/Window)
 
#### Actual behavior

Provide a description of the actual behavior observed.

Produce the "204" result for the Linux plan and the "200" result for the Window plan.

#### Known workarounds

Provide a description of any known workarounds.

The workaround is to use the Windows plan.

#### Related information 

Provide any related information 

* Programming language used: C# .net Core 3.1 
* Links to the source: https://github.com/RenetConsulting/angularcore.net/tree/master/Services/CoreCaptchaAzure

**Comment by v-bbalaiagar** [comment]
Hi @aaltotsky, Apologies for the delayed response. Please let us know if you are still seeing this issue on your Function App, so that we will further look into the backend logs.

**Comment by aaltotsky** [comment]
Hi @v-bbalaiagar . I think you fix it. Thanks.
