### ISSUE TITLE
Sudden "cold start" of 1.5 seconds lost before start of HttpTrigger? 

### ISSUE THREAD

**Issue by deyanp** [Azure/azure-functions-host#6728]
#### Is your question related to a specific version? If so, please specify:
Using base docker image mcr.microsoft.com/azure-functions/dotnet:3.0 on AKS 1.18.8
azurefunctions: 3.0.14287.0

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
F#/.NET Core 3.1.402

#### Question
I am seeing 1.5 seconds lost before the first code line of the HttpTrigger is executed (log.Info - see screenshot from AppInsights below) ... this is a prewarmed AKS pod running Azure Functions Http Trigger ... any ideas how I can troubleshoot this? Is it really so that the Azure Functions Host is taking the time before my application logic (JIT or what is this???), or there is something (static) in my application which executes before the first line of the HttpTrigger?

![image](https://user-images.githubusercontent.com/25847560/94864464-4eb58580-043c-11eb-95c5-5d93681c7913.png)

Other requests before and after this one have only a few ms "lost" there:

![image](https://user-images.githubusercontent.com/25847560/94865051-385bf980-043d-11eb-9ad4-5d6a9801de67.png)

Any idea how to troubleshoot this will be very much appreciated!

**Comment by ankitkumarr** [comment]
@safihamid, I am guessing we only do the pre-jit optimizations when running in Azure Functions managed environment, right?

**Comment by safihamid** [comment]
@ankitkumarr yes that's right. the JIT is taking time here. If they add a warmup trigger and use latest Functions host it should help here.

**Comment by ankitkumarr** [comment]
@deyanp, sorry for the delay here. Were you running our images directly on top of AKS, without using Azure Functions?

If so, I am not sure if warmup trigger would help, unless you call "admin/warmup" directly before executing the function app. I can't think of any other to avoid the startup cost. Here's some info on [warmup triggers](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-warmup?tabs=csharp).

**Comment by deyanp** [comment]
The functions are running on AKS, I am using the docker image with the the Azure Functions host baked in.

The 1,5 seconds were due to some startup/static/initialization code of ours ... 
There is no warmup trigger on AKS, but there is readiness probe for example (in latest versions of K8s also a startup probe should be available, but not on AKS yet) which can be used for this purpose.
