### ISSUE TITLE
Powershell function output to blob

### ISSUE THREAD

**Issue by andy968** [Azure/azure-functions-host#6734]
I have a Powershell function triggering from blob. I am then processing the file and outputting it to another blob container. The output filename is using rand-guid. I want to get that rand-guid in the function so I can then email a download link from the container. Please help

**Comment by v-bbalaiagar** [comment]
Hi @andy968, Apologies for the delayed response, Here is a [stackoverflow](https://stackoverflow.com/questions/52172941/how-can-i-reference-rand-guid-value-from-declarative-binding-in-azure-function) which addresses similar scenario. Please check and let us know if this helps.
