### ISSUE TITLE
Azure function runtime v3 proxy passing incomplete http context

### ISSUE THREAD

**Issue by ikaplans** [Azure/azure-functions-host#6745]
There seems to be an issue with the ActionContext used to invoke ActionResult, when using a function proxy.
When the function is called directly the HttpContext of the passed ActionContext contains a Request object with a populated headers collection.
When the same function is invoked via proxy route, the collection is empty.

This can be easily reproduced in an emulator by creating a function app, with a single HttpTrigger function which returns a custom MyActionResult that returns the value of context.HttpContext.Request.Host.
```
public class MyActionResult : OkObjectResult
{
    public MyActionResult() : base(string.Empty) {}

    public override Task ExecuteResultAsync(ActionContext context)
    {
        Console.WriteLine(context.HttpContext.Request.Host);
        base.Value = context.HttpContext.Request.Host;
        return base.ExecuteResultAsync(context);
    }
}
```

The app should have a proxy, that defines an alternate route to the same function:
```
{
"$schema": "http://json.schemastore.org/proxies",
"proxies": {
    "functionProxy": {
        "matchCondition": {
            "methods": ["GET"],
            "route": "/proxied/ProxyTestFunction"
        },
        "backendUri": "https://localhost/direct/ProxyTestFunction"
    }
}
}
```

When calling the function directly via http://localhost:7071/direct/ProxyTestFunction the result is {"value":"localhost:7071","hasValue":true,"host":"localhost","port":7071}
Whe calling via http://localhost:7071/proxied/ProxyTestFunction the result is
{"value":null,"hasValue":false,"host":"","port":null}

[Repro project](https://github.com/Azure/azure-functions-host/files/5319475/ProxyBugFunctionTest.zip)

**Comment by v-anvari** [comment]
Hi @ikaplans , Apologies for the delayed response, Are you still facing this issue, the issue was somehow lost in the trace. Were you able to find any solution. While working with proxies, you could also try using the serverless model of APIM

**Comment by ikaplans** [comment]
Hello,

The issue is still relevant.
No workaround has been found.

Regards,
Ilya
