### ISSUE TITLE
Attempt to recreate deleted function app fails with "Website with given name {0} already exists."

### ISSUE THREAD

**Issue by aradice-truenorth** [Azure/azure-functions-host#6749]
I needed to move a function app to a different subscription (with the same name as this is known to an external system) so I deleted the function app, storage account and app service plan and attempted to run my PowerShell script that creates and configures these in the new subscription. The step of the script which deploys the resources using an ARM template failed with:

```
ValidationError: Deployment failed. Correlation ID: d8102b20-ced3-4e8d-b1c7-6ed99f09031d. {
  "Code": "Conflict",
  "Message": "Website with given name mti-propaut-netsuiteproxy already exists.",
  "Target": null,
  "Details": [
    {
      "Message": "Website with given name mti-propaut-netsuiteproxy already exists."
    },
    {
      "Code": "Conflict"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "54001",
        "MessageTemplate": "Website with given name {0} already exists.",
        "Parameters": [
          "mti-propaut-netsuiteproxy"
        ],
        "Code": "Conflict",
        "Message": "Website with given name mti-propaut-netsuiteproxy already exists."
      }
    }
  ],
  "Innererror": null
}
```

I attempted instead to recreate the function in the original subscription so that I could move it to the new subscription. When I entered the function name in the UI an error indicated that the name was not available. 

I thought that maybe there was a stale DNS entry somewhere so I left it over the weekend (about 67 hours at time of writing) but I still cannot create the function through either route (UI or ARM template) this morning. I have checked using an online DNS lookup (https://mxtoolbox.com/) and the DNS entry mti-propaut-netsuiteproxy.azurewebsites.net is available. Please help!

**Comment by pragnagopa** [comment]
@aradice-truenorth - can you retry creating under the same subscription? If it succeeds, please migrate resources following instructions here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/move-resource-group-and-subscription

**Comment by aradice-truenorth** [comment]
@pragnagopa I attempted instead to recreate the function in the original subscription so that I could move it to the new subscription. When I enter the function name in the UI an error indicates that the name isnot available.

**Comment by v-anvari** [comment]
Hi @aradice-truenorth , There could be a duplicate entry made or the issue might be occurring during the deployment. 
Are you still finding the error? if yes, Can you share the repro steps in detail, so that we can clone the issue from our end.

**Comment by aradice-truenorth** [comment]
@v-anvari this issue is very simple to reproduce: if I attempt to create a new function app either using az or the Azure portal that has a name of "mti-propaut-netsuiteproxy" a message tells me that the name is already in use. But not function app with this name exists in either of my Azure subscriptions and a DNS lookup to mti-propaut-netsuiteproxy.azurewebsites.net finds nothing.

Azure appears to have got into an inconsistent state internally. Do you have access to be able to fix this? I know I could use a different name but an external system has already been configured to point to this address and reconfiguration of the system is time consuming.

**Comment by v-anvari** [comment]
Hi @aradice-truenorth , Thank you for pointing this out. I am able to reproduce the issue. I will check with the team internally and get back to you soon. Apologies for the delay

![image](https://user-images.githubusercontent.com/66122429/103914446-dbed3200-512f-11eb-8b63-495657b25eee.png)

**Comment by paulbatum** [comment]
@aradice-truenorth This type of problem is unrelated to the azure functions host (this repo). It relates to the App Service / Functions hosting infrastructure itself. You'll need to create a support request. In the left hand nav for any function app (I know you can't open it for the original app because its been deleted), you'll see the support / troubleshooting  section with this option:
![image](https://user-images.githubusercontent.com/10663/103927305-0529a600-50cf-11eb-96dd-044ea7629ba0.png)
