### ISSUE TITLE
Handle language worker shutdown failures during worker restart

### ISSUE THREAD

**Issue by divyagandhisethi** [Azure/azure-functions-host#6754]
This issue is tracking the fix for one of the CRIs where language worker gets stuck while restarting on function invocation timeouts.  @yojagad pointed to this line - https://github.com/Azure/azure-functions-host/blob/v2.x/src/WebJobs.Script/Workers/ProcessManagement/WorkerProcess.cs#L192 which might be the issue.

**Comment by yojagad** [comment]
cc: @pragnagopa @mhoeger 

It looks like there can be cases where WaitForExit() can enter a deadlocked state even if the process exits. Might need to explore alternate solutions.

**Comment by pragnagopa** [comment]
Thanks for opening the issue. We should switch to WaitForExit(timeout) - https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.waitforexit?view=netcore-3.1#System_Diagnostics_Process_WaitForExit_System_Int32_
