### ISSUE TITLE
FunctionMetadataManager uses stale AssemblyLoadContext

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-host#6766]
There's a race condition in the flow where `ScriptStartupTypeLocator` calls `FunctionMetadataManager` to get the FunctionMetadata.

When ScriptHost restarts due to a file change, `ScriptStartupTypeLocator` calls `FunctionMetadataManager` to get a new set of functions for bundle optimization. `FunctionMetadataManager` gets the `IFunctionProviders` from the service provider, but the service provider returns the services from the old ScriptHost.

**Comment by pragnagopa** [comment]
Needs more investigation. Moving to next sprint.
