### ISSUE TITLE
How to filter out information logging, but retain custom metrics

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-host#6768]
**environment :** Functions v3 / C#

I want to filter out the trace informational noise from my Azure Function App logging.

![image](https://user-images.githubusercontent.com/4224880/95434050-b2621600-0948-11eb-9832-90c3f35f02e0.png)

So provided the default configuration to filter all logs to `Warning` level.

![image](https://user-images.githubusercontent.com/4224880/95428728-50ea7900-0941-11eb-8eee-d3b28e57ac9e.png)

This removes the 'Executing' / 'Executed' logs as expected.

---

**However** now my custom metrics which I am emitting via `TelemetryClient.GetMetric` / `TrackValue` are also being discarded.

I can't filter more explicitly in the `host.json` using the function category (i.e. `Function.X`) as the custom Metrics are also published under this same category.

How do I get rid of the default trace informational noise from the function, yet retain my custom metrics?

**Comment by v-bbalaiagar** [comment]
Hi @olitomlinson, Apologies for the delayed response, Please go through the documents below to filter logs by source in host.json
https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#logging
https://docs.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2#configure-log-levels

Related Information: 
[Azure/azure-functions-host/issues/4474](https://github.com/Azure/azure-functions-host/issues/4474)
https://medium.com/99xtechnology/filter-application-insight-logs-for-azure-durable-functions-5558b19ebaa1
