### ISSUE TITLE
Integration with Azure Notification Hubs NuGet library

### ISSUE THREAD

**Issue by mpodwysocki** [Azure/azure-functions-host#6773]
#### Investigative information

Please provide the following:

- Timestamp:
- Function App version:
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

#### Repro steps

Provide the steps required to reproduce the problem:

According to the [Azure Functions for C# Reference](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#referencing-external-assemblies), we should be able to automatically reference the Azure Notification Hubs NuGet of [`Microsoft.Azure.NotificationHubs`](https://www.nuget.org/packages/Microsoft.Azure.NotificationHubs/).  When importing this library, however, gives an error of the following:

```
[Error] run.csx(2,1): error CS0006: Metadata file 'Microsoft.Azure.NotificationHubs' could not be found
```

Steps to reproduce:

1. Create new C# .NET Core 3.1 Function
2. Create C# function with a reference to `#r Microsoft.Azure.NotificationHubs`
3. Run the function and receive the above error.

Sample code as follows:

```csharp
#r "Newtonsoft.Json"
#r "Microsoft.Azure.NotificationHubs"

using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Newtonsoft.Json;

public static async Task<IActionResult> Run(HttpRequest req, ILogger log)
{
    log.LogInformation("C# HTTP trigger function processed a request.");
}
```  

#### Expected behavior

Expected behavior is to properly import the library and make available in Azure Functions.

#### Actual behavior

The Azure Function, when invoked, gives a 500 error with the following:

```
[Error] run.csx(2,1): error CS0006: Metadata file 'Microsoft.Azure.NotificationHubs' could not be found
```

#### Known workarounds

No workarounds available

#### Related information 

Provide any related information 

* Programming language used C#
* Links to source
* Bindings used: Azure Notification Hubs

**Comment by mhoeger** [comment]
Unfortunately I think this documentation is only relevant for V1...

@brettsam - Should this guidance even exist still? https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#referencing-external-assemblies

cc: @ggailey777

**Comment by brettsam** [comment]
I'm not sure NotificationHubs was ever supported like that in v1, even: https://github.com/Azure/azure-functions-host/blob/v1.x/src/WebJobs.Script/Description/DotNet/FunctionMetadataResolver.cs#L58-L64

```csharp
private static readonly List<ISharedAssemblyProvider> SharedAssemblyProviders = new List<ISharedAssemblyProvider>
{
    new DirectSharedAssemblyProvider(typeof(Newtonsoft.Json.JsonConvert).Assembly), /* Newtonsoft.Json */
    new DirectSharedAssemblyProvider(typeof(ServiceBusAttribute).Assembly), /* Microsoft.Azure.WebJobs.ServiceBus */
    new DirectSharedAssemblyProvider(typeof(WindowsAzure.Storage.StorageUri).Assembly), /* Microsoft.WindowsAzure.Storage */
    new LocalSharedAssemblyProvider(@"^Microsoft\.AspNet\.WebHooks\..*"), /* Microsoft.AspNet.WebHooks.* */
};
```



Here's the current list for v2 and v3: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Description/DotNet/ScriptFunctionMetadataResolver.cs#L55-L59

```csharp
private static readonly List<ISharedAssemblyProvider> SharedAssemblyProviders = new List<ISharedAssemblyProvider>
{
    new DirectSharedAssemblyProvider(typeof(Newtonsoft.Json.JsonConvert).Assembly), /* Newtonsoft.Json */
    new DirectSharedAssemblyProvider(typeof(Microsoft.WindowsAzure.Storage.StorageUri).Assembly), /* Microsoft.WindowsAzure.Storage */
};
```

**Comment by mhoeger** [comment]
😮 !! @brettsam - can you review the docs changes? https://github.com/MicrosoftDocs/azure-docs-pr/pull/135667

@mpodwysocki - Can you try referencing the Notification Hubs NuGet library through a function.proj file instead [as documented here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#using-nuget-packages)? Apologies, it looks like our docs got stale there and we are fixing that!

**Comment by v-anvari** [comment]
Hi @mpodwysocki , I can no longer access the PR mentioned above, can you please confirm if the issue has been resolved for you, so that I can follow up as required
