### ISSUE TITLE
Load bindings in parallel

### ISSUE THREAD

**Issue by goiri** [Azure/azure-functions-host#6775]
#### What problem would the feature you're requesting solve? Please describe.
The bindings are loaded in series with the current code.

#### Describe the solution you'd like
Make them load in parallel.

**Comment by goiri** [comment]
I created a PR with the code changes:
https://github.com/Azure/azure-functions-host/pull/6774

**Comment by v-anvari** [comment]
Closing this issue as the PR resolves this issue
