### ISSUE TITLE
Enable EnsureWorkerForSiteV2 on SLA sites and verify placeholder hit rate

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#6777]

**Comment by pragnagopa** [comment]
Moved to Sprint 88 as changes are checked into ANT91. Need to wait for the roll out to start before analyzing the data.

**Comment by fabiocav** [comment]
Moving this to sprint 90, but this is blocked on an App Service release, just using this for tracking.

**Comment by fabiocav** [comment]
Work on this has resumed. This will continue in the next sprints.

**Comment by fabiocav** [comment]
Closing. the remaining work is being tracked internally.
