### ISSUE TITLE
Documentation improvement.

### ISSUE THREAD

**Issue by hem-sharma** [Azure/azure-functions-host#6778]
Microsoft.Azure.WebJobs SDK for creating Azure Functions has issues in reading `local.settings.json` if IConfiguration overrode by custom configuration. 

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version: V3
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

#### Repro steps

Provide the steps required to reproduce the problem:

1. Step A: Create a function app,
2. Step B: Add Queue Trigger functions,
3. Step C: Add code to use Dependency injection,
4. Step D: Create an empty IConfiguration using -

```c#
IConfiguration configuration = new ConfigurationBuilder().Build();
....
builder.Services.AddSingleton<IConfiguration>(configuration);
```
5. Step E: After overridden default configuration all functions (Queue, Timer, etc.) expecting Connection strings from local.settings.json or from the environment variables will start failing.

`A host error has occurred during startup operation '4a5fff7d-95bd-4f2f-933c-eb0f789b3e6c'.
[2020-10-10T03:08:59.833] Microsoft.Azure.WebJobs.Extensions.DurableTask: Unable to find an Azure Storage connection string to use for this binding.`

#### Expected behavior

After investigation, I found out that all the required settings (cron, connection strings) on which function binding depends are not only driven from environment variables values but these environment variables must be available in Configuration injected or available through DI.

Example:

If I have a Queue trigger with like:

```c#

[FunctionName("MyFunction")]
public static void Run([QueueTrigger("myqueue-items", Connection = "MyQueueConnection")]string myQueueItem, ILogger log)
{
...
}
```

then `MyQueueConnection` must be available in the Configuration section with the same name. But after injected a configuration excepting environment variables, it starts failing.

#### Actual behavior

This warning or note must be mentioned in the default templates or on documentation as while overriding the Configuration in DI then there should be `AddEnvironmentVariables()` injected or the required settings must be manually added as configuration sections under IConfiguration.

For this specific e.g.

```c#
IConfiguration configuration = new ConfigurationBuilder().AddEnvironmentVariables().Build();
```

#### Known workarounds

Make sure to check Configuration available in DI must have required binding settings.

#### Related information 

Provide any related information 

* Programming language used: C#
* Links to source
* Bindings used: Queue/Timer

**Comment by ThejaChoudary** [comment]
@gzuber able to repro the issue can you please look into this further

**Comment by v-anvari** [comment]
Opened a new document issue for further validation - https://github.com/MicrosoftDocs/azure-docs/issues/82589. Closing this issue here
