### ISSUE TITLE
Support for HTTP 3

### ISSUE THREAD

**Issue by prabh-62** [Azure/azure-functions-host#6779]
#### Describe the solution you'd like
Ability to switch to HTTP/3
<img width="1034" alt="http_3_functions" src="https://user-images.githubusercontent.com/13006107/95658253-fd199480-0ae6-11eb-8d76-1425bc1b83c7.png">

#### Additional context
- [Chrome is deploying HTTP/3 and IETF QUIC](https://blog.chromium.org/2020/10/chrome-is-deploying-http3-and-ietf-quic.html)
- [Cloudflare - HTTP/3: it's alive!](https://blog.cloudflare.com/http3-the-past-present-and-future/)

**Comment by v-bbalaiagar** [comment]
Hi @prabh-62,  Apologies for the delayed response. Were you able find a solution? do let us know if a follow up is required.
