### ISSUE TITLE
FileBufferingReadStream: Microsoft.AspNetCore.WebUtilities: Cannot access a disposed object

### ISSUE THREAD

**Issue by prabh-62** [Azure/azure-functions-host#6780]
#### Investigative information
If the order of Azure Function HTTP Trigger aren't in the order WebHost expects, the error messages coming out don't make much sense.

##### System
- `func --version`  -> `3.0.2931`
- `dotnet --version` -> `3.1.402`

Provide the steps required to reproduce the problem:

## Steps
- `> func new ImageService --dotnet`
- `> cd ImageService`
- `> func init` (Add a HTTP Trigger)
- Swap code in the new HTTP Trigger class with this snippet
```csharp
 public static class MergePDF
    {
        [FunctionName(nameof(MergePDF))]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "mergePDF/{id}")]
            string id,
            HttpRequest req,
            ILogger log)
        {
            var reader = new StreamReader(req.Body, Encoding.UTF8, true, 1024, true);
            {
                var body = await reader.ReadToEndAsync().ConfigureAwait(false);
                log.LogInformation(body);
                return new OkObjectResult(body);
            }
        }
    }
```
- `func start` and invoke the API.

#### Expected behavior

Azure Function API should error out with HTTP status code 500 and provide a helpful error message.

#### Actual behavior

Azure Function API returns HTTP status code 500 with a cryptic error message.
```log
[2020-10-10T16:40:23.683] Executed 'MergePDF' (Failed, Id=71d79e4b-5943-403b-a062-e52e201c828c, Duration=366ms)
[2020-10-10T16:40:23.683] System.Private.CoreLib: Exception while executing function: MergePDF. Microsoft.AspNetCore.WebUtilities: Cannot access a disposed object.
[2020-10-10T16:40:23.683] Object name: 'FileBufferingReadStream'.
```

#### Related information 

Provide any related information 

* Programming language used - C#
* Links to source
* Bindings used

**Comment by mikhail-khalizev** [comment]
`[HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "mergePDF/{id}")]` should be attached to `HttpRequest req`:
```
 public static class MergePDF
    {
        [FunctionName(nameof(MergePDF))]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "mergePDF/{id}")]
            HttpRequest req,
            string id,
            ILogger log)
        {
            var reader = new StreamReader(req.Body, Encoding.UTF8, true, 1024, true);
            {
                var body = await reader.ReadToEndAsync().ConfigureAwait(false);
                log.LogInformation(body);
                return new OkObjectResult(body);
            }
        }
    }
```

**Comment by prabh-62** [comment]
I understand that the issue can be fixed by attaching `HttpTrigger` to `HttpRequest`. However, the reason, I opened this issue was to provide a descriptive error message instead of `Cannot access a disposed object`

**Comment by v-anvari** [comment]
Hi @prabh-62 , Apologies for the delay, Can we understand if you are looking for a triage to this issue? Do you have any queries or updates?

**Comment by prabh-62** [comment]
Nothing new from my side

**Comment by v-anvari** [comment]
Hi @prabh-62 , Can we know if you are still looking for a solution, so that I can follow up with the right team and close the issue accordingly

**Comment by prabh-62** [comment]
You can close this issue.

**Comment by v-anvari** [comment]
Thank you for the update
