### ISSUE TITLE
consumption plan scaling understanding.

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/azure-functions-host#6793]
I have azure function project with say 5 different service bus trigger functions.
  app
       f1,f2,f3,f4,f5
in consumption plan how scaling happens ?
1.  will az function scaler create multiple instances of my funcApp on different host machines ? (what appinsight parameters can tell me how many machines it was scaled to ? hostinstanceid  or cloud_roleInsance ? what is difference between them ?)

2. if say my funcapp got scaled to 3 instances i1,i2,i3  then f1 in each of these instances will do parallel processing of messages right ?
3.  if i set website scale limit to 1 and if there are multiple messages and f1 will execute one message with invocation id 1 and then again invocation id 2 instance will be used to process the next message ?

4. please share some detailed doc links if u have about how internals work . i want to understand and design accordingly.

please advise 
thanks
krishna

**Comment by v-anvari** [comment]
Hi @krishnasingh1818 , Apologies for the delayed response

Here is a document on how scaling works in Azure Functions - https://docs.microsoft.com/en-us/azure/azure-functions/event-driven-scaling#runtime-scaling

Here is a scale comparison between different plans - https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#scale

hostInstanceId is a function App log output, which indicates the dedicated host id in which the the function is running. 

Here is some information on how to configure logs : https://docs.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2

You can also now query the scale controller logs to understand how scale controller works - https://docs.microsoft.com/en-us/azure/azure-functions/analyze-telemetry-data#query-scale-controller-logs

Closing this issue as the required information is provided, please feel free to reach back to us or re-open this issue in case of any queries.
