### ISSUE TITLE
Move EventGrid Blob trigger work to Azure SDK repository

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-host#6794]
Azure SDK Azure Storage Extension:
https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Webjobs.Extensions.Blobs

EventGrid Blob Trigger:
https://github.com/Azure/azure-webjobs-sdk/pull/2438

**Comment by fabiocav** [comment]
The code has been migrated to the new repo. PR will be opened from there.

**Comment by fabiocav** [comment]
Closing as resolved. PR will be opened soon.
