### ISSUE TITLE
Pin Apps to ~2.0 

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#6795]
Pin identified breaking apps on auto-upgrade to ~2.0

**Comment by pragnagopa** [comment]
Completed:
- Public cloud windows
- National cloud windows

TODO:
-  Public cloud Linux consumption
-  Public cloud Linux AppService / EP
-  National clouds Linux Consumption
-  National clouds Linux AppService / EP

**Comment by fabiocav** [comment]
Currently in progress; moving to sprint 88

**Comment by pragnagopa** [comment]
Public cloud Linux AppService / EP - Done

**Comment by pragnagopa** [comment]
Did not find any potentially breaking apps in Linux consumption / dedicated/ EP in national clouds

**Comment by pragnagopa** [comment]
Blocked on pinning Linux consumption apps. Will work with @divyagandhii to unblock

**Comment by fabiocav** [comment]
Closing as done.
