### ISSUE TITLE
[Linux]Prepare for auto-upgrade

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#6798]
cc @anirudhgarg @mhoeger 

- Generate 2.1.xxxx images with same build as 3.0.xxxx
-  Install `libcurl` on 2.1.xxxx images

copying notes from email thread:

When an environment variable "DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER" is set to false on a Linux environment, "you need to deploy libcurl yourself if you want to use the old HttpClient implementation. If you have .NET Core 2.0 working on your machine, then libcurl is already installed," per docs: https://github.com/dotnet/core/blob/57c2195c0bb533ae023d21ce2fd754b5d7e03e8d/release-notes/2.1/2.1.0.md#networking-performance and https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=netcore-3.1#remarks

**Comment by fabiocav** [comment]
Need to follow up on the status of this work

**Comment by pragnagopa** [comment]
No action needed. Auto-upgrade completed as part of https://github.com/Azure/app-service-announcements/issues/266 , no issues reported that are specific to Linux Function Apps.
