### ISSUE TITLE
Proxy Name FunctionMetadata duplicate Error

### ISSUE THREAD

**Issue by Satak** [Azure/azure-functions-host#6801]
If you set Proxy name as same as your function, you will get an error:

`Microsoft.Azure.WebJobs.Script: Found duplicate FunctionMetadata with the name <name>.`

![image](https://user-images.githubusercontent.com/10957012/96241622-1c169b80-0fab-11eb-89b2-d130bb144921.png)

Proxy settings:

![image](https://user-images.githubusercontent.com/10957012/96241656-2769c700-0fab-11eb-92d7-af799758a548.png)

This is not documented that you can't have the same name for function and proxy setting.

**Comment by v-bbalaiagar** [comment]
Hi @Satak, Apologies for the delayed response, We would like to know if you were able to find a solution to this issue. Kindly let us know so that we can look into this further.

**Comment by Satak** [comment]
I just renamed my proxy setting differently than function

**Comment by v-bbalaiagar** [comment]
Hi @Satak, Function names and proxy names must be globally unique. Proxies ultimately become functions.
