### ISSUE TITLE
Issue using nuget package Microsoft.CognitiveServices.Speech with function.proj (native Microsoft.CognitiveServices.Speech.core.dll)

### ISSUE THREAD

**Issue by rggammon** [Azure/azure-functions-host#6804]
I am trying to add Microsoft.CognitiveServices.Speech to my function using https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#using-nuget-packages

I created the following function.proj file:
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CognitiveServices.Speech" Version="1.13.0" />
    </ItemGroup>
</Project>
```

In the logs, I see:
```
2020-10-16T18:37:37.122 [Information] Starting packages restore
2020-10-16T18:37:42.315 [Information] Determining projects to restore...
2020-10-16T18:37:46.129 [Information] Restored D:\local\Temp\55bc6a2d-b370-4231-a07c-061bbd8d8c7d\function.proj (in 2.94 sec).
2020-10-16T18:37:46.582 [Information] Packages restored.
2020-10-16T18:37:46.582 [Information] Package references have changed.
2020-10-16T18:37:46.875 [Information] Assembly reference changes detected. Restarting host...
```
... and in my function run.csx, I am adding:
```
using Microsoft.CognitiveServices.Speech;
using Microsoft.CognitiveServices.Speech.Audio;
...
var config = SpeechConfig.FromSubscription("<myspeechkeyhere>", "eastus");
```

Compilation is successful:
```
2020-10-16T19:54:24.091 [Information] Compilation succeeded.
```

... but execution fails:
```
2020-10-16T19:55:53.652 [Error] Executed 'Functions.HttpTrigger1' (Failed, Id=1ee1cece-5927-4dfa-b9fa-7ec0bb868e01, Duration=75ms)Unable to load DLL 'Microsoft.CognitiveServices.Speech.core.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
```

... and when I look at D:\home\site\wwwroot\HttpTrigger1 in kudu, I don't see the dll.

In the nuget package, this file is at:
Microsoft.CognitiveServices.Speech.1.13.0\runtimes\win-x64\native\Microsoft.CognitiveServices.Speech.core.dll

I think this is a native dll.

Is there a way to get Microsoft.CognitiveServices.Speech working with Azure Functions? I want to get an in-memory stream of synthesized voice, as described at: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-text-to-speech "Get result as an in-memory stream"

**Comment by rggammon** [comment]
https://www.garypretty.co.uk/2019/04/02/generating-realistic-speech-on-the-fly-with-azure-functions-and-cognitive-services-speech-apis/ shows how to use the http rest endpoint of the cognitive speech service, if there is no way to use the nuget package.

**Comment by v-bbalaiagar** [comment]
Hi @rggammon, Apologies for the delayed response, the issue was somehow lost in the trace. Were you able find a solution? do let us know if a follow up is required. I shall follow with the right team members to resolve this issue.

**Comment by rggammon** [comment]
The solution from Gary linked to above is a good work-around, but it would be great to have a library that can be used server-side without the native dll dependency, since it is the native dll dependency that breaks the library in the azure functions scenario.
eg: it would be great if the library could still load and make network calls, even if Microsoft.CognitiveServices.Speech.core.dll is not present, or something along these lines.

**Comment by v-bbalaiagar** [comment]
Hi @rggammon, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @rggammon, Discussed this request internally, currently there is no support for this scenario. But, Will be considering this suggestion forward.
Closing this issue, please feel free to reach back to us in case of any further queries related to this issue.
