### ISSUE TITLE
The eventhub triggered function doesn't scale above 20 instances

### ISSUE THREAD

**Issue by Badabum** [Azure/azure-functions-host#6809]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app, select `Diagnose and solve problems` from the left, and view relevant dashboards before opening your issue.

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version: v3
- Function App name: ingestion-processor
- Function name(s) (as appropriate): ProcessRawPost
- Invocation ID:
- Region: CentralUS

#### Repro steps

1. Create a function app
2. Publish single event hub triggerd function
3. Create event hub with 20 throughput units and 32 partitions.
3. Add load to EventHub. in my scenario it's rooughly 20k msgs/minute
4. Observe scaling behavior in the Live Metrics
5. There is max of 20 instances running for given function app. Even though, all instances have 50%+ CPU and processing 100+ requests/second

#### Expected behavior

Function app scales to at least 32 instances to match the count of partitions in event hub. I would expect it to scale even further though.

#### Actual behavior

There is at max 20 instances

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by v-anvari** [comment]
Hi @Badabum , to understand the cause better, can you tell us what is the plan used? 

If its a [dedicated plan](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#scale), then the max instances is 20, after which it scales out.

**Comment by Badabum** [comment]
Hi @v-anvari , nope, it was consumption plan.

**Comment by Badabum** [comment]
Not sure what was the cause, because we tried a lot of different things and nothing helped at that time. We mitigated the issue by moving the event hub triggered function to a separate app with its own storage account and changed logic to reduce function execution time. Right now it scales even beyond 40 instances(most of which are idle)  Let me know if yo
u need more information.

**Comment by v-anvari** [comment]
Hi @Badabum , since the previous app is moved, we wouldn't be able to tell the cause. But let us know if are you facing issues with the new app?
