### ISSUE TITLE
Can I inject IDurableOrchestrationContext using depedency injection?

### ISSUE THREAD

**Issue by EnenDaveyBoy** [Azure/azure-functions-host#6811]
in V3 C# can i inject IDurableOrchestrationContext into something like a mediatr pipeline or/and a service class?

I have it working in an old project but can't get it to work in a new project in visual studio code?
 I can't find any information on it and no matter what i try it doesn't work.
Happy to upload anything needed to figure it out but thought I would find out if its possible first.

at present the dependency inject IDurableOrchestrationContext  is always null (its fine in the function class), even though everthing else is injected fine.

**Comment by v-anvari** [comment]
@fabiocav, could you please assign it to Durable repo

**Comment by olitomlinson** [comment]
@EnenDaveyBoy 

Unfortunately, you can’t use durableOrchestrationContext through DI.

However, as of 2.4.0 you can use the durableClient through DI.

**Comment by EnenDaveyBoy** [comment]
sorry forgot all about this,all sorted thanks
