### ISSUE TITLE
Update LogAnalytics Schema

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#6825]
We're now sending new columns with Azure Monitor, so we'll need to update the schema once it's deployed everywhere.

**Comment by fabiocav** [comment]
PR is out, currently waiting for a sign-off from an external team.

**Comment by fabiocav** [comment]
@brettsam ; need to follow up to understand where this is now. Will move to sprint 90 to track.

**Comment by fabiocav** [comment]
@brettsam can you provide an update on the status of this issue? Moving to sprint 93 for tracking.

**Comment by fabiocav** [comment]
Closing as complete. Waiting for the deployment/release.
