### ISSUE TITLE
maxConcurrentCalls not working

### ISSUE THREAD

**Issue by kosnkow** [Azure/azure-functions-host#6830]
having this "serviceBus": {
      "messageHandlerOptions": {
        "maxConcurrentCalls": 1
      }
    }

does not affact how servicebus azure function takes out messages to process from service bus queue.
Even if I set this to 1 and run the function locally it process as many messages in paralell as it can (multiple threads ) this is blocking us to go to release.

**Comment by v-anvari** [comment]
Hi @kosnkow , we would like to know how you have developed the scenario locally, and what language you have used. Repro steps would be helpful. 

If its possible to paste the code that's busted, then it will be helpful for us to repro the issue
