### ISSUE TITLE
Debug Telemetry from Azure Function?

### ISSUE THREAD

**Issue by ghost** [Azure/azure-functions-host#6834]
On my Azure V3, C#, HTTP Trigger function, I DI the TelemetryConfiguration and make a new TelemetryClient:

```
public SendGridWebHookEndPoint(PersonicomDBContext context, ILogger<SendGridWebHookEndPoint> logger, TelemetryConfiguration telemetryConfiguration)
        {
            _dbContext = context;
            _log = logger;
            _telemetryClient = new TelemetryClient(telemetryConfiguration);
        }
```
In my local environment I can't see any of my Application Insight Events, Exceptions, or Traces. I've disabled sampling via samplingSettings->isEnabled.

Is there something else I need to do to see AppInsight data locally via the VS 2019 Application Insights Search window when using Azure Functions Host?

**Comment by v-bbalaiagar** [comment]
Hi @foconnor-DS, Apologies for the delayed response. Could you please go through the [document](https://docs.microsoft.com/en-us/azure/azure-monitor/app/diagnostic-search#where-do-you-see-search) to see an Application Insights Search window in the azure portal and in visual studio. Let us know if you are able to solve with this information.

**Comment by v-bbalaiagar** [comment]
Hi @foconnor-DS, Closing this issue, please feel free to re-open the issue for any further queries regarding this issue.
