### ISSUE TITLE
Azure Function App "Function Runtime Setting" changed to "Custom" automatically from verison 3

### ISSUE THREAD

**Issue by onlywithlad** [Azure/azure-functions-host#6843]
Hi Team,
I upgraded my function app from dot net core 2.1 to 3.1 and same was deployed with function runtime setting as 3 from dropdown - "Runtime Version"
But after 3 days "Function Runtime Setting" automatically changed to "Custom" from version 3 and now dropdown is not editable. that is my function app version changed to version 2. so function app stopped working.
Can anyone guide me why this issue happened?

**Comment by ThejaChoudary** [comment]
@onlywithlad  Can you share the app details and timestamp etc to invetigate further.
Thank you!
