### ISSUE TITLE
AccessDenied after continuously loading DDLs using Assembly.Load()

### ISSUE THREAD

**Issue by feskensa** [Azure/azure-functions-host#6846]
#### Investigative information

Please provide the following:

- Timestamp: 10/27/2020, 1:06:41.257 PM (UTC)
- Function App version: 3.0.14785.0
- Function App name: functionrepro 
- Function name(s) (as appropriate): Function
- Invocation ID: 6fade0fea055c041
- Region: North Europe

#### Repro steps

I prepared a [repo ](https://github.com/sn0wtorch/reprofunction) with the code for the function, a simple DLL, and a small console to call the function in rapid succession.

This will work exactly _once_ after which the function has to be restarted since it never seems to recover. 

If you want to create your own function, just deploy the "Function" -- its linked to a temporary storage where the DLL is already uploaded. 

For full repro steps, including changing the storage the function is using:

1. Build, get bytes for the DLL, convert to base64 string and upload to storage of your choice
2. update storage reference in function
3. deploy function
4. update URL to call in console program
5. start console program / Postman runner => call the function in rapid succession for about 500-1000 requests

#### Expected behavior

Be able to load DLLs using Assembly.Load and creating an instance of a type inside that DLL using Activator.CreateInstance without hitting an "invisible" limit.

#### Actual behavior

After 500-1000 requests (sometimes a bit more) an "invisible" limit is hit on the amount of DLLs that are loaded into the AppDomain. Any loading after this limit is hit fails, returning "Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)" and the function is unable to recover from this.

#### Known workarounds

Found 2 possible workarounds:

- Restart the function whenever this occurs (Obviously not good)
- Take the code and move it to a asp.net core webapp (for some reason the webapp is perfectly happy loading many thousands of DLLs)

#### Related information 

Provide any related information 

* Programming language used : C# 
* Framework: netcoreapp3.1
* Links to source: [repo ](https://github.com/sn0wtorch/reprofunction) 
*Added screenshot of HTTP Server Errors, Loaded Assemblies, and Memory below

<details>
<summary>Problem happens at [...] Assembly.Load[...]</summary>

```csharp

        // Extract type from DLL and create an instance of that type
        public async Task<dynamic> LoadAsync(string dllBlobRef)
        {
            TypeInfo modelTypeInfo = await ExtractTypeInfo(dllBlobRef);
            dynamic instance = Activator.CreateInstance(modelTypeInfo);

            return instance;
        }

        // Get DLL Blob from storage, convert it back into bytes, load dll, and return (for test purposes) first type found.
        private async Task<TypeInfo> ExtractTypeInfo(string dllBlobRef)
        {
            string base64ModelBlobContent = await _blobStorage.DownloadTextAsync(dllBlobRef);
            byte[] assemblyByteArray = Convert.FromBase64String(base64ModelBlobContent);
            Assembly modelAssembly = Assembly.Load(assemblyByteArray);

            return modelAssembly.DefinedTypes.First();
        }
```

![image](https://user-images.githubusercontent.com/42011198/97325222-09d21280-1873-11eb-9d8a-480a089efbe1.png)

</details>

**Comment by feskensa** [comment]
Did anyone have a chance to look at this?

Let me know if I can help in any way :)

**Comment by v-anvari** [comment]
Apologies for the delayed response. Were you able find a solution? do let us know if a follow up is required
