### ISSUE TITLE
Roll-out V2 to V3 auto-upgrade

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#6856]
cc @divyagandhii 

Tracking issue to setup repro apps in linux consumption and dedicated and also to monitor logs as we start auto-upgrading linux stamps.

**Comment by fabiocav** [comment]
Work here will continue in sprint 89

**Comment by fabiocav** [comment]
Validation has been done in UD0 for Linux consumption

**Comment by fabiocav** [comment]
Rollout in progress on Linux. Closing this as the initial work has been completed.
