### ISSUE TITLE
Azure Function App on Linux consumption plan zipdeploy error

### ISSUE THREAD

**Issue by Dhruv-1982** [Azure/azure-functions-host#6857]
I am trying to deploy my package on azure function app with Linux consumption plan. I am using zipdeploy from powershell. the endpoint i am using is like "https://functionapp.scm.azurewebsites.net/api/zipdeploy". I am trying to execute the below

Invoke-RestMethod -Uri $apiUrl -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} -Method POST -InFile $filePath -ContentType "multipart/form-data"

But everytime i am getting error 
Invoke-RestMethod : The remote server returned an error: (404) Not Found.

Client is powershell (Module- Azurerm)

I have not done any deployment yet so unable to share the function app execution details for the app.

**Comment by Dhruv-1982** [comment]
Log Stream Details of my App

2020-10-29T21:45:42Z   [Information]   Host Status: {
  "id": "*******",
  "state": "Running",
  "version": "3.0.14492.0",
  "versionDetails": "3.0.14492 Commit hash: b088b9dad1238cef70931c608f16c5c315d328fb",
  "processUptime": 807564

**Comment by balag0** [comment]
Could you try Option 2 from
https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

to share the app name privately. It should work for apps with no deployments as well.

**Comment by Dhruv-1982** [comment]
Here is the execution details
2020-11-02T06:29:26Z   [Information]   Executed 'DeviceTwinChangeTopicDLQProcessingFunc' (Succeeded, Id=d64e024f-a232-44e7-979d-fb614c25a908, Duration=5027ms)

We are facing the same problem for all our function apps hosted on consumption plan.

**Comment by Dhruv-1982** [comment]
Any update the issue?

**Comment by itshemant09** [comment]
@Dhruv-1982 : try this it should work
$apiUrl = "https://$sitename.scm.azurewebsites.net/api/zipdeploy"
$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $username, $password)))
$userAgent = "powershell/1.0"

 

Invoke-RestMethod -Uri $apiUrl -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)} -UserAgent $userAgent -Method POST -InFile $warFilePath -ContentType "application/x-www-form-urlencoded"

**Comment by Dhruv-1982** [comment]
This works. Thanks for the details.

**Comment by itshemant09** [comment]
@balag0 @pragnagopa  I think we can close this and improve our docs.

@Dhruv-1982 do let us know if you need any help 🙂

**Comment by swettstein** [comment]
the resolution was not very helpful for me. what exactly was the problem and fix?

**Comment by balag0** [comment]
ContentType was mismatched. Should be set to application/x-www-form-urlencoded

**Comment by swettstein** [comment]
@balag0 only when using WAR file instead of ZIP?

i'm using this: 
`Invoke-WebRequest -Uri "https://$resourceName.scm.azurewebsites.net/api/zipdeploy?isAsync=true" -Method Post -Headers @{Authorization = ("Basic {0}" -f $auth)} -InFile $zip -ContentType  'multipart/form-data'`

and it works for windows/consumption function apps but is not working for linux/consumption function apps. i tried using `application/x-www-form-urlencoded` but it returned a 403 instead and when navigating to it in the portal, it appears to be running just fine.

**Comment by balag0** [comment]
Could you please open a new issue and include the appname as well using
https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately
