### ISSUE TITLE
Individually manipulating the maxPollingIntervall for each Function

### ISSUE THREAD

**Issue by plamber** [Azure/azure-functions-host#6862]
I am looking for a way to manipulate the maxPollingIntervall of individual functions. The host.json can be used to specify a global setting for the maxPollingInterval.

On the other hand, is there a way for me to specify different settings for each individual function? I am fine with writing code to accomplish this task.

We work with ASP.NET core and C#.

Thank you for your feedback,

**Comment by ankitkumarr** [comment]
@mathewc, do you know if there's a way for someone to specify maxPollingInterval for individual functions?

**Comment by mathewc** [comment]
The only way would be to register your own IQueueProcessorFactory instance [via DI](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection) which will allow you to selectively override things based on queue name, etc. There's an example in the tests [here](https://github.com/Azure/azure-webjobs-sdk/blob/ed4ff86f527178bfb73c27e90793ea955c793841/test/Microsoft.Azure.WebJobs.Host.EndToEndTests/AsyncChainEndToEndTests.cs#L220).

**Comment by plamber** [comment]
Thank you @mathewc, this definitely helps.
