### ISSUE TITLE
Newly deployed function app using ARM templates will intermittently not be available during the first minutes after successful deployment

### ISSUE THREAD

**Issue by sven-hoffmann** [Azure/azure-functions-host#6863]
The issue is happening while provisioning new environments for testing purposes. These are short lived scenarios where the resources are created, tested and deleted. Even though the deployment succeeds, the environment is actually not ready for test cases to be executed against it – tests will sometimes just fail because of this issue.

I was directed to create an issue here from a support case on this topic where you can also find more context information if needed: 120092822001035

#### Investigative information

This can be intermittently reproduced in general, so timestamps or not really useful. We're working on a sensitive project, so I am not able to give information into our concrete resources publically.
- Timestamp: [not useful as this is a general issue]
- Function App version: 3
- Function App name: [omitted]
- Function name(s) (as appropriate): [omitted]
- Invocation ID: [omitted]
- Region: West Europe

#### Repro steps

Deploy an ARM template with the WEBSITE_RUN_FROM_PACKAGE instruction in the app_settings. Contact the function immediately after the deployment is successful (e.g. in a script or test case)

#### Expected behavior

After Azure Resource Manager confirms a successful deployment I can immediately use the functions I provided in the input declaration via WEBSITE_RUN_FROM_PACKAGE  and not run into any issues.

#### Actual behavior

Here's a log indicating how the function app behaves, checks happened every second after deployment:
```
1: SUCCESS
<snip>
7: SUCCESS
8: FAIL, Returned 301 HTTP/1.1 301 Moved Permanently, Location header redirecting in cycles (same url we queried)
9: SUCCESS
10: FAIL, Returned 301 HTTP/1.1 301 Moved Permanently, Location header redirecting in cycles (same url we queried)
11: FAIL, Returned 301 HTTP/1.1 301 Moved Permanently, Location header redirecting in cycles (same url we queried)
12: SUCCESS
<snip>
21: FAIL, Returned 301 HTTP/1.1 301 Moved Permanently, Location header redirecting in cycles (same url we queried)
```

This pattern will continue for the first minutes after the allegedly successful deployment and make any interactions completely unreliable.

We're using the consumption plan. Using the elastic premium plan makes matters worse. Then you get 500 errors mixed inbetween the 200s and 301s.

#### Known workarounds

Static sleeps help reduce the likelihood of this occurring but in the end it is still an unresolved race condition. No deterministic wait condition could be found as a reliable workaround.

#### Related information 

* Programming language used: typescript, nodejs runtime
* Links to source: [omitted]
* Bindings used: HTTP + Event Grid Trigger
* We use the consumption plan

**Comment by erwinkramer** [comment]
@sven-hoffmann I Stumbled on the same issue on an Elastic plan. Turns out WEBSITE_RUN_FROM_PACKAGE breaks the whole resource because there isn't any zip deployed to it. Which kind of makes sense but then again this isn't documented anywhere. 

It's also impossible to deploy a Zip to the function when you have WEBSITE_RUN_FROM_PACKAGE set in this scenario. Makes me wonder why it's possible to even put this value in an ARM template as it's function is very limited: Only if you have an existing function resource and only if there is a function deploy to it, THEN the option just works, but then again, the variable is being set already by the zip deploy process...

**Comment by sven-hoffmann** [comment]
@erwinkramer thank you very much for this response. I'm very surprised by this information. Reading the official documentation here: https://docs.microsoft.com/de-de/azure/azure-functions/run-functions-from-deployment-package there's no mention of such limitations.
What do you see as the recommended way to deploying a function app **including application code** in one go (template) atomically?

**Comment by erwinkramer** [comment]
@sven-hoffmann best I could do is make the WEBSITE_RUN_FROM_PACKAGE value 0 on initial deploy, and 1 after the first zip deploy. Not nice, but no good alternative on ARM deployments.

**Comment by sven-hoffmann** [comment]
@erwinkramer ok, well I still believe that the documented way of providing an **URL** to WEBSITE_RUN_FROM_PACKAGE should work as it is documented. See the link I posted above for this additional option to setting 0 and 1.

**Comment by erwinkramer** [comment]
@sven-hoffmann I'm not able to test with an URL, I only could test with 0 and 1 values.

**Comment by v-bbalaiagar** [comment]
Apologies for the delay in response. This issue was somehow missed, we are eager to know if you are still facing the same issue, so that we can look into it.

**Comment by erwinkramer** [comment]
@v-bbalaiagar i haven't seen this issue anymore, and i did deploy several times .

**Comment by sven-hoffmann** [comment]
@v-bbalaiagar I will need some time to check this. We have workarounds in place since the time I created this issue in November 2020. I suspect the issue is still there because in my eyes it is a conceptual issue.
