### ISSUE TITLE
Linux Dedicated/Premium: Write console logs to stdout

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-host#6887]
Part of #6215. 

Currently, user logs don't appear in Azure Monitor for function apps running on Linux dedicated and premium plans. By piping user logs to stdout, we can take advantage of existing infrastructure that writes stdout to AzMon. This is already done for Linux Consumption, so we should be able to use the same logic.

Right now stdout output goes to the AppServiceConsoleLogs table. Ideally, all output will go to a single, better-named table (FunctionsLogs) with filters for the user to separate specific streams, ex. Durable Functions specific output. Additional work required on Antares.

**Comment by fabiocav** [comment]
PR ready for review. Moving to sprint 96.
