### ISSUE TITLE
Migrate EventGrid Blob Trigger to azure-sdk-for-net

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-host#6888]
PR: https://github.com/Azure/azure-sdk-for-net/pull/17137

**Comment by fabiocav** [comment]
@alrod can you confirm that work for this is in progress? I'm assuming this will be done in sprint 90, correct?

**Comment by fabiocav** [comment]
PR in progress in the Azure SDK repo. Moving to sprint 91

**Comment by fabiocav** [comment]
PR has been signed off and will be merged in sprint 92

**Comment by alrod** [comment]
PR is merged.
