### ISSUE TITLE
Queue Trigger Invocation added to poison queue with no errors, warnings or exceptions

### ISSUE THREAD

**Issue by ADH-LukeBollam** [Azure/azure-functions-host#6894]
I have a queue triggered function which is occasionally stopping with no indication why. Logs are streaming from the job fine, until it is added to the poison queue.

For example, at 9:41 this job was added to the poison queue
![image](https://user-images.githubusercontent.com/24449147/98904623-e951bb80-24f4-11eb-8ecb-8f0366968ae7.png)

The end to end transaction does not contain any information on why it stopped (times here are in my local time)
![image](https://user-images.githubusercontent.com/24449147/98905144-e1464b80-24f5-11eb-9f67-0bf517384541.png)

But checking the invocation logs from the Function Monitor, it doesn't even appear there (ignore the other failures, they are from a known issue). See how the OperationId of this function is not listed anywhere:
![image](https://user-images.githubusercontent.com/24449147/98904703-156d3c80-24f5-11eb-9fd1-502d2074eed7.png)

#### Investigative information

Please provide the following:

- Timestamp: 11/11/2020, 09:31:10:503 UTC time
- Function App version: 3
- Function App name: 
- Function name(s) (as appropriate): 
- Invocation ID: 74c8f217-7a4c-434d-8acb-cc6f6a6ebeb5
- Region: Australia East

#### Repro steps

Provide the steps required to reproduce the problem:

No reproduce, usually re-running the job will succeed. Cause or what the error is is unknown.

#### Expected behavior

Provide a description of the expected behavior.

The job should succeed, or at least provide information on why it failed.

#### Actual behavior

Provide a description of the actual behavior observed.

The jobs intermittently fail without an error.

#### Known workarounds

retry the job

#### Related information 

Provide any related information 
Function is running on a Premium plan, deployed from Visual Studio. The job is configured to run one invocation per instance at a time.

Here is the host.json:

```
{
  "version": "2.0",
  "aggregator": {
    "batchSize": 1000,
    "flushTimeout": "00:00:30"
  },
  "extensions": {
    "queues": {
      "batchSize": 1,
      "maxDequeueCount": 1,
      "newBatchThreshold": 0
    }
  },
  "functionTimeout": "00:59:59",
  "logging": {
    "logLevel": {
      "Microsoft.EntityFrameworkCore": "Warning",
      "Function.MyFunction": "Information",
      "Host.Results": "Information",
      "default": "Information"
    },
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": false
      }
    },
    "console": {
      "isEnabled": "true"
    }
  }
}
```

**Comment by v-anvari** [comment]
Hi @LukeBolly, 

In your code:-
_"extensions": {
    "queues": {
      "batchSize": 1,
      **"maxDequeueCount": 1,**
      "newBatchThreshold": 0
    }
  },_

At, 2020-11-11 09:31:22.8721558, an exception - "_System.ArgumentOutOfRangeException_" was thrown as the Message has reached MaxDequeueCount of 1, it couldn't check any further, which lead to "Moving message to queue 'recording-import-jobs-poison'"

You can check the [failures and exceptions](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-exceptions#diagnosing-exceptions-using-visual-studio) in your application insight logs. Please reopen the issue in case of any concerns

**Comment by ADH-LukeBollam** [comment]
@v-anvari the exception you have linked is for a different invocation. Also the message was added to the poison queue at 09:41, 10 minutes after that exception.

maxDequeueCount is the number of retries after failure yes? Please look at the invocation number I linked, there is no information in there about why the job failed.

**Comment by v-anvari** [comment]
Hi @LukeBolly , My apologies for pasting the wrong link, I have updated the link. We are further investigating on the issue.

**Comment by v-anvari** [comment]
Invocation id- 74c8f217-7a4c-434d-8acb-cc6f6a6ebeb5
Host Instance Id: bd51ea76-b56a-4dfd-89c0-e60679091b29
Event name : Function started
Time stamp : 2020-11-11 09:31:10.5082262
Function incomplete

**Comment by ADH-LukeBollam** [comment]
Hi @v-anvari , I've had the same issue happen again, this time with even less logs. 

Please look at host: 67a95eb3-f3b6-498f-a61a-a3f2fc1459fe

The host starts, 5 minutes later it adds my job to the poison queue, and then shuts down! I don't get any logs of it even attempting to start the job. I don't know how I'm meant to attempt to fix this. I've got no errors in Kudu or app insights.

**Comment by v-anvari** [comment]
Hi @LukeBolly, I have moved the issue to investigation. Meanwhile, can I know if the invocation id  "67a95eb3-f3b6-498f-a61a-a3f2fc1459fe" is for a different function app? Can I know the region of the new App.

**Comment by ADH-LukeBollam** [comment]
That ID is for a Host, not an Invocation. Host is only alive for 20 minutes so you can see the full process of it starting, adding my job to the poison queue, then shutting down.

The Host is still in Australia East, for the same function app.

**Comment by v-anvari** [comment]
@soninaren, @sidkri Tagging them to figure out if drain mode will be a feasible option here.

**Comment by sidkri** [comment]
@v-anvari it does look like a candidate from the logs I pulled for HostInstanceId "bd51ea76-b56a-4dfd-89c0-e60679091b29" between 2020-11-11T09:00:00Z and 2020-11-12T10:00:00Z. The host is stopped while processing a message from the queue.  I do see a scale-in operation at the time and the host shuts down 37 seconds after invocation starts.

@LukeBolly do you know how long this function typically runs for when processing queue messages?

**Comment by mhoeger** [comment]
I'm also looking at this too, and it looks like their premium functions instances are scaling up and down frequently when scaling shouldn't be happening?

Here's an example of the scale vote, where we go from 1 => 2 workers:
```
SiteScaleVote: Queue is idle
SiteScaleVote: More than 1/2 Worker(s) are busy: BusyRatio 1
SiteInformation: Attempting to scale out because at least 1/2 triggers voted to add workers.
```

And looking into the instance that was already there, it wasn't actually processing anything? Then, when it scales back down almost immediately, a function execution is lost (drain mode not enabled yet).

@glennamanns and @wenhzha - this looks like the scaling behavior is too aggressive for this Premium (Windows) app. I'll send queries in email, but wanted to give you context here too

**Comment by mhoeger** [comment]
Hi @LukeBolly - it looks like processing each queue message is very computationally expensive and leads to high CPU on an instance. This means that we scale out to accommodate pretty much every new queue message and when we scale those instances back in, we sometimes see lost executions. There's a fix for the lost executions on scale in that is currently being rolled out. Glenna just enabled this for your site (thank you Glenna!) so you now have the fix. You shouldn't see executions that fail to complete anymore.

I'll leave this open but mark it as needing author feedback. If you don't see the issue anymore in the coming days, please close this issue. Thanks!

**Comment by ADH-LukeBollam** [comment]
Great, I'll keep an eye on it and let you know.

**Comment by v-anvari** [comment]
Follow up issue - https://github.com/Azure/azure-functions-host/issues/7518
