### ISSUE TITLE
dotnet restore fails on Docker on a Latest PC

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-host#6895]
Sometimes, dotnet restore fails on Docker by following error. If you use fast PC, it always happens.  Not always but sometimes. 
It happens when we use Docker and a fast PC.  For more details, you can refer to this [blog](https://tsuyoshiushio.medium.com/solving-flaky-dotnet-restore-issue-only-on-docker-failed-to-retrieve-information-cd847573c3f2) 

```
The SSL connection could not be established, see inner exception.
  Authentication failed because the remote party has closed the transport stream. (TaskId:69)
  GET https://www.myget.org/F/azure-appservice-staging/api/v2/FindPackagesById()?id='Microsoft.IdentityModel.Tokens'&semVerLevel=2.0.0 (TaskId:69)
07:18:18.448     1>/usr/share/dotnet/sdk/3.1.402/NuGet.targets(128,5): error : Failed to retrieve information about 'Microsoft.Azure.WebSites.DataProtection' from remote source 'https://dotnetmyget.blob.core.windows.net/artifacts/aspnetcore-dev/nuget/v3/flatcontainer/microsoft.azure.websites.dataprotection/index.json'. [/src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj]
/usr/share/dotnet/sdk/3.1.402/NuGet.targets(128,5): error :   Connection refused [/src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj]
NuGet.Protocol.Core.Types.FatalProtocolException: Failed to retrieve information about 'Microsoft.Azure.WebSites.DataProtection' from remote source 'https://dotnetmyget.blob.core.windows.net/artifacts/aspnetcore-dev/nuget/v3/flatcontainer/microsoft.azure.websites.dataprotection/index.json'.
---> System.Net.Http.HttpRequestException: Connection refused
---> System.Net.Sockets.SocketException (111): Connection refused
  at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
  --- End of inner exception stack trace ---
```

#### Repro steps

This issue is happen on https://github.com/Azure/azure-functions-docker-private (mesh image) for the development enveiornment. Sometimes happens, 

#### Expected behavior

dotnet restore works propery

#### Actual behavior

dotnet restore fails by the exception that I showed. 

#### Known workarounds

The root cause looks throttling on the private nuget respository.  So that if you use fast machine with Docker it will reach the threshold.  For preventing this, 

1. Update the NuGet.config by limiting number of concurrent request

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="maxHttpRequest" value="16" />
  </config>
  <packageSources>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
    <add key="azure_app_service" value="https://www.myget.org/F/azure-appservice/api/v2" />
    <add key="azure_app_service_staging" value="https://www.myget.org/F/azure-appservice-staging/api/v2" />
    <add key="azure-appservice-test" value="https://azfunc.pkgs.visualstudio.com/e6a70c92-4128-439f-8012-382fe78d6396/_packaging/azure-appservice-test%40Local/nuget/v3/index.json" />
    <add key="buildTools" value="https://www.myget.org/F/30de4ee06dd54956a82013fa17a3accb/" />
    <add key="AspNetVNext" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json" />
    <add key="Microsoft.Azure.Functions.PowerShellWorker" value="https://azfunc.pkgs.visualstudio.com/e6a70c92-4128-439f-8012-382fe78d6396/_packaging/Microsoft.Azure.Functions.PowerShellWorker/nuget/v3/index.json" />
  </packageSources>
</configuration>
```
#### Related information 

Provide any related information 

* Docker (I updated latest) (I tested Docker for Windows and WSL2) 

My PC always have it. My colleague who bought a new PC happens as well. 

One example Dockerfile that fails sometimes
https://github.com/Azure/azure-functions-docker-private/blob/master/host/3.0/buster/amd64/mesh-java8.Dockerfile

I'm wondering if I should send a pull request in here since it makes it slower your build. Or should I fix on the docker side? (e.g. we can override the Nuget.Config on the docker side. )

**Comment by v-bbalaiagar** [comment]
Hi @TsuyoshiUshio , Please let us know if this is yet to be triaged, so that I can route this issue to concerned team.
