### ISSUE TITLE
Unable to get custom domain in Durable Functions after upgrading to Functions V3

### ISSUE THREAD

**Issue by bachuv** [Azure/azure-functions-host#6898]
I received a customer issue from a customer running a Durable Function (JavaScript) saying that they no longer see their custom domain reflected in the response payload when they upgraded from Functions V2 to Functions V3. 

Here is the doc that talks about Durable Functions responses: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api#response.

#### Repro steps

1. Create a Durable Function JavaScript and deploy it to Azure
2. Create a custom domain
3. Confirm that the FUNCTIONS_EXTENSION_VERSION app setting is set to `~3`
4. Send a request to the DurableFunction's HTTP client function using the custom domain and the returned payload should have `azurewebsites.net` in the payload URIs instead of the configured custom domain.

#### Expected behavior

Sending an HTTP request to the Durable Function's HTTP client function, returns this payload.
```
{
    "id": "abc123",
    "purgeHistoryDeleteUri": "http://functionapp.<customdomain>/runtime/webhooks/durabletask/instances/abc123?code=XXX",
    "sendEventPostUri": "http://functionapp.<customdomain>/runtime/webhooks/durabletask/instances/abc123/raiseEvent/{eventName}?code=XXX",
    "statusQueryGetUri": "http://functionapp.<customdomain>/runtime/webhooks/durabletask/instances/abc123?code=XXX",
    "terminatePostUri": "http://functionapp.<customdomain>/runtime/webhooks/durabletask/instances/abc123/terminate?reason={text}&code=XXX"
}
```

#### Actual behavior

Sending an HTTP request to the Durable Function's HTTP client function, returns this payload.

```
{
    "id": "abc123",
    "purgeHistoryDeleteUri": "http://functionapp.azurewebsites.net/runtime/webhooks/durabletask/instances/abc123?code=XXX",
    "sendEventPostUri": "http://functionapp.azurewebsites.net/runtime/webhooks/durabletask/instances/abc123/raiseEvent/{eventName}?code=XXX",
    "statusQueryGetUri": "http://functionapp.azurewebsites.net/runtime/webhooks/durabletask/instances/abc123?code=XXX",
    "terminatePostUri": "http://functionapp.azurewebsites.net/runtime/webhooks/durabletask/instances/abc123/terminate?reason={text}&code=XXX"
}
```

#### Known workarounds

None

#### Related information 

- Durable Functions JavaScript, Durable extension version 2.3.0
- Durable Functions source code (getting the webhook): https://github.com/Azure/azure-functions-durable-extension/blob/6c7873d65e504fcd9d3ba17c6706e08324d6745f/src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs#L246
- Functions host code for WebHookProvider: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/WebHooks/DefaultScriptWebHookProvider.cs#L55-L69
- Functions host code for HostNameProvider: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/HostNameProvider.cs#L31-L51

cc @brettsam @mathewc

**Comment by v-anvari** [comment]
Apologies for the delayed response. Were you able find a solution? do let us know if a follow up is required

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
