### ISSUE TITLE
Breaking Change: HTTP response body downcast to text/plain if string object

### ISSUE THREAD

**Issue by sadgit** [Azure/azure-functions-host#6904]
#### Repro steps

Given a string response
return (ActionResult)new OkObjectResult($"Hello, {name}")

In v3 this will be downcast to "content-type = text/plain" when "accept */*" is requested
In earlier versions this will default to  "content-type = application/json" 

Now the response body is ```Hello, {name}```
Instead of ```"Hello {name}"```

This can upset brittle client code that assumes JSON will be returned.

If the accept header is set to "application/json" the response matches the request.

Is it possible to prefer json over text if no preference is stated.

**Comment by sadgit** [comment]
I have a workaround - but would prefer a host.json setting or attribute

```
   let CreateJPResponse (req: HttpRequestMessage) (status: HttpStatusCode, payload: _) =
        match req.Headers.Accept.ToString().Trim() with
        | null
        | ""
        | "*/*" ->
            let result = new JsonResult(payload)
            result.StatusCode <- (int status) |> Nullable
            result :> IActionResult
        | _ ->
            let result = new ObjectResult(payload)
            result.StatusCode <- (int status) |> Nullable
            result :> IActionResult
```

**Comment by v-bbalaiagar** [comment]
Hi @sadgit, Apologies for the delayed response, let us know if you were able to find a solution.
