### ISSUE TITLE
Azure Functions Proxies running locally return 404 but works in the Cloud

### ISSUE THREAD

**Issue by AlexanderAnishchik** [Azure/azure-functions-host#6905]
My setup:

- Windows 10 Pro
- Microsoft Visual Studio Enterprise 2019 Version 16.8.0
- Core Tools Version:  3.0.2996 Commit hash: c54cdc36323e9543ba11fb61dd107616e9022bba
- Function Runtime Version:  3.0.14916.0

**I have two solutions - one with functions and one with proxies. Everything works as expected in cloud but locally I'm receiving 404 each time I send a request via Postman. If I send a request directly to function - it works.**

Proxy solution files:
_proxies.json_
```json
{
  "$schema": "http://json.schemastore.org/proxies",
  "proxies": {
    "serialnumberapp": {
      "matchCondition": {
        "route": "/serialnumber/{version}/{functionName}"
      },
      "backendUri": "%SerialNumberAppURL%/api/{version}/{functionName}",
      "requestOverrides": {
        "backend.request.headers.x-functions-key": "%SerialNumberAppKey%"
      }
    }
  }
}
```
_local.settings.json_
```json
{
    "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "SerialNumberAppURL": "http://localhost:7071",
    "SerialNumberAppKey": ""
  }
}
```
Function solution starts with next endpoint:
  GetLicensesBySearch: [GET] http://localhost:7071/api/v1/GetLicensesBySearch

I'm trying to send request such a http://localhost:7070/serialnumber/v1/GetLicensesBySearch?Page=1&PerPage=10.

Any ideas? Thanks

**Comment by anthonychu** [comment]
Can you try changing `"backendUri": "%SerialNumberAppURL%/api/{version}/{functionName}"` to `"backendUri": "http://localhost/api/{version}/{functionName}"`?

`http://localhost` is a special value that routes to the same function app.

**Comment by AlexanderAnishchik** [comment]
@anthonychu Thanks for reply. But this is two **separate** function app. And `%SerialNumberAppURL%` is replaced by cloud host after deployment to azure. Anyway I tried and it didn't help. Should I provide some additional info?

**Comment by anthonychu** [comment]
@AlexanderAnishchik  Oh okay makes sense.

The route's match condition is `"/serialnumber/{version}/{functionName}"`. I think the URL you should be calling should be something like `http://localhost:7070/serialnumber/v1/GetLicensesBySearch?Page=1&PerPage=10`

**Comment by AlexanderAnishchik** [comment]
@anthonychu Yes, sorry, I'm calling `http://localhost:7070/serialnumber/v1/GetLicensesBySearch?Page=1&PerPage=10` It was typo in description of issue. Does not work in both cases.  I'm pretty sure it worked locally few month ago.

**Comment by anthonychu** [comment]
@AlexanderAnishchik I wonder if anything with “localhost” as the host gets routed by proxies to the same function app. Can you try changing the SerialNumberAppURL app setting to http://127.0.0.1:7071 ?

**Comment by AlexanderAnishchik** [comment]
@anthonychu yes, it works now with 127.0.0.1 instead of localhost for separate app. Should it be treated as a bug?

**Comment by anthonychu** [comment]
I’m not sure if we can fix this as it can be a breaking change. Perhaps we can note this in our documentation. /cc @ggailey777
