### ISSUE TITLE
EventHub Trigger not firing on windows consumption plan

### ISSUE THREAD

**Issue by abirax** [Azure/azure-functions-host#6909]
#### Check for a solution in the Azure portal
My Azure function is written in c# with event hub trigger on windows consumption plan is not firing consistently.I noticed that when I browse to the site the triggers magically work and the function behaves normally and then again stops working.I haven't done any deployments. 
Below are the versions I am using
<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.0.1" />

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version: 3.0
- Function App name: defectauditsubscriber-qa-func
- Function name(s) (as appropriate):
- Invocation ID:
- Region:WestUS2

#### Repro steps

1. send a message to event hub after a while you will see that the message is not processed by your Azure function 
2. open Azure portal and brwse to azure function the message come back

#### Expected behavior

Provide a description of the expected behavior.

the Azure function should trigger when the message is in eventhub

#### Actual behavior

the Azure function is not triggering  when the message is in eventhub

#### Known workarounds

1) to create a function dummy timer within the same function app to keep the function app alive. This didnot work as the fucntion timer also stopped working and then magically woke when I browsed the portal.
2) Run a power shell script to sync triggers. 
3)open the portal manually 

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by abirax** [comment]
@paulbatum  I am also facing a similar issue the event hub trigger doesnt fire.I have opened a case  as well 120111721006592.I am deploying via arm template . My issue is even if I sync it manually using powershell the problem doesnt go away .Kindly help.

**Comment by paulbatum** [comment]
@abirax I think there is a typo in your app name details, as I wasn't able to find an app with that name. But since you already have a support case open, I'll let that investigation happen first.

**Comment by abirax** [comment]
@paulbatum defectauditsubscriber-qa-func is the function app sorry for the typo. The microsoft support team investigated and mentioned that it is an issue at Microsoft end for event hub but they dont know when it will be fixed. For now they advised I create a new timmer trigger azure function which periodically syncs the eventhub triggered Azure function or switch to dedicated plan,but it is just a workaround and a very dirty one. If possible please investigate since it is a basic case which is failing.I have currently implemented the timmer sync for now.

**Comment by abirax** [comment]
@paulbatum As advised I created the timmer trigger but even that is going idle and skipping the time 
Innovocation ID 34348591-0a23-4f1d-a880-a83b5a762948
azfuncsyncer.


ProcessId | 18028 |  
-- | -- | --
LogLevel | Information |  
Category | Function.AzFunctionSyncer |  
InvocationId | 34348591-0a23-4f1d-a880-a83b5a762948 |  
prop__UnscheduledInvocationReason | IsPastDue |  
prop__OriginalSchedule | 2020-11-20T12:40:00.0000000Z

**Comment by abirax** [comment]
@paulbatum   Support,Got back to me in the function trigger params my eventhubconnectionstring was coming from key vault and not part of the app settings that is what is the likely cause. I feel this is the real reason because after I moved the schedule in timmer to keyvault I started seeing the issue.So hold off on investigation for now.

**Comment by paulbatum** [comment]
@abirax I am curious, were you using the key vault references feature that is documented [here](https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references), to specify your eventhub connection string? Or were you retrieving the connection string from key vault in some of your functions startup code?

The reason I ask, is that if you are using key vault references, then your function should still trigger correctly.

**Comment by abirax** [comment]
> @abirax I am curious, were you using the key vault references feature that is documented [here](https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references), to specify your eventhub connection string? Or were you retrieving the connection string from key vault in some of your functions startup code?
> 
> The reason I ask, is that if you are using key vault references, then your function should still trigger correctly.

Hi @paulbatum  I was retrieving key vault value in the function startup code.(startup.cs).
