### ISSUE TITLE
Support >2GB objects as input/output

### ISSUE THREAD

**Issue by gohar94** [Azure/azure-functions-host#6910]
#### What problem would the feature you're requesting solve? Please describe.
The CLR imposes a 2GB limit on objects [as mentioned here](https://stackoverflow.com/questions/1087982/single-objects-still-limited-to-2-gb-in-size-in-clr-4-0). This means that any input/output binding that goes through the host cannot exceed 2GB.

#### Describe the solution you'd like
A solution to go around this limit to enable accessing larger bindings (e.g. downloading blobs >2GB.)

#### Describe alternatives you've considered
n/a

#### Additional context
n/a

**Comment by fabiocav** [comment]
@gohar94 / @pragnagopa is this still relevant? Are there more details you want to add to this?

**Comment by gohar94** [comment]
@fabiocav This is to allow transferring objects > 2GB from the functions-host to the out-of-proc worker. My understanding at the time was that this is not supported - is that still true?

**Comment by gohar94** [comment]
> @gohar94 / @pragnagopa is this still relevant? Are there more details you want to add to this?

This is to allow transferring objects > 2GB from the functions-host to the out-of-proc worker. My understanding at the time was that this is not supported - is that still true?

**Comment by fabiocav** [comment]
Are you referring to the payload size (e.g. blob size)? If so, it's still a limitation when going over gRPC.

Is the solution here already present with the shared memory implementation?

**Comment by gohar94** [comment]
> Are you referring to the payload size (e.g. blob size)? If so, it's still a limitation when going over gRPC.
> 
> Is the solution here already present with the shared memory implementation?

Yes, the payload size that the system as a whole can accept for input/output blobs.
One bottleneck as you mentioned is gRPC. Also, IIRC, if you read more than 2GB into a byte array in dotnet, that will also cause issues (I might be wrong).
But my feeling is that since with shared memory we stream data into the memory mapped files (and those don't have a 2GB limitation), we might be okay with >2GB blobs. Worth testing though.

**Comment by pragnagopa** [comment]
@fabiocav - good to have a solution for processing larger payloads relying on shared memory instead to reading 2GB into an byte[] directly.

**Comment by liliankasem** [comment]
@fabiocav

**Comment by fabiocav** [comment]
@pragnagopa yes, the solution here would be to leverage shared memory. I'm trying to identify whether there is anything else we should be tracking for the host, as it already implements the capability and now it's really up to the workers to take advantage of that. 

If there are no actions we should be tracking, this issue should be closed here.

**Comment by pragnagopa** [comment]
I believe we need to do the work in the host / webjobs SDK to not read  2GB into an byte[] directly --> this is a limitation that cannot be solved with SharedMemory feature even though it has the potential to solve it.
