### ISSUE TITLE
Referencing function level injected cancellation token instance at startup for dependency injection

### ISSUE THREAD

**Issue by HMoen** [Azure/azure-functions-host#6911]
#### Is your question related to a specific version? If so, please specify:
.NET core 3.1
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
Is it possible to reference the AF instance level cancellation token injected into each function during FunctionsStartup?

#### Use Case
When configuring services during startup, we have a service that takes a cancellation token to pass down to the specific client methods. I understand I can pass it down at the method level, but prefer to trim parameters if possible.

Thanks.

**Comment by v-bbalaiagar** [comment]
Hi @HMoen, Apologies for the delayed response, If you are looking for a startup installation token then you can use the application lifetime and that will provide the information.

Please go through the [document](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostapplicationlifetime?view=dotnet-plat-ext-5.0) for lifetime events including notifications and cancellation token.

**Comment by HMoen** [comment]
Hi @v-bbalaiagar, we are using .NET Core 3.1 and .NET Standard 2.0. It seems [Microsoft.Extensions.Hosting](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostapplicationlifetime?view=dotnet-plat-ext-5.0&viewFallbackFrom=netcore-3.1) nuget package dependencies require >= 5.0.0 (even though documentation states otherwise) which we are not ready to migrate to at the moment. Any other option?

**Comment by v-bbalaiagar** [comment]
Hi @HMoen, Thank you for your feedback! Checking this internally for the possibilities. We will update you with any information found.

**Comment by v-bbalaiagar** [comment]
Hi @HMoen, You can look for the packages [here ](https://www.nuget.org/)and you can navigate to the site. This is the actual package[ link](https://www.nuget.org/packages/Microsoft.Extensions.Hosting/3.1.15) that is compatible with .NET core 3.1

**Comment by HMoen** [comment]
@v-bbalaiagar, looks like this will work. Thanks for your assistance.
