### ISSUE TITLE
Azure function triggers are not being synced for QueueTrigger - JobHosts stops and does not come back alive again

### ISSUE THREAD

**Issue by Ruud-cb** [Azure/azure-functions-host#6917]
#### Check for a solution in the Azure portal

Checked, not reporting any issues.

The Azure Function is automatically stops the JobHost and is not coming back alive again after a new Queue message has been added to the storage queue. This seems to be related to Triggers not being synced to Azure's infrastructure. According to [this documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies#deployment-technology-availability) when using Zip deploy, it should be no problem. I've asked in this issue as well: https://github.com/Azure/Azure-Functions/issues/210#issuecomment-722948087

#### Investigative information

Please provide the following:

- Timestamp: 2020-11-20T07:44:42.0219214 (of Job Stopped event, see below)
- Function App version: 3
- Function App name: mt****-acc
- Function name(s) (as appropriate): Sync**** ProductQueue*** (but others in the same app have the same problem)
- Invocation ID: ddfa0390-f04f-4305-a0f8-92bfb3fc3e3d
- timestamp of invocation: 2020-11-20T07:29:06.0943056Z
- Region: West-Europe

Above invocation is of one of the below mentioned calls, it should help you find my function.

#### Repro steps

Provide the steps required to reproduce the problem:

The below timestamps are coming from AppInsights. At this stage, the azure function has already been deployed a week ago and went offline just as demonstrated in these steps.

Inserted queue item: 2020-11-20T07:03:15Z and 2020-11-20T07:03:17Z
Opened the Function page in the portal: 07:10 (UTC). This apparently causes an http call to the azure function which triggers the jobhost to come back alive again.

Notice logging (Application Insights):
```
2020-11-20T07:10:36.4538397Z: 	Initializing Warmup Extension.
2020-11-20T07:10:37.0663393Z: 	Starting JobHost
2020-11-20T07:10:38.6679443Z:	REQUEST - Sync****ProductQueue***
2020-11-20T07:10:42.653873Z:	REQUEST - Sync****ProductQueue***
2020-11-20T07:10:55.5202488Z:	Executed 'Sync****ProductQueue***' (Succeeded, Id=a26d712c-4437-44be-a4e1-680cda64f7a5, Duration=16852ms)
2020-11-20T07:10:55.5809272Z:	Executed 'Sync****ProductQueue***' (Succeeded, Id=03d5a8e9-a326-4120-8be4-5b88060a687f, Duration=12927ms)
```

Followed by some errors in analysis:

```
2020-11-20T07:11:37.5643728Z:	Initiating breaking change analysis...
2020-11-20T07:11:40.7098572Z: 	The invoked member is not supported in a dynamic assembly.
Stacktrace:
System.NotSupportedException:
   at System.Reflection.Emit.InternalAssemblyBuilder.get_CodeBase (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Script.ChangeAnalysis.ChangeAnalysisService.LogBreakingChangeReport (Microsoft.Azure.WebJobs.Script.WebHost, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script.WebHost, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\src\WebJobs.Script.WebHost\BreakingChangeAnalysis\ChangeAnalysisService.csMicrosoft.Azure.WebJobs.Script.WebHost, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 140)
   at Microsoft.Azure.WebJobs.Script.ChangeAnalysis.ChangeAnalysisService+<TryLogBreakingChangeReportAsync>d__12.MoveNext (Microsoft.Azure.WebJobs.Script.WebHost, Version=3.0.0.0, Culture=neutral, PublicKeyToken=nullMicrosoft.Azure.WebJobs.Script.WebHost, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\src\WebJobs.Script.WebHost\BreakingChangeAnalysis\ChangeAnalysisService.csMicrosoft.Azure.WebJobs.Script.WebHost, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: 103)
2020-11-20T07:11:40.7098825Z:	Breaking change analysis operation failed
```

Another insert at 2020-11-20T07:26:41Z, was processed within a minute.
Another isnert at 2020-11-20T07:28:36Z, was processed within a few seconds.

Between each insert above exception occurs again. So at least the above exception does not cause the function to crash or shutdown.

I left the function alone for a while, new logging noticed:

```
2020-11-20T07:44:42.0219214Z:	Stopping JobHost
2020-11-20T07:44:42.3306105Z:	Stopping the listener '{listenerName}' for function '{functionName}'
2020-11-20T07:44:42.3308382Z:	Stopped the listener '{listenerName}' for function '{functionName}'
2020-11-20T07:44:42.3324247Z:	Job host stopped
```

Added a new item at 2020-11-20T09:27:10Z

Azure function doesn't seem to be triggered to come back alive again. I left it in the queue for 10 minutes. 
I opened a browser and went to http://[functionname].azurewebsites.net/ after a 3 seconds load it shows the Your Functions 3.0 app is up and running page. Refresh the storage queue and the message is dissapeared and thus processed (noticed again in logging same as above that the JobHost is being started.

What I have tried:
I tried to update:
- Microsoft.NET.Sdk.Functions from v3.0.5 to v3.0.9 
- Microsoft.Azure.Functions.Extensions from 1.0.0 -> 1.1.0
- Microsoft.Azure.WebJobs.Extensions.Storage 3.0.10 -> 4.0.3

After that I got other errors like him:
https://github.com/Azure/azure-webjobs-sdk/issues/2586#issuecomment-717592987

This caused my function to go into an error state and cannot be started again. So I reverted  Microsoft.Azure.Functions.Extensions back to 1.0.0 which fixed that issue.

#### Expected behavior

I would expect that after deployment the qeueue triggers are synced with Azure's back-end.

#### Actual behavior

Triggers seem to not be synced, even though I use the documented Deployment method: ZIP Deploy.

#### Known workarounds

Make a HTTP call to the azure function each time a message is inserted.

#### Related information 

Provide any related information 

* Programming language used: C#
* Links to source: Private repo
* Bindings used

<details>
<summary>Source</summary>

```csharp
        [FunctionName("Sync****ProductQueue***")]
        public async Task RunSync****ProductQueue***([QueueTrigger("sync-masterit-dynamicsproducts-queue", Connection = "StorageConnectionString")] string myQueueItem, ILogger log)
        {
            log.LogInformation($"C# Sync****ProductQueue*** trigger function started contact sync: {myQueueItem}");
            var data = FunctionHelpers.GetDataSyncUpdate2(myQueueItem);
            log.LogInformation($"C# Sync****ProductQueue*** trigger function data contact sync: ID: {data.Item1}, type: {data.Item2.ToString()}");
            try
            {
                await _masterItDynamicsSyncBusinessLogic.IsEnabled(x => x.PullProduct(data.Item1));
            }
            catch (Exception ex)
            {
                if (ex.GetType() == typeof(ConflictException))
                {
                    log.LogWarning(ex.Message, myQueueItem, ex);
                }
                else
                {
                    log.LogError(ex.Message, myQueueItem, ex);
                    throw;
                }
            }
        }
```
</details>

More detailed info on how my function is set-up: https://github.com/Azure/azure-functions-host/issues/6542#issuecomment-726719292

Important note: I have written this function to be re-usable for many customers in different azure subscriptions. I need a solution that 'scales', e.g. fixes it for all of them. Luckely not running in production yet but that won't be very far away, so we do have some time to do some debugging.

**Comment by mykle90** [comment]
We are seeing the exact same behavior as described above. The function app seems to just stop running after a short while. Navigating to the functions app page makes the function start running instantly and empties the incoming queues.

Our function app does only contain functions that uses queues as triggers.

**Comment by mykle90** [comment]
As a workaround on our project we added a new function that runs every 5 minutes, that just logs a single string with the datetime like this.

```C#
public static class Ping
    {
        [FunctionName("Ping")]
        public static async Task RunAsync([TimerTrigger("0 */5 * * * *")] TimerInfo myTimer, ILogger log)
        {
            log.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");
        }
    }
```

With this workaround the jobhost no longer stops after 15-20 minutes, and the queues gets emptied within a minute of items getting put on. Hope this can help anyone that are facing the same issue.

**Comment by Ruud-cb** [comment]
Thanks mykle90, either that or sending a GET request to the azure function url works as a workaround. But ofcourse I rather utilize the full potential of consumption app services instead of still keeping the service active manually.

**Comment by frourke** [comment]
We are also seeing this behaviour. 
I have added a sync triggers step to the end of our deployment pipeline. It made no difference, jobhost kept stopping.
We already have a TimerTrigger with a CRON expression coming from appsettings. This does not keep the jobhost alive.
We had to hard code the CRON expression for @mykle90 workaround to work.
e.g. [TimerTrigger("%appsettings%")] to [TimerTrigger("0 */5 * * * *")]

Update:
Microsoft got back to me around the issues with the non-triggering functions. The conclusion from the product team is that the Scale Controller can't cope with the environment variable format for retrieving the cron expression, and that hard-coding as we've been doing it is the way forward for the conceivable future.

**Comment by awatertrevi** [comment]
> Thanks mykle90, either that or sending a GET request to the azure function url works as a workaround. But ofcourse I rather utilize the full potential of consumption app services instead of still keeping the service active manually.

I completely agree, is there any update on this issue from the Microsoft side @pragnagopa @v-anvari?

**Comment by carl-berg** [comment]
Same issue here. Oddly enough the "same" function runs dependably in one environment, but times out/stops executing in another.

**Comment by v-anvari** [comment]
Hi @carl-berg / @awatertrevi  , Thank you for your feedback, Can you share the function app details privately so that we can look into the backend logs
[Sharing Your Function App name privately · Azure/azure-functions-host Wiki (github.com)](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)

**Comment by gma2222** [comment]
I'm dealing with the same issue. Any progress on this?

**Comment by v-anvari** [comment]
Thank you for your feedback, Can you open a new issue with the required details. Closing this issue as there is no further activity
