### ISSUE TITLE
Allow only one restart worker channel operation at a time

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#6919]
cc @brettsam @yojagad 

If a function app is using multiple worker processes configured via app setting `FUNCTIONS_WORKER_COUNT` -
 Language worker processes are launched 10secs apart:

https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs#L142-L149

If multiple language worker channels need to be restarted at the same time - for example - function invocations timed out across various channels - restarts need to be staggered as well to avoid resource contention:

https://github.com/Azure/azure-functions-host/blob/068209f79864805d210ba5df1e05ca7b92033b9d/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs#L383

**Comment by pragnagopa** [comment]
cc @vrdmr

**Comment by fabiocav** [comment]
In progress. Will be completed in sprint 90
