### ISSUE TITLE
Azure function worker stopped and started automatically while process is running

### ISSUE THREAD

**Issue by WhatZitToyya** [Azure/azure-functions-host#6929]
I have a timer-triggered function app in Azure that runs once every 15 minutes, sometimes the function runs normally, and sometimes the function stops in the middle of the process without any error. Before the function stops, it issues a log like this :

> Worker process started and initialized

See the details in this screenshot:

![images](https://user-images.githubusercontent.com/32626581/99930129-8973d400-2d82-11eb-8f82-f751ce30e9a7.png)

After log **Worker process started and initialized** appears, the process stops unexpectedly.

**Comment by v-anvari** [comment]
Hi @WhatZitToyya, Kindly provide us the Function App name so that we can look into our backend logs.
