### ISSUE TITLE
Google webhooks

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-functions-host#693]
Would like to be able to process [Google webhooks](https://www.google.com/webmasters/tools/home). Currently, in order to do that, google requires ["property verification"](https://www.google.com/webmasters/tools/home) (via DNS or a file accessible from a web property).

**Comment by christopheranderson** [comment]
This might be unblocked with some custom route features we're adding soon. We'll review if it doesn't address it.

**Comment by SeanFeldman** [comment]
Thank you @christopheranderson.

> custom route features

Are you referring to #389?

**Comment by fabiocav** [comment]
@SeanFeldman cleaning up stale issues and this seems to be addressed. Please let us know if that isn't accurate. Thanks!
