### ISSUE TITLE
Passing query parameter "code" to anonymous function causes error if no AzureWebJobsStorage is set

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-host#6932]
This is affecting customers in managed functions in SWA. If `code` is passed as a parameter to an anonymous function (when storage is not configured), the function should run and the function code should be able to read the query string parameter. Currently this is an error.

Reported here https://github.com/Azure/static-web-apps/issues/165 and in email thread from Support.

**Comment by fabiocav** [comment]
Adding @kashimiz

**Comment by fabiocav** [comment]
@anthonychu based on @kashimiz's tests, this seems to be addressed. Can you please confirm?
