### ISSUE TITLE
Exception: "Scope disposed{no name} is disposed and scoped instances are disposed and no longer available." during httpClient creation

### ISSUE THREAD

**Issue by navipa** [Azure/azure-functions-host#6945]
Similar issue was reported in 2019 https://github.com/Azure/azure-functions-host/issues/4989
Looks like regression in RunTime version "version":"3.0.14916.0"
I can't create client out of HttpFactory: 
var client = this._clientFactory.CreateClient();
throws Exception: Scope disposed{no name} is disposed and scoped instances are disposed and no longer available.

Functionality stopped working without any code changes.

**Comment by v-bbalaiagar** [comment]
Hi @navipa, Apologies for the delayed response. Were you able find a solution? do let us know if a follow up is required
