### ISSUE TITLE
Change the function name at runtime

### ISSUE THREAD

**Issue by toburger** [Azure/azure-functions-host#6948]
#### Is your question related to a specific version? If so, please specify:
No

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All)
C#, F#

#### Question
Is it possible to change the function name at runtime?

I have defined a Azure Function endpoint by providing the `FunctionNameAttribute` where the function name gets specified in the attribute constructor.

Now the endpoint contains a bunch of routings and I'd like to change the function name to reflect each specific route.

The reason for this is that I'd like to see each routing endpoint as a different "operation" in Application Insights.
At the moment I can't differentiate the routing endpoints, because the operation name is always the name specified in the `FunctionNameAttribute`.

**Comment by v-bbalaiagar** [comment]
Hi @toburger, Apologies for the delayed response. It is not possible to change the function name as mentioned in the [document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#methods-recognized-as-functions). The UI does not directly support to change the function name, but you can work around this using the manual steps  mentioned[ here](https://stackoverflow.com/questions/40656603/rename-an-azure-function/40656647#:~:text=The%20UI%20does%20not%20directly,click%20on%20the%20Stop%20button.&text=Note%3A%20doing%20this%20can%20lose%20some%20historical%20logging.). Let us know if you are able to solve with this information.
