### ISSUE TITLE
Language Workers Exceeded - Language Workers not freeing up

### ISSUE THREAD

**Issue by marcd123** [Azure/azure-functions-host#6950]
Our dev environment has a `FUNCTIONS_WORKER_PROCESS_COUNT` of 8, but today we encountered an error in our deployed function app saying that this limit has been exceeded. This led to the function being called returning a 500. This function app hasn't received any requests for the last 9 days, so these language workers are definitely not in use. I'm unsure why it tried to start up another language worker when making this request. See the exact log below:

![image](https://user-images.githubusercontent.com/9528376/100645681-9f454400-3302-11eb-9238-da735fbb2b25.png)

This is a Python durable functions app, though the function we experienced the issue with (negotiate) is a plain HTTP trigger not part of any orchestration. 

This function app also uses a custom Linux docker image which inherits from the Python function app base image.

@pragnagopa I've seen you have experience with this issue. We'd really appreciate your input.

#### Investigative information

Please provide the following:

- Timestamp:
2020-11-30 17:40:54.723

- Function App version:
~3

- Function App name:
labelright-dev

- Function name(s) (as appropriate):
negotiate

- Invocation ID:
331ae1c2-f748-492d-ac0b-b370e3bde7f8

- Operation ID:
5f871b093153184e8c42d996969073a3

- Region:
East US

#### Expected behavior

This function invocation uses one of the already initialized language workers.

Ideally new language workers would not spawn if already at the limit defined in `FUNCTIONS_WORKER_PROCESS_COUNT`

We expect to not have to restart the function app to resolve the issue.

#### Actual behavior

Whenever we make any request of this environment, we get a 500 error due to the language workers exceeded error.

#### Known workarounds

Restarting the environment should flush everything and cause the language workers to reinitialize over time. This is not ideal though.

#### Related information 

Provide any related information 

* Programming language used 
Python 3.6

* Extensions used
```
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.3.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.SignalRService" Version="1.02.2" />
<PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.1.3" />
```

**Comment by pragnagopa** [comment]
cc @vrdmr  - For guidance on optimum value for `FUNCTIONS_WORKER_PROCESS_COUNT`

@marcd123 - from the description the issue indicates some kind of process leak. I need to investigate to understand the root cause.

**Comment by marcd123** [comment]
Thanks @pragnagopa 

Let me know if there is any other information I can provide.

Might be worth mentioning our Service Plan is EP2, and we have a minimum of two pre-warmed instances at all times.

**Comment by pragnagopa** [comment]
@marcd123  - I looked up the logs for your app. Your app is running functions runtime [3.0.14120.0](https://github.com/Azure/azure-functions-host/releases/v3.0.14120) which is few months old.  Please update your docker image to use latest runtime.  In general, it is good practice to keep the runtime updated in your custom image. In this case, we made few fixes in code path that is causing the exception you are seeing.

Tagging @vrdmr / @Hazhzeng  - for better guidance on how to keep functions runtime on custom docker images up-to-date.

**Comment by marcd123** [comment]
Thank you @pragnagopa 

@vrdmr @Hazhzeng  This is our Dockerfile as is, it inherits mostly from the Python 3.8 Azure Functions base image:

```
# Python 3.8 functions base image
FROM mcr.microsoft.com/azure-functions/python:3.0-python3.8-appservice

# Perform apt-get update
# Support PDF to Image Conversion
# Support Excel to Image Conversion
RUN apt-get update && apt-get install -y poppler-utils wkhtmltopdf xvfb

# Support PDF Table Extraction with Java
RUN mkdir -p /usr/share/man/man1 /usr/share/man/man2 && \
    apt-get install -y --no-install-recommends openjdk-11-jre
```

Should we be updating functions runtime version in the Dockerfile? Is there someway to do this in Azure portal or in host.json?

**Comment by Hazhzeng** [comment]
Hi @marcd123,

Usually, we automatically update the tag **3.0-python3.8-appservice** in our deployment. To ensure you're using our latest host in the custom image, please try to build the image with `--no-cache` flag (e.g. `docker build -t <new-tag> --no-cache .`)

Alternatively, you can also explicitly define the base image by changing the line 
```
FROM mcr.microsoft.com/azure-functions/python:3.0-python3.8-appservice
```
to
```
FROM mcr.microsoft.com/azure-functions/python:3.0.15149-python3.8-appservice
```
Here is the link to follow up with our latest release. https://mcr.microsoft.com/v2/azure-functions/python/tags/list

**Comment by marcd123** [comment]
Thanks @Hazhzeng 

We've updated the base docker image and Azure portal is now reporting 3.0.15149.0

I'll report back if we encounter the issue again. We can close for now though.
