### ISSUE TITLE
Log fully resolved binding metadata

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#6958]
Today we don't have any logs in our system logs that tell us what bindings (or binding settings) someone is using. We have some details in the metrics table, but even those are lacking for .NET apps (they only log triggers).

We need to investigate a better way to log these to our backend logs so we can more easily identify what a customer is using if we need to help debug issues.

**Comment by yojagad** [comment]
Closing this in favor of https://github.com/Azure/azure-functions-host/issues/6966
