### ISSUE TITLE
Add additional columns of information to FunctionLogs

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-host#6960]
Add Static Web Apps resource id as a new column to FunctionLogs in kusto. @annaji-msft is `WEBSITE_STATICWEBAPP_FUNCTION_ASSIGNEEID` the right value for this or do we need something else?

@brettsam may have other columns to add as well.

**Comment by anthonychu** [comment]
@brettsam @fabiocav Would like to get this into the next sprint. Hopefully this isn't a ton of work, but we have a gap in being able to easily link function apps to static web apps. Perhaps this is just a simple log message at host startup instead of an extra column. But would like to be able to query which static web app a function app is linked to.

**Comment by fabiocav** [comment]
@annaji-msft @anthonychu , is this still relevant? We may need to come up with a better approach to ensure we're not bloating the log output for Functions outside of the context of SWA (or other components).
