### ISSUE TITLE
Does FunctionsStartup execute on every function trigger

### ISSUE THREAD

**Issue by baharedankoyuncu** [Azure/azure-functions-host#6961]
Hi,

As per the [documentaion](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#register-services) we are registering services in our `FunctionsStartup`.

During the startup we need to retrieve configuration values from an external resource which means we essentially have an outbound HTTP call.

The question is, does the startup class run on every trigger execution e.g. http, queue and timer?

If yes, does this behavior change depending on the hosting plan i.e. using pre-warmed workers?
How does using Azure Key Vault or App Service Configuration differ from the above scenario?

Function runtime version: 3
Language: C#
Hosting plan: Consumtion plan

**Comment by anthonychu** [comment]
No. It runs once when a function app instance starts up. Once it is up, the instance will continue to execute functions until it is shut down for inactivity. When scaleout occurs, each new instance that starts up will execute its startup once.

**Comment by baharedankoyuncu** [comment]
Hi @anthonychu, thanks for the quick reply.

Is it fair to assume that if we have a timer triggered function that runs every 5 minutes then we can potentially avoid it being shut down?

**Comment by balag0** [comment]
Yes, It will reduce the frequency but it is not perfect.
Timer trigger runs on a single instance only, so it is still possible for other instances to idle out and get removed. Any instance can get recycled during platform upgrades or due to unhealthy workers as well.

**Comment by baharedankoyuncu** [comment]
@balag0 I see, so the scale controller scales out based on the trigger type. Thanks for the input everyone, it's appreciated. Have a nice day :-)
