### ISSUE TITLE
[Feature] IDurableOrchestrationClient to be injected anywhere

### ISSUE THREAD

**Issue by MhAllan** [Azure/azure-functions-host#6962]
I want to be able to organize the logic of Azure function in a mockable way, so I do need interfaces and classes. The problem is that  IDurableOrchestrationClient is not possible to inject in constructors of my classes, so it always needs to be part of the method signature which doesn't look anything intuitive

**Comment by olitomlinson** [comment]
@MhAllan this is supported as of 2.4.0

See the release notes here https://github.com/Azure/azure-functions-durable-extension/releases

> Durable Clients in other .NET Core applications (#1125)

> Before this release, the only way to perform management operations on orchestrations and entities was to use Azure Functions bindings to access an IDurableClient or to use the built-in management HTTP APIs. Thanks to a contribution by @davidrevoledo, instances of IDurableClient can be created in external ASP.NET Core, console, and Azure Functions applications via dependency injection!

> Check out our new sample project for examples of how you can create these client instances in your own applications.

**Comment by v-anvari** [comment]
Hi @MhAllan , Let us know if you have got the information that you were looking for in the above provided release notes
