### ISSUE TITLE
What is the lifetime of IDurableOrchestrationClient ?

### ISSUE THREAD

**Issue by MhAllan** [Azure/azure-functions-host#6963]
What is the lifetime of IDurableOrchestrationClient?

**Comment by v-anvari** [comment]
Hi @MhAllan , Can you provide us more insights on the ask?

Are you talking about the [Time span](https://docs.microsoft.com/en-us/dotnet/api/system.timespan?view=net-5.0#remarks)?

**Comment by MhAllan** [comment]
I am asking when is it created and when is it collected, is it safe to treat it as a singleton? or is it per instance?

**Comment by v-anvari** [comment]
Hi @MhAllan , Durable Functions is used to manage task lifetimes. The monitors can end execution when a condition is met, or another function can use the durable orchestration client to terminate the monitors. 

When a request is received, a new orchestration instance is created for that job ID, which is achieved by [singleton behavior ](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-singletons?tabs=csharp) for all durable functions.

[Example](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=csharp#monitoring)

**Comment by MhAllan** [comment]
Thanks a lot @v-anvari  .. please free to close this issue =)
