### ISSUE TITLE
Is there downtime during slot swap for timer triggered function?

### ISSUE THREAD

**Issue by stukalin** [Azure/azure-functions-host#6969]
`Runtime version: ~3`
`Language: C#`
`Service plan: S1 with "always on" option enabled`

I tried to test reliability of timer triggered functions when I do the slot swap. I've created a dummy function which runs every second (the `useMonitor` set to false) and simply logs some stuff. I have 2 slots: production and qa. I have set the `WEBSITE_ADD_SITENAME_BINDINGS_IN_APPHOST_CONFIG=1` option as many sources on the Internet recommend doing to prevent downtimes.

Now I perform a slot swap with preview and then complete the swap. My app insights log shows me the following.
![image](https://user-images.githubusercontent.com/9863365/101594390-9e976680-3a02-11eb-81c7-7eabd06bba01.png)

As far as I can judge my prod slot function stopped writing at 5:44:09. It was restored later - at 5:45:10
![image](https://user-images.githubusercontent.com/9863365/101594583-ff26a380-3a02-11eb-924b-389fc2664435.png)

I did a quick check for traces for 2 neighbouring invocations of prod and qa at 5:44:09 and 5:44:44 (the gap in the logs) to make sure the qa function had written what it supposed to and it was indeed the case, i.e. the slot sticky setting was _qa_ and other slot specific env variables were _qa_.
![image](https://user-images.githubusercontent.com/9863365/101595010-c0451d80-3a03-11eb-9a73-a5c87a75b34f.png)

From all of this I can make a conclusion that the timer triggered function on the prod slot was somehow down for a good minute.

At the same time I can observe in the Kudu process explorer that whenever I make a slot swap complete operation the qa process becomes the prod process, i.e. the PID and the timestamp are preserved, so no downtime from this perspective.

## Questions: ##
1. Any idea what happens here?
2. Is it expected?
3. How can I be sure no downtime happens during the slot swap for timer triggered functions? In reality I don't have to fire my trigger that often, it'd be more like every 5 minutes or so, but what if I am lucky enough to complete the swap at this very moment of the timer trigger invocation?

**Comment by stukalin** [comment]
Update on this one. It turns out the issue is visible only in app insights. I've made another test which fills a queue with timestamps and this time there weren't any missing timestamps during the swap. So, feel free to close this one or report this to app insight guys.

**Comment by v-anvari** [comment]
Hi @stukalin , [Log sampling](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#applicationinsightssamplingsettings) may cause some executions to not show up in the Application Insights monitor blade, hence it needs to be disabled since log sampling is enabled by default. 

Can you let us know the function app name and the time stamp of the error, so that we can look into the backend logs if required
