### ISSUE TITLE
Azure Function not obeying to maxConcurrentCalls 

### ISSUE THREAD

**Issue by LeonB87** [Azure/azure-functions-host#6970]
I'm creating an Azure Function app that has to process messages in a Servicebus in sequential order. When developing locally this works fine. when deploying to Azure there is an issue where more messages are processes in parallel.

Please provide the following:

- Timestamp: 16:02
- Function App version: ~3
- Function App name: servicebusTrigger
- Function name(s) (as appropriate): 
- Invocation ID:   Id=344fcaa8-7783-41fe-9e2a-75707ef22e86) - 2020-12-09T15:11:40.063
- Region: West Europe

**What language does your question apply to? (e.g. C#, JavaScript, Java, All)**
C#
Dot Net Core 3.1

This is my current host.json

```json
{
  "version": "2.0",
  "extensions": {
    "serviceBus": {
      "prefetchCount": 0,
      "messageHandlerOptions": {
        "autoComplete": true,
        "maxConcurrentCalls": 1,
        "maxAutoRenewDuration": "00:05:00"
      },
      "sessionHandlerOptions": {
        "autoComplete": true,
        "messageWaitTimeout": "00:00:30",
        "maxAutoRenewDuration": "00:55:00",
        "maxConcurrentSessions": 1
      }
    }
  },
  "aggregator": {
    "batchSize": 1,
    "flushTimeout": "00:00:30"
  },

  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  }
}
```

I'm using the example from Visual Studio 2019 and I'm not using any DI

```csharp
[FunctionName("servicebusTrigger")]
        public static void Run([ServiceBusTrigger("myTopic", "MySubscription", Connection = "ServiceBusConnection")] String mySbMsg, 
            ILogger log, 
            DateTime enqueuedTimeUtc,
            MessageReceiver MessageReceiver,
            long SequenceNumber,
            string MessageId,
            string locktoken
            )
        {
        // My Code doing some stuff and calling a Webhook
        }
```

I've set the App Scale limit to 1 using

```powershell
az resource update --resource-type Microsoft.Web/sites -g myRG -n MyAPP/config/web --set properties.functionAppScaleLimit=1
```

I've set the Application property WEBSITE_MAX_DYNAMIC_APPLICATION_SCALE_OUT to 1
![image](https://user-images.githubusercontent.com/10503724/101649712-7f68fb00-3a3b-11eb-913a-6e99c6397036.png)

I've set the APP Service plan scale out to 1
![image](https://user-images.githubusercontent.com/10503724/101649425-27ca8f80-3a3b-11eb-9095-d7e62fd07814.png)

The App Service plan is a Premium Tier.

**Comment by olitomlinson** [comment]
@LeonB87 

How do you know the function is executing concurrently?

**Comment by ladislauNagy** [comment]
I have a similar issue also tried to configure MaxConcurrentCalls from Startup.cs because we use DI.
In our case the function calls multiple APIs when processing a message and we have a configured rate limit on the API Manager, when the function processes too many messages at once, we can see exceptions in application insights with the message: "Rate limit is exceeded", exception type: "GatewayError".

**Comment by v-anvari** [comment]
Hi @LeonB87 , Kindly provide us more insights on where are you seeing these errors and what kind of errors. If possible,  please provide us more details on errors.

Also, While checking the logs for your function app name provided in the issue, we do not see any running or active functions, it could be deleted or has been moved.

**Comment by LeonB87** [comment]
Hi @v-anvari 

The original Azure function was deleted and redeployed in another RG

Our Azure Function is acting as a Orchestrator which calls a Webhook (from an Automation account in this case). The Azure Function check a small DB whether an "agent" is available, and if so, It claims that "agent" and calls the webbook. This is to make sure no more then N jobs are running simultaneously on the Automation Account and they all run with a specific "agent"..

When running locally, This is the case, and no more then N (2 during testing) are ever running on the Automation Account. the azure function waits until an agent is set to available in the DB/ When running on Azure, When you rapidly add more messages, multiple messages get send to the webhook and it's running around 5 or 6 jobs at the same time.

**Comment by v-anvari** [comment]
Thankyou @LeonB87 , We would like to clone the scenario and also check the backend logs. Could you please provide us the current Function App name which is showing this issue and the appropriate timestamp of the error.
