### ISSUE TITLE
Dependency injection failure when manually invoking IServiceCollection.BuildServiceProvider

### ISSUE THREAD

**Issue by bianyifan** [Azure/azure-functions-host#6976]
#### Is your question related to a specific version? If so, please specify:

I don't think so, but we are using 3.0.14916.0, if that helps.

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 

C#.

#### Question

We have encountered a weird exception while the function host trying to activate a service:

```
Unable to resolve service for type 'Microsoft.Azure.WebJobs.Script.IEnvironment' while attempting to activate 'Microsoft.Azure.WebJobs.Script.Configuration.ScriptHostOptionsSetup'. 
```

We have traced this back to where we manually called `IServiceCollection.BuildServiceProvider`, and this exception is gone after we changed to use the `ServiceProvider` passed to our anonymous function as parameter from `AddSingleton<TService>(this IServiceCollection services, Func<IServiceProvider, TService> implementationFactory) where TService : class`.

This exception doesn't reproduce when we run it locally in Visual Studio, but happens online after we deployed it to App Service.

I have looked into the source code mentioned in similar issue #6783, also found [a usage of `IServiceCollection.BuildServiceProvider`](https://github.com/SeanFeldman/NSB-Function-DI-repro/blob/d0210edbf819e088b9fdb54e3c6f218e72ee1646/AzureFunctions.ServiceCollectionWrapper/AzureServiceBusNativeTriggeredFunctionWithWrapper.cs#L29).

Could you help us understand this situation, and probably come up with a way of preventing this from happening in future?

**Comment by bianyifan** [comment]
cc @OsmondJiang @junshi356 for awareness.

**Comment by v-anvari** [comment]
Hi @bianyifan , Apologies for the delayed response, 

The IServiceCollection interface is used for building a dependency injection container. After it's fully built, it gets composed to an IServiceProvider instance which you can use to resolve services. You can inject an IServiceProvider into any class. IServiceProvider defines a GetService(Type type) method to resolve a service. 

This is further explained here , https://github.com/Azure/azure-functions-host/issues/4594 

Can I know if the issue is that there is no warning or no error during the local debugging. Do you see this issue still, if yes could you give us the source code and repro steps so that I can follow up with the concerned team to check if this is intentional.

**Comment by bianyifan** [comment]
Hi @v-anvari , the code to reproduce this bug is something like:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton<TService>()
        .AddSingleton(() => BuildAnotherService(services.BuildServiceProvider().GetService<TService>()));
}
```

I know that this usage should be avoided and `AddSingleton(serviceProvider => BuildAnotherService(serviceProvider.GetService<TService>()))` shall be used instead, and we did change our code to use IServiceProvider.
But we still want to know if it's possible to avoid exception being thrown at runtime, and why it doesn't reproduce locally and only happens on Azure App Service. If it's not possible, maybe clarify this in relevant documentation? Thanks.

**Comment by v-anvari** [comment]
Hi @bianyifan , Thank you for your feedback! We will investigate this further and update as appropriate.

**Comment by v-anvari** [comment]
Hi @bianyifan , I checked this issue internally and we want to understand why is it working locally and throw exception in Azure, Could you give us the complete repro steps with the code, of what are you trying to do here. How are you testing it locally. This will help us understand why is there an exception.

**Comment by bianyifan** [comment]
Well, I can't reproduce this bug with the latest Azure Functions host extensions, probably this has been fixed in some commit. No further help needed, but thanks for your help anyway.
