### ISSUE TITLE
Create services to capture diagnostic events identified by the functions runtime

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#6980]
We need to build a service that would allows us to capture diagnostic events recognized by the functions runtime. Diagnostic events can be error conditions that require user actions to mitigate the issue or a warning for a potentially unideal configuration on customers part. The idea is to capture and such events and build a pipeline to bring this to customers attention. This is not meant to be used as an analytical tool to replace application insights or other solution. But is meant to serve as a quick guide to help resolve most common conditions. 

This issue particularly handles the pipeline to capture the diagnostic events.

Each of the diagnostic event at the minimum we expect to have the following information.
1. ErrorCode 
2. Message
3. Level
4. HelpLink
5. Exception (if any)
6. Additional Details (if any)

**Comment by fabiocav** [comment]
This issue has been partially done, @soninaren is further breaking it down to reflect the work that has been done and have more granular tracking.
