### ISSUE TITLE
Fix Artifacts to publish in release pipeline

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-host#6982]
Currently, we select the list of artifacts in one of the steps that we need to publish nupkgs for. Initially it was marked as "Select all" but that's problematic, because we dont want to publish ExtensionsMetadata, Abstractions and one other package.

Temporarily, we've manually selected which ones to publish, but because the artifact names change every release, this isn't the right fix. We edit the release task and the "Agent Job" right above "Nuget push" has a list of the artifacts. We need to check the ones we want.

We need to fix that release step to handle publish without manual intervention.

cc: @ankitkumarr

**Comment by ankitkumarr** [comment]
It's didn't seem like there was a way to download artifacts using wildcards. I think a simple fix could be that we download all artifacts and then add a task to filter the ones we need and publish those.

**Comment by mhoeger** [comment]
Done
