### ISSUE TITLE
Add logging for auto-upgrade to figure out SqlClient errors

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#6987]
cc @fabiocav 

Need to add more logging to figure out apps that might break on auto-upgrade:

Errors:

1. System.PlatformNotSupportedException : System.Data.SqlClient is not supported on this platform." 
2. System.DllNotFoundException : Unable to load DLL 'sni.dll' or one of its dependencies
3. System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.2.2.0"
4. System.IO.FileNotFoundException : Could not load file or assembly 'System.Data.SqlClient

**Comment by fabiocav** [comment]
Completed.
