### ISSUE TITLE
HTTP Trigger routes can overwrite /admin/ APIs

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-host#6990]
#### Repro steps
1. Deploy an app with the below content.
2. Make an HTTP trigger request with the master key against /admin/host/status and notice how it returns the response from the HTTP trigger.

host.json
```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingExcludedTypes": "Request",
      "samplingSettings": {
        "isEnabled": true
      }
    }
  },
  "extensions": {
    "http": {
      "routePrefix": ""
    }
  }
```

HTTP Trigger
```csharp
        [FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = "{*route}")] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            string name = req.Query["name"];

            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name = name ?? data?.name;

            string responseMessage = string.IsNullOrEmpty(name)
                ? "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."
                : $"Hello, {name}. This HTTP triggered function executed successfully.";

            return new OkObjectResult(responseMessage);
        }
```

#### Expected behavior

Http triggers should take a lower priority in routing logic vs APIs defined by the Functions host, such as admin and extension webhook urls.

#### Actual behavior

All HTTP requests get routed to the HTTP trigger

#### Known workarounds

Pin to a previous version of the Functions Host runtime by setting the app setting `FUNCTIONS_EXTENSION_VERSION` to 3.0.14916

**Comment by mathewc** [comment]
Hmmm, so you're saying this looks like a regression in the last release, and doesn't repro in 3.0.14916? The most recent changes we made in this space were in https://github.com/Azure/azure-functions-host/pull/6808 by @safihamid. Not saying this is what caused this, but we haven't changed the route stuff in a long time before this, so I recommend investigating here first.

**Comment by safihamid** [comment]
Hmm taking a look shortly. Thanks for the ping

**Comment by safihamid** [comment]
Sent the PR. Looks like I had added tests for every possible scenarios for proxy combinations and such but not for when route is set to "{*route} and routePrefix is set to "". This check for /admin was already there before but was thinking it's really not required and impacts throughput as we need to do a check for it on every call :(
