### ISSUE TITLE
[Auto-Upgrade]V2 apps Auto-Upgraded to V3 failing with System.DllNotFoundException : Unable to load DLL 'sni.dll' or one of its dependencies

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#6996]
cc @fabiocav @brettsam 
 
Very similar to https://github.com/Azure/azure-functions-host/issues/5950

Repro  : (As of now I could not repro it locally. But reproes when running in Azure)

`run.csx:`

```csx
 #r "Newtonsoft.Json"
 #r "System.Configuration"

using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Newtonsoft.Json.Linq;
using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Net.Http;
using System.Text;

    public static string Run(HttpRequest req, TraceWriter  log)
    {
        string conStr = "ValidTestConnectionString";

        using (SqlConnection conn = new SqlConnection(conStr))
            {
                log.Info($"Getting new Power BI users, Start DateTime: {DateTime.Now}");
                conn.Open();

            }
        return conStr;
    }
```

`function.json`

```json
{
  "bindings": [
      {
          "type": "httpTrigger",
          "name": "req",

          "authLevel": "anonymous",
          "direction": "in",
          "methods": [ "get" ]
      },
      {
          "type": "http",
          "name": "$return",
          "direction": "out"
      }
  ]
}

```

Above code works in V2 but throws following error when running in V3:

```
System.TypeInitializationException : The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception. ---> System.TypeInitializationException : The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception. ---> System.DllNotFoundException : Unable to load DLL 'sni.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
```

**Comment by pragnagopa** [comment]
Flagging this as P1 as this is a blocking issue for Auto-Upgrade

**Comment by pragnagopa** [comment]
Root cause:
- SiteExtension deployed to windows platform on Azure does not include native library `sni.dll` 
- Output for publish command used to build SiteExtension https://github.com/Azure/azure-functions-host/blob/dev/build/build-extensions.ps1#L64 - does not include `sni.dll` 
- Verified native binaries are included when using publish command without specifying RID 

@fabiocav  - any idea where we should follow up to fix the publish command with RID?

**Comment by fabiocav** [comment]
I'm assigning to myself for initial investigation/planning/triage.

**Comment by fabiocav** [comment]
We'll also move this to sprint 92 to reflect when the work will be taking place

**Comment by pragnagopa** [comment]
Verified updating `System.Data.SqlClient` package  to the latest - resolves the issue. `dotnet publish -r win-x86` includes `sni.dll` in the site extension !
