### ISSUE TITLE
[Premium] Service Bus triggerd function does not scale out under load

### ISSUE THREAD

**Issue by Kiechlus** [Azure/azure-functions-host#7001]
### Describe the bug

Service Bus triggered premium function is not scaling out eventhough it has a lot of unprocessed messages with long running, memory intensive tasks.

### Investigative information

Please find all `Invocation ID`s and execution times in the attached Excel sheet: [invocationIds.xlsx](https://github.com/Azure/azure-functions-host/files/5718503/invocationIds.xlsx)

### Steps to reproduce

1. Linux Python Function App (EP2) in West Europe
2. Use the following `host.json`:
```
"serviceBus": {
    "prefetchCount": 100, // also tried 0, 2
    "messageHandlerOptions": {
          "autoComplete": true,
          "maxConcurrentCalls": 16,
          "maxAutoRenewDuration": "00:05:00"
    }
 }
```
3. Set the following env vars
```
FUNCTIONS_EXTENSION_VERSION=~3
FUNCTIONS_WORKER_PROCESS_COUNT=2
FUNCTIONS_WORKER_RUNTIME=python
```
4. Send all at once 30 messages each containing a task running about ~5 minutes and consuming up to 3GB of memory
5. Observe logs to see what is being worked on at which time and in which sequence

### Expected behaviour

<img src="https://user-images.githubusercontent.com/9875731/102661772-cbbfe380-417d-11eb-853e-4281b578e03a.png" width="350">

- Expecting to scale up to 10 instances under heavy load
- Each instance runs two processes, so expecting to see up to 20 messages to be worked on simultaneously
- Not expecting immediate scale out, as no warm instances are configured

### Actual behaviour

- As visible from logging, at all times only two tasks are worked on in parallel, which is due to FUNCTIONS_WORKER_PROCESS_COUNT=2
- No scaling seems to take place at all eventhough finishing all tasks  took ~ one and a half hours
- Messages are consumed immediately, but they are not processed, as visible on the longer and longer execution times in the attached excel file
- On other test runs some messages even completely disappeared without being worked on. They are neither visible in AI, nor in deadletter queue nor in any log.

<img src="https://user-images.githubusercontent.com/9875731/102662183-92d43e80-417e-11eb-944b-c0387f5d688e.png" width="350">

**Comment by Kiechlus** [comment]
Do I understand something wrong? When I set `App Scale out`  to one warm instance instead of zero, I get four processes in parallel instead of two.

I thought Premium plan means that at least one instance is always billed but other instances are added on the fly according to load and are billed based on the execution time.

With this setting (one warm instance), will I be billed one or two always running instances?

**Comment by brettsam** [comment]
It looks like now you have `prefetchCount: 0`, which would make sense for long-running tasks like this. The examples you have above show `prefetchCount: 100`, which means that one process will fetch up to 100 messages and store them in-memory, preventing any other worker to get them.

I checked some logs from the last few days and things appear to properly scale out now -- if you are still having issues, can you point to an InvocationId and I can take a look around that time frame?
