### ISSUE TITLE
Nodejs function is unreachable and does not recover

### ISSUE THREAD

**Issue by ChristianSauer** [Azure/azure-functions-host#7004]
We have issues with a NodeJs Function triggered by an HTTP Trigger. This Trigger has very uneven load, e.g. it can receive zero POSTS for an hour or so, and millions of POSTs an hour later. Confusingly, sometimes the Function runtime becomes unreachable and disables the Function. The invoking side sends events for a long time, but gets only a 404.

Here is an example Invocation:
![image](https://user-images.githubusercontent.com/7250249/102722367-f4bcb180-4300-11eb-99f0-52f41d0e3562.png)

Notice the drop to nothing over this weekend (19, 20) , but the function should have received events in this timeframe.

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version:  not visible for me 
- Function App name: func-er-gi-eb0a1917-eastus
- Function name(s) (as appropriate): eventReceiver
- Invocation ID: N/A
- Region: westus

#### Expected behavior

Function should be available and running

#### Actual behavior

After a random period of time the function runtime becomes unreachable and the http triggered function is no longer reachable.

#### Known workarounds

Provide a description of any known workarounds.

Disabling and enabling this function "reboots" the function app, but thats annoying and prevents our automation.

#### Related information 

Provide any related information 

* Programming language used: Nodejs
* Bindings used: HttpTrigger

**Comment by balag0** [comment]
We had an issue with hostversion 3.0.15149.0 earlier last week. The 2 workers that were failing with 404 were impacted by this issue.

We started applying a patch last week and on Friday it reached East US. I can also see that there have been no errors with the new host version 3.0.15185.0 (which includes the patch). i have also confirmed that all 4 workers assigned to this app currently are running the newer host version, let me know if you are still seeing this issue. We apologize for the inconvinience

**Comment by ChristianSauer** [comment]
@balag0 Thank you for the quick response. I can confirm that it seems to be running fine in eastus. 
Did the patch reach westeurupe, canadacentral and australiaeast? Especially australiaeast seemed to have problems this night.

**Comment by balag0** [comment]
Thanks for confirming. Australia East is in the last batch of regions and not updated yet. This should be complete in the next 6 hours.

**Comment by ChristianSauer** [comment]
Thanks, the graphs of the last days look good.
Thank you very much and happy holidays!
