### ISSUE TITLE
Receiving HTTP 404 while running/testing simple example locally using a container, customHandler and R

### ISSUE THREAD

**Issue by rhuettl** [Azure/azure-functions-host#7008]
Hi team,

Running a custom container locally in Docker, function calls always resulting in 404 results.

I just have taken a good example at [Microsoft docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image?pivots=programming-language-other&tabs=bash%2Cportal&WT.mc_id=javascript-10496-davidsmi) without modification, resulting in the same 404 behavior (also when running the example in Azure).

Azure CLI used 2.16.0
Docker on Windows 10 used 20.10.0
Function Core used 3.0.3160

Calling the function in a browser is giving a 404 result back (but just within the docker test, all other tests without docker are working successful):
![image](https://user-images.githubusercontent.com/23125000/103031249-c556b080-455d-11eb-9a5e-5e40f27fc809.png)

And the log is then looking like:
![image](https://user-images.githubusercontent.com/23125000/103030881-fa163800-455c-11eb-9f39-f958e1d847e4.png)

For me it seems that the function has been called successfully after the request but the routing didn't work as expected. The function logic won't be callesd, returning in a 404 then because the endpoint can't be found (why, that's the good question)  :-( 

Maybe the given example by Microsoft has some errors but I tried different settings. All ending in a 404 when running the function in a container.
Also tried the great example provided by David: [https://github.com/revodavid/R-custom-handler](https://github.com/revodavid/R-custom-handler) without success, also ending in 404.

We like to use the Azure function custom handlers (containers) but currently we can't get any of the examples to work.

Any help would be great :-)

Thank you in advance, greetings, merry Christmas
Ralf

PS. I uploaded my plumber example at https://github.com/rhuettl/azurefuncR

**Comment by rhuettl** [comment]
I re-tested the docker built on a personal/private server and not on a company one and the call succeeded!
Seems that docker is creating or starting the image different this way - but running the same version, really strange.

**Comment by v-bbalaiagar** [comment]
Hi @rhuettl, Apologies for the delay in response. This issue was somehow missed, we are eager to know if you are still facing the same issue, so that we can look into it.
