### ISSUE TITLE
Cant create a vnet integrated function app when the backing storage account is locked down

### ISSUE THREAD

**Issue by brett-ed** [Azure/azure-functions-host#7011]
This is in regards to the issue reported and discussed on:  https://github.com/Azure/azure-functions-host/issues/5572

This issue still exists.  

The only way I can get the vnet integrated function app to create successfully is to toggle the storage account back to be publicly accessible.  Once its created, I can flip it back to private and the app works just fine.  

ARM reports back an obscure INTERNALSERVERERROR when the account is not publicly accessible.  

The storage account is setup to allow access from the subnet the function app is being deployed to.  If I had to guess, I'd say that the runtime is attempting to access the account prior to the vnet integration step being complete.

**Comment by v-anvari** [comment]
Hi @bte8444 , Let us know if the example here helps - https://azure.microsoft.com/en-us/resources/templates/function-premium-vnet-integration/

Meanwhile, there is an open discussion here with different solutions - https://github.com/Azure/Azure-Functions/issues/1361
