### ISSUE TITLE
Retry Policy - Recommended Settings

### ISSUE THREAD

**Issue by bgribaudo** [Azure/azure-functions-host#7012]
#### Is your question related to a specific version? If so, please specify:
Microsoft.Azure.WebJobs >= 3.0.23 must be used

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
All

#### Question
Hello,

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp#retry-limitations-during-preview makes the following recommendation:
> In the consumption plan, the app may be scaled down while performing retries. For best results, choose a retry interval <= 00:01:00 and <= 5 retries.

Can you provide some background as to the "why" behind this recommendation? It makes me wonder that the scale down process does not factor in the fact that a retry is scheduled/taking place, but I'm not sure. 

Thanks,
Ben

**Comment by v-anvari** [comment]
Hi @bgribaudo, For example if MaxDequeueCount = 1; then the function tries to receive the message and in case there is another job running and reaches a time out for any reasons, then there wouldn't be any retry, thus the function fails. 

Retry is the maximum number of times an execution is retried before eventual failure. But on a Consumption plan, a [function execution times out](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#timeout) after a configurable period of time. Hence, it is suggested to maintain a retry interval <= 00:01:00 and <= 5 retries.

**Comment by bgribaudo** [comment]
Thank you, @v-anvari!

So the function's timeout applies to the summed runtime of all retries (vs. each retry getting its own timeout--like its own 5 minutes to run on the consumption plan)...good to know!
