### ISSUE TITLE
How function.json and it's corresponding function work behind the scene

### ISSUE THREAD

**Issue by DVGY** [Azure/azure-functions-host#7014]
#### Is your question related to a specific version? If so, please specify:
Node 12 LTS, 
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
It applied to node js 
#### Question
Q1. I am wondering how `function.json` settings work behind the scene. For example in the following function which is event triggered. How the settings described in `function.json` works as input to function and output to the function. This is some sort of magic, but I want an in-depth view how it works
 

 
```
{
  "bindings": [
    {
      "type": "eventGridTrigger",
      "name": "eventGridEvent",
      "direction": "in"
    },
    {
      "name": "inputBlob",
      "type": "blob",
      "path": "{data.url}", // how the values of data.url is parsed here
      "connection": "projectimagestore_STORAGE",
      "direction": "in",
      "datatype": "binary"
    },
    {
      "name": "outputBlob",
      "direction": "out",
      "type": "blob",
      "path": "compressedprojectimages/{filename}",
      "connection": "projectimagestore_STORAGE"
   ]
}
```
```
module.exports = async function (context, eventGridEvent, inputBlob) {
    try{
    context.log(typeof eventGridEvent);
    context.log(eventGridEvent);
    context.log(context);
    context.log(typeof inputBlob);
    context.log({inputBlob})

   // context.bindings.outputBlob = inputBlob

    }
};
```
Q2. Also can we add custom custom properties in context object other than name (`"name": "xyzblob"`) property that eventually get used in `function.json settings` ?

**Comment by v-anvari** [comment]
Hi @DVGY , Apologies for the delayed response. Here is a document explaining the behavior of the bindings - https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=v2#exporting-a-function

https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings?tabs=csharp

You can give any name as defined in the example here - https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=v2#contextbindings-property

Function.json 
```
{
    "type":"queue",
    "direction":"out",
    "name":"myOutput"
    ...
}
```
code:
```

context.bindings.myOutput = { 
        some_text: 'hello world', 
        a_number: 1 };
```

Closing this issue as the required information is provided.
