### ISSUE TITLE
Azure functions local debugging spawning lot of conhost.exe processes 

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/azure-functions-host#7015]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app, select `Diagnose and solve problems` from the left, and view relevant dashboards before opening your issue.

#### Investigative information

Please provide the following:
![image](https://user-images.githubusercontent.com/10679463/103308545-4f789c00-49d8-11eb-8c54-fa93bf66c438.png)

#### Repro steps

1. vs2019 16.8.3 version
2. create new servicebus triggered function.
3. continuously start and stop debugging multiple times and keep eye on task manager conhost.exe process it will keep increasing and soon fill the taskmanager list
4. try put break point and keep start /stop debug and one point u will notice break point not being hit.
5. terminate all conhost.exe and try again and break point will hit.

#### Expected behavior

multiple conhost.exe should not remain in background when debug is stopped and breakpoints must be hit.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used C#
* Links to source
* Bindings used  servicebus topic trigger with session based receiver

**Comment by v-anvari** [comment]
Closing this issue as duplicate  - 
https://github.com/Azure/azure-functions-host/issues/7016
