### ISSUE TITLE
lot of conhost process open in task manager after continous stop/start debug sessions on local machine.

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/azure-functions-host#7016]
#### Investigative information
Azure function local debugging after sometime lot of conhost.exe remains open in task manager and break points don't get hit.  After i terminate all conhost.exe and debug again then break point got hit.

![image](https://user-images.githubusercontent.com/10679463/103309067-a894ff80-49d9-11eb-8cdc-1c4d8776463f.png)

![image](https://user-images.githubusercontent.com/10679463/103308545-4f789c00-49d8-11eb-8c54-fa93bf66c438.png)

#### Repro steps

1. vs2019 16.8.3 version
2. create new servicebus triggered function.
3. continuously start and stop debugging multiple times and keep eye on task manager conhost.exe process it will keep increasing and soon fill the taskmanager list
4. try put break point and keep start /stop debug and one point u will notice break point not being hit.
5. terminate all conhost.exe and try again and break point will hit.

#### Expected behavior

multiple conhost.exe should not remain in background when debug is stopped and breakpoints must be hit.

#### Actual behavior

lot of conhost.exe remain open in task manager even after debug is stopped and when list becomes log sometimes break points stop getting hit until u terminate all conhost.exe and start app again.

#### Known workarounds

terminate all conhost.exe from taskmanager and debug app again.

#### Related information 

Provide any related information 

* Programming language used C#
* Bindings used  servicebus topic trigger with session based receiver

**Comment by v-anvari** [comment]
Hi @krishnasingh1818 , Apologies for the delayed response, I tried to reproduce the issue and did not see this behavior. Let us know if you were seeing this issue still
