### ISSUE TITLE
Instances running a mix of old and new code after zip deploy

### ISSUE THREAD

**Issue by ZachTB123** [Azure/azure-functions-host#7017]
I am doing some performance testing of an Azure Function running on a consumption plan (Windows). The Function App has a function with an Event Hub trigger. I am also using custom handlers.

I am generating mock data to the Event Hub (over 1 million messages per minute) which has caused the function to scale out and add more instances (at least 32 since my Event Hub has 32 partitions). Once the function has scaled out, I made a code change. For the sake of demonstration, I just changed the message that is logged when my function is invoked. This deployment completed at 2020-12-30T02:32:17.3405088Z (based on the "Deployments" page under the "Advanced Tools"). Coming up on an hour after the deployment, I see the "old" and "new" log messages in Application Insights:

<img width="607" alt="Screen Shot 2020-12-29 at 9 29 01 PM" src="https://user-images.githubusercontent.com/17228033/103328053-e404ed80-4a1c-11eb-97e7-ed6707f45218.png">

Note that the message starting with "Edit19:" was from the newest deployment at 2020-12-30T02:32:17.3405088Z and is the message I am expecting to see from all instances.

This looks to be similar to #5663. The only way I can get my new code to take effect completely is to stop the function (to force it to scale down). Then I can start it again and all instances log the expected message. This is not a viable solution for us in production.

I am using a custom script to handle the deployment since we will not be able to use the Azure Functions Core Tools. The script does the following:

1. [Execute a zip deploy](https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push#rest). `WEBSITE_RUN_FROM_PACKAGE` is set to `1`.
2. Restart the Function App.
3. Sync triggers.

#### Investigative information

Please provide the following:

Note, I am providing an example of an execution using the old code and an execution using the new code:

**Old code (Edit18)**

- Timestamp: 2020-12-30 03:24:50.6274151
- Function App version: 3.0.15193.0
- Invocation ID: c9955619-a073-482a-bf32-4c357d73b608
- Region: Central US

**New code (Edit19)**

- Timestamp: 2020-12-30 03:24:50.5329417
- Function App version: 3.0.15193.0
- Invocation ID: 6a49b982-3977-43cb-97f1-0e094d6ab878
- Region: Central US

#### Repro steps

1. Create a Function App (Windows/Consumption) with a function that has an Event Hub trigger.
2. Force the function to scale out (add a bunch of events to the Event Hub).
3. After the function has scaled out, make a code change and execute a deployment (using the steps my custom script uses above).
4. Wait some time (e.g. 10+ minutes). You will see invocations that are using the old code and some invocations that are using the new code.

#### Expected behavior

The new code has propagated to all instances.

#### Actual behavior

Some invocations use the old code, some invocations use the new code.

#### Known workarounds

Stop the function so it scales down. Wait a few minutes. Start it up again and it will now be using the new code for all instances that are spun up.

#### Related information 

function.json:

```
{
  "bindings": [
    {
      "type": "eventHubTrigger",
      "name": "events",
      "direction": "in",
      "eventHubName": "%EVENT_HUB_NAME%",
      "consumerGroup": "%CONSUMER_GROUP%",
      "cardinality": "many",
      "connection": "EVENT_HUB_CONNECTION_STRING",
      "dataType": "string"
    }
  ]
}
```

host.json:

```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.*, 3.0.0)"
  },
  "extensions": {
    "eventHubs": {
      "batchCheckpointFrequency": 1,
      "eventProcessorOptions": {
        "maxBatchSize": 512,
        "prefetchCount": 1024
      }
    },
    "serviceBus": {
      "prefetchCount": 100,
      "messageHandlerOptions": {
        "autoComplete": true
      }
    }
  },
  "functionTimeout": "00:10:00",
  "customHandler": {
    "description": {
      "defaultExecutablePath": "main.exe"
    }
  }
}
```

**Comment by ZachTB123** [comment]
@anthonychu This is one of the issues we discussed when we met last.

**Comment by ZachTB123** [comment]
I stopped my Function App (and disabled all functions) temporarily as described in the above `Known workarounds` section at around 10:10 pm CST, and I am indeed only seeing the new code (Edit19) now.

**Comment by v-anvari** [comment]
Hi @ZachTB123, I was looking at the backend logs of your Function App. I see that the invocation id : c9955619-a073-482a-bf32-4c357d73b608 started at a time stamp of : 2020-12-30 03:24:50.**3961630** which should be just before you made the changes, and the job completed at Time Stamp: 2020-12-30 03:24:53.**7909379** which is few seconds after the new job has started. 

I do see the event sequence has parallel jobs running. This is usually because there are incomplete jobs which had already started before you pause the App and they are trying to finish when you restart the App again. 

It would be ideal if you wait for few minutes before you restart.

**Comment by anthonychu** [comment]
Thanks @ZachTB123.

I think one thing that we need to do here is to rule out the deployment mechanism as a cause (even though we had talked about this and are quite certain it is not). If there's a way to test this out by pushing the change using Core Tools, it would help a lot in focusing any investigations.

/cc @pragnagopa @yojagad

**Comment by ZachTB123** [comment]
I tested this with Core Tools and didn't have any issues. After looking at the Core Tools code more closely, I decided to mirror that logic in my deploy script. The specific logic that I mirrored starts [here](https://github.com/Azure/azure-functions-core-tools/blob/3.0.3160/src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs#L356). I was able to determine this by turning on debug logging for the Core Tools. Following that logic, the steps it takes are:

1. Update the `WEBSITE_RUN_FROM_PACKAGE` app setting to `1` [here](https://github.com/Azure/azure-functions-core-tools/blob/3.0.3160/src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs#L532).
2. Execute the zip deploy [here](https://github.com/Azure/azure-functions-core-tools/blob/3.0.3160/src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs#L537).
3. Sync triggers [here](https://github.com/Azure/azure-functions-core-tools/blob/3.0.3160/src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs#L380).

After updating my script with this logic I had no issues.

It looks like my issues come from a misunderstanding of how to use a zip deploy when `WEBSITE_RUN_FROM_PACKAGE` is `1`. My original logic was to set this App Setting right away in my Terraform and then execute a zip deploy + restart since [this](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#benefits-of-running-from-a-package-file) says:

> Can be deployed to a production app (with restart).

This led me to believe that I just needed to trigger the restart request after the zip deploy but that never seemed to work for me (saw old and new code running). I was also confused because [this](https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url) documentation says:

> Function trigger sync: If you are running Functions on a Consumption plan, modifying their triggers requires a synchronization process that doesn't occur when using the zip API or other file-based deployment methods like FTP. Zipdeploy will perform this synchronization for you.

I originally omitted trigger syncing from my script because of that but then noticed Core Tools was doing it, so I added it back.

I've done multiple deploys using the new logic and haven't had any issues. I'll be doing some additional testing and will close if I have no further issues.

**Comment by balag0** [comment]
I believe this could be the issue when setting the value to "1" at app creation time.
https://github.com/Azure/azure-functions-host/issues/5722#issuecomment-619596843

Basically if WEBSITE_RUN_FROM_PACKAGE is set "1" and there is no content deployed yet, the functions runtime will be shutdown.

**Comment by pragnagopa** [comment]
Thanks all for the follow up! I am going to flag this as doc issue as it might be worth documenting / providing sample scripts for deployment that mimics what we do in Core-Tools

**Comment by balag0** [comment]
There could also be a case for this to be considered as a bug in the worker where it is not able to differentiate between unreachable content vs empty content. If the worker could flag empty content differently then functions runtime can also react differently instead of shutting down. But there might be more complexity involved here.
