### ISSUE TITLE
Use v12 of Azure Storage SDK

### ISSUE THREAD

**Issue by petro2050** [Azure/azure-functions-host#7022]
It looks like the runtime is using v11 of Azure Storage SDK, but this package is deprecated. (https://www.nuget.org/packages/WindowsAzure.Storage/9.3.3). 

Can you please upgrade to v12 so that we don't have to manually install this package and increase our final DLL size and cold start times?

**Comment by v-bbalaiagar** [comment]
Hi @petro2050 , The Version you are pointing to is a deprecated version. There have been further upgrades made for Storage and changes in the dependencies. The latest stable version for [Microsoft.Azure.WebJobs.Extensions.Storage ](https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-get-started#install-the-storage-binding-extension) is 4.0.3 which is available in the [NuGet Gallery](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage). Please go through the provided document link for more information and let us know in case of any further queries.

**Comment by petro2050** [comment]
@v-bbalaiagar My project currently doesn't have a Startup class so I'll need to create one. The example you gave is for web jobs. Can you show me an example for functions? I looked at https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection, but it's extending `FunctionsStartup` and `IFunctionsHostBuilder` doesn't have `ConfigureWebJobs` defined.

**Comment by v-bbalaiagar** [comment]
Hi @petro2050, Please find the example for creating [startup file](https://github.com/dodyg/practical-aspnetcore/tree/3.1-LTS/projects/azure-functions/StartupExample).  Configure web jobs is a part of [HostBuilder](https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-get-started#create-the-host) instance.

**Comment by petro2050** [comment]
@v-bbalaiagar As you said, Configure web jobs is part of `HostBuilder`, but https://github.com/dodyg/practical-aspnetcore/blob/3.1-LTS/projects/azure-functions/StartupExample/StartupExample/StartUp.cs#L13 is passing `IWebJobsBuilder`.

**Comment by v-bbalaiagar** [comment]
Hi @petro2050, Here is a [tracking issue](https://github.com/Azure/azure-webjobs-sdk/issues/2575) which is being addressed and worked upon on a similar scenario, Please find the space for further updates.

Closing this issue, please feel free to ping in the issue comment.
