### ISSUE TITLE
Change Feed processor records invocations as 'request' telemetry in Application Insights

### ISSUE THREAD

**Issue by alexjamesbrown** [Azure/azure-functions-host#7023]
I've got an Azure Function Cosmos DB change feed processor. It has Application Insights configured.

When this is invoked by a change in cosmos db, the invocation is sent to Application Insights as a 'request' - albeit without a URL, and a response code of 0

![image](https://user-images.githubusercontent.com/437743/103423907-72a27780-4ba1-11eb-8b25-7482fa97583c.png)

Is this by design?

**Comment by anthonychu** [comment]
Yes I believe it is. Azure Functions tracks each invocation, whether it's HTTP or other trigger, as a request in App Insights. /cc @brettsam

**Comment by brettsam** [comment]
Yes, this is correct. All function invocations are logged as requests in application insights as there's not a concept there of a "generic operation".
