### ISSUE TITLE
Linux consumption specialization fails if not in placeholder mode

### ISSUE THREAD

**Issue by divyagandhisethi** [Azure/azure-functions-host#7029]
For linux consumption apps which are pinned to a given host version, their apps are not launched in placeholder mode since they are already specialized at startup.  The linux consumption controller fails to specialize when on startup because we have an assumption that we will always start in placeholder mode.

**Comment by divyagandhisethi** [comment]
Example Kusto query for a failing pinned container-

https://wawscus.kusto.windows.net/wawsprod?query=H4sIAAAAAAAEAGWOwWoCMRRF9wP9h4crBWdI0mTGCC6KKAgWRP2BNH1qxCRD8kYR%2bvEVQURc3sM9lzvvgiUXQ17Gff4o%2fuBywISwSmhdxq3zuCHjW%2fhBuiAG6P8aQrrhvmCClVyUggHTY1WPmayYFFzqZlBV3LsweO6t4wlhMoHet7Mp5rijahoDGRcwLUImEyz2XusPfNe%2b2racac35dCbK%2brORkik5qpuR0kIpeVfbFI9o6e37EDaxSxaHsMQznm6x896ka1H8A06cOJf9AAAA&web=0

FunctionsLogs
| where PreciseTimeStamp between (datetime(2020-12-20 09:56:04.0421497)..1min)
| where Role == "Microsoft.ContainerInstance"
| where RoleInstance == "App-E9911CE2-637440548678592554"
| project PreciseTimeStamp, Source, Level, Summary

```
> PreciseTimeStamp	      Level	Summary
> 2020-12-20 09:56:04.6281084	4	Initializing LinuxContainerInitializationService.
> 2020-12-20 09:56:04.6281475	4	Host context specified via CONTAINER_START_CONTEXT
> 2020-12-20 09:56:04.6281854	4	Applying host context
> 2020-12-20 09:56:04.6282264	2	Assign called while host is not in placeholder mode
> 2020-12-20 09:56:04.6282641	4	StartAssignment invoked (Success=False)
```

**Comment by fabiocav** [comment]
@divyagandhisethi do we want to make the fix in the API, or is there an infrastructure fix we need to put in place to avoid calling this API in non-placeholder scenarios?

**Comment by fabiocav** [comment]
@divyagandhisethi was this resolved by the PR you've referenced?

**Comment by divyagandhisethi** [comment]
@fabiocav - yes we can close this out.
