### ISSUE TITLE
Regression: InvalidCastException while creating a WCF channel in Azure Function

### ISSUE THREAD

**Issue by ivan-sam** [Azure/azure-functions-host#7033]
#### Investigative information

Please provide the following:

- Function App version: v3 ("Microsoft.NET.Sdk.Functions" Version>="3.0.6")
- Region: West Europe

#### Repro steps

Provide the steps required to reproduce the problem:

1. Add package "System.ServiceModel.Http" Version>="4.7.0"
2. Create a simple HttpTrigger with the code consuming any WCF service with httpBinding:
```
        [FunctionName("WcfCheckHttpTrigger")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", Route = "WcfCheck")] HttpRequest req, ILogger log)
        {
            var binding = new BasicHttpBinding(BasicHttpSecurityMode.Transport);
            var address = new EndpointAddress("https://anywcfservice.com/SimpleWcfService.svc");
            using var channelFactory = new ChannelFactory<ISimpleServiceChannel>(binding, address);

            using var channel = channelFactory.CreateChannel();
            var response = await channel.InvokeSomeServiceOperationAsync();
            return new OkObjectResult(new { Response = response });
        }
```
3. Debug the function locally using Visual Studio.
4. Deploy the function to Azure (we deploy to ASE) and invoke the trigger twice.

#### Expected behavior

Function invokes the WCF service successfully twice while debugging locally.
Deployed Function invokes the WCF service successfully twice.

#### Actual behavior

Function invokes the WCF service successfully twice while debugging locally.
Deployed Function **invoked** the WCF service successfully twice **before some changes were made to the host**. I don't have exact date, but I'm sure that it was working a couple of months ago.
But current behavior for deployed function is that the first invocation works as expected, but there's an exception on a second invocation:
```
Exception while executing function: WcfCheckHttpTrigger 
 System.InvalidCastException : Unable to cast object of type 'generatedProxy_2' to type 'SimpleService.ISimpleServiceChannel'.
   at System.Reflection.DispatchProxy.Create[T,TProxy]()
   at System.ServiceModel.Channels.ServiceChannelProxy.CreateProxy[TChannel](MessageDirection direction,ServiceChannel serviceChannel)
   at System.ServiceModel.Channels.ServiceChannelFactory.CreateProxy[TChannel](MessageDirection direction,ServiceChannel serviceChannel)
   at System.ServiceModel.Channels.ServiceChannelFactory.CreateChannel[TChannel](EndpointAddress address,Uri via)
   at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address,Uri via)
   at System.ServiceModel.ChannelFactory`1.CreateChannel()
   at async Function.WcfCheckHttpTrigger.Run(HttpRequest req,ILogger log) at D:\a\1\s\src\Function\WcfCheckHttpTrigger.cs : 166
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs : 52
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 559
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance,ParameterHelper parameterHelper,ILogger logger,CancellationTokenSource functionCancellationTokenSource) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 505
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance,FunctionStartedMessage message,FunctionInstanceLogEntry instanceLogEntry,ParameterHelper parameterHelper,ILogger logger,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 283
   End of inner exception
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance,FunctionStartedMessage message,FunctionInstanceLogEntry instanceLogEntry,ParameterHelper parameterHelper,ILogger logger,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 330
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 94
```

#### Known workarounds

Force runtime of one of the previous versions, that are still available (see comments for details), e. g. FUNCTIONS_EXTENSION_VERSION = ~3.0.14916. The problem is that previous versions are removed regularly. Switching to the function v2 also helps.

#### Related information 

Provide any related information 

* Programming language used: C#
* I found an issue with similar symptoms: https://github.com/natemcmaster/DotNetCorePlugins/issues/124
So the issue might be related to the way how function assemblies are loaded.
* I did some other investigations related to the **hosting and loading** area and found out that having a static variable in the trigger similar to `private static object _obj = new object()` combined with code logging the hash code of that object in the trigger shows the difference in hosting models for functions running locally (the hash is the same for all function trigger invocations) and deployed function (each invocation logged different hash)

Again, important thing is that is **regression issue** which **breaks** the code, that was running for months.

P.S. Example above is very simplified version of the real code, running on production. There the repositories that call WCF services are injected, app has multiple layers.

**Comment by ivan-sam** [comment]
I've created a small solution that helps to reproduce the issue: https://github.com/ivan-sam/AzFuncWithWcfServiceBug

And the hosted version of the function can be found here: https://wcfcheckfunctionapp20210106075546.azurewebsites.net

**Comment by ivan-sam** [comment]
Just checked: a newly created function **v2** with exactly same code works with no issues.
Here's an example of such function: https://wcfcheckfunctionv2app20210106185128.azurewebsites.net

**Comment by ivan-sam** [comment]
With the help of the article: https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version and the wiki https://github.com/Azure/azure-functions-host/wiki/Function-Runtime-Versioning I was able to find available older versions of runtime 
![image](https://user-images.githubusercontent.com/4918115/103859520-77dc5680-50ba-11eb-8f81-ec959dfe895b.png)
There were only two for 3.x (along with the current 3.0.15193): 3.0.13353 and 3.0.14916). I tested both setting app configuration variable like this: `FUNCTIONS_EXTENSION_VERSION = ~3.0.14916` - the issue has gone!

**Comment by nawafbaraya** [comment]
Hi, i had the exact same issue and going to  runtime version ~3.0.14916 fixed it, thanks a lot!

**Comment by ivan-sam** [comment]
Also checked deployment to Function App (Linux) - same issue.

**Comment by ivan-sam** [comment]
Since ServiceModel.ChannelFactory uses Reflection.Emit under the hood to create dynamic proxy, there's a chance that much more cases (where libraries that are using Reflection.Emit involved) are broken in host version 3.0.15193

**Comment by ivan-sam** [comment]
Did investigation of the behavior, related to the static fields: it also shows the difference between 3.0.14916 and 3.0.15193:
```
        private static DateTime FixedUtc = DateTime.UtcNow;

        [FunctionName("CheckStaticField")]
        public static IActionResult Run2(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            return new OkObjectResult(new { FixedUtc });
        }

```

**3.0.14916:** every invocation shows the same value
**3.0.15193:** every invocation shows new value

**Update:** Further investigation showed that change in the statics behavior caused the issue with WCF (and not the fact that dynamic proxies are generated using `Reflection.Emit`) because `DispatchProxyGenerator` maintains cache in a static field.

**Comment by SOFSPEEL** [comment]
Wanted to add that I'm seeing same behavior in an Azure Windows v3 deployment.

Since I'm using Autofac DI my cast exception (also shown below) occurred on the CreateChannel code below.

It seems like you've already got a handle on fixing this, but two thing I might add:
- When running the function app locally I don't see this issue (only when running under Azure).
- I was beginning to loose my faith in Azure Function Apps (i.e. same code runs fine in App Service, etc.) as not being able to make soap calls is a big deal, so big thanks to @ivan-sam for your temporary fix.
- and I guess also thirdly, good luck fixing this to @v-anvari , this static deal sounds like a doozy.

```
             builder
                .Register((c, p) =>
                {
                    var config = c.Resolve<ProxyConfiguration>()
                        .KnownProxies
                        .FirstOrDefault(sp => sp.ContractName == typeof(T).Name);

                    var address = ToServiceUri(config);
                    return new ChannelFactory<T>(GetBinding<T>(config),
                        new EndpointAddress(address));
                })
                .SingleInstance();

            // a channel from the factory. Include the UseWcfSafeRelease()
            // helper to handle proper disposal.
            builder
                .Register(c => c.Resolve<ChannelFactory<T>>().CreateChannel())
                .As<T>()
                .UseWcfSafeRelease();


```
**Exception is:**
`Exception while executing function: TopRanksOrchestrator Orchestrator function 'TopRanksOrchestrator' failed: The activity function 'TopRanksFullEventList' failed: "Failed to deserialize exception from TaskActivity: {"$type":"System.InvalidOperationException, System.Private.CoreLib","ClassName":"System.InvalidOperationException","Message":"Exception binding parameter 'blackbaudInterfaceProvider'","Data":null,"InnerException":{"$type":"Autofac.Core.DependencyResolutionException, Autofac","ClassName":"Autofac.Core.DependencyResolutionException","Message":"An exception was thrown while activating.Gateway.BLL.Providers.Interface.BlackbaudInterfaceProvider ->.Gateway.ServiceProxy.Blackbaud.Soap.","Data":{"$type":"System.Collections.ListDictionaryInternal, System.Private.CoreLib","ActivatorChain":"ACS.Fundraising.Gateway.BLL.Providers.Interface.BlackbaudInterfaceProvider ->.Gateway.ServiceProxy.Blackbaud.Soap"},"InnerException":{"$type":"System.InvalidCastException, System.Private.CoreLib","ClassName":"System.InvalidCastException","Message":"Unable to cast object of type 'generatedProxy_2' to type '.Gateway.ServiceProxy.Blackbaud.Soap'.","Data":{"$type":"System.Collections.ListDictionaryInternal, System.Private.CoreLib"},"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Reflection.DispatchProxy.Create[T,TProxy]()\r\n   at System.ServiceModel.Channels.ServiceChannelProxy.CreateProxy[TChannel](MessageDirection direction, ServiceChannel serviceChannel)\r\n   at System.ServiceModel.Channels.ServiceChannelFactory.CreateProxy[TChannel](MessageDirection direction, ServiceChannel serviceChannel)\r\n   at System.ServiceModel.Channels.ServiceChannelFactory.CreateChannel[TChannel](EndpointAddress address, Uri via)\r\n   at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)\r\n   at System.ServiceModel.ChannelFactory`1.CreateChannel()\r\n   at ACS.Fundraising.Gateway.ServiceProxy.AutofacServiceClientHelper.<>c__0`1.<Register>b__0_1(IComponentContext c) in `
```

**Comment by janus78** [comment]
This exact same issue happened on our functions code execution, in our case we were not able to set an older function extension version to implement the workaround so this issue completey broke our code, we are exploring other ways to do the service calls in the meantime this bug is fixed.

**Comment by pragnagopa** [comment]
Thank you for the details! Apologies for delayed response. 

@fabiocav / @brettsam - this looks like a recent regression as it works on `3.0.14916` . Auto-Upgraded apps are running into this issue as well.

**Comment by fabiocav** [comment]
Assigning to sprint 95 for investigation.

**Comment by fabiocav** [comment]
@ivan-sam we were unable to look at this issue during this sprint. Moving this to sprint 97 for a more realistic timeline.

**Comment by ivan-sam** [comment]
I've got some good news and some bad news.

The bad one: the version that I suggested to pin runtime to (as a workaround) was removed: [Removal of older Azure Functions Runtime version: 3.0.14916](https://github.com/Azure/app-service-announcements/issues/313)

The good one though is that I wasn't able to reproduce the issue on the latest version: 3.0.15371 😃 :
![image](https://user-images.githubusercontent.com/4918115/109665387-653c4600-7b6e-11eb-9e2d-108595dbe5dd.png)
The function application that I created for reproducing the issue is working properly.

**Comment by fabiocav** [comment]
@ivan-sam that's a great update. I'll close this as resolved, but please let us know if you run into issues.
