### ISSUE TITLE
Function with slots and WEBSITE_CONTENTAZUREFILECONNECTIONSTRING

### ISSUE THREAD

**Issue by valters-tomsons** [Azure/azure-functions-host#7042]
Technical Information:
- .NET Core 3.1
- Azure Premium ASP plan
- Windows Host

Hi, I hope this is the right repository for this issue.

When adding a slot to function app, it should be documented clearly that `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` must be set for both staging and production apps.

In our case, we deploy staging slot separately from production app and we have noticed that the aforementioned variable must be manually added to production app, otherwise package deployments fail with `Failed to deploy web package to App Service. Internal Server Error (CODE: 500)` to both (staging & prod).

**Comment by v-bbalaiagar** [comment]
Hi @FaithLV, Can you share us the link that you are referring to. We shall validate and make the required changes.

**Comment by valters-tomsons** [comment]
@v-bbalaiagar I think the appropriate place for this note would be here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#website_contentazurefileconnectionstring

**Comment by v-anvari** [comment]
Hi @FaithLV , 

Required application settings
AzureWebJobsStorage
Required for Consumption and Premium plan functions:
WEBSITE_CONTENTAZUREFILECONNECTIONSTRING
WEBSITE_CONTENTSHARE

In this [document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-recover-storage-account#guidance) it is stated that "The above settings must be provided and valid at creation time. An automated deployment that doesn't contain these settings results in a function app that won't run, even if the settings are added later." 

These settings need to manually set-up for any slot. Even during swap, connection string is swapped automatically, but this setting can be altered to stick to a particular slot. 

[Which settings are swapped](https://docs.microsoft.com/en-us/azure/app-service/deploy-staging-slots#which-settings-are-swapped)
