### ISSUE TITLE
Updating RPC layer to include RetryContext

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-host#7048]
https://github.com/Azure/azure-webjobs-sdk/pull/2658#issuecomment-758138906

**Comment by jeffhollan** [comment]
@alrod @pragnagopa @fabiocav trying to assess - is this the only remaining work item to exposing retry context as part of retry feature?

**Comment by pragnagopa** [comment]
cc @AnatoliB 

@jeffhollan -  For C#, work should be complete after we realease udpated SDK to nuget. For non-dotnet languages each language worker needs to be updated to include "RetryContext" as part of "ExecutionContext"

Issue https://github.com/Azure/azure-functions-python-worker/issues/814 is tracking python changes. We need similar work-items in other language worker repos as well.
