### ISSUE TITLE
Azure Queue Message not firing function sometimes

### ISSUE THREAD

**Issue by srjhunjhunwalacorp** [Azure/azure-functions-host#7050]
#### Is your question related to a specific version? If so, please specify:
Azure Function Version - 1.0.29

Scenario - 
Azure Function Running Naively on a virtual Machine which is in corporate environment, and Azure storage Queue is in Public external network of same tenant.

Our function is on C#

#7042 Question  - Our local running azure function sometime stops getting fired by new queue messages, this basically results in queue messages getting stack up and function goes stale until you restart them.

Any pointer to get this sorted?

**Comment by v-anvari** [comment]
Hi @srjhunjhunwalacorp , Let us know if you are seeing this issue with the latest Function versions

**Comment by srjhunjhunwala** [comment]
Hi @v-anvari,

We have a dependency on .NET Framework 4.6 that is why kept it to 1.X.

**Comment by v-anvari** [comment]
Hi @srjhunjhunwala , Are you still seeing these errors?
