### ISSUE TITLE
Migrate storage abstraction to Storage v12

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-host#7057]
#### What problem would the feature you're requesting solve? Please describe.
AzureWebJobsStorage is a connection string only. We wish to support connecting using managed identities.

#### Describe the solution you'd like
We should move the implementation of the storage abstraction used by TimerTrigger to the latest Azure SDKs. This includes support for Azure.Identity. We should leverage `Microsoft.Extensions.Azure` where possible to ensure consistency of configuration options.

**Comment by fabiocav** [comment]
Closing issue as done.
