### ISSUE TITLE
[Auto-Upgrade]System.TypeInitializationException : The type initializer for 'MongoDB.Bson.Serialization.BsonClassMap'

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#7059]
cc @fabiocav 

Few apps are failing on auto-upgrade with the error:
```
System.TypeInitializationException : The type initializer for 'MongoDB.Bson.Serialization.BsonClassMap' threw an exception. ---> System.ArgumentNullException : Value cannot be null. (Parameter 'type')
```

These apps are being pinned actively. Needs investigation.

**Comment by youxu71** [comment]
Any progress on the fixing? We have several Functions running on PROD facing this issue. As a mitigation work around, we have to downgrade the runtime to 2.x.

**Comment by pragnagopa** [comment]
Yes, this is related to https://github.com/Azure/app-service-announcements/issues/266 . We have been actively pinning apps running into this issue. For now please pin apps to Functions V2.  We recommend upgrading to Functions V3 at your earliest convenience.

**Comment by pragnagopa** [comment]
Copying mitigation steps from https://github.com/Azure/app-service-announcements-discussions/issues/175#issuecomment-762931352

> updating the Functions SDK version to the latest major 1.x release (1.0.38) and updating our MondoDB dependency too did the trick. With this mitigation in place next we aim for Functions V3. Thx.

**Comment by youxu71** [comment]
> Yes, this is related to [Azure/app-service-announcements#266](https://github.com/Azure/app-service-announcements/issues/266) . We have been actively pinning apps running into this issue. For now please pin apps to Functions V2. We recommend upgrading to Functions V3 at your earliest convenience.

Thanks @pragnagopa, by upgrading to Function V3, do you mean just set the FUNCTIONTIONS_EXTENSION_VERSION TO ~3 in Functions configuration in portal? If so, it failed with the MongoDB exception. Do we need update the MongoDB reference as well?

**Comment by pragnagopa** [comment]
> Do we need update the MongoDB reference as well

Yes, please update Functions SDK version to the latest major and update MongoDB reference, test it locally with [Azure Functions Core Tools V3](https://github.com/Azure/azure-functions-core-tools/#to-install-with-npm) before deploying to Azure.

**Comment by youxu71** [comment]
> > Do we need update the MongoDB reference as well
> 
> Yes, please update Functions SDK version to the latest major and update MongoDB reference, test it locally with [Azure Functions Core Tools V3](https://github.com/Azure/azure-functions-core-tools/#to-install-with-npm) before deploying to Azure.

Thanks, do you know what is the least version of MongoDB SDK which works with V3 function?

**Comment by pragnagopa** [comment]
Apologies, I do not have an exact version recommendation. But you should be able to run it locally to ensure reference you updated to works as expected.
