### ISSUE TITLE
V3: "Synchronous operations are disallowed" when returning Task<HttpResponseMessage>

### ISSUE THREAD

**Issue by AnatoliB** [Azure/azure-functions-host#7064]
The following function fails with status 500 and the following message in the log: `Microsoft.AspNetCore.Server.Kestrel.Core: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.`

``` CSharp
[FunctionName("SayHello")]
public async Task<HttpResponseMessage> Run(
    [HttpTrigger(AuthorizationLevel.Function, "post", Route = null)]HttpRequestMessage req,
    ILogger log)
{
    return req.CreateResponse(HttpStatusCode.OK, "Hello");
}
```

Setting AllowSynchronousIO solves the issue, but the problem is that this code worked in V2, so this complicates migration to V3.

Please note that the following code works fine under the same circumstances:

``` CSharp
[FunctionName("SayHello")]
public async Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Function, "post", Route = null)]HttpRequestMessage req,
    ILogger log)
{
    return new OkObjectResult("Hello");
}
```

#### Repro steps

1. Create an HTTP-triggered function with the code above (returning `Task<HttpResponseMessage>`).
2. Start the app locally and invoke the function (e.g. `irm 'http://localhost:7071/api/SayHello' -Method POST`).

#### Expected behavior

200 response.

#### Actual behavior

500 response. The host logs contain:
```
An unhandled host error has occurred.
Microsoft.AspNetCore.Server.Kestrel.Core: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
```

#### Known workarounds

- Set `AllowSynchronousIO` to `true` in the code; or
- Set `AzureWebJobsFeatureFlags` app setting to `AllowSynchronousIO`; or
- Set `FUNCTIONS_V2_COMPATIBILITY_MODE` app setting to `1`; or
- Modify the function code to return `Task<IActionResult>` instead of `Task<HttpResponseMessage>`.

Please note that, even though there are many workarounds, the point is that this complicates migrating a working app from V2 to V3.

#### Related information 

func --version
**3.0.3233**

**Comment by tommck** [comment]
I have the same problem.. I started using `return new HttpResponseMessage(....` instead :(

**Comment by AmirulOm** [comment]
We had the same problem. I'm following this for updates.

**Comment by fabiocav** [comment]
This is a known change between 2.0 and 3.0. This is something that was introduced by the underlying platform.

The recommendation is to change the code to avoid synchronous IO, but to make migration simpler (and this is something that is done automatically to auto-migrated apps), you can add the compatibility mode flag, which will disable this behavior.

To enable the flag, set the following app setting:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#functions_v2_compatibility_mode

**Comment by tommck** [comment]
I'm confused... what does this have to do with Synchronous I/O @fabiocav ?
