### ISSUE TITLE
@IanKemp , Let us know if you have any further queries related to this issue.

### ISSUE THREAD

**Issue by erickson71** [Azure/azure-functions-host#7066]
@IanKemp , Let us know if you have any further queries related to this issue.

_Originally posted by @v-anvari in https://github.com/Azure/azure-functions-host/issues/5782#issuecomment-693494565_

**Comment by v-anvari** [comment]
Hi @erickson71 , I have reopened [https://github.com/Azure/azure-functions-host/issues/5782](https://github.com/Azure/azure-functions-host/issues/5782). Further follow ups would be updated in that issue
