### ISSUE TITLE
Special character "%" in url path results in 500 Internal server error

### ISSUE THREAD

**Issue by spmanjunath** [Azure/azure-functions-host#7069]
Azure function version: 3.1 (netcoreapp3.1)

I have azure function that uploads the files, some of these files have special character like $, %, #, etc., in their names.  Consider below example,

File Name: Word%.docx
Example of Uri invoked (Encoded url):  http://localhost/api/file/Word%25.docx

since the file name is encoded the expectation is that the function is triggered, in fact the Azure function that is hosted locally (executed from Visual Studio) gets invoked.  However, the Azure hosted function fails with 500 Internal Server Error, i did not notice any registration of the invocation itself (the call never reaches the hosted function), it appears that the exception is returned at a higher layer.

For files with names having "#" the Azure hosted function works as expected, the problem appears to be specific to the "%" symbol.

**Comment by v-anvari** [comment]
Hi @spmanjunath , We would like to repro the scenario to understand the issue better. Kindly, provide us the repro steps or the zip file for repro

**Comment by spmanjunath** [comment]
Sorry for the wrong reporting, the Azure function works well with the '%'.  In my implementation it was the API Gateway that was causing this issue, the Azure function sits behind this gateway, and i completely ignored that fact.  You can close this issue.  Thanks.

**Comment by v-anvari** [comment]
Thankyou for the update. The issue is closed
