### ISSUE TITLE
How do I find the full .NET Core v2 version which Azure is using to host my Function App 

### ISSUE THREAD

**Issue by sdg002** [Azure/azure-functions-host#7070]
#### Is your question related to a specific version? If so, please specify:
We have .NET Core functions on V2

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
We are seeing some assembly load failures. Local debugging works fine. We want to know the precise version of that Azure runtime is using to host our assembly

**Comment by pragnagopa** [comment]
This could be related to Auto-Upgrade roll out we finished last week. Please see https://github.com/Azure/app-service-announcements/issues/266 for more details.

**Comment by v-anvari** [comment]
Closing this issue as the required information is provided, please feel free to reach back to us or re-open this issue in case of any queries.
