### ISSUE TITLE
AI: Local storage access has resulted in an error

### ISSUE THREAD

**Issue by gaborbuzasi** [Azure/azure-functions-host#7072]
Hi,

This is still an issue using the latest Azure Functions running in Docker container on a premium linux plan.

_Originally posted by @emanuel-virca in https://github.com/Azure/azure-functions-host/issues/4263#issuecomment-747562174_

**Comment by v-anvari** [comment]
Hi @gaborbuzasi , Apologies for the delayed response, Can we know if you are seeing this error with the latest versions
