### ISSUE TITLE
How to specify Application Insights role name for locally running function?

### ISSUE THREAD

**Issue by vviskari** [Azure/azure-functions-host#7074]
#### Is your question related to a specific version? If so, please specify:

No

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 

Java (all?)

#### Question

How can I specify Application Insights "role name" for a Function that runs locally?

I have to use the same instrumentation key to monitor several apps and role name is a way to distinguish them from each other in Application Insights. I can do this for Spring Boot apps (use Java Agent and define the role name in ApplicationInsights.json).

I can't find way to define an Insights role name for Functions.

**Comment by anthonychu** [comment]
Related to https://github.com/Azure/azure-webjobs-sdk/issues/2635

**Comment by v-bbalaiagar** [comment]
Hi @vviskari, Were you able to find a solution here. Kindly let us know if you could resolve it can we close this issue?

**Comment by vviskari** [comment]
Hi @v-bbalaiagar, Solution is in the related issue https://github.com/Azure/azure-webjobs-sdk/issues/2635.
Are there any estimates when this would be released so I can test? Thanks.

**Comment by v-bbalaiagar** [comment]
Hi @vviskari, This is under implementation and will be updated in the announcement page here - https://github.com/Azure/app-service-announcements/issues

**Comment by v-bbalaiagar** [comment]
Hi @vviskari, Closing this issue as the required information is provided, please feel free to reach back to us in case of any further queries related to this issue.
