### ISSUE TITLE
No Runtime V3 builds for Worker testing

### ISSUE THREAD

**Issue by vrdmr** [Azure/azure-functions-host#7076]
#### Is your question related to a specific version? If so, please specify:
For Python's E2E test and some unit tests, we use the host's no runtime build. For a long time, the version used for testing has been v2 build. We plan to use v3 host for testing but a no-runtime build isn't generated for it. 

E.g.: [setup.py#L21-L24](https://github.com/Azure/azure-functions-python-worker/blob/dev/setup.py#L21-L24)
```python
WEBHOST_URL = (
  "https://github.com/Azure/azure-functions-host/releases/download"
  "/v2.0.14494/Functions.Binaries.2.0.14494.no-runtime.zip"
)
```

#### Question
Is there anything special that needs to be done to get the no-runtime builds to be produced for v3 builds now?

**Comment by Hazhzeng** [comment]
This should be fixed by https://github.com/Azure/azure-functions-python-worker/pull/808
