### ISSUE TITLE
End-To-End transaction: from API Management to Azure Functions to ServiceBus not working

### ISSUE THREAD

**Issue by erwinkramer** [Azure/azure-functions-host#7081]
I'm using the Function v3.0.15193.0 runtime hosted on Windows in an elastic plan inside a vnet. 

Libraries inside my solution (i'm running from a package file):
```
  <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="3.0.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.2.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.3" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
```

I'm not specifying any Application Insights reference, since I rely on the build-in support in the Azure Function magic. 

In API Management, I specified the _W3C_ correlation protocol instead of the _Legacy_ option. 

### Describe the bug

I'm trying to get the End-to-end transaction flow working. Currently, I see my API Management resource and Azure Function resource in the same flow, so far so good. 

After the Azure function (http trigger), it should show the Service Bus queue request (not working) and the function behind that service bus queue (it shows the function _information_ logging and _request_ calls in app insights, but there is no relation with the previous function, nor with the servicebus from the trigger). 

In the first function I'm passing in the message to the queue by making the servicebus message myself, with the following decoration on top of the function:
`[ServiceBus("queue-x", Connection = "y")] out Message sbMessage`

With a message object like this:
`sbMessage = new Message(Encoding.UTF8.GetBytes(a.b.ToString()))
                {
                    CorrelationId = correlationId
                };`

Similar issues are described here: https://stackoverflow.com/questions/58939510/end-to-end-correlation-for-api-management-functions-and-servicebus and here https://stackoverflow.com/questions/65131102/azure-app-insights-issue-with-end-to-end-tracing

Both describe different solutions, which both feel like workarounds. Or am I missing something?

**Comment by erwinkramer** [comment]
Just figured out with the help of: https://github.com/Azure/Azure-Functions/issues/1613#issuecomment-687062296 that the issue is every nuget reference with a dependency on System.Diagnostics.DiagnosticSource newer than 4.7.0

**Comment by v-bbalaiagar** [comment]
Hi @erwinkramer, Apologies for the delayed response. Were you able to find a solution here. Kindly let us know if you could resolve it can we close this issue?

**Comment by erwinkramer** [comment]
@v-bbalaiagar I've found the workaround is using an older version of packages using System.Diagnostics.DiagnosticSource. So it's not solved, please see my previous comment. It's still relevant.

**Comment by v-bbalaiagar** [comment]
Hi @erwinkramer, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by pragnagopa** [comment]
@fabiocav  / @brettsam  - Issue has enough details and the work-around is to use earlier versions for `System.Diagnostics.DiagnosticSource` version - 4.7.0

Is there anything we can do to address this issue?

**Comment by MarekLani** [comment]
please any progress on this?

**Comment by v-bbalaiagar** [comment]
Can you check the comment mentioned here - https://github.com/Azure/azure-functions-host/issues/7278#issuecomment-1004653629
Let us know if that works.

**Comment by erwinkramer** [comment]
@v-bbalaiagar I've upgraded to .net 6 and did the changes like in https://github.com/Azure/azure-functions-host/issues/7278#issuecomment-1004653629 last month, and yes, this solves the issue, i see the whole chain in app insights from start to finish with a service bus queue in between. Thanks.
