### ISSUE TITLE
Function timer trigger not firing

### ISSUE THREAD

**Issue by oslabyi** [Azure/azure-functions-host#7091]
i'm new one in work with Functions app, and try to deploy scheduled function

Timestamp: 2021-01-23 throughout the day
Function App version (1.0 or 2.0): 2.0
Function App name: e.g. testtimetriggerapp
Function name(s) (as appropriate): TestTimerTrigger
Region: Central US
Operating System: Windows
App service plane: (Y1: 0)

**Rep steps**
I had create new test app, and deploy, it should fire every hour (0 */1 * * *)

**Expected behavior**
The function fires every hour.

**Actual behavior**
Function do not fire in time by schedule.
The function fires only when I visit the portal

**Comment by AartBluestoke** [comment]
is the app service plan set to 'always on'?

**Comment by balag0** [comment]
The cron expression doesnt look right. For once every hour use the expression "0 0 * * * *"
More examples at https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=csharp#ncrontab-examples

**Comment by oslabyi** [comment]
> 
> 
> is the app service plan set to 'always on'?

i use Consumption plan, and as i read - it do not have "Always on", system automatically take care when function should wake up.

**Comment by oslabyi** [comment]
> 
> 
> The cron expression doesnt look right. For once every hour use the expression "0 0 * * * *"
> More examples at https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=csharp#ncrontab-examples

thx, my mistake, used cron expression instead of ncron
