### ISSUE TITLE
[Auto-Upgrade] Send notifications for apps that are pinned to Functions V2 - Linux Dedicated

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#7096]
For Dedicated / EP - Look up hosting DB for apps with LinuxFx Version set to 
```
DOCKER|mcr.microsoft.com/azure-functions/dotnet:2.0.14786-appservice
```

**Comment by fabiocav** [comment]
Moving to next sprint as we're still tracking this work.

**Comment by fabiocav** [comment]
Moving this to sprint 96 as we want to continue to track.

**Comment by pragnagopa** [comment]
Closing as this being tracked internally.
