### ISSUE TITLE
Scheduled Azure Functions not running before visiting portal

### ISSUE THREAD

**Issue by mookid8000** [Azure/azure-functions-host#7100]
I have an Azure Functions app with a bunch of functions scheduled using `[TimerTrigger("*/2 * * * *")]`, i.e. they're scheduled to be executed every 2 minutes.

They're deployed using the "Deploy Azure Function App" pipeline task in Azure DevOps. It's hosted on a "Consumption (Serverless)" plan in Azure.

Often I catch the functions NOT BEING EXECUTED! 😳  I usually discover this, because the data they're retrieving for me is missing since the last deployment. So I go visit the Azure Portal, and it's clear from the charts that nothing has been executed for a while.

After clicking around a bit, refreshing some of the views, they wake up and start running. Here's a chart showing my 7 functions being executed every 2 minutes, 24 hours a day, 365 days a year (yes.... I went and refreshed things and thus woke up the functions at ~5:40 AM this morning).

![image](https://user-images.githubusercontent.com/32968/105802114-d8183700-5f9a-11eb-97af-b3a89e0ad7d8.png)

I heard that this was an issue.... in 2018... 🙄  is this still an issue? Or am I doing something wrong?

#### Investigative information

- Timestamp: 2021-01-26 04:39:09.806
- Function App version: v3
- Invocation ID: 4ae0159dd761004c84920b0672cea4f3 (this is the first execution of one of the functions after lying dormant overnight)
- Region: West Europe
- Stack: .NET Core 3.1
- SDK: Microsoft.NET.Sdk.Functions 3.0.11

**Comment by mookid8000** [comment]
This is what it looks like when 

1. I get up at 5:30 in the morning
2. realize that the functions scheduled every 2 minutes round the clock _have not been running since the day before yesterday_
3. I click "Refresh" and generally just click around a bit

👇 

![image](https://user-images.githubusercontent.com/32968/106095037-5c052700-6133-11eb-9d02-36e4a3979ead.png)

Let me know if I should fetch more information about my functions... although, I've heard from others that this could be an issue, and so I assume it's not a problem that pertains to my particular setup. Could be wrong though, so I'd be happy to provide any kind of additional information.

**Comment by v-bbalaiagar** [comment]
Hi @mookid8000, I tried to get the logs but looks like the app is deleted. I'm unable to fetch the details. Can you please provide the function app name.

**Comment by mookid8000** [comment]
The app is not deleted – the name is "helios-dev-fx"

**Comment by mookid8000** [comment]
Functions not running again... went and visited the portal, clicked "Refresh" a couple of times... after a while:

![image](https://user-images.githubusercontent.com/32968/106196425-b218af80-61b1-11eb-9ed2-123077388eec.png)

🙄 

It this how scheduled Azure Functions are supposed to work?

**Comment by v-bbalaiagar** [comment]
Hi @mookid8000, We have checked the logs and we see errors for different functions which states "invalid cron expression" and the App is eventually shutting down after that. 
Error: The 'AtI******' function is in error: '*/2 * * * *' is not a valid CRON expression.

See this [document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#timeout) for more info on function app timeout duration.

Also, you can diagnose the exceptions in your web app with [application insights.](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-exceptions)

 The sampling is enabled in your App which is enabled by default which can lead to missing logs. You may have to make certain changes in the [configuration ](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#application-insights-pricing-and-limits)to fit your particular scenario.

Do let us know if any of the above works for you.

**Comment by mookid8000** [comment]
I don't get it... I can run the functions locally without any problems.

The cron expression `*/2 * * * *` is valid according to e.g. [CronHub](https://crontab.cronhub.io/)

![image](https://user-images.githubusercontent.com/32968/106330269-371fc980-6283-11eb-8a58-83d8ac8ce3de.png)

and – as you can see in the charts, _the functions do execute_, just not when I'm not looking. 😳 

> See this document for more info on function app timeout duration.

Isn't "function app timeout durations" about having a timeout on the execution of the functions? Doesn't seem related to scheduling of the functions, or am I missing something?

**Comment by anthonychu** [comment]
@mookid8000 can you please try with this expression: `0 */2 * * * *`? Functions supports an extra field for seconds. https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer#ncrontab-expressions

I wonder if what may be happening is the following. The symptoms seem to be consistent with this:

- The functions host works with both formats, with or without seconds.
- We have a separate component called the scale controller that is in charge of scaling and waking up your app when an event (like a timer) needs to run. There's a chance this component does not support the crontab format without seconds and that's what's producing the error here. If the app ever scales down, this error might be preventing it from scaling back up. Opening the portal wakes the app up.

**Comment by anthonychu** [comment]
@mookid8000 Actually I tried to reproduce your issue and so far haven't been able to. My timer function will not run at all with the incorrect cron expression.

However, please update the format of your cron expressions and see if the problem continues.

Looks like we need to do a better job of surfacing the errors, though.

**Comment by mookid8000** [comment]
OK I can see now that it's because my cron expressions did not have the "seconds" component.

It's a little bit weird that they seemed to run fine locally, and they seemed to run fine for a while in Azure... but they would always end up shutting down, and then they would start again when I clicked around in the portal.

So.... I've now made this test:
```csharp
    [TestFixture]
    [Description(@"Verifies that all of the used CRON expressions can be validated using the variation that Azure uses.

As per https://github.com/Azure/azure-functions-host/issues/7100 it can be seen that Azure uses NCronTab (with seconds enabled) to parse the expressions, and so that is what we do here too.
")]
    public class CheckCronExpressions
    {
        [TestCaseSource(nameof(GetCronExpressions))]
        public void CheckExpression(CronExpression expression)
        {
            Console.WriteLine($"EXPRESSION: {expression}");

            var options = new CrontabSchedule.ParseOptions { IncludingSeconds = true };
            var crontabSchedule = CrontabSchedule.Parse(expression.Expression, options);

            Console.WriteLine(crontabSchedule);
        }

        static IEnumerable<CronExpression> GetCronExpressions()
        {
            return typeof(Startup).Assembly.GetTypes()
                .SelectMany(type => type.GetMethods())
                .Where(method => method.GetCustomAttributes(typeof(FunctionNameAttribute), inherit: true).Any())
                .Select(method => new CronExpression(method, method.GetParameters().Select(p => p.GetCustomAttribute<TimerTriggerAttribute>()?.ScheduleExpression).FirstOrDefault(expression => expression != null)))
                .Where(e => e.Expression != null);
        }

        public class CronExpression
        {
            public MethodInfo Method { get; }
            public string Expression { get; }

            public CronExpression(MethodInfo method, string expression)
            {
                Method = method;
                Expression = expression;
            }

            public override string ToString() => $"{Method.DeclaringType?.Name}.{Method.Name}: {Expression}";
        }
    }
```
that iterates over all of my functions, trying to parse the cron expressions with options `new CrontabSchedule.ParseOptions { IncludingSeconds = true }`. The `IncludingSeconds = true` was the thing that made the difference 🙂 

When visiting the portal, the execution count looks much more like 7 functions scheduled every 2 minutes:

![image](https://user-images.githubusercontent.com/32968/106365280-d05ae880-6334-11eb-97e6-e9c4763c7d35.png)

Thanks for your help! 🙂

**Comment by anthonychu** [comment]
@mookid8000 Yes it’s working locally for me as well. We’ll fix it. (Ideally we support with or without seconds)
