### ISSUE TITLE
Unable to cast object of type 'generatedProxy_3' to type 'HK.Plugin.POS.Services.ItemInfo.IItemInfoService'

### ISSUE THREAD

**Issue by lintho** [Azure/azure-functions-host#7112]
After the automatic upgrade to 3.0 our function stopped working.

**The error message was:**
Unable to cast object of type 'generatedProxy_3' to type 'HK.Plugin.POS.Services.ItemInfo.IItemInfoService'

We are using a WCF service(IItemInfoService), and the second time the function ran the error occured, and it kept having errors every run, until i restarted, and it worked ONCE, then errors again.

The WCF service was registered as an interface in startup, and was used with DI in the function.

**Temp fix:**
After downgrading to 2.0, it once again works

CODE:
```
public override void Configure(IFunctionsHostBuilder builder)
{
            builder.Services.AddTransient<IHKService, LindbakService>();
            builder.Services.AddScoped<IItemInfoService>(provider =>
            {
                var client = new ItemInfoServiceClient();

                return client;
            });
}


public class HKService : IHKService{
        private readonly IItemInfoService _itemInfoService;
        public LindbakService(IItemInfoService itemInfoService)
        {
            _itemInfoService = itemInfoService;
        }

}


public async Task<List<ItemMaintenanceItem>> GetAllItems(DateTime changedSince){
 var productResponse = await _itemInfoService.GetAllActiveProductsInArtsXml2Async(
                    new GetAllActiveProductsInArtsXml2_Request
                    {
                        ChangedSince = changedSince,
                        Paging = new LindBakServices.ItemInfo.PaginationParameters { Limit = limit, Offset = offset },
                        StoreNumber = StoreNumber,
                        IncludeArticleRelations = true,
                        StoreNumberType = LindBakServices.ItemInfo.StoreIdentifierType.StoreNumber,
                    });

}


 public class ProductInfoFunction
    {
        private readonly ILindbakService _lindbakService;
public ProductInfoFunction(ILindbakService lindbakService)
        {
            _lindbakService = lindbakService;
          
        }
[Singleton]
        [FunctionName("AddAllProductChangeToQueue")]
        public async Task AddAllProductChangeToQueue([TimerTrigger("0 */3 * * * *")] TimerInfo myTimer, ILogger log)
        {
                  var products =  await _lindbakService.GetAllItems(lastDate);
        }

}

```

**Comment by pragnagopa** [comment]
cc @brettsam 

@fabiocav - assigned this to you for now. Please re-assign as needed. Customer needs help with moving to Functions V3

**Comment by HGrzesiakKG** [comment]
I have exactly the same problem.
When I call the function with TimeTrigger.
I have two cases:
1. The first call to TimeTrigger with a reference to the WCF service works fine, but the next calls to the function throw the error "Unable to cast object of type 'generatedProxy_X' (X is number) to type 'WCFService'.
2. When I call the TimeTrigger function with a reference to the WCF service for the first time and then call the HttpTrigger function, I get "Unable to cast object..." in both cases.

Going from 4 versions of azure functions to 2 or 3 doesn't help.

`Message: Unable to cast object of type 'generatedProxy_10' to type 'WCFService'.
StackTrace:    at System.Reflection.DispatchProxy.Create[T,TProxy]()
   at System.ServiceModel.Channels.ServiceChannelProxy.CreateProxy[TChannel](MessageDirection direction, ServiceChannel serviceChannel)
   at System.ServiceModel.Channels.ServiceChannelFactory.CreateProxy[TChannel](MessageDirection direction, ServiceChannel serviceChannel)
   at System.ServiceModel.Channels.ServiceChannelFactory.CreateChannel[TChannel](EndpointAddress address, Uri via)
   at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.ClientBase`1.CreateChannel()
   at System.ServiceModel.ClientBase`1.CreateChannelInternal()
   at System.ServiceModel.ClientBase`1.get_Channel()
   at System.ServiceModel.ClientBase`1.get_InnerChannel()
   at System.ServiceModel.ClientBase`1.System.ServiceModel.ICommunicationObject.Open(TimeSpan timeout)`
