### ISSUE TITLE
HttpTrigger to set the AuthorizationLevel dynamically from environment variables?

### ISSUE THREAD

**Issue by justinyoo** [Azure/azure-functions-host#7115]
* Azure Functions runtime version: both 2.x and 3.x (aaaaaand possibly 1.x)
* Language: C#

I've got some code like below:

```csharp
[FunctionName(nameof(OpenApiHttpTrigger.RenderSwaggerDocument))]
[OpenApiIgnore]
public static async Task<IActionResult> RenderSwaggerDocument(
    [HttpTrigger(AuthorizationLevel.Anonymous, "GET", Route = "swagger.{extension}")] HttpRequest req,
    string extension,
    ILogger log)
{
    ...
}
```

I want to dynamically assign the authorisation level to the `HttpTrigger` by reading the value from the environment variables, something like `%WebJobsHttpTriggerAuthLevel%`. So the code above changes to:

```csharp
[FunctionName(nameof(OpenApiHttpTrigger.RenderSwaggerDocument))]
[OpenApiIgnore]
public static async Task<IActionResult> RenderSwaggerDocument(
    [HttpTrigger("%WebJobsHttpTriggerAuthLevel%", "GET", Route = "swagger.{extension}")] HttpRequest req,
    string extension,
    ILogger log)
{
    ...
}
```

I know other bindings like Storage Queue, Service Bus, Cosmos DB, etc read connection strings like this way.

Do we have a similar feature against HTTP trigger?

**Comment by justinyoo** [comment]
To give more context on this request:

[This extension](https://github.com/Azure/azure-functions-openapi-extension) provides pre-defined endpoints for the Open API document generation.

Some organisations want to secure those endpoints by adding the function key, or the others leave the endpoints publicly accessible. If we have this option&ndash;dynamically assigning the auth level from environment variables&ndash;we can give devs to choose the auth level of their choice.

**Comment by fabiocav** [comment]
@justinyoo is this still a requirement after the last chat we had?

**Comment by justinyoo** [comment]
@fabiocav Yes, from the Open API extension perspective, it's still required.

**Comment by justinyoo** [comment]
This issue, https://github.com/Azure/azure-functions-dotnet-worker/issues/562, is related to this one

**Comment by fabiocav** [comment]
@justinyoo we're reviewing this as part of our triage process and we need more information about the problem you're trying to solve as we still feel we don't have a lot of clarity here.

Would you be able to provide more information about the problem you're trying to solve with this?

**Comment by justinyoo** [comment]
The current `HttpTrigger` binding only takes the hard-coded value of authorisation level like `AuthorizationLevel.Anonymous` or `AuthorizationLevel.Function`. It's OK in most cases.

But in an edge case, like Swagger UI with Azure Functions OpenAPI extension, some particular endpoints need to be flexible for their auth levels, which can be configured by environment variables. It's similar concept to how connection strings for Service Bus and Cosmos DB are configured by environment variables

**Comment by wsugarman** [comment]
I think this is especially important as new hosting environments become available for Azure Functions. While in app services, a function app may specify `AuthorizationLevel.Anonymous` and rely on Easy Auth. However, in Kubernetes, they may opt for `AuthorizationLevel.Function`. This flexibility also aligns with existing solutions, like being able to specify the cron expression for timer triggers via environment variables.
