### ISSUE TITLE
Timeout issues when querying Cosmos DB using input binding

### ISSUE THREAD

**Issue by robinhultman** [Azure/azure-functions-host#7116]
Azure Functions V3
Consumption Plan
Invocation ID: 22792f2b-4724-4c33-ab1c-da5055f99f65
West Europe

We have a function which is triggered by an HTTP request and performs a simple query against a Cosmos Database using an injected (input binding) DocumentClient. 

**Symptom**: We have seen some cases when the request to Cosmos times out after 1.7 minutes resulting in a SocketException. It seems that the load on the function is very low when this is happening
The client cancels the request after 20 seconds.

I have some other invocations (from other Function Apps) where this have happened if that is of any help.
I would really appreciate some help with this!

**Comment by v-bbalaiagar** [comment]
Hi @robinhultman, Apologies for the delayed response, I am unable to get the logs with the mentioned invocation Id. Can you confirm.
Also, can you please provide us the latest invocation id of the error and time stamp to get the logs and check the cause.
