### ISSUE TITLE
Update 2.1.xxxx extension to use files from 3.0.xxxx

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#7117]
cc @alrod @suwatch 

SiteExtensions 2.1.xxxx and 3.0.xxxx are same bits packaged to support ~2 apps running on windows to use Functions V3

To avoid shipping duplicate files, need to update application.xdt file in 2.1.xxxx to point to 3.0.xxxx

here is an example:
```
<virtualDirectory path="/" physicalPath="%ProgramFiles(x86)%\SiteExtensions\Functions\3.0.15371\%XDT_BITNESS%" />
```

**Comment by pragnagopa** [comment]
@fabiocav - This would require adding 3.0.xxxx and 2.1.xxxx packages together and removing them together as physical path for site extension 2.1.xxxx is hardcoded.  Please ACK on this approach.

**Comment by fabiocav** [comment]
This is correct. Though, we should be able to avoid hardcoding the path. We should have the ability to process the replacement based on the environment variables provided.

**Comment by alrod** [comment]
XDT transform does not allow partial replacement in the string. It can replace a node or an attribute. I see there are 2 approaches:
1. Hardcode in applicationHost.xdt
2. Replacement in ANT code.

**Comment by fabiocav** [comment]
I think there's an assumption being made here. The suggestion is not to replace in the transform. I'll reach out to chat.

**Comment by pragnagopa** [comment]
Moving to next sprint and assigning to @fabiocav 

Notes from offline discussion:

- Update build to produce following artifacts: 
    - 3.0.xxxx.zip - no changes to this
    - 2.1.xxxx.zip - this zip should only contain `extension.xml` and `.xdt` file  with contents as described in the decription.

- Create a batch file as part of build artifacts that will add `3.0.xxxx.zip` and `2.1.xxxx.zip` to the RU feed 
- Create a batch file as part of build artifacts that will remove `3.0.xxxx.zip` and `2.1.xxxx.zip` to the RU feed 

NOTE: We need to add two zip files to ensure SiteExtension gets cleaned up for both 3.0.xxxx and 2.1.xxxx

**Comment by pragnagopa** [comment]
Updating offline discussion:

@fabiocav  / @alrod  - @suwatch pointed out another failure condition we will end up while cleaning up. For example

1.  We delete 2.1.1234 and 3.0.1234 
2. On the workers, above packages will be deleted only when not in use
3. If on a worker, ~3 apps are not running but ~2 apps are using site extension 2.1.1234 then, 3.0.1234 will be deleted but 2.1.1234 will not be deleted
4. Then, ~2 apps will start failing as there no files on the machine

**Comment by fabiocav** [comment]
Yeah, that makes sense. Need to define a proper solution for that. Flagging this as blocked until then.

**Comment by pragnagopa** [comment]
This is addressed in the platform to allow using Functions.3.0.xxxx site extension for Functions ~2 apps.
