### ISSUE TITLE
Azure function timer trigger in aks pods not singleton

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/azure-functions-host#7118]
#### Is your question related to a specific version? If so, please specify:
AKS, .netCore3.1, AzureFunctions3

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
c#
#### Question
I have function projects with different types of functionTriggers.  One of them is TimerTrigger based and we need to run them on odd/even intervals in primary/secondary regions.  Before putting functions into aks we used consumption plan and gave odd/even intervals in region0 and region1. This was helped to stop overlapping runs from 2 regions.

We are now trying out putting az functions to aks. 
now each region spins 2 pods and the 2 pods each of them create lock by host name in azure storage for timer trigger. since 2 pods have different hostnames we seeing 2 different locks being created instead of just one lock for one region.

We want all timer triggers in multiple pods in same region to run the timer trigger only one time instead of timertrigger in each pod running in parallel.  Please advise if there is any thing we can do to achieve singleton behavior for a timertrigger running between multiple pods in same region

**Comment by TsuyoshiUshio** [comment]
Hi @krishnasingh1818 Probably, you encounter the same issue as me. Could you try this solution?
https://github.com/Azure/azure-functions-host/issues/7128

**Comment by krishnasingh1818** [comment]
thank you @TsuyoshiUshio your suggested fix works.
