### ISSUE TITLE
Investigate TimerTrigger problems with cron expressions

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-host#7123]
There seems to be some inconsistencies in how cron expressions are handled. Specifically, an expression without seconds works locally, but fails silently when deployed to Azure.

A customer reported an app (#7100) that actually had a some executions with a cron expression missing seconds, but then it stops running after a while. See @anthonychu for a kusto query that shows this problem.

Two recent issues reported with what appears to be the same problem:
#7100
https://github.com/Azure/Azure-Functions/issues/1829

**Comment by mathewc** [comment]
While all our Functions documentation says to use 6 part expressions (including seconds), the extension actually supports 5 part expressions (see code [here](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/9c87af74f90159f8b987c77aa77546f55a62a84e/src/WebJobs.Extensions/Extensions/Timers/Scheduling/CronSchedule.cs#L56)). We count the expression parts and configure `CrontabSchedule.ParseOptions.IncudingSeconds` to true IFF there are 6. So in the context of WebJobs, and when running Azure Functions locally either will work.

The disconnect is that the ScaleController ONLY parses with `IncludeSeconds=true`. This will fail for 5 part expressions meaning an error will be logged and the SC won't be monitoring the schedule. @anthonychu for the cases you were investigating, can you check the SC logs and verify this is what's happening?

As far as a fix, we could simply update SC with the same logic so it supports 5 part as well. I've logged a work item [here](https://msazure.visualstudio.com/One/_workitems/edit/9270306) for that.

**Comment by anthonychu** [comment]
Thanks @mathewc. Not sure how to check the scale controller logs but I pasted a kusto query showing the problem in the Azure DevOps item you created.

**Comment by fabiocav** [comment]
Closing this as the scale controller change has been made.
