### ISSUE TITLE
Design and create endpoints to provide diagnostic events captured

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#7125]
We need to build a service that would allows us to capture diagnostic events recognized by the functions runtime. Diagnostic events can be error conditions that require user actions to mitigate the issue or a warning for a potentially unideal configuration on customers part. The idea is to capture and such events and build a pipeline to bring this to customers attention. This is not meant to be used as an analytical tool to replace application insights or other solution. But is meant to serve as a quick guide to help resolve most common conditions.

**Comment by fabiocav** [comment]
Moving to sprint 96. This will be decomposed into smaller tasks.

**Comment by fabiocav** [comment]
Work currently in PR. Leaving in sprint 97
