### ISSUE TITLE
Timer Trigger trigged on each pod on kubernetes with KEDA.

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-host#7128]
Found this issue.

https://github.com/kedacore/keda/discussions/1508

#### Repro steps

Create a timer trigger and deploy the kuberenetes with min-replica as 2. then configure `AzureWebJobsStorage` to point a Storage Account. 

```
func init --docker-only --csharp
func new   // chose timer trigger
// config local.settings.json 
func kubernetes deploy --name timger-func --registry tsuyoshiushio --min-replicas 2
```

#### Expected behavior

Only one container runs timer trigger. 

#### Actual behavior

Both containers run timer trigger.

#### Known workarounds

Create a single container. 

#### Related information 

The root cause is, the functions host looks at hostname to create a lease blob.
In case of KEDA, the host name is container name.  We need to create a PR for solving this. 

https://github.com/Azure/azure-functions-host/blob/ecaafa21d276f99ed5bfe105e6798bd82320ba66/src/WebJobs.Script/Host/ScriptHostIdProvider.cs#L63

![image](https://user-images.githubusercontent.com/1390976/106946465-fb02c380-66dd-11eb-86e3-ab7427337c9b.png)

![image](https://user-images.githubusercontent.com/1390976/106946484-00f8a480-66de-11eb-835b-cd82575b9f50.png)

**Comment by TsuyoshiUshio** [comment]
It works if you specify `AzureFunctionsWebHost__hostid`. 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=csharp#function-apps-sharing-storage

**Comment by krishnasingh1818** [comment]
> It works if you specify `AzureFunctionsWebHost__hostid`.
> https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=csharp#function-apps-sharing-storage

Thanks. Am not clear what to do to resolve this. Do u mean set that hostid env to same value for all pods in same region? Doest it have any other side effects? Will appinsight logs still show actual host or the one I will override using env var hostid?
