### ISSUE TITLE
Duplicate events using Event Hub trigger

### ISSUE THREAD

**Issue by anwather** [Azure/azure-functions-host#7131]
I'm using an event hub trigger - code is PowerShell receiving resource diagnostic events being sent through. The event hub has 4 partitions and cardinality is set to "one" which has reduced the amount. But still there are duplicate events being sent.

#### Investigative information

Please provide the following:

- Timestamp: 2021-02-05T02:00:13.7686992Z
- Function App version: ~3
- Function App name: Not available for sharing. 
- Function name(s) (as appropriate): insights-logs-appservicehttplogs
- Invocation ID: ef496043-da3a-40d8-86e2-97daff6339df
- Region: Australia Southeast

#### Repro steps

The invocation with the id above - same events were processed at time 2021-02-05T02:00:29.419461Z with invocation id 06cedb9b-8f5b-4bc6-90e5-0662b4083214 

#### Related information 

Provide any related information 

* Programming language used  - PowerShell
* Bindings used
```
{
    "scriptFile": "../run.ps1",
    "bindings": [
        {
            "type": "eventHubTrigger",
            "name": "eventHubMessages",
            "direction": "in",
            "eventHubName": "insights-logs-appservicehttplogs",
            "connection": "EventHubConnectionString",
            "cardinality": "one",
            "consumerGroup": "$Default"
        }
    ]
}
```

**Comment by v-anvari** [comment]
Hi @anwather , I checked the backend logs for both the invocation id's. But, the events are in order when the function has started and completed as expected. "Executed 'Functions.insights-logs-appservicehttplogs' (Succeeded, Id=06cedb9b-8f5b-4bc6-90e5-0662b4083214, Duration=914ms)". Are you saying that the event took place without a trigger or a message being triggered

**Comment by anwather** [comment]
In this case it appears that the same event was processed twice - in 2 separate invocations..

- ef496043-da3a-40d8-86e2-97daff6339df
- 06cedb9b-8f5b-4bc6-90e5-0662b4083214

I'm not sure if you can confirm that these invocations were triggered by the same event hub message?

**Comment by v-anvari** [comment]
Hi @anwather , We checked both the invocation id's but we are unable to fetch the message details. Can you let us know the version of the Event hub extensions used. If it is above 4.x eventhubs extension, there are log entries that show the sequence number of the messages used for that execution. For example.

Trigger Details: PartionId: 0, Offset: 4295012096, EnqueueTimeUtc: 2021-02-10T01:34:10.0550000Z, SequenceNumber: 780, Count: 10

Can you let us know if all your messages are duplicate or is it just certain messages, and how did you trace the duplicates.
