### ISSUE TITLE
Function app runtime moved to 3.x despite FUNCTIONS_EXTENSION_VERSION setting

### ISSUE THREAD

**Issue by RPM1984** [Azure/azure-functions-host#7132]
Hi there,

We recently restarted our .NET Core 2.2 function app, and received this error in the portal:
> Microsoft.Extensions.Configuration: Value cannot be null. (Parameter 'config').

After chatting to Azure support, the issue was the function app host moved to 3.x even though we had this setting:

```
{
   "name": "FUNCTIONS_EXTENSION_VERSION",
   "value": "~2",
   "slotSetting": false
}
```

The fix was to pin to the version the app was on previously:

```
{
   "name": "FUNCTIONS_EXTENSION_VERSION",
   "value": "2.0.14786.0",
   "slotSetting": false
}
```

The expected behavior [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#functions_extension_version) is that the host should only ever move to the _latest_ version of that major release, in this case 2.x. So it shouldn't have moved to a 3.x host.

I also saw [this page](https://github.com/Azure/azure-functions-host/wiki/Platform-upgrade-from-Azure-Functions-runtime-v2-to-v3#opting-out-of-the-upgrade), so maybe i should be using `~2.0` instead of `~2`? (in which case, the first msdocs page is incorrect?)

I was asked to raise an issue here by the Azure Support person. Will pass on this ticket to him for reference.

Thanks!

**Comment by v-anvari** [comment]
Hi @RPM1984 , The [first document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#functions_extension_version) that you are referring to, mentions to use "To pin the app to a specific version, use the full version number (for example, "2.0.12345")."

While using the latest versions, the default runtime would be 3.0. But, in your case you expected it to be 2.0. 
Could you please give us the repro steps of your project, so that we can reproduce the issue and find the cause of it.

**Comment by RPM1984** [comment]
hi @v-anvari , thanks for jumping in! 😃 

to clarify, i'm not trying to pin to a _specific_ version, I'm trying to pin to the _latest_ 2.x version, as per the doc:
> A tilde with major version means use the latest version of that major version (for example, "~2").

So, my expectation is a value of `~2` could result in any host version of 2.x being run, but **not** 3.x.

The repro steps would be:
1. Add a .NET Core 2.2 app
2. Add the value `~2` for `FUNCTIONS_EXTENSION_VERSION`
3. Restart the app

3 is where it broke for me, as Azure allocated me a 3.x host. It's not entirely reprocuble, as i guess it depends on the algorithm for Azure?

Anyway, it seems as though the fix is that the value should be `~2.0`, not `~2`. I tried this, and it worked (haven't been allocated a 3.x since), so i believe the issue is the docs [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#functions_extension_version) need to be updated to match [here](https://github.com/Azure/azure-functions-host/wiki/Platform-upgrade-from-Azure-Functions-runtime-v2-to-v3#opting-out-of-the-upgrade)

**Comment by balag0** [comment]
Hope this helps clarify things

If the FUNCTIONS_EXTENSION_VERSION is set to ~2, it will move to Functions runtime v3 but in v2 compatibility mode. It will target .NET Core 3.1. It will receive patches.
If the FUNCTIONS_EXTENSION_VERSION is set to ~2.0, it will stay on Functions runtime v2. It will target .NET Core 2.2. It will not be patched.
If the FUNCTIONS_EXTENSION_VERSION is not present, it will get the latest major version - as of today that is Functions runtime v3.

**Comment by RPM1984** [comment]
@balag0 

> If the FUNCTIONS_EXTENSION_VERSION is set to ~2, it will move to Functions runtime v3 but in v2 compatibility mode. It will target .NET Core 3.1. It will receive patches.

i thought that's only if `FUNCTIONS_V2_COMPATABILITY_MODE` is set to true?
https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#functions_v2_compatibility_mode

**Comment by v-anvari** [comment]
Hi @RPM1984 , In these cases FUNCTIONS_V2_COMPATABILITY_MODE is set to true by default. It needs to be explicitly set to true only if you come across errors during the upgrades. [https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions#migrating-from-2x-to-3x](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions#migrating-from-2x-to-3x)

You will find more information in the announcement page here : [https://github.com/Azure/app-service-announcements/issues/266](https://github.com/Azure/app-service-announcements/issues/266)

Please feel free to reach back to us in case you have any further queries regarding this issue
