### ISSUE TITLE
Azure Functions does not support DiagnosticListener callbacks when using System.Diagnostics.DiagnosticSource (> 4.7.0)

### ISSUE THREAD

**Issue by utpilla** [Azure/azure-functions-host#7135]
DiagnosticListener callbacks are not called in Function apps when using System.Diagnostics.DiagnoticSource (> 4.7.0)

#### Investigative information
Tried this locally

#### Repro steps
- Clone this repo: https://github.com/utpilla/AzureFunctions-DiagnosticSource/tree/DiagnosticSource_5.0.1 and switch to branch DiagnosticSource_5.0.1 
- Run the AzureFunctions-DiagnosticSource project
- Make an HTTP GET request to http://localhost:7071/api/HttpHandlerDiagnosticListener

#### Expected behavior
Response should be:
```
[
    "System.Net.Http.HttpRequestOut.Start",
    "System.Net.Http.Request",
    "System.Net.Http.HttpRequestOut.Stop",
    "System.Net.Http.Response"
]
```

This is a list of events that are logged by HttpClient when making an outbound Http request

#### Actual behavior
Response is empty

#### Known workarounds
Revert the System.Diagnostics.DiagnosticSource package version to 4.7.0

#### Related information 
* It works correctly with the main branch as it's using System.Diagnostics.DiagnosticSource (= 4.7.0)
* Programming language used: C#
* Links to source: https://github.com/utpilla/AzureFunctions-DiagnosticSource/tree/main

**Comment by fabiocav** [comment]
We need to track the unification change in 4.0.

Tagging @brettsam for validation in v4

**Comment by RohitRanjanMS** [comment]
@utpilla this is working in V4, we can close this issue.
@brettsam @fabiocav FYI

**Comment by ThomsonTan** [comment]
Haven't seen any PR tagged for this issue. Is it working now?

**Comment by RohitRanjanMS** [comment]
Hi @ThomsonTan did this not work for you in V4?

**Comment by cijothomas** [comment]
> Hi @ThomsonTan did this not work for you in V4?

It should work in V4 and Otel 1.3.*. 
A working app is here: https://github.com/cijothomas/FunctionsOpenTelemetry/tree/master/FunctionsOpenTelemetry

**Comment by agr** [comment]
Should it work with non-isolated workers? What I see is that msbuild when building a function deletes the "System.Diagnostics.DiagnoticSource.dll" file (presumably by a [`RemoveRuntimeDependencies`](https://github.com/Azure/azure-functions-host/blob/fba2162ce368859b15350f307eee385eaec76282/tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator/Targets/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets#L24) msbuild task) if it ends up in the output directory, then when the code touches any OpenTelemetry class a `TypeInitializationException` exception is thrown: 

> FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

OpenTelemetry.Api/1.4.0 [depends](https://www.nuget.org/packages/OpenTelemetry.Api/1.4.0#dependencies-body-tab) on that particular version of System.Diagnostics.DiagnosticSource.

Setting `_FunctionsSkipCleanOutput` to `true` (as suggested [here](https://github.com/Azure/azure-functions-host/issues/5894#issuecomment-615832940)) seem to help though.

**Comment by fabiocav** [comment]
@agr 7.0.0 dependencies will not work in Azure Functions 4.0 (in-proc) with the unification rules it has. 

If you need to use 7.0.0, the recommendation is to use the Isolated (out-of-proc) model.

**Comment by fabiocav** [comment]
Closing this as resolved
