### ISSUE TITLE
Shutdown placeholder language worker processes if user specifies appsetting for languageWorkers:runtime:arguments

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#7139]
cc @mhoeger @yojagad 

Host has the ability to shutdown incompatible language worker process here https://github.com/Azure/azure-functions-host/blob/51e7a2ead2327889da27c28681f89e60bd75a46f/src/WebJobs.Script/Workers/Rpc/WebHostRpcWorkerChannelManager.cs#L121

If a user specifies an appsetting to overwrite process startup arguments such as documented here:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan?tabs=portal#memory-usage-considerations

Host should shutdown language worker process that started in placeholder mode.

This solution will work on windows and linux.

@mhoeger - assigning this issue to you since you have most context. Please re-assign as appropriate.

**Comment by mhoeger** [comment]
cc: @anthonychu - this will let you use `languageWorkers:node:arguments` on static web apps!

**Comment by fabiocav** [comment]
Moving to sprint 97 as stretch goal
