### ISSUE TITLE
Diagnostic-Id set in message properties is not automatically populated into system.diagnostics.activity.current.parentid and output eventhub dependency not showing in appinsight

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/azure-functions-host#7150]
#### Is your question related to a specific version? If so, please specify:
I had put this question here but they didnt know solution and closed it. hence posting here as it seems more correct place.
https://github.com/MicrosoftDocs/azure-docs/issues/69890

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#, AzureFunction v3 , .net core 3.1,  hosted in linux in AKS

#### Question
1.  Diagnostic-Id set in message properties is not automatically populated into system.diagnostics.activity.current.parentid when azure service bus trigger function executed in linux or on local machine. 
Things run fine when function are deployed in azure function consumption plan windows.  but recently we moving functions to aks and noting that this value is received as null when sb function triggers to process a message having diagnostic-id set in its message properties.

2. Another issues is from our service bus trigger function after doing some work we send ouput to event hub.  when hosted in azure windows consumption plan it was showing this as dependency in appinsights but after moving functions to aks that dependency is not logged in appinsight.

please advise

**Comment by v-anvari** [comment]
Hi @krishnasingh1818 , Apologies for the delayed response, Could you please explain the issue in detail, what exactly are you trying to do in your functions
