### ISSUE TITLE
The "GenerateFunctionsExtensionsMetadata" task could not be instantiated

### ISSUE THREAD

**Issue by twtb** [Azure/azure-functions-host#7152]
Followed the steps to create a sample Azure function from: https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-your-first-function-visual-studio.
The function runs fine locally (using F5), but when I try to publish it to Azure I get the following exception: 

```
2>The "GenerateFunctionsExtensionsMetadata" task could not be instantiated from "C:\Users\<username>\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.2.1\build\..\tools\net46\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.dll". Could not load file or assembly 'Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator' or one of its dependencies. The system cannot find the file specified.
2>The "GenerateFunctionsExtensionsMetadata" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.
```

The file "Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.dll" does exist on the specified location.

The project contains the following NuGet packages:
`    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.16.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.3" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.2.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />`

Visual Studio version: 16.8.4

What can be done to further investigate this problem?

**Comment by v-anvari** [comment]
Hi @twtb , We require additional details to repro this issue. 

After creating the function app, what are the additional steps that you are following. Can you give us the repro steps in detail, which trigger are you using. Is it possible to provide a test zip file which can produce the same error.

**Comment by v-anvari** [comment]
We see that the error says - " Could not load file or assembly 'Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator' or one of its dependencies". We have identified an issue related to "Microsoft.Extensions.DiagnosticAdapter" with a different scenario. We would require more information of your scenario to resolve
