### ISSUE TITLE
Azure Function Consumption occasional HTTP 502

### ISSUE THREAD

**Issue by robinhultman** [Azure/azure-functions-host#7157]
We have an Azure Function dotnet 3.1 running on a consumption plan. The Function is called from Api Management.
Occasionally we get a HTTP 502 response from the function.

I have gone through the usual troubleshooting steps and I can't find anything in the logs of the function, I only see that there has been a problem in the logs generated by APIM.
During this time the Function did not have high load.
I do not have any invocation id for these requests (since I can only find them in the APIM logs)
There are 12 requests with this error between 2021-02-13T16:38:19 - 2021-02-13T16:43:53.8207378Z for example:

Timestamp: 2021-02-13T16:38:19.6778769Z
Region: west-europe
API Management request id: c2e22e72-ac02-4417-8a56-f765cdc77767

Oddly it seems that there has been a few successful requests during this time.

**Comment by balag0** [comment]
Are you able to share the name of the function app using https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by robinhultman** [comment]
Thanks!
2021-02-15T08:05:55.159 441611bd-2880-4fb2-a7bc-92984652e93e west-europe

**Comment by balag0** [comment]
Looks like one of the worker assigned to the function app had become unhealthy and requests were timing out. The worker couldn't push logs as well. It is not clear what triggered this though.

**Comment by robinhultman** [comment]
Thank you for looking in to this!
There is basically no way for me to avoid this kind of issue except switching to another plan?

**Comment by balag0** [comment]
Switching to another plan might not help completely since the issue was at the worker level and so all skus running on that worker will be impacted. It will be interesting to look at the frequency of this issue as well to see if there is any platform improvement we make to recover the app faster.

**Comment by robinhultman** [comment]
It seems to be happen from time to time but I guess the impact isn't that high after I added retries in API Management.
This issue has more impact on us :)
https://github.com/Azure/azure-functions-host/issues/7116

**Comment by v-bbalaiagar** [comment]
Hi @robinhultman, Apologies for the delayed response, the issue was somehow lost in the trace. Can you tell us if you are still facing this issue.
