### ISSUE TITLE
System.UnauthorizedAccessException when reading Event Log evtx file

### ISSUE THREAD

**Issue by robhurry** [Azure/azure-functions-host#7158]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app, select `Diagnose and solve problems` from the left, and view relevant dashboards before opening your issue.

I am trying to read an exported evtx event log file in an Azure Function. It works when I debug the Azure Function from Visual Studio but fails when published to Azure and executed.
I receive the file content of the event log file as a byte array and then write to a temporary file.
 I then try to create an instance of EventLogReader from the Microsoft.Extensions.Logging.EventLog package.

#### Investigative information

Please provide the following:

- Timestamp: 2021-02-15T14:13:13.537
- Function App version: 
- Function App name: 
- Function name(s) (as appropriate): 
- Invocation ID: 741ce311-c475-4f58-b9f3-f20184729df5
- Region: Norway East

#### Repro steps

Provide the steps required to reproduce the problem:

I am trying to read an exported evtx event log file in an Azure Function. 
I receive the file content as a byte array and then write to a temporary file.
 I then try to create an instance of EventLogReader from the Microsoft.Extensions.Logging.EventLog package.

#### Expected behavior

The instance of the EventLogReader should be created successfully.

#### Actual behavior

Provide a description of the actual behavior observed.

The following exception is thrown:

System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at System.Diagnostics.Eventing.Reader.EventLogException.Throw(Int32 errorCode)
   at System.Diagnostics.Eventing.Reader.NativeWrapper.EvtQuery(EventLogHandle session, String path, String query, Int32 flags)
   at System.Diagnostics.Eventing.Reader.EventLogReader..ctor(EventLogQuery eventQuery, EventBookmark bookmark)

#### Known workarounds

If I run the Azure Function from Visual Studio in debug mode it works successfully but when published to Azure it gives the error.

#### Related information 

Provide any related information 

Azure Function
C#
.net core 3.1
Microsoft.Extensions.Logging.EventLog package.

<details>
<summary>Source</summary>

```csharp
         
            log.LogInformation("Creating temp file...");
            string tempfile = Path.GetTempFileName();
            string fileout = Path.ChangeExtension(tempfile, ".evtx");
            File.WriteAllBytes(fileout, eventLogData);
            log.LogInformation("Written temp file: "+ fileout);
      
            var eventLog = new EventLogReader(fileout, PathType.FilePath);
            log.LogInformation("Reading event log...");
</details>

**Comment by arpitadessai** [comment]
Hello, 
Any update on this issue? I am seeing the same behavior.

**Comment by robhurry** [comment]
@arpitadessai  Unfortunately I never managed to get it to work using Microsoft.Extensions.Logging.EventLog so I ended up needing to use this project:
https://github.com/EricZimmerman/evtx
I was then able to read the contents of the file manually into a byte array and load it as a stream.

**Comment by v-anvari** [comment]
Hi @robhurry , Checked this internally to understand if reading for evtx file has any known issues. As far as the team knowns, there are no known issues. It could  be because the file is not being read properly or as expected. To understand the behavior, we would need to reproduce the issue. Let us know if you are still facing this issue. Then we would require the latest Function App details during the time of error. This will help us check the logs to understand the errors
