### ISSUE TITLE
"Dynamic pricing tier is not allowed in this resource group"

### ISSUE THREAD

**Issue by scottxrobertson** [Azure/azure-functions-host#7163]
Hi,

I am attempting to deploy a function app to a new, and empty, resource group. I am intermittently experiencing the issue mentioned in this comment:

https://github.com/Azure/azure-functions-host/issues/851#issuecomment-258767647

I am using nearly the same ARM template, deploying to a new resource group with no existing "regular" Web Apps (no resources at all).

So far this error has happened 2 out of 6 times I have attempted to deploy to a new resource group.

I have used the same template previously dozens of times without any issues, so potentially a bug has been introduced?

Complete ARM template below:

```json
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "functionAppName": {
      "type": "string",
      "metadata": {
        "description": "The name of the function app that you wish to create."
      }
    },
    "appServicePlanName": {
      "type": "string",
      "metadata": {
        "description": "The name of the App service plan to host this app."
      }
    },
    "applicationInsightsName": {
      "type": "string",
      "metadata": {
        "description": "The name of the Application Insights for this app."
      }
    },
    "storageAccountName": {
      "type": "string",
      "metadata": {
        "description": "The name of your storage account"
      }
    },
    "functionAppPackageUrl": {
      "type": "string",
      "metadata": {
        "description": "The URL of the ZIP of the code for the function app (set to '1' to do deployment as a separate process)"
      },
      "defaultValue": "1"
    }
  },
  "variables": {},
  "resources": [
    {
      "type": "Microsoft.Web/serverfarms",
      "apiVersion": "2015-04-01",
      "name": "[parameters('appServicePlanName')]",
      "location": "[resourceGroup().location]",
      "properties": {
        "name": "[parameters('appServicePlanName')]",
        "computeMode": "Dynamic",
        "sku": "Dynamic"
      }
    },
    {
      "apiVersion": "2015-05-01",
      "name": "[parameters('applicationInsightsName')]",
      "type": "Microsoft.Insights/components",
      "kind": "web",
      "location": "[resourceGroup().location]",
      "tags": {
        "[concat('hidden-link:', resourceGroup().id, '/providers/Microsoft.Web/sites/', parameters('functionAppName'))]": "Resource"
      },
      "properties": {
        "Application_Type": "web",
        "ApplicationId": "[parameters('functionAppName')]"
      }
    },
    {
      "apiVersion": "2016-03-01",
      "type": "Microsoft.Web/sites",
      "name": "[parameters('functionAppName')]",
      "location": "[resourceGroup().location]",
      "kind": "functionapp",
      "dependsOn": [
        "[resourceId('Microsoft.Web/serverfarms', parameters('appServicePlanName'))]",
        "[resourceId('Microsoft.Insights/components', parameters('applicationInsightsName'))]"
      ],
      "properties": {
        "serverFarmId": "[resourceId('Microsoft.Web/serverfarms', parameters('appServicePlanName'))]",
        "httpsOnly": true,
        "siteConfig": {
          "appSettings": [
            {
              "name": "FUNCTIONS_WORKER_RUNTIME",
              "value": "dotnet"
            },
            {
              "name": "FUNCTIONS_EXTENSION_VERSION",
              "value": "~3"
            },
            {
              "name": "AzureWebJobsStorage",
              "value": "[concat('DefaultEndpointsProtocol=https;AccountName=', parameters('storageAccountName'), ';AccountKey=', listkeys(resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccountName')), providers('Microsoft.Storage', 'storageAccounts').apiVersions[0]).keys[0].value)]"
            },
            {
              "name": "AzureWebJobsDashboard",
              "value": "[concat('DefaultEndpointsProtocol=https;AccountName=', parameters('storageAccountName'), ';AccountKey=', listkeys(resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccountName')), providers('Microsoft.Storage', 'storageAccounts').apiVersions[0]).keys[0].value)]"
            },
            {
              "name": "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING",
              "value": "[concat('DefaultEndpointsProtocol=https;AccountName=', parameters('storageAccountName'), ';AccountKey=', listkeys(resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccountName')), providers('Microsoft.Storage', 'storageAccounts').apiVersions[0]).keys[0].value)]"
            },
            {
              "name": "WEBSITE_CONTENTSHARE",
              "value": "[toLower(parameters('functionAppName'))]"
            },
            {
              "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
              "value": "[reference(resourceId('microsoft.insights/components/', parameters('applicationInsightsName')), '2015-05-01').InstrumentationKey]"
            },
            {
              "name": "WEBSITE_RUN_FROM_PACKAGE",
              "value": "[parameters('functionAppPackageUrl')]"
            },
            {
              "name": "AzureWebJobsSecretStorageType",
              "value": "Files"
            }
          ]
        }
      }
    }
  ],
  "outputs": {
    "functionAppName": {
      "type": "string",
      "value": "[parameters('functionAppName')]"
    }
  }
}
```

**Comment by v-bbalaiagar** [comment]
Hi @scottxrobertson, This can happen in the following situation:

1) You're creating the Function App in an existing resource group
2) This resource group already contains regular (i.e. non-Dynamic or Premium) Web Apps in the same region that you're trying 
    to create the Function App. This can even occur if you are creating a Azure Functions Premium Plan in a resource group that 
    has an App Service Premium Plan of the same OS.
3) The scale unit that those non-Dynamic or Premium resources are in does not yet support this SKU
4) You are attempting to create a Linux Consumption app in a resource group with any other app service plan type.

Related Information:
https://github.com/Azure/Azure-Functions/wiki/Creating-Function-Apps-in-an-existing-Resource-Group
[azure-functions-host/issues/6014](https://github.com/Azure/azure-functions-host/issues/6014)

**Comment by scottxrobertson** [comment]
Thanks for the reply.

I don't believe the situation you are describing applies in this case.

I am creating a new resource group, then running the ARM template above against that empty resource group. There are no  existing resources at all, let alone any Web Apps or App Services.

The more concerning part is that this issue is intermittent. Sometimes I can create a resource group, run the ARM template, and it works. Other times I create a resource group, run the ARM template and it fails with the above error. If it does fail, running the same ARM template against the same resource group a second time seems to work.

Regardless, see below for my responses to your points:

> * You're creating the Function App in an existing resource group
**Of course, I think this is a given :)**

> * This resource group already contains regular (i.e. non-Dynamic or Premium) Web Apps in the same region that you're trying
>   to create the Function App. This can even occur if you are creating a Azure Functions Premium Plan in a resource group that
>   has an App Service Premium Plan of the same OS.
**The resource group was completely empty. There were no resources at all, let alone any Web Apps or App Services.**

> * The scale unit that those non-Dynamic or Premium resources are in does not yet support this SKU
**N/A - there were no other resources**

> * You are attempting to create a Linux Consumption app in a resource group with any other app service plan type.
**N/A - there were no other resources**

**Comment by balag0** [comment]
@scottxrobertson Could you provide the correlation id , timestamp , region or any other information that we can use to locate the request from our logs?

**Comment by scottxrobertson** [comment]
Hi @balag0 ,

See below for the details requested for one of the failed deployments:

- **Correlation ID**: c644bd50-ac6f-4ef6-b6c7-25830568c38b
- **Start time**: 2/18/2021, 10:33:32 AM
- **Region**: Australia East

**Comment by balag0** [comment]
Thanks. It looks like one of the scale units in Aus East region is not configured to allow consumption function workloads, so when a app lands on that scale unit it will be blocked by that exception. I am checking if we can enable consumption feature on the scale unit. In the mean time retrying should work since other scale units on the region are able to accept functions workloads.

**Comment by scottxrobertson** [comment]
Thanks @balag0 - please keep me posted on when this is resolved.

**Comment by balag0** [comment]
@scottxrobertson 
The config has been updated and you shouldn't see these errors any more. 
Please reactivate if you can still repro this.
