### ISSUE TITLE
Missing method exception when creating SignalR client (only happens within Azure Function)

### ISSUE THREAD

**Issue by kirk-marple** [Azure/azure-functions-host#7177]
I'm stumped on this one.  I'm trying to create a connection to our SignalR hub, from within an Azure Function (C#, .NET Core 3.1).

This had been working, and appears to now have a package conflict, because it can't find the "get_Transport" method on HttpConnection.

I've confirmed that we're using 3.1.12 of the SignalR client package, and even disassembled that, and can see the get_Transport method.

I'm guessing that, when running in the latest Function host, it's loading a different version of HttpConnection?

#### Investigative information

Please provide the following:

- Timestamp: 2/20/2021, 9:16:44 PM (PDT)
- Function App version: v3
- Function App name: unstruk-knowledge-dev-functions
- Function name(s) EntityEvent
- Invocation ID: n/a (not sure where to find this)
- Region: West US 2

#### Repro steps

Within an Azure Function (C#) built with netcoreapp3.1, we no longer can use the SignalR client to connect to an hub.

This same code works properly from within an xUnit test assembly, but not within the Azure Function.

#### Expected behavior

Attempting to connect to SignalR hub, from within Azure Function.

#### Actual behavior

Failing to connect to SignalR client; throwing missing method exception.

#### Known workarounds

None

#### Related information 

```
        <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="3.1.12" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson" Version="3.1.12" />
        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
        
```

From the Azure Function request:

SDK version: dotnetc:2.16.0-18277
Operation ID: 36fce3c04dba5547a1b0cc00add7118b
Request ID: 71ea1886ebd62849

<details>
<summary>Exception</summary>

```
Method 'get_Transport' in type 'Microsoft.AspNetCore.Http.Connections.Client.HttpConnection' from assembly 'Microsoft.AspNetCore.Http.Connections.Client, Version=3.1.12.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at Unstruk.Frameworks.Integrations.Services.SignalRIntegrationService.<>c__DisplayClass5_0.<<CreateSignalRClientAsync>b__5>d.MoveNext()
</details>

**Comment by v-bbalaiagar** [comment]
Hi @kirk-marple, We would like to clone the scenario that you are trying. Could you please provide us the repro steps.

**Comment by kirk-marple** [comment]
Sure, let me put together a sample solution, and get you a simpler repro.
