### ISSUE TITLE
Assembly.GetCallingAssembly() not working correctly on linux

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/azure-functions-host#7178]
#### Is your question related to a specific version? If so, please specify:
azfunc v3

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
c#

#### Question
Assembly.GetCallingAssembly() not working correctly on linux. we have 2 az functions one deployed on aks and works fine but other gives wrong Assembly.GetCallingAssembly() and always points to Microsoft.Azure.WebJobs.Script.WebHost

please advise if there is another way to get the calling assembly.

**Comment by v-bbalaiagar** [comment]
Hi @krishnasingh1818, We would like to have more insights on the scenario to understand it better. Can you please give us more details regarding where you are making that call. where that API is being called and consumed.
