### ISSUE TITLE
Azure Durable function concurrency issue

### ISSUE THREAD

**Issue by siddhant777** [Azure/azure-functions-host#7180]
#### Is your question related to a specific version? If so, please specify:
Not version specific but observed in Function runtime version ~3
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
Python
#### Question
Azure Durable Function handles only one HTTP request at a time. When another request is made, it puts the new request in PENDING state and does not start it unless previous one completes. How can concurrency be achieved in this situation?

**Comment by v-bbalaiagar** [comment]
Hi @siddhant777, Apologies for the delayed response, Can you please go through the issue here which addresses similar scenario-
https://github.com/Azure/azure-functions-durable-extension/issues/1020

Please check and let us know if this helps.
