### ISSUE TITLE
Upload a same single blob parallelly into two different containers which resides in two different storage account 

### ISSUE THREAD

**Issue by DVGY** [Azure/azure-functions-host#7181]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
Node js 12
#### Question

What problem was encountered?

I want to upload file parallelly in two containers each of are in different storage account.

Ex: StorageAccount1: container_xyz
StorageAccount2: container_abc

Steps to reproduce the issue?
Here is what my code looks like

// index.js

```
module.exports = async function (context, req) {
  const UserID = "";
  let rawDataQuery = "";
  let rawData = "";

  try {
  // Do some task and store data in buffer

 context.bindings.myReportFile = buffer;


  }
 catch(err){
 }
```
// function.json

```
{
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": ["get"],
      "webHookType": "genericJson",
      "route": "reports/{id:guid}"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    },
    {
      "name": "myReportFile",
      "direction": "out",
      "type": "blob",
      "path": "reports/{reportInitialNameFormat}_{reportID}.{reportExt}",
      "connection": "XYZ_STORAGE"
    },
   
  ]
}
```
The above code uploads my file directly to reports container which resides at storage account (Location/Region 1)

If I add a line after the `context.bindings.myReportFile = buffer`; , i.e
`context.bindings.myReportFileSecond = buffer`; and add following json in` function.json`

```
{
      "name": "myReportFileSecond ",
      "direction": "out",
      "type": "blob",
      "path": "reports/{reportInitialNameFormat}_{reportID}.{reportExt}",
      "connection": "ABC_STORAGE"
    }
```
Will it upload the both blob file parallelly ? or It will upload sequentially.?
I am interested to in knowing how to upload a same blob parallelly into two different container, each container resides in two different storage account.

**Comment by v-anvari** [comment]
Hi @DVGY , Apologies for the delayed response. We can add the blobs to two different containers residing in 2 different containers by adding 2 storage output bindings. 

Here is a small sample code that I have tried with blob trigger and 2 blob output bindings. 

C sharp:

public  class Function1
    {
        [FunctionName("Function1")]
        public static void Run([BlobTrigger("samples-workitems/{name}", Connection = "AzureWebJobsStorage")]string myBlob,
            [Blob("test/{name}", FileAccess.Write, Connection = "AzureWebJobsStorage")] Stream outBlob1,
            [Blob("test/{name}", FileAccess.Write, Connection = "AzureWebJobsStorage1")] Stream outBlob2, ILogger log)

        {
            log.LogInformation($"C# Blob trigger function Processed blob");
            outBlob1.Write(Encoding.ASCII.GetBytes(myBlob));
            outBlob2.Write(Encoding.ASCII.GetBytes(myBlob));
        }
    }

I have 2 containers (samples-workitems, test )in 1 storage account (AzureWebJobsStorage) for trigger input and blob output, and second output container (test) in another storage account (AzureWebJobsStorage1). You can give multiple connection strings and add the connections respectively. The blobs will be added at the same time as soon as a message is read. 

Here are few examples for output blob bindings using different languages. https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/azure-functions/functions-bindings-storage-blob-output.md

Do let us know if this information is helpful.

**Comment by v-anvari** [comment]
Closing this issue as the required information is provided, please feel free to reach back to us or re-open this issue in case of any queries.
