### ISSUE TITLE
Add Inflight invocations completed status on the host

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#7188]
This is a follow up for DrainMode feature

Calling drain mode API allows for a graceful shutdown of the host to complete inflight invocations and stops listening for new events from trigger sources.

To handle this in LinuxConsumption more effectively, host needs to expose an API that platform can poll to figure out if all the inflight invocations are completed. Without this information a host instance needs to stay in drain mode for a specified amount of time - even though all the inflight invocations completed.  This leads to capacity crunch.

cc @fabiocav @soninaren @divyagandhisethi @balag0

**Comment by pragnagopa** [comment]
@divyagandhisethi - Can DataRole determine state of inflight invocations by looking at functionExecution status?

**Comment by soninaren** [comment]
We do provide customers with cancellation tokens to all functions including inflight and new invocations.  Any new invocations that get started after drain mode has been activated should be handled by the customer. Functions already inflight are provided ample time for them to complete execution.

**Comment by soninaren** [comment]
Also the proposed API may not be helpful because the customer could pre-fetch a 1000 messages. Each can take up to 10 minute to finish execution and user could also configure the function app to process one function at a time.

**Comment by pragnagopa** [comment]
> Functions already inflight are provided ample time for them to complete execution.

Can you please expand on what ample time means? My understanding is there is a fixed grace period that we allow for drain mode.

> Also the proposed API may not be helpful because the customer could pre-fetch a 1000 messages. Each can take up to 10 minute to finish execution and user could also configure the function app to process one function at a time.

Ask here is for platform to be able to detect and optimize cases where all invocations after drain mode is called complete in < 10mins . This will ensure a host instance (container) is not waiting for the whole 10mins before being teared down.

**Comment by soninaren** [comment]
> Can you please expand on what ample time means? My understanding is there is a fixed grace period that we allow for drain mode.

By ample time I meant `time >= default timeout period` for the respective sku. So for consumption it would be >=10 mins
 
> Ask here is for platform to be able to detect and optimize cases where all invocations after drain mode is called complete in < 10mins . This will ensure a host instance (container) is not waiting for the whole 10mins before being teared down.

The ask makes sense and has clear advantages. We would have to investigate this further to understand performance impact as this would require keeping track of all invocations across all extensions.

**Comment by soninaren** [comment]
tagging @mathewc as he is working on a design that will likely provide this information.

**Comment by pragnagopa** [comment]
cc @alrod @AnatoliB fyi
