### ISSUE TITLE
Azure Service Health Alerts when custom runtimes are decommissioned

### ISSUE THREAD

**Issue by willvelida** [Azure/azure-functions-host#7189]
#### What problem would the feature you're requesting solve? Please describe.

In our Azure Function applications, we have opted to pin a custom runtime. From time to time, our Functions will fail to invoke due to specific versions of the runtime being removed or simply not working. To avoid any downtime on our applications, we have created a PowerShell script that allows us to roll back to a stable version. But we usually have to do this after the fact, as removal of certain runtimes are hidden away on a GitHub issue page. This isn't good enough .

#### Describe the solution you'd like

We need greater transparency on when certain versions of the Azure Functions Runtime are being removed. We'd like to be notified of removals via Azure Service Health. That way, we can have these alerts delivered to us, instead of us having to tracking the App Service Announcements issues page: https://github.com/Azure/app-service-announcements/issues

#### Describe alternatives you've considered

We can monitor the issues page, but it is a bit tedious to keep having to do manual checks to ensure that any custom runtime that we use doesn't cause breaking changes in our application.

**Comment by v-anvari** [comment]
Hi @willvelida , Apologies for the delayed response. Thank you for your feedback! We will investigate this scenario and update you with the possibilities.

**Comment by pragnagopa** [comment]
Thanks @willvelida for the recommendation. Tagging @amamounelsayed and @anirudhgarg to incorporate this into functions runtime release process.

**Comment by fabiocav** [comment]
@willvelida the request makes sense, but I would like to better understand your scenario:
 - Why are you pinning the runtime version?
 - Are you seeing impact with every version update?
