### ISSUE TITLE
Microsoft.Extensions.* - 3.1.10 usage by host however Keyvault config extension 3.1.10 is deprecated

### ISSUE THREAD

**Issue by VaclavK** [Azure/azure-functions-host#7192]
#### Is your question related to a specific version? If so, please specify:

I am on function host 3.20 ( I believe is the latest version available)

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 

c#

#### Question

we use KeyVault configuration extension package - due to earlier versions now being deprecated we had to upgrade to 3.1.12
however it also pushes up its dependencies e.g. configuration abstractions to 3.1.12

host is linked to 3.1.10

debugging we get e.g.

		configuration	error CS1705: Assembly 'XXX' with identity 'XXX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.Extensions.Configuration.Abstractions, Version=3.1.12.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.Configuration.Abstractions' with identity 'Microsoft.Extensions.Configuration.Abstractions, Version=3.1.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'	

is there a plan to release new host linked to latest 3.X release of microsoft.extensions (at the moment that is 3.1.12)

**Comment by v-bbalaiagar** [comment]
Hi @VaclavK, Apologies for the delayed response, checking internally on this issue. We will update you with any information found.

**Comment by v-anvari** [comment]
Hi @VaclavK , Apologies for the delay, The latest Azure Functions release is [3.1.3](https://github.com/Azure/azure-functions-host/releases/tag/v3.1.3)

The Latest Microsoft.Extensions.Configuration.AzureKeyVault packages is[ 3.1.17 ](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureKeyVault/) which is dependent on the latest Microsoft.Azure.KeyVault (>= 2.3.2) package.

The dependencies are updated in the latest releases. Closing this issue as the required information is provided, please feel free to reach back to us or re-open this issue in case of any queries.
