### ISSUE TITLE
It's closed, but it shouldn't be.

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-functions-host#7193]
https://github.com/Azure/azure-functions-host/issues/6542#issuecomment-778294039

Any news on this?

**Comment by v-bbalaiagar** [comment]
Hi @jackbond, Closing this issue as duplicate, Here is a [tracking issue](https://github.com/Azure/azure-functions-host/issues/6542) which is being addressed and worked upon on a similar scenario, Please find the space for further updates.
