### ISSUE TITLE
Function proxy very slow in handling gzipped backend response

### ISSUE THREAD

**Issue by ulfandersson** [Azure/azure-functions-host#7197]
#### Description

We are encountering unreasonable large response time overhead (200-300 ms from backend response to proxy response) when using azure function proxy and the backend resource is a few houndred kb compressed data. Using API management instead does NOT provide this overhead.

#### Investigative information

- Timestamp: 2021-03-02T13:43:48.8999321Z
- Function App version: 3.0.15371.0
- Invocation ID: Not sure if it exists for a proxy call?
- Region: North Europe

#### Repro steps

1. Create an Azure Function with a function proxy that has a backend url of any semi-large file which will be sent compressed (example: http://www.json-generator.com/api/json/get/cpeYXXlhKa?indent=2)
2. Call GET on the created proxy url with header "Proxy-Trace-Enabled" set to "true" and fetch the log file from the file storage associated with the function.
3. Create an api management service resource with an api endpoint with the same backend url as in step 1.
4. Call GET on the api management api endpoint with "Ocp-Apim-Trace: True" and fetch the log file from the blob url in the response header.

(Note that the request and/or response is not modified in any way in this scenario)

#### Expected behavior

Neither the Azure function proxy nor the api management service is expected to add any significant overhead when proxying the data.

#### Actual behavior

With Azure function proxy we observe a significant delay of about 200-300 ms which is not observed for api management. This overhead is not present when the backend data is not compressed.
Observering the logs we can se that the whole delay seems to come between "backend->decompressor" and "outbound->transfer-response".
Excerpt from [apim_example_log.log](https://github.com/Azure/azure-functions-host/files/6069986/apim_example_log.log) (no delay):
```json
...
     {
        "source": "decompressor",
        "timestamp": "2021-03-02T13:39:59.9439622Z",
        "elapsed": "00:00:00.8758839",
        "data": "Content-Encoding header with value `gzip` detected in message headers. Content re-compression may require to correctly apply content modification policies."
      }
    ],
    "outbound": [
      {
        "source": "transfer-response",
        "timestamp": "2021-03-02T13:39:59.9439622Z",
        "elapsed": "00:00:00.8760108",
        "data": { "message": "Response headers have been sent to the caller." }
      },
```
Excerpt from [azure_function_proxy_example.log](https://github.com/Azure/azure-functions-host/files/6069987/azure_function_proxy_example.log) (almost 300 ms delay here):
```json
...
      {
        "source": "decompressor",
        "timestamp": "2021-03-02T13:43:49.4464496Z",
        "elapsed": "00:00:00.5466427",
        "data": "Content-Encoding header with value `gzip` detected in message headers. Content re-compression may require to correctly apply content modification policies."
      }
    ],
    "outbound": [
      {
        "source": "transfer-response",
        "timestamp": "2021-03-02T13:43:49.7445719Z",
        "elapsed": "00:00:00.8447708",
        "data": {
          "message": "Response headers have been sent to the caller."
        }
      },
```
_(sensitive request headers removed from the logs)_

#### Known workarounds

Fetching without compression from the backend url seems to give similar performance between apim and azure function proxy.

**Comment by v-anvari** [comment]
Hi @ulfandersson , The Azure function Proxies has a lot of limitations unlike for APIM. The Gzipped compressions are not supported in Linux and has a lot of backend limitations for Windows. The response took lot of time, because the team was deciding the proxy requirements here after. 

Azure Functions Proxies will no longer be supported in 4.x. You are recommended to use Azure API Management.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=csharp%2Cv4#breaking-changes-between-3x-and-4x
