### ISSUE TITLE
[Linux] Storage resiliency for apps running of Azure File share

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-host#7199]
Storage might become unavailable post specialization, Need a way to identify and mitigate

**Comment by fabiocav** [comment]
@balag0 do you have concrete action items we should be tracking as issues?

**Comment by balag0** [comment]
I think we are not ready to finalize details on this yet. There is some work in progress currently that changes the storage interaction pattern, so will have to revisit this in a few months.

**Comment by balag0** [comment]
I have also moved this to the internal taskboard for now. There may or may not be changes needed in this repo.
