### ISSUE TITLE
Azure functions - Log output threshold exceeded 

### ISSUE THREAD

**Issue by jaganpt** [Azure/azure-functions-host#7201]
I created a azure function app v3 with a timer function which logs large text. 
I got the below threshold exceeded issue. Please let me know how to include large log output in azure functions.

App service plan of the function app : **EP1**

**Error:**
----------------------
2021-03-03T16:31:04.713 [Information] [00000000000000001274] ##########Log some sample text. Counter#636###################Log output threshold exceeded.

Sample Code to reproduce the issue:
-----------------------------------------
public static class TestFunction
    {
        [FunctionName("TestFunction")]
        public static void Run([TimerTrigger("0 0 * * * *")] TimerInfo myTimer, ILogger log)
        {
            LogHelper.Init(log);
            try
            {
                LogHelper.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");

                for (int i= 0;i < 25000; i++){

                    LogHelper.LogInformation($"##########Log some sample text. Counter#{i}###################");
                    LogHelper.LogInformation($"This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.");
                }
               
            }
            catch (Exception ex)
            {
                LogHelper.LogError($"Something went wrong. {ex.Message}", ex);
            }
        }
    }

**Comment by v-anvari** [comment]
Hi @jaganpt , I am trying to reproduce, but I am getting errors in the code itself. Can I know all the namespaces that you are using and the repro steps. Are you trying it in visual studio or portal.

**Comment by jaganpt** [comment]
Hi @v-anvari ,
Here is the code with namespaces. I ran in portal and getting log threshold issue.
Logs are not completely logging as mentioned below.

2021-03-03T16:31:04.713 [Information] [00000000000000001274] ##########Log some sample text. Counter#636###################Log output threshold exceeded.


using System;
using FunctionAppLogsThresholdPOC.Helper;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.Extensions.Logging;

namespace FunctionAppLogsThresholdPOC
{
    public static class TestFunction
    {
        [FunctionName("TestFunction")]
        public static void Run([TimerTrigger("0 0 * * * *"), Disable("true")] TimerInfo myTimer, ILogger log)
        {
            LogHelper.Init(log);
            try
            {
                LogHelper.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");

                for (int i= 0;i < 25000; i++){

                    LogHelper.LogInformation($"##########Log some sample text. Counter#{i}###################");
                    LogHelper.LogInformation($"This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.");
                }
               
            }
            catch (Exception ex)
            {
                LogHelper.LogError($"Something went wrong. {ex.Message}", ex);
            }
        }
    }
}

**Comment by jaganpt** [comment]
Hi @v-anvari ,

Also please add the below LogHelper class to the solution. Thanks.
Create Helper folder and add the LogHelper.cs class.


using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Text;

namespace FunctionAppLogsThresholdPOC.Helper
{
    internal static class LogHelper
    {
        private static ulong counter { get; set; } = 0;
        private static ILogger thisLogger { get; set; }
        private static object counterLock { get; set; } = new object();

        static private ulong getIncreasedCounter()
        {
            lock (counterLock)
                counter++;

            return counter;
        }

        private static string formatMessage(string message)
        {
            var increasedCounterNumer = getIncreasedCounter();
            return $"[{increasedCounterNumer:00000000000000000000}] {message}";
        }

        public static void Init(ILogger logger)
        {
            thisLogger = logger;
        }

        public static void LogDebug(string message)
        {
            var formattedMessage = formatMessage(message);
            thisLogger.LogInformation(formattedMessage);
        }

        public static void LogInformation(string message)
        {
            var formattedMessage = formatMessage(message);
            thisLogger.LogInformation(formattedMessage);
        }

        public static void LogWarning(string message)
        {
            var formattedMessage = formatMessage(message);
            thisLogger.LogWarning(formattedMessage);
        }

        public static void LogError(string message)
        {
            var formattedMessage = formatMessage(message);
            thisLogger.LogError(formattedMessage);
        }

        public static void LogError(Exception ex)
        {
            LogError(ex.Message);
            if (ex.InnerException != null)
                LogError(ex.InnerException);
        }

        public static void LogError(string message, Exception ex)
        {
            LogError(message);
            LogError(ex);
        }

    }
}

**Comment by v-anvari** [comment]
Hi @jaganpt , Thankyou for the detailed repro, I have deployed the project. I will further investigate and check the logs for 24 hours and reach back to you

**Comment by v-anvari** [comment]
Hi @jaganpt , I haven't received any error running the project locally or in portal. Can you give me the details of the error that you are seeing, are you seeing the error in Application insights or monitor logs?

![image](https://user-images.githubusercontent.com/66122429/111137945-65dccf80-85a5-11eb-9717-0a5137198a2f.png)

**Comment by jaganpt** [comment]
Hi @v-anvari ,
Please check the logs in console. Logs are truncated and you can find the below log output threshold exceeded message as shown below.
Please let me know if you need any further details. Thanks.

2021-03-03T16:31:04.713 [Information] [00000000000000001274] ##########Log some sample text. Counter#636###################Log output threshold exceeded.

**Comment by v-anvari** [comment]
Hi @jaganpt , Below is my error log output and there are I don't find any errors in last 4 days . Can I have the details of your function App name, region in which it is deployed and also the invocation id of the error, so that I can check the backend logs to understand the error from backend logs
![image](https://user-images.githubusercontent.com/66122429/111171111-a438b580-85ca-11eb-9a17-3b9d324fda45.png)

**Comment by jaganpt** [comment]
Hi @v-anvari ,
Can you please try by increasing the for loop count and sample text as shown below. Please find the below snap shot where the logs has been truncated and  log output threshold exceeded. Here logs truncated at counter#23021. I will share you the requested details soon. Thanks.

for (int i= 0;i < 250000; i++)
{
 LogHelper.LogInformation($"##########Log some sample text. Counter#{i}###################");
 LogHelper.LogInformation($"This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.This is for testing.");

}

Error screen shot:

![image](https://user-images.githubusercontent.com/78982760/111182430-3337d480-85af-11eb-8a0d-0846c9f8aa01.png)

**Comment by v-anvari** [comment]
Hi @jaganpt , I have deployed another App with more logs like suggested. I shall observe for 24 hours and update you the results.

**Comment by v-anvari** [comment]
Hi @jaganpt , I have increased the count like you suggested and the log output, but there are no errors. Can we have your Function App details to check the backend logs

![image](https://user-images.githubusercontent.com/66122429/111444148-1080f980-8730-11eb-81ae-4f1862ac3244.png)

**Comment by jaganpt** [comment]
Hi @v-anvari ,

I have shared the function app details to your (v-anvari@microsoft.com) email. Please check and let me know for any further details. Thanks.

**Comment by v-anvari** [comment]
Hi @jaganpt , I checked the backend logs and also tried to reproduce the issue, but I don't see any error related to the above. If you are seeing this error in your live metrics logs in your function App, then it is because the live logs do not have the capacity to show more number of logs, and it also depends on your network on how many messages can be processed at a time. 

We would like to know if the executions are failing because of this message, The best way to check the failures is through application insights [Diagnose exceptions and failures ](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-exceptions#:~:text=%20Diagnose%20exceptions%20in%20your%20web%20apps%20with,to%20send...%205%20Next%20steps.%20%20More). I do see other timeout exceptions. Can you check the logs in app insights and let me know if you are able to troubleshoot the errors from your insights

**Comment by jaganpt** [comment]
Hi @v-anvari,
The logs are missing in application insights when threshold issue occurs.
We will share you the further details to your (v-anvari@microsoft.com) email. 
Thank you.

**Comment by jaganpt** [comment]
Hi @v-anvari ,
We have shared the details to your (v-anvari@microsoft.com) email. 
Please check and let us know for any further details needed.
Thank you.

**Comment by jaganpt** [comment]
Hi @v-anvari ,

We are still facing the log threshold issues. Please let me know if you need any further details to analyze the issue.
We have already shared the details to your (v-anvari@microsoft.com) email.

Thank you.

**Comment by v-anvari** [comment]
Hi @jaganpt , Apologies for the delayed response. I have got the mail from Thomas. If the logs are missing from live metrics, it is expected due to the network concerns. We are unable to reproduce this issue, but we have understood that the logs are missing from application insights. Checking this internally for further investigation. 

Function invocation id for Function App reference: 46d02b50-f882-4a87-ae25-a772b4310475
Region- West Europe

**Comment by v-anvari** [comment]
Hi @jaganpt , I have checked the logs in Applens, but the function App running status says its "Stopped". Can you tell us if the function App is shut down?
What is the latest timestamp of the error.

**Comment by jaganpt** [comment]
Hi @v-anvari,

I think you are referring to dev function app. Please check Thomas email for the live function app details. Thanks.

**Comment by v-anvari** [comment]
Hi @jaganpt , Yes I am talking about the one which Thomas shared. We need to check why the logs are missing from Application insights. Are you still facing this scenario, if yes, Can you give us the recent invocation id , time stamp and region of a working function app? 

Since the dev is stopped, it doesn't give us the metrics earlier to 30 days

**Comment by jaganpt** [comment]
Hi @v-anvari ,

I have shared the requested details  to your (v-anvari@microsoft.com) email. 
Please check and let me know if you need any further details. 
Yes, we are still facing the issues.  Thanks

**Comment by v-anvari** [comment]
Hi @jaganpt , Thank you, reaching out to you on mail

**Comment by v-anvari** [comment]
Hi @jaganpt , I have sent out a mail to you, did you get a chance to check the settings. 

I see that the default sampling settings is enabled in your Function App. This could cause missing execution logs from your monitor logs.  Please look at the guidance for more information : 
[Monitor Azure Functions | Microsoft Docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#configure-sampling)

**Comment by jaganpt** [comment]
Hi @v-anvari ,
Thanks for your reply.
We will check the sampling settings and reach out to you for any queries. Thanks.

**Comment by v-anvari** [comment]
As discussed in mail, please find the file 

[7201asptest.zip](https://github.com/Azure/azure-functions-host/files/6413749/7201asptest.zip)

**Comment by v-anvari** [comment]
Triaging this issue as it requires further investigation. User unable to see any of the monitor logs. Checked the Application settings, everything looks fine. No errors found in the backend.

**Comment by v-anvari** [comment]
Hi @jaganpt , Dev team has reviewed this scenario and they suggested two possible things that can be done here

1. Restarting the function App to make sure that no limits were wrongly set during the deployment of the App. This could be a system error as well. 
2. Since the issue looks like its coming from the Application insights. Can you check if you are reaching any CAP limit. (eg below)
![image](https://user-images.githubusercontent.com/66122429/117337804-73cf1280-aebb-11eb-93eb-410e90363548.png)

**Comment by jaganpt** [comment]
Hi @v-anvari ,

We will check as suggested and update you. Thanks.

**Comment by jaganpt** [comment]
Hi @v-anvari ,

I have restarted the app and also verified the CAP limit which is 100 GB/day. Still logs are missing from the logs. Thanks.

**Comment by v-anvari** [comment]
Hi @jaganpt , While the team is investigating, this looks like an issue related to your specific app. Did you have a chance to submit a support request. If not, can you submit a support request and check if the support team could find out something from their end specific to your app.
