### ISSUE TITLE
The request size limits need to be configurable

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#7204]
We need to use an environment variable allow users to override the request size limit. The environment variable name should be `FUNCTIONS_REQUEST_BODY_SIZE_LIMIT`

https://github.com/Azure/azure-functions-host/blob/69111926ee920d4ba10829c8fa34303bb8165a42/src/WebJobs.Script.WebHost/Program.cs#L43-L50

**Comment by balag0** [comment]
Will updating the logic here work for placeholders as well?

**Comment by soninaren** [comment]
Why would placeholders need to have request body greater than 30 MB?

**Comment by balag0** [comment]
When the app is in placeholder mode that new setting will anyway not be set, so yes there is no expectation that will need to work for placeholders. My question was more on , will this code run again during specialization or is the only chance to use the config at initial startup.

**Comment by soninaren** [comment]
Yes, we would need to make sure that the config applies when specialization takes place. Given that the config is controlled by environment variable, changing the app setting would cause a restart anyway.

**Comment by fabiocav** [comment]
Had a chat with @soninaren about an approach that will work for specialization as well
