### ISSUE TITLE
DryIoc.ContainerException

### ISSUE THREAD

**Issue by klogan12** [Azure/azure-functions-host#7207]
Getting this exception on function app execution suddenly. We use DI for httpfactory. What is the best way to solve this.

{Message: "An error has occurred.",…}
ExceptionMessage: "Scope disposed{no name, Parent=disposed{no name, Parent={no name, Parent={no name, Parent={no name, Parent={no name, Parent={no name, Parent={no name}}}}}}}} is disposed and scoped instances are disposed and no longer available."
ExceptionType: "DryIoc.ContainerException"
Message: "An error has occurred."
StackTrace: "   at DryIoc.Throw.It(Int32 error, Object arg0, Object arg1, Object arg2, Object arg3) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 9000
↵   at DryIoc.Scope.TryGet(Object& item, Int32 id) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7890
↵   at DryIoc.Container.InstanceFactory.GetAndUnwrapOrDefault(IScope scope, Int32 factoryId) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 1481
↵   at DryIoc.Container.InstanceFactory.GetInstanceFromScopeChainOrSingletons(IResolverContext r) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 1467
↵   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 309
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
↵   at System.Linq.Expressions.Interpreter.ExceptionHelpers.UnwrapAndRethrow(TargetInvocationException exception)
↵   at System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Run(InterpretedFrame frame)
↵   at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame frame)
↵   at System.Linq.Expressions.Interpreter.LightLambda.Run(Object[] arguments)
↵   at Thunk(Func`2 , IResolverContext )
↵   at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 225
↵   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 196
↵   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedServiceProvider.GetService(Type serviceType) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\ScopedServiceProvider.cs:line 25
↵   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
↵   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
↵   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(String name)
↵   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass14_0.<.ctor>b__1()
↵   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
↵   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
↵   at System.Lazy`1.CreateValue()
↵   at System.Lazy`1.get_Value()
↵   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandler(String name)
↵   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)

**Comment by athamala** [comment]
We started noticing this while running functions version 3.0.15371

**Comment by klogan12** [comment]
@athamala  - So workaround to change function version to 2.0?

**Comment by klogan12** [comment]
Error is happening even with version 2.0.15229.0.

2021-03-10T00:10:26.658 [Information] Host Status: {"id": "xxxx","state": "Running",**"version": "2.0.15229.0","versionDetails": "2.0.15229.0 Commit hash: N/A","processUptime": 72729}**
2021-03-10T00:10:26.670 [Information] Host Status: {"id": "xxxxx","state": "Running","version": "2.0.15229.0","versionDetails": "2.0.15229.0 Commit hash: N/A","processUptime": 72741}

**Comment by athamala** [comment]
Programming error at our end partially caused this, creating too many identical requests and by fixing that we have mitigated this. But we haven't found the actual reason for this.

**Comment by v-anvari** [comment]
Hi @klogan12 , Apologies for  the delayed response. We are trying to understand your scenario to understand the error. Can we have the repro steps and what other packages you are using in your project.
