### ISSUE TITLE
Expose current retry count to Custom Handlers

### ISSUE THREAD

**Issue by ZachTB123** [Azure/azure-functions-host#7212]
#### What problem would the feature you're requesting solve? Please describe.

This is the same ask as [this](https://github.com/Azure/azure-webjobs-sdk/issues/2595) issue but I would like to see this surfaced to custom handlers. For example, I want send Event Hub messages to a Storage Account for later processing if I am on my final retry attempt.

#### Describe the solution you'd like

The value available in a header similar to invocation id or a part of the [request payload](https://docs.microsoft.com/en-us/azure/azure-functions/functions-custom-handlers#request-payload) in `Metadata`.

#### Describe alternatives you've considered

N/A

#### Additional context

[This](https://github.com/Azure/azure-webjobs-sdk/issues/2595) has links to updating other language works but I don't see a mention of Custom Handlers. I don't know if Custom Handlers will get this feature automatically or will need another update but as of right now, I don't see this data exposed.

**Comment by pragnagopa** [comment]
cc @anthonychu 
Tagging @fabiocav to find an owner.

**Comment by madelinegordon** [comment]
@anthonychu , should the retry context be included in the data or metadata of the http request?
