### ISSUE TITLE
Azure Fuctions proxy not accepting Private SSL certificates on back-end request

### ISSUE THREAD

**Issue by bvduijn** [Azure/azure-functions-host#7213]
Azure Fuctions proxy not accepting Private SSL certificates on back-end request

#### Investigative information

Please provide the following:

- Timestamp: 15:21 GMT
- Function App version:  Runtime version 3
- Function App name: 
- Function name(s) (as appropriate): 
- Invocation ID:  Trace Id 44728e5fb2894c1b9f9fb5b14b426a45  "activityId": "44728e5f-b289-4c1b-9f9f-b5b14b426a45"
- Region: WestEurope

#### Repro steps

Provide the steps required to reproduce the problem:

Configured Azure VNet integration
Configured Azure functions for internal DNS
Published a local server through Azure Function Proxy
Invoked web request to new Azure endpoint

#### Expected behavior

Get a normal 200 response

#### Actual behavior

Got this response in the Trace Logs
      {
        "source": "forward-request",
        "timestamp": "2021-03-08T15:19:24.0896946Z",
        "elapsed": "00:00:00.0561253",
        "data": {
          "messages": [
            "The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.",
            "The SSL connection could not be established, see inner exception.",
            "The remote certificate is invalid according to the validation procedure."
          ]
        }
      }
#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 
- I've verified DNS is working; publishing a site without SSL works fine
- I've tried to add internal certificates to SSL/TLS Settings 
- Configured WEBSITE_LOAD_CERTIFICATES to "*"
- When in the PS debugging console I can see the certificate chain is available 

```powershell
get-childitem cert:currentuser\my
```

**Comment by v-bbalaiagar** [comment]
Hi @bvduijn, Apologies for the delayed response, I am unable to get the logs with the mentioned Invocation ID. Can you confirm the details. Meanwhile, can you please go through the [SO](https://stackoverflow.com/questions/52939211/the-ssl-connection-could-not-be-established) where the SO talks about mentioned exception and solutions to resolve it. 
Please check and let us know if this helps.
