### ISSUE TITLE
System.ComponentModel.Annotatoins Version=5.0.0.0 (doesn't exist)

### ISSUE THREAD

**Issue by trailmax** [Azure/azure-functions-host#7221]
Just getting this exception when trying to create DbContext for EntityFramework 6.4.4. 

> FileNotFoundException: Could not load file or assembly 'System.ComponentModel.Annotations, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'

I've tried adding Annotations NuGet package directly to the function project, but that made zero difference.

I'm on Functions v3, netcoreapp3.1. I've gone through all threads and SO questions related. The problem is very similar to [this issue](https://github.com/Azure/azure-functions-core-tools/issues/479) but there is no official solution or workaround provided. 

[Solution linked](https://stackoverflow.com/a/50776946/809357) in that thread works, but I'm wondering if there is an official solution to this problem provided by Az Functions team? 
(i.e. I don't feel comfortable putting internet-provided code snippet that I don't fully understand into production)

**Comment by Sellorio** [comment]
Also having this issue... Binding redirects are a hack. Why is it looking for the wrong version?

Ok for me it was having to run Clean Solution. Since I had to do a metric boat ton of nuget and project version changes to make Azure Functions in .Net actually work.

As an aside, not really sure why Azure Functions .net felt the need to rearchitect all the stuff that was well designed in MVC Core and do it all wrong. Makes switching to Azure Functions tedious as best.

**Comment by AndreaCuneo** [comment]
Also having the same issue.

**Comment by JohannesBertens** [comment]
Following this as well, the "workaround" with the RedirectAssembly function works for us, but this is not a long-term solution.

**Comment by trailmax** [comment]
I think I found another workaround for this issue, but that might not be available to everyone: update to .Net 5 in functions and use out-of process execution. This way you don't depend on Az Functions runtime itself and can use whatever you like in dependencies. But there is no official documentation (yet) on upgrade path from your netcoreapp 3.1 to .net5 and there is no support for Durable functions (a showstopper for myself)

**Comment by joelmdev** [comment]
I get this for System.ComponentModel, Version=5.0.0.0, not the DataAnnotations, but I'd imagine it's a related issue.

**Comment by merinofg** [comment]
Downgrading the **System.ComponentModel.Annotations** NuGet package to **v4.7.0** solved for me.
If it helps, also had to downgrade **Microsoft.EntityFrameworkCore** package to **v3.1.16** so all package can play nicely.

**Comment by i3anaan** [comment]
Experiencing this issue as well, downgrading to v4.7.0 worked for us!

**Comment by v-anvari** [comment]
Hi @trailmax , 5.X.X versions are supported and were explicitly released for .Net 5. .Net core 3.xx or lesser do not support the 5.x.x versions. So downgrading the versions to below 5.x.x is the solution. Closing this issue as the required information is provided.

**Comment by IanKemp** [comment]
This is yet another case where adding the  `<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>` "workaround" (AKA what should be the default behaviour) to your functions app CSPROJ is required to get correct behaviour.
