### ISSUE TITLE
Usage of SDK vs REST API in Azure Function

### ISSUE THREAD

**Issue by cpatil7** [Azure/azure-functions-host#7228]
#### Question : 
Using Azure SDK for enabling managed identity in the NodeJS function app. These SDKs increased the size of our function app by almost 3mb, which resulted in a high startup time. We then moved to using REST API to make calls for managed identity. Question is are these SDK libraries optimized for size?

**Comment by cpatil7** [comment]
@v-anvari - any update please

**Comment by v-anvari** [comment]
Hi @cpatil7 , We are quiet not sure about this, the correct repository to raise this issue would be [https://github.com/Azure/azure-sdk-for-node/issues](https://github.com/Azure/azure-sdk-for-node/issues). I wouldn't be able to transfer this issue, kindly raise a new issue in "sdk for node"

Closing this issue, please feel free to reach back to us in case of any further queries related to function host.
