### ISSUE TITLE
Azure Function timer trigger not always firing according to schedule

### ISSUE THREAD

**Issue by pjeschko** [Azure/azure-functions-host#7231]
I need some help, because I don't know if I did something wrong or this is simply a bug. I have written a simple azure function using node.js that uses a timer trigger on a consumption plan and should trigger by its TCRON expression every 5 minute, but when I take a look into the application insights "request" data I can see that it does in fact not trigger every 5 minutes. It leaves out some intervals.

Here are some facts:
* My function does not require more than 5 minutes to execute it takes about 2 seconds.
* I also have app insight data sampling disabled in the configuration.
* No I did not change my config or deploy during that intervals left out.
* Yes I am aware that it does not exactly trigger ever 5 minutes sharp. But it should be somewhat near to that.

Requests in App Insight Logs entry timestamps that show that intervals are missing:

3/16/2021, 9:34:59.996 AM	
3/16/2021, 9:29:59.996 AM	
3/16/2021, 9:20:00.002 AM	
3/16/2021, 9:05:00.018 AM	
3/16/2021, 8:50:00.006 AM	
3/16/2021, 8:35:00.000 AM	
3/16/2021, 8:24:59.993 AM	

function.json of the azure function in question contain the CRON expression
```
{
  "bindings": [
    {
      "name": "myTimer",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 */5 * * * *"
    }
  ]
}
```

host.json of the app
```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": false,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  }
}
```

**Comment by v-bbalaiagar** [comment]
Hi @pjeschko, Could you please provide us the invocation id of the error and time stamp during the error to get the logs and check the cause.

**Comment by pjeschko** [comment]
Sorry I did not see that you have asked for an invocation id and timestamp of the error.
From my point of view I don't think I can give you the invocation ID because in the application insight data there is no entry for that missing invocation.

And well for the timestamps they are the missing timestamps like for example around the following times:
  * 3/16/2021, 9:15:00.000 AM
  * 3/16/2021, 9:20:00.000 AM
The fundtion app name is: website-watcher-export-func-app-v1
and the function name is: website-watcher-export-func

**Comment by v-bbalaiagar** [comment]
Hi @pjeschko, We are reopening the issue and we are checking the backend logs.

**Comment by v-bbalaiagar** [comment]
Hi @brettsam, kindly look into this issue.
 I went through the logs for this issue and it is working as scheduled but in App Insight Logs entry timestamps show that intervals are missing.

**Comment by v-bbalaiagar** [comment]
cc @brettsam, tagging brett for further investigation

These are my findings:

![image](https://user-images.githubusercontent.com/74654421/113871840-ebccee80-97d0-11eb-8a1c-d2f8e858c0df.png)

![image](https://user-images.githubusercontent.com/74654421/113872003-161eac00-97d1-11eb-9da7-1a688683634e.png)

**Comment by pjeschko** [comment]
@v-bbalaiagar. We have disabled Application Insights Logging Sampling on purpose, because the description of the "feature", mentioned it can lead to missing Application Insights data.

**Comment by v-bbalaiagar** [comment]
Hi @pjeschko, Apologies for the delayed response. If this is an ongoing issue, can you provide us the recent time stamp where you observe this behavior and we will be able to look at the logs and understand what could have happened there.
