### ISSUE TITLE
Azure Function EventHub Output Binding fails with messages larger than 256KB

### ISSUE THREAD

**Issue by ChristianSauer** [Azure/azure-functions-host#7235]
#### Check for a solution in the Azure portal
If you're not sure where to file your issue, feel free to file it here. Please provide detailed steps to reproduce, including code if applicable.

I am running an Azure Function, written in Node.JS, which sends large events to the Event Hub, these events are large (more than 256kb, less than 1MB). This should work, but fails with the message `Event is too large. Event is approximately 418487b and max size is 245760b`
I see that this should be fixed in https://github.com/Azure/azure-functions-eventhubs-extension/issues/29 but it does still not work.

#### Investigative information

Please provide the following:

- Timestamp: 2021-03-19T14:56:33.911684Z
- Function App version: 3
- Function App name:  func-er-gi-eb0a1917-westeurope
- Function name(s) (as appropriate): eventReceiver
- Invocation ID: 2f1c367f-41ed-4bce-ad0f-4a9b4c7af43e
- Region: westeurope

**Comment by ZachTB123** [comment]
I've encountered this also. In my `host.json` file I have my `extensionBundle` version set to `[2.*, 3.0.0)`. [This](https://github.com/Azure/azure-functions-extension-bundles/blob/v2.x/src/Microsoft.Azure.Functions.ExtensionBundle/extensions.json#L25) says it should be using `4.2.0` for Event Hubs which is [suppose](https://github.com/Azure/azure-functions-eventhubs-extension/releases/tag/v4.2.0) to include the fix but based on my logs in App Insights, it says I am using `4.1.1.0`.

**Comment by v-anvari** [comment]
cc @alrod / @sidkri

**Comment by MATT-444** [comment]
I too was suffering from this issue, but managed to get it working with some help from Microsoft.

Turns out that changing the extension bundle to be [2.*, 3.0.0) isn't enough and you also need to explicitly include the eventHubs extension in your host.json

{
  "version": "2.0",
  "managedDependency": {
    "Enabled": true
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.*, 3.0.0)"
  },
  "extensions": {
    "eventHubs": {}
  }
}

**Comment by ZachTB123** [comment]
My function that is having this issue omits the `eventHubs` extension from its `host.json` file, but I am noticing that a few functions that do have the `eventHubs` extension specified are still using version `4.1.1.0` which has this issue.

**Comment by alrod** [comment]
Current v2 bundle extension [2.*, 3.0.0) uses 4.2.0:
[https://github.com/Azure/azure-functions-extension-bundles/blob/v2.x/src/Microsoft.Azure.Functions.ExtensionBundle/extensions.json#L25](https://github.com/Azure/azure-functions-extension-bundles/blob/v2.x/src/Microsoft.Azure.Functions.ExtensionBundle/extensions.json#L25)

@ZachTB123 do you still experience the issue?

**Comment by ZachTB123** [comment]
@alrod I don't see any recent invocations that indicate version `4.1.1.0` is being used like I mentioned in my previous post but I also did implement a fix already in code where we are checking the size and manually sending the data to Event Hub using the sdk if the size is greater than 245kb.
