### ISSUE TITLE
Host.json implies ServerTelemetryChannel is used in production which is not the case

### ISSUE THREAD

**Issue by SavaNDragos** [Azure/azure-functions-host#7237]
Version 3.
Application is being deployed in Azure Functions, with a windows app plan behind and an app insight.
		<PackageReference Include="Microsoft.ApplicationInsights" Version="2.17.0" />
		<PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.17.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Logging.ApplicationInsights" Version="3.0.25" />
		<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />

Create the telemetry client: 
	var telemetry = new TelemetryClient(TelemetryConfiguration.CreateDefault());

We use it later to record some data:
telemetry.TrackTrace(nameof({an.enum.vale}), callParameters.ToAppInsightsData());

I saw data not being saved in appInsight (random behavior)
Started investigating and have the idea that sampling is not the fault. (sampling disabled and last test was with min=max =100)

Looking more the issue points to the fact that the channel in the 'telemetry' is actually a InMemoryChannel and not a ServerTelemetryChannel how I was expecting from:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core

Reproduction, new project with telemetry being initialized in the function and try to record something.
logging what that of channel it is being used when you deploy to Azure Function = InMemoryChannel

Wasn't ServerTelemetryChannel expected?

**Comment by v-anvari** [comment]
Hi @SavaNDragos , Yes, According to the document here, the default channel is ServerTelemetryChannel https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core#configuring-a-telemetry-channel. Can we have more details to understand your scenario better. Can we know the code that you are writing and the expected vs actual behavior. We would require repro steps to reproduce this scenario if required
