### ISSUE TITLE
BlobTrigger in dotnet-isolated does not allow binding input blob to Stream neither read blob Uri without getting blob payload

### ISSUE THREAD

**Issue by Dzoukr** [Azure/azure-functions-host#7240]
Based on documentation hint from https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=csharp, the bigger blobs should not be binded directly to `string` or `Byte[]`. 

However when using this code:

```csharp
public static class MyBlobFunction
{
    [Function("MyBlobFunction")]
    public static void Run([BlobTrigger("some-input", Connection = "")] Stream myBlob, string name, FunctionContext context)
    {
        var logger = context.GetLogger("MyBlobFunction");
        logger.LogInformation($"C# Blob trigger function Processed blob\n Name: {name} \n Data: {myBlob}");
    }
}
```

I got an error:

```
System.Private.CoreLib: Exception while executing function: Functions.MyBlobFunction. System.Private.CoreLib: Result: Failure
Exception: Microsoft.Azure.Functions.Worker.Diagnostics.Exceptions.FunctionInputConverterException: Error converting 1 input parameters for Function 'MyBlobFunction': Cannot convert input parameter 'myBlob' to type 'System.IO.Stream' from type 'System.ReadOnlyMemory`1[[System.Byte, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
```

I understand that the input `myBlob` parameter is string, but that's something I need to avoid (as mentioned in original documentation) for bigger files. Please note that for non-isolated process this works as expected.

Can I get somehow only the blob `Uri` without reading its content?

**Comment by v-anvari** [comment]
Hi @Dzoukr , Apologies for the delayed response, Streams aren't supported when using BlobTriggers in .Net 5.0.

Azure/azure-functions-dotnet-worker#378 (comment)

Duplicate issue : [azure-functions-dotnet-worker/issues/398.](https://github.com/Azure/azure-functions-dotnet-worker/issues/398)

The right repository for this issue/updates is Dot Net worker.
