### ISSUE TITLE
Microsoft.Azure.WebJobs.Script.Diagnostics.Extensions.LoggerExtension logging during cold start

### ISSUE THREAD

**Issue by safihamid** [Azure/azure-functions-host#7242]
This call https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs#L111 is invoking bunch of logging and JIT methods during specialization as shown below. Inc% is ~7% of the time spent in Functions process in VMSS stamp.
Need to call something similar during placeholder to avoid all those initializations during specialization or remove the method altogether?
 

Name | Inc % | Inc
-- | -- | --
\|\|    \|     \|     \|    \|\| \|+   microsoft.azure.webjobs.script!Microsoft.Azure.WebJobs.Script.ScriptHostBuilderExtensions+<>c__DisplayClass7_3.<AddScriptHostCore>b__8(Microsoft.Azure.WebJobs.Hosting.IWebJobsStartupTypeLocator) | 9.4 | 28
\|\|    \|     \|     \|    \|\| \|\|+   microsoft.azure.webjobs.host!WebJobsBuilderExtensions.UseExternalConfigurationStartup | 9.4 | 28
\|\|    \|     \|     \|    \|\| \|\| + system.private.corelib!System.Lazy`1[System.__Canon].get_Value() | 9.4 | 28
\|\|    \|     \|     \|    \|\| \|\|  +   system.private.corelib!System.Lazy`1[System.__Canon].CreateValue() | 9.4 | 28
\|\|    \|     \|     \|    \|\| \|\|   + system.private.corelib!System.Lazy`1[System.__Canon].ExecutionAndPublication(System.LazyHelper,   Boolean) | 9.4 | 28
\|\|    \|     \|     \|    \|\| \|\|    +   system.private.corelib!System.Lazy`1[System.__Canon].ViaFactory(System.Threading.LazyThreadSafetyMode) | 9.4 | 28
\|\|    \|     \|     \|    \|\| \|\|     +   microsoft.azure.webjobs.script!Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator.<.ctor>b__7_0() | 9.4 | 28
\|\|    \|     \|     \|    \|\| \|\|      +   system.private.corelib.il!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[System.__Canon].Start(!!0&) | 9.4 | 28
\|\|    \|     \|     \|    \|\| \|\|       +   system.private.corelib.il!AsyncMethodBuilderCore.Start | 9.4 | 28
\|\|    \|     \|     \|    \|\| \|\|          +   microsoft.azure.webjobs.script!Microsoft.Azure.WebJobs.Script.DependencyInjection.ScriptStartupTypeLocator+<GetExtensionsStartupTypesAsync>d__11.MoveNext() | 9.4 | 28
\|\|    \|     \|     \|    \|\| \|\|           + microsoft.azure.webjobs.script!LoggerExtension.ScriptStartNotLoadingExtensionBundle | 7.7 | 23
\|\|    \|     \|     \|    \|\| \|\|           \|+   microsoft.extensions.logging.abstractions.il!Microsoft.Extensions.Logging.LoggerMessage+<>c__DisplayClass8_0`4[System.__Canon,System.Boolean,System.Boolean,System.Boolean].<Define>b__1(class   Microsoft.Extensions.Logging.ILogger,!0,!1,!2,!3,class System.Exception) | 7.4 | 22
\|\|    \|     \|     \|    \|\| \|\|           \|\|+   microsoft.extensions.logging.abstractions.il!Microsoft.Extensions.Logging.LoggerMessage+<>c__DisplayClass8_0`4[System.__Canon,System.Boolean,System.Boolean,System.Boolean].<Define>g__Log\|0(class   Microsoft.Extensions.Logging.ILogger,!0,!1,!2,!3,class System.Exception) | 7.1 | 21
\|\|    \|     \|     \|    \|\| \|\|           \|\|\|+   microsoft.extensions.logging.abstractions.il!Microsoft.Extensions.Logging.Logger`1[System.__Canon].Microsoft.Extensions.Logging.ILogger.Log(value   class Microsoft.Extensions.Logging.LogLevel,value class   Microsoft.Extensions.Logging.EventId,!!0,class System.Exception,class   System.Func`3) | 6.4 | 19
\|\|    \|     \|     \|    \|\| \|\|           \|\|\|\|+   microsoft.extensions.logging.il!Logger.Log | 5.7 | 17
\|\|    \|     \|     \|    \|\| \|\|           \|\|\|\|\|+ microsoft.extensions.logging.il!Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog\|12_0(value   class Microsoft.Extensions.Logging.LogLevel,value class   Microsoft.Extensions.Logging.EventId,class   Microsoft.Extensions.Logging.ILogger,class System.Exception,class System.Func`3,class   System.Collections.Generic.List`1&,!!0&) | 5.4 | 16
\|\|    \|     \|     \|    \|\| \|\|           \|\|\|\|\|\|+   microsoft.azure.webjobs.script.webhost.il!SystemLogger.Log | 3.0 | 9
\|\|    \|     \|     \|    \|\| \|\|           \|\|\|\|\|\|\|+   microsoft.extensions.logging.abstractions.il!Microsoft.Extensions.Logging.LoggerMessage+LogValues`4+<GetEnumerator>d__13[System.__Canon,System.Boolean,System.Boolean,System.Boolean].MoveNext() | 1.7 | 5

**Comment by fabiocav** [comment]
Moving this to sprint 100 as the work is still in progress.

**Comment by fabiocav** [comment]
@soninaren would you be able to provide an update on this? Should this be moved to the next sprint?

**Comment by brettsam** [comment]
If this log message isn't super-useful, I say we just delete it. The alternative is calling it in the above `if` block if we're in placeholder mode. That'd run it, but it seems odd, especially if this log message isn't critical.

**Comment by soninaren** [comment]
I think i will have to do it so that it is explicitly called in placeholder mode. The log is actually critical because we ignore extension bundle config explicitly for some very specific conditions. This log message is the only thing that helps identify why the bundle config was ignored.
