### ISSUE TITLE
[LinuxConsumption] Support mounting file share provided by Azure Files

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#7252]
In order to support Managed Dependencies feature for Powershell Functions - we need a writable persistent file storage 

Note: We should continue supporting run from zip

cc @divyagandhisethi @AnatoliB @Francisco-Gamino @stefanushinardi

**Comment by balag0** [comment]
Will be scoped to powershell for now to avoid cold start impact to other apps.

**Comment by pragnagopa** [comment]
> Will be scoped to powershell for now to avoid cold start impact to other apps.

ACK. We should scope the change for powershell only for now.

**Comment by AnatoliB** [comment]
> Will be scoped to powershell for now to avoid cold start impact to other apps.

What about placeholders though?

**Comment by pragnagopa** [comment]
> What about placeholders though?

Call to download dependencies happens after specialization.  This should be OK! But we need to test to confirm.

**Comment by balag0** [comment]
Correct. Mounting and downloads happen after/during specialization. So we will be able to identify if the specialization is happening for powershell vs other langauges.

**Comment by AnatoliB** [comment]
Great, thank you. PowerShell worker starts installing dependencies on the first function load request. If the file share is mounted by this moment, we are good.

**Comment by fabiocav** [comment]
Moving this to sprint 99 as this was a late addition. Please feel free to change if that's not appropriate.

**Comment by pragnagopa** [comment]
Thanks! Sprint 99 sounds good. @balag0  - Marking this as P1 as this a blocker for tooling updates needed to support powershell on Linux.
