### ISSUE TITLE
TelemetryConfiguration is not resolved by dependency injection

### ISSUE THREAD

**Issue by ben-burton** [Azure/azure-functions-host#7254]
I am encountering the same error as the following closed issue: #5530. I am injecting TelemetryConfiguration as per the documentation here:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#log-custom-telemetry-in-c-functions

As referenced on this page here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#logging-services

> Don't register your own TelemetryConfiguration or TelemetryClient if you are using the built-in Application Insights functionality. If you need to configure your own TelemetryClient instance, create one via the injected TelemetryConfiguration as shown in Log custom telemetry in C# functions.

#### Investigative information

Please provide the following:

- Function App version: 3

Running functions host locally

#### Repro steps

Implement as per Log custom telemetry section in documentation referenced above

#### Expected behavior

TelemetryConfiguration is resolved

#### Actual behavior

Exception 'Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type 'Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration' while attempting to activate...' is thrown when starting the functions host

#### Related information 

Provide any related information 

* C#

```csharp
namespace functionapp0915
{
    public class HttpTrigger2
    {
        private readonly TelemetryClient telemetryClient;

        /// Using dependency injection will guarantee that you use the same configuration for telemetry collected automatically and manually.
        public HttpTrigger2(TelemetryConfiguration telemetryConfiguration)
        {
            this.telemetryClient = new TelemetryClient(telemetryConfiguration);
        }
    }
}
```

**Comment by v-anvari** [comment]
Hi @ben-burton, Thank you for your feedback! We will investigate and update our findings as appropriate.

**Comment by v-anvari** [comment]
Hi @ben-burton , I was able to run the App successfully, As your repro steps indicate, I have added the steps documented in log custom telemetry. If you are still facing this issue, can you provide more details on the packages and dependencies that you are using. How are you debugging the code. 

References used:
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Microsoft.ApplicationInsights;
using Microsoft.ApplicationInsights.DataContracts;
using Microsoft.ApplicationInsights.Extensibility;
using System.Linq;

Packages used:
![image](https://user-images.githubusercontent.com/66122429/118857418-a7fff580-b8f5-11eb-9c69-6e45f81fe30c.png)

output:
Executed 'Function1' (Succeeded, Id=384a192c-f87b-4565-acad-5077ea96447a, Duration=99ms)

**Comment by v-anvari** [comment]
Update: I get the mentioned error " _Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type 'Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration' while attempting to activate '_7254.Function1_" when I don't add "APPINSIGHTS_INSTRUMENTATIONKEY": "any value" in Local.settings.json.

As mentioned in comment here https://github.com/Azure/azure-functions-host/issues/3741#issuecomment-645964338, setting the value to some dummy string (like "abc") will cause the TelemetryConfiguration to be registered.

Let us know if this helps

**Comment by v-anvari** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue
