### ISSUE TITLE
[General Question] How is the Dryloc library merged into the output assembly?

### ISSUE THREAD

**Issue by gjuttla** [Azure/azure-functions-host#7255]
Hi
Please apologize if this is an off-topic question.

I was wondering how you merged the Dryloc library into the `Microsoft.Azure.WebJobs.Script.WebHost.dll` assembly.

![image](https://user-images.githubusercontent.com/22775678/112862697-5174f880-90b6-11eb-9be5-aba6c49c02bf.png)
azure-functions-host version: 3.0.15417

I couldn't find the Dryloc source (e.g. the class `CompositeScopeName` from the screenshot) in the source of this repo or any IL merge build step.

Asking because the last info I have is that ILMerge (the official tool) did not work with .NET [Core] yet.

Thanks

**Comment by v-anvari** [comment]
Hi @gjuttla , The Assembly is not being merged, the Dryloc is being complied into the code directly.

**Comment by gjuttla** [comment]
Hi @v-anvari 
Thanks for the info. 

Closing this question.
