### ISSUE TITLE
Log warning with link to announcement repo for pinned apps

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#7264]

**Comment by pragnagopa** [comment]
cc @fabiocav - for traige
cc @anirudhgarg as fyi

**Comment by madelinegordon** [comment]
Log a warning from the Host to alert the customer that they are pinned to a version that may not be stable when a release takes place. 

announcement repo = "app-service-announcements"

**Comment by fabiocav** [comment]
Closing this as it's no longer applicable.
