### ISSUE TITLE
Incorrect route registration may impact function routes

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#7266]
The following route will impact functions handling `PUT` requests in the latest host version due to a route precedence change:

https://github.com/Azure/azure-functions-host/blob/9c2ce4c108b08724b623df088d9ed4d232af116a/src/WebJobs.Script.WebHost/Controllers/ExtensionsController.cs#L62

The action must be updated to handle the correct route.

**Workaround**: Pin functions runtime version to : 3.0.15406 ([instructions](https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal#view-and-update-the-current-runtime-version))

**Comment by fabiocav** [comment]
@yojagad adding you to this, but if you need to reassign, let us know.

@safihamid @pragnagopa @sidkri all have context on the issue and should be able to assist.

**Comment by pragnagopa** [comment]
Workaround: Please pin functions runtime version to : `3.0.15406`

**Comment by pragnagopa** [comment]
cc @Francisco-Gamino - current release owner.
