### ISSUE TITLE
Dangerous behavior when using IServiceProvider.CreateScope()

### ISSUE THREAD

**Issue by qcnguyen** [Azure/azure-functions-host#7284]
#### Investigative information

- Function App version: .net core 3.1

**Description**
The registered scoped object won't be correctly resolved whenever IServiceProvider.CreateScope() is invoked. 
Please refer the code below:

**Code for StartUp:**
```

[assembly: FunctionsStartup(typeof(FunctionApp1.StartUp))]
namespace FunctionApp1
{
    public class StartUp : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var serviceCollection = builder.Services;
            serviceCollection.AddScoped<ScopedService>();
            serviceCollection.AddTransient<Service>();
        }
    }
}
```
**Main Code**
```
using System;
using System.Threading.Tasks;
using FluentAssertions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection;

namespace DangerousWhenCreateScope
{
    public class Function1
    {
        public Function1(Service service)
        {
        }
        [FunctionName("Function1")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            return new OkResult();
        }
    }

    public class Service
    {
        public Service(IServiceProvider serviceProvider, ScopedService scopedService)
        {

            var o0 = serviceProvider.GetService<ScopedService>();
            scopedService.Id.Should().Be(o0.Id);  //Works fine

            var o1 = serviceProvider.GetService<ScopedService>();
            o0.Id.Should().Be(o1.Id);  //Works fine

            var scope = serviceProvider.CreateScope(); //Please note that the created scoped is not used anywhere, just a dummy useless scope.

            var o2 = serviceProvider.GetService<ScopedService>();
            o1.Id.Should().Be(o2.Id); //For Azure function, the test failed here !!!!!!!!!!!!!!!
        }
    }

    public class ScopedService
    {
        public Guid Id { get; } = Guid.NewGuid();
    }
}
```

### Expected behavior:
the o1.Id Should be same as o2.Id . This is the behavior that asp.net core web is having

### Actual behavior
**the o1.Id is not same as o2.Id .**

More information:
I think this is the root cause of issues #5851 , #5590 when HttpClientFactory did create a scope internally, and it pollute the IServiceProvider of whole application. The services that resolved after HttpClientFactory.CreateClient() invocation will be created under the scope from HttpClientFactory , and then, when HttpClientFactory decide to recycle the scope, the application services will be affected as well.

- I think it related to this issue #5098  as well

**Comment by v-anvari** [comment]
Hi @qcnguyen , Checking this issue internally for any updates.

**Comment by fabiocav** [comment]
@qcnguyen can you please add the app setting `AzureWebJobsFeatureFlags` with a value of `EnableEnhancedScopes` and re-run your tests to validate whether this helps with your scenario? Thanks!

**Comment by qcnguyen** [comment]
The EnableEnhancedScopes works. Thanks, but when will it become the default behavior ?

**Comment by fabiocav** [comment]
This will become the default behavior with the next release.

**Comment by v-anvari** [comment]
Closing this issue  as the required information is provided, please feel free to reach back to us in case of any further queries related to this issue

**Comment by JoeBrockhaus** [comment]
> @qcnguyen can you please add the app setting `AzureWebJobsFeatureFlags` with a value of `EnableEnhancedScopes` and re-run your tests to validate whether this helps with your scenario? Thanks!

@fabiocav I'm investigating this scope disposed exception described in #5590 / #5851 when calling `httpClientFactory.CreateClient()` after some period of time:

>_`Scope disposed{no name, Parent=disposed{no name, Parent={no name, Parent={no name, Parent={no name, Parent={no name}}}}}} is disposed and scoped instances are disposed and no longer available.`_

We are leveraging the following package versions: 

```xml
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.29" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="2.2.0" />
```

Should the above app setting also resolve this exception?

**Comment by qcnguyen** [comment]
> This will become the default behavior with the next release.

it's been a month and we are still waiting for this. can you please confirm the exact day, please. It's critical for us @fabiocav
