### ISSUE TITLE
Functions Runtime Error Microsoft.Azure.Extensions.CosmosDB: Method Not Found

### ISSUE THREAD

**Issue by bobbytreed** [Azure/azure-functions-host#7286]
Functions runtime error
Microsoft.Azure.WebJobs.Extensions.CosmosDB: Method not found: 'Microsoft.Azure.WebJobs.IWebJobsExtensionBuilder Microsoft.Azure.WebJobs.WebJobsExtensionBuilderExtensions.ConfigureOptions(Microsoft.Azure.WebJobs.IWebJobsExtensionBuilder, System.Action`3<Microsoft.Extensions.Configuration.IConfiguration,System.String,!!0>)'.

I've searched the web, but only one page of links referencing this error and all are either closed issues, with little description, or spam links.

**Comment by v-anvari** [comment]
Hi @bobbytreed ,Can you provide us with the repro steps and the piece of code that is busted. What is the method that is breaking?

**Comment by bobbytreed** [comment]
It's not a method.  That's the error message in the azure portal.

Dependencies from project

 <ItemGroup>
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.6.0" />
    <PackageReference Include="Docker.DotNet" Version="3.125.4" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.15.0" />
    <PackageReference Include="Microsoft.Azure.Management.Automation" Version="2.0.7" />
    <PackageReference Include="Microsoft.Azure.Management.ContainerInstance" Version="3.0.0" />
    <PackageReference Include="Microsoft.Azure.Management.Fluent" Version="1.37.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.3" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.2" />
  </ItemGroup>

![image](https://user-images.githubusercontent.com/10874547/114533611-1200ed00-9c1c-11eb-82c8-c7e39266b6d6.png)

**Comment by v-anvari** [comment]
@bobbytreed , Can we have the repro steps to reproduce this error?

**Comment by bobbytreed** [comment]
I didn't do anything unique.  I created a new AzF using Visual Studio.  I clicked through all dialogs to create a new App Service, App Insights, etc. Then I published. I mean the function itself is 100 line, and you can see the short list of dependencies.

**Comment by v-anvari** [comment]
Hi @bobbytreed , Thank you for the information, This error could be due to multiple reasons and its important for us to understand the cause to provide a resolution. We are unable to reproduce this error from our end and not sure what is the cause of the error in your project scenario. Can we get the details of package references used and the code, for us to reproduce the error at our end.
