### ISSUE TITLE
Fix check for IsFileSystemReadOnly

### ISSUE THREAD

**Issue by pgombar** [Azure/azure-functions-host#7293]
Today, [this check](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Config/HostJsonFileConfigurationSource.cs#L260) for IsFileSystemReadOnly will always return true if `SCM_RUN_FROM_PACKAGE` app setting is present. This app setting is always present for Linux Consumption deployments, even if it's not used, so there can be a situation where we are not using `SCM_RUN_FROM_PACKAGE` on Linux Consumption (e.g. portal deployment/editing) and want the filesystem to be writable, so the logic for the check needs to be updated.

Impact:
1) Extension bundles are not loaded because the host cannot modify host.json and write the appropriate bundle.
2) File watching is disabled if the filesystem is read-only, causing slower function app updates.

**Comment by pragnagopa** [comment]
This needs to be part of next host release - blocker to enable in-portal editing

**Comment by pragnagopa** [comment]
@brettsam / @soninaren / @fabiocav - adding a little more context. This issue prevents loading extension bundles when app is created from portal - so only HttpTrigger and TimerTrigger templates are available.

**Comment by fabiocav** [comment]
Currently in PR. We should be able to review and merge for the current sprint.
