### ISSUE TITLE
[Kubenetes]Provide host lease management without storage account

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#7301]
We need to have a non-storage based lease mechanism for Kubernetes environments. This is achieved by injecting a side car which performs leader election in Kubernetes. The functions runtime sends a web request to this sidecar to get the leader for that particular lock name. The lock name here is derived by the webjobs sdk and is based on the app name and the function name.

**Comment by fabiocav** [comment]
Is this tied to the PR @divyagandhisethi is moving from WebJobs to the Host?

**Comment by divyagandhisethi** [comment]
> 
> 
> Is this tied to the PR @divyagandhisethi is moving from WebJobs to the Host?

Yes. I will link my PR to this issue.
