### ISSUE TITLE
ANSI control characters in container logs.

### ISSUE THREAD

**Issue by mcollier** [Azure/azure-functions-host#7309]
#### Investigative information

Please provide the following:

- Timestamp: 2021-04-22T02:02:46.233721012Z
- Function App name: https://csefeedback-419898-app.azurewebsites.net
- Region: East US

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a containerized Azure Function for Linux, as indicated at https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image?tabs=bash%2Cportal&pivots=programming-language-csharp#create-and-test-the-local-functions-project.
1. Publish the image to DockerHub.
1. Create the Azure Function using the newly created image.
1. Enable container logs, as specified at https://aka.ms/linux-diagnostics.
1. Once the function is running, in the Azure portal, navigate to the Deployment Center and view the Logs.

#### Expected behavior

Logs do not contain ANSI control characters.

#### Actual behavior

Logs contain ANSI control characters, making the log output slightly more difficult to read.

![image](https://user-images.githubusercontent.com/1142273/115645926-4137ee00-a2ef-11eb-94c9-9a94d878aeef.png)

#### Known workarounds
N/A

#### Related information 
N/A

**Comment by v-bbalaiagar** [comment]
Hi @mcollier, Can you please confirm if this issue requires for us to investigate further.

**Comment by mcollier** [comment]
It seems that setting an application setting / environment variable of `AzureFunctionsJobHost__Logging__Console__DisableColors` with a value of **true** will disable the ANSI control characters.

https://stackoverflow.com/a/57933813

cc: @anthonychu

**Comment by v-bbalaiagar** [comment]
Hi @mcollier, Thanks for the update, Does it requires more information or triage

**Comment by mcollier** [comment]
No. I think the next step is updating docs.

**Comment by v-bbalaiagar** [comment]
Hi @mcollier,  Can you please confirm if you can transfer this issue or tag the docs team.

**Comment by v-bbalaiagar** [comment]
Closing this issue as document issue is opened. Please provide your inputs here- https://github.com/MicrosoftDocs/azure-docs/issues/78755
