### ISSUE TITLE
Update build pipelines to increment minor version for each release

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#7312]
- Increment minor version on release

**Comment by pragnagopa** [comment]
cc @brettsam @fabiocav

**Comment by yojagad** [comment]
Was thinking if dev branch should point to a minor version that's about to be released. This way

- After a release is cut everytime, this minor version is updated. 
- Dev always points to a minor version you're working towards... This also makes cutting off a release easier.

**Comment by fabiocav** [comment]
Yes. We can send an update to the minor version at any point now.

**Comment by fabiocav** [comment]
Tagging @brettsam as this is something he just finished doing in 4.x

**Comment by yojagad** [comment]
Added automation here https://azfunc.visualstudio.com/Azure%20Functions/_releaseDefinition?definitionId=20&_a=definition-tasks&environmentId=209

A sample test PR from my fork : https://github.com/yojagad/azure-functions-host/pull/1

**Comment by fabiocav** [comment]
@yojagad can we discuss this approach? I would really like to avoid those kinds of integrations if possible, and I think we have the ability to parameterize the appropriate files so we're injecting this information at build time instead.

**Comment by yojagad** [comment]
Are you suggesting looking at releases to determine the successive minor version during build time? Or did you have something else in mind like looking at the minorVersion in release/3.0 branch ?

There is still the issue of updating the azure-pipelines.yml to display the appropriate minor which is pretty static. The above approach would cover both.

**Comment by fabiocav** [comment]
I just feel we can come up with a better approach that doesn't require changes and additional commits from a service account. 

I'm not proposing any specific solution with the above, though, I think we can talk through some options.

**Comment by yojagad** [comment]
Okay, I'll set something up and we can discuss through some options.

**Comment by yojagad** [comment]
I'll also remove the automation meanwhile

**Comment by yojagad** [comment]
Discussed this offline. Main concern here is using a service account that adds additional commits on dev branch.
Therefore, action items here are
- Update Manual step in release preparation pipeline to include instructions to update minor version after merging dev to release/3.0 . At this point even if OGFs fail, the commit made to dev to fix OGF should be cherry picked to release/3.0.
- Add a validation step to ensure dev's minor version is 1 ahead of release/3.0's minor version. Release preparation pipeline should not be successful without this.

**Comment by yojagad** [comment]
I've updated the steps here https://azfunc.visualstudio.com/Azure%20Functions/_releaseDefinition?definitionId=21&_a=definition-pipeline

**Comment by fabiocav** [comment]
Closing as done.
