### ISSUE TITLE
Update build script to produce site extension for patching Rapid Update feed

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#7314]
Each patch version of functions host site extension should include following -

- extension.xml --> just like regular site extension package
- Update build to use deterministic flag: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/code-generation#deterministic
- In the Folder 3.1.xxxx  Include following
    - hashesForHardlinks.txt  -- this file should include hashes for all the files need to run this as site extension
    - Version.json ? -- this file should include metadata regarding what is the full runtime version this site extension is patching
    - Include all the patched dlls
    - Include Microsoft.Azure.WebJobs.Script.dll as HostVersion in runtime which is also populated in Kusto relies on assembly version for this dll: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Host/ScriptHost.cs#L72  -- we need to ensure HostVersion is the patched version

**Comment by pragnagopa** [comment]
cc @fabiocav @brettsam

**Comment by fabiocav** [comment]
@yojagad should this work remain assigned to a sprint?

**Comment by yojagad** [comment]
Yes, please. I've been running some tests on a sample PR (https://github.com/Azure/azure-functions-host/pull/7346). Will be updating that PR and linking this work item to it
