### ISSUE TITLE
Authentication feature interferes with CORS feature on Linux Consumption

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-host#7316]
# Repro steps

1. Create Linux consumption function application
2. Create an azure web app that can host JS code
3. Add the web app domain as a CORS allowed origin
4. Enable Authentication for the application.
5. Try to make a cross-origin POST request in browser JS code from your web app to the function app. The CORS pre-flight request will return a 401.

#Fix
Swap CORS and EasyAuth middleware

**Comment by zsolt-halo** [comment]
Fantastic :) thanks!

**Comment by Jayruler3** [comment]
Yea
