### ISSUE TITLE
Azure Portal can't list functions (Azure Functions runtime is unreachable)

### ISSUE THREAD

**Issue by kelly-centare** [Azure/azure-functions-host#7330]
#### Investigative information

Hello, I inherited this application and am admittedly not an Azure expert. I am trying to troubleshoot some behavior and am having a difficult time getting any useable logs in the azure portal for this function. Looking through kudu is not revealing any recent longs (they are all from 2020, despite this function running every 15 minutes successfully).

- Timestamp: 4/29/2021 3:15PM (but this is always happening)
- Function App version: ~3
- Function App name: keen-integration-dev
- Function name(s) (as appropriate): All of them
- Invocation ID: This is happening in the Azure Portal
- Region: East US

I have seen similar issues reported ([#4855](https://github.com/Azure/azure-functions-host/issues/4855)) but my error is a bit different.

#### Repro steps

1. Go to Azure portal
2. Open up the azure function
3. Click Functions on the sidebar

#### Expected behavior

A list of azure functions is displayed that can be drilled into for more info

#### Actual behavior

I'm seeing an error banner "Azure Functions runtime is unreachable" and no functions listed.

![image](https://user-images.githubusercontent.com/83428455/116613750-b1053480-a8fe-11eb-8ab9-8dfb9539c56f.png)

Additional dev console errors below:
![image](https://user-images.githubusercontent.com/83428455/116614015-fd507480-a8fe-11eb-88ef-71108789ef4f.png)

`2021-04-29T20:22:30.307Z [error][FunctionsListBlade][getFunctions][failed] - Failed to load functions`

`[WebsitesExtension]  3:22:30 PM FunctionsListBlade FunctionsListBlade: [FunctionsListBlade][getFunctions][failed] - Failed to load functions `

`ErrorEntity:
Code: "BadRequest"
Message: "Encountered an error (InternalServerError) from host runtime."`

#### Known workarounds

None known.
I may be able to attach the debugger via Visual Studio and see log output this way.

#### Related information 

Provide any related information 

* This function app does have 5 separate functions in it
* I do see an error occurring every 6 hours, and I'm trying to get more information on that by viewing the logs these functions print out while running

**Comment by v-anvari** [comment]
Hi @kelly-centare , There are a few reasons why you may get this notification, shown in Figure 1 when you try to view your Function list in the Azure portal.  One such reason is that you have some kind of network restriction like VNET or Firewall that prevents the Azure Function host from accessing the Azure Storage Account on which your code exists.  So, check your endpoints which you have configured in the AzureWebJobsStorage and WEBSITE_CONTENTAZUREFILECONNECTIONSTRING application settings, and make sure there is nothing restricting the Function App host from access.

Here is the document to troubleshoot such issues: [https://docs.microsoft.com/en-us/azure/azure-functions/functions-recover-storage-account](https://docs.microsoft.com/en-us/azure/azure-functions/functions-recover-storage-account)

**Comment by balag0** [comment]
The underlying exception seems to be 

`System.InvalidOperationException : No authentication handler is registered for the scheme 'ArmToken'. The registered schemes are: Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("ArmToken",...)?`

So this is likely the same issue as https://github.com/Azure/azure-functions-host/issues/6805
@kelly-centare recommend pinging the other thread to see if there are any possible workarounds.

**Comment by miklen** [comment]
I have the same error and I think it's caused by adding authentication to the functions. I'm using the Azure Function authentication from Microsoft.Identity.Web (https://github.com/AzureAD/microsoft-identity-web/pull/856).
