### ISSUE TITLE
Run functions from a subdirectory

### ISSUE THREAD

**Issue by aaronadamsCA** [Azure/azure-functions-host#7345]
### What problem would the feature you're requesting solve? Please describe.

I want to build and deploy Azure Functions that live in a monorepo and use [TypeScript project references](https://www.typescriptlang.org/docs/handbook/project-references.html). This means the `host.json` file and function directories would be in a subdirectory, not the root directory.

### Describe the solution you'd like

1. Support a new Azure Functions environment variable that accepts a relative path from the package root directory to the `host.json` file.
2. Support a new `host.json` setting that accepts a relative path from the directory of the `host.json` file to the function directories.

I believe this could be adequate to support function applications using a modern Node.js application pattern:

- A function could live in `packages/function/` and include many references to other packages.
- The function configuration could live in `packages/function/host.json`; this would be the value of the new environment variable.
- Function directories could live in `packages/function/src/`; `src` would be the value of the new setting in `host.json`.

This could work for both JavaScript and TypeScript apps; the [existing hacky solution using `scriptFile` in `function.json`](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=v2#typescript) would continue to work for TypeScript functions.

This could even permit multiple function apps to run from the same repository, maybe even from the same build. If multiple function apps (like an HTTP API and its queue message handlers) shared large amounts of interrelated code in a single repository, you could potentially build once and deploy twice.

### Describe alternatives you've considered

Today we run `tsc --build` to recursively build the project and its references, and then in GitHub Actions run `mv ${{ env.working_directory }}/dist/* ./` to move the function's output files into the root directory. Then we package and deploy.

This works for us, but it is also bad. 🙂 Some of the problems include:

- It depends on Yarn workspaces, because it requires Node.js module resolution to resolve our TypeScript project references. Standard projects use relative path resolution and would not have this option.
- We needed to add `/package.json` to our `.funcignore`, because the root package's `"type": "module"` was causing the transpiled JavaScript to exit with `ERR_REQUIRE_ESM`. This is too esoteric to be a safe solution.
- We are crossing our fingers hoping for no future file/directory name collisions.

I've chosen a Microsoft stack; I'd ideally like the TypeScript team and the Azure Functions team to work together and devise a sane solution that doesn't involve writing shell scripts and crossing my fingers.

**Comment by v-anvari** [comment]
Hi @aaronadamsCA , Thank you for reaching out to us, checking this internally if this scenario is possible, will be updating the information

**Comment by aaronadamsCA** [comment]
Thanks @v-anvari.

If it helps, compare the current ["required folder structure for a JavaScript project"](projects) to the structure I think you should support:

```
- WorkspaceProject
| - node_modules
| - projects
| | - FunctionsProject
| | | - src
| | | | - MyFirstFunction
| | | | | - index.ts
| | | | | - function.json
| | | | - MySecondFunction
| | | | | - index.ts
| | | | | - function.json
| | | - dist
| | | | - (files emitted by `tsc --build`)
| | | - host.json
| | | - tsconfig.json
| | - SharedCodeProject
| | | - src
| | | | - myFirstHelperFunction.ts
| | | | - mySecondHelperFunction.ts
| | | - dist
| | | | - (files emitted by `tsc --build`)
| | | - tsconfig.json
| - .funcignore
| - package.json
| - tsconfig.build.json
| - tsconfig.json
```

In this scenario, `projects/FunctionsProject/dist/MyFirstFunction/index.js` can require code in `projects/SharedCodeProject/dist/myFirstHelperFunction.js`. Both projects share a top-level `node_modules/` directory. For these reasons, you need to be able to deploy the whole project, then instruct Azure Functions to run the functions found in `packages/FunctionsProject/dist/`. Presumably Node.js module resolution would take care of the rest.

(Being able to put the function files under `src/` is more a matter of convention and convenience, but if you're adding one feature to support better directory structures, I might as well ask for two! It's much easier to browse a larger monorepo when projects have their source code in a directory alongside their various configuration files.)

**Comment by v-anvari** [comment]
cc @fabiocav / @brettsam , Tagging for validation on supportability

**Comment by aaronadamsCA** [comment]
Thanks @v-anvari. Note that I've updated "Describe alternatives you've considered" above to describe our current workaround and why it's a limited and fragile solution.

**Comment by v-anvari** [comment]
Thank you @aaronadamsCA , The scenario will reviewed and validated.

**Comment by v-anvari** [comment]
Hi @aaronadamsCA, I have discussed this internally and this scenario is currently a known limitation which the team is working on and finding different work arounds to make it perform better. Unfortunately, I cannot provide an ETA for this implantation.

**Comment by aaronadamsCA** [comment]
Thanks @v-anvari. Our workaround is working for now, but it's rather difficult to support; I'd love to be able to move to a build-once-deploy-everywhere approach.

If you or the team would like access to our closed-source repository to see how we're doing things and to better understand what could be improved, contact me by email (in my profile) and I'm happy to provide this.

**Comment by v-anvari** [comment]
Thank you @aaronadamsCA , I shall check with the team if a PR can be raised.

Since this is also a feature request, I suggest you to submit a feature request here- https://feedback.azure.com/forums/355860-azure-functions

**Comment by fabiocav** [comment]
This is something we're tracking as a future enhancement. We don't have a concrete ETA we can share, but some of the required host work will likely be happening in the upcoming semester.

@ankitkumarr do we have an existing work item/issue tracking some of the host work for worker driven indexing?

**Comment by fabiocav** [comment]
Modifying the previous comment, as the scenario isn't 100% the same, but those are similar requirements.

We have some work planned to improve this behavior, but don't really have a concrete ETA at this point. The host work will likely be happening in the upcoming semester.

@ankitkumarr do we have a work item/issue tracking worker driven indexing?

**Comment by v-anvari** [comment]
Hi @aaronadamsCA , Here is a work item to improve this behavior - https://github.com/Azure/azure-functions-host/issues/7496. Similarly there will be work items created for Node and other languages.
