### ISSUE TITLE
Keys appear to not be persisted on Kubernetes

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-host#7353]
#### Investigative information

When creating a new key for a function, it sometimes appear as if the key wasn't saved. This is actually due to case mismatch between Write and Read of function key names in KubernetesSecretsRepository. For a function named `Http1`, [`WriteAsync()`](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Security/KeyManagement/KubernetesSecretsRepository.cs#L65) is called with functionName `http1`, while [`ReadAsync()`](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Security/KeyManagement/KubernetesSecretsRepository.cs#L60) us called with `Http1`. 

This results in keys being created for `http1` through the keys API, but they don't get back on read. 

#### Repro steps

1. Create an app on Kubernetes with a function named `Http1`
2. Call Keys API to create key `key1`
3. Call List Keys API

#### Expected behavior

To get 2 keys from the list keys API. `default` and `key1`

#### Actual behavior

only get back `default` key

#### Known workarounds

name functions in lowercase only

#### Related information 

/cc @pragnagopa

**Comment by pragnagopa** [comment]
cc @divyagandhisethi @TsuyoshiUshio fyi

**Comment by pragnagopa** [comment]
cc @fabiocav - fyi - tagging for hotfix for sprint 100

**Comment by ahmelsayed** [comment]
https://github.com/Azure/azure-functions-host/pull/7362
