### ISSUE TITLE
Application Insights - lost traces after package upgrade

### ISSUE THREAD

**Issue by CristianDorinFlorea** [Azure/azure-functions-host#7358]
We have a function app with service bus triggers. We're using Application Insights to monitor our application. 
We are referencing `Microsoft.ApplicationInsights.AspNetCore v2.15.0`.
This is how telemetry is configured in code:
```
public class Startup : FunctionsStartup
{
        public override void Configure(IFunctionsHostBuilder builder)
        {
           var instrumentationKey = Environment.GetEnvironmentVariable("APPINSIGHTS_INSTRUMENTATIONKEY", EnvironmentVariableTarget.Process);
            if (!string.IsNullOrWhiteSpace(instrumentationKey))
            {
                builder.Services.AddApplicationInsightsTelemetry(instrumentationKey);
            }
        }
}
```
In the Application Insights we are seeing the events like this:
![appinsights](https://user-images.githubusercontent.com/40396294/117657126-dec16780-b1a1-11eb-9f65-59f17b517796.png)

After upgrading to `Microsoft.ApplicationInsights.AspNetCore v2.16.0` or `v2.17.0` we cannot see the traces anymore.
Please see the the below screenshot and notice the differences.
![appinsights2png](https://user-images.githubusercontent.com/40396294/117662863-b5f0a080-b1a8-11eb-9ce7-6a84d6b157f8.png)

**Comment by v-anvari** [comment]
Thank you @CristianDorinFlorea , Shall try to reproduce this scenario and update you with findings

**Comment by v-anvari** [comment]
Hi @CristianDorinFlorea , I was unable to reproduce this issue in accordance with your scenario. Can you provide the repro steps so that I can get a reproduce the issue properly.
