### ISSUE TITLE
Sanitize strings before logging metric events

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#7369]
https://github.com/Azure/azure-functions-host/blob/d57f51ed8995c3acd07a0ded8de79af1680267ea/src/WebJobs.Script.WebHost/Diagnostics/MetricsEventManager.cs#L121-L149

**Comment by pragnagopa** [comment]
cc @@jcookems

**Comment by fabiocav** [comment]
@pragnagopa will you be looking at this or would you like us to have it assigned?

**Comment by fabiocav** [comment]
@pragnagopa ping

**Comment by pragnagopa** [comment]
Apologies missed ping here. Moving to next sprint. Will send a PR in the next few days

**Comment by pragnagopa** [comment]
PR opened! Please review
