### ISSUE TITLE
Centralize common code for ScriptBindingProvider

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#737]
E.g. in ScriptBindingProvider.DefaultType. We should see how we can push dealing with common things like cardinality etc. can be centralized so each extension doesn't have to implement it.

See [this pr](https://github.com/Azure/azure-webjobs-sdk-script/pull/735) for details.

**Comment by fabiocav** [comment]
@mathewc though a some of what you've described above hasn't been done, we've been able to get rid of most of that logic for all but a couple of extensions, so I'll go ahead and close this.

Feel free to reopen and comment if you feel there's still something we should be following up on.
