### ISSUE TITLE
Is there any tool/price level for keeping functions warm?

### ISSUE THREAD

**Issue by aronchick** [Azure/azure-functions-host#7374]
I'm getting a 404 occassionally - and only on the first request. Is there any way to keep the function warm such that it doesn't time out and return 404? Thanks!

**Comment by jormasyrja** [comment]
Do you mean you want to keep the **Function App** warm? In Premium tier, you will always have at least 1 instance of the App running warm.

For Consumption tier, the app instances are started when the first request comes in (cold start). To prevent this cold start, my team and I are using no-op **timer triggers** with fixed intervals (something like 5 minutes).

**Comment by aronchick** [comment]
Ok - this is exactly the problem - it's just cold start running on Consumption tier.

I wish there was a better way to handle it (responding the connection is alive and holding the connection open until it spins up) and/or better documentation (not just returning 404 - returning a custom error message / http error code that didn't imply the resource didn't exist) and/or a simpler way to upgrade your Linux instance (I know, it's being worked on).

**Comment by balag0** [comment]
@aronchick yes, we might have a bug where misleading status codes are being returned sometimes. Could you share the approx. timestamp and the appname using https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately  from when you last saw this issue.

**Comment by v-bbalaiagar** [comment]
Hi @aronchick, Can you please provide the above requested details.

**Comment by aronchick** [comment]
I'm so sorry - i long since deleted it.

You could take a shot at repro-ing by just checking the error code on a function that has been shut down / is in cold start.
________________________________

**Comment by v-bbalaiagar** [comment]
Hi @aronchick, The error is a known issue as mentioned above, Can you please provide if there is a way to repro the issue.

**Comment by aronchick** [comment]
i have long since deleted it - what's the error you get when requesting a curl from a cold function? if it's not 400, maybe you fixed it?

**Comment by v-bbalaiagar** [comment]
Hi @balag0, Can you please confirm if it is fixed or if there is a tracking issue.

**Comment by balag0** [comment]
Its still pending but being tracked elsewhere. So lets close this issue.
