### ISSUE TITLE
[Kubenetes] Update sync triggers to include host.json as this needed to build scaled objects

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#7382]
Build server running in kubernetes is responsible for generating scaled objects needed for Keda Scalers

For Durable Triggers - information from host.json is needed.

**Comment by pragnagopa** [comment]
cc @divyagandhisethi - we need to take hotfix for this

**Comment by ahmelsayed** [comment]
related https://github.com/Azure/azure-functions-host/issues/7288

**Comment by TsuyoshiUshio** [comment]
Done by the PR.
