### ISSUE TITLE
Running in-memory .NET 5 isolated-process host for integration testing

### ISSUE THREAD

**Issue by joshmouch** [Azure/azure-functions-host#7384]
Since the .NET 5 isolated process functions basically act like a console application, I'm thinking it should be possible to create an in-memory host to use for integration tests, similar to the ASP.Net core TestHost.

Is this a supported scenario?  Do you know what issues I may run into?  Is creating a TestHost on your roadmap already?

Just as a simple test, I tried the following in an xunit constructor, and I get the following exception in `GrpcServiceCollectionExtensions`:

```
var hostBuilder = new HostBuilder()
				.ConfigureFunctionsWorkerDefaults()
				.ConfigureServices(s =>
				{
					//s.AddSingleton<IHttpResponderService, DefaultHttpResponderService>();
				})
				.Build();
hostBuilder.RunAsync();
```

```
// System.UriFormatException: 'Invalid URI: The hostname could not be parsed.'
// arguments.Host is null, which is probably why

                GrpcChannel grpcChannel = GrpcChannel.ForAddress($"http://{arguments.Host}:{arguments.Port}", new GrpcChannelOptions()
                {
                    Credentials = ChannelCredentials.Insecure
                });

```

**Comment by v-anvari** [comment]
Hi @joshmouch , Thank you for your feedback! Checking the possibilities internally. 

cc @ankitkumarr , for any comments

**Comment by v-anvari** [comment]
Hi @joshmouch , Apologies for the delayed response, the team is working on this feature or approach already and you can find the updates in the following link - [Implement test worker/test framework · Issue #281 · Azure/azure-functions-dotnet-worker (github.com)](https://github.com/Azure/azure-functions-dotnet-worker/issues/281). 

Closing this issue as all the updates will be provided there.
