### ISSUE TITLE
Refactor the SyncTrigger extensions payload to make it generic

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-host#7394]
#### What problem would the feature you're requesting solve? Please describe.
Currently as a tactical solution for LIMA scenarios, FunctionsSyncManager is adding the extensions portion of host.json to the sync triggers payload only for Kubernetes environments. We want to remove that restriction so it's applied in other environments as well, which will allow us to address https://github.com/Azure/azure-functions-host/issues/5390 in a general manner.

For more details see the discussion in : https://github.com/Azure/azure-functions-host/pull/7386

CC: @pragnagopa @mathewc @cgillum 

#### Describe the solution you'd like
Make the `extensions` payload to generic so it's always returned, not based on sku/environment. We'll need to update the minimal response that is returned when the full payload `{ triggers: [], functions: [], extensions: {}, secrets: {} }` is over the size limit. The new minimal format will be `{ triggers: [], extensions: {} }`. This way, consumers can rely on host level extensions config in addition to the functions config already included in the triggers data.

#### Describe alternatives you've considered
We can keep it only available for Kubernetes Environment, However, Container usage for the AppService will be the same. 

#### Additional context
We considered the PR https://github.com/Azure/azure-functions-host/pull/7386 as hot fix. We need to refactor and add proper test for the generic usage.

**Comment by pragnagopa** [comment]
@TsuyoshiUshio  - would you like to address this sometime in future as you have most context?

**Comment by TsuyoshiUshio** [comment]
@pragnagopa  Yes. absolutely.

**Comment by pragnagopa** [comment]
cc @mathewc  

@TsuyoshiUshio  - Please address comments - https://github.com/Azure/azure-functions-host/pull/7386#discussion_r637004808 as well as part of this fix.

**Comment by fabiocav** [comment]
@TsuyoshiUshio are you planning on working on this item as part of spring 103? Can we have a quick sync on this to talk about the proposed solution?

**Comment by mathewc** [comment]
Yes - before anything is checked in for this, I need to review. The general goals for this are captured in https://github.com/Azure/azure-functions-host/issues/5390.

**Comment by TsuyoshiUshio** [comment]
Not for todays deployment. I'd happy to discuss the design first! It should requires careful testing.

**Comment by TsuyoshiUshio** [comment]
I'd like to know the counter microservices spec at first. I mean I'd like to research the pattern How the SyncTrigger Payload is used. I know the usage of Kubernetes environment with KuduLite, However, I don't know about the other use cases. Do you know the pointer?

**Comment by fabiocav** [comment]
@TsuyoshiUshio moving this to the triaged milestone until we have a chance to discuss.

**Comment by pragnagopa** [comment]
Tagging @chiangvincent and @cachai2 - this needed for Scale Controller changes - Target Based Scaling feature

**Comment by pragnagopa** [comment]
Tagging @mathewc - as FYI for discussions and review

**Comment by fabiocav** [comment]
Is there a proposed design for this? Can we sync on a design prior to having this assigned to a sprint?

**Comment by mathewc** [comment]
Recommend closing this test PR and opening a new PR with production code. In general that PR will:

1. Add the "extensions" and "concurrency" sections to the sync triggers payload in both full and minimal formats. I.e. the minimal format returned when ArmCacheEnabled is true or when the full payload is oversize will now be an object format always including these two properties in addition to "triggers"
2. For minimal format, we'll no longer return an array format - we'll always return object. That ensures we can always include these properties. ScaleController and other consumers already handle both array and object formats of course.
3. Remove the Kubernetes specific changes added in https://github.com/Azure/azure-functions-host/pull/7386/files

**Comment by kashimiz** [comment]
Marking this as in-progress as a PR by Tsuyoshi is under review: https://github.com/Azure/azure-functions-host/pull/7863

**Comment by TsuyoshiUshio** [comment]
We decide to create a separate API `admin/host/extensions/config` for fetching the host.json with AppSertings/default value. 
I'm going to share the Pull Request.
