### ISSUE TITLE
.Net 5 (dotnet-isolated) Some metrics are not recorded for some periods

### ISSUE THREAD

**Issue by NeilMacMullen** [Azure/azure-functions-host#7399]
The "Thread Count", "Connections" and "Handle Count" metrics are measured as zero for long periods even though the function is running normally (as verified from logging),  "Memory Working Set" does show sensible values however.

![image](https://user-images.githubusercontent.com/9131337/119225370-3f826580-bafb-11eb-8186-327deccaafde.png)

The in-app process count during this period is clearly not zero.  "ProcessThreads" here is ` Process.GetCurrentProcess().Threads.Count`   Other numbers are from ThreadPool.GetAvailable/GetMax

```
5/22/2021, 9:21:11.651 AM	Function Ended Threads used: 0/682 comp: 1/1000 ProcessThreads:13	
5/22/2021, 9:21:11.648 AM	0 messages to process Threads used: 0/682 comp: 1/1000 ProcessThreads:13	
5/22/2021, 9:21:11.648 AM	44 messages processed in 11637ms Threads used: 0/682 comp: 1/1000 ProcessThreads:13	
5/22/2021, 9:21:10.391 AM	7 messages to process Threads used: 0/682 comp: 1/1000 ProcessThreads:13	
5/22/2021, 9:21:00.020 AM	37 messages to process Threads used: 0/682 comp: 1/1000 ProcessThreads:13	
5/22/2021, 9:21:00.010 AM	Function started Threads used: 2/682 comp: 1/1000 ProcessThreads:13	
5/22/2021, 9:20:13.883 AM	Function Ended Threads used: 0/682 comp: 1/1000 ProcessThreads:14	
5/22/2021, 9:20:13.880 AM	0 messages to process Threads used: 0/682 comp: 1/1000 ProcessThreads:14	
5/22/2021, 9:20:13.880 AM	41 messages processed in 13857ms Threads used: 0/682 comp: 1/1000 ProcessThreads:14	
5/22/2021, 9:20:13.856 AM	1 messages to process Threads used: 0/682 comp: 1/1000 ProcessThreads:14	
5/22/2021, 9:20:13.542 AM	2 messages to process Threads used: 0/682 comp: 1/1000 ProcessThreads:14	
5/22/2021, 9:20:11.771 AM	5 messages to process Threads used: 0/682 comp: 1/1000 ProcessThreads:14	
5/22/2021, 9:20:00.044 AM	33 messages to process Threads used: 0/682 comp: 1/1000 ProcessThreads:13	
5/22/2021, 9:20:00.024 AM	Function started Threads used: 1/682 comp: 0/1000 ProcessThreads:13	
5/22/2021, 9:19:10.472 AM	Function Ended Threads used: 0/682 comp: 1/1000 ProcessThreads:13	
5/22/2021, 9:19:10.469 AM	38 messages processed in 10470ms Threads used: 0/682 comp: 1/1000 ProcessThreads:13	
5/22/2021, 9:19:10.469 AM	0 messages to process Threads used: 0/682 comp: 1/1000 ProcessThreads:13	
5/22/2021, 9:19:08.925 AM	6 messages to process Threads used: 0/682 comp: 1/1000 ProcessThreads:13	
5/22/2021, 9:18:59.999 AM	Function started Threads used: 2/682 comp: 0/1000 ProcessThreads:12	
5/22/2021, 9:18:59.998 AM	32 messages to process Threads used: 0/682 comp: 1/1000 ProcessThreads:12	
```

Same function as in this issue: https://github.com/Azure/azure-functions-host/issues/7389

#### Investigative information

Please provide the following:

- Timestamp: 07:00 - 11:00 22nd May 2021 (UTC)
- Function App version: dotnet-isolated (latest sdk)
- Function App name: Ingestion
- Function name(s) (as appropriate): Ingestion
- Invocation ID: One of these two I assume?
```
 Executing 'Functions.Ingestion' (Reason='Timer fired at 2021-05-22T11:46:00.0073204+00:00', Id=76a011dd-42fe-4d67-bed4-0a59a5323a21) 
Executed 'Functions.Ingestion' (Succeeded, Id=818b3541-4e6a-457b-8b0d-6b0600680c25, Duration=9152ms)
```

- Region: West-US2

**Comment by v-anvari** [comment]
Hi @NeilMacMullen , I have checked the logs for the mentioned App name, but I don't see any errors in the backend. This looks like it is coming from the front end and the metrics are wrong shown. Can we get the repro steps so that we can reproduce it from our end.

**Comment by NeilMacMullen** [comment]
@v-anvari  Yes I agree it is an issue with presentation/measurement.  I'm afraid I don't have any suggestion for repro steps except to say "run the function (dotnet-isolated) and look at the thread count metric after 24 hours."

FWIW, Here is the thread-count and "working memory set"  trace over the last 72 hours showing the problem has occurred twice...  It's interesting the working memory shows drops at the time the thread count zeroes-out.  Not sure if that is just a variation of the same measurement problem or a clue...

![image](https://user-images.githubusercontent.com/9131337/119337639-ff4fee00-bc86-11eb-9786-7f37c6012d70.png)

**Comment by NeilMacMullen** [comment]
And here's a trace  (working memory/thread count) from a different function.  Again, the function is running fine despite the alarming chart apparently showing it stopped using any threads a few days ago!

![image](https://user-images.githubusercontent.com/9131337/119338922-7d60c480-bc88-11eb-84ae-cd004c3e6cd4.png)

**Comment by v-anvari** [comment]
Hi @NeilMacMullen , I would suggest the same approach here as well, to diagnose the memory dump like suggested here [7389](https://github.com/Azure/azure-functions-host/issues/7389) . A support request can help you understand the issue as well. As both the issues are coming from the client side

**Comment by NeilMacMullen** [comment]
@v-anvari   As with the other issue, I don't consider this a bug in "my" code.  It may not be caused by the function-host; it could be a problem with the portal, the health monitor or whatever other component is responsible for collecting and presenting the ThreadCount metric.  However all those things are owned by Microsoft and I'd hope that there would enough internal communication between teams that someone would take ownership of this.

As before, I'm happy to supply or collect further information that would help Microsoft debug this.

**Comment by v-anvari** [comment]
Thank you for the feedback, yes, the issue doesn't seem to be coming from the code, but from the client side or the issue is from the portal. As suggested, if you can submit a support request from you subscription, the support team will be able to help. The support team will have control over the front end of your application. We are happy to help you, but I don't see any error in the backed logs. Opening an incident should be helpful in diagnosing the issue.

Since both the issues are different from each other, as there is leakage, it will be helpful for us to understand where are the threads being consumed, from the memory dump.
