### ISSUE TITLE
Azure function optional parameter does not work

### ISSUE THREAD

**Issue by ruifrvaz** [Azure/azure-functions-host#7418]
As the name suggests, optional parameter is not working for me when hosted in azure.

I have tried both optional as {name?} and {name:alpha?}. Both work locally, but when I deploy and test on azure, it returns 404 resource not found whenever I run without parameter. Further looking into application insights the error message is "Unable to match incoming request to an operation."

Here are the function specifications. Removing ? (optional modifier) returns 200, but the parameter is no longer optional:

[HttpTrigger(AuthorizationLevel.Function, "POST", Route = Route + "/Import/{name?}")] HttpRequest req,
            [Table("mappings")] CloudTable mappingsTable, string name)

// function.json

{
  "generatedBy": "Microsoft.NET.Sdk.Functions-3.0.9",
  "configurationSource": "attributes",
  "bindings": [
    {
      "type": "httpTrigger",
      "route": "test/Import/{name?}", // {name:alpha?} does not work either
      "methods": [
        "POST"
      ],
      "authLevel": "function",
      "name": "req"
    }
  ],
  "disabled": false,
  "scriptFile": "../bin/ING.CDaaS.AzdoSNowSync.Functions.dll",
  "entryPoint": "ING.CDaaS.AzdoSNowSync.Functions.MappingsFunctions.ImportMappings"
}

// host.json

{
  "version": "2.0",
  "functionTimeout": "03:00:00",
  "logging": {
    "logLevel": {
      "default": "Information",
      "Host": "Information",
      "Function": "Information"
    }
}

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

calling "test/Import/" without {name} actually works

#### Actual behavior

404 operation not found.

any help is greatly appreciated.

*update*

it might be worth mentioning that i am using apim as a proxy to the azure function. here is the apim configuration:

{
      "type": "Microsoft.ApiManagement/service/apis/operations",
      "apiVersion": "2019-01-01",
      "name": "[concat(variables('apiManagementMappingsApiName'), '/import')]",
      "dependsOn": [
        "[resourceId('Microsoft.ApiManagement/service/apis', parameters('apiManagementName'), 'Import')]"
      ],
      "properties": {
        "displayName": "Import",
        "method": "POST",
        "urlTemplate": "test/import/{name}",
        "templateParameters": [
          {
            "name": "name",
            "required": false,
            "values": [],
            "type": "string"
          }
        ],
        "responses": []
      }
    }

Could it be wrong at the apim level? If so i would not expect to receive a 404 at the function, but already at apim.

**Comment by ruifrvaz** [comment]
hi @v-anvari  and @brettsam  i have updated the documentation to include the apim proxy.

**Comment by v-anvari** [comment]
Hi @ruifrvaz , Thank you for your feedback! To investigate this further, could we get some more information on the project scenario. Can we get the repro steps and which version of .Net are you using.

To the latest comment, What documentation is it. Could you give us more details

 I see few fixes to similar issue in the past - https://github.com/Azure/azure-functions-host/issues/2419

**Comment by ruifrvaz** [comment]
Hi, I am using .netcore 3.1.
I think the problem might be with APIM and not the function parameter. What confused me is that the operation error ended up in the function application insights but that might be because of the way the function was configured.

I will try to reproduce this myself and get back to you.

**Comment by v-anvari** [comment]
Thank you for the update
