### ISSUE TITLE
Function host shuts with An unhandled exception has occurred. Host is shutting down.

### ISSUE THREAD

**Issue by CarlosOnline** [Azure/azure-functions-host#7419]
Function host shuts down causing function calls to end prematurely.

There is almost no information as to where the error comes from and why the function host is shutting down.

I suspect it has to do with Storage exception since the next expected action is to place a message on a storage queue.  This action doesn't take place.  Instead the function host shuts down.

Can you please help with diagnosing / investigating the issue?

5/28/2021, 6:03:40 AM | An unhandled exception has occurred. Host is shutting down. | 3 | trace | {"prop__{OriginalFormat}":"An unhandled exception has occurred. Host is shutting down.","HostInstanceId":"6d3955e0-e542-4dd3-83dd-461cc258b088","ProcessId":"1","Category":"Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostExceptionHandler","LogLevel":"Error"} | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | PC | &nbsp; | &nbsp; | 0.0.0.0 | &nbsp; | &nbsp; | &nbsp; | &nbsp; | azure-function-optimize-fa | 73120cbfb6e2e69174b2b0f69117c0e77bf859ec66594fb9b8cdd930a699002f | ae1cec4f-4a88-4c48-be00-9e37070e6ee3 | azure-function-opt-fa | 57a4cc0f-05d2-4628-8395-5fa30efc357e | azurefunctions: 3.0.15725.0 | 261b019f-bfb5-11eb-869c-2818787afd49 | 1 | azure-function-opt-fa | &nbsp;
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
5/28/2021, 5:59:04 AM | Calling StopAsync on the registered listeners | 1 | trace | {"prop__{OriginalFormat}":"Calling StopAsync on the registered listeners","HostInstanceId":"6d3955e0-e542-4dd3-83dd-461cc258b088","ProcessId":"1","Category":"Microsoft.Azure.WebJobs.Host.DrainModeManager","LogLevel":"Information"} | &nbsp; | &nbsp; | f08038a9d6566d4fb198dc5250e5f7a7 | ac49de4423f14c49 | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | PC | &nbsp; | &nbsp; | 0.0.0.0 | &nbsp; | &nbsp; | &nbsp; | &nbsp; | azure-function-optimize-fa | 73120cbfb6e2e69174b2b0f69117c0e77bf859ec66594fb9b8cdd930a699002f | ae1cec4f-4a88-4c48-be00-9e37070e6ee3 | azure-function-opt-fa | 57a4cc0f-05d2-4628-8395-5fa30efc357e | azurefunctions: 3.0.15725.0 | 92c3f524-bfb4-11eb-869c-2818787aa000 | 1 | azure-function-opt-fa | &nbsp;
5/28/2021, 5:59:04 AM | Requesting cancellation for function invocation '6730c137-e2a7-48f9-9f9a-3051307eca20' | 1 | trace | {"prop__{OriginalFormat}":"Requesting cancellation for function invocation '{invocationId}'","HostInstanceId":"6d3955e0-e542-4dd3-83dd-461cc258b088","ProcessId":"1","Category":"Microsoft.Azure.WebJobs.Host.DrainModeManager","LogLevel":"Information","prop__invocationId":"6730c137-e2a7-48f9-9f9a-3051307eca20"} | &nbsp; | &nbsp; | f08038a9d6566d4fb198dc5250e5f7a7 | ac49de4423f14c49 | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | PC | &nbsp; | &nbsp; | 0.0.0.0 | &nbsp; | &nbsp; | &nbsp; | &nbsp; | azure-function-optimize-fa | 73120cbfb6e2e69174b2b0f69117c0e77bf859ec66594fb9b8cdd930a699002f | ae1cec4f-4a88-4c48-be00-9e37070e6ee3 | azure-function-opt-fa | 57a4cc0f-05d2-4628-8395-5fa30efc357e | azurefunctions: 3.0.15725.0 | 92c3f523-bfb4-11eb-869c-2818787aa000 | 1 | azure-function-opt-fa | &nbsp;
5/28/2021, 5:59:04 AM | DrainMode mode enabled | 1 | trace | {"prop__{OriginalFormat}":"DrainMode mode enabled","HostInstanceId":"6d3955e0-e542-4dd3-83dd-461cc258b088","ProcessId":"1","Category":"Microsoft.Azure.WebJobs.Host.DrainModeManager","LogLevel":"Information"} | &nbsp; | &nbsp; | f08038a9d6566d4fb198dc5250e5f7a7 | ac49de4423f14c49 | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | PC | &nbsp; | &nbsp; | 0.0.0.0 | &nbsp; | &nbsp; | &nbsp; | &nbsp; | azure-function-optimize-fa | 73120cbfb6e2e69174b2b0f69117c0e77bf859ec66594fb9b8cdd930a699002f | ae1cec4f-4a88-4c48-be00-9e37070e6ee3 | azure-function-opt-fa | 57a4cc0f-05d2-4628-8395-5fa30efc357e | azurefunctions: 3.0.15725.0 | 92c3f522-bfb4-11eb-869c-2818787aa000 | 1 | azure-function-opt-fa | &nbsp;
5/28/2021, 5:58:44 AM | Call to StopAsync complete, registered listeners are now stopped | 1 | trace | {"prop__{OriginalFormat}":"Call to StopAsync complete, registered listeners are now stopped","HostInstanceId":"0d38902d-bad0-4a7a-815f-a2b5c1111f99","ProcessId":"1","Category":"Microsoft.Azure.WebJobs.Host.DrainModeManager","LogLevel":"Information"} | &nbsp; | &nbsp; | f3f9d79b917f6d4dadd18f2110c59b2f | f8b9e011adfe474c | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | PC | &nbsp; | &nbsp; | 0.0.0.0 | &nbsp; | &nbsp; | &nbsp; | &nbsp; | azure-function-optimize-fa | 62d27af4c7afd8755b10cf9736a2c8186712b453be2c4c5a04e300d061b6a4dd | ae1cec4f-4a88-4c48-be00-9e37070e6ee3 | azure-function-opt-fa | 57a4cc0f-05d2-4628-8395-5fa30efc357e | azurefunctions: 3.0.15725.0 | 8e0d6f2b-bfb4-11eb-869c-501ac5ba468c | 1 | azure-function-opt-fa | &nbsp;
5/28/2021, 5:58:44 AM | Calling StopAsync on the registered listeners | 1 | trace | {"prop__{OriginalFormat}":"Calling StopAsync on the registered listeners","HostInstanceId":"0d38902d-bad0-4a7a-815f-a2b5c1111f99","ProcessId":"1","Category":"Microsoft.Azure.WebJobs.Host.DrainModeManager","LogLevel":"Information"} | &nbsp; | &nbsp; | f3f9d79b917f6d4dadd18f2110c59b2f | f8b9e011adfe474c | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | PC | &nbsp; | &nbsp; | 0.0.0.0 | &nbsp; | &nbsp; | &nbsp; | &nbsp; | azure-function-optimize-fa | 62d27af4c7afd8755b10cf9736a2c8186712b453be2c4c5a04e300d061b6a4dd | ae1cec4f-4a88-4c48-be00-9e37070e6ee3 | azure-function-opt-fa | 57a4cc0f-05d2-4628-8395-5fa30efc357e | azurefunctions: 3.0.15725.0 | 8e0d6f2a-bfb4-11eb-869c-501ac5ba468c | 1 | azure-function-opt-fa | &nbsp;
5/28/2021, 5:58:44 AM | DrainMode mode enabled | 1 | trace | {"prop__{OriginalFormat}":"DrainMode mode enabled","HostInstanceId":"0d38902d-bad0-4a7a-815f-a2b5c1111f99","ProcessId":"1","Category":"Microsoft.Azure.WebJobs.Host.DrainModeManager","LogLevel":"Information"} | &nbsp; | &nbsp; | f3f9d79b917f6d4dadd18f2110c59b2f | f8b9e011adfe474c | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | PC | &nbsp; | &nbsp; | 0.0.0.0 | &nbsp; | &nbsp; | &nbsp; | &nbsp; | azure-function-optimize-fa | 62d27af4c7afd8755b10cf9736a2c8186712b453be2c4c5a04e300d061b6a4dd | ae1cec4f-4a88-4c48-be00-9e37070e6ee3 | azure-function-opt-fa | 57a4cc0f-05d2-4628-8395-5fa30efc357e | azurefunctions: 3.0.15725.0 | 8e0d6f29-bfb4-11eb-869c-501ac5ba468c | 1 | azure-function-opt-fa | &nbsp;
5/28/2021, 5:58:40 AM | CreateProductionPlan response: OK OK siteId: [c85f0552-131d-4924-b90c-e69e53d6a297] planType: [Initial%20Plan] productionDay: [2021-05-27] | 1 | trace | {"prop__{OriginalFormat}":"CreateProductionPlan response: OK OK siteId: [c85f0552-131d-4924-b90c-e69e53d6a297] planType: [Initial%20Plan] productionDay: [2021-05-27]","HostInstanceId":"6d3955e0-e542-4dd3-83dd-461cc258b088","InvocationId":"6730c137-e2a7-48f9-9f9a-3051307eca20","ProcessId":"1","Category":"CustomerPlanning.Client.CustomerPlanningClient","LogLevel":"Information"} | &nbsp; | RunOptimization | 6dc9421cfa141745af40aef097f55195 | 1763f9a186cb274a | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | PC | &nbsp; | &nbsp; | 0.0.0.0 | &nbsp; | &nbsp; | &nbsp; | &nbsp; | azure-function-optimize-fa | 73120cbfb6e2e69174b2b0f69117c0e77bf859ec66594fb9b8cdd930a699002f | ae1cec4f-4a88-4c48-be00-9e37070e6ee3 | azure-function-opt-fa | 57a4cc0f-05d2-4628-8395-5fa30efc357e | azurefunctions: 3.0.15725.0 | 92c3f51f-bfb4-11eb-869c-2818787aa000 | 1 | azure-function-opt-fa | &nbsp;
5/28/2021, 5:58:40 AM | CreateProductionPlan post: https://azure-function-customer-fa.azurewebsites.net/api/planning/customer/optimization/production-plan/site/c85f0552-131d-4924-b90c-e69e53d6a297/plan-type/Initial%20Plan/production-day/2021-05-27/created-by/carlos | 1 | trace | {"prop__{OriginalFormat}":"CreateProductionPlan post: https://azure-function-customer-fa.azurewebsites.net/api/planning/customer/optimization/production-plan/site/c85f0552-131d-4924-b90c-e69e53d6a297/plan-type/Initial%20Plan/production-day/2021-05-27/created-by/carlos","HostInstanceId":"6d3955e0-e542-4dd3-83dd-461cc258b088","InvocationId":"6730c137-e2a7-48f9-9f9a-3051307eca20","ProcessId":"1","Category":"CustomerPlanning.Client.CustomerPlanningClient","LogLevel":"Information"} | &nbsp; | RunOptimization | 6dc9421cfa141745af40aef097f55195 | 1763f9a186cb274a | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | PC | &nbsp; | &nbsp; | 0.0.0.0 | &nbsp; | &nbsp; | &nbsp; | &nbsp; | azure-function-optimize-fa | 73120cbfb6e2e69174b2b0f69117c0e77bf859ec66594fb9b8cdd930a699002f | ae1cec4f-4a88-4c48-be00-9e37070e6ee3 | azure-function-opt-fa | 57a4cc0f-05d2-4628-8395-5fa30efc357e | azurefunctions: 3.0.15725.0 | 92c3f51e-bfb4-11eb-869c-2818787aa000 | 1 | azure-function-opt-fa | &nbsp;
5/28/2021, 5:58:40 AM | CreateProductionPlan started. siteId: [c85f0552-131d-4924-b90c-e69e53d6a297] planType: [Initial Plan] productionDay: [2021-05-27] createdByEmail: [carlos] | 1 | trace | {"prop__{OriginalFormat}":"CreateProductionPlan started. siteId: [c85f0552-131d-4924-b90c-e69e53d6a297] planType: [Initial Plan] productionDay: [2021-05-27] createdByEmail: [carlos]","HostInstanceId":"6d3955e0-e542-4dd3-83dd-461cc258b088","InvocationId":"6730c137-e2a7-48f9-9f9a-3051307eca20","ProcessId":"1","Category":"CustomerPlanning.Client.CustomerPlanningClient","LogLevel":"Information"} | &nbsp; | RunOptimization | 6dc9421cfa141745af40aef097f55195 | 1763f9a186cb274a | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | PC | &nbsp; | &nbsp; | 0.0.0.0 | &nbsp; | &nbsp; | &nbsp; | &nbsp; | azure-function-optimize-fa | 73120cbfb6e2e69174b2b0f69117c0e77bf859ec66594fb9b8cdd930a699002f | ae1cec4f-4a88-4c48-be00-9e37070e6ee3 | azure-function-opt-fa | 57a4cc0f-05d2-4628-8395-5fa30efc357e | azurefunctions: 3.0.15725.0 | 92c3f51d-bfb4-11eb-869c-2818787aa000 | 1 | azure-function-opt-fa | &nbsp;
5/28/2021, 5:58:40 AM | Run optimization for c85f0552-131d-4924-b90c-e69e53d6a297 Initial Plan 05/27/2021 00:00:00 1 | 1 | trace | {"prop__{OriginalFormat}":"Run optimization for c85f0552-131d-4924-b90c-e69e53d6a297 Initial Plan 05/27/2021 00:00:00 1","HostInstanceId":"6d3955e0-e542-4dd3-83dd-461cc258b088","InvocationId":"6730c137-e2a7-48f9-9f9a-3051307eca20","ProcessId":"1","Category":"Optimization.Lib.OptimizationApi","LogLevel":"Information"} | &nbsp; | RunOptimization | 6dc9421cfa141745af40aef097f55195 | 1763f9a186cb274a | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; | PC | &nbsp; | &nbsp; | 0.0.0.0 | &nbsp; | &nbsp; | &nbsp; | &nbsp; | azure-function-optimize-fa | 73120cbfb6e2e69174b2b0f69117c0e77bf859ec66594fb9b8cdd930a699002f | ae1cec4f-4a88-4c48-be00-9e37070e6ee3 | azure-function-opt-fa | 57a4cc0f-05d2-4628-8395-5fa30efc357e | azurefunctions: 3.0.15725.0 | 92c3f51c-bfb4-11eb-869c-2818787aa000 | 1 | azure-function-opt-fa | &nbsp;
&nbsp;

<br class="Apple-interchange-newline">

**Comment by v-bbalaiagar** [comment]
Hi @CarlosOnline, Thank you for reaching out to us, checking internally on this issue.

**Comment by v-bbalaiagar** [comment]
Hi @CarlosOnline, Can we know the region to check the back end logs to understand the cause. Meanwhile, we would like to also clone the scenario that you are trying. Could you please provide us the repro steps for the same.

**Comment by CarlosOnline** [comment]
West Europe

**Comment by CarlosOnline** [comment]
I don't have a repro.  The function app was deployed and that was it.  Sometimes there are no calls to it and it shutsdown any way.  I am pretty sure it has to do with the QueueTriggers.  There are 3 QueueTrigger functions and Application Insight errors come in threes.

Have attached export templates for the azure function, storage account, and a function.json for a queue trigger.


[Op.zip](https://github.com/Azure/azure-functions-host/files/6625592/Op.zip)

**Comment by CarlosOnline** [comment]
Got a call stack from diagnostics and troubleshooting.  It really looks like the Azure Function cannot access Storage Queues.  The Azure function is in a Vnet.

```
Got the stack trace for the Connection timed out error.  It looks like the azure function can't connect to the Storage queues.

Container exited unexpectedly: last 10 seconds logs [2021-06-09T18:09:46.903586779Z  Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostExceptionHandler[0]
2021-06-09T18:09:46.903617581Z       An unhandled exception has occurred. Host is shutting down.
2021-06-09T18:09:46.903623482Z Microsoft.Azure.Storage.StorageException: Connection timed out
2021-06-09T18:09:46.903635183Z  ---> System.Net.Http.HttpRequestException: Connection timed out
2021-06-09T18:09:46.903639883Z  ---> System.Net.Sockets.SocketException (110): Connection timed out
2021-06-09T18:09:46.903644383Z    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
2021-06-09T18:09:46.903658484Z    --- End of inner exception stack trace ---
2021-06-09T18:09:46.903662684Z    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
2021-06-09T18:09:46.903666785Z    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
2021-06-09T18:09:46.903670885Z    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2021-06-09T18:09:46.903674885Z    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2021-06-09T18:09:46.903678986Z    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
2021-06-09T18:09:46.903683186Z    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2021-06-09T18:09:46.903687186Z    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2021-06-09T18:09:46.903691187Z    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2021-06-09T18:09:46.903695487Z    at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
2021-06-09T18:09:46.903699587Z    --- End of inner exception stack trace ---
2021-06-09T18:09:46.903703487Z    at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
2021-06-09T18:09:46.903708988Z    at Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener.ExecuteAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Queues\Listeners\QueueListener.cs:line 193
2021-06-09T18:09:46.903714088Z    at Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.RunAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Timers\TaskSeriesTimer.cs:line 147
2021-06-09T18:09:46.903718788Z Request Information
2021-06-09T18:09:46.903722589Z RequestID:
2021-06-09T18:09:46.903726289Z RequestDate:
2021-06-09T18:09:46.903730089Z StatusMessage:
2021-06-09T18:09:46.903733790Z ErrorCode:
```

**Comment by v-bbalaiagar** [comment]
Hi @CarlosOnline, The best recommendation here is that you need to configure the Vnet properly to talk to the endpoints. 
Also, Can you please go through the [blog ](https://blog.brooksjc.com/2021/04/22/azure-functions-access-to-restricted-storage-accounts/)which addresses similar scenario where the blog talks about Vnet.

Please check and let us know if this helps.

**Comment by CarlosOnline** [comment]
This is not a vnet issue I removed the QueueTrigger and polled the queues myself and it works. You need to fix the QueueTrigger code to not take down the Azure function

**Comment by v-bbalaiagar** [comment]
Hi @CarlosOnline,  Apologies for the delayed response. I couldn't reach your function's backend logs.
Can you please go through the document here- https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=python
Also, Can you please go through the SO which addresses similar scenario- https://stackoverflow.com/questions/64034389/using-blobtrigger-with-azurite-crashes-function-host

Please check and let us know if you are able to solve with the above information.
