### ISSUE TITLE
.net 5 , Unable to resolve service for type 'Microsoft.Extensions.Configuration.AzureAppConfiguration.IConfigurationRefresherProvider'

### ISSUE THREAD

**Issue by reddaiahnethi** [Azure/azure-functions-host#7420]
Created a Azure HTTP Trigger Function in .net5 

Facing below issue, when I have IConfigurationRefresherProvider as DI
Unable to resolve service for type 'Microsoft.Extensions.Configuration.AzureAppConfiguration.IConfigurationRefresherProvider'

I have the below in program.cs, still facing this the above issue.

 configurationBuilder.AddAzureAppConfiguration((options) =>
            {
                options.Connect(configuration["AppConfigConnectionString"]);
                options.ConfigureRefresh(refreshOptions =>
                {
                    refreshOptions.Register("RefresherKey", "ConnectService", refreshAll: true);
                    refreshOptions.Register("RefresherKey", "Impersonation", refreshAll: true);
                })
                .Select(KeyFilter.Any, "ConnectService")
                .Select(KeyFilter.Any, "Impersonation")
                .ConfigureKeyVault(keyVaultOptions =>
                {
                    keyVaultOptions.SetCredential(new DefaultAzureCredential());
                });
                configurationRefresher = options.GetRefresher();
            });

            configuration = configurationBuilder.Build();

**Comment by v-bbalaiagar** [comment]
Hi @reddaiahnethi, Thank you for reaching out to us, checking internally on this issue.

**Comment by v-bbalaiagar** [comment]
Hi @reddaiahnethi, We would like to know the detailed exception stack and Can we have the repro steps, in order to understand what is happening here.
