### ISSUE TITLE
[Ver 3.0.12] Could not evaluate 'Cosmos.CRTCompat.dll' for extension metadata. 

### ISSUE THREAD

**Issue by zhenyuan0502** [Azure/azure-functions-host#7422]
I facing this message again in version `3.0.12`
![image](https://user-images.githubusercontent.com/16673159/120354445-a0484400-c32c-11eb-88d0-d16ce6f79524.png)

As this topic has fixed in `3.0.7` (I confirmed the message has gone when I downgraded to `3.0.7`-`3.0.11`  
https://github.com/Azure/azure-functions-host/issues/5963#issue-610805945

**Comment by v-bbalaiagar** [comment]
Hi @zhenyuan0502, This issue is already considered for a fix and the updates will be given there.

Closing this issue as duplicate. For more updates please follow the space - https://github.com/Azure/azure-functions-host/issues/6899
