### ISSUE TITLE
Need support for store connection details in KeyVault and read it in Azure Functions

### ISSUE THREAD

**Issue by kanagaraj2503** [Azure/azure-functions-host#7425]
##Not sure whether we have option to store the connection String in Keyvault and retrieve it in azure functions, whether is it currently supported in Azure Functions? If supported, please share the sample code to retrieve in Functions. 

Also how to support in **[StorageAccount("ConnectionKey")]** Attribute at the function class level whereas ConnectionKey right now read it from AppSetting Key (say e.g., "ConnectionKey"), does it only support from config file key or still support to read it from KeyVault ?

### Project Requirement:
Currently _AzureWebJobStorage_ and _AzureStorage_ storage connection details are stored in appsettings.json file, since this is not good practice to expose the secrets in config file, so need to move the Azure storage connection details to Keyvault and read it from Keyvault.

**Comment by zhenyuan0502** [comment]
I have tested it on Configuration settings on deployed Azure Function, the first is I used the key-vault uri created by Azure Portal, then the uri, such like `https://your-keyvault.vault.azure.net/secrets/your-connection-string`, put it as final `@Microsoft.KeyVault(SecretUri=https://your-keyvault.vault.azure.net/secrets/your-connection-string)` and it's automatically served as normal connection string.
![image](https://user-images.githubusercontent.com/16673159/120485914-be6e7c80-c3de-11eb-89ed-8224066c5181.png)

That's your desire?

**Comment by v-bbalaiagar** [comment]
Hi @kanagaraj2503, Let us know if the above information resolves your query, or if you have any further queries.

**Comment by kanagaraj2503** [comment]
Hi @v-bbalaiagar / @zhenyuan0502 ,

After adding @Microsoft.KeyVault(SecretUri=https://your-keyvault.vault.azure.net/secrets/your-connection-string) it is not resolving the value, it simply gives the values same that given in Appsettings.json file ( @Microsoft.KeyVault(SecretUri=https://your-keyvault.vault.azure.net/secrets/your-connection-string) ). The sample code snippet is below

**Appsettings.json**
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureStorage": "@Microsoft.KeyVault(SecretUri=MyKeyVaultSecretURI)"
    }
}
```
**Code**:
```
.........
var storageConnection = Configuration.GetValue<string>("AzureStorage");
.........
```
Am I missing anything here? 

Thanks.

**Comment by zhenyuan0502** [comment]
@kanagaraj2503 In your case seems you are trying to store KeyVault for local development only, If you would like to do please follow this instruction: https://www.techwatching.dev/posts/azure-functions-custom-configuration

Since the deployed Azure Function doesn't need this settings because it automatically extracts, so no code changes as it's served as normal connection string: https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references#source-application-settings-from-key-vault

> To use a Key Vault reference for an application setting, set the reference as the value of the setting. Your app can reference the secret through its key as normal. No code changes are required.

That means, in your Azure Portal, both:
- @Microsoft.KeyVault(SecretUri=https://your-keyvault.vault.azure.net/secrets/your-connection-string)
- Your-normal-connection-string

Would be read as Your-normal-connection-string, no code need to handle this

**Comment by v-bbalaiagar** [comment]
Hi @kanagaraj2503, Let us know if you are able to resolve with the above information, or if you have any further queries.

**Comment by kanagaraj2503** [comment]
Hi @zhenyuan0502 / @v-bbalaiagar 

The above details work for normal function and portal level app settings using KeyVault, could you please guide how that would work for Unit Test project, also share the sample code snippet to verify ?

What I've done so far:
1. Have the "AzureStorage" : "@Microsoft.KeyVault(SecretUri=https://your-keyvault.vault.azure.net/secrets/your-connection-string)" in appsettings.json (Unit Test project)
2. Azure function Identity being updated to Key AzureStorage as @Microsoft.KeyVault(SecretUri=https://your-keyvault.vault.azure.net/secrets/your-connection-string)
3. Azure function system identity enabled.
4. In Keyvault have added access policy to GET Permission and selected principal as "MyFunction"
5. After all above changes trying to read the AzureStorage key value in my test class, code snippet below
public static void BeforeAllTests(TestContext context)
        {         
            var storageAccount = CloudStorageAccount.Parse(Configuration.GetValue<string>("AzureStorage"));
            ........................
        } 
6. Output is returned same as value given against AzureStorage key in appsettings.json (e.g., @Microsoft.KeyVault(SecretUri=https://your-keyvault.vault.azure.net/secrets/your-connection-string) ) 

Thanks.

**Comment by kanagaraj2503** [comment]
Hi @v-bbalaiagar - Hope you have gone thru my above request, any update/resolution?
Thanks.

**Comment by v-bbalaiagar** [comment]
Hi @kanagaraj2503, Checking internally for any possibilities.

**Comment by v-bbalaiagar** [comment]
Hi @kanagaraj2503, With the KeyVault referencing appsettings.json that's not going to work. The Microsoft keyVault reference that's only processed in the context of web service, so the app service infrastructure when it sees there will automatically go and resolve the information from the KeyVault and there is nothing locally or part of the unit test project.
For local development scenarios you need to load the configuration file that has the appropriate secrets in the appropriate information to use and you won't be able to rely on key Vault references as that is a web apps app service feature.

**Comment by kanagaraj2503** [comment]
Ok @v-bbalaiagar,

Is that something Microsoft going to resolve in future OR will have to live with secret expose in development machine?

Thanks.

**Comment by v-bbalaiagar** [comment]
Hi @kanagaraj2503, Apologies for the delayed response, Can you please go through the below documents for using Azure Key Vault - https://docs.microsoft.com/en-us/learn/modules/configure-and-manage-azure-key-vault/1-introduction
  https://docs.microsoft.com/en-us/azure/key-vault/secrets/overview-storage-keys

Please check and let us know if this helps.
