### ISSUE TITLE
Can't configure `FunctionAppLogs` category 

### ISSUE THREAD

**Issue by kmadof** [Azure/azure-functions-host#7431]
`FunctionAppLogs` is not available to set up in `Diagnostics` tab. I have only categories typical for App Service:

![obraz](https://user-images.githubusercontent.com/1680172/120789050-5a100200-c531-11eb-88e6-7e0a6e467567.png)

Even when I have configuration in place (which I know that I have them because logs are exported to Log Analytics Workspace) I don't see them on `Diagnostic setting`.

When I run my terraform code I got:

```
Error: Error creating Monitor Diagnostics Setting "name-here" for Resource "/subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.Web/sites/<func-name>": insights.DiagnosticSettingsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Category 'FunctionAppLogs' is not supported."
```

It started on Wednesday in `North Europe`. It affecst all our functions.

**Comment by pragnagopa** [comment]
Thanks for reporting the issue. We are actively investigating. 

cc @FinVamp1 @CooperLink @brettsam @anirudhgarg fyi

**Comment by v-anvari** [comment]
Hi @kmadof , Please confirm if this is the case still. I am able to see the function app logs as expected

![image](https://user-images.githubusercontent.com/66122429/136971599-0f4a16fc-9509-4d02-9878-bf5c088072f1.png)

**Comment by kmadof** [comment]
No. The issue was solved and now all is as expected. Thanks @v-anvari for taking a look on this!
