### ISSUE TITLE
New Functions App Doesn't seem to repsond to HTTP Calls

### ISSUE THREAD

**Issue by TehWardy** [Azure/azure-functions-host#7432]
New functions app from VS template ...

![image](https://user-images.githubusercontent.com/6891030/120840478-3a450200-c562-11eb-9d46-6c3845d05299.png)

... as you can see, running (I have made no changes to this app it's just the default template) ...

![image](https://user-images.githubusercontent.com/6891030/120840563-547ee000-c562-11eb-8401-82e2faf98020.png)

... looks good so far ....

![image](https://user-images.githubusercontent.com/6891030/120840732-82fcbb00-c562-11eb-9555-fc8e8d04fb0a.png)

... oh ... not what I expected!

Have I missed something?

Edit:  Additional note ... 
It seems that the function code isn't hit at all, so I figure this is a functions framework / routing issue of some sort.
I figured this much out by sticking a breakpoint on the first line of code in the function and not seeing it hit when a request is made to it.

Out of the box I would expect at least this breakpoint to be hit ...

![image](https://user-images.githubusercontent.com/6891030/120919411-5e632900-c6b1-11eb-9c93-169f3a2429b7.png)

**Comment by v-anvari** [comment]
Hi @TehWardy , I am unable to reproduce the scenario

Repro steps:
1. Take a Http triggered function app
2. Take the url and request a Get request from the Postman

I haven't added anything additional, can you retry the scenario and let us know if you are facing the issue. 

![image](https://user-images.githubusercontent.com/66122429/121003708-75864180-c7ab-11eb-9573-9009dd08cd41.png)

![image](https://user-images.githubusercontent.com/66122429/121003761-846cf400-c7ab-11eb-9008-975a968c6195.png)



Packages used:

![image](https://user-images.githubusercontent.com/66122429/121004003-c85ff900-c7ab-11eb-9e11-a56ed9609e27.png)

Framework used:

![image](https://user-images.githubusercontent.com/66122429/121004086-df9ee680-c7ab-11eb-988d-51efd9cd47af.png)

**Comment by TehWardy** [comment]
![image](https://user-images.githubusercontent.com/6891030/121148816-04419f80-c83a-11eb-8b22-24989d0ffa59.png)
![image](https://user-images.githubusercontent.com/6891030/121148841-086dbd00-c83a-11eb-8d1c-cefc5d5aaf39.png)
![image](https://user-images.githubusercontent.com/6891030/121148853-0c014400-c83a-11eb-8cf1-3b7703551bdf.png)

...

Totally confused!
I've used Functions for years.

**Comment by TehWardy** [comment]
Ok turns out I found another postman bug ... 
Sheesh I hate that thing sometimes!
