### ISSUE TITLE
Consider upgrading Microsoft.IdentityModel.* libraries to 6.X, at least on v4 runtime

### ISSUE THREAD

**Issue by cjaliaga** [Azure/azure-functions-host#7449]
#### What problem would the feature you're requesting solve? Please describe.
Currently the v3 runtime references `Microsoft.AspNetCore.Authentication.JwtBearer 3.1.0` that depends on `Microsoft.IdentityModel.Protocols.OpenIdConnect >= 5.5` => `System.IdentityModel.Tokens.Jwt >= 5.5` => `Microsoft.IdentityModel.JsonWebTokens >= 5.5`. We are pining these libraries so customer Functions Apps cannot use a higher version as the runtime will load its own.

Wide-used libraries are starting to use `Microsoft.IdentityModel.Protocols.OpenIdConnect >= 6` and `Microsoft.IdentityModel.JsonWebTokens >= 6`, such `Microsoft.Data.SqlClient` which depends on `Microsoft.IdentityModel.Protocols.OpenIdConnect >= 6.8` and `Microsoft.IdentityModel.JsonWebTokens >= 6.8`: https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.1.3

If customer apps try to make use of anything in these assemblies, such:

```csharp
var handler = new Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler();
```
will get the "right version of the assembly not found" issue:

```csharp
Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=6.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
```

#### Describe the solution you'd like
Ideally I'd like to be able to use `Microsoft.IdentityModel` version 6 libraries on the v3 runtime. Currently our dependency on the WebHost seems to be `Microsoft.AspNetCore.Authentication.JwtBearer`, where the other `Microsoft.IdentityModel.*` libraries are just dependencies.

**V3**
For the V3 we could try to manually install the last versions of the dependencies on the WebHost. I've had running for months now a custom version of the runtime as a Docker container that's doing exactly this and everything seems to be running fine, however, the test were not exhaustive so I cannot confirm there will not be any further problem with this solution: https://github.com/TrackSeries/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj

**V4**
For the V4 I hope it should be easier. Updating `Microsoft.AspNetCore.Authentication.JwtBearer`  to `6.0.0-preview.4.21253.5` should bring all the dependencies together:

https://github.com/Azure/azure-functions-host/blob/280c4f6ca646997a408360aa30ab8e46618440b1/src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj#L64

**Comment by fabiocav** [comment]
Thank you for opening this! This will be part of V4 as updates to all framework and internal host dependencies are within scope for the new version. Closing this as the work is already tracked by the upgrade, but let us know if you have any additional questions.
