### ISSUE TITLE
what is the correct value of %HOME% 

### ISSUE THREAD

**Issue by JamesDuggan** [Azure/azure-functions-host#7461]
#### Is your question related to a specific version? If so, please specify:
Function App is version 3 (windows) on Premium (EP1) plan

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
Resolved issue https://github.com/Azure/azure-functions-host/issues/3626 suggests %HOME% should be is D:\home. The value I see is C:\home, which is not writeable to. 

Is this a resource deployment issue or a bug?

**Comment by v-bbalaiagar** [comment]
Hi @JamesDuggan,  Thank you for reaching out to us, checking internally on this issue.

**Comment by balag0** [comment]
The actual drive letter is an implementation detail. As long as you are using %HOME% to resolve the path, the behavior should be the same. 
What is the exact path you are writing to? For apps using Run from package,  the content directory under  home/site/wwwroot will be readonly.

**Comment by JamesDuggan** [comment]
The app uses run from package. 

I want to write to the data folder of the file share of the Function App storage account, and as per https://github.com/Azure/azure-functions-host/issues/3626 I would prefer not to hard-code.

Environment.GetEnvironmentVariable("home") resolves to C:\home.

Using an app setting to retrieve the filepath (%home%\data\myData.txt) to which I intend to write, I get the following error:
C:\Program Files (x86)\SiteExtensions\Functions\3.0.15961\32bit\%home%\data\myData.txt' is denied.

I have a workaround whereby I can use Environment.GetEnvironmentVariable("resourcedrive") which resolves to D: and then hack a home path, but should not have to. Perhaps you can expand on how to resolve %home% to be as documented by https://github.com/Azure/azure-functions-host/issues/3626 ?

**Comment by JamesDuggan** [comment]
would it be possible to have an update please?

**Comment by balag0** [comment]
There are no multiple ways to resolve %home%. 

It is expected that the program files directory is readonly.

One thing, I don't understand is why writing to
C:\home\data\myData.txt
touches
C:\Program Files (x86)\SiteExtensions\Functions\3.0.15961\32bit%home%\data\myData.txt

Can you try the following command from kudu
`touch %home%\data\myData.txt`
and see if that creates the file myData.txt at C:\home\data\myData.txt?

**Comment by JamesDuggan** [comment]
That creates a file, and helps my understanding. From reading of #3626 I expected %home% to resolve to D:\home. Not clear why %home% is not resolving, but from perspective of this issue, my question is answered. 

Thanks
