### ISSUE TITLE
409 LeaseAlreadyPresent

### ISSUE THREAD

**Issue by NovaDomus** [Azure/azure-functions-host#7475]
I am getting a lot errors/logs from a function app in Application Insights as shown below. I do understand that is an blob storage issue, I do not know where it comes from. I dont use blob storage myself and the error doest mention the blob/file it wants to acquire. 

I use azurefunctions: 3.0.15733.0- sdk with the dotnet runtime.

**Server:Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id:c1c73167-201e-000f-4244-64bd38000000
x-ms-client-request-id:db57e4b8-5abb-4311-9d54-4f251730f7c1
x-ms-version:2020-04-08
x-ms-error-code:LeaseAlreadyPresent
Date:Fri, 18 Jun 2021 13:19:39 GMT
Content-Length:221
Content-Type:application/xml**

I managed to remove the logging by surpressing the loglevels via an override.
"AzureFunctionsJobHost__logging__logLevel__Azure-Core" : "Error"

But obviously it feels like it is caused by something inside the azure function host.

**Comment by v-anvari** [comment]
Hi @NovaDomus , Could you please share the Invocation id of the error and timestamp and the region. Could you also explain the project scenario and provide the repro steps
