### ISSUE TITLE
"Allow unauthenticated access" not working for Linux/Python function app

### ISSUE THREAD

**Issue by aandyl** [Azure/azure-functions-host#7484]
I am having trouble using the "allow unauthenticated access" setting in the app service auth integration with my Linux/Python function app. I am hoping that it is appropriate to file an issue here, if not then apologies in advance.

To reproduce the problem: create a functions app project in VS code and select Python 3.8 as the runtime. Deploy to a new function app in my Azure account, US West region. This works, and I can trigger the function using my browser and see the hello world response.

Then, in the "Authentication" blade for the newly created function app in the portal, add an identity provider, pick an existing app registration, and under "App Service authentication settings" select the radio button for "Allow unauthenticated access". (I have also tried creating a new app registration, the behavior is the same.)

When authentication is set up, open the example function in the browser again. Now I am redirected to the oauth signin page. (The redirect URL is like `https://login.windows.net/common/oauth2/authorize?response_type=id_token&redirect_uri=https://<myapp>.azurewebsites.net/.auth/login/aad/callback&client_id=<...>&scope=openid profile email&response_mode=form_post&nonce=<...>&state=redir=%2Fapi%2Fhttpexample`). If I call the API with curl, I get a 401.

What I am expecting to happen is that the function handler gets called anyways, but the authentication headers should reflect that there is no authenticated client. Then I can generate the redirect to the authentication page in my app, as appropriate.

If I configure the app service auth integration using the "Authentication (classic)" blade, the setting to allow unauthenticated (anonymous) requests works as I expect.

**Comment by v-anvari** [comment]
Hi @aandyl , Thank you for the feedback, we will reproduce this issue and update as appropriate

**Comment by v-anvari** [comment]
Hi @aandyl , I have tried to reproduce the mentioned scenario. Below are the repro steps:

1. Deploy a python function to a Function App - region- west US
2. Add a new identity provider - AAD provider
3. Edit authentication 
![image](https://user-images.githubusercontent.com/66122429/123294473-81eff580-d532-11eb-8359-987c76357533.png)
4. Create a http triggered function
5. call the function url in a new window

Result:
1. Authentication page received
2. Function executed successfully 

In case, I am missing a step, please tell us. I have used standard authentication

**Comment by aandyl** [comment]
@v-anvari thanks for looking into this. I'm not sure I understand your findings. What I understand is that you followed the reproduction steps I gave, and you were presented with the login page on trying to call the function via a browser. That is what I observed as well. When the "allow unauthenticated access" setting is active, I expected that the authentication page would not display automatically, and instead the application would be responsible to redirect to the authentication page when desired.

I tried clicking "cancel" on the authentication page to see if it would let me proceed to the application as an anonymous user, but that gives me the error "Used declined to consent to access the app." I also tried calling the function directly with curl to see if I could access without authentication that way, but when I do that I get a 401 unauthorized error (not a 302 redirecting to the authentication page, like is returned to browsers).

Maybe I have misunderstood how this is supposed to work. When "allow unauthenticated access" is on, how do I access the function app without authenticating?

**Comment by v-anvari** [comment]
Hi @aandyl , Yes your understanding is right, it is supposed to let anonymous user. But, I am checking this behavior internally to take a look on this behavior.

**Comment by v-anvari** [comment]
Hi @aandyl , I have validated this behavior with the concerned team. The difference between both are that, if you select "Allow Unauthenticated access", it would still require access, but anyone with a allowed credentials can access it. This information should be provided in the code as mentioned here in the document. Both the options require Authentication, because you have selected the AAD. 

On the other hand, if you select "Require Authentication" then it will be the identity provider or yourself.

It is documented here - https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization#authorization-behavior

**Comment by v-anvari** [comment]
You can use multiple sign-in providers in that case - https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization#authorization-behavior

**Comment by aandyl** [comment]
I tried adding an additional auth provider, but the behavior was the same -- it still redirected me to Microsoft sign-in. It actually still redirects me to Microsoft sign-in even if I delete all the auth providers. (The only way I have been able to find to turn off authentication once configured with the new experience is to manually call the config/authsettingsv2 REST API with a configuration that clears `platform.enabled`).

Another note -- the unauthenticated access configuration works as I expect if I use the "Authentication (classic)" blade, but then stops working if I do the opt-in upgrade to the new version.

Providing a mode where unauthenticated requests are allowed does create a risk that endpoints are inadvertently left open, so I would understand a decision not to support unauthenticated requests. But at the very least, I would suggest clarifying the documentation and adding some warning when attempting to upgrade a configuration that is no longer supported.

**Comment by v-anvari** [comment]
Hi @aandyl , Thank you for your feedback! We will investigate this further and update as appropriate.

**Comment by v-anvari** [comment]
Hi @aandyl , I tried to reproduce by adding additional identity providers, but I am unable to reproduce the error. I also checked with the UI team to validate the scenario. Can you tell us how are you adding the multiple identity providers in your code

**Comment by PawanHegde** [comment]
Thanks for opening this ticket, @aandyl. I'd been struggling with this same issue so this ticket clears it a bit. But the official documentation even now is really confusing. @v-anvari, the documentation link that you provided still pretty heavily implies that users don't need to authenticate. The naming of those options needs to be changed and the documentation updated. It's ridiculous that even with "Allow unauthenticated access" clients need authentication.

**Comment by v-anvari** [comment]
Hi @PawanHegde , The "Allow unauthenticated access" should be allowing only the other sign-in providers or anonymous users which are added to the code as mentioned in the document. If you don't wish to have authentication, you don't need to use any authentication. If the authentication is not working as expected, then we would need to investigate the steps you are following. How are you adding the identity providers in the code. As per the testing team, the blade is working as expected. 

![image](https://user-images.githubusercontent.com/66122429/126963928-88472a4b-ab25-4a41-8415-34382a6ee890.png)
