### ISSUE TITLE
Recover the deleted Function App Code, 

### ISSUE THREAD

**Issue by DVGY** [Azure/azure-functions-host#7486]
#### Is your question related to a specific version? If so, please specify:
I do not know which version to specify
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
Nodejs
#### Question
I some how deleted my whole azure function app (Node js). It had one http and two event triggered functions. 
**Is there any way I can get my function code ?**

Yes I still have access to the storage account it has access to. 

Please help me resolve this issue.

**Comment by balag0** [comment]
It depends on how the app was deployed. But since you still have access to the storage account, try checking the following locations in the storage account

File shares (each folder here maps to a function app)
Containers (check for files inside containers named scm-releases / function-releases)

**Comment by DVGY** [comment]
> scm-releases

I could not find anything. I used VSCode to deploy to function app.

**Comment by balag0** [comment]
Can you share the name of the app? Let me know if you are not able the share the name publicly and I can provide alternative instructions.

**Comment by DVGY** [comment]
> Can you share the name of the app? Let me know if you are not able the share the name publicly and I can provide alternative instructions.

@balag0 pls share the instructions so that I can send you privately.

**Comment by balag0** [comment]
Sure. create a new app in any plan and any region. For this new app use the name [DeletedAppName]-622.
For example if the deleted app's name was abcd, the name of the new app you create will be abcd-622

Once you have the new app, share the name of the new app using
https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately#option-2

There is no need to deploy to the new app.

**Comment by DVGY** [comment]
> Sure. create a new app in any plan and any region. For this new app use the name [DeletedAppName]-622.
> For example if the deleted app's name was abcd, the name of the new app you create will be abcd-622
> 
> Once you have the new app, share the name of the new app using
> https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately#option-2
> 
> There is no need to deploy to the new app.

GUID ea85218d-1dfb-4cd2-bebd-b3d6faee3b7a
UTC Time 2021-06-22 18:47:22.465
Region Japan East

**Comment by DVGY** [comment]
> Sure. create a new app in any plan and any region. For this new app use the name [DeletedAppName]-622.
> For example if the deleted app's name was abcd, the name of the new app you create will be abcd-622
> 
> Once you have the new app, share the name of the new app using
> https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately#option-2
> 
> There is no need to deploy to the new app.

Date 2021-06-22 19:06:49.239
Operation Id 7b6c7dcb7293964e8011993e5853025a
Guid e620ba98-aca6-435f-adec-d9055ab9451c
Region Japan East

**Comment by DVGY** [comment]
> Sure. create a new app in any plan and any region. For this new app use the name [DeletedAppName]-622.
> For example if the deleted app's name was abcd, the name of the new app you create will be abcd-622
> 
> Once you have the new app, share the name of the new app using
> https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately#option-2
> 
> There is no need to deploy to the new app.

@balag0 
Update: One of function in the Function App was event grid trigger. I can still see the function name in Topic Subscription. When I click on it. It loads forever. 
![image](https://user-images.githubusercontent.com/46158826/123038968-f598e200-d40e-11eb-9540-2ebdc82182cd.png)
![image](https://user-images.githubusercontent.com/46158826/123038986-021d3a80-d40f-11eb-97f9-46c07a8bbd21.png)

![image](https://user-images.githubusercontent.com/46158826/123038814-b5396400-d40e-11eb-9e7b-7cc64c5e434e.png)

It will be very helpful I can somehow access the code
