### ISSUE TITLE
Function fails to load required System.Threading.Channels dll

### ISSUE THREAD

**Issue by sebastianburckhardt** [Azure/azure-functions-host#7488]
#### Investigative information

- Timestamp: 2021-06-22T16:56:35.475
- Function App version: 3
- Function App name: reproloadfailure20210622094402
- Function name(s) (as appropriate): Function1
- Invocation ID: eb7f9f81-907d-4eaf-8c2b-9a70823dc658
- Region: us west 2

#### Repro steps

1. Create function app w/ http trigger using template in VS2019.
2. Add NuGet package System.Threading.Channels 5.0.0
3. Replace trigger code with
```csharp
[FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "repro")] HttpRequest req)
        {
            var _ = System.Threading.Channels.Channel.CreateBounded<DateTime>(10);
            return new OkObjectResult("ok");
        }
```
4. Deploy to EP1 function app
5. Invoke the trigger, e.g. `curl -v https://reproloadfailure20210622094402.azurewebsites.net/api/repro`

#### Expected behavior

The function should load all required assemblies and execute successfully.

#### Actual behavior

Function fails. Log Stream shows that System.Threading.Channels could not be loaded:

```
2021-06-22T16:56:35.428 [Information] Executing 'Function1' (Reason='This function was programmatically called via the host APIs.', Id=eb7f9f81-907d-4eaf-8c2b-9a70823dc658)
2021-06-22T16:56:35.475 [Error] Executed 'Function1' (Failed, Id=eb7f9f81-907d-4eaf-8c2b-9a70823dc658, Duration=67ms)Could not load file or assembly 'System.Threading.Channels, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
```

#### Known workarounds

Using  an  old version of Microsoft.NET.Sdk.Functions fixes the problem.

I found that 3.0.3 works, but 3.0.4 or 3.0.13 do not, so the bug was likely introduced with 3.0.4 and has remained there since then.

#### Related information

This was originally discovered in the context of microsoft/durabletask-netherite#55.

**Comment by v-bbalaiagar** [comment]
Hi @sebastianburckhardt, The version of the package 5.0.0 would be supported with the auto proc worker only and not within proc model. So, the recommendation here would be to go with the proc worker if you want to use the package 5.0.0

**Comment by sebastianburckhardt** [comment]
Why is 5.0.0 not supported in proc? Any plans to support it? what about 6.0.0?

I don't think out-of-proc worker is an option for us (@ConnorMcMahon may be able to confirm this) , since this code is running within the Durable Functions extension.

**Comment by v-bbalaiagar** [comment]
Hi @ConnorMcMahon, Kindly can you share any inputs here.

**Comment by ConnorMcMahon** [comment]
I agree with @sebastianburckhardt. This is for code that will be running in-process since extensions don't work out-of-proc.
