### ISSUE TITLE
Run a event grid function in vscode

### ISSUE THREAD

**Issue by DVGY** [Azure/azure-functions-host#7492]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
node js 12
#### Question
1. How can I test existing event grid triggered function in Function App inside VSCode? 

I am asking this because developing a function on azure portal and writing long code is very inefficient for me.

In my event grid function. I have event subscription to some storage.

Please help me.

**Comment by v-bbalaiagar** [comment]
Hi @DVGY, Here is a [blog post](https://blog.mcilreavy.com/articles/2018-12/debug-eventgrid-triggered-azure-function) which addresses similar scenario where the blog talks about locally debugging an event grid triggered Azure Function.
Please check and let us know if this helps

**Comment by alrod** [comment]
You can use `ngrok `for local debugging:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-debug-event-grid-trigger-local#allow-azure-to-call-your-local-function

do not forget change port after starting the function app from VSCode

**Comment by DVGY** [comment]
@Thanks
