### ISSUE TITLE
[Epic] Add functionality in host to support function indexing by worker

### ISSUE THREAD

**Issue by anandagopal6** [Azure/azure-functions-host#7496]
Host should accommodate for new worker indexing pipeline while remaining backwards compatible.

Steps
- [x] #7516
- [x] #7513 
- [x] #7514 
- [x] #7550
- [x] #7556
- [x] #7582
- [x] #7532
- [x] #7806 
- [x] #7797
- [x] #7606
- [x] #7850 
- [x] #7849
- [x] #7879 
- [x] #7916
- [x] #8081
- [x] #8199 
- [x] #8110
- [x] Additional logging - https://github.com/Azure/azure-functions-host/pull/8231
- [x] Detector - [link](https://dev.azure.com/Azure-Functions-Supportability/IPD%20Reduction%20-%20Copper/_workitems/edit/613)

**Comment by surgupta-msft** [comment]
@fabiocav Does it make sense to close this Epic now as the tasks listed in the description are done?

**Comment by surgupta-msft** [comment]
Closing the epic.
