### ISSUE TITLE
In V3, error coming when adding MvcJsonMvcOptionsSetup

### ISSUE THREAD

**Issue by manish1635** [Azure/azure-functions-host#7497]
Moving my azure function from V2 to V3. function is broken into the following lines in startup.cs file:
public override void Configure(IFunctionsHostBuilder mybuilder)
{
mybuilder.Services.AddTransient<IConfigureOptions<MvcOptions>, MvcJsonMvcOptionsSetup>();
}
Using.netcore3.1, I have read "functions-versions#breaking-changes-between-2x-and-3x" and other documents as well. It seems I have to use Microsoft.AspNetCore.Mvc.NewtonsoftJson rather than Microsoft.AspNetCore.Mvc.Formatters.Json.Internal. Any suggesstion, how i should use?

**Comment by v-bbalaiagar** [comment]
Hi @manish1635, Thank you for reaching out to us, checking internally on this issue.

**Comment by v-bbalaiagar** [comment]
Hi @manish1635, We would like to have more insights on the scenario to understand it better and what you are trying to configure here so that we can provide the recommendation.
