### ISSUE TITLE
Warmup Trigger not running, when App Service Authentication/Authorization is turned on

### ISSUE THREAD

**Issue by Saikes** [Azure/azure-functions-host#7512]
#### Investigative information

Please provide the following:

- Timestamp: 30.06.2021
- Function App version: 3
- Function App name: WarmUpTest-KKO
- Function name(s) (as appropriate): Warmup
- Invocation ID: (none because not triggering)
- Region: West Europe

#### Repro steps

Provide the steps required to reproduce the problem:

Example: 

1. Switch Authentication on
2. Deploy Azure Function
3. Warmup Trigger is not running

1. Switch Authentication completly off (allow anonymous requests is not enough)
2. Deploy Azure Function
3. Warm Up trigger runs

#### Expected behavior

Provide a description of the expected behavior.

Warm up trigger should be able to run, even if authentication is switched on.

#### Actual behavior

Provide a description of the actual behavior observed.

1. Switch Authentication on
2. Deploy Azure Function
3. Warmup Trigger is not running

#### Known workarounds

Not using Auth.

#### Related information 

Provide any related information 

* C#
<summary>Source</summary>

```csharp
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Logging;

namespace WarmupSample
{

	//Declare shared dependencies here

	public static class Warmup
	{
		[FunctionName("Warmup")]
		public static void Run([WarmupTrigger()] WarmupContext context,
			ILogger log)
		{
			//Initialize shared dependencies here

			log.LogInformation("Function App instance is warm 🌞🌞🌞");
		}
	}
}
```

**Comment by v-bbalaiagar** [comment]
Hi @Saikes, Thank you for reaching out to us, checking this internally for the possibilities. We will update you with any information found.

**Comment by v-bbalaiagar** [comment]
Hi @Saikes, I am unable to get the logs as your function app deleted it seems. Let us know if you are still facing the same issue, if yes share us the function app name.

**Comment by Saikes** [comment]
Hi together,
we found the issue in in the meanwhile with the help of Microsoft Support. You need to set the website to use HTTPS only (go to TLS/SSL settings in the portal and set HTTPS Only to On). This resolves the issue. The Azure Function is deleted by me, as I got no answer after 14 days and solved it with the Microsoft Support. Still needs to be documented. Forgot to update here, sorry ,)

**Comment by v-bbalaiagar** [comment]
Hi @Saikes, Thank you for the update, I have submitted the issue in azure-docs repo  - https://github.com/MicrosoftDocs/azure-docs/issues/78586

Closing this issue, please feel free to reach back to us in case of any further queries related to this issue.
