### ISSUE TITLE
Add GRPC message definitions for sending metadata requests and receiving metadata from worker

### ISSUE THREAD

**Issue by anandagopal6** [Azure/azure-functions-host#7513]
Need to add new message definitions to FunctionRpc.proto to enable the worker indexing workflow.

Messages to add:
- [x] Message for host requesting metadata from worker; should send directory path
- [x] Message for sending metadata from worker to host; should include list of metadata + status results and an overarching status result for the overall request
- [x] Message including all necessary information to populate FunctionMetadata; each function will correspond to one of these messages, so a list of these messages will be sent through the overall response message from worker to host

**Comment by anandagopal6** [comment]
Still need to add the StatusResult field for the overall metadata response message and integrate this into the response parsing logic.

**Comment by anandagopal6** [comment]
StatusResult field has been added. Message types should be fully implemented now.

**Comment by fabiocav** [comment]
Work is in progress, expecting a PR in 106. Updating sprint assignment to reflect that
