### ISSUE TITLE
Allow app settings expression in table binding filter

### ISSUE THREAD

**Issue by MrJer** [Azure/azure-functions-host#7515]
I had a difficult time working with input table binding because the `filter` setting doesn't accept app setting expression.

Considering the `take` setting can accept an app setting, I would like to see `filter` setting behave the same.

Alternatively, allowing app setting in binding parameter is an improvement to the current situation as well.

Sample function.json:
```

 {
      "tableName": "<TableName>",
      "connection": "<ConnectionString>",
      "name": "<BindingName>",
      "type": "table",
      "direction": "in",
      "take": "%TakeSize%", // This works
      "filter": "%FilterString%" // This causes function host to throw an error
}
```

Error message thrown: 
```

The 'foo' function is in error: Unable to configure binding '<BindingName>' of type 'table'. This may indicate invalid function.json properties. Input string was not in a correct format.

```

**Comment by v-bbalaiagar** [comment]
Hi @MrJer, Thank you for reaching out to us, checking this internally for the possibilities. We will update you with any information found.

**Comment by v-bbalaiagar** [comment]
Hi @MrJer, You can use IQueryable methods to do any filtering required. Can you please go through the document for more information - https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table-input?tabs=csharp#usage

Please check and let us know if this helps.

**Comment by MrJer** [comment]
Hey @v-bbalaiagar , my function is written in typescript, so I don't have access to IQueryable methods 🙂 I could use `filter()` function to filter down my data, but that would require my entire table storage to be retrieved and defeat the purpose of having a `filter` property in input binding IMO.

**Comment by v-bbalaiagar** [comment]
Hi @MrJer, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @MrJer, Here is a blog post which addresses similar scenario. Can you please go through here - https://medium.com/medialesson/query-strings-as-filter-in-table-input-bindings-for-azure-functions-fc7f4293133f
