### ISSUE TITLE
Check for worker indexing capability and redirect to worker indexing pipeline when appropriate

### ISSUE THREAD

**Issue by anandagopal6** [Azure/azure-functions-host#7516]
The worker indexing code path should only be selected once the worker indexing capability has been confirmed and the feature flag has been enabled.

At the moment, the code path can be manually switched in ScriptHost.InitializeAsync

Capability and feature flag checks still need to be implemented.

**Comment by anandagopal6** [comment]
Added feature flag for enabling worker indexing. This feature flag should work in tandem with the indexing capability until the feature flag is removed. For now, the enabled feature flag redirects to the worker indexing pipeline.

**Comment by anandagopal6** [comment]
Capability service has been added to my local branch. It stores capabilities for each worker runtime in a central structure. Every time a new worker channel sends its capabilities to the host, we update the `_workerCapabilities` structure in `WorkerCapabilities` that can later be queried through `GetCapabilityValue(runtimeLanguage, capabilityName)`.

**Comment by anandagopal6** [comment]
Update: it turns out that worker capabilities are not accessible/exchanged at ScriptHost startup if placeholder mode is not enabled. Because of this, we are now checking the worker config file for the worker indexing ability.

The feature flag has been made and is currently hiding the entire worker-indexing codepath in the host.

To determine whether the worker should index or not, there is a utility function call `CanWorkerIndex` that will take in a worker config, consult that file, and then also check to see if the feature flag is enabled. If both of these pieces of information are true/enabled, then the util function returns true.

**Comment by fabiocav** [comment]
This has been merged into the feature branch. Closing as done.
