### ISSUE TITLE
The default request body causes non-http trigger failed with http 500

### ISSUE THREAD

**Issue by yeahsicy** [Azure/azure-functions-host#7517]
#### Investigative information

- Timestamp: since the app created at 2021-06-25T00:26:09.0741373Z
- Function App version: 3.0.15885.0
- Function App name: timer624
- Function name(s) (as appropriate): TimerTrigger1
- Invocation ID: n/a
- Region: West US 2

#### Repro steps

1. create a function app via portal. 
2. deploy a non-http trigger (timer trigger). 
3. go to the function > Code + Test > Test/Run, where the default request body is the function app home page. 
4. Hit "Run". 

#### Expected behavior

the function should execute successfully as the body is irrelevant. 

#### Actual behavior

the function returns 500 Internal Server Error. 

#### Known workarounds

Remove the default request body or shorten the body size. 

#### Assessment

the issue seems due to the body size - the default body is the function app home page that is too large/long. 

#### Related information 

* Programming language used: python
* Links to source: the default timer code
* Bindings used: Timer

**Comment by yeahsicy** [comment]
I didnt have a chance to test all the non-http triggers in every worker runtime. But I assume this might be widespread. 

Thanks, 
@yeahsicy

**Comment by v-bbalaiagar** [comment]
Hi @yeahsicy, Thank you for reaching out to us, checking internally on this issue.

**Comment by v-bbalaiagar** [comment]
Hi @yeahsicy, I am unable to reproduce this issue. Can you please share the details of your run time stack ,OS and python code.

Also, I am unable to get the logs as your function app deleted it seems. Can you try to create the function app again and share the name to get the logs and check the cause.

**Comment by yeahsicy** [comment]
Hi @v-bbalaiagar , I couldn't repro the issue anymore. I noticed the difference that the Function App version: 3.0.15885.0 is no longer being used in Azure. I assume it'd be related to that specific runtime, however, I specified FUNCTIONS_EXTENSION_VERSION to that but it wasn't recognized. So I couldn't test further. 

Anyway, it'd be great if you can investigate the issue on that runtime version. But if that version is deprecated, you may close out this issue. Thanks. 

Reference: 
https://github.com/Azure/azure-functions-host/releases/tag/v3.0.15885

**Comment by v-bbalaiagar** [comment]
Hi @yeahsicy, I tried to reproduce the issue with the Function App version: 3.0.15885 but it is not updated as expected and the working version is updated. Function App version: 3.0.15885 is not deprecated. If that version is undergoing changes or commits then automatically the working version is updated it will be supported once the version is released.
