### ISSUE TITLE
Reenable WebJobs analyzers for Functions

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#7531]
Creating this issue to track the work required to reenable the Roslyn Analyzers we've built for WebJobs and make those available in Functions. 

This may need to be decomposed for each of the analyzers once we scope that work.

**Comment by fabiocav** [comment]
@kashimiz FYI

**Comment by fabiocav** [comment]
We'll be leaving this item open as an epic, creating individual issues for the difference analyzers.

**Comment by fabiocav** [comment]
@kashimiz moving this to sprint 114 so we can finish this up.

**Comment by fabiocav** [comment]
Work in progress. Expecting a PR for this in 118

**Comment by kashimiz** [comment]
Decomposing into related issues:

* https://github.com/Azure/azure-functions-host/issues/8255
* https://github.com/Azure/azure-functions-host/issues/8256
* https://github.com/Azure/azure-functions-host/issues/8257
* https://github.com/Azure/azure-functions-host/issues/8258

**Comment by mattchenderson** [comment]
Closing since only #8258 remains, and we're moving away from issues as epics.
