### ISSUE TITLE
Documentation for adopting worker indexing flow in the host

### ISSUE THREAD

**Issue by anandagopal6** [Azure/azure-functions-host#7532]
Documentation needs to be created to explain the changes made to the host for it to support worker indexing. This information should be easily understood by anyone with working knowledge of the host, and it should explain what changes were made and why they were necessary.

Documentation components
- [x] Sequence diagram for new code flow
- [x] Create a wiki page to include the sequence diagram and explain the flow
  - [x] Explain new GRPC messages
- [x] Add comments throughout new functions in the code
- [x] Add capability documentation into wiki
- [x] Keep PPT updated with high-level overview on host implementation details

**Comment by anandagopal6** [comment]
Sequence Diagram: https://microsoft-my.sharepoint.com/:u:/p/t-anjanan/EQ4h-XzrfX5GsKzAx9MTVFABEc427uyqLBmVPgDJJjTYSQ?e=vYKHCc

This diagram shows two different flows: one for host indexing and one for worker indexing.

**Comment by anandagopal6** [comment]
Started a wiki page with some details on the host changes that have been made so far for worker indexing: https://github.com/Azure/azure-functions-host/wiki/Worker-Indexing-Changes

**Comment by anandagopal6** [comment]
Updated original PPT file with details on the host changes:
https://microsoft-my.sharepoint.com/:p:/p/t-anjanan/EdQrSKS3jI9CrlepjFSFLOEBC_MyqDbmPhFNbzYLuQVqcQ?e=zUzgXG

**Comment by anandagopal6** [comment]
Also made a wiki page for the Python worker to start documenting changes for that end of the project implementation.
https://github.com/Azure/azure-functions-python-worker/wiki/Worker-Indexing-Pipeline

**Comment by fabiocav** [comment]
Closing as done.
