### ISSUE TITLE
Release latest Microsoft.Azure.WebJobs.Script.Abstractions to Nuget

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#7533]
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Script.Abstractions/1.0.0-preview does not include latest changes we made to introduce RetryOptions.

cc @fabiocav @brettsam

**Comment by pragnagopa** [comment]
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Script.Abstractions/1.0.2-preview  is now available on Nuget

**Comment by pragnagopa** [comment]
Re-opening as publishing to nuget is not succeeding.

**Comment by fabiocav** [comment]
Moving this to 106.

**Comment by fabiocav** [comment]
@pragnagopa this slipped this sprint. Let's chat and get this published out. 

Moving to 107 to make sure we don't lose this.

**Comment by fabiocav** [comment]
@pragnagopa will reach out, but should have this published today.

**Comment by justinyoo** [comment]
It's currently 1.0.0-preview and shipped with Logic Apps Standard. Wonder when this package goes GA?

**Comment by liliankasem** [comment]
@fabiocav has this been released, can we close the issue?

**Comment by justinyoo** [comment]
It's still in preview: https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Script.Abstractions

**Comment by fabiocav** [comment]
This was missed. Assigning to 118 and we'll have this pushed out ASAP.

**Comment by kshyju** [comment]
The package is part of the host artifact. Need to setup a pipeline.

**Comment by kshyju** [comment]
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Script.Abstractions/1.0.4-preview is out now.
