### ISSUE TITLE
Invalid URI: The hostname could not be parsed. 

### ISSUE THREAD

**Issue by curtisconner** [Azure/azure-functions-host#7534]
Hi, I have read all the other issues with the above error but cant get this to work at all.

here is my project settings
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <Configurations>Debug;Release;Test</Configurations>
  </PropertyGroup>

Here is my nuget packages
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Core" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Abstractions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.EventHubs" Version="4.2.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="4.0.4" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.3" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.3.0" />

My startup code is
public static void Main()
        {
            var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults()
                .ConfigureServices(services =>
                {
                    services.AddHttpClient();

                    var providers = new List<IConfigurationProvider>();

                    var env = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
                    Console.WriteLine($"Using environment {env}");

                    var config = new ConfigurationBuilder();
                    config.AddJsonFile("appSettings.json", optional: false, reloadOnChange: true);
                    if (env != null)
                    {
                        config.AddJsonFile($"appsettings.{env}.json", false, true);
                    }
                    else
                    {
                        Console.WriteLine("********** GET HELP THE ENVIRONMENT WAS NOT SET THIS IS BAD ********************");
                    }

                    config.AddEnvironmentVariables();

                    _configuration = config.Build();
                    providers.AddRange(config.Build().Providers);

                    services.AddSingleton<IConfiguration>(new ConfigurationRoot(providers));

                    services.AddOptions();

                })
                .Build();
         
            host.Run();
        }

my function is

 [Function("UpdateWynOrgs")]
        public async Task<HttpResponseData> Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequestData req, FunctionContext executionContext)
        {
            var logger = executionContext.GetLogger("UpdateSmsLog");
}

I am running in VS2019 debugging local.  I get the Invalid URI: The hostname could not be parsed. when the code start at the host.Run().  Any ideas

**Comment by v-anvari** [comment]
Hi @curtisconner , I am trying to reproduce this scenario, can I know what you are passing in the host.json file.
