### ISSUE TITLE
Functions not working due to BlobStorageSecretRepoError

### ISSUE THREAD

**Issue by pgombar** [Azure/azure-functions-host#7537]
#### Investigative information

Starting from 7/6 with Functions runtime release 3.1.0, we introduced a change in the order of precedence for applying application configuration related to secrets, specifically AzureWebJobsStorage.
With 3.1.0, settings from custom sources take precedence over app settings, which didn’t use to be the case. Given this breaking change in behaviour, customers apps might stop working when an invalid AzureWebJobsStorage URI value is given from custom sources.

#### Repro steps

Deploy a function app in one of the following regions: Canary, West Central US, North Central US, or West US to get version 3.1.0. With app creation, AzureWebJobsStorage app setting will be set to a valid blob. Deploy a HTTP trigger function and modify the code to inject a custom value for AzureWebJobsStorage and set it to an invalid value. Function app and function invocations will stop working.

#### Expected behavior

The expected behavior would be to not take the custom source as the ground truth for app settings, so the app would continue working after the faulty custom source was introduced.

#### Actual behavior

The function app stops working because the AzureWebJobsStorage value is being read from custom source and is invalid.

#### Known workarounds

1)	Validate and fix the value for AzureWebJobsStorage (in ALL configuration sources). Requires app restart.
2)	Add the following feature flag as an app setting, which prevents the new logic to be used. Requires app restart:
a.	App setting name: AzureWebJobsFeatureFlags
b.	App setting value: DisableMergedConfiguration

**Comment by yojagad** [comment]
Small update on **Expected Behavior** 

The webhost scoped configuration source should take precedence over the jobhost scoped one. Therefore, even if they inject an invalid value for AzureWebjobsStorage from within startup code, etc, the AzureWebjobsStorage app setting during creation of function app would be used.
