### ISSUE TITLE
Azure functions runtime is unreachable

### ISSUE THREAD

**Issue by impresent7** [Azure/azure-functions-host#7540]
I have create a python function using VS code and deploying this using zip deploy. The function is deployed to premium app service plan P1:V2. First time when i create function using ARM scripts via Cli and deploy the function using cli. it works fine. But suddenly when i make any changes to the function code after deployment of new code it gives me error as "Azure Functions runtime is unreachable" on Functions page in Azure portal.
After looking into to the container logs on kudu only thing i can find is "ERROR - Container XXX for site XXX did not start within expected time limit. "
"ERROR - Container XXX  didn't respond to HTTP pings on port:80, failing site start. See container logs for debugging"

I am not sure where to see the container logs.

When i redeploy the old running function code ever this problem persist. 
There is no clue for this error. I haven't made any changes to the storage account which could be the potential issue for this error as per Microsoft documentation.

it seems somewhere the container is lost reference for the webapp.

**Comment by impresent7** [comment]
I have added the appsetting "WEBSITE_PORT" : "8080" and function app  Always on setting but no resolution.

**Comment by v-anvari** [comment]
Hi @impresent7 , Thank you for reaching out to us, could you share us the repro steps and the document you are referring to, this will help us reproduce the issue from our end. 

Also, are you exposing the port first 
Use the EXPOSE instruction in your Dockerfile to expose port 8080.

More information on this topic
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops
https://docs.microsoft.com/en-us/archive/blogs/waws/things-you-should-know-web-apps-and-linux
https://github.com/MicrosoftDocs/azure-docs/issues/34451

**Comment by impresent7** [comment]
Hi No , I am not using the EXPOSE instruction as not sure how to do it. also i am not explicitly using any docker container. I am creating the azure function app using Azure cli and ARM teamplates. After this i deploy my code which is developed on VS code for python using zip deploy on the function app using below command.
az functionapp deployment sources config-zip -g <resource group> -n <function app> --src <zip.file>

it all going fine when doing this first time as a initial deployment. but when i make any changes to my code and perform the zip deploy i am facing this issue.

**Comment by v-anvari** [comment]
Hi @impresent7 , Thank you for the details, We require further information to understand the App config. Can you provide us the App details, https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately.

Meanwhile, The following document help you understand why the container is not responding to the Pings - https://docs.microsoft.com/en-us/archive/blogs/waws/things-you-should-know-web-apps-and-linux#your-container-must-respond-to-an-http-pingapplies-to-web-app-for-containers.

Can we know why are you adding "WEBSITE_PORT" : "8080"
