### ISSUE TITLE
[Linux Consumption] Support package download using MI

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-host#7548]
Currently download only works with SAS. 
Add support to use MI token to complete the download.

**Comment by balag0** [comment]
Fixed by https://github.com/Azure/azure-functions-host/pull/7571

**Comment by pragnagopa** [comment]
cc @mattchenderson fyi

**Comment by fabiocav** [comment]
@pragnagopa , is this fixed as per @balag0 's comment above? Do we just need to close the issue?

**Comment by balag0** [comment]
Yes. forgot to close this. closing now. Thanks

**Comment by fabiocav** [comment]
Thanks @balag0 !
