### ISSUE TITLE
Host should pass capabilities (or version) to workers on startup

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#7549]
Certain features of workers may only be enabled (or defaults may change) in Functions v4. Today there's no way for them to know the host version that they're running with.

**Comment by brettsam** [comment]
@AnatoliB / @alrod / @vrdmr / (and maybe others) -- I filed this because there were several v4 breaking changes in language workers that wanted to change defaults if they were running in v4. We said that we needed a way for the worker to know the host version. It turns out that we already send `host_version` with the `WorkerInitRequest`. Will this work, or do some of these features require this to be sent earlier, like as part of the cmd line args?

I think these are the issues that asked for this:
- https://github.com/Azure/Azure-Functions/issues/1962
- https://github.com/Azure/Azure-Functions/issues/1969

**Comment by fabiocav** [comment]
Closing this as we already have the information being passed and the requirement is no longer present.
