### ISSUE TITLE
Break down channel initialization in RpcFunctionInvocationDispatcher

### ISSUE THREAD

**Issue by anandagopal6** [Azure/azure-functions-host#7550]
`RpcFunctionInvocationDispatcher.InitializeAsync()` is responsible for starting the worker channel initialization process. This logic needs to be broken down into multiple sections because this method currently starts the worker channels, sets up the function invocation buffers, and sends the function load requests. 

However, the worker indexing pipeline requires that the worker provide the function metadata before the function invocation buffers can be set up and before the function load requests can be sent.

**Comment by fabiocav** [comment]
Work completed and merged into the feature branch.
