### ISSUE TITLE
Azure function host restart hourly

### ISSUE THREAD

**Issue by tkwin** [Azure/azure-functions-host#7552]
We have one V2 function app with consumption plan written in C# that is deployed to Azure. It also has one timer trigger that run every 15 minutes to prevent function cold start.  It also add email notification along with Dependency Injection at Function Start up for monitoring purpose. When I deploy it to Azure, I receive the email notification every hourly - it reset the function runtime even though I've added timer trigger to warm up function instance. Can someone highlight why it happens to restart function runtime hourly?

**Comment by v-bbalaiagar** [comment]
Hi @tkwin, Could you please provide us the invocation id ,time stamp and region to get the logs and check the cause.
