### ISSUE TITLE
When do the function core tools get updated with the latest function hosts?

### ISSUE THREAD

**Issue by ghost** [Azure/azure-functions-host#7553]
Hi Team,

Can we get some documentation on when the core tools are updated to take the latest version of the functions host:

https://github.com/Azure/azure-functions-core-tools/issues/2631

Currently the core tools 3.0.3568 (latest) is still using runtime version 3.0.15828.0.

**Comment by v-anvari** [comment]
Hi @pb-adrianbezzina , The updates can be found in the release notes here - https://github.com/Azure/azure-functions-core-tools/releases. The updates for the current version is still in-progress. 

Closing this issue as the required information is provided, please feel free to reach back to us in case of any further queries related to this issue
