### ISSUE TITLE
.NET 5 + Linux + VNET integration Scenario repro

### ISSUE THREAD

**Issue by cachai2** [Azure/azure-functions-host#7554]
1. Create repro scenario in web apps

**Comment by pragnagopa** [comment]
cc @pgombar @divyagandhisethi  

Scope of this issue is to set up a stand alone repro using WebApps + Grpc Host c#+ Grpc Client C# - similar to .Net 5 worker

**Comment by fabiocav** [comment]
We now have a repro with all the details/information we need. Closing this issue as we'll continue to track progress using #7555
