### ISSUE TITLE
Process received metadata from worker and hydrate pipeline with metadata

### ISSUE THREAD

**Issue by anandagopal6** [Azure/azure-functions-host#7556]
Once the metadata is received from the worker and it is minimally parsed by `GrpcWorkerChannel`, the metadata needs to be validated and used to hydrate the existing `FunctionMetadataManager._functions` structure.

**Comment by anandagopal6** [comment]
Solution: `FunctionMetadataManager` calls `WorkerFunctionMetadataProvider` to get the metadata through `GrpcWorkerChannel`. Once the provider receives the parsed data, it will validate it similar to how `HostFunctionMetadataProvider` validates functions. This validated list of metadata will be returned to the manager and saved into `_functions`. 

This has been implemented and manually tested locally, will be addressed in the next worker indexing PR.

**Comment by fabiocav** [comment]
This has been completed and in the feature branch.
