### ISSUE TITLE
When the Functions Host fails to initialize a language worker, it never recovers. 

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-host#7558]
The Functions Host should retry when failing to initialize a language worker.

**Comment by fabiocav** [comment]
Assigning this to the sprint for investigation and triage. 

@kashimiz will validate the flow and engage @pragnagopa if needed.

**Comment by Francisco-Gamino** [comment]
@yojagad added a fix to ensure that at least one channel is initialized before sending function invocations. However, if the worker initialization times out, the Host shutdowns.

Linking issue for reference https://github.com/Azure/azure-functions-host/issues/7590.

**Comment by fabiocav** [comment]
@Francisco-Gamino; @kashimiz is still working on validation and will continue to look at this in 112

**Comment by fabiocav** [comment]
@Francisco-Gamino this issue started a broader investigation around reliability and diagnostics for the OOP layer. 

As a result, @liliankasem has opened a number of issues and is tracking enhancements that will cover this as well.

To follow the progress of those items, you can use the epic https://github.com/Azure/azure-functions-host/issues/8076

Closing this in favor of the new issues that were created.
