### ISSUE TITLE
The new authorization experience breaks on Python Function App with Linux consumption plan

### ISSUE THREAD

**Issue by nuntipat** [Azure/azure-functions-host#7559]
#### Investigative information

Please provide the following:

- Timestamp: Wed 21 Jul 2021 6:32PM (GMT+7)
- Function App version: 3.0.15885.0
- Function App name: testnuntipat1
- Function name(s) (as appropriate): testapi 
- Invocation ID: N/A
- Region: West US and also Southeast Asia (only 2 regions has been tested)

#### Repro steps

1. Create a new Function App (Python 3, Consumption Plan)
2. Deploy one HttpTrigger function for example the default function created by the VS code extension. Now the function should be accessible through the function's url e.g. https://testnuntipat1.azurewebsites.net/api/testapi?name=nuntipat
3. Set up authentication using the Authentication (classic) tab in the portal. Request to the following url in step 2 should still return the same response. ![Screen Shot 2564-07-21 at 18 36 43](https://user-images.githubusercontent.com/2668437/126482631-6aafb90b-5bd8-4435-8f86-afade8e3d410.png)
4. Change the action to take when request is not authenticated to "Log in with Google" (or other provider). Now, request to the same url will be redirect to Google login page
5. Update to the new Authentication experience. **Now, request to the same url will return 401.** ![Screen Shot 2564-07-21 at 18 41 44](https://user-images.githubusercontent.com/2668437/126483203-55d9b257-4e83-401c-a8b0-4f6021f3d006.png)
6. Update the setting to allow unauthenticated requests. **Now, request to the same url will still return 401.** 
![Screen Shot 2564-07-21 at 18 44 18](https://user-images.githubusercontent.com/2668437/126483490-8971bfcf-b017-4550-b97a-6a328fb2de31.png)

I have tried to restart the Function App and redeploy but the issue is still persisted. Also, the issue exists even when I skip step 3 and 4 and start with the new authentication setting page.

#### Expected behavior

1. The Function App should be accessible when "Allow Anonymous requests (no action)" is selected in the the new Authentication page.
2. The Function App should redirect to the provider login page when "Require authentication" is selected in the the new Authentication page.

#### Actual behavior

The Function App always return 401 for all options in the authentication settings pane.

#### Known workarounds

N/A

#### Related information 

1. The problems **_don't_** exist on the Node.js 14 Function App using the consumption plan with Windows based instance so it may be related to the Linux instance use by the Python Function App
2. I believe that this issue is related to this [issue](https://github.com/Azure/static-web-apps/issues/512) regarding the bring your own function feature of the Azure Static Web App. Thus, we can't use Azure Static Web App with external Function App at this time due to this issue (at least for Python based Function App).
3. Revert to the old authentication page is not an option as it isn't being support by Azure Static Web App which require Authentication V2

**Comment by v-bbalaiagar** [comment]
Hi @nuntipat, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by pragnagopa** [comment]
Tagging @ConnorMcMahon fyi

@balag0  - can you please take a look and follow up?

**Comment by ConnorMcMahon** [comment]
Taking a look.

**Comment by ConnorMcMahon** [comment]
I have identified the bug and have a fix for it that we are working on testing. It will likely be some time before it is deployed.

In the meantime, this can be mitigated by going to resources.azure.com, navigating to /sites/config/authsettingsv2, and posting a null body. This will disable EasyAuth, and the classic experience can be used to enable the feature.

Thanks for bringing this to our attention.

**Comment by nuntipat** [comment]
@ConnorMcMahon Thank you for the update. I'm looking forward to test again after the fix is deployed. Meanwhile, could you please confirm whether this will fix my other related [issue](https://github.com/Azure/static-web-apps/issues/512) in the Static Web App repository.

**Comment by ConnorMcMahon** [comment]
This should also fix your static web app issue, as linking your function app to Static Web Apps uses the Authentication feature behind the scenes.

**Comment by ConnorMcMahon** [comment]
Workaround to downgrade to classic auth experience, which does not have this issue:

Note that the below can be done via raw ARM requests, a tool like azrest, or our browser ARM experience at https://resources.azure.com.

1. Retrieve the current settings at `/subscriptions/<subid>/resourceGroups/<resource-group>/providers/Microsoft.Web/sites/<sitename>/config/authsettings` with a POST command. Store this for later.
2. POST a `null` value to the "properties" property at `/subscriptions/<subid>/resourceGroups/<resource-group>/providers/Microsoft.Web/sites/<sitename>/config/authsettingsv2`
3. PUT the settings stored in step 1 to `/subscriptions/<subid>/resourceGroups/<resource-group>/providers/Microsoft.Web/sites/<sitename>/config/authsettings`.

**Comment by ConnorMcMahon** [comment]
The fix for the authsettingsv2 configuration has been deployed globally.

The new Authentication portal experience will be restore in the next two weeks or so.
