### ISSUE TITLE
Does Service Bus trigger use long pulling connections for get messages from Service Bus?

### ISSUE THREAD

**Issue by serhiisolodovnyk** [Azure/azure-functions-host#7560]
I would like to use Azure Functions V3(and V4)(C#) to process messages from Service Bus. But in the Service Bus with a Standard tier, there is a limit of 1000 free brokered connections. Will these connections be used for heavy workloads? 

Similar question:  
https://stackoverflow.com/questions/47911468/trigger-azure-function-from-service-bus-topic-without-consuming-brokered-connect

Price details Service Bus:
https://github.com/uglide/azure-content/blob/master/articles/service-bus/service-bus-pricing-billing.md

**Comment by v-anvari** [comment]
Hi @sergeysolod17 , The limitations would be same as service bus. You can find more information here https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=csharp

**Comment by serhiisolodovnyk** [comment]
Thank you, @v-anvari , I tested the trigger with Service Bus - it looks like 1 connection per function instance keeps constantly open. I think it won't be that expensive.

**Comment by v-anvari** [comment]
yes @sergeysolod17 , You can use up to 200 connections per instance. Closing this issue as the required information is provided, please feel free to reach back to us or re-open this issue in case of any queries.
