### ISSUE TITLE
Where to check actual/complete version number of the runtime

### ISSUE THREAD

**Issue by sadiqkhoja** [Azure/azure-functions-host#7564]
I have a function app running on Azure with FUNCTIONS_EXTENSION_VERSION = ~2, where can I find actual/complete version of the runtime?

**Comment by balag0** [comment]
You can get the complete version number in the portal overview page
![image](https://user-images.githubusercontent.com/28721598/127035496-59c5179f-6bd4-46ce-8276-8ab0577cad26.png)

**Comment by sadiqkhoja** [comment]
thanks

**Comment by sadiqkhoja** [comment]
doesn't seam to be right:

I have set Runtime version to ~2:
![image](https://user-images.githubusercontent.com/447837/127040036-0a7d1e0c-d6e9-4f3c-8c4f-a4c5bcadb093.png)


and overview page shows:

![image](https://user-images.githubusercontent.com/447837/127040089-bf48d708-b42e-4f3c-951a-38445fcac157.png)

**Comment by balag0** [comment]
It is by design. Checkout https://github.com/Azure/app-service-announcements-discussions/issues/175#issuecomment-661632013

**Comment by sadiqkhoja** [comment]
thanks
