### ISSUE TITLE
How to use items that were in Startup.cs --> Configure method is an Azure .NET 5 isolated process Function App

### ISSUE THREAD

**Issue by dcadlereii** [Azure/azure-functions-host#7573]
I am working with a new C# Function App using the .NET 5 dotnet-isolated where the examples only show the Program.cs and there is no Startup.cs class. I have an issue where I need to register a SyncFusion license, which I typically do in the Startup.cs -->Configure Method by using this line;

`Syncfusion.Licensing.SyncfusionLicenseProvider.RegisterLicense("...");`

But I do not know where to add this line in the new approach in a .NET 5 isolated process function where there is no Startup.cs file. 

Can anyone provide an example of where I would add things I would typically put in a Startup.cs --> Configure method? 

Is there some extension method you can daisy chain similar to the...

```
    .ConfigureServices(services =>
    {
         ...
         ...
         ...
     }
```

... used with the HostBuilder in the .NET 5 isolated process version of the program.cs file?

**Comment by v-bbalaiagar** [comment]
Hi @dcadlereii, Closing this issue as duplicate. For more updates please follow the space - https://github.com/Azure/Azure-Functions/issues/1990
