### ISSUE TITLE
Python Function App suddenly fails to sync triggers for functions with no changes to AzureWebJobStorage string or to the storage account

### ISSUE THREAD

**Issue by eranjbarSuncor** [Azure/azure-functions-host#7578]
#### Investigative information

Please provide the following:

- Timestamp: 8/3/2021 3:17:26 PM
- Function App version: 3.0.15828.0
- Function App name: iotdevarmfncuw2001 and iotdevarmfncuw2002
- Function name(s) (as appropriate): all functions within function apps
- Invocation ID: can't seem to find it in the logs
- Region: us west 2

#### Repro steps

Provide the steps required to reproduce the problem:

I have deployed a function app and uploaded functions to it. It works fine with no issues. I reupload my functions using the same workflow I utilized the first time but the functions failed to sync the trigger. I utilized the sample Github Actions workflow that is provided in the Microsoft Documentations regarding Function Apps [here](https://github.com/Azure/actions-workflow-samples/blob/master/FunctionApp/linux-python-functionapp-on-azure.yml)

#### Expected behavior

Provide a description of the expected behavior.

To work as expected, like it used to

#### Actual behavior

Provide a description of the actual behavior observed.

Here is my function app information:
![image](https://user-images.githubusercontent.com/82841988/128052773-fea830be-1055-4bad-8cff-0090f0dc2792.png)

I utilize the `Diagnose and solve problems` feature but run into this regarding functions triggering: 

![image](https://user-images.githubusercontent.com/82841988/128045868-f2e025e0-aa49-43b0-a446-da4903131b80.png)

and everything else is green:
![image](https://user-images.githubusercontent.com/82841988/128052643-d6849666-e9e0-4f3b-abba-0fc0668fd773.png)

I verified that my `AzureWebJobsStorage` is properly set to the right connection string of the storage account 

![image](https://user-images.githubusercontent.com/82841988/128046076-06e75c8f-4354-4b1e-9165-b0803f2823df.png)

and I have even refreshed the connection strings to the storage account and update the `AzureWebJobsStorage`... 

I have also checked the network for the storage account of the function app and verified that it is not integrated with a virtual network and no private endpoints are added to it: 

![image](https://user-images.githubusercontent.com/82841988/128046512-4fbb48d1-fb5d-4c5c-9fc1-81a7c6b9609e.png)

![image](https://user-images.githubusercontent.com/82841988/128046550-dcd9a9b0-3202-4cb1-a7b9-11e798620917.png)

I do have some private endpoints and virtual network integration for the python function app, but these have not caused this issue the first time around and are what I needed to do to get the Eventhub, which is behind a virtual network, to be able to trigger the function app.

![image](https://user-images.githubusercontent.com/82841988/128047454-6697bfb8-cc12-442b-889b-2ffaddbc0685.png)

I have tried to delete the function apps and their related storage accounts several times and recreate them but I keep running into the same issue

I have also verified that I am able to run the function locally with no issue while having my `local.settings.json` point the web job storage string to my storage account:

![image](https://user-images.githubusercontent.com/82841988/128050940-59086253-8e07-4ed6-8d5c-356f5bf16bdd.png)

#### Related information 

Provide any related information 

* Programming language used: Python
* Bindings used: EventHub triggers
<details>
<summary>Source</summary>

```python
from typing import List
import logging

import azure.functions as func


def main(event: func.EventHubEvent):
    logging.info(
        f'Function triggered to process a message: {event.get_body().decode()}')
    logging.info(f'  EnqueuedTimeUtc = {event.enqueued_time}')
    logging.info(f'  SequenceNumber = {event.sequence_number}')
    logging.info(f'  Offset = {event.offset}')
```
</details>

**Comment by v-bbalaiagar** [comment]
Hi @eranjbarSuncor, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @eranjbarSuncor, I checked on this issue internally and they suggested you to reach out to support. This seems like a production impacting issue and, it's just not the best form for you to file these kinds of issues, particularly with issues that are so specific in configuration.
