### ISSUE TITLE
Develop worker indexing unit tests

### ISSUE THREAD

**Issue by anandagopal6** [Azure/azure-functions-host#7582]
Unit tests need to be developed to ensure that the worker-indexing code path functions properly.

<h3>Potential Test Cases</h3>

- [ ] GrpcWorkerChannel
  - [x] Mock inbound successful FunctionMetadataResponses event
  - [x] Mock inbound failed FunctionMetadataResponses event
  - [ ] TimeoutException for receiving FunctionMetadataResponses
- [x] RpcFunctionInvocationDispatcher
  - [x] Create maxProcessCount GrpcWorkerChannels in reorganized InitializeAsync call
  - [x] Create GrpcWorkerChannels and setup invocation buffers after receiving function metadata
  - [x] Null functions parameter and not worker indexing
- [ ] WorkerFunctionMetadataProvider
  - [x] Valid and invalid function name
  - [x] Valid and invalid bindings
  - [ ] GetFunctionMetadataAsync mock metadata response and dispatcher
- [x] Utility.CanWorkerIndex()
  - [x] Enabled feature flag + worker config property
  - [x] Enabled feature flag + missing worker config property
  - [x] Disabled feature flag + worker config property
  - [x] Disabled feature flag + missing worker config property
  - [x] Null worker config file
  - [x] Null worker config description
  - [x] Null workerIndexing attribute
- [ ] FunctionMetadataManager
  - [ ] Mock worker configs and check to see if correct provider is returned
- [x] ScriptStartupTypeLocator
  - [x] If workerIndexing, get all types

**Comment by fabiocav** [comment]
Closing as the work being tracked here has been completed.
