### ISSUE TITLE
Remove APPINSIGHTS_INSTRUMENTATIONKEY from app settings creation 

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-host#7587]
During the transition to the new Application Insights connection string setting (`APPLICATIONINSIGHTS_CONNECTION_STRING`), we've been continuing to also add the legacy `APPINSIGHTS_INSTRUMENTATIONKEY` setting. We're starting to see customers comment on this and there's confusion because of [this statement in the App Insights docs](https://docs.microsoft.com/en-us/azure/azure-monitor/app/sdk-connection-string?tabs=net):
![image](https://user-images.githubusercontent.com/1388263/128542477-1706ff79-b209-44c3-8383-dcc74bea7766.png)

We should stop creating the `APPINSIGHTS_INSTRUMENTATIONKEY` setting.

**Comment by v-anvari** [comment]
Tagging @fabiocav / @brettsam , for further inputs

**Comment by fabiocav** [comment]
@ehamai is this something you/your team would be able to do? This is happening in the create flow.

**Comment by liliankasem** [comment]
@shimedh is this something you and your team can take a look at? :D

**Comment by shimedh** [comment]
Currently we are adding both instrumentation key as well as connection string during creates. We have two other places where we depend on instrumentation key that needs to be updated before we can update creates. We have WI's for all. Also had a meeting with @anthonychu , @apawast, @AnatoliB and others and they are going to sync with AI folks and decide on a plan before we update all tooling including Portal.

**Comment by liliankasem** [comment]
@shimedh @AnatoliB - any new updates on this?

**Comment by fabiocav** [comment]
@shimedh is there a better place to track this? If not, do you have any updates? Thanks!

**Comment by shimedh** [comment]
> @shimedh is there a better place to track this? If not, do you have any updates? Thanks!

We are tracking it with WI - https://msazure.visualstudio.com/Antares/_workitems/edit/10531370
It has dependency on ANT99.
Yutang (@yutanglin16) is the PM tracking this with AI team.

**Comment by brettsam** [comment]
Closing as this is being tracked elsewhere.
