### ISSUE TITLE
Erroneous dispatcher state when webhostLanguageWorkerProcess doesn't come up

### ISSUE THREAD

**Issue by yojagad** [Azure/azure-functions-host#7590]
Language worker processes can fail to come up during runtime startup.

An example of successful process startup is 
![image](https://user-images.githubusercontent.com/26885664/131417662-a34bbb01-41f7-4c90-9b8b-a8ffa7c8c34d.png)

An example of unsuccessful process startup is 
![image](https://user-images.githubusercontent.com/26885664/131417707-0f82fa31-aa0b-4336-ab23-6207123a9c8f.png)

In the second scenario mentioned, currently the dispatcher is **still** set to `initialized` thus, requests being routed to erroneous channels. 

The original design is for the Dispatcher to wait until a certain timeout period and then shutdown the runtime if it does not (https://github.com/Azure/azure-functions-host/blob/2520fdb09fbaf7518925f8aaea618dd9b95de7ba/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs#L63) .

This workitem is to ensure that `dispatcher` state is not set to `initialized` in case of language worker process startup errors thus conforming to the original, intended design.

cc: @pragnagopa @AnatoliB @alrod @amamounelsayed @fabiocav

**Comment by fabiocav** [comment]
@yojagad I see there's a PR open for this, so I'm leaving in 107, but let me know if you need to move.
