### ISSUE TITLE
BlobStorageSecretsRepository Write failure should fail key creation request

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-functions-host#7591]
We're seeing cases where a PUT to admin/host/functionkeys/testkey0 succeed and return 201 created, even though there was an exception thrown from the blob persistence logic [here](https://github.com/Azure/azure-functions-host/blob/91b7d1c780f2e040d32b02b38f6af5bab4799c96/src/WebJobs.Script.WebHost/Security/KeyManagement/BlobStorageSecretsRepository.cs#L191). So somewhere upstream we must be swallowing this exception. If the persistence fails, the PUT request should fail. 

Additionally, the error message is rather poor in these cases. We only log "There was an error performing a write operation on the Blob Storage Secret Repository. Please ensure the 'AzureWebJobsStorage' connection string is valid.". We should provide more details on the actual underlying storage exception, rather than offering the unhelpful bit on checking the storage connection string.

See recent CRI #251344724

**Comment by fabiocav** [comment]
@soninaren it would be good to validate the read paths as @liliankasem ran into some issues that could be similar in the read path.
