### ISSUE TITLE
Azure Function configuration does not get latest version of Key Vault secret

### ISSUE THREAD

**Issue by codebrane** [Azure/azure-functions-host#7596]
A function that initially has a versioned Key vault Reference in its Configration never reads the current version after a configuration change.

#### Repro steps

Create a function with a versioned Key vault Reference of the form:

`TheSecret`
`@Microsoft.KeyVault(SecretUri=https://name.vault.azure.net/secrets/TheSecret/__version__)`

and in the Function:

```
if (!int.TryParse(Environment.GetEnvironmentVariable("TheSecret"), out int theSecret))
{
    theSecret = 10;
}
```

The first time the function runs it retrieves the specific version of the secret.

Create a new version of `TheSecret` in the Key Vault and change the function application configuation to the non-versioned type:

`TheSecret`
`@Microsoft.KeyVault(SecretUri=https://name.vault.azure.net/secrets/TheSecret/)`

The original version of `TheSecret` in the Key Vault was 60, the default in the code is 10 and the current version in the Key Vault is 120. 60 is always returned, i.e. the version it first read.

The function never reads the latest version of the secret. It always reads the first one it was configured to use, i.e. the versioned one. Even after restarting the function or re-publishing it, it always reads the versioned secret it was first configured to use.

**Comment by codebrane** [comment]
I came across [this issue](https://stackoverflow.com/questions/55487930/key-vault-value-does-not-update-if-value-changes-in-secret-as-it-generates-new-v) that suggests restart doesn't work and start/stop is required but that doesn't work either.

[This issue](https://stackoverflow.com/questions/61026882/issue-with-azure-function-configuration-object-caching) also describes the observed behaviour.

**Comment by codebrane** [comment]
The specific version of the secret that is being read is disabled in the Key Vault and the only other place that version is referenced is in local.settings.json which isn't published.

**Comment by v-bbalaiagar** [comment]
Hi @codebrane, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.
Meanwhile, Can you please go through the [SO ](https://stackoverflow.com/questions/62496934/azure-function-app-use-latest-version-of-key-vault-secret-via-application-settin)which addresses similar scenario.
Please check and let us know if this helps.

**Comment by codebrane** [comment]
thanks for that. I can work round it using the new format for code access to Key Vault:
```

public static async Task<string> GetSecretFromKeyVault(string secretName)
{
    var client = new SecretClient(new Uri("https://name.vault.azure.net"), new DefaultAzureCredential());
    var secret = await client.GetSecretAsync(secretName).ConfigureAwait(false);
    return secret.Value.Value;
}

```

**Comment by v-bbalaiagar** [comment]
Hi @codebrane, Apologies for the delayed response. Were you able find a solution? Let us know if you have any further queries related to this issue. I shall follow with the right team members to resolve this issue.

**Comment by codebrane** [comment]
I only have the manual workaround above as the function configuration doesn't read the latest secret version. It reads it once and not again.

**Comment by v-bbalaiagar** [comment]
Hi @codebrane, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @codebrane, Apologies for the delayed response, I checked this internally. 

Regarding things to try, here are a few : 
1. Try removing the trailing slash - that could confuse it (though unlikely)
2. Alternatively, try using the other syntax form for this, `@Microsoft.KeyVault(VaultName={vault_name};SecretName={secret_name})`
3. Stop & start (not restart) the function app (I've seen this make a difference, though it shouldn't in theory)

If all these fail, disable the system msi, re-enable & confirm secret get permissions are assigned within the key vault policies. (note you will have to stop/start the function app after doing this).

**Comment by codebrane** [comment]
I tried restarting, stopping/starting the app but it didn't fix it.
I tried removing the trailing slash from the secret url but it didn't fix it.

The only way to get the function app to read the latest version of the secret is to make a change to the configuration setting, adding/removing the trailing slash, just to get it to save the configuration. It's the act of saving the configuration that seems to force the app to read the latest secret version.

**Comment by balag0** [comment]
Yes, restarting the app doesn't guarantee a refresh.

From
https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references#rotation

>Any configuration changes made to the app will cause an immediate update to the latest versions of all referenced secrets.

**Comment by codebrane** [comment]
There doesn't seem to be a way for a function app to read the actual latest version of a secret, in the sense that latest version should be the actual latest version, rather than reading a "latest version" URL and cacheing the value. Unless I can get the configuration Save button to enable the function app never reads the latest version value of the secret.

It would appear that code is the only workaround as the function read the value from the "latest version" URL and caches it. If a new latest version is added to the secret, the function doesn't know and never uses it. "Latest version" should mean the value of the latest version.

Is this just how function apps work? Should configuration be avoided (as it doesn't update) and use code instead to get the actual latest version of a secret?

**Comment by balag0** [comment]
Automatic refresh happens within 24 hours. Just to clarify, are you looking for a way to refresh more frequently?

From https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references#rotation
> When newer versions become available, such as with a rotation event, the app will automatically update and begin using the latest version within one day
