### ISSUE TITLE
Removal of X-Powered-By HTTP header for Azure Functions v1 on Consumption plan

### ISSUE THREAD

**Issue by thiensk** [Azure/azure-functions-host#7602]
#### Is your question related to a specific version? If so, please specify:
Azure Functions **V1.x** on **consumption plan**, HTTP triggered

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
We are using multiple azure functions (V1, consumption plan) which are http triggered. Recently we underwent a security scan and the result of it is a task to remove the X-Powered-By http header property.

- We have to stick with consumption plan so [solution ](https://github.com/Azure/azure-functions-host/issues/1237#issuecomment-406341047) to create a Web App and use the same hosting plan for functions  is not feasible 
- No plans so far to upgrade azure functions  to v2, where this issue has been already solved by this [fix](https://github.com/Azure/azure-functions-host/commit/88615cdb573c34ce076ce65dacf7746e5e1735e7)
- using proxies.json responseOverrides to clear the property doesn't work. As a result there are actually two X-Powered-By properties present 
![image](https://user-images.githubusercontent.com/26627672/129017065-4c314a7f-9ff8-4a8a-b463-e80f0206ecde.png)

Is there any way how to remove this property?

**Comment by v-bbalaiagar** [comment]
Hi @thiensk, Thank you for your feedback, I checked on this issue internally, the only recommendation we can provide here is to move V3 or V4 at this point. 
We would be good to understand why you are unable to move to V2, V2 is not a recommended version to be moving to at this point, so it will be V3 or V4, We can provide an answer here stating that this is not a change that we're planning to make to V1 at this point.

**Comment by thiensk** [comment]
Thanks.. I am new at this project but I guess it's a situation that if it works it works, do not touch it until it's not really urgent.. Will propose the upgrade then..
