### ISSUE TITLE
Controlling scale out alternatives?

### ISSUE THREAD

**Issue by jaltin** [Azure/azure-functions-host#7604]
I see that there are several options for controlling scale out:

**1 - functionAppScaleLimit** (https://github.com/MicrosoftDocs/azure-docs/blob/4f0990d78d5ece72d35a83b2f8d52a78fe425765/articles/azure-functions/event-driven-scaling.md#limit-scale-out)

**2 - WEBSITE_MAX_DYNAMIC_APPLICATION_SCALE_OUT** (https://github.com/MicrosoftDocs/azure-docs/blob/4f0990d78d5ece72d35a83b2f8d52a78fe425765/articles/azure-functions/functions-app-settings.md#website_max_dynamic_application_scale_out)

**3 - Setting it manually via Azure portal**

I see that WEBSITE_MAX_DYNAMIC_APPLICATION_SCALE_OUT is in preview and has been so for a long time. Is it ever going to be graduating from preview?

For our needs I would prefer to use WEBSITE_MAX_DYNAMIC_APPLICATION_SCALE_OUT but wanted to know if it is reliable and we can use it.

**Comment by balag0** [comment]
functionAppScaleLimit is the way to go. functionAppScaleLimit replaces WEBSITE_MAX_DYNAMIC_APPLICATION_SCALE_OUT.

**Comment by jaltin** [comment]
Thanks for verifying that @balag0. Closing this issue.
