### ISSUE TITLE
PUT /admin/functions/{funcName} should return 400 if file system is readonly

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-host#7625]
Check file system status using
https://github.com/Azure/azure-functions-host/blob/a90271a7430af9bb8ba0554461927151301226ad/src/WebJobs.Script/Config/ScriptApplicationHostOptions.cs#L35

Changes needed would be similar to how appoffline is implemented.

**Comment by brettsam** [comment]
@pgombar -- should we move this to Sprint 109? 108 is ending today...
