### ISSUE TITLE
dotnet runtime rid not being considered causing incorrect "platform dependent" assembly load from nuget package 

### ISSUE THREAD

**Issue by AnuragSingh-MSFT** [Azure/azure-functions-host#7626]
Summary:
Runtime: .NET 3.1
OS: Windows
Language: C#
Sdk: Microsoft.NET.Sdk.Functions v3.0.13
 
Unable to create PerformanceCounter after upgrading Nuget "System.Diagnostics.PerformanceCounter" from version 4.7.0 to 5.0.0, and it fails with error below:
 
System.PlatformNotSupportedException : Performance Counters are not supported on this platform.
Assembly: System.Diagnostics.PerformanceCounter, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
 
This happens on dev machine as well as in Azure (under lying OS being Windows)

Repro steps & Workaround:
Repro:
1.	Create Azure functions app from VS with HTTP trigger. 
2.	Add Nuget package "System.Diagnostics.PerformanceCounte" version 5.0.0
3.	In the created function "Function1", include the following line so that it gets called when the function is triggered:
 
PerformanceCounter pCtr = new PerformanceCounter();
 
4.	Run the function app locally. 
5.	Triggering this function would result in the System.PlatformNotSupportedException being thrown. The same behavior is observed when the function is deployed in Azure. 
 
Workaround:
Include the following in .csproj file for this function under <PropertyGroup> (When the app is deployed to Windows)
 
`<runtimeidentifier>win</runtimeidentifier>`
 
Ref: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog
 
This ensures the dotnet runtime to look for the correct platform dependent library to be loaded from Nuget package (in current scenario - Windows). 
 
Additional information:
The issue does not happen when using version 4.7.0 of this assembly as it gets loaded from the cli tools directory instead of the project bin directory. 

Ask:
Please include the "resource identifier (rid)" into consideration for function app runtime in Azure and cli tools, so that "platform dependent" assemblies can be correctly loaded from Nuget packages.

**Comment by v-anvari** [comment]
Hi @AnuragSingh-MSFT , The 5.x.x packages are targeted only for the .Net 5 runtime.  Your project is targeted to .net 3.1, so you can only use the packages lower than 5.x.x

**Comment by AnuragSingh-MSFT** [comment]
Thank you @v-anvari. 
The 5.0.0 version of this nuget package supports .NET standard 2.0 and higher (ref: [System.Diagnostics.PerformanceCounter](https://www.nuget.org/packages/System.Diagnostics.PerformanceCounter/5.0.0)). Therefore, based on my understanding, .NET Core 3.1 would also support it. (ref: [.NET standard implementation support](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support)). 

The issue here is not related to this specific package. It will impact reference to any other package which has platform dependent assemblies.

**Comment by AnuragSingh-MSFT** [comment]
@v-anvari, I wanted to check if you had a chance to review my comment earlier and if you have any questions.

**Comment by v-anvari** [comment]
Hi @AnuragSingh-MSFT , My apologies, Yes I have seen your response, I am sure why the bot failed to change the label. I shall move this issue for review.

**Comment by fabiocav** [comment]
@AnuragSingh-MSFT those specific dependencies are indeed unified by the host and 5.0 is not supported in Functions 3.0. 

The options you can explore are:
 - .NET Isolated (currently supported, targeting .NET 5.0)
 - .NET 6.0 support in Functions 4.0 (currently in preview, supporting in-proc and isolated)
