### ISSUE TITLE
Cannot deploy managed-identity-awere queue and blob triggered functions in the same Azure Functions app

### ISSUE THREAD

**Issue by mdddev** [Azure/azure-functions-host#7636]
Hello

I'm trying to deploy an Azure Functions app (Windows/consumption) using blob and queue triggered functions. My ultimate goal is to _not_ use shared account key authentication with Azure Storage. This goes for the account used by AF internally (AzureWebJobsStorage) and any account used for bindings/triggers. Ideally I want  to re-use the single storage account that is created when initially deploying the function app (V1-storage). This was never an issue when authenticating with storage account keys.

I have gotten it running when only using a queue-triggered function. It fails when a blob-triggered functions is added.

After restarting the app, a warning message appers in the portal: `System.IO.FileSystem: The user name or password is incorrect. : 'C:\home\LogFiles\Application\Functions\Host'.`.

Below please find the information for my setup. 

* Windows consumption-tier app
* NET Core 3.1
* Storage account: _Disabled_ blob public access
* Storage account: _Disabled_ storge account key access
* Has system-assigned MSI enabled with the following RBAC permissions
* --Key Vault Secrets User
* --Storage Blob Data Owner (account scope)
* --Storage Queue Data Contributor (account scope)

And here is the code. As you can see it's really boilerplate code to keep things simple for debugging.

functions
```csharp
using System.IO;
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Logging;

namespace meh
{
    public static class functions
    {
        [FunctionName("queue")]
        public static void Run([QueueTrigger("meh")]string myQueueItem, ILogger log)
        {
            log.LogWarning($"C# Queue trigger function processed: {myQueueItem}");
        }

        [FunctionName("blob")]
        public static void Run([BlobTrigger("blobbo/{name}")]Stream myBlob, string name, ILogger log)
        {
            log.LogInformation($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");
        }

        // ... other
    }
}
```

csproj-file: note the beta5 storage extensions version
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.0-beta.5" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.7" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

host.json
```json
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingExcludedTypes": "Request",
            "samplingSettings": {
                "isEnabled": true
            }
        }
    }
}
```

app settings: I also experimented with having separate names for the function connetion string references (BlobConnection and QueueConnection, and then specifying this in the functions' connection attribute, but this did not help unfortunately.
```json
[
  {
    "name": "APPLICATIONINSIGHTS_CONNECTION_STRING",
    "value": "@Microsoft.KeyVault(SecretUri=https://<my-key-instance>.vault.azure.net/secrets/app-insights/)",
    "slotSetting": false
  },
  {
    "name": "AzureWebJobsStorage__accountName",
    "value": "<my-v1-storage-af-account>",
    "slotSetting": false
  },
  {
    "name": "BlobConnection__accountName",
    "value": "<my-v1-storage-af-account>",
    "slotSetting": false
  },
  {
    "name": "BlobConnection__credential",
    "value": "managedIdentity",
    "slotSetting": false
  },
  {
    "name": "FUNCTIONS_EXTENSION_VERSION",
    "value": "~3",
    "slotSetting": false
  },
  {
    "name": "FUNCTIONS_WORKER_RUNTIME",
    "value": "dotnet",
    "slotSetting": false
  },
  {
    "name": "QueueConnection__accountName",
    "value": "<my-v1-storage-af-account>",
    "slotSetting": false
  },
  {
    "name": "QueueConnection__credential",
    "value": "managedIdentity",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_RUN_FROM_PACKAGE",
    "value": "https://<my-v1-storage-af-account>.blob.core.windows.net/zip/run.zip",
    "slotSetting": false
  }
]
```

Looking forward to any help you can offer. Cheers

**Comment by v-anvari** [comment]
Hi @mdddev , Thank you for reaching out to us,  We will investigate this further and update you with the findings. Meanwhile, have you tried this scenario with lower versions of "Microsoft.Azure.WebJobs.Extensions.Storage". Let us know the output.

**Comment by mdddev** [comment]
Hi @v-anvari , I just tested this with the beta 3 and beta 4 versions of the storage extension package. It did solve the problem of the host not starting up. So there are no more error messages. Still, the functions are not triggered when uploading a blob or enqueing a message. Looking at the trace logs in application insights it states `0 functions loaded`

**Comment by v-anvari** [comment]
Hi @mdddev , I try to reproduce the issue and there were few other issues raised on the beta versions of storage. Now when I try to reproduce the issue. Can you let us know by using the stable versions if you are still seeing the errors 

![image](https://user-images.githubusercontent.com/66122429/132247383-6e51b8bd-4f6a-44cb-8caf-0d3b484f0883.png)

**Comment by mdddev** [comment]
@v-anvari Thanks for reaching out. I was under the [impression](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob#storage-extension-5x-and-higher) that MSI support was only recently introduced in the version 5 (currently in beta) of the storage extension, so according to the available [docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#configure-an-identity-based-connection) from MS I have not tried the stable version 4 in this context. Should I? Was there a recent functional upgrade to v4 (MSI-capabilities)?

**Comment by mdddev** [comment]
###  Update
To further debug this, I tried changing the suffix of the connection name configuration values for the blob and queue triggers to the following (as suggested [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#:~:text=If%20%22AzureWebJobsStorage%22%20will%20be%20used%20for%20any%20other%20service%2C%20you%20may%20instead%20specify%20AzureWebJobsStorage__blobServiceUri%2C%20AzureWebJobsStorage__queueServiceUri%2C%20and%20AzureWebJobsStorage__tableServiceUri%20separately)).

```json
...
  {
    "name": "BlobConnection__blobServiceUri",
    "value": "https://<my-v1-storage-af-account>.blob.core.windows.net",
    "slotSetting": false
  },
  {
    "name": "QueueConnection__queueServiceUri",
    "value": "https://<my-v1-storage-af-account>.queue.core.windows.net",
    "slotSetting": false
  },
...
```

```csharp
///...
        [FunctionName("queue")]
        public static void Run([QueueTrigger("meh", Connection = "QueueConnection")]string myQueueItem, ILogger log)
        {
            log.LogWarning($"C# Queue trigger function processed: {myQueueItem}");
        }

        [FunctionName("blob")]
        public static void Run([BlobTrigger("blobbo/{name}", Connection = "BlobConnection")]Stream myBlob, string name, ILogger log)
        {
            log.LogInformation($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");
        }
```

Additionally, I granted the `Storage Blob Data Contributor` role to the MSI (it has `Storage Blob Data Owner` already, though).

Unfortunately, I am still not able to get it to work.

**Comment by v-anvari** [comment]
My apologies you are right, the support is introduced with the beta versions. Recently there were few fixes and changes implemented which is documented here.

 https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Queues/CHANGELOG.md#500-beta4-2021-05-18

Can you try using the below configuration and let us know if that works.

{
    "MyStorageConnection1": {
        "blobServiceUri": "https://<my_account>.blob.core.windows.net",
        "queueServiceUri": "https://<my_account>.queue.core.windows.net"
    },

    "MyStorageConnection2": {
        "accountName": "<my_account>"
    }
}

**Comment by v-anvari** [comment]
Can I also have you complete Local.settings.json file. In you case, can I see the App settings file. Can you make sure the settings are in the same format as below, 

{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "<language worker>",
    "AzureWebJobsStorage": "<connection-string>",
    "MyBindingConnection": "<binding-connection-string>",
    "AzureWebJobs.HttpExample.Disabled": "true"
  },
  "Host": {
    "LocalHttpPort": 7071,
    "CORS": "*",
    "CORSCredentials": false
  },
  "ConnectionStrings": {
    "SQLConnectionString": "<sqlclient-connection-string>"
  }
}

**Comment by v-anvari** [comment]
One more detail to check is that, since you have disabled the access to storage account keys, and managing keys from the key vault, Before Key Vault can access and manage your storage account keys, you must authorize its access your storage account. The Key Vault application requires permissions to list and regenerate keys for your storage account. These permissions are enabled through the Azure built-in role Storage Account Key Operator Service Role. 

Here is the document explaining the steps. Can you confirm me this as well. 
https://docs.microsoft.com/en-us/azure/key-vault/secrets/overview-storage-keys-powershell#give-key-vault-access-to-your-storage-account
