### ISSUE TITLE
Cannot build function projects using .NET 6 previews

### ISSUE THREAD

**Issue by johnkors** [Azure/azure-functions-host#7642]
Hi, 

could you take a look at [this issue](https://github.com/Azure/azure-webjobs-sdk/issues/2755) and check if it makes more sense to move it to this repo?

Thanks

**Comment by v-bbalaiagar** [comment]
As this issue is being addressed in [#2755](https://github.com/Azure/azure-webjobs-sdk/issues/2755), closing this issue as duplicate.
