### ISSUE TITLE
Core 3.1 app has different behavior when in a Function

### ISSUE THREAD

**Issue by jdluzen** [Azure/azure-functions-host#7643]
We currently have a Core 3.1 app using EntityFramework and the Windows only Sql Spatial assemblies running fine. I put a Function around it, and EntityFramework/SqlClient throws an exception: `System.Data.SqlClient: No mapping exists from object type Microsoft.SqlServer.Types.SqlGeography to a known managed provider native type.`

After many hours of isolating and debugging, my current working theory is that somehow multiple assemblies and/or types are stepping on each other. There are two different versions of `System.Data.SqlClient` loaded at the same time. I found one being used in my normal output folder, and another in the Host Function's folder. I create a brand new .NET5 Function out of proc, and it works fine. 

Reading through a good number of GitHub and SO posts, I see some that come close but don't quite match up to what I'm seeing here. Does this sound plausible and could someone point me in the direction to debug this further?

**Comment by jdluzen** [comment]
This does seem to be the case. Removing the direct project reference from the Function, loading the business logic Assembly in the Default AssemblyLoadContext, and manually Invoke() it through reflection, it works.

**Comment by v-anvari** [comment]
Hi @jdluzen , From you latest comments, can we know if you were able to resolve the issue. Let us know if you have any further queries

**Comment by jdluzen** [comment]
I'm not sure if Resolved is the proper term. This workaround does work, but it exerts a heavy price. Our build pipeline and solution needs to change to accommodate complete separation of the Function and business projects. We'll also likely need to setup Dependency Injection more manually than out of the box. I would appreciate some comments to whether or not this behavior is a known issue, likely referenced here https://github.com/Azure/azure-functions-host/wiki/Assembly-Resolution-in-Azure-Functions, or if this is something unexpected.

**Comment by v-anvari** [comment]
Hi @jdluzen , Apologies for the delayed response. We need to understand the project scenario and expected behavior to be able to reproduce the issue and understand if there are any errors that could be resolved

**Comment by v-anvari** [comment]
Can you also point us to the paragraph in the wiki that you are pointing to

**Comment by jdluzen** [comment]
I've been attempting to come up with a self contained repro sample for you, but have been unsuccessful so far.

The type mismatching is referred in https://github.com/Azure/azure-functions-host/wiki/Assembly-Resolution-in-Azure-Functions#what-are-the-challenges-when-running-on-azure-functions under the first bullet point mentioning JObject. This also lines up with what I am seeing here under the last bullet point mentioning the assembly being loaded multiple times: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext?view=netcore-3.1#technical-challenges.

The Exception in the first post has a reference to type mapping, and the code around the Exception being thrown is doing just that: https://github.com/microsoft/referencesource/blob/master/System.Data/System/Data/SqlClient/assemblycache.cs#L58 So that is my guess, the registered type in a Dictionary (https://github.com/microsoft/referencesource/blob/master/System.Data/System/Data/SqlClient/SqlUdtInfo.cs#L62) can't be found because it's coming from different AssemblyLoadContexts. Unfortunately as mentioned earlier, I am unable to fully prove that this is what is happening.

**Comment by v-anvari** [comment]
Can you provide the csproj file for both the cases ie, .Net 3.1 and .Net 5
