### ISSUE TITLE
Azure Function App misses Continous Deployment choices

### ISSUE THREAD

**Issue by BrutalCSkakan** [Azure/azure-functions-host#7650]
I can only see Github as a valid CI/CD option in the Deployment Center. 
I know for a fact that there's more, which I also can see in the Networking tab in my browser. 

Image with the missing options:
![image](https://user-images.githubusercontent.com/8394703/132242252-0aa89579-6bac-4223-9786-4eb54952ecf7.png)

Image from the Network tab stating that there's 4 different CI/CD services
![image](https://user-images.githubusercontent.com/8394703/132242431-ffcbb82b-bdf9-4239-9c45-4bbd20569165.png)

As you can see, there's already some expiry date on the Bitbucket service, but that was configured for another Function App earlier. More specific, it was created for a Function app - Which I then deleted and created a new one (I had the wrong region), which had the exact same name.

There's no error in the console, and the page seems to work fine. 

Why isn't the Bitbucket service available for me?

**Comment by v-anvari** [comment]
Hi @BrutalCSkakan , You should be able to see all the options. Can we know if you are creating a function App locally? 
Also, which location is the current function App.

![image](https://user-images.githubusercontent.com/66122429/132243936-b975a39f-2234-4168-95cf-49620cd99311.png)

**Comment by v-anvari** [comment]
Can we also know the OS of the Function App

**Comment by BrutalCSkakan** [comment]
Hi @v-anvari 
The app is created from the Portal, and then maintained through the Azure Function plugin in Visual Code.
The location is North Europe, and it's running Linux with Java 11.

**Comment by v-anvari** [comment]
Hi @BrutalCSkakan , If the App is a Consumption plan, then Continuous deployment is not yet supported for Linux apps running on a Consumption plan.

Here is the document https://docs.microsoft.com/en-us/azure/azure-functions/functions-continuous-deployment
