### ISSUE TITLE
Activity.Current is null

### ISSUE THREAD

**Issue by Zenuka** [Azure/azure-functions-host#7651]
I've noticed that some of our apps have stopped adding custom properties to our application insights telemetry. To investigate I started a new v2 function app project (.net core 3.1 and Microsoft.NET.Sdk.Functions nuget 3.0.13) and noticed that `Activity.Current` is null. 

#### Repro steps
The function below will throw a `NullReferenceException` on the first line with `Activity.Current.AddTag("test", "value");`
```C#
[FunctionName("Function1")]
public static async Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
    ILogger log)
{
    Activity.Current.AddTag("test", "value");
    log.LogInformation("C# HTTP trigger function processed a request.");

    string name = req.Query["name"];

    string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
    dynamic data = JsonConvert.DeserializeObject(requestBody);
    name = name ?? data?.name;

    string responseMessage = string.IsNullOrEmpty(name)
        ? "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."
        : $"Hello, {name}. This HTTP triggered function executed successfully.";

    return new OkObjectResult(responseMessage);
}
```

#### Expected behavior

I expect `Activity.Current` to not be null so I can use that to add information to my request telemetry in application insights.

#### Actual behavior

`Activity.Current` is null.

#### Known workarounds

I don't know any workarounds.

#### Runtime version
```
Core Tools Version:       3.0.3442 Commit hash: 6bfab24b2743f8421475d996402c398d2fe4a9e0  (64-bit)
Function Runtime Version: 3.0.15417.0
```

**Comment by v-anvari** [comment]
Hi @Zenuka , Can we know your CSproj file. Similar scenarios were fixed/ tracked earlier as mentioned here - https://github.com/Azure/azure-functions-host/issues/5014 and https://github.com/Azure/azure-functions-host/issues/7278

**Comment by Zenuka** [comment]
Ah sorry, I missed those.
My .csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.9" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

I used the Visual Studio new function app template.

**Comment by v-anvari** [comment]
Tagging @brettsam / @fabiocav  for further investigation

**Comment by Zenuka** [comment]
I've also tried the workaround proposed in #7278 (downgrading to version 4.6 of System.Diagnostics.DiagnosticSource) without success.

**Comment by v-anvari** [comment]
Hi @Zenuka , We are tracking a similar issue due to the dependency miss match and is being addressed for the issue. As a temporary work around you can delete the System.Diagnostics.DiagnosticSource on the project file and unify it to the dependency in the host file. There must be a dependency miss match, one from the project and one from the host.

**Comment by Zenuka** [comment]
How do I know which version to use? In my production app, there is no direct reference in my project file to `System.Diagnostics.DiagnosticSource` but only indirect ones from a lot of nuget packages (app insights, service bus, storage blobs, cosmos, key vault). They all use version 5.0.0. I could not find any information on how to unify dependencies in the host file, do you have some information about that?

In the plain sample I provided above, what would you recommend to do?

**Comment by v-anvari** [comment]
Hi @Zenuka , As you say that there are different Nuget packages that are being referenced. Can you check all the dependencies to Diagnostic source. Also, since you are working on .Netcore 3.1 version, packages with 5.x.x versions are not supported. Can we have the details of all those packages, because I dont see them in the csproj file

**Comment by Zenuka** [comment]
Thanks for your quick reply! The .csproj file I supplied was meant for an easy and reproducible sample. This was created using File -> New Solution in Visual Studio. 

Why is `System.Diagnostics.DiagnosticSource` with version 5.x not supported on .net core 3.1? 

This is a screenshot from our function app with the dependency tree using `System.Diagnostics.DiagnosticSource`:
![image](https://user-images.githubusercontent.com/5391012/133990594-d81aa796-8eaf-4b1d-82bb-a488e7c5b9cb.png)

We also reference [Microsoft.ApplicationInsights](https://www.nuget.org/packages/Microsoft.ApplicationInsights/)  in a shared project which has a dependency set to >= 5.0.0.
![image](https://user-images.githubusercontent.com/5391012/133991293-0e363fa1-3c10-4fc2-8828-1c2be3de7915.png)
![image](https://user-images.githubusercontent.com/5391012/133991298-d0f16ac2-52f6-416b-a06f-6cd40eece8fd.png)

**Comment by v-anvari** [comment]
Hi @Zenuka , You should be able to add a package explicitly to System.Diagnostics.DiagnosticSource package. This will over ride the dependent packages. Can you try doing this and let us know if that works.

https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/4.7.1

dotnet add package System.Diagnostics.DiagnosticSource --version 4.7.1

**Comment by Zenuka** [comment]
For my production apps I was able to add the reference by modifying my project files with the follow lines:
```
<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="4.7.1">
  <NoWarn>NU1605</NoWarn>
</PackageReference>
```
Unfortunately, `Activity.Current` is still null. Same goes for the sample I provided using the following project file:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="4.7.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

Are you able to get it working with a basic sample?

**Comment by v-anvari** [comment]
Hi @Zenuka , Thank you for the feedback, this issue is a known issue and is being tracked here - https://github.com/Azure/azure-functions-host/issues/7278, and this is because the package was removed from unification. Team is tracking the problem to fix it. This scenario is different for different code samples. I haven't tried to repro your code yet.  If 4.7.1 isn't working, please downgrade further and let me know if that works.  

Some more information:
https://github.com/Azure/azure-functions-host/issues/5014

**Comment by Zenuka** [comment]
I've tried downgrading to the following versions without success: `4.7.1, 4.7.0, 4.6.0, 4.5.1, 4.5.0, 4.4.1, 4.4.0`. My sample was created using the default azure function template in Visual Studio 16.10.4. The project is .net core 3.1 and references `Microsoft.NET.Sdk.Functions 3.0.13`. The runtime that is used is:
```
Azure Functions Core Tools
Core Tools Version:       3.0.3442 Commit hash: 6bfab24b2743f8421475d996402c398d2fe4a9e0  (64-bit)
Function Runtime Version: 3.0.15417.0
```
The line I added to the generated http function is: `Activity.Current.AddTag("test", "value");`.
I hope this helps troubleshooting.

**Comment by v-anvari** [comment]
Tagging @brettsam , for more inputs, we have few issues related to the package version. Could you please take a look at this issue

**Comment by Zenuka** [comment]
After talking to @johannesoenema it appears that when you downgrade `System.Diagnostics.DiagnosticSource` and run it locally, it `Activity.Current` is null but when deployed to Azure it successfully added properties to the request telemetry. So the workaround works in Azure

**Comment by v-anvari** [comment]
Thank you for the confirmation. We are tracking similar scenarios in other issues. Happy to know that you a workaround. Closing this issue here
