### ISSUE TITLE
Improve error message when multiple incompatible trigger bindings are specified

### ISSUE THREAD

**Issue by IanKemp** [Azure/azure-functions-host#7667]
#### What problem would the feature you're requesting solve? Please describe.
A co-worker accidentally defined a function to have multiple triggers:

```csharp
        public async Task<int> ProcessBlob(
          [QueueTrigger("QueueName", Connection = "ConnectionStringName")] string blobQueue,
          [ActivityTrigger] Orchestration_Context inputs,       
          ILogger log)
```

which results in host start failure, and this rather unhelpful error message:

```ps
A host error has occurred during startup operation '83b24a80-e9fa-477d-a85a-463ab000bb74'.
System.Linq: Sequence contains more than one matching element.
Value cannot be null. (Parameter 'provider')
```

Running `func.exe` manually with `CLI_DEBUG=1` set beforehand, I was able to view the full stack trace, which was actually helpful and led me to [ExternalConfigurationStartupValidator.cs](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/DependencyInjection/ExternalConfigurationStartupValidator.cs#L46). With that it became clear that the issue was with trigger bindings, which allowed me to figure out the above mistake that was made.

#### Describe the solution you'd like
Change the linked code from:

```csharp
                var trigger = function.Bindings.SingleOrDefault(b => b.IsTrigger);
```

to

```csharp
                var triggers = function.Bindings.Where(b => b.IsTrigger);
                if (triggers.Count() > 1)
                {
                    throw new InvalidOperationException($"Function \"{function.Name}\" has multiple triggers defined; this is not permitted");
                }

                var trigger = triggers.SingleOrDefault();
```

I don't believe that doing `Where()`/`Count()` here is particularly problematic from a performance standpoint, as this code is executed on host startup, which (should) happen relatively infrequently and only once during the host lifetime.

#### Describe alternatives you've considered
Painful debugging.

**Comment by v-anvari** [comment]
Thank you for your feedback! We will investigate this scenario and update you with the possibilities.

**Comment by mathewc** [comment]
@IanKemp thanks for taking the time to report this issue. PR https://github.com/Azure/azure-functions-host/pull/7685 addresses this.

**Comment by IanKemp** [comment]
Thanks for the super fast turnaround @mathewc !
