### ISSUE TITLE
Design work for supporting resume API for drain mode

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#7673]
When performing a scale-in operation on a function app, Antares infrastructure will put the function app in drain mode. This will effectively make it so that the function app would stop fetching new events. However this leads to another issue if we the function app needs to scale out again very quickly. At that point platform could chose a worker that is new, or a worker that is potentially still asleep causing the event queue to build up and leads to the function app assigned to workers that are forever asleep. This risk is particularly elevated for stamps that have limited capacity.

To address this issue we need an API that starts the worker that was previously put in drain mode, allowing it fetch new events.

**Comment by fabiocav** [comment]
Moving this to sprint 111. 

/cc @liliankasem

**Comment by liliankasem** [comment]
Closing this out as initial design doc is in and we created issues to track the next steps:

- https://github.com/Azure/azure-functions-host/issues/7781
- https://github.com/Azure/azure-functions-host/issues/7774
- https://github.com/Azure/azure-functions-host/issues/7785
