### ISSUE TITLE
 Fapp Errors 404

### ISSUE THREAD

**Issue by fnw18** [Azure/azure-functions-host#7680]
I'm facing problems with Functions that are active and with recurring requests, and suddenly they start getting 404 error.

The error happens for some time and then resumes normally, but our application is critical and the error makes the product unfeasible.

The last error encountered on Friday is attached.
<img width="1241" alt="Captura de Tela 2021-09-18 às 11 41 57" src="https://user-images.githubusercontent.com/90974289/133892781-db2ec5d0-46ed-4cd9-9345-7ad42bbaa9b8.png">

We use the Consume plan, but I understand that this would not be a problem as our application is never cold.

Is there any solution to have a more resilient structure?

**Comment by v-bbalaiagar** [comment]
Hi @fnw18, Thank you for your feedback! Could you please provide us the invocation id of the error, region and time stamp during the error to get the logs and check the cause.

**Comment by fnw18** [comment]
Region - East US
UTC 18:52 17/09/2021
Exemple of invocation id: \|37af682d-482bf314751754f0.37af682e_ |

**Comment by v-bbalaiagar** [comment]
Hi @fnw18, Apologies for the delayed response, I am unable to get the logs with the given invocation id. Could you share the app name using https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately to check the cause.
