### ISSUE TITLE
TableOutput Binding should support updates

### ISSUE THREAD

**Issue by LPalmerMSI** [Azure/azure-functions-host#7700]
The TableOutput binding can not, currently, update tables.  A change to the binding should be make for create or update. 

Add a parameter to the annotation (Java) for outputType=Create, Update, CreateOrUpdate.

If I have to use the Azure Java SDK for 50% of the uses cases why do I need this binding to begin with?  The binding is currently too limited.

**Comment by v-anvari** [comment]
Hi @LPalmerMSI , Can you explain this scenario further by providing a sample code or repro steps.
What is in the current design that you want us to make it better. 
What is the actual and expected output

**Comment by LPalmerMSI** [comment]
I think the description is self explanatory.  I'm not sure what you're looking for in "repro steps", this is not a bug, it's a limitation in the way the TableOutput azure function binding functions.  The binding will only do an "insert" operation on a table.  It should be expanded to include "update" and "upsert" as well.
