### ISSUE TITLE
Set IsPackable=false by default on project creation

### ISSUE THREAD

**Issue by IanKemp** [Azure/azure-functions-host#7701]
#### What problem would the feature you're requesting solve? Please describe.
See https://github.com/dotnet/templating/issues/376. The rationale here is similar to there - the output of an Azure Functions project should generally not be placed into a NuGet package.

#### Describe the solution you'd like
Add `<IsPackable>false</IsPackable>` to the .csproj file when creating an Azure Functions project in Visual Studio.

#### Describe alternatives you've considered
Adding it manually, which is painful.

**Comment by v-anvari** [comment]
Hi @IanKemp , Can you explain this scenario a bit further with a sample or repro steps. What is the need to add the property in you code. Expected and Actual result.
