### ISSUE TITLE
Short FunctionExecutionTimeMs but long duration (response time)

### ISSUE THREAD

**Issue by sudarsanvsr** [Azure/azure-functions-host#7726]
I have a Python Azure function on premium plan that is http triggered. There are multiple instances running (scale out and always on enabled) and each instance is running 2 workers and is processing at most 2 concurrent requests. 

Sometimes, I'm seeing this weird behavior that traces (in app insights) is showing an execution time that is super short for some invocations (say under 100ms) but the response time as seen in requests (again in app insights) for the same operation_id is almost 2 mins. This is severely degrading our P95 response times. 

Is there an explanation for why this would happen?

**Comment by sudarsanvsr** [comment]
Think I figured out the issue. There are a few long-running invocations that cause incoming requests to get queued. When the long-running ones finish, which have a long execution time and therefore response time, the queued ones get picked up and their response time is already bad by then. This brings me to a different question: Why is the function not scaling out in this instance? 

I also do not understand perhaps the implementation of how a request gets handled in presence of maxConcurrentRequests setting. In my scenario, there are 2 workers in every instance and we have a maxConcurrentRequests setting equal to 2. If two invocations on an instance become long-running, then are there other requests already queued up for this particular instance and thereby those requests also end up facing a long response time? Ideally, when there are two long-running requests on an instance no other request should get assigned to that instance, right? Or, am I in the wrong for expecting this?

**Comment by v-bbalaiagar** [comment]
Hi @sudarsanvsr, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @sudarsanvsr, I checked this internally. When there are two long-running requests on an instance no other request should get assigned to that instance. This is the expected behavior. Here is the document to explaining the behavior about maxConcurrentRequests - https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-output#hostjson-settings

**Comment by sudarsanvsr** [comment]
Thanks for the responses. I'll reopen this issue again if our service runs into the scenario (which, I'm sure we faced when I opened this issue). I'm currently unable to repro since our service is not in heavy use.
