### ISSUE TITLE
Use System.Xml to create msbuild xml file instead of Microsoft.Build

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-host#7737]
# [7737](https://github.com/Azure/azure-functions-host/issues/7737) Removing the Microsoft.Build dependency

Taking a dependency on the MSBuild library just to generate an XML file leads to ton of unused project dependencies that increase the size of our project. We can easily remove this library and use System.Xml to generate the exact same XML payload.

From the screenshot below, the only dependency we actually use is `System.Runtime.Loader` which we can import on our own.

![Extra dependencies](https://user-images.githubusercontent.com/2198905/135676608-b5a75caf-f234-405b-933a-c0fd283a7ee2.png)

The benefit of using the `Microsoft.Build` library is that we get some prebuilt functionality around creating msbuild.xml files i.e. we have a model to represent the schema for the XML file, and methods such as `AddPropertyGroup` which make it really easy to add new XML elements. However if all we're using this for is generating an XML file, we can easily create those elements ourselves, without having to take on all the additional dependencies that come with `Microsoft.Build` that we never use.

## Design

`Microsoft.Build` provides `ProjectRootElement` which enables us to create a new msbuild project file. It has functions such as `ProjectRootElement.Create`, `AddItemGroup()` and `AddPropertyGroup()` which are used to create something like the following XML output:

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <VersionFile>netstandard2.0</VersionFile>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis" Version="3.3.1" />
    <ItemGroup>
</Project>
```

Our implementation would need to replace those methods with our own to achieve the same purpose, but with less dependencies. All those methods do under the covers is create an XML file, so we should be able to just use the builtin `System.Xml` library to create the same XML payload.

### Identified functionality for parity

- Creating a `Project` root element with attributes
    - Create from file if it exists
    - Create from scratch
    - Should contain a searchable list of elements
- Creating a `PropertyGroup` with the following properties:
    - `TargetFramework`
    - `WarningsAsErrors` with the following properties:
- Creating an `ItemGroup`
    - `PackageReference`
- Creating an `Item`
- Create a `PackageReference`
- Remove a `PackageReference`
- Removing a child element

#### Option 1

We already have a class `ProjectExtensions` that extends the `ProjectRootElement`. We can reuse this class to extend `XmlDocument` and add all of the required functionality defined [here](#identified-functionality-for-parity)

#### Option 2

We create a new class to replace `ProjectRootElement` which extends `XmlDocument`. We essentially create our own type for the MSBuild Project and only implement the [core functionality we need](#identified-functionality-for-parity).

#### Microsoft.Build to System.Xml mappings

Either way, we will be surfacing System.Xml elements that MS Build wraps through `ProjectRootElement`, so we will need to define the mappings we replace, such as:

- [ProjectRootElement](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.construction.projectrootelement?view=msbuild-16-netcore) = XML document
- [ProjectItemElement](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.construction.projectitemelement?view=msbuild-16-netcore) = XML element `Item`
- [ProjectItemGroupElement](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.construction.projectitemgroupelement?view=msbuild-16-netcore) = XML element for `ItemGroup`

//TODO: class diagram

### Concerns

- We will essentially have to build our own wrapper for creating msbuild XML files. This could led to some maintenance down the road if the schema changes
    - On the plus side, we only need a select number of elements and properties, and how often will the schema be changing?

## Scope of Work

The scope of work is pretty small, it's mostly cleaning up unused references, but the biggest chunk of work would be writing our own `Project` XML file builder which comes from replacing use of `ProjectRootElement`.

- Remove the `Microsoft.Build` library
- Add the `System.Runtime.Loader` library
    - We're using this in our project but it's currently coming through `Microsoft.Build`
- `ExtensionsManager.cs`
    - Replace usage of `ProjectRootElement`
- `PackageManager.cs`
    - Replace usage of `ProjectRootElement`
- `ProjectExtensions.cs`
    - Update existing functions to work with `System.Xml`
    - Implement `Project` builder methods ([see design](#design))
- Clean up unused references to `Microsoft.Build`

**Comment by fabiocav** [comment]
PR is out. This work was lower in priority this sprint, so we couldn't get it reviewed.

Moving to 113.

**Comment by fabiocav** [comment]
This was a lower priority/stretch goal for 113, moving to 114.
