### ISSUE TITLE
Flood of HTTP related logging since upgrading to host v4

### ISSUE THREAD

**Issue by felinepc** [Azure/azure-functions-host#7740]
#### Is your question related to a specific version? If so, please specify:
Azure Function Core Tools v4 and Azure Functions .NET 6 

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
I just upgraded from Azure Functions .NET 5 to .NET 6 Preview (isolated). Whenever my function runs, both locally via Core Tools v4 and in Azure Function .NET 6 Preview, I see a flood of logs like this (multiple ones every second):

>  Request [8902e6ea-1961-4ad9-8f87-bb0f6f099010] PUT http://127.0.0.1:10000/devstoreaccount1/azure-webjobs-hosts/locks/...
> [2021-10-03T19:54:21.385Z] x-ms-lease-action:renew
> [2021-10-03T19:54:21.386Z] x-ms-lease-id:53510324-35c0-47e9-b6e1-fd2f8ef8fb24
> [2021-10-03T19:54:21.386Z] x-ms-version:2020-08-04
> [2021-10-03T19:54:21.387Z] Accept:application/xml
> [2021-10-03T19:54:21.388Z] x-ms-client-request-id:8902e6ea-1961-4ad9-8f87-bb0f6f099010
> [2021-10-03T19:54:21.388Z] x-ms-return-client-request-id:true
> [2021-10-03T19:54:21.389Z] User-Agent:azsdk-net-Storage.Blobs/12.9.0,(.NET 6.0.0-rc.1.21451.13; Microsoft Windows 10.0.19043)
> [2021-10-03T19:54:21.389Z] x-ms-date:Sun, 03 Oct 2021 19:54:21 GMT
> [2021-10-03T19:54:21.390Z] Authorization:REDACTED
> [2021-10-03T19:54:21.390Z] client assembly: Azure.Storage.Blobs
> [2021-10-03T19:54:21.394Z] Response [af72cd2f-b19c-4597-b217-d9a4d1aeea5c] 200 OK (00.0s)
> [2021-10-03T19:54:21.396Z] Transfer-Encoding:chunked
> [2021-10-03T19:54:21.396Z] ETag:"0x8D9869716532FD0"
> [2021-10-03T19:54:21.397Z] Server:Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
> [2021-10-03T19:54:21.397Z] x-ms-request-id:5cb1884c-8736-4c95-b310-872c0063e5aa
> [2021-10-03T19:54:21.398Z] x-ms-version:2020-08-04
> [2021-10-03T19:54:21.399Z] x-ms-lease-id:2470eee6-d47a-4ac4-b9db-4f1967aa1165
> [2021-10-03T19:54:21.399Z] Date:Sun, 03 Oct 2021 19:54:21 GMT
> [2021-10-03T19:54:21.400Z] Last-Modified:Sun, 03 Oct 2021 17:56:12 GMT
> [2021-10-03T19:54:21.401Z] Response [8902e6ea-1961-4ad9-8f87-bb0f6f099010] 200 OK (00.0s)
> [2021-10-03T19:54:21.407Z]
> [2021-10-03T19:54:21.407Z] Transfer-Encoding:chunked
> [2021-10-03T19:54:21.408Z] ETag:"0x8D9869716D04F10"
> [2021-10-03T19:54:21.409Z] Server:Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
> [2021-10-03T19:54:21.409Z] x-ms-request-id:72742bcb-343f-4112-a41f-b8c296ac8534
> [2021-10-03T19:54:21.410Z] x-ms-version:2020-08-04
> [2021-10-03T19:54:21.411Z] x-ms-lease-id:53510324-35c0-47e9-b6e1-fd2f8ef8fb24
> [2021-10-03T19:54:21.411Z] Date:Sun, 03 Oct 2021 19:54:21 GMT
> [2021-10-03T19:54:21.412Z] Last-Modified:Sun, 03 Oct 2021 17:56:13 GMT
> [2021-10-03T19:54:21.412Z]
> [2021-10-03T19:54:22.362Z] Request [976fd430-xxxx-xxxx-b0be-ebf5d4a10565] GET https://storeaccountxxx.queue.core.windows.net/xxx-queue/messages?sv=2020-02-10&ss=q&srt=sco&sp=rwdlacup&se=3021-03-23T08:47:27Z&st=2021-03-23T00:47:27Z&spr=https&sig=REDACTED&numofmessages=16&visibilitytimeout=600
> [2021-10-03T19:54:22.365Z] x-ms-version:2018-11-09
> [2021-10-03T19:54:22.366Z] Accept:application/xml
> [2021-10-03T19:54:22.366Z] x-ms-client-request-id:976fd430-54b4-4fc0-b0be-ebf5d4a10565
> [2021-10-03T19:54:22.367Z] x-ms-return-client-request-id:true
> [2021-10-03T19:54:22.367Z] User-Agent:azsdk-net-Storage.Queues/12.8.0,(.NET 6.0.0-rc.1.21451.13; Microsoft Windows 10.0.19043)
> [2021-10-03T19:54:22.368Z] client assembly: Azure.Storage.Queues
> [2021-10-03T19:54:22.409Z] Request [1d974eeb-6978-462e-9935-9cf5bcfc4db3] GET https://storaccountxxx.queue.core.windows.net/xxx-queue/messages?sv=2020-02-10&ss=q&srt=sco&sp=rwdlacup&se=3021-03-23T08:47:27Z&st=2021-03-23T00:47:27Z&spr=https&sig=REDACTED&numofmessages=16&visibilitytimeout=600
> [2021-10-03T19:54:22.414Z] x-ms-version:2018-11-09
> [2021-10-03T19:54:22.414Z] Response [976fd430-54b4-4fc0-b0be-ebf5d4a10565] 200 OK (00.0s)
> [2021-10-03T19:54:22.415Z] Accept:application/xml
> [2021-10-03T19:54:22.416Z] x-ms-client-request-id:1d974eeb-6978-462e-9935-9cf5bcfc4db3
> [2021-10-03T19:54:22.417Z] x-ms-return-client-request-id:true
> [2021-10-03T19:54:22.417Z] User-Agent:azsdk-net-Storage.Queues/12.8.0,(.NET 6.0.0-rc.1.21451.13; Microsoft Windows 10.0.19043)
> [2021-10-03T19:54:22.418Z] client assembly: Azure.Storage.Queues
> [2021-10-03T19:54:22.416Z] Cache-Control:no-cache
> [2021-10-03T19:54:22.419Z] Transfer-Encoding:chunked
> [2021-10-03T19:54:22.420Z] Server:Windows-Azure-Queue/1.0,Microsoft-HTTPAPI/2.0
> [2021-10-03T19:54:22.420Z] x-ms-request-id:9c7e3985-e003-0018-1590-b80dc8000000
> [2021-10-03T19:54:22.421Z] x-ms-version:2018-11-09
> [2021-10-03T19:54:22.421Z] Date:Sun, 03 Oct 2021 19:54:22 GMT

These logs appear to be related to function storage and queue/eventhub pooling/leases. But I can't figure out how to filter these out (what their sources are, tried System.Net.Http.HttpClient without luck). The only way to stop them for now is to set default `logLevel` to `Warning` but that will filter out other useful logs.

This did not happen with v3.

Any advice would be greatly appreciated.

**Comment by v-bbalaiagar** [comment]
Hi @felinepc, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @felinepc, Could you provide us the csproj file.
