### ISSUE TITLE
referencing values from host.json

### ISSUE THREAD

**Issue by pjgsk** [Azure/azure-functions-host#7745]
I want to be able to reference some values from outside the host.json file but none of the tries worked:

1. through env variable
`{
  "version": "2.0",
  "extensions": {
    "http": {
      "routePrefix": "",
      "customHeaders": {  
        "x-version": "%SOMEVERSION%"
    }  
    }
  }
}
`
where SOMEVERSION was Key for Value defined in local.settings.json

2. through json ref 

`{
  "version": "2.0",
  "extensions": {
    "http": {
      "routePrefix": "",
      "customHeaders": {  
        "x-version": {"$ref": "package.json#/version"}
    }  
    }
  }
}
`

What is the correct way of doing it?

**Comment by v-bbalaiagar** [comment]
Hi @pjgsk, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @pjgsk, By "outside the host.json" do you mean an arbitrary JSON file that isn't host.json. We would like to know what language are you writing your Azure function in.

**Comment by pjgsk** [comment]
Yes, I meant arbitrary JSON file, that is not host.json (in my example it is package.json). My az functions are written in ts/js, but does that matter at all?

**Comment by v-bbalaiagar** [comment]
Hi @pjgsk, Thank you for the update, I shall discuss this internally and update as appropriate.

**Comment by v-bbalaiagar** [comment]
Hi @pjgsk, I checked this internally. You can use by adding a double underscore for example version__ , extensions__ , http__
On windows you can also use colon but double underscore will be cross platform, so you would work both on Linux and windows.
