### ISSUE TITLE
What would cause AzureFunctionsJobHost__* defined via portal to be removed?

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-functions-host#7764]
#### Is your question related to a specific version? 

No. This is a portal related questions.

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 

C#

#### Question

I had two settings overrides for `AzureFunctionsJobHost__` provided via portal to control Service Bus trigger and avoid a scenario that was causing failures in production.
![image](https://user-images.githubusercontent.com/1309622/137028801-68d2153d-1b0e-4b09-a695-0ecb355fa7b7.png)

Those failures came back and after investigation, it was identified that those settings **were gone** from the portal.

My question is the following: what can wipe `AzureFunctionsJobHost__*` settings provided via the portal?
Would a redeployment of the Function App remove the overrides?

**Comment by SeanFeldman** [comment]
The redeployment is done using ARM templates. Which, is wiping the settings. Thank you, @anthonychu 

**Please**, update the documentation (https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#override-hostjson-values and https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurefunctionsjobhost__) to indicate ARM redeployment will wipe the settings.

**Comment by v-bbalaiagar** [comment]
Hi @SeanFeldman,  Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Opened a new document issue for further validation - https://github.com/MicrosoftDocs/azure-docs/issues/82385. Closing this issue here.
