### ISSUE TITLE
Merging PR for worker indexing (project stein)

### ISSUE THREAD

**Issue by surgupta-msft** [Azure/azure-functions-host#7773]
Document - [Here](https://microsoft.sharepoint.com/:w:/r/teams/Antares/_layouts/15/Doc.aspx?sourcedoc=%7BE0283F6F-8072-4173-9D50-76966BD6D8F2%7D&file=Project%20Stein%20(Worker%20Indexing)%20Reference%20Documentation.docx&wdLOR=c0AEA68A1-EC24-47E6-80AA-D5F67612F840&action=default&mobileredirect=true&cid=6ad859e5-0a29-4b02-b7f8-7cce84b166e6)

Epic - https://github.com/Azure/azure-functions-host/issues/7496 

PR - https://github.com/Azure/azure-functions-host/pull/7606

The PR merge needs below steps to be completed -
1. PR review
2. Completion of below items that should go with first release of feature.
          - https://github.com/Azure/azure-functions-host/issues/7806
          - https://github.com/Azure/azure-functions-host/issues/7797
          - https://github.com/Azure/azure-functions-language-worker-protobuf/pull/57

**Comment by fabiocav** [comment]
@surgupta-msft working on breaking this down into more granular issues.

**Comment by surgupta-msft** [comment]
Tracking this issues as part of https://github.com/Azure/azure-functions-host/issues/7496

**Comment by surgupta-msft** [comment]
The PR has been merged - https://github.com/Azure/azure-functions-host/pull/7606
