### ISSUE TITLE
[Resume API] Implement resume API endpoint in the functions host

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-host#7774]
Based on the design document for Drain Mode Resume, implement the resume API within the functions host.

Epic: #7772 
[Design document](https://dev.azure.com/msazure/One/_wiki/wikis/Antares%20Engineering%20Hub/189846/ResumeModeAPI)

**Comment by fabiocav** [comment]
PR is out, but this work is still in progress/review. Moving to sprint 114
