### ISSUE TITLE
Azure Function response time consistently increasing over time

### ISSUE THREAD

**Issue by aangelisc** [Azure/azure-functions-host#7778]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app, select `Diagnose and solve problems` from the left, and view relevant dashboards before opening your issue.

#### Investigative information

Please provide the following:

- Timestamp: Ongoing from 2:00PM BST
- Function App version: 3
- Function App name: OnNewBlob-dev
- Function name(s) (as appropriate): OnNewBlob
- Invocation ID: NA
- Region: UK South

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a Linux Node.js function triggered by a blob creation (using EventGrid)
2. Integrate function with VNet integration and create a private endpoint for the storage account so that it is reachable from the function.
3. Consistently push blobs to the storage account - triggering the function

#### Expected behavior

Provide a description of the expected behavior.

The function response time (average and maximum) should be fairly stable over time.

#### Actual behavior

Provide a description of the actual behavior observed.

The response time increases continuously the longer the instance is running. This will then cause timeouts on EventGrid as it is unable to determine if the event was successfully delivered.

#### Known workarounds

Provide a description of any known workarounds.

Restarting the function essentially creates a new instance and the response time is reset (although the same issue will reoccur).

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

Language: TypeScript
Binding: HTTP Trigger (from EventGrid)

**Comment by v-anvari** [comment]
Thank you for reaching out to us,  We will investigate this further and update you with the findings.

**Comment by v-anvari** [comment]
Can you also, provide the source code that you are using and explain the VNet setup
