### ISSUE TITLE
Azure Functions runtime is unreachable - When a Queue Trigger function is added.

### ISSUE THREAD

**Issue by MahaSPR** [Azure/azure-functions-host#7779]
Hello, 

I have an Azure Function App with Python 3 code implementation, that has HTTP Trigger functions and Timer Trigger Functions, which are running fine on an EP2 App Service Plan. But, as soon as I add and deploy a Queue Trigger function, I get the error "Azure Functions runtime is unreachable." in the Azure Portal when I try to view the Functions. 

#### Investigative information

Please provide the following:

- Timestamp: 10/15/21 @10:40am CST
- Function App version: 3
- Function App name: 
- Function name(s) (as appropriate):
- Invocation ID: (where do I find it??
- Region: North Central US

Provide the steps required to reproduce the problem:

Step 1: Crate an Azure Function App in VS Code with a HTTP Trigger function and a Timer Trigger function and deploy them to Azure Function App.
Step 2: Navigate to the Azure Function App in Azure Portal
Step 3: Click on the "Functions" menu on the left navigation panel and check the functions listed on the right side. 
Step 4: Check for any status /error message displayed above the functions list. There should not be any error at this time
Step 5: Click on one of the functions, and then click on "Code + Test" menu to see the function code. 
Step 6: You should be able to see the function code in the code editor, and you should be able to invoke it on-demand, and see the results.

Now, go back to VS Code editor and add an HTTP Trigger Function to add messages to a Azure Queue Storage, and another Queue Trigger function to consume those messages from the queue. Configure the storage queue and the storage connection for use by these to functions. Then, deploy the changes to Azure Function App. Once the deployment is completed, repeat steps 2 to 6 listed above. This time, you will see "Azure Functions runtime is unreachable" error message at step 4, and you won't see the newly added 2 functions showing up there, and you cannot invoke any existing functions, as you cannot see the code, and the "Test/Run" option is disabled.

**Comment by v-bbalaiagar** [comment]
Hi @MahaSPR, Thank you for the feedback! We will reproduce this issue and update as appropriate.

**Comment by v-bbalaiagar** [comment]
Hi @MahaSPR, Here is a blog post which addresses similar scenario where the blog talks about Azure Functions runtime is unreachable and solutions to resolve it - https://azureappservices.blogspot.com/2019/07/azure-functions-runtime-is-unreachable.html
Also, Here is how you can troubleshoot the issue - https://docs.microsoft.com/en-us/azure/azure-functions/functions-recover-storage-account

Please check and let us know if you are able to resolve the issue with this information.
