### ISSUE TITLE
When does Azure functions runtime version change?

### ISSUE THREAD

**Issue by pastushenkoy** [Azure/azure-functions-host#7783]
Hello everyone.

I had interesting problem couple of weeks ago:
We have an azure function which executes in process and reacts to queue trigger.

About a year ago we deployed it to cloud and it worked successfully until we needed to change a littel piece of code. This piece of code didn't touch any architecture or nuget packages, it just intoduced some internal logic.
After we deployed a new version we started to get error 'Could not load file or assembly Microsoft.Extensions.DependencyInjection.Abstrations'.
We tried to rollback our changes, but error kept throwing.

I assume that this happens because of after we deployed a new version of our app, we got new runtime version.

What I'm really interested is why runtime changed only after deployment? Is it expected behaviour that during regular work, WebHost version never changes? Is it pinned at the moment of deploy and kept until next deployment?

**Comment by balag0** [comment]
When an app starts, it will use the latest host version at that point in time. After that, if there is a new host version available on the platform, the running instances will not be automatically recycled to pick up the new host version. But if the app/ running instances get recycled for some reason (app restart, app deployment, service healing), they will start using the new host version.

If the host version is [pinned](https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal) to a specific host version, then the same host version will be used across app recycle/restart even if newer host versions are available.

**Comment by pastushenkoy** [comment]
@balag0  Thank you for your answer. Can you also tell me will the host version be updated if application scales to zero, i.e. has no running instances at the moment?

**Comment by balag0** [comment]
When there are no running instances, the app will not be using any particular host version at that time. The version selection will eventually happen at the time of starting a new instance (based on the config on the app and the available host versions on the worker).

**Comment by v-bbalaiagar** [comment]
Hi @pastushenkoy,  Let us know if the information resolves your query, or if you have any further queries.

**Comment by pastushenkoy** [comment]
@v-bbalaiagar Yes, totally resolves. Thank you very much for your help.
