### ISSUE TITLE
Introduce list of language workers to start in placeholder mode

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-host#7791]
Add new environment variable  that lists langauge workers instead of hardcoding the list here: https://github.com/Azure/azure-functions-host/blob/443869e7a41c820288d0d5cb87b31e7569ed118d/src/WebJobs.Script/Workers/Rpc/RpcInitializationService.cs#L26-L40

This is useful to set explicit list of languages in mesh images used for Linux Consumption  where we do bring up python and node language workers.

**Comment by fabiocav** [comment]
@pragnagopa I see you've assigned yourself. Are you planning on driving this, or do you want us to assign it to someone?

**Comment by pragnagopa** [comment]
Planning on working on this issue myself! Will send a PR soon.
