### ISSUE TITLE
Support UPPER_CASE keys for all settings

### ISSUE THREAD

**Issue by NickH-KiwiAirways** [Azure/azure-functions-host#7798]
In the AppSettings, all settings use upper case names other than `AzureWebJobsStorage`.

This causes an issue when using Doppler or other secret/env managers, as they only support upper case keys for cross-environment support.

My request is that AzureWebJobsStorage is updated to use upper case for the setting lookup, or to make the comparisons case-insensitive.

https://github.com/Azure/functions-action/blob/master/src/handlers/resourceValidator.ts#L200

**Comment by v-bbalaiagar** [comment]
Hi @NickH-KiwiAirways , Please let us know if the above information resolves your query, or if you have any further queries.

**Comment by v-bbalaiagar** [comment]
Closing this issue as there is no further activity, please feel free to reach back to us in case of any further queries related to this issue.
