### ISSUE TITLE
Cross entity transaction support is broken in Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.0.0

### ISSUE THREAD

**Issue by andreasohlund** [Azure/azure-functions-host#7810]
#### What problem would the feature you're requesting solve? Please describe.

In v4.* you could gain access to the ServiceBus connection object via the injected `MessageReceiver`. This in turn allows cross entity transactions to be used.

- [Example of injection](https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/blob/release-1.3/src/NServiceBus.AzureFunctions.SourceGenerator/TriggerFunctionGenerator2.cs#L130)
- [Example of usage](https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/blob/release-1.3/src/NServiceBus.AzureFunctions.InProcess.ServiceBus/Transactions/MessageReceiverTransactionStrategy.cs#L30)

We, [Particular Software](https://particular.net/), uses this to [enable our users to utilize cross entity transaction](https://docs.particular.net/nservicebus/hosting/azure-functions-service-bus/#message-consistency).

In version 5.0.0, which uses the new Azure.Messaging.ServiceBus SDK, we need access to the `ServiceBusClient` [which is responsible for creating pooled message senders that can participate in cross entity transactions](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-transactions#see-it-in-code).

The problem is that, as far as I can tell, no way to get access to the `ServiceBusClient` via the function trigger, this prevents us from creating message senders that can participate in cross entity transactions like shown in the above example and is blocking our customers from upgrading to Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.0.0  version until this is resolved.

#### Describe the solution you'd like

A supported way to access the `ServiceBusClient` that would allow us to use cross entity transactions.

#### Describe alternatives you've considered

None so far

#### Additional context

N/A

cc @seanfeldman

**Comment by fabiocav** [comment]
This has been addressed in https://github.com/Azure/azure-sdk-for-net/pull/24990. Closing this as the issue will be addressed with an extension release (tracked in the linked repo), as opposed to a host deployment.

Thanks!
