### ISSUE TITLE
Azure functions runtime failing with error ANCM failed to find native dependencies

### ISSUE THREAD

**Issue by Badabum** [Azure/azure-functions-host#7812]
So just recently is started to notice a lot of 500s from various function app running in our subscription. The error is not the screenshot below. All function apps have pinned runtime version 3.0.15885.
All apps target netcoreapp3.1.
Also noticed the same issue for on the apps using dotnet-isolated runtime with .net5 function app.

![image](https://user-images.githubusercontent.com/6359085/139273774-fd0fc952-58b2-4280-b078-c0845215e43c.png)

**Comment by v-bbalaiagar** [comment]
Hi @Badabum, Thank you for your feedback!  Here is how you can troubleshoot the issue - https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1#50031-ancm-failed-to-find-native-dependencies

Please check and let us know if you are able to resolve the issue with this information.

**Comment by Badabum** [comment]
@v-bbalaiagar I'm not using App Service, I'm talking about function apps. This situation happened for the apps running OK in production for more than a year and then they stopped. So I assume that the issue was in some runtime updates in azure itself

**Comment by v-bbalaiagar** [comment]
Thank you for the update. We will investigate this further and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @Badabum, If this is a production impacting issue, a good option for you to open a support ticket so that they can look at a little more closely.

**Comment by jhoops88** [comment]
We have also been impacted by this in a production environment, and that environment and its code has not been changed by us in months.

This was first noticed by our weekly monitoring on Sunday, 31st October 2021.

Can you provide any further updates to help resolve?

**Comment by v-bbalaiagar** [comment]
Hi @jhoops88, Can you open a support ticket as it is impacting in a production environment.

**Comment by jhoops88** [comment]
We resolved this in our instance by updating all our Azure related NuGet packages:

Azure.Storage.Blobs
Microsoft.Azure.Functions.Extensions
Microsoft.Azure.WebJobs.Extensions.DurableTask
Microsoft.Azure.WebJobs.Extensions.SendGrid
Microsoft.Azure.WebJobs.Extensions.Storage

**Comment by v-bbalaiagar** [comment]
Thank you for the update @jhoops88
