### ISSUE TITLE
Add Azure Database for MySQL | MariaDB | Postgres Root CA Cert to host package.

### ISSUE THREAD

**Issue by sjwaight** [Azure/azure-functions-host#7819]
When attempting to use Azure Functions to call SSL-enabled instances of these three Azure DBaaS offerings I currently have to bundle and deploy the BaltimoreCyberTrustRoot.crt.pem file as part of my Azure Function codebase. While this requirement is well documented for each service for generic client use (for example: https://docs.microsoft.com/en-us/azure/mysql/howto-configure-ssl#step-1-obtain-ssl-certificate) there is no mention of it anywhere specifically for Azure Functions.

#### Describe the solution you'd like
Bundle the BaltimoreCyberTrustRoot.crt.pem file as part of the Azure Functions runtime host so I don't need to deploy as part of my solution.

#### Describe alternatives you've considered
Alternatively, provide some extension capability for Azure OSS Databases that allows me to install the cert as part of installation of the extension. This would avoid needing to download the cert and check it into source control and deploy as part of my code. Document the process and provide demo code to show how to reference the cert in Functions code.

**Comment by v-bbalaiagar** [comment]
Hi @sjwaight, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Opened a new document issue for further validation - https://github.com/MicrosoftDocs/azure-docs/issues/83920. Closing this issue here.
