### ISSUE TITLE
'WEBSITE_TIME_ZONE' is not applied to the application log

### ISSUE THREAD

**Issue by yuna-s** [Azure/azure-functions-host#7820]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
ALL
#### Question
Doesn't the 'WEBSITE_TIME_ZONE' Application setting change the time zone of application logs?

I've added Application setting 'WEBSITE_TIME_ZONE' to Configuration.
But, in the logs, the date and time are still in UTC.
![image](https://user-images.githubusercontent.com/38641545/139818159-f96020df-9745-49be-8ae8-b5fc91f658d0.png)

Is the reason for above issue because Functions Host is directly specifying UTC in the FileLogger class?
Line 118
https://github.com/Azure/azure-functions-host/blob/852eed9ceef6ef56b431428a8eb31f1bd9c97f3b/src/WebJobs.Script/Diagnostics/FileLogger.cs
> string timestamp = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ss.fff", CultureInfo.InvariantCulture);

![image](https://user-images.githubusercontent.com/38641545/139820376-e864387c-6edb-4569-bb59-4df6619f33f7.png)

If it is possible, I would like to know how to change the time zone of the log.
Thanks.

**Comment by v-anvari** [comment]
Hi @yuna-s , Can we know if this is for Linux, if yes, this is a supported feature only on Linux App service plan. This is tracked here - https://github.com/Azure/azure-functions-host/issues/5246

There is a blog on this [ here](https://blog.maximerouiller.com/post/getting-rid-of-time-zone-issues-within-azure-functions/), and surely the logs are going to be in the specified time zone and not UTC. 

Also, the supported values for windows - https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-vista/cc749073(v=ws.10)?redirectedfrom=MSDN

**Comment by v-anvari** [comment]
These could be related to any of the below as well:
https://github.com/Azure/azure-functions-python-worker/issues/897
https://github.com/Azure/azure-functions-host/issues/7119
