### ISSUE TITLE
Unable to set inout binding to blob storage output binding 

### ISSUE THREAD

**Issue by slimmingworlduk** [Azure/azure-functions-host#7823]
MS documentation suggests that the output binding can be any of the following: 

You can bind to the following types to write blobs:

- TextWriter
- out string
- out Byte[]
- CloudBlobStream
- Stream
- CloudBlobContainer ^1
- CloudBlobDirectory
- ICloudBlob ^2
- CloudBlockBlob ^2
- CloudPageBlob ^2
- CloudAppendBlob ^2

^1 Requires "in" binding direction in function.json or FileAccess.Read in a C# class library. However, you can use the container object that the runtime provides to do write operations, such as uploading blobs to the container.

^2 Requires "inout" binding direction in function.json or FileAccess.ReadWrite in a C# class library.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-output?tabs=csharp

For those marked as (^2) it is required to set the `inout` binding instead of `out`. 

This however seems to be unsupported: 

```log
2021-11-02T21:40:04.545 [Error] Microsoft.Azure.WebJobs.Host: Error indexing method
'Functions.BlobTrigger'. Microsoft.Azure.WebJobs.Host: **ReadWrite access is not supported.
Pick either Read or Write.** 
```

Unable to append to file if can't read and write. Can only overwrite existing.

**Comment by Ved2806** [comment]
Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by Ved2806** [comment]
Hi @slimmingworlduk, Could you please share code sample so that we can investigate?
