### ISSUE TITLE
Azure Function 'HttpRequestMessage' does not contain a definition for 'CreateResponse' or GetQueryNameValuePairs

### ISSUE THREAD

**Issue by dmoorjmalani** [Azure/azure-functions-host#7826]
#### Investigative information

Please provide the following:

- Timestamp:
- Function App version: 1
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

#### Repro steps

Provide the steps required to reproduce the problem:
1. Create an Azure Function App
2. Add a function, I am using Portal to code
2. The Version is set to ~1
3. I am trying to access certificate stored in Azure Vault for that I added following assemblies using project.json  
`{
  "frameworks": {
    "net46": {
      "dependencies": {
        "Microsoft.Azure.KeyVault": "3.0.3",
        "Microsoft.Azure.Services.AppAuthentication": "1.6.2",
        "Microsoft.IdentityModel.JsonWebTokens": "6.14.0",
        "Microsoft.NET.Sdk.Functions": "1.0.24",
        "Microsoft.Net.Http": "2.2.29",
        "Microsoft.Rest.ClientRuntime.Azure": "3.0.0.0"
      }
    }
  }
}`
4. As soon as the packages get downloaded and the compilation fails giving following message
`HttpRequestMessage' does not contain a definition for 'GetQueryNameValuePairs' and the best extension method overload 'HttpRequestMessageExtensions.GetQueryNameValuePairs(HttpRequestMessage)' requires a receiver of type 'HttpRequestMessage'`
`'HttpRequestMessage' does not contain a definition for 'CreateResponse' and the best extension method overload 'HttpRequestMessageExtensions.CreateResponse<string>(HttpRequestMessage, HttpStatusCode, string)' requires a receiver of type 'HttpRequestMessage'`
5. I have following references added on the top
`using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Azure.KeyVault;
using Microsoft.Azure.Services.AppAuthentication;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.IdentityModel.JsonWebTokens;
using Newtonsoft.Json;`
6. This seems to be same issue as reported in the [link ](https://github.com/Azure/azure-functions-host/issues/6040). Some solutions indicate to modify .csproj file to make sure AzureFunction is ~1, but as i am working out of Portal i don't have this file, but as i have stated, the version is set to ~1. Similar [issue](https://stackoverflow.com/questions/54377126/azure-functions-httprequestmessage-does-not-contain-a-definition-for-createre)

**Comment by Ved2806** [comment]
Hi @dmoorjmalani 
1. Does the workaround mentioned [issue](https://stackoverflow.com/questions/54377126/azure-functions-httprequestmessage-does-not-contain-a-definition-for-createre) here works?
2. Is there any specific reason to use version ~1? if not, you can change it in the portal "configuration". 
3.  How you are trying to configure key vault?

**Comment by dmoorjmalani** [comment]
Hi @Ved2806
Thank you for taking time out to help me.
1. No, the workaround to delete system.net.http from packages\nuget does not work. it gives package not found error, that means i have to explicitly install system.net package
2. It is an old function to which i am adding capabilities
3. I followed this [blog ](https://integration.team/blog/retrieve-azure-key-vault-secrets-using-azure-functions-and-managed-service-identity/)to configure key vault

Let me know if you need more information

Thanks,
Deepa M

**Comment by Ved2806** [comment]
@dmoorjmalani 
You may want to use this package [Microsoft.AspNetCore.Mvc.WebApiCompatShim v2.2.0](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessageextensions.createerrorresponse?view=aspnetcore-2.2)
