### ISSUE TITLE
Expose IsFunctionAppEditable in the /admin/host/status API

### ISSUE THREAD

**Issue by pgombar** [Azure/azure-functions-host#7841]
#### Investigative information

Instead of relying on various app settings to determine if a function app can be edited in the Portal or not, instead leverage the existing flag `IsFileSystemReadOnly` from `ScriptApplicationHostOptions`. Do this by exposing it as another property in the /admin/host/status API.

**Comment by fabiocav** [comment]
What is the use case here? I'm assuming there's an existing component looking at environment variables and will be switching to use the status API instead, correct?

**Comment by pgombar** [comment]
@fabiocav that's right, the Portal will be consuming this API to determine if portal editing should be enabled or disabled. Today, Portal relies on app settings, and that has shown to be an inconclusive check for this use case.
