### ISSUE TITLE
Create more load test function apps for dotnet v4

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-host#7847]
For load testing v4 with dotnet, we have 3 projects. For each one of these project, we only have 1 test function app deployed and so we're only testing one configuration of platform and SKUs.

1. In-proc dotnet function (docker deployment)
    - Linux, Elastic Premium, West US
2. In-proc dotnet function (zip deployment)
    - Windows, P1v2, West US
3. Isolated worker dotnet function (zip deployment)
    - Windows, P1v2, West US

We need to create more Function Apps in our test environment to load test these apps under different SKUs, platforms and regions. 

#### Example:

- Windows, Consumption (East US, Europe, Asia)
- Windows, Elastic Premium (East US, Europe, Asia)
- Linux, Consumption (East US, Europe, Asia)
- Linux, Elastic Premium (East US, Europe, Asia)
- Linux, P1v2 (East US, Europe, Asia)

#### Work to be done

- Create terraform scripts to deploy new Function Apps for different SKUs for each of the above function projects
- Create loaderio tests to run against each of the new Function Apps created
- Setup the notification webhook as specified in the other loaderio tests to ensure load test results are populated in the HttpTestResults table

Related issues:

- https://github.com/Azure/azure-functions-host/issues/7934
- https://github.com/Azure/azure-functions-host/issues/7932
- https://github.com/Azure/azure-functions-host/issues/8091
- https://github.com/Azure/azure-functions-host/issues/7933
- https://github.com/Azure/azure-functions-host/issues/8092

[Example set of PRs that need to be created](https://azfunc.visualstudio.com/Azure%20Functions/_git/FunctionAppsForLoaderTests/pullrequests?_a=active&createdBy=6dc68abb-fe41-4a84-8d25-d206653bd835) (dotnet isolated)

**Comment by fabiocav** [comment]
Making this an Epic.

@liliankasem will break this down into issues for each of the scenarios we want to validate and have them linked here.

**Comment by liliankasem** [comment]
Related issues:

- https://github.com/Azure/azure-functions-host/issues/7934
- https://github.com/Azure/azure-functions-host/issues/7932
- https://github.com/Azure/azure-functions-host/issues/8091
