### ISSUE TITLE
Logging improvements for worker and host communication and exceptions

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-host#7848]
We have seen many CRIs where out-of-proc language workers fail to start or call back to the host within the defined timeout period. We need to identify the root-cause and fix all the potential reasons, however currently this is very difficult as we are dealing with a long tail of various issues from different components and levels. The log “Did not find any initialized language workers” is generic and we need to look at all the scenarios that would get us to this exception and provide more details in the logs so we can better investigate. We need better logging to really help us understand why this is happening before we continue the investigation on those CRIs.

To do this, we need to improve our logging in the host so that we can:

a) provide more detail for easier traceability and debugging to help surface the underlying issue
b) setup enough information so that we can investigate the original issue, should it appear again

As you can see, there are 35million error messages in the last 10 days where we “didn’t find a language worker” but only ~220k instance where the worker actually failed.
 
Count | Error
-- | --
35,580,553 | Did not find any initialized language workers
220,918 | Failed to initialize webhost language worker channel for runtime
280,845 | Starting worker process failed

<p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><o:p> </o:p></span></p>
 
#### Work to be done

- Develop a set of failure scenarios in isolation to ensure the host reacts to them as expected
- Investigate various scenarios that could lead to the following error messages and create issues to a) add new logs where necessary to help identify the cause of the issue, and b) include more details in existing logs where possible about what caused the issue
    - "Did not find any initialized language workers"
    - "Failed to initialize webhost language worker channel for runtime"
    - "Starting worker process failed"
- Investigate and document other reliability improvements for the host such as retires and worker health detection

**Comment by pragnagopa** [comment]
Adding few notes here.

> "Did not find any initialized language workers"

This error means - invocation request came through but there is no initialized language worker that can handle the request. It is concerning that these errors have massive count - 35,580,553 - I recommend prioritizing this issue to investigate.

**Comment by liliankasem** [comment]
Epic to address this created, follow the epic for updates on this topic.

- https://github.com/Azure/azure-functions-host/issues/8076
