### ISSUE TITLE
Worker Indexing - Protobuf changes to update RpcFunctionMetadata with more properties

### ISSUE THREAD

**Issue by surgupta-msft** [Azure/azure-functions-host#7849]
Host needs RetryOptions and configuration source information to populate FunctionMetadata, so two more properties need to be added to RpcFunctionMetadata to convey this information.

Steps to complete -
1. PR in protobuf repo - https://github.com/Azure/azure-functions-language-worker-protobuf/pull/57
2. To prepare PR for host repo based on changes required due to Protobuf repo.

**Comment by fabiocav** [comment]
@surgupta-msft will gather more information to better understand the requirements here (and identify whether this is needed)

/cc @pragnagopa

**Comment by surgupta-msft** [comment]
Discussed with @pragnagopa. RetryContext (same as RetryOptions) has been addressed in below PRs already - 

https://github.com/Azure/azure-functions-language-worker-protobuf/commit/466445a6a9f887e20cc525fc24e23843e9bd5c47
https://github.com/Azure/azure-functions-host/pull/7134/files 

This work does not seem to be related to workerIndexing. Closing this issue.
