### ISSUE TITLE
Creating Functions with 'forbidden' names results in errors

### ISSUE THREAD

**Issue by Jandev** [Azure/azure-functions-host#7851]
There appears to be an issue with the Functions runtime when using forbidden(?) words as a Function name. I've seen this happen when I named my function `NewGuid`.

While the samples here are on my local development machine, the same issue also occurs on a Function App within Azure (used a Linux Consumption based service plan (`Y1`))

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a new Function App, 3.1 in-proc
2. Name the function HTTP triggered function `NewGuid` (Anonymous access), no need for a body, but you can do some logging if you want
3. Press F5 (in Visual Studio)
4. Invoke the `NewGuid` Function
5. Result should be as the following screenshot:

![Receiving 404 in JSON](https://user-images.githubusercontent.com/462356/141129477-135df8e3-b3e3-4dc4-8a9a-18e7b5278431.png)
```json
{ "statusCode": 404, "message": "Resource not found" }
```

Another repro, but now change the name to lower case (`newguid`), this will result in the following exception when starting the project:
![System.InvalidOperationException](https://user-images.githubusercontent.com/462356/141129627-51d48b78-1982-47ee-9eac-875681e3a616.png)
```
System.InvalidOperationException
  HResult=0x80131509
  Message=The host has not yet started.
  Source=Microsoft.Azure.WebJobs.Host
  StackTrace:
   at Microsoft.Azure.WebJobs.JobHost.StopAsync() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 121
   at Microsoft.Azure.WebJobs.Hosting.JobHostService.StopAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\JobHostService.cs:line 32
   at Microsoft.Extensions.Hosting.Internal.Host.<StopAsync>d__10.MoveNext()
```

To proof my environment & code actually works, I renamed it to `TheFunction`
![Working solution](https://user-images.githubusercontent.com/462356/141129839-504f93d0-1559-4dfa-913d-36af24b14bce.png)

#### Expected behavior

I expected my Functions to 'just work', whatever the name would be.

#### Known workarounds

Rename the Function

#### Related information 

Provide any related information 

* Programming language used: C#
* Core Tools Version:       3.0.3904 Commit hash: c345f7140a8f968c5dbc621f8a8374d8e3234206  (64-bit)
* Function Runtime Version: 3.3.1.0

```csharp
// Lowercase sample
using Microsoft.AspNetCore.Http;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using System;
using Microsoft.Extensions.Logging;

namespace Api
{
    public static class NewGuid
    {
        [FunctionName("newguid")]
        public static string Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "GET", Route = null)] 
            HttpRequest req,
            ILogger log)
        {
            var guid = Guid.NewGuid().ToString("D");
            log.LogInformation("Created guid `{0}`", guid);
            return guid;
        }
    }
}

// Pascal case sample
using Microsoft.AspNetCore.Http;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using System;
using Microsoft.Extensions.Logging;

namespace Api
{
    public static class NewGuid
    {
        [FunctionName("NewGuid")]
        public static string Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "GET", Route = null)] 
            HttpRequest req,
            ILogger log)
        {
            var guid = Guid.NewGuid().ToString("D");
            log.LogInformation("Created guid `{0}`", guid);
            return guid;
        }
    }
}

// Working, renamed, sample
using Microsoft.AspNetCore.Http;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using System;
using Microsoft.Extensions.Logging;

namespace Api
{
    public static class NewGuid
    {
        [FunctionName("TheFunction")]
        public static string Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "GET", Route = null)] 
            HttpRequest req,
            ILogger log)
        {
            var guid = Guid.NewGuid().ToString("D");
            log.LogInformation("Created guid `{0}`", guid);
            return guid;
        }
    }
}


```

**Comment by v-anvari** [comment]
Hi @Jandev , NewGuid is a reserved keyword in c# and is used by .Net as seen here- https://docs.microsoft.com/en-us/dotnet/api/system.guid.newguid?view=net-5.0. As it is reserved keyword, you cannot use it as an identifier. This is as per design. Do let us know if you have any further queries.
Also, it is suggested to follow naming convention as mentioned here - https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming

**Comment by Jandev** [comment]
No real questions on the matter, I just found it interesting Functions with these names result in some weird error.
In line with this, I guess all (static?) methods on types aren't supported by design?
