### ISSUE TITLE
Max connections on a Consumption plan

### ISSUE THREAD

**Issue by Magnus12** [Azure/azure-functions-host#7854]
Reading [Manage connections in Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections?tabs=csharp) I understand that the max active connection limit is 600 per instance on a Consumption plan.

> This limit is per instance. When the scale controller adds function app instances to handle more requests, each instance has an independent connection limit

I would assume that means that when servers are added each server has a limit of 600 connections (?). However it seems that this limit is applied over all instances. If we open 30 connections on each server (instance) and we have 30 servers running we are getting `Host thresholds exceeded: Connections`.

So what does "Instance" mean in  [Manage connections in Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/manage-connections?tabs=csharp)? And if I have 600 connections per instance why am i getting exception with only 30 connections with 30 servers?

**Comment by balag0** [comment]
this page explains the thresholds in more detail - https://github.com/Azure/azure-functions-host/wiki/Host-Health-Monitor

**Comment by v-bbalaiagar** [comment]
Hi @Magnus12, Let us know if the above information resolves your query, or if you have any further queries.

**Comment by Magnus12** [comment]
@v-bbalaiagar Essentially I only want to know if it is 600 in total across all instances (servers that the plan scales out to) or 600 per instance.
