### ISSUE TITLE
Secretless configuration with Managed Identity - Microsoft.Azure.WebJobs.Script.WebHost: Secret initialization from Blob storage failed due to missing both an Azure Storage connection string and a SAS connection uri. For Blob Storage, please provide at least one of these.

### ISSUE THREAD

**Issue by jbpaux** [Azure/azure-functions-host#7859]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app, select `Diagnose and solve problems` from the left, and view relevant dashboards before opening your issue.

#### Investigative information

Please provide the following:

- Timestamp: 2021-11-15
- Function App version: 4
- Function App name: nmnbepptiql5s-func
- Function name(s) (as appropriate): NA
- Invocation ID: NA
- Region: northeurope

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a Storage Account
2. Create a Linux Consumption Function v4 with `SystemManaged` Identity
3. Assign RBAC Blob Data Owner on the SA to the MI
4. Remove AppSettings : `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING`/`WEBSITE_CONTENTSHARE`
5. Set AppSettings `WEBSITE_RUN_FROM_PACKAGE` to a blob URL in the SA where the Functions will be uploaded as a zip
6. Set AppSettings `AzureWebJobsStorage__accountName` to the name of the SA
7. Build the Function (C# .Net6)
8. Upload it to the previous URL
9. The function appears in the function list
10. Go to the portal and see the previous message: `Microsoft.Azure.WebJobs.Script.WebHost: Secret initialization from Blob storage failed due to missing both an Azure Storage connection string and a SAS connection uri. For Blob Storage, please provide at least one of these. If you intend to use files for secrets, add an App Setting key 'AzureWebJobsSecretStorageType' with value 'Files'.`

#### Expected behavior

It should just work and leverage the AzureWebJobsStorage to store keys

#### Actual behavior

Error message on the portal and function is not working as expected:

 `Microsoft.Azure.WebJobs.Script.WebHost: Secret initialization from Blob storage failed due to missing both an Azure Storage connection string and a SAS connection uri. For Blob Storage, please provide at least one of these. If you intend to use files for secrets, add an App Setting key 'AzureWebJobsSecretStorageType' with value 'Files'.`

#### Known workarounds

Failback to a connection string for AzureWebjobsStorage

#### Related information 

Provide any related information 

* Programming language used  : C# .Net6
* Links to source : None at the moment, can provide if needed (+bicep)
* Bindings used: Storage

**Comment by jbpaux** [comment]
cc @paulbatum @pragnagopa @mattchenderson if you have ideas as I saw good infos in #6423 and #7571

**Comment by Ved2806** [comment]
@jbpaux Could you please share the function app name and the format used for the AzureWebJobsStorage__accountName?

**Comment by jbpaux** [comment]
Hi, function app name is : nmnbepptiql5s-func
AzureWebJobsStorage__acountName is set to nmnbepptiql5ssa

**Comment by jbpaux** [comment]
why is it staled ? I answered... @fabiocav you can remove the label..

**Comment by jbpaux** [comment]
@fabiocav ?

**Comment by Ved2806** [comment]
Hi @fabiocav, Could you please take a look?

**Comment by pragnagopa** [comment]
Assigning to @balag0 for initial investigation. This could be related to how the app is deployed - Related issue https://github.com/Azure/azure-functions-core-tools/issues/2684

**Comment by balag0** [comment]
@jbpaux  I see the appsetting name on the app is set to AzureWebJobsStorage__acountName
Can you try setting it to AzureWebJobsStorage__ac`c`ountName

**Comment by unscrum** [comment]
I'm seeing this same issue on Linux Plan with User Managed Identity in South Central US.  

RBAC is setup as:
Storage Blob Data Owner
Storage Queue Data Reader
Storage Queue Data Message Processor

Also using FuncAppVersion ~4 and .NET 6

**Comment by balag0** [comment]
@unscrum the original issue was a typo in the appsetting name, if that is not the case here, could you please open new issue with the appdetails. Closing this one as resolved. Thanks.
