### ISSUE TITLE
[Custom Handlers] Add option for host to not follow redirects

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-host#7860]
#### What problem would the feature you're requesting solve? Please describe.
For custom handlers, when `enableForwardingHttpRequest` is enabled, when the custom handler returns a 301, 302, or 307, this is not propagated back in the HTTP response from the function host. Instead, the host [follows](https://github.com/Azure/azure-functions-host/blob/1010912485d019bedb30bcb32086e9a54ab2cbca/src/WebJobs.Script/Workers/Http/DefaultHttpWorkerService.cs#L120) the redirect and returns the response from that. 

#### Describe the solution you'd like
There should be an option to disable following redirects and simply propagate the 30x responses back to the caller.

#### Describe alternatives you've considered
No known workarounds.

#### Additional context
The current behavior is probably considered a bug but since it's a breaking change, it needs to be behind a flag.

**Comment by anthonychu** [comment]
FYI @fabiocav @kshyju @satvu as this affects some of the custom handler related stuff you might be working on.

**Comment by fabiocav** [comment]
Moving this to 117, but we're still trying to make the current release with this item.

**Comment by anthonychu** [comment]
Uploaded a repro here: https://github.com/anthonychu/20220121-custom-handlers-redirect

@madelinegordon @fabiocav:

* Do you agree that this is a breaking change and needs a flag to enable, or is it a bug?
* Should we never follow redirects when invoking the custom handler, or only when `enableForwardingHttpRequest` is true? I can't think of a reason why a custom handler would return a redirect and expect the host to follow it.

**Comment by fabiocav** [comment]
I think it would make sense to make this change apply to scenarios where we have `enableForwardingHttpRequest` enabled, and that being the case, since this is not publicly documented, we should be able to make the change without a flag.

Thoughts?

**Comment by fabiocav** [comment]
Work should be completed in 118.
