### ISSUE TITLE
Image.FromStream throws an ArgumentException

### ISSUE THREAD

**Issue by ihordyrman** [Azure/azure-functions-host#7862]
#### Is your question related to a specific version? If so, please specify:
V3 / .net core 3.1 / Consumption plan / 32bit
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question
I have a code in my function that creates a new Image (System.Drawing.Image) from byte[] 
```cs
await using MemoryStream tempStream = new MemoryStream(imageInfo.Content);
Image img = Image.FromStream(tempStream);
```
Content holds a valid byte array of an image that I need to process. After calling FromStream it throws an exception "Parameter is not valid". 

I've made some research and found this [list of restrictions](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#win32ksys-user32gdi32-restrictions) for azure web apps. The problem is this code worked totally fine until a week or so.
Locally it works as expected without any exceptions. I'm trying to figure out if this problem is related to the web apps restrictions or no and if yes why has it worked before?

**Comment by ihordyrman** [comment]
After making some workaround I've found that this code doesn't work properly only inside durable functions.
I've moved this logic to a single HTTP trigger function and now it's working as expected.
Still can't figure out why this is happening in durable functions.

**Comment by ihordyrman** [comment]
Well, it's still failing sometimes. So, the problem is not related to the durable functions.

**Comment by v-bbalaiagar** [comment]
Hi @ihordyrman, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by ihordyrman** [comment]
Hi, @v-bbalaiagar. 
I've struggled with the current issue for too long and have decided to move to the new Isolated process model. 
After switching the problem is gone, so I can assume that it was related to the host runtime.

**Comment by v-bbalaiagar** [comment]
Hi @ihordyrman, Thank you for the update, Please let us know if this can be closed or you have further queries.
