### ISSUE TITLE
Application SDK Version 2.18 ETA for availability on Function V3

### ISSUE THREAD

**Issue by ffarinha-msft** [Azure/azure-functions-host#7869]
Hi,

Kindly requesting if there is any expected ETA that can be provided regrading the support for Application Insight SDK  V2.18 on the functions V3 ? 

Currently we can see that at least for .NET core on Linux the dll loaded there is for V2.17. 

We need to use server Telemetry Channel with the new IAsyncFlushable which is only available on the new AI SDK version 2.18 (released 3 months ago https://www.nuget.org/packages/Microsoft.ApplicationInsights/).

Another option is to run function V4 which already accepts V2.18 of the AI SDK (already tested), but it's in preview. What ever ETA is closer is fine for us.

**Comment by fabiocav** [comment]
Moving this to the host as we'll be performing the update here. 

We'll make the change to 3.0 and 4.0
