### ISSUE TITLE
When using MSI for AzureWebJobsStorage, can I disable shared key access for the underlying storage account?

### ISSUE THREAD

**Issue by mdddev** [Azure/azure-functions-host#7871]
Hi

When using [managed-identity-aware](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=azurewebjobsstorage#connecting-to-host-storage-with-an-identity-preview) host connections to `AzureWebJobsStorage`, can I safely disable shared key access on the underlying storage account?

Even though the shared key is not used, it is still existing. I'd like to [disable account key access](https://docs.microsoft.com/en-us/azure/storage/common/shared-key-authorization-prevent?tabs=portal) altogether and force Azure Ad auth. Will this be a problem? Not only for running an existing app but also regarding deployment?

Does the tooling like `az functionapp deployment` use account key-derived SAS and will break eventually?

Cheers

**Comment by balag0** [comment]
Yes some deployment scenarios might still need access to the storage key for now. It depends on configs like private endpoints, key vault references, OS/SKU etc.
Also just the deployment would fail not the app as that would still continue use the identity based connections.

**Comment by mdddev** [comment]
Thanks @balag0 
Maybe you can say something regarding this particular case. Will that work in your opinion? Any insights will be mich appreciated.

* Elastic Premium Windows
* Regional VNET integration into subnet
* The subnet has a storage service endpoint enabled
* The host storage account has network restrictions enabled allowing access from that VNET-integrated subnet
* No private endpoints used
* KeyVault references are used
* using MSI-aware triggers for queue and blob for a DIFFERENT storage account (here account key access is already disabled).  
* Does using input/output bindings matter?
* deployment via cli: az functionapp deployment source config-zip
* WEBSITE_RUN_FROM_PACKAGE = 1

**Comment by mdddev** [comment]
I am closing this now. At the latest BUILD suuport was [announced](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/azure-functions-may-update-for-microsoft-build/ba-p/3827388) for the host working with AzureWebJobsStorage. So this support was not there previously.
