### ISSUE TITLE
Worker Indexing - Investigation on using worker capabilities instead of worker.config

### ISSUE THREAD

**Issue by surgupta-msft** [Azure/azure-functions-host#7879]
For now, the worker indexing check within the host is based off the worker.config.json file defining workerIndexing as “true”. This doesn’t fit the true spirit of the worker “advertising” the ability of indexing to the host. Instead, it would make more sense for the worker to decide whether to index or not and then send "indexing” as a capability during the initial GRPC handshake when starting up communication with the host.

**Comment by kashimiz** [comment]
Design is under discussion; requires feedback from maintainers of language workers.

**Comment by fabiocav** [comment]
Moving this to sprint 116 for design. 

@surgupta-msft will update with details once we close on a design for this.

**Comment by surgupta-msft** [comment]
Below is the summary of multiple discussions on this issue -
If the payload of customer app does not allow worker to index then worker will have the ability to deny indexing and host will fallback to its own indexing. This work is being tracked as part of issue - https://github.com/Azure/azure-functions-host/issues/7916 and changes are in PR - https://github.com/Azure/azure-functions-host/pull/7980

cc @fabiocav
