### ISSUE TITLE
Sending single FunctionLoadRequest in case of multiple functions

### ISSUE THREAD

**Issue by surgupta-msft** [Azure/azure-functions-host#7880]
Host should be sending single FunctionLoadRequest even if multiple functions are there in Function App. Need to investigate if current code already has this behavior and fix if it does not already exist.

**Comment by kashimiz** [comment]
This change is motivated by performance improvements to host startup latency.

@brettsam @soninaren Can you provide context on the current behavior of the host, and why we went with the existing design? My understanding (from @satvu) is that the host currently sends one FunctionLoadRequest per function to the worker. What potential downsides are there to consolidating FunctionLoadRequests?

**Comment by fabiocav** [comment]
I think we're in agreement that we want to make this change and modify the existing behavior before this GAs. 

@vrdmr @surgupta-msft it would be good to bring this up during the sync.
