### ISSUE TITLE
OutOfMemoryException on V3 to V4 Migration (with .NET Core 3.1 to .NET 6.0)

### ISSUE THREAD

**Issue by christophwille** [Azure/azure-functions-host#7881]
I migrated an existing .NET Core 3.1 in-proc Azure Functions app to .NET 6.0 using the guidance at https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=in-process%2Cv4&pivots=programming-language-csharp#migrating-from-3x-to-4x. Then I published (with setting delete all extra files) to the slot where the .NET Core 3.1 function lived and worked nicely for months.

The code in question opens read to Blob storage (custom code, no trigger). Simplified:

```
var client = new BlobServiceClient(new Uri($"https://{_accountName}.blob.core.windows.net"), _accountCredentials);
var blobClient = client.GetBlobContainerClient(containerName).GetBlobClient(blobName);

var stream = await blobClient.OpenReadAsync(new BlobOpenReadOptions(false));
```

This then OOMs.

#### Investigative information
- Windows consumption tier
- Timestamp: 2021-11-23 10:07:17.691
- Function App version: 4.0.1.16815
- Function App name: eeazfuncppe
- Function name(s) (as appropriate): ReadRevitVersion

| where operation_Id == '2c0db5f3218278cae72bf3ae9bdeced7'
| where customDimensions['InvocationId'] == '6299cbff-aaa3-4d2b-8bfe-9184dcede4ca'

Exception:

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, GC_ALLOC_FLAGS flags)
   at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int32 minimumLength)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.OpenReadInternal(Int64 position, Nullable`1 bufferSize, BlobRequestConditions conditions, Boolean allowModifications, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.OpenReadAsync(BlobOpenReadOptions options, CancellationToken cancellationToken)
   at MyFunc.ReadRevitVersionFunc.Run(HttpRequest req, ILogger log) in D:\VIMaecWorkspace\Repos\estimatingedge\src\MyFunc\ReadRevitVersionFunc.cs:line 37
```

Side-note: I am having problems with OOM on Windows Docker Container for .NET 6.0 too (totally different though), so maybe that is related here.

**Comment by v-bbalaiagar** [comment]
Tagging @pragnagopa , for further insights

**Comment by pragnagopa** [comment]
@christophwille - please confirm if your app is running on dynamic sku and is x64 bit

**Comment by christophwille** [comment]
Yes, it is 64 Bit (Configuration/General Settings). Where can I see dynamic? I went to resources.azure.com for the underlying plan and it says `"computeMode": "Dynamic",` and

```
  "sku": {
    "name": "Y1",
    "tier": "Dynamic",
    "size": "Y1",
    "family": "Y",
    "capacity": 0
  }
```

**Comment by pragnagopa** [comment]
Thanks @christophwille for sharing the details!. There is a known issue in the platform for x64 bit Function Apps running on Windows in dynamic sku. Fix will be rolled out in the next couple of months. Until then please set  App Setting: `COMPLUS_GCHeapHardLimit` to the value `0x60000000`

cc @fabiocav @kranthikumarm @safihamid

**Comment by christophwille** [comment]
Just to make sure - we are talking about Configuration/Application settings?

**Comment by pragnagopa** [comment]
> we are talking about Configuration/Application settings?

Correct - add new app setting `COMPLUS_GCHeapHardLimit` and set it's  value to `0x60000000`

**Comment by christophwille** [comment]
I have verified that this works, however, then went back to netcore3.1 to wait for the "official" fix (this function app is not critical to be moved to 6.0)

In my initial comment I had a side note about other OOMs in Windows .NET 6 containers - would that fix apply there too / different fix / other discussions/issues you could point me to?

**Comment by fdipuma** [comment]
We are experiencing the same issue after migrating an app from .NET Core 3.1 + Functions v3 to .NET 6 + Functions v4.

64bit app config.

Is that related to https://github.com/Azure/azure-functions-host/issues/5430 ?

**Comment by lukasvosyka** [comment]
Same here! Also seems to OOM at 100MB memory usage. Can it be? We also are running Consumption plan functions on Windows and deployed as NET6.0 v4 functions running now into OOMs.

**Comment by lukasvosyka** [comment]
@pragnagopa based on this documentation https://docs.microsoft.com/en-us/dotnet/core/run-time-config/garbage-collector it tells the variable `DOTNET_GCHeapHardLimit`?

Is this correct?

**Comment by sbest-gcm** [comment]
> Thanks @christophwille for sharing the details!. There is a known issue in the platform for x64 bit Function Apps running on Windows in dynamic sku. Fix will be rolled out in the next couple of months. Until then please set App Setting: `COMPLUS_GCHeapHardLimit` to the value `0x60000000`
> 
> cc @fabiocav @kranthikumarm @safihamid

Any update on the permanent fix?

**Comment by pragnagopa** [comment]
Fix related to x64 Apps rolled out to production. Closing this issue. Please open a separate issue with repro details
