### ISSUE TITLE
How to get the function Keys in ARM templates?

### ISSUE THREAD

**Issue by FisherMS** [Azure/azure-functions-host#7897]
Azure Function app Runtime version: ~3
C#
I want get the Http trigger url in Azure function app in ARM template. But I cant find the right method.

when I use these code has exception.
```json
    "Key": {
        "type": "string",
        "value": "[listsecrets(resourceId('Microsoft.Web/sites/functions', parameters('existingFunctionAppName'), parameters('functionName')),'2015-08-01').key]"
    },        
    "Url": {
        "type": "string",
        "value": "[listsecrets(resourceId('Microsoft.Web/sites/functions', parameters('existingFunctionAppName'), parameters('functionName')),'2015-08-01').trigger_url]"
    }   
```
So, what is the correct method the get the trigger url or the function keys?

![image](https://user-images.githubusercontent.com/12068896/143814542-10481a8b-9535-47d3-89e3-e90eaa05893f.png)

**Comment by v-bbalaiagar** [comment]
Hi @Fisher-Joe, Thank you for your feedback! If your question is how to get the full trigger URL + key via ARM, here is the API: 
POST https://management.azure.com/subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Web/sites/{app}/functions/{func}/listsecrets?api-version=2016-08-01 

For the keys, we would recommend using the [key management APIs](https://github.com/Azure/azure-functions-host/wiki/Key-management-API). Where the key management API more robust API and will continue to work with different secret storage providers (e.g. Azure Storage, which is what is used when slots are enabled and will eventually become the default)

Let us know if this helps.

**Comment by Fisher-Joe** [comment]
Hi @v-bbalaiagar  
Thank you.

Sorry, I cant find how to config the ARM template to  get the trigger url by  [key management APIs](https://github.com/Azure/azure-functions-host/wiki/Key-management-API)

I use below config has a exception.
```json
[
    {
        "name": "TryToAwakeReportFuncApp",
        "functionAppResourceId": "[concat('Microsoft.Web/sites/', variables('sample1FunName'))]",
        "functionName": "HttpAwakeFunc",
        "httpTriggerUrl": "[concat('https://', variables('sample1FunName'),'.azurewebsites.net/api/','HttpAwakeFunc','?code=',listkeys(variables('sample1HttpFuncResId'), '2021-02-01').default)]",
        "useCommonAlertSchema": true
    }
]
```
```shell
6:04:02 AM - Resource Microsoft.Web/sites/functions 'ReportFunsApphqkyvd/HttpAwakeFunc' failed with message '{
  "Code": "Unauthorized",
  "Message": "Encountered an error (Forbidden) from extensions API.",
  "Target": null,
  "Details": [
    {
      "Message": "Encountered an error (Forbidden) from extensions API."
    },
    {
      "Code": "Unauthorized"
    },
    {
      "ErrorEntity": {
        "Code": "Unauthorized",
        "Message": "Encountered an error (Forbidden) from extensions API."
      }
    }
  ],
  "Innererror": null
}'
```

**Comment by FisherMS** [comment]
Hi @v-bbalaiagar 
Thank you.
I cannot find how to config the ARM template use the  key management APIs.
Could you give a example?

Now, I use this config to get the key.
```json
 "HttpAwakeFuncTriggerUrl": {
      "type": "string",
      "value": "[concat('https://', variables('sample1FunName'),'.azurewebsites.net/api/','HttpAwakeFunc','?code=',listkeys(variables('sample1HttpFuncResId'), '2021-02-01').default)]",
      "metadata": {
        "comments": "concat a trigger URL"
      }
    }
```

**Comment by v-bbalaiagar** [comment]
Hi @Fisher-Joe, Check out [this GitHub thread ](https://github.com/Azure/azure-functions-host/issues/3994#issuecomment-507693624)for some examples of how to use these APIs in your ARM templates.

Please check and let us know if this helps.

**Comment by FisherMS** [comment]
Hi @v-bbalaiagar ,
Thank you.
This method introduces a new dependency on Key Vault. I want to know is there  a simple way to directly obtain the automatically generated Key in FunApp instead of using KeyVault.
