### ISSUE TITLE
intermittent 404 Nginx error custom handler

### ISSUE THREAD

**Issue by Ballzer0** [Azure/azure-functions-host#7898]
#### Investigative information
We are using a Linux function on consumption tier in Northern europe. The issue seems similar to this. https://docs.microsoft.com/en-us/answers/questions/393494/random-404-error-on-azure-function.html

similar issue: https://github.com/Azure/azure-functions-host/issues/7421

Please provide the following:

- Timestamp: 2021-11-29T09:12:00Z
- Function App version: 3
- Function App name: quantus-test-go
- Invocation ID: d6739caf-1e66-42f7-81c7-e1f0c86655f5
- Region: North Europe 

#### Repro steps
issue seems intermittent, cant lock down exact repro steps, but happens when i call the function multiple times in a row to do processing.

#### Expected behavior

expected behavior is to reach my function, not to be stopped by nginx

#### Known workarounds
I've read on forums that upgrading to a premium function will solve the issue, but this would mess with the scalability we have designed for our application.

**Comment by Ballzer0** [comment]
error from power automate trying to reach the function
![image](https://user-images.githubusercontent.com/28560729/143833634-785bba15-2f03-484b-9a37-cac0431d5838.png)

error as HTML
```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by Ved2806** [comment]
Hi @yojagad / @balag0 , Could you please look into this issue?

**Comment by Ballzer0** [comment]
we upgraded to Function App version: 4

This **"so far"**, seems to have solved the issue, we will still be monitoring the situation, but the problem hasn't showed itself since we did the upgrade. I will keep the issue open for now and report back later.

**Comment by Ballzer0** [comment]
The function has been running for 1 day now without any more nginx 404 errors, normally we would have seen errors by now. Looks like the problem was with the Function App Version V3
