### ISSUE TITLE
Risk Alert if deployed customer function app is not deployed with Ready2Run

### ISSUE THREAD

**Issue by safihamid** [Azure/azure-functions-host#7901]
Need to log a statement if .NET Function app is not deployed with Ready2Run. This log entry will be read and alert to customers in cold start Risk Alert section of the portal.

Code to check for the condition:

using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;

static bool IsReadyToRun(Stream stream)
{
    try
    {
        using (PEReader peFile = new PEReader(stream))
        {
            return peFile.PEHeaders.CorHeader?.ManagedNativeHeaderDirectory.Size != 0;
        }
    }
    catch
    {
        return false;
    }
}

**Comment by anthonychu** [comment]
@fabiocav @brettsam we need a plan for using R2R by default and without additional work by the customer before we can warn about stuff like this.

**Comment by safihamid** [comment]
@anthonychu that is covered by a different issue. Raedy2Run is documented very well and we will link to the documentation in Risk Alerts. This is just to be able to notify customers what needs to be done to get best cold start so they are aware of it.
I would put it in same exact category as warmup triggers for premium/app service plans. We don't add it by default but we have it in Risk Alerts and documentation for it.
Yes would be great to add it by default but I treat these two separately.

**Comment by safihamid** [comment]
Other issue tracking what asked by @anthonychu:

https://github.com/Azure/azure-functions-host/issues/7900
