### ISSUE TITLE
IANA timezone style doesn't work on Windows dotnet 6.

### ISSUE THREAD

**Issue by daigok** [Azure/azure-functions-host#7909]
#### Investigative information
I'm using a Windows function v4 using dotnet 6 on consumption tier in Japan East. Our code uses TimeZoneInfo with IANA style, but the code throws System.TimeZoneNotFoundException.

#### Repro steps

Create a new function on the portal. And create a new HttpTrigger function like follows:

```csharp
#r "Newtonsoft.Json"
using System;
using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Newtonsoft.Json;

public static async Task<IActionResult> Run(HttpRequest req, ILogger log)
{
    log.LogInformation("C# HTTP trigger function processed a request.");
    //var timeZone = TimeZoneInfo.FindSystemTimeZoneById("Tokyo Standard Time");
    var timeZone = TimeZoneInfo.FindSystemTimeZoneById("Asia/Tokyo");
    log.LogInformation($"{timeZone}");

    string name = req.Query["name"];

    string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
    dynamic data = JsonConvert.DeserializeObject(requestBody);
    name = name ?? data?.name;

    string responseMessage = string.IsNullOrEmpty(name)
        ? "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."
                : $"Hello, {name}. This HTTP triggered function executed successfully.";

            return new OkObjectResult(responseMessage);
}
```

Hit to "Run" the above code.

#### Expected behavior

It should be successfully finished.

#### Actual behavior

It throws a following exception.

```
2021-11-30T15:10:21.022 [Error] Executed 'Functions.HttpTrigger1' (Failed, Id=91fd9fd5-5b20-4a42-92cf-42bdf78de402, Duration=16ms)The time zone ID 'Asia/Tokyo' was not found on the local computer.
```

Dotnet 6 supports both IANA and Windows time zone style. So the code above should be fine.
https://devblogs.microsoft.com/dotnet/date-time-and-time-zone-enhancements-in-net-6/

#### Known workarounds
If we use TimeZoneConverter library, it accepts IANA style even on Windows.

**Comment by Ved2806** [comment]
Hi @daigok, You may want to use getSystemTimeZones() to retrieve in information about all the available time zone. Please let us know if this is helpful?

**Comment by daigok** [comment]
@Ved2806 
```csharp
TimeZoneInfo.FindSystemTimeZoneById("Asia/Tokyo");
```
The code above is what I want to use not getSystemTimeZones(). I've tried the FindSystemTimeZoneById("Asia/Tokyo") on my Windows dotnet 6, it works fine. This should be supported on the dotnet 6 environment.

Please check the article below.
https://devblogs.microsoft.com/dotnet/date-time-and-time-zone-enhancements-in-net-6/#time-zone-conversion-apis

**Comment by Ved2806** [comment]
Hi @daigok, In the below link, you will get the information about how to use getSystemTimeZones() to verify and inspect different available time zones on your local machine. https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.getsystemtimezones?view=net-6.0

**Comment by daigok** [comment]
```csharp
GetSystemTimeZones()
```
shows following time zones on the cloud.
```
2021-12-12T14:38:38.302 [Information] DisplayName: (UTC+09:00) Osaka, Sapporo, Tokyo
2021-12-12T14:38:38.302 [Information] StandardName: Tokyo Standard Time
```

 And the code below works fine.
```csharp
TimeZoneInfo.FindSystemTimeZoneById("Tokyo Standard Time");
```
However, the IANA style doesn't work.
```csharp
TimeZoneInfo.FindSystemTimeZoneById("Asia/Tokyo");
```

The both code works fine on local Windows on dotnet 6.

**Comment by Ved2806** [comment]
Thank you for the feedback! We will check for the possibilities internally and update you with the findings.

**Comment by daigok** [comment]
@Ved2806 
Any updates? 

The issue is labeled as no-recent-activity. Can you remove the label, otherwise the issue will be closed automatically.

**Comment by mrurb** [comment]
This issue is still ongoing is there plans to implement iana timezones?
`The time zone ID 'Etc/GMT+5' was not found on the local computer.`
Azure function running net6.0 and azure function 4.1.3.17473

**Comment by Ved2806** [comment]
Hi @fabiocav Could you please help with this?

**Comment by kshyju** [comment]
Hi @daigok Thanks for sharing the repro information. This issue is not specific to azure functions. You will experience the same issue if you try your code in an aspnet core web api (net 6) and deploy to azure. Let me check with the team to determine whether this is a platform issue or an issue with the API itself. 

cc @pragnagopa @fabiocav

**Comment by pragnagopa** [comment]
cc @pgombar fyi - incase follow up is needed for any platform changes

**Comment by pguidoPokerAtlas** [comment]
Having the same issue on Azure App Service when using "America/New_York" for example.  When querying the server OS, I get the following:
      "operatingSystemDescription": "Microsoft Windows 10.0.14393",
      "frameworkDescription": ".NET 6.0.1",
Seems like it should support both Windows and IANA timezone id's based on these versions.

**Comment by kshyju** [comment]
As per [this comment](https://github.com/dotnet/runtime/issues/60175#issuecomment-974295612), the OS build should be 1903 or later for the ICU.dll (which the API relies on) to be present in the OS. 

A workaround is suggested [here](https://github.com/dotnet/runtime/issues/60175#issuecomment-939352598). When you use this workaround, the visual studio publish artifact will include the ICU dll from your local machine. I was able to verify this workaround on an aspnet core web api app deployed on azure app service (deployed from visual studio publish option).

Could you give this a try @daigok @pguidoPokerAtlas @mrurb ?
