### ISSUE TITLE
Using Azure.Messaging.EventGrid.EventGridEvent

### ISSUE THREAD

**Issue by jblanchet** [Azure/azure-functions-host#7910]
#### Is your question related to a specific version? If so, please specify:
Using Functions v3 or v4, (along with .net 3.1 or .net 6).

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
Creating a brand new EventGrid triggered function through the VS 2022 template, if I want to use the new Azure.Messaging.EventGrid.EventGridEvent class (instead of the old one Microsoft.Azure.EventGrid.Models.EventGridEvent), I get an error when the event tries to fire:

`[2021-11-30T15:58:16.533Z] Executed 'ProcessLogs' (Failed, Id=28049e5d-7bba-4740-b04b-41e5f55b6a28, Duration=67ms)
[2021-11-30T15:58:16.535Z] System.Private.CoreLib: Exception while executing function: ProcessLogs. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'eventGridEvent'. Newtonsoft.Json: Unable to find a constructor to use for type Azure.Messaging.EventGrid.EventGridEvent. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path '[0].id', line 1, position 7.`

I can't find any examples of an actual function which uses the new EventGridEvent class (just some unit test examples on github), but I would like to not have to use Newtonsoft, which is what the old Microsoft.Azure.EventGrid.Models.EventGridEvent class uses. Is this possible?

My entire function code:

```using Azure.Messaging.EventGrid;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.EventGrid;
using Microsoft.Extensions.Logging;

namespace EventGridTestNet6
{
    public static class Function1
    {
        [FunctionName("ProcessLogs")]
        public static void Run([EventGridTrigger] EventGridEvent eventGridEvent, ILogger log)
        {
            log.LogInformation(eventGridEvent.Data.ToString());
        }
    }
}

**Comment by v-bbalaiagar** [comment]
Hi @jblanchet, Thank you for your feedback! If you want to use the latest and greatest types, you have to be on the latest version of the extension as well. 
Here is the latest version of the event grid extension - https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventGrid/

Please check and let us know if you are able to solve the issue with this information.

**Comment by jblanchet** [comment]
Ah right, that was my issue. Thank you for the response!
