### ISSUE TITLE
ServiceBusTrigger should auto scale with identity-based connections

### ISSUE THREAD

**Issue by sanjaydebnath** [Azure/azure-functions-host#7921]
Currently to make sure 'auto scaling' works correctly we have to provide a shared access policies that has the 'manage' capability at the service bus namespace level. It's well documented [here](https://docs.microsoft.com/en-us/azure/azure-functions/event-driven-scaling#understanding-scaling-behaviors).

> Scale efficiency: For Service Bus triggers, use Manage rights on resources for the most efficient scaling. With Listen rights, scaling isn't as accurate because the queue length can't be used to inform scaling decisions. To learn more about setting rights in Service Bus access policies, see Shared Access Authorization Policy. For Event Hub triggers, see the scaling guidance in the reference article.

Now with newer [v4 versions we can use MSI based connection strings](https://docs.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial-2#configure-your-service-bus-trigger-with-a-managed-identity) that does not require a full connection string or shared access policies (just the namespace is needed). It actually solved the problem of managing & rotating the shared access policies greatly. E.g. in my function app I could add a key like 'ServiceBusConnection__fullyQualifiedNamespace' with value 'mynamespace.servicebus.windows.net' and things should just work fine. 

But now the problem is if I want to auto scale the function app (consumption/premium plan) along with taking advantage of this key-less connection strings or shared access policies, it does not work.

#### Describe the solution you'd like
ServiceBusTrigger should auto scale with MSI based connection string (assuming the user identity has 'Azure Service Bus Data Owner' role against the service bus namespace.

#### Describe alternatives you've considered
For now I am adding the shared access policy in KeyVault & referring the same from azure function app config.

**Comment by Ved2806** [comment]
@karshinlin Could you please look at it?
Hi @sanjaydebnath , Could you please provide functionapp name/invocactionid, region and timestamp so that we can look at the log?
