### ISSUE TITLE
Functions V4 don't support Microsoft.Azure.WebJobs.Extensions.Storage 5.0.0

### ISSUE THREAD

**Issue by heavenwing** [Azure/azure-functions-host#7954]
#### Repro steps

1, Build a Function app with v3 and .NET Core 3.1 and deploy it into Azure, csproj like this:
```xml
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <UserSecretsId>af22dcc4-fd68-42fc-83a8-e0cbb32875ef</UserSecretsId>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AzureFunctions.Autofac" Version="4.0.3" />
    <PackageReference Include="FreeSql.Provider.SqlServer" Version="2.6.100" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="4.0.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.5.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="0.8.1-preview" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="3.1.18" />
    <PackageReference Include="Microsoft.Graph.Auth" Version="1.0.0-preview.6" />
    <PackageReference Include="Microsoft.Graph.Beta" Version="0.49.0-preview" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
    <PackageReference Include="Polly" Version="7.2.2" />
  </ItemGroup>
```
2, Upgrade this app into v4 and .NET 6.0, at same time upgrade "Microsoft.Azure.WebJobs.Extensions.Storage" into 5.0.0, csproj is:
```xml
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <UserSecretsId>af22dcc4-fd68-42fc-83a8-e0cbb32875ef</UserSecretsId>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.5.0" />
    <PackageReference Include="AzureFunctions.Autofac" Version="4.0.3" />
    <PackageReference Include="FreeSql.Provider.SqlServer" Version="2.6.100" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="4.0.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.6.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Sql" Version="0.1.131-preview" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.0" />
    <PackageReference Include="Microsoft.Graph.Beta" Version="4.22.0-preview" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />
    <PackageReference Include="Polly" Version="7.2.2" />
  </ItemGroup>
```
3, Use arm template to change function app's runtime into V4, and re-deploy it into Azure, Azure portal report error like this:
```
ExtensionStartupType AzureStorageWebJobsStartup from assembly 'Microsoft.Azure.WebJobs.Extensions.Storage, Version=3.0.10.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not meet the required minimum version of 4.0.4.0. Update your NuGet package reference for Microsoft.Azure.WebJobs.Extensions.Storage to 4.0.4 or later.
```
4, Downgrade "Microsoft.Azure.WebJobs.Extensions.Storage" into 4.0.5, deploy it again, it's working

#### Expected behavior

It should be working when use "Microsoft.Azure.WebJobs.Extensions.Storage"  5.0.0

#### Actual behavior

Function app cannot be working.

#### Known workarounds

Downgrade "Microsoft.Azure.WebJobs.Extensions.Storage" into 4.0.5

#### Related information 

Locally debugging is always working.

This issue may be releated with https://github.com/Azure/Azure-Functions/issues/1987

**Comment by heavenwing** [comment]
@paulbatum Please review this issue. If you need whole project source code, please contact me internally.

**Comment by paulbatum** [comment]
@heavenwing I just tried to reproduce this myself and I was not successful. I took your first csproj, built and ran, then did a clean (so that I don't have anything from the V3 version in my output directory), updated the csproj using your second example and built again, confirmed it was working locally, then deployed to Azure using the publish feature in VS (I kept the default of "run from package" selected). The app I deployed to was created as functions V4 (.NET) and [is running without issues](http://github7954.azurewebsites.net).

My best guess of what is happening here is that you are trying to do an in-place upgrade of a function app and your method of publishing is not removing old artifacts.

Can you try using the same flow I described, where you create a new V4 function app and then deploy the v4 build (using the same csproj you shared)? My guess is that the issue won't repro in this case. If so then the remaining investigation can focus on the details of the specific function app you are deploying to (and how you're doing your deployment)

**Comment by paulbatum** [comment]
One more thing - can you try accessing the scm endpoint for the application, and use the process explorer to view the loaded modules. 

For example if I go here (and authenticate):
https://github7954.scm.azurewebsites.net/ProcessExplorer/

I choose the non-scm process in the list, and open the modules view:
![image](https://user-images.githubusercontent.com/10663/144910513-0b445ce3-843a-4589-8c2c-828cd907a384.png)

and then I scroll down:
![image](https://user-images.githubusercontent.com/10663/144910601-ee376650-3948-4e35-a0f0-81f72f105d60.png)

You can see that `Microsoft.Azure.WebJobs.Extensions.Storage` is not in my list. My guess is that it will be for the app that repros, and thats the problem.

**Comment by heavenwing** [comment]
I use Azure Pipeline to deploy this function app. In the release pipeline, I use "ARM template deployment" task to update function app from v3 into v4 firstly, then use "Azure Functions" task to update function app package.
The yaml of "Azure Functions" task is 
```yaml
steps:
- task: AzureFunctionApp@1
  displayName: 'Azure Function App Deploy'
  inputs:
    azureSubscription: 'ADMS Test Subscription'
    appType: functionApp
    appName: '$(FnAppName)'
    package: '$(System.DefaultWorkingDirectory)/_ci/fnapp/*.zip'
    appSettings: 
```
May be, your guess is right, "Azure Functions" don't clean old storage dll. 

In process explorer, I can see `Microsoft.Azure.WebJobs.Extensions.Storage` 4.0.3 in my list.

**Comment by paulbatum** [comment]
@heavenwing If you configure this function app to use [run from package](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package), that might solve the problem. I would try setting it to "1" - this configures the system to store the deployed zip into the filesystem and then run from that zip directly. It means that the app won't see older files.
