### ISSUE TITLE
EventHub Trigger stops firing after a while

### ISSUE THREAD

**Issue by GufCab** [Azure/azure-functions-host#7972]
In a .NET function running with an Eventhub Trigger, the function simply stops triggering after a while (from a few hours to a few days) with no errors in the log. 
Events are being added to the EventHub just fine and no changes are made to either function, serviceplan or EventHub. We have tried this with both a consumption plan function and a service plan function (though not with 'always on' enabled).

Restarting or disabling/enabling the function does not work - but changing the consumer group appears to work for a while until it happens again. 

#### Investigative information

Please provide the following:

- Timestamp: 2021-12-09 08:35:40.710
- Function App version: V3
- Function App name: os2-kk-test-iitf-functions-router
- Function name(s) (as appropriate): Router
- Invocation ID: NA, the function doesn't fire
- Region: West Europe

#### Repro steps

Running the app for a while, the app simply stops after some time.

#### Expected behavior

The app should keep ingesting events.

#### Known workarounds

Setting a new Consumergroup on the EventHub and function seems to reset it.

#### Related information 

Provide any related information 

* Programming language used 
C#/.NET

* Bindings used
EventHub Trigger

* Included libs in .csproj
``` <PackageReference Include="Microsoft.Azure.Devices" Version="1.30.0"/>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.2.0"/>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11"/>
    <PackageReference Include="System.Runtime.Caching" Version="4.7.0"/>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.11"/>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3"/>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.1.0"/>
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.11"/>
```

**Comment by AdaTheDev** [comment]
I'm also experiencing this behaviour - C# EventHub trigger stops consuming events, no errors. 

In terms of workaround - if I go into the Function App in the Azure Portal, without actually changing anything, that seems to make it "wake up" and it starts processing messages again. But obviously not viable for Production use.

Very similar setup:
* Functions V3 in West Europe
* Linux Consumption Plan
* Microsoft.Azure.Functions.Extensions 1.1.0
* Microsoft.NET.Sdk.Functions 3.0.13
* Microsoft.Azure.WebJobs.Extensions.EventHubs 4.0.1
* Not using the $Default consumer group

**Comment by GufCab** [comment]
We actually found the reason for our issue and have solved it. Hierarchical namespacing was enabled in the storage account used by the trigger. Due to some error in the eventhub trigger, the function is unable to regain the lease on the eventhub - which explains the behaviour. 

The issue is also described here:
https://github.com/Azure/azure-functions-eventhubs-extension/issues/81

And if one follows the best practice for storage accounts, it would not have happened: 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-best-practices?tabs=csharp#storage-account-configuration
