### ISSUE TITLE
Microsoft.Azure.WebJobs.Host.dll is shipping with an Embedded PDB.

### ISSUE THREAD

**Issue by chuckries** [Azure/azure-functions-host#7986]
Larger issue here: https://github.com/Azure/Azure-Functions/issues/2126

Microsoft.Azure.WebJobs.Host.dll from the [Microsoft.Azure.WebJobs](https://www.nuget.org/packages/Microsoft.Azure.WebJobs/) package is shipping with an Embedded PDB, which is not expected for release built, optimized binaries. See the issue referenced above for further discussion of the issues with this.

**Comment by v-bbalaiagar** [comment]
Hi @chuckries, Closing this issue as duplicate. For more updates please follow the space - https://github.com/Azure/Azure-Functions/issues/2126
