### ISSUE TITLE
Azure Functions - .NET 5 - Did not find any initialized language workers - Intermittently

### ISSUE THREAD

**Issue by venkatsm** [Azure/azure-functions-host#7991]
we are seeing "Did not find any initialized language workers" when our .NET 5 (dotnet-isolated) function is triggered. The trigger is on event hubs, which works well for a few executions and intermittently it throws an exception. In the last few days, the error rate is going high around

Investigative information
Please provide the following:

Timestamp (UTC): 2021-12-14T15:42:49.385Z
Function App version: ~3 (presuming this is runtime version)
Function App name: <redacted>
Function name(s) (as appropriate): <redacted>
Invocation ID: f0b4788f-b57c-47ef-92a6-9bf893efeda6
Region: East US
Expected behavior
Function app triggers and completes successfully.

Actual behavior
Function app is triggered but host fails to start within c.50 seconds; log shows "Did not find any initialized language workers"

Known workarounds
None

Related information
.NET 5 function app; single function within.
Running as dotnet-isolated

**Comment by v-bbalaiagar** [comment]
Hi @venkatsm, Thank you for your feedback! I went through the logs for the time stamp : 2021-12-14 00:00:00 to 2021-12-14 18:42:00. I see the error "Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.Dtp***** ---> System.InvalidOperationException : Did not find any initialized language workers".

We will investigate this further and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @liliankasem , Could you please take a look at this issue.

**Comment by liliankasem** [comment]
This might be due to your function app crashing due to a Cosmos exception

```
"Details": Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.Dtp***---> Microsoft.Azure.WebJobs.Script.Workers.WorkerProcessExitException : C:\Program Files (x86)\dotnet\dotnet.exe exited with code -532462766
 Unhandled exception. Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: ServiceUnavailable (503); Substatus: 0; ActivityId: 0ba86e12-7607-4d7a-b655-7e9248ea72d9; Reason: (The request failed because the client was unable to establish connections to 0 endpoints across 1 regions. The client CPU has thread starvation.,--- Cosmos Diagnostics ---
 ```

**Comment by liliankasem** [comment]
@venkatsm are you still seeing this issue today? I can't seem to pull up the logs for invocation id `f0b4788f-b57c-47ef-92a6-9bf893efeda6` so I wonder if you have anything recent I can look at.
