### ISSUE TITLE
Is Runtime Scale Monitoring supported in V4?

### ISSUE THREAD

**Issue by danielrobinson95** [Azure/azure-functions-host#7996]
Is runtime scale monitoring supported in v4 function apps? 

I'm unable to toggle the Runtime Scale Monitoring feature when using a V4 function app. The "On" option is disabled. 

![image](https://user-images.githubusercontent.com/26141892/146084249-b0e8a4e8-693a-42e7-908c-c5680ccccf10.png)

When switching to V3 without updating any other settings, the radio button becomes enabled. 

![image](https://user-images.githubusercontent.com/26141892/146084431-0e7862ee-5315-4ea6-bfae-fcd22f328761.png)

**Comment by v-bbalaiagar** [comment]
Hi @danielrobinson95, Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @pragnagopa , Can you please confirm if runtime scale monitoring supported in v4 function apps.

**Comment by pragnagopa** [comment]
@danielrobinson95  - Please confirm the SKU for V4 function app. Runtime Driven Scaling is only supported for Elastic Premium Function Apps. 
cc @chiangvincent @cachai2 @TsuyoshiUshio

**Comment by danielrobinson95** [comment]
@pragnagopa  Yes it is an EP plan. The same function app lets me toggle the `Runtime scale monitoring` option when I downgrade the runtime to V3.

**Comment by pragnagopa** [comment]
@danielrobinson95 - thanks for confirmation. Assigning to @TsuyoshiUshio - to repro issue and follow up with UX team.

**Comment by Tyler-V** [comment]
Has this been addressed? I am currently observing this in an EP plan on runtime version 4.

What is even more odd is I can't adjust any of my scale out settings, this lead me down the rabbit hole that setting Runtime Scale Monitoring to On is a prerequisite for adjusting anything in scale out

![image](https://user-images.githubusercontent.com/3893234/168160067-02a73bd4-1eaf-4fff-b1a2-0a0b6ad2d931.png)

**Comment by smokedlinq** [comment]
FYI this was working prior, I have a BICEP template that has been deployed last month that no longer works.

**Comment by TsuyoshiUshio** [comment]
Hello. I think it is a bug of the Portal.  For mitigation, I use Azure CLI instead and it works. 

```
az resource update -g <RESOURCE_GROUP> -n <FunctionAppName>/config/web --set properties.functionsRuntimeScaleMonitoringEnabled=1 --resource-type Microsoft.Web/sites
```


  
CC @pragnagopa

**Comment by TsuyoshiUshio** [comment]
Now The portal looks fixed it. 
![image](https://user-images.githubusercontent.com/1390976/194909100-6cbee783-e5af-4eb5-8fbd-3415bfac2ca9.png)
