### ISSUE TITLE
App setting error when referencing keyvault secret on Function App using Linux Service Plan

### ISSUE THREAD

**Issue by twentytwokhz** [Azure/azure-functions-host#7997]
We are unable to set an Application Setting on the Configuration section of a Function App v4 .NET 6 isolated process.
This happens on a Linux App Service Plan.

The setting references a KeyVault secret in the format ```@Microsoft.KeyVault(SecretUri=https://myvaul.vault.azure.net/secrets/MySecret-ConnectionString/)```

This works correctly on a Function App using a Windows App Service Plan.
Both have user managed identity to access the appropriate KeyVault instance.

On the windows plan the setting shows with a green checkmark.
On the linux plan the setting is shown with a red error marker.

Running the diagnostics and troubleshooting section is not helpful.
It does not reveal **any** kind of error on the keyvault reference thus misleading the user.

**Comment by balag0** [comment]
@twentytwokhz Could you share the appname - https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by twentytwokhz** [comment]
@balag0 Function hosted here (no sensitive data):
https://bb-linuxfunctionapp.azurewebsites.net/
Region: WestEurope

**Comment by balag0** [comment]
Thanks. Looks like a mismatch in the type of identity being used. Is the app using SystemAssignedIdentity to resolve references?

**Comment by twentytwokhz** [comment]
> Thanks. Looks like a mismatch in the type of identity being used. Is the app using SystemAssignedIdentity to resolve references?

I'm using a **User assigned managed identity**. The code goes like this:

```csharp
    public static class Program
    {
        public static async Task Main()
        {
            ThreadPool.SetMinThreads(100, 100);
            ServicePointManager.DefaultConnectionLimit = 100; //(Or More)

            var host = new HostBuilder()
                .ConfigureAppConfiguration(builder =>
                {
                    builder.AddEnvironmentVariables();

                    string appcsUrl = Environment.GetEnvironmentVariable("AppConfigUrl");
                    string clientId = Environment.GetEnvironmentVariable("ManagedIdentityClientId");

                    builder.AddAzureAppConfiguration(options =>
                    {
                        var defaultAzureCredential = GetDefaultAzureCredential(clientId);

                        options.Connect(new Uri(appcsUrl), defaultAzureCredential)
                            // also setup key vault for key vault references
                            .ConfigureKeyVault(kvOptions =>
                            {
                                kvOptions.SetCredential(defaultAzureCredential);
                            });
                    });
                })
                .ConfigureServices((context, services) =>
                {
                    services.AddLogging();
                    services.AddAzureAppConfiguration();

                    services.AddTransient<IMailService, MailService>();
                    services.AddTransient<ITableStorageService, TableStorageService>();
                    services.AddTransient<IBlobStorageService, BlobStorageService>();

                    //these are always singleton services
                    services.AddSingleton<IIoTHubService, IoTHubService>();

                    var cosmosClientOptions = new CosmosClientOptions
                    {
                        OpenTcpConnectionTimeout = TimeSpan.FromSeconds(int.Parse(context.Configuration["CosmosDB-OpenTcpConnectionTimeout"])),
                        MaxRetryWaitTimeOnRateLimitedRequests = TimeSpan.FromSeconds(int.Parse(context.Configuration["CosmosDB-MaxRetryWaitTimeOnRateLimitedRequests"])),
                        Serializer = new SystemTextJsonSerializer()
                    };
                    var client = new CosmosClient(context.Configuration["CosmosDB-ConnectionString"], cosmosClientOptions);
                    services.AddSingleton<CosmosClient>(client);
                    services.AddTransient<ICosmosDbService, CosmosDbService>();
                })
                .ConfigureFunctionsWorkerDefaults()
                .Build();

            await host.RunAsync();
        }

        private static DefaultAzureCredential GetDefaultAzureCredential(string clientId) => new DefaultAzureCredential(new DefaultAzureCredentialOptions
        {
            ManagedIdentityClientId = clientId,
            //be explicit about this to prevent frustration
            ExcludeManagedIdentityCredential = false,
            ExcludeAzureCliCredential = false,

            ExcludeSharedTokenCacheCredential = false,
            ExcludeVisualStudioCodeCredential = false,
            ExcludeInteractiveBrowserCredential = true,
            ExcludeEnvironmentCredential = true,
            ExcludeVisualStudioCredential = false
        });
    }
```

**Comment by twentytwokhz** [comment]
@balag0 I think I narrowed it down to this [topic](https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references#access-vaults-with-a-user-assigned-identity)

In my case there might be differences between windows function apps deployed via ARM templates and this particular linux function app which was created via _Visual Studio Code_ advanced wizard.

The difference lies in the **keyVaultReferenceIdentity** property that I inspected on the **Export template**
- in the windows function app it was correctly referencing the user assigned managed identity
- in the linux function app (even though I set the user assigned managed identity in the Portal UI) the template shows a value of `SystemAssigned`

**Comment by twentytwokhz** [comment]
I executed the commands in the documentation with some minor tweaks (syntax was not working in cloud shell) and then the Key vault reference started working 🥇 🥳 

Closing this since now it's working.. but please note this was NOT obvious **at all**.
There is still room for improvement on the function app creation experience
