### ISSUE TITLE
TimerTrigger schedule obtained from config does not change inside of a deployed function app?

### ISSUE THREAD

**Issue by sonic1981** [Azure/azure-functions-host#8010]
I'm deploying a `dotnet-isolated` v3 azure function to a resource group with the following config:

```c#
[Function("Schedule")]
public async Task Schedule([TimerTrigger("%schedule%")] TimerInfo myTimer)
```

I have `schedule` as a setting in that app currently set to: `0 0 */12 * * *`. This works fine. 

The problem is if I want to update schedule to run more often, for example: `* * * * * *` the function app does not appear to run any more frequently? I've tried re-starting the app, etc. but my app still does not run. 

![image](https://user-images.githubusercontent.com/1443217/146352053-48218c2d-75a2-4b6d-9293-eaf0b669affb.png)

I can do this locally without an issue. Is this supported?

**Comment by Ved2806** [comment]
Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by Ved2806** [comment]
Hi @sonic1981 Could you please provide the following function app information so that we can investigate this issue further.
Function App Name, TimeStamp and region.
