### ISSUE TITLE
Why does the app need to be an Azure Function app?

### ISSUE THREAD

**Issue by alexandrehtrb** [Azure/azure-functions-host#8020]
Hello,

I worked for some time with Azure Functions and one aspect that intrigues me is: why does the app need to be an Azure Function app?

The functions' declarations, bindings and overall code are different from the mostly used ASP.NET, at least for .NET. Creating an Azure Function requires a development effort to write this API layer. This raises a question: why can not an ASP.NET app be used in a serverless way?

A serverless application has four steps to execution:

1) An incoming event triggers the initialization of the app. This event may be a HTTP request, a topic message, etc. This event processing is halted whilst the app initializes.
2) The app initializes.
3) The app, now running, processes the event.
4) If there are no incoming events for a certain amount of time, the app can be stopped.

Why does the app have to be an Azure Function app? It could be any kind of app, of any programming language.

**Comment by Ved2806** [comment]
Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by Ved2806** [comment]
Hi @alexandrehtrb, There are few benefits of using azure function app over app service. Azure Function App is a serverless solution that allows you to write less code in a language of your choice. Infrastructure itself will take care of keeping resources up to date as well as deploying and maintaining servers. It is very easy to achieve deployment automation with Azure function app and it also provides as many as or as few as resources needed thus it saves the cost of running your app. 

You may want to read more about function apps [here]( https://docs.microsoft.com/en-us/azure/azure-functions/functions-overview)

Kindly let us know if you found above information useful!

**Comment by alexandrehtrb** [comment]
Hello Sujeet,

I understand how an Azure Function facilitates the creation of an API in many scenarios, such as creating a new endpoint, with only a few lines of code.

Nevertheless, I am suggesting that Azure Functions could accept any kind of application, as what really matters is how the app is triggered and its execution sustained (like I explained in the first comment).

**Comment by TroyWitthoeft** [comment]
@alexandrehtrb It's not _entirely_ clear what you are asking?  It sounds like less of an issue and more of an exploratory discussion?  Could be interesting!  But, not an issue per se.  A practical example of a basic ASP.NET that you want to build into a function would further the discussion.

To ponder on it, you'd probably want to research the history of dotnet.   In particular understanding why MS created  the cross platform ASP.Net Core from the older ASP.net.  And their eventual standardization and onvergence back together in .NET 5.0.  it probably also involves some discussion about the layer where your code interacts with the Azure scale controller and the differences between in and out-of-process apps.

**Comment by alexandrehtrb** [comment]
@TroyWitthoeft , yes, this is more of an exploratory discussion, that I think it fits here.

An example solution is this:

1. We have a reverse proxy that is managed by Azure.
2. When an incoming request reaches this reverse proxy, the reverse proxy will check if the application is running:
- If yes, then redirect the incoming request to this application.
- Otherwise, start the application; once it is started, redirect the request to the application.
3. The reverse proxy monitors for incoming requests; if there are no requests for a certain amount of time, then shutdown the application.

**Comment by Ved2806** [comment]
Hi @alexandrehtrb, The infrastructure that the Azure functions runs on requires the dependencies on both the runtime environment and the same infrastructure components. It essentially require the application to be built and deployed as an Azure functions application as opposed to just a regular ASP net core app.

**Comment by alexandrehtrb** [comment]
I see, @Ved2806 ... Could this change, to support the scenario I described above?

**Comment by alexandrehtrb** [comment]
@Ved2806 I replied and provided Author Feedback

**Comment by Ved2806** [comment]
Hi @fabiocav , Could you please look into this?

**Comment by Ved2806** [comment]
Hi @mattchenderson , Could you please help with this?

**Comment by Ved2806** [comment]
Hi @alexandrehtrb Do you still have queries regarding this? Please let us know can we close this?

**Comment by alexandrehtrb** [comment]
I believe I found something related to what I am suggesting:

https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-other?tabs=rust%2Cwindows

But still, I think this could evolve to something better.
I will close this issue, since this is a suggestion.
