### ISSUE TITLE
What is the ServiceLifetime of ServiceProvider in a Time Trigger Azure Functions

### ISSUE THREAD

**Issue by uttom-akash** [Azure/azure-functions-host#8022]
#### Version info:

- TargetFramework: netcoreapp3.1
- AzureFunctionsVersion: v3

#### Question

I am observing that the `hashCode` of `_serviceProvider`  is the same throughout all the execution of the below function at an interval of 1 min.

```
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Logging;
using System;

namespace TestFunction
{
    public class Function2
    {
        private readonly IServiceProvider _serviceProvider;
        public Function2(IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider;
        }

        [FunctionName("Function2")]
        public void Run([TimerTrigger("0 */1 * * * *")] TimerInfo myTimer, ILogger log)
        {
            var hashCode = _serviceProvider.GetHashCode();
            log.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");
        }
    }
}
```

So, what is the ServiceLifetime of ServiceProvider in a Time Trigger Azure Functions?

**FYI**: I also compared the `hashcode` of `serviceProvider` in an API for two requests but they are different.

**Comment by uttom-akash** [comment]
cc @fabiocav. @madelinegordon

**Comment by Ved2806** [comment]
Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by Ved2806** [comment]
Hi @i-akash,

For a Functions app, the different service lifetimes behave as follows:

Transient: Transient services are created upon each resolution of the service.
Scoped: The scoped service lifetime matches a function execution lifetime. Scoped services are created once per function execution. Later requests for that service during the execution reuse the existing service instance.
Singleton: The singleton service lifetime matches the host lifetime and is reused across function executions on that instance. Singleton lifetime services are recommended for connections and clients, for example DocumentClient or HttpClient instances.

You can also use ServiceLifetime Enum which specifies the lifetime of a service in an IServiceCollection.
[ServiceLifeTime Enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicelifetime?view=dotnet-plat-ext-6.0)

Please let us know if that information is useful.

**Comment by uttom-akash** [comment]
@Ved2806 
My Question was :
If the function executes multiple times, the service provider is always the same.
But when hitting api endpoints multiple times, the service provider is different.

Why?

**Comment by Ved2806** [comment]
Hi @i-akash, Could you please let us know what API you are referring to. Are you talking about API call to be triggered as function?

**Comment by uttom-akash** [comment]
@Ved2806  
I am referring to `Web API with ASP.NET Core` as API here.

**Comment by Ved2806** [comment]
Hi @fabiocav Could you please look into this?

**Comment by Ved2806** [comment]
Hi @i-akash The service lifetime should match the behavior which you found in ASP.NET core. If you continue to run it please let us know. The lifetime of the service provider should match the lifetime of the function execution.

**Comment by uttom-akash** [comment]
@Ved2806 But the lifetime of the service provider is equal to the lifetime of the function. I mean it behaves like a singleton object.
