### ISSUE TITLE
.Net 6 Isolated Function: Unable to resolve service for type 'Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration' while attempting to activate function

### ISSUE THREAD

**Issue by willyt150** [Azure/azure-functions-host#8043]
#### Is your question related to a specific version? If so, please specify:
V4 .Net 6 Isolated
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question
I've created a .Net 6 Isolated HttpTriggered function in Visual Studio 2022

I'm trying to get the TelemetryConfiguration injected, and based on [other issues logged](https://github.com/Azure/azure-functions-host/issues/3741#issuecomment-645964338) and [docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#logging-services) this should NOT be null once my local.settings.json has a value for `APPINSIGHTS_INSTRUMENTATIONKEY`

However, that isn't the case when running locally.

Is there a new way to access it in .Net 6 isolated? Cause this works just fine in my .Net 3.1 functions.

Thanks for your time!

**Comment by v-bbalaiagar** [comment]
Hi @willyt150 , Thank you for your feedback!
Hi @brettsam , Could you please take a look at this issue.

**Comment by lommez** [comment]
@willyt150,

The documentation is wrong.
The right way to inject TelemetryConfiguration is using IOptions interface, like this:

IOptions<TelemetryConfiguration>

**Comment by willyt150** [comment]
thanks @lommez

your example is missing the actual implementation, but I'm familiar with the IOptions<T>, so you pointed me in the correct direction. Thank you again!

so @v-bbalaiagar my issue has been solved, but the docs just need to be updated calling out how to properly retrieve the injected telemetry configuration.
