### ISSUE TITLE
Is headless Chromium supported in Windows Azure functions now?

### ISSUE THREAD

**Issue by JowieXiang** [Azure/azure-functions-host#8046]
Based on this [blog post](https://dev.to/azure/running-headless-chromium-in-azure-functions-with-puppeteer-and-playwright-2fgk) and multiple related issues(#4883, #2417,... ), windows Azure functions does not support headless Chromium. Wondering if there's been any update on this, or is it planned that windows will support this in the future?

We're trying to develop an automated test function using playwright and headless chromium. It would be a real pity to not be able to achieve such task using AF.

**Comment by balag0** [comment]
No, it's still just on Linux. It is possible to run this using a custom image using Windows containers on App service. But this is not a well-supported functions scenario yet (support might come in the future but no timelines yet)

**Comment by JowieXiang** [comment]
> No, it's still just on Linux. It is possible to run this using a custom image using Windows containers on App service. But this is not a well-supported functions scenario yet (support might come in the future but no timelines yet)

Thank you @balag0 , at least we know for sure this won't work now. Looking forward for updates in the future :)
