### ISSUE TITLE
Binding metrics not emitted for in-proc precompiled applications

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#8059]
This is a gap that seems to date back to the initial implementation of direct load (WebJobs loaded Functions), and our FunctionMetadata instance is not fully populated with binding information for that scenario, causing the host to miss metric logging for input and output bindings.

We need to ensure metrics are correctly emitted so we have accurate information for binding usage.

**Comment by kshyju** [comment]
PR with the fix: https://github.com/Azure/azure-functions-vs-build-sdk/pull/542

**Comment by kshyju** [comment]
Sdk.Functions package 4.1.0 which has the fix for this, is now available in nuget gallery.

https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/4.1.0

**Comment by fabiocav** [comment]
Closing as resolved by https://github.com/Azure/azure-functions-vs-build-sdk/pull/542

**Comment by kshyju** [comment]
V3 version of the package with this fix is now available in nuget gallery.

https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/3.1.0
