### ISSUE TITLE
Use MSAL for authentication via Authorization: Bearer token

### ISSUE THREAD

**Issue by shaipetel** [Azure/azure-functions-host#8060]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app, select `Diagnose and solve problems` from the left, and view relevant dashboards before opening your issue.

Securing an azure function (V3) using Microsoft authentication provider and using @azure/msal-browser to authenticate.

The login popup places a 3rd party cookie on the azure function domain and uses that for authentication, and also returns an accessToken.

When 3rd party cookies are blocked - the access token that is passed via a header:
`Authorization: Bearer {accessToken}`

Isn't working, and the request return 401 Unauthorized.

We need to be able to pass authentication using headers, not only 3rd party cookies.

#### Investigative information

Please provide the following:

- Function App version: 3.0.0
- Function App name: https://kwizfuncts.azurewebsites.net
- Function name(s) (as appropriate): /api/posts
- Invocation ID:
- Region: East US2

#### Repro steps

Provide the steps required to reproduce the problem:

1. Run the MSAL authentication using @azure/msal-browser
2. A cookie is placed on the target domain, and accessToken returned.
> everything works!

Option 1:
- Try the same steps using Google Chrome incognito mode, which blocks 3rd party cookies by default
> access denied!

Option 2:
- Run the 2 steps above to get everything working.
- Visit the function in the browser
- Manually delete the cookie "AppServiceAuthSession"
- Make the request again using @azure/msal-browser with the accessToken recieved, sending it in the header
> access denied!
This will now end up in a worst situation, since msal thinks it still has a valid token, don't know that the cookie was deleted on the target domain, and will not even attempt to prompt the user for login again.

#### Expected behavior

Provide a description of the expected behavior.

Sending the accessToken via header:
`Authorization: Bearer {accessToken}`

should authenticate the request.

#### Actual behavior

The header is ignored, and only the 3rd part cookie "AppServiceAuthSession" is being used.

**Comment by v-bbalaiagar** [comment]
Hi @shaipetel , Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by shaipetel** [comment]
@v-bbalaiagar  figured it out.
Its NOT documented - at all.
The key was the following:
1. Do not request a graph scope (User.Read for example - your token will not work since your application doesn't own that scope so it can't verify the token)
2. Have your app registration declare a new app URI, and expose an API (example: app://xxx-xxx/my-own-scope)
3. In your azure function, edit the Microsoft authentication provider, and add app://xxx-xxx as a "allowed token audiences"
4. When requesting a token using MSAL, request ONLY the scope you have set up in step 2

Doing that, sso works, acquire token works, and Bearer token works.
There is ZERO documentation that I found that explains step 3, and step 3 was critical to making this work. Otherwise, again, the token you get would not validate correctly.

**Comment by shaipetel** [comment]
in fact - I've seen many posts online that says Azure Functions do not support authorization bearer authentication.
Not only did I get it to work - but I can now get it working conditionally (so, a function can work both anonymously returning 1 set of results, or if there is an authorization token - the function will get a logged-in user name and may return a different set of results).
