### ISSUE TITLE
BlobTrigger Function App (C#) using Managed Identity

### ISSUE THREAD

**Issue by avnet78** [Azure/azure-functions-host#8062]
We have a C# Blob Trigger Function App. I would like to use the Managed Identity as we don't want to use the connection strings in the configuration.
System Assigned Managed Identity is enabled and Storage Blob Data Owner & Storage Queue Data Contributor roles are assigned to the Function App. I am using nuget package version 5.0.0 for Microsoft.Azure.WebJobs.Extensions.Storage as suggested by @paulbatum & provided the storage account name for the config/app setting entry AzureWebJobsStorage__accountName.

I did everything correctly and followed instructions/comments in the following links:

https://github.com/Azure/azure-functions-host/issues/6423
https://gist.github.com/paulbatum/c301e8ca07b2561db91030a1566383fa

Not sure what am I missing here. 
Please help  @paulbatum or @kasobol-msft.

**Comment by balag0** [comment]
I think we would need the appname to investigate - https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by avnet78** [comment]
Here is the function app info:

UTC execution time: 2022-01-19T01:23:21.673
Execution Id: ab3f8e8a-65e8-432f-aeea-61b9cf530bc7

**Comment by liliankasem** [comment]
> Here is the function app info:
> 
> UTC execution time: 2022-01-19T01:23:21.673 Execution Id: ab3f8e8a-65e8-432f-aeea-61b9cf530bc7

@avnet78  You also need to provide the region :)

**Comment by avnet78** [comment]
UTC execution time: 2022-01-19T01:23:21.673 
Execution Id: ab3f8e8a-65e8-432f-aeea-61b9cf530bc7
Location: West US 2 (PST)

**Comment by avnet78** [comment]
@liliankasem any update?

**Comment by liliankasem** [comment]
Sorry I haven't had time to investigate this. I'll see if this can be assigned during the next sprint

**Comment by colincmac** [comment]
@liliankasem I saw a similar issue when scaffolding a lab to debug an issue. Similar scenario, but local debugging only. However, I've previously encountered issues with the newer Identity based storage account connections with Functions in .NET. I may be able to provide a sample internally if it helps.

**Comment by colincmac** [comment]
Update with more details. Again, I'm only debugging it locally with Visual Studio.
- My user has `Storage Blob Data Owner` & `Storage Queue Data Contributor` assigned at the storage account resource scope.
- Microsoft.Azure.WebJobs.Extensions.Storage 5.0.0
- Microsoft.NET.Sdk.Functions 4.0.1
- .NET 6.0
`
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage__accountName": "mystorageaccount",
    "TestBlob__accountName": "mystorageaccount",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
  }
}
`

Console:
![Logs 1-1](https://user-images.githubusercontent.com/99688332/156599607-3e10816a-e172-4564-8c2c-674d49c92500.PNG)

Insights:
![Logs 1-2_LI](https://user-images.githubusercontent.com/99688332/156601537-5c305ab6-650c-4645-a454-8218991498ac.jpg)

This seems to be the call that's failing:
![image](https://user-images.githubusercontent.com/99688332/156600734-92a142cf-14ec-49e0-90a1-607d0344299c.png)

**Comment by avnet78** [comment]
Thank you @colincmac, we're facing the same issue.

**Comment by colincmac** [comment]
@avnet78 I may have found a workaround. Needs further testing, but it seems to be working. I created a custom role that combines the Storage Blob Data Owner & Storage Queue Data Contributor.  Then I then added these 2 permissions
![image](https://user-images.githubusercontent.com/99688332/156609360-84d17eef-dab3-4310-b606-41ccc07f7391.png)

JSON for the role looked like this in the end

```
{
    "id": "/subscriptions/<my-subscription>/providers/Microsoft.Authorization/roleDefinitions/<random-guid>",
    "properties": {
        "roleName": "Functions Blob Data Owner",
        "description": "Allows a Function app to operate against a Storage Account.\nCombines Storage Blob Data Owner & Storage Queue Data Contributor. Also allows Microsoft.Storage/storageAccounts/blobServices/read.",
        "assignableScopes": [
            "/subscriptions/<my-subscription>"
        ],
        "permissions": [
            {
                "actions": [
                    "Microsoft.Storage/storageAccounts/blobServices/containers/*",
                    "Microsoft.Storage/storageAccounts/blobServices/generateUserDelegationKey/action",
                    "Microsoft.Storage/storageAccounts/queueServices/queues/delete",
                    "Microsoft.Storage/storageAccounts/queueServices/queues/read",
                    "Microsoft.Storage/storageAccounts/queueServices/queues/write",
                    "Microsoft.Storage/storageAccounts/blobServices/read"
                ],
                "notActions": [],
                "dataActions": [
                    "Microsoft.Storage/storageAccounts/blobServices/containers/blobs/*",
                    "Microsoft.Storage/storageAccounts/queueServices/queues/messages/delete",
                    "Microsoft.Storage/storageAccounts/queueServices/queues/messages/read",
                    "Microsoft.Storage/storageAccounts/queueServices/queues/messages/write",
                    "Microsoft.Storage/storageAccounts/queueServices/queues/messages/process/action"
                ],
                "notDataActions": []
            }
        ]
    }
}
```

As a note, I think the issue is with the AzureWebJobsStorage connection, rather than the blob storage extension. Though the docs still mark it as in [preview](https://docs.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial#use-managed-identity-for-azurewebjobsstorage-preview).

**Comment by avnet78** [comment]
Thank you @colincmac, please keep me posted on the workaround.

**Comment by liliankasem** [comment]
@colincmac if you do have a repro you can share that would be helpful! From what I'm reading here it sounds like blob requests are failing due to permissions errors, despite the managed identity having the correct storage permissions/scope assigned?

cc: @mattchenderson @balag0 in case they have more info on this

**Comment by colincmac** [comment]
That is correct. I can clean it up and push something up tomorrow. Everything is working now with the updated permissions in the custom role, even when published in a Linux consumption plan.

**Comment by avnet78** [comment]
@colincmac I tried creating a custom role with the same set of permission you had under actions and dataactions. I initially tested it against a couple of existing BlobTrigger based FunctionApps and it worked.

But I added the same role to another FunctionApp which also uses BlobTrigger but strangely when I copy a data file into the blob it doesn't fire. I am not really sure why it isn't working with this particular function app.

Almost all of our Function apps are BlobTrigger based. I see that 2 are working but the one I tested earlier didn't work. I will test the others and keep you posted.

**Comment by avnet78** [comment]
@colincmac Sorry, my bad. I didn't realize that the 3rd Function App I tested wasn't referencing version 5.x of Microsoft.Azure.WebJobs.Extensions.Storage
It works like a charm after I installed the Microsoft.Azure.WebJobs.Extensions.Storage v 5.0 nuget package.

**Comment by liliankasem** [comment]
@avnet78 sounds like you were able to solve the issue? Going to close for now but feel free to reopen if still experiencing this issue.

**Comment by avnet78** [comment]
Yes, the issue is resolved. You may close it.

Thanks!
