### ISSUE TITLE
Please improve access the ApplicationSettings in out of proc azure functions.

### ISSUE THREAD

**Issue by sonic1981** [Azure/azure-functions-host#8063]
#### What problem would the feature you're requesting solve? Please describe.
I need to be able to access some values that another service are adding to `ApplicaionSettings` on an Azure Service Bus. There is no simple way to do this in an out of proc service. I have (after much digging discovered the following code will allow me to access this information:

```c#
IReadOnlyDictionary<string, object> bindingData = context.BindingContext.BindingData;

if (bindingData.ContainsKey("UserProperties") == false)
{
    throw new Exception("Service bus message is missing UserProperties binding data");
}

string userPropertiesStr = bindingData["UserProperties"].ToString();
if (string.IsNullOrEmpty(userPropertiesStr))
{
    throw new Exception("UserProperties is null or empty");
}

JsonDocument json = JsonDocument.Parse(userPropertiesStr);
JsonElement xProp = json.RootElement.GetProperty("x");
string x = serializationProp.GetString();
```
[See my SO question](https://stackoverflow.com/questions/70709823/how-can-i-access-the-applicationproperties-of-a-service-bus-message-in-a-azure-f)

But really, this should be a LOT easier?
#### Describe the solution you'd like
why not just expose a dictionary of `ApplicaionSettings` in the `FunctionContext`? Then that code could be simplified to:

```c#
string x = context.ApplicaionSettings["x"];
```

#### Describe alternatives you've considered
[See my SO question](https://stackoverflow.com/questions/70709823/how-can-i-access-the-applicationproperties-of-a-service-bus-message-in-a-azure-f)

**Comment by v-bbalaiagar** [comment]
Hi @sonic1981 , Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by sonic1981** [comment]
I'm moved this to the correct repo https://github.com/Azure/azure-functions-dotnet-worker/issues/782
