### ISSUE TITLE
SNI.dll not found by runtime, in the wrong directory

### ISSUE THREAD

**Issue by tgriff** [Azure/azure-functions-host#8064]
(Note that I posted this issue over in [Azure/Azure-Functions](https://github.com/Azure/Azure-Functions/issues/2141) but haven't gotten any traction there so trying here. Also note that I've seen other issues regarding SNI.dll but haven't seen anything that exactly describes or resolves my issue.)

I have an Azure Functions app using SDK version 1.0.38. It consumes other projects in my solution, some of which are using Entity Framework Core 3 (they are all targeting .Net Framework 4.8.1). This means it has a dependency on Microsoft.Data.SqlClient (1.0.19269.1) which also as a dependency on SNI.dll (1.0.19235.1).

At runtime, I am getting the following exception:
`Microsoft.Data.SqlClient: The type initializer for 'Microsoft.Data.SqlClient.TdsParser' threw an exception. Microsoft.Data.SqlClient: The type initializer for 'Microsoft.Data.SqlClient.SNILoadHandle' threw an exception. Microsoft.Data.SqlClient: The type initializer for 'Microsoft.Data.SqlClient.SNINativeMethodWrapper' threw an exception. Microsoft.Data.SqlClient: Failed to load <project path>\bin\Debug\net48\bin\x86\SNI.dll.`

According to this message, the runtime is looking for SNI.dll under `net48\bin\x86` rather than under `net48\x86` where it actually resides. The path `net48\bin\x86` does not exist.

I am able to resolve this locally by adding the following "post-build" event to my .csproj:
`<Target Name="FixSNILocation" AfterTargets="CopySNIFiles">`
`<Exec Command="mkdir $(TargetDir)\bin\x86&#xD;&#xA;copy /Y $(TargetDir)\x86\SNI.dll $(TargetDir)\bin\x86\SNI.dll" />`
`</Target>`

Unfortunately, I am having issues when it comes time to "officially" build and publish the project. The project is built in an ADO pipeline using the [Visual Studio Build task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/visual-studio-build?view=azure-devops). While the copy command in my .csproj works correctly, SNI.dll is not being added to the correct location (`net48\bin\<arch>`) in the resulting <projectName>.zip file. Right now I'm working around it with some tasks to extract the zip file, copy the x86 and x64 binaries to the correct location, then re-zipping it.

So I've managed to work around this issue, but it's fragile and I'm hoping there's a better solution. Any idea why the SNI.dll binary gets put in the "wrong" location during the build? Is there a better way I can solve this?

### Investigative information

- Timestamp: 2022-01-14T16:16:02.328Z
- Function App version: ~1
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: 0acc286b-6666-4ac5-9daa-7c97bb049c43
- Region: West US

#### Repro steps

Provide the steps required to reproduce the problem:

1. Azure Functions app v1
2. Create a function that uses EFCore3 (and thereby has a dependency on Microsoft.Data.SqlClient and SNI).
3. Build and run the app.

#### Expected behavior

The function runs successfully (including the code that relies upon EFCore3) without having to do any extra post-build steps.

#### Actual behavior

When the function runs code that relies upon EFCore3 you will get the exception I mention above.

#### Known workarounds

1. Add a post-build event to copy SNI.dll from `net48\<arch>` to `net48\bin\<arch>`.
2. If using an ADO build pipeline, add tasks to unzip the published zip file, copy SNI.dll to the correct location, and then re-zip it.

#### Related information 

Provide any related information 

* Programming language used: C#
* Links to source: Contact me privately, please.
* Bindings used

**Comment by Ved2806** [comment]
Closing this issue as it is duplicate one. Please follow this [link](https://github.com/Azure/Azure-Functions/issues/2141) for more updates.
