### ISSUE TITLE
Access service provider during startup

### ISSUE THREAD

**Issue by dxynnez** [Azure/azure-functions-host#8068]
#### Question
Hi team,

I would like to know if there is a way to access the IServiceProvider during function startup? In asp.net core you would be able to access it in the Startup's Configure method, or, in a [startupfilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.istartupfilter?view=aspnetcore-3.1); but function startup seems to only expose the DI functionality.

Our use case is that, we need to perform certain operation during function startup, and block it until the operation completes. For some of the operations we want to be able to use the instances that have been registered in the DI container.

**Comment by Ved2806** [comment]
Thank you for the feedback! We will check for the possibilities internally and update you with the findings.

**Comment by Ved2806** [comment]
Hi @dxynnz, The IServiceProvider is not build during the function startup and you won't be able to use it in registration path. there is no provider that has been build yet. If you are trying to build the provider from the a builder, you may have services in the partial state and not all of them will be registered.  It would be helpful if you could let us know, what you are attempting to do here?

**Comment by dxynnez** [comment]
Hi @Ved2806  - Avoid manually building the provider is exactly what we are trying to avoid. But still, we need to perform some operation (ensure DB is in a valid state and some other sanity check) before the function starts to take traffic.

Is there any hook that we can hook up this type of operations? I was googling around and [a thread on SO](https://stackoverflow.com/questions/46553687/azure-function-run-code-on-startup) suggested to use the IExtensionConfigProvider but I feel like it's pretty hacky and according to the doc our use case doesn't seem to be what the interface was intended for.

**Comment by dxynnez** [comment]
Hi @Ved2806, is there any update on this?

**Comment by Ved2806** [comment]
Hi @kshyju  Could you please help with this?

**Comment by dxynnez** [comment]
Hi @Ved2806 / @kshyju , just checking up - is it something doable in azure functions?

**Comment by dxynnez** [comment]
Hi @Ved2806 / @kshyju  just trying my luck one more time to see if there is anything you could share with me... Thanks.

**Comment by kshyju** [comment]
@dxynnez It is not currently supported out of the box.
