### ISSUE TITLE
Cannot manipulate req.HttpContext.Response locally

### ISSUE THREAD

**Issue by bjornharrtell** [Azure/azure-functions-host#8080]
The trick described in https://stackoverflow.com/questions/67301743/how-to-return-stream-of-data-from-azure-function-http which can be used to for example stream the response works when deployed at Azure but locally it fails with:

[2021-12-26T20:59:57.885Z] An unhandled host error has occurred.
[2021-12-26T20:59:57.885Z] Microsoft.AspNetCore.Server.Kestrel.Core: Headers are read-only, response has already started.

I'm running azure-functions-core-tools 4.0.3971 on Ubuntu and dotnet sdk 6.0.

**Comment by liliankasem** [comment]
@bjornharrtell is this still happening with the latest core tools version?

@v-bbalaiagar can you do some initial investigation on this issue?

**Comment by bjornharrtell** [comment]
@liliankasem yes just tried it and same error. I'm now on Ubuntu 22.04 with azure-functions-core-tools-4 4.0.3971-1 and 6.0.300.

**Comment by bjornharrtell** [comment]
Just realized I didn't have the latest core tools because it's not yet in a feed for Ubuntu 22.04.. I've manually updated to 4.0.4483-1 which appears to be the latest version and the issue remains.

**Comment by liliankasem** [comment]
We'll need to take a look to see why it's working in Azure and not locally, in the meantime would something like this fix the issue for local testing?

```csharp
[FunctionName("HttpTrigger")]
public async Task<HttpResponseMessage> Run(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
    ILogger log)
{
        var stream = new MemoryStream(Encoding.UTF8.GetBytes("{\"hello\":\"world\"}"));
        var responseContent = new StreamContent(stream);
        responseContent.Headers.ContentType = MediaTypeHeaderValue.Parse("application/json-data-stream");

        return new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = responseContent
        };
}
```

**Comment by bjornharrtell** [comment]
@liliankasem indeed that way of doing it does work locally, thanks!

**Comment by fabiocav** [comment]
Closing as answered.
