### ISSUE TITLE
Feature request: Support other IoC containers

### ISSUE THREAD

**Issue by biltongza** [Azure/azure-functions-host#8095]
This is a dupe of #4410 but that issue is locked and I want to start the conversation again.

Azure functions V1 didn't support dependency injection, so when we built our functions against it way back when, we opted to use the service locator pattern because we wanted DI, which gave us the opportunity to make use of Castle Windsor interceptors.

That has since become a core part of how our functions work.

We hoped to be able to use the built in DI that ships with Azure Functions since v2 to get rid of the service locator pattern, but we are not aware of a way for us to use interceptors with it, so we are still stuck with it :(

There is a comment showing a workaround, which is to implement `IJobActivatorEx`, but the response to that says it is an unsupported scenario since that's essentially running under a new runtime.

If fully supporting other IoC containers is not possible, then support for more features in the DI framework (such as interceptors) is a good path forward, except I believe the built in DI was not built for this kind of scenario.

If there could be a specification of what `IJobActivatorEx` needs to do to get to an equivalent to the built in DI runtime, perhaps the community can come up with its own solutions to the problem, and MS wouldn't need to directly support it (though I can imagine there would be issues logged here about it anyway).

**Comment by Ved2806** [comment]
Hi @fabiocav , Could you please look into this?

**Comment by Ved2806** [comment]
Hi @fabiocav This is something what you have already answered and closed the issue [#4410](https://github.com/Azure/azure-functions-host/issues/4410). User has initiated this conversation again. Could you please help with this?

**Comment by fabiocav** [comment]
@biltongza the recommendation here is to use the[ .NET Isolated model](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide). That will give you the flexibility to use any IoC framework.
