### ISSUE TITLE
System.Private.Uri: Invalid URI: The hostname could not be parsed

### ISSUE THREAD

**Issue by KirylZotkin** [Azure/azure-functions-host#8097]
At times I see that weird error message when I come to the portal to check on my functions app - **"System.Private.Uri: Invalid URI: The hostname could not be parsed"**. Plus **Runtime version** field on UI says **"Error"**. It happens usually few hours after function starts up. No errors in logs other than "409 There is already a lease present" which seems to be ok. 

I also have a separate app that pushes a message into the topic that the Function App listens to each 30 sec. The code in the function completes these messages upon arrival. At first it works as expected and I see function triggered twice per min and active messages in the topic are close to 0, but then it just stops processing the messages. And at this point if I go to check my function I'd see the error.

![image](https://user-images.githubusercontent.com/25956066/150971561-10c7518c-8032-4af8-8d8e-bbe391d42679.png)

**Details:**

**Platfrom**: windows, x64
**Runtime version**: 3.3.1.0
**Runtime stack**: .net 3.1
**Plan**: Consumption
**Region**: France Central

**Trigger looks like this -**

```
public async Task Run([ServiceBusTrigger("***",
            "***",
            Connection = "ConnectionString",
            IsSessionsEnabled = true)]ServiceBusReceivedMessage[] messages,
            ILogger log,
            ServiceBusMessageActions messageActions)
```

**Libs** -

```
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.20" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.2.0" />
```

Host.json -

```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    },
    "logLevel": {
      "default": "Error",
      "Function": "Information"
    }
  },
  "extensions": {
    "serviceBus": {
      "prefetchCount": 100,
      "maxMessages": 100,
      "maxConcurrentCalls": 16,
      "maxConcurrentSessions": 8,
      "sessionIdleTimeout": "00:00:10",
      "maxAutoLockRenewalDuration": "00:05:00",
      "autoCompleteMessages": false,
      "maxMessageBatchSize": 100,
      "messageHandlerOptions": {
        "autoComplete": false,
        "maxConcurrentCalls": 16,
        "maxAutoRenewDuration": "00:05:00"
      },
      "sessionHandlerOptions": {
        "autoComplete": false,
        "messageWaitTimeout": "00:00:10",
        "maxAutoRenewDuration": "00:05:00",
        "maxConcurrentSessions": 8
      },
      "batchOptions": {
        "maxMessageCount": 100,
        "operationTimeout": "00:00:05",
        "autoComplete": false
      }
    }
  }
}
```

#### Known workarounds

If I go and do something in the portal related to the app, like open its Log stream, the error disappears like in a minute or so, and all messages that were stuck would finally get processed -

![image](https://user-images.githubusercontent.com/25956066/150969581-d189b922-0d2f-4994-aaaf-0533cf576ffe.png)

**Comment by Ved2806** [comment]
Thank you for the feedback! We will check for the possibilities internally and update you with the findings.

**Comment by KirylZotkin** [comment]
any update?

**Comment by Ved2806** [comment]
Hi @KirylZotkin Could you please provide the following information to investigate this further?
Function App name, Region and timestamp.

**Comment by KirylZotkin** [comment]
Function App name: wlm-dev-media-functions
Region: France Central
timestamp: based on the screenshot above it's 2022-01-25T10:08:35

P.S. I've already updated the function to use Linux host but I still see the same errors/same behavior like at this very moment (09:57 UTC). New function name is wml-dev-media-functions

**Comment by cheenamalhotra** [comment]
**Update**: I was able to resolve this error by ensuring Startup function succeeds, there was an issue due to invalid keyvault properties.

-------

This is happening in East US region as well. Seems to be related to WEBSITE_RUN_FROM_PACKAGE - if I remove this config, functions go away, but SCM host starts to work.

Would appreciate a workaround pls?

```
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.5.0" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.23.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.1.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.8" /> 
```

Tried with all "Microsoft.NET.Sdk.Functions" versions "3.0.8" - "3.0.13", but couldn't get this working.

**Comment by satvu** [comment]
Closing as resolved
