### ISSUE TITLE
Azure functions and AzureWebSecretStorageType

### ISSUE THREAD

**Issue by csalgo70** [Azure/azure-functions-host#8113]
##### Version information

**dotnet version**: 6.0.101
**Azure Functions Version**: 4.0.3971

#### Repro steps

**Objective:** Make the function host use a KeyVault to store host and function keys instead of using azure-webjobs-secrets container in storage.

1. Create and publish a simple functions app.
2. Create a keyvault.
3. In App settings under Configuration for the function app set the following variables

- AzureWebJobsSecretStorageKeyVaultName ( not sure if this is still relevant but tried setting this too )
- AzureWebJobsSecretStorageKeyVaultUri ( set this to the uri )
- AzureWebSecretStorageType ( set this to "keyvault" ) 

4. Create managed identity for the functions app.
5. In the KeyVault add access policy and pick the managed identity of the function app and give permissions to read / write to key vault secrets.

#### Expected behavior

I expected any new keys added would now use keyvault instead of azure-webjobs-secrets container in storage.

#### Actual behavior

Its not using the keyvault at all. It continues to update host.json file in azure-webjobs-secrets container of the storage.

#### Related information 

Provide any related information 

* Programming language used C#

**Question:**

 What am I doing wrong ?

**Comment by kashimiz** [comment]
Hi @csalgo70,

Are you trying to use KeyVault with a user-assigned managed identity to store function keys? For that scenario, these are the settings/steps required - it looks like you're missing the `AzureWebJObsSecretStorageKeyVaultClientId` setting:

<html>
<body>
<h5 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 0.875em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">User-assigned managed identity</h5><ul dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;">Create a user-assigned managed identity</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Assign the user managed identity to your Functions App</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Give the created identity Key Vault secret permissions through access policies</li></ul>

App Setting | Value
-- | --
AzureWebJobsSecretStorageType | keyvault
AzureWebJobsSecretStorageKeyVaultUri | Key Vault URI
AzureWebJobsSecretStorageKeyVaultClientId | User managed identity client ID


</body>
</html>

Required settings for this and other scenarios (ex. AAD) are covered in the related breaking change issue: https://github.com/Azure/Azure-Functions/issues/2048

@anthonychu @ggailey777 It looks like these settings aren't documented in Docs' [app settings reference](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurewebjobssecretstoragetype); can we create a work item to add them? Perhaps a mention on the [Use Key Vault references](https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references) page as well (or somewhere in the Secure App section) as that's the first result I get searching "azure functions keyvault secrets", "azure functions secret management", etc.

**Comment by ggailey777** [comment]
@kashimiz it looks like we missed adding those new settings to the reference article. I've opened [1915470](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1915470) to track internally. Thanks! 
\+ @mattchenderson

**Comment by kannanMSFT** [comment]
Actually, I was trying to use system managed identity

**Comment by csalgo70** [comment]
Actually I was trying to use system managed identity. So the following should have worked based on the note but its not working in my case.

<html>
<body>
<h5 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 0.875em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">System-assigned managed identity</h5><ul dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;">Enabled system managed identity inside your Functions App</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">Give the created identity Key Vault secret permissions through access policies</li></ul>

App Setting | Value
-- | --
AzureWebJobsSecretStorageType | keyvault
AzureWebJobsSecretStorageKeyVaultUri | Key Vault URI


</body>
</html>

**Comment by kannanMSFT** [comment]
Any update on this ?

**Comment by liliankasem** [comment]
@csalgo70 I followed the same steps mentioned and was not able to repro. I'm seeing the host secrets inside the Key Vault and every time I renew a function key or host master key, the Key Vault is getting updated with the latest secret value. I can see that the host.json and functionname.json files still exist inside of the `azure-webjobs-secrets` container but have **not** been updated since setting up the system managed identity.

Here are the steps I took:

1. Create and deploy a new Function App (dotnet 6, v4, windows consumption)
1. Create a Key Vault
1. In the Function App, navigate to the Identity tab in the portal, turn on system assigned and copy the Object (principal) ID
1. Open the Key Vault and navigate to Access Policies
1. Add Access Policy -> Select the Secret Management template -> Select principal -> search for the system-assigned principal created in step 3
1. Save the new access policy that was just created
1. Navigate to the Overview tab and copy the Vault URI
1. Open the Function App again and navigate to Configuration
1. Add the following app settings and save

App Setting | Value
-- | --
AzureWebJobsSecretStorageType | keyvault
AzureWebJobsSecretStorageKeyVaultUri | [Your Key Vault URI]

If you go back to the KeyVault and open the Secrets tab, you should be able to see the Function App secrets:

![Screen Shot 2022-02-23 at 4 41 35 PM](https://user-images.githubusercontent.com/2198905/155435070-656aebef-6dfb-4078-9d09-a5e689a39849.png)
