### ISSUE TITLE
Retry attributes not working with v3 Function, .NET 5, dotnet-isolated, EventHub trigger

### ISSUE THREAD

**Issue by josh-endries** [Azure/azure-functions-host#8116]
I have a v3, .NET 5, dotnet-isolated, EventHub trigger Function for which I am trying to enable retry behavior. I can get it to work locally via the `host.json` file (haven't tried `host.json` deployed yet), but not via C# attributes. Using C# attributes doesn't work deployed or local. Neither fixed delay nor exponential backoff seem to work. I've tried attributing both the class and method. When I run it this way, it receives the event(s), fails, and then just sits there.

function code (from working `host.json` attempt):

    //[FixedDelayRetry(5, "00:00:05")]
    public class MyFunction
    {
        public MyFunction(
            ILogger<MyFunction> logger
        )
        {
            Logger = logger;
        }

        [Function("MyFunction")]
        //[ExponentialBackoffRetry(10, "00:00:05", "00:05:00")]
        public async Task Run(
            [EventHubTrigger("%EventHubName%", Connection = "EventHubConnectionString", ConsumerGroup = "%ConsumerGroupName%")]
            string[] events
        )
        {
            Logger.LogInformation(string.Join(", ", events));
            await Task.Delay(5000);
            throw new Exception();
        }
    }

local.settings.json:

	{
		"Values": {
			"FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
                        ...app settings...
		}
		"IsEncrypted": false
	}

host.json:

	{
		"version": "2.0",
		"logging": {
			"applicationInsights": {
				"samplingSettings": {
					"isEnabled": true,
					"excludedTypes": "Request"
				}
			}
		},
		"extensions": {
			"eventHubs": {
				"batchCheckpointFrequency": 1,
				"eventProcessorOptions": {
					"maxBatchSize": 1024
				},
				"initialOffsetOptions": {
					"type": "fromEnd"
				}
			}
		},
		"retry": {
			"strategy": "fixedDelay",
			"maxRetryCount": 5,
			"delayInterval": "00:00:05"
		}
	}

csproj:

    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
        <AzureFunctionsVersion>v3</AzureFunctionsVersion>
        <OutputType>Exe</OutputType>
        <Version>1.0</Version>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>CS1573;CS1591;CS1712;CS8600;CS8601;CS8602;CS8603;CS8604;CS8618;CS8619;CS8620;CS8625;CS8765;CS8766</WarningsAsErrors>
      </PropertyGroup>
      <ItemGroup>
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.EventHubs" Version="4.3.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" OutputItemType="Analyzer" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.6.0" />
        <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.30" />
        <PackageReference Include="Microsoft.ApplicationInsights" Version="2.19.0" />
      </ItemGroup>
      <ItemGroup>
        <ProjectReference Include="..\MyLibrary.csproj" />
      </ItemGroup>
      <ItemGroup>
        <None Update="host.json">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="local.settings.json">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
          <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </None>
      </ItemGroup>
    </Project>

output header:

    Azure Functions Core Tools
    Core Tools Version:       3.0.3904 Commit hash: c345f7140a8f968c5dbc621f8a8374d8e3234206  (64-bit)
    Function Runtime Version: 3.3.1.0

**Comment by josh-endries** [comment]
I had a colleague try it as well and they got the same result, so it doesn't seem to be my local environment.

**Comment by hezite** [comment]
doesn't work for .net 6.0 core either:(

**Comment by lukehanlon** [comment]
I can also confirm this doesn't work for me either, .Net 6.0 Isolated, Functions v4 with CosmosDb trigger, so incredibly frustrating.

**Comment by kshyju** [comment]
See [this](https://github.com/Azure/azure-functions-dotnet-worker/issues/832).

In short, dotnet isolated do not support the attribute usage for retry. You have to use the host.json approach.

**Comment by kshyju** [comment]
Closing as answered, but please let us know if you have any additional questions/issues.
