### ISSUE TITLE
Injecting CancellationToken to Queue-Triggered functions causes exception in dotnet isolated processes - Azure Functions V4, .NET 6.0

### ISSUE THREAD

**Issue by Arash-Sabet** [Azure/azure-functions-host#8120]
Please have a look at the following function implementation:

```cs

public class NotificationSender
{
   private readonly ILogger<NotificationSender> _logger;

   public NotificationSender(ILogger<NotificationSender> logger) => (_logger) = (logger);

    [Function("Notifier")]
    public Task NotifyAsync([QueueTrigger("notifications")]string messagePayload)
    {
		_logger.LogInformation($"Notification received: {messagePayload}");
		return _Task.CompletedTask;
    }
}
```

The C# project's definition is per the following entry and `"FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"` is in `local.settings.json` file.

```xml
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.6.0"/>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0"/>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13"/>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.14.0"/>
    <PackageReference Include="Monitoring.Authentication" Version="0.0.0.2"/>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" Version="5.0.0"/>
  </ItemGroup>
```

This function runs well when a message is added to the Azure Storage Queue. We'd like to leverage `CancellationToken` and therefore modified the function per the following code:

```cs
 [Function("Notifier")]
 public Task NotifyAsync([QueueTrigger("notifications")]string messagePayload, CancellationToken cancellationToken)
 {
    _logger.LogInformation($"Notification received: {messagePayload}");
    return _Task.CompletedTask;
 }
```

Once a message is pushed the queue, this function is triggered and produces the following error message:

> [2022-02-05T20:48:06.049Z] Executed 'Functions.Notifier' (Failed, Id=11ce9e72-6ddb-4dcd-8ae0-e13f36849055, Duration=148ms)
> [2022-02-05T20:48:06.049Z] System.Private.CoreLib: Exception while executing function: Functions.Notifier. System.Private.CoreLib: Result: Failure
> [2022-02-05T20:48:06.049Z] Exception: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
> [2022-02-05T20:48:06.049Z]  ---> System.NullReferenceException: Object reference not set to an instance of an object.
> [2022-02-05T20:48:06.049Z]    at lambda_method2(Closure , NotificationSender , Object[] )
> [2022-02-05T20:48:06.049Z]    at Microsoft.Azure.Functions.Worker.Invocation.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker.Core\Invocation\VoidTaskMethodInvoker.cs:line 22
> [2022-02-05T20:48:06.049Z]    --- End of inner exception stack trace ---
> [2022-02-05T20:48:06.049Z]    at System.Threading.Tasks.Task`1.get_Result()
> [2022-02-05T20:48:06.049Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
> [2022-02-05T20:48:06.049Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
> [2022-02-05T20:48:06.049Z]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
> [2022-02-05T20:48:06.049Z] --- End of stack trace from previous location ---
> [2022-02-05T20:48:06.049Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> [2022-02-05T20:48:06.049Z] --- End of stack trace from previous location ---
> [2022-02-05T20:48:06.049Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
> [2022-02-05T20:48:06.049Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 16
> [2022-02-05T20:48:06.049Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 167
> [2022-02-05T20:48:06.049Z] Stack:    at System.Threading.Tasks.Task`1.get_Result()
> [2022-02-05T20:48:06.049Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
> [2022-02-05T20:48:06.049Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
> [2022-02-05T20:48:06.049Z]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
> [2022-02-05T20:48:06.049Z] --- End of stack trace from previous location ---
> [2022-02-05T20:48:06.049Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> [2022-02-05T20:48:06.049Z] --- End of stack trace from previous location ---
> [2022-02-05T20:48:06.049Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
> [2022-02-05T20:48:06.049Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 16
> [2022-02-05T20:48:06.049Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 167.
> [2022-02-05T20:48:06.053Z] Message has reached MaxDequeueCount of 5. Moving message to queue 'notifications-poison'.

**Comment by v-bbalaiagar** [comment]
Hi @Arash-Sabet , Thank you for your feedback. This issue is relating to an issue which is already being tracked and the updates will be given there - https://github.com/Azure/azure-functions-dotnet-worker/issues/180

Closing this issue here. Please find the space for further updates.
