### ISSUE TITLE
Reference Function Keys from Key Vault

### ISSUE THREAD

**Issue by saikatguha** [Azure/azure-functions-host#8121]
I am using *Function Keys* for authenticating certain webhook integrations.

I would like to store the actual key in Azure Key Vault so I can manage and rotate these keys inside AKV using tooling built for AKV, and have the various Azure services pick up the updated keys.

Currently, Key Vault references are supported in Application *Settings* where I can reference a AKV secret. However, there are not supported for Function Keys.

**Feature request: Support AKV references in Function Keys.**

Current functionality: AKV references are supported here:
![image](https://user-images.githubusercontent.com/308774/152692266-d5c27d31-0778-4981-b55f-b3ede9d47b2a.png)

Lacking feature: However, AKV references are _not_ supported here:
![image](https://user-images.githubusercontent.com/308774/152692303-3401c62d-05f6-45ce-99cb-fdb9698f265a.png)

**Comment by Ved2806** [comment]
Hi @mattchenderson Could you please look into this?

**Comment by mattchenderson** [comment]
Please see: https://learn.microsoft.com/en-us/azure/azure-functions/security-concepts?tabs=v4#secret-repositories
