### ISSUE TITLE
Cannot swap slots with different function runtime versions

### ISSUE THREAD

**Issue by dxynnez** [Azure/azure-functions-host#8123]
Hi team,

We are migrating our function apps from .netcore 3.1 to .net 6.0 and would love to do this without downtime if it's at all possible.

We first deployed .net 6.0 compatible binaries to staging slot and changed the FUNCTIONS_EXTENSION_VERSION on it from ~3 to ~4 and then performed a swap. But the swap failed with message:
``
'Failed swapping site. Error: Cannot swap slots for site 'cpc-fn-hello-int-int01' because the application initialization in 'staging' slot either took too long or failed. Please check AppInit module configuration or try using swap with preview if application initialization time is very long.'
``

If I first changed the FUNCTIONS_EXTENSION_VERSION on the production slot to ~4 then the swap would succeed, but apparently this would introduce downtime.

Is it something by design? If so, is there any other way to do this without downtime?

Thanks in advance!

**Comment by v-bbalaiagar** [comment]
Hi @dxynnez , Thank you for your feedback! Similar scenarios were tracked earlier as mentioned here - https://github.com/Azure/Azure-Functions/issues/2118

Also, here is a blog post which addresses similar scenario where the blog talks about deployment slot swap failures and how to fix them - https://ruslany.net/2017/11/most-common-deployment-slot-swap-failures-and-how-to-fix-them/

Please check and let us know if this helps.

**Comment by dxynnez** [comment]
@v-bbalaiagar thanks for linking the issue! Yes that's exactly what happened to us. The underlying problem seems to be that any config ends with _EXTENSION_VERSION is indeed slot-sticky. In that case, what would be the alternative to upgrade functions without causing downtime?

The blog post isn't that much useful though (probably also outdated).

**Comment by dxynnez** [comment]
Hi @v-bbalaiagar , any update on this?

**Comment by v-bbalaiagar** [comment]
Hi @dxynnez ,Team is investigating on the issue. Issue [2118](https://github.com/Azure/Azure-Functions/issues/2118) is a tracking issue and the updates will be given there.

**Comment by v-bbalaiagar** [comment]
Closing this issue as this is already being tracked and updates will be given there - https://github.com/Azure/Azure-Functions/issues/2118
