### ISSUE TITLE
Function from referenced assembly is not exposed   in hosting app

### ISSUE THREAD

**Issue by jvmlet** [Azure/azure-functions-host#8134]
Consider `FunctionApp` project that references  `FunctionLib` project.

`FunctionLib` has `HTTTrigger` function :

````c#
      [FunctionName("MyHttpTrigger")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", Route = null)] HttpRequest req,
            ILogger log)
        {
            return new OkObjectResult("Hello");
        }
````
When I run `FunctionApp`, the `MyHttpTrigger` function  is not exposed.
If manually copy the generated  `FunctionLib\bin\debug\net5.0\MyHttpTrigger\function.json`  to  `FunctionApp\bin\debug\net5.0\MyHttpTrigger\function.json` and rerun the `FunctionApp` I can invoke the function via `http://localhost:7071/api/MyHttpTrigger`

Please advise
Thanks

**Comment by jvmlet** [comment]
Please support functions from referenced nuget package as well.

**Comment by Ved2806** [comment]
Hi @kshyju @fabiocav Could you please look into this?

**Comment by surgupta-msft** [comment]
Hi @jvmlet The other [issue ](https://github.com/microsoft/DurableFunctionsMonitor/issues/18)linked above seems to have been closed. Are you still looking for our assistance here? If yes, can you please review if the discussion here talks about the similar problem? - https://stackoverflow.com/questions/38276838/azure-webjobs-no-functions-found-in-another-assembly
