### ISSUE TITLE
Azure Functions Script (.csx) support for .NET 6

### ISSUE THREAD

**Issue by j2jensen** [Azure/azure-functions-host#8146]
#### What problem would the feature you're requesting solve? Please describe.
Any attempt I've made to target a framework other than `netstandard2.0` in Azure Scripts yields cryptic warnings and errors when referencing Nuget packages, as detailed in [this StackOverflow post](https://stackoverflow.com/questions/71119692/can-an-azure-functions-script-csx-target-net-6).

#### Describe the solution you'd like
- If frameworks outside of `netstandard2.0` _are not_ supported, the runtime should clearly indicate that with an error when the `function.proj` file sets an unsupported target.
- If frameworks outside of `netstandard2.0` _are_ supported, then I need help understanding why I'm getting the errors I'm seeing, and what steps are required to get, say, .NET 6, working.
- In either case, the [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp) should be updated. (Do I need to file a separate issue [here](https://github.com/azure/azure-functions/issues/new) for that?

#### Describe alternatives you've considered
Lack of modern framework support makes me think I should be using Azure Function C# Libraries instead. Again, the documentation should make this limitation clear so developers don't go down the csx road a ways before realizing it's a dead-end.

#### Additional context
I've been getting the general impression that Azure Functions Scripts is a forgotten/stale technology. I'm frequently finding suggestions about how to do things like leverage `IHttpClientFactory` in Azure Functions (to avoid socket starvation and stale DNS problems), and how to leverage dependency injection in Azure Functions, only to discover that none of it works in Azure Functions Scripts. I'm wondering if I should recommend that our teams not bother with Scripts, even for relatively simple scripts.

**Comment by Ved2806** [comment]
Thank you for the feedback! We will check for the possibilities internally and update you with the findings.

**Comment by Ved2806** [comment]
[ Issue 2063](Azure/azure-functions-dotnet-worker#816) is a tracking issue and the updates will be given there, closing this issue as duplicate.

**Comment by j2jensen** [comment]
@Ved2806 with all respect, the issue you linked has no apparent relation to this one, besides a vague reference to socket exhaustion. It is not a duplicate.

**Comment by v-bbalaiagar** [comment]
Hi @j2jensen , Apologies for the confusion, I have updated the issue link in the above comment. We shall keep the issue open and will investigate this further and update you with the findings.

**Comment by Ved2806** [comment]
Hi @j2jensen , Have you resolved this issue yet or is it still there?

**Comment by j2jensen** [comment]
Sorry I didn't respond sooner. @Ved2806 no, this issue has not been resolved. There is still no documentation indicating whether .NET 6 is supported in csx files, and I have not found any workaround for the issues mentioned in the StackOverflow post I linked.

**Comment by j2jensen** [comment]
@Ved2806 is there any way to get this re-opened, or would I need to create a new issue to report that this has not been addressed?

**Comment by Ved2806** [comment]
Hi @anthonychu Could you please look into this issue?

**Comment by anthonychu** [comment]
@fabiocav @mattchenderson

**Comment by chinazor-allen** [comment]
Following. Would be nice to know the workaround for csx files using .NET 6.
