### ISSUE TITLE
WebJob SDK doesn't meet ApplicationInsights-dotnet issue #2195.

### ISSUE THREAD

**Issue by Hakuroda** [Azure/azure-functions-host#8159]
#### Investigative information

In this issue https://github.com/microsoft/ApplicationInsights-dotnet/issues/2195, it insisted that Microsoft.ApplicationInsights.AspNetCore 2.17.0 has a bug and the issue is mitigated its later version 2.18.0.
If we see azure-functions-host v.3.4.2(current my function app) dependency, WebJobs.Script.csproj, this repository has a dependency to Microsoft.Azure.WebJobs.Logging.ApplicationInsights ver.3.0.30-11874.
- WebJobs.Script.csproj
https://github.com/Azure/azure-functions-host/blob/v3.4.2/src/WebJobs.Script/WebJobs.Script.csproj#L57

I don't find exact version repository but it seems that Microsoft.Azure.WebJobs.Logging.ApplicationInsights v.3.0.30 has a dependency to Microsoft.ApplicationInsights.AspNetCore ver.2.17.0.
- WebJobs.Logging.ApplicationInsights.csproj
https://github.com/Azure/azure-webjobs-sdk/blob/v3.0.30/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/WebJobs.Logging.ApplicationInsights.csproj#L27
<img width="360" alt="image" src="https://user-images.githubusercontent.com/67581008/154926916-6aebdafc-183f-40bf-8bc6-40cc1a55a9f9.png">

In my env, an error happened "The specified configuration does not have a telemetry channel. (Parameter 'configuration')" and I guess this is due to the race condition in Microsoft.ApplicationInsights.AspNetCore. Also Brett handled previously this version up here, https://github.com/Azure/azure-functions-host/pull/7448. But I don't see updates for now...

Could you update Microsoft.ApplicationInsights.AspNetCore defined in WebJobs.Logging.ApplicationInsights.csproj?

- Timestamp: N/a
- Function App version: v.3.4.2
- Function App name: N/a
- Function name(s) (as appropriate): N/a
- Invocation ID: N/a
- Region: Japan East

#### Repro steps

Create Azure Functions in Japan East region. Running an application on it, the similar error will be observed.

#### Expected behavior

Use Microsoft.Azure.WebJobs.Logging.ApplicationInsights v.2.18.0 later. Current version Microsoft.Azure.WebJobs.Logging.ApplicationInsights v.2.17.0 is deprecated.

#### Actual behavior

Use Microsoft.Azure.WebJobs.Logging.ApplicationInsights v.2.17.0 that is deprecated already. It might happen "The specified configuration does not have a telemetry channel. (Parameter 'configuration')".

#### Known workarounds

N/a

#### Related information 

N/a

**Comment by Ved2806** [comment]
Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by Ved2806** [comment]
Hi @brettsam Could you please help with this?

**Comment by brettsam** [comment]
Here are the two PRs that bumped the host to 2.20. These should be rolling out with the next version of Functions.
- v3: https://github.com/Azure/azure-functions-host/pull/8040
- v4: https://github.com/Azure/azure-functions-host/pull/8041
