### ISSUE TITLE
Add support for LoggerFactoryOptions on ScriptLoggerFactory

### ISSUE THREAD

**Issue by a99cl208** [Azure/azure-functions-host#8161]
#### What problem would the feature you're requesting solve? Please describe.
By default LoggerFactory options does not track any additionnal properties, like SpanId, ParentId, TraceId, contrary to the default configuration from ASP.NET (see here: https://github.com/dotnet/aspnetcore/blob/master/src/DefaultBuilder/src/WebHost.cs).
Problem is that not having the parent ID makes difficult to process to the end to end correlation analysis.

#### Describe the solution you'd like
in this file : https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Diagnostics/ScriptLoggerFactory.cs
add IOptions<LoggerFactoryOptions> options in the constructor and pass it to the inner loggerfactory.

**Comment by Ved2806** [comment]
Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by fabiocav** [comment]
@a99cl208 would you mind sharing more information about the logs you're looking at and what information/correlation details you feel are missing today? Trying to better understand as, depending on what is missing here, the scope of the work might be different, as just enabling the property tracking along might not be sufficient.

Thanks!

**Comment by a99cl208** [comment]
@fabiocav to be honest i do not recall anything aside of what was written in the ticket. Still it is maybe a good idea to take into account the logger factory options as part of general extensibility design consideration but i will let you decide if its useful and/or relevant.
