### ISSUE TITLE
Design WorkerHeartbeat functionality

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-host#8164]
Create a design document to outline an approach for implementing the `WorkerHeartbeat` functionality. This should include the protobuf design and host implementation details.

`WorkerHeartbeat` will help us improve reliability as we can use this request to determine the state of the worker and use that information in turn to determine when to start/stop a worker process. The worker should send a heartbeat message every ~10 sec so that the host can then figure out health if pings did not come as expected. As of now host relies on `worker_init_response` - worker heartbeat can be extended to include rich set of information

Our protobuf currently has an empty definition for the WorkerHeartbeat here:

https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.Grpc/azure-functions-language-worker-protobuf/src/proto/FunctionRpc.proto#L156

**Comment by liliankasem** [comment]
Potentially related to #4852

There seems to be a disconnect between the host reading events and the out-of-proc worker being up and running and ready to handle invocations.

**Comment by fabiocav** [comment]
Moving this to the backlog for discussion, including potential issues with some worker's ability to implement this.

**Comment by fabiocav** [comment]
Discussion on this is in progress. Moving to 122 for completion.

**Comment by liliankasem** [comment]
Upon investigation, the team is moving forward with [option 2 as outlined in the design document](https://dev.azure.com/msazure/One/_git/AAPT-Antares-Docs?path=/TeamDocs/FunctionTeamDocs/Design/Host/WorkerHeartbeat.md&version=GBmaster&line=1&_a=preview).

The `WorkerStatusRequest/Response` messages are already implemented by the language workers, and is currently being
used by the FrontEnd and the dynamic concurrency feature to determine worker latency and health. The next step would
be to ensure that we are implementing logic to handle the worker overloaded state to ensure we restart an unhealthy
worker, this work is already being tracked by the [dynamic concurrency epic](https://github.com/Azure/azure-functions-host/issues/7499).

Action items from this investigation:

- [x] Remove WorkerHeartbeat from proto ([pr](https://github.com/Azure/azure-functions-language-worker-protobuf/pull/71))
- [x] Create [issue](https://github.com/Azure/azure-functions-dotnet-worker/issues/113) in dotnet worker to implement WorkerStatusResponse
- [x] Create [issue](https://github.com/Azure/azure-functions-host/issues/8417) to restart unresponsive workers
