### ISSUE TITLE
Did not find any initialized language workers - Azure functions Net 6 on linux

### ISSUE THREAD

**Issue by sjuarezgx** [Azure/azure-functions-host#8167]
Under some circunstances that I describe below, Azure functions on linux don't work, throwing the error "Did not find any initialized language workers"

Within the Application Insights logs I can see the specific error:

Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Hosting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the specified file.

When compiling our project, version 6.0.0 of Microsoft.Extensions.Hosting remains as a dependency.
That can be seen by de-compiling the dll with Jetbrains dotpeek for example.

However, the function's project deps.json file has the reference to 5.0.0

 "Microsoft.Extensions.Hosting": "5.0.0",

That inconsistency is what causes the error.

The way to reproduce it simply is, in any project, to put this in the csproj:

FrameworkReference Include="Microsoft.AspNetCore.App"

Using this framework causes the dependency to version 6.0.0 of the dll to be generated, however, the azure msbuilds are incorrectly generating the deps.json of the project, putting version 5.0.0.

Info about the project:

TargetFramework net6.0
AzureFunctionsVersion V4
Isolated
"Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13"
"Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="4.2.1"
"Microsoft.Azure.Functions.Worker.Extensions.Storage" Version="4.0.4" 
"Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.0.1"
"Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0"
"Microsoft.Azure.Functions.Worker" Version="1.5.2" 

Info about the function:
- Function App Runtime version: 4.1.3.3
- Function App name: httplinux2net6
- Function name(s) (as appropriate): DataProvider1
- Invocation ID: f0bcf73d-0a3e-443b-bca4-bfd67024bb4c
- Region: Central US

Known workaround

Having this runtime.config.json avoids the error

{
  "runtimeOptions": {
    "tfm": "net6.0",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "6.0.0-rc.2.21480.5"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "6.0.0-rc.2.21480.10"
      }
    ]
  }
}

**Comment by v-bbalaiagar** [comment]
Hi @sjuarezgx , Similar scenarios were fixed/ tracked earlier as mentioned here - https://github.com/Azure/azure-functions-dotnet-worker/issues/556
Please check and let us know if this helps.

cc @liliankasem

**Comment by sjuarezgx** [comment]
Hi v-bbalaiagar 
I already checked that issue, in fact, I posted to it also.

I can see that the "Did not find any initialized language workers" is a generic excepction, with too many possible causes.
But as I told you in this post, in our case, we could arrive to the origin of the problem. The *deps.json file generated by the msbuild tools of Azure has a wrong reference to "Microsoft.Extensions.Hosting" ( 5.0.0 instead of  6.0.0). This is due to having a reference to "Microsoft.AspNetCore.App" in the project.
We tried configuring DOTNET-ISOLATED|6.0 for Linux-Fx-Version property at the function app, but we have still the error.

Thanks for your help.

**Comment by v-bbalaiagar** [comment]
Hi @pragnagopa / @fabiocav , Could you please look into this issue.

**Comment by liliankasem** [comment]
> azure msbuilds are incorrectly generating the deps.json 

@brettsam is this something you can help investigate?

**Comment by sjuarezgx** [comment]
Hello
Could you return any feedback about this issue please?

Thanks
sjuarezgx

**Comment by runtimeware** [comment]
Also having the same issue (we're also v4, dotnet-isolated).  We've found that we'll get random 500's thrown by function all complaining about the same problem (this is on a Premium Sku fwiw) - our package references look like this:

"Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13"
"Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0"
"Microsoft.Azure.Functions.Worker" Version="1.6.0" 

"Microsoft.Azure.WebJobs.Extensions" Version="4.0.1"

"Microsoft.Extensions.Configuration.EnvironmentVariables" Version="6.0.0"
"Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.0" 

"Microsoft.Azure.Functions.Worker.Extensions.SignalRService" Version="1.2.2" 

"Microsoft.AspNetCore.WebUtilities" Version="2.2.0"
"Microsoft.EntityFrameworkCore" Version="6.0.0"
"Microsoft.EntityFrameworkCore.Tools" Version="6.0.0"

**Comment by liliankasem** [comment]
For anyone experiencing "Did not find initialized language workers" issues, please open a support ticket. This is a very vague exception that could occur for a variety of reasons and will vary for every application.
