### ISSUE TITLE
[Microsoft.Azure.WebJobs.Extensions.ServiceBus] maxMessageCount and maxMessages are not working as expected

### ISSUE THREAD

**Issue by cosminstirbu** [Azure/azure-functions-host#8176]
Hello,

I'm trying to limit the number of messages in a batch when using `Microsoft.Azure.WebJobs.Extensions.ServiceBus`.

I've tried with both 2.x an 5.x settings it doesn't honor `maxMessageCount` and `maxMessages`

2.x

```
{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "My.Function": "Information"
    },
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensions": {
    "serviceBus": {
      "messageHandlerOptions": {
        "maxConcurrentCalls": 10,
        "autoComplete": false
      },
      "batchOptions": {
        "maxMessageCount": 70,
        "operationTimeout": "00:00:10",
        "autoComplete": false
      }
    }
  }
}
```

5.x

```
{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "My.Function": "Information"
    },
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensions": {
    "serviceBus": {
      "autoCompleteMessages": false,
      "maxMessages": 70
    }
  }
}
```

The messages batch size that we're seeing is of approximately 800 messages, even though we're expecting to see maximum 70 messages.

#### Expected behavior

The maximum batch size should be 70.

#### Actual behavior

The batch size is even 800 messages some times.

#### Related information 

The way we're testing is the following:

1. Stop the function
2. Publish messages (800+)
3. Start the function
4. Look the logs as we're explicitly logging the array length.

Provide any related information 

* Programming language used: C#
* Bindings used: `Microsoft.Azure.WebJobs.Extensions.ServiceBus` version `5.2.0`

Snippet:

```
    [FunctionName("IngestionServiceBusFunction")]
    public async Task RunForEvent(
        [ServiceBusTrigger("%EventsTopicName%", "%EventsSubscriptionName%", Connection = "ServiceBusConnection")] ServiceBusReceivedMessage[] receivedMessages,
        ServiceBusMessageActions messageActions)
    {
           Logger.LogInformation("[{logCode}] Will process a batch size of {batchSize} messages", LogCodes.BatchSizeInfo, receivedMessages.Length);
    }
```

**Comment by cosminstirbu** [comment]
Is there any sort of additional logging I can check to make sure that the values from `host.json` are at least read as expected?

**Comment by cosminstirbu** [comment]
It seems that in 5.x the name of the property is `maxMessageBatchSize`, as per the [source code](https://github.dev/Azure/azure-sdk-for-net/blob/8208937479fcd8d4e02ef301701941bd132305dd/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Config/ServiceBusOptions.cs#L137) and not `maxMessages` as per [docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#additional-settings-for-version-5x).

I have changed the property name and now it works as expected.

Before closing this issue please revisit the docs and fix the property name.

Also, my understanding from reading the docs:

_When using service bus extension version 5.x and higher, the following global configuration settings are supported **in addition** to the 2.x settings in ServiceBusOptions._ 

is that the old 2.x settings should work as well. That doesn't seem to be the case. We should either fix the code or fix the docs.

**Comment by v-bbalaiagar** [comment]
Hi @cosminstirbu , Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @cosminstirbu , Opened a new document issue for further validation - https://github.com/MicrosoftDocs/azure-docs/issues/89658 . Closing this issue here
