### ISSUE TITLE
Reload Environment variable

### ISSUE THREAD

**Issue by teaglebuilt** [Azure/azure-functions-host#8180]
In .NET there is an option for dependency injection for the startup host to add additional functionality to disable or enable functions.

#### Is your question related to a specific version? If so, please specify:
No
#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 
Reloadable environment variables, toggling functions on and off
#### Question
How can i disable or enable functions? Leading to how can I change the value of an environment variable at runtime of the worker? Is this possible?

**Comment by Ved2806** [comment]
Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by Ved2806** [comment]
Hi @brettsam, Could you please help with this?

**Comment by liliankasem** [comment]
@brettsam any thoughts?

**Comment by brettsam** [comment]
If you're looking to toggle functions on/off during runtime, this isn't supported; evaluation of whether a function is disabled or not happens at startup time and I don't imagine we'd change this; too many things depend on this state being set during initialization.

What scenario are you looking for, exactly? That may help...

One thing you could do is have a function be a no-op based on some value. For example, check a value at the start of a function, then return immediately if it evaluates to "this function is disabled".
