### ISSUE TITLE
Implement worker config profiles

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-host#8184]
Profiles enable workers to change how the worker is configured based on certain conditions, for example a worker may want to configure itself differently for a consumption application vs a dedicated application. The profiles will be defined in the `worker.config.json` file and will essentially override the default worker description based on a set of conditions.

Work to do:

- design the profile schema
- implement the profile parser logic

[Design doc](https://dev.azure.com/msazure/One/_git/AAPT-Antares-Docs/pullrequest/5715621?_a=files)

**Comment by fabiocav** [comment]
Design on this is done and @shreyas-gopalakrishna is iterating on a PR.

This should be completed in the next sprint, so we're updating the milestone to reflect that.
