### ISSUE TITLE
Function App runs fine locally but fails when deployed to Azure

### ISSUE THREAD

**Issue by PandaBoy00** [Azure/azure-functions-host#8198]
Hi there,

Following Microsoft Quick Start for Function App with Go (https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-other?tabs=go%2Cwindows)

I was able to successfully run the code locally on my Windows computer.  I continued to follow the steps to deploy the Function App to Azure portal and when try to run the Function App at the /api/HttpExample endpoint.  It would fail to execute even though it runs fine locally.

#### Investigative information

Please provide the following:

- Timestamp: 2022-03-03 21:56:04.395 (UTC)
- Function App version: ~4
- Function App name: appTestGolang
- Function name(s): HttpExample
- Invocation ID: 1e3c4be5a3ba4d569940e7cf10bb1f62
- Region: East US
- OS: Linux
- App Service Plan: Consumption

#### Repro steps

Provide the steps required to reproduce the problem:

1. Open any browser to the URL: https://apptestgolang.azurewebsites.net/api/HttpExample

#### Expected behavior

Provide a description of the expected behavior.

1. As per execution locally it should print out "This HTTP triggered function executed successfully. Pass a name in the query string for a personalized response."

#### Actual behavior

Provide a description of the actual behavior observed.

Webpage fails to load

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used : Go 1.17.7
* Links to source: https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-other?tabs=go%2Cwindows
* Bindings used
<details>
<summary>Source</summary>
```go
package main

import (
    "fmt"
    "log"
    "net/http"
    "os"
)

func helloHandler(w http.ResponseWriter, r *http.Request) {
    message := "This HTTP triggered function executed successfully. Pass a name in the query string for a personalized response.\n"
    name := r.URL.Query().Get("name")
    if name != "" {
        message = fmt.Sprintf("Hello, %s. This HTTP triggered function executed successfully.\n", name)
    }
    fmt.Fprint(w, message)
}

func main() {
    listenAddr := ":8080"
    if val, ok := os.LookupEnv("FUNCTIONS_CUSTOMHANDLER_PORT"); ok {
        listenAddr = ":" + val
    }
    http.HandleFunc("/api/HttpExample", helloHandler)
    log.Printf("About to listen on %s. Go to https://127.0.0.1%s/", listenAddr, listenAddr)
    log.Fatal(http.ListenAndServe(listenAddr, nil))
}
```
functions.json
```json
{
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "get",
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}
```

</details>

**Comment by v-bbalaiagar** [comment]
Hi @PandaBoy00 , Thank you for your feedback! I shall repro this issue to check if we are missing something and update you with the findings.

**Comment by v-bbalaiagar** [comment]
Hi @PandaBoy00 , I went through the logs. We detected that the Function App runtime encountered the below exceptions:
System.InvalidOperationException : Error while assigning execute permission.
Path doesn't exist!
The Application Insights extension is no longer supported : The Application Insights extension is no longer supported. Package references to Microsoft.Azure.WebJobs.Extensions.ApplicationInsights can be removed.
System.ComponentModel.Win32Exception : Failed to start Worker Channel. Process fileName: HttpExample
An error occurred trying to start process 'HttpExample' with working directory '/home/site/wwwroot'. No such file or directory

Please review your functions code/config to see which part is causing the error and apply the fixes appropriately.
 
[Monitor | Monitor Azure Functions Using Application Insights](https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring)

Related Information :
https://stackoverflow.com/questions/71571157/function-app-runs-fine-locally-but-fails-when-deployed-to-azure/71747857#71747857
