### ISSUE TITLE
Flood of HTTP related logging since upgrading to host v4

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/azure-functions-host#8203]
We are facing similar issue after upgrading to .net 6 functions.

https://github.com/Azure/azure-functions-host/issues/7740

below is my .csproj

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <Version>6.0.1</Version>
    <Nullable>warnings</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Abc.Common.Metrics.Functions" Version="2.0.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.2.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Contracts.csproj" />
    <ProjectReference Include="..\DataAccess.csproj" />
    <ProjectReference Include="..\Events.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="TemplateResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TemplateResource.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="TemplateResource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>TemplateResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>`

**Comment by v-bbalaiagar** [comment]
Hi @krishnasingh1818 , Thank you for your feedback! This issue is relating to an issue which is already being tracked - https://github.com/Azure/azure-functions-dotnet-worker/issues/796 . Please find the space for further updates.

Closing this issue, please feel free to ping in the issue comment.
