### ISSUE TITLE
JavaScript project is not auto-detected without "FUNCTIONS_WORKER_RUNTIME"

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-host#8210]
#### Repro steps

1. Create a hello world JavaScript project with a single http trigger
1. Run the host from the v3.5.1 tag of this repo pointing to that project
2. Hit the trigger, like "http://localhost:5000/api/HttpTrigger1?name=Test"

NOTE: Do _not_ set "FUNCTIONS_WORKER_RUNTIME" anywhere (it won't get set by default if you're just running the host. If you use core tools, it'll use values from local.settings.json which likely includes "FUNCTIONS_WORKER_RUNTIME")

#### Expected behavior

It should return "Hello, Test. This HTTP triggered function executed successfully."

#### Actual behavior

It fails with 500 status code and logs say "Did not find any initialized language workers"

#### Known workarounds

Explicitly set "FUNCTIONS_WORKER_RUNTIME" to "node"

#### Related information 

This issue does not reproduce with v3.4.2. I did some digging and the issue started reproducing after this commit: https://github.com/Azure/azure-functions-host/commit/7e52075f6377530ddc0970e38cff1625816f2bed

**Comment by liliankasem** [comment]
@surgupta-msft @soninaren - this looks like it was due to the worker indexing changes you worked on, can you take a look?

**Comment by liliankasem** [comment]
Backport to v3: https://github.com/Azure/azure-functions-host/pull/8212

**Comment by liliankasem** [comment]
@ejizba @surgupta-msft - looks like the backport was merged, are there any other actions we need to take to close this issue?

**Comment by ejizba** [comment]
Nothing I'm aware of
