### ISSUE TITLE
Diagnose and solve problems - critical availability risk alert

### ISSUE THREAD

**Issue by davidchrystal** [Azure/azure-functions-host#8218]
#### Is your question related to a specific version? If so, please specify:
Function runtime version 3. dotnet core version 5.0.406

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#.

#### Question

We are getting a critical Availability risk alert when using the 'Diagnose and solve problems' feature to diagnose a function app.

The function app uses managed identity to connect a service bus queue. Everything works.

The code includes the connection name:
`public static void Run([ServiceBusTrigger("myinputqueue", Connection = "ServiceBusConnection")]string myQueueItem, ILogger log)`

and the configuration includes the connection name: 
`ServiceBusConnection__fullyQualifiedNamespace`

The Diagnose and solve problems feature gives the critical availability alert.

<img width="889" alt="ServiceConnectionError" src="https://user-images.githubusercontent.com/7789197/157639739-ddf6f16a-4f01-4352-a05b-c8d705317f67.png">

`The following Application Settings are referenced in Function bindings but not configured in the Function App. This can cause execution errors
Function: dncfunctionapp/ServiceBusTrigger, Binding parameter: myQueueItem, Application setting: ServiceBusConnection`

Is there anything we can do to resolve the issue?

**Comment by Ved2806** [comment]
Thank you for the feedback, We will discuss this internally and let you know about the findings.

**Comment by Ved2806** [comment]
Hi @davidchrystal Diagnose and solve problems usually throws alerts after performing the analysis based on recommended settings for azure resources. If you want to resolve them, please follow the recommended ways suggested in diagnose and solve problems.
