### ISSUE TITLE
.Net core runtime version 6.0.3 on azure functions

### ISSUE THREAD

**Issue by ManeeshRajamMS** [Azure/azure-functions-host#8232]
We are using dotnet core to develop azure functions.
We are trying to upgrade the .NET Core runtime version on Azure functions from 6.0.0 to 6.0.3 (which includes a security patch)
As of now we have configured our Function Apps to below:

Function App settings on azure portal:
•	FUNCTIONS_EXTENSION_VERSION = ~4
•	FUNCTIONS_WORKER_RUNTIME = dotnet

csproj settings on C#:
<TargetFramework>net6.0</TargetFramework>
<RuntimeFrameworkVersion>6.0.3</RuntimeFrameworkVersion>
<RollForward>LatestPatch</RollForward>
<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
<AzureFunctionsVersion>v4</AzureFunctionsVersion>

SDKs used:
•	Microsoft.NET.Sdk.Functions 4.1.0
•	.NET Core SDK 6.0.201

#### Question
Problem: The runtime dotnet core version on Azure function is still on 6.0.1. Confirmed this by adding log statement(Environment.Version) inside Azure function.
Is there any configuration setting that we can make to use dotnet core runtime version 6.0.3 on azure function?

Please let me know if you need more details or any other project setup related details for perusal.

**Comment by v-bbalaiagar** [comment]
Hi @ManeeshRajamMS , Thank you for your feedback! Here is the document how you can set the runtime version - https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal

Please check and let us know if this helps.

**Comment by ManeeshRajamMS** [comment]
Thanks @v-bbalaiagar , this document does not specify the exact .NETCore runtime version that would be used while running the azure functions. 
we have 6.0.0 / 6.0.1 / 6.0.2 / 6.0.3 .NETCore runtime versions.
Which one would be used for C# / dotnet Azure function.

How do we ensure that our azure function uses 6.0.3 .NET Core runtime version and not the lower versions.
Looking for more insights into this.

**Comment by ManeeshRajamMS** [comment]
Thanks @v-bbalaiagar , this document does not specify the exact .NETCore runtime version that would be used while running the azure functions.
we have 6.0.0 / 6.0.1 / 6.0.2 / 6.0.3 .NETCore runtime versions.
Which one would be used for C# / dotnet Azure function.

How do we ensure that our azure function uses 6.0.3 .NET Core runtime version and not the lower versions.
Looking for more insights into this.

**Comment by surgupta-msft** [comment]
@ManeeshRajamMS some information is given in this link regarding using specific language version - https://docs.microsoft.com/en-us/azure/azure-functions/supported-languages. Please check if this helps you.

**Comment by dxynnez** [comment]
I think in-process hosting azure function doesn't support self-contained mode - basically you are tight to whatever runtime version the function host is running with.

In function V4 there is a isolated hosting model where you should be able to control the runtime version (I haven't tried, but they make it sound like it's one of the benefit of the isolated mode) - https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#differences-with-net-class-library-functions

**Comment by anirudhgarg** [comment]
This issue should be closed. We dont support running your own custom .NET runtime.
