### ISSUE TITLE
Azure Function V4 is not working properly with Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel nuget version 2.18+

### ISSUE THREAD

**Issue by YairoR** [Azure/azure-functions-host#8242]
Hi,

I've created an Azure Function V4 project and added a reference to the Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel nuget version 2.18.

The code I've used is very simple:
```
var telemetryConfiguration = new TelemetryConfiguration("myIkey", new ServerTelemetryChannel());
var telemetryClient = new TelemetryClient(telemetryConfiguration);
telemetryClient.TrackTrace("Hi");
```
The code is running locally (using the emulator) as expected, but when I've published the function to Azure I saw that the function is failing with the following exception:
_Could not load type 'Microsoft.ApplicationInsights.Channel.IAsyncFlushable' from assembly 'Microsoft.ApplicationInsights, Version=2.17.0.146, Culture=neutral, PublicKeyToken=31bf3856ad364e35'._
The same exception is happening for version 2.19 and 2.20.

When removing the 'new ServerTelemetryChannel()' from the TelemetryConfiguration object initialization, everything is working ok.
Looks like ServerTelemetryChannel is calling to a dependency that is looking for Microsoft.ApplicationInsights nuget version 2.17.

#### Investigative information

Please provide the following:

- Timestamp: 3/17/2022 
- Function App version: 4
- Function App name: testaiversion20220317163249
- Function name(s) (as appropriate): Function1 
- Invocation ID: --
- Region: East US

#### Expected behavior

Provide a description of the expected behavior.

I would expect that the Azure Function will work properly with the WindowsServer.TelemetryChannel nuget.

#### Actual behavior

Explained above.

#### Known workarounds

Downgrade Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel nuget to 2.17.

**Comment by runefs** [comment]
We have the same issue in a functions app. (runtime v 4.1.3.3) if IU disable the line of code that causes the error an iterates through all the assemblies (`System.AppDomain.CurrentDomain.GetAssemblies()`) I can see two versions of the Microsoft.ApplicationInsights.dll from to rather different locations

```json
{
    "location": "/home/site/wwwroot/bin/Microsoft.ApplicationInsights.AspNetCore.dll",
    "name": "Microsoft.ApplicationInsights.AspNetCore",
    "version": "2.20.0.103"
  }
{
    "location": "/azure-functions-host/Microsoft.ApplicationInsights.AspNetCore.dll",
    "name": "Microsoft.ApplicationInsights.AspNetCore",
    "version": "2.17.0.146"
  }
```

We only reference two assemblies directly: 
Microsoft.ApplicationInsights
Microsoft.ApplicationInsights.AspNetCore
Not the above mentioned and it's not one of the loaded assemblies either another similarly named assembly `Microsoft.AI.ServerTelemetryChannel` is loaded (v2.17) downgrading the two assemblies we reference do not fix the issue. The line of code that causes the issue in our startup is this `services.AddApplicationInsightsTelemetry(aiOptions) `

**Comment by v-bbalaiagar** [comment]
Hi @YairoR , Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by mathieuisabel** [comment]
I've experienced the same as @runefs on my end. I had to rollback the App Insights package version from 2.20 to 2.17 for the time being. The function runtime build in azure is 4.1.3.17473

**Comment by mathieuisabel** [comment]
It looks like the 4.2 runtime might resolve that particular problem as it looks like it depends on App Insights 2.20:

https://github.com/Azure/azure-functions-host/commit/e378c87b195025c4d5b98a1aa306df46db004b61#diff-6a49576770202827579aca50b0a820e13b37b1737a8e35a8b0da08d3f37a254dR46

I did see they rolled back a 4.2 build recently due to an issue though so we might need to check that.

https://github.com/Azure/azure-functions-host/issues/8249

**Comment by YairoR** [comment]
I'm not sure if this was fixed (probably yes), so closing as it's more than a 1 year old
