### ISSUE TITLE
Flood of FunctionIndexingException after Azure did 'Update website extension'

### ISSUE THREAD

**Issue by andyhammar** [Azure/azure-functions-host#8244]
Hi

All of a sudden we got a flood of exception regarding all our functions in a function app.
We had not done any changes, but infrastructure had. (Azure Application Change Service)
Restart didn't help, not redeployment.
What to do?
Thanks!

Looks like four "update website extension" has happened:
![image](https://user-images.githubusercontent.com/1713268/158956374-7af2b5b3-6be1-4921-93e1-0f9c57f60e17.png)

Logs of the exception, it started around 19:00 UTC:
![image](https://user-images.githubusercontent.com/1713268/158956395-dc259e2a-b607-43b3-b86f-03078fe47aed.png)

First exception at 2022-03-17 19:18:48.744:

| timestamp [UTC] | 2022-03-17T19:18:48.744642Z |
| -- | -- |
| problemId | System.InvalidOperationException at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndex.Add |
| type | System.InvalidOperationException |
| assembly | Microsoft.Azure.WebJobs.Host, Version=3.0.33.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 |
| method | Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndex.Add |
| outerType | Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException | 
| outerMessage | Error indexing method 'BindingErrorsBmsServerEntity' |
| outerAssembly | Microsoft.Azure.WebJobs.Host, Version=3.0.33.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 |
| outerMethod | Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer+<IndexMethodAsync>d__21.MoveNext |
| innermostType | System.InvalidOperationException |
| innermostMessage | Method overloads are not supported. There are multiple methods with the name 'BmsHealthReadModels.Functions.BindingErrorsFunctions.BindingErrorsFunction.BindingErrorsBmsServerEntityRun'. |

More info:
HostInstanceId: 3f950525-4169-442f-a87f-7c6933de428d
Region: West Europe
Runtime version: ~4
64 Bit

cloud_RoleInstance | 82b0635b3f18447efed7c3088ba2fffbc37f91433df971dfb94cbe7257168025
-- | --
| appId | a6d92ce0-d4f0-4915-9843-bddde0140281
| sdkVersion | azurefunctions: 4.2.1.17812
| itemId | 12dcac30-a627-11ec-a7d7-b73b0fa5befe

**Comment by timosnel** [comment]
This is occurring to us too. Rolling back to runtime version 4.1.3.17473 fixed our problems. 

There seems to be two issues for us:

- The error indexing method you described
- Missing method exception when validating JWT tokens [(seems to be this issue)](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1792)

These problems started happening to us around 17:30 UTC

We are unsure how to proceed, we have many functions that we would prefer not to pin to a specific runtime version.

**Comment by marnilss** [comment]
We (actually simon.wendel@decerno.se 💪) noticed this with Docker-image based functions as well, in mcr.microsoft.com/azure-functions/dotnet:4.2.1
Reverted to mcr.microsoft.com/azure-functions/dotnet:4.1.3, and exceptions are gone.

**Comment by marcin-burak** [comment]
Hey guys, just a heads up for those of you who are running Azure Functions on a consumption plan. 

We're using .NET 6 v4 Azure Functions as our serverless APIs with `Microsoft.Identity.Web` v1.12 (can't use higher versions due to [known issue mentioned here](https://github.com/AzureAD/microsoft-identity-web/issues/1548)) in order to validate our tokens and call other downstream APIs. 

Woke up today to the news that most services are suddenly not working as expected. After some digging around found out about new Azure Functions runtime being rolled out to Azure App Service resources, so in my case I had to follow those steps to get things back and running again:

1. Remove those flags from my .csproj
```
<RuntimeIdentifier>win-x86</RuntimeIdentifier>
<PublishReadyToRun>true</PublishReadyToRun>
```

2. Add this flag if you're publishing your Azure Functions directly from Visual Studio (VS2022 in my case)
```
<DisableFunctionExtensionVersionUpdate>true</DisableFunctionExtensionVersionUpdate>
```

3. Deploy your Azure Functions
4. Change the `FUNCTIONS_EXTENSION_VERSION` environment variable (Azure App Service Configuration setting) from `~4` to `4.1.3` 
5. Restart your Azure Function in the Azure Portal

**Comment by bbieniek** [comment]
Guys, this is priority zero.

**Comment by fabiocav** [comment]
This issue was resolved earlier. An app restart might be required, but changing setting should not be needed.

**Comment by marcin-burak** [comment]
In my consumption plan case it seems to be fixed. I switched back to `~4` and restarted my Azure Function and all is working well as it was earlier. Thank you.

**Comment by andyhammar** [comment]
Here too, the ~4 version seems to have been rolled back to 4.1.3.17473 so functions on ~4 are functional as normal. Thanks @fabiocav !

**Comment by Ved2806** [comment]
Hi @andyhammar, please let us know is this issue resolved?

**Comment by marnilss** [comment]
Docker image mcr.microsoft.com/azure-functions/dotnet:4 tag still points to 4.2.1 version - so no solution yet on that one.

**Comment by andyhammar** [comment]
Addings links and closing this.
Release announcement, and rollback comment: https://github.com/Azure/app-service-announcements/issues/357
Open issue: https://github.com/Azure/azure-functions-host/issues/8248
