### ISSUE TITLE
Rollback of function runtime 4.2.1 in Azure?

### ISSUE THREAD

**Issue by b-twis** [Azure/azure-functions-host#8249]
Hi All,

It appears that on Friday all our Function App Runtimes were upgraded to v4.2.1.17812 which caused Library compatibility issues on every one of our functions in every environment, 
Specifically with the upgrade of Microsoft.IdentityModel.Tokens to v6.15.1 found in commit https://github.com/Azure/azure-functions-host/commit/d02fe0862445d0662ec68695c062555bbc1e0864

We mitigated this by pinning all our runtimes to a previously working version v  4.1.3.17473.

This allowed our services to come back while we upgrade our code to move to the updated IdentityModel library.

We are running net6.0 'In-process' functions under v4, so host library dependency changes like this is a massive problem for us. 

When trying to verify the library upgrade, and force the broken behaviour in Azure by manually setting the runtime to v4.2.1 I get an error in the "Function runtime settings"

![image](https://user-images.githubusercontent.com/2098465/159188581-81e7e158-e5df-4ac5-a7c8-a2ae26a03c95.png)

This seems to indicate that the release was rolled back, can someone confirm this?

Does this mean that there is no need to migrate to the IdentityModel 6.15.1? Or will it come out at a later stage?

Is there a place that publishes when breaking changes like this are happening?  or that shows the library versions of each released runtime version?

Regards,

Basil

**Comment by v-bbalaiagar** [comment]
Hi @pragnagopa , Could you please look into this issue.

**Comment by pragnagopa** [comment]
Assigning to @fabiocav and @brettsam for follow up.

Yes, as of now we have rolled back Functions Runtime 4.2.1 due to https://github.com/Azure/azure-functions-host/issues/8248

Please wait for confirmation on this issue before you unpin to ensure newer roll out does not cause downtime.

Also, follow - https://github.com/Azure/app-service-announcements/issues/357 for release updates

**Comment by fabiocav** [comment]
@b-twis can you share more details on the issue you found with the dependency update? This was a minor update on a unified dependency (6.10 - 6.15), so it would be good do understand the problem you found with that.

The goal is for that change to land in a future update, so it would be good to understand how this minor bump has impacted you.

Thanks!

**Comment by b-twis** [comment]
@pragnagopa, thank you for the information. I am attempting to keep them pinned but our release automation needs changing which is taking some time. 


@fabiocav, 

Interesting that it was only a minor update. 

Our code is referencing System.IdentityModel.Tokens.Jwt v 5.6.0 which works fine in runtime 4.1.3.17473.

We encountered the following runtime error, and I have seed a similar on in the past from a library version mismatch between us an the host. 

Unfortunately I can not reproduce this after the runtime downgrade. 

```
System.MissingMethodException: Method not found: 'Void Microsoft.IdentityModel.Tokens.InternalValidators.ValidateLifetimeAndIssuerAfterSignatureNotValidatedJwt(Microsoft.IdentityModel.Tokens.SecurityToken, System.Nullable`1<System.DateTime>, System.Nullable`1<System.DateTime>, System.String, Microsoft.IdentityModel.Tokens.TokenValidationParameters, System.Text.StringBuilder)'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
```

I had assumed it was a major update since prior to that commit I could not see an explicit reference to v 6.x of the System.IdentityModel library. 


Regards,

Basil

**Comment by fabiocav** [comment]
@b-twis this was previously a transitive dependency, and previously, the version previously used would have mapped to 6.10, bumped to 6.15.

We're taking a look at the issue.

**Comment by fabiocav** [comment]
Do you happen to have a more detailed stack or information about the code you have in place here?
