### ISSUE TITLE
Change in telemetry functionality after upgrading to v4 / .net 6.0 

### ISSUE THREAD

**Issue by simonness** [Azure/azure-functions-host#8253]
#### Is your question related to a specific version? If so, please specify:
v4

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
After upgrading a Service Bus trigger Azure Function from .net core 3.1, v3 (SDK v3.0.13) to .net 6.0, v4 (SDK v4.0.1), the Function's Request telemetry on Application Insights appears on a different Operation Id and without any of our Custom Properties from upstream activities flowing.  Note we are still using in process (FUNCTIONS_WORKER_RUNTIME set to dotnet).  Is this to be expected?  Is there anyway to configure things so that telemetry happens on one operation and custom properties flow?

We also upgraded package Microsoft.Azure.WebJobs.Extensions.ServiceBus from 4.3.0 to 5.2.0.

We can see that the 2 operations are still correlated and there is a Request Property "Operation links".

BEFORE:

![image](https://user-images.githubusercontent.com/10990813/159672996-1fc82a6c-bcaa-4fdd-bd5d-1935ccee990b.png)

![image](https://user-images.githubusercontent.com/10990813/159672530-419e5c1a-b4f9-419a-b1e6-b2bfc93e94a0.png)

AFTER:

![image](https://user-images.githubusercontent.com/10990813/159673067-cbf94389-1a4e-44ca-9610-2d8411b07e41.png)

![image](https://user-images.githubusercontent.com/10990813/159674465-f47d61f8-9445-43bb-9cd0-2bc1300134ec.png)

![image](https://user-images.githubusercontent.com/10990813/159673420-d13e42bb-7214-4f00-ba94-85d3c4bd164e.png)

**Comment by v-bbalaiagar** [comment]
Hi @simonness , Thank you for your feedback! I checked this internally. Can you try to check if it is working when downgrade the package Microsoft.Azure.WebJobs.Extensions.ServiceBus  to 4.3.0

**Comment by simonness** [comment]
Thanks @v-bbalaiagar, we did initially try this out of curiosity and noticed the Azure Function Service Bus Trigger failed to consume messages from the queue when doing this downgrade.  Is it a requirement to use > v5.0.0 of Microsoft.Azure.WebJobs.Extensions.ServiceBus with Azure Functions v4?

**Comment by simonness** [comment]
Hi @v-bbalaiagar, apologies, it looks like a clean build wasn't done the the first time around.  I can confirm that downgrading Microsoft.Azure.WebJobs.Extensions.ServiceBus to v4.3.0 makes the change in behaviour in telemetry go away.  Should we raise this issue on https://github.com/Azure/azure-sdk-for-net?

**Comment by simonness** [comment]
I have raised https://github.com/Azure/azure-sdk-for-net/issues/27954
