### ISSUE TITLE
Analyzer: Illegal Binding Syntax

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-host#8257]
Part of https://github.com/Azure/azure-functions-host/issues/7351

See https://github.com/Azure/azure-webjobs-sdk/blob/4e287eb443e2445a298a8a959f7cd01efc46e2c9/src/Analyzer/WebJobs.VSAnalyzer.Core/ErrorList.cs#L83

**Comment by fabiocav** [comment]
Still iterating on changes. Moving to sprint 123

**Comment by fabiocav** [comment]
Linked PR in progress. Moving to sprint 125
