### ISSUE TITLE
Is it possible to set a message header on a ServiceBus output binding?

### ISSUE THREAD

**Issue by richorama** [Azure/azure-functions-host#8262]
#### Is your question related to a specific version? If so, please specify:

N/A

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 

N/A

#### Question

When a function has a Service Bus Topic as an output binding, it is possible to set the message headers/properties as well as the message body?

https://docs.microsoft.com/en-us/rest/api/servicebus/message-headers-and-properties

**Comment by liliankasem** [comment]
@sidkri is this something you might have an answer to?

**Comment by richorama** [comment]
@sidkri are you able to help?

**Comment by ltrain777** [comment]
@richorama Was there a resolution to this issue?

**Comment by richorama** [comment]
I didn't find one :¬(

**Comment by alrod** [comment]
@richorama, you can set properties of [ServiceBusMessage](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmessage?view=azure-dotnet) in C#:
https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus#service-bus-output-binding

With other languages only body is supported - `string, byte[]`
