### ISSUE TITLE
Is Dependency Injection supported in Azure Functions v4?

### ISSUE THREAD

**Issue by j2jensen** [Azure/azure-functions-host#8265]
#### Is your question related to a specific version? If so, please specify:

Yes, Azure Functions v4

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 

C#

#### Question

A team member told me that he'd run into problems when trying to upgrade an Azure Functions (In-Process) class library to .NET 6, and he pointed me to the [Prerequisites](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#prerequisites) section of the documentation, which includes this prerequisite:

> * [Microsoft.Extensions.DependencyInjection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/) (currently, only version 3.x and earlier supported)

Are we understanding correctly that one of the prerequisites to enable dependency injection still doesn't support (or isn't supported by) v4? So applications written to use dependency injection are stuck on v3 or earlier?

I did notice [this issue](https://github.com/Azure/azure-functions-host/issues/8073) which appears to imply that Dependency Injection is a thing in v4. Do the docs just need to be updated?

For context:
* Azure Functions v4 has been GA since November 2021. 
* Functions v3 is [limited to](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#supported-versions) .NET Core 3.1 for in-process libraries.
* .NET Core 3.1 will stop being supported in December 2022.

**Comment by liliankasem** [comment]
Yup, DI is supported in v4.x. I've created a PR to get the documentation updated
