### ISSUE TITLE
How can I add custom properties using ILogger on each "LogInformation" call without using BeginScope each time?

### ISSUE THREAD

**Issue by SqlBenjamin** [Azure/azure-functions-host#8270]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question
I'm writing to Application Insights inside Azure Functions using the ILogger available to the orchestrator/activity functions. If I want to add custom properties I know I can do that using a message template. However, if I want to add some custom properties to each of my logs without using a message template that's where it gets a little more confusing. The only way I can see to do this is by doings something like:
```
var custProps = new Dictionary<string, object>()
{
    { "CustPropOne", "123456-7890123"},
    { "CustPropTwo", "blah blah blah"},
    { "CustNumber", 12345}
}
using (log.BeginScope(custProps))
{
    log.LogInformation("this is a message without a template");
}
```
However, **if I don't want to use BeginScope in a using statement for every time I log is there a different or better way to achieve this? ...and do it relatively easily?**

**Comment by Ved2806** [comment]
Hi @SqlBenjamin Thank you for the feedback, we will discuss this internally and let you know about the findings.

**Comment by Ved2806** [comment]
Hi @SqlBenjamin Using BeginScope is the recommended way of logging. I found few different methods for logging [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerextensions?view=dotnet-plat-ext-6.0). You may try them and please let us know if they are helpful

**Comment by SqlBenjamin** [comment]
That's what I was looking at to come up with the "BeginScope" method to log custom properties. But it seems like there should be a better/easier way to do that. Let me ping you internally to explain; I know a different workstream that may resolve this issue but I'm not positive.

**Comment by Ved2806** [comment]
Hi @SqlBenjamin Currently we only support the dot net logging extension methods at this moment and beginScope is the only way to pass the custom properties. Thanks.
