### ISSUE TITLE
Read content of all loaded modules in Functions process during placeholder mode for cold start improvement on higher percentiles

### ISSUE THREAD

**Issue by safihamid** [Azure/azure-functions-host#8285]
Based on Cold Start Profiles, This will improve cold start on higher percentiles.
We want to read all those dlls in 4K bytes and access one byte every 4K so they are actually read from disk and loaded in OS cache.
We do not actually want to load actual assemblies into the process just to read the content of files.

Best if this is done as part of /warmup call that DWAS does into the Functions Host process.

**Comment by pragnagopa** [comment]
@fabiocav / @brettsam  - planning to work on this for the next host sprint. Do let us know if you have any concerns

**Comment by pragnagopa** [comment]
cc @kshyju as FYI

**Comment by fabiocav** [comment]
@pragnagopa should this be moved? We're closing 119, should this be moved to 120? 

Do you have a design for this? Feels questionable to have this implemented in the host when it scope is much narrower (as opposed to DWAS, for instance)

**Comment by safihamid** [comment]
@fabiocav we talked about it and we were thinking we should do it in the host itself or otherwise we needed different approach es for Windows(DWAS) and Linux, .... This change should improve cold start on higher percentiles for both Windows and Linux. we are already seeing the positive impact of similar work we did for Java .jar files.

**Comment by pragnagopa** [comment]
@fabiocav moving this to next sprint. Do let us know if you still have concerns on implementing this in host

**Comment by brettsam** [comment]
@pragnagopa -- is this still being worked on? Should we bump to next sprint?

**Comment by pragnagopa** [comment]
Thanks for moving to next sprint. Will prioritize this work.
