### ISSUE TITLE
Serialization of OData annotations where appropriate

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-host#8286]
#### What problem would the feature you're requesting solve? Please describe.
There are situations where out-of-process workers may lose information due to a lack of OData information which the .NET SDK is processing. When we go to serialize that out, we lose this information. An example would be in Tables where you can lose precision for integers due to JS having a different max int, among other things. 

#### Describe the solution you'd like
The serialization handed off to the language worker should be the same as what the host received on the wire during the fetch, with some exclusions (metadata/data splits and general section carving that's intentional).

This item is to track centralizing configuration and enforcement of this behavior from the host. 

#### Describe alternatives you've considered
Work could be undertaken by each extension individually, and likely each would have to participate at least, but I think the idea here would be to centralize as much as we can.

This item may require work in the WebJobs SDK as well. That is TBD based on current discussion and any investigation that gets started here.

**Comment by surgupta-msft** [comment]
@mattchenderson @JoshLove-msft Do we expect changes on the Host side for this work or only in azure-sdk repo (as a related issue has been created in that repo - https://github.com/Azure/azure-sdk-for-net/issues/28069).

It would be helpful if you can share more details on what is expected from Host here and any code links to begin investigation on host side.
