### ISSUE TITLE
The role assignment required for queue trigger function is not specified in "Connecting to host storage with an identity"

### ISSUE THREAD

**Issue by Cheng811** [Azure/azure-functions-host#8296]
#### Question
Recently I am trying to ulilize the new feature of "Connecting to host storage with an identity". My function is a queue triggered function. I notice that other than the default role required by the extention, it is specified that some roles is needed for specific extention in the "Azurewebjobsstorage". Queue trigger is not mentioned in the table below while it is quite common in the current functions. Is there some other instrcutions about this?
![image](https://user-images.githubusercontent.com/93894596/162870129-d3064042-cb93-4795-ae20-92e3c6557ed0.png)

The documnet mentioned:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=azurewebjobsstorage#connecting-to-host-storage-with-an-identity-preview

**Comment by Ved2806** [comment]
Hi @pragnagopa Could you please redirect to the correct person?

**Comment by Ved2806** [comment]
Hi @Cheng811 I found something [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial) having information about the role assignments. Please let us know if it is useful. Thanks.
