### ISSUE TITLE
Make service resolutions during cold start specialization consistent between middleware approach and timer based approach

### ISSUE THREAD

**Issue by safihamid** [Azure/azure-functions-host#8308]
We are seeing different number of service resolutions in cold start profiles and also up to 200 msec cold start latency difference depending on the specialization code path picked.

696 service resolutions when specialization is done using SpecializationTimer (every 500 msec)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/1000764/163879288-2da48c0e-f908-44e1-b6e0-ef1ae407153b.png)

880 service resolutions when specialization is done by going thru standard Middleware logic:

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/1000764/163879469-1a0b71c8-ee9c-47dd-9c48-408e9af3fbc9.png)

**Comment by surgupta-msft** [comment]
@safihamid @pragnagopa since the pull request associated with this issue is merged, can we close this issue?

**Comment by safihamid** [comment]
yes it can be closed.
