### ISSUE TITLE
Azure function automatically restarting during processing

### ISSUE THREAD

**Issue by subhabratamallick** [Azure/azure-functions-host#8313]
I have a python azure function which I am using to run a 1 hour long process. 

Function type is HTTP and the main operation is happening in thread in the background.

I am observing that sometimes the function is automatically restating without any proper error message.

Also, I am not able to debug this from Kudu live log or diagnostic. 

#### Investigative information

Please provide the following:

- Timestamp: 2022-04-21T03:44:34.685793782Z
- Function App version: 3.5.2.0
- Function App name: 
- Function name(s) (as appropriate):
- Invocation ID:  d20dc705-6327-4813-9063-93006284a48a
- Region: West-Europe

####Logs

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Its expected that the functions should complete the run and provide the required output.

#### Actual behavior

In actual the functions is restarting in between and the process is failing.

#### Related information 

Provide any related information 

* Programming language used  - Python
* Links to source
* Bindings used

**Comment by v-bbalaiagar** [comment]
Hi @subhabratamallick ,  I am unable to get the logs with the given invocation id. Could you share the app name using https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately to check the cause.

**Comment by fabiocav** [comment]
Closing stale issue.

@subhabratamallick if you're still experiencing problems, can you please open another issue with the details?

Thank you!
