### ISSUE TITLE
Failure during indexing does not cause host/container to exit.

### ISSUE THREAD

**Issue by PehrGit** [Azure/azure-functions-host#8318]
We're having a problem where a transient error occurs during the indexing of a function. This causes a "fail" to be logged:
```
fail: Function.SynchronizeIssuersFunction[0]
      Microsoft.Azure.WebJobs.Host: Error indexing method 'SynchronizeIssuersFunction'. System.Private.CoreLib: Exception has been thrown by the target of an invocation.
```

However, the process does not exit and the pod (we're running in AKS) keeps running, though the function is not processing queue messages. I would expect that in the case of such a failure during startup, the container would exit and this would be a trigger for the orchestrator to restart the pod which in turn would fix our problem because the error is transient.

I've tested this outside of a container and the behaviour is the same, if one of the functions fails to index, the host still starts up.

#### Investigative information

Please provide the following:

- Timestamp: 2022-04-22T09:38:06.1651395Z
- Function App version: 4
- Function App name: pod running in AKS
- Function name(s) (as appropriate):
- Invocation ID: startup operation '0e00430d-e4df-4a78-9727-70b87eeb2523'
- Region: West Europe

#### Repro steps

Provide the steps required to reproduce the problem:

1. Add a `DependencyInjectionConfig` (from AzureFunctions.AutoFac) to a function
2. In that config, throw an exception

#### Expected behavior

Provide a description of the expected behavior.

- After the exception, the host would stop with a non-zero exit code

#### Actual behavior

Provide a description of the actual behavior observed.

- The exception is logged but the host still starts up

#### Known workarounds

Provide a description of any known workarounds.

- None yet

#### Related information 

Provide any related information 

* Programming language used: **C#**
* Bindings used: **QueueTrigger**

<details>
<summary>Source</summary>

```csharp
using AzureFunctions.Autofac;
namespace MyNamespace{
    [DependencyInjectionConfig(typeof(DependencyInjectionInitializer))]
    public class ImportReportFunction
    {
        [FunctionName("ImportReport")]
        public async Task RunAsync(
            [QueueTrigger(QueueStorageNames.ImportReportQueueName)]
            EventGridEvent eventGridEvent,
            [Inject] ILogger logger,
            [Inject] ICommandExecutor commandExecutor)
        {
            // function content omitted
        }
    }

    public class DependencyInjectionInitializer
    {
        public DependencyInjectionInitializer(string functionName)
        {
            throw new Exception("test");
        }
    }
}
```
</details>

**Comment by v-bbalaiagar** [comment]
Hi @PehrGit , I was trying to reach the App data yesterday and it says the App is disabled or deleted. Can you tell us if you are still facing the same issue.

**Comment by PehrGit** [comment]
> Hi @PehrGit , I was trying to reach the App data yesterday and it says the App is disabled or deleted. Can you tell us if you are still facing the same issue.

Hi, the app is running in AKS, not in an App Service, that might be why you can't find it. As a solution, we've tried running the app in the dotnet-isolated runtime and it seems that in that runtime, the app does actually exit when initialization errors occur. As this also gives other advantages, we are probably going to go that route.

**Comment by v-bbalaiagar** [comment]
Hi @PehrGit , Please let us know if this can be closed or you have further queries.

**Comment by PehrGit** [comment]
@v-bbalaiagar We've found a more kubernetes-native way to prevent the errors that were occurring so for now the problem is not occurring for us. So I will close this issue, thank you for your assistance!
