### ISSUE TITLE
host "default" key deployment via ARM template fails when deployment slot is "Stopped"

### ISSUE THREAD

**Issue by tokleine** [Azure/azure-functions-host#8321]
I experienced this issue and stumbled upon this old issue that finally solved my problem. However, I wonder if this is an intended feature or if there is a technical reason for this (unintuitive) behavior.

See below issue:

Fun fact, when the Function App is stopped then the ARM deployment will throw a bad request.
```json
{
    "Code": "Unauthorized",
    "Message": "Encountered an error (Forbidden) from extensions API.",
    "Target": null,
    "Details": [
        {
            "Message": "Encountered an error (Forbidden) from extensions API."
        },
        {
            "Code": "Unauthorized"
        },
        {
            "ErrorEntity": {
                "Code": "Unauthorized",
                "Message": "Encountered an error (Forbidden) from extensions API."
            }
        }
    ]
}
```

_Originally posted by @DibranMulder in https://github.com/Azure/azure-functions-host/issues/3994#issuecomment-508039025_

**Comment by v-bbalaiagar** [comment]
Hi @tokleine , Thank you for your feedback!
Tagging @mathewc , for more inputs

**Comment by mathewc** [comment]
Yes this is by design, though unintuitive I agree. Many of the Functions ARM APIs rely on calls that are proxied to the Function App itself, so the app must be running for those calls to succeed.
