### ISSUE TITLE
cors origin doesn't seem to be supported when use redirects on local hosting

### ISSUE THREAD

**Issue by EnenDaveyBoy** [Azure/azure-functions-host#8327]
When i debug, and I set the HttpStatus to redirect (302)  i get a cors error in the browser saying it needs the Access-Control-Allow-Origin headers, yet when i use HttpStatus OK (200) it works without issue (this is in a react spa and using fetch)

Visual Studio Code
Azure Functions Isolated .net5 V3 c#
local debugging (with localhost and local IP)

I also can't add the Access-Control-Allow-Origin manually

**Comment by Ved2806** [comment]
Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by EnenDaveyBoy** [comment]
thanks i think i have it sorted the original problem and it was a subseqent request causing the issue, however i do intend on building my own cors service for production and need to know if this is possible, becuase i definatly can't add cors headers in the response at this time

**Comment by Ved2806** [comment]
Hi @kshyju Could you please look into this issue?

**Comment by kshyju** [comment]
@EnenDaveyBoy There is a CORS tab under API menu in the azure portal for your function app, where you can configure the CORS behavior.

**Comment by EnenDaveyBoy** [comment]
what happens if I want to manage my own cors? I am building a Saas and from what i can tell there is no way to programically add origins dynamically on azure?

**Comment by kshyju** [comment]
If you want to programmatically control [CORS ](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)behavior from the azure functions code, it is possible. All you have to do is to send the `Access-Control-Allow-Origin` header with the value you want.

Example for in-proc dotnet function code

````
req.HttpContext.Response.Headers.Add(HeaderNames.AccessControlAllowOrigin, "https://news.microsoft.com");
````

where `req` is an instance of `HttpRequest` type.


You can use the `HeaderNames.AccessControlAllowOrigin` constant ( from `Microsoft.Net.Http.Headers;` namespace) to get the header name.

**Comment by kshyju** [comment]
Closing as answered. Feel free to let us know if you still have questions.
