### ISSUE TITLE
DryIoc Exception After Upgrading to .NET 6 and V4

### ISSUE THREAD

**Issue by roend83** [Azure/azure-functions-host#8330]
I'm getting the following error after upgrading my .NET 5 V3 in-process function to a .NET 6 V4 in-process function:

Scope disposed{no name} is disposed and scoped instances are disposed and no longer available.

This happens when I register a singleton object that accepts an IServiceProvider as a dependency that when invoked tries to create an instance of a service registered as scoped. The first call to this works. Every subsequent call fails with the error above. I've attached a small function app that reproduces this error.

[V4BugRepro.zip](https://github.com/Azure/azure-functions-host/files/8575327/V4BugRepro.zip)

**Comment by liliankasem** [comment]
@brettsam is this related to this issue #7874? If so the fix made to address it (#8170) should be released in the next version of the host

**Comment by roend83** [comment]
It sounds like the same issue.  I didn't find it because I was searching for the error message.

**Comment by v-bbalaiagar** [comment]
Closing this issue as its tracked in the above mentioned issue. Please feel free to reach back to us in case of any further queries related to this issue.
