### ISSUE TITLE
Azure Premium plans for Functions on Linux in VNET, and managed identity

### ISSUE THREAD

**Issue by gdotkannan** [Azure/azure-functions-host#8337]
#### Is your question related to a specific version? If so, please specify:

.NET, 6.0 , Azure functions v4

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question

**Context:**

1. The blob storage used for the function app is fully locked down with storage keys disabled.
2. All private end points are added.
3. The function app is on linux inside a VNET ( in its own subnet )
4. Plan to deploy functions with blob triggers and others like service bus using only managed identity.
5. Correct managed identity roles are assigned.
6. The app settings like AzureWebJobsStorage__xxxuri are set.

All this works fine when you are in regular App service plans deployed as container on linux.

**Issue**

Now trying to deploy the same natively (without any docker) using Azure Functions premium plan on linux.

1. I don't want to use any connection strings like WEBSITE_CONTENTAZUREFILECONNECTIONSTRING using File Share because we don't want to enable keys on storage and only use managed identity.

3. I can deploy the zip package to blob storage and use managed identity.

So for this scenario what are correct app settings I need for the deployment / running of the functions on linux using Azure Premium functions plan using blob storage with managed identity and not use file share with connection strings.

**Comment by gdotkannan** [comment]
Here are my current settings on the function app:

![image](https://user-images.githubusercontent.com/102122051/165800941-baf4d82c-aab3-4866-a896-72f762ead4cf.png)

I have followed the run from package with URL

https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#using-website_run_from_package--url

I have manually uploaded the package to the blob storage container and have the following settings:

WEBSITE_RUN_FROM_PACKAGE to https://storageAccountName.blob.core.windows.net/packages/Archive.zip

In this case I get "Azure Functions runtime is unreachable"

**Comment by gdotkannan** [comment]
I tried to WEBSITE_RUN_FROM_PACKAGE to 1 and deployed from VS code / cmd line options 
I get "Service Unavailable" from .scm.azurewebsites.net .

**Comment by v-bbalaiagar** [comment]
Hi @pragnagopa / @fabiocav , Could you please look into this issue

**Comment by gdotkannan** [comment]
Update:

I later found out that managed identity is not supported for premium function hosting storage. Apparently you do need WEBSITE_CONTENTAZUREFILECONNECTIONSTRING ( and enable access keys for that storage ). Unless that has changed you can go ahead and close this issue.

**Comment by pragnagopa** [comment]
Thanks for the confirmation. Yes, Elastic Premium plans do have support VNET.
