### ISSUE TITLE
Function level retries and instance restart

### ISSUE THREAD

**Issue by gunzip** [Azure/azure-functions-host#8344]
#### Is your question related to a specific version? If so, please specify:

v3

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 

Any language.

#### Question

For any function, we can put up a retry policy (thank you!).

I'm wondering if the timers are retained in memory or persisted in some way.

In other words: will the information about the scheduled retries be lost when the function-app
instance is restarted (for downscaling or deployment)? What's the expected behavior in case?

**Comment by v-bbalaiagar** [comment]
Hi @gunzip , Thank you for your feedback! Here is the document on azure Functions error handling and retries - https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp

Please check and let us know if this helps

**Comment by gunzip** [comment]
Yes!
