### ISSUE TITLE
Name restrictions for name properties for bindings in function.json

### ISSUE THREAD

**Issue by xlight05** [Azure/azure-functions-host#8351]
So i have this requirement to put a reserved key for the name field in the binding.  Please note value __payload below. While Deploying it does not give any error but when I execute the function its not getting called and it returns 404 error to the caller.  However when i change this __payload to any text, function executes as expected. 

What I want to know is, is there any restrictions for this field? if so what are they? 

```
{
  "bindings": [
    {
      "type": "httpTrigger",
      "authLevel": "anonymous",
      "methods": [
        "post"
      ],
      "direction": "in",
      "name": "__payload",
      "route": "hello/{*RemainingPath}"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ]
}
```

**Comment by v-bbalaiagar** [comment]
Hi @xlight05 , Thank you for your feedback! Here is the document on binding expressions - https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns
Please check and let us know if this helps.
