### ISSUE TITLE
Event Hub Trigger using managed identity fails to trigger

### ISSUE THREAD

**Issue by martin-hauge** [Azure/azure-functions-host#8355]
We have a Function set to run on an Event Hub trigger, using the Function App's managed identity for connecting. Occasionally the trigger seems to fail, and the function does not run until we interact with it in the portal (refreshing the function page or viewing the log stream) at which point it resumes running. Logs do not show any exceptions or other indications.

#### Investigative information

This refers to the last successful invocation, there is no record of failures as the function simple fails to trigger.

- Timestamp: 2022-04-22T17:01:58.7019918Z
- Function App version: 4.1.3.3
- Function App name: 
- Function name(s) (as appropriate):
- Invocation ID: 7bdf002a-0d71-430a-b0f9-5e692a6078bf
- Region: West Europe

#### Repro steps

Set up a Function with code and configuration as detailed below, with an event hub trigger connected to an event hub with steady traffic using the Function App's system managed identity. Leave alone for 4-72 hours.

#### Expected behavior

The function should trigger regularly, as long as there are messages on the Event Hub.

#### Actual behavior

After a time, typically a few hours to a couple of days, of running well, the function stops triggering. Logs show no exceptions, nor resource exhaustion or unusual run durations. Proper triggering does not resume until we interact with the function in some way, such as redeploying, restarting, or viewing the log stream in the portal.

#### Known workarounds

Using a connection string instead of managed identity works fine. That is, with an Application Setting called `EventHubConnection` containing a connection string to the Event Hub Namespace instead of the setup described below (and with the same code), the function runs as expected. We have run the two variants in parallel (using different consumer groups on the same hub) and only the managed identity variant fails.

#### Related information 

Language is C#. The binding was set up as described [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=in-process%2Cfunctionsv2%2Cextensionv5&pivots=programming-language-csharp#identity-based-connections), with an Application Setting called `EventHubConnection__fullyQualifiedNamespace` containing the url of the Event Hub Namespace.

<details>
<summary>Source</summary>

```csharp
[FunctionName("Function")
public async Task Function(
            [EventHubTrigger("%EventHubWarmQueue%", Connection = "EventHubConnection", ConsumerGroup = "%ConsumerGroupWarmQueue%")] EventData[] events,
            ILogger log)
        {
            var eventsStream = new MemoryStream();
            var eventWriter = new BinaryWriter(eventsStream);
            
            foreach (EventData eventData in events)
            {
                try
                {
                    eventWriter.Write(eventData.EventBody);
                    eventWriter.Write('\n');
                }
                catch (Exception e)
                {
                    // We need to keep processing the rest of the batch - capture this exception and continue.
                    exceptions.Add(e);
                }
            }

            eventWriter.Flush();
            var ingestTask = InsertAsync(eventsStream);
            await ingestTask;

            if (exceptions.Count > 1)
                throw new AggregateException(exceptions);

            if (exceptions.Count == 1)
                throw exceptions.Single();

            log.LogInformation($"Inserted {eventCount} events");
        
}
```

(Where InsertAsync ingests data to a Data Explorer database.)

</details>

**Comment by Ved2806** [comment]
Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by Ved2806** [comment]
Hi @martin-hauge Please open a ticket with our support team to investigate this issue further. Thanks.
