### ISSUE TITLE
Issue with azure cli command 'az functionapp create' - App Keys not generated

### ISSUE THREAD

**Issue by MrMeterPing** [Azure/azure-functions-host#8364]
Im comming from here [Azure/Azure-Functions#2221](Azure/Azure-Functions#2221) 

Do I miss something how to create a function using azure cli? How can I add a key to my function?

Steps to reproduce:

> az storage account create --name $(StorageAccountName) --resource-group $(StorageResourceGroupName)
> 
> az appservice plan create --name $(AppServicePlanName) --resource-group $(AppServicePlanResourceGroupName) --sku $(AppServicePlanSku) --location $(AppServicePlanLocation)
> 
> az functionapp create --resource-group $(FunctionResourceGroupName) --plan $(AppServicePlanPath) --name $(FunctionName) --storage-account $(StorageAccountPath) --functions-version $(FunctionVersion) --os-type $(FunctionOs) --runtime dotnet --disable-app-insights true --app-insights-key $(ApplicationInsightsImbasKey) --subnet $(FunctionSubnetPath)
> 
> az functionapp keys list --name $(FunctionName) --resource-group $(FunctionResourceGroupName)

Last command returns: Operation returned an invalid status 'Bad Request'

az rest command returns:

> az rest --method post --uri "/subscriptions/xyz/resourceGroups/rg-func/providers/Microsoft.Web/sites/func-test/host/default/listKeys?api-version=2022-03-01" --query functionKeys.default --output tsv

> Bad Request({"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime.","Target":null,"Details":[{"Message":"Encountered an error (InternalServerError) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (InternalServerError) from host runtime."}}],"Innererror":null})

Also in the Azure Portal the App Key are not shown and cannot be set:
![image](https://user-images.githubusercontent.com/101572840/166706232-744b7183-87b2-4e44-81de-fbda6b7a0328.png)

Do I miss something how to create a function using azure cli? How can I add a key to my function?

**Comment by v-bbalaiagar** [comment]
Hi @MrMeterPing , I was able to successfully create the function app and plan with your code, and obtain the keys, with only a few minor changes made.

Could you verify your permissions perhaps, and use the MS Docs for further command argument references?

[az function app create](https://docs.microsoft.com/en-us/cli/azure/functionapp?view=azure-cli-latest#az-functionapp-create)

[az appservice plan create](https://docs.microsoft.com/en-us/cli/azure/appservice/plan?view=azure-cli-latest#az-appservice-plan-create)

I've removed

--runtime dotnet
--runtime-version is not supported for --runtime dotnet. Dotnet version is determined by --functions-version. Dotnet version will be 6.0 for this function app.

--app-insights-key
you disabled insights, so this was redundant

--subnet
this needed the --vnet argument, which you didn't use

**Comment by MrMeterPing** [comment]
Thank you for your support @v-bbalaiagar.

 I managed to create the function with keys.    

Nevertheless I get the following error it works:
--subnet argument is a resource ID. Ignoring --vnet argument.

Further it takes some time the app keys are listed in azure. Refresh button helps here....

For other readers here is the complete create script:
>  az functionapp create `
>
>         --resource-group $(FunctionResourceGroupName) `
>         --plan $(AppServicePlanResourceID) `
>         --name $(FunctionName) `
>         --storage-account $(StorageAccountResourceID) ` <==/subscriptions/xyz/resourceGroups/rg-bla/providers...
>         --functions-version $(FunctionVersion) ` <== 4
>         --os-type $(FunctionOs) ` <== windows
>         --app-insights-key $(ApplicationInsightsImbasKey) `
>         --vnet $(FunctionVnetResourceID) ` 
>         --subnet $(FunctionSubnetResourceID)
