### ISSUE TITLE
Creating Azure Function resource for isolated model does not work

### ISSUE THREAD

**Issue by dozer75** [Azure/azure-functions-host#8367]
There is no way to create a valid Azure Function resource for isolated model. 

I have tried a lot of variations using both Azure CLI (using the description [here](https://github.com/Azure/azure-functions-dotnet-worker#create-the-azure-resources)), Bicep (not any direct documentation anywhere, but tried using Visual Studio Code template + various posts like [here](https://markheath.net/post/azure-functions-bicep) and [here](https://stackoverflow.com/a/66591408/2226873) to create a bicep script (as shown later)) to create the resources. Also tried using Azure Portal, but AFAIK it is not possible at all to create isolated model there. I have also tried to create both Windows and Linux based Azure functions as well tried both .NET 5 and .NET 6 with the same result.

The actual result is actually varying a bit:
- Using Azure CLI 2.36.0 states that `dotnet-isolated` is not supported (both for Windows and Linux)
  - while Azure CLI 2.31.0 does not state this and the resource is created (se below).
  - Reported the issue for 2.36.0 in [this bug report](https://github.com/Azure/azure-cli/issues/22281) to the Azure CLI team.
- When using Azure CLI 2.31.0 or bicep I get the error `Microsoft.Azure.WebJobs.Script: WorkerConfig for runtime: dotnet-isolated not found.`
  - what's strange is that the Azure CLI 2.31.0 did NOT give it from the beginning it just suddenly started.

It may not be an issue with Azure Functions, but the lack of documentation on HOW to set up Azure Functions with Isolation Mode is totally missing making it impossible to implement.

We're using IaC to create our Azure environment and are dependent of having it to work with bicep at least.

#### Investigative information

**This is resource deployment, so it is impossible to provide this information (except region)**

Please provide the following:

- Timestamp:
- Function App version:
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region: West Europe

#### Repro steps

Provide the steps required to reproduce the problem:

**Repro step using Azure CLI**
1. Follow the description as outlined in [Deploying to Azure -> Create the Azure resources](https://github.com/Azure/azure-functions-dotnet-worker#create-the-azure-resources) description.
    - **CAUTION: Does not work at all using Azure CLI 2.36.0**
    - Also tried .NET 6 and Functions Version 4
    - Also tried Linux deployment
3. Go to the created resource in Azure Portal

**Repro step using Bicep**

1. Create a resource group using `az group create --name <resourcegroup> --location <location>`
2. Run the following script using the command `az deployment group create --template-file ./<name of bicep file> --resource-group  <resource group from 1>`
    - ```
        @description('The location (or region) of the resources deployed.')
        param Location string = 'westeurope'
        
        var name = 'azure-functions-${uniqueString(resourceGroup().id)}'
        
        resource appInsightsComponents 'Microsoft.Insights/components@2020-02-02' = {
          name: '${name}-insights'
          location: Location
          kind: 'web'
          properties: {
            Application_Type: 'web'
            Request_Source: 'rest'
          }
        }
        
        resource storageAccount 'Microsoft.Storage/storageAccounts@2021-09-01' = {
          name: 'fnstor${uniqueString(resourceGroup().id)}'
          location: Location
          kind: 'StorageV2'
          sku: {
            name: 'Standard_LRS'
          }
          tags: {
            Important: 'For ${name} Only'
          }
        }
        
        var storageConnectionString = 'DefaultEndpointsProtocol=https;EndpointSuffix=${environment().suffixes.storage};AccountName=${storageAccount.name};AccountKey=${listKeys(storageAccount.id, storageAccount.apiVersion).keys[0].value}'
        
        resource appServicePlan 'Microsoft.Web/serverfarms@2021-03-01' = {
          name: '${name}-plan-linux'
          location: Location
          sku: {
            name: 'Y1'
            tier: 'Dynamic'
          }
          kind: 'linux'
          properties: {
            reserved: true
          }
        }
        
        resource azureFunction 'Microsoft.Web/sites@2020-06-01' = {
          name: name
          location: Location
          kind: 'functionapp,linux'
          properties: {    
            serverFarmId: appServicePlan.id
            siteConfig: {
              appSettings: [
                {
                  name: 'AzureWebJobsStorage'
                  value: storageConnectionString
                }
                {
                  name: 'WEBSITE_CONTENTAZUREFILECONNECTIONSTRING'
                  value: storageConnectionString
                }
                {
                  name: 'FUNCTIONS_EXTENSION_VERSION'
                  value: '~3'
                }
                {
                  name: 'APPINSIGHTS_INSTRUMENTATIONKEY'
                  value: reference(appInsightsComponents.id, appInsightsComponents.apiVersion).InstrumentationKey
                }
                {
                  name: 'FUNCTIONS_WORKER_RUNTIME'
                  value: 'dotnet-isolated'
                }
              ]
              linuxFxVersion: 'DOTNET-ISOLATED|5.0'
            }
          }
        }
        ```
    - Also tried with .NET 6 and Function extensions `~4'
    - Also tried using Windows deployment
3. Go to the created resource in Azure Portal

#### Expected behavior

Provide a description of the expected behavior.

A fully working Azure Function resource should have been created based on the provided configuration.

#### Actual behavior

Both the Azure CLI deployment and the Azure Bicep deployment resources reports the following error

![image](https://user-images.githubusercontent.com/7486163/167086128-1785e8c7-716b-480c-bd05-e5dd1b009371.png)

and the `Runtime version` states `Error`.

There is no other information and trying to access the site simply returns `Function host is not running.`

#### Known workarounds

There is no working workarounds.

#### Related information 

No related information, all is provided above.

**Comment by dozer75** [comment]
Just an update, after trying and failing A LOT today, I did discover that it works from time to time by following the steps below, but I do not have any good explanation when and why it does that. My guesses is that during the day I tried it about 50 times and 2 times it just worked.

The steps I tried was:
1. I replaced the azureFunction deployment to the following (switched to .NET 6 and Functions version 4 as well)
```
resource azureFunction 'Microsoft.Web/sites@2018-11-01' = {
  name: name
  location: Location
  kind: 'functionapp,linux'
  properties: {
    clientAffinityEnabled: false
    serverFarmId: appServicePlan.id
    siteConfig: {
      appSettings: [
        {
          name: 'AzureWebJobsStorage'
          value: storageConnectionString
        }
        {
          name: 'FUNCTIONS_EXTENSION_VERSION'
          value: '~4'
        }
        {
          name: 'APPINSIGHTS_INSTRUMENTATIONKEY'
          value: reference(appInsightsComponents.id, appInsightsComponents.apiVersion).InstrumentationKey
        }
        {
          name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
          value: reference(appInsightsComponents.id, appInsightsComponents.apiVersion).ConnectionString
        }
        {
          name: 'FUNCTIONS_WORKER_RUNTIME'
          value: 'dotnet'
        }
      ]
      cors: {
        allowedOrigins: [
          'https://portal.azure.com'
        ]
      }
      use32BitWorkerProcess: true
      linuxFxVersion: 'DOTNET|6.0'
    }
  }
  tags: {
    'hidden-link: /app-insights-resource-id': appInsightsComponents.id
  }
}
```
2. I deployed a function using deployment in VS2022 which asked me if I wanted it to update my Azure Function resource with the following question

And it worked a few times.

I did a diff between Azure Functions resources that worked and that didn't, and what I can see is that `linuxFxVersion` changes to `DOTNET-ISOLATED|6.0` when it succeeds. Otherwise it remains with `DOTNET|6.0` while `FUNCTIONS_WORKER_RUNTIME` changes to `dotnet-isolated`.

I am starting to suspect that there is something strange going on the datacenters that for some reason prohibits the `linuxFxVersion` to change to `DOTNET-ISOLATED|6.0` which is should from time to time for some reason.

**Comment by dozer75** [comment]
After I wrote my last comment I tried to switch between `dotnet` and `dotnet-isolated` in `FUNCTIONS_WORKER_RUNTIME` in Settings -> Configuration on my Function App in Azure Portal, and suddenly it works (`linuxFxVersion` is set to `DOTNET-ISOLATED|6.0`)  after a few times switching back and forth!

This is really strange and I cannot find any good reason for this.

**Comment by Ved2806** [comment]
Hi @dozer75 Please refer this issue [#8311](https://github.com/Azure/azure-functions-host/issues/8311) and let us know if it helps.

**Comment by dozer75** [comment]
Hi, sorry for delay...

Yes, I have tried creating and deploying directly (got that as a tip from Azure Support) and almost everything that I can have digged out of all the different azure funtions related information I have found both on GitHub, StackOverflow and other places to no avail.

Currently, we have rewritten our current Azure Functions to non dotnet-isolated functions and have decided to stop all further usage of Azure Functions. The lack of resonable response time both on various Azure Functions GitHub repos and from Azure Support (where the issue just has stopped up) indicates that this isn't anything we want to use in our business critical environment. We're in need of using stable products where the possibilities to get aid to resolve critical issues quick in reasonable time is of upmost importance.

Right before we gave up, we found that the issue occurs more often on Linux based environments compared to Windows based environments for some reason, but then was in the time where the decision was made to move away from Azure Functions if that is for some aid to you.

**Comment by dozer75** [comment]
Oh, BTW, I actually got an answer I suspect is related to this (forgot about that) when I posted on Azure CLI why it didn't work to create dotnet-isolated using AZ CLI [here](https://github.com/Azure/azure-cli/issues/22281#issuecomment-1132428340), not sure if this is related though, it is a maze of various repos and services and so on that are involved in this so I kind of lost track of everything in the end due to all the different things I tried.

**Comment by Ved2806** [comment]
Hi @dozer75 Is it resolved for you?

**Comment by dozer75** [comment]
Well, it is not resolved since it doesn't work, but we avoid this functionality so it's not critical for us anymore. But IMHO it's still an issue that should be looked at. But it's ok to close this issue for my part, so I'll close it.
