### ISSUE TITLE
Breaking change in GSon dependencies with version 3.7.1

### ISSUE THREAD

**Issue by fxgendrin-sesimagotagcom** [Azure/azure-functions-host#8369]
With 3.7.1 azure-functions-host, you updated Java Worker Version to [1.11.0](https://github.com/Azure/azure-functions-java-worker/releases/tag/1.11.0)
In 1.11.0, gson version is changed to 2.9.0
In that version (com.google.gson.internal.ConstructorConstructor)
`public ConstructorConstructor(Map<Type, InstanceCreator<?>> instanceCreators) `
Is changed to 
`public ConstructorConstructor(Map<Type, InstanceCreator<?>> instanceCreators, boolean useJdkUnsafe)`
So that code can no more is executed with that version, as often Azure updates functionapp without special notice, we get an exception. 

As workaround: change the constructor with adding false for useJdkUnsafe

**Comment by Ved2806** [comment]
Thank you for your feedback! We will check for the possibilities internally and update you with the findings.

**Comment by Ved2806** [comment]
Hi @kaibocai @amamounelsayed Could you please help with this issue?

**Comment by kaibocai** [comment]
Hi @fxgendrin-sesimagotagcom thanks for reaching out. I am wondering why would you use a class in the internal package? 
This is gson 1.7.2 doc about it's internal package https://javadoc.io/doc/com.google.code.gson/gson/1.7.2/com/google/gson/internal/package-summary.html
for version latter, gson even stop provide java doc for internal packages.

**Comment by shreyas-gopalakrishna** [comment]
Hello @fxgendrin-sesimagotagcom, Thank you for reaching out. 

As @kaibocai mentioned it is not recommended to use internal packages. That code is restricted to be only used by gson. 
To help you mitigate this issue we suggest pinning back to an older version of the host. 
[Pinning to a specific minor version](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=in-process%2Cazure-cli%2Cv4&pivots=programming-language-csharp#pinning-to-a-specific-minor-version)

The gson version update to 2.9.0 is announced at the [Java worker issues](https://github.com/Azure/azure-functions-java-worker/issues/559) page. We recommend following the page for version updates and new features.

**Comment by kaibocai** [comment]
Hi @fxgendrin-sesimagotagcom thanks for reaching out, I am wondering why would you use a class in the internal package?
This is gson 1.7.2 doc about it's internal package https://javadoc.io/doc/com.google.code.gson/gson/1.7.2/com/google/gson/internal/package-summary.html
for version latter, gson even stop provide java doc for internal packages.

**Comment by fxgendrin-sesimagotagcom** [comment]
Hi
Yes, it is Gson internal class, so we have not to use it. 
Thanks, we will change our implementation for it. 

Side question: where is available a "public" calendar about internal update for functionapp?

**Comment by shreyas-gopalakrishna** [comment]
Hi @fxgendrin-sesimagotagcom 
Please find the following versions to pin back to 
Windows: 3.5.2
Linux dedicated: 3.6.0
Linux Consumption: 3.6.1

You can find updates about the host and java worker in the Github issues/ announcements
[Announcement](https://github.com/Azure/app-service-announcements/issues)
[Java worker](https://github.com/Azure/azure-functions-java-worker/issues)
[Java worker wiki](https://github.com/Azure/azure-functions-java-worker/wiki )

**Comment by Ved2806** [comment]
Hi @fxgendrin-sesimagotagcom is this issue resolved?

**Comment by fxgendrin-sesimagotagcom** [comment]
@Ved2806 base on the replies: forbidden internal package usage and version to pin back, issue is closed.

**Comment by shreyas-gopalakrishna** [comment]
Hi @fxgendrin-sesimagotagcom, The Windows runtime pinned version 3.5.2 will soon (mostly by end of this year) be deprecated/removed. 
Checking with you to know if you are still using version 3.5.2. If you are still using, we recommend moving to the latest runtime version soon.
