### ISSUE TITLE
[Question] Does function host make any effort of determine whether there are enough resource to trigger a new function?

### ISSUE THREAD

**Issue by dxynnez** [Azure/azure-functions-host#8395]
Hi team,

We are wondering **on a single worker instance**, would function host make any effort to determine whether there are enough resource to trigger a new function? More specifically, for eventhub trigger function, my understanding is that there could be concurrent invocations for the same function as long as there are more events to be processed and each invocation would handle a batch of the events (assuming we are binding to a batch of events, not a single event). But processing the events could be resource intensive and if function host starts multiple threads to process all batches in parallel, the worker could easily run out of resource (e.g. memory). Is there any mechanism in place to cap the memory consumption at some percentage to make sure the worker won't crash?

We are on dedicated plan and we host multiple apps (including web apps & function apps) on each ASP, such behavior is desired for us to make sure a burst of events that a function app listens to wouldn't cause the entire worker to fail. I use eventhub trigger function as am example, but the same problem might apply to all sort of triggers.

Any guidance would be greatly appreciated!

**Comment by Ved2806** [comment]
Hi @dxynnez Thanks for the update, We will discuss this internally and let you know about the findings! Thanks.

**Comment by dxynnez** [comment]
Hi @Ved2806 , any update to this? Thanks!

**Comment by Ved2806** [comment]
Hi @dxynnez You can achieve this goal by configuring the AppInsights for monitoring your azure functions. Please go through the [document](https://docs.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2) and let us know if it is helpful?

**Comment by dxynnez** [comment]
@Ved2806  We dont use AppInsights (we are msft internal and we use geneva) but it should be unrelated...I was not looking for options to instrument the azure function. I am looking for the correct expectation to set with Azure function on dedicated plan - I think it could be a pretty common question people would have so raising up the question here might help someone else in the community also.

**Comment by dxynnez** [comment]
This is just frustrating... For all questions / issues I raised in this Repo or any Azure function related ones, I had to waited for at least half month to get any response - this is super inefficient to have any sort of bi-directional conversation and is definitely discouraging community engagement.

**Comment by brettsam** [comment]
Each trigger has its own mechanism for when to start new work. But there's nothing that dynamically decides whether to fetch more items based on resource usage.

In the EventHubs example, the trigger uses the [EventHubs SDK](https://docs.microsoft.com/en-us/azure/event-hubs/event-processor-balance-partition-load) under-the-covers, and the functions host exposes [settings](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs?tabs=in-process%2Cextensionv5&pivots=programming-language-csharp#hostjson-settings) that dictates how it behaves. EventHubs, specifically, also determines how it scales out (and how much it can process at once) by how many partitions you have in your EventHub.

In Storage Queues, you have settings like [batchSize and newBatchThreshold](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue?tabs=in-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp#host-json) that dictates how much work is being done at any time.

**Comment by dxynnez** [comment]
Thanks @brettsam ! I actually talked to the event hub trigger folks at the [azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net) repo but they made it sound like each trigger basically is only in charge of fetching new 'works' (e.g. pumping in events), but it's up to the function host to decide whether to start the 'work' (invoke the corresponding function) or not. Is it not the case?

For eventhub, the settings being exposed at this point is scoped to each partition. That being said, there is no easy way to limit the max number of concurrent running eventhub trigger functions at this point as there are 2 moving pieces (the max partitions each worker could own is the number of partitions / number of workers).

**Comment by dxynnez** [comment]
This is not stale, please.

**Comment by dxynnez** [comment]
This is not stale, can someone fix the bot, please? @Ved2806 @brettsam

**Comment by dxynnez** [comment]
this is not complete. Please reopen.

**Comment by fowl2** [comment]
I think we're kind of talking about "backpressure" here. I'm also interested in this answer.  (A bit of a different context - consumption plan with limited instances and multiple trigger types (trigger providers?))

It'd be great if eg. there were lots of HTTP trigger executions, fetching/processing of Service Bus messages could be reduced.

**Comment by dxynnez** [comment]
@Ved2806 @brettsam could any of you help reopen the issue? I don't think it's been addressed. Thank you!
