### ISSUE TITLE
Deadlock when a language worker restart crashes on initialization

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#8403]
We have a deadlock in the language worker restart flow. 

1. For example, for some reason (due to a timeout, say), we need to kill the process.
2.  We restart the process and wait for the init call to come from the worker (waiting on a `TaskCompletionSource` to be completed):
    - https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs#L576
    - https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs#L135
    - https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs#L157
4. But the worker process crashes before connecting (which happened to your incident). Therefore, we never complete the `_workerInitTask`.
5. We see the error and try to restart again.
    - https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Workers/Rpc/RpcWorkerProcess.cs#L68
7. We hit a lock in the restart loop that is meant to prevent multiple restarts from occurring simultaneously... but b/c we never completed that init task in step 1, it is never released. As far as it's concerned, 2 restarts are happening simultaneously.
    - https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs#L570

This can cause the process to effectively hang as it's waiting for these two events to complete. 

Note: In some other flows, we do explicitly set the `_workerInitTask` -- https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs#L815

**Comment by alrod** [comment]
Possibly related:
https://github.com/Azure/azure-functions-nodejs-worker/issues/482

**Comment by liliankasem** [comment]
**Repro steps**

1. Add 10 second sleep in the dotnet worker

  ```csharp
  // GrpcWorker.cs -> ProcessRequestCoreAsync()
  else if (request.ContentCase == MsgType.WorkerInitRequest)
  {
      responseMessage.WorkerInitResponse = WorkerInitRequestHandler(request.WorkerInitRequest);
      // add these lines
      Console.WriteLine("Sleeping 10 seconds");
      System.Threading.Thread.Sleep(10000);
  }
  ```

2. Add a log to print out the worker process ID in the host

  ```csharp
  // WorkerProcess.cs -> StartProcessAsync()
  Process.Start();
  _workerProcessLogger?.LogDebug($"{Process.StartInfo.FileName} process with Id={Process.Id} started");
  // add this line
  Console.WriteLine($"{Process.StartInfo.FileName} process with Id={Process.Id} started");
  ```

3. In the host, place a breakpoint on `await _workerInitTask.Task;`
   - GrpcWorkerChannel.cs -> StartWorkerProcessAsync()

4. Run the host in debug mode using the dotnet worker sample app and skip the first time
   the breakpoint is hit to let the host start up normally

5. The language worker should time out after a couple seconds

    ```log
    Failed to start a new language worker for runtime: dotnet-isolated.
    System.TimeoutException: The operation has timed out.
    ```

6. During the restart flow, once you get to the `await _workerInitTask.Task;` breakpoint,
   continue and wait - it will timeout again

7. After the host recovers for the last time you shoud get to that breakpoint again, kill the worker
   process `sudo kill -9 <process id>` and **immediately** continue the debugger. 

8. You should get an exception on `DisposeAndRestartWorkerChannel`, continue the debugger and then you should see this error message:

   ```log
   Unhandled exception. fail: 
       Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher[0]
       Exceeded language worker restart retry count for runtime:dotnet-isolated. Shutting down and proactively recycling the Functions Host to recover
   System.TimeoutException: The operation has timed out
   ```

You should now be in the deadlock state! The function app will not work and the host will not recover

**Comment by brettsam** [comment]
This was actually related to a fix already made by @alrod -- it took a while to realize this. Dupe of https://github.com/Azure/azure-functions-host/issues/7983, which has already been fixed and deployed. The incident mentioned above happened in 4.1.0 -- which was *before* this was deployed in 4.2.0.
