### ISSUE TITLE
Unhandled host error:  Headers are read-only when accessing the Response object in HTTP Trigger function.

### ISSUE THREAD

**Issue by flq** [Azure/azure-functions-host#8413]
#### Investigative information

- Timestamp: Testing locally, see example for reproduction
- Function App version:  Core Tools 4.0.4544 Commit hash: N/A  (64-bit), Function Runtime: 4.3.2.18186
- Programming language: C#, .NET6

#### Repro steps

When defining the following function and calling it, it will correctly return the "OK".

```csharp
[FunctionName("BotThingy")]
[UsedImplicitly]
public async Task RunThis(
	[HttpTrigger("get", Route = "test")]
	HttpRequest request)
{
	request.HttpContext.Response.StatusCode = 200;
	await using var w = new StreamWriter(request.HttpContext.Response.Body);
	await w.WriteLineAsync("OK");
	await w.FlushAsync();
}
```
however the logs will be filled with an attempt to access the response object AFTER taking control of it in the body of the function.
```
[2022-05-24T20:04:44.104Z] An unhandled host error has occurred.
[2022-05-24T20:04:44.104Z] Microsoft.AspNetCore.Server.Kestrel.Core: Headers are read-only, response has already started.
```

#### Background 
Why we do this: The MS Bot framework to write Teams App Bots requires to be wired up to an HTTP endpoint as such:

```csharp
// botFrameworkHttpAdapter is of type IBotFrameworkHttpAdapter from assembly  Microsoft.Bot.Builder.Integration.AspNet.Core 
// bot is of type IBot from Microsoft.Bot.Builder
await botFrameworkHttpAdapter.ProcessAsync(request, request.HttpContext.Response, bot);
```

#### Expected behavior

The functions host should be able to deal with the situation that a HTTP trigger function access the response object directly for, well, reaons. The following article here suggests a way how middleware can safely add headers when it is possible to do so: ["Add Headers To A Response In ASP.NET 5"](https://khalidabuhakmeh.com/add-headers-to-a-response-in-aspnet-5)

**Comment by flq** [comment]
As a workaround, if I change the return of the function to `Task<IActionResult>` and then change the return to

```csharp
return new NullResult()
```
where **NullResult** is

```csharp
public class NullResult : IActionResult
{
    public Task ExecuteResultAsync(ActionContext context) 
      => Task.FromResult(Task.CompletedTask);
}
```
the problem appears to go away.

**Comment by surgupta-msft** [comment]
@flq can you try once again with the latest runtime version 4.5.2 and verify if you are still seeing this issue? Below is my setup  which did not reproduce the issue.

Programming language: C#, .NET6 (in-proc)
Core Tools Version:       4.0.4590 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.5.2.18383

```csharp

      [FunctionName("Function1")]
      public static async Task<IActionResult> Run(
          [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
          ILogger log)
      {
          log.LogInformation("C# HTTP trigger function processed a request.");

          req.HttpContext.Response.StatusCode = 200;

          string name = req.Query["name"];

          string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
          dynamic data = JsonConvert.DeserializeObject(requestBody);
          name = name ?? data?.name;

          string responseMessage = string.IsNullOrEmpty(name)
              ? "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."
              : $"Hello, {name}. This HTTP triggered function executed successfully.";

          return new OkObjectResult(responseMessage);
      }
```

![image](https://user-images.githubusercontent.com/16623184/173926445-bf16727f-468c-454b-8bb5-57fea1696295.png)

**Comment by chaospixel** [comment]
@surgupta-msft , I think you might have missed a crucial part of the author's post...

His Function was writing to the Response stream directly, and flushing it. Your counter-example is buffering the response and then sending it. These are fundamentally different approaches.

In the author's streaming response scenario, the stream has progressed beyond the point where headers can be added. Whatever is trying to add them is failing.

I have a similar situation where I am trying to control the response directly (in my case it's because I'd like to start responding as soon as my IAsyncEnumerable datasource starts responding with data in an effort to reduce time-to-first byte. However, after my function implementation ends, something in the host/runtime/framework tries to add headers to the response and fails.

For now I'll continue with the author's workaround - but it would be great if it were possibly to stream responses from IAsyncEnumerables.

**Comment by chaospixel** [comment]
also, this appears to be related to https://github.com/Azure/azure-functions-host/issues/8080

**Comment by flq** [comment]
@surgupta-msft yes, I'm also a bit confused about the example you provide - I would have assumed that your example would also have run correctly before whatever you changed, since you actually do provide a return from the function? 🤔

**Comment by flq** [comment]
I am the author of the issue and I've responded - correct? So here's my feedback: The proposed code sample does not correspond to the problem outlined in the beginning.

**Comment by surgupta-msft** [comment]
Got it. Yes, I am able to repro the issue. Thanks @flq and @chaospixel for clarifying. We will need investigation here but the requirements mentioned in the issue are clear. 

@flq Just wanted to double check if the [suggestion](https://github.com/Azure/azure-functions-host/issues/8080#issuecomment-1128049043) provided in related [issue](https://github.com/Azure/azure-functions-host/issues/8080) is helpful in your case. This will give more data points for our investigation.

**Comment by surgupta-msft** [comment]
While we are investigating this, the [workaround](https://github.com/Azure/azure-functions-host/issues/8413#issuecomment-1136893015) suggested above is the correct approach. You can also use another approach to return [ContentResult](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.contentresult?view=aspnetcore-6.0)  `Task<ContentResult>` and set StatusCode in it.

**Comment by petrkoutnycz** [comment]
`ContentResult` seems to work for me, thank you.
