### ISSUE TITLE
Defaulting to Bundles V3

### ISSUE THREAD

**Issue by shreyabatra4** [Azure/azure-functions-host#8414]
New Function Apps created in the portal should default to Bundles V3.

Edited by @fabiocav:

- [x] Update default host.json created by the runtime
- [x] Update the bundles feed
- [x] Update Core Tools host.json

**Comment by fabiocav** [comment]
@satvu do we need to capture additional details about the work here to make this actionable so we can have it assigned to a sprint?

**Comment by satvu** [comment]
@fabiocav I added it to the project but think I didn't add this to the backlog correctly. I've never touched any of the related components but seems straightforward.

**Comment by fabiocav** [comment]
This needs to be prioritized to catch the first September release.
