### ISSUE TITLE
 WorkerConfig for runtime: dotnet-isolated not found

### ISSUE THREAD

**Issue by mahesh-maximus** [Azure/azure-functions-host#8430]
I'm getting the error " WorkerConfig for runtime: dotnet-isolated not found", just after every deployment.

https://github.com/Azure/azure-functions-host/blob/2360468596d0c6fb0e79b2315ec6b889dcefe38e/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs#L255

**Comment by kshyju** [comment]
@mahesh-maximus Can you share your function app name and region where you are trying to deploy, so that we can take a look? Also, what is your deployment method? Can you confirm the deployment was successful? Thanks
