### ISSUE TITLE
Fix flaky unit test

### ISSUE THREAD

**Issue by madelinegordon** [Azure/azure-functions-host#8444]
Unit test [RpcFunctionInvocationDispatcherTests.FunctionDispatcher_AdditionalAttributes()](https://github.com/Azure/azure-functions-host/blob/7c8c6e4bfcf4e0f3d2c70b1860bdde1fe16a4136/test/WebJobs.Script.Tests/Workers/Rpc/RpcFunctionInvocationDispatcherTests.cs#L639) is extremely flaky, causing build failures on unrelated PR's. 

- [history](https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=74327&view=ms.vss-test-web.build-test-results-tab&runId=1240712&resultId=100847&paneView=history)

**Comment by liliankasem** [comment]
side note: I think the expected/actual is in the wrong order - the test is failing as it is expecting the property count to be `2` but it's actually `0`. 

`Assert.Equal(item.Properties.Count, 2);` should be `Assert.Equal(2, item.Properties.Count);`
