### ISSUE TITLE
Encountered an error (BadGateway) from host runtime

### ISSUE THREAD

**Issue by lipalath-ms** [Azure/azure-functions-host#8460]
I have the following ARM template for deploying Azure Function Apps to production and staging slots:

```
module functionAppTemplate_F 'functionApp.bicep' = {
  name: 'functionAppTemplate-F'
  params: {    
  }
  dependsOn: [
    servicePlanTemplate
  ]
}

module functionAppSlotTemplate_F 'functionAppSlot.bicep' = {
  name: 'functionAppSlotTemplate-F'
  params: {    
  }
  dependsOn: [
    functionAppTemplate_F
  ]
}
```
I see the following error during deployment:

[![enter image description here][1]][1]

What am I missing?

  [1]: https://i.stack.imgur.com/rw5Lq.png

**Comment by Ved2806** [comment]
Hi @mattchenderson Could you please help with this issue?

**Comment by lipalath-ms** [comment]
@Ved2806 @mattchenderson  Any update on this please?

**Comment by mattchenderson** [comment]
This is not enough information for us to action upon. What are the contents of these modules? What is the resolved actual ARM template? For which operation is the error being presented? You can get the overall status information from the "Deployments" tab in the resource group within the portal. Drilling in can show individual steps failing.

**Comment by lipalath-ms** [comment]
@mattchenderson  @Ved2806 

[NonProdService.zip](https://github.com/Azure/azure-functions-host/files/8970333/NonProdService.zip)

Please see above bicep templates that I use for deployment.

![image](https://user-images.githubusercontent.com/6519992/175370852-10acc516-fe95-4218-92ce-e71e87218d54.png)

![image](https://user-images.githubusercontent.com/6519992/175371146-2c6c7eba-387a-4379-8d20-3d93b3608af4.png)

**Comment by Ved2806** [comment]
Hi @mattchenderson please provide your inputs with this issue. Thanks.

**Comment by mimuruth** [comment]
@Ved2806 Do you have the correlation Id?

**Comment by Ved2806** [comment]
Hi @ilantom Could you please provide the needed information?
