### ISSUE TITLE
Azure Functions Queue trigger awfully takes a lot of time to pick up messages from the Azure Queue

### ISSUE THREAD

**Issue by hamhus** [Azure/azure-functions-host#8476]
#### Is your question related to a specific version? If so, please specify:
.NET 6
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question
We are implementing scalable integration solution. JSON messages are being pushed from Kafka to Azure Queues to CRM. We are experiencing longer delays in the Azure function picking up messages from the Queue. We have the Azure function running under an App service plan, with one instance. The currently delays are up to 10 minutes for the message to be picked up from the Queue. I have a batchSize of 32 messages in host.json with maxPollingInterval 100 ms. Kafka is supposed to send at least 10-50k JSON requests every day.
How can I scale this solution for the message to be accepted by the Azure function in 1-2 seconds. My overall goal is to send the message from Kafka-Azure Queue-Azure function- CRM in 10-15 seconds.

**Comment by Ved2806** [comment]
Hi @hamhus Thank you for the feedback, we will discuss this internally and let you know about the findings soon!

**Comment by Ved2806** [comment]
Hi @hamhus Did you tried scaling up the app from the portal? please let us know if it works. Thanks.
@AnatoliB @alrod Do you have any inputs on this?
