### ISSUE TITLE
Setting linuxFxVersion has no effect on the host runtime version

### ISSUE THREAD

**Issue by ilya-git** [Azure/azure-functions-host#8478]
#### Investigative information

- Timestamp: 2022-15-06
- Function App version: 4.3.2.2
- Invocation ID: N/A
- Region: North Europe

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create an Azure function on linux consumption plan with dotnet 6
2. Run `az functionapp config show`, linuxFxVersion is set to "DOTNET|6.0"
3. Run `az functionapp config set` to set the version to `DOCKER|mcr.microsoft.com/azure-functions/mesh:4.5.2` (as described [here](https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=azurecli#manual-version-updates-on-linux))
4. Run `az functionapp config show`, linuxFxVersion is set to the new value
5. Wait until the Azure Function restarts and check the host startup logs (that are collected e.g. via diagnostics).

#### Expected behavior

I expected that the version of the host would be 4.5.2.x in this case but it does not seem to be the case. 

#### Actual behavior

This is what is shown in the logs (hostVersion of all subsequent logs is set to 4.3.2.2 as well):

> Starting Host (HostId=<id>, InstanceId=<id>, Version=4.3.2.2, ProcessId=72, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=~4)

#### Known workarounds

Unknown

#### Related information 

I have tried to use node versions of docker image an my C# application still runs, so it seems the version that I set has no effect.

**Comment by Ved2806** [comment]
Hi @pragnagopa Could you please help with this issue?

**Comment by pragnagopa** [comment]
We do not recommend pinning to older runtime version for linux consumption applications. Please let us know what is the issue you are running to that requires you to pick older version. Also, note that `4.5.2` - https://github.com/Azure/azure-functions-host/releases?page=4 is 5months old and we cannot provide support for Functions Runtimes that are older than 2 months unless there is an identified regression
