### ISSUE TITLE
Function App Connections Leak

### ISSUE THREAD

**Issue by mdarefull** [Azure/azure-functions-host#8489]
#### Investigative information

- Timestamp: June 9th 5:30 PM UTC
- Function App version: ~3
- Function App name: func-connections-cus-dev
- Function name(s) (as appropriate): GetById
- Region: Central US

In our production APIs, hosted in dedicated ASPs, we found that, after some usage, the APIs would stop connecting to our SQL On-Prems DB throwing timeout exceptions that would only get away if we restarted the Function App. 

After meticulous investigation we were able to determine the issue to be the ~1K limit of connections being hit after which, no new connection was able to be made. 

Since we follow all the guidelines for connection management, we opened a support ticket with Microsoft Support over a month ago and have been investigating since... No resolution has been made.

The given Function App is a minimal reproducible project explicitly created for this issue. We are able to provide source code and credentials if needed.

The given Function App contains the simplest of HTTP functions and leverages Entity Framework Core using its default configuration to execute a Stored Procedure hosted on an On-Prems SQL DB through a Hybrid Connection.

After the function is executed several times, all of which responded successfully, we can see how some connections remain active. With enough time, more and more connections stay active until it reaches the ~1K limit. In our last test run, over 10 days ago, we performed around 1K HTTP requests in a 30 minutes window. Up to this day, no new request has been made and the number of Active Connections has been sitting at 100.

#### Repro steps
1. Perform many requests to the Function endpoint. Over 500 requests each 30 minutes should be enough.
2. Stop performing any additional requests.
3. Check the active connection metric. 

#### Expected behavior
After some time of inactivity, I would expect all the connections to close, none to remain active.
**NOTE**: We were able to validate that our code closes the connection. In similar tests ran locally, the number of open connections go to zero always.

#### Actual behavior
Out of the total open connections (one per request), some remain active until the Function App is restarted. 
Eventually, with enough requests, the limit of ~1K hits, and no new connections can be created, resulting on timeouts.

#### Known workarounds
We have tried everything from the code side. The only way to remediate this issue has been to restart the Function App, after which the active connections drop to 0.

#### Related information 

Provide any related information 

* Programming language used .NET Core 3.1, C#.

```
public class ContractsFunction
{
  public ContractsFunction(ContractsRepository repository) => Repository = repository;

  public ContractsRepository Repository { get; }

  [FunctionName(nameof(GetById))]
  public async Task<ActionResult<Contract?>> GetById(
    [HttpTrigger(AuthorizationLevel.Function, nameof(HttpMethods.Get))] HttpRequest req)
  {
    var contract = await Repository.Get();
    return new OkObjectResult(contract);
  }
}
```
```
public class Startup : FunctionsStartup
{
  /// <inheritdoc/>
  public override void Configure(IFunctionsHostBuilder builder)
    => builder.Services
    .AddDbContextPool<ContractsDbContext>(
      options => options
      .UseSqlServer(
        Environment.GetEnvironmentVariable("DbConnectionString"),
        options => options
          .EnableRetryOnFailure()
          .CommandTimeout(180))
      .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking),
      1024)
    .AddScoped<ContractsRepository>();
}
```

**Comment by verydarkmagic** [comment]
Have you ever found the problem? We are facing similar issue with durable functions.
 Currently testing out disabling connection pool on client.

**Comment by Relki** [comment]
We're having the same problem but with asp. Net core api on a dedicated ASP. We can literally watch a chart of connections and it is just a straight 45 degree angle till it hits 8000~ connections and hits a ceiling. Then perf drops, connections are faulted etc.

We experimented by turning off health probe for that api and we can see almost a normal socket usage now. Could azure health probes not be closing connections after each probe?

**Comment by kshyju** [comment]
@mdarefull Is this still an issue you are experiencing with the latest supported version?
