### ISSUE TITLE
Introduce new app setting to control skipping null entries from event payload when sending to OOP layer

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-host#8499]
Background:
For out-of-process functions, the host code gets the trigger data from the listener/processor module & then we convert the event data object [to RPC invocation request](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.Grpc/Extensions/ScriptInvocationContextExtensions.cs#L25) instance which we will send to the out-of-process worker via GRPC. In the current implementation, we are skipping the empty entries in the [ToRpcStringArray method](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.Grpc/MessageExtensions/GrpcMessageConversionExtensions.cs#L276) which gets called internally inside [ToRpcInvocationRequest ](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.Grpc/Extensions/ScriptInvocationContextExtensions.cs#L25) method.

![Empty-Entry-Skipped-ToRpc](https://user-images.githubusercontent.com/144469/173693125-cea46e63-f582-4f5d-849a-0a725da35d35.png) 

This behavior causes confusion when dealing with batched event processing where the event body of one of the entries in the batch is `null`. The above screenshot is taken from an example where we are processing event hub messages(batched) where one of the message has null body, but the message still has valid meta properties. The oop worker will not be able to associate the meta properties of the message payload entries (message body) with the meta properties array.  See [this issue](https://github.com/Azure/azure-functions-dotnet-worker/issues/876) for a complete example.

Ask:

We need to introduce a new app setting, which when set to True, will skip the code which do the[ _null check and discard_](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.Grpc/MessageExtensions/GrpcMessageConversionExtensions.cs#L282) codepath. Default value of this setting will be "False", so no existing apps are impacted.

**Comment by fabiocav** [comment]
This would likely (ideally) be a capability advertised by the language worker as opposed to an app setting.

**Comment by wesselkranenborg** [comment]
@fabiocav: Is there any update on this? To me it looks like a small change, I can also try to contribute something but then it helps if I get some pointers where and how to change it.
