### ISSUE TITLE
Azure function queue trigger not working

### ISSUE THREAD

**Issue by navrajarch** [Azure/azure-functions-host#8501]
I wrote an azure function which will get triggered when an entry to queue is made.
After receiving data it will send a welcome email via sendgrid to the newly registered user.
The function works in Visual studio an queue trigger is fired when running in Visual studio, however when i deploy it via Visual studio publish, its not working.
It worked for first day but then the next day it just stopped and has not worked and entries in queue are not being processed.

Function App Name: isoftapifunctionsaus 
Function Name: Process Registration
Region; Australia East
Given below is my function code

using System;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using SendGrid.Helpers.Mail;

namespace APIFunctions
{
    public class ProcessRegistration
    {
        [FunctionName("ProcessRegistration")]
        public void Run([QueueTrigger("apiregistrations", Connection = "storageConnection")]string myQueueItem, ILogger log,[SendGrid(ApiKey = "SendKey")] out SendGridMessage message)
        {
            log.LogInformation($"C# Queue trigger function processed: {myQueueItem}");
            var newReg = JsonConvert.DeserializeObject<Registration>(myQueueItem);
            log.LogInformation($"User Name: {newReg.UserName}");
            log.LogInformation($"Email: {newReg.email}");
            log.LogInformation($"Conf Code: {newReg.confCode}");
            message = new SendGridMessage();

            try
            {
                message.AddTo(newReg.email);
                message.SetFrom(new EmailAddress("email-id"));
                if (newReg.type == "register")
                {
                    var mailData = new WelcomeeMailData();
                    mailData.user = newReg.UserName;
                    message.SetTemplateId("<template-id>");
                    mailData.confCode = newReg.confCode;
                    message.SetTemplateData(mailData);
                }
                else
                {
                    message.AddContent("text/html", "Welcome to our cool new website");
                    message.SetSubject("Welcome to our site");
                }

            }
            catch (Exception ex)
            {
                log.LogInformation($"Error Message: {ex.Message}");
                log.LogInformation($"Error Trace: {ex.StackTrace}");
            }

        }
    }

    public class WelcomeeMailData
    {
        public string user { get; set; }
        public string confCode { get; set; } 
    }

    public class Registration
    {
        public string UserName { get; set; }
        public string type { get; set; }
        public string email { get; set; }
        public string confCode { get; set; }
    }
}

local.settings.json

{
    "IsEncrypted": false,
  "Values": {
    "SendKey": "",
    "AzureWebJobsStorage": "",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "storageConnection": ""
  }
  }

I have created 2 settings in Azure portal for SendKey and storageconnection as well.

#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app, select `Diagnose and solve problems` from the left, and view relevant dashboards before opening your issue.

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version:
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID:
- Region:

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by surgupta-msft** [comment]
@navrajarch I noticed below exception in our logs related to your app.

```
Microsoft.Azure.Storage.StorageException : Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
```

**Comment by navrajarch** [comment]
> @navrajarch I noticed below exception in our logs related to your app.
> 
> ```
> Microsoft.Azure.Storage.StorageException : Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
> ```

Thanks for the investigation @surgupta-msft  . This might mean that there is an issue in connection string. the one working previously was valid for 1 day and i replaced it with the newer one which has 1 year validity and that connection string is working fine offline. however after updating it several times on the function app in Configuration section its still not working.
are there any logs after that?

**Comment by Ved2806** [comment]
Hi @navrajarch Thank you for the feedback we will discuss this issue internally and let you know about the findings soon.

**Comment by surgupta-msft** [comment]
@navrajarch I cannot see any logs on your app after Timestamp - 2022-06-26 11:09:49 and before that the only errors I can see are related to storage authentication.

```
Microsoft.Azure.Storage.StorageException : Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   at async Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd,IRetryPolicy policy,OperationContext operationContext,CancellationToken token)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener.ExecuteAsync(CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Queues\Listeners\QueueListener.cs : 193
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Timers.TaskSeriesTimer.RunAsync(CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Timers\TaskSeriesTimer.cs : 147
```
