### ISSUE TITLE
Function App: Missing Application Settings detected mitigation not working

### ISSUE THREAD

**Issue by imdiptanu** [Azure/azure-functions-host#8520]
#### Question
Function App -> "Diagnose and Solve problems" dashboard showing the below error -

```
Missing Application Settings detected; The following Application Settings are referenced in Function bindings but not configured in the Function App. This can cause execution errors -

Function: xxx/WorkitemFunction, Binding parameter: sbMessage, Application setting: xxSBConnection
```

![image](https://user-images.githubusercontent.com/35115483/176804202-30ede708-4c0c-42be-bcef-a36d892ba966.png)

I am using managed identity and `xxSBConnection__fullyQualifiedNamespace` is also correctly setup and the function is executing. 
Code: 
```
public void HandleWorkitemAsync(
            [ServiceBusTrigger(
                topicName: $"%{TopicubscriptionConfigPath}%",
                subscriptionName: $"%{SubscriptionConfigPath}%",
                Connection = $"{xxSBConnection}"
            )]
            string sbMessage
```

However, If I add `{"xxSBConnection": "xx.servicebus.windows.net"}`  the alert goes away, but the function is unable to connect to SB. How to fix this issue?

**Comment by savbace** [comment]
I have the same issue and it seems to be "false positive". My setting is in the format: `Storage__ConnectionString`. It's separated by double underscore which is understandable by dotnet. And function executes correctly.
However Azure complains about having the setting in the format separated by colon `Storage:ConnectionString`. Which is understandable by dotnet too. The alert looks weird for me 😕.

**Comment by snicro** [comment]
I also have the same issue.

**Comment by satvu** [comment]
Closing as it seems to be related to #8554 which was resolved and closed.
