### ISSUE TITLE
"The host is disposed and cannot be used."

### ISSUE THREAD

**Issue by d-wozniak** [Azure/azure-functions-host#8523]
#### Investigative information

- Timestamp: **_2022-07-04T13:13:56.9858889Z_**
- Function App version: **_sdkVersion: azurefunctions: 3.8.2.0_**
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: **_0404ce91-fc77-4aa1-87f2-6c4d852f5156_**
- Region: **_North Europe_**

#### Repro steps

1. The reproduction steps require the usage of the application that is responsible for triggering function app...
2. The application sends data to the function app and...
3.  Triggers some HTTP triggered functions which runs some R scripts with the usage of the R.NET package (v 1.9.0) that makes some calculations and...
4. Once the function is finished it sends items to the queue (which triggers other function).
5. At some point of the processing of the data the following error is visible in the LogStream:

`2022-07-04T13:13:56.954 [Error] Executed '...' (Failed, Id=0404ce91-fc77-4aa1-87f2-6c4d852f5156, Duration=2ms)Microsoft.Azure.WebJobs.Script.HostDisposedException : The host is disposed and cannot be used. Disposed object: 'Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedResolver'; Found IListener in stack trace: 'Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener, Microsoft.Azure.WebJobs.Extensions.Storage, Version=3.0.11.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> DryIoc.ContainerException : Container is disposed and should not be used: Container is disposed.You may include Dispose stack-trace into the message via:container.With(rules => rules.WithCaptureContainerDisposeStackTrace())at DryIoc.Throw.It(Int32 error,Object arg0,Object arg1,Object arg2,Object arg3) at D:\a\_work\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs : 9000at DryIoc.Container.ThrowIfContainerDisposed() at D:\a\_work\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs : 413at DryIoc.Container.WithCurrentScope(IScope scope,Boolean preferInterpretaion) at D:\a\_work\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs : 438at DryIoc.ResolverContext.OpenScope(IResolverContext r,Object name,Boolean trackInParent,Boolean preferInterpretation) at D:\a\_work\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs : 2709at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.WebHostServiceProvider.CreateScope() at D:\a\_work\1\s\src\WebJobs.Script.WebHost\DependencyInjection\WebHostServiceProvider.cs : 51at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedResolver.CreateChildScope(IServiceScopeFactory rootScopeFactory) at D:\a\_work\1\s\src\WebJobs.Script.WebHost\DependencyInjection\ScopedResolver.cs : 43at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.CreateScope() at D:\a\_work\1\s\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs : 106End of inner exceptionat Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.CreateScope() at D:\a\_work\1\s\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs : 110at Microsoft.Azure.WebJobs.Host.Executors.FunctionInstance.get_InstanceServices() at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInstance.cs : 52at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IFunctionInstanceEx functionInstance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs : 32at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory1.<>c__DisplayClass1_1.<.ctor>b__0(IFunctionInstanceEx i) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs : 20at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory1.Create(IFunctionInstanceEx functionInstance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs : 26at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker2.CreateInstance(IFunctionInstanceEx functionInstance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs : 44at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.Initialize() at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 793at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 104`

This behavior has been noticed once we changed the implementation to include ScopeServiceFactory (it was mentioned somewhere in the older threads that it helped)

**Initial issue**

![image](https://user-images.githubusercontent.com/44200009/177185720-17c9d974-3822-406c-9790-8425d0697306.png)

The initial issue repro steps are the same as described above. 

#### Expected behavior

- Expected behavior is to complete all the azure function invocations without an error. 

#### Actual behavior

- With a big amount of data to process some of the functions are throwing an error nondeterministic as mentioned in the repro steps. 

#### Known workarounds

- Process less data

#### Related information 

* Programming language used: C#
* Links to source: -
* Bindings used: HTTP + Queue

**Comment by surgupta-msft** [comment]
Apologies for the lack of activity here. Is this something you're still experiencing with the latest versions?
