### ISSUE TITLE
DI Scope for Function class constructor and HttpContext are different

### ISSUE THREAD

**Issue by richardszalay** [Azure/azure-functions-host#8546]
#### Investigative information

Please provide the following:

- Function App version: 4.6.1.18388

#### Repro steps

Run a basic Azure Function project with the following code:

```
public interface ISomeScopedService {}
public class SomeScopedService : ISomeScopedService  {}

public class Startup : FunctionsStartup
{
  public override void Configure(IFunctionsHostBuilder builder)
  {
    builder.Services.AddScoped<ISomeScopedService, SomeScopedService>();
  }
}


public class SampleFunction
{
  private readonly ISomeScopedService ctorInjectedService;

  public SampleFunction(ISomeScopedService service)
  {
    this.ctorInjectedService = service;
  }

  [FunctionName("SampleFunction")]
  public async Task<IActionResult> SampleFunction(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "sample")] HttpRequest request)
  {
    var httpContextService = request.HttpContext.RequestServices.GetRequiredService<ISomeScopedService>();

    var same = object.ReferenceEquals(ctorInjectedService, httpContextService);

    return new OkObjectResult(same);
  }
}

```

#### Expected behavior

The injected services are the same instance because both were resolved within the scope and the service has a scoped lifetime.

#### Actual behavior

The injected services are different instances

#### Known workarounds

Stop using constructor injection for scoped services and httpContext.RequestServices

**Comment by Ved2806** [comment]
Hi @fabiocav Could you please help with this issue?

**Comment by Ved2806** [comment]
Hi @richardszalay You may want to go through [this](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-6.0#service-lifetimes) Please let us know if it helps

**Comment by richardszalay** [comment]
Hi @Ved2806, I'm not sure how that documentation helps with this particular issue. Can you clarify why you shared that particular documentation link?
