### ISSUE TITLE
Authentication with AAD does not authenticate requests within the portal

### ISSUE THREAD

**Issue by ChrisAllisonMalta** [Azure/azure-functions-host#8567]
When I turn on MS AAD authentication in the Azure Function in the portal I CANNOT execute any functions, even within the portal let alone in client apps. 

#### Investigative information

Please provide the following:

- Timestamp: 22.07.2022 17:00 CET (approx)
- Function App version: 4
- Function App name: TestingMSAuth
- Function name(s) (as appropriate): TestMSAuth
- Invocation ID: 
- Region: France Central 

#### Repro steps

Provide the steps required to reproduce the problem:

Create a new hello world Functions App in VS Mac
Publish to a new resource in Azure
Turn on Authentication and create a new identity provider (Microsoft)

All using default settings

IF I click on the autogenerated log in redirect url ({APP NAME}.auth/login/aad/callback) and log in, i can call my function. However I can't call that same function with the same log in from within the portal (Functions > {FunctionName} > Code and Test) I get returned a 401 unauthenticated exception

#### Expected behavior

Calling a GET will return: "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."

#### Actual behavior

401 response: "You do not have permission to view this directory or page. "

#### Related information 

Provide any related information 

* Below is all the source code

<details>
<summary>Source</summary>

```csharp
using System;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace TestMSAuth
{
    public static class TestMSAuth
    {
        [FunctionName("TestMSAuth")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            string name = req.Query["name"];

            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name = name ?? data?.name;

            string responseMessage = string.IsNullOrEmpty(name)
                ? "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."
                : $"Hello, {name}. This HTTP triggered function executed successfully.";

            return new OkObjectResult(responseMessage);
        }
    }
}
```
</details>

**Comment by Ved2806** [comment]
Hi @ChrisAllisonMalta Thanks for your feedback, we are reproducing this issue and discussing it internally and will let you know about the findings soon.

**Comment by ChrisAllisonMalta** [comment]
> Hi @ChrisAllisonMalta Thanks for your feedback, we are reproducing this issue and discussing it internally and will let you know about the findings soon.

Thanks @Ved2806 , I had also logged a support ticket (TrackingID#2207190050001558) in Azure on this issue and the wider problem its causing me, there maybe some extra data in there that helps

**Comment by ChrisAllisonMalta** [comment]
Hi @Ved2806  any update on this? I'm trying to run an app in production and without being able to use authentication properly is a headache.

**Comment by Ved2806** [comment]
Hi @ChrisAllisonMalta as per the repro steps given by you, It is not working while creating functions in VS Mac. Could you please confirm that if it is working as expected with VS windows? so that we can focus on Mac part

**Comment by ChrisAllisonMalta** [comment]
> Hi @ChrisAllisonMalta as per the repro steps given by you, It is not working while creating functions in VS Mac. Could you please confirm that if it is working as expected with VS windows? so that we can focus on Mac part

Hi Ved, sorry I don't have access to a windows machine. Its a simple hello world app so should be easily reproducible at MS (which you imply you have done)

**Comment by mattchenderson** [comment]
I read this as a portal feature request. The system technically is working as expected, but it could be made easier to use. Because no token is attached on the request which is being constructed in the test/run experience, the system rejects it. The cookie that might have been set during a prior login is similarly not presented in the API model of this request as constructed. The portal experience does not capture any identity context and therefore cannot present the token itself, and if it did, it would need to be explicit, so grabbing the token and adding it as a header would just be as a convenience.  So, the request is valid - the portal could conceptually present a flow to log the user in and populate that header. However, this would not be a high-priority item.

**Comment by ChrisAllisonMalta** [comment]
> I read this as a portal feature request. The system technically is working as expected, but it could be made easier to use. 

Hi @mattchenderson thanks for looking at this, it may be the case that the system is working how it should right now however my point , albeit not written explicitly here but communicated multiple times directly to Microsoft, is that it USED to work that way. I know memory is fallible but Im 99% sure I was trouble shooting API calls in the portal with AAD before there was an upgrade to EasyAuth.
