### ISSUE TITLE
Dependency Update ApplicationInsights 2.21

### ISSUE THREAD

**Issue by czb182** [Azure/azure-functions-host#8573]
I want to consume recently released ApplicationInsights 2.21 SDK.  I believe it is required to reference the same version of SDK as referencing by azure functions host, so requesting azure functions host AI SDK be updated from 2.20 to 2.21

**Comment by Ved2806** [comment]
Hi @czb182 Thank you for the feedback, we will discuss this internally and let you know about the findings soon

**Comment by Ved2806** [comment]
Hi @czb182 AppInsights SDK has been updated to 2.21.0

**Comment by czb182** [comment]
link to commit?  I don't see.

**Comment by czb182** [comment]
functions host still references 2.20, not sure where you are seeing 2.21.

**Comment by Ved2806** [comment]
Hi @czb182 Please check [here](https://www.nuget.org/packages/Microsoft.ApplicationInsights)

**Comment by czb182** [comment]
I don't follow.  That just a link to application insights.  My defect was to have azure functions host consume latest AI sdk.
