### ISSUE TITLE
413 Request entity too large

### ISSUE THREAD

**Issue by ADRaks** [Azure/azure-functions-host#8586]
Fixed with #5820

_Originally posted by @fabiocav in https://github.com/Azure/azure-functions-host/issues/5548#issuecomment-607464343_

Hi I am also facing the same problem, from your fix i couldn't understand which fix i need to use. 

I am using Azure function app Http trigger and if i try to upload a file of more than 100MB than 413 Request entity too large error throwing.

**Comment by ADRaks** [comment]
@madelinegordon  can you please help on this ?

**Comment by wbail** [comment]
Hi @ADRaks, how are you?

The max request body size is 100MB.

As a suggestion, you could try blob trigger:

- https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-overview
- https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob?tabs=in-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp

**Comment by soninaren** [comment]
> Hi @ADRaks, how are you?
> 
> The max request body size is 100MB.
> 
> As a suggestion, you could try blob trigger:
> 
> * https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-overview
> * https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob?tabs=in-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp

The info here is accurate.  Closing this as it is by design
