### ISSUE TITLE
Question about retry policy support status for `CosmosDBTrigger`

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-functions-host#8591]
#### Is your question related to a specific version? If so, please specify:

Azure Functions v4

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 

All

#### Question

We have already set a retry policy for `CosmosDBTrigger` to prevent Change Feed checkpoints from advancing on failure, ensuring reliable processing without data loss.

e.g. https://dev.to/shibayan/a-quick-review-of-the-azure-functions-new-feature-retry-policy-p56

However, the documentation notes that retry policies other than Timer and Event Hubs are no longer supported. The loss of retry support in `CosmosDBTrigger` has a very large impact and reduces the reliability of the application.

- https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=fixed-delay%2Cin-process&pivots=programming-language-csharp

>The retry policy support in the runtime for triggers other than Timer and Event Hubs is being removed after this feature becomes generally available (GA). Preview retry policy support for all triggers other than Timer and Event Hubs will be removed in October 2022.

Will a built-in retry be implemented in `CosmosDBTrigger` by 2022/10? If there are no plans to do so, support by retry policy should not be removed.

**Comment by Ved2806** [comment]
Hi @ealsur Could you please help with this issue?

**Comment by ealsur** [comment]
Our extension code does not include any Retry behavior. This was already discussed at https://github.com/Azure/azure-webjobs-sdk-extensions/issues/783#issuecomment-1221139195 and it seems it was something Functions added on top of all Triggers.

**Comment by shibayan** [comment]
Thanks for your comment. I will review the linked Issue and make additional comments if necessary, so I will close this Issue.
