### ISSUE TITLE
ExtensionMetadataGenerator hangs when calling TypeReference.Resolve on some system attributes

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-host#8597]
This line of code hangs when running extension metadata generator on certain system attributes.

https://github.com/Azure/azure-functions-host/blob/b5e21770905343a3a58a6614c0a32ec3d80f1860/tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator.Console/ExtensionsMetadataGenerator.cs#L95

#### Repro
Call ExtensionsMetadataGenerator.Generate on the assemblies in [drop.zip](https://github.com/Azure/azure-functions-host/files/9238646/drop.zip)

**Comment by plukawski** [comment]
I am facing exactly the same issue - prevents me from using the newer versions of this nuget because this makes the build to never end.

**Comment by soninaren** [comment]
Resolved in #8772
