### ISSUE TITLE
Additional logging and cleanup for gRPC RX

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-host#8604]
Follow up issue to clean up & address comments for: [remove RX as the primary pipe for gRPC communications](https://github.com/Azure/azure-functions-host/pull/8281#top):

- [x] Add log to exception caught in the `ProcessItem` method in `GrpcWorkerChannel`
- [x] Create issue to track multistream capability configuration

**Comment by fabiocav** [comment]
Assigning to the sprint to capture details and create issues for the work we need to complete.
