### ISSUE TITLE
Selective loading of extensions in Host in case of Stein (WorkerIndexing)

### ISSUE THREAD

**Issue by surgupta-msft** [Azure/azure-functions-host#8614]
Currently, in case of Worker Indexing, Host loads all the extensions as it does not have function metadata available at that time for filtering out extensions that are not needed. This issue is to enable selective loading of extensions in case of Stein.

**Comment by surgupta-msft** [comment]
Design doc - [Link](https://dev.azure.com/msazure/One/_git/AAPT-Antares-Docs?version=GBmaster&path=/TeamDocs/FunctionTeamDocs/Design/Host/SelectiveLoadingOfExtensions.md) 

There is also a _deep dive_ document in-progress mentioning sequence of events in Host code in legacy and stein scenarios and explaining which classes will be impacted as part of the proposed approach for selectively loading extensions.

**Comment by fabiocav** [comment]
Currently iterating on the design. Moving to sprint 132 to close on that work.

**Comment by fabiocav** [comment]
Closing this item as we have the initial design in place. 

@surgupta-msft , can you please link the implementation item here once you have that?

**Comment by surgupta-msft** [comment]
Here is the link tracking implementation of this work - https://github.com/Azure/azure-functions-host/issues/8870
