### ISSUE TITLE
[Custom Handlers] Returning Binary Content from the function

### ISSUE THREAD

**Issue by xlight05** [Azure/azure-functions-host#8622]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
Custom Handlers
#### Question
Similar to  #5656, I just want to read bytes from a file and send that as the response to the caller of the function.(HTTP Trigger and HTTP Output).  How do I do this? What I did was, I tried having(and not having) dataType = "binary" in the functions.json  and included base64 string of  the file as the body of the response. When the function gets invoked a file gets downloaded but its a text file(not what was served from the code). how do we handle this?

```json
{
  "bindings": [
    {
      "type": "httpTrigger",
      "authLevel": "anonymous",
      "methods": [
        "get"
      ],
      "direction": "in",
      "name": "httpPayload",
      "route": "hello/nonHttpResTest3"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "resp",
      "dataType": "binary"
    }
  ]
}
```
Sample response json

```
{"Outputs":{"resp":{"statusCode":"200", "headers":{"Content-Type":"application/octet-stream"}, "body":<base64 encoded string of the file>}}, "Logs":[], "ReturnValue":null};
```

Sample file that got downloaded(This is supposed to be a  png screenshot) - https://gist.github.com/xlight05/62eb66f25aecb9433b9748a3e313f5b4 

@mhoeger

**Comment by Ved2806** [comment]
Hi @xlight05 Thank you for the feedback, we are investigating this issue further and will let you know about the findings soon

**Comment by Ved2806** [comment]
Hi @xlight05 I decoded the sample file that you have attached and it gives me an image file which is of .png type. You will need to decode the downloaded file for getting the expected result. Thanks.

**Comment by xlight05** [comment]
> Hi @xlight05 I decoded the sample file that you have attached and it gives me an image file which is of .png type. You will need to decode the downloaded file for getting the expected result. Thanks.
@Ved2806 
Yes true, where should the decoding happen? Is the response json im returning correct?  Shouldn't the azure platform do the decoding part before sending the response back to the user?
