### ISSUE TITLE
How to increase request size limit on an isolated host on Linux?

### ISSUE THREAD

**Issue by Psymingz** [Azure/azure-functions-host#8661]
#### Is your question related to a specific version? If so, please specify:
Hosting: P1V2 Linux Plan
Microsoft.Azure.Functions.Worker.Sdk: 1.3.0
Microsoft.Azure.Functions.Worker: 1.8.0
Microsoft.Azure.Function.Worker.Extensions.Http: 3.0.13
Function Runtime Version: ~4
TargetFramework: .NET 6.0
AzureFunctionsVersion: v4

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
Hi there.

I'm experiencing issues with Azure Functions when attempting to POST large multipart/form-data requests.
I have tested with a few different request sizes and it seems like the issue arises when request size is > 30mb.

Following error message is returned with a HTTP statuscode of 413: "_The page was not displayed because the request entity is too large._"

The request never hits the function (verified from Application Insights).

I cannot reproduce it locally and I expect it's because the limits are handled by Azure somehow and therefore not enforced locally.

[According to this documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#service-limits), the request size limit should be 100mb as we are running on a premium linux plan (P1V2)

[This part of the Azure Functions documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=isolated-process%2Cfunctionsv2&pivots=programming-language-csharp#content-types) states that the limit for HttpTriggers should be defined in the web.config.

**My assumption** is that a web.config is related to ASP.NET Core and not isolated Azure functions so I'm a bit confused.

I need some guidance in how I can allow request sizes up to 100mb.

Thanks!

**Comment by Ved2806** [comment]
Hi @pragnagopa Could you please help with this issue?

**Comment by Ved2806** [comment]
Hi @pragnagopa Is there any input from your side?

**Comment by Psymingz** [comment]
Update:
We are hosting the Function Apps as a backend to Azure Static Web App frontend that proxies the requests to the backend.

It seems the request limit for Azure Static Web Apps is 30MB.
