### ISSUE TITLE
Scale controller shuts function down when using QueueTrigger with ":" in connection string

### ISSUE THREAD

**Issue by mariusz-rubin** [Azure/azure-functions-host#8665]
- Timestamp: 2022-08-25T08:01:23.661Z
- Function App version: 4.9.0.18814, C# isolated-process
- Invocation ID: 97b39b3a-5de8-4902-9ab0-82d18816f2e6
- Region: Norway East

#### Repro steps

Create a function with `QueueTrigger` that has `ConnectionString` set to a nested app setting with a ":". 

```csharp
[Function("FunctionName")]
public async Task Run(
            [QueueTrigger("queueName", Connection = "MyStorageAccount:ConnectionString")] string message,
            FunctionContext context)
{ ...
```

In the Azure Portal in Application settings set the connection string to the storage account with the setting name in the format: `MyStorageAccount__ConnectionString` 

After deploying the function to Azure it connects to the queue and starts to process messages.
After some period of time (from 30 min to one hour) the function is shut down, even though in the queue are still 2000 messages.
In the AppTraces logs appears:
```
- DrainMode mode enabled
- Calling StopAsync on the registered listeners
- Stopping the listener 'Microsoft.Azure.WebJobs.Extensions.Storage.Common.Listeners.QueueListener' for function 'FunctionName'
- Call to StopAsync complete, registered listeners are now stopped
- Stopped the listener 'Microsoft.Azure.WebJobs.Extensions.Storage.Common.Listeners.QueueListener' for function 'FunctionName'
```

After enabling logs from the scale controller in app settings with `SCALE_CONTROLLER_LOGGING_ENABLED` I noticed that the scale controller cannot connect to the storage account with the specified connection string:
```
- Specified connection string is null or empty for connection: MyStorageAccount:ConnectionString. Invalid connection.
- Function app does not contain any active triggers.
```

I wasn't able to use in `QueueTrigger` an app setting name with '__' separator `MyStorageAccount__ConnectionString`. The function cannot start locally.

After changing the connection string to a simple app setting without nesting `MyStorageAccountConnectionString`, the scale controller was able to connect. It started to scale function properly and doesn't unexpectedly shut down the function.

#### Expected behavior

The scale controller should be able to connect to the storage account queue using a nested app setting with a ":".
Another solution is to forbid using the ":" as a separator in the `ConnectionString` in the `QueueTrigger` attribute.

This would save hours of investigation why the function is unexpectedly stopped without a reason.

#### Actual behavior

The function is shut down after about 30 minutes to an hour without a reason specified in the logs, even though there are messages in the queue waiting to be processed.

#### Known workarounds

Not using nested app settings with a ":" in the `ConnectionString` property for the `QueueTrigger`.

**Comment by Ved2806** [comment]
Hi @mariusz-rubin Could you please share the function app name for the deeper investigation?

**Comment by ghost** [comment]
We just ran into this same issue exactly as described by @mariusz-rubin. Would be good to further investigate this.
