### ISSUE TITLE
Can this workaround be removed?

### ISSUE THREAD

**Issue by PehrGit** [Azure/azure-functions-host#8681]
Hi, the code referenced below says ` // Workaround until https://github.com/Azure/azure-functions-host/issues/7188 is addressed.`. It seems that #7188 has since been fixed, can this sleep now be removed? It would be very helpful for us to not keep our pods running longer than they have to.

https://github.com/Azure/azure-functions-host/blob/b3d90c43e7a510ab0930202a3ed924249bb7e66c/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs#L799

**Comment by kshyju** [comment]
@pragnagopa @liliankasem Do you have insights on the impact of the change requested here?

**Comment by liliankasem** [comment]
> @pragnagopa @liliankasem Do you have insights on the impact of the change requested here?

If it's closed, I would assume that we can remove that todo item, but @pragnagopa @soninaren and @alrod might have more context here

**Comment by PehrGit** [comment]
Thanks for the replies so far, any new insights? The hardcoded 10 minutes is an issue for us in 2 ways:
- For some function apps, we only have short-running functions so there's no need to wait the full 10 minutes to shut down
- For others, we have some long running functions that may need more than 10 minutes to finish

So it would be very nice if the hardcoded sleep of 10 minutes can be removed

**Comment by npalmius** [comment]
Any further thoughts on this issue @liliankasem @pragnagopa ? It would be great if this could be resolved, for the reasons that @PehrGit describes.

**Comment by liliankasem** [comment]
We're discussing with the appropriate teams if we can remove the workaround or not, will update here once I have more information.

In the meantime, @PehrGit found a way around this and documented their process here:

- https://github.com/Azure/azure-functions-docker/issues/677#issuecomment-1309909598

**Comment by npalmius** [comment]
Hi @liliankasem, has this been released?

I can see it in the release notes for [v4.27.5](https://github.com/Azure/azure-functions-host/releases/tag/v4.27.5):

>  * Update WebJobsScriptHostService to remove hardcoded sleep during application shut down (https://github.com/Azure/azure-functions-host/pull/9520)

but I upgraded to image `azure-functions/python:4.27.5-python3.11-slim`, which appears to be running v4.27.5.5:

```
info: Host.Startup[401]
      Starting Host (HostId=..., InstanceId=1b65a633-4363-4c36-9a07-70d05ffb027c, Version=4.27.5.5, ProcessId=9, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))
```

and 10 minute delay still appears to be there.
