### ISSUE TITLE
Log stream shows logs from all apps/functions

### ISSUE THREAD

**Issue by arynaq** [Azure/azure-functions-host#8689]
I couldn't find any related issues here (might be my lacking search-fu) but we are seeing some weird/unexpected behavior in azure function app log streaming (in Function App -> Monitor -> Log stream) in the portal. I suspect the weird behavior is caused by the fact that we have more than one app / function streaming to the same app insights instance, but that I gather to be the whole point, to have centralized logging on the platform.

There are two issues:

**Issue A**
- We notice the log stream shows app insight logs from all of the other apps / function apps that log to the same instance
- This makes it very hard to pick up logs from the actual function we are looking at

**Issue B**
- Switching from app insights logs to filesystem logs (still in the Log Stream UI) renders the UI blank
- Nothing shows up, the console clearly logs the action `2022-08-31T10:49:33.460Z [info][LogStreamFrameBladeReact][selectedLoggingOption][clicked] `
- Only refresh renders the view back to normal (with default stream of applicaiton insights)

#### Investigative information

Please provide the following:

- Timestamp: `022-08-31T10:49:33.460Z`
- Function App version: `3.12.1.0`
- Function App name: `hansalgoliasyncprodapp`
- Function name(s) (as appropriate): `N/A`
- Invocation ID: Happens regardless, example `2ebb2e1f-a503-4ab5-a59f-e639c95d90ed`
- Region: `Norway East`

#### Repro steps

Provide the steps required to reproduce the problem:

1. Log to same app insights instance from more than one function app
2. Go to any of the above function apps -> Monitoring -> Log Stream
3. Application insights log stream shows logs from other function apps (and other apps in general)
4. Filesystem logs does not load (blank UI)

#### Expected behavior

- Log streaming should be scope down to function app in portal
- Selecting filesystem logs should not render UI blank

#### Actual behavior

- Log streaming shows logs from all apps/functions on the same app insights instance
- Switching to filesystem logs render the stream log view in UI blank

#### Known workarounds

Be slower in iterations and wait for actual logs in app insights so traces can be filtered with KQL, not optimal.

**Comment by DBJDBJ** [comment]
Try AF tagging perhaps?

https://www.codeproject.com/Tips/5294072/Add-tags-to-Azure-functions-Application-Insights

**Comment by kshyju** [comment]
@RohitRanjanMS Could you help with this question?

**Comment by RohitRanjanMS** [comment]
thanks @kshyju, I will have a look at it.

**Comment by RohitRanjanMS** [comment]
Hi @arynaq we don't apply any filter on the log stream. You see everything that is getting logged in AI. You have some ability to apply filters when you go to "Open in Live Metrics" or open it directly from ApplicationInsights.

**Comment by DBJDBJ** [comment]
> Hi @arynaq we don't apply any filter on the log stream. You see everything that is getting logged in AI. You have some ability to apply filters when you go to "Open in Live Metrics" or open it directly from ApplicationInsights.

One might think the issue is not having one log stream per one Azure Function.

**Comment by RohitRanjanMS** [comment]
Hi @arynaq, it's a fair expectation, probably the confusion is because you are viewing it from a specific function app. Streaming is AI capability; we only fetch the logs from AI and show it in on the portal without any filter.
