### ISSUE TITLE
Cannot bind POCO to return value of function

### ISSUE THREAD

**Issue by ZainRizvi** [Azure/azure-functions-host#869]
Binding the return value of a function to an output causes the error:

Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.ReturnOutputTest'. Microsoft.Azure.WebJobs.Host: Can't bind Blob to type 'Submission#0+Poco&'. 

#### Repro steps

Create a function with an output bound to a blob.  I triggered my function using a manual trigger.  Here's the code:

```
using System;

public static Poco Run(string input, TraceWriter log)
{
    log.Info($"C# manually triggered function called with input: {input}");
    return new Poco {
        MyString = "input",
        myDateTime = DateTime.Now
    };
}
 
public class Poco {
    public string MyString {get; set; }
    public DateTime myDateTime {get; set;}
}
```

Bindings:
```
{
  "bindings": [
    {
      "type": "blob",
      "name": "$return",
      "path": "testoutput/{rand-guid}",
      "connection": "AzureWebJobsDashboard",
      "direction": "out"
    },
    {
      "type": "manualTrigger",
      "name": "input",
      "direction": "in"
    }
  ],
  "disabled": false
}
```
#### Expected behavior

Binding works and outputs value to blob

#### Actual behavior

The binding fails.

Compiling the function gives the error:
`Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.ReturnOutputTest'. Microsoft.Azure.WebJobs.Host: Can't bind Blob to type 'Submission#0+Poco&'.
`

You see this error when switching to the Develop tab in the portal:

```
Error:

Function ($ReturnOutputTest) Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Functions.ReturnOutputTest'. Microsoft.Azure.WebJobs.Host: Can't bind Blob to type 'Submission#0+Poco&'.
Session Id: 2d0750255192418fb22ae96f623db8df

Timestamp: 2016-11-03T18:23:09.194Z
```

**Comment by mathewc** [comment]
@fabiocav Perhaps this issue was resolved by your commit https://github.com/Azure/azure-webjobs-sdk-script/commit/20f6b2004e783012ae68f010fa6045f7d914ab66?

**Comment by fabiocav** [comment]
Not this issue. Need to repro this to see what is going on. Was focused on other items and #870 today.

**Comment by vishnukumarwatchfinder** [comment]
Hi, 
Is this issue resolved because I am facing the same problem.

**Comment by fabiocav** [comment]
Closing stale issue. This is no longer applicable
