### ISSUE TITLE
Azure Cosmos DB trigger and bindings for Azure Functions 4

### ISSUE THREAD

**Issue by iAmBipinPaul** [Azure/azure-functions-host#8709]
I see `Microsoft.Azure.WebJobs.Extensions.CosmosDB` is in preview for v4 and `Document` is now private class.
What is recommended version to use `CosmosDBTrigger` with v4 function ?

**Comment by satvu** [comment]
Closing as the package has been GA for a while. Further information about CosmosDB triggers in V4 can be found [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-trigger?pivots=programming-language-csharp&tabs=python-v2%2Cin-process%2Cextensionv4).
