### ISSUE TITLE
Upgrade to V4 from V3 Azure Function fails with 500 error.

### ISSUE THREAD

**Issue by dabarney1** [Azure/azure-functions-host#8717]
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Azure.WebJobs.Host;
using AD = Microsoft.IdentityModel.Clients.ActiveDirectory;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System.Data;
using System.Text;

namespace AASRefreshFunctions
{
    /// <summary>
    /// The Class where the functions reside.
    /// </summary>
    public static class AASRefreshFunction
    {
        /// <summary>
        /// Processes the model.
        /// </summary>
        /// <param name="req">The req.</param>
        /// <param name="log">The log.</param>
        /// <param name="context">The context.</param>
        /// <returns>The URL of the created resource.</returns>
        [FunctionName("ProcessModel")]
        public static async Task<HttpResponseMessage> ProcessModel([HttpTrigger(AuthorizationLevel.Anonymous,
            "post", Route = null)]HttpRequestMessage req,
            ILogger log,
            ExecutionContext context)
        {
            log.LogInformation("HTTP trigger function called to process the model");

            // Read the config values.
            var config = new ConfigurationBuilder()
                .SetBasePath(context.FunctionAppDirectory)
                .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
                .AddEnvironmentVariables()
                .Build();
            log.LogInformation("Read the settings");

            // Get the input parameters: Server, Model, processing mode
            var data = await req.Content.ReadAsAsync<ProcessModelRequest>();
            log.LogInformation("Read Input");

            // Form the Post request to the Analysis server
            HttpClient client = HttpClientFactory.Create();
            client.BaseAddress = new Uri(config["SSASBaseUrl"]);

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer",
                await GetAuthToken(config, log));

            log.LogInformation("Created the request");
            HttpResponseMessage response = await client.PostAsJsonAsync($"{data.ServerName}/models/{data.ModelName}/refreshes", data);
            log.LogInformation("Returning the response");

            // return URI of the created resource. The location header contains the refresh id

            GetProcessStatusRequest reqresult = null;
            reqresult = new GetProcessStatusRequest();
            reqresult.RefreshUrl = response.Headers.Location.ToString();
            return new HttpResponseMessage(response.IsSuccessStatusCode ? HttpStatusCode.OK : HttpStatusCode.InternalServerError)
            {
                Content = new StringContent(JsonConvert.SerializeObject(reqresult), Encoding.UTF8, "application/json")
            };
         }

        /// <summary>
        /// Gets the process status.
        /// </summary>
        /// <param name="req">The req.</param>
        /// <param name="log">The log.</param>
        /// <param name="context">The context.</param>
        /// <returns>The status of the Requested Process.</returns>
        [FunctionName("GetProcessStatus")]
        public static async Task<HttpResponseMessage> GetProcessStatus([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequestMessage req,
            ILogger log,
            ExecutionContext context)
        {
            log.LogInformation("HTTP trigger function called to Get the Process Status");

            // Read the config values.
            var config = new ConfigurationBuilder()
                .SetBasePath(context.FunctionAppDirectory)
                .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
                .AddEnvironmentVariables()
                .Build();
            log.LogInformation("Read the Settings");

            // Form the Post request to the Analysis server
            HttpClient client = HttpClientFactory.Create();
            var ReqResult1 = "result";
            try
            {
                ReqResult1 = await req.Content.ReadAsStringAsync();
                JsonSerializerSettings serSettings1 = new JsonSerializerSettings();               
                client.BaseAddress = new Uri((JsonConvert.DeserializeObject<GetProcessStatusRequest>(ReqResult1,serSettings1)).RefreshUrl);
            }
            catch (Exception ex)
            {
                log.LogError(ex.Message,ex);
                log.LogError(ex.StackTrace);
                throw;
            }

            log.LogInformation("Read Input");
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", await GetAuthToken(config, log));
            log.LogInformation("Created the request");
            HttpResponseMessage response = await client.GetAsync("");
            log.LogInformation("Got the response");
            GetStatusResponse objectresult = null;
            var Reqresult = "result";
            try
            {
                 Reqresult  = await response.Content.ReadAsStringAsync();
                 JsonSerializerSettings serSettings = new JsonSerializerSettings();               
                 objectresult = JsonConvert.DeserializeObject<GetStatusResponse>(Reqresult,serSettings);
            }
            catch (Exception ex)
            {
                log.LogError(ex.Message,ex);
                log.LogError(ex.StackTrace);
                throw;
            }
            log.LogInformation("objectresult " + objectresult.status);
            log.LogInformation("objectresult " + objectresult.Messages);
            log.LogInformation("Client bassaddres " +client.BaseAddress);
            log.LogInformation("Returning the response");
 
            // return URI of the created resource. The location header contains the refresh id
            var finalResponse = new GetProcessStatusResponse()
            {
                Status = objectresult.status,
                Messages = objectresult.Messages
            };
            log.LogInformation("After finalResponse");

            return new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(JsonConvert.SerializeObject(finalResponse), Encoding.UTF8, "application/json")
            };
        }

        /// <summary>
        /// Gets the authentication token.
        /// </summary>
        /// <param name="config">The configuration.</param>
        /// <param name="log">The log.</param>
        /// <returns>The Auth Token for the provided client.</returns>
        private static async Task<string> GetAuthToken(IConfigurationRoot config, ILogger log)
        {
            log.LogInformation("Start Get Auth Token");
            AD.AuthenticationContext authenticationContext = new AD.AuthenticationContext(config["AADDomain"]);
            AD.AuthenticationResult authResult = await authenticationContext.AcquireTokenAsync(config["Resource"],
                new AD.ClientCredential(config["ClientID"], config["ClientSecret"]));
            log.LogInformation("End Get Auth Token");
            return authResult.AccessToken;
        }
    }

    /// <summary>
    /// The GetProcessStatusRequest class
    /// </summary>
    public class GetProcessStatusRequest
    {
        public string RefreshUrl { get; set; }
    }

    public class GetProcessStatusResponse
    {
        public string Status { get; set; }
        public List<Message> Messages { get; set; }
    }

    public class Message
    {
        public string message { get; set; }
        public string type { get; set; }
        public string code { get; set; }
        public Location location { get; set; }
    }

    public class Location
    {
        public SourceObject sourceObject { get; set; }
    }

    public class SourceObject
    {
        public string table { get; set; }
        public string partition { get; set; }
    }

    /// <summary>
    /// The request class for the ProcessModel method.
    /// </summary>
    public class ProcessModelRequest
    {
        public string CommitMode { get; set; }
        public int MaxParallelism { get; set; }
        public List<object> Objects { get; set; }
        public int RetryCount { get; set; }
        public string Type { get; set; }

        public string ServerName { get; set; }

        public string ModelName { get; set; }
    }

    /// <summary>
    /// The objects class.
    /// </summary>
    public class Object
    {
        public string table { get; set; }
        public string partition { get; set; }
        public string status { get; set; }
    }

    /// <summary>
    /// The Status response class.
    /// </summary>
    public class GetStatusResponse
    {
        public DateTime startTime { get; set; }
        public DateTime endTime { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public string currentRefreshType { get; set; }
        public List<Object> objects { get; set; }
        public List<Message> Messages { get; set; }
    }
}

**FULL CODE ABOVE**

Upgrade` to V4 from V3 Azure Function fails with 500 error.  if FUNCTIONS_V2_COMPATIBILITY_MODE is added then it works.
V3 and V2 will not be supported after December 2.
After; changing the code below, it works without the FUNCTIONS_V2_COMPATIBILITY_MODE set.

  New Code

 // return URI of the created resource. The location header contains the refresh id

            GetProcessStatusRequest reqresult = null;
            reqresult = new GetProcessStatusRequest();
            reqresult.RefreshUrl = response.Headers.Location.ToString();
            return new HttpResponseMessage(response.IsSuccessStatusCode ? HttpStatusCode.OK : HttpStatusCode.InternalServerError)
            {
                Content = new StringContent(JsonConvert.SerializeObject(reqresult), Encoding.UTF8, "application/json")
            };

OLD Code
           // return URI of the created resource. The location header contains the refresh id
            return req.CreateResponse(response.IsSuccessStatusCode ? HttpStatusCode.OK : HttpStatusCode.InternalServerError
                , new GetProcessStatusRequest() { RefreshUrl = response.Headers.Location.ToString() });

**Comment by mathewc** [comment]
If your function is working correctly now on v4, that's great and it seems you no longer have an issue. To clarify, the December 3 date mentioned [here](https://azure.microsoft.com/en-us/updates/extended-support-for-microsoft-net-core-31-will-end-on-3-december-2022/) just means we'll no longer be providing support/fixes for v2/v3 Function Apps, however those apps will continue to run. But it's good you've made the migration :)

Regarding the specific code you called out above from your, ProcessModel method, I have the following questions:

-  because you're returning an HttpResponseMessage, the return type of your function should be `Task<HttpResponseMessage>` not `Task`
- is it safe for this function be "Anonymous"?
