### ISSUE TITLE
Azure Function output trace level log in log stream with information level in host.json

### ISSUE THREAD

**Issue by RetYn** [Azure/azure-functions-host#8719]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app, select `Diagnose and solve problems` from the left, and view relevant dashboards before opening your issue.

#### Investigative information

log level in host.json is 
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true,
                "excludedTypes": "Request"
            }
        }
    }
}
When I run azure function locally, the console window does not output any [verbose] level log
But when I deployed to azure, and I can [verbose] debug level log in log stream
![image](https://user-images.githubusercontent.com/7384252/189155491-16f02dc0-46a3-4401-a78e-de515bf0e3a0.png)
Httpclient debug level log will also print httpheader for each request.
That will leak our authorization within HTTP request header.
Function version is v4.

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

The function should not output any [verbose] level log

#### Actual behavior

The function output any [verbose] level log
![image](https://user-images.githubusercontent.com/7384252/189104959-1fbb1cdb-580b-494c-bb3d-d3ebf2e38202.png)

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

</details>
-->

**Comment by RohitRanjanMS** [comment]
This is addressed through this [PR ](https://github.com/Azure/azure-webjobs-sdk/pull/3002).
