### ISSUE TITLE
System Assigned Managed Identity to avoid WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and WEBSITE_CONTENTSHARE

### ISSUE THREAD

**Issue by seemano** [Azure/azure-functions-host#8740]
Hi,

I have function app v4(recently migrated from v2). it has various connection strings WebJobsQueuesConnectionString, WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and AzureWebJobsStorage. Premim app service plan

As part of MSI implementation, i manged to get rid of WebJobsQueuesConnectionString and AzureWebJobsStorage by replacing them with AzureWebJobsStorage__accountName and WebJobsQueuesConnectionString__queueServiceUri.

I have followed the thread https://github.com/Azure/azure-functions-host/issues/8135 **to get rid of** WEBSITE_CONTENTAZUREFILECONNECTIONSTRING but my function is not making successfull connection to storage and not working as expected any input will be appreciated.

I get below messages on function home page.
![image](https://user-images.githubusercontent.com/42339769/190027914-878dc01c-2869-4be4-a938-937d2316e882.png)

I get below message when click on functions in my function app
![image](https://user-images.githubusercontent.com/42339769/190028013-c4ee424f-5a82-48c1-a295-e3261b956341.png)

**Comment by surgupta-msft** [comment]
There is updated guidance [here](https://github.com/Azure/azure-functions-host/issues/8135#issuecomment-1668708396) and the docs are also getting updated to avoid any confusion related to this. Let us know if you are still experiencing the issue.
