### ISSUE TITLE
Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 when using Fiddler

### ISSUE THREAD

**Issue by kornakar** [Azure/azure-functions-host#8749]
When trying to debug an Azure Function (.NET 6.0, isolated, http trigger) while Fiddler Classic is running as a proxy, I get this exception.

.NET 3.1 function works fine (with or without Fiddler) and also .NET 6 function works fine **without** Fiddler running.

The exception is raised in Main method on the line await host.RunAsync();

Can I force it to use http 1 while debugging? Fiddler is a must-have tool for http trigger functions.

Workaraound is of course to **not** use isolated functions, but I would like to try them out.

```
Grpc.Core.RpcException: 'Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.", DebugException="System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.
   at System.Net.Http.HttpConnectionPool.ThrowGetVersionException(HttpRequestMessage request, Int32 desiredVersion)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Shared.TelemetryHeaderHandler.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")'
```

**Comment by jviau** [comment]
Isolated functions uses gRPC, which relies on HTTP/2, which from what I can tell is not supported by fiddler. This is due to several security features and implementation details of gRPC and HTTP/2 which makes it incompatible with Fiddler. Unfortunately, this issue is out of our hands and would be up to Fiddler to work out.

> Fiddler is a must-have tool for http trigger functions.

Can you elaborate on what you are using fiddler for with http trigger functions? If you are using it for sending requests and checking responses, perhaps Postman would be a better option?

**Comment by kornakar** [comment]
> Can you elaborate on what you are using fiddler for with http trigger functions? If you are using it for sending requests and checking responses, perhaps Postman would be a better option?

When I'm developing locally, I use it to inspect any calls the azure function makes to 3rd party APIs. Usually the 3rd party APIs don't behave as they should, so it's really helpful to see what's happening under the hood.

For calling the http triggered function, I use Postman, and sometimes just a browser window.

Thank you for the answer. I'll open an issue to Fiddler's issue tracker about this.
