### ISSUE TITLE
Pipeline Migration: azure-functions-host

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-host#8756]
Part of #8743

- [x] Migrate pipeline
- [x] Update downstream dependencies
- [x] Cleanup repo
  - [x] Remove obsolete YAML
  - [x] Remove webhook
  - [x] Update badges

**Comment by fabiocav** [comment]
Work is in progress. Moving to sprint 132.

**Comment by fabiocav** [comment]
Moving to sprint 135.

- Issues will be created to track remaining failing tests
- We'll continue with the pipeline migration and artifact validation
- Any future releases will be blocked on the issues @kashimiz will be creating to investigate the test failures.

**Comment by fabiocav** [comment]
Closing as done.
