### ISSUE TITLE
Pipeline Migration: azure-webjobs-sdk

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-host#8757]
Part of #8743

- [x] Migrate pipeline
- [x] Update downstream dependencies
- [x] Cleanup repo
  - [x] Remove obsolete YAML
  - [x] Remove webhook
  - [x] Update badges

**Comment by fabiocav** [comment]
Adding this to sprint 131 as a stretch goal.

**Comment by fabiocav** [comment]
The pipeline has been moved. @kashimiz is investigating failing tests and finalizing migration.

**Comment by fabiocav** [comment]
Closing as done.
