### ISSUE TITLE
ContainerNotFound exception

### ISSUE THREAD

**Issue by Noppey** [Azure/azure-functions-host#8761]
- Localhost
- Function App version: 4.8.1.18957

#### Repro steps

Provide the steps required to reproduce the problem:

1. Rename the Azurite folder to AzuriteOld
2. Open Visual Studio 2022
3. Run the function app

#### Expected behavior

No exceptions

#### Actual behavior

```
Azure.RequestFailedException: 'Service request failed.
Status: 404 (The specified container does not exist.)
ErrorCode: ContainerNotFound

Headers:
Server: Azurite-Blob/3.18.0
x-ms-error-code: ContainerNotFound
x-ms-request-id: 702ca022-6103-4980-93bb-d1534abde2fc
Date: Fri, 16 Sep 2022 13:34:34 GMT
Connection: keep-alive
Keep-Alive: REDACTED
'
```

Microsoft.Azure.WebJobs.Host.Storage.dll!Microsoft.Azure.WebJobs.Host.BlobLeaseDistributedLockManager.ReadLeaseBlobMetadata(Azure.Storage.Blobs.BlobClient blobClient, System.Threading.CancellationToken cancellationToken) Line 337

#### Known workarounds

Continue function app, next the the exception does not show up.

#### Related information 

Provide any related information 

* Programming language used: C#
```
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
```

```
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "AzureWebJobsSecretStorageType": "files",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
```

**Comment by ramya894** [comment]
@Noppey Can you explain us the scenario of creation the function apps in local so that we can check for the insights.

**Comment by Noppey** [comment]
Just create a function app, rename azurite temp directory and run.

**Comment by ramya894** [comment]
@Noppey We would like to know the use case or the reason behind the creating the function app in local.

**Comment by Noppey** [comment]
For development
