### ISSUE TITLE
Pipeline Migration: azure-webjobs-sdk-extensions

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-host#8771]
Part of #8743

### Build
- [x] Migrate pipeline
- [x] Update downstream dependencies
- [x] Cleanup repo
  - [x] Remove obsolete YAML
  - [x] Remove webhook
  - [x] Update badges

### Release
- [x] Confirm release process
  - [x] [WebJobs.Extensions.CosmosDB](https://github.com/Azure/azure-webjobs-sdk-extensions/tree/dev/src/WebJobs.Extensions.CosmosDB)
  - [x] [WebJobs.Extensions.Http](https://github.com/Azure/azure-webjobs-sdk-extensions/tree/dev/src/WebJobs.Extensions.Http)
  - ~[WebJobs.Extensions.MobileApps](https://github.com/Azure/azure-webjobs-sdk-extensions/tree/dev/src/WebJobs.Extensions.MobileApps)~ (deprecated)
  - [x] [SendGrid](https://github.com/Azure/azure-webjobs-sdk-extensions/tree/dev/src/WebJobs.Extensions.SendGrid)
  - [x] [Timers.Storage](https://github.com/Azure/azure-webjobs-sdk-extensions/tree/dev/src/WebJobs.Extensions.Timers.Storage)
  - [x] [Twilio](https://github.com/Azure/azure-webjobs-sdk-extensions/tree/dev/src/WebJobs.Extensions.Twilio)

**Comment by fabiocav** [comment]
Assigning this to sprint 135 as a stretch goal

**Comment by kashimiz** [comment]
Closing as complete.
