### ISSUE TITLE
Function host won't start locally with outbound http/https disabled

### ISSUE THREAD

**Issue by paulhickman-a365** [Azure/azure-functions-host#8774]
I am trying to run the local Azure functions host on a windows machine in an environment where we have to explicitly request outbound https/http is enabled for each target name/ip address from the security team.

I am getting mysterious request to 152.199.19.161 when I start the Azure function host locally. Can you explain what this to / what it is for, and potentially give a more clear error message when it is blocked.

#### Repro steps

On a windows machine:

1. Install and run the Azure storage emulator
2. Install azure core tools 4.0.4629 with functions runtime 4.6.1.18388
3. Use a firewall to block outbound http and https from the windows machine to the internet
4. Create and start a nodejs functions app:
````
func init test --node
cd test
func start
````

#### Expected behavior

Functions app starts and reports a  "no functions found" warning

#### Actual behavior

Functions app emits the version banner and then in red:
````
A host error has occurred during the startup operation '<guid here>'
System.Net.Http: The SSL connection could not be established, see inner exception. 
System.Net.Sockets: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.. An existing connection was forcibly closed by the remote host.
Value cannot be null. (Parmaeter 'provider')
````

The firewall logs show a denied attempt to connect to the IP address 152.199.19.161 which is owned by ANS communications and has no reverse DNS lookup to suggest what it is.

https://who.is/whois-ip/ip-address/152.199.19.161

**Comment by ramya894** [comment]
@paulhickman-a365 We would like to know the usecase or the reason for creating the function app in local environment, so that we can be able to assist you further.

**Comment by paulhickman-a365** [comment]
The situation I gave above is the simplest way to re-produce the problem.

In our real world scenario, we are starting a function app locally in order to debug it.

We've since added an exception for 152.199.19.161 to our firewall and the function app now starts

**Comment by ramya894** [comment]
Closing the issue as resoled.
