### ISSUE TITLE
Dynamic concurrency in azure function

### ISSUE THREAD

**Issue by ashokj82** [Azure/azure-functions-host#8781]
I am trying to use dynamic concurrency in Azure functions.

host.json has below configuration.

{"DynamicConcurrencyEnabled": false,"MaximumFunctionConcurrency": 20,"SnapshotPersistenceEnabled": true}

But still log shows dynamic concurrency is not enabled. Any help please.

**Comment by kshyju** [comment]
You are using `false` value for `dynamicConcurrencyEnabled` setting. Did you mean to use `true`?

See the docs about configurating here: https://learn.microsoft.com/en-us/azure/azure-functions/functions-concurrency#dynamic-concurrency-configuration

**Comment by ashokj82** [comment]
Yes I am using dynamicConcurrencyEnabled :true

**Comment by mathewc** [comment]
Please provide a Function App Name and timestamp for us to investigate. FYI - usually when we see issues like this, assuming your host.json configuration is correct, the issue ends up being that on startup you're configuring app configuration yourself via DI and you're removing our default config providers, one of which is responsible for applying host.json config. In these situations NO host.json config is being applied.
