### ISSUE TITLE
Dependency Update ApplicationInsights 2.21

### ISSUE THREAD

**Issue by czb182** [Azure/azure-functions-host#8786]
I want to consume recently released ApplicationInsights 2.21 SDK. I believe it is required to reference the same version of SDK as referencing by azure functions host, so requesting azure functions host AI SDK be updated from 2.20 to 2.21

**Comment by czb182** [comment]
I originally requested in #8573 but it has been closed for some reason.

The request is simple.  Please update the Azure Functions AI dependency from 2.20 to 2.21.

**Comment by ramya894** [comment]
@czb182 Please find the below link for reference.
https://www.nuget.org/packages/Microsoft.ApplicationInsights
Please use the below commands for installation of AI dependency to 2.21
NuGet\Install-Package Microsoft.ApplicationInsights -Version 2.21.0
dotnet add package Microsoft.ApplicationInsights --version 2.21.0
<PackageReference Include="Microsoft.ApplicationInsights" Version="2.21.0" />
paket add Microsoft.ApplicationInsights --version 2.21.0
#r "nuget: Microsoft.ApplicationInsights, 2.21.0"
// Install Microsoft.ApplicationInsights as a Cake Addin
#addin nuget:?package=Microsoft.ApplicationInsights&version=2.21.0

// Install Microsoft.ApplicationInsights as a Cake Tool
#tool nuget:?package=Microsoft.ApplicationInsights&version=2.21.0

If you still face the issue, please comment below

**Comment by czb182** [comment]
the azure functions runtime references Application Insights, and that version, currently 2.20, is shipped as part of it.  As far as I know you should not reference a different version that what ships with the runtime.  So I could add a reference to 2.21, but I believe this would conflict with the version the runtime ships with.  This is why I'm requesting for the runtime to update its depenendy from 2.20 to 2.21, which is the latest AI version.

**Comment by ramya894** [comment]
@czb182 We will check this with our next level team and let you know the update.

**Comment by czb182** [comment]
Open back up
