### ISSUE TITLE
Memory leak - .NET in-proc

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-host#8797]
I have a .NET 6.0 Function app that I deployed to a **Windows Consumption Plan** which ended up not triggering at all due to a misconfiguration in my host.json for function timeout (1hr instead of 10min).

Yet in the Overview for my function app, I see this:
![image](https://user-images.githubusercontent.com/20270743/192869358-29c3eb62-2cdc-4999-a6eb-be304552fa51.png)

Which speaks to me as memory is ever-increasing from ~50mb to ~100mb before being eventually GC'd and dropping back down. However with **zero** function executions in this time, I would expect **no** change in the memory working set unless something is "leaking".

#### Investigative information

Please provide the following:

- Timestamp: 9/28/2022 ~11:45am PST
- Function App version: ~4
- Function App name: `dncipipeline-functions-consumption`
- Function name(s) (as appropriate): n/a
- Invocation ID: n/a
- Region: `westus2`

**Comment by kshyju** [comment]
@brandonh-msft Is this still a valid issue? If not, I would like to close this so that we can focus on other valid issues which requires attention.

**Comment by brandonh-msft** [comment]
> @brandonh-msft Brandon Hurlburt FTE Is this still a valid issue? If not, I would like to close this so that we can focus on other valid issues which requires attention.

probably not, given its age.
