### ISSUE TITLE
"Slot Swap" operation randomly change slot host keys

### ISSUE THREAD

**Issue by lipalath-ms** [Azure/azure-functions-host#8807]
Hi,

I'm doing deployment to functionApp slot (+ my custom script to enable managed identity on all slots and update app settings with values from keyVault) in my Azure Devops classic pipeline and then swap slot operation with "Azure App Service manage" task. Unfortunately, swap randomly changing host keys on my slot, which is causing 401 in other places. They are always swapping between two sets of host keys, one set which is a copy of functionApp prod slot (with one custom host key), and second, set with only _master and default keys.

How to prevent changing hostKeys on my slot?

Investigative information
Please provide the following:

Function App version: 4.12.2.19454
Function App name: gmm-data-int
Region: West US 2

**Comment by ramya894** [comment]
@liliankasem Here is a [blog post ](https://www.michaelscollier.com/inconsistent-functions-host-key)which addresses similar scenario where the blog talks about inconsistent host key and solutions to resolve it. Please check and let us know if this helps.
