### ISSUE TITLE
Timer Trigger intermittently triggering multiple AKS container instances at the same time

### ISSUE THREAD

**Issue by krishnad1982** [Azure/azure-functions-host#8813]
We got a timer-based trigger built on Dotnet core 3.1 and deployed to multiple regions in AKS cluster.

1. It triggers every 30 seconds. 
2. Two instances were deployed in each region.
3. All are using the same storage account.

We recently noticed that two instances in the same region intermittently trigger simultaneously, as shown in the screenshot below, even though the timer trigger always ensures one instance per Microsoft documents.

We call a stored proc under the hood. So triggering of multiple instances is leading to issues with data integrity
The easiest solution is to scale down to one instance.
**Is there any option to fix it more properly?**

![Azure_Web](https://user-images.githubusercontent.com/15156261/193401144-a460f92e-df8a-4d47-9d04-ce0542e11331.PNG)

**Comment by ramya894** [comment]
@krishnad1982 Please provide us the function app name so that we can check further.
