### ISSUE TITLE
Alternative Way to use WEBSITE_CONTENTAZUREFILECONNECTIONSTRING

### ISSUE THREAD

**Issue by rebuildtech** [Azure/azure-functions-host#8832]
HI Team

I have a requirement for one of the typical environment where i wanted to deploy Functionapp, its Storage everything associated to a Private Endpoint and wanted to store the Storage account connection strings into a keyvault which is also associated to a private endpoint and wanted to reference them with KeyVault reference in Appsettings .

however the typical requirement is that, the DNS zones for Private Endpoint cannot be created via my BICEP script as there is a Azure policy which deploys the DNS Zones for my Private Endpoints which gets created about 10 mins later

Also on one of the other environment, my DNS zones are already created and the private endpoints refer to that DNS zones, However still here as well we have the issue because the Access Policies for KeyVault is referring to FunctionApp.

Hence as per the order until the FunctionApp gets created the KeyVault doesnt get created.

And now, the actual issue we have got is that with specific to WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and AzureWebJobsStorage App settings in FunctionApp, These settings when deployed along with my FunctionApp , It throws an error during my BICEP deployment that , Associate Storage cannot be resolved

ideally in both the enviornment because of these limitation i have been having this issue.

Is there a way to get around this ?

I have seen many deployment where most of them used listconnectionstrings for generating the access keys in functionapp directly. However as these have to be secured enough. They didnt wanted it to be

Can someone, please help me on this if there is a better approach to get along with this.

**Comment by rebuildtech** [comment]
Just an update

I know there is a way to use Managed Identity for AzureWebJobsStorage and use AzureWebJobsStorage__accountName

Link reference : https://learn.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial#use-managed-identity-for-azurewebjobsstorage-preview


 , But the real problem comes with the settings WEBSITE_CONTENTAZUREFILECONNECTIONSTRING

We are using Windows version and Function Premium EP1 Plan

Hence i dont see a way to ommit this specific settings or use an alternative way to insert a value into this app settings

Request to please help

**Comment by rebuildtech** [comment]
@surgupta-msft , Request you to please let me know if you have any suggestion on this. Thank you!!

**Comment by surgupta-msft** [comment]
@rebuildtech the discussion [here](https://github.com/Azure/azure-functions-host/issues/8135) seems to be related. Please check if it can help in resolving your issue.
