### ISSUE TITLE
Host should support Http Activity even without App Insights

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-host#8846]
With OpenTelemetry you can do stuff like this to get automatic Activity creation for requests:

```csharp
// Instead of AppInsights, use OpenTelemetry
services.AddOpenTelemetryTracing(tcb =>
{
    // Adds Activity tracking for incoming requests
    tcb.AddAspNetCoreInstrumentation();
});
```

Today, we require ApplicationInsights for this.

**Comment by brettsam** [comment]
@RohitRanjanMS -- filing this as tracking issue.

**Comment by RohitRanjanMS** [comment]
We are using [AddAspNetCoreInstrumentation](https://github.com/Azure/azure-functions-host/blob/de44db4bf69f533c3e30da41f989ddb318a548f6/src/WebJobs.Script/Diagnostics/OpenTelemetry/OpenTelemetryConfigurationExtensions.cs#L65) to get the request telemetry in the OTel flow.
