### ISSUE TITLE
Switch from IApplicationLifetime(deprecated) to IHostApplicationLifetime

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-host#8866]
https://github.com/dotnet/aspnetcore/issues/7749
https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.iapplicationlifetime?view=aspnetcore-6.0

Usage of the deprecated type in host: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/WebScriptHostExceptionHandler.cs#L17

**Comment by jviau** [comment]
Duplicate of #8508
