### ISSUE TITLE
Implement selective loading of extensions in Host in case of Stein (WorkerIndexing)

### ISSUE THREAD

**Issue by surgupta-msft** [Azure/azure-functions-host#8870]
This issue tracks implementation of selective loading of extensions in case of WorkerIndexing - [Design doc](https://dev.azure.com/msazure/One/_git/AAPT-Antares-Docs?version=GBmaster&path=/TeamDocs/FunctionTeamDocs/Design/Host/SelectiveLoadingOfExtensions.md) 

Corresponding design issue for reference - https://github.com/Azure/azure-functions-host/issues/8614

**Comment by fabiocav** [comment]
The associated PR addresses this issue. Currently iterating on reviews and design feedback.
