### ISSUE TITLE
FileNotFoundException when referencing System.Diagnostics.DiagnosticSource version 7.0.0

### ISSUE THREAD

**Issue by jooooel** [Azure/azure-functions-host#8908]
#### Description
I initially filed this issue [here](https://github.com/RehanSaeed/Serilog.Enrichers.Span/issues/238) since I thought is was related to that nuget package. But I've been able to narrow it down. 

When creating a brand new v4 function app (using `func new`) on .NET 6, if I add `<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="7.0.0" />` I get the following exception when trying to access something from that package:

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at serilog_span_bug.Test.Run(HttpRequest req, ILogger log)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at serilog_span_bug.Test.Run(HttpRequest req, ILogger log)
   at lambda_method110(Closure , Test , Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.TaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\TaskMethodInvoker.cs:line 21
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
```

I've created a minimal repro by just creating a new Function project, included the package reference, and created a new Activity. I also create a standar .NET 6 Console project, doing the same thing, and it works fine there. So I'm guessing this is related to the Functions runtime and how assemblies are loaded?

#### Repro steps

1. Clone/Fork https://github.com/jooooel/serilog-span-bug
1. Run the function called Test in the project called `function`
1. Invoke the function by going to http://localhost:7071/api/Test in a browser2. 

#### Expected behavior

That I can reference that package without getting an exception. (In my case I'm really referencing another package that is referencing it).

#### Actual behavior

The exception written above

#### Known workarounds

🤷‍♂️

#### Related information 

Provide any related information 

* Programming language used  - C# / .NET 6
* Links to source - https://github.com/jooooel/serilog-span-bug

**Comment by ramya894** [comment]
@jooooel We are investigating the issue and update you with the solution soon.

**Comment by ramya894** [comment]
@jooooel  If you are having trouble to switch to .net 7 in isolated model app, kindly open an issue in the dotnet isolated worker repo.
