### ISSUE TITLE
SCALE_CONTROLLER_LOGGING_ENABLED but no scaling information found in Application Insights

### ISSUE THREAD

**Issue by sdg002** [Azure/azure-functions-host#8914]
#### Is your question related to a specific version? If so, please specify:
Azure functions 4.0

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
Python 3.9

#### Question
Our Azure function is scaling up and `SCALE_CONTROLLER_LOGGING_ENABLED` is set to  `AppInsights:Verbose` but we cannot see scale controller related logs in the **Traces** table of Application Insights

## Overview of the setup
Azure function plan (P1V2) --> One service bus queue trigger --> calls some dummy Python code for now
We have configured scale out based on the **message count** in the **service bus queue**.

## How does our Function configuration look?
![image](https://user-images.githubusercontent.com/20245330/202157103-44c84424-54d1-493f-9a9c-84a0937124dd.png)

## What is the scale out configuration ?
![image](https://user-images.githubusercontent.com/20245330/202157270-5754c0e2-f02a-4b55-b42b-d59586064aa4.png)

## 1-How do we know that the function is scaling ?
![image](https://user-images.githubusercontent.com/20245330/202157645-03cdaa39-f7fe-46d3-9a3f-26cadefeec04.png)

![image](https://user-images.githubusercontent.com/20245330/202157733-9b812287-e1cc-4b83-98c9-4201e32682dc.png)

## 2-How do we know that the function is scaling ?

Looking at the Activity Log of the function plan , we see this
![image](https://user-images.githubusercontent.com/20245330/202157982-325061b9-8114-4edc-9d19-6d98ae313acc.png)

## What queries we tried in Application Insights
We followed [this link](https://learn.microsoft.com/en-us/azure/azure-functions/analyze-telemetry-data#query-scale-controller-logs) of Microsoft

### Zero results
![image](https://user-images.githubusercontent.com/20245330/202160310-13770c42-518e-4165-8d86-e72b9ad36684.png)

### Zero results
![image](https://user-images.githubusercontent.com/20245330/202159855-0805d818-41e8-41aa-beab-7dd857a3f095.png)

## What are we expecting ?
We want to query Application Insights or Log Analytics Workspace and find out when the Azure function scaled up and scaled down.
This would be very helpful for us in selecting the right function plan and optimizing our costs.

**Comment by ramya894** [comment]
@sdg002 We will check this issue with our next level team and update you,

**Comment by mathewc** [comment]
ScaleController logging only applies to Consumption or Elastic Premium plans. Looks like you have a dedicated plan with your own auto-scale rules configured? There is no ScaleController in the picture here, so this setting doesn't apply.

**Comment by sdg002** [comment]
Thanks for replying @mathewc ,

Yes -  we have auto-scale rules configured. We are using event driven scaling around an Azure Service Bus queues.

If  `SCALE_CONTROLLER_LOGGING_ENABLED` does not come in the picture for reasons mentioned by you - then what would should be the recommended approach to see a graph of the `instance count` vs `time` ?  I want to demonstrate how the Azure functions scaled up over a period of time and then how it scaled down ?  

Thanks.

**Comment by bhagyshricompany** [comment]
There are a few options to view a graph of the instance count vs time for Azure Functions:

Azure Monitor: Azure Monitor provides detailed metrics and logs for Azure Functions, including the number of instances and when they were scaled. You can use the Azure Monitor Metrics Explorer to view a graph of the instance count over time.

Azure Log Analytics: You can use Azure Log Analytics to query and visualize the logs for Azure Functions, including the scale events. You can create a custom query to extract the instance count and timestamp for each scale event, and then use the built-in visualization tools to create a graph of the instance count over time.

Azure App Insights: You can use Azure App Insights to track the performance of your Azure Functions. App Insights includes a built-in metric for instance count, which can be used to create a graph of the instance count over time.

Azure Dashboard: You can create a custom Dashboard in Azure portal and add the Metrics of your functions and also add the graph of instances count.

It is recommended to use Azure Monitor or Azure Log Analytics for more detailed analysis, but all above options will give you a graph of the instance count over time for your Azure Functions.
