### ISSUE TITLE
Null values are ignored by introduced new app setting to control skipping empty entries from event payload when sending to OOP layer

### ISSUE THREAD

**Issue by wesselkranenborg** [Azure/azure-functions-host#8924]
#8499 aims with this PR https://github.com/Azure/azure-functions-host/pull/8642 to try to fix the bug of skipping null entries. But the implementation right now made is only fixing the bug for event payload which is `string.Empty` and not null. Null values are still skipped and still cause the same bug.

@kshyju @fabiocav 

The original bug (https://github.com/Azure/azure-functions-dotnet-worker/issues/876) is not yet solved with this as we are sending `null` payloads and **not** `string.Empty`.

**Comment by kshyju** [comment]
@wesselkranenborg Could you share more information about the use case where null entries are coming in the trigger payload? Are you writing null entries in an output binding? If so, could you share the code please? Curious to see the producer part of the null entries. Thanks!

**Comment by wesselkranenborg** [comment]
@kshyju Thanks for the follow up questions. We have an IoT platform where we are sending telemetry and 'commands' from the devices in the field to our cloud platform. Our IoT Hub has an custom enpoint towards an EventHub and we process that EventHub for our realtime component via Azure Functions input binding (isolated worker, .NET 6). All our telemetry messages have a body but our 'commands' don't have a body, only properties on the message, based on the properties we handle the commands.

An example how we dispatch those in our IoT Device towards the IoT Hub is this:
<img width="786" alt="image" src="https://user-images.githubusercontent.com/4964604/208048060-ff843cbd-fef9-4761-9ae3-e00cb196b762.png">

As you can see the payload parameter is an optional field and the `Microsoft.Azure.Devices.Client.Message` also supports sending a message without payload (so payload null). With our commands from the IoT Device towards the cloud we only populate the properties and not the payload. 

The class `Microsoft.Azure.Devices.Client.Message` (part of the IoT Device SDK) contains some methods which handle the BodyStream (payload) and you can see the null checks in there, so it is a valid situation:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/4964604/208048923-069c91c5-e474-4cc7-a21a-39271f83652b.png">

We have validated that with the new changes you made we still face our initial problem (https://github.com/Azure/azure-functions-dotnet-worker/issues/876).

If you have any additional questions I'm happy to answer them.

**Comment by kshyju** [comment]
Thank you @wesselkranenborg. All my testing had been using functions output binding and it automatically converted my null values to empty strings, so this was not addressed. Thanks!

**Comment by kshyju** [comment]
@wesselkranenborg The changes are merged now. Will post an update when this bits are released (probably after holidays).
