### ISSUE TITLE
Front End returns site disabled due to quota enforcement (403.67), but the app was indeed restarted due deployment

### ISSUE THREAD

**Issue by hrgsmms** [Azure/azure-functions-host#8925]
+ Issue

While supporting a customer on an investigation regarding 403s returned by a Function App Front End Table, we got distracted by the return status.substatus "403.67", presented on diagnostics -> 4xxx errors Detector. 

That says "403.67" means site disabled due to quota enforcement 
[(https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.site.dailymemorytimequota?view=azure-dotnet)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.site.dailymemorytimequota?view=azure-dotnet)

However, we could see the error was raised indeed because the function was called when a deployment was being performed.

+ What is needed:

Could you please help on understanding why the limits was returned or if the status.substatus "403.67" returned also can mean indeed the function was down due deployments.

#### Investigative information

Please provide the following:

- Timestamp:  11/17/2022 08:24:00
- Function App version: 2.0.15229.0
- Function App name: cm-pl-apse-wa1-apse-dev
- Function name(s) (as appropriate): getaccesstoken
- Invocation ID: 
- Region: westus2

**Comment by ramya894** [comment]
@hrgsmms we will check this issue with next level team and update you with the solution.

**Comment by ramya894** [comment]
@hrgsmms Please raise a Microsft support ticket for this issue as it is platform related issue.
