### ISSUE TITLE
'ApplicationPartAttribute' does not exists in the namespace 'Microsoft.AspNetCore.MvC.ApplicationParts'

### ISSUE THREAD

**Issue by thopdev** [Azure/azure-functions-host#8927]
Upgrade from .NET 6 v4 in-process to .NET 7 v4 isolated breaks our build with the following errors:
The type or namespace name 'ApplicationPartAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.ApplicationParts' (are you missing an assembly reference?)
The type or namespace name 'ApplicationPartAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.ApplicationParts' (are you missing an assembly reference?)

The error is caused when using a class with using: using Microsoft.AspNetCore.Mvc;

#### Investigative information

- Timestamp: 18-11-2022
- Function App version: 4

#### Repro steps
We tried to reproduce the problem in another project. I did get it to work 1 time receiving the same error but after other tries i am not able to generate this error in a stand alone project. 

#### Known workarounds
Removing all reference to the MVC project removes the error. This does make it that we can't use razor templates that we use for emails.

### Example
We would like to use the MVC for the ActionContext like below
```
public class ViewRenderService : IViewRenderService
{
    private readonly IRazorViewEngine _razorViewEngine;
    private readonly ITempDataProvider _tempDataProvider;
    private readonly IActionContextProvider _actionContextProvider;

    public ViewRenderService(IRazorViewEngine razorViewEngine,
        ITempDataProvider tempDataProvider,
        IActionContextProvider actionContextProvider)
    {
        _razorViewEngine = razorViewEngine;
        _tempDataProvider = tempDataProvider;
        _actionContextProvider = actionContextProvider;
    }

     public async Task<string> RenderToStringAsync(string viewName, object model)
     {
         var actionContext = _actionContextProvider.ActionContext;

         using (var sw = new StringWriter())
         {
             var viewResult = _razorViewEngine.FindView(actionContext, viewName, false);

             if (viewResult.View == null)
             {
                 throw new ArgumentNullException($"{viewName} does not match any available view");
             }

             var viewDictionary = new ViewDataDictionary(new EmptyModelMetadataProvider(), new ModelStateDictionary())
             {
                 Model = model,
             };

             var viewContext = new ViewContext(
                 actionContext,
                 viewResult.View,
                 viewDictionary,
                 new TempDataDictionary(actionContext.HttpContext, _tempDataProvider),
                 sw,
                 new HtmlHelperOptions()
             );

             await viewResult.View.RenderAsync(viewContext);
             return sw.ToString();
         }
     }
}

```

**Comment by ramya894** [comment]
@thopdev : Hope this helps, If you are having trouble to switch to .net 7 in isolated model app, please open an issue in the dotnet isolated worker repo.

**Comment by thopdev** [comment]
Thank you for your help. I posted it on the correct repo now. https://github.com/Azure/azure-functions-dotnet-worker/issues/1192
