### ISSUE TITLE
Incorrect log message

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-host#8929]
Log message has the ToString() result of the collection.

> Worker description arguments after formatting: System.Collections.Generic.List`1[System.String]

Source: Host.LanguageWorkerConfig
Host version: 4.24.1.0

**Comment by mathewc** [comment]
Tagging @shreyas-gopalakrishna since this came from hist commit https://github.com/Azure/azure-functions-host/commit/1e1cb478bd25768e5dc07259120a47f673eb7bdc it seems.
