### ISSUE TITLE
How to handle timeout before process done on Azure Service Bus trigger for Azure Functions

### ISSUE THREAD

**Issue by mwicha** [Azure/azure-functions-host#8930]
I use Azure Service Bus trigger for Azure Functions.

My programming language is Javascript.

From is https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=in-process%2Cextensionv5&pivots=programming-language-javascript#example, I cannot set autoComplete = False. That mean it is auto complete. How to make sure that message is consumed will complete before Azure function timeout (10 mins is my maximum)? If timeout that mean I will loss message.

**Comment by ramya894** [comment]
@mwicha We will discuss this with our next level team and update you.

**Comment by ramya894** [comment]
@mwicha Please use the below Doc links for more information and guidance.

[Azure Functions scale and hosting | Microsoft Learn](https://learn.microsoft.com/en-us/azure/azure-functions/functions-scale#timeout)

[Azure Functions best practices | Microsoft Learn](https://learn.microsoft.com/en-us/azure/azure-functions/functions-best-practices?tabs=csharp)

[Improve Azure Functions performance and reliability | Microsoft Learn](https://learn.microsoft.com/en-us/azure/azure-functions/performance-reliability#avoid-long-running-functions)
