### ISSUE TITLE
Ability to modify the length of a query string

### ISSUE THREAD

**Issue by hajekj** [Azure/azure-functions-host#8933]
#### What problem would the feature you're requesting solve? Please describe.
Currently, Query String is limited to 4096 - https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/web.config and there is no way to override it. In App Service on Windows, the way to override would be via applicationhost.xdt placed in D:\home\site\ folder.

#### Describe the solution you'd like
I would like to be able to override the query length either with the standard way like in App Service or have the query string length included in host.json settings.

#### Describe alternatives you've considered
I can modify requests to be sent as POST, however I need it to be cached with Azure Front Door.

#### Additional context
There doesn't seem to be such a limit when running this from Docker images or Linux.

Related to #3023

**Comment by ramya894** [comment]
@hajekj We will check this request with our next level team and update you.

**Comment by ramya894** [comment]
@hajekj Thanks for reporting, we have discussed this request with next level team and got an update as this will be implemented and documented soon.
