### ISSUE TITLE
Invocation goes to poison queue with no exception

### ISSUE THREAD

**Issue by AlexPagoni** [Azure/azure-functions-host#8942]
I have a Queue Trigger function that under some circumstances just stops running. I've seen some past issues that are very similar but the results in there have not helped. 

At 8:18 the run starts, continues on until 8:21 that it just stops:
![image](https://user-images.githubusercontent.com/86569127/204749874-3d008428-8200-4c45-90c1-d720b5e9ad2c.png)

No failed runs appear in the Invocation History of the app: 
![image](https://user-images.githubusercontent.com/86569127/204750090-71c9ef5a-02fc-4fbd-824b-c024e49fc6b1.png)

This happens to all runs that are bit longer, short runs have been successful as it appears above. Usually up to ~2+ minutes. 

Please provide the following:

- Timestamp: 11/30/2022, 8:18:43.109 AM
- Function App version: 3
- Function App name: 
- Function name(s) (as appropriate): 
- Invocation ID: 03d8e157-07b8-4654-929d-9ae890d3dbc9
- Region: North / West Europe (tried both)

#### Repro steps

All runs that take more than 2.5 minutes

#### Expected behavior

The logic itself has been tested and is successful in local runs. It should complete.

#### Actual behavior

Invocation run just stops.

#### Known workarounds
None

#### Related information 
Written in python, below is also my host.json

`{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.*, 4.0.0)"
  },
  "concurrency": {
    "dynamicConcurrencyEnabled": true,
    "snapshotPersistenceEnabled": true
  },
  "extensions": {
    "queues": {
      "maxDequeueCount": 1,
      "batchSize" : 1
    }
  },
  "functionTimeout": "-1"
}`

**Comment by ramya894** [comment]
@AlexandrosP1 Could you please provide us the function app name so that we can check in the system logs and update you.

**Comment by AlexPagoni** [comment]
@ramya894  FunctionApp -> heronautomations, Function -> SearchArthro11

**Comment by AlexPagoni** [comment]
@ramya894 Hi, I did reply but this says my ticket will auto-close

**Comment by ramya894** [comment]
@AlexandrosP1 We will investigate the issue further and update you with the findings.

**Comment by AlexPagoni** [comment]
@ramya894 Hi, has there been any progress on this? Thank you!

**Comment by bhagyshricompany** [comment]
@AlexandrosP1 Ramya went on long leave, and I will be looking into it. I'll provide an update as soon as possible

**Comment by AlexPagoni** [comment]
@bhagyshricompany Issue was with a section of my logic creating an infinite loop, which is why runs seemingly provided no error. I will close this issue now
