### ISSUE TITLE
Npgsql.EntityFrameworkCore.PostgreSQL 7.0 causes an error when it is used in Azure Function .Net 6.0

### ISSUE THREAD

**Issue by tonyaccahr** [Azure/azure-functions-host#8947]
Open VS2022 and create a new Azure Functions Project.

- TargetFramework: net6.0
- AzureFunctionsVersion :v4

Install the package Npgsql.EntityFrameworkCore.PostgreSQL 7.0 and run the project.

I'm getting the error : Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

Downgrading the 7.0 to 6.0.7 works fine.

Thanks,

Please check the attached project:

[FunctionApp1.zip](https://github.com/Azure/azure-functions-host/files/10136523/FunctionApp1.zip)

**Comment by ramya894** [comment]
@tonyaccahr We are able to reproduce this problem and discuss with our next level team update you with the solution.
