### ISSUE TITLE
Add /root/modules for PowerShell

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-functions-host#896]
PowerShell functions should support a root level `/modules` folder for modules that need to be shared across Functions in one Function App.

Reason:
No PackageManagement available in PowerShell (in Azure Functions) so one would have to copy modules into multiple functions (where needed) and thus make maintaining that module a lot harder. (explained here in last paragraph: https://david-obrien.net/2016/11/azure-functions-byo-powershell-modules/)

**Comment by fabiocav** [comment]
Closing stale issue, no longer applicable. For Azure Functions PowerShell documentation/information please see https://github.com/azure/azure-functions-powershell-worker
