### ISSUE TITLE
.NET Core WebJob application unable to connect to storage account after upgrade to VS 17.4.1

### ISSUE THREAD

**Issue by vijayrkn** [Azure/azure-functions-host#8967]
Creating an issue on behalf of the VS customer: 
I have a strange but blocking issue after upgrading to VS 17.4.1 (enterprise).

I had a simple webjob application in .net core that listens for a message on a storage queue and begins processing a job when a message hits the queue. If I use a version of VS below 17.4, it works fine. Once I upgraded to v17.4, I get an error that I can no longer connect to the storage account due to invalid credentials. The connection strings are fine.

I get an error on the host.RunAndBlock() method (see screenshot).

System.InvalidOperationException: ‘The account credentials for ‘storageaccountname’ are incorrect.’

I have tried this twice and still have the issue.

I want to upgrade to 17.4 since I need support for my ARM processer on my MAC M1 (parallels).

The credentials are fine and a simple downgrade fixes the issue.

Any thoughts on how I can get this resolved?

More details available on the developer community portal: https://developercommunity.visualstudio.com/t/NET-Core-WebJob-application-unable-to-c/10202267

**Comment by soninaren** [comment]
@vijayrkn , We have upgraded the template azure webjob, the new template works as expected. I had tested the template before pushing it to VS. Going to close this one but feel free to re-open if you are still facing this issue.
