### ISSUE TITLE
Change to explicit import of PowerShell modules

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-functions-host#897]
Related to: https://github.com/Azure/azure-webjobs-sdk-script/issues/896

I understand that it is handy to have automatic loading of modules (see `PowerShellFunctionInvoker.cs` line 93) but this has performance implications for my function.
I don't always need to import a module and having this automatic loading of modules in the code potentially makes my function slow (especially for big modules), for example when branching in my code and only need to import a module in certain scenarios this is the case. More info here: https://david-obrien.net/2016/11/azure-functions-byo-powershell-modules/

Therefor I'd like to propose removal of this functionality and have the developer of a function call `Import-Module` where necessary.

Happy to create a PR for this.

**Comment by KirkMunro** [comment]
Related: #1563.
