### ISSUE TITLE
[.NET] Allow for System.Text.Json types in HTTP Trigger Binding

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-host#8976]
#### What problem would the feature you're requesting solve? Please describe.
I tried to use `System.Text.Json.JsonDocument` as the binding type for `HttpTrigger` in **in-proc Functions v4** (.NET 6) and was met with a serialization error ("no default constructor"). As we support Newtonsoft.Json types here (e.g. `JObject`), we should also support STJ types.

#### Describe the solution you'd like
Allow for, at minimum, `System.Text.Json.JsonDocument` support.

#### Describe alternatives you've considered
One can, of course, use `HttpRequest` and manually `.Parse()` the content of it, but that's always been possible and shouldn't be an excuse for not supporting our own JSON object model as a serialization target (as this "workaround" could similarly argue that _no_ types outside `HttpRequest` should be implemented).

**Comment by jviau** [comment]
I don't believe we have any plans to invest in adding STJ support to in-proc.

@fabiocav, @brettsam for additional comment.

**Comment by aishwaryabh** [comment]
No plans to add STJ support to in proc
