### ISSUE TITLE
support for "implicit" Azure auth

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-functions-host#898]
I envision a fair amount of Azure Functions to be used as glue in certain Azure workflows.

Something on Azure happens, an Event is created, Function is triggered and that Function now adds something to a database, kills a VM, restarts a VM, updates/deletes an ARM deployment, adds something to a Queue... (anything)

It would be really awesome if Azure Functions would make it easy, if not transparent, to authenticate against other Azure resources.

For example:

- describe an ARM template where 
  - a Function (app) is created
    - this Function gets an internal resource ID
  - a second Resource Group with resources is created
    - Function is configured to have certain permissions on this Resource Group

I can now execute any command against this Resource Group from within the Function without explicitly authenticating against Azure.
The request by the Function would be handled and authenticated internally.

Happy to elaborate further on this if needed.

**Comment by fabiocav** [comment]
Much of this has been enabled with the MSI support that was introduced. Closing this as resolved, but fee free to follow up if needed.
