### ISSUE TITLE
Function App Service Bus trigger not firing

### ISSUE THREAD

**Issue by slabarque** [Azure/azure-functions-host#8991]
Hi

I have a function app with a service bus trigger. During testing the trigger was firing correctly when placing messages on the service bus subscription and checking the function app log stream. Now the application is running in a production environment where messages get placed on the bus once a day. However the function app is not getting triggered by these messages and they remain queued. I see the same behavior on our dev and acceptance environments. When I open the function app on the Azure portal to take a look it suddenly starts processing all of the messages. It's like the function app is sleeping until I wake it up by looking at it...
Some details:
Function app name: fa-expenses-sync-m3-dev
Function name: ConsumeExpenseReportNotifications
Function app runtime: v4
Operating system: Windows
Hosting plan: Consumption
Version .net: 6
Location: eastus

![image](https://user-images.githubusercontent.com/2572680/208467489-cd0ed066-9441-4c12-a923-ff47dd561850.png)
![image](https://user-images.githubusercontent.com/2572680/208467600-1735e2aa-bc4a-45f7-88bf-39b72404e1e4.png)
![image](https://user-images.githubusercontent.com/2572680/208467643-7f12a2d6-53e6-429b-bf11-2abd72d36cc1.png)
![image](https://user-images.githubusercontent.com/2572680/208468952-d7a1e4b8-f88a-4cc3-939f-00e21bbdabd6.png)
![image](https://user-images.githubusercontent.com/2572680/208469578-bb16b312-5864-4549-b243-18ba20337adc.png)
![image](https://user-images.githubusercontent.com/2572680/208469633-1122e78b-726f-413a-b2f1-531e30381f5a.png)

When I check "diagnose and solve problems" I see this:
![image](https://user-images.githubusercontent.com/2572680/208469885-315a6c92-b7db-4c61-9e0b-20a92ddbfe6c.png)
However I have followed the guidelines from the docs
https://learn.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial-2#connect-to-service-bus-in-your-function-app
The function app is configured to use a managed identity and the correct access rules have been configured on the service bus.

Again, the function works when recently accessed trough the portal, but not when left alone for a certain amount of time...

**Comment by ramya894** [comment]
@slabarque We are investigating this issue and update you with findings soon.

**Comment by mattramsay-ice** [comment]
+1 seeing this same issue sporadically, nothing in the logs to explain the cause - all logs appear normal

**Comment by kshyju** [comment]
@slabarque I see you are using [application setting binding expression](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns#binding-expressions---app-settings) for topicName and subscriptionName parameters of the ServiceBusTrigger attribute. Can you confirm your production environment has this entries set? In the screenshot shared above, you are using `%ServiceBus:TopicName%` expression. So you should have an application setting entry with key `ServiceBus:TopicName` with topic name you want to use as value. Same question for subscription name. (Check these under Settings->Configuration) in the portal.

If these settings are present, can you check your application insight logs? The folowing query should give you some insights.

```
traces 
| order by timestamp desc
| where severityLevel > 1
```
If you do not see anything with the above query, remove the where condition for serviertyLevel. It will show all logs and you may get some idea about what is going on. 

Do you have another trigger running which is also listening to the **_same_** service bus topic? ex: a staging environment of this app or so?

**Comment by slabarque** [comment]
@kshyju I have application settings configured as depicted in my original post. They are using the double underscore naming convention:
ServiceBus__TopicName
ServiceBus__SubscriptionName

At the moment the messages are published on the the topic there are no logs at all from the consumer. Only when opening the function app in the Azure portal it gets triggered and starts processing the messages and producing logs.

There are no other triggers running on that same topic/subscription. This is the only one. The messages just get queued and only disappear when processed by the function app.

**Comment by slabarque** [comment]
Hi

Kind request to see if there are any updates on this issue. Our customer is impacted by this. And I'm wondering whether it might be more efficient to open a MS ticket...

Kind regards

**Comment by slabarque** [comment]
I know this is a difficult period (X-mas NY and so...). But an update would be very much appreciated :-)

**Comment by kshyju** [comment]
@slabarque Happy New Year 🎆 I suggest opening a ticket with our support team to investigate this further.
