### ISSUE TITLE
HttpTrigger function doesn't work if the route constraint contains a period

### ISSUE THREAD

**Issue by sumavangala** [Azure/azure-functions-host#9000]
If the route constraint contains a period, call to the function results in error - `The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`

Is there a way to fix this?

Workaround we currently have is to explicitly add a trailing slash.

Example:
`Route = "getdetails/user/{*userId}")`

Doesn't work: `http://testapi.azurewebsites.net/api/getdetails/user/test/id/test.cs`
Works: `http://testapi.azurewebsites.net/api/getdetails/user/test/id/test.cs/`

Note that only some period usage is causing this problem.

Example:

Works:
`http://testapi.azurewebsites.net/api/getdetails/user/test/id/test.js`
`http://testapi.azurewebsites.net/api/getdetails/user/test/id/test.net`
`http://testapi.azurewebsites.net/api/getdetails/user/test/id/test.cpp`
`http://testapi.azurewebsites.net/api/getdetails/user/test/id/test.test`
`http://testapi.azurewebsites.net/api/getdetails/user/test/id/test.vb.net`

Doesn't work:
`http://testapi.azurewebsites.net/api/getdetails/user/test/id/test.java`
`http://testapi.azurewebsites.net/api/getdetails/user/test/id/test.vb`
`http://testapi.azurewebsites.net/api/getdetails/user/test/id/test.cd`
`http://testapi.azurewebsites.net/api/getdetails/user/test/id/test.sd`

**Comment by fabiocav** [comment]
This is a result of those extensions being rejected by the platform. No further action planned at this point, but please open a new issue if you need assistance.
