### ISSUE TITLE
Re-enable v1 Tests: Mobile Tables

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-host#9004]
Part of #9003 

Some tests that passed locally and on AppVeyor fail on the ADO build agent. These tests were disabled so that the migration could progress, but the causes of their failures should be investigated and fixed, and the tests re-enabled.

- [ ] [`CSharpEndToEndTests.MobileTable`](https://github.com/Azure/azure-functions-host/blob/38231675d444b6421bef1039da4be5dda0f2fcca/test/WebJobs.Script.Tests.Integration/CSharpEndToEndTests.cs#L54)
- [ ] [`CSharpEndToEndTests.MobileTablesTable`](https://github.com/Azure/azure-functions-host/blob/38231675d444b6421bef1039da4be5dda0f2fcca/test/WebJobs.Script.Tests.Integration/CSharpEndToEndTests.cs#L83)
- [ ] [`FSharpEndToEndTests.MobileTablesTable`](https://github.com/Azure/azure-functions-host/blob/38231675d444b6421bef1039da4be5dda0f2fcca/test/WebJobs.Script.Tests.Integration/FSharpEndToEndTests.cs#L73)
- [ ] [`NodeEndToEndTests.MobileTables`](https://github.com/Azure/azure-functions-host/blob/38231675d444b6421bef1039da4be5dda0f2fcca/test/WebJobs.Script.Tests.Integration/NodeEndToEndTests.cs#L187)

**Comment by soninaren** [comment]
Closing this one as it is not applicable anymore.
