### ISSUE TITLE
Azure Functions Runtimes

### ISSUE THREAD

**Issue by xlight05** [Azure/azure-functions-host#9011]
#### Background
Currently I'm currently implementing support for azure functions and tooling for Ballerinalang. Ballerinalang plans to support both java and native backends for the language. As Ballerina is not supported in azure functions by default, we use custom handlers underneath. For java backend we use Java 11 as the runtime.  I'm trying to figure out the appropriate runtime for the native backend. I noticed naively compiled languages such as go, rust uses custom handler as the runtime. 

#### Question
My main question is that are there any drawbacks(performance and such) of using Java runtime for native backend as well? The native executable works just fine in the java runtime environment as well.  Is the code for these runtime creation open source? Do we have performance details on these environments?

**Comment by liliankasem** [comment]
Hello, there shouldn't be any issues using the java runtime for the native backend; if the build creates native binaries, the Java runtime shouldn't be required, but ultimately, the host doesn't care. All the host does is run the command provided when you setup the custom handler i.e.

```json
{
  "version": "2.0",
  "customHandler": {
    "description": {
      "defaultExecutablePath": "app/handler.exe",
      "arguments": [
        "--database-connection-string",
        "%DATABASE_CONNECTION_STRING%"
      ],
      "workingDirectory": "app"
    }
  }
}
```

I'm not aware of any drawbacks to this, nor the performance details - for that you'll have to run some benchmarks yourself with the native executable running with java vs something else.

**Comment by xlight05** [comment]
Alright, Good to know. Thanks a lot for the information. ;)
