### ISSUE TITLE
Host intercepts OPTIONS request despite CORS not enabled

### ISSUE THREAD

**Issue by simunic-cz** [Azure/azure-functions-host#9012]
#### Is your question related to a specific version? If so, please specify:
4.14.0.0

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
\-

#### Question

We have a custom runtime Function App running under Linux Consumption plan. We need to handle all `OPTIONS` requests ourselves, within the application code. For this reason I never enabled the Function App CORS - never added any "Allowed Origins", never enabled `Access-Control-Allow-Credentials`. Here is the terraform code used to create this function:
<details>
<summary>Terraform code describing the Function App</summary>

```hcl
resource "azurerm_service_plan" "ttAPIServicePlan" {
  name                = "tt-v2-${lower(var.ENV)}-service-plan-api"
  os_type             = "Linux"
  sku_name            = "Y1"
  resource_group_name = azurerm_resource_group.ttResourceGroup.name
  location            = azurerm_resource_group.ttResourceGroup.location
}

resource "azurerm_linux_function_app" "ttAPIFunctionApp" {
  name                       = "tt-v2-${lower(var.ENV)}-function-app-api"
  resource_group_name        = azurerm_resource_group.ttResourceGroup.name
  location                   = azurerm_resource_group.ttResourceGroup.location
  service_plan_id            = azurerm_service_plan.ttAPIServicePlan.id
  storage_account_name       = azurerm_storage_account.ttAPIStorageAccount.name
  storage_account_access_key = azurerm_storage_account.ttAPIStorageAccount.primary_access_key

  site_config {}

  app_settings = {
    # Infrastructure variables
    "FUNCTIONS_WORKER_RUNTIME"       = "custom"
    "APPINSIGHTS_INSTRUMENTATIONKEY" = azurerm_application_insights.ttAPIApplicationInsights.instrumentation_key

    # Runtime variables
    "ENV"                  = var.ENV
    "CDN_ACCOUNT_URL"      = var.CDN_ACCOUNT_URL
    "CDN_CONTAINER_NAME"   = var.CDN_CONTAINER_NAME
    "MONGO_CONNECTION_URI" = var.MONGO_CONNECTION_URI
    "MONGO_DATABASE"       = var.MONGO_DATABASE
  }
}
```
</details>

Despite the CORS never been explicitly enabled and there been no entries under "Allowed Origins", `OPTIONS` requests are still being captured and handled by Azure and never actually reaching the application code. How do I disable CORS if I never enabled it in the first place and prevent Azure from handling any `OPTIONS` requests?

If I remove **either the `Origin` or the `Access-Control-Request-Method`** header when replicating the issue with PostMan, the request is not handled by the Functions Host and does actually reach our application code. However, when **both the `Origin` and `Access-Control-Request-Method`** headers are present in the request (which from the browser always are), then the request never reaches the application code and is intercepted by Azure.

There seem to be quite many issues dealing with very similar problems, especially:
- https://github.com/Azure/azure-functions-host/issues/5200
- https://github.com/Azure/azure-functions-host/issues/1303
None of the answers are helpful though. In the first issue, there seem to be someone encountering the same problem (down in the comment - https://github.com/Azure/azure-functions-host/issues/5200#issuecomment-558557416), but its author was only told to open different ticket and the issue was never addressed.

Here are our `host.json` file:
<details>
<summary>The host.json file</summary>

```json
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true,
                "excludedTypes": "Request"
            }
        }
    },
    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[4.0.0, 5.0.0)"
    },
    "extensions": {
        "http": {
            "routePrefix": "",
            "customHeaders": {
                "Access-Control-Expose-Headers": "*"
            }
        }
    },
    "customHandler": {
        "enableForwardingHttpRequest": true,
        "description": {
            "defaultExecutablePath": "handler",
            "arguments": []
        }
    }
}
```
</details>
and `function.json` file:<br/><br/>
<details>
<summary>The function.json file</summary>

```json
{
    "bindings": [{
        "authLevel": "anonymous",
        "type": "httpTrigger",
        "direction": "in",
        "name": "req",
        "methods": [
            "options",
            "get",
            "post",
            "put",
            "patch",
            "delete"
        ],
        "route": "{*route}"
    }, {
        "type": "http",
        "direction": "out",
        "name": "res"
    }]
}
```
</details>

**Comment by satvu** [comment]
@patrik-simunic-cz apologies for the delayed response - are you still experiencing this issue?
