### ISSUE TITLE
Time Trigger function stops triggering, and resumes

### ISSUE THREAD

**Issue by albertllonch** [Azure/azure-functions-host#9016]
#### Investigative information

Please provide the following:

- Timestamp: 2023-01-04T08:36:00.0032509+00:00
- Function App version: 4
- Function App name:
- Function name(s) (as appropriate): Export
- Invocation ID: 87d01193-e1d9-4c38-a4fd-edd14cc8eb74
- Region: Europe West

#### Repro steps

I have a CRON Timetrigger function executing every 2 minutes, somehow it stops triggering randomly, and resume after aprox 10 minutes.
I have traces that indicates that the function is executed completily in time (not overlapping the next 2 minute execution), but the next scheduled execution is ignored.

#### Expected behavior

Trigger every 2 minutes

#### Actual behavior
![imagen](https://user-images.githubusercontent.com/11357564/210591993-583dc847-50a4-4592-8579-70bad8479a73.png)

Last good execution is at 8:36am (Timestamp of the issue), and next execuiton is 8:46
![imagen](https://user-images.githubusercontent.com/11357564/210592638-1a1df739-cd9c-463a-8020-66b4c24ffe4b.png)

**Comment by surgupta-msft** [comment]
Since the logs to investigate such issues are time sensitive, I would recommend opening a support ticket so that it can properly be investigated by an assigned engineer on the team.
