### ISSUE TITLE
Implement detector to identify use of ParameterBindingData

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-host#9022]
We need a detector to help us identify when ParameterBindingData is being used so we can help troubleshoot potential CRIs for this new feature. We can use [information](https://github.com/Azure/azure-functions-host/pull/9028) from `FunctionMetrics` kusto table to build the detector or can add more logs in Host if needed.

**Comment by surgupta-msft** [comment]
Added entry in [IPD dashboard](https://dev.azure.com/Azure-Functions-Supportability/IPD%20Reduction/_boards/board/t/IPD%20Reduction%20Team/Feature%20Areas/?workitem=817)

**Comment by fabiocav** [comment]
All of the work to enable to detector creation has been completed.

Leaving this open and moving to 139 to validate once the detector is created.

**Comment by surgupta-msft** [comment]
Detector in Prod - [link](https://applens.trafficmanager.net/subscriptions/1402be24-4f35-4ab7-a212-2cd496ebdf14/resourceGroups/surgnodetest5/providers/Microsoft.Web/sites/surg-net-test5/detectors/functionPreviewDetector?startTime=2023-01-31T17:00&endTime=2023-01-31T23:44)

**Comment by fabiocav** [comment]
@surgupta-msft is still tracking some enhancements to the detector, so we're leaving this open until those are done.
