### ISSUE TITLE
HttpTrigger unable to execute durable orchestration in Kubernetes, "unable to load metadata for function"

### ISSUE THREAD

**Issue by cfmayer** [Azure/azure-functions-host#9024]
Executing a durable function from an HTTP Trigger function returns the error that the metadata for the orchestrator function can't be found.

```
Executed 'Function' (Failed, Id=a36ba631-40f2-42af-a343-927190d30911, Duration=0ms)
System.InvalidOperationException: Unable to load metadata for function 'Function'.
...
a303b1e2e10c4aeab93807e612cdd2a1: Function 'Function (Orchestrator)' was aborted. Reason: An internal error occurred while attempting to execute this function. The execution will be aborted and retried. Details: System.NullReferenceException: Object reference not set to an instance of an object.
```

#### Investigative information

- Function App version: 2.0
- Core tools version: 4.0.4865
- Function runtime version: 4.12.2.19454

Package versions
- Microsoft.Azure.WebJobs.Extensions.DurableTask 2.9.0
- Microsoft.NET.Sdk.Functions 4.1.3

#### Repro steps

1. Follow the steps here to create a durable function in VS 2022, but add support for docker: https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-create-first-csharp?pivots=code-editor-visualstudio
2. Build and deploy the project to kubernetes (in this case, AKS using a private registry accessible via vnet)
```
func.exe kubernetes deploy `
 --name func-test1 `
 --registry xxxx/func-test1 `
 --service-type ClusterIP `
 --pull-secret registry 
```
3. Use a terminal from the pod to activate the function, ```curl http://localhost/api/function_httpstart?code=xxx```

#### Expected behavior

Orchestrator executes and queues up 3 instances of the activity (no execution because the other pod is scaled to 0).

#### Actual behavior

Error described above is returned.

#### Known workarounds

1. Adding ```[DurableClient(ExternalClient = true)]``` to the Function1_HttpStart function does not work.
2. Combining the 2 kubernetes deployments that separate the HttpTrigger and the durable functions does work but doesn't allow for deployment automation. I've also seen mentions that there's a reason these are separated, but I haven't found any documentation as to why, so I presume this is unsupported.

#### Related information 

https://github.com/Azure/azure-functions-durable-extension/issues/2110 describes the same problem for tools v3, but the workaround doesn't work.

**Comment by surgupta-msft** [comment]
Apologies for the lack of activity here. Is this something you're still experiencing with the latest versions?

**Comment by cfmayer** [comment]
It's too late now. I'm off that project and gone from that company.
