### ISSUE TITLE
dotnet-isloated functions (NetFx 4.8 based) has stopped working

### ISSUE THREAD

**Issue by thyme51** [Azure/azure-functions-host#9034]
#### dotnet-isloated functions (NetFx 4.8 based) has stopped working (Jan 11th)
Two observations:
- I used to be able to list my functions and monitor it using "Functions...". I'm aware I cannot edit them as the warning displays
<img width="718" alt="image" src="https://user-images.githubusercontent.com/8446402/212928732-992aeb0d-ef77-4af4-a5e1-b0df80623921.png">
- 10th of January, log statements in AI disappeared

#### Investigative information

Please provide the following:

- Timestamp:
- Function App version: 4
- Function App name: dev-fa-tengswplnaz36
- Function name(s):  FunctionTimer1
- Region: west-europe

```
<!-- 
     [Function("FunctionTimer1")]
        public void Run1([TimerTrigger("0 */2 * * * *")] MyInfo myTimer)
        {
            _logger.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");
            _logger.LogInformation($"Next timer schedule at: {myTimer.ScheduleStatus.Next}");

            // Read configuration data
            string keyName = "TestApp:Settings:Message";
            string message = _configuration[keyName];

            // Read configuration data
            _logger.LogInformation($"Azure App Config test - Message: {message}");
        }
```

#### Repro steps

Provide the steps required to reproduce the problem:

Running th KQL 
```
AppTraces
| where Message contains 'C#'
| extend dag = dayofmonth(TimeGenerated)
| project  TimeGenerated, dag
| order by TimeGenerated desc

```
results in 
<img width="368" alt="image" src="https://user-images.githubusercontent.com/8446402/212932271-08f51ce0-eb7e-4168-b076-9017e10324c9.png"> that show last sign of life is 2023-11-01 09:56

The function app is compiled using yml pipeline
https://dev.azure.com/jrt51/GIDev/_build?definitionId=13

and published deployed by yml pipeline
https://dev.azure.com/jrt51/GIDev/_build?definitionId=15

#### My Troubleshooting
- Rerunning pipelines
- Searching for trace statements: "C# Timer trigger function executed" but last seen at 1/11/2023 9:56:00 AM
- Recreated AppService Plan and function App
- App files looks correct in Function App
<img width="663" alt="image" src="https://user-images.githubusercontent.com/8446402/212934982-1e21864b-02d6-4d89-b4ed-7e974305987e.png">

**Comment by jviau** [comment]
@thyme51 are you still encountering this issue? Do you see any traces or exceptions from application insights regarding that timer trigger?
