### ISSUE TITLE
DiagnosticEventLoggerExtensions class improvements

### ISSUE THREAD

**Issue by madelinegordon** [Azure/azure-functions-host#9044]
[DiagnosticEventLoggerExtensions.cs](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Diagnostics/DiagnosticEventLoggerExtensions.cs)

#### What problem would the feature you're requesting solve? Please describe.
- When I want to add logs to diagnostic events in a class that already has other log statements, I need to specify `Microsoft.Azure.WebJobs.Script.Diagnostics.DiagnosticEventLoggerExtensions.LogError` if I don't want all of the other log statements to also log to diagnostic events. (e.g. if I add `using Microsoft.Azure.WebJobs.Script.Diagnostics.DiagnosticEventLoggerExtensions` and call `LogError` and `LogInfo` specifically to log to diagnostic events, now all calls to `LogError` and `LogInfo` in the entire class will log to diagnostic events.)
- In [`DiagnosticEventLogger`](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Diagnostics/DiagnosticEventLogger.cs) which implements `ILogger`, the `Log` method takes an `EventId eventId` paramater. The `DiagnosticEventLoggerExtensions` class's `Log` method takes a parameter `int eventId`. The EventId struct has an [implicit operator](https://github.com/dotnet/runtime/blob/ff12237f483eb0afdabf1aeb71b69ff992d6bd40/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/EventId.cs#L18), but wondering if this should be pointed out in a comment on the `LogDiagnosticEvent` method for clarity?   Additionally, the `DiagnosticEventLogger` doesn't do anything with eventId, so perhaps could emit that as a required parameter from `LogError` and `LogInfo` in `DiagnosticEventLoggerExtensions`?

#### Describe the solution you'd like
- In `DiagnosticEventLoggerExtensions.cs`, change the method names to specify the DiagnosticEventLogger, i.e. 'LogDiagnosticEventInfo' and 'LogDiagnosticEventError'
- Add comments to `DiagnosticEventLoggerExtensions.cs` explaining that `eventid` is not used? Or emit that param from the class methods altogether?

#### Additional context
Creating this issue to track discussion, as the `DiagnosticEventsLoggerExtensions` class is public and I don't know if anyone is using it/if changing these methods would constitute a breaking change?

**Comment by jviau** [comment]
Two issues to discuss here:

1. Removing the public API contract. @fabiocav @brettsam - given this is a public contract, but they really shouldn't be, how quickly can we remove them? I think the biggest concern here is customers accidentally using these overloads and being confused about the obscure behavior.
2. Re-evaluating how we do diagnostic logs ourselves. Does this even belong on `ILogger`? Is that _too_ accessible where someone internally may still misuse it? How do we guarantee it is only a very intentional effort by someone to use a diagnostic log given the impact of them.

**Comment by madelinegordon** [comment]
Synced with @fabiocav - because we are confident that the extensions use the WebHost extensions and not those in Webjobs.Script, it is safe to change the method names in this class to fix the naming conflict.
