### ISSUE TITLE
Profile manager code sets incorrect value for _activeProfile variable causing specialization code to fail for dotnet-isolated

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-host#9052]
Specialization code path fails for dotnet-isolated function apps when the workerconfig does not have any entries in the "profiles" section.

Current behavior observed during specialization.

1. [WebHostRpcWorkerChannelManager.SpecializeAsync](https://github.com/Azure/azure-functions-host/blob/7570b6daba86ae58931f116694e78700f4e86cd4/src/WebJobs.Script/Workers/Rpc/WebHostRpcWorkerChannelManager.cs#L118) method is invoked.
2. [UsePlaceholderChannel](https://github.com/Azure/azure-functions-host/blob/7570b6daba86ae58931f116694e78700f4e86cd4/src/WebJobs.Script/Workers/Rpc/WebHostRpcWorkerChannelManager.cs#L143) method gets called with "dotnet-isolated" as `workerRuntime` parameter.
3. [WorkerProfileManager.IsCorrectProfileLoaded](https://github.com/Azure/azure-functions-host/blob/v4.15.1/src/WebJobs.Script/Workers/Profiles/WorkerProfileManager.cs#L93) gets called and it returns `false`
   
![image](https://user-images.githubusercontent.com/144469/214678874-308afbfa-1189-4c2a-a3cd-f332232f814d.png)

4. `UsePlaceholderChannel` returns `false` and the caller code shuts down the placeholder channel.
https://github.com/Azure/azure-functions-host/blob/7570b6daba86ae58931f116694e78700f4e86cd4/src/WebJobs.Script/Workers/Rpc/WebHostRpcWorkerChannelManager.cs#L132-L137

Synced with @shreyas-gopalakrishna  and he thinks the value of `_activeProfile` is incorrect here. It should be ideally null/empty because the worker config for dotnet-isolated did not have any profiles. Further debugging shown that the guid stored in that variable is the id from the java worker config.

The `LoadWorkerDescriptionFromProfiles` method sets the value for  `_activeProfile` every time it is called. In my case, it was initially called for java and that did set the GUID and then later called for dotnet-isolated. The `GetEvaluatedProfile` method returned `false`, so the code path to set/reset the value of `_activeProfile` did not get executed. The value from java stayed there for the variable.

https://github.com/Azure/azure-functions-host/blob/7570b6daba86ae58931f116694e78700f4e86cd4/src/WebJobs.Script/Workers/Profiles/WorkerProfileManager.cs#L61-L73

**Comment by fabiocav** [comment]
@shreyas-gopalakrishna can you confirm you're driving this work? If so, we can have this assigned to you.

Thanks!

**Comment by shreyas-gopalakrishna** [comment]
Yes, I got my draft changes tested with help from Shyju. Will create a PR for this
