### ISSUE TITLE
ErrorCode: UnsupportedHttpVerb, when max retires is reached for blob trigger.

### ISSUE THREAD

**Issue by erizet** [Azure/azure-functions-host#9054]
I have a function with a blob trigger. When max retries(5) is reached, the log says:

`Message has reached MaxDequeueCount of 5. Moving message to queue 'webjobs-blobtrigger-poison'.`

After this the next log post is an exception.

```
The resource doesn't support specified Http Verb.
RequestId:8af1334f-901e-0062-037e-31b9de000000
Time:2023-01-26T12:06:31.7337888Z
Status: 405 (The resource doesn't support specified Http Verb.)
ErrorCode: UnsupportedHttpVerb

Content:
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>UnsupportedHttpVerb</Code><Message>The resource doesn&apos;t support specified Http Verb.
RequestId:8af1334f-901e-0062-037e-31b9de000000
Time:2023-01-26T12:06:31.7337888Z</Message></Error>

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-error-code: UnsupportedHttpVerb
x-ms-request-id: 8af1334f-901e-0062-037e-31b9de000000
x-ms-version: 2018-11-09
Date: Thu, 26 Jan 2023 12:06:31 GMT
Allow: REDACTED
Content-Length: 243
Content-Type: application/xml

```

There seems to be an error when moving the message to the new queue.

#### Investigative information

Please provide the following:

- Timestamp: 2023-01-26T12:06:31.9523064Z
- Function App version: 4
- Function App name: func-integration-intrum-send-sftp
- Function name(s) (as appropriate): SendDocumentsToIntrum
- Invocation ID: 
- Region: Sweden Central

#### Expected behavior

Message moved to poison queue.
#### Actual behavior

host is closing down and the restareted, and after a while the error repeats.

#### Known workarounds
?

#### Related information 

Provide any related information 

* Programming language used C#
* Links to source
* Bindings used

**Comment by jviau** [comment]
@erizet do you have a stack trace you can share? Or a minimal repro? Will be helpful to know which exact HTTP request is failing (particularly what piece of code is making that request) so we can triage as appropriate.
