### ISSUE TITLE
Automatic recovery when polling stops

### ISSUE THREAD

**Issue by yuna-s** [Azure/azure-functions-host#9060]
#### What problem would the feature you're requesting solve? Please describe.
Polling of a queue trigger function was stopped for about 2 days until a scale out operation.  It was mitigated to add new instances but could you consider a way to detect the issue and recover it by Azure Functions.

I already talked this request with Yong(EEE). So, please refer to our internal messages about this. Thank you.

**Comment by shaykchen** [comment]
Hi, we have the issue https://github.com/Azure/azure-sdk-for-net/issues/35650 opened to trace this issue.

**Comment by satvu** [comment]
Closing this as https://github.com/Azure/azure-sdk-for-net/issues/35650 is tracking the issue
