### ISSUE TITLE
Extraneous logs generated without any changes to function app

### ISSUE THREAD

**Issue by ajraczkowski** [Azure/azure-functions-host#9065]
Starting 2023-01-14, I am seeing infrastructure events logged from my Azure function which were not previously logged. This is causing bloat in data sent to App insights.

My function app has not been redeployed or otherwise changed by me during the entire month of January.

Below you will see a screenshot of the count of all events logged from the function app (excluding category Function.*) and how there were none of these logged at the beginning of January compared to currently over a hundred of these logged daily.

#### Investigative information

Please provide the following:

- Timestamp: 2023-02-01T23:45:45.8134531Z (most recent instance as of time this issue was opened)
- Function App version: 4
- Function App name: [Not provided]
- Function name(s) (as appropriate): [Not provided]
- Invocation ID: 5a0df9d1-65d6-433f-9511-15af13608890 (most recent invocation as of time this issue was opened)
- Region: East US 2

#### Repro steps

Each time my function runs, it generates infrastructure-level logs that were not present previously. 

#### Expected behavior

I expect no logs to be sent to App Insights aside from the Function.* category logs.

#### Actual behavior

Lots of Host and other events started logging around 2023-01-14 and started increasing significantly on 2023-01-26:

![image](https://user-images.githubusercontent.com/213488/216192681-e7830b72-d257-4644-8e50-c84ddb712c04.png)

#### Known workarounds

I can manually suppress these events via config. However I did not have to do this before; therefore I believe this is a bug that needs to be fixed.

#### Related information 

N/A

**Comment by MSIT-BPSC-IOT** [comment]
@ajraczkowski Can you please share the manual steps? I tried updating the host.json and appsetting files with below which didn't work.

```
{
  "version": "2.0",
  "functionTimeout": "00:55:00",
  "logging": {
    "logLevel": {
      "Default": "Warning",
      "System": "Warning",
      "Microsoft": "Warning",
      "Azure.Messaging.ServiceBus": "Error",
      "Azure.Storage.Blobs": "Error",
      "Azure.Core": "Error",
      "Microsoft.Azure.WebJobs.Extensions.Storage": "Error",
      "Microsoft.Azure.WebJobs.Extensions.ServiceBus": "Error"
    }
  }
}
```

**Comment by maranmaran** [comment]
I too am having very difficult time reducing clutter, actually reducing it at all. Only way I found was removing logging providers, registering my own doing some weird stuff I shouldn't otherwise. My local console behaves ok but my app insights gets spammed constantly and I just don't know what to do about it anymore.

This `host json` still logs a lot of stuff for me

```  
"logLevel": {
      "default": "None",
      "Host": "None",
      "Host.*": "None",
      "Microsoft": "None",
      "Microsoft.*": "None",
      "Azure": "None",
      "Azure.*": "None",
      "Worker": "None",
      "Worker.*": "None",
      "Function": "None",
      "Function.*": "None",
      "Function.MyCustomFunction": "Warning"
    },
    "applicationInsights": {
      "enableDependencyTracking": false,
      "enableLiveMetrics": true,
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Dependency;Event;Request"
      }
    }
```

**Comment by ajraczkowski** [comment]
> @ajraczkowski Can you please share the manual steps? I tried updating the host.json and appsetting files with below which didn't work.

To clarify, I haven't actually tried to suppress these logs because I feel that the Azure functions platform should fix the regression that caused them to appear suddenly. I assumed that I _could_ suppress them, but if you are unable to, then that only suggests that this needs to be fixed with higher priority.

**Comment by RohitRanjanMS** [comment]
Hi @ajraczkowski , this is not a regression. We have added more telemetry into our runtime for monitoring and troubleshooting. This is the case with other SDK/APIs as well. All the latest SDKs like Azure SDKs and HttpClient are intrumentd to emit more telemetry. 
Unfortunately, the flip side is the volume of telemetry.
Please suppress it in host.json or you can add a telemetry processor to suppress it as well. https://github.com/RohitRanjanMS/ApplicationInsightsDemo/blob/main/InProc/InProcApplicationInsightsDemo/Startup.cs
