### ISSUE TITLE
Running Azure Functions locally shows 1 function found but 0 loaded and it doesn't work

### ISSUE THREAD

**Issue by Filip3** [Azure/azure-functions-host#9093]
I have an Azure Http Trigger function, which builds successfully and runs without errors, but it's not loading the function or functions. 
The current run output gives out the following in verbose mode:
![image](https://user-images.githubusercontent.com/3075629/218457487-04299ccc-01ab-44c6-8746-1c99f541f327.png)

While testing the endpoint, using Postman, it gives me out of obvious reasons the 404 HTTP response.
Trying to resolve the issue I have tried multiple possibilities that can be related to the function itself, such as:

 - Incorrect project type
 - Missing function triggers, and any issues related to them
 - Invalid function signatures
 - Missing Nuget packages
 - Incorrect local.settings.json
 - Incorrect host.json
 - Run configuration
 - Going through verbose logs output on run and build for any pointers

Initial assumptions were that it was due to the function I was working on, but further investigations showed that it's happening for all the local development functions that I want to run and debug locally(tried it in multiple IDEs and Terminal with a new test function). Which points to a more global issue.
Currently running it using JetRider but have also tried using Visual Studio and directly the command line execution.

The azure function using 
Azure Functions Core Tools: 4.0.4915
Function Runtime Version: 4.14.0.19631
Framework: .net 6.0
Language: C#

Update:

Host.json and any settings are not loaded for the function or any function related. 
For example `func settings list` output:
![image](https://user-images.githubusercontent.com/3075629/219385648-9c9bfaea-2d33-4542-81e8-2ecb0721e5c8.png)

Question:
What could be causing this and or how can it be resolved?

**Comment by Filip3** [comment]
As none of the options worked, to correct the issue where the correct `host.json` file is read.
Such as:

 - Update all tools
 - Check all configurations that the project itself has
 - Confirm that this is a local issue and not a project issue
 - Check with different Azure Functions Core Tools
 - Reconfigure to use configuration options in the `local.appsettings.json` that would be used in the `host.json`

 Whereas I did not manage to find any documentation on what actually the tools and framework do in the background when the `host.json` is not found or it's there but ignored. Based on what was the output I can figure it is not an issue with the tools, but some configuration that caused it to ignore the host.json file, generate a new one and created it on top of that in the root of the `bin` folder instead of the proper `debug` or `release` output folder where it would have been read.

I decided to go with the basic approach of uninstalling all IDEs, including Visual Studio, JetRider, Visual Studio Code, and all instances of the Azure Functions Core Tools. This actually resolved the issue, and when installing all tools back, it still continued to work. I suspect this is a common framework approach in which it uses a similar approach for any default configuration files, when not present.

As a confirmation, Azure Functions do generate a new `host.json` file if one is not found or for some reason ignored, and that one is being used. But the way how it goes about it, I haven't still been able to find out. 

I would be glad to find out if there is any documentation on that or how that could affect the build and output when those files are involved.

Thank you!

**Comment by JacobCaron** [comment]
I am also running into this issue. However, both my local environment and azure-function web service can't find the functions. If I place the functions on the root level, like below, it works:
```
host.json
package.json
myFunc/
  - myFunc.ts
  - function.json
```

This does not work:
```
host.json
package.json
src/
  - myFunc/
    -- myFunc.ts
    -- function.json
```

Why?

**Comment by JustMilan** [comment]
Check your `Properties/launchSettings.json` In that file on line 3 (in my case) is specified what it needs to run

**Comment by surgupta-msft** [comment]
Apologies for the lack of activity here. Is this something you're still experiencing with the latest versions?

**Comment by Filip3** [comment]
@JustMilan, I did check my `properties/launchSettings.json` but it didn't have any issue with it. As the same settings were used and worked on other developer machines.
@surgupta-msft, I did manage to resolve it, in a way where I had to uninstall and reinstall everything. Even though it wasn't the desired approach, but I did not have any other option at the time. 
I also posted a bit more information on it here:
https://stackoverflow.com/a/75578705/3910333

**Comment by BluMichele** [comment]
> Apologies for the lack of activity here. Is this something you're still experiencing with the latest versions?

I do, here is my post on Microsoft Q&A https://learn.microsoft.com/en-us/answers/questions/1454890/linux-dotnet-isolated-function-hosted-on-app-servi?comment=answer-1385418&page=1#comment-1441341

**Comment by seeess1** [comment]
I'm having a similar issue and getting the `1 functions found (Custom) 0 functions loaded` message. My function runs just fine locally. But when I try deploying to my Function App, it seems the app can't find my function and so it can't execute. Here's what's happening in more detail:

My application is running on Python 3.9. When I run it locally using the `Run and Debug` mode in VS Code, I can see it executes successfully in the terminal output.

Then I try deploying from VS Code to my Function App:

<img width="308" alt="image" src="https://github.com/Azure/azure-functions-host/assets/28066066/6b55a06b-4d3b-41f4-a937-fe67b6f72ffd">

And the terminal output shows the deployment is successful:

```
Deployment successful. deployer = ms-azuretools-vscode deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
```

But when I go to the Function App in the Azure Portal, no functions are listed there:

<img width="779" alt="image" src="https://github.com/Azure/azure-functions-host/assets/28066066/c0684460-ed44-447e-8bbe-5c1a40448fab">

And the log stream shows:

```
Connected!
2023-12-01T21:08:00Z   [Verbose]   Initiating background SyncTriggers operation
2023-12-01T21:08:00Z   [Information]   Loading functions metadata
2023-12-01T21:08:00Z   [Information]   Reading functions metadata (Custom)
2023-12-01T21:08:00Z   [Information]   1 functions found (Custom)
2023-12-01T21:08:00Z   [Information]   0 functions loaded
2023-12-01T21:08:00Z   [Information]   Loading functions metadata
2023-12-01T21:08:00Z   [Information]   Reading functions metadata (Custom)
2023-12-01T21:08:00Z   [Information]   1 functions found (Custom)
2023-12-01T21:08:00Z   [Information]   0 functions loaded
2023-12-01T21:10:31Z   [Verbose]   Received request to drain the host
2023-12-01T21:10:31Z   [Information]   DrainMode mode enabled
2023-12-01T21:10:31Z   [Information]   Calling StopAsync on the registered listeners
2023-12-01T21:10:31Z   [Information]   Call to StopAsync complete, registered listeners are now stopped
```

So it seems like the code is deploying but the Function App can't load it for some reason.

Have looked around for a solution but no luck yet. Hoping this thread can help me figure out my particular issue.

**Comment by SeccoMaracuja** [comment]
I deployed my function using Visual Studio 2022 instead of Visual Studio Code, and it worked.
