### ISSUE TITLE
Linux Consumption resolution of content payload needs to be identity-aware

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-host#9097]
#### What problem would the feature you're requesting solve? Please describe.
Honoring:
- Identity-based AzureWebJobsStorage configurations, when that is used as the landing place for a package.
- general `WEBSITE_RUN_FROM_PACKAGE` expectations available on the rest of the platform. If one provides a storage URI without a SAS, it should be able to use managed identity, as per [this documentation].

[this documentation]: https://learn.microsoft.com/en-us/azure/app-service/deploy-run-package#access-a-package-in-azure-blob-storage-using-a-managed-identity

#### Describe the solution you'd like
Same behavior as [this documentation]. Logic from the existing platform behavior can be shared internally as needed.

#### Describe alternatives you've considered
Given the way tooling approaches Linux Consumption deployments, RFP=URL almost always needs to be used. introduction of a requirement for Azure Files to facilitate a deployment is excessive. In most all viable pathways, the host is made to resolve the payload, and therefore we need to update the logic in the AtlasInstanceManager to leverage the identity when needed.

**Comment by surgupta-msft** [comment]
Validated that RFP=URL works using managed identity for both the scenarios - UserAssigned and SystemAssigned as described in [this documentation](https://learn.microsoft.com/en-us/azure/app-service/deploy-run-package#access-a-package-in-azure-blob-storage-using-a-managed-identity)

Here is the code in the Host for context -
    - User Assigned identity - [link](https://github.com/Azure/azure-functions-host/blob/9c5fb8f13b36c38a1a3ab4f577fb5716f6af253b/src/WebJobs.Script.WebHost/Management/LinuxSpecialization/ManagedIdentityTokenProvider.cs#L32)
    - System Assigned identity - [link](https://github.com/Azure/azure-functions-host/blob/9c5fb8f13b36c38a1a3ab4f577fb5716f6af253b/src/WebJobs.Script.WebHost/Management/LinuxSpecialization/PackageDownloadHandler.cs#L73)
