### ISSUE TITLE
Add support for Retry context for Worker Indexing

### ISSUE THREAD

**Issue by gavin-aguiar** [Azure/azure-functions-host#9104]
#### What problem would the feature you're requesting solve? Please describe.

We need to add support for retry_context for the new programming model.  While indexing the function, the context for retries was lost since the FunctionMetadataResponse does not have any way to initialize the context object. 
With the new change, the RpcFunctionsMetadata will now have retry context which needs to be read by the host.

**Comment by mattchenderson** [comment]
This is apparently blocked on https://github.com/Azure/azure-functions-language-worker-protobuf/pull/93

**Comment by fabiocav** [comment]
@vrdmr unable to assign this to a sprint as this is blocked on the issue @mattchenderson mentioned above.

**Comment by gavin-aguiar** [comment]
https://github.com/Azure/azure-functions-language-worker-protobuf/pull/93 can go in but I need someone from the host team to review the changes and confirm if this is what the host code needs.

**Comment by fabiocav** [comment]
@kashimiz could you please assist?

**Comment by fabiocav** [comment]
Adding this to 142 and flagging https://github.com/Azure/azure-functions-language-worker-protobuf/pull/93 as a dependency.

**Comment by fabiocav** [comment]
We should be unblocked, assuming https://github.com/Azure/azure-functions-host/issues/9178 has been resolved. We should validate against the latest host version.

**Comment by fabiocav** [comment]
Moving to 146 as this is currently blocked on feedback from other language worker teams.
