### ISSUE TITLE
Always On Path

### ISSUE THREAD

**Issue by cosminstirbu** [Azure/azure-functions-host#9109]
Hello,

My understanding is that when you use Always On (on a Dedicated Plan) then an HTTP request is made periodically to the root path ("homepage") of your Azure Function - at least that's how it works with a regular App Service (Web API).

We would like to create an HTTP trigger function that gets invoked when the Always On request is made - however, as it seems you cannot create an HTTP trigger function that responds on the root path (as per https://github.com/Azure/azure-functions-host/issues/848) we're not sure how to accomplish that.

Is there a way to create an HTTP trigger function that gets invoked by the  Always On request?

Thank you,
Cosmin

**Comment by cosminstirbu** [comment]
Interestingly enough, as per the screenshot from a third party monitoring tool (Dynatrace) it seems that Always On mechanism doesn't call the root path but instead it calls the "/admin/warmup" path (every 5 minutes).

![Screenshot 2023-02-23 at 13 50 40](https://user-images.githubusercontent.com/7135690/220899632-08234657-04b2-4931-90f7-b970a56b9d35.png)

This means that I could add a WarmupTrigger and it would get called by Always On - the issue is though that the [HostWarmupMiddleware](https://github.dev/Azure/azure-functions-host/blob/8c8d2df01b6a3d5dbfbf5e268241eef8d4f4eb83/src/WebJobs.Script.WebHost/Middleware/HostWarmupMiddleware.cs#L56) allows the request through only once, when the host is in stand by mode.

It seems odd that Always On calls "/admin/warmup" - is there a way to override that? Or is there any other way to have a function invoked when you're being called by Always On?

**Comment by kshyju** [comment]
As of today, there are no extensibility points available for you to hook up your own trigger when the /admin/warmup API is called. Can you elaborate your use case a bit more so that we can review internally and see it makes sense to support something like that in the future ?

In the mean time, Is setting another timer trigger which makes a call to your http trigger an option for you?

**Comment by cosminstirbu** [comment]
> As of today, there are no extensibility points available for you to hook up your own trigger when the /admin/warmup API is called. Can you elaborate your use case a bit more so that we can review internally and see it makes sense to support something like that in the future ?
> 
> In the mean time, Is setting another timer trigger which makes a call to your http trigger an option for you?

My use case is related to the AlwaysOn functionality of the Dedicated plan - basically I want my own code to be exercised (to avoid idling and cold starts) when the platform calls the /admin/warmup path.

I guess we could do this with a timer trigger instead though, but then I am struggling to understand the usefulness of the AlwaysOn feature as it pertains to Azure Functions on Dedicated plan.
