### ISSUE TITLE
Azure Functions - service bus trigger (golang)

### ISSUE THREAD

**Issue by guydillen** [Azure/azure-functions-host#9120]
#### Is your question related to a specific version? If so, please specify:
N/A
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
golang
#### Question
Trying the example of https://techcommunity.microsoft.com/t5/apps-on-azure-blog/building-serverless-go-applications-with-azure-functions-custom/ba-p/3623617 
When running 'func start' I'll receive 1 message; but when sending following messages they don't trigger the service bus trigger (=no other message come  in)?

**Comment by cosmicray001** [comment]
@soninaren Could you please assign this issue to me? Recently, I've faced this issue and solved it by myself.

**Comment by soninaren** [comment]
Closing as this is a stale issue. @guydillen Please re-open if you still need assistance here.
