### ISSUE TITLE
Azure function timer trigger runs every time I open the function app

### ISSUE THREAD

**Issue by DamilolaAdeniji** [Azure/azure-functions-host#9156]
Hello,

I recently just created my first azure functions timer trigger. 

However, I noticed that it runs every single time I open the function. 

Is this normal? 

How do I get it to stop?

**Comment by surgupta-msft** [comment]
@DamilolaAdeniji This does not seem to be normal. Is it possible to provide a sample repro app/code, so we can investigate from our side?
