### ISSUE TITLE
Concerns of FunctionsPreservedDependencies

### ISSUE THREAD

**Issue by SuyliuMS** [Azure/azure-functions-host#9161]
#### Is your question related to a specific version? If so, please specify:
No

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
We are going to use OpenTelemetry 1.4.0 in our function, but OpenTelemetry has a dependency to System.Diagnostics.DiagnosticSource and it will throw a exception when trigger functions:
FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=7.0.0.0

However we can add FunctionsPreservedDependencies element to .csproj file to fix this error:
```
  <ItemGroup>
    <FunctionsPreservedDependencies Include="System.Diagnostics.DiagnosticSource.dll" />
  </ItemGroup>
```

**Will System.Diagnostics.DiagnosticSource.dll in FunctionsPreservedDependencies affect function behaviors?**

We are basically wondering what would be the impact for preserving our own dependency version for dlls also used by the function host and if it’s ok to preserve the System.Diagnostics.DiagnosticSource. We are on dedicated plan and we don’t use AppInsight – all of our instrumentations are Geneva based.

**Comment by RohitRanjanMS** [comment]
Tagging @brettsam and @fabiocav

**Comment by fabiocav** [comment]
@SuyliuMS that specific dependency is unified as types defined there flow from the host and the Function (there's type exchange between the two contexts), with the most important one being [`Activity`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activity?view=net-8.0). 

You have the ability to load your own version using the configuration above, but that would be scoped to your Function only. This is useful in a set of scenarios (and why the configuration exists), but will cause problems if you're relying on the instances of those types flowing from the host.
