### ISSUE TITLE
Issues with multicore usage for node.js functions on dedicated compute

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#917]
Running the script host on medium or large VMs will not result in efficient resource usage for node.js based functions. I ran a high throughput scenario and looked at my CPU usage and it pretty clearly maxed out a single core and never moved to multiple cores:
![image](https://cloud.githubusercontent.com/assets/10663/20234924/964a50d2-a839-11e6-95bf-91f1a5bb19aa.png)

The workaround is to provision multiple small VMs, but this is not a great option for memory intensive workloads.

**Comment by paulbatum** [comment]
When this is fixed, remember to update the documentation change that was tracked by https://github.com/Azure/Azure-Functions/issues/67

**Comment by paulbatum** [comment]
@mamaso can you do a first pass investigation on whether there is anything actionable here? I am assuming that it is basically impossible to get edge to use multiple cores given that it runs in process and the typical multicore answer for Node.js is to run multiple node.exe processes. Leave your findings here and then move the issue back to the Next milestone.

**Comment by mamaso** [comment]
@paulbatum out of curiosity is this one function execution or multiple executions?

**Comment by paulbatum** [comment]
Multiple concurrent executions.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by mamaso** [comment]
You're right, edge is locked down to the process from which it's called.

Some interesting options:
- Multiple c# worker processes which each use edge - this would map to functions as a whole if we moved toward a process-per-invocation model
- Threads within node process are a possibility if we did some work to support [web-worker threads](https://github.com/audreyt/node-webworker-threads).  Looks to use serialized message passing & not shared mem
- Multiple v8 worker processes

Other notes:
- spawning a v8 process costs ~10ms and 10mb
- if we did v8 process per execution (not a pool) it would solve problems with globals (i.e. console.log could hook into context.log)
- IPC could be an issue if we need to pass around large binding values (blobs, etc).  Not a good shared memory option available for node until something like [SharedArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer) lands

**Comment by paulbatum** [comment]
@mamaso Makes sense, thanks for looking at this!

**Comment by ColbyTresness** [comment]
@paulbatum This is a stale V1 item, correct? Or is it still open for a reason?

**Comment by paulbatum** [comment]
You're correct - closing.
