### ISSUE TITLE
StopIteration Python Exception not caught by runtime, blocking the execution until time out

### ISSUE THREAD

**Issue by BSpirit** [Azure/azure-functions-host#9177]
Hello,

I use Python Azure Functions in the context of my work and I think I found what could be considered an issue.
If a StopIteration Exception is raised, the Azure Function runtime will not catch it and the function will keep running until the time out.

#### Investigative information

- Timestamp: 2023-03-23T11:03:28.6541409Z
- Function App version: 4.16.4.4
- Function App name: ADSMgPOC
- Function name(s) (as appropriate): ExportFeatures
- Invocation ID: f33d7d01-c69f-43ae-b1a4-d4a007bea3d7
- Region: France Central

#### Repro steps

I have a QueueTrigger Python Azure Function.
If this function raise a StopIteration during its execution, this exception will not be caught by the runtime and the function will keep executing until the time out, potentially blocking incoming messages.

#### Expected behavior

I would expect the runtime to catch the exception and mark the function execution as failed.

#### Related information 

Provide any related information 

* Programming language used: python
* Bindings used: QueueTrigger

**Comment by aishwaryabh** [comment]
Is this still an issue?

**Comment by aishwaryabh** [comment]
Closing issue as there's no response
