### ISSUE TITLE
Hot reload doesn't work with EnableWorkerIndexing turned on

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-host#9185]
#### Repro steps

Provide the steps required to reproduce the problem:

1. Create a windows consumption Node 18 app
2. Add the app setting `AzureWebJobsFeatureFlags` set to `EnableWorkerIndexing`
3. Create an http trigger on the function from the portal
4. Execute the HTTP trigger
5. Change the code from the portal
6. Execute the HTTP trigger again

(This can also be reproduced with core tools on a local app)

#### Expected behavior

The second execution should reflect the changes

#### Actual behavior

The second execution is the same as the first.

#### More information 

This affects apps that are _not_ using the new programming model, which is why we had [this bug on core tools](https://github.com/Azure/azure-functions-core-tools/issues/3239) and [this incident](https://portal.microsofticm.com/imp/v3/incidents/details/376625315/home) (internal link only) filed when `EnableWorkerIndexing` was on by default in 4.16.4.

At a minimum, we should fix this for old model apps before we re-enable `EnableWorkerIndexing` by default. Of course ideally we get it to work for new model apps as well.

**Comment by jurijsk** [comment]
Can confirm the issue. Also getting `Worker process started and initialized.` in the terminal on changes, but changes are not applied. 

I believe I use v4 and I have `EnableWorkerIndexing` in local.settings.json. 
My tooling version is:
```
Azure Functions Core Tools
Core Tools Version:       4.0.5095 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.16.5.20396
```
@ejizba is there any workaround at the moment?

**Comment by ejizba** [comment]
Unfortunately no workaround for the new v4 preview model. Plan is to get this fixed before we GA

**Comment by MattSidor** [comment]
@jurijsk My workaround is to run the function with [nodemon](https://github.com/remy/nodemon/) to automatically restart the function when the `dist` folder changes.

I run two terminal sessions concurrently: one uses `tsc` to watch for file changes and rebuild `dist`; the other runs `nodemon`.

These are the two scripts from `package.json` that I run in each terminal session:

```json
"scripts": {
  "watch": "tsc -w",
  "start": "nodemon --exec \"func start\"",
},
```

```zsh
$ npm run watch
$ npm start
```
