### ISSUE TITLE
Disable access to files outside of %HOME%/site/wwwroot using VFS apis

### ISSUE THREAD

**Issue by balag0** [Azure/azure-functions-host#9191]
#### What problem would the feature you're requesting solve? Please describe.
The original intent of these apis was to enable editing and viewing functions source code. So, allowing access to files outside of the content root folder is unintended behavior and allows clients to take dependency on undocumented / unsupported features. This limits our ability to change how this api works in the future.

#### Describe the solution you'd like
Restrict access to files under wwwroot folder.

#### Describe alternatives you've considered
None.

**Comment by fabiocav** [comment]
Moving this to sprint 145 as the Worker Indexing changes took priority over this work.
