### ISSUE TITLE
IFunctionsHostBuilder.Services.BuildServiceProvider() breaks FunctionsStartup

### ISSUE THREAD

**Issue by noontz** [Azure/azure-functions-host#9202]
#### Investigative information
- Function App version: v4
- .NET 6.0

#### Repro steps

Provide the steps required to reproduce the problem:
    
    using Microsoft.Extensions.DependencyInjection;
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var issue = builder.Services.BuildServiceProvider();
        }
    }

#### Expected behavior

A host that starts correctly

#### Actual behavior

A host that breaks with this message:

A host error has occurred during startup operation 'b0cd01ac-4f2f-4183-ade2-85139cbe9b59'.
[2023-04-07T23:18:00.581Z] DataAccess: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

**Comment by satvu** [comment]
If you are trying to bring in the 7x version, this isn't supported in In-Proc (which will use 6x). If you want to use 7x, I recommend moving to the isolated model. 

Closing as answered.
