### ISSUE TITLE
Setting 'TZ' on Azure function hosted in Linux Consumption plan throws CryptographicException

### ISSUE THREAD

**Issue by alicelupsan** [Azure/azure-functions-host#9203]
Previously Running Azure functions suddenly started failing around daylight saving time with the following error: 

Request [54b1af8b-b9c3-4f46-96ae-37e852da9937] exception Azure.RequestFailedException: The SSL connection could not be established, see inner exception. 

System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
---> System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
at Interop.Crypto.X509StoreSetVerifyTime(SafeX509StoreHandle ctx, DateTime verifyTime)

#### Investigative information

- Timestamp: 2023-04-10T07:56:46.7250043Z
- Function name(s) (as appropriate): All functions fail to start
- Invocation ID: d7b820c2-9212-4508-b464-758113b00ece
- Region: Switzerland North

![image](https://user-images.githubusercontent.com/4572584/230862080-d4e722b8-43cb-44f4-9116-95d96c2e7ede.png)

#### Repro steps

Provide the steps required to reproduce the problem:

1. Deploy Azure functions to Linux Hosted Basic Cosumption plan
2. Set 'TZ' environment vaiable in Configuration Settings to 'Europe/Berlin' or other valid tz values.
3. Save the configuration (functions restart) 
4. Functions are no longer reachable, see errors below: 

![image](https://user-images.githubusercontent.com/4572584/230862664-75b0328f-712b-4486-b16e-d11db6853d85.png)

#### Expected behavior

After Setting the 'TZ' the functions should not fail, at least if not supported it should give another message.

#### Actual behavior

All functions in that host fail to start. Why is this happening? Is this because we are on the consumption plan? 

#### Known workarounds

If I remove the 'TZ' environment variable the functions start working again, but I have a dependency on this.

#### Related information 

Provide any related information 

* C#
* TimerTrigger, HttpTrigger, all functoons fail to start

**Comment by liliankasem** [comment]
We've received a support case for this same issue, I'll share the outcome of that investigation when it's complete.

In the meantime, I've been informed that "TZ" is not supported for linux consumption, and only works for EP and dedicated SKUs. If that's true, it's odd that your application was working with a timezone before the daylight savings issue. 

cc: @balag0 in cases you have more information to share about this

**Comment by liliankasem** [comment]
**Follow up from Bala:**

`TZ` it not actually a platform app setting like `WEBSITE_TIME_ZONE` is, it's just a regular environment variable that customers can add to their code/environment to use in their application. Both platform app settings and customer environment variables end up as environment variables inside the container, but the difference is that only one of them (platform defined app settings) are looked at by platform components. `TZ` is not supported by platform components.

Regarding why it used to work before, this would have been due to docker's handling of time zones (using static data it had when the image was built). Since the platform never supported it, there is no guarantee it will continue to work or work consistently.

**Comment by alicelupsan** [comment]
Thank you very much for the response! 

If the application fails so badly when setting this TZ environment variable there should be a warning when I save the configuration that this might not be supported. Or at least when I try to run the diagnose tool.

I spent a lot of time trying to figure out what was configured wrong. It only fails if I set a valid value for the TZ environment variable. Just a suggestion, maybe it would be a time saver for others.

**Comment by liliankasem** [comment]
That's totally fair, we didn't really know if would fail people in this way when day light savings hit - I can talk to the team about improving documentation/diagnostic events around this!

**Comment by fabiocav** [comment]
@pragnagopa would you be able to work on a documentation update (and perhaps detectors) to make sure this is clear?

**Comment by pragnagopa** [comment]
Thanks for the feedback. We will track updating the [docs](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?pivots=programming-language-python&tabs=python-v2%2Cin-process#ncrontab-time-zones) to call out setting `TZ` is not supported on Linux Consumption Function App

**Comment by brettsam** [comment]
I just ran into a similar time zone issue with Linux Consumption where:
- `WEBSITE_TIME_ZONE` was set
- The ScaleController applied the offset and scheduled timers as if `WEBSITE_TIME_ZONE` worked
- When the Linux worker started, it did not know about the offset and ran the timers immediately as if they were behind schedule.

This led to a lot of confusion and oddities in when the timers fired. Having many timers makes it even more confusing.

I want to use this issue as a tracking item for a couple improvements we can make here:
- Raise a Diagnostic Event (that will show up in the portal) if a Linux Consumption app has used `TZ` or `WEBSITE_TIME_ZONE`
- Also log a `Warning` that will show up in App Insights, if they're using these.

But I'm also not sure that we've meant for the ScaleController to use `WEBSITE_TIME_ZONE` as part of its timer calculations if the site is Linux Consumption.

@pragnagopa / @balag0, do you know if there's a ScaleController fix that we could track internally?

**Comment by FinVamp1** [comment]
@brettsam also ran into this issue where setting TZ on Linux Consumption breaks Sync Triggers as well with a similar Cryptographic exception. Added a work item on me to Warn if the TZ  Application settings is added for Linux Consumption.
