### ISSUE TITLE
Duplication Issue

### ISSUE THREAD

**Issue by ksharshith** [Azure/azure-functions-host#9204]
I am facing Duplication of the logs in application insights which can be seen in the following screenshot 
![image](https://user-images.githubusercontent.com/54582602/230893026-6e615e37-f21c-441e-9c5a-963aaebe2625.png)

As per the image, we can see there are two logs logged with an identical time stamp but the only difference is itemId
I can see we are not using itemId in our configuration.

By API Calls I am not able to find 2 logs that are sent. But logs are populated twice.

**Comment by ksharshith** [comment]
I can see an issue is raised for the same 
https://github.com/Azure/azure-functions-host/issues/1627

**Comment by ksharshith** [comment]
Hi @jviau, any update on this issue ?

**Comment by RohitRanjanMS** [comment]
Hi @ksharshith , are you still facing this issue? If yes, then can you share your app name and the time window when you had this issue?
The way our logging pipeline is designed that we can have some duplicates due to failures and retries, but this should be rare. How often do you see duplicate logs?

**Comment by RohitRanjanMS** [comment]
We have published a detector under "Diagnose and solve problems" to troubleshoot these kind of issues.

<img width="920" alt="image" src="https://github.com/Azure/azure-functions-host/assets/90008725/6bf2f2f5-2f5c-4c42-80f8-dcfa391ba67a">

**Comment by swarnimsuman** [comment]
Hi @RohitRanjanMS
We are experiencing a similar issue where duplicate log messages are being registered in the Azure dashboard. However, from the application's perspective, only a single message is being sent to the Application Insights tracer. This behavior is consistent for a few specific log messages but does not occur for all log messages.

<img width="1322" alt="image" src="https://github.com/Azure/azure-functions-host/assets/36529263/ff0eff56-a8e9-43b9-a57a-3d59bc28996a">

Application ID: 396353da-ae9b-4c0e-88dc-595930546782
