### ISSUE TITLE
Update default bundles version in host reference

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#9206]
The default bundle reference defined [here](https://github.com/Azure/azure-functions-host/blob/35913e7c2285cd5774a4647bbb84fe5caa8a5834/src/WebJobs.Script/ScriptConstants.cs#LL183C9-L183C76) needs to be updated to default to bundles 4.0.

**Comment by soninaren** [comment]
This is a duplicate issue #9100
