### ISSUE TITLE
DrainMode mode enabled suddenly shuts down all function job hosts for Event Hub Trigger

### ISSUE THREAD

**Issue by mikkovor** [Azure/azure-functions-host#9208]
We have a function app (consumption plan) that consumes events from an event hub. Yesterday we noticed that the function had stopped consuming events and there were no exception or anything out of ordinary to be found. 

#### Investigative information

Please provide the following:

- Timestamp: 4/11/2023 10:07:55 PM
- Function App version: custom (~4)
- Function App name: dev-hb-core-sw-store-hbc-telemetry
- Function name(s) (as appropriate): ProcessIncomingTelemetryStore
- Invocation ID: 
- Region: West Europe

#### Expected behavior

After DrainMode enabled instances should start on event hub trigger or maybe should not be shut down at all if event hub is receiving a steady flow of requests.

#### Actual behavior

At seemingly random times the Drainmode is enabled and all function instances are shutdown and they seem to come back up at again seemingly random times.

Here's an image of trace logs where the event hub events were not consumed for a good 7+ hours.

![drainmode_enabled](https://user-images.githubusercontent.com/43668612/231388161-b07f1be2-ae99-4586-aed9-ee897494ca9b.jpg)

And an image of of the event hub incoming / outgoing that shows that it was a steady flow when it just decided to scale in and shutdown all instances?

![incoming-outgoing](https://user-images.githubusercontent.com/43668612/231388586-818e8ffb-1373-4ef4-b75a-d0444a0505e5.jpg)

**Comment by fabiocav** [comment]
@mikkovor are you still experiencing this issue? 

For production impacting issues like what you're describing above, we recommend engaging our support team as opposed to using GitHub issues, as that will ensure things are handled in a timely manner.

Thanks!

**Comment by mikkovor** [comment]
It was happening in dev environment so wasn't a huge deal and after some restarts on the services it seemed to work again after a few hiccups
