### ISSUE TITLE
Unable to catch exceptions in StartUp when connecting to Azure app configuration

### ISSUE THREAD

**Issue by itshawi** [Azure/azure-functions-host#9210]
We recently enabled our function app to use Azure App Configuration to host our service configurations, using Managed Identity to gain access to the resource. Our goal is to ensure that if Azure App Configuration is down or the endpoint is invalid, our service falls back to using the configurations in the host.json file. However, our current implementation does not catch the exception when an invalid endpoint is provided, resulting in the service being terminated. We need to modify our implementation to catch the exception and have our service fall back to using the configurations in the host.json file as desired. We were unable to find a solution to this problem space, so we are looking to see if anyone else has faced this issue or has a suggestion? 

### Error Message when provided invalid endpoint: 
A host error has occurred during startup operation 'b10a6a4d-e182-4c6-abLf-e1417a935ab8'. Azure. Core: No such host is known. (github-sample-appconfiguration.azconfig.io:443). System.Net.Http: No such host is known. (github-sample-appconfiguration.azconfig.io:443). System. Net. Sockets: No such host is known. Value cannot be null. (Parameter 'provider')

### Here is the Code
![image](https://user-images.githubusercontent.com/82969710/232166052-957c6dc6-2636-4748-b803-278104b93800.png)

**Comment by satvu** [comment]
@itshawi apologies for the delayed response, are you still experiencing issues? 

From the code sample you provided, it seems like you are overriding a host-provided service (`IConfiguration`). I would start with [this official guide](https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#function-app-provided-services) to troubleshoot.
