### ISSUE TITLE
Grant rights to Azure Function to Get Existing Alerts and to Change their State

### ISSUE THREAD

**Issue by JasonDWilson** [Azure/azure-functions-host#9216]
#### Is your question related to a specific version? If so, please specify:
.Net 7

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
I have 2 Azure Functions that need to be able to interact with log alerts in application insights.  I have enabled managed identities for these roles and tried to give them the Contributor role in in just Application Insights.  My code threw the following error: a Exception: Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed exception.

I tried granting the identities the owner role in both Application Insights and then in the entire resource group with the same result.
![image](https://user-images.githubusercontent.com/57236874/233069164-0ada1e1a-e285-4e94-9d09-74004b48a407.png)

The functions work properly when run locally, but not when published to Azure even though they have the same rights that I do.

Here is the code that I am using to get a bearer token to use with the resource manager Rest API:

``` Csharp
        try
        {
            token = await GetAccessTokenAsync("https://management.azure.com/.default");
        }
        catch(Exception ex)
        {
            var result = $"Error retrieving token: {ex.Message}";
            _logger.LogError(ex, result);
            return result;
        }

        public async Task<string> GetAccessTokenAsync(string resourceId)
        {
            var tokenCredential = new DefaultAzureCredential();
            var accessToken = await tokenCredential.GetTokenAsync(
                new TokenRequestContext(scopes: new string[] { resourceId }));
            return accessToken.Token;
        }
```

Please advise on how I should proceed.

Thank you,

Jason

**Comment by JasonDWilson** [comment]
Also wouldn't mind a method to work with alerts in the SDK, but I couldn't find it in documentation -- I'm sure I wasn't looking in the right place

**Comment by JasonDWilson** [comment]
Is this the right place to ask this question?

**Comment by bhagyshricompany** [comment]
Thanks for reporting pls share the function name,app name ,region time stamp etc.
