### ISSUE TITLE
Despite maxTelemetryItemsPerSecond = 1 , 20.000.000 errors per hour were logged.

### ISSUE THREAD

**Issue by well0549** [Azure/azure-functions-host#9221]
We have a Durable function that runs under a managed identity.
It uses another managed identity to read the Servicebus Queue.

We had a misconfiguration in the Identity that reads the queue.

What we have seen now is the following:

During a week (with wrong identity) there was a spike for three hours sending 20.000.000 log messages an hour  to log analytics.
Then a day without any entries.....
The next day another spike of 20.000.000 messages (again for three hours)
And the we fixed the identity.

But in the host settings of the function I have the following.....

"logging": {
   "applicationInsights": {
   "samplingSettings": {
   "isEnabled": true,
   "maxTelemetryItemsPerSecond": 1,
   "excludedTypes": "Request"
   }
},
   "LogLevel": {
   "Default": "Error",
   "Host.Results": "Error",
   "Function": "Error",
   "Host.Aggregator": "Error"
  }
}

So how is this possible that it send so many errors ? MaxTelemetry is 1 per second !!!!!

**Comment by RohitRanjanMS** [comment]
Hi @well0549, maxTelemetryItemsPerSecond is only applicable to ApplicationInsights. It won't impact the volume of logs that you see in LogAnalytics and we don't have any ability to filter logs for LogAnalytics.
