### ISSUE TITLE
DI Scope for Function class constructor and HttpContext are different

### ISSUE THREAD

**Issue by finetester-dev** [Azure/azure-functions-host#9222]
#### Is your question related to a specific version? If so, please specify:
AzureFunctionsVersion v4 and TargetFramework  Dotnet6.0
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question
If Use DI using Function's Constructor Injection and  httpRequest.HttpContext.RequestServices.GetService(Rate) in FunctionInvocationFilterAttribute It gives me different instances, as on the bases of this Filter I need to perform certain action  using Rate instance. And I cannot add it as Singleton as the application is multiuser.

**Comment by kshyju** [comment]
Hi @finetester-dev Could you please share a minimal repro of this issue so that we can take a closer look? A link to a GitHub repo would be great.
