### ISSUE TITLE
collision for Host ID 'functionsv4placeholdertemplatesi' was detected

### ISSUE THREAD

**Issue by ArunasFalcon** [Azure/azure-functions-host#9223]
#### Investigative information

Please provide the following:

- Timestamp: 21. April 2023 um 4:12:04 GMT-4
- Function App version: 4.19.0.20414
- Function App name: func-zen-om-as-shd-dispatcher-wswadsftposl6
- Function name(s) (as appropriate): dispatcher (but not really relevant)
- Invocation ID: none
- Region: north europe

The function is deployed with an explicitly assigned host id, using this expression (bicep template):
`guid(uniqueString(<function name>))`

#### Repro steps

Open the overview page of the function

#### Expected behavior

Should not display errors

#### Actual behavior

The overview page displays the error:
"A collision for Host ID 'functionsv4placeholdertemplatesi' was detected in the configured storage account. For more information, see https://aka.ms/functions-hostid-collision."

Error Id: AZFD004

#### Known workarounds

None so far. Web search didn't turn up anything, search in the issue list didn't turn up anything either.
The function works correctly (but that's possible anyway with host id collisions due to pure chance).

#### Related information 

I ran

`Get-AzFunctionApp -ResourceGroupName '<the resource group>' | ForEach-Object { $_.ApplicationSettings.AzureFunctionsWebHost__hostid }`

and there are in fact no duplicates. The function func-zen-om-as-shd-dispatcher-wswadsftposl6 reporting the host id collision is in that list, and I verified the explicit host id setting.
Given that the host id reported in the error message (functionsv4placeholdertemplatesi) contains the term 'placeholder', and obviously we never set that host id manually and the generated host name is also completely different, I suspect a problem with the actual host id collision detection. The storage account for the functions also does not contain any folder called 'functionsv4placeholdertemplatesi' as would typically be the case if that would actually be the host id or host name.

**Comment by kshyju** [comment]
Are you using a storage account shared by more than one function app/same function with different slots?

**Comment by ArunasFalcon** [comment]
Hi, yes, around 30 function apps use the same storage account, That's why we are using AzureFunctionsWebHost__hostid and WEBSITE_CONTENTSHARE in the first place. Both are set to something that is unique.

**Comment by ArunasFalcon** [comment]
I did provide feedback...

**Comment by kshyju** [comment]
@ArunasFalcon Could you please open a support ticket so that the team can investigate the issue in your function app?

**Comment by ArunasFalcon** [comment]
I can do that of course, but quick question: it's been a month and there have been multiple incremental deployments to the function app. The portal doesn't show the message any more. I haven't found a way to see past advisor alerts, so will support still be able to look those up?
