### ISSUE TITLE
Concurrency management for function triggers

### ISSUE THREAD

**Issue by apranaseth** [Azure/azure-functions-host#9240]
Currently functions provides way to manage concurrency based on the number of triggers running per instance and maximum instances.   For Logic Apps stateful workflows, where the control is sent back to functions trigger soon after the trigger runs we need the function host/trigger to hold on and wait for some sort of a signal from Logic Apps to maintain concurrency on the triggers.

**Comment by mathewc** [comment]
SDK feature https://github.com/Azure/azure-webjobs-sdk/pull/3011 will unblock the LA and allow them to build these capabilities in their extension.
