### ISSUE TITLE
Dependency injection is broken since 4.19.0 for some C# function apps.

### ISSUE THREAD

**Issue by machielvisser** [Azure/azure-functions-host#9247]
Since the host upgraded to 4.19.0 we have some C# azure functions that suddenly can't resolve dependencies that are injected through the startup class. It looks a bit like the startup class is skipped.

**Comment by machielvisser** [comment]
The functions that don't work have a modified host.json that is different than the one we deploy with the function app. The functions that do work do have their original host.json file. When correcting the host.json file it starts working again. Now the questions is why did a host.json file of a running function app change by itself?

Wrong host.json:
```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.*, 3.0.0)"
  }
}
```

Correct host.json:
```
{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "default": "Information"
    },
    "applicationInsights": {
      "samplingExcludedTypes": "Request",
      "samplingSettings": {
        "isEnabled": true
      }
    }
  }
}
```

**Comment by machielvisser** [comment]
It seems we never actually deployed the correct host.json. So the wrong one was there all along. But since 4.19.0 it impacts the dependency injection of the function app apparently.

**Comment by jviau** [comment]
@machielvisser can you clarify your final comment - is there an issue here or not? Given an incorrect host.json, I am not surprised that causes DI failures as it could be drastically altering the application behavior. I don't see that as anything we can address as the issue lies in providing a bad host.json.
