### ISSUE TITLE
How to set custom handler arguments via Application settings?

### ISSUE THREAD

**Issue by xlight05** [Azure/azure-functions-host#9260]
#### Question
I'm in the process of adding debugging capabilities for Ballerina Azure functions ;). Ballerina is implemented using Custom handlers. I need to pass debug args to start the ballerina debug server upon `func start`. I noticed, in other languages such as java you can use the field "languageWorkers__java__arguments" in application settings to do this. What is the equivalent of that for custom handlers? 

Please note I want to do this using application settings. not host.json as we need vscode impl, we need to programmatically set these. 
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
Ballerina(Custom Handlers)

**Comment by soninaren** [comment]
Here is the documentation for setting arguments for custom handlers.
https://learn.microsoft.com/en-us/azure/azure-functions/functions-custom-handlers

Here is the documentation that describes how to override host.json config using app settings. 
https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings

Mainly you need to use the app setting in the following format. `AzureFunctionsJobHost__path__to__setting` in your case it should translate to `AzureFunctionsJobHost__customHandler__arguments`
