### ISSUE TITLE
Function failed with an exception 'Could not Find a part of the Path C:\local\Temp\Images\filename'

### ISSUE THREAD

**Issue by reykhan786** [Azure/azure-functions-host#9262]
I am using azure function version 3 using .net 3.1 . I am writing bytes to the Images folder C:\local\Temp\Images\
and when i am trying to read the file from the same folder i am getting error  'Could not Find a part of the Path C:\local\Temp\Images\filename'

This was working fine on production instance but suddenly it is throwing this error.

**Comment by liliankasem** [comment]
@reykhan786 v3 has reached EOL (end of life) - we recommend migrating to v4: 

- [Migrate version 3 to version 4](https://learn.microsoft.com/en-us/azure/azure-functions/migrate-version-3-version-4?tabs=net6-in-proc%2Cazure-cli%2Cwindows&pivots=programming-language-csharp)

If you're still seeing issues and this is impacting production, please open a support case with Azure.
