### ISSUE TITLE
Consumption plan based Function App not awakening to process Queue messages.

### ISSUE THREAD

**Issue by jgmeier** [Azure/azure-functions-host#9286]
We have an Azure Function App with Queue trigger running on a Consumption plan that seems to go to sleep and not wakeup to process new messages.  As has been reported in this repository several times over the years, if I log into the resource in Azure Portal the function appears to awaken shortly after and process the messages, but within 24 hours or less will re-enter its slumbered state and not awaken again.  

We are running ~v4 function runtime.

I'll be glad to provide additional identifying info as needed.

Thanks.

**Comment by kshyju** [comment]
@jgmeier I suggest you open a ticket with the support so that the team can investigate what is going on with your app.

**Comment by jgmeier** [comment]
This issue appears to have resolved itself.

**Comment by sam-bradshaw-wcmc** [comment]
Seeing the same issue start appearing
