### ISSUE TITLE
Update table client behind scale metrics

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-host#9287]
The scale metrics respoitory is using an old table client of its own:
https://github.com/Azure/azure-functions-host/blob/a9e69d28e22188db35ec4c2956e1363681da8db2/src/WebJobs.Script.WebHost/Scale/TableStorageScaleMetricsRepository.cs#L40

That need to be updated to use `Azure.Data.Tables` instead of the deprecated `Microsoft.Azure.Cosmos.Table`.

We also need to reassess the fact that this component is just creating its own client against a known connection without overrides. That pattern is not sustainable.

**Comment by fabiocav** [comment]
Duplicate of #10166
