### ISSUE TITLE
Map WebJobs RPC extensions onto the gRPC host

### ISSUE THREAD

**Issue by jviau** [Azure/azure-functions-host#9291]
This issue is to track the work related to consuming the new WebJobs extensions that will be added as part of https://github.com/Azure/azure-webjobs-sdk/pull/2978. The necessary work for the functions host is to:

When the WebJobs script host is ready:
1. discover `WebJobsRpcEndpointDataSource` from the new script host's `IServiceProvider`.
2. map them onto the gRPC hosts available endpoints.

Additionally, as part of mapping the endpoints we should:

1. Ensure the gRPC service is resolved from a new scope of the script hosts `IServiceProvider`
2. Replace the `HttpContext.RequestServices` with the script hosts `IServiceProvider`.

**Comment by fabiocav** [comment]
Changes merged into the feature branch. Moving this to sprint 150 to track completion and merge into `dev`
