### ISSUE TITLE
Enabling drain mode causes cancelling sending invocation to the language workers on the ServiceBus listener stop

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-host#9298]
Current ServiceBus code implements graceful shutdown for C# in-proc functions when we are about to shut down the host. 
To achieve this we  [cancel the token](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Listeners/ServiceBusListener.cs#L228) and then [close](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Listeners/ServiceBusListener.cs#L239) the processor – this allow to request cancelations in in-flight executions.

The problem is that CloseAsync does not stop receiving messages immediately - new messages can be delivered after starting CloseAsync (for initial 100-200ms), CloseAsync is finished – no new deliveries.
For out-of-proc we have the code which cancels executions when cancelation is requested – we do not send invocation to language worker. For SB it leads to multiple deliveries and coping to dead latter queue as well as skipping executions the SB trigger code.
[azure-functions-host/GrpcWorkerChannel.cs at 428215c25052dfde38e66fd064b9981dffbda562 · Azure/azure-functions-host (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-functions-host%2Fblob%2F428215c25052dfde38e66fd064b9981dffbda562%2Fsrc%2FWebJobs.Script.Grpc%2FChannel%2FGrpcWorkerChannel.cs%23L743&data=05%7C01%7Calrod%40microsoft.com%7Cdbfb781e076b4aca233908db62de5a2a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638212479376999829%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Hv5SDeUu1hS%2FTP5BFOE%2Fu4zwC2yd0wHwpAHFkcmzJGI%3D&reserved=0)

                // do not send an invocation request if cancellation has been requested
                if (context.CancellationToken.IsCancellationRequested)
                {
                    _workerChannelLogger.LogWarning("Cancellation has been requested. The invocation request with id '{invocationId}' is canceled and will not be sent to the worker.", invocationId);
                    context.ResultSource.TrySetCanceled();
                    return;
                }

Is there any reason to have the code above to skip sending invocation to the language worker? Do we cancel the execution if it’s C# in-proc?

Internal email thread title: "Service Bus message got triggered between SB listener being "attempted to stopped" & "actually stopped" ICM 381018457"

**Comment by alrod** [comment]
Closing - the issue is on SB extension side:
https://github.com/Azure/azure-sdk-for-net/pull/36792

**Comment by alrod** [comment]
Reopening to investigate, it looks like the ServiceBus fix is not a proper fix.

**Comment by AnatoliB** [comment]
Resolved by https://github.com/Azure/azure-sdk-for-net/pull/38063
