### ISSUE TITLE
When will Azure Functions support NET 8?

### ISSUE THREAD

**Issue by sjuarezgx** [Azure/azure-functions-host#9340]
I´d like to know when it will be possible to have Azure functions support for NET 8
Thanks

**Comment by kshyju** [comment]
[Dotnet isolated model](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide) will support NET8.0 in a few weeks. No specific dates to share at this point. Please follow the below issue to get updates about the progress.

[.NET 8.0 support](https://github.com/Azure/azure-functions-dotnet-worker/issues/1644)

**Comment by ZepHakase22** [comment]
I didn't understand whether or not .Net 8 will support in process model or only isolated model.

**Comment by kshyju** [comment]
At RTM, .NET 8 support will be only in the isolated model.
