### ISSUE TITLE
HTTP proxying mode still sends gRPC representation

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-functions-host#9343]
Dispatch for an HTTP-triggered function using the new mode still includes the old behavior, in addition to the new. There is an unnecessary deserialization of the request into the gRPC representation, and an attempt to send that to the worker. This gets in the way of large request payload streaming, as we'd hit the same bottleneck as when HTTP request proxying is not in play.

**Comment by brettsam** [comment]
Fixed with #9415
