### ISSUE TITLE
Invalid secrets file format during Warmup

### ISSUE THREAD

**Issue by codermrrob** [Azure/azure-functions-host#9353]
#### Is your question related to a specific version? If so, please specify: 
Using AzureFunctionsVersion V4

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question

I have a function which has been working fine. A new branch for this function extended use of redis to include key/value storage for state data and did some major refactoring.

Now when I try to start the function locally I am consistently getting the following error :

```
A host error has occurred during startup operation '287cd2d0-14cb-4833-ba33-96f7131c6368'.
Microsoft.Azure.WebJobs.Script.WebHost: Invalid secrets file format.
```

then shortly after another error message in the log:
```
Value cannot be null. (Parameter 'provider')
```

The complete warmup log from starting the function to the final error message is attached.

I can't find much/any specific reference to this error anywhere. I located what seems to be the secrets file and it looks like it is automatically generated. If I delete it, it is recreated and I still receive the error.

The log from the start to the error is attached.
[warmup.log](https://github.com/Azure/azure-functions-host/files/11890718/warmup.log)

The secrets file (host.json) in emulator storage referenced is:

```
{
  "$type": "Microsoft.Azure.WebJobs.Script.WebHost.HostSecrets, Microsoft.Azure.WebJobs.Script.WebHost",
  "masterKey": {
    "$type": "Microsoft.Azure.WebJobs.Script.WebHost.Key, Microsoft.Azure.WebJobs.Script.WebHost",
    "name": "master",
    "value": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==",
    "encrypted": false
  },
  "functionKeys": {
    "$type": "System.Collections.Generic.List`1[[Microsoft.Azure.WebJobs.Script.WebHost.Key, Microsoft.Azure.WebJobs.Script.WebHost]], System.Private.CoreLib",
    "$values": [
      {
        "$type": "Microsoft.Azure.WebJobs.Script.WebHost.Key, Microsoft.Azure.WebJobs.Script.WebHost",
        "name": "default",
        "value": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX==",
        "encrypted": false
      }
    ]
  },
  "systemKeys": {
    "$type": "System.Collections.Generic.List`1[[Microsoft.Azure.WebJobs.Script.WebHost.Key, Microsoft.Azure.WebJobs.Script.WebHost]], System.Private.CoreLib",
    "$values": []
  },
  "hostName": "localhost:7021",
  "instanceId": "000000000000000000000000B54BA274",
  "source": "runtime",
  "decryptionKeyId": ""
}
```

Can someone provide me any guidance or pointers or any ideas on how I might fix or work around this error? Thank you.

**Comment by snoova** [comment]
Same here. Any Ideas?

**Comment by liliankasem** [comment]
Hi, could you please share a minimal code repro project for investigation?

Understanding if this is dotnet or dotnet-isolated, the nuget packages references, the host.json file, the host version, the core tools version, the storage enumerator version and how Program.cs( if used) is setup would help. 

Is this issue happening in Azure or just local?
