### ISSUE TITLE
WEBSITE_TIME_ZONE app setting breaks duration times shown

### ISSUE THREAD

**Issue by wesmc7777** [Azure/azure-functions-host#936]
I set a WEBSITE_TIME_ZONE app setting to "Eastern Standard Time" in order to be able to specify CRON expressions in local time (EST).

This may very well have introduced this behavior.  

#### Repro steps

Provide the steps required to reproduce the problem

1. Set a WEBSITE_TIME_ZONE app setting for the Function app to "Eastern Standard Time" 
2. Function executions after the setting change can have duration times shown on the Monitor tab as negative values. For example, "a few seconds ago	(-17,999,874 ms)"

#### Expected behavior

Correct duration calculation with new timezone set.

#### Actual behavior

Function duration times shown on the Monitor tab can now show negative values. For example, "a few seconds ago	(-17,999,874 ms)"

#### Known workarounds

Remove WEBSITE_TIME_ZONE app setting

#### Related information 

Provide any related information 

* Programming language used 
* Links to source

**Comment by davidebbo** [comment]
Interestingly, if you go to the WebJobs dashboard (/azurejobs on the scm site), then everything looks fine. But in Portal, it's messed up.

I think what's happening is that the API is returning data in the local timezone, and the portal is interpreting it as UTC. So I think the bug is in the logging logic, that should always be logging everything in UTC, and likewise the API that needs to be pure UTC.

**Comment by davidebbo** [comment]
I verified that it's the /azurejobs API that's returning bogus data. e.g. look at `duration` in:

```
    {
      "executingJobRunId": null,
      "id": "0b5294fe-841a-4648-99ee-96c04d592176",
      "functionId": null,
      "functionName": null,
      "functionFullName": null,
      "functionDisplayTitle": "HttpTriggerCSharp1 (Method: POST, Uri: ...)",
      "status": "CompletedSuccess",
      "whenUtc": "2016-11-16T22:34:24.9014148Z",
      "duration": -17999140.6634,
      "exceptionMessage": null,
      "exceptionType": null,
      "hostInstanceId": "00000000-0000-0000-0000-000000000000",
      "instanceQueueName": null
    },
```

**Comment by MikeStall** [comment]
All our calculations should be using UTC (so timezone should be irrelevant). We must be missing one somewhere.

**Comment by lindydonna** [comment]
@MikeStall we should fix this ASAP, can you take it for the current milestone?

**Comment by MikeStall** [comment]
This may be related to https://github.com/Azure/azure-webjobs-sdk/issues/815

**Comment by MikeStall** [comment]
@wesmc7777  - would you rather we add a TimeZone property to TimeTrigger so that you didn't need to adjust WEBSITE_TIME_ZONE  at all?  Or are you adjusting WEBSITE_TIME_ZONE  for other reasons?

**Comment by wesmc7777** [comment]
@MikeStall @lindydonna 

I discovered this while adding doc coverage for the timer trigger. I don't have a business case of my own for this.  Mathew had given this approach (WEBSITE_TIME_ZONE) to a few customers who needed, or wanted, their timer triggers to fire based on local time. Customers asking for this generated a need for doc coverage,  This is presently a documented option in our docs for the time trigger binding reference.  I think the customers who were involved would overwhelmingly support the time zone property as a resolution.

**Comment by fabiocav** [comment]
Closing stale issue. This should no longer be an issue, but please let us know if you feel this was closed in error.
