### ISSUE TITLE
Investigate issue with changes to test_data causing Node to be unavailable

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#9365]
Creating this to track a recently reported issue where updates to `test_data`, which is a file the portal will use to persist test/run data, are causing Node instability. 

Changes to that file should not impact the worker, but we're seeing the host go into a bad state, reporting an uninitialized worker when that happens (`Did not find any initialized language workers`, requiring a host restart for recovery).

Steps to repro the issue:

1. Create a Node.js app in the portal (old programming model)
2. Add an http trigger
3. Modify `test_data` (if running through the portal, simply use test/run)

This seems related to the worker indexing capability enablement.

**Comment by liliankasem** [comment]
@brettsam  @kshyju did either of you look into this at all?

**Comment by liliankasem** [comment]
Resolved via #9501
