### ISSUE TITLE
Should Application Insights logs display in Functions Core Tools?

### ISSUE THREAD

**Issue by davidlfox** [Azure/azure-functions-host#9378]
#### Is your question related to a specific version? If so, please specify:
function v4

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C# (probably others)

#### Question
Should application insights logs render when debugging locally? I've seen numerous posts that say "just use Azure storage and configure instrumentation key, etc" but this should work locally. I've tried modifying `local.settings.json` e.g.

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "System": "Information",
      "Microsoft": "Information"
    },
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "Trace"
      }
    }
  },
```

and no logs appear in the debug console in Visual Studio 2022 or the Functions Core Tools console when running lines like `_logger.LogInformation..` or `_logger.LogMetric...`

**Comment by RohitRanjanMS** [comment]
Hi @davidlfox , you should see the logs in debug console. Do you have the InstrumentationKey/ConnectionString defined in localsettings when you debug locally?

<img width="1048" alt="image" src="https://github.com/Azure/azure-functions-host/assets/90008725/3f1e8d3d-f661-4887-aabe-6c1b5f2d117a">

**Comment by davidlfox** [comment]
what should the values be when debugging locally if im not connected to an azure storage account?

**Comment by RohitRanjanMS** [comment]
@davidlfox you can use development storage. You need AI Connection string to see logs in the debug console. We don't load the AI related dependencies if you don't set the connection string.

{
    "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "APPLICATIONINSIGHTS_CONNECTION_STRING": "<connection string>"
  }
}

**Comment by davidlfox** [comment]
i got `LogInformation` working but what about `LogMetric` e.g. `ILoggerExtensions.LogMetric(_logger, "eventCount", 0);`? that doesnt output to the console. is that managed a different way?

**Comment by RohitRanjanMS** [comment]
you should see metrics as well.

<img width="813" alt="image" src="https://github.com/Azure/azure-functions-host/assets/90008725/1ba19be2-c550-4bae-b1e1-a3d6feffddae">
