### ISSUE TITLE
No-error-message: Setting extension bundle in dotnet-isolated results in 0 Functions started

### ISSUE THREAD

**Issue by paulyuk** [Azure/azure-functions-host#9396]
If I use one of the common host.json files that asserts extension bundles, the deployed app will silently fail to load with 0 functions started.  

I expected to get an error message saying extension bundle config in host.json is invalid, and read <url> to learn how to set properly for dotnet-isolated.

Repros in cloud and using Core Tools 4.0.5198.

#### Repro steps

1. func init -> dotnet-isolated
2. func new -> HTTP
3. Change host.json to this:
```
{
    "version": "2.0",
    "logging": { "fileLoggingMode": "debugOnly", "logLevel": { "default": "Information", "Host.Results": "Error", "Function": "Error", "Host.Aggregator": "Trace" } },
    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[4.0.0, 5.0.0)"
    }
}
```
4. func start, or deploy

#### Expected behavior

In Application insights logs I would see a specific message after 0 Functions start:

"ExtensionsBundle config in host.json is invalid for dotnet-isolated.  See <url> for details."

**Comment by mattchenderson** [comment]
This is the line of code that needs to be updated: 
https://github.com/Azure/azure-functions-host/blob/6ae92c8b8d50217a528465fcf54eb7bc0358009f/src/WebJobs.Script/DependencyInjection/ScriptStartupTypeLocator.cs#L102

An additional OR statement is needed to catch isolated as well. The value being looked for right now is just "DotNetAssembly", but I believe `functionMetadata.Language` will be "dotnet-isolated" in this case.
