### ISSUE TITLE
No-error-message: using Managed identity for storage + zipdeploy + Linux consumption

### ISSUE THREAD

**Issue by paulyuk** [Azure/azure-functions-host#9397]
#### Check for a solution in the Azure portal
Currently it is not supported to use standard approach for managed identity on functions storage account in Linux Consumption with zip deploy.

This issue tracks the lack of error message when the user/deployment is in this state, because all you see is `0 Functions started` in the application insights logs.

#### Repro steps

To repro:
1) clone and run this hello world python v2 sample
[functions/starters/python at main · paulyuk/functions · GitHub](https://github.com/paulyuk/functions/tree/main/starters/python)

2) `azd up` (provisions the RG, does a zip package and zipdeploy)

Note the http function works now at route /api/http
 

3) Verify Identity - System Managed Identity on the Functionapp (already done ) is enabled

4) Add IAM roles to storage account, in particular the Storage Blob Data Owner and grant to the system managed identity of the function

Note the function *still works fine, but will break in the next step:

5) Change the connection string to use managed identity instead of connectionstring with key/secret

From

  {

    "name": "AzureWebJobsStorage",

    "value": "..shh its a secret..",

    "slotSetting": false

  }

 

To

  {

    "name": "AzureWebJobsStorage__accountname",

    "value": "stgvcf47zjvz27e",

    "slotSetting": false

  },

6) restart the function and test /api/http

 

Result:
Function is down / 404
App Insights lights show "1 functions found; 0 functions loaded".

#### Expected behavior

There is an error message describing this unsupported configuration of Linux Consumption with zipdeploy and managed identity, and see <url> for more info and workarounds (namely server build). 

-->

#### Known workarounds

Use server build (non tools based) methods described here

https://learn.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies?tabs=windows

**Comment by paulyuk** [comment]
related to https://github.com/Azure/azure-functions-python-worker/issues/1288

**Comment by fabiocav** [comment]
Investigation is in progress. @surgupta-msft is collecting some additional information about the issue and will start working on implementing a fix in sprint 154

**Comment by surgupta-msft** [comment]
The PR is merged to improve the error logs on Host side. We are also planning to build a detector on this log, that will be tracked [here](https://dev.azure.com/Azure-Functions-Supportability/IPD%20Reduction/_workitems/edit/907).
