### ISSUE TITLE
Diagnostic Events should be written to Kusto

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-host#9404]
Diagnostic events should be written to Kusto, so we can write a detector for these. 

/cc @paulyuk, @mattchenderson @FinVamp1 @soninaren @eamonoreilly @fabiocav

**Comment by fabiocav** [comment]
Assigning this for investigation/validation, as this should already be the case.

**Comment by fabiocav** [comment]
@Francisco-Gamino , after investigation, @soninaren has confirmed this is flowing into Kusto as expected. 

The one thing that is missing is the event ID, but Naren is looking into bringing that into Kusto as well.

@soninaren can you please link to the issue you're using to track that work? Thanks!
