### ISSUE TITLE
"404 not found" while trying to upgrade from .net core app 3.1 to 6.0

### ISSUE THREAD

**Issue by Alice010242** [Azure/azure-functions-host#9451]
Framework: netcoreapp3.1 --> net6.0
AzureFunctionsVersion: v3 --> v4

We leverage on Azure CI/CD to do the deployment. However, we got "404 not found" after the deployment to a slot.
I have checked all the possible problems listed in the [log](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/how-to-troubleshoot-azure-functions-http-trigger-404-error/ba-p/3766817#:~:text=One%20of%20the%20common%20causes,result%20in%20a%20404%20error.), still no luck. 
cs project file: 

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.7.0" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.34.0" />
    <PackageReference Include="Microsoft.Azure.Kusto.Data" Version="11.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="3.0.12" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.3.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="4.0.1" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.47.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AzureResourceLib\AzureResourceLib.csproj" />
    <ProjectReference Include="..\ICPEmailService\ICPEmailService.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>`

**Comment by mattchenderson** [comment]
Hi - this isn't enough information for us to action on here. Is there a particular operation returning the 404 that you can identify? You may also consider opening a support ticket.
