### ISSUE TITLE
HTTP Request timeouts

### ISSUE THREAD

**Issue by jeroenvermunt** [Azure/azure-functions-host#9462]
As of the 10th of august 2023, some HTTP requests are suddenly timing out whilst working normally on locally hosted functions.

#### Repro steps
Perform a common get request:
````
url = 'get_request'
response = requests.get(url, timeout=100)
````

#### Expected behavior
expected to receive a 200 response 

#### Actual behavior
actually throws a timeout on the HTTPConnectionpool:
````
ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='<api_host>', port=443): Max retries exceeded with url: <endpoint>
(Caused by NewConnectionError(': Failed to establish a new connection: [Errno 101] Network is unreachable'))
````

#### Related information 
- I tried migrating from EU-north to EU-west, this did not change anything
- This only happens for specific api calls, for which I cannot provide a reproducible version due to privacy of these endpoints (require authentication)
- Runtime 4.23.00
- I cannot seem to properly debug the requests, for which the suite proposed in #9438 may be useful.

This behavior makes our functions apps unusable and unreliable, and currently the only solution seems to be migrating to a different host.

**Comment by bhagyshricompany** [comment]
Thanks for reporting.Meanwhile you can share the func app name region timestamp etc. will check and update you
