### ISSUE TITLE
Function that is failing to compile should not continue to execute (and fail) repeatedly

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-host#950]
We've seen cases with a failing script compilation hooked up to a high throughput event source (such as an event hub with a large number of events). Its extremely wasteful - we should stop the function from triggering until there is a successful compilation.

**Comment by cgillum** [comment]
Related (possibly duplicate) issue: https://github.com/Azure/azure-webjobs-sdk-script/issues/169

**Comment by christopheranderson** [comment]
@mathewc will come up with a proposal
