### ISSUE TITLE
UTF-8 encoding in Azure Functions context. .NET 7

### ISSUE THREAD

**Issue by lucas-fsousa** [Azure/azure-functions-host#9508]
#### Question
Hello. I'm having trouble applying UTF8 encoding in my application context. I created a test function to evaluate if the server is UP, the function.

There is an internal service that saves the log in the database and writes in the console, this implements the Ilogger. The function just returns an HTTP OK status with the message "Azure functions funcionando OK na codificação UTF-8 [àáâãçéèêíìîóòôõúùû]" and saves that same message in the database, but the result that is presented in the console, in the database and in the http response is "Azure functions funcionando OK na codifica��o UTF-8 [������������������]"

Any suggestion? I looked in the documentation and also in internet forums, but I didn't find anything that could solve this problem.

The log service works perfectly, this is shared by all the solution that has console application and Web API, I never had this problem anywhere, only in the Azure functions project

OBS:  This issue only occurs in my Azure Functions container when deploying to production.

My code is:
```csharp
public class VerificaDisponibilidade {
  private readonly LogService logService;
  public VerificaDisponibilidade(LogService log) { 
    logService = log;
  }

  [Function("VerificaDisponibilidade")]
  public async Task<HttpResponseData> Run([HttpTrigger(AuthorizationLevel.Function, "get")] HttpRequestData req) {
    var response = req.CreateResponse(HttpStatusCode.OK);
    response.Headers.Add("Content-Type", "text/plain; charset=utf-8");

    logService.LogInformation($"Azure functions funcionando OK na codificação UTF-8 [àáâãçéèêíìîóòôõúùû]");
    await response.WriteStringAsync($"Azure functions funcionando OK na codificação UTF-8 [àáâãçéèêíìîóòôõúùû]");

    return response;
  }
}
```

**Comment by bhagyshricompany** [comment]
Thanks for reporting pls share the function name,  app name,region,timestamp etc

**Comment by lucas-fsousa** [comment]
Hello @bhagyshricompany! How can I get the timestamp?

Below I make available a test carried out by the Azure Test Field which shows the return completely out of expectations.

#### Request Logs
2023-09-05T16:00:28Z   [Information]   Executing 'Functions.VerificaDisponibilidade' (Reason='This function was programmatically called via the host APIs.', Id=bc56213a-3ee8-48be-b8e9-2678e6e32a2a)
2023-09-05T16:00:28Z   [Verbose]   Sending invocation id: 'bc56213a-3ee8-48be-b8e9-2678e6e32a2a
2023-09-05T16:00:28Z   [Verbose]   Posting invocation id:bc56213a-3ee8-48be-b8e9-2678e6e32a2a on workerId:63bf7945-72c9-48ba-9af7-234da20349a0
2023-09-05T16:00:30Z   [Information]   Executed 'Functions.VerificaDisponibilidade' (Succeeded, Id=bc56213a-3ee8-48be-b8e9-2678e6e32a2a, Duration=2333ms)

#### HTTP response content
OK - UTF-8 [������������������]

#### Here is also part of the requested information (no timestramp)

AppName -> func-flixlead-prod
Location -> Brazil South
Docker Container Location -> Brazil South
FuncName -> VerificaDisponibilidade

**Comment by bhagyshricompany** [comment]
FUNCTIONS_WORKER_RUNTIME doesn't exist in your app settings.This is a mandatory settings which specifies the language worker runtime to load in the function app. This will correspond to the language being used in your application. pls check

**Comment by lucas-fsousa** [comment]
I added this environment variable with the value "dotnet-isolated" and still the problem persists. I also found a file called worker.config.json that already has this language setting for "dotnet-isolated" set.

**Comment by lucas-fsousa** [comment]
I made this configuration within the Azure settings panel. There the item "FUNCTIONS_WORKER_RUNTIME" was defined with the value "dotnet-isolated". I saved the configuration and restarted the services. But the problem persisted.

**Comment by bhagyshricompany** [comment]
Please raise the the request on Azure portal.

**Comment by lucas-fsousa** [comment]
I abandoned the project due to time constraints in delivering the product. I had to choose other things, so the project was removed from the portal. At this moment, I cannot upload the structure again, I will consider this issue closed.
