### ISSUE TITLE
Publish Microsoft.Azure.Webjobs.Script.Abstractions new version

### ISSUE THREAD

**Issue by swghimire** [Azure/azure-functions-host#9527]
#### What problem would the feature you're requesting solve? Please describe.
Logic Apps repo is using Microsoft.Azure.Webjobs.Script.Abstractions 1.0.0-preview and that is causing a transitive dependency issue related to Newtonsoft.Json. 

#### Describe the solution you'd like
There is a version of this package available on MyGet, 1.0.4-preview. Could we try to have that published? 

#### Describe alternatives you've considered
na 

#### Additional context
na

**Comment by liliankasem** [comment]
Closing as dupe, will be addressed by https://github.com/Azure/azure-functions-host/issues/7533
