### ISSUE TITLE
EventHubTrigger on EventData[] processing same event multiple times

### ISSUE THREAD

**Issue by NattyMojo** [Azure/azure-functions-host#9543]
#### Investigative information

Please provide the following:

- Timestamp: 09/13/2023 20:27:09 thru 09/13/2023 20:59:06
- Function App version: 4.1.3
- Function App name: gsp01fap-getpaid-ext-prod
- Function name(s) (as appropriate): ProcessSalesOrderEvents
- Invocation ID:
- Region: West US 2

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create function with EventHubTrigger for EventData[] for processing batches that logs message id's 
2. host.json:  "eventHubs": {
      "maxEventBatchSize": 200,
      "minEventBatchSize": 50,
      "maxWaitTime": "00:02:00"
    }
3. Send chunk of messages (>1k or so)
4. See logs for messages handled multiple times

#### Expected behavior

Should see each message only processed one time ever.

#### Actual behavior

Single message being handled many times over.
![image](https://github.com/Azure/azure-functions-host/assets/37313152/e4ac1b46-7d96-4663-a134-da8b4771545c)

#### Known workarounds

None

#### Related information 

.NET 6 application
Microsoft.Azure.WebJobs.Extensions.EventHubs: 5.3.0

**Comment by NattyMojo** [comment]
Found new releases for the Microsoft.Azure.WebJobs.Extensions.EventHubs, tried 5.4.0 and still seeing this issue. Thought maybe the release notes about scaling and checkpoints would help this situation, but appears not.
> Fixed a race condition when Function instances are scaling that could cause a checkpoint to be written before the Function code was invoked to process events. This would result in the new owner for the partition skipping those events causing them to go unprocessed.

**Comment by bhagyshricompany** [comment]
Thanks for reporting this issue Will check and update.

**Comment by bhagyshricompany** [comment]
@fabiocav  please comment.

**Comment by drdamour** [comment]
@NattyMojo think this is better opened in the extension itself at https://github.com/Azure/azure-sdk-for-net

**Comment by NattyMojo** [comment]
Issue resolved in v6+ of the Microsoft.Azure.WebJobs.Extensions.EventHubs package (see https://github.com/Azure/azure-sdk-for-net/issues/39267) upgraded and all is well. Closing this thread.
