### ISSUE TITLE
Skip specialization using native placeholder if platform setting is not 64 bit

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-functions-host#9548]
For dotnet-isolated placeholder support, our [documentation recommends](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#placeholders-preview) customers to use "64 bit" platform setting. But as of today, if they don't make that change, specialization will fail because our native placeholder component would not be able to load 32 bit assemblies.  We should update host code to skip specialization code executing using the native component and fallback to loading the customer assembly directly.

**Comment by kshyju** [comment]
cc @safihamid @mattchenderson

**Comment by safihamid** [comment]
@kshyju please make sure we update the code in Antares to create native isolated SLA sites as 64bit. The change is somewhere in Antares repo where SLA sites get created.
