### ISSUE TITLE
Azure functions host randomly fails on SAS token check

### ISSUE THREAD

**Issue by tgjzd** [Azure/azure-functions-host#9558]
Since yesterday, consumption plan function apps started to fail randomly. Function app stops working completely. Http endpoints return: 
`HTTP Error 500.30 - ASP.NET Core app failed to start `
Azure Portal stops providing runtime version and functions list.
It affects only some of my function apps - all of them share the same region, are 32bit, uses the same app settings format etc.

#### Investigative information

- Timestamp: 2023-09-21T08:35:15Z
- Function App version: can't say - portal shows "---"
- Function App name: azwe-tacho-analysis-fun-q02
- Function name(s) (as appropriate):
- Invocation ID: n/a
- Region: westeurope

This happened for the first time yesterday. Today I managed to reproduce the same error.

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create Windows Dotnet Azure Functions 32bit, consumption plan with simple HTTP Endpoint(to keep functionapp alive)
2. Use app settings using following format:

`AzureWebJobsStorage = DefaultEndpointsProtocol=https;AccountName=[SANAME];AccountKey=[SAKEY];EndpointSuffix=core.windows.net`

`WEBSITE_RUN_FROM_PACKAGE = 1`

`WEBSITE_CONTENTAZUREFILECONNECTIONSTRING = DefaultEndpointsProtocol=https;AccountName=[SANAME];AccountKey=[SAKEY];EndpointSuffix=core.windows.net`

3. Create availability test in Application Insights which pings http endpoint every 5 minutes
4. Set function app scale out limit to 1 instance(in order to maximise the probability that we will have the same working instance for a long time)
5. Wait for failing availability tests

Step 4 is not mandatory, bug occurs also without an instance limit, however, it may be easier to reproduce with instance limit.

#### Expected behavior

Function app is running.

#### Actual behavior

Function app stops working for good. It requires manual restart.

eventlog.xml contains:
```xml
 <Event>
    <System>
      <Provider Name=".NET Runtime" />
      <EventID>1026</EventID>
      <Level>1</Level>
      <Task>0</Task>
      <Keywords>Keywords</Keywords>
      <TimeCreated SystemTime="2023-09-20T13:13:01Z" />
      <EventRecordID>251963375</EventRecordID>
      <Channel>Application</Channel>
      <Computer>10-30-22-134</Computer>
      <Security />
    </System>
    <EventData>
      <Data>Application: w3wp.exe
        CoreCLR Version: 6.0.2023.32017
        .NET Version: 6.0.20
        Description: The process was terminated due to an unhandled exception.
        Exception Info: System.AggregateException: One or more errors occurred. (Invalid URI: The
        format of the URI could not be determined.)
        ---&gt; System.UriFormatException: Invalid URI: The format of the URI could not be
        determined.
        at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind,
        UriCreationOptions&amp; creationOptions)
        at System.Uri..ctor(String uriString)
        at Microsoft.Azure.WebJobs.Script.Utility.GetSasTokenExpirationDate(String valueToParse,
        Boolean isAzureWebJobsStorage) in /_/src/WebJobs.Script/Utility.cs:line 896
        at
        Microsoft.Azure.WebJobs.Script.WebHost.Health.TokenExpirationService.EmitLogging(Dictionary`2
        appSettings) in /_/src/WebJobs.Script.WebHost/Health/TokenExpirationService.cs:line 100
        at
        Microsoft.Azure.WebJobs.Script.WebHost.Health.TokenExpirationService.AnalyzeSasTokenInUri()
        in /_/src/WebJobs.Script.WebHost/Health/TokenExpirationService.cs:line 88
        at
        Microsoft.Azure.WebJobs.Script.WebHost.Health.TokenExpirationService.ExecuteAsync(CancellationToken
        cancellationToken) in /_/src/WebJobs.Script.WebHost/Health/TokenExpirationService.cs:line 57
        at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean
        throwOnFirstFailure)
        at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
        at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken
        token, String startupMessage)
        at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken
        token, String startupMessage)
        at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken
        token)
        --- End of inner exception stack trace ---
        at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
        at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken
        cancellationToken)
        at System.Threading.Tasks.Task.Wait()
        at Microsoft.Azure.WebJobs.Script.WebHost.Program.Main(String[] args) in
        /_/src/WebJobs.Script.WebHost/Program.cs:line 30
      </Data>
    </EventData>
  </Event>
```

#### Known workarounds

Manual restart of function app.

Not tested: Probably using other format of related app setting values helps.

#### Related information 

I suspect that this error is related to changes from the following PR: https://github.com/Azure/azure-functions-host/pull/9381
I run locally`WebJobs.Script.WebHost` project using `WEBSITE_RUN_FROM_PACKAGE, WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` app settings with previously mentioned format and it throws the same exception.

**Comment by mdarefull** [comment]
This is happening for my customer as well to one of their production Azure Functions. We maintain 6 Azure Functions APIs in two environments (testing and production), 3 use consumption mode, their configurations and the way we work with them is almost identical. However one of them has started to randomly fail with this same exact error. 

The first exception we have on record is from 9/20/2023, 1:12:10.5838682 AM Central Time. Since then we have been receiving these errors randomly and the only way to fix them is by restarting the Function App.

**Comment by mdarefull** [comment]
@tgjzd Have you found any other workaround? What did you mean when you say:

> Not tested: Probably using **other format of related app setting** values helps.

**Comment by mdarefull** [comment]
Due to the urgency of this issue to my customer (it is affecting real production users), I went ahead and reviewed the PR referenced by @tgjzd. I believe the issue is that the code in 

> Microsoft.Azure.WebJobs.Script.WebHost.Health.TokenExpirationService.AnalyzeSasTokenInUri()

Is assuming the value of the App Settings 'WEBSITE_RUN_FROM_PACKAGE' to be an URI, which in all my cases is 1.

**Comment by tgjzd** [comment]
I thought about using value that conforms expected uri format, but now, I'm afraid that it's applicable only to `WEBSITE_RUN_FROM_PACKAGE` setting, since the `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` can't be just an url. However, I'm not sure which one causes exceptions.

Probably temporary pinning runtime version can help. According to https://github.com/Azure/azure-functions-host/releases page, related changes were made in 4.26.0 version, so probably we can just pin to earlier version, e.g.
`FUNCTIONS_EXTENSION_VERSION = 4.25.2` 
however, I haven't tested it yet. I'm looking forward to any answer from the project team in this issue.

**Comment by aishwaryabh** [comment]
Yes the issue is with us expecting `WEBSITE_RUN_FROM_PACKAGE` to be a URI but the parsing fails since it isn't a URI. I'll have a PR ASAP to mitigate this issue. For a workaround, like @tgjzd mentioned pinning to a previous host version without these changes should work :)
