### ISSUE TITLE
Azure Function Host vs Webjobs SDK memory usage

### ISSUE THREAD

**Issue by jsheetzmt** [Azure/azure-functions-host#9567]
#### Investigative information

Hello, we are hosting Azure functions in Azure Container Apps and see a vastly higher memory footprint compared to the WebJobs SDK.

#### Repro steps

1. Create docker image using `mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated7`.
2. Timer triggers using dotnet-isolated
3. Deploy to Azure Container Apps
4. Watch memory usage in Azure Metrics

#### Expected behavior

Azure Function Host has comparable memory to using Webjobs SDK. 

#### Actual behavior

Azure Functions nearly doubles the amount of memory in use

1. Azure Function Host: 300mb+ memory usage
2. Webjobs SDK: 180mb memory usage

![image](https://github.com/Azure/azure-functions-host/assets/103272899/8097a6cd-c5cc-447d-b494-8a232643293b)

#### Known workarounds

Use Webjobs SDK

#### Related information 

- NET 7
- C#

Issues:

- https://github.com/Azure/Azure-Functions/issues/1810

**Comment by bhagyshricompany** [comment]
Thanks for informing will check and update.

**Comment by bhagyshricompany** [comment]
@fabiocav  pls comment.

**Comment by fabiocav** [comment]
The WebJobs SDK is a much smaller subset of the host surface. The host brings in a significantly larger set of features, contributing to its footprint. 

We're always working on improving the host size and its performance in general. There's active work to reduce the footprint, scoping the host to align with the specific workload scenarios (e.g., avoid paying the cost for other language features), but ultimately, the host (a runtime application) and the SDK are very different products. 

If the WebJobs SDK meets the requirements, using that is a valid option to reduce the memory utilization.

Closing this issue as answered, but please let us know if you have any additional questions.

**Comment by stevendarby** [comment]
As well as high memory use the docker image size is huge too (https://github.com/Azure/azure-functions-docker/issues/236). Is there any work being done to reduce the size of the functions runtime?
