### ISSUE TITLE
Diagnostic Events API should work with a Managed Identity

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-host#9569]
Currently, the Diagnostic Events API relies on a connection string to read the diagnostic events from table storage. However, if a user has configured their app to use Managed Identity, they will not be able to get these events to help troubleshoot any issues with their function app.

/cc @soninaren @eamonoreilly  @FinVamp1 @fabiocav @mattchenderson

**Comment by Francisco-Gamino** [comment]
@fabiocav @mattchenderson -- Would it be possible to prioritize this work item? Managed identity for AzureWebJobs storage is supported today.

**Comment by fabiocav** [comment]
Flagging this issue to investigate whether we have work require in the host and geomaster, and see if we have an opportunity to track those separately.

**Comment by fabiocav** [comment]
Initial investigation is complete, need a formal design review to work through the details.

**Comment by fabiocav** [comment]
Moving this back to the backlog in favor of other high priority items.
