### ISSUE TITLE
rewrite rules in azure application gateway

### ISSUE THREAD

**Issue by KarthikSuggana** [Azure/azure-functions-host#9572]
Hi ,

When I'm accessing to client server I'm getting an Login failed:   "message":"There was an error processing your request."},"headers":{}}},"msg":"not a valid IPv4 address: 139.5..:58252"} and checked the logs status code is 500. After looking into issue deeper got to know (ip:port) in IPv4 colon is not acceptable so created the rewrite rule x-forward-for = 139.5..,58252 in app gateway. In my Ip insted of colon**(:)** given comma**(,)** then it is accessing the client server. But here my question is how to provide access to all end users. We couldn't be able to add all the whitelisted IP's in that condition. how we can give the syntax

**Comment by bhagyshricompany** [comment]
HI,
Thanks for reporting please share the fun name timestamp region etc.
