### ISSUE TITLE
Diagnostic event `name` and `description` are swapped for event id `AZFD0006`

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-functions-host#9596]
While I was testing a new diagnostic event, I noticed that `name` and `description` are swapped for event id `AZFD0006`. We should fix this.
 
<img width="1097" alt="image" src="https://github.com/Azure/azure-functions-host/assets/12720858/7ff2161a-55eb-49c7-8b25-98b02f7809ef">

**Comment by surgupta-msft** [comment]
Seems like we need to update [this](https://github.com/Azure/azure-functions-host/blob/266f0fb78575bfe3b8182c21cf20fd01a64f794b/src/WebJobs.Script.WebHost/Health/TokenExpirationService.cs#L115) line? cc @aishwaryabh
