### ISSUE TITLE
Cannot see logs in Function App > Function > Monitor > Logs

### ISSUE THREAD

**Issue by oshihirii** [Azure/azure-functions-host#9604]
Same issue was reported here in 2017:

https://github.com/Azure/azure-functions-host/issues/1222

I created an Azure Function locally by running these commands:
```bash
# create the 'project' which will then be deployed to the Function App in Azure  
func init MyFunctionAppName --worker-runtime javascript --model V4

# navigate to the project folder 
cd MyFunctionAppName /

# create the Function 
func new --template "Http Trigger" --name MyHttpTriggerFunction

# start the function and test locally  
func start

# deploy to azure
func azure functionapp publish MyFunctionAppNameinAzure
```

Those commands are from the official docs:

https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Cisolated-process%2Cnode-v4%2Cpython-v2%2Chttp-trigger%2Ccontainer-apps&pivots=programming-language-javascript

The default function code is:

```js
const { app } = require('@azure/functions');

app.http('MyHttpTriggerFunction', {
    methods: ['GET', 'POST'],
    authLevel: 'anonymous',
    handler: async (request, context) => {
        context.log(`Http function processed request for url "${request.url}"`);

        const name = request.query.get('name') || await request.text() || 'world';

        return { body: `Hello, ${name}` };
    }
});
```

I changed `authLevel` to `function` and after deployment could successfully pass the Function Key through to a curl request to check it was working correctly:
```bash
curl https://MyFunctionAppNameinAzure.azurewebsites.net/api/MyHttpTriggerFunction -H "x-functions-key: *************"
```
It returns the expected response.

However, the problem is I cannot see the logs that should be generated from this line in the function code:
```js
context.log(`Http function processed request for url "${request.url}"`);
```
I am looking for them here:

Function App > Function > Monitor > Logs

All it says on that black Logs screen is:

'Connecting to Application Insights...'

and then:

'Connected!'  

I keep making the curl request and expect to see the logged message and don't see anything.  

I don't know if it is related, but the default `host.json` file content is this:
```js
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[4.*, 5.0.0)"
  }
}
```

The default 'local.settings.json' file content is:
```js
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "node",
    "AzureWebJobsFeatureFlags": "EnableWorkerIndexing",
    "AzureWebJobsStorage": "UseDevelopmentStorage=true"
  }
}
```

I have gone to the Function App > Application Insights and it says:

'Your app is connected to Application Insights resource: MyFunctionAppName'

So the 'logging functionality' seems like it should be 'turned on'.  

In Function App > Overview:

 - the Operating System is Linux.  
 - the Subscription is Pay-As-You-Go.
 - the Status is Running.

On the Function page, there is a note at the top of the page that says:

'Your app is currently in read only mode because new Node programming model experience is in preview.'
 
which is kind of unsettling.

**Comment by oshihirii** [comment]
**Update:**

In the time it took me to write the original issue above (which was significant), it seems to have 'righted itself'.  

When I send the curl request, I can now see the message being logged out in the following location a few seconds later:

Function App > Function > Monitor > Logs

**Comment by bhagyshricompany** [comment]
Thanks for  informing please  share the funct app name time region etc.Thanks

**Comment by Peach-24** [comment]
/bot not-stale

I'm still seeing this issue.

**Comment by RohitRanjanMS** [comment]
Hi @oshihirii , Function App > `Function > Monitor > Logs` is the log streaming feature. You will only see logs that's emitted after the session is established with the Functions runtime. 
I will close this issue now as it seems it's working.

@Ivan-Nikov and @Peach-24 , if you are facing issue then please create another issues with all the details and we will look into it.
