### ISSUE TITLE
Add recovery on StartHostAsync if OperationCanceledException was thrown.

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-host#9639]
#### What problem would the feature you're requesting solve? Please describe.
The custom startup can take long time and end up with the `OperationCanceledException` [here](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs#L184). The function host does not try to recover/restart and stays in "Function host is not running" state. For "Runtime Driven Scale" scenarios the only instance returns 503 on "`/admin/host/scale/status`" [here ](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Filters/RequiresRunningHostAttribute.cs#L80) and fails to scale out/process messages.

#### Describe the solution you'd like
The idea is to add retires (~3) then fail with 503 if after 3 attempts we are unable to start the host. We have similar model for a language worker initialization.

#### Additional context
CRI number 424896199

**Comment by liliankasem** [comment]
Added this to the next sprint to discuss.

**Comment by surgupta-msft** [comment]
Had an offline discussion on this. We will be going with a different approach to handle issue at the platform level.
