### ISSUE TITLE
Function invoked twice when called from Standard Logic App workflow HTTP action

### ISSUE THREAD

**Issue by gr-lukedupuis** [Azure/azure-functions-host#9642]
#### Check for a solution in the Azure portal

I've gone through relevant documentation, like retry policy, etc. as well as used the "Diagnose and Solve Problems" tools and I'm not able to see what may be causing this issue.

The issue is sometimes, somewhat frequently, the function is invoked twice, even though (as far as I can see) the caller only calls it once.

##### Timestamps

It happens frequently. Here's one example when it happened. The timestamps are accurate. The log messages are summaries.

- 10/25/2023, 1:33:05.705 PM ET Invocation Id=ae6481d3-c647-429d-8cdb-b23246edcaea
- 10/25/2023, 1:33:05.708 PM ET console.log Run Id=08585033518054521834873289238CU00 Request 1
- 10/25/2023, 1:33:40.611 PM ET console.log Run Id=08585033518054521834873289238CU00 Request 1 response
- 10/25/2023, 1:33:44.381 PM ET Invocation  Id=2daa4d3c-5db9-4c02-a4f3-4757270a4239
- 10/25/2023, 1:33:44.383 PM ET console.log Run Id=08585033518054521834873289238CU00 Request 2
- 10/25/2023, 1:33:44.397 PM ET console.log Run Id=08585033518054521834873289238CU00 Request 2 response

##### Additional details

- Function App version: 2.0
- Region: East US

#### Repro steps

- I have not been able to reproduce the issue isolated from when and where it happens. I have tried both direct concurrent requests to the function and concurrent requests from a test workflow. However, these tests requests take less time for the function to process than the requests the live function processes, so maybe duration of the function run is a factor.
- It happens in 2 separate standard logic app workflows when an HTTP action calls the function.
- The function app doesn't have a retry policy defined.
- The issue happens even if the HTTP action in the workflow has the retry policy disabled.
- The issue happens when more than a few concurrent requests are sent, but not necessarily a huge amount, like fewer than 100.
- The operation that the function does usually takes some time, but the issue happens even on requests under a minute as in the example timestamps above.

#### Expected behavior

The workflow HTTP action calls the function 1 time and the function is called 1 time.

#### Actual behavior

The HTTP action calls the function 1 time (as far as I can see) and the function is called 2 times.

#### Known workarounds

The requests are cached in blobs by workflow run ID, so when the function receives the 2nd request, it sees a request for the given workflow was already received and it returns a 200 response. Meanwhile, the first request either already completed before the 2nd request, or the 1st request completes after the 2nd request.

#### Related information 

- Node.js
- The function is straightforward. It only handles errors, caches, logs, and calls an imported dependency function to makes an HTTP request outside of Azure. The caching and logs are only necessary because of the double-request issue. The try/catch block would catch any errors in the sendRequest function or elsewhere in the block. If an error in getErrorRes were the cause, then there would be an unhandled error in the logs.

<details>
<summary>Source</summary>

```javascript
async function Main(context, req) {
  try {
    if (typeof req.body !== 'object') {
      throw new Error('Request body must be a key/value object with the required properties. { "url": "string", "method": "string" }');
    } else if (!req.body.url) {
      throw new Error('Request body "url" is required.');
    } else if (!req.body.method) {
      throw new Error('Request body "method" is required.');
    }

    const runId = req.headers?.['x-ms-workflow-run-id'];
    const operationName = req.headers?.['x-ms-workflow-operation-name'];
    const cacheEnabled = operationName === 'Operation_name';

    if (cacheEnabled) {
      console.log(`${runId}: Request: ${JSON.stringify(req.body)}`);

      const cached = await cache(runId); // Checks if blob exists, saves if not

      console.log(`${runId}: Cached: ${cached}`);

      if (cached) {
        const res = {
          status: 200,
          headers: {
            'request-cache': 'true'
          }
        };

        console.log(`${runId}: Cached: true: Response: ${JSON.stringify(res)}`);

        context.res = res;
        return;
      }
    }

    const { status, headers, body } = await sendRequest(req.body); // Sends request to external resource

    if (cacheEnabled) {
      console.log(`${runId}: Cached: false: Response: ${JSON.stringify({
        status: 200,
        headers,
        body
      })}`);
    }

    context.res = {
      status,
      body,
      headers: Object.keys(headers)
        .reduce((o, k) => {
          o[`response-${k.toLowerCase()}`] = headers[k];
          return o;
        }, {
          'Content-Type': 'application/json'
        })
    };
  } catch(e) {
    const errorRes = getErrorRes(e, req); // Gets an error response object; doesn't have an uncaught error or it would show in logs
    console.log(`Error: ${JSON.stringify(errorRes.body)}`);
    context.res = errorRes;
  }
}
```
</details>

**Comment by bhagyshricompany** [comment]
thanks for informing  will  check and update' pls share the which link doc you followed.
Thanks

**Comment by gr-lukedupuis** [comment]
@bhagyshricompany Thank you for your response.

Here's a document about function retries, [Azure Functions error handling and retries](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=fixed-delay%2Cisolated-process&pivots=programming-language-javascript). And here's the `function.json` file where no retry is defined.

```json
{
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": [
        "post"
      ]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}
```

`hosts.json` ([host.json reference for Azure Functions 2.x and later](https://learn.microsoft.com/en-us/azure/azure-functions/functions-host-json)) has a `functionTimeout` property. Without a timeout defined in `hosts.json`, requests to the function time out after 5 minutes. When the issue happens however, the requests are taking less than 5 minutes, so timeout doesn't seem to be the cause. Here's the `hosts.json` file.

```json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.*, 4.0.0)"
  }
}
```

The HTTP action retry policy on the function app is currently enabled. However, the issue happens even if the retry policy is disabled. The issue happens when the first request is successful. If a request is successful, then the HTTP action shouldn't retry. The second request frequently happens even before the first request returns a response, so the HTTP action definitely shouldn't retry, especially because nothing is timing out. Here's documentation on [Logic App Workflow Retry policy limits](https://learn.microsoft.com/en-us/azure/logic-apps/logic-apps-limits-and-config?tabs=consumption%2Cazure-portal#retry-policy-limits).

![image](https://github.com/Azure/azure-functions-host/assets/123748093/abdaef85-28a5-4561-be0c-7b6ad9a68f69)

**Comment by gr-lukedupuis** [comment]
It's an odd bug I don't expect will be resolved any time soon if at all. I'll go ahead and close the issue for now. If more useful information surfaces I'll be sure to share it.
