### ISSUE TITLE
[BUG]: Conflict between Azure App Services Settings and Azure Functions (specifically 'function' auth compatibility)

### ISSUE THREAD

**Issue by ChristopherSalam** [Azure/azure-functions-host#9647]
I looked in the Azure portal in the diagnosis and check problems area and did not find much related to this issue.

- Function App version: ~4
- Function App name: bytefileuploadfunc-tech
- Region: West US 

#### Related information 

Our function is written in Typescript.

Example function.json:

{
  "bindings": [
    {
      "authLevel": "function", // changed to "anonymous"
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": ["post"],
      "route": "v1/upload/start"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ],
  "scriptFile": "../dist/uploadStart/index.js"
}

#### Expected behavior

Our repo uses Azure Pipeline Tasks and Azure Functions, and we have a healthCheck endpoint that is using anonymous authentication and 2 endpoints using 'function' authentication. We expect the task pipeline to run and deploy an azure function that's available to be accessed with http triggers and allow for 'function' based authentication.

#### Actual behavior

The function authentication has some conflict with Azure App Service Settings. After the endpoint completes release, hits to the endpoint causes one of three errors on the 'function' authenticated endpoints (the anonymous function works everytime): 

1. Endpoints that never return, just hang
2. Endpoints that return a 503 error
3. Endpoints that return a 401 error (example - log in Application Insights)
![401 Error](https://github.com/Azure/azure-functions-host/assets/8991089/2717c7ff-b32b-48f2-b670-8fd7c7fb0710)

The errors is persistent and repeatable, and we can only fix the site by re-releasing the pipeline.

We think there's some race condition between Azure App Services Settings that makes the functional authentication not work as expected. 

#### Known workarounds

1. Introducing a delay in the pipeline after the Azure App Services Settings is run. 

![Bash Delay Step](https://github.com/Azure/azure-functions-host/assets/8991089/606d5a07-4078-4d04-a0ee-f367d02ef315)

2. Turning off the Azure App Services Settings (obviously not useful)

3. Inverting the order of the Swap Slots Task step and the Azure App Services Settings (exposes us to a moment where the older settings are working on the new Slot)

5. Turning off the function authentication in our Azure Function (ok for now since that route has additional authentication, but not ideal for other planned work). 

I also filed this bug with https://github.com/Azure/Azure-Functions/issues/2416  and Azure Pipeline Tasks (https://github.com/microsoft/azure-pipelines-tasks/issues/19173)

**Comment by bhagyshricompany** [comment]
Thanks for reporting pls raise the issue on azure portal.Thanks
