### ISSUE TITLE
How to make JVM based custom handlers work with both windows and linux envs

### ISSUE THREAD

**Issue by xlight05** [Azure/azure-functions-host#9668]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
Custom Handlers (Java runtime)
#### Question
Ballerina language implementation is based on custom handlers. However, we encourage users to select Java 17 as the runtime as Ballerina requires JVM (startup command - java -jar file.jar). The generated host.json file is as follows. 

```
{
  "version": "2.0",
  "extensions": {
    "http": {
      "routePrefix": ""
    }
  },
  "customHandler": {
    "description": {
      "defaultExecutablePath": "java",
      "defaultWorkerPath": "azf_cross.jar",
      "arguments": [
        "-jar",
        "%BALLERINA_DEBUG_FLAGS%"
      ]
    },
    "enableForwardingHttpRequest": false
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.*, 4.0.0)"
  }
}

```

What I want is a host JSON file to run this on both Windows and Linux. The above file works perfectly fine in Windows not in Linux. After SSH into Linux, I noticed that Java was not available in the path. How do we solve this problem? Shouldn't the Java Linux environment path contain Java? 

@liliankasem @anthonychu @pragnagopa

**Comment by pragnagopa** [comment]
As your application payload does not include the runtime - in this case `java` - could you try setting [linuxFxVersion](https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#linuxfxversion) site config property to `java|11` ?

**Comment by xlight05** [comment]
Hi @pragnagopa thanks for the response.
Sorry, seems like I don't have access to the link you mentioned. However I tried the following command, still no luck ;(

```
az functionapp config set --name <FUNCTION_APP> \
--resource-group <RESOURCE_GROUP> \
--linux-fx-version Java|17
```
I didn't quite get what you meant by application payload. Just for clarification, for azure functions consumption apps, doesn't the function app define the runtime to be used? In ballerina cases, we recommend users to select java 17 when they create the function app.

**Comment by pragnagopa** [comment]
Apologies for incorrect link above - fixed it. 

> Just for clarification, for azure functions consumption apps, doesn't the function app define the runtime to be used?

For Custom Handlers we expect the application payload to include the runtime or provide a full path to the executable if relying on the platform to provide the runtime. On windows this seems to be working at the environment vars are set correctly.

For linux could you try setting `"defaultExecutablePath": "%JAVA_HOME%/bin/java"` and see if it works?
tagging @CooperLink FYI
