### ISSUE TITLE
Azure Function SQL Trigger Binding not firing once automatically stopped

### ISSUE THREAD

**Issue by yorek** [Azure/azure-functions-host#9682]
I’ve been using the Trigger Binding for SQL lately, and I noticed that at some point I get a “Stopped the listener”, if the trigger doesn’t detect changes for some time (1 hour for example) message

![image](https://github.com/Azure/azure-functions-sql-extension/assets/2612362/256a3880-2417-4c2c-8542-a3af04222367)

And after that, the trigger doesn’t work anymore. If I make some changes to the database, they do not fire up the trigger. I order to make everything working again, I have to go to the Azure Portal, and interact in some way with the deployed Azure function, for example use the “Live metrics” feature.

Is this a known issue or I’m doing something wrong?

**Comment by yorek** [comment]
Maybe related to this issue Azure/azure-functions-sql-extension#892?

**Comment by lucyzhang929** [comment]
Hi @yorek, could you share the following information:
Timestamp:
Function App version: 
Invocation ID: 
Region:

**Comment by Charles-Gagnon** [comment]
@fabiocav Do you know why the listeners would be stopped? If our listener is stopped then it's definitely expected you won't get any more trigger activations...but that's not something we control AFAIK.

**Comment by yorek** [comment]
> Hi @yorek, could you share the following information: Timestamp: Function App version: Invocation ID: Region:

Timestamp: 2023-11-10T19:38:53.3543291Z
Invocation ID: 11ee1096-b090-4156-8373-98e838ae9c7b
Region: Central US 
Function App version: 4

This is when the function was executed. After a while (hours? minutes? not sure...) you'll see that it stops listening to the SQL changes

**Comment by Charles-Gagnon** [comment]
Not sure if it's related, but a quick search shows that other people have had similar looking issues in the past with other triggers.

https://stackoverflow.com/questions/63446501/azure-function-trigger-listener-stops-running-abruptly

Given that the extension itself doesn't control anything about when the listener is started/stopped it seems likely this is something with the host, but we'll look into the logs and see if we can find any more information out.

**Comment by lucyzhang929** [comment]
@fabiocav Looking through the Kusto logs, there aren't any errors coming from the SQL Extension but there are logs coming from the Host related to DrainMode which is then calling StopAsync on all the listeners. This seems to be scaling related. Is this something you or your team can help take a look at?

**Comment by fabiocav** [comment]
Hey @lucyzhang929 , yes, we can help take a closer look at this. Updating here for visibility, but will continue following up on the thread started on this issue. 

Will post any updates here as new information becomes available.

**Comment by fabiocav** [comment]
Updating here as promised.

The issue was caused because this app is deployed to the Consumption SKU, which does not support activation for the SQL Trigger. 

Whenever the application idles out (which is the normal behavior in Consumption when there's no traffic), the trigger will not activate the app to process events. 

This is noted in the trigger documentation [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-azure-sql-trigger?tabs=isolated-process%2Cportal&pivots=programming-language-csharp), but @lucyzhang929 is tracking documentation enhancements to make this clearer and address conflicting verbiage. 

Closing as resolved.
