### ISSUE TITLE
Error configuring services in an external startup class. Grpc.AspNetCore.Server: Could not load file or assembly 'Microsoft.AspNetCore.Routing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. 

### ISSUE THREAD

**Issue by dush88c** [Azure/azure-functions-host#9685]
I upgraded my Azure function project to `.Net 7` and a few libraries too. After it when I deployed the app into Azure function service, it gives me error. 

`Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. Grpc.AspNetCore.Server: Could not load file or assembly 'Microsoft.AspNetCore.Routing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. `

Here is the my project file of Azure Function project 

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Messaging.EventGrid" Version="4.21.0" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.2.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="3.3.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.13.4" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.2.0" />
    <PackageReference Include="OneSignalApi" Version="2.0.2" />	
	<PackageReference Include="SendGrid" Version="9.28.1" />
	<PackageReference Include="Twilio" Version="6.15.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by dush88c** [comment]
As I heard and realised, my project is not a .Net isolated project and this is a dotnet in-proc app which is only supported with LTS versions and .Net 7 is not an LTS version. So I downgraded the .Net version 6  (LTS) and deployed it. 
I am planning to upgrade to .Net 8 which is LTS version.

**Comment by shivamgoel008** [comment]
This error often occurs when there's a mismatch between the versions of the packages referenced in your project

go to manage NuGet Packages of project -> go to updates section -> update all the packages and try to run
