### ISSUE TITLE
Traces lost after awaiting long task?

### ISSUE THREAD

**Issue by spplante** [Azure/azure-functions-host#9731]
Not sure if this is a bug related to Azure Insights or Function Apps, but I am using an Azure Function v4 in .net 6.0 and Azure Insights randomly loses traces after awaiting for an async method that takes roughly 8 minutes to complete.

When executing the function using the Test/Run button in Azure, I can see all logs correctly in the live console, however in both the Monitor page or Azure Insights the traces after the long await don't exist.

I validated that there is 0% sampling in Azure Insights going on.

It looks like after a certain amount of time Insights just gives up and goes to sleep. I have had one successfull execution where 100% of the traces were there, in this case the long operation took +- 6 min instead of 8 minutes, not sure if it has something to do with this...

#### Investigative information

Please provide the following:

- Timestamp: 12/9/2023 11:00:02 PM
- Function App version: v4
- Function name(s) (as appropriate): GovernanceAttributes_Full
- Invocation ID: 89ef4f25-f4be-4fcb-b5ac-39882757f255
- Region: East US 2

#### Repro steps

In an async method of your code: 

- Add some traces using **ILogger.LogInformation("...")**
- Await for 8 minutes using **await Task.Delay(480000);**
- Add some traces again after the await

#### Expected behavior

Insights should not lose traces and should show all traces

#### Actual behavior

Once in Azure, you will see the logs in the live console when you "Run/Test" your function manually, but both the **Monitor** section and **Insights** will often lose traces that were sent after the Task.Delay

#### Known workarounds

N/A

#### Related information 

N/A

**Comment by bhagyshricompany** [comment]
Hi @spplante  thanks for reporting will check and update.

**Comment by spplante** [comment]
@bhagyshricompany Any news on this?

**Comment by bhagyshricompany** [comment]
@aishwaryabh  pls comment .

**Comment by fabiocav** [comment]
@RohitRanjanMS tagging you here for awareness (and in case you have some thoughts)

@bhagyshricompany flagging this with `Needs: Triage Assistance` so we can build a repro to investigate what is happening here.

**Comment by RohitRanjanMS** [comment]
Hi @spplante , it seems the app no longer exists. Please create a support ticket if you are still facing this issue with some other app? We can enable diagnostics logs to investigate TelemetryClient behavior.
