### ISSUE TITLE
Is there a nuget package I can use for adding Microsoft.Azure.WebJobs.Script.WebHost to my project?

### ISSUE THREAD

**Issue by varkey98** [Azure/azure-functions-host#9754]
#### Is your question related to a specific version? If so, please specify:
No

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
I would like to do `dotnet add package Microsoft.Azure.WebJobs.Script.WebHost` to my project, but not finding it in the NuGet gallery.

**Comment by bhagyshricompany** [comment]
Thanks for   reporting  @varkey98 Microsoft.Azure.WebJobs.Script.WebHost is not available on the NuGet Gallery as a standalone package. This package is typically associated with Azure Functions projects and is often included as part of the Azure Functions runtime.

If you are working on an Azure Functions project, you generally don't need to add this package manually. Instead, Azure Functions projects typically reference the necessary Azure Functions SDK, and the runtime dependencies are managed automatically.

**Comment by varkey98** [comment]
I'm new to dotnet programming as well as Azure Functions, trying to deploy an application in Azure in process runtime on dotnet 6. So if I add a `<PackageReference Include=Microsoft.Azure.WebJobs.Script.WebHost Version=... />` in my csproj, will it be resolved automatically?

**Comment by varkey98** [comment]
I'm getting this error on compiling
```
The type or namespace name 'Script' does not exist in the namespace 'Microsoft.Azure.WebJobs' 
```

**Comment by kshyju** [comment]
@varkey98 I am curious to know why you want to consume that package. Would you mind elaborating your use case which requires this package?

**Comment by varkey98** [comment]
I was trying to implement IJobHostHttpMiddleware,  https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Middleware/IJobHostHttpMiddleware.cs.

**Comment by kshyju** [comment]
> I was trying to implement IJobHostHttpMiddleware, https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Middleware/IJobHostHttpMiddleware.cs.

But why? What is your end goal? The in-proc model does not support custom middleware. The [dotnet isolated model ](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide)does.

**Comment by varkey98** [comment]
Yes, understood. I want to print the request bodies and I think telemetry can help me do that, but when going through the source code, this interface piqued my interest

**Comment by varkey98** [comment]
Still learning dotnet, so pretty much trying out things, also wanted to do it myself and not rely on otel or any other telemetry solutions since we're trying to build our own solution

**Comment by kshyju** [comment]
As you found out yourself, the `Microsoft.Azure.WebJobs.Script.WebHost` package is not available for customers to consume.
