### ISSUE TITLE
Emit metrics for permanent app failures

### ISSUE THREAD

**Issue by liliankasem** [Azure/azure-functions-host#9770]
We are currently emitting a metric called "AppFailureCount" this metric captures the number of permanent app failures. We are incrementing this count any time a HostInitializationException is thrown in the host. This work item is to expand the scope of where we increment the `AppFailureCount` to capture more app failures. The metrics design doc outlines some scenarios of what we would consider a permanent app failure. Review those scenarios and a) ensure we are incrementing `AppFailureCount` for all the listed use cases and b) discover further permanent app failure use cases and ensure we capture the metrics for these new sceanrios.

**Comment by satvu** [comment]
Closing as related PR has been merged.
