### ISSUE TITLE
Microsoft Identity Denial of service vulnerability

### ISSUE THREAD

**Issue by czb182** [Azure/azure-functions-host#9792]
https://github.com/advisories/GHSA-8g9c-28fc-mcx2

Looks like runtime needs to be updated to Microsoft.IdentityModel 6.34+ (current is 6.32).

runtime includes several libraries
![image](https://github.com/Azure/azure-functions-host/assets/7947899/410e475e-a1a0-4b9c-a7dd-4748d7fb8f80)

specifically Microsoft.IdentityModel.JsonWebTokens and System.IdentityModel.Tokens.Jwt are flagged, but I image all need to be kept in sync.

**Comment by fabiocav** [comment]
Thank you for reporting. This being updated and actively worked on already.

For similar issues in the future, please refer to https://github.com/Azure/azure-functions-host/security/policy on how to submit security concerns. 

Thank you!

**Comment by fabiocav** [comment]
Removing security related issue.

For guidance on how to report security concerns, please see https://github.com/Azure/azure-functions-host/security/policy

Thank you
