### ISSUE TITLE
Enable integration tests in OOP branch

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#9803]
Issue tracking enablement of the following tests under the integration project:

```			
Namespace: Microsoft.Azure.WebJobs.Script.Tests.ApplicationInsights Not Run (13)			
Namespace: Microsoft.Azure.WebJobs.Script.Tests.Controllers Not Run (52)			
Namespace: Microsoft.Azure.WebJobs.Script.Tests.CosmosDB Not Run (4)				
Namespace: Microsoft.Azure.WebJobs.Script.Tests.Host Not Run (3)			
Namespace: Microsoft.Azure.WebJobs.Script.Tests.Integration Not Run (3)			
Namespace: Microsoft.Azure.WebJobs.Script.Tests.Integration.ContainerManagement Not Run (9)			
Namespace: Microsoft.Azure.WebJobs.Script.Tests.Integration.Controllers Not Run (1)			
Namespace: Microsoft.Azure.WebJobs.Script.Tests.Integration.Diagnostics Not Run (10)			
Namespace: Microsoft.Azure.WebJobs.Script.Tests.Integration.EventHubs Not Run (1)			
Namespace: Microsoft.Azure.WebJobs.Script.Tests.Integration.Host Not Run (17)			
Namespace: Microsoft.Azure.WebJobs.Script.Tests.Integration.Management Not Run (112)			
Namespace: Microsoft.Azure.WebJobs.Script.Tests.Integration.Middleware Not Run (5)			
Namespace: Microsoft.Azure.WebJobs.Script.Tests.Integration.Scale Not Run (11)			
Namespace: Microsoft.Azure.WebJobs.Script.Tests.Integration.Storage Not Run (12)				
Namespace: Microsoft.Azure.WebJobs.Script.Tests.Middleware Not Run (8)			
Namespace: Microsoft.Azure.WebJobs.Script.Tests.PreJIT Not Run (1)			
Namespace: Microsoft.Azure.WebJobs.Script.Tests.Security Not Run (3)			
```

**Comment by kshyju** [comment]
ProxyFunctionDescriptorProviderTests tests fails with below exception. We potentially need a new version of the Proxy package with the non-ambiguous call to his method.

> System.AggregateException : One or more errors occurred. (The call is ambiguous between the following methods or properties: 'System.Collections.Generic.CollectionExtensions.GetValueOrDefault<TKey, TValue>(System.Collections.Generic.IReadOnlyDictionary<TKey, TValue>, TKey, TValue)' and 'Microsoft.Azure.AppService.Proxy.Common.Expressions.ExpressionSyntaxExtensions.GetValueOrDefault<TKey, TValue>(System.Collections.Generic.IReadOnlyDictionary<TKey, TValue>, TKey, TValue)'
The call is ambiguous between the following methods or properties: 'System.Collections.Generic.CollectionExtensions.GetValueOrDefault<TKey, TValue>(System.Collections.Generic.IReadOnlyDictionary<TKey, TValue>, TKey, TValue)' and 'Microsoft.Azure.AppService.Proxy.Common.Expressions.ExpressionSyntaxExtensions.GetValueOrDefault<TKey, TValue>(System.Collections.Generic.IReadOnlyDictionary<TKey, TValue>, TKey, TValue)')
---- Microsoft.Azure.AppService.Proxy.Common.Expressions.ExpressionParsingException : The call is ambiguous between the following methods or properties: 'System.Collections.Generic.CollectionExtensions.GetValueOrDefault<TKey, TValue>(System.Collections.Generic.IReadOnlyDictionary<TKey, TValue>, TKey, TValue)' and 'Microsoft.Azure.AppService.Proxy.Common.Expressions.ExpressionSyntaxExtensions.GetValueOrDefault<TKey, TValue>(System.Collections.Generic.IReadOnlyDictionary<TKey, TValue>, TKey, TValue)'
The call is ambiguous between the following methods or properties: 'System.Collections.Generic.CollectionExtensions.GetValueOrDefault<TKey, TValue>(System.Collections.Generic.IReadOnlyDictionary<TKey, TValue>, TKey, TValue)' and 'Microsoft.Azure.AppService.Proxy.Common.Expressions.ExpressionSyntaxExtensions.GetValueOrDefault<TKey, TValue>(System.Collections.Generic.IReadOnlyDictionary<TKey, TValue>, TKey, TValue)'

@fabiocav to start a thread with the proxy folks.

**Comment by kshyju** [comment]
#### Disabled test (Will revisit later)

1. CSharpEndToEndTests.HttpTrigger_Model_Binding_V2CompatMode
2. DependencyTests.Verify_DepsJsonChanges
3. ProxyFunctionDescriptorProviderTests.ValidateProxyFunctionDescriptor
4. ProxyFunctionDescriptorProviderTests.ValidateProxyFunctionInvoker
5. ProxyFunctionProviderTests.ProxyMetadata_WhenProxyFileChanges_IsRefreshed

**Comment by fabiocav** [comment]
@kshyju is making progress on this, but currently blocked on https://github.com/Azure/azure-functions-host/issues/9852

**Comment by fabiocav** [comment]
Opened separate issues to track the blocked items. Closing this as resolved.
