### ISSUE TITLE
Create Flex image with the OOP host

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#9811]
Create the required image(s) to use the host from the OOP branch for Flex workloads.

**Comment by kshyju** [comment]
db3 and blu stamps have these deployed.

[internal link](https://msazure.visualstudio.com/One/_git/AAPT-Antares-Websites?path=/src/Hosting/Functions/poolconfigurations/waws-prod-msftintch1-503/localpoolconfig.json&version=GBuser/functions/fc-pools-release&line=218&lineEnd=219&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)
