### ISSUE TITLE
AzureWebJobsSecretStorageType changed from `files` to `blob` after slot creation.

### ISSUE THREAD

**Issue by georgeOsdDev** [Azure/azure-functions-host#9814]
#### Investigative information

AzureWebJobsSecretStorageType unexpectedly changed from `files` to `blob` after slot creation.
Portal show below warning, But it does not describe secret repository change.
If this is expected behavior, it would be nice to explain more detail in warning message or doc.

<img width="236" alt="image" src="https://github.com/Azure/azure-functions-host/assets/1381907/d89932fb-cb58-4afd-989f-a5be5e1809c1">

#### Repro steps

1. Create FunctionApp
2. Set AzureWebJobsSecretStorageType  as `files`
3. Add function secret `mySecret`
4. Create slot `stg`
5. Check AzureWebJobsSecretStorageType  of production slot 

#### Expected behavior

`AzureWebJobsSecretStorageType` keeped as `files`.

#### Actual behavior

`AzureWebJobsSecretStorageType` changed from `files` to `blob` .

#### Known workarounds

Manualy edit AzureWebJobsSecretStorageType as `files`

#### Related information 

https://github.com/MicrosoftDocs/azure-docs/issues/87990

**Comment by dsgagi** [comment]
This also applies when AzureWebJobsSecretStorageType is set to `keyvault`.
After slot creation, setting is unexpectedly changed from `keyvault` to `blob`.

**Comment by liliankasem** [comment]
@bhagyshricompany can you work on a repro for this please?

**Comment by bhagyshricompany** [comment]
can you check it again it seems  same as files.
<img width="727" alt="image" src="https://github.com/Azure/azure-functions-host/assets/116645353/b62d0e37-6017-42dd-944b-2cd4eaca7eab">
