### ISSUE TITLE
How to view the console output from Azure functions?

### ISSUE THREAD

**Issue by varkey98** [Azure/azure-functions-host#9828]
#### Is your question related to a specific version? If so, please specify:
In Process runtime

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question

I have an azure function (in process runtime) and I'd like to print some logs using Console.WriteLine(). I can see these logs when run locally, but how to see them in the azure portal?

**Comment by nikvarma** [comment]
you can view the logs multiple ways. follow below simple steps.

- Navigate to your function App on Azure portal
- Click on your function
- on left side - Click on Monitor tab.

you'll see the request came to your functions.

**Comment by bhagyshricompany** [comment]
Thanks for informing the log you can enable and see in the application insight.

**Comment by varkey98** [comment]
I found out that for the logs to be shown in the azure platform, the DI logger should be used and Console.WriteLine() ones are skipped.
