### ISSUE TITLE
Support the ability to disable the proxies feature

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#9829]
We need the ability to permanently disable the feature based on environment (SKU) configuration.

Proxies is a deprecated feature, and for new SKUs, this capability should not be enabled as it won't be properly supported by the platform.

**Comment by pragnagopa** [comment]
This is likely done. @fabiocav any pending work? breaking; P0

**Comment by fabiocav** [comment]
This was done in https://github.com/Azure/azure-functions-host/pull/10104
