### ISSUE TITLE
Provide route params to worker when using http proxy

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-host#9840]
We'd like the host to pass the worker route param info when using http proxies. We have the url and could potentially parse it ourselves, but the user registers routes using ASP.NET route syntax since the host handles all the actual routing logic. It would be pretty complicated to parse ASP.NET route syntax (e.g. `example/{name}`) since it's different than typical Node.js route syntax (e.g. `example/:name`).

Theoretically this should be easy for the host to do for us since all the route info is in the url, not the request body itself. The host could either send the route param over rpc (we still get an rpc request per invocation) or tacked on to the request sent through the proxy as a header or something. Either way would work for us.

[Discussed offline here](https://teams.microsoft.com/l/message/19:aca957d82eba48f8a6dadf5ba1117d7d@thread.tacv2/1706565951224?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=201c2bb2-812d-4986-ac92-9bfad0d6cc59&parentMessageId=1706565951224&teamName=Azure%20Functions%20Team&channelName=Host&createdTime=1706565951224) (Internal-only thread)

**Comment by fabiocav** [comment]
Had a chat with @kshyju and although it looks like we already provide the required data, there are enhancements that would make this simpler to consume.

Deprioritizing this since it's no longer a blocker, but we'll leave this open to track those enhancements.
