### ISSUE TITLE
where to track dotnet 8 support for in process?

### ISSUE THREAD

**Issue by drdamour** [Azure/azure-functions-host#9845]
#### Is your question related to a specific version? If so, please specify:
runtime 4

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
c#

#### Question
i've come across quite a few stories for tracking dotnet 8 isolated process support, but havent' seen one for in process.  https://techcommunity.microsoft.com/t5/apps-on-azure-blog/net-on-azure-functions-august-2023-roadmap-update/ba-p/3910098 said

> However, there will not be an in-process equivalent at the same time. That will come in a subsequent release in early 2024, and we will be doing what we can to make it available as soon as possible. So, if you are looking to use .NET 8 right when it comes out, you will have an option with the isolated worker model. But if you wish to continue using the in-process model, there will be a slight delay.

wanting to understand what this slight delay is actually going to be and where to track progress like i could for isolated process with https://github.com/Azure/azure-functions-dotnet-worker/issues/1644

**Comment by tombiddulph** [comment]
It'd be good to get a timeline on this, .NET 6 is EOL in 9 months (not that I'm counting).

**Comment by bhagyshricompany** [comment]
Thanks for reporting will check and update you.

**Comment by bhagyshricompany** [comment]
@fabiocav  pls comment.

**Comment by marcin0klusek** [comment]
Any news on that? @bhagyshricompany @fabiocav

**Comment by tombiddulph** [comment]
As it stands, there are 260 days until .NET in process functions go out of support..any updates @fabiocav?

**Comment by tombiddulph** [comment]
Looks like some .NET 8 work is happening on this branch https://github.com/Azure/azure-functions-host/tree/feature/oop-host

**Comment by bjornharrtell** [comment]
Unfortunately I think "oop" means out of process i.e isolated worker mode, so that branch is perhaps not relevant.

**Comment by MarienMonnier** [comment]
It can be tracked in #9951

**Comment by drdamour** [comment]
excellent glad to finally get coms / movement on this
