### ISSUE TITLE
AZFD0001: AzureWebJobsStorage app setting is not present.

### ISSUE THREAD

**Issue by SamBonavika** [Azure/azure-functions-host#9855]
This is an exact duplicate of #9349, with the exact configuration and exact symptoms. That bug was closed by @soninaren on 26-Oct-2023 but the issue is still happening.

Following is the comment I posted on that (closed) bug a few weeks:

--------------------------------------------------------------------------------

I am still seeing "warning" messages displayed on the Overview tab of my function apps.

All of our Function Apps use the "App Service Plan" model.

Our Production environment is in both EastUS and WestUS3, running on EP3 Service Plan, and the "Runtime version" is 4.27.5.21549.

Our QA environment is in WestUS3, running on an S1 Service Plan, and the "Runtime version" is 4.28.3.21820.

The warning in Production is: Storage is not configured properly, Function scaling will be limited. Click to learn more.
The warning in QA is: "AzureWebJobsStorage" app setting is not present.

In both of these environments, we are using the same constructs listed by @Francisco-Gamino in the original report, and as recommended by the [Guidance](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=blob&pivots=programming-language-csharp#connecting-to-host-storage-with-an-identity) article as well as the [Best Practices](https://msrc.microsoft.com/blog/2023/04/best-practices-regarding-azure-storage-keys-azure-functions-and-azure-role-based-access/) document.

Please advise.

**Comment by SamBonavika** [comment]
We sure could use some eyeballs on this issue ...

**Comment by JacobIhle** [comment]
This message has recently started showing on our function apps as well. 
West Europe
Both B1 and P1V2
Runtime version: 4.34.2.2

**Comment by SamBonavika** [comment]
There's been a recent change to the message displayed in our Production environment (USEast):

`Your app is not configured for dynamic scaling. Scaling could be limited. Click to learn more.`

Unfortunately, the link goes to a page where neither the words `dynamic` nor `scaling` can be found.

Two steps up ... three back?

**Comment by soninaren** [comment]
> There's been a recent change to the message displayed in our Production environment (USEast):
> 
> `Your app is not configured for dynamic scaling. Scaling could be limited. Click to learn more.`
> 
> Unfortunately, the link goes to a page where neither the words `dynamic` nor `scaling` can be found.
> 
> Two steps up ... three back?

This is a separate unrelated issue. Please open a new issue for this.

**Comment by soninaren** [comment]
A config fix was pushed to fix this. This should now show up anymore.
