### ISSUE TITLE
Azure function can't read a static file occasionally

### ISSUE THREAD

**Issue by catwang01** [Azure/azure-functions-host#9861]
I'm using a timer triggered azure function in .NET. 

```
Azure function info:
runtime version: 4.29.1.21919
file system: windows

.NET version: .NET6.0
```

I have a static json file which is published to the azure function runtime environment. It is placed in the root of the project and I use the following code to get its path:

```
Path.Combine(context.ExecutionContext.FunctionAppDirectory, 'myconfig.json')
```

The weird thing is that the azure function occasionally throws `FileNotFound` error on this file. Sometimes the azure function can read the file and sometimes it can't, without any code or azure function configuration change. 

 Does anyone have any idea about why this happens?

**Comment by well0549** [comment]
Have a look here, maybe it will help you...

https://github.com/Azure/azure-functions-durable-extension/issues/2823

**Comment by bhagyshricompany** [comment]
Hi @catwang01  To answer your question on how to read any file you can use the below. I am using the below code to get the file path and it is working as expected and didn't observe any issue. Environment.GetEnvironmentVariable("HOME") + @"\site\wwwroot{director(if any)\youfilename}
In case you are still facing the issue then please let me know.Thanks
