### ISSUE TITLE
Hyphen in environment variable

### ISSUE THREAD

**Issue by keidyz** [Azure/azure-functions-host#9877]
Let's say you have a function named `foo-bar` and want to mute the default azure information logs but not that function's information logs, you can do this in the host.json
```
{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "Function": "Error",
      "Function.foo-bar": "Information"
    }
  }
}
```

Instead of modifying host.json, you can also use the following in the local.settings.json and it would work
```
'AzureFunctionsJobHost__logging__logLevel__Function': 'Error'
'AzureFunctionsJobHost__logging__logLevel__Function.foo-bar': 'Information'
```

But dots and hyphens are not allowed in app settings. How do you get around this?

**Comment by surgupta-msft** [comment]
This documentation talks about Host.json path and equivalent Appsetting - https://learn.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2#overriding-monitoring-configuration-at-runtime

Also note that this approach will not work on Linux in an Elastic Premium plan or a Dedicated (App Service) plan as mentioned in the documentation.

> Overriding the host.json through changing app settings will restart your function app. App settings that contain a period aren't supported when running on Linux in an Elastic Premium plan or a Dedicated (App Service) plan. In these hosting environments, you should continue to use the host.json file.
