### ISSUE TITLE
Reenable proxy tests

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-host#9878]
Reenable the following tests for proxies:

 1. ProxyFunctionDescriptorProviderTests.ValidateProxyFunctionDescriptor
 2. ProxyFunctionDescriptorProviderTests.ValidateProxyFunctionInvoker
 3. ProxyFunctionProviderTests.ProxyMetadata_WhenProxyFileChanges_IsRefreshed

**Comment by fabiocav** [comment]
This is currently blocked on an updated proxies package.

**Comment by kshyju** [comment]
These tests are now enabled.
