### ISSUE TITLE
Service bus trigger function stops but does not restart

### ISSUE THREAD

**Issue by ticosido** [Azure/azure-functions-host#9881]
We have a V4 function that is triggered via a service bus message.  It's fairly common for us to see `Stopping the listener 'Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener'` messages in the log.  These are usually followed by `Found the following functions:` messages within five minutes or so, and the function continues processing again.

On a number of occasions since 2024-02-15 02:20, the function has stopped with the "ServiceBusListener" queue, but it has not restarted.  This causes the service bus messages to back up.  Prior to this, the function was processing messages as normal, and stopping and restarting normally.

I can wake the function up again by going into its overview page in the Azure portal.  It will then start processing messages as normal.  I don't even have to click on the refresh button or restart the function.

I have tried turning on Application Insights and using the `SCALE_CONTROLLER_LOGGING_ENABLED` appsetting with a value of `AppInsights:Verbose`, but nothing was logged.

There were also a few host name clashes due to the length of the function names exceeding 32 characters, so I also tried setting the `AzureFunctionsWebHost:hostId` appsetting, but this did not affect things.

We have tried syncing the triggers via the API, but this has not resolved the problem.

#### Investigative information

- Timestamp: 15 Feb 2024 02:21:26.604, 15 Feb 2024 10:53:56.996, 15 Feb 2024 12:19:15.633, 15 Feb 2024 13:10:36.248, 15 Feb 2024 16:48:09.469
- Function App version: V4
- Function name(s) (as appropriate): Don't want to share in public
- Invocation ID: 5ca7347d-82a5-42b1-9b14-515c27e5660d
- Region: UK South

#### Repro steps

This is an intermittent problem, so it's difficult to reproduce.  We have processes that run and add a service bus message to a queue that this function should process.  It may work for an hour or so, then stop working.  Could it possibly be due to the amount of load on the various functions we have running?

#### Expected behavior

The function restarts without user intervention.

#### Actual behavior

The function stops and doesn't restart.

#### Known workarounds

Go into the overview page in the portal.  This will wake the function up and it will continue processing messages as normal.

#### Related information 

N/A

**Comment by JohanGovers** [comment]
We have also experienced this and our only known workaround is to restart the function/wake it up from the Azure portal.

**Comment by liliankasem** [comment]
Hi folks, investigating issues in a production app requires a support ticket, please open one via the Azure portal - thanks!
