### ISSUE TITLE
System managed Identity for "AzureWebJobsStorage__accountName" not working as expected. Throwing permission error

### ISSUE THREAD

**Issue by vikramdadwal** [Azure/azure-functions-host#9893]
Getting the following error when trying to use Managed Identity for AzureWebJobsStorage:

![image](https://github.com/Azure/azure-functions-host/assets/10174566/64045a78-4ab3-4a14-bd9e-54c60e76eab1)

I am following this Microsoft blog: https://techcommunity.microsoft.com/t5/apps-on-azure-blog/use-managed-identity-instead-of-azurewebjobsstorage-to-connect-a/ba-p/3657606

System MI is given the following permission on the storage account:

![image](https://github.com/Azure/azure-functions-host/assets/10174566/28c0652b-9627-4d79-b4d2-96a9b64b919c)

Following is the App Settings in Azure:

![image](https://github.com/Azure/azure-functions-host/assets/10174566/229bead2-4ea5-4b3c-8557-e3bdd9d00a17)

**Comment by tarak9999999** [comment]
I am also facing the same issue, do you use blob triggers in your repo?

**Comment by bhagyshricompany** [comment]
Thanks for reporting pls provide repro steps.Thanks

**Comment by vikramdadwal** [comment]
@bhagyshricompany : Please consider the above steps as repro steps only.

**Comment by bhagyshricompany** [comment]
Hi @vikramdadwal   it will not work if the storage account is in a sovereign cloud or has custom DNS..
pls confirm this.

**Comment by vikramdadwal** [comment]
No the storage account is not in sovereign cloud nor its DNS.  

Anyways we have resolved the issue by deploying a fresh azure function on azure and creating the azure function with latest nugetss. 

Looks like for old already deployed azure functions this does not work at all.

**Comment by vikramdadwal** [comment]
Also just a general feedback on azure functions, this is not the first time a feature is release for azure function and its not backwards compatibility,  that too for just an year nack azure function.

**Comment by bhagyshricompany** [comment]
@fabiocav  pls comment and validate .Thanks

**Comment by liliankasem** [comment]
Thank you for the feedback, we will keep this in mind as we roll out new features. In future, for issues like this please open a support ticket as it would make it easier for us to investigate your specific app. Thanks!
