### ISSUE TITLE
How to set up auto scale out in APP SERVICE PLAN based on FUNCTIONS_WORKER_PROCESS_COUNT

### ISSUE THREAD

**Issue by kujaska** [Azure/azure-functions-host#9899]
#### Is your question related to a specific version? If so, please specify:
Durable Functions Python v.2

#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
Python 3.10

#### Question
How to set up auto scale out in APP SERVICE PLAN based on FUNCTIONS_WORKER_PROCESS_COUNT?

We have set FUNCTIONS_WORKER_PROCESS_COUNT = 10 (max) and need to create a new instance (scale out) each time actual worker process count on an instance exceeds 9
how to do it?

**Comment by bhagyshricompany** [comment]
Thanks for reporting check and update you.

**Comment by bhagyshricompany** [comment]
please   ref this. https://learn.microsoft.com/en-us/azure/app-service/manage-automatic-scaling?tabs=azure-portal

**Comment by bhagyshricompany** [comment]
no  update.hence closing here.Thanks
