### ISSUE TITLE
JobHost stopping randomly while running Kafkatrigger in function app

### ISSUE THREAD

**Issue by MinhTranVolvo** [Azure/azure-functions-host#9900]
Hi team,
We are developing a function app which use KafkaTrigger from this https://learn.microsoft.com/sv-se/azure/azure-functions/functions-bindings-kafka-trigger?tabs=isolated-process%2Cconfluent&pivots=programming-language-csharp to catch all the message and store in our database. We host it it Azure Function App and it works fine for about 30 min and then the Jobhost just stopping without error.

We are using the v4 of this function app and the language is C#

Our app infos are
![Capture](https://github.com/Azure/azure-functions-host/assets/148233723/44df5119-5206-4648-872d-915ce3c84244)
Region is West Europe
Please provide us what is going on in our app!
BR,
Minh Tran

**Comment by bhagyshricompany** [comment]
Thanks for reporting please provide the app name,timestamp region,func name.Thanks

**Comment by MinhTranVolvo** [comment]
Hi,
I did resolve this issue. Problem is that this Kafka trigger will not work with the consumption plan. We did upgrade this to the premium plan so that the jobhost will never be idled. We wonder if we use the isolated version, will this be fixed?

I did provide our function app information above
![image](https://github.com/Azure/azure-functions-host/assets/148233723/ad934093-c6a4-4949-a37b-2f42c678583e)

Can you check if and provide us why it did not work with consumption plan?
BR,
Minh Tran

**Comment by bhagyshricompany** [comment]
its not supported for now if in future have anything will update but for now  have premium plan.
