### ISSUE TITLE
dotnet-isloated and aspnet integration

### ISSUE THREAD

**Issue by davidpetric** [Azure/azure-functions-host#9907]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question
Hi, 

Opened this issue in the Azure function dotnet worker repo but it seems it gets ignored for some reason.

I am trying to override the JSON Serializer when using the AspNet Core integration, and found a way but I am afraid I am doing something that will break in the future because it is not documented anywhere or maybe is not the intended behavior.

Please read the issue from the Azure function dotnet worker repo:

https://github.com/Azure/azure-functions-dotnet-worker/issues/2131

**Comment by liliankasem** [comment]
Looks like @fabiocav is looking into this in the worker repo; closing as it's a worker issue not a host issue.
