### ISSUE TITLE
Azure Function (HttpTrigger) returns response code 0 instead of 204 intermittently

### ISSUE THREAD

**Issue by boylec** [Azure/azure-functions-host#9910]
Hey guys, this issue was closed awhile back but it shouldn't be. Forcing people to put a retry on a function just because it sometimes returns a 0 response code (when that is not by design) is not a solution.

We get a 0 response code probably 1 in 20 times. when the function succeeded.

![image](https://user-images.githubusercontent.com/8148174/310603123-d2704d9f-4c14-42bb-9b06-ebd4e0bc8466.png)

Note, our API endpoint is not being called by Azure Data Factory, its being called by an external party so we do not have control over their retry policies.

_Originally posted by @ankitkumarr in https://github.com/Azure/azure-functions-host/issues/5813#issuecomment-628221016_

**Comment by liliankasem** [comment]
Can you share more info about the kind of app you're using? v3 or v4? Which stack and language version? Please also provide a code repro we can use to investigate
