### ISSUE TITLE
.NET 9 Preview 1 extension installed on Windows Function App, how to enable?

### ISSUE THREAD

**Issue by davepcallan** [Azure/azure-functions-host#9915]
**I've installed the .NET 9 runtime extension**, how do I enable it?
I don't see it present in the version selection dropdown, I've restarted after installing the extension.

Does anyone know? Thanks in advance

I've also tried something like :

_az functionapp config set -g GROUPNAME -n APPNAME --net-framework-version v9.0_

without success.

Does this extension work?

![image](https://github.com/Azure/azure-functions-host/assets/106764096/e6707c69-766c-4211-8ecf-23a37aeec632)

**Comment by bhagyshricompany** [comment]
Hi @davepcallan  Thanks for reporting its not working.

**Comment by kshyju** [comment]
@davepcallan As of now, Azure Functions do not support .NET 9 preview versions, but support is expected in the future. However, there is currently no ETA available.
