### ISSUE TITLE
question regarding availability of newly cut releases in Azure

### ISSUE THREAD

**Issue by jkdmyrs** [Azure/azure-functions-host#9916]
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#

#### Question

I'm generally curious on how soon after a release is cut on this repo the version is available for use in Azure for C# Consumption Function Apps. 

We are experiencing some exceptions that appear to be fixed in version `4.31.0` of the host, but our function apps are still on `4.30.0.x`.

**Comment by liliankasem** [comment]
@VpOfEngineering Are you able to share any info around release turn around?

**Comment by VpOfEngineering** [comment]
Hello! We generally try to release updates fully within 4-5 weeks of cutting a release on this repo. Of course, issues can arise and that will extend the timeline. 

I believe 4.31 is fully released.

**Comment by jkdmyrs** [comment]
> ...4-5 weeks...

this is what I was looking for! Thanks @VpOfEngineering.
