### ISSUE TITLE
Possible missing word in wiki

### ISSUE THREAD

**Issue by kmosti** [Azure/azure-functions-host#9939]
#### Check for a solution in the Azure portal
N/A

#### Investigative information
N/A

#### Repro steps
N/A

#### Expected behavior

https://github.com/Azure/azure-functions-host/wiki/function.json

There seems to be an important missing word here:

> When marked as disabled, a function will not run. A timer function will not fire, a queue function **will trigger** on new queue messages, etc. When scriptFile is specified a function uses that file as the function entry point

#### Actual behavior
N/A

#### Known workarounds
N/A

#### Related information 
N/A

**Comment by mathewc** [comment]
Thanks for pointing this out. Fixed. Note that our official doc https://learn.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings is more up to date.
