### ISSUE TITLE
Exception in TelemetryClient while trying to authenticate to application insights and write events

### ISSUE THREAD

**Issue by MarWiJTL** [Azure/azure-functions-host#9940]
Hello, 

I am trying to use the **TelemetryClient** in a **.NET C#** solution and write **logs/events** through a **Azure function** into a **application insight** with **Azure AD**. Both systems are running in the same ressource group. 

After I tested the function local it does not worked and throws me an error, the error leads to a problem with the authentification.

**Expected behavior**
Authentication should work to application insights using Azure AD

**Actual behavior**
Exception is thrown:

> System.Private.CoreLib: Exception while executing function: TestFunction. Microsoft.ApplicationInsights: The provided tokenCredential must inherit Azure.Core.TokenCredential (Parameter 'tokenCredential').

Here is a snippet of the code used to authentificate:

```
var config = new TelemetryConfiguration
{
   ConnectionString = "InstrumentationKey=00000000-0000-0000-0000-000000000000;IngestionEndpoint=https://xxxxx.applicationinsights.azure.com/"
};

var credential = new DefaultAzureCredential();    
config.SetAzureTokenCredential(credential);
```

Another snipped of the code i use later to write my events (works fine):

```
//We create a new event, that can be sent to Azure 
var invalidRequestTelemetryEvent = new EventTelemetry
{
   Name = "DemoTelemetryEvent",
   Properties =
   {
      ["DemoNumber"] = item.Number,
      ["DemoCode"] = item.Code
   }
};


 //We sent the event to the application inside and add it to the table 'customEvents'
 this._telemetryClient.TrackEvent(invalidRequestTelemetryEvent);
```

**Related information:**

Programming language C#

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.10.4" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.19.1" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.17.1" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.22.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.2.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

This ticket is very similar to the following:
https://github.com/Azure/azure-functions-host/issues/8861

The ticket was marked as resolved, even if there is not an solution. The msftbot closed the ticket automatically.
If someone here has suggestions, how to solve the error, I would love to get hints.

I also checked Microsoft documentation and did everything as desscribed bellow:
https://learn.microsoft.com/en-us/azure/azure-monitor/app/azure-ad-authentication?tabs=net

**Comment by RohitRanjanMS** [comment]
Hi @MarWiJTL , this might not be related to Functions. Can you try this with a console app on your local machine and see if it works.

**Comment by MarWiJTL** [comment]
> Hi @MarWiJTL , this might not be related to Functions. Can you try this with a console app on your local machine and see if it works.

Hi @RohitRanjanMS, thank you for the reply. In my understanding it should be related to the Function authentification logic. 

I used the fuction local before, without the SetAzureTokenCredential method and it worked.
My local system is using Visual Studio (VS) 2022. VS has the integrated Azure Service Authentication (Tools>Options>Azure Service Authentication). 

![image](https://github.com/Azure/azure-functions-host/assets/106547918/2138516a-8c09-4fec-b263-0359629d41e5)

I can confirm that it works **local** to write e.g. events into the table customeEvents of the Azure Application Insights.
![image](https://github.com/Azure/azure-functions-host/assets/106547918/026d9c93-c05c-402d-85f0-acf0c2ebb352)


As soon i am working with the method SetAzureTokenCredential() I am getting always the error described in my post.
It looks for me like a problem in the implementation of the TelemetryClient.

> System.Private.CoreLib: Exception while executing function: TestFunction. Microsoft.ApplicationInsights: The provided tokenCredential must inherit Azure.Core.TokenCredential (Parameter 'tokenCredential').

**Comment by RohitRanjanMS** [comment]
Please follow the doc [here ](https://learn.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2#:~:text=Require%20Microsoft%20Entra%20authentication)to enable Entra Authentication.
