### ISSUE TITLE
Function triggers configuration references don't work with function app's configuration system in isolated mode

### ISSUE THREAD

**Issue by andriysavin** [Azure/azure-functions-host#9943]
#### Is your question related to a specific version? If so, please specify:
V4
#### What language does your question apply to? (e.g. C#, JavaScript, Java, All) 
C#
#### Question
First trying isolated worker mode, I was surprised that connection string name specified in a trigger attribute (e.g. `[QueueTrigger("domain-events", Connection = "StorageConnection")]`)  couldn't be found in the app's configuration system (appsettings.json in particular). I understand technical differences between loading general app configuration used within the app, and loading triggers configuration, used _by the hosting process_. However, I found out that host process still (partially?) plugs app's configuration in, but includes only `FunctionsHostingConfig`  section of that config. So, if I have the following in my appsettings.json:

```Javascript
// This works
"FunctionsHostingConfig": {
  "ConnectionStrings": {
    "StorageConnection": "UseDevelopmentStorage=true"
  }
},
// This does NOT work
"ConnectionStrings": {
  "StorageConnection": "UseDevelopmentStorage=true"
}
```
... the first connection string is loaded by the trigger.

So actually, not supporting app configuration looks to be an artificial limitation.
 
Questions:
1. Why is that so?
2. Would be using `FunctionsHostingConfig` section (as shown above) a reliable workaround for my goal?

**Comment by jviau** [comment]
>Questions:
> 1. Why is that so?
> 2. Would be using FunctionsHostingConfig section (as shown above) a reliable workaround for my goal?

1: config in functions has a lot of nuances to it as there are many independent pieces that need config applied to it. So, the "why" boils down to: we had to differentiate config that applies to the piece that manages your worker process vs the more generic functions runtime itself. Clarifying and improving on this experience is something we would like to tackle eventually, but no concrete plans at the moment.

2: Yes it appears that should work. Alternatively, you can look into using [host.json](https://learn.microsoft.com/en-us/azure/azure-functions/functions-host-json)

**Comment by andriysavin** [comment]
@jviau thank you!
