### ISSUE TITLE
Simplify Node Http Response Logic

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-functions-host#997]
Currently a http response exists in two forms:
 1. `context.res = bodyValue; // res is interpreted as 200 with body bodyValue`
 2. `context.res = {  body: bodyValue, headers: ..., status: ... } // res is fully specified object`

Removing option 1 is something we ought to consider, as it has some negatives:
 - We are forced to guess whether the returned object is a response based on existence of 'body' property, which in a couple cases is incorrect:
   - `bodyValue` has a `body` property (workaround is nested body inside body)
   - a response object is returned with only `headers` and `status`
 - The 'magic' code of 1 doesn't save lines of code
   - `context.res = bodyValue; context.done();` vs `context.res.send(bodyValue);`
 - We would decrease the matrix of things we need to test (currently, different behavior in content type handling between 1 and 2)
 - Simplified documentation and examples with a single recommended way of interacting with http in node

#978 #814

**Comment by johnnliu** [comment]
has this change gone in?  context.res isn't working suddenly

**Comment by fabiocav** [comment]
@johnnliu for full control of the response (send raw payload, manage content type, etc), we've added a flag you can set.
Details are available here: https://github.com/Azure/azure-webjobs-sdk-script/issues/965#issuecomment-262618266

**Comment by giuleon** [comment]
@fabiocav I tried this snippet to validate the SharePoint List web hook:
                    context.res = {
                                status: 200,
                                body: req.query.validationtoken, 
                                headers: {
                                    'Content-Type': 'text/plain'
                                },
                                isRaw: true
                            }
In req.query.validationtoken there is the sharepoint token for the validation that the function must to send back to SharePoint like a response in text plain, but I receive ever the message "Failed to validate the notification URL" in fact with postman if I call my function there is no response and the content type is not available
<img width="728" alt="noresponse" src="https://cloud.githubusercontent.com/assets/3914090/20806125/ed554c90-b7f9-11e6-9f27-f0370e002f0d.PNG">
<img width="275" alt="noresponse2" src="https://cloud.githubusercontent.com/assets/3914090/20806152/0995ccc2-b7fa-11e6-8df8-931276006dc5.PNG">

**Comment by giuleon** [comment]
No news about this issue ?

**Comment by mathewc** [comment]
Can you share the rest of your code? I just tried myself and this works fine - I get the code back with the correct content type:

```javascript
module.exports = function (context, req) {
    context.res = {
        status: 200,
        body: req.query.validationtoken,
        headers: {
            'Content-Type': 'text/plain'
        },
        isRaw: true
    };
    context.done();
};
```

**Comment by giuleon** [comment]
Only for testing I created this function:

`module.exports = function (context, req) {
    context.log('Node.js HTTP trigger function processed a request. RequestUri=%s', req.originalUrl);

    if (req) {
        if (req.query && req.query.validationtoken) {
            // if validationtoken is specified in query
            // immediately return token as text/plain
            context.log(req.query);
            context.log(req.query.validationtoken);

            context.res = {
                        status: 200,
                        body: req.query.validationtoken,
                        headers: {
                            'Content-Type': 'text/plain'
                        },
                        isRaw: true
                    };
        }
    }
    context.done();
};`

I'm using postman to send a post to my azure function with in query string validationtoken=123456778 as I expect from SharePoint but doesn't work for me:
<img width="784" alt="noheaders" src="https://cloud.githubusercontent.com/assets/3914090/21058059/83ebd000-be3c-11e6-9528-f135def9f919.PNG">
<img width="443" alt="noplaintext" src="https://cloud.githubusercontent.com/assets/3914090/21058058/83eb491e-be3c-11e6-94f2-f2624998a3b3.PNG">

**Comment by mathewc** [comment]
As I mentioned above, I think the issue is your function.json and how your response is bound. Here's what mine looks like. Note that my output is `res` not `$return`. What does yours look like?

```javascript
{
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    }
  ]
}
```

**Comment by giuleon** [comment]
Thank you @mathewc the bindings was wrong "$return" ;-)

**Comment by stefan-akelius** [comment]
Maybe slightly OT but is there a specific reason you didn't just pass in the standard `IncomingMessage` and `ServerResponse` objects from node but rolled your own req and res types?

**Comment by mamaso** [comment]
@stefan-akelius At present all function triggers are routed through a C# process. We use [edgejs](https://github.com/tjanczuk/edge) for interop between node and C#.  The requests are served in C# so unfortunately we don't have access to a node generated `IncomingMessage` or `ServerResponse` (I'd love to support those types natively as well).

**Comment by yvele** [comment]
@stefan-akelius You might have a look at [azure-function-express](https://github.com/yvele/azure-function-express) (we needs contributors)
