### ISSUE TITLE
Blob trigger function delays and over crowded

### ISSUE THREAD

**Issue by GonzaloNumetri** [Azure/azure-functions-host#9973]
I am working with C# and .NET8. Azure Function Version 4
I have a Blob Trigger Azure Function running without issues in Azure cloud. The function is updated using GitHub Actions from my repository. When I want to add new features, I test them locally before deployment.
The issue is that now, when I run the function locally, it starts triggering all the blob changes that have occurred since it was run locally. This usually takes a lot of time. When it finally finishes triggering, I run the new changes and it takes them hours to run. Previously, it was just seconds. How can I reduce that delay in the trigger?

**Comment by bhagyshricompany** [comment]
Thanks for reporting pls share the all repro steps.pls refer this https://learn.microsoft.com/en-us/azure/azure-functions/functions-event-grid-blob-trigger?tabs=isolated-process%2Cnodejs-v4&pivots=programming-language-csharp
